### ISSUE TITLE
Add associated roles only displays 11 roles

### ISSUE THREAD

**Issue by stmi11** [keycloak/keycloak#15246] opened 2022-11-01 10:16 UTC
### Area

admin/ui

### Describe the bug

Only the first 11 realm roles are visible when adding associated roles to an existing realm role in the new Admin console:
![image](https://user-images.githubusercontent.com/10886480/199207964-a70604cd-f6a0-4162-8c5f-9f3ba80fb24c.png)

### Version

19.0.3

### Expected behavior

The "Add associated roles" modal window must be able to display all available realm roles, even when there are more than 11.

### Actual behavior

Only the first 11 realm roles are fetched in the "Add associated roles" modal window in the Realm roles page in the new Admin console.

### How to Reproduce?

1. Log in to the Admin console
2. Go to the "Realm roles" page.
3. Make sure you have at least 12 realm roles, otherwise create as many realm roles as needed. Let's assume we have exactly 12.
4. Click on a realm role.
5. Click on the "Action" button and select "Add associated roles".
6. The modal window that just popped up displays the first 10 realm roles (sorted alphabetically). Click on the right arrow to go to the next page.
7. The next page only contains 1 role. It should contain 2 (since we assume a total of 12 realm roles).
8. Click on the arrow next to "1-10" and select "20 per page". You will now see the first 11 realm roles, when there should be 12.

### Anything else?

* The issue is caused by an incorrect API call towards the admin API. For the "Add associated roles" modal window the Admin console will always make the HTTP request `GET https://example.com/auth/admin/realms/test-realm/roles?first=0&id=253b5e8a-03b9-4fb3-bf22-0a279f78a061&max=11` with the `max` query parameter always set to 11, regardless of how many realm roles actually exist and regardless of which page you are on or how many roles you have set to display per page.
* The issue does not appear on the "Realm roles" page itself, there the API request is performed with the correct value set on the `max` query parameter. Example:
![image](https://user-images.githubusercontent.com/10886480/199210433-def3dbb8-df8a-484f-91f3-6868fc49b04e.png)
* The issue is similar to this bug: https://github.com/keycloak/keycloak/issues/15231
* The search window in the "Add associated roles" modal window does not help since it only performs a search on the already fetched data. I assume this is by design but doesn't hurt to mention it.
* Filtering by clients in the "Add associated roles" modal window works as expected, the HTTP request sets the appropriate value for the `max` query parameter in that API call. The issue only appears when "Filter by roles" is selected.

**Comment by ssilvert** [comment] 2022-11-02 13:35
@stmi11 This is fixed in Keycloak 20.0.0.  I'm going to close the issue but we can reopen if you still see a problem.

**Closed by ssilvert** 2022-11-02 13:35 UTC
Labels: kind/bug, area/admin/ui, status/triage

**Comment by michalgabor** [comment] 2023-02-03 14:41
hi guys.
This problem is detected again in version 20.0.3

**Comment by jonkoops** [comment] 2023-02-03 15:15
@michalgabor you can report your issue on the [UI repository](https://github.com/keycloak/keycloak-ui/issues). Please provide the steps to reproduce this and make sure you have tested this in the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly).

**Comment by ssilvert** [comment] 2023-02-03 21:13
@michalgabor I can't reproduce this in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).  But if you can reproduce using the nightly then we can investigate further.

If we do need to reopen just let me know.  You wouldn't need to make a new issue in the UI repo.  I have rights to migrate the issue over to there. 

But I'm pretty sure this is already fixed.

**Comment by michalgabor** [comment] 2023-02-06 10:25
@ssilvert thank you for your response. 
I have now tested on the nightly version. The problem has been detected there. 

Simulation of the issue: https://www.youtube.com/watch?v=q_wPIYVBWC0
