### ISSUE TITLE
Crash LDAP Groups import 

### ISSUE THREAD

**Issue by AustralEpitech** [keycloak/keycloak#15730] opened 2022-11-28 16:42 UTC
### Area

ldap

### Describe the bug

When you create a mapper for `group-ldap-mapper`, if you put `Membership User LDAP Attribute` to an attribute not imported in keycloak, the groups get imported and are visible from the group tab, but if you click on one, you get the error `Request failed with status code 500`. The same happens when you try to see the groups from a user or via an api request
If you set `User Groups Retrieve Strategy` to `GET_GROUPS_FROM_USER_MEMBEROF_ATTRIBUTE`, everything works properly in the group tab, but from a user or via an api request, the same error happens.

### Version

19.0.3 (bitnami k8s chart)

### Expected behavior

The groups should work properly.

### Actual behavior

ERROR: `Request failed with status code 500`

### How to Reproduce?

- Connect keycloak to a `LDAP`
- Add `group-ldap-mapper`
- Set the field `Membership User LDAP Attribute` to a field not mapped (eg. `sn` or a custom attribute)
- Check the group tab

**Comment by charlieharcum** [comment] 2023-04-19 14:59
Any updates on this one?  I have the exact same issue.  Just trying to sync a few basic groups from Active Directory but have this exact issue.  If no members are added to the groups in AD I can open and view the groups from inside keycloak.  But once a user is a member and a new sync is done, the groups are synced but when you open them from inside keycloak you get that 500 error

**Comment by sguilhen** [comment] 2023-05-17 22:12
@AustralEpitech I've started triaging this on Keycloak 21.1.0 and I couldn't reproduce the 500 error. I believe this can have something to do with the way I've structured my test user/group, so I would like to ask if you could share an ldif containing a sample user/group using your structure.

**Comment by sguilhen** [comment] 2023-12-08 12:58
I'm closing this as I could not reproduce the problem and have not had an update since May. If the problem still exists in latest Keycloak version, please re-open with more detailed instructions to reproduce.

**Closed by sguilhen** 2023-12-08 12:58 UTC
Labels: kind/bug, area/ldap, team/store, status/triage
