### ISSUE TITLE
Unable to configure custom authenticator via the Admin UI

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#14491] opened 2022-09-19 13:31 UTC
### Describe the bug

I have defined Sms Authenticator as second factor for authentication.
Clicking on the button for configuring it in the UI it results in the following error: "Can't convert undefined to object" and there are no logs in the console regarding it. 
![Error](https://user-images.githubusercontent.com/26387482/191028909-5660e615-963a-43b1-8ff9-ad302f9eb890.PNG)

When I downgrade to version 19.0.1 I'm able to configure it but have the issue with processing the template: https://github.com/keycloak/keycloak/issues/13401 

### Version

19.0.2

### Expected behavior

Authenticator is configured, no error is shown

### Actual behavior

The custom authenticator cannot be configured. Error shown in the UI. "Can't convert undefined to object" 

### How to Reproduce?

1. Do a copy of the browser flow
2. Add additional step after the "Username password form" => in my case Sms Authenticator
3. Click on the button to configure the authenticator => error is shown

**Comment by sventorben** [comment] 2022-09-20 17:03
Same as #14493?

**Comment by enastevska** [comment] 2022-09-21 07:49
yes

**Comment by Chris403** [comment] 2022-09-22 13:00
We have the same issue, as a workaround change the "Admin Console Theme" to keycloak and refresh your session. You'll be able to finish your settings.

**Comment by ssilvert** [comment] 2022-09-23 00:10
I'm closing this as a duplicate of keycloak/keycloak-ui#3375.  

The fix has been merged if anyone wants to try out the nightly build at https://github.com/keycloak/keycloak/releases/tag/nightly.

**Closed by ssilvert** 2022-09-23 00:10 UTC
Labels: kind/bug, status/triage
