### ISSUE TITLE
Admin console is not loading over HTTP in production mode

### ISSUE THREAD

**Issue by mvk37** [keycloak/keycloak#14812] opened 2022-10-10 02:19 UTC
### Describe the bug

I am trying to enable HTTP by KC_HTTP_ENABLED=true. In development mode I can access admin console by both http and https. No problem. But in production mode I can access admin console only over https.

When I try to access over http http://127.0.0.1:8080/admin/  loading page is spinning forever and I see this error in the browser: 

```
GET https://127.0.0.1:8443/realms/master/protocol/openid-connect/login-status-iframe.html/init?client_id=security-admin-console&origin=http://127.0.0.1:8080

403 Forbidden
```

This request some reason is using https.

REST API works fine. I can get access token both over http and https.

### Version

19.0.3

### Expected behavior

I can access admin console both over http and https when  KC_HTTP_ENABLED=true

### How to Reproduce?

export KC_HTTPS_KEY_STORE_PASSWORD=keycloak
export KC_HTTPS_KEY_STORE_FILE=/home/mkuznets/certs/keycloak.jks
export KC_HOSTNAME=127.0.0.1 
export KC_HTTP_ENABLED=true

./kc.sh build
./kc.sh start

In a browser access admin GUI over http: 
http://127.0.0.1:8080/admin/

Admin GUI spinning and not loading.

**Comment by Heromyth** [comment] 2022-10-12 06:15
Everything is ok when running Keycloak in development mode:
```
kc start-dev
```

**Comment by stianst** [comment] 2022-10-19 10:50
Question: if you have gone to the trouble of enabling https, why on earth would you want to be able to access the admin console over http?

**Comment by mvk37** [comment] 2022-10-19 13:43
We have a customer who prefer works on internal network over http.

If it is a problem to implement at least make a note in documentation that there is a restriction. Http is not fully supported in production mode.

**Comment by stianst** [comment] 2022-10-19 14:44
I would strongly recommend against ever going anywhere near the admin console with HTTP only in production, that's why I'm asking.

If you have HTTPS enabled Keycloak will assume you want to use HTTPS URLs. That's why the admin console will try to contact Keycloak over HTTPS, and it will also use HTTPS URLs for it's configured redirect/web origin URLs.

You can use `hostname-admin-url=http://127.0.0.1:8443` if you'd like, which would force the admin URLs to that, not that it's a great idea though.

**Comment by stianst** [comment] 2022-10-19 14:47
Closing this one as there's not a bug here. We've created a follow-up here https://github.com/keycloak/keycloak/issues/15018 to track various docs (and possibly other improvements) we can make to make this stuff easier to configure/understandable.

**Closed by stianst** 2022-10-19 14:47 UTC
Labels: kind/bug, area/admin/ui, area/dist/quarkus, status/triage

**Comment by Kamolbekcode** [comment] 2025-01-27 13:49
raxmat bro
