### ISSUE TITLE
Errors: failed to write / response has already been written

### ISSUE THREAD

**Issue by JasperSurmont** [keycloak/keycloak#27157] opened 2024-02-20 09:46 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After upgrading from v15 to v23.0.6, we periodically receive these two errors :

<details>
  <summary>Failed to write</summary>
  
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-90) Uncaught server error: java.io.IOException: java.io.IOException: Failed to write                                                                  at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:216)                                                                                                                           at java.base/java.io.InputStream.transferTo(InputStream.java:783)                                                       at org.jboss.resteasy.reactive.common.providers.serialisers.InputStreamMessageBodyHandler.writeTo(InputStreamMessageBodyHandler.java:38)                                                                                                        at org.jboss.resteasy.reactive.server.providers.serialisers.ServerInputStreamMessageBodyHandler.writeResponse(ServerInputStreamMessageBodyHandler.java:46)                                                                                      at org.jboss.resteasy.reactive.server.providers.serialisers.ServerInputStreamMessageBodyHandler.writeResponse(ServerInputStreamMessageBodyHandler.java:17)                                                                                      at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:227)                   at org.jboss.resteasy.reactive.server.core.serialization.DynamicEntityWriter.write(DynamicEntityWriter.java:106)                                                                                                                                at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:32)              at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)                                                                                              at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)                                                                                                                        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)                               at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)                                    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)                              at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)                                                 at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)                             at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                at java.base/java.lang.Thread.run(Thread.java:833) 

</details>
<details>
<summary>Response has already been written</summary>

ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-90) HTTP Request to /auth/resources/2hslb/admin/keycloak.v2/logo.svg failed, error id: 8a4303ea-aa06-4d20-bed6-30fcd999411d-1: java.lang.IllegalStateException: Response has already been written                                                                            at io.vertx.core.http.impl.Http2ServerResponse.checkValid(Http2ServerResponse.java:554)                                 at io.vertx.core.http.impl.Http2ServerResponse.exceptionHandler(Http2ServerResponse.java:134)                           at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.<init>(ResteasyReactiveOutputStream.java:45)                                                                                                                           at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.createResponseOutputStream(VertxResteasyReactiveRequestContext.java:457)                                                                                        at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getOrCreateOutputStream(ResteasyReactiveRequestContext.java:979)                                                                                                      at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter.writeResponse(FullyFeaturedServerJacksonMessageBodyWriter.java:51)                                                                      at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:227)                   at org.jboss.resteasy.reactive.server.core.serialization.DynamicEntityWriter.write(DynamicEntityWriter.java:106)                                                                                                                                at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:32)              at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)                                                                                              at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)                                                                                                                        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)                               at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)                                    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)                              at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)                                                 at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)                             at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                at java.base/java.lang.Thread.run(Thread.java:833)
</details>

Everything seems to work on the front-end, but these errors are clogging up the log and we don't know why they are occurring. 

### Version

23.0.6

### Regression

- [ ] The issue is a regressions

### Expected behavior

No errors to be there

### Actual behavior

The errors are there, even though it looks like nothing is wrong on the front-end

### How to Reproduce?

We are running keycloak 23.0.6 on windows server 2019 with very little customization. I am not entirely sure how to effectively reproduce this issue.

**Comment by shawkins** [comment] 2024-02-27 18:28
> We are running keycloak 23.0.6 on windows server 2019 with very little customization

Are you using any custom jax rs / resteasy filters - anything that may have access to the response? 

Is there more nested to the failed to write exception? It seems like that could have an underlying exception that the response is closed (client closed the connection?) or has already been written - which would then be similar to the other stack you provided.

There have been several upstream issues with the Response already written: https://github.com/search?q=repo%3Aquarkusio%2Fquarkus+%22Response+has+already+been+written%22&type=issues&s=created&o=desc - so it's possible that your hitting something related.

**Comment by JasperSurmont** [comment] 2024-02-28 09:51
As far as I know, we are not doing anything custom. It seems like the Response has already been written errors always occur when fetching some front-end files such as .css or .woff2 files.

It does seem like there is more to the 'Failed to write' exception, it is caused by a 'connection was closed'.

It seems like sometimes the theme data is not found correctly. We see this since the frontend displays a red banner stating it cannot load one of the files (css, js, ...). This is caused by the 'Response has already been written' error, after which I think the Failed to write exception follows.

We do use custom themes, but it is also erroring on the keycloak.v2 theme.

**Comment by shawkins** [comment] 2024-02-28 19:51
From your description above does it seem like root problem is just "connection was closed" and that there may simply be excessive logging of the exceptions that follow?

What is inbetween your clients and your keycloak instance, such as a proxy, that may be causing http connections to close unexpectedly?

**Comment by stianst** [comment] 2024-03-07 07:09
@vmuzikar moving back to cloud-native, this is either something environment specific or it's something caused by Quarkus/filters/etc.

**Comment by shawkins** [comment] 2024-03-18 15:59
Closing due to lack of updates. 

cc @vietj or others on the vert.x team - might be worth a look to see if this is familiar / benign.

**Closed by shawkins** 2024-03-18 15:59 UTC
Labels: kind/bug, area/core, area/dist/quarkus, team/cloud-native, status/triage
