### ISSUE TITLE
Liquibase warnings causing major delays in Kubernetes deployments

### ISSUE THREAD

**Issue by rection** [keycloak/keycloak#20696] opened 2023-05-31 14:17 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dependencies

### Describe the bug

I am using k3s engine Keycloak deployment with MySQL databases. I saw same lines in docker deployment, and microk8s engine.

I am taking these warning lines 4 times in my keycloak logs.
```
WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
```

They are causing delay from keycloak build process between 5 to 10 minutes.

They seems a MySQL limitations from MySQL's dialect. I found this [jira ticket](https://liquibase.jira.com/browse/CORE-955) in liquidbase. This issue seems already solved.

### Version

21.1.0

### Expected behavior

Keycloak should start as PostgreSQL deployments. To explain differences between MySQL and PostgreSQL in my side:

Keycloak-MySQL build time for all containers: 5-10 minutes
Keycloak-PostgreSQL build time for all containers: maximum 3 minutes

Each CI pipeline runs 5-10 minutes. So, I shouldn't see any when I changed databases.

### Actual behavior

These warnings repeat 4 times in the keycloak log. It causes more than 5 minutes delay until keycloak reachable.

The database already configured for keycloak database, db user and db password. They are running in k8s, and there is no resource limit to prevent any operation.

```
2023-05-19 14:28:25,288 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_240035, Site name: null
2023-05-19 14:28:25,986 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-05-19 14:28:25,986 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-05-19 14:28:26,433 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2023-05-19 14:28:26,895 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-05-19 14:28:26,896 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-05-19 14:30:53,602 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-05-19 14:30:53,614 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
```

### How to Reproduce?

I am using k3s engine. The keycloak database initialized with custom mysql dockerfile. This deployment resources:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        args:
          - "start"
          - "--optimized"
        env:
          - name: KEYCLOAK_ADMIN
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "admin"
          - name: KC_DB
            value: "mysql"
          - name: KC_DB_URL
            value: "jdbc:mysql://keycloak-mysql/keycloak"
          - name: KC_DB_USERNAME
            value: "root"
          - name: KC_DB_PASSWORD
            value: "test"
          - name: KC_HOSTNAME_STRICT
            value: "false"
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
            scheme: HTTP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-mysql
spec:
  selector:
    matchLabels:
      app: keycloak-mysql
  serviceName: keycloak-mysql
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - name: mysql
          image: keycloakdb:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test
          volumeMounts:
            - name: keycloak-mysql-pv
              mountPath: /var/lib/mysql
              subPath: mysql
  volumeClaimTemplates:
    - metadata:
        name: keycloak-mysql-pv
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
  labels:
    app: keycloak-mysql
spec:
  selector:
    app: keycloak-mysql
  type: ClusterIP
  clusterIP: None
  ports:
  - name: database
    protocol: TCP
    port: 3306
```

This is my init.sql:
```
CREATE DATABASE keycloak CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER 'keycloak'@'%' IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON keycloak.* TO 'keycloak'@'%';
FLUSH PRIVILEGES;
```

This is my MySQL Dockerfile:
```
FROM mysql:8.0
ADD init.sql /docker-entrypoint-initdb.d/
```

This is my Keycloak Dockerfile:
```
FROM quay.io/keycloak/keycloak:latest as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=mysql

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

### Anything else?

I found these links:

https://stackoverflow.com/questions/34986220/liquibase-modifydatatype-fails-on-mysql
https://github.com/rancher/rancher/issues/4202

**Comment by andre-nascimento-rh** [comment] 2023-06-06 12:52
Thank you for the report, @rection!

Now I believe I'm able to reproduce the issue, however, in order to avoid time-wasting, let's ask @keycloak/store team buddies If they have some clue about what's happening in this case.

@hmlnarik , any ideas about this?

Thanks in advance.

**Comment by ahus1** [comment] 2023-06-07 07:55
@rection - what happens when you start Keycloak with an empty database is that Keycloak applies a lot of small database schema changes to migrate the DB schema incrementally to the latest version. 

The warnings you see although they are MySQL specific are a not the cause of the delay, it is the number of DB schema changes and how fast a DB processes them. Some DBs are faster compared to others, so you see a performance difference between PostgreSQL and MySQL. You see the same in our scheduled runs, see "Legacy Store IT" for different DBs here: https://github.com/keycloak/keycloak/actions/runs/5196171028/jobs/9369788700

You might want to dig down into database performance optimization here, choose only fast databases, or pre-seed the database with a database dump of a previous Keycloak version to remove the need to migrate the DB schema. Once you have a pre-seeded database from an old Keycloak version, and run a newer version of Keycloak against it, Keycloak will only run the remaining changes against the database which should be faster.

If that answers your question, I suggest closing this issue.

**Comment by andre-nascimento-rh** [comment] 2023-06-07 08:06
Thanks for your quick and clarifier answer, @ahus1 !

So, relying on the comment above, I removed the labels "kind/bug", "help wanted" and "status/triage". And If the aforementioned comment answers your question, @rection , I'd like to close this issue, If you agree.

Thanks.

**Comment by rection** [comment] 2023-06-07 13:24
Thank you for your answers @ahus1 and @andre-nascimento-rh . That's so helped to understand the real problem behind the build operation. 

In my opinion, improving MySQL performance will gain maximum 1 minutes. I don't see any point to work on that.

I don't have an option like to pre-seeded database for now. I saw mariadb seems lower build time when compared with MySQL. I will give a chance to mariadb. I hope mariadb will work better.

Thank you for all your efforts. This issue can close. I might update if I find another way to break this build time.

**Closed** 2023-06-07 13:56 UTC
Labels: area/dependencies, team/cloud-native

**Comment by nxadm** [comment] 2023-06-08 10:11
Addition for poeple searching in the issues: the warning is also present when using mariadb as the backend and Keycloak not running on Kubernetes.

**Comment by nidavellir9** [comment] 2024-10-22 19:14
Only one small addition of this issue, the warning is also present on v21.1.2 of Keycloak using MariaDB
