### ISSUE TITLE
Enabling "Exclude Session State.." has no effect.

### ISSUE THREAD

**Issue by n3vu0r** [keycloak/keycloak#27528] opened 2024-03-05 08:30 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Unable to exclude `session_state` claim from access token.

### Version

23.0.7, 24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Access token should not include `session_state` if exclusion is enabled.

### Actual behavior

Access token still includes `session_state` even though exclusion is enabled.

### How to Reproduce?

Steps to reproduce:

 1. Select `admin-cli` client in the UI
 2. Go to `Advanced`/`OpenID Connect Compatibility Modes`
 3. Enable `Exclude Session State From Authentication Response`
 4. Go to `admin-cli`/`Client Scopes`/`Evaluate`
 5. Select admin user
 6. Access token still includes `session_state`

**Comment by mposolda** [comment] 2024-03-07 14:48
I am closing as this is not a bug. Note that switch `Exclude Session State From Authentication Response` is not related to `session_state` claim in token, but it is related really to OIDC authentication response as it's name states. That is the response, which is usually sent by Keycloak server to the OIDC client by browser redirect and usually includes parameters like `code`, `state` etc. See the specification for some details: https://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions . So the switch work as expected.

Regarding removing `session_state` from the token claims, we have different issue for this - https://github.com/keycloak/keycloak/issues/27624 . You can monitor that one for further update on this.

**Closed** 2024-03-07 14:48 UTC
Labels: area/oidc, kind/bug, team/core-clients

**Comment by n3vu0r** [comment] 2024-03-07 15:27
Thanks for your explanation, it's very helpful.
