### ISSUE TITLE
Import overrides some realm settings and WebAuthn policies

### ISSUE THREAD

**Issue by huguesn** [keycloak/keycloak#25225] opened 2023-12-01 19:46 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

When importing a _RealmRepresentation_ through the import Rest API endpoint `PUT /admin/realms/${realmName}`, if the representation contains `null` attributes, some realm settings are overridden to their default value.

Affected attributes:
- Realm settings > Tokens > **OAuth 2.0 Device Code Lifespan**
- Realm settings > Tokens > **OAuth 2.0 Device Polling Interval**
- Realm settings > Events > User events settings > **Expiration**
- Authentication -> Policies -> **Webauthn Policy** (all the attributes)
- Authentication -> Policies -> **Webauthn Passwordless Policy** (all the attributes)

I found out while testing Keycloak Config CLI with a minimal json. I wanted to be able to update a realm by importing only a few attributes. It is working fine, excepted for those attributes (listed above). While hunting the bug, I found that the issue is not on that tool, but on Keycloak itself.

### Version

23.0.0

### Expected behavior

When importing a _RealmRepresentation_ with `null` attributes, I expect these attributes to **NOT** change on the realm. It is a requirement if I want to apply a specific setting without having to have the full representation with all the values in the json.

### Actual behavior

When importing a _RealmRepresentation_ with `null` attributes, some of these attributes **ARE** changed on the realm. The description of the bug contains all the attributes affected by this bug.

### How to Reproduce?

Steps:
1. Create a new realm
2. Update to a non-default value any of the affected attributes such as:
   - Authentication -> Policies -> Webauthn Passwordless Policy -> **Require resident key** (set to `Yes`)
3. Update the realm through the Import API with a _RealmRepresentation_ with `null` for every attributes

Automated steps:
```bash
#!/bin/sh

#docker run -it  \
#  -p 8080:8080 \
#  -e KC_HOSTNAME_URL=http://localhost:8080 \
#  -e KC_HTTP_ENABLED=true \
#  -e KEYCLOAK_ADMIN=admin \
#  -e KEYCLOAK_ADMIN_PASSWORD=admin \
#  --entrypoint /opt/keycloak/bin/kc.sh keycloak/keycloak:23.0.0 start

BASE_URL=http://localhost:8080
USER=admin
PASS=admin

TOKEN=`curl -s -d "client_id=admin-cli" -d "username=$USER" -d "password=$PASS" -d "grant_type=password" "$BASE_URL/realms/master/protocol/openid-connect/token" | jq -r .access_token`

EMPTY_REALM_REPRESENTATION='{"id":null,"realm":"test","displayName":"","displayNameHtml":null,"notBefore":null,"defaultSignatureAlgorithm":null,"revokeRefreshToken":null,"refreshTokenMaxReuse":null,"accessTokenLifespan":null,"accessTokenLifespanForImplicitFlow":null,"ssoSessionIdleTimeout":null,"ssoSessionMaxLifespan":null,"ssoSessionIdleTimeoutRememberMe":null,"ssoSessionMaxLifespanRememberMe":null,"offlineSessionIdleTimeout":null,"offlineSessionMaxLifespanEnabled":null,"offlineSessionMaxLifespan":null,"clientSessionIdleTimeout":null,"clientSessionMaxLifespan":null,"clientOfflineSessionIdleTimeout":null,"clientOfflineSessionMaxLifespan":null,"accessCodeLifespan":null,"accessCodeLifespanUserAction":null,"accessCodeLifespanLogin":null,"actionTokenGeneratedByAdminLifespan":null,"actionTokenGeneratedByUserLifespan":null,"oauth2DeviceCodeLifespan":null,"oauth2DevicePollingInterval":null,"enabled":null,"sslRequired":null,"passwordCredentialGrantAllowed":null,"registrationAllowed":null,"registrationEmailAsUsername":null,"rememberMe":null,"verifyEmail":null,"loginWithEmailAllowed":null,"duplicateEmailsAllowed":null,"resetPasswordAllowed":null,"editUsernameAllowed":null,"bruteForceProtected":null,"permanentLockout":null,"maxFailureWaitSeconds":null,"minimumQuickLoginWaitSeconds":null,"waitIncrementSeconds":null,"quickLoginCheckMilliSeconds":null,"maxDeltaTimeSeconds":null,"failureFactor":null,"privateKey":null,"publicKey":null,"certificate":null,"codeSecret":null,"roles":null,"groups":null,"defaultRoles":null,"defaultRole":null,"defaultGroups":null,"requiredCredentials":null,"passwordPolicy":null,"otpPolicyType":null,"otpPolicyAlgorithm":null,"otpPolicyInitialCounter":null,"otpPolicyDigits":null,"otpPolicyLookAheadWindow":null,"otpPolicyPeriod":null,"otpPolicyCodeReusable":null,"otpSupportedApplications":null,"localizationTexts":null,"webAuthnPolicyRpEntityName":null,"webAuthnPolicySignatureAlgorithms":null,"webAuthnPolicyRpId":null,"webAuthnPolicyAttestationConveyancePreference":null,"webAuthnPolicyAuthenticatorAttachment":null,"webAuthnPolicyRequireResidentKey":null,"webAuthnPolicyUserVerificationRequirement":null,"webAuthnPolicyCreateTimeout":null,"webAuthnPolicyAvoidSameAuthenticatorRegister":null,"webAuthnPolicyAcceptableAaguids":null,"webAuthnPolicyExtraOrigins":null,"webAuthnPolicyPasswordlessRpEntityName":null,"webAuthnPolicyPasswordlessSignatureAlgorithms":null,"webAuthnPolicyPasswordlessRpId":null,"webAuthnPolicyPasswordlessAttestationConveyancePreference":null,"webAuthnPolicyPasswordlessAuthenticatorAttachment":null,"webAuthnPolicyPasswordlessRequireResidentKey":null,"webAuthnPolicyPasswordlessUserVerificationRequirement":null,"webAuthnPolicyPasswordlessCreateTimeout":null,"webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister":null,"webAuthnPolicyPasswordlessAcceptableAaguids":null,"webAuthnPolicyPasswordlessExtraOrigins":null,"users":null,"federatedUsers":null,"scopeMappings":null,"clientScopeMappings":null,"clients":null,"clientScopes":null,"defaultDefaultClientScopes":null,"defaultOptionalClientScopes":null,"browserSecurityHeaders":null,"smtpServer":null,"userFederationProviders":null,"userFederationMappers":null,"loginTheme":null,"accountTheme":null,"adminTheme":null,"emailTheme":null,"eventsEnabled":null,"eventsExpiration":null,"eventsListeners":null,"enabledEventTypes":null,"adminEventsEnabled":null,"adminEventsDetailsEnabled":null,"identityProviders":null,"identityProviderMappers":null,"protocolMappers":null,"components":null,"internationalizationEnabled":null,"supportedLocales":null,"defaultLocale":null,"authenticationFlows":null,"authenticatorConfig":null,"requiredActions":null,"browserFlow":null,"registrationFlow":null,"directGrantFlow":null,"resetCredentialsFlow":null,"clientAuthenticationFlow":null,"dockerAuthenticationFlow":null,"attributes":null,"keycloakVersion":null,"userManagedAccessAllowed":null,"social":null,"updateProfileOnInitialSocialLogin":null,"socialProviders":null,"applicationScopeMappings":null,"applications":null,"oauthClients":null,"clientTemplates":null,"clientProfiles":null,"clientPolicies":null}'

# Required for this test to be idempotent
curl -X DELETE --silent $BASE_URL/admin/realms/test \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN"

# Create a realm with default settings
curl -X POST --silent $BASE_URL/admin/realms \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
     -d "$EMPTY_REALM_REPRESENTATION"

RESULT_DEFAULT_SETTINGS=`curl -X GET --silent $BASE_URL/admin/realms/test \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN"`

# Update the realm for 2 attributes (one is affected by the bug)
# "webAuthnPolicyPasswordlessRequireResidentKey" set to "Yes" <------- AFFECTED
# "defaultSignatureAlgorithm" set to "HS384"
UPDATE_2_ATTRIBUTES=`echo $EMPTY_REALM_REPRESENTATION | jq '.webAuthnPolicyPasswordlessRequireResidentKey = "Yes" | .defaultSignatureAlgorithm = "HS384"'`
curl -X PUT --silent $BASE_URL/admin/realms/test \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
     -d "$UPDATE_2_ATTRIBUTES"
	 
RESULT_UPDATE_2_ATTRIBUTES=`curl -X GET --silent $BASE_URL/admin/realms/test \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN"`

# Update the realm with a random attribute "displayName"
RANDOM_UPDATE=`echo $EMPTY_REALM_REPRESENTATION | jq '.displayName = "New display name"'`
curl -X PUT --silent $BASE_URL/admin/realms/test \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN" \
     -d "$RANDOM_UPDATE"
	 
RESULT_RANDOM_UPDATE=`curl -X GET --silent $BASE_URL/admin/realms/test \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $TOKEN"`

echo AFFECTED ATTRIBUTE: webAuthnPolicyPasswordlessRequireResidentKey
echo Default value on realm creation:
echo $RESULT_DEFAULT_SETTINGS | jq .webAuthnPolicyPasswordlessRequireResidentKey

echo Value after updating the attribute:
echo $RESULT_UPDATE_2_ATTRIBUTES | jq .webAuthnPolicyPasswordlessRequireResidentKey

echo Value after another attribute get updated:
echo $RESULT_RANDOM_UPDATE | jq .webAuthnPolicyPasswordlessRequireResidentKey

echo
echo NOT-AFFECTED ATTRIBUTE: defaultSignatureAlgorithm
echo Default value on realm creation:
echo $RESULT_DEFAULT_SETTINGS | jq .defaultSignatureAlgorithm

echo Value after updating the attribute:
echo $RESULT_UPDATE_2_ATTRIBUTES | jq .defaultSignatureAlgorithm

echo Value after another attribute get updated:
echo $RESULT_RANDOM_UPDATE | jq .defaultSignatureAlgorithm
```

Output:  
![image](https://github.com/keycloak/keycloak/assets/2357257/cc354796-92da-4d29-b48f-8aef7517ea27)

### Anything else?

The bug appears to be inside `LegacyExportImportManager.importRealm(RealmRepresentation, RealmModel, boolean)`.  
https://github.com/keycloak/keycloak/blob/main/model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java#L165

**Comment by bastianccm** [comment] 2024-02-16 12:53
Hi, I have encountered a similar issue with the `isOtpPolicyCodeReusable` flag.
If it is not set, thus, it's `null`, so the fallback to `false` is triggered in
https://github.com/keycloak/keycloak/blob/c30b9545ef013b4c3083a4c251ebd3db505180d0/model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java#L885

There is similar behaviour for the oauth device attributes:
https://github.com/keycloak/keycloak/blob/c30b9545ef013b4c3083a4c251ebd3db505180d0/server-spi/src/main/java/org/keycloak/models/OAuth2DeviceConfig.java#L85-L92

I assume the WebAuthN is caused by the same null fallbacks.

**Comment by mposolda** [comment] 2024-02-21 11:41
@douglaspalmer This might be already fixed by one of your latest commits. Could you please confirm if it is same issue and close this if yes?

In the meantime, anyone is welcome to try this with latest Keycloak nightly release and confirm if the issue is already fixed. Keycloak nightly can be downloaded from https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by douglaspalmer** [comment] 2024-02-22 05:31
This should be fix on HEAD. This PR is already merged: https://github.com/keycloak/keycloak/pull/26718/files.

**Closed by douglaspalmer** 2024-02-22 05:31 UTC
Labels: kind/bug, area/import-export, status/triage, team/core-clients
