### ISSUE TITLE
User Federation - Remove imported users not working

### ISSUE THREAD

**Issue by sebastian-czech** [keycloak/keycloak#13888] opened 2022-08-19 14:18 UTC
### Describe the bug

We updated from Keycloak 18.0.2 to 19.0.1 and noticed that it is not possible to remove imported users anymore.
We tried it using our upgraded configuration and database as well as with an empty keycloak installation and failed both time.

Following conditions were used
- A single ldap configuration was added
- Vendor: Active Directory
- Bind type: simple
- Edit mode: Read_Only
- Import users: Enabled
- No automatic syncronization

100 users were imported using the ldap configuration. It was possible to remove the imported users using version 18.0.2 but not possible using version 19.0.1. After pressing the button "Imported users have been removed." was printed and no errors were shown within the log but the users are still available.

![image](https://user-images.githubusercontent.com/91592298/185638530-1f8097f3-cb6a-4664-9936-1b3a17066d28.png)

### Version

19.0.1

### Expected behavior

Synchronized ldap users are removed.

### Actual behavior

Synchronized ldap users still exist.

### How to Reproduce?

Use a new Keycloak instance and connect to an AD.

**Comment by mhajas** [comment] 2023-02-20 17:49
@sebastian-czech How do you test whether the user exists after you trigger `remove imported`? Also, have you tried 20.0.x?

**Comment by mhajas** [comment] 2023-03-31 11:08
@sebastian-czech Thank you for reporting this bug, however, we are not able to reproduce it so I am closing this.

If anyone is experiencing this issue and can provide more details so we can reproduce it, please add a comment to this issue.

**Closed** 2023-03-31 11:51 UTC
Labels: kind/bug, area/ldap, team/store
