### ISSUE TITLE
Users default search displays the message "No search results" as soon as type the first letter.

### ISSUE THREAD

**Issue by tzengshinfu** [keycloak/keycloak#30070] opened 2024-06-03 06:50 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When type the first letter, the message "No search results" is displayed immediately, and the search box loses focus.

### Version

24.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

Wait for the user to finish typing and press ➡️, without displaying any messages during this period.

### Actual behavior

When type the first letter, the message "No search results" is displayed immediately, and the search box loses focus.

### How to Reproduce?

1. Manage>Users>User list.
2. Click on the search box of "Search User".
3. As soon as type the first letter.
4. The message "No search results" is displayed immediately, and the search box loses focus.

### Anything else?

![demo](https://github.com/keycloak/keycloak/assets/2170033/620a19f1-40f8-44bc-bc4f-bff38270755b)

**Comment by bjoernhype** [comment] 2024-06-04 11:27
This seems to be a duplicate of https://github.com/keycloak/keycloak/issues/29153 and https://github.com/keycloak/keycloak/issues/29488. Both where closed as "fixed in net release", but today 24.0.5 was released without fixing this :(

**Comment by michaelkebe** [comment] 2024-06-06 09:25
Stumbled on this, too.

In my case only occurs, if a user federation is enabled, as in the two other issues.

**Comment by davidezordan25** [comment] 2024-06-11 09:35
Version 25.0.0 fixed it.

**Closed** 2024-06-13 08:15 UTC
Labels: kind/bug, area/admin/ui, help wanted, team/ui, status/auto-expire, status/auto-bump, priority/normal

**Comment by edewit** [comment] 2024-07-17 06:48
and duplicate of #27917
