### ISSUE TITLE
Docs: server_admin/topics/users/proc-creating-user.adoc

### ISSUE THREAD

**Issue by MuhammadAbeerAkmal** [keycloak/keycloak#24003] opened 2023-10-16 08:12 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

File: server_admin/topics/users/proc-creating-user.adoc

When I am trying to create a user and click the create button, the `success` message is not showing but the user is added to the list. Nothing happens when I add a user.

### Version

22.0.4

### Expected behavior

When we will click on the `create` button, the `success` message or `error` message should be shown.

### Actual behavior

When we will click on the `create` button, the `success` message or `error` is not be shown.

### How to Reproduce?

Create a user and click the create button. You will not see anything updated on the screen.

**Comment by rmartinc** [comment] 2023-10-19 10:44
@MuhammadAbeerAkmal Using 22.0.4 I see the success message in the right/top corner. I cannot reproduce it. Anyway I'm moving to the UI team for now.

![Screenshot from 2023-10-19 12-41-58](https://github.com/keycloak/keycloak/assets/26901232/bbad1a5e-eba7-40fb-a0b6-1cca71226a44)

**Comment by ssilvert** [comment] 2023-10-31 19:32
@MuhammadAbeerAkmal I'm going to close this as I also can not reproduce.  If you find a way to reproduce this on the latest Keycloak version we can reopen.

**Closed by ssilvert** 2023-10-31 19:32 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
