### ISSUE TITLE
Audience Mapper putting guids in token instead of Client IDs

### ISSUE THREAD

**Issue by recurs10n** [keycloak/keycloak#31684] opened 2024-07-26 21:20 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

This may be two issues because I'm not sure if the symptoms are related. If so, I can put a second bug in. 

After creating a Client Scope with two mappers, one for Audience and one for User Client Roles, I've assigned the scope to a client. In both mappers the Client ID has been set. In version 25 of Keycloak this results in a token with a Guid in the Audience and I won't get a resource_access field. 

`"aud": [
    "90c0d592-91b1-49ba-a56e-41a8627cc8f4"
  ],`

If I remove the Client ID from both mappers I will get all the client names (not guids) in the audience field and the resource_access field will be populated for all clients. 

`"aud": [
    "test-client",
    "account"
  ]`

If I add an Audience mapper for a specific client and also add and Audience Resolve mapper, I will get both a guid and then also the names of all the clients in the Audience field.

`"aud": [
    "90c0d592-91b1-49ba-a56e-41a8627cc8f4",
    "test-client",
    "account"
  ]`

This works as expected in version 23. We found this when trying to upgrade to version 25.

### Version

25

### Regression

- [X] The issue is a regression

### Expected behavior

Adding an Audience mapper to the client scope adds the name of the client, not the guid, to the Audience.

Adding a User Client Role mapper with a specific clientID adds only roles for that client to the token.

### Actual behavior

Audiences are mapping as Guids and resource_access is not being added to the token if ClientID is specified in the mappers.

### How to Reproduce?

1. Create an a new private OIDC client. 
2. Remove the built-in "roles" Client Scope
3. Create a new role for the client
4. Assign the role to a user
5. Create a new client scope 
6. In that scope create an Audience mapper with the Client ID set to the new client
7. In that scope create a User Client Roles mapper with the Client ID set to the new client
8. Add the Client Scope to the Client as default
9. Request an access token for the client using the user you assigned the role to

**Comment by graziang** [comment] 2024-08-13 08:37
Closing this issue as it is a duplicate of #30436, which has already been fixed by #30523 available in the latest release.

**Closed by graziang** 2024-08-13 08:37 UTC
Labels: kind/bug, area/core, status/triage, team/core-clients
