### ISSUE TITLE
keycloak-js ESM does not work

### ISSUE THREAD

**Issue by robrez** [keycloak/keycloak#30261] opened 2024-06-07 19:03 UTC
### Description

The dependency on js-sha256 causes the esm you vend to not work properly.  Please consider switching libraries (eg: https://www.npmjs.com/package/@noble/hashes). It is also possible to use rollup to make an esm-compatible build of js-sha256 (eg: https://github.com/bundled-es-modules)

Filed separately: https://github.com/emn178/js-sha256/issues/44

**Comment by codespearhead** [comment] 2024-06-14 20:44
Can you elaborate on how "js-sha256 causes the ESM-compatible build to not work properly"?

**Comment by robrez** [comment] 2024-06-14 22:36
Sure, hopefully this helps:  https://stackblitz.com/edit/vitejs-vite-pvidyi?file=README.md

To be less terse and provide additional commentary to accompany the stackblitz above

- [js-sha256](https://github.com/emn178/js-sha256) is vended as CJS
  - There is no "module" field in its package.json
  - There is only a "main" field which points to a CJS file

While the ESM spec does say that it's fine to [import CJS from ESM](https://nodejs.org/api/esm.html#interoperability-with-commonjs), in practice it causes nothing but pain for dependents.

The pain is that build tooling must be given special instructions whenever a dependency is introduced that imports CJS.  This might be shrugged off as not a big deal whenever someone adds ESM that imports CJS as a direct dependency.  However this is pretty awful when you add a direct dependency that adds a transitive dependency that uses import statements on CJS.  You end up having to document code with blurbs such as, "If you add this package as a dependency, then be sure your build tooling is updated to handle the fact that it imports CJS".  And the need for such documentation becomes viral on any packages that depend on your package.

**Comment by jonkoops** [comment] 2024-06-17 10:53
Duplicate of #15769

**Closed by jonkoops** 2024-06-17 10:53 UTC
Labels: kind/enhancement, status/triage
