### ISSUE TITLE
x509 login code flow not working in version 18

### ISSUE THREAD

**Issue by mjschmidt** [keycloak/keycloak#12463] opened 2022-06-10 12:33 UTC
### Describe the bug

Keycloak 18 does not appear to be willing to use an x509 certificate for login code flow authentication when also carrying out mutual SSL.

### Version

18.0.0

### Expected behavior

Keycloak should read the x509 certificate, validate it then allow the user access.

### Actual behavior

Error message from debug logs

```x509 certificate is not available for mutual SSL```

### How to Reproduce?

Deploy keycloak 18 and attempt to use x509 code flow with mTSL/mutual SSL

### Anything else?

Based on reading through the method it looks like keycloak beleives the x509 certificate is null or lengeth null. However it is not and works fine with every other endpoint I hit.
https://www.javatips.net/api/keycloak-master/services/src/main/java/org/keycloak/authentication/authenticators/x509/X509ClientCertificateAuthenticator.java

**Comment by zamofingrApex** [comment] 2022-06-22 14:05
Any news about it ? I have the same problem, SSL is working fine but the authentication popup to choose the certificate never appears.

Thanks

**Comment by mjschmidt** [comment] 2022-06-24 12:51
Glad to hear someone else has this issue, but it looks like its only been triaged. Hopefully this gets into their sprint planning soon because this is kind of the main feature needed from Keycloak.

**Comment by zamofingrApex** [comment] 2022-06-24 13:20
@mjschmidt
It is working for me now. I didn't created the trust store.  And the major error was I forgot to enable mutual TLS. You can do that with :
`bin/kc.[sh|bat] start --https-client-auth=<none|request|required>`

let me know if you are still stuck

**Comment by mjschmidt** [comment] 2022-06-24 13:53
no no I gave it the truststore and keycloak itself is working. The area I am having issue with is setting up the codeflow to accept incoming pki certificates via the browser for private key authentication for various client services.

**Comment by mjschmidt** [comment] 2022-06-24 13:54
Also I am using keycloak on Kubernetes with the Operator

**Comment by mjschmidt** [comment] 2022-06-28 14:57
@zamofingrApex just to clarify. Are you able to log into keycloak with a pki certificate, or were you just able to get keycloak to take your jks and/or public and private certs so that keycloak itself is using https/mutualTLS/TwoWaySSL?

**Comment by hokiegeek2** [comment] 2022-09-09 16:27
@mjschmidt I am seeing the same error when I attempt to run keycloak behind ingress. However, I am using 16.1.1

**Comment by droslean** [comment] 2022-09-16 23:19
I think the problem I am facing is related to this one. https://github.com/keycloak/keycloak/issues/14468

**Comment by hokiegeek2** [comment] 2022-09-17 11:37
> Is there currently a timeline on what future version will support x509? Currently using on Kubernetes and have to have FIPS mode enabled as well.

@V1P3R5T1NG @droslean I just testing with 19.0.1 yesterday and no luck yet -> have either of you tried this version yet?

**Comment by droslean** [comment] 2022-09-19 07:29
@hokiegeek2 No luck...

**Comment by hokiegeek2** [comment] 2022-09-19 13:27
@droslean The issue is I am running into is the x509 authentication is working fine on Kubernetes if I access via a NodePort--in other words, if keycloak is not behind a reverse proxy, which in the case of Kubernetes, ingress. I see the same results with Keycloak 16.1.1 and 19.0.1.

However, with Keycloak behind Kubernetes ingress (nginx reverse proxy), Keycloak extracts the TLS wildcard cert--not the client cert. That's where I am stuck WRT Keycloak x509 authentication

**Comment by droslean** [comment] 2022-09-19 14:27
@hokiegeek2 The keycloak-operator should create a `keycloak-discovery` service. Try to use that service to reach keycloak, instead

**Comment by hokiegeek2** [comment] 2022-09-19 14:45
@droslean does that work for requests coming from outside Kubernetes? We have use case involving Jupyterhub callbacks which require access to Keycloak external to Kubernetes via NodePort (x509 works) and Ingress (x509 not currently working).

**Comment by droslean** [comment] 2022-09-19 14:48
@hokiegeek2 In this case you will need to configure your ingress to use the same TLS as keycloak or tell your ingress to redirect the SSL. Check  https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/tls.md

**Comment by hokiegeek2** [comment] 2022-09-27 10:34
@droslean @mjschmidt @V1P3R5T1NG I have x509 authentication working w/ keycloak behind ingress w/ version 19.0.1. The first supporting log message I see is this:

![image](https://user-images.githubusercontent.com/10785153/192501125-306381eb-2121-4c26-bf6f-ae46942a5a9f.png)

And the I see this where the end user certificate is found:

![image](https://user-images.githubusercontent.com/10785153/192501460-57d3dffa-4014-462e-97a0-119ffae97024.png)

Finally, I see the following log message showing I successfully authenticated via x509:

![image](https://user-images.githubusercontent.com/10785153/192502400-0e381075-18fd-4139-9e1c-7c1346d9ae0a.png)

The last, remaining issue (I think) is the following error message:

![image](https://user-images.githubusercontent.com/10785153/192502823-2b225405-4e0a-4bce-8e39-7409893f5229.png)

I am thinking that this error is due to the fact I have the root CA in my truststore but not the intermediate CA -> does that make sense?

**Comment by mposolda** [comment] 2022-11-24 11:19
I am closing as this is tracked in the operator here https://github.com/keycloak/keycloak-operator/issues/586 . Please open the other issue in the "keycloak-operator" if you still seeing issues (Note that the fact you're using operator is very important "details", but it is completely missing in the steps-to-reproduce)

**Closed by mposolda** 2022-11-24 11:19 UTC
Labels: area/authentication, kind/bug, status/triage
