### ISSUE TITLE
Custom user provider new admin UI custom properties

### ISSUE THREAD

**Issue by taliano89** [keycloak/keycloak#13866] opened 2022-08-18 15:05 UTC
### Describe the bug

New admin UI starting from 19.0.0 does not show properties for custom user provider.

### Version

19.0.1

### Expected behavior

All additional properties for custom user store provider should be shown

### Actual behavior

New admin UI shows only provider name but no additional properties.

### How to Reproduce?

Upload jar with custom implementation of UserStorageProviderFactory. Go to admin UI under User Federation. Try to add custom provider, no additional properties are shown.

**Comment by ssilvert** [comment] 2022-08-18 18:04
Hi @taliano89.

This is fixed in the next release.  See https://github.com/keycloak/keycloak-ui/issues/3059.

**Comment by ssilvert** [comment] 2022-08-18 18:05
duplicate of https://github.com/keycloak/keycloak-ui/issues/3059

**Closed by ssilvert** 2022-08-18 18:04 UTC
Labels: kind/bug, status/triage
