### ISSUE TITLE
add trim to register form

### ISSUE THREAD

**Issue by yuliia-tinana** [keycloak/keycloak#17482] opened 2023-03-07 07:14 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

when a user tries to register and presses the space bar at the end of the line he cannot register because he got error invalid email. 

### Version

19.0.1-21.0.1

### Expected behavior

when user send form with register it should .trim() email and other fields

### Actual behavior

Invalid email address. - if add space in email

### How to Reproduce?

create realm, on register, go to register form, add information about new user, tap white-space in the end or in begin email address

**Comment by pedro-hos** [comment] 2023-03-07 21:36
@yuliia-tinana Thanks for pointing this out, however, I can't reproduce the issue! Have you used some specific version? I have tried to create a new user with white space on the email field, and keycloak accepted and applied trim.

**Comment by bastianccm** [comment] 2023-03-09 08:58
Hi, I can reproduce this with Keycloak 21.0.1 using the legacy (default) provider.
Spaces at the end of the username are preserved (which might also cause issues, maybe related to #11452), and the email validation fails (because spaces are not valid in emails. I'll have a look if I can provide a fix.

**Comment by pedro-hos** [comment] 2023-03-14 00:36
Thanks @bastianccm! Hi @mposolda may we close this one since seems duplicated by https://github.com/keycloak/keycloak/issues/11452?

**Comment by jsorah** [comment] 2023-05-18 20:02
Thanks for the report, however I will mark this as a duplicate of #11452

**Closed by jsorah** 2023-05-18 20:02 UTC
Labels: kind/bug, area/account/api, status/triage, team/other
