### ISSUE TITLE
Getting Keycloak exception with request 500 status code when generating a jwt

### ISSUE THREAD

**Issue by saksonikEgor** [keycloak/keycloak#28677] opened 2024-04-12 12:33 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I installed Keycloak locally, I did everything according to the [guide](https://www.baeldung.com/spring-boot-keycloak): I created a realm “test-realm”, in it there was a client “test-client” and a user “user1” with the password 123456. When I contact the endpoint to get a token (http://localhost:8180/realms/test-realm/protocol/openid-connect/token) I get an error:
```
2024-04-10 16:20:26,836 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "io.vertx.core.http.HttpServerRequest.authority()" is null
    at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.getRequestHost(VertxResteasyReactiveRequestContext.java:194)
    at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getAuthority(ResteasyReactiveRequestContext.java:481)
    at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getBaseUri(UriInfoImpl.java:131)
    at org.keycloak.urls.HostnameProvider.getScheme(HostnameProvider.java:51)
    at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.fromFrontEndUrl(DefaultHostnameProvider.java:181)
    at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.getScheme(DefaultHostnameProvider.java:90)
    at org.keycloak.models.KeycloakUriInfo.<init>(KeycloakUriInfo.java:51)
    at org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:78)
    at org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:85)
    at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.checkSsl(TokenEndpoint.java:156)
    at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:129)
    at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```
**Keycloak server response:**
```json
{
    "error": "unknown_error",
    "error_description": "For more on this error consult the server log at the debug level."
}
```
**When Keycloak starts, the server writes the following logs:**
```
2024-04-10 16:19:46,573 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2024-04-10 16:19:46,818 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-04-10 16:19:46,915 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-04-10 16:19:49,314 WARN  [io.quarkus.agroal.runtime.DataSources] (JPA Startup Thread) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2024-04-10 16:19:51,153 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-04-10 16:19:51,180 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_692571, Site name: null
2024-04-10 16:19:52,155 INFO  [io.quarkus] (main) Keycloak 24.0.2 on JVM (powered by Quarkus 3.8.3) started in 7.393s. Listening on: http://0.0.0.0:8180
2024-04-10 16:19:52,155 INFO  [io.quarkus] (main) Profile dev activated.
2024-04-10 16:19:52,155 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2024-04-10 16:19:52,161 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

I expected to receive a response from the server access_token and a refresh_token

### Actual behavior

Getting a server error with text: **java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "io.vertx.core.http.HttpServerRequest.authority()" is null at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.getRequestHost(VertxResteasyReactiveRequestContext.java:194)**

and 500 status code

### How to Reproduce?

1. Start Keycloak server
2. Create realm
3. Create client
4. Making post request to by path `http://localhost:<port>/realms/<realm_name>/protocol/openid-connect/token` and with headers 
```
client_id:<your_client_id>
username:<your_username>
password:<your_password>
grant_type:password
```

### Anything else?

Realm settings: [realm-export.json](https://github.com/keycloak/keycloak/files/14958720/realm-export.json)
My question in StackOverflow: [question](https://stackoverflow.com/questions/78308726/keycloak-exception-cannot-invoke-object-tostring-because-the-return-value-o/78310799#78310799)
My operating system is **macOS 11.7.10**

I also tried recreating the scopes and installing different versions of the Keycloak server and got the same error.

**Comment by saksonikEgor** [comment] 2024-04-12 13:49
> My feeling is the quarkus/resteasy is not getting your request URI OK. That error seems to indicate that the authority part of the request URL (authority is `[userinfo@]host[:port]`) is empty/null.
> 
> Are clients accessing through a reverse proxy or similar? Is it configured OK? Is it working accessing directly to the keycloak server? (I think the answer to this question is yes, because you can access for the admin console to configure it, so please check if there is something in front of the server.)

[As it turned out](https://stackoverflow.com/questions/78308726/keycloak-exception-cannot-invoke-object-tostring-because-the-return-value-o), the problem was with the postman. I didn't understand what exactly the problem was, but resetting Postman to default settings solved the problem.

**Comment by sschu** [comment] 2024-04-12 13:51
It probably did not send a host header. However, this should not cause a 500 error...

**Comment by saksonikEgor** [comment] 2024-04-12 14:06
**Here is the full request description from Postman**
```Json
{
  "name": "http://localhost:8180/realms/test-realm/protocol/openid-connect/token",
  "protocolProfileBehavior": {
    "disabledSystemHeaders": {
      "accept-encoding": true,
      "connection": true,
      "accept": true,
      "user-agent": true,
      "host": true,
      "content-length": true,
      "content-type": true
    }
  },
  "request": {
    "method": "POST",
    "header": [
      {
        "key": "grant_type",
        "value": "password",
        "type": "text",
        "disabled": true
      },
      {
        "key": "username",
        "value": "user1",
        "type": "text",
        "disabled": true
      },
      {
        "key": "password",
        "value": "123456",
        "type": "text",
        "disabled": true
      },
      {
        "key": "client_id",
        "value": "test-client",
        "type": "text",
        "disabled": true
      }
    ],
    "body": {
      "mode": "urlencoded",
      "urlencoded": [
        {
          "key": "grant_type",
          "value": "password",
          "type": "text"
        },
        {
          "key": "username",
          "value": "user2",
          "type": "text"
        },
        {
          "key": "password",
          "value": "123456",
          "type": "text"
        },
        {
          "key": "client_id",
          "value": "test-client",
          "type": "text"
        }
      ]
    },
    "url": {
      "raw": "http://localhost:8180/realms/test-realm/protocol/openid-connect/token",
      "protocol": "http",
      "host": [
        "localhost"
      ],
      "port": "8180",
      "path": [
        "realms",
        "test-realm",
        "protocol",
        "openid-connect",
        "token"
      ]
    }
  },
  "response": []
}
```

**Comment by sschu** [comment] 2024-04-12 15:18
Yeah, this looks wrong. All the standard headers seem to be disabled. I will go ahead and close this as not a bug.

**Closed** 2024-04-12 15:18 UTC
Labels: area/authentication, kind/bug, team/core-clients

**Comment by rmartinc** [comment] 2024-04-15 07:11
@saksonikEgor As @sschu suggested I think the issue is that there is no host header present in the request. I can reproduce the same exception doing a simple curl like the following:

```
curl --http1.0 -H "Host:" -v http://localhost:8080/realms/master/protocol/openid-connect/token --data-raw ""
```

The initial NPE is thrown in quarkus [here](https://github.com/quarkusio/quarkus/blob/3.8.3/independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java#L194). But, in general, there are several inconsistencies in how the vertx projects manage the empty host (vert.x and web-vertx) that generate NPEs in other places when no host header is sent. So I'm not sure where to send a PR to fix this. For the moment I'm asking in [the vert.x group](https://groups.google.com/g/vertx/c/OBffuFH-WZU) about the discrepancies I detected, to see what they think.

But anyway, I don't think this is very important. The host header is compulsory for http 1.1+ and this won't affect a lot of people.
