### ISSUE TITLE
Keycloak 24.0.3 not starting in production in rolling update mode

### ISSUE THREAD

**Issue by nsauter** [keycloak/keycloak#28944] opened 2024-04-20 11:04 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I am trying to install Keycloak 24.0.3 and basically just installed openjdk-17, moved the unzipped keycloak.zip to /opt and tried to start with bin/kc.sh start but i get the following errors all the time:

```
2024-04-20 11:01:16,508 ERROR [org.infinispan.CLUSTER] (jgroups-7,keycloakv2-48994) ISPN000475: Error processing response for request 2 from keycloak-59258: java.io.IOException: Unknown type: 28
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:720)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:269)
        at org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:250)
        at org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:98)
        at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:85)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
        at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1562)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1471)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1663)
        at org.jgroups.JChannel.up(JChannel.java:734)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:936)
        at org.jgroups.protocols.FRAG2.up(FRAG2.java:139)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:846)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:226)
        at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1086)
        at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:825)
        at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:807)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:456)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:680)
        at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
        at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:189)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
        at org.jgroups.protocols.Discovery.up(Discovery.java:294)
        at org.jgroups.stack.Protocol.up(Protocol.java:340)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1184)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:107)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-04-20 10:55:32,391 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-04-20 10:55:32,391 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
```

Starting with start-dev works well and Server is available via WebUI. Am i doing something wrong?

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Server starts up just like start-dev does

### Actual behavior

kc.sh start is not successfully starting the server whil start-dev does

### How to Reproduce?

I stated my steps above. I literally just downloaded the latest zip release, unzipped it to /opt/keycloak and started the server after i did a bin/kc.sh build.

**Comment by nsauter** [comment] 2024-04-20 13:22
Addition: Thia happens with every 24 Version. Version 23 works as espected.

**Comment by ahus1** [comment] 2024-04-21 15:31
The error message indicates you're trying a rolling update with an old version of Keycloak already running, or at least in the same network where there is already another Keycloak which is listening to the JGroups communication. 

This is not supported, you'll need to first shutdown the old instances of Keycloak. 

This is a duplicate of #28617

**Closed** 2024-04-21 15:31 UTC
Labels: kind/bug, area/core, team/core-shared

**Comment by nsauter** [comment] 2024-04-22 06:27
Is there a Doc in which i would have found this? Why does it work with Version 23? Is there a way to make that error clearer for what i going on? Java exceptions are always a bit of pain in the butt so it would be cool to have a clear error message or something like that.
