### ISSUE TITLE
Enabling LDAP provider breaks REST API

### ISSUE THREAD

**Issue by fjf2002** [keycloak/keycloak#24138] opened 2023-10-19 08:58 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/api

### Describe the bug

Having my LDAP user federation enabled/disabled results in quite different behaviour using the GET /admin/realms/{realm}/users endpoint.
Too many federated users are returned.

In detail:
* I do a curl request: something like GET "$KEYCLOAK_SERVER/admin/realms/$MYREALM/users?exact=true&q=enabled:false%20myattr:myvalue"
* When my user federation if off, everything works as expected.
* When my user federation is activated, additional federated users are added to the result set. These added users ...
  * are enabled (i. e. clearly violated the q filter parameter),
  * do not have the custon myattr attribute set (i. e. clearly violated the myattr filter parameter),
  * do exist in the user_entity database table (LDAP Editmode=UNSYNCED).

Please note that not ALL LDAP users are returned, even not all LDAP users that currently exist in the user_entity database table are returned.

I think we agree some wrong subset of all ldap users is returned. However it is very unclear to me what (arbitrary?) subset of LDAP users is returned here.

By the way, my individual problem would be solved if I could filter out the federated users. However this bug should be solved for federated users altogether.

### Version

22.0.1

### Expected behavior

Returned federated users shall match the filter criteria.

### Actual behavior

Some (but not all) federated users are returned, not matching the filter criteria.

### How to Reproduce?

Use curl to perform a GET request, something like 

"$KEYCLOAK_SERVER/admin/realms/$MYREALM/users?exact=true&q=enabled:false%20myattr:myvalue"

**Comment by fjf2002** [comment] 2023-10-19 09:49
It seems to be an implication of my other issue, https://github.com/keycloak/keycloak/issues/24141 .
When the username in keycloak differs from the LDAP username (see the ticket), it occurs; otherwise not.

**Comment by martin-kanis** [comment] 2023-11-08 14:27
@rmartinc Can you please check whether this is connected to the https://github.com/keycloak/keycloak/issues/24141 as you already reproduced the later?

**Comment by rmartinc** [comment] 2023-11-08 15:42
I think this issue is more a duplicate of https://github.com/keycloak/keycloak/issues/22578. The ldap provider just searches using a [defined set of attributes](https://github.com/keycloak/keycloak/blob/22.0.5/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java#L351-L361). So you cannot search using any attribute (like  `enabled` or `myattr`). Recently there was a change, previously no results were returned when using non-manged attrs and now all users are returned (not a fan of this but it's like it is now).

@fjf2002 Probably when https://github.com/keycloak/keycloak/issues/24141 is fixed this is also fixed for you (I have #24141 more or less done but I'm waiting to other changes in ldap to be merged to send the PR because I think it will conflict). Because you will use the imported data in the DB to do the search. Now you have the problem that the link is done via username and the user is also shown in the ldap search because it detects the user as a different one. So it's more or less a manifestation of the same issue plus the fact that search by attributes is not implemented in ldap (or only implemented for some of them).

@martin-kanis We can improve the searchLDAPByAttributes using any defined attribute in the ldp provider. But I think that is more an enhancement than a bug.

**Comment by fjf2002** [comment] 2023-11-08 16:48
@rmartinc: Thanks for your investigation :-)

**Comment by martin-kanis** [comment] 2024-01-10 12:35
Closing this as https://github.com/keycloak/keycloak/issues/24141 is fixed. Feel free to try with next nightly build or the upcoming 24 release.

**Closed by martin-kanis** 2024-01-10 12:35 UTC
Labels: kind/bug, area/ldap, team/store, status/triage
