### ISSUE TITLE
Declarative User Profile attribute localization working for self registration page but not admin console create user page

### ISSUE THREAD

**Issue by JSCorpo** [keycloak/keycloak#19611] opened 2023-04-10 09:04 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Declarative User Profile attribute localization working for self registration page but not admin console create user page

The localization is configured for newly created user profile attribute
![localization](https://user-images.githubusercontent.com/127390108/230869742-bd82d614-d0ca-42d9-b6ec-a374ed7d1f01.jpg)

The localization is displayed at self registration page
![self registration page attribute](https://user-images.githubusercontent.com/127390108/230869797-eec6d70d-bbbb-48b3-8ca2-e39559a90ca0.jpg)

But the localization is not displayed at admin console create user page
![admin console create user does not display localization](https://user-images.githubusercontent.com/127390108/230869882-3d0cf1d6-50bf-48a4-a280-76a6079931e3.jpg)

### Version

21.0.1

### Expected behavior

The admin console create user page should display the localization display name that is configured in the realm settings

### Actual behavior

The localization is not displayed at admin console create user page
![admin console create user does not display localization](https://user-images.githubusercontent.com/127390108/230870101-ba288b43-8f47-4473-905c-17cb0295cbcd.jpg)

### How to Reproduce?

Go to realm settings
go to localization tab
enable Internationalization 
create new message bundle
go to user profile table
create new user profile attribute
configure attribute display name with new localization message created earlier
go to create user page

**Comment by ssilvert** [comment] 2023-04-10 13:27
I think this might be fixed by https://github.com/keycloak/keycloak/pull/17076.

Once that is merged, we can take another look and see.

**Comment by jonkoops** [comment] 2023-05-23 17:01
Closing this issue due to lack of response, feel free to get back to us if this is still a problem.

**Comment by JSCorpo** [comment] 2023-05-24 01:26
@ssilvert I have tested, the localization is working for admin console, but it is displaying the localization key instead of the value

Localization configuration
![image](https://github.com/keycloak/keycloak/assets/127390108/1cc62b69-a4f0-4c07-8814-b28b0446e92a)
![image](https://github.com/keycloak/keycloak/assets/127390108/9fcec9af-183a-41af-a9b3-7c5ffd58c4ea)

Admin console displaying localization key instead of value
![image](https://github.com/keycloak/keycloak/assets/127390108/2604ad53-a3b0-4e15-9c52-4555e98f9419)

Self registration displaying localization value
![image](https://github.com/keycloak/keycloak/assets/127390108/f177f836-6b1f-4d7b-bf8d-98181b7e39bc)

**Comment by ssilvert** [comment] 2023-05-24 18:57
Thanks @JSCorpo.  We will fix it.

**Comment by ssilvert** [comment] 2023-05-24 20:29
@JSCorpo This is working as designed in the latest build, but there is a little trick.  The message key needs to include the context.  In this case, the context is `users`.  So in the message bundle, your key should be `users:TestLocal`.  Then for your testattribute in User Profile, set the display name to `${users:TestLocal}`

This is brand new functionality and we need to document it somewhere.

Please give it a try and let me know if that fixes it for you.

**Comment by JSCorpo** [comment] 2023-05-25 01:33
Hi @ssilvert, I have tested with users:TestLocal and ${users:TestLocal}, the outcome is the same

Localization Configuration:
![image](https://github.com/keycloak/keycloak/assets/127390108/ffd94105-8395-4215-afdc-e53147931238)
![image](https://github.com/keycloak/keycloak/assets/127390108/01d9e4b3-7d2f-4401-a376-e85ad6e81d09)

Admin console create user page:
![image](https://github.com/keycloak/keycloak/assets/127390108/0fb088d2-7d11-4d87-8c3a-8f8cb4afe2fc)

Self Registration page:
![image](https://github.com/keycloak/keycloak/assets/127390108/06aa7582-01da-4f3a-9913-91f5fdb07893)

**Comment by jonkoops** [comment] 2023-05-25 10:22
@ssilvert I am not sure, but the functionality you are referring to will be released in [Keycloak 22](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/22_0_0.adoc#changes-to-custom-admin-console-messages). It should only apply to messages translated in the React code, so only the Admin Console.

Or am I missing something here?

**Comment by ssilvert** [comment] 2023-05-25 12:08
@jonkoops It works for the registration page and admin console.  But I just found that it does not work for account console.  We need to fix it.

@JSCorpo You need to be running on a nightly build for this to work.

**Comment by ssilvert** [comment] 2023-05-25 12:16
Another side note.  If you want to override one of the built-in attributes from the Realm --> Localization tab, you need to include the `users` context in the key.  For instance, to override the email key, you would specify `users:email`.

**Comment by jonkoops** [comment] 2023-05-25 14:31
> We need to fix account console v3.

Yeah, we'll need to implement the same there.

**Comment by JSCorpo** [comment] 2023-05-26 01:54
@ssilvert I am running on the nightly build from a few days ago, 24th Jun, is this the version with the fix?

**Comment by ssilvert** [comment] 2023-05-26 13:47
@JSCorpo Yes, that one should work.  It's working for me.

**Comment by JSCorpo** [comment] 2023-05-29 02:52
@ssilvert, I downloaded the latest nightly build today, 29/05/2023, but it is still not working

**Comment by ssilvert** [comment] 2023-05-30 19:37
It's definitely working for me.  Here is how I set it up:

Realm settings -> User Profile -> Edit Attirbute
<img width="618" alt="userprofileattributedisplaynam" src="https://github.com/keycloak/keycloak/assets/507202/d4ceed7d-9738-46b2-94dc-bde52b1dd13d">

Realm settings -> Localization
<img width="669" alt="localizationofdisplayname" src="https://github.com/keycloak/keycloak/assets/507202/387a621d-acda-498f-8f04-5188182a1721">

Users -> User details
<img width="542" alt="UserSettings" src="https://github.com/keycloak/keycloak/assets/507202/937228c5-92b0-4d70-b0e8-b513a6d62f24">

**Comment by JSCorpo** [comment] 2023-06-05 02:42
Hi @ssilvert, my version is still displaying the key instead of the value. How do you download the nightly release for testing? maybe my steps to downloading the nightly release is incorrect.

**Comment by JSCorpo** [comment] 2023-06-06 02:44
@ssilvert Is this the zip to download?
![image](https://github.com/keycloak/keycloak/assets/127390108/1fde685e-2a36-40e9-bceb-240cc9c37d17)

**Comment by ssilvert** [comment] 2023-06-06 11:00
@JSCorpo Yes.

**Closed** 2023-06-30 19:03 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui
