### ISSUE TITLE
Incorrect flow name displayed when bound

### ISSUE THREAD

**Issue by mrpatrickpilch** [keycloak/keycloak#16198] opened 2022-12-29 22:41 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

The "Used by" column in the *Authentication* page used to / should display the name of the default flow it is bound to like "Registration flow" or "Browser flow". 

In 20.0.2, instead of displaying the flow it's bound to, it just displays the flow's own name.

![image](https://user-images.githubusercontent.com/88005594/210017236-3ed37d27-a35c-4f9a-835d-c2dbfce3d496.png)

### Version

20.0.2

### Expected behavior

If I create a new flow named "broken" and bind it to "Direct grant flow", I would expect it to be listed with "Used by" stating "Direct grant"

![image](https://user-images.githubusercontent.com/88005594/210017572-bff8105b-7346-4c7a-8cde-b331f1590309.png)

![image](https://user-images.githubusercontent.com/88005594/210017505-bf9d856d-8fbf-48af-a24e-9b1637b51177.png)

### Actual behavior

When creating a fresh empty flow named "broken" and binding it to "Direct grant flow", the following is displayed in the Authentication page -> Flows tab listing:

![image](https://user-images.githubusercontent.com/88005594/210017689-9d6b1cc4-0808-4eb3-8441-22f719e864ae.png)

### How to Reproduce?

1. Go to Authentication page -> Flows tab.
2. Execute "Create flow" with distinct name like "goof". Flow type does not matter.
3. In the "goof" flow details page, click the top right "Action" select dropdown and choose "Bind flow"
4. In the "Bind flow" dialog that pops up, choose "Direct grant flow" and click "Save".
5. Go back to the Authentication page -> Flows Tab and observe the listing for "goof"

**Comment by mposolda** [comment] 2023-03-06 13:27
I am changing to "area/admin/ui" as it looks like admin console issue and I can confirm it with the latest version.

In the "Used By" table, I see the name of the flow itself. I agree that it will be better to see instead the value it is bind to (EG. pretty much same values, which are shown when I click on `Bind flow` button on the right side. So something like `Browser flow`, `Registration flow`, `Direct grant flow` etc. Maybe the word `flow` can be omited?

**Comment by edewit** [comment] 2023-03-16 09:46
this has been fixed with 6da66d845603aa84b7d251fa809fa620fc242456

**Closed by edewit** 2023-03-16 09:46 UTC
Labels: kind/bug, impact/medium, area/admin/ui, team/ui
