### ISSUE TITLE
Do not ignore proxy settings when calling external Identity Provider

### ISSUE THREAD

**Issue by alex-vg** [keycloak/keycloak#13693] opened 2022-08-10 09:51 UTC
### Description

Currently there is no way of calling IDPs which are only reachable behind a corporate proxy.
I would expect that Keycloak respects the HTTP_PROXY env or at least -Dhttp.proxyHost and -Dhttp.proxyPort settings (including NO_PROXY).
It would be even more nice to have a switch on the IDP-Settings page to ignore or repect the proxy settings, or even set the proxy settings.

### Motivation

Using Keycloak behind a corporate firewall and proxy, this is mandatory.

**Comment by dpulrichth** [comment] 2023-04-25 19:13
I cannot confirm that setting HTTP_PROXY, HTTPS_PROXY and NO_PROXY does not work as intended. I can access an external IDP through a proxy server using the environment variables using Keycloak 21.0.2.

However, JRE Arguments passed to Keycloak don't seem to work or are ignored when making the call to the external IDP. It would be good if those Arguments worked so the Environment Variables don't have to be set globally inside a container to so they cannot be used by other tools.

**Comment by mposolda** [comment] 2023-04-26 15:03
We have documentation about http proxy here: https://www.keycloak.org/server/outgoinghttp#_proxy_mappings_for_outgoing_http_requests . I am closing this, please re-open if you are still seeing it in the newest Keycloak 21.1.1 version.

**Closed by mposolda** 2023-04-26 15:03 UTC
Labels: kind/enhancement, area/core, help wanted, team/core

**Comment by hjain1407** [comment] 2024-10-15 06:05
how do we set these proxy variables for operator based installation .
