### ISSUE TITLE
Account Console route not found

### ISSUE THREAD

**Issue by bilias** [keycloak/keycloak#26450] opened 2024-01-24 12:07 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The Account Console gives me:
Page not found
/iss=https%3A%2F%2Fsso.example.com%2Frealms%2Fmaster is not a valid route.

This happens on all realms. I don't have any error in the logs.
Similar to #22486

Apart from that, all account pages work (Personal Info, Account Security, Applications).
But if I click Applications -> Account Console
I again get the Page not found, not a valid route

### Version

23.0.4

### Expected behavior

No error and show Personal info

### Actual behavior

Page not found
/iss=https%3A%2F%2Fsso.example.com%2Frealms%2Fmaster is not a valid route.

### How to Reproduce?

I've tried a clean 23.0.4.
I've copied configuration from production. Just changed the port and the hostname/hostname-admin
I even copied my local theme. Couldn't reproduce it....

### Anything else?

Would like some info on how to debug it. Running with --log-level=DEBUG gives a log of output. Even with this I couldn't spot anything there.

**Comment by jonkoops** [comment] 2024-01-24 15:31
Possible duplicate of #26405

**Comment by LeoQuote** [comment] 2024-01-27 14:20
Hmm, cannot reproduce on keycloak 23.0.4, you can open the network tools in browser, inspect every 302 response to see there's anything wrong.

Normally, the 302 location would be like: 

```
Location | https://keycloak.example.com/auth/admin/master/console/#state=f60d1189-e796-4868-b5b3-e9935336916b&session_state=2a98554d-d33a-4210-8386-05f6ef80134a&iss=https%3A%2F%2Fkeycloak.example.com%2Fauth%2Frealms%2Fmaster&code=ad981bc8-27
```

please notice `/master/console/#state=` there should be a `#` between path and arguments

Shortly after that, keycloak JS adaptor would try to extract info and get token from these arguments, and finally get rid of them.

See these codes for details https://github.com/keycloak/keycloak/blob/0178a91f668ce15badac20f432c158f9a971ac1d/js/libs/keycloak-js/src/keycloak.js#L1073

If you see a strange 302 response, it could be keycloak's problem, if not, there could be something wrong with the keycloak JS adaptor you're using.

Since you cannot reproduce the bug even with a clean 23.0.4, not to mention the nightly build which you haven't tried, there's high probability that keycloak has no responsibility for this abnormal situation, you should check something else, like load balancer or even browser plugins ...

**Comment by jonkoops** [comment] 2024-01-28 11:47
I am going to go ahead and close this issue, I would recommend running the latest version of Keycloak and Keycloak JS. Unfortunately if we cannot reproduce an issue we are not able to identify and fix it. If you do find a way to reproduce this issue reliably, do file a new report.

**Closed by jonkoops** 2024-01-28 11:47 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui

**Comment by bilias** [comment] 2024-01-29 08:35
Well, I was using the latest stable 23.0.4
Anyway after upgrading today to 23.0.5 and empty cache/ data/ folders problem disappeared.
