### ISSUE TITLE
Mail verification isn't working for multiple accounts in one session (only on auto login by clicking the verification mail, not by logging in with the credentials)

### ISSUE THREAD

**Issue by kerkmann** [keycloak/keycloak#14776] opened 2022-10-06 13:32 UTC
### Describe the bug

If a user is registering multiple accounts (different accounts with different usernames/mails etc.) at the same time, they try to confirm the verification for all their accounts.

When the user is confirming the first mail, he is automatically logged in with these account (for example, account (A)).
But now he's unable to confirm the second account (B).
Because keycloak is accepting the verification mail, but giving an error response "the user is already logged in".

The strange thing about that is, if a user (account (A)) is logged in with their credentials*, he can confirm the mail for the second account (B).
*(by typing in their credentials and not automatically logged in through the verification process)

All accounts are independent and have correlation.

### Version

16 - 19.0.3

### Expected behavior

Both behaviors should be equal.

If a user is confirming their account (A) he should be logged in automatically (works right now).
And he should be able to confirm other account (B) by clicking the verification mail.

### Actual behavior

So, the behaviors for confirming a mail it's different, based on the origin.
If the user is logged in by using the login page (using their credentials, account (A)), verifying another account (B) is possible.
If the user is logged in automatically (using the confirmation mail from account (A)), verifying another account (B) is NOT possible.

### How to Reproduce?

You need to register two accounts and verify them in a sequence:
- Enable account registration and mail verification for realm
- Register a new account (A)
- Register a new account (B)
- Click on the verification mail for account (A)
- Click on the verification mail for account (B)
- See that account (B) can not be verified because "the user is already logged in"

### Anything else?

The verification process itself is working.
It's only a problem that a user needs to log out to be able to confirm other accounts than itself.
And the weird thing by that is, that there are different behaviors for the same process.

With account (A) and account (B) I mean entirely different accounts, different username, different mail etc.

**Comment by pedroigor** [comment] 2023-12-18 23:12
I'm able to reproduce the error in the behavior and for me, following the verification link when the user is authenticated using his credentials also ends up in the same behavior.

@kerkmann Does it make sense at all to allow a user to verify a different e-mail than his own in a session that is not really for the same user?

For me, the message saying that the user is already logged in is more appropriate because you should not be able to verify an e-mail for a different account other than yours. Going even further, perhaps we should also invalidate the link and fire an event when this happens.

Perhaps an improvement would be to change the message to something like `You can not confirm the e-mail for another account` or something similar.

@mposolda I would close this one and perhaps work on improvements in a specific and separate issue.

**Comment by mposolda** [comment] 2023-12-19 16:23
Yes, this is tricky because we currently don't support something like Google - having multiple accounts of the same realm in the same browser. And supporting it would be very non-trivial...

At the same time, the current behaviour is likely not very ideal, but I am not sure if we can easily improve it? Some possibilities to how we can handle when we detect, that actionToken session (which is the authenticationSession of the 2nd user from the email) belongs to account `B`, but current browser SSO session already has account `A` authenticated:

1) Logout user `A` from this browser. Which means that account `B` email can be successfully verified and new SSO session of user `B` can be established in this browser afterwards
2)  Don't logout user `A` automatically, but just display some better message with the link to logout current browser session. In other words, user will need to explicitly confirm if he wants to logout before proceed further. If he confirms, we can logout user `A` and then continue with email verification of user `B` and then possibly login new SSO session of user `B` . So this is same like option (1), but with confirmation screen
3) Don't logout user `A`, but just allow account `B` to verify his email. So then we will be able to display some message like `Your email account-b-email@mail.com was verified, but you are already authenticated in this browser as different user` .
4) Do the same like we do today, but just slightly update the error message to be more clear?
5) Any other option?

It seems like (2) might be best from usability perspective, but also probably most work...

**Comment by pedroigor** [comment] 2023-12-19 18:42
For now, I would start with  (4) as it is the first step towards (2). It is simpler and enough to give a better reason why e-mail verification is not possible.

It would be nice to enable multiple accounts (and an account selector) within the same browser session but it should be done carefully. For now safer is to just do what we have today but with a better message, I think.

However, this code https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/LoginActionsServiceChecks.java#L130 does not provide a consistent behavior in cases where the user is already authenticated and the server is about to process an action token (e.g.: verifying email). If the user does not have required actions it will show the `already logged in` page. However, if the user has required actions it will continue with the flow.

IMO, we should either prevent or allow verifying the email from another account if the user is already authenticated. I would prefer preventing verification because of the reasons you mentioned.

**Comment by mposolda** [comment] 2023-12-19 18:48
> IMO, we should either prevent or allow verifying the email from another account if the user is already authenticated. I would prefer preventing verification because of the reasons you mentioned.

+1

**Closed** 2024-01-05 11:45 UTC
Labels: area/authentication, kind/bug, team/core
