### ISSUE TITLE
Keycloak admin page is not loading https status 204

### ISSUE THREAD

**Issue by harikant-lftt** [keycloak/keycloak#19821] opened 2023-04-19 16:24 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/cli

### Describe the bug

I am using quay.io/keycloak/keycloak:21.1 below is my docker compose file

version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: 'keycloak'
    deploy:
      replicas: 1
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${POSTGRES_INFRA_DB_HOST}/${KEYCLOAK_DB_DATABASE}?&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: dev-example.net
        
      KC_HOSTNAME_PORT: 443
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HTTP_ENABLED: true
       
    command:
      - start
      - "--auto-build"
    ports:
      - 80:8080
      - 443:8443
    networks:
      - alf-overlay-nw
     
networks:
  alf-overlay-nw:
    external: true

I am unable open admin login page  
it load till <host>/realms/master/protocol/openid-connect/login-status-iframe.html/init?client_id= with status  204

After that it keep showing loading  icons

My all other REST API is working ok

### Version

21.1

### Expected behavior

Key clock admin page should load

### Actual behavior

Key clock admin page not loading

### How to Reproduce?

Hit the main host of server  like https://dev-example.net after that click administration console button

**Comment by jonkoops** [comment] 2023-04-19 16:30
Are there any visible errors being logged to the browser console?

**Comment by harikant-lftt** [comment] 2023-04-20 04:24
nothing as such

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/128361106/233257758-6f361574-db8e-4ae9-9420-e79d436c8644.png">

**Comment by jonkoops** [comment] 2023-04-20 12:48
Did you check under the 'Console' tab as well?

**Comment by harikant-lftt** [comment] 2023-04-20 12:50
nothing inside console tab as well

**Comment by jonkoops** [comment] 2023-04-20 12:53
Very strange, I suspect this is a UI issue rather than a CLI issue. I'll relabel this for now as we try to reproduce this.

**Comment by harikant-lftt** [comment] 2023-04-26 02:50
@jonkoops 
was there any luck here, am I doing some mistake in configuration

**Comment by jonkoops** [comment] 2023-04-26 08:01
I haven't had the time to investigate this, but I think there is probably some missing configuration.

**Comment by jonkoops** [comment] 2023-04-26 08:02
This is a possible duplicate of #14666. @ssilvert WDYT?

**Comment by ssilvert** [comment] 2023-04-27 01:27
@jonkoops I agree.  I'm going to add this issue to the list and close it.

@harikant-lftt You might want to look at #14666 for more info.

**Closed by ssilvert** 2023-04-27 01:27 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by jonkoops** [comment] 2023-05-02 10:00
Duplicate of #14666

**Comment by blalasaadri** [comment] 2024-06-18 13:39
> **[EDIT]** Resolved! I had to specify `hostname-admin-url` and `hostname-url` **without the port**!
> 
> Do not follow the documentation! https://www.keycloak.org/server/all-config
> 
> > hostname-url
> > Set the base URL for frontend URLs, **including** scheme, host, **port** and path.
> 
> Adding the port to the URL, when using default ports (80 or 443), breaks KeyCloak.

This really helped! For me, we couldn't specify the `hostname-url` or `hostname-admin-url` because we're loading those dynamically, but removing the `hostname-port` (which was set to 443) did the trick. 🙂
