### ISSUE TITLE
JPARealmProvider based searchClientsByAttributes stream response can contain nulls

### ISSUE THREAD

**Issue by jsorah** [keycloak/keycloak#14878] opened 2022-10-13 13:40 UTC
### Describe the bug

While doing some load testing of a migration from MariaDB to Postgres for Keycloak, we ran into an interesting race condition within our custom extensions.

It involves a call to a core API for "searchClientsByAttributes" [1] - during times of high volatility (ex: create/delete many clients associated with a specific attribute) - some implementations may return a client ID list containing a specific client, and before that list is consumed fully, the client is deleted - resulting in a subsequent call to "getClientById" [2] that returns a null value [3] from within the searchClientsByAttributes implementation itself.

This poses a usability issue from the developer perspective.  
- Developers must be aware that the stream _could_ contain nulls, which in this case I do not think is obvious.  And this scenario could change per underlying implementation, even per database vendor.
- Developers must know to protect against the use case every time they call this Stream based API (using something such as .filter(Objects::nonNull)

It seems baking the filter into the searchClientsByAttributes implementations would make sense to keep the responsibility of null filtering to within the underlying code.  It does create some minor implications - such as possibly returning a list shorter than what was requested, while still having more clients that could be queried for.

Example - 150 clients tagged with some attribute - request 50 of them, one of those 50 is deleted (meets the race condition laid out above), filter any nulls - now only 49 clients are returned, while there are still 100 more remaining.

I only looked at this specific method within the code base, but I am curious if there are more places where this pattern might be applicable - where the stream could theoretically have random "null" entries injected due to similar conditions and should be filtered.

[1] 
https://github.com/keycloak/keycloak/blob/f80a8fbed0940f28e8a23ebcdc5469c7299c0457/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L765-L796

[2]
https://github.com/keycloak/keycloak/blob/f80a8fbed0940f28e8a23ebcdc5469c7299c0457/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L795

[3] 
https://github.com/keycloak/keycloak/blob/f80a8fbed0940f28e8a23ebcdc5469c7299c0457/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L729-L739

### Version

18

### Expected behavior

Nulls are not present in stream response

### Actual behavior

Nulls are present in stream response

### How to Reproduce?

Backing DB - Postgres

Need an API interface exposed from Keycloak that has the ability to create clients:
- Creation (underlying implementation tags with specific attribute)
- Deletion
- List clients by the specific attribute (using `searchClientsByAttributes` method)

The client attribute needs to be searchable.

A test then can be written against such interface that creates, deletes, and lists clients at random and at a high frequency.

**Comment by hmlnarik** [comment] 2022-10-13 14:56
@jsorah Thank you for reporting the bug.

What is the used transaction isolation level?

> It seems baking the filter into the searchClientsByAttributes implementations would make sense to keep the responsibility of null filtering to within the underlying code. It does create some minor implications - such as possibly returning a list shorter than what was requested, while still having more clients that could be queried for.

I agree and a PR would be more than welcome.

> I only looked at this specific method within the code base, but I am curious if there are more places where this pattern might be applicable - where the stream could theoretically have random "null" entries injected due to similar conditions and should be filtered.

This could indeed happen, and seems to be the case for a few other places in `JpaRealmProvider` (search by `map\(.*get.*ById`) which should all be guarded by the non-null filter.

**Comment by jsorah** [comment] 2022-10-13 15:13
> What is the used transaction isolation level?

We're using read committed

> This could indeed happen, and seems to be the case for a few other places in JpaRealmProvider (search by map\(.*get.*ById) which should all be guarded by the non-null filter.

Noted, I see this likely impacts the recently added searchGroupByAttributes APIs as well.  I'll chat with some folks about collaborating on a PR here.

**Comment by hmlnarik** [comment] 2022-10-13 18:23
> > What is the used transaction isolation level?
> 
> We're using read committed

That makes sense. For nulls not to happen, you would need at least repeatable read.

> > This could indeed happen, and seems to be the case for a few other places in JpaRealmProvider (search by map(.*get.*ById) which should all be guarded by the non-null filter.
> 
> Noted, I see this likely impacts the recently added searchGroupByAttributes APIs as well. I'll chat with some folks about collaborating on a PR here.

Thanks!

**Comment by nagarjun-repala** [comment] 2023-02-13 02:41
Hi team, can I work on this issue?

**Comment by hmlnarik** [comment] 2023-02-14 14:58
@nagarjun-repala Thank you for the offer. Please consider this issue assigned to you. Feel free to submit a PR.

**Comment by nagarjun-repala** [comment] 2023-03-25 11:48
Hi @hmlnarik @jsorah 

I tried creating a client using Keycloak REST API documentation, but I don't understand how I search clients using attributes can you please explain to me what are the attributes for the client(If possible help me to create a client with specific attributes)? When I'm looking into GET /{realm}/clients API, how do I pass attributes to this API? Please refer to the below screenshot and the link for REST API Documentation [Link](https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_clients_resource) I'm not able to invoke the searchClientsByAttributes method from the REST API documentation. Feel free to ask more questions If you want more details from me. Correct me If I miss anything. Please help me how to reproduce the issue. Thank you.
![Screenshot from 2023-03-25 17-05-00](https://user-images.githubusercontent.com/61962408/227715098-4c6e12c5-aa9a-4d41-b0f6-9450458d1fa3.png)

**Closed** 2024-06-13 00:06 UTC
Labels: kind/bug, impact/low, area/storage, good first issue, help wanted, team/core-clients, priority/low, status/auto-expire, status/auto-bump, status/expired-by-bot
