### ISSUE TITLE
Cannot find symbol class DelegateCreator

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#9208] opened 2021-12-17 07:42 UTC
### Describe the bug

Not able to run any tests from IntelliJ due to missing classes in org.keycloak.models.map.common.DeepCloner.*. 

I have to remove map modules from model/pom.xml to be able to run any tests.

![image](https://user-images.githubusercontent.com/2271511/146507851-1097d84b-f419-4d31-b477-3e90396a7c24.png)

Not sure if this means I have to do a Maven build manually before using IntelliJ, but if that's the case that's not a good solution.

### Version

main

### Expected behavior

KeycloakServer or tests run as expected from IntelliJ without requiring a separate Maven build.

### Actual behavior

Build error in IntelliJ (see screenshot above)

### How to Reproduce?

Not confirmed, but I would think this would do it:

* mvn clean
* Open IntelliJ
* Run KeycloakServer, or any tests from the testsuite

**Comment by mhajas** [comment] 2022-01-06 09:50
I came across a similar issue in IntelliJ as well. @stianst Can you try to invalidate caches and restart? If I remember correctly it resolved this issue for me. I would say this is not a problem in our code, as it works with `mvn` all the time. Maybe Intellij is doing compilation in some wrong order and doesn't generate classes correctly.

**Comment by hmlnarik** [comment] 2022-10-21 11:17
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of Keycloak, feel free to reopen and provide details to why it is still valid.

**Closed by hmlnarik** 2022-10-21 11:17 UTC
Labels: kind/bug, area/storage, status/triage
