### ISSUE TITLE
Client my-client has browser flow override, but this flow does not exist

### ISSUE THREAD

**Issue by ddl-olsonJD** [keycloak/keycloak#20193] opened 2023-05-05 17:41 UTC
### Description

Currently, when a user deletes a flow that is used as part of a browser flow, the link within the browser flow still remains which leads to `org.keycloak.models.ModelException`. Can we consider either a cascade update, or ensure that the flow is not being used prior to deleting it? as to avoid causing an internal error?

### Motivation

to ensure proper login flow is followed

**Comment by graziang** [comment] 2024-06-25 07:36
duplicate of #30706

**Closed by graziang** 2024-06-25 07:36 UTC
Labels: kind/enhancement, status/triage
