### ISSUE TITLE
New Public Key generated by a client app after initial authentication results in client assertion validation failure

### ISSUE THREAD

**Issue by javacup** [keycloak/keycloak#14263] opened 2022-09-07 18:31 UTC
### Describe the bug

A confidential client was configured in keycloak with JWKS URL enabled with a functioning URL endpoint to download the public key to authenticate the client. 
![Screen Shot 2022-09-07 at 10 32 37 AM](https://user-images.githubusercontent.com/397774/188942515-31e3fcc5-c437-4f65-8ec8-fb3a59ed4338.png)

The initial authentication downloaded the public key as we were able to monitor the logs in the client application as shown below.

2022-09-07 10:31:42.427  INFO 7811 --- [nio-8100-exec-2] c.g.b.auth.controller.BackEndController  : In /.well-known/back_end_auth_client_jwks.json

According to the help text in keycloak in Realm -> Clients -> Keys -> Use JWKS URL 
".. This allows great flexibility because new keys will be always re-downloaded again when client generates new keypair."
![Screen Shot 2022-09-07 at 11 31 58 AM](https://user-images.githubusercontent.com/397774/188952408-a666fa8d-3100-4bb0-bea1-3f9c085da189.png)

In this use case, the client app was able to authenticate using a JWT client assertion mechanism and received an access token. However, when the client re-generated a new public key, the client authentication resulted  in 

2022-09-07 10:18:20,893 ERROR [org.keycloak.services] (executor-thread-14) KC-SERVICES0025: Error when validating client assertion: java.lang.RuntimeException: Signature on JWT token failed validation
	at org.keycloak.authentication.authenticators.client.JWTClientAuthenticator.authenticateClient(JWTClientAuthenticator.java:168)
	at org.keycloak.authentication.ClientAuthenticationFlow.processFlow(ClientAuthenticationFlow.java:72)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateClient(AuthenticationProcessor.java:901)
	at org.keycloak.protocol.oidc.utils.AuthorizeClientUtil.authorizeClient(AuthorizeClientUtil.java:51)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.checkClient(TokenEndpoint.java:246)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:190)

### Version

18.0.2

### Expected behavior

It is expected that the client authentication process would re-download the new keys, like how it was described in the help text. It is also expected that when the public key is downloaded initially, it is cached as specified by the response header "Cache-Control" 

### Actual behavior

As mentioned above, the actual behavior throws an error when validating the client assertion 

2022-09-07 10:18:20,893 ERROR [org.keycloak.services] (executor-thread-14) KC-SERVICES0025: Error when validating client assertion: java.lang.RuntimeException: Signature on JWT token failed validation
	at org.keycloak.authentication.authenticators.client.JWTClientAuthenticator.authenticateClient(JWTClientAuthenticator.java:168)
	at org.keycloak.authentication.ClientAuthenticationFlow.processFlow(ClientAuthenticationFlow.java:72)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateClient(AuthenticationProcessor.java:901)
	at org.keycloak.protocol.oidc.utils.AuthorizeClientUtil.authorizeClient(AuthorizeClientUtil.java:51)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.checkClient(TokenEndpoint.java:246)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:190)

### How to Reproduce?

configure a confidential client 
![Screen Shot 2022-09-07 at 10 44 51 AM](https://user-images.githubusercontent.com/397774/188944714-fce69c27-c7dd-4ff1-b347-9e0491f97a21.png)
configure JWKS
![Screen Shot 2022-09-07 at 10 32 37 AM](https://user-images.githubusercontent.com/397774/188944740-db648445-87eb-48e0-9623-bf7d13c99b57.png)

Host a REST end point that returns the public key in json format
![Screen Shot 2022-09-07 at 10 47 47 AM](https://user-images.githubusercontent.com/397774/188944975-4affeb81-5423-41f8-b46d-3fc9dc057cf7.png)

Using the jdk keytool, generate a key pair by providing a key store file name, alias, and a password.

```
./keytool -genkeypair \
  -alias kc-oauth-jwt \
  -keyalg RSA \
  -keypass kc-pass \
  -keystore /tmp/kc-jwt.jks \
  -storepass kc-pass
```

expected output will be in jks format. This will allow us to get the public and private keys programatically . 
```
ClassPathResource ksFile = new ClassPathResource(KEY_STORE_FILE);
			KeyStoreKeyFactory ksFactory = new KeyStoreKeyFactory(ksFile, KEY_STORE_PASSWORD.toCharArray());
			keyPair = ksFactory.getKeyPair(KEY_ALIAS);

```
Fetch an access token using the following headers:

client_assertion: JWT token signed by private key
grant_type:client_credentials
client_assertion_type:urn:ietf:params:oauth:client-assertion-type:jwt-bearer

token endpoint: $REALM_PATH/protocol/openid-connect/token

Response:
![Screen Shot 2022-09-07 at 10 52 20 AM](https://user-images.githubusercontent.com/397774/188945753-5c6d8c96-fefa-470d-abfe-e4d1bfe446cc.png)

In order to regenerate the key pair, you have to delete it from the store. 

```
./keytool -delete \
  -alias kc-oauth-jwt \
  -keystore /tmp/kc-jwt.jks \
  -storepass kc-pass
```

Repeat the step that generates a key pair.

If you now try to authenticate the client it results in an error
![Screen Shot 2022-09-07 at 11 26 59 AM](https://user-images.githubusercontent.com/397774/188951588-7a585e5f-b320-4746-ae09-10b225e3e944.png)

![Screen Shot 2022-09-07 at 11 27 47 AM](https://user-images.githubusercontent.com/397774/188952146-f29d3ebd-0d88-41a4-81d9-d76e1550b6f1.png)

**Comment by mposolda** [comment] 2023-04-04 09:45
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by rmartinc** [comment] 2024-02-16 11:20
@javacup But what's the `kid` of the new key? If it's the same keycloak will sue the same key. The `kid` should be different to trigger the refresh of the keys in the client.

**Comment by javacup** [comment] 2024-02-16 14:41
@rmartinc  we were able to fix the back then, by creating a new kid when generating the JWT token for subsequent authentications based on a configured schedule. 
Ideally Keycloak should have used the combination of the kid+expiration to re-download a new public key.

**Comment by rmartinc** [comment] 2024-02-16 16:52
@javacup There is no expiration when you search using kid, the idea is that when you create a new key you have to set a new kid. This way the JWT is created with a different kid in the header. The cache searches using that kid, no key is returned, then it refreshes the keys for that client (there is a minimum time between refresh). That's the basics of key rotation. If you use the same kid there can be always failures, because there is no way to differentiate a token signed with the old or new key.

I'm going to close this issue as it was thought to work this way.

Thanks!

**Closed by rmartinc** 2024-02-16 16:52 UTC
Labels: area/oidc, kind/bug, status/triage, team/core-clients
