### ISSUE TITLE
Keycloak.X 18.0.0 - export/import in container does not work as expected

### ISSUE THREAD

**Issue by djotanov** [keycloak/keycloak#11902] opened 2022-05-09 09:41 UTC
### Describe the bug

Docker image is created as:
```
ARG KEYCLOAK_VERSION="18.0.0"
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} as builder

ENV KC_CACHE_STACK=kubernetes
ENV KC_DB=mysql
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

RUN /opt/keycloak/bin/kc.sh build --db=mysql --transaction-xa-enabled=false

# Runtime image
ARG KEYCLOAK_VERSION="18.0.0"
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} as runtime
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
```

If I run this image, and set environment variables:
```
JAVA_OPTS_APPEND="-Djgroups.dns.query=..."
KC_HOSTNAME_STRICT=false
KC_HOSTNAME_STRICT_HTTPS=false
KC_HTTP_PORT=8080
KC_HTTP_ENABLED=true
KC_DB_URL_DATABASE=keycloak_test
KC_DB_URL_HOST=xxx
KC_DB_USERNAME=xxx
KC_DB_USERNAME=xxx
```
and run:
```
./bin/kc.sh start
```
then the server starts fine, and connects to mysql database that I've configured.

If I run:
```
./bin/kc.sh export --dir ./export
```
then the server does not start and exception is thrown:
```
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=localhost
2022-05-09 08:15:32,097 WARN  [io.agroal.pool] (main) Datasource '<default>': Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:32,263 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.jdbc.driver is set to 'com.mysql.cj.jdbc.Driver' but it is build time fixed to 'org.h2.Driver'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
 - quarkus.http.root-path is set to '/auth' but it is build time fixed to '/'. Did you change the property quarkus.http.root-path after building the application?
2022-05-09 08:15:32,555 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-05-09 08:15:32,694 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:32,696 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
        at io.agroal.pool.ConnectionFactory.connectionSetup(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:210)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-09 08:15:33,292 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:33,395 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-09 08:15:33,422 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-09 08:15:33,433 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-09 08:15:33,579 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-09 08:15:33,684 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-05-09 08:15:33,684 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-05-09 08:15:33,780 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:33,780 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:33,781 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:33,781 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:35,799 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) c5cf5e52c0c1-35457: no members discovered after 2006 ms: creating cluster as coordinator
2022-05-09 08:15:35,810 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [c5cf5e52c0c1-35457|0] (1) [c5cf5e52c0c1-35457]
2022-05-09 08:15:35,816 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `c5cf5e52c0c1-35457`, physical addresses are `[10.0.2.100:44606]`
2022-05-09 08:15:36,413 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-05-09 08:15:36,531 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-05-09 08:15:36,532 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-05-09 08:15:36,532 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:36,533 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

As a workaround, if I pass --auto-build to the export command:
```
./bin/kc.sh export --dir ./export --auto-build
```
then the server starts, performs the export successfully, but the script exits with error code, and message of unsupported flag --auto-build:
```
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=localhost
Changes detected in configuration. Updating the server image.
2022-05-09 08:16:30,160 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-05-09 08:16:30,727 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-09 08:16:30,759 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-09 08:16:30,774 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-09 08:16:30,931 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-09 08:16:31,028 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-05-09 08:16:33,131 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) c5cf5e52c0c1-61054: no members discovered after 2003 ms: creating cluster as coordinator
2022-05-09 08:16:33,140 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [c5cf5e52c0c1-61054|0] (1) [c5cf5e52c0c1-61054]
2022-05-09 08:16:33,144 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `c5cf5e52c0c1-61054`, physical addresses are `[10.0.2.100:7800]`
2022-05-09 08:16:33,567 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: c5cf5e52c0c1-61054, Site name: null
2022-05-09 08:16:33,841 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Exporting into directory /opt/keycloak/./export
2022-05-09 08:16:50,203 INFO  [org.keycloak.services] (main) KC-SERVICES0033: Full model export requested
2022-05-09 08:16:59,924 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Realm 'master' - data exported
2022-05-09 08:17:01,536 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Users 0-0 exported
2022-05-09 08:17:01,701 INFO  [org.keycloak.services] (main) KC-SERVICES0035: Export finished successfully
2022-05-09 08:17:02,380 INFO  [io.quarkus] (main) Keycloak 18.0.0 on JVM (powered by Quarkus 2.7.5.Final) started in 34.612s. Listening on: http://0.0.0.0:8080
2022-05-09 08:17:02,381 INFO  [io.quarkus] (main) Profile import_export activated.
2022-05-09 08:17:02,381 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-05-09 08:17:02,428 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-05-09 08:17:02,484 INFO  [io.quarkus] (main) Keycloak stopped in 0.100s
Unknown option: '--auto-build'
Try 'kc.sh export --help' for more information on the available options.
```

The same issue is present for `import` as well.

### Version

18.0.0

### Expected behavior

The export should work the same as start. It seems that the properties with which the quarkus distribution is built (mysql database) are not respected in export/import and export/import process still sees default h2 database configuration.

### Actual behavior

The export/import fails

### How to Reproduce?

Follow the steps from bug description

**Comment by kdvalin** [comment] 2022-05-11 16:53
Seeing something similar on the `import` command as well.

This is the relevant portions of the dockerfile I'm using to build KeyCloak
```Dockerfile
...
RUN /opt/keycloak/bin/kc.sh build --db postgres 
...
ENTRYPOINT [ "/opt/keycloak/bin/kc.sh", "start-dev",  "--db=postgres" ]
````

With these enviornment variables
```
KC_DB_PASSWORD=password
KC_DB_USERNAME=postgres
KC_DB_URL_DATABASE=postgres
KC_DB_URL_HOST=postgres
```
I get this output
```
2022-05-11 16:47:51,877 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
2022-05-11 16:47:51,877 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
2022-05-11 16:47:52,007 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.jdbc.driver is set to 'org.postgresql.xa.PGXADataSource' but it is build time fixed to 'org.h2.jdbcx.JdbcDataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
2022-05-11 16:47:52,214 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-05-11 16:47:52,372 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
2022-05-11 16:47:52,373 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	... 17 more

2022-05-11 16:47:52,867 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-11 16:47:52,964 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-11 16:47:52,973 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-11 16:47:53,102 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-11 16:47:53,423 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_839958, Site name: null
2022-05-11 16:47:53,458 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
2022-05-11 16:47:53,600 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-05-11 16:47:53,601 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-05-11 16:47:53,601 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
2022-05-11 16:47:53,601 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection refused (Connection refused)
2022-05-11 16:47:53,601 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```


When altering the env. variables to be
```
KC_DB_PASSWORD=password
KC_DB_USERNAME=postgres
KC_DB_URL=jdbc:postgresql://postgres/postgres
```

I get
```
2022-05-11 16:35:24,636 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.jdbc.driver is set to 'org.postgresql.xa.PGXADataSource' but it is build time fixed to 'org.h2.jdbcx.JdbcDataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
2022-05-11 16:35:24,892 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-05-11 16:35:25,157 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': FATAL: password authentication failed for user "sa"
2022-05-11 16:35:25,159 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "sa"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:646)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-11 16:35:25,559 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-11 16:35:25,684 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-11 16:35:25,698 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-11 16:35:25,788 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': FATAL: password authentication failed for user "sa"
2022-05-11 16:35:25,898 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-11 16:35:26,321 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-05-11 16:35:26,321 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-05-11 16:35:26,322 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: FATAL: password authentication failed for user "sa"
2022-05-11 16:35:26,322 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

So it seems that `KC_DB_URL` can set the host of the source database, BUT I cannot get it to work with the username and password.  Setting `KC_DB_URL` to  `jdbc:postgresql://postgres:password@postgres/postgres` yields the first error again.

**Comment by DGuhr** [comment] 2022-05-13 13:13
Possible duplicate of https://github.com/keycloak/keycloak/issues/11767

**Comment by DGuhr** [comment] 2022-05-13 13:14
Possible duplicate of https://github.com/keycloak/keycloak/issues/11767

**Comment by DGuhr** [comment] 2022-05-16 11:28
So, analyzing this atm and just wanted to post the current state:

It seems that when we are loading the import/export profile, so when invoking import or export, from the class path keycloak.conf ConfigSource (ordinal 150), the actual database value does not get picked up from the PersistedProperties ConfigSource anymore. 

**Workaround atm: Add `KC_DB=<your-db-you-added-in-the-buildimage>` also to your runtime configurations env vars/configfile**

I will investigate further why this behaves like it does. Very weird indeed, as the ordinals should fit (persisted has 200, classpathconfigsource has 150).

**Comment by DGuhr** [comment] 2022-05-17 11:03
Ok, fix in the making, I still have to figure out how to properly test this, but locally it works.

**Comment by DGuhr** [comment] 2022-05-17 11:10
FTR: This happens due to the fact that the PersistedConfigSource (containing the "build options" that were set during a "build" beforehand) does not get loaded under some conditions (ref: [here](https://github.com/keycloak/keycloak/blob/0bda7e6038dc85cd0ef45a9f9abedcd48dc8f9ab/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java#L71)). 

See also this diff: https://www.diffchecker.com/GzGYtIoh where I added some debug outputs, line 3 is the important one (also lines 135-150 to see the difference for what kc.db is actually loaded)

**Comment by pedroigor** [comment] 2022-05-26 18:05
Should be fixed by https://github.com/keycloak/keycloak/pull/12157.

**Closed by pedroigor** 2022-05-26 18:05 UTC
Labels: kind/bug, area/dist/quarkus, area/import-export, triage/backport
