### ISSUE TITLE
Quarkus DefaultHostnameProvider does not consider configured admin hostnames

### ISSUE THREAD

**Issue by srose** [keycloak/keycloak#11925] opened 2022-05-10 12:50 UTC
### Describe the bug
Allowed Redirect URis do not accept custom ADMIN hostnames generated by Quarkus DefaultHostnameProvider

Wildfly distribution not affected.

**Conditions**:
- KC_HOSTNAME_ADMIN must be set to a different hostname than KC_HOSTNAME
- (Quarkus distribution as expressed by version 18.0.0)

**Symptom**: 
Accessing the security-admin-console via that KC_HOSTNAME_ADMIN the login redirect is corret, but reports an error: Invalid redirect.

First analysis result (with @thomasdarimont) shows:

**Keycloak Wildfly (18.0.0)**
adminUri used in
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/url/DefaultHostnameProvider.java#L73
adminUri configured in
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/url/DefaultHostnameProviderFactory.java#L40
**Keycloak Quarkus (18.0.0)**
The `adminHostName` is not used by DefaultHostnameProvider#getHostname(...)
https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java#L82
I think a proper fix would be to change:

```
if (ADMIN.equals(urlType)) {
    return getHostname(originalUriInfo);
}
```

to this:

```
if (ADMIN.equals(urlType)) {
    // use configured adminHostname if configured
    if (adminHostName != null) {
        return adminHostName;
    }
    return getHostname(originalUriInfo);
}
```

### Version

18.0.0

17.0.x

### Expected behavior

Login works without error.

### Actual behavior

Login stops with "Invalid redirect"

### How to Reproduce?

- KC_HOSTNAME_ADMIN must be set to some other URL
- (Quarkus distribution as expressed by version 18.0.0)
- Start keycloak and login into the admin-console

### Anything else?

Working on a PR...

**Comment by vmuzikar** [comment] 2022-05-30 12:23
@srose Thank you for reporting this! I believe this is a duplicate of https://github.com/keycloak/keycloak/issues/12190. Feel free to re-open if you think otherwise.

**Closed by vmuzikar** 2022-05-30 12:23 UTC
Labels: kind/bug, area/dist/quarkus, status/triage
