### ISSUE TITLE
The account page encounters an error when an unauthorized user logs in.

### ISSUE THREAD

**Issue by RManesiya** [keycloak/keycloak#33099] opened 2024-09-19 11:45 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The account user interface page encounters an error when a user belonging to a newly created realm with following default roles removed.

Default roles removed:
```
manage-account
manage-account-links
```

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

It should display "Forbidden page" similar to this that got displayed in versions <  25.0.0

![Forbidden-2024-09-19_6-20-18](https://github.com/user-attachments/assets/f82817db-5f84-4581-b031-5f6fd7deca5c)

### Actual behavior

An error is encountered when user logs in, and spinner is displayed.
![2024-09-19_6-00-53](https://github.com/user-attachments/assets/4203bf6b-e9b5-4c98-bec3-4ef3c24bc75d)

### How to Reproduce?

1. Download [Keycloak 25.0.5](https://github.com/keycloak/keycloak/releases/download/25.0.5/keycloak-25.0.5.zip)
2. Unzip `keycloak-25.0.5.zip` to temporary location in my case `C:\Temp\keycloak-25.0.5`
3. Edit `C:\Temp\keycloak-25.0.5c\conf\keycloak.conf`, and update hostname section as shown below
```
# Hostname for the Keycloak server.
hostname=http://localhost:8080/auth
hostname-backchannel-dynamic=false
http-relative-path=/auth 
```
4. Open command prompt and issue following command:
```bash
cd C:\Temp\keycloak-25.0.5\bin
kc.bat start-dev
```

5. Visit `http://localhost:8080/auth` and create default admin user with some password

7. Create a new realm by name "idp"

8. Goto `http://localhost:8080/auth/admin/master/console/#/idp/realm-settings/user-registration`
    Uncheck `Hide inherited roles` and Unassign following roles
```
manage-account
manage-account-links
```

9. Visit `http://localhost:8080/auth/admin/master/console/#/idp/users` and create a new user with some password.

10. Visit `http://localhost:8080/auth/realms/idp/account/` and log in using the new user that was just created. You will encounter following error.

![2024-09-19_6-00-53](https://github.com/user-attachments/assets/4203bf6b-e9b5-4c98-bec3-4ef3c24bc75d)

**Comment by jonkoops** [comment] 2024-09-19 12:04
Duplicate of #32609

**Closed by jonkoops** 2024-09-19 12:04 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui
