### ISSUE TITLE
Syncing users from FreeIPA maps LDAP-fullname field to KC-Firstname field.

### ISSUE THREAD

**Issue by kwoot** [keycloak/keycloak#15623] opened 2022-11-22 12:24 UTC
![Screenshot from 2022-11-22 13-19-17](https://user-images.githubusercontent.com/484336/203313559-e276626f-4919-4dff-b596-ed7afea7602b.png)
![Screenshot from 2022-11-22 13-19-26](https://user-images.githubusercontent.com/484336/203313566-d27929f8-1c62-4e8a-aee4-d23ff02b42bb.png)
### Area

import-export

### Describe the bug

When synchronizing user accounts through user federation, using KC 20.0.1 and FreeIPA 4.9.8
the LDAP 'Full name' field is imported into the 'First name' field in KC. 

This is not correct.

The LDAP 'First name' field should be imported into the 'First name' field in KC.

### Version

20.0.1

### Expected behavior

The LDAP 'First name' field should be imported into the 'First name' field in KC.

### Actual behavior

The LDAP 'Full name' field is imported into the 'First name' field in KC. 

### How to Reproduce?

Install both applications, define user federation through LDAP, select 'sync all users' from the KC web gui.

**Comment by slominskir** [comment] 2022-11-22 13:07
Duplicate of https://github.com/keycloak/keycloak/issues/13492, which itself is a duplicate of a very old https://issues.redhat.com/browse/KEYCLOAK-8062, which is a duplicate of an ancient https://issues.redhat.com/browse/KEYCLOAK-1300

Note: there was a fix for this years ago that was rejected because a test case wasn't provided: https://github.com/keycloak/keycloak/pull/5976

**Comment by kwoot** [comment] 2022-11-22 13:19
Solved. The way to solve this is as follows:
In KC: go to User Federation and select your LDAP provider.
Locate at the top the "Mappers"  tab. Edit the mapper for 'first name´. Change the value of the field 'LDAP Attribute' from 'cn' to 'givenName'. Sync the users again and notice that first name field is now correct.

Why this is default not correct is beyond me. But at least there is a place now that documents a solution.

**Comment by slominskir** [comment] 2022-11-22 13:21
Yes, when you choose "rhds", it should know what schema to use.  That's a bug.   Using the admin console to fix it is a workaround.   Another workaround is to use the kcadm command line tool and bash like so:

```
MAPPER_ID=`${KEYCLOAK_HOME}/bin/kcadm.sh get components -r ${KEYCLOAK_REALM} -q name='first name' --fields id | jq -r .[0].id`
${KEYCLOAK_HOME}/bin/kcadm.sh update components/${MAPPER_ID} -r ${KEYCLOAK_REALM} -s 'config."ldap.attribute"=["givenName"]'
```

**Comment by slominskir** [comment] 2022-11-22 20:07
RHDS Configuration and Schema Reference:
 - [Default schemas list](https://access.redhat.com/documentation/en-us/red_hat_directory_server/12/html/configuration_and_schema_reference/assembly_schema-definitions_config-schema-reference-title#ref_default-directory-server-schema-files_assembly_schema-definitions) - notice `06inetorgperson.ldif`
 - [inetOrgPerson schema detail](https://access.redhat.com/documentation/en-us/red_hat_directory_server/12/html/configuration_and_schema_reference/assembly_entry-object-class-reference_config-schema-reference-title#ref_inetOrgPerson_assembly_entry-object-class-reference) - notice `givenName` field used for first name

**Comment by slominskir** [comment] 2022-11-23 21:25
I have created a reproducer Docker Compose [project](https://github.com/slominskir/keycloak_ldap):
```
git clone -b givenName_15623 https://github.com/slominskir/keycloak_ldap
cd keycloak_ldap
docker compose up
```

**Note A**: I used a 389 directory server container because I couldn't readily find a Red Hat Directory Server container (licensing may be why).  I see there exists a [Red Hat Identity Manager](https://catalog.redhat.com/software/containers/rhel7/ipa-server/58477345d65ec83ce4f311a2?tag=4.6.8-66&architecture=amd64&container-tabs=gti&push_date=1667234314000) container (built on FreeIPA with RHDS), but the licensing is unclear.  A [FreeIPA](https://hub.docker.com/r/freeipa/freeipa-server/) container (built on 389, which is what RHDS is built on) exists too, but it's difficult to run.

**Note B**: The schema may be configurable with Red Hat Directory Server, so instead of observing the vendor, it may make more sense to observe the user object classes and look for `inetOrgPerson` for example.  However, the [default RHDS](https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html-single/administration_guide/index#adding_an_entry-ldapadd) does use the inetOrgPerson so that's a more sensible default then `cn` as is used now.

**Closed** 2024-06-05 00:06 UTC
Labels: kind/bug, area/import-export, help wanted, team/core-iam, status/auto-expire, status/auto-bump, priority/normal, status/expired-by-bot

**Comment by kwoot** [comment] 2024-06-05 07:44
IMHO This is a small bug that can be easily fixed by someone knowledgeable about the code. And thus should not be closed.

**Comment by Gabgobie** [comment] 2024-08-03 18:09
I aggree with kwoot.
Without going too indepth, this should be the place to fix it, maybe additionally change a test to expect the changed values.

https://github.com/keycloak/keycloak/blob/7c69c857a1216cf2af07c4d2859fc961817f530a/js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx#L47-L56

I'd have to really go through the code to find the proper keys to set the default values though so unfortunately I am currently unable to make a PR about this. Maybe I can come back to this when things around me have cooled down a bit.

This free, unverified redhat access solution provides a table with the correct values if you scroll down a bit.

https://access.redhat.com/solutions/3010401



I don't have any intention to insult the hard work of the maintainers but there is one thing that's confusing to me in this context:
Why is there no option to use kerberos for authentication to the 389 server. After all both FreeIPA and Keycloak are the basis for RedHat Enterprise products (IdM and SSO) so why don't they get first class interoperability support? That's not the point of this issue though and I can see how this would be a lower priority when looking at the amount of open issues.

Best,
Gab
