### ISSUE TITLE
Persistence.xml property replacement not working

### ISSUE THREAD

**Issue by kuldeepsingh99** [keycloak/keycloak#25384] opened 2023-12-07 16:23 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I have followed [this](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/user-storage-jpa) example to build custom storage API.

I am testing this in Docker Compose

This is my persistence.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
             version="3.0">
    <persistence-unit name="user-store" transaction-type="JTA">
        <class>com.portal.keycloak.test.UserEntity</class>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect" />
            <property name="hibernate.connection.datasource" value="user-store" />
            <property name="jakarta.persistence.transactionType" value="JTA" />
            <property name="hibernate.hbm2ddl.auto" value="update" />
            <property name="hibernate.connection.url" value="jdbc:mysql://myhost:3306/mydb?zeroDateTimeBehavior=convertToNull" />
            <property name="hibernate.connection.username" value="{env.USER}"/>
            <property name="hibernate.connection.password" value="Bq9Hevk9k2GWFqDk"/>
        </properties>
    </persistence-unit>
</persistence>
```

I have also created quarkus.properties

```
quarkus.datasource.user-store.db-kind=mysql 
quarkus.datasource.user-store.username=
quarkus.datasource.user-store.password=
quarkus.datasource.user-store.jdbc.url=
```

### Version

22.0.0

### Expected behavior

Server Should Start

### Actual behavior

Property env.USER is not getting replaced and server is not starting

I have check the environment variable exist in docker container
```
jakarta.persistence.PersistenceException: [PersistenceUnit: user-store] Unable to build Hibernate SessionFactory
ERROR: [PersistenceUnit: user-store] Unable to build Hibernate SessionFactory
ERROR: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Error calling DriverManager#getConnection [null]
ERROR: Error calling DriverManager#getConnection [null]
ERROR: Access denied for user '{env.USER}'@'172.18.0.7' (using password: YES)
```

### How to Reproduce?

checkout this [project](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/user-storage-jpa) 

update the SQL Dialect in persistence.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
             version="3.0">
    <persistence-unit name="user-store" transaction-type="JTA">
        <class>com.portal.keycloak.test.UserEntity</class>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect" />
            <property name="hibernate.connection.datasource" value="user-store" />
            <property name="jakarta.persistence.transactionType" value="JTA" />
            <property name="hibernate.hbm2ddl.auto" value="update" />
            <property name="hibernate.connection.url" value="jdbc:mysql://myhost:3306/mydb?zeroDateTimeBehavior=convertToNull" />
            <property name="hibernate.connection.username" value="{env.USER}"/>
            <property name="hibernate.connection.password" value="Bq9Hevk9k2GWFqDk"/>
        </properties>
    </persistence-unit>
</persistence>
```

Create Table
```
CREATE TABLE `user_entity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by vramik** [comment] 2024-01-08 11:56
Thank you @kuldeepsingh99 for the report ... I was able to reproduce that once you put `<property name="hibernate.connection.username" value="${env.USER}"/>` into `persistence.xml` and you leave `quarkus.datasource.user-store.username` empty in `quarkus.properties` then there is an error:

```
ERROR: FATAL: password authentication failed for user "${env.USER}"
```

As a workaround you can add `quarkus.datasource.user-store.username=${env.USER}` into `quarkus.properties` as it has higher priority and I was able to verify locally that the environmental variable is properly replaced.

**Comment by shawkins** [comment] 2024-02-26 19:06
@vramik @kuldeepsingh99 is the resolution here to update the quickstart to state that data source configuration should be done via the quarkus.properties, and not in the persistence.xml?

**Comment by vramik** [comment] 2024-02-26 19:43
@shawkins as I understand it, the issue is that property replacement doesn't work correctly when used in persistence.xml.

**Comment by shawkins** [comment] 2024-02-26 20:23
@vramik two thoughts on that:

- following what the example is doing, the datasource is being configured by quarkus.properties and referenced by name with hibernate.connection.datasource. It seems odd to then set the username, password, and url in the persistence.xml instead. 
- There's no mention of using env properties in https://quarkus.io/guides/hibernate-orm and curly braces without a $ is a different convention than quarkus typically uses. Regardless this is question / issue for quarkus correct? There's not much we can do from the keycloak side. cc @geoand @pedroigor

**Comment by geoand** [comment] 2024-02-27 07:04
For persistence related stuff, @yrodiere and @gsmet are the SMEs

**Comment by shawkins** [comment] 2024-02-27 12:58
> For persistence related stuff, @yrodiere and @gsmet are the SMEs

Thanks @geoand any guidance here is appriciated.

I should clarify it appear the user tried {env.USER} and that @vramik tried ${env.USER}. Both seemed to remain literals rather than being replaced.

**Comment by gsmet** [comment] 2024-02-27 13:45
TBH, I'm not entirely sure what should replace `env.USER` in the `persistence.xml`. I don't think that's an Hibernate ORM feature.

WildFly/EAP actually has a feature for that (https://stackoverflow.com/a/43022304/5043585) so I wouldn't be surprised if it was WildFly/EAP doing the work before.
And we don't replace environment variables in files in Quarkus.

My advice would be to put all the configuration in the `application.properties` and avoid mixing the two approaches.
`application.properties` has support for environment variables expansion: https://quarkus.io/guides/config-reference#with-environment-variables

In general, I would avoid using `persistence.xml` in Quarkus.

**Comment by yrodiere** [comment] 2024-02-27 15:09
> My advice would be to put all the configuration in the `application.properties` and avoid mixing the two approaches. `application.properties` has support for environment variables expansion: https://quarkus.io/guides/config-reference#with-environment-variables
> 
> In general, I would avoid using `persistence.xml` in Quarkus.

+1 on both counts.

**Comment by shawkins** [comment] 2024-02-27 17:17
> In general, I would avoid using persistence.xml in Quarkus.

Thank you @yrodiere and @gsmet. The resolution here will be to completely remove the persistence.xml from the example and to use only the quarkus.properties instead. Moving to be a non-bug backlog issue. As @vmuzikar pointed out in #22688 this is likely not considered a fully supported path for Keycloak given the direct configuration / reliance on quarkus.

**Closed** 2024-02-27 17:28 UTC
Labels: impact/low, area/storage, help wanted, team/cloud-native
