### ISSUE TITLE
Keycloak 26: login-status-iframe can not read cookie with SameSite=Lax in top-level with another doamin

### ISSUE THREAD

**Issue by ryanlemon** [keycloak/keycloak#34728] opened 2024-11-07 07:26 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Hey guys,
I have my app running with the https://domaina.com, and assume keycloak running with the https://domainb.com. Then I had login-status-iframe in my app. Before the version 26, the cookie KEYCLOAK_SESSION is secure=true;samesite=none. Each time the docmument.cookie can return the right cookie, while in 26, it always return me '', so changed signal returns back to app for logout.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Allow document.cookie get the KEYCLOAK_SSION in app with another domain.

### Actual behavior

document.cookie always return ''.

### How to Reproduce?

Have a simple site with react, and add login-status-iframe into.
After login, the login-status-iframe can not read the cookie KEYCLOAK_SESSION, so return changed to app for logout.

**Comment by jonkoops** [comment] 2024-11-07 13:28
This must be a configuration issue as I cannot reproduce it. When I run the latest version of the server the cookie is set with `SameSite=None; Secure`. You can see this in action in this [example project](https://github.com/jonkoops/kjs-playground).

**Comment by blxs** [comment] 2024-11-07 14:29
Seems like it is related to [#34295](https://github.com/keycloak/keycloak/issues/34295)

**Comment by ryanlemon** [comment] 2024-11-07 14:38
> Seems like it is related to [#34295](https://github.com/keycloak/keycloak/issues/34295)

@blxs  many thanks, i think you are right. Hope it could be fix sooner.

**Comment by jonkoops** [comment] 2024-11-07 15:21
I'll close this a duplicate then

**Comment by jonkoops** [comment] 2024-11-07 15:21
Duplicate of #34295

**Closed by jonkoops** 2024-11-07 15:21 UTC
Labels: area/oidc, kind/bug, status/triage, team/core-clients
