### ISSUE TITLE
"Network response was not OK" when loading Authentication section of admin console

### ISSUE THREAD

**Issue by jmallach** [keycloak/keycloak#33193] opened 2024-09-23 10:09 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When trying to access the Configure → Authentication section of the admin console for my realm, I always get "Network reponse was not ok".

Starting keycloak in with `debug` logs, I can spot the following, which I guess is related:

```
keycloak-1  | 2024-09-23T10:00:33.098784017Z 2024-09-23 10:00:33,097 DEBUG [org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext] (executor-thread-19) Restarting handler chain for exception exception: com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "org.keycloak.authentication.RequiredActionFactory.isConfigurable()" because "factory" is null
keycloak-1  | 2024-09-23T10:00:33.098864968Z    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._wrapAsIOE(DefaultSerializerProvider.java:531)
keycloak-1  | 2024-09-23T10:00:33.098948862Z    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:504)
keycloak-1  | 2024-09-23T10:00:33.098970681Z    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
keycloak-1  | 2024-09-23T10:00:33.098987816Z    at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1574)
keycloak-1  | 2024-09-23T10:00:33.099004377Z    at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1275)
keycloak-1  | 2024-09-23T10:00:33.099021152Z    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
keycloak-1  | 2024-09-23T10:00:33.099037418Z    at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter.writeResponse(FullyFeaturedServerJacksonMessageBodyWriter.java:79)
keycloak-1  | 2024-09-23T10:00:33.099053149Z    at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:216)
keycloak-1  | 2024-09-23T10:00:33.099069856Z    at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:184)
keycloak-1  | 2024-09-23T10:00:33.099085951Z    at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:28)
keycloak-1  | 2024-09-23T10:00:33.099101194Z    at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
keycloak-1  | 2024-09-23T10:00:33.099117386Z    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
keycloak-1  | 2024-09-23T10:00:33.099141916Z    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1  | 2024-09-23T10:00:33.099177430Z    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak-1  | 2024-09-23T10:00:33.099189896Z    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak-1  | 2024-09-23T10:00:33.099202131Z    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak-1  | 2024-09-23T10:00:33.099211567Z    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak-1  | 2024-09-23T10:00:33.099220558Z    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak-1  | 2024-09-23T10:00:33.099229766Z    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1  | 2024-09-23T10:00:33.099238962Z    at java.base/java.lang.Thread.run(Thread.java:1583)
keycloak-1  | 2024-09-23T10:00:33.099248166Z Caused by: java.lang.NullPointerException: Cannot invoke "org.keycloak.authentication.RequiredActionFactory.isConfigurable()" because "factory" is null
keycloak-1  | 2024-09-23T10:00:33.099258786Z    at org.keycloak.admin.ui.rest.AuthenticationManagementResource.toRepresentation(AuthenticationManagementResource.java:148)
keycloak-1  | 2024-09-23T10:00:33.099286468Z    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
keycloak-1  | 2024-09-23T10:00:33.099337702Z    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
keycloak-1  | 2024-09-23T10:00:33.099355383Z    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
keycloak-1  | 2024-09-23T10:00:33.099371643Z    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak-1  | 2024-09-23T10:00:33.099386772Z    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
keycloak-1  | 2024-09-23T10:00:33.099396355Z    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
keycloak-1  | 2024-09-23T10:00:33.099405910Z    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak-1  | 2024-09-23T10:00:33.099415059Z    at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
keycloak-1  | 2024-09-23T10:00:33.099424083Z    at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:71)
keycloak-1  | 2024-09-23T10:00:33.099432893Z    at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:15)
keycloak-1  | 2024-09-23T10:00:33.099441751Z    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
keycloak-1  | 2024-09-23T10:00:33.099450994Z    ... 18 more
keycloak-1  | 2024-09-23T10:00:33.099461227Z
keycloak-1  | 2024-09-23T10:00:33.103759774Z 2024-09-23 10:00:33,099 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-19) Error response 400: com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "org.keycloak.authentication.RequiredActionFactory.isConfigurable()" because "factory" is null
```

This does not happen when loading Authentication in the master realm. In my realm, I  have several forks of the browser flow that add support for OTP and WebAuthn, but that's about it.

### Version

25.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

The list of Authentication flows is presented.

### Actual behavior

"Network response was not ok".

### How to Reproduce?

Can be reproduced everytime, possibly because something in my setup is bugging Keycloak.

### Anything else?

I believe this happened after upgrading from 24 to 25.

**Comment by ssilvert** [comment] 2024-09-23 11:58
Server side error.  Switching to core.

**Comment by sschu** [comment] 2024-09-23 12:34
@ssilvert Isnt this a duplicate of https://github.com/keycloak/keycloak/issues/32624 ?

**Closed** 2024-09-23 12:36 UTC
Labels: kind/bug, area/admin/api, team/core-iam, team/core-shared

**Comment by jonkoops** [comment] 2024-09-23 14:50
Duplicate of #32624
