### ISSUE TITLE
Infispan Cache replication error after Keycloak update

### ISSUE THREAD

**Issue by beye-pelz** [keycloak/keycloak#13479] opened 2022-08-02 07:43 UTC
### Describe the bug

I'm currently running a plain Install of the quarks install package.
It's a cluster of 2 instances wich currently run on version 18.0.0.
For the cache I'm using JDBCPing for the replication.

Now I tried to update to 18.0.2 and 19.0.1 resulting in this Exception:
```
2022-08-02 08:10:23,938 WARN  [org.infinispan.statetransfer.InboundTransferTask] (jgroups-6,ub-desktop-12483) ISPN000210: Failed to request state of cache authenticationSessions from node ub-accman-2-51925, segments {12-22 64-70 104-116 131-169 210-228}: org.infinispan.commons.CacheException: ExceptionResponse(java.lang.IllegalArgumentException: Segments must not be null or empty)
        at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
        at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
        at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1495)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1397)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
        at org.jgroups.JChannel.up(JChannel.java:780)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
        at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
        at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
        at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
        at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
        at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
        at org.jgroups.protocols.Discovery.up(Discovery.java:300)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

I can see in the package that infispan has been updated.

The kecloak Server isn't starting at all, after this Exception occurs.

### Version

18.0.0

### Expected behavior

An updated from 18.0.0 to 18.0.2 or 19.0.1 with to provied qaurkus tar.gz should be possible without any cache errors.

### Actual behavior

Update results in this Exceptipon:
```
2022-08-02 08:10:23,938 WARN  [org.infinispan.statetransfer.InboundTransferTask] (jgroups-6,ub-desktop-12483) ISPN000210: Failed to request state of cache authenticationSessions from node ub-accman-2-51925, segments {12-22 64-70 104-116 131-169 210-228}: org.infinispan.commons.CacheException: ExceptionResponse(java.lang.IllegalArgumentException: Segments must not be null or empty)
        at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
        at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
        at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1495)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1397)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
        at org.jgroups.JChannel.up(JChannel.java:780)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
        at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
        at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
        at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
        at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
        at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
        at org.jgroups.protocols.Discovery.up(Discovery.java:300)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Anything else?

My keycloak.conf:
`# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
db=mssql

# The username of the database user.
#db-username=keycloak

# The password of the database user.
#db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
#db-url=jdbc:postgresql://localhost/keycloak

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
proxy=edge

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
#hostname=myhostname

http-relative-path=/auth

cache-config-file=cache-ispn.xml

transaction-xa-enabled=false

hostname-strict=false

hostname-strict-https=false

http-enabled=true

log-file=/var/log/keycloak/keycloak.log`

My cache-ispn.xml:
`<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

    
    <jgroups>
        <stack name="jdbc-ping-tcp" extends="tcp">
            <TCP bind_port="7600" />
            <JDBC_PING connection_driver="com.microsoft.sqlserver.jdbc.SQLServerDriver" 
                connection_username="${env.KC_DB_USERNAME}" connection_password="${env.KC_DB_PASSWORD}"
                connection_url="${env.KC_DB_URL}"
                info_writer_sleep_time="500"
                remove_all_data_on_view_change="true"
                stack.combine="REPLACE"
                stack.position="MPING" />
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="jdbc-ping-tcp"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
`

**Comment by mhajas** [comment] 2022-08-02 08:35
Hello, it seems there is some cache replication from one node to another. Are you trying to run Keycloak version 18 together with Keycloak version 18.0.2/19.0.1 in one cluster?

**Comment by beye-pelz** [comment] 2022-08-02 08:41
Hi, thats correct, since it's an HA Cluster, this is the scenario when updating in production.
In the documentation i didn't find anything, that an update in this way isn't possible.
Otherwise this would mean, to have an downtime on every update.

The sceneraio is update is insallated on Node 1, but this isn't starting, because when Node 1 gethers the information from Node 2 it already fails.

At the moment I'm  not able to bring the update to production.

**Comment by mhajas** [comment] 2022-08-02 09:20
Thank you for more details. It seems it was already reported here: #12718 and there is also some workaround: https://github.com/keycloak/keycloak/issues/12718#issuecomment-1169687793.

Currently, Keycloak doesn't support no-downtime upgrades even though, it is possible it worked with some previous versions. It depends on changes done in the corresponding version. The good news is that with the new store we plan to support no-downtime upgrades.

I am closing this issue as it is a duplicate of #12718. If the workaround doesn't work for you, feel free to continue the discussion there.

**Closed by mhajas** 2022-08-02 09:20 UTC
Labels: kind/bug, status/triage
