### ISSUE TITLE
Realm export with ldap user federation fails to bind

### ISSUE THREAD

**Issue by fjakop** [keycloak/keycloak#13362] opened 2022-07-27 10:36 UTC
### Describe the bug

We're trying to export a realm which has user federation with ldap turned on. Bind credentials are correctly configured and normal ldap sync is working.

When we start the export, via `keycloak/bin/kc.sh export --file bup.realm.json --realm bup` it runs into an error saying " simple bind failed" (see full log below)

### Version

17.0.0

### Expected behavior

The realm should be exported in a file called bup.realm.json.

### Actual behavior

```
me@server:~> /keycloak/bin/kc.sh export --file bup.realm.json --realm bup
  2022-07-27 12:24:03,111 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: keycloak.my.domain:10181, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
  2022-07-27 12:24:03,711 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
  2022-07-27 12:24:03,740 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
  2022-07-27 12:24:03,762 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
  2022-07-27 12:24:03,940 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
  2022-07-27 12:24:04,082 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
  2022-07-27 12:24:04,082 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
  2022-07-27 12:24:04,170 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 4.19MB
  2022-07-27 12:24:04,171 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 4.19MB
  2022-07-27 12:24:04,223 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [server-13411|1] (2) [server-13411, server-11667]
  2022-07-27 12:24:04,227 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `server-11667`, physical addresses are `[10.10.54.20:24654]`
  2022-07-27 12:24:05,010 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: server-11667, Site name: null
  2022-07-27 12:24:05,367 INFO  [org.keycloak.services] (main) KC-SERVICES0034: Export of realm 'bup' requested.
  2022-07-27 12:24:05,367 INFO  [org.keycloak.exportimport.singlefile.SingleFileExportProvider] (main) Exporting realm 'bup' into file /home/me/bup.realm.json
  2022-07-27 12:24:24,644 INFO  [org.keycloak.storage.ldap.LDAPIdentityStoreRegistry] (main) Creating new LDAP Store for the LDAP storage provider: 'ldap', LDAP Configuration: {fullSyncPeriod=[-1], pagination=[true], connectionPooling=[true], usersDn=[OU=Users,DC=domain,DC=intern], cachePolicy=[DEFAULT], useKerberosForPasswordAuthentication=[false], importEnabled=[true], enabled=[true], usernameLDAPAttribute=[cn], bindDn=[binduser@domain.intern], changedSyncPeriod=[-1], lastSync=[1658838922], vendor=[ad], uuidLDAPAttribute=[objectGUID], allowKerberosAuthentication=[false], connectionUrl=[ldaps://domain.intern], syncRegistrations=[false], authType=[simple], debug=[false], searchScope=[1], useTruststoreSpi=[ldapsOnly], priority=[0], trustEmail=[false], userObjectClasses=[person, top], rdnLDAPAttribute=[cn], editMode=[READ_ONLY], validatePasswordPolicy=[false], batchSizeForSync=[1000]}, binaryAttributes: []
  2022-07-27 12:24:24,693 INFO  [org.keycloak.truststore.SSLSocketFactory] (main) No truststore provider found - using default SSLSocketFactory
  2022-07-27 12:24:24,962 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
  2022-07-27 12:24:25,151 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
  2022-07-27 12:24:25,151 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: LDAP Query failed
  2022-07-27 12:24:25,151 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@665e9a87
  2022-07-27 12:24:25,151 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Could not query server using DN [OU=Users,DC=domain,DC=intern] and filter [(&(objectClass=*)(objectGUID=\3e\91\40\d0\f9\c9\74\43\ae\9e\c9\76\88\40\6b\70))]
  2022-07-27 12:24:25,151 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: simple bind failed: DOMAIN.INTERN:636
  2022-07-27 12:24:25,151 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection or outbound has closed
  2022-07-27 12:24:25,151 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

```

### How to Reproduce?

* Setup a realm called "my"
* Setup user federation with your Windows Active Directory (ldaps)
* Test Connection from user federation page until successful
* Export the realm via CLI `keycloak/bin/kc.sh export --file my.realm.json --realm my`

**Comment by vramik** [comment] 2022-11-30 17:09
Hello @fjakop, thank you for reporting the issue. Could you please verify whether the ldap is running during the export? Also it'd be helpful if you could verify whether the issue is still present in latest release. Thank you.

**Comment by fjakop** [comment] 2022-12-16 07:43
Hi @vramik, the answer to the first question is yes, the ldap is running. I had not yet the chance to upgrade the version and re-check.

**Comment by vramik** [comment] 2023-01-10 13:44
@fjakop So far I was not able to reproduce it, so I'm going to close it for now, but feel free to reopen the issue when you are able to provide more information and steps to reproduce the issue.

**Closed by vramik** 2023-01-10 13:44 UTC
Labels: kind/bug, area/import-export, area/ldap, status/triage
