### ISSUE TITLE
Searching not working when user is the same in kerberos and in ldap

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#31095] opened 2024-07-07 14:13 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

We use LDAP for our users and AD for kerberos. So I can't enable Kerberos authentication on the ldap section, and need to create its own user federation profile.

So I have an LDAP user federation and a Kerberos user federation.

What happens is that I can search on my user list, eg, user "francis" . It searches and shows results from LDAP.

However, when user "francis" authenticates for the first time, searching for it on the console gives me this error: 

"No users found, could be due to wrongly configured federated provider For more on this error consult the server log at the debug level." 

If I delete LDAP, I can search for the user. If I delete kerberos user federation, I can search for the user. But not when both are enabled.

I imagine that this is a bug. But I also wonder: is that possible at all to login with kerberos and doesn't have it creating a user, but rather having it grab the ldap user that's already there? 

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Get all the users displayed, no matter where they reside.

### Actual behavior

Error is presented

### How to Reproduce?

Get ldap configured. Get kerberos configured as its own user storage. Log in with kerberos. Search for user.

**Comment by pedroigor** [comment] 2024-07-23 23:09
@oculos AFAIK, the kerberos provider will always import the user. 

I think there is a conflict here because once you authenticate for the first time and federated/create the user in the local database, the user is associated with the kerberos provider. Then when federating the same LDAP user, you'll get an error because a same user with the same name exists.

Not sure because I have not tried to to reproduce yet using a set-up like yours.

Do you mind sharing the logs to see if you get any useful messages or stack trace there?

**Comment by oculos** [comment] 2024-07-24 12:38
> @oculos AFAIK, the kerberos provider will always import the user.
> 
> I think there is a conflict here because once you authenticate for the first time and federated/create the user in the local database, the user is associated with the kerberos provider. Then when federating the same LDAP user, you'll get an error because a same user with the same name exists.
> 
> Not sure because I have not tried to to reproduce yet using a set-up like yours.
> 
> Do you mind sharing the logs to see if you get any useful messages or stack trace there?

Somehow, I didn't get that error today. What happened when I tested today was these two things:

- having both the ldap configuration and the kerberos enabled as another user storage, made the kerberos user supersede the ldap one. When I search for the user, only the kerberos one is used. When I disable kerberos, that user is shown as disable, and the ldap user can't log in if kerberos is disabled.
- deleting an LDAP user is impossible. I try to delete it, but can't. See the trace log attached.

[tracelog.tgz](https://github.com/user-attachments/files/16362182/tracelog.tgz)

So, while I can't reproduce the original bug, the essence remains the same:
- we can't use Kerberos user storage when having the same user on ldap. The user is imported to Keycloak, and even deactivating kerberos doesn't allow that user to log in with ldap password.
- We can't delete a kerberos user. We need to delete the whole kerberos user storage to delete its users.

I think that, besides the bugs here described, there is a functionality that is missing: having kerberos as an IdP, and not necessarily as user storage. This is important for those who don't have kerberos provided by the user storage. In our case, we have LDAP as our user storage, and another solution for kerberos. Kerberos doesn't give us the same attributes we get from LDAP, so being able to have account linking would be really nice here.

Should I submit a feature request here @pedroigor ?

**Comment by pedroigor** [comment] 2024-07-24 23:03
Yeah, the federated user can only have a single source of truth for their identity. However, I remember something about authenticating users using Kerberos but without linking then with a provider. I will need to ask @keycloak/core-clients team to see if they can help us here as well.

@oculos Otherwise, feel free to open a feature request. I think we can close this issue once we have a better position about the use case you described from the @keycloak/core-clients team.

**Comment by oculos** [comment] 2024-07-24 23:05
But what about not being able to delete Kerberos users? Isn’t this a bug of its own?

**Comment by pedroigor** [comment] 2024-07-24 23:10
Just a sec. I'm reproducing it here.

**Comment by pedroigor** [comment] 2024-07-24 23:22
@oculos Not sure if a bug or if it is there for a reason ....

The problem with delete is that the user, once created when authenticating for the very first time, is set with a federation link where the value is the Kerberos provider. However, the Kerberos provider does not implement `UserRegistrationProvider` and will cause the removal to fail.

I can send a fix for that but I would rather handle it in a different issue? Wdyt?

Even though I have something that works and removes the local user created by the Kerberos authenticator, I need to discuss more deeply with some people why we are working like that today.

**Comment by pedroigor** [comment] 2024-07-24 23:25
If you want to try it out, please use this branch https://github.com/pedroigor/keycloak/tree/tmp-kerberos. But still, not sure why we are not doing that already.

**Comment by oculos** [comment] 2024-07-25 07:07
> @oculos Not sure if a bug or if it is there for a reason ....

Good point. However, since the behavior is different than that of deleting a user on LDAP, it could perhaps present a more human friendly error? 

> The problem with delete is that the user, once created when authenticating for the very first time, is set with a federation link where the value is the Kerberos provider. However, the Kerberos provider does not implement `UserRegistrationProvider` and will cause the removal to fail.

Ahhh, I see! 
> I can send a fix for that but I would rather handle it in a different issue? Wdyt?

Yeah, maybe it could have its own issue. I'll open it now and point this, ok?

> Even though I have something that works and removes the local user created by the Kerberos authenticator, I need to discuss more deeply with some people why we are working like that today.

Fantastic! Thanks for that! :)

**Comment by pedroigor** [comment] 2024-07-25 10:57
> What about the user superseding the LDAP user? Should it be handled as a bug? My problem is the inconsistency that it's bypassing LDAP users when a kerberos user have logged in.

This one looks should be an RFE. AFAIK, you either use Kerberos from a LDAP provider or a separate Kerberos provider. Both won't work well together if they are the source for the same identities.

**Comment by pedroigor** [comment] 2024-08-05 20:48
@oculos I'm closing this one in favor of https://github.com/keycloak/keycloak/issues/31603 and https://github.com/keycloak/keycloak/issues/31604.

I sent a fix for #31603, let's see if it passes the review.

**Closed by pedroigor** 2024-08-05 20:48 UTC
Labels: kind/bug, area/storage, status/triage, team/core-iam, team/core-shared, status/reopened
