### ISSUE TITLE
Regex Claim Values not working for IDP provider setting

### ISSUE THREAD

**Issue by pinkyjpainadath** [keycloak/keycloak#10932] opened 2022-03-25 04:06 UTC
### Describe the bug

We created an identity provider mapper, with claim value as regex. It seems not to be working. 

Example claim: "groups": "aCO_Admin,aCO_DummyTenant1_Admin,aO_DummyTenant1_ReadOnlyUser,aCNSMO_DummyTenant1_User"

We provided the regex value as 
groups .*aCO_Admin which is not working. tried many regex combinations which are not working as well.

![image](https://user-images.githubusercontent.com/52444432/160051974-dbf8a26e-2081-4092-aea3-e0af573a1dc0.png)

### Version

15.1.1

### Expected behavior

IDP. Mapper should work with regex. Advanced Claim to Group mapper type will assign the user to right group, if regex matches the value of the claim.

### Actual behavior

IDP Mapper regex is not working. User is not getting assigned to the right group when regex pattern is used, else it is working.

### How to Reproduce?

Have a IDP integration. Create a IDP Provider and add a mapper with Advanced Claim to Group. in the claim value, enable regex and add regex pattern 

Example claim: "groups": "aCO_Admin,aCO_DummyTenant1_Admin,aO_DummyTenant1_ReadOnlyUser,aCNSMO_DummyTenant1_User"

sample claim as:
groups .*aCO_Admin

**Comment by mpalavrov** [comment] 2022-11-21 13:48
Is there any work-around here or is it planned to be fixed?

**Comment by rmartinc** [comment] 2023-03-02 11:29
I have tested this and it's working for me in 21.0.0. Note that the regex is a java regex. If your value is really the string `aCO_Admin,aCO_DummyTenant1_Admin,aO_DummyTenant1_ReadOnlyUser,aCNSMO_DummyTenant1_User` (a comma separated string). The regex ` .*aCO_Admin` is not OK (the value does not end with aCO_Admin). You can test the regex for example [here](https://www.freeformatter.com/java-regex-tester.html).

I'm going to close this one as I cannot reproduce it.

**Closed by rmartinc** 2023-03-02 11:29 UTC
Labels: area/oidc, kind/bug, status/triage
