### ISSUE TITLE
Session cross-reference / transaction mismatch

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#20855] opened 2023-06-07 18:56 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

#20793 introduced a memory leak similar to #19396.

Context contains objects from session `S1`.
Session `S1` contains objects that refer to transaction `T1`, and often to session `S1` (see e.g. [`RealmAdapter`](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java#L53)).

Now in the new variant of `runJobInTransactionWithResult`, a new session `S2` is created with transaction `T2`.
It however refers objects from `S1`, and until that transaction is completed, it prevents its garbage collection.

Furthermore, the objects in the new session `S2` context are controlled by transaction `T1`, while they should be controlled by transaction `T2`.

### Version

main

### Expected behavior

Objects from a transaction of a session are controlled by that transaction.

### Actual behavior

Objects from the context of a session are controlled by parent transaction.

### How to Reproduce?

Leverage new variant of `runJobInTransactionWithResult`.

**Comment by pedroigor** [comment] 2023-06-08 00:08
How #20793 is different than https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/common/util/ResponseSessionTask.java?

Do you mean that the objects being set (e.g.: realm) are not fetched from the new session but are set directly into the context object from the original session (and original transaction)?

**Comment by hmlnarik** [comment] 2023-06-08 04:38
@pedroigor Exactly

**Comment by rmartinc** [comment] 2023-06-08 06:49
@hmlnarik Thanks again for catching this! I think hat then we need to re-read the objects in the context with the new session via their IDs. I see that this was done [here](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/common/util/ResponseSessionTask.java#L92-L116). If you want I can move the method to the utility class and use this now.

**Comment by hmlnarik** [comment] 2023-06-08 07:13
@rmartinc That is correct, please go ahead. Would be great to have some method, e.g. `cloneContextToSession(KeycloakContext originalContext, KeycloakSession targetSession)`  in `KeycloakModelUtils` to achieve this.

**Comment by hmlnarik** [comment] 2023-06-08 19:20
`RealmModel` and `ClientModel` only is good for the start.

**Comment by rmartinc** [comment] 2023-06-09 10:31
I had another idea yesterday. So I'm presenting two solutions:

1. This [branch](https://github.com/rmartinc/keycloak/tree/issue-20855). It's the initial idea of re-reading the context models into the new session. It has two commits, first one is the direct implementation (fails with [cockroach](https://github.com/rmartinc/keycloak/actions/runs/5209250469)) and the second commit only re-reads the RealModel ([it works](https://github.com/rmartinc/keycloak/actions/runs/5213916313)). I have tested with both realm and client model locally and it works too. I'll modify this branch if this idea is chosen.
2. The new idea is different and is in another [branch](https://github.com/rmartinc/keycloak/tree/issue-20855-2). The store immediately property is moved to the Event and it's the listener the one that decide what to do. So it can enlist to the transaction, can persist/send the event now or whatever. I have modified the JPA and a test listener and [all tests pass](https://github.com/rmartinc/keycloak/actions/runs/5219856288).

So @hmlnarik take a look to both ideas. I'll do what you prefer. I would bet for the second solution because I think it's better. It works for all the DB, we don't need to re-read objects as the listener can use the original transaction (it can rollback later), the transaction (if rolled back) would also remove model modifications done by the listener... The behavior is a bit different but it's more flexible. A simple listener that doesn't care about transaction is not affected by the immediately and same behavior is expected. A complicated one that wants to enroll to the transaction, now can know when to do it.

Regards!

**Comment by hmlnarik** [comment] 2023-06-09 11:18
Thank you @rmartinc.

The second ides puts the custom extensions at risk of losing events since there is no guarantee that the logic of storing event according to `immediately` flag is respected. Consequently events may be lost upon rollback. Furthermore, the extensions should _not_ cope with the transaction control as that area is very error-prone - for this reason the transaction is controlled from within Keycloak classes.

Thus the first idea (while incorporating feedback from the [first commit](https://github.com/rmartinc/keycloak/commit/a7eafec4da46d97a6fa88c7eae31e6113508a941#comments)) is the one to go with.

**Comment by pedroigor** [comment] 2023-06-09 12:35
Going further with the improvements, we should probably avoid setting the model directly into the `KeycloakContext`. We are doing that everywhere and as we learned from this issue (and previous ones) it is very easy to introduce the problem back as it is not easy to cover/test.

Why we don't set the `id` instead of the model and make sure the model is resolved within the session/transaction scope automatically?

It should remove a few boilerplate code and be a lot safer for those propagating the context to a separate session/transaction/thread.

**Comment by rmartinc** [comment] 2023-06-09 12:37
Okis @hmlnarik, I'm preparing the solution 1 with `RealmModel` and `ClientModel` only.

**Comment by hmlnarik** [comment] 2023-06-09 15:30
Optimizations like lazy loading or restricting what is stored in context are good but they are not the core of this blocker issue. At this moment, main is broken and this issue needs fix. Please keep this bug fix focused.

**Comment by pedroigor** [comment] 2023-06-09 22:49
Please, let's collaborate nicely. As we were discussing alternatives about how to solve the bug fix, I'm proposing another alternative.

If you think it makes sense but prefer doing it in a separate issue, just say it. But don't say the obvious by saying "At this moment, the main is broken and this issue needs to be fixed. Please keep this bug fix focused". Unnecessary.

Also, the issue here is basically caused by not encapsulating context propagation so that developers don't need to worry about them when they need to run blocks using separate sessions. As you know, the code being written here also happens in other places. Don't expect people to be as smart as you are.

**Comment by hmlnarik** [comment] 2023-06-12 07:02
> Please, let's collaborate nicely. As we were discussing alternatives about how to solve the bug fix, I'm proposing another alternative.
> 
> If you think it makes sense but prefer doing it in a separate issue, just say it. But don't say the obvious by saying "At this moment, the main is broken and this issue needs to be fixed. Please keep this bug fix focused". Unnecessary.

@pedroigor, I see that my message could have been received in a different manner that I wished, and I'm sorry that it seems to have happened. My intention was and is to fix this rather sooner than later for 22 timeframe, and I am happy to take it a step further by loading the realm and other objects in context lazily when needed later in a separate discussion / issue. That is why I'm asking to keep the bug fix focused on the bug, and have the enhancement filed separately as an enhancement.

**Closed** 2023-06-12 11:18 UTC
Labels: kind/bug, priority/critical, area/core, area/storage, team/store, team/core
