### ISSUE TITLE
Permission Evaluation Issue on custom attribute evaluation on RPT token generation

### ISSUE THREAD

**Issue by sridhar1495** [keycloak/keycloak#20436] opened 2023-05-18 07:05 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

I am trying to create regex-based policy in client authorization with the attribute that is created in the group. And mapped the policy to the scope-based-permission and evaluated in the Keycloak itself and it is working fine and getting the scope properly. But when I get the RPT token in the authorization's permissions that scope is not found. When we checked in the current version(21.1.1) also the same issue is present. 

On analyzed the issue we found that it is because the claim structure we are trying to evaluate is having the structure 'claimname.value'. If I configure to get the value to be present is 'claimname' itself and configured the policy to evaluate it is working as expected. So, we assume that the Evaluation engine is not given support for that kind structure during the RPT generation.

The behavior is as follows:
1. Created Attribute in the group called 'ADMIN' as follows
![image](https://github.com/keycloak/keycloak/assets/75622411/4189244e-9113-49ca-afe3-08ee237842bf)

2. Added 'admin; user to the above group
![image](https://github.com/keycloak/keycloak/assets/75622411/7c48cc19-d1d1-4bae-bd34-f2351e0a876b)

3. Created 'Client Scopes' and mapper to get the group attribute in the JWT token at realm level and marked as default
![image](https://github.com/keycloak/keycloak/assets/75622411/0c272f81-23f4-4c8c-9218-8db665f5b24e)
![image](https://github.com/keycloak/keycloak/assets/75622411/20ae3ebd-2ac9-4147-820e-edad1a831a0d)
![image](https://github.com/keycloak/keycloak/assets/75622411/885fe07f-aedd-4429-a0f7-ef777eced291)

4. Created Regex-policy inside the client and checked for the exact value
![image](https://github.com/keycloak/keycloak/assets/75622411/d81e7a6b-97a7-420c-bd83-0b9328236d53)
![image](https://github.com/keycloak/keycloak/assets/75622411/182218b4-8a17-4b7f-906b-d35982c16368)

5. Mapper this in the scope-based permission to get the 'read' scope
![image](https://github.com/keycloak/keycloak/assets/75622411/b272cd67-42a8-4cd3-ae16-fa844df4446c)
![image](https://github.com/keycloak/keycloak/assets/75622411/e0f197d9-a96f-4e90-b80b-5be19400b5a5)

6. When I use the evaluation option in the keycloak it is giving the permission for that scope
![image](https://github.com/keycloak/keycloak/assets/75622411/079e2373-f8fa-4119-8ae7-bb57ff46747c)
![image](https://github.com/keycloak/keycloak/assets/75622411/152a4a96-667a-4a5f-af24-a4670f541ec0)

7. when I am the RPT token using the token API POST: http://localhost:8080/realms/dev/protocol/openid-connect/token by passing the authentication token with the following 2 values grant_type = urn:ietf:params:oauth:grant-type:uma-ticket, audience = service-client in the token the 'read' scope is missing for the same user. Even the token is having the mapper value
![image](https://github.com/keycloak/keycloak/assets/75622411/1dae0cfa-cf4f-4384-9df5-bbec0f3079fa)

8. This is behavior is working fine when I change the 'Token Claim Name' in the Mapper to 'attributes' from 'attributes.values' and changed the policy accordingly.

### Version

20.0.3

### Expected behavior

The Evaluation must behave properly as per the Regex configured in the policy based on the claim structure.

### Actual behavior

If the claim structure is represented as Object1.Object2=value is failing for the regex written for the structure Object1.Object2 even with the exact match.

### How to Reproduce?

The behavior is as follows:
1. Created Attribute in the group called 'ADMIN' as follows
![image](https://github.com/keycloak/keycloak/assets/75622411/4189244e-9113-49ca-afe3-08ee237842bf)

2. Added 'admin; user to the above group
![image](https://github.com/keycloak/keycloak/assets/75622411/7c48cc19-d1d1-4bae-bd34-f2351e0a876b)

3. Created 'Client Scopes' and mapper to get the group attribute in the JWT token at realm level and marked as default
![image](https://github.com/keycloak/keycloak/assets/75622411/0c272f81-23f4-4c8c-9218-8db665f5b24e)
![image](https://github.com/keycloak/keycloak/assets/75622411/20ae3ebd-2ac9-4147-820e-edad1a831a0d)
![image](https://github.com/keycloak/keycloak/assets/75622411/885fe07f-aedd-4429-a0f7-ef777eced291)

4. Created Regex-policy inside the client and checked for the exact value
![image](https://github.com/keycloak/keycloak/assets/75622411/d81e7a6b-97a7-420c-bd83-0b9328236d53)
![image](https://github.com/keycloak/keycloak/assets/75622411/182218b4-8a17-4b7f-906b-d35982c16368)

5. Mapper this in the scope-based permission to get the 'read' scope
![image](https://github.com/keycloak/keycloak/assets/75622411/b272cd67-42a8-4cd3-ae16-fa844df4446c)
![image](https://github.com/keycloak/keycloak/assets/75622411/e0f197d9-a96f-4e90-b80b-5be19400b5a5)

6. When I use the evaluation option in the keycloak it is giving the permission for that scope
![image](https://github.com/keycloak/keycloak/assets/75622411/079e2373-f8fa-4119-8ae7-bb57ff46747c)
![image](https://github.com/keycloak/keycloak/assets/75622411/152a4a96-667a-4a5f-af24-a4670f541ec0)

7. when I am the RPT token using the token API POST: http://localhost:8080/realms/dev/protocol/openid-connect/token by passing the authentication token with the following 2 values grant_type = urn:ietf:params:oauth:grant-type:uma-ticket, audience = service-client in the token the 'read' scope is missing for the same user. Even the token is having the mapper value
![image](https://github.com/keycloak/keycloak/assets/75622411/1dae0cfa-cf4f-4384-9df5-bbec0f3079fa)

8. This is behavior is working fine when I change the 'Token Claim Name' in the Mapper to 'attributes' from 'attributes.values' and changed the policy accordingly.

**Comment by mposolda** [comment] 2023-05-19 14:38
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:

- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
- If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here https://www.keycloak.org/community for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by sridhar1495** [comment] 2023-05-21 08:25
@mposolda Thank you for informing me. 

- Yes, all the information and screenshot are based on the latest version(21.1.1) of keycloak only I have taken and pasted here.
- Also, I have checked all the possible configurations related to my action, and I haven't found any mistakes so far(If any in the future I will update with the details).
- I am checking the codes as well to find the cause spot, If I was able to find the exact point I will contribute as per the guideline.

**Comment by zvigrinberg** [comment] 2023-05-31 06:21
Hi @sridhar1495 @mposolda 
By Chance, I Came across this issue as well, and managed to resolve it( Tested it already for various inputs, and it works great ).
Originally the problem is that claims that their value is a JSON object itself,  are not mapped to the final attributes that the regex policy evaluation process can access, and therefore it ignores them by mistake.
I'll open a PR with a fix for that issue very soon.

**Comment by zvigrinberg** [comment] 2023-06-01 06:17
soon i'll have some time, i'll add some tests and open a PR.

**Closed** 2023-06-07 13:18 UTC
Labels: area/authorization-services, kind/bug, status/triage, team/core

**Comment by sridhar1495** [comment] 2023-06-22 09:44
@zvigrinberg Hi just to know, is the fix is already published in the KeyCloak or in which version can we expect it to be released?

**Comment by zvigrinberg** [comment] 2023-06-22 10:05
@sridhar1495 Hi, I have no idea, maybe it will be included in the next release version, which still not released, but i can't tell you for sure, maybe you should ask some of the maintainers..
