### ISSUE TITLE
JSON on message for events

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#33141] opened 2024-09-20 11:57 UTC
### Description

Keycloak already provides JSON as one of its output formats for logging.
However, event logging (org.keycloak.events) have very structured data on the `message` field that could be sent structured as json.
This would help a lot using the data without further parsing/processing on systems like ELK.

### Motivation

Messages formatted as json would provide searchable data without the need of parsing. Event-logging is very important for most organizations, and this would make things easier when using a central logging solution.

**Comment by shawkins** [comment] 2024-09-20 12:29
Duplicate of #22348

**Closed by shawkins** 2024-09-20 12:29 UTC
Labels: kind/feature, status/triage
