### ISSUE TITLE
Failed to index warnings in log at startup

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#29476] opened 2024-05-13 10:44 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Starting 24.0.4 there is a lot of warnings printed, which was not present in 24.0.3 and earlier:

```
2024-05-13 12:40:13,930 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index org.apache.tools.ant.Task: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,957 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index org.springframework.core.io.DefaultResourceLoader: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,958 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index org.springframework.core.io.ResourceLoader: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,959 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index org.springframework.core.io.Resource: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,980 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index jakarta.jms.XAConnection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,980 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index jakarta.jms.XASession: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,981 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index jakarta.jms.XAConnectionFactory: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,985 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index io.mashona.logwriting.ArrayStore: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,987 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index org.apache.activemq.artemis.core.journal.RecordInfo: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:13,987 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index org.apache.activemq.artemis.core.journal.Journal: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
2024-05-13 12:40:14,012 WARN  [io.qua.dep.ind.IndexWrapper] (build-73) Failed to index jakarta.jms.Connection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@199e4c2b
```

### Version

24.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

No warnings like these should be present

### Actual behavior

List of confusing warnings that the end user of Keycloak should not have to deal with

### How to Reproduce?

Simply start 24.0.4

**Comment by vmuzikar** [comment] 2024-05-13 10:47
This seems to be a duplicate of: https://github.com/keycloak/keycloak/issues/28947.

**Closed** 2024-05-13 10:50 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage, backport/24.0
