### ISSUE TITLE
Unable to delete realm (deleteErrorRealmSetting)

### ISSUE THREAD

**Issue by jb-home** [keycloak/keycloak#26047] opened 2024-01-09 14:48 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Unable to delete a custom realm.

### Version

23.0.4

### Expected behavior

Realm should be deleted.

### Actual behavior

The UI shows following error popup: deleteErrorRealmSetting

I am also unable to delete the realm using the API.

### How to Reproduce?

I am using a mySQL cluster.
I created the realm in 23.0.3 and was unable to delete it.
Updated to 23.0.4 and issue still persists.

### Anything else?

2024-01-09 14:37:53,481 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-71) SQL Error: 1064, SQLState: 42000
2024-01-09 14:37:53,481 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-71) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"keycloak".COMPOSITE_ROLE where CHILD_ROLE = 'b8030bdb-f73c-4918-a994-117777930f' at line 1
2024-01-09 14:37:53,481 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-71) Uncaught server error: org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [delete from "keycloak".COMPOSITE_ROLE where CHILD_ROLE = ?] [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"keycloak".COMPOSITE_ROLE where CHILD_ROLE = 'b8030bdb-f73c-4918-a994-117777930f' at line 1] [n/a]
at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:64)
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
at org.hibernate.sql.exec.internal.StandardJdbcMutationExecutor.execute(StandardJdbcMutationExecutor.java:96)
at org.hibernate.query.sql.internal.NativeNonSelectQueryPlanImpl.executeUpdate(NativeNonSelectQueryPlanImpl.java:76)
at org.hibernate.query.sql.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:839)
at org.hibernate.query.spi.AbstractQuery.executeUpdate(AbstractQuery.java:637)
at org.keycloak.models.jpa.JpaRealmProvider.removeRole(JpaRealmProvider.java:430)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
at org.keycloak.models.jpa.JpaRealmProvider.removeRoles(JpaRealmProvider.java:466)
at org.keycloak.storage.RoleStorageManager.removeRoles(RoleStorageManager.java:195)
at org.keycloak.models.cache.infinispan.RealmCacheSession.removeRoles(RealmCacheSession.java:858)
at org.keycloak.models.jpa.JpaRealmProvider.removeClient(JpaRealmProvider.java:955)
at org.keycloak.models.jpa.JpaRealmProvider.removeClients(JpaRealmProvider.java:942)
at org.keycloak.storage.ClientStorageManager.removeClients(ClientStorageManager.java:257)
at org.keycloak.models.cache.infinispan.RealmCacheSession.removeClients(RealmCacheSession.java:612)
at org.keycloak.models.jpa.JpaRealmProvider.removeRealm(JpaRealmProvider.java:180)
at org.keycloak.models.cache.infinispan.RealmCacheSession.removeRealm(RealmCacheSession.java:521)
at org.keycloak.services.managers.RealmManager.removeRealm(RealmManager.java:264)
at org.keycloak.services.resources.admin.RealmAdminResource.deleteRealm(RealmAdminResource.java:489)
at org.keycloak.services.resources.admin.RealmAdminResource$quarkusrestinvoker$deleteRealm_56928e4b2fb2e8c48d4983df30b15118d69f3a51.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"keycloak".COMPOSITE_ROLE where CHILD_ROLE = 'b8030bdb-f73c-4918-a994-117777930f' at line 1
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
at com.mysql.cj.jdbc.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:596)
at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
at org.hibernate.sql.exec.internal.StandardJdbcMutationExecutor.execute(StandardJdbcMutationExecutor.java:83)
... 37 more

**Comment by ssilvert** [comment] 2024-01-10 19:54
Doesn't look like a UI bug.  Moving to core team.

**Comment by sguilhen** [comment] 2024-02-21 21:50
This is a duplicate of https://github.com/keycloak/keycloak/issues/25961 - the bug fix will be available both in Keycloak 24.0.0 and 23.0.7

**Closed by sguilhen** 2024-02-21 21:50 UTC
Labels: kind/bug, area/core, status/triage, team/core-iam
