### ISSUE TITLE
Incorrect JSON returned in case of unavailable user federation

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#23396] opened 2023-09-20 16:50 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When Keycloak is configured with a user fedeation such as LDAP and that user federation is not available, Keycloak show the following error message in the admin UI when searching for users.

> No users found, could be due to wrongly configured federated provider
> Unexpected non-whitespace character after JSON at position 1775 (line 1 column 1776)

Keycloak returned the following response to the admin UI. Note that the json is invalid, but contains all users from local Keycloak database.

```json
[
    {
        "id": "139020a3-4459-43b1-a92f-d90e5cf093a1",
        "createdTimestamp": 1632070461116,
        "username": "test",
        "enabled": true,
        "emailVerified": true,
        "email": "test@example.com",
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        },
        "bruteForceStatus": {
            "numFailures": 0,
            "disabled": false,
            "lastIPFailure": "n/a",
            "lastFailure": 0
        }
    },
    {
        "id": "139020a3-4459-43b1-a92f-d90e5cf093a2",
        "createdTimestamp": 1632070461116,
        "username": "test2",
        "enabled": true,
        "emailVerified": true,
        "email": "test2@example.net",
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        },
        "bruteForceStatus": {
            "numFailures": 0,
            "disabled": false,
            "lastIPFailure": "n/a",
            "lastFailure": 0
        }
    },
    {
        "id": "139020a3-4459-43b1-a92f-d90e5cf093a3",
        "createdTimestamp": 1632070461116,
        "username": "test3",
        "enabled": true,
        "emailVerified": true,
        "email": "test3@example.org",
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        },
        "bruteForceStatus": {
            "numFailures": 0,
            "disabled": false,
            "lastIPFailure": "n/a",
            "lastFailure": 0
        }
    },
    {
        "id": "139020a3-4459-43b1-a92f-d90e5cf093a4",
        "createdTimestamp": 1632070461116,
        "username": "test4",
        "enabled": true,
        "emailVerified": false,
        "email": "test4@example.com",
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        },
        "bruteForceStatus": {
            "numFailures": 0,
            "disabled": false,
            "lastIPFailure": "n/a",
            "lastFailure": 0
        }
    },
    {
        "id": "139020a3-4459-43b1-a92f-d90e5cf093a5",
        "createdTimestamp": 1632070461116,
        "username": "test5",
        "enabled": true,
        "emailVerified": true,
        "email": "test5@local.local",
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        },
        "bruteForceStatus": {
            "numFailures": 0,
            "disabled": false,
            "lastIPFailure": "n/a",
            "lastFailure": 0
        }
    }
]{
    "error": "unknown_error"
}
```

I understand that Keycloak cannot show any users from the unavailable federation, but it does not show the users returned for the query either.

### Version

22.0.3

### Expected behavior

Show the list of users that could be loaded from Keycloak itself (and available user federations with higher priority than the unavailable one). Show an additional hint that not all users could be loaded due to an issue with the federation provider.

### Actual behavior

Shows this error message and returns invalid JSON.

![image](https://github.com/keycloak/keycloak/assets/12183470/a7a0776d-89a4-490c-8ada-29a82ae7215f)

### How to Reproduce?

* Start a fresh Keycloak instance
* add a local user to a realm
* configure a user federation (ldap) within that the same realm and set the connection url to a non-existing server and all other attributes to valid values
* navigate to the user tab and search for all users

**Comment by ssilvert** [comment] 2023-09-20 20:08
Moving this to core team as API should not be returning invalid JSON.

**Comment by rmartinc** [comment] 2023-09-22 12:30
This is a duplicate of #20451 (and others) which should be fixed now after @pedroigor switched to the resteasy reactive #10713. It was a long issue with complicated resolution and the fix was merged just a few days ago. @sventorben Can you please test with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?

I'm closing now this one because it's a duplicate for sure.

**Closed** 2023-09-22 12:30 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core

**Comment by sventorben** [comment] 2023-10-10 11:54
@rmartinc I just tested with nightly. Now the JSON is syntactically correct, but missing users from first user federation:

```json
{"error":"unknown_error"}
```

However, I get this error message now:

![image](https://github.com/keycloak/keycloak/assets/12183470/300fc1fc-6c7f-4e86-987f-4563e460b44e)

![image](https://github.com/keycloak/keycloak/assets/12183470/3b7168f7-f903-4cab-ad42-a4b3a5576c61)

**Comment by rmartinc** [comment] 2023-10-10 12:21
Yes, users won't be returned, just the error. This is what was happening before with wildfly. I think that the UI error should be clearer, @jonkoops do you agree to file a issue for that?

**Comment by rmartinc** [comment] 2023-10-10 14:01
IMHO the method just return a list of users, we would need to change to return something more and say there was an error. As commented this issue was only to return the previous functionality and return a valid json, as with wildfly. Anything else is an enhancement and should be treated as a different issue.

**Comment by sventorben** [comment] 2023-10-10 15:40
@jonkoops It is not about misconfiguration. It may be that the user federation may temporarily not be available e.g. due to a network failure. I think an admin should be made aware of this and get an info in the admin console instead of just seeing an empty list of users. One of our customers recently had a temporary outage of one of their LDAP servers. This behaviour was very annoying, because neither support staff nor admins were able to work with Keycloak.

So, I do not understand why Keycloak should not simply show at least users from the local database and user federations with higher prio. Obviously, they could be loaded as the JSON in my initial report shows.

If this should be discussed first or a seprate feature request, fine for me.

**Comment by jonkoops** [comment] 2023-10-10 15:45
> I think an admin should be made aware of this and get an info in the admin console instead of just seeing an empty list of users.

I completely agree with this. I think we should make a dedicated section in the Admin Console for this that will highlight any sort of issues that are currently happening, perhaps even e-mail the admin user about it. But I don't think this should break the API that lists the users.

> So, I do not understand why Keycloak should not simply show at least users from the local database and user federations with higher prio. Obviously, they could be loaded as the JSON in my initial report shows.

I am also not aware of why this was done, but what you are saying here does make sense to me.

> If this should be discussed first or a seprate feature request, fine for me.

Yes, please do log these as new and separate issues. It makes it easier for us to triage and get it assigned to the correct team.

**Comment by rmartinc** [comment] 2023-10-10 18:06
@steeveborc You can disable the ldap provider. I think that doing that you can manage users in the database. You can enable later when the ldap is available again. Imported users are disabled an read-only (or similar). Please don't fill an issue to return users if there is an error, that increments a lot the complexity to get very little benefit.

@jonkoops But it's true that there is an error in the console if there is an error returning the users. I think that one should be filed.

**Comment by sventorben** [comment] 2023-10-10 19:12
> You can disable the ldap provider. I think that doing that you can manage users in the database. You can enable it later when the ldap is available again.

Yes, I could do that, but would need to find the failing provider first (via log analysis?) and disable all other ldap providers with lower priority as well.

> Please don't file an issue to return users if there is an error, that increments a lot the complexity to get very little benefit.

Sorry, I disagree in this point. If you have a lot of user federations and one fails, the current behavior leaves people (support. call center agents, admins) unable to do their work. They are left with an empty user list and do not really know what is going on. They are unable to reset passwords, impersonate users and help with support cases, or manage permissions.

Regarding complexity, how complex is this really? As you can see from the JSON that I posted initially, the list of user is already there. Due to the error, it was syntactically incorrect JSON, but the data was exactly what I wanted. That combined with a meaningful warning message would really increase user experience a lot.

**Comment by NagenderPulluri** [comment] 2023-10-19 14:14
In our LDAP system, there is an issue where we are unable to search for users using their email addresses. However, we can successfully search for users by their first name or username. When attempting to search for users by email, we are encountering an error message  on UI which states: 

"No users found, could be due to wrongly configured federated provider Unexpected non-whitespace character after JSON at position 472."

It's worth noting that when we intentionally modify the email address by removing the letter "m" from the end ".com" and searching with only ".co," we are able to retrieve the correct user details.

This issue is occurring within our production environment, and it's imperative that we resolve it promptly. Could someone please help.

**Comment by jonkoops** [comment] 2023-12-09 11:24
Please log a new issue if this is still reproducible in the latest version of Keycloak. Comments on closed issues are largely ignored, as we cannot track their status.

**Comment by akiragothick** [comment] 2024-01-05 22:21
Dear friends,

Was this problem solved? Can someone tell me how I can see the log?

![image](https://github.com/keycloak/keycloak/assets/22055806/de0c435e-41f8-4715-8b7c-a6ac05c8238a)

![image](https://github.com/keycloak/keycloak/assets/22055806/66f914fd-156b-4008-aba9-e303ac089fff)

Please

**Comment by fxbayuanggara** [comment] 2024-02-01 23:50
I have this issue too on 23.0.5

**Comment by jonkoops** [comment] 2024-02-08 15:30
Closing this discussion, if you are able to reproduce this issue please log a new ticket.
