### ISSUE TITLE
keycloak 17 behind nginx reverse proxy redirects admin console to port 443 instead of 8444

### ISSUE THREAD

**Issue by mehdiMj-ir** [keycloak/keycloak#10626] opened 2022-03-07 15:05 UTC
### Describe the bug

Hi, I setup `keycloak 17 `on `Ubuntu 20.04`, `openjdk-11-jre` and reverse peroxided  by `nginx 1.18.0`.
It's this setup is okay on production https port 443, but when I try change it and serve it on different port for example 8444 it doesn't work and redirects to 443!
![Screenshot_20220307_181011](https://user-images.githubusercontent.com/20270329/157055608-1977950f-8186-4935-ba4d-cbb5ac5f330a.png)

### Version

17

### Expected behavior

I Expected to redirects me to nginx port which I was serving 8444

### Actual behavior

But it redirects me to port 443

### How to Reproduce?

Download `Keycloak 17` and install `openjdk-11-jre` & `nginx 1.18.0` on `Ubuntu 20.04`.
create TLS certificates and run in production mode with these configurations.
```conf/keycloak.conf
db-url-host=10.10.10.10 # postgres server
db=postgres
db-username=keycloak
db-password=keycloak
hostname=key-test.xxxxxxxxx.ir
http-enabled=true
https-certificate-file=/etc/ssl/certs/pem.pem
https-certificate-key-file=/etc/ssl/private/key.key
https-port=8443
proxy=passthrough
```

and this Nginx configuration:

```nginx.conf
## 
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}
upstream keykloack{
  server key-test.xxxxxxxxx.ir:8443;
}

server {
  listen 80;
  server_name key-test.xxxxxxxxx.ir;
  return 301 https://$server_name:8444$request_uri;
}

server {
  listen 8444 ssl http2;
  server_name  key-test.xxxxxxxxx.ir;

  ssl_certificate     /etc/ssl/certs/pem.pem;
  ssl_certificate_key /etc/ssl/private/key.key;

  error_page 497 https://$server_name:8444$request_uri;

  location / {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $http_host;
    proxy_pass https://keykloack;
  }
}
```

### Anything else?

I look for it on documentation but didn't found any thing relative to s, once again thank you guys for help and support :)

**Comment by romainsi** [comment] 2022-03-08 09:37
Hi, 

It seems when indicating the port in hostname it solves the problem :
hostname=key-test.xxxxxxxxx.ir:8444

Regards,
Romain.

**Comment by mehdiMj-ir** [comment] 2022-03-08 14:11
Oh, didn't know that.
I'm behind `Mikrotik` Router Firewall and I have to serve my back-end through other ports and my front with 80 & 443.
Thank you very much for your time and your answer.
I hope you guys add this to Keycloak documentations.
Once again thanks @romainsi, `Redhat` && `Keycloak` community :)

**Comment by stianst** [comment] 2022-03-11 08:16
Including the port in `hostname` is not intended to work, but seems to. In situations like these when the proxy is on a non-standard port we don't actually have proper support for that right now, and need to introduce an option for this (`--proxy-port`, `--hostname-port`, or something)

**Comment by smallgod** [comment] 2022-03-14 18:58
hi guys, I have Keycloak 17.0.0 as well behind Nginx proxy server.
I still keep getting a redirect to the port: 8443 instead of the Nginx port: 443

Have a look at the screenshot (browser url:port and the admin portal link url:port below - they are different)

*I have a similar configuration as the reporter only a change in Nginx port number.

<img width="796" alt="Screenshot 2022-03-14 at 21 56 34" src="https://user-images.githubusercontent.com/2032761/158241869-10ae28c8-80a6-475c-b7a5-5a95a399a67c.png">

**Comment by mehdiMj-ir** [comment] 2022-03-15 06:27
please add more information and logs.

try `https-port=443` in **keycloak.conf** and `listen 443 ssl http2;` in your **nginx** configurations, you good to go

**Comment by zanettea** [comment] 2022-03-25 18:07
Hello @stianst , I have the same issue in 17.0.1, even specifying the new flag --hostname-port. Unfortunately in this new version it  seems that the workaround of using the port in the hostname is not working anymore, so I reverted to 17.0.0.

**Comment by timoschlueter** [comment] 2022-03-31 08:26
I can confirm that 17.0.0 and 17.0.1 seem to work differently. On 17.0.1 we get the blank admin page with our configuration but with 17.0.0 it works just fine. Is there a best practice configuration example for keycloak 17.0.1 behind a reverse proxy (nginx in our case?)

**Comment by fredericoschardong** [comment] 2022-04-08 02:03
> I can confirm that 17.0.0 and 17.0.1 seem to work differently. On 17.0.1 we get the blank admin page with our configuration but with 17.0.0 it works just fine. Is there a best practice configuration example for keycloak 17.0.1 behind a reverse proxy (nginx in our case?)

Any luck? Same issue here.

**Comment by tbaro** [comment] 2022-04-10 09:50
> > I can confirm that 17.0.0 and 17.0.1 seem to work differently. On 17.0.1 we get the blank admin page with our configuration but with 17.0.0 it works just fine. Is there a best practice configuration example for keycloak 17.0.1 behind a reverse proxy (nginx in our case?)
> 
> Any luck? Same issue here.

I had the same blank screen issue behind an nginx reverse proxy. In my case, i discovered that Keycloak sends a very large cookie when requesting the admin page, which resulted in a response of HTTP 400 (bad request) from nginx. I added a large_client_header_buffers line to the server block:

```
server {
    listen 443     ssl
    servername  keycloak.yourdomain.com
    **large_client_header_buffers 4 16k;**
   
}
```

Hope this works for you too.

**Comment by sbenhazez** [comment] 2022-06-08 11:11
Keycloak quarkus 18.0 :
I had the same blank screen issue behind an nginx reverse proxy.
nginx --> ingress --> keycloak  (kubernetes)
nginx --> keycloak (docker compose)

From the recommended version of keycloak quarkus, 
the same debate with keycloak behind a proxy 

🆘

**Comment by sheinbergon** [comment] 2022-06-13 12:31
Simply put, using this setup:

      KC_FEATURES: token-exchange,grained-authz
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql:/*****:5432/keycloak
      KC_DB_USERNAME: ****
      KC_DB_PASSWORD: ****
      KC_PROXY_MODE: edge
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HOSTNAME_PORT: 443
      KC_HOSTNAME: ******
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: ****

Works well for `17.0.0`, but doesn't work for `17.0.1` or `18.0.0`.

@stianst any idea on when would a fix for this be introduced?

**Comment by jlmartins-sf** [comment] 2022-07-08 03:25
Hi @sheinbergon, did you solve this?

**Comment by sheinbergon** [comment] 2022-07-11 09:34
> Hi @sheinbergon, did you solve this?

Nope, I'm stuck using version 17.0.0. The issue still exists when in 18.0.2
@stianst any idea on how to solve it?

**Closed** 2022-08-10 14:34 UTC
Labels: kind/bug, area/dist/quarkus, status/triage

**Comment by schrill** [comment] 2022-08-25 14:03
[](url)Confirming the above, version's above 17.0.0 do not work with our current setup and result with a white admin page.
We are using a similar setup ALB with SSL termination and an ECS container and can confirm that present configuration works for version 17.0.0 without browser errors.
`start --auto-build --proxy=edge --hostname=${local.project_env}.${element(keys(dependency.zone.outputs.zone_id),1)} --http-relative-path=/${local.name_infix} --hostname-strict-https=true --metrics-enabled=true --log-level=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG --cache-config-file=cache-ispn-jdbc-ping.xml`
The above line is how we start the ephemeral containers, the entrypoint...
Both Version 19 error out with following error:
![Screenshot from 2022-08-25 16-01-16](https://user-images.githubusercontent.com/37488482/186685647-eb9decff-3375-4a32-9cd6-ef3d89195e18.png)
Tried with current DB and auto migration and with a blank DB, resulting in the same error.

**Comment by pedroigor** [comment] 2022-08-25 20:26
@schrill Can you try disabling the new admin console: `--features-disabled=admin2`?
