### ISSUE TITLE
Operator secrets sequencing

### ISSUE THREAD

**Issue by Bengreen** [keycloak/keycloak#22170] opened 2023-08-02 05:05 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

When deploying using the operator the operator checks if the db secrets exist and if they do not then it stops further deployment.

If the secrets are later provisioned this does not get picked up by the operator so the deployment becomes stuck.

Successful deployment requires the secrets are in place prior to creating the keycloak definition. This makes an implied sequencing.

Ideally the operator will retry the creation of the deployment/statefulset or it will create the stateful regardless of the secret and allow the sts and pod operations to implement the retries.

### Version

22.0.0

### Expected behavior

Creation of the stateless set occurs regardless of the presence of the db credentials secret or the operator checks for presence of secrets after a timeout

### Actual behavior

After the initial check for secrets when the keycloak object is created and faulted no further updates or progress is made.

### How to Reproduce?

Create a keycloak definition using secret references to db username and password referring to a secret that does not exist.
The stateful set will not be created.
Create the appropriate secret.
The operator will not update.

Now delete the keycloak object then recreate.
The stateful set is now constructed. Showing that the operator has an implied sequencing that should ideally be removed or avoided to ensure consistent deployments

**Comment by shawkins** [comment] 2023-08-02 11:21
This is not reproducible for me.  If you check the operator logs when a keycloak is not ready the reconciliation should be retried at 10 second intervals, which should pickup the Secrets once they are created.

**Comment by vmuzikar** [comment] 2023-08-03 15:42
@Bengreen Thanks for the report. Closing this as we are unable to reproduce.

**Comment by Bengreen** [comment] 2023-08-12 19:49
I have tried this a few times and I am finding it very easy to create this error using the following sequence:

Follow the notes here: https://www.keycloak.org/operator/basic-deployment
But do not create the secret for the db. (keycloak-db-secret)

then create the Keycloak definition as below.

`apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    httpPort: 8080
    httpEnabled: true
  hostname:
    strict: false
  ingress:
      enabled: false
`

If you watch the operator as this is applied you can see it failing with a java stack error as a 404 trying to access the secret:

`Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1:443/api/v1/namespaces/keycloak/secrets/keycloak-db-secret. Message: secrets "keycloak-db-secret" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=secrets, name=keycloak-db-secret, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=secrets "keycloak-db-secret" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
`

As you described @shawkins this does repeat and retry after (not 10 seconds but much lower). BUT it does not continue to do this and fails permanently after a set number of tries (not sure exactly how many.... looks to be approx 5-10).

After that point it no longer checks for the secrets.
From creation to no longer trying takes: about 20secs
ie from `2023-08-12 19:45:45,938` until `2023-08-12 19:46:04,601`

If I now create the relevant secret on the cluster.
`kubectl -n keycloak create secret generic keycloak-db-secret --from-literal=username=keycloak --from-literal=password=pgpw1`
Nothing happens as the operator has stopped watching.

This makes the operator dependant upon the order of the secret creation and therefore not idempotent.
As a result this requires that the operator must use a sequencing around it to make it work correctly.

**Comment by shawkins** [comment] 2023-08-12 20:25
I don't think I gave the system long enough to settle down into a failure state when I locally tested creating the secret after the deployment.  The issue is that the we are not getting to the 10 second retry, but the general KeycloakController.updateErrorStatus - which does not allow for specifying a rety and instead will simply exhaust the default operator sdk retries eventually.

A workaround is to add a label operator.keycloak.org/component=watched-secret to your secret, that will then casue the reconciliation to complete.

**Comment by Bengreen** [comment] 2023-08-13 10:09
I tried that but unfortunately the operator does not take it on and insteads cleans up the label. (ie removes it).

    2023-08-13 10:07:23,151 INFO  [org.key.ope.con.WatchedSecretsStore] (-927557408-pool-9-thread-5) No CRs watching "keycloak-db-secret" Secret, cleaning up labels


Any other ideas?

**Comment by shawkins** [comment] 2023-08-13 10:21
Right, the exception is inhibiting the creation of the statefulset.  So it
would take modifying or recreating the keycloak cr to trigger the full
reconciliation.

**Comment by Bengreen** [comment] 2023-08-13 10:30
That is what I was worrying about so the order is very specific for the keycloak operator.

When we use this in our production systems we deploy all items to Kubernetes via CD and do not control order (ie k8s best practice).

Is it necessary that the operator needs to stall the creation of the Statefuleset as the statefulset itself will already stall when the secret is not available and start when the secret becomes available?

**Comment by shawkins** [comment] 2023-08-13 10:59
> Is it necessary that the operator needs to stall the creation of the Statefuleset as the statefulset itself will already stall when the secret is not available and start when the secret becomes available?

Please see #22404 - there will also be some continued discussion on there about what the right approach is in general

**Comment by Daniel-Fan** [comment] 2023-08-24 18:58
Hi Team, I was able to reproduce the issue.

The installation flow is
1. Create KeyCloak CR
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: cs-keycloak
  namespace: keycloak-integration
spec:
  db:
    host: keycloak-edb-cluster-rw
    passwordSecret:
      key: password
      name: keycloak-edb-cluster-app
    usernameSecret:
      key: username
      name: keycloak-edb-cluster-app
    vendor: postgres
  hostname:
    strict: false
  http:
    tlsSecret: cs-ca-certificate-secret
  ingress:
    className: openshift-default
    enabled: true
  instances: 1
```
2. Create EDB postgreSQL `Cluster` Kind CR to provision KeyCloak.
```

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: keycloak-edb-cluster
  namespace: keycloak-integration
spec:
    bootstrap:
      initdb:
        database: keycloak
        owner: app
    instances: 1
    logLevel: info
    primaryUpdateStrategy: unsupervised
    storage:
      size: 1Gi
    walStorage:
      size: 1Gi
```

When KeyCloak Operator starts to reconcile the CR, it raise error on missing secret `keycloak-edb-cluster-app`.
```
2023-08-23 18:07:05,181 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-keycloakcontroller-72) Error during event processing ExecutionScope{ resource id: ResourceID{name='cs-keycloak', namespace='keycloak-integration'}, version: 159092995} failed.: io.fabric8.kubernetes.client.ResourceNotFoundException: Resource couldn't be fetched : Failure executing: GET at: https://172.30.0.1:443/api/v1/namespaces/keycloak-integration/secrets/keycloak-edb-cluster-app. Message: secrets "keycloak-edb-cluster-app" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=secrets, name=keycloak-edb-cluster-app, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=secrets "keycloak-edb-cluster-app" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.require(BaseOperation.java:155)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.require(BaseOperation.java:92)
	at org.keycloak.operator.controllers.WatchedSecretsStore.lambda$fetchCurrentSecrets$3(WatchedSecretsStore.java:158)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.operator.controllers.WatchedSecretsStore.fetchCurrentSecrets(WatchedSecretsStore.java:159)
	at org.keycloak.operator.controllers.WatchedSecretsStore.<init>(WatchedSecretsStore.java:70)
	at org.keycloak.operator.controllers.KeycloakController.reconcile(KeycloakController.java:110)
	at org.keycloak.operator.controllers.KeycloakController.reconcile(KeycloakController.java:49)
	at org.keycloak.operator.controllers.KeycloakController_ClientProxy.reconcile(Unknown Source)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:152)
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:110)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:219)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:109)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:140)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:121)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:91)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:64)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:409)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1:443/api/v1/namespaces/keycloak-integration/secrets/keycloak-edb-cluster-app. Message: secrets "keycloak-edb-cluster-app" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=secrets, name=keycloak-edb-cluster-app, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=secrets "keycloak-edb-cluster-app" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:478)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:741)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:185)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.require(BaseOperation.java:153)
	... 26 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1:443/api/v1/namespaces/keycloak-integration/secrets/keycloak-edb-cluster-app. Message: secrets "keycloak-edb-cluster-app" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=secrets, name=keycloak-edb-cluster-app, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=secrets "keycloak-edb-cluster-app" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:671)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:651)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:600)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:560)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:140)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.vertx.VertxHttpRequest.lambda$null$1(VertxHttpRequest.java:122)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:444)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:708)
	at io.vertx.core.impl.EventLoopContext.lambda$execute$2(EventLoopContext.java:78)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

2023-08-23 18:07:05,182 ERROR [io.jav.ope.pro.eve.EventProcessor] (ReconcilerExecutor-keycloakcontroller-72) Exhausted retries for ExecutionScope{ resource id: ResourceID{name='cs-keycloak', namespace='keycloak-integration'}, version: 159092995}
```

But it does not re-queue the KeyCloak CR reconciliation when this error happens.
When the secret shows up in the namespace, KeyCloak operator stays silent and does not proceed. So I have to manually restart the operator pod to trigger a reconciliation

**Comment by Bengreen** [comment] 2023-08-24 20:33
I have found that updating a dummy environment var on keycloak object is
best way to trigger operator to re-process.
Not ideal but works for temporary until get a better option in place.

**Closed** 2023-09-01 08:34 UTC
Labels: kind/bug, team/cloud-native, area/operator
