### ISSUE TITLE
How to refresh exchanged token by target (audience) client?

### ISSUE THREAD

**Issue by gassan** [keycloak/keycloak#15330] opened 2022-11-03 16:04 UTC
### Area

oidc

### Describe the bug

1. The **Original Client** requests an exchange token for another internal **Target Client** and
2. Passes it to the **Target Service**.
4. It works fine, but after 5 minutes the token expires and when the **Target Client** requests a new access token with the own `id` and `secret`, an error message is thrown: "Invalid refresh token. Token client and authorized client don't match".

What is the right way to refresh exchanged token?

### Version

18-20

### Expected behavior

An exchange token requested by **Original Client** for **Target Client** should be allowed to be refreshed by **Target Client**

### Actual behavior

An error message is thrown: "Invalid refresh token. Token client and authorized client don't match".

### How to Reproduce?

Create 2 clients and allow the **Original Client** to request an exchange token for **Target Client**.

https://keycloak.ch/keycloak-tutorials/tutorial-token-exchange/#step-1%3A-enabling-token-exchange-in

### Anything else?

May be make following check turnable (config var)? So we could request with OriginalClient access token an exchange token with Target Client id and secret. (it works without `admin_fine_grained_authz` feature)
https://github.com/keycloak/keycloak/blob/f616495b051ae9555fe97df0e269c8332401b8d5/services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java#L320-L323

**Comment by belinde** [comment] 2023-03-01 16:34
I think I have the same problem. I think the problem could be in the generated refresh token: the **aud** field has a the same value of **iss**, but I'd expect to be the Target Client (like for the Access Token) 

Here's an example, this is the refresh token got by my backend client **restApi** to the frontend client **Frontend**. "Frontend does not appear anywhere in the token, so it correctly cannot exchange the refresh token autonomously.

```json
{
  "exp": 1677729935,
  "iat": 1677686735,
  "jti": "9ce5e9bd-9803-43be-9152-5c6abc3f0b09",
  "iss": "https://auth.contoaperto.com/realms/ContoApertoLocal",
  "aud": "https://auth.contoaperto.com/realms/ContoApertoLocal",
  "sub": "091d1714-77a3-4573-b970-8ab715e2eab6",
  "typ": "Refresh",
  "azp": "restAPI",
  "session_state": "15739ac2-8b47-40bb-a867-416b3cf87df9",
  "scope": "email customer merchant profile",
  "sid": "15739ac2-8b47-40bb-a867-416b3cf87df9"
}
```

**Comment by davide-talesco** [comment] 2023-03-04 08:46
Hi we have the same issue. I believe the problem is with the azp field which is the original client that exchanged the token for the target client. Keycloak should allow both exchanged token original client and target client to refresh it but looks like it is only allowing the original client... Am I right?

**Comment by mposolda** [comment] 2023-04-04 09:54
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by patrykpacewicz** [comment] 2023-07-17 19:29
> ```json
>   "aud": "https://auth.contoaperto.com/realms/ContoApertoLocal",
> ```

The issue still exists in the latest version as well (keycloak 22.0.0)

**Closed** 2023-09-11 13:37 UTC
Labels: kind/bug, area/token-exchange, status/triage, team/core

**Comment by JRDVN** [comment] 2023-10-04 15:35
I have the exact same issue here. In my case it happens in an impersonation scenario where public client A allows a user to impersonate user from another application, public client B. [This case is described in keycloak google discussion forum](https://groups.google.com/g/keycloak-user/c/EsdY0M_odeg/m/ybIxwXEWBAAJ?utm_medium=email&utm_source=footer).

@pedroigor If I get it right, to allow client B to refresh tokens, client B should do a token exchange to get a refresh token issued for himself (with azp set to client B id)? But how do I keep the fact that user is impersonated by another user(because a new access token will be returned as well), and how to get the refresh token for the impersonated user?
