### ISSUE TITLE
Memory leak pathcache

### ISSUE THREAD

**Issue by avijain7143** [keycloak/keycloak#11098] opened 2022-04-04 13:30 UTC
### Describe the bug

We have been observing some memory leak on keycloak side. 

Attaching 2 different snapshots for the memory leak occurred in different times.

![image](https://user-images.githubusercontent.com/26165673/165316889-f0e47b36-e914-4efa-82de-e231191aa82b.png)
![image](https://user-images.githubusercontent.com/26165673/165316938-3c644c13-b593-4c13-8545-a1ec54ed03e9.png)

Uses : 
PolicyEnforcerConfig enforcerConfig -> PolicyEnforcer -> getEnforcerConfig()
PathCacheConfig cacheConfig = enforcerConfig.getPathCacheConfig();
pathCache = new PathCache(cacheConfig.getMaxEntries(), cacheConfig.getLifespan());

Reason for extending org.keycloak.adapters.authorization.PolicyEnforcer.PathConfigMatcher 
overirde method matches.

Please see implementation of this class - 

public class PathConfigMatcherProxy extends org.keycloak.adapters.authorization.PolicyEnforcer.PathConfigMatcher 
    {
    	private final Map<String, PathConfig> paths;
    	private final PathCache pathCache;
    	private final AuthzClient authzClient;
    	private final PolicyEnforcerConfig enforcerConfig;

    	public PathConfigMatcherProxy(Map<String, PathConfig> paths, PolicyEnforcerConfig enforcerConfig, AuthzClient authzClient) 
    	{
    		super(paths, enforcerConfig, authzClient);
    		this.paths = paths;
    		this.enforcerConfig = enforcerConfig;
    		PathCacheConfig cacheConfig = enforcerConfig.getPathCacheConfig();

    		if (cacheConfig == null) {
    			cacheConfig = new PathCacheConfig();
    		}

    		pathCache = new PathCache(cacheConfig.getMaxEntries(), cacheConfig.getLifespan());
    		this.authzClient = authzClient;

    	}

    	private boolean checkMatches(String uriTemplate, String path) 
    	{
    		PathPatternParser parser = new PathPatternParser();
    		parser.setMatchOptionalTrailingSeparator(true);
    		PathPattern p = parser.parse(uriTemplate);
    		PathContainer pc = toPathContainer(path);
    		return p.matches(pc);
    	}

    	private PathContainer toPathContainer(String path) 
    	{
    		if (path == null) 
    		{
    			return null;
    		}
    		return PathContainer.parsePath(path);
    	}

    	@Override
    	public PathConfig matches(String targetUri) 
    	{
    		PathConfig pathConfig = pathCache.get(targetUri);

    		if (pathCache.containsKey(targetUri) || pathConfig != null) 
    		{
    			return pathConfig;
    		}

    		List<PathConfig> matchWithwildcards = new ArrayList<>();
    		for (PathConfig entry : getPaths()) 
    		{
    			StringBuilder resourceUri = new StringBuilder(entry.getPath());
    			log.debug("Matching resource URI {} with target URI {}.", resourceUri, targetUri);
    			if(!StringUtils.isEmpty(entry.getPath()) && entry.getPath().endsWith("/*"))
    			{
    				resourceUri.append("*");
    			}
    			if(checkMatches(resourceUri.toString(), targetUri))
    			{
    				log.debug("Target URI macthed with resource: {}", resourceUri);
    				if(!resourceUri.toString().contains("*"))
        			{
        				log.debug("No *");
        				pathConfig = entry;
        				break;
        			}
    				else
    				{
    					matchWithwildcards.add(entry);
    				}
    			}
    		}
    		
    		if(pathConfig == null)
    		{
    			if(!CollectionUtils.isEmpty(matchWithwildcards) && matchWithwildcards.size()==1)
    			{
    				pathConfig = matchWithwildcards.get(0);
    				log.debug("Path config get 0 : " + pathConfig.getPath());
    			}
    			else if(!CollectionUtils.isEmpty(matchWithwildcards))
    			{
    				Map<Integer, PathConfig> sizePathMap = new HashMap<>();
    				for(PathConfig wildCardMatch:matchWithwildcards)
    				{
    					int SplitSize = wildCardMatch.getPath().split("/").length;
    					sizePathMap.put(SplitSize, wildCardMatch);
    					log.debug("Made map entry for {}", wildCardMatch.getPath());
    				}
    				Integer maxMatch = Collections.max(sizePathMap.keySet());
    				pathConfig = sizePathMap.get(maxMatch);
    				log.debug("Pathconfig: {}", pathConfig.getPath());
    			}
    		}

    		if (enforcerConfig.getLazyLoadPaths() || enforcerConfig.getPathCacheConfig() != null) 
    		{
    			if ((pathConfig == null || (pathConfig.getPath().contains("*")))) 
    			{
    				try 
    				{
    					List<ResourceRepresentation> matchingResources = authzClient.protection().resource().findByMatchingUri(targetUri);

    					if (!matchingResources.isEmpty()) 
    					{
    						Map<String, Map<String, Object>> cipConfig = null;
    						PolicyEnforcerConfig.EnforcementMode enforcementMode = PolicyEnforcerConfig.EnforcementMode.ENFORCING;

    						if (pathConfig != null) 
    						{
    							cipConfig = pathConfig.getClaimInformationPointConfig();
    							enforcementMode = pathConfig.getEnforcementMode();
    						}

    						pathConfig = PathConfig.createPathConfigs(matchingResources.get(0)).iterator().next();

    						if (cipConfig != null) 
    						{
    							pathConfig.setClaimInformationPointConfig(cipConfig);
    						}
    						pathConfig.setEnforcementMode(enforcementMode);
    					}
    				} catch (Exception cause) 
    				{
    					log.error("Could not lazy load resource with path [" + targetUri + "] from server");
    					return null;
    				}
    			}
    		}

    		pathCache.put(targetUri, pathConfig);
    		return pathConfig;
    	}

    	@Override
    	protected String getPath(PathConfig entry) {
    		return entry.getPath();
    	}

    	@Override
    	protected Collection<PathConfig> getPaths() {
    		return paths.values();
    	}

    	public PathCache getPathCache() {
    		return pathCache;
    	}

    	public void removeFromCache(String pathConfig) {
    		pathCache.remove(pathConfig);
    	}
    }

### Version

14

### Expected behavior

There should be no memory leak issue.

### Actual behavior

Memory leak

### How to Reproduce?

Ran traffic for 72 hrs.

### Anything else?

heaphero analysis - https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMi8wMy8zMC8tLWhlYXBkdW1wICgyNiktOC0xMi0xNC5qc29u

**Comment by avijain7143** [comment] 2022-04-06 13:41
Kindly suggest on this issue if we should upgrade the version or something else, would really appreciate a quick response on this one. :)

**Comment by pedroigor** [comment] 2022-04-08 13:57
@avijain7143 Thanks.

I'm a bit lost why the `max-entries` setting is not forcing a hard limit on the number of cached entries.

Does it happens with your implementation or it is a problem with the `PathConfigMatcher` itself?

**Comment by avinashjain7143** [comment] 2022-04-12 13:39
@pedroigor Thanks for your response.

I am using the default, whatever provided by the PathConfigMatcher class itself.

**Comment by avijain7143** [comment] 2022-04-12 13:40
@pedroigor Thanks for your response.

I am using the default, whatever provided by the PathConfigMatcher class itself.

**Comment by avijain7143** [comment] 2022-04-13 06:24
@pedroigor If I need to support keycloak 14 version only - what would be the workaround for that? Can you please help with that?

**Comment by pedroigor** [comment] 2022-04-13 11:38
@avijain7143 I would start porting the changes from `KEYCLOAK-13942`. If the issue still persist than I'm afraid we need to check if the error persists in the latest versions. And ideally, upgrade.

You should probably consider upgrading anyways because of the fixes (including CVEs) we had since then.

**Comment by avijain7143** [comment] 2022-04-29 12:11
I get this error in my kubernetes pod logs - any specific reason? I will plan to upgrade the keycloak version in near future but just need some quick solution for now, please help.

ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-232) Uncaught server error: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 915035 from common-services-auth-2
        at org.infinispan@11.0.9.Final//org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:255)
        at org.infinispan@11.0.9.Final//org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:298)
        at org.infinispan@11.0.9.Final//org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:102)
        at org.infinispan@11.0.9.Final//org.infinispan.cache.impl.CacheImpl.get(CacheImpl.java:540)
        at org.infinispan@11.0.9.Final//org.infinispan.cache.impl.CacheImpl.get(CacheImpl.java:534)
        at org.infinispan@11.0.9.Final//org.infinispan.cache.impl.AbstractDelegatingCache.get(AbstractDelegatingCache.java:439)
        at org.infinispan@11.0.9.Final//org.infinispan.cache.impl.EncoderCache.get(EncoderCache.java:696)
        at org.infinispan@11.0.9.Final//org.infinispan.cache.impl.AbstractDelegatingCache.get(AbstractDelegatingCache.java:439)
        at org.keycloak.keycloak-model-infinispan@14.0.0//org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.get(InfinispanChangelogBasedTransaction.java:128)
        at org.keycloak.keycloak-model-infinispan@14.0.0//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionEntity(InfinispanUserSessionProvider.java:326)
        at org.keycloak.keycloak-model-infinispan@14.0.0//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:259)
        at org.keycloak.keycloak-model-infinispan@14.0.0//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:254)
        at org.keycloak.keycloak-services@14.0.0//org.keycloak.services.managers.AuthenticationManager.verifyIdentityToken(AuthenticationManager.java:1380)
        at org.keycloak.keycloak-services@14.0.0//org.keycloak.services.managers.AppAuthManager$BearerTokenAuthenticator.authenticate(AppAuthManager.java:167)
        at org.keycloak.keycloak-services@14.0.0//org.keycloak.services.resources.admin.AdminRoot.authenticateRealmAdminRequest(AdminRoot.java:175)
        at org.keycloak.keycloak-services@14.0.0//org.keycloak.services.resources.admin.AdminRoot.getRealmsAdmin(AdminRoot.java:211)
        at jdk.internal.reflect.GeneratedMethodAccessor425.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.createResource(ResourceLocatorInvoker.java:73)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.createResource(ResourceLocatorInvoker.java:52)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:103)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)

**Comment by avijain7143** [comment] 2022-05-02 07:32
I see that sessions keeps on increasing in the infinispan cache and which is leading to OOM to me. I tried to increase the resources in my pods but after few hours of traffic run using jmeter I am still getting same issue. 
What is the way to get the number of active sessions in infinispan cache, basically I need the cache size so that can be used to track that it requires x memory for n number of sessions.
Appreciate the response.

**Comment by pedroigor** [comment] 2022-08-08 12:24
I'm not sure what we can do more here but try it out using the latest versions. It is easier for us to reproduce errors using the latest versions because of the changes that were made over time.

Please, let me know if we should continue discussing this problem. For now, I'm closing it.

**Closed by pedroigor** 2022-08-08 12:24 UTC
Labels: area/authorization-services, kind/bug, status/triage
