### ISSUE TITLE
Queries for LDAP-linked users are extremely slow

### ISSUE THREAD

**Issue by jalfd** [keycloak/keycloak#16244] opened 2023-01-04 11:48 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

Any query for users using the REST API are extremely slow, if the users in question are imported from LDAP.

For example, the query `GET /realms/$REALM/users` which returns 100 users on my machine, takes almost 24 seconds to complete. A query for a specific username (`/users?username=$FOO`) takes over half a second.
I suspect the problem is that the LDAP server is queried for every user, instead of just responding with users from Keycloak's own database.

The same does not appear to be the case when an OIDC ID token is generated. That is much faster, suggesting that user information is taken from Keycloak's database without checking the LDAP server.

I suggest using this behavior with the REST API as well: since Keycloak has already synced users from LDAP to its database, use that to provide the response.

### Version

20

### Expected behavior

A query like `GET /realms/$REALM/users` takes time measured in milliseconds

### Actual behavior

A query like `GET /realms/$REALM/users` takes time measured in tens of seconds.

### How to Reproduce?

1. Set up LDAP User Federation and synchronize users from the LDAP server.
2. Using the REST API, query for a set of users (/realms/$REALM/users or even /realms/$REALM/users?username=$MYUSER). The response time varies depending on the number of retrieved users, but I'm seeing at least hundreds of milliseconds per user (half a second for a single user query, 24 seconds if requesting 100 different users)

The problem is also visible in the web management UI. Simply select a realm, go to Users, type in a username and click search. You would expect the user to appear instantly, but it visibly spends a long time loading before presenting the result

**Comment by tsondergaard** [comment] 2023-01-10 14:34
See also #10005.

**Comment by tsondergaard** [comment] 2023-01-13 14:32
Note: updates are very fast if the LDAP provider is not configured to "Import Users" - in this case it makes a single LDAP query to LDAP to retrieve all the information. If "Import Users" is enabled it instead makes an ldap query per-user which is extremely slow for an LDAP (Active Directory) server with e.g 5000 users.

A curious detail is that `GET /realms/{realm}/users` returns `[]` if the realm is configured with an LDAP provider with "Import Users" disabled - instead it is necessary to use `GET /realms/{realm}/users?username=*` to get responses. An this query on the other hand doesn't work if "Import users" is checked because that code-path treats the username parameter as a username substring and doesn't allow the explicit use of `*`. That means the user of this REST API *must* know whether "Import Users" is checked or not. Not ideal.

**Comment by hmlnarik** [comment] 2023-02-17 12:56
Duplicate of #10005

**Comment by hmlnarik** [comment] 2023-02-17 12:57
Thank you for the report. I am closing in favour of #10005

**Closed by hmlnarik** 2023-02-17 12:57 UTC
Labels: kind/bug, area/ldap, status/triage
