### ISSUE TITLE
Can't create user via api after I changed email settings

### ISSUE THREAD

**Issue by mohamadvp** [keycloak/keycloak#25483] opened 2023-12-12 06:30 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

I have made an admin panel for my customers and in there, I have a user creation form, the user creation form was working fine but I changed some login settings and now it's not working, no user is created and I'm getting this error from the API:

``{"errorMessage":"User name is missing"}``

the object which I'm sending is this:

``
{
  "username": "test",
  "email": null,
  "enabled": true
}
``

and the new login settings are these:

![photo1702361554 (1)](https://github.com/keycloak/keycloak/assets/109647992/f2443422-4972-4da3-b90b-d96b961a113b)

I want to know what has causes this issue and how can I fix it.

### Version

23.0.1

### Expected behavior

User should be created with the object which I'm sending to the API

### Actual behavior

I get an error which says "User name is missing"

### How to Reproduce?

Not sure but probably if you set the settings as I did and send the object which I did, you'd probably get the same error too.

**Comment by mohamadvp** [comment] 2023-12-13 11:58
I turned off the Email as Username option and now I can create users with the same data that I was sending before, but I don't think that it should behave like this. I mean that email shouldn't become the source of truth and if it exists it COULD be used instead of the username.

**Comment by pedroigor** [comment] 2024-02-22 13:32
@mohamadvp When you set `Email as username`, `email` is mandatory and should be sent whenever you are updating the user. Note that Keycloak does not support PATCH operations so you need to always send the entire user representation.

The meaning of that flag is to actually use the `email` as the source of truth for looking up users. In fact, the `username` is automatically updated to the value you set to the `email`.

For that reason, I'm closing as not a bug.

**Closed by pedroigor** 2024-02-22 13:32 UTC
Labels: kind/bug, area/account/api, status/triage, team/core-iam
