### ISSUE TITLE
Revoking consent breaks for certain client IDs

### ISSUE THREAD

**Issue by svenseeberg** [keycloak/keycloak#12738] opened 2022-06-24 21:52 UTC
### Describe the bug

If the client has an URL as client ID, revoking the consent for a user returns a 404 not found.

For example the Nextcloud SSO/SAML app requires that the full URL `https://nextcloud.example.com/apps/user_saml/saml/metadata` is set as the client id.

If I try to revoke the consent for a user, the HTTP DELETE request (`https://keycloak.example.com/admin/realms/my-realm/users/ceffa2ee-acce-4608-bfcb-f82f7447f8fd/consents/https:%2F%2Fnextcloud.example.com%2Fapps%2Fuser_saml%2Fsaml%2Fmetadata`) returns a 404 and no further error.

### Version

18.0.1

### Expected behavior

The consent for all valid client IDs should be revocable.

### Actual behavior

Revoking a consent for a client with URL as client id does not work.

### How to Reproduce?

Set a URL as client ID

**Comment by chrisx8** [comment] 2023-03-15 15:16
Can confirm this is still an issue in Keycloak 21.0.1, with both the v2 Account Console and the v2 Admin Console. This essentially makes SAML client consents unrevokable, as many SAML SPs use URLs as their EntityID.

**Comment by svenseeberg** [comment] 2023-03-15 15:47
Yes, this is still a problem in Keycloak 21.0.1.

**Comment by mposolda** [comment] 2023-03-22 15:34
Looks like a regression, so adding to Keycloak 22 for now.

**Comment by rmartinc** [comment] 2023-04-04 07:43
OK, I have filed a new issue for the UI team just mentioning the account v2 bug. It's #19515. I thought it was better start afresh and explain just that issue.

I'm going to close this one as server side seems to be working OK.

Thanks!

**Closed by rmartinc** 2023-04-04 07:43 UTC
Labels: kind/bug, impact/medium, area/account/ui, team/ui

**Comment by bonnm** [comment] 2023-08-29 09:23
After a little investigation, I found that the problem occurrs with slashes ('/') in the clientID and only when Keycloak is running **behind an Apache proxy**. The 404 not found response comes very fast without Keycloak doing a database query. So I think that Apache is modifying or encodiung the relevant parts of the path (which includes the clientID) in a way so that the URL router on Keycloak side is not able to map the request to the coresponding API method implementation.
When connecting the browser direclty to Keycloak without proy, everything works fine.

**Comment by svenseeberg** [comment] 2023-09-05 17:08
We're using Nginx. Does anyone know how to solve the issue there?
