### ISSUE TITLE
Login with Github errors with class cast exception when user chooses to keep their email addresses private

### ISSUE THREAD

**Issue by prisamuel** [keycloak/keycloak#9429] opened 2022-01-07 14:37 UTC
### Describe the bug

Keycloak errors out with an IDENTITY_PROVIDER_LOGIN_ERROR and shows a 502 error page when a user chooses to login with Github. This only occurs when the user has decided to make their email address private on Github pages. Irrespective of what the user chooses to show or not show on their public Github account, an OIDC exchange for credentials should return back a email address if the scope has the appropriate entries (user:email, in this case).

### Version

15.0.2

### Expected behavior

Irrespective of whether the user opts to show their email on their public profile on Github, when doing an OIDC flow, the service provider should be able to access the user's email address if they include the appropriate scope parameter.

### Actual behavior

<img width="1607" alt="Screenshot 2022-01-07 at 16 51 36" src="https://user-images.githubusercontent.com/151395/148558487-77fd3e7e-e91f-4460-a954-af821189657c.png">

### How to Reproduce?

1. Connect an application that uses keycloak to provide the ability to 'Login with Github'. 
<img width="1688" alt="Screenshot 2022-01-07 at 16 51 14" src="https://user-images.githubusercontent.com/151395/148558408-0a5cc81f-4fc8-4b13-b8bf-b04a9902fd35.png">

2. Login with a Github account that has the box "Keep my email addresses private" checked.
<img width="1702" alt="Screenshot 2022-01-07 at 16 51 24" src="https://user-images.githubusercontent.com/151395/148558428-f0a453e1-afb5-44cd-81d8-fb82f515ecf6.png">

3. Keycloak will return as error page.
<img width="1607" alt="Screenshot 2022-01-07 at 16 51 36" src="https://user-images.githubusercontent.com/151395/148558445-badc4dc0-1152-4d76-a61f-c8eb518f0f44.png">

### Anything else?

Need to investigate how the user profile is accessed by keycloak during this exchange.

Context: On GitHub profile settings, under Public email, some users (including myself) have that option set to "Don't show my email address." The call to /user only returns the public email address, so if the user doesn't want it shown, the API will respect that. To get the user's email addresses regardless of whether or not they are public, use the call to /user/emails with the appropriate access token included.

I believe the error is from here:
```
Caused by: org.keycloak.broker.provider.IdentityBrokerException: Could not obtain user email from github.
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.social.github.GitHubIdentityProvider.searchEmail(GitHubIdentityProvider.java:108)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.social.github.GitHubIdentityProvider.doGetFederatedIdentity(GitHubIdentityProvider.java:87)
        ... 78 more
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.ObjectNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader 'com.fasterxml.jackson.core.jackson-databind@2.12.1' @27b76147)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.social.github.GitHubIdentityProvider.searchEmail(GitHubIdentityProvider.java:98)
        ... 79 more
```

Full Keycloak logs with error lines:
```
11:15:03,177 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-18) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: Could not obtain user profile from github.
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.social.github.GitHubIdentityProvider.doGetFederatedIdentity(GitHubIdentityProvider.java:92)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.getFederatedIdentity(AbstractOAuth2IdentityProvider.java:306)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:502)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.keycloak.keycloak-wildfly-extensions@15.0.2//org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
        at org.keycloak.keycloak-wildfly-extensions@15.0.2//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
        at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
        at io.undertow.core@2.2.5.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
        at io.undertow.core@2.2.5.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.keycloak.broker.provider.IdentityBrokerException: Could not obtain user email from github.
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.social.github.GitHubIdentityProvider.searchEmail(GitHubIdentityProvider.java:108)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.social.github.GitHubIdentityProvider.doGetFederatedIdentity(GitHubIdentityProvider.java:87)
        ... 78 more
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.ObjectNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader 'com.fasterxml.jackson.core.jackson-databind@2.12.1' @27b76147)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.social.github.GitHubIdentityProvider.searchEmail(GitHubIdentityProvider.java:98)
        ... 79 more

11:15:03,181 WARN  [org.keycloak.events] (default task-18) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=demo, clientId=xxx, userId=null, ipAddress=172.17.0.1, error=identity_provider_login_failure, code_id=cb103222-cc1e-4283-94c4-515f9c586a5b, authSessionParentId=cb103222-cc1e-4283-94c4-515f9c586a5b, authSessionTabId=ev8gVnMQEtU
11:17:05,613 WARN  [org.keycloak.events] (default task-18) type=LOGIN_ERROR, realmId=demo, clientId=xxx, userId=null, ipAddress=172.17.0.1, error=user_not_found, auth_method=openid-connect, auth_type=code, redirect_uri=http://localhost:8081/blah/, code_id=cb103222-cc1e-4283-94c4-515f9c586a5b, authSessionParentId=cb103222-cc1e-4283-94c4-515f9c586a5b, authSessionTabId=iY_2P6iSQxE
```

**Comment by masteryyh** [comment] 2022-10-13 07:58
same issue here, can't get github identity provider working when user's email is private

**Comment by sternenseemann** [comment] 2022-11-09 22:04
We can also reproduce this and the cause (private emails) seems to check out as well.

My guess is the object that fails to cast is an error message from github, logging that somehow would help confirming the diagnosis.

**Comment by rmartinc** [comment] 2023-02-28 16:56
Hi!

I have tested this and I cannot reproduce the issue. So probably github has done something. I configured my email private in github and the when login to keycloak (via account page) I see that github presents a consent page saying the email is going to be shared.

![github](https://user-images.githubusercontent.com/26901232/221921341-a08bc105-37ce-4e1a-ba15-264531ced36c.png)

And after that I am correctly moved to the account page with username, email and name automatically set. So please test with the last version 21.0.0 and check if it's also working for you.

**Comment by prisamuel** [comment] 2023-03-06 11:42
Agreed, just tested this again and Github have changed the flow to consent and release private email field and this works now.

**Comment by sternenseemann** [comment] 2023-05-16 17:16
The issue disappeared for a while for us, but we've had an authorization failure today due to what appears to be the same issue (caused in `org.keycloak.social.github.GitHubIdentityProvider.searchEmail`) once again. Maybe GitHub reverted their change?

**Comment by prisamuel** [comment] 2023-05-16 20:47
Sigh, keycloak should still handle this scenario gracefully with a better error page/message. I've linked a screenshot of the page above. Given that Github changes their implementation, the best keycloak could do is to display a nicer error to the user that their email was released by the 3rd party IDP (Github) here.

**Comment by muradm** [comment] 2023-05-29 22:58
same issue here

**Comment by prisamuel** [comment] 2023-05-30 09:54
Reopening issue given the reports mentioned above.

**Comment by rmartinc** [comment] 2023-05-30 11:09
Hi!

I have tested this again and the github provider is still working with my setup. We cannot do more if we don't know exactly what to test. I have a user with "Keep my email addresses private" set in github. And I can login with it perfectly in keycloak. I see that the email is received in the method `searchEmail` (the one that is failing in those stracktraces) and I receive this array:

```json
[{"email":"****","primary":true,"verified":true,"visibility":"private"},{"email":"1576140+****@users.noreply.github.com","primary":false,"verified":true,"visibility":null}]
```

Can someone please check what json is received when the error is displayed? I suppose some type of error is received.

The only thing we can do with this information is not making the email compulsory as it's now. Right now if the emails is not retrieved there is an exception.

**Comment by sternenseemann** [comment] 2023-06-03 11:45
@rmartinc I've got a report of a successful login again today, so it seems that something changed on GitHub's side again.

**Comment by muradm** [comment] 2023-06-05 03:19
@rmartinc I'm still getting same exception, just tried. I don't think this happens in browser, but server side. Since all interactions with GitHub happen via HTTPS there is no point in getting dumps. If you could point at what logger at what level would log the needed thing, we may try to collect the data.

**Comment by muradm** [comment] 2023-06-05 16:43
@rmartinc indeed, setting "Public email" on GitHub account from nothing to some verified email workarounds issue. Still this requires solution, since it is virtually impossible to ask every potential user update their GitHub account.

**Comment by muradm** [comment] 2023-06-06 13:26
@rmartinc, here the JSON in your example:
```
[{"email":"****","primary":true,"verified":true,"visibility":"private"},{"email":"26901232+rmartinc@users.noreply.github.com","primary":false,"verified":true,"visibility":null}]
```
it includes:
```
"email":"26901232+rmartinc@users.noreply.github.com"
```
That feature is turned on for you. I suspect that this feature, called `Keep my email addresses private`. It is configurable at `Settings -> Emails`. When it is enabled, GitHub generates that weird mail address.

That means that there are 3 states:
|No|Public email|Keep my email addresses private|Result|
|---|---|---|---|
|1|set|enabled|no problem (array with to elements as in your JSON)|
|2|unset|enabled|no problem (again no problem, because at least one email is available)|
|3|unset|disabled|subject exception (no public email, no private email, probably null or empty object return there)|

From your JSON, I suspect that you are on case 2, if you unset public email or on case 1 if you set public email. However, exception seems to happen on case 3, where I am.

I'm ruling out case about old tokens, because it is very fresh setup for us.

I will try to find a way to run your branch, but later..

**Comment by rmartinc** [comment] 2023-06-06 13:57
OK @muradm, maybe the result is just not an array, but a single json object. I'll also try later or tomorrow.

**Comment by rmartinc** [comment] 2023-06-07 08:51
Ah! OK, I was always using an OAuth application in github. The documentation already states that you have to use [an OAuth application](https://www.keycloak.org/docs/21.1.1/server_admin/index.html#_github). I just followed it to configure my sample app.

But it would be nice to modify the github social provider to better manage the errors and display the responses when the endpoints return errors. I moving this issue to backlog and I'll try to do that when I have time. Probably tests need also changes  because social tests are always a pain as they cannot be easily run in CI. If someone wants to work on this just let me know.

**Closed** 2023-07-10 19:09 UTC
Labels: area/oidc, kind/bug
