### ISSUE TITLE
Failed to update database (MySQL)

### ISSUE THREAD

**Issue by hfastek** [keycloak/keycloak#28454] opened 2024-04-04 21:58 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

- new keycloak installation
- AWS RDS MySQL 8.0.35
- Keycloak - custom image created from 22.0.5 (same error on 23.0.6) image, StatefulSet, replicaCount: 2

logs:

```
2023-12-14 08:48:35,958 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-12-14 08:48:39,857 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-12-14 08:48:39,857 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-12-14 08:48:39,987 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
2023-12-14 08:48:43,362 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-12-14 08:48:43,362 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-12-14 08:48:43,554 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-12-14 08:48:43,555 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2023-12-14 08:48:44,526 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com encountered an exception.
2023-12-14 08:48:44,674 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2023-12-14 08:48:44,713 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-12-14 08:48:44,713 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2023-12-14 08:48:44,714 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table 'MIGRATION_MODEL' already exists [Failed SQL: (1050) CREATE TABLE orchestrator_keycloak.MIGRATION_MODEL (ID VARCHAR(36) NOT NULL, VERSION VARCHAR(36) NULL)]
2023-12-14 08:48:44,714 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table 'MIGRATION_MODEL' already exists [Failed SQL: (1050) CREATE TABLE orchestrator_keycloak.MIGRATION_MODEL (ID VARCHAR(36) NOT NULL, VERSION VARCHAR(36) NULL)]
2023-12-14 08:48:44,714 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table 'MIGRATION_MODEL' already exists [Failed SQL: (1050) CREATE TABLE orchestrator_keycloak.MIGRATION_MODEL (ID VARCHAR(36) NOT NULL, VERSION VARCHAR(36) NULL)]
2023-12-14 08:48:44,714 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Table 'MIGRATION_MODEL' already exists [Failed SQL: (1050) CREATE TABLE orchestrator_keycloak.MIGRATION_MODEL (ID VARCHAR(36) NOT NULL, VERSION VARCHAR(36) NULL)]
2023-12-14 08:48:44,714 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Table 'MIGRATION_MODEL' already exists
2023-12-14 08:48:44,715 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

DATABASECHANGELOG:
```
ID                         AUTHOR               FILENAME                                    DATEEXECUTED              ORDEREXECUTED  EXECTYPE
1.0.0.Final-KEYCLOAK-5461  sthorger@redhat.com  META-INF/jpa-changelog-1.0.0.Final.xml      2023-12-14 08:37:46       1              EXECUTED
1.0.0.Final-KEYCLOAK-5461  sthorger@redhat.com  META-INF/db2-jpa-changelog-1.0.0.Final.xml  2023-12-14 08:37:46       2              MARK_RAN
1.1.0.Beta1                sthorger@redhat.com  META-INF/jpa-changelog-1.1.0.Beta1.xml      2023-12-14 08:37:47       3              EXECUTED
1.1.0.Final                sthorger@redhat.com  META-INF/jpa-changelog-1.1.0.Final.xml      2023-12-14 08:37:47       4              EXECUTED
1.2.0.Beta1                psilva@redhat.com    META-INF/jpa-changelog-1.2.0.Beta1.xml      2023-12-14 08:37:50       5              EXECUTED
1.2.0.Beta1                psilva@redhat.com    META-INF/db2-jpa-changelog-1.2.0.Beta1.xml  2023-12-14 08:37:50       6              MARK_RAN
```

full csv:
https://github.com/keycloak/keycloak/files/13673099/DATABASECHANGELOG.csv

### Version

22.0.5, 23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

normal keycloak start

### Actual behavior

ERROR: Failed to update database

### How to Reproduce?

appears randomly, with a reproduction ratio of approximately 1/20.

### Anything else?

The previous bug report (#22181) was closed due to inactivity. However, I believe there might be valuable insights in the `databasechangelog`, as suggested in this https://github.com/keycloak/keycloak/issues/22181#issuecomment-1814783069

**Comment by pedroigor** [comment] 2024-04-08 14:12
Can you please confirm if the error only happens when you have multiple instances started during an upgrade?

Perhaps this is something related to the lock not being properly held/recognized when starting the liquibase upgrade.

I'm marking it as a priority `normal` to keep an eye on similar reports from the community so we can prioritize it accordingly.

**Comment by pedroigor** [comment] 2024-04-08 14:17
In theory, this should be enough to prevent any overlap when upgrading the database. See https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java#L340.

**Comment by hfastek** [comment] 2024-04-10 08:14
> Can you please confirm if the error only happens when you have multiple instances started during an upgrade?

I always run two pods (via StatefulSet), so I cannot confirm if this issue would not occur on a single instance. What's important to note is that this problem consistently arises during a new Helm installation (on a clean database), and it results in a crash loop.

Today's logs:
```
$ kubectl logs -n mynamespace keycloak-0
...
2024-04-10 06:41:52,153 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) keycloak-0-46478: no members discovered after 2004 ms: creating cluster as coordinator
2024-04-10 06:41:52,176 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-0-46478|0] (1) [keycloak-0-46478]
2024-04-10 06:41:52,443 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-0-46478`, physical addresses are `[10.249.11.185:7800]`
2024-04-10 06:41:52,477 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-04-10 06:41:58,445 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:41:58,445 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:41:58,688 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
2024-04-10 06:42:04,126 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:42:04,126 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:42:04,185 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:42:04,186 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:42:05,838 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com encountered an exception.
2024-04-10 06:42:05,893 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-04-10 06:42:05,959 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-04-10 06:42:05,959 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2024-04-10 06:42:05,962 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com:
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:42:05,962 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com:
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:42:05,962 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com:
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:42:05,963 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:42:05,963 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Multiple primary key defined
2024-04-10 06:42:05,963 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

$ kubectl logs -n mynamespace keycloak-1
...
2024-04-10 06:40:42,629 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) keycloak-1-45194: no members discovered after 2003 ms: creating cluster as coordinator
2024-04-10 06:40:42,652 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-1-45194|0] (1) [keycloak-1-45194]
2024-04-10 06:40:42,861 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-1-45194`, physical addresses are `[10.249.17.21:7800]`
2024-04-10 06:40:42,891 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-04-10 06:40:48,279 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:40:48,279 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:40:48,446 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
2024-04-10 06:40:53,959 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:40:53,960 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:40:54,006 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, setNullable will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:40:54,006 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
2024-04-10 06:40:55,737 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com encountered an exception.
2024-04-10 06:40:55,800 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-04-10 06:40:55,862 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-04-10 06:40:55,864 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2024-04-10 06:40:55,865 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com:
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:40:55,865 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com:
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:40:55,866 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com:
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:40:55,867 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE keycloak.RESOURCE_URIS ADD PRIMARY KEY (RESOURCE_ID, VALUE)]
2024-04-10 06:40:55,867 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Multiple primary key defined
2024-04-10 06:40:55,867 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

I've searched for the phrase 'Migration failed for changeset' and found potentially related issue: #24550

**Comment by pedroigor** [comment] 2024-04-10 11:14
@hfastek OK, that is an important hint to what/how we need to investigate.

**Comment by shawkins** [comment] 2024-05-06 19:40
Duplicate of #23268

**Comment by hfastek** [comment] 2024-05-08 08:15
@shawkins 
> Duplicate of #23268

In the above issue, Azure has sql_generate_invisible_primary_key set to ON by default. However, in my case with Amazon RDS, it appears to be set to OFF by default (verified through `SELECT @@sql_generate_invisible_primary_key;`). Therefore, I'm concerned that there might be another underlying issue. Alternatively, albeit less likely, there could be a situation on AWS where the sql_generate_invisible_primary_key is somehow switched to ON during a problem occurrence (which I can verify in subsequent reproductions). This would be particularly unusual because this option isn't even configurable in the db-parameter-group.

**Comment by shawkins** [comment] 2024-05-08 10:53
@hfastek if this is similar to #24550 then it would be caused in some way by two pods running migration at the same time - and that the transactions used are insufficient for the migration steps to not conflict with one another. This scenario becomes more likely if you have enabled parallel pod management on the statefulset #21108

~priority-normal

**Comment by hfastek** [comment] 2024-05-09 10:49
Hi @shawkins,

Thank you for the quick response and suggestion about the pod management policy.
I was using the Parallel policy because it was the default in the Bitnami Keycloak Helm chart. I will try OrderedReady 👍

**Closed** 2024-08-08 00:06 UTC
Labels: kind/bug, area/storage, help wanted, team/core-iam, team/core-shared, status/auto-expire, status/auto-bump, priority/normal, status/expired-by-bot
