### ISSUE TITLE
On the clients page,The "Home URL" of account-console and account is wrong, missing path /realms/xxx/account

### ISSUE THREAD

**Issue by potterhe** [keycloak/keycloak#31521] opened 2024-07-23 11:37 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Operation Path: admin console -> Clients -> Client list -> Home URL，shown as: http://localhost:8080 not http://localhost:8080/realms/xxx/account, miss "/realms/xxx/account"

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

account-console's Home URL is "http://localhost:8080/realms/xxx/account"

### Actual behavior

account-console's Home URL is "http://localhost:8080", miss "/realms/xxx/account"

### How to Reproduce?

```
version: '2'

services:
  mysql:
    image: mysql:8.1.0
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=keycloak
    volumes:
      - './mysql_data:/var/lib/mysql'
  keycloak:
    image: keycloak/keycloak:25.0.2
    command: ["start", "--features", "organization"]
    ports:
      - '8080:8080'
      - '9000:9000'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=example
      - KC_DB_URL=jdbc:mysql://mysql/keycloak
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
    depends_on:
      - mysql
```

### Anything else?

na

**Comment by ssilvert** [comment] 2024-07-26 20:50
This is working fine for me:

<img width="926" alt="ClientList" src="https://github.com/user-attachments/assets/7a2561ed-7cd5-45f8-89d0-fef5c0979482">

**Comment by iliuta** [comment] 2024-07-29 15:16
I have the same problem, after migrating from 25.0.1 to 25.0.2, but also from 24 to 25.0.2.

**Comment by Loic-des-Rochettes** [comment] 2024-07-31 14:22
Same here with 25.0.2 and h2 out of the box :

![image](https://github.com/user-attachments/assets/4fd37f03-7f6b-4dc9-a5ec-acc23f9eed5e)

```yaml
services:
  keycloak:
    image: "quay.io/keycloak/keycloak:25.0.2"
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ********
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      DEBUG: "true"
      DEBUG_PORT: '*:8787'
    entrypoint: /bin/bash
    command: -c "/opt/keycloak/bin/kc.sh start"
    ports:
      - 8080:8080
      - "127.0.0.1:8787:8787"
    expose:
      - 8787
    volumes:
      - ./data/:/opt/keycloak/data/ # h2 database data dir
```

**Comment by Loic-des-Rochettes** [comment] 2024-07-31 14:25
@potterhe Could you check the checkbox : This issue is a regression ?
Because it is...

**Comment by Loic-des-Rochettes** [comment] 2024-07-31 14:33
No problem in 25.0.1 with the exact same database so it is a 25.0.2 regression.

**Comment by ssilvert** [comment] 2024-08-02 18:31
@Loic-des-Rochettes @potterhe @iliuta 

I see it now in 25.0.2.  However, this appears to be fixed in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).  

Can one of you confirm?

**Comment by divialth** [comment] 2024-08-05 17:27
I just stumbled over the same issue. In the current nightly the issue is no longer present.

**Comment by ssilvert** [comment] 2024-08-05 20:42
Thanks @divialth.  I'm going the close this issue now.

**Closed by ssilvert** 2024-08-05 20:42 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by divialth** [comment] 2024-08-21 13:16
I would have expected, that this bug will also be fixed in the current release.
But in 25.0.4 the bug is still here.
Do we have to wait for the next major release?

**Comment by ssilvert** [comment] 2024-08-22 12:29
@divialth Keycloak 26 is coming soon.

**Comment by hypery2k** [comment] 2024-08-23 04:17
so the bug will not be fixed in 25?

**Comment by iliuta** [comment] 2024-09-03 05:32
I confirm, it is definitely not working in 25.0.4.
