### ISSUE TITLE
Password policy not applied during password reset

### ISSUE THREAD

**Issue by geekdinazor** [keycloak/keycloak#11111] opened 2022-04-05 08:55 UTC
### Describe the bug

I set password policy with minimum length 8, includes at least one character uppercase, one character lowercase,  one digit  except  username. Then I register new user with username "can".  Registration screen force me use password with password policies that I set.  But during password reset screen, it's not. I can set password of user as "can".  

### Version

16.1.1

### Expected behavior

Password reset screen should be enforce password policies. 

### Actual behavior

Password reset screen not enforce password policies.

### How to Reproduce?

You can reproduce my example test scenario.

**Comment by DGuhr** [comment] 2022-04-05 10:08
Hi @geekdinazor I tried to reproduce it locally with the latest version, and it seems it is not reproducible (anymore?), at least not in latest quarkus release (17.0.1) and latest main (999 snapshot). So i suggest you update to the latest version of keycloak (or keycloak legacy if wildfly). 

I then tried to check 16.1.1 wildfly for the bug, using below docker image: 
`docker run --rm -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:16.1.1`

then I set up a test realm like this: 
![Screenshot 2022-04-05 at 11 57 16](https://user-images.githubusercontent.com/89905860/161729317-a4d4e6e0-71f3-4ba2-a863-a1794fcbadd6.png)

and registered a new user "can" using the account console ( http://localhost:8080/auth/realms/test/account/ ). Registration screen shows the right error for password policy, as you say. Then I logged into the account console and tried to change pw to "can" there, and also see the expected error, see screenshot: 
![Screenshot 2022-04-05 at 12 00 47](https://user-images.githubusercontent.com/89905860/161730037-b086d3a2-a026-4faa-8d3e-7293667b9ed6.png)

So not reproducible for me. Can you please provide more information and doublecheck your configuration? Thanks.

**Comment by geekdinazor** [comment] 2022-07-21 14:19
We realize that this issue occured when we use LDAP (as [389-ds](https://directory.fedoraproject.org/)) for user federation. We cannot reproduce it  with standalone Keycloak instance that same version and same configurations.

**Comment by railsmechanic** [comment] 2022-10-12 13:01
We've the same issue with 16.1.1 and OpenLDAP. Password policy is not enforced with this setup. Any news?

**Comment by ettik** [comment] 2022-11-14 08:06
Exactly the same here. We've Keycloak 16.1.1 and openldap as repository and password policy is not enforced by keycloak. As workaround we had to apply password enforcement into openldap, but this isn't the best option.

**Comment by werkon** [comment] 2022-12-14 11:34
We have exactly the same problem. In addition to that, the updatePasswordMessage is not displayed in the form.

**Comment by woprandi** [comment] 2023-01-31 14:45
I have the same issue, the LDAP password policy is not applied. 
After some tests, I think it's because the policy is bypassed when using the admin DN for LDAP password change.
It's directly reproductible with `ldappasswd` command line.

**Comment by rmartinc** [comment] 2023-03-02 10:59
Hi! If you are using an LDAP user federation the password is not validated by default. In the LDAP provider configuration there is an advance setting which is "Validate password policy" (default off). If you enable it the password is validated with the realm policies before sending it to the LDAP.

Note that this is totally different to use password policies at LDAP level.

**Comment by hmlnarik** [comment] 2023-03-06 13:41
> It's directly reproductible with ldappasswd command line.

Thank you for confirmation. 
Not a Keycloak bug, closing.

**Closed by hmlnarik** 2023-03-06 13:41 UTC
Labels: area/authentication, kind/bug, area/ldap, team/store
