### ISSUE TITLE
Terms and conditions step is not added in registration flow

### ISSUE THREAD

**Issue by cwlam** [keycloak/keycloak#22612] opened 2023-08-22 12:17 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

File: server_admin/topics/users/proc-requiring-tac-agreement-at-registration.adoc

I followed the steps in the documentation (version 22.0.1)  to enable the "Terms and condition" step in the registration flow, but this is not working. In the registration flow the step "Terms and condition"step is not added and also not possible to add this manually. This issue can be reproduced with the latest version (22.0.1) and also with the latest nightly build.

### Version

22.0.1

### Expected behavior

Expected behavior should be as described in the latest version of the documentation (version 22.0.1).

### How to Reproduce?

1. Select a Realm
2. Click on Realm settings and select tab Login. Enable checkbox "User registration"
3. Click on Authentication and select tab Required actions. Enable checkbox "Terms and Conditions"
4. Click on tab Flows and click on registration flow

**Comment by jungm** [comment] 2023-08-29 11:04
We're experiencing the same issue, possibly this is caused because keycloak has been upgraded in our case and some migration to add the step to this default flow is missing/broken?
Starting keycloak 22.0.1 against a blank database works as expected and the terms and conditions step is present in the builtin registration flow

@cwlam what worked for us as a workaround is just copying the registration flow into our own flow and add the terms and conditions step there, the built-in flow is read only and can't be edited

**Comment by ahus1** [comment] 2023-09-01 15:30
Duplicate of #22612

**Closed by ahus1** 2023-09-01 15:30 UTC
Labels: kind/bug, area/core, status/triage, team/core

**Comment by ahus1** [comment] 2023-09-01 15:31
Duplicate of #21730
