### ISSUE TITLE
LinkedIn Identity Provider Failing Token Issuer Check

### ISSUE THREAD

**Issue by LaramieHartmann** [keycloak/keycloak#28686] opened 2024-04-12 21:05 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

The Linkedin-openid-connect began failing sometime recently. Logs show the followin:

```
(executor-thread-679) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: 
Wrong issuer from token. Got: https://www.linkedin.com/oauth expected: https://www.linkedin.com/
	at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:722)
	at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:686)
```

LinkedIn's discovery page (https://www.linkedin.com/oauth/.well-known/openid-configuration) indicates that the issuer should be `https://www.linkedin.com/oauth` so my guess is that LinkedIn recently changed their issuer value which is causing Keycloak to fail validation.

Any ideas on how to resolve this? Thanks much!

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

After configuring the built-in LinkedIn identity provider, a user should be able to successfully login/authenticate using the Sign in with Linked in button.

### Actual behavior

After signing in to LinkedIn, Keycloak displays `Unexpected error when authenticating with identity provider`.

### How to Reproduce?

Use the built-in LinkedIn identity provider to sign in.

**Comment by rmartinc** [comment] 2024-04-15 08:43
@LaramieHartmann I cannot reproduce this. I configured the linked-in provider in my laptop and I can login OK and the iss in the id-token is `https://www.linkedin.com/oauth`. The current linked-in provider loads the configuration from the endpoint you mention [here](https://github.com/keycloak/keycloak/blob/24.0.2/services/src/main/java/org/keycloak/social/linkedin/LinkedInOIDCIdentityProviderFactory.java#L51), so I really don't know where the expected `https://www.linkedin.com/` is coming from.

**Comment by rmartinc** [comment] 2024-04-15 09:06
One more comment, if you follow the code the metadata is loaded and saved in an static property of the provider factory. So, it if was changed recently, just a restart of keycloak will reload the metadata (I don't remember if the issues was `https://www.linkedin.com/` before).

**Comment by rmartinc** [comment] 2024-04-15 14:10
Thanks @tavsec! Then it's explained. I'm going to close the issue as I don't expect the metadata is going to change very frequently (if we see that saving it in the class is a problem we can do other thing, but for the moment I think that it's OK).

**Closed by rmartinc** 2024-04-15 14:10 UTC
Labels: area/oidc, kind/bug, status/triage, team/core-clients, status/auto-expire
