### ISSUE TITLE
API / UI errors when LDAP OU has duplicate email addresses

### ISSUE THREAD

**Issue by bp974** [keycloak/keycloak#22441] opened 2023-08-14 16:59 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

If the underlying LDAP server has more than 1 user with the same email address, Keycloak responds with 400 response code along with the response body matching the request. There is an additional 'error' in the response body as well. 

The sync of users does give the error that states it cannot import the user with the duplicated email address. 
```
2023-08-14 16:36:09,744 ERROR [org.keycloak.storage.ldap.LDAPStorageProviderFactory] (Timer-0) Failed during import user from LDAP: org.keycloak.models.ModelDuplicateException: Can't import user 'testy tester' from LDAP because email 'johndoe0@mail.example.org' already exists in Keycloak. Existing user with this email is 'john0 doe0'
        at org.keycloak.storage.ldap.mappers.UserAttributeLDAPStorageMapper.checkDuplicateEmail(UserAttributeLDAPStorageMapper.java:165)
        at org.keycloak.storage.ldap.mappers.UserAttributeLDAPStorageMapper.onImportUserFromLDAP(UserAttributeLDAPStorageMapper.java:89)
        at org.keycloak.storage.ldap.LDAPStorageProvider.lambda$importUserFromLDAP$7(LDAPStorageProvider.java:557)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
        at org.keycloak.storage.ldap.LDAPStorageProvider.importUserFromLDAP(LDAPStorageProvider.java:552)
        at org.keycloak.storage.ldap.LDAPStorageProviderFactory$3.run(LDAPStorageProviderFactory.java:615)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:261)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:383)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:260)
        at org.keycloak.storage.ldap.LDAPStorageProviderFactory.importLdapUsers(LDAPStorageProviderFactory.java:597)
        at org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncImpl(LDAPStorageProviderFactory.java:543)
        at org.keycloak.storage.ldap.LDAPStorageProviderFactory.sync(LDAPStorageProviderFactory.java:477)
        at org.keycloak.storage.managers.UserStorageSyncManager$2$1.call(UserStorageSyncManager.java:109)
        at org.keycloak.storage.managers.UserStorageSyncManager$2$1.call(UserStorageSyncManager.java:104)
        at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.storage.managers.UserStorageSyncManager$2.run(UserStorageSyncManager.java:104)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:261)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:383)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:260)
        at org.keycloak.storage.managers.UserStorageSyncManager.syncAllUsers(UserStorageSyncManager.java:94)
        at org.keycloak.storage.managers.UserStorageSyncManager$4.run(UserStorageSyncManager.java:214)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)

2023-08-14 16:36:09,900 INFO  [org.keycloak.storage.ldap.LDAPStorageProviderFactory] (Timer-0) Sync all users finished: 0 imported users, 10 updated users, 1 users failed sync! See server log for more details
```

### Version

22.0.1

### Expected behavior

Any users found with duplicated email would be rejected in Keycloak and log an error message as show above. 

API requests return successfully with response code 200 without any users with duplicated email addresses. 

### Actual behavior

API requests return a 400 response code along with the body of what was requested and an erroneous error appended to the body. 
```
[
    {
        "id": "bef8c62b-1e01-4277-bec3-2f45febdc646",
        "createdTimestamp": 1691772521664,
        "username": "admin",
        "enabled": true,
        "totp": false,
        "emailVerified": false,
        "firstName": "Admin",
        "email": "admin@mail.example.org",
        "federationLink": "f269e0b7-b32d-44d1-b7bf-9da7d16c593f",
        "attributes": {
            "LDAP_ENTRY_DN": [
                "CN=Admin,CN=Users,DC=example,DC=org"
            ],
            "LDAP_ID": [
                "71426632-230a-4b26-9ce8-d7a14641703e"
            ],
            "modifyTimestamp": [
                "20230808174927.0Z"
            ],
            "createTimestamp": [
                "20230807213922.0Z"
            ]
        },
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    }
]{
    "error": "unknown_error"
}
```

### How to Reproduce?

Deploy Keycloak 22.0.1 and connect to Active Directory. Ensure this AD and the OU you plan to connect with Keycloak has 2 users that share the same email address.

In the UI, attempt to search for all users in the realm. Notice the error. 
Via API, fetch all users: Notice all users are returned in the response body along with error and 400 response code.

**Comment by martin-kanis** [comment] 2023-08-30 08:52
@bp974 Thanks for reporting the issue. I was able to reproduce with current main.

I think issue is not related only to AD but other LDAP providers as well. We have a test for sync with duplicate email `org.keycloak.testsuite.federation.ldap.LDAPSyncTest#test02duplicateUsernameAndEmailSync` which correctly handles the exception. Problem is, when you directly search for a user i.e `session.users().searchForUserStream(appRealm, Map.of(UserModel.SEARCH, "user*")).collect(Collectors.toList())`, it throws aforementioned exception.

**Comment by sguilhen** [comment] 2024-02-21 01:27
@rmartinc can this possibly be related to https://github.com/keycloak/keycloak/issues/25778?

**Comment by rmartinc** [comment] 2024-02-21 07:28
@sguilhen Yes, I think it's a duplicate of #25778 and better said #23396. With 23.0.x and the resteasy-reactive incorporation the second #23396 was fixed but there are still situations that can happen like #25778 (if the user is detected as duplicated in the middle of the stream because of the email and the response was partially sent to the browser, the error is still just appended). In #25778 I'm trying to fix the duplicate mail exception just warning and not incorporating the user to the response.

I think we can close this and continue with #25778.

**Closed** 2024-02-21 07:28 UTC
Labels: kind/bug, area/ldap, team/core-iam
