### ISSUE TITLE
RHBK operator 21.0.2 install : keycloak admin console enter infinite loop (iframe Issue)

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#21670] opened 2023-07-13 07:36 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

**Infra**
KC operator 21.0.2
External PostgreSQL database
Admins Console Panel

**Deployment**
Install Keycloak Operator 21.0.2 
Create an instance
click On "Administration Console" to enter your credentials.
 

**Error Report**
---> Keycloak admin console enetsr an infinite loop display  when trying to access credentials.

When calling inspect _chrome debugging tool_, it will display:
 
_localhost/:1 Uncaught {error: 'Timeout when waiting for 3rd party check iframe message.'}
 
The application is showing following error messages for iframe (using inspect)
 
Document
URL
chrome-error://chromewebdata/
Unreachable URL
https://test.keycloak.org/realms/master/protocol/openid-connect/3p-cookies/step1.html_

Owner Element
 
_<iframe>
Frame Creation Stack Trace
 
It
 @ keycloak.mjs:1319_

---> It seems that it cannot reach out the hostname provided (test.keycloak.org).

### Version

21.0.2

### Expected behavior

Able to log to admin console with credentials

### Actual behavior

Infinite loop

### How to Reproduce?

Those iinstall instructions are following 

Doc reference:
_Basic Keycloak deployment guide
https://www.keycloak.org/operator/basic-deployment_

1.1) Install Keycloak operator (KC 21)
 
1.2) create secrets
 
$ openssl req -subj '/CN=test.keycloak.org/O=Test Keycloak./C=US' -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
 
$ kubectl create secret tls example-tls-secret --cert certificate.pem --key key.pem
 
 
1.3) Create keycloak instance from yaml file
 
_apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    url: jdbc:postgresql://x.y.z.w:5432/keycloak
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    tlsSecret: example-tls-secret
  hostname:
    hostname: test.keycloak.org_
 
 
1.4) Verify succesful deployment of RH-SSO console
 
oc get pods
NAME                                 READY   STATUS    RESTARTS   AGE
example-kc-0                         1/1     Running   0          21m
keycloak-operator-5f7888b677-b2q9t   1/1     Running   0          42m
 
 
 
 
2) Accessing admin console
 
 
2.1) Disable ingress controller on the RHBK instance
 
 ingress:
    enabled: false
 
 
2.2) enable port forwarding
 
kubectl port-forward service/example-kc-service 8443:8443
 
 
2.3) You can access to the admin console at https://localhost:8443/
 
When clicking on the administrative panel "Administrative console", you will enter an infinite loop
 
Inspect admin console is reporting an iframe error
 
 
The value of the iframe element is
 
<iframe src="https://test.keycloak.org/realms/master/protocol/openid-connect/3p-cookies/step1.html" title="keycloak-3p-check-iframe" style="display: none;"></iframe>
 
The Application TAB also displays
 
Unreachable URL
 
https://test.keycloak.org/realms/master/protocol/openid-connect/3p-cookies/step 
 
---> test.keycloak.org is Hostname provided within the yaml file.
 
 
 
 
 
3) Additional troubleshooting done
 
 
3.1) When hostname is also removed from the Yaml file, we gotr thw following error message:
 
 
 
oc logs -f example-kc1-0
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2023-07-11 12:42:28,868 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 8870ms
Server configuration updated and persisted. Run the following command to review the configuration:
 
kc.sh show-configefined as an environment variable KC_HOSTNAME_STRICT set to false does not work.
 
 
Next time you run the server, just run:
 
kc.sh start --optimized 
 
ERROR: Unexpected error when starting the server in (production) mode
ERROR: Failed to start quarkus
ERROR: Strict hostname resolution configured but no hostname setting provided
For more details run the same command passing the '{}verbose' option. Also you can use '{-}-help' to see the details about the usage of the particular command.
 
===> The hostname is a required parameter of the of the operator.
 
 
 
3.2) Even disabling _hostname-strict_ (as an environment variable) in keycloak operator, when defined as an environment variable KC_HOSTNAME_STRICT set to false does not work.

### Anything else?

Keycloak2.10.2 image with Openshift is working fine.

**Comment by Paul6552** [comment] 2023-07-13 10:04
Duplicate of [ticket](https://github.com/keycloak/keycloak/issues/14666)

Maybe try the latest version first

**Comment by jonkoops** [comment] 2023-07-13 10:16
Duplicate of #14666

**Closed by jonkoops** 2023-07-13 10:16 UTC
Labels: kind/bug, team/cloud-native, status/triage, area/operator
