### ISSUE TITLE
Missing ":providerId" param - Error when viewing users from federated provider with limited admin roles

### ISSUE THREAD

**Issue by mozdi** [keycloak/keycloak#22175] opened 2023-08-02 09:16 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I´ve created a realm-role in master-realm that should allow User-Admins to manage all users of the a specific realm.
The following roles are associated with the realm-role: _REALMNAME_-realm - view-users, _REALMNAME_-realm - query-users and _REALMNAME_-realm - manage-users.

When testing the permissions, all users show up, but only users that have been created locally in keycloak, can be managed. When klicking on a user from a federated ldap provider, the error "**Missing ":providerId" param**" is displayed to the User-Admin.

### Version

22.0.1

### Expected behavior

User-Admins with roles "view-users", "manage-users" and "query-users" are able to view, modify ALL users.

### Actual behavior

User-Admins with roles "view-users", "manage-users" and "query-users" are able to view, modify only local users, but not users from federated providers.

### How to Reproduce?

1. Create a new realm _REALMNAME_.
2. Add an LDAP federated provider to the new realm _REALMNAME_.
3. Create a new realm-role in the master-realm and associate the follwing roles with the newly created realm-role: _REALMNAME_-realm - view-users, _REALMNAME_-realm - query-users and _REALMNAME_-realm - manage-users.
4. Assign the realm-role to a user.
5. Login with the user and switch to the new realm.
6. Go to "users" and click on a user from the federated provider.

**Comment by jonkoops** [comment] 2023-08-02 09:19
> User-Admins with roles "view-users", "manage-users" and "query-users" are able to view, modify ALL users.

@ssilvert did you not recently create a fix for this one?

**Comment by ssilvert** [comment] 2023-08-02 17:47
@jonkoops I don't think I've seen that error before.  I'll have to look into it.

**Comment by ssilvert** [comment] 2023-08-04 20:33
@mozdi  The problem was that we render a link back to the provider on federated users.  If you don't have `view-realm` access, will fail on rendering that link.

I submitted a fix, but if you need a workaround sooner you can assign `view-realm` access to your users and the Details page will work.

**Closed** 2023-08-07 19:37 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui

**Comment by DavidHaltinner** [comment] 2023-09-14 16:43
Looks like this is still an issue in 22.0.3 released the other day.

We have only federated users, but we have a few non-admins who can access the users in Keycloak for the sole purpose of resetting some people's OTP. They can log in OK, they can open the user OK, but when they go to the credential tab, they get this same error.
Adding the view-realm does workaround the issue.
Looks like there may be a second spot that needs to be fixed as well.

**Comment by jonkoops** [comment] 2023-09-21 11:40
If you are still experiencing issues, please report a new issue with the steps to reproduce it. Comments on closed issues are likely to get lost.
