### ISSUE TITLE
Keycloak Throws lock exceptions when we put bursts of traffic as it tries to clear the events and at the sametime keycloak writing the events

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#24546] opened 2023-11-04 02:54 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

We are trying to put bursts of traffic to keycloak installed in a Kubernetes environment with MariaDB as the database and adming and login events enabled. After some successful requests, we start to see lock exceptions in the keycloak logs and requests start to fail with the following error.

```
2023-08-21 10:35:03,713 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 33) ARJUNA012113: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 33,5,main] missed interrupt when cancelling TX 0:ffffc0a8c5d6:9d8d:64e2c0ea:3d92b -- exiting as zombie (zombie count decremented to 0)
2023-08-21 10:35:03,713 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredEvents: javax.persistence.PessimisticLockException: could not execute statement
        at org.hibernate.internal.ExceptionConverterImpl.wrapLockException(ExceptionConverterImpl.java:273)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:108)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1705)
        at org.keycloak.events.jpa.JpaEventStoreProvider.clearExpiredEvents(JpaEventStoreProvider.java:107)
        at org.keycloak.services.scheduled.ClearExpiredEvents.run(ClearExpiredEvents.java:39)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.lambda$run$0(ScheduledTaskRunner.java:56)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:50)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: org.hibernate.PessimisticLockException: could not execute statement
        at org.hibernate.dialect.MySQLDialect$3.convert(MySQLDialect.java:547)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:80)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:50)
        at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:177)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:458)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:377)
        at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1483)
        at org.hibernate.query.internal.AbstractProducedQuery.doExecuteUpdate(AbstractProducedQuery.java:1714)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1696)
        ... 14 more
Caused by: java.sql.SQLException: (conn=247032) Lock wait timeout exceeded; try restarting transaction
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:299)
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:840)
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:779)
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:698)
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:641)
        at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
        at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:334)
        at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:311)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 22 more
        
```

APIs that we call for the bursts of traffic:
Authentication token request with client credentials flow
resource owner password credentials flow

With similar load, we didn't face any such issues. Do anyone face these kind of issues with quarkus versions? Is this due to handling the concurrency of reads and writes? Can anyone throw some information on this and if this is a bug, we request you to look into it.  

### Version

22.0.0

### Expected behavior

Keycloak should handle the read and writes efficiently related to events to the database.

### Actual behavior

Keycloak throwing lock exceptions when we enable admin and login events.throws

### How to Reproduce?

Put bursts of traffic and make the API calls mentioned in the description after enabled admin and login events with an expiry time.

**Comment by pedroigor** [comment] 2024-01-05 15:16
Are you experiencing the same when using the latest version? In any case, I would suggest you to try to reproduce this using our `keycloak-benchmark` tool, if not already. See https://github.com/keycloak/keycloak-benchmark/. It should help to share your set-up and you are running tests.

@ahus1 @kami619 Have you seen that?

**Comment by kami619** [comment] 2024-01-10 11:41
@pedroigor Hi Pedro, `keycloak installed in a Kubernetes environment with MariaDB as the database and admin and login events enabled`, this is a database combination which is not currently part of the architecture we are using for our tests. We currently use PostgreSQL as the DB and didn't see that behavior. I shall try to reproduce this with the `admin and login events enabled(if they aren't already enabled by default) and report back.

**Comment by ahus1** [comment] 2024-02-12 10:48
Closing due to lack of comments from author

**Closed by ahus1** 2024-02-12 10:48 UTC
Labels: kind/bug, area/storage, status/triage, team/core-shared

**Comment by derweise** [comment] 2024-03-06 22:24
> The exception above is thrown when deleting old events from the database fails. This is harmless and the next successful would delete expired events. The default interval for the cleanup is 900 seconds.
> 
> Depending on the database used, deadlocks and timeouts might be more frequent.
> 
> MySQL uses the isolation level of repeatable read, while other databases like PostgreSQL use read committed. Combined with the behavior of MySQL in general this could make it more likely to have deadlocks.
> 
> Please consider changing the default isolation level for the database to read committed and report back if this changes your observed behavior. If this is the case, we could re-test this here, and make this eventually a default for Keycloak.
> 
> While we haven't tested this behavior ourselves, other seem to have made good experience with that: #9749
> 
> According to the docs, this should be possible to configure for the database https://dev.mysql.com/doc/refman/8.2/en/innodb-transaction-isolation-levels.html
> 
> We might also be able to configure this from the Keycloak point of view with a Quarkus option https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.transaction-isolation-level



> The exception above is thrown when deleting old events from the database fails. This is harmless and the next successful would delete expired events. The default interval for the cleanup is 900 seconds.
> 
> Depending on the database used, deadlocks and timeouts might be more frequent.
> 
> MySQL uses the isolation level of repeatable read, while other databases like PostgreSQL use read committed. Combined with the behavior of MySQL in general this could make it more likely to have deadlocks.
> 
> Please consider changing the default isolation level for the database to read committed and report back if this changes your observed behavior. If this is the case, we could re-test this here, and make this eventually a default for Keycloak.
> 
> While we haven't tested this behavior ourselves, other seem to have made good experience with that: #9749
> 
> According to the docs, this should be possible to configure for the database https://dev.mysql.com/doc/refman/8.2/en/innodb-transaction-isolation-levels.html
> 
> We might also be able to configure this from the Keycloak point of view with a Quarkus option https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.transaction-isolation-level

I have a Keycloak cluster 23.0.x and tcpping. The cluster starts up successfully, but after 15 minutes (as you say 900 seconds) I start getting these errors:

`2024-03-06 21:43:25,281 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p4-t1) ISPN000136: Error executing command PutKeyValueCommand on Cache 'work', writing keys [task::ClearExpiredEvents]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 47 from keycloack01-49837 after 15 seconds`

But we do not have any traffic when this error occurs.

**Comment by derweise** [comment] 2024-03-06 22:24
@ahus1 

I have a Keycloak cluster 23.0.x and tcpping. The cluster starts up successfully, but after 15 minutes (as you say 900 seconds) I start getting these errors:

2024-03-06 21:43:25,281 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p4-t1) ISPN000136: Error executing command PutKeyValueCommand on Cache 'work', writing keys [task::ClearExpiredEvents]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 47 from keycloack01-49837 after 15 seconds

But we do not have any traffic when this error occurs.
