### ISSUE TITLE
Keycloak server to store data in oracle database have error : ORA-00932: inconsistent datatypes: expected - got NCLOB

### ISSUE THREAD

**Issue by phamthuy** [keycloak/keycloak#15561] opened 2022-11-18 01:50 UTC
### Area

dist/quarkus

### Describe the bug

Keycloak server to store data in oracle database but apper error

2022-11-18 00:33:24,989 WARN [io.agroal.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state VALIDATION
2022-11-18 01:00:06,201 WARN [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 932, SQLState: 42000
2022-11-18 01:00:06,201 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) ORA-00932: inconsistent datatypes: expected - got NCLOB

2022-11-18 01:00:06,202 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredAdminEvents: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)

Caused by: Error : 932, Position : 178, Sql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=:1 and realmattri0_.VALUE<>:2 , OriginalSql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=? and realmattri0_.VALUE<>?, Error Msg = ORA-00932: inconsistent datatypes: expected - got NCLOB

at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)

### Version

20.0.1

### Expected behavior

keycloak server runs smoothly with no errors

### Actual behavior

Error appear when keycloak uses oracle database to store data
2022-11-18 01:00:06,202 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredAdminEvents: org.hibernate.exception.SQLGrammarException: could not extract ResultSet

Caused by: Error : 932, Position : 178, Sql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=:1 and realmattri0_.VALUE<>:2 , OriginalSql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=? and realmattri0_.VALUE<>?, Error Msg = ORA-00932: inconsistent datatypes: expected - got NCLOB

### How to Reproduce?

I change keycloak storing data to oracle and run keycloak using below docker file:

[Dockerfile_Test.txt](https://github.com/keycloak/keycloak/files/10036993/Dockerfile_Test.txt)

After server start, wait 15' then error appears

**Comment by rmartinc** [comment] 2022-11-18 09:06
Can you paste the full stack-trace to see what part of the code is doing a comparison on a NCLOB?

**Comment by sschu** [comment] 2022-11-18 17:42
This is probably a duplicate of https://github.com/keycloak/keycloak/issues/15528.

**Comment by phamthuy** [comment] 2022-11-21 02:08
> 
This bug arises from line 291 in "JpaEventStoreProvider.java" file because oracle doesn't support NCLOB type in where clause

Detail :
` cr.select(root).where(cb.and(cb.equal(root.get("name"),RealmAttributes.ADMIN_EVENTS_EXPIRATION),cb.notEqual(root.get("value"), "0")));`

This code will generate to sql command:
`select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=:1 and realmattri0_.VALUE<>:2`

Column VALUE in table "REALM_ATTRIBUTE" has data type is NCLOB

**Comment by rmartinc** [comment] 2022-11-21 08:05
Yes, there is a condition over a NCLOB attribute. But it seems this is already being managed by #15528.

**Comment by ahus1** [comment] 2022-11-22 10:13
Closing this as a duplicate.

**Closed by ahus1** 2022-11-22 10:13 UTC
Labels: kind/bug, area/dist/quarkus, status/triage
