### ISSUE TITLE
Keycloak 20.0.3 container does not support Java 17

### ISSUE THREAD

**Issue by domitopp** [keycloak/keycloak#16727] opened 2023-01-31 09:29 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

We have a custom user storage provider build with maven/JDK 17 with target 17. According to https://www.keycloak.org/docs/latest/release_notes/index.html#supported-openjdk-versions (as of 2023-01-31) Keycloak supports Java 17.
When starting the container image it fails during build with
`ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.UnsupportedClassVersionError: one/of/our/Classes has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

### Version

20.0.3

### Expected behavior

According to the docs we expect Keycloak to work with jars compiled with Java 17

### Actual behavior

Keycloak fails with jars compiled with Java > 11

### How to Reproduce?

Build custom user storage provider with Java >11 and try to build and start Keycloak (in Docker container)

**Comment by sschu** [comment] 2023-01-31 09:48
This is a duplicate of https://github.com/keycloak/keycloak/issues/16441 and https://github.com/keycloak/keycloak/issues/15916 and will be implemented with https://github.com/keycloak/keycloak/issues/14349.

**Comment by domitopp** [comment] 2023-01-31 09:54
Oh, sorry for that. Seems like I used the wrong search terms or I have overlooked these issues.
Thanks for the quick reply!

**Closed** 2023-01-31 09:55 UTC
Labels: kind/bug, area/dist/quarkus, status/triage

**Comment by domitopp** [comment] 2023-01-31 09:58
Just for reference: https://github.com/keycloak/keycloak/pull/16014

**Comment by danghuybk** [comment] 2023-12-20 05:55
Hi @sschu, I suppose this should be fixed already? I still got the same issue, could you pls show how to fix it?
