### ISSUE TITLE
Single client export/import bug

### ISSUE THREAD

**Issue by intellitour** [keycloak/keycloak#9468] opened 2022-01-10 13:10 UTC
### Describe the bug

When you export a single client (through the admin interface), the client's roles and their attributes does not appear in the exported JSON and therefore, are not imported back when you need it.

### Version

Latest release (and every version I've ever used)

### Expected behavior

The JSON file should contain all the roles and each role's attributes.

### Actual behavior

The JSON file does not include the exported client's roles nor their attributes.

### How to Reproduce?

Create a client with some roles and give one or more roles some attributes. Export that single client through admin interface and then try to import the file to another realm or instance.

### Anything else?

I have a PR that solves this: https://github.com/keycloak/keycloak/pull/9439#issuecomment-1008853911

**Comment by mposolda** [comment] 2023-03-28 13:00
Preliminary adding to Backlog. We may need to triage it later.

**Comment by indiealexh** [comment] 2023-06-27 16:28
Would ADORE this feature please :D

I am deploying apps to production and copying the client WITH the client roles would save me hours.

**Comment by intellitour** [comment] 2023-06-30 23:42
> Would ADORE this feature please :D
> 
> 
> 
> I am deploying apps to production and copying the client WITH the client roles would save me hours.

Check #9439
I've made it. But it was not accepted due to performance concerns. I did notice a minor performance hit, very small and manageable IMHO.

**Comment by abstractj** [comment] 2024-02-06 19:20
@mposolda confirmed that the same behavior is still present in 23.0.6. Although, I disagree that this is a bug, from my perspective it is an enhancement request.

**Comment by intellitour** [comment] 2024-02-07 01:31
As @stianst didn't provide evidence on his concern about a performance hit (significant, as he told), which I know there is, but I consider it negligible, should I (we?) revisit #9439 and add some performance test evidence? Or should I make it an extension? This cannot be so difficult. Such a simple fix/tweak and here we are... years passing by and the situation remains the same.

**Comment by mposolda** [comment] 2024-03-04 18:20
I am closing as this is not a bug, but would be rather an enhancement as mentioned by @abstractj . Please open new GH issue as an "enhancement" rather than a bug.

Regarding the PR #9439 : it changes the behaviour of `ClientsResource.getClients` , which is the Keycloak endpoint for listing all clients. I am not sure how this relates to the export/import of the client, which is mentioned in the description. IMO the improvement for this export/import issue should not change the default behaviour of the endpoint of `ClientsResource.getClients` (the reason is exactly the performance as already mentioned on the original PR), but fix should likely rather do something specific only for export/import.

**Closed by mposolda** 2024-03-04 18:20 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core-clients
