### ISSUE TITLE
When a user is (temporarily) blocked the message invalidUserMessage is shown instead of the message accountTemporarilyDisabledMessage

### ISSUE THREAD

**Issue by cgm-maarten** [keycloak/keycloak#33394] opened 2024-09-30 13:39 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When a user account is temporary locked because of the brute force detection the appropriate message should be shown not the generic "invalidUserMessage"

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The message with key accountTemporarilyDisabledMessage is shown. (possible also with the username/password form)
(possibly/probably the user might be shown accountDisabledMessage when the brute force detection triggers that action)

When using the normal keycloak/login theme

### Actual behavior

The message with key: invalidUserMessage is shown on password screen.

### How to Reproduce?

Have a login flow:
1. username form
2. password form
enable bruteforce detection (and trigger the brute force action)

### Anything else?

Would also solve: [17014](https://github.com/keycloak/keycloak/issues/17014)

**Comment by cgm-maarten** [comment] 2024-09-30 13:40
I'm unsure wheter it is regression, but the message keys suggest that it used to work

**Comment by rmartinc** [comment] 2024-10-01 08:24
@cgm-maarten This is a duplicate of #17014. Currently keycloak sends the most secure message as the previous issue describes. In the other issue the contributor is trying to add a configuration in the brute-force to show the specific message (less secure but more descriptive) or the general message (more secure, less user-friendly), which I think covers the two situations ok.

Duplicate of #17014.

**Closed by rmartinc** 2024-10-01 08:24 UTC
Labels: kind/bug, status/triage, area/login/ui, team/core-clients

**Comment by cgm-maarten** [comment] 2024-10-02 06:54
@rmartinc Having the message in the theme, suggests behavior that is not present currently in the application. Leading to a mismatch in expectations.

In which case, a solution could also be: removing the message key accountTemporarilyDisabledMessage from the theme.

(possibly reintroducing the key again when the duplicate issue is implemented.)
