### ISSUE TITLE
Not able to assign roles when created users using API

### ISSUE THREAD

**Issue by kbpmowrya** [keycloak/keycloak#32351] opened 2024-08-22 14:15 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I am using keycloak version 22.0.4
/admin/realms/{{realm}}/users 
Couldn't able to assign roles like "realmRoles": [	"fullstack-developer","backend-developer ].
------------------------------
The same way, I am not able to assign role to user without "id":"c87fa265-e70f-40e0-8d9f-1f44916d8a5c" in the payload.
{{keycloak_url}}/admin/realms/{{realm}}/users/{{userId}}/role-mappings/realm
Payload:
[{"name":"fullstack-developer","description":"${role_default-roles}","composite":false,"clientRole":false,"containerId":"308bba17-5f3a-48e7-afce-5acf7b6b4486"}]

### Version

22.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

realmroles should be assigned while creating users.

### Actual behavior

realmroles should be assigned while creating users.

### How to Reproduce?

use the followig payload
{{keycloak_url}}/admin/realms/{{realm}}/users

{
        "createdTimestamp": 1588880747548,
        "username": "wafella",
        "enabled": true,
        "totp": false,
        "emailVerified": true,
        "firstName": "Stephen",
        "lastName": "Strange",
        "email": "roland@marvel.com",
        "credentials": [{
            "type": "password",
            "value": "password",
            "temporary": false
        }],
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        },
        "realmRoles": [	"c87fa265-e70f-40e0-8d9f-1f44916d8a5c" ]
    }

**Comment by kbpmowrya** [comment] 2024-08-23 09:48
Please find my docker compose file as attachment.
[docker-compose.txt](https://github.com/user-attachments/files/16726931/docker-compose.txt)

**Comment by sschu** [comment] 2024-08-23 10:34
Duplicate of https://github.com/keycloak/keycloak/issues/13390

**Closed by sschu** 2024-08-23 10:34 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core-shared
