### ISSUE TITLE
multiselect-checkboxes are cutting characters from the label

### ISSUE THREAD

**Issue by Rainson12** [keycloak/keycloak#30253] opened 2024-06-07 12:10 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When choosing `multiselect-checkboxes` as input-type for an user attribute, the first two and last character will be cut off:
![image](https://github.com/keycloak/keycloak/assets/13119203/22a59265-dfbf-45bc-9f08-ffcb539ae3c7)

Although the code (https://github.com/keycloak/keycloak/blob/main/js/libs/ui-shared/src/user-profile/OptionsComponent.tsx#L35 or label function: https://github.com/keycloak/keycloak/blob/main/js/libs/ui-shared/src/user-profile/utils.ts#L34) seems to be correct, it seems that during the build process some logic gets removed as when looking at the executed code, the check for `isBundleKey` is omitted:
![image](https://github.com/keycloak/keycloak/assets/13119203/a14a9f01-0425-4b1f-a7ad-4b4421c3ddf0)

See that function `L` only consists of the substring function but no check of the `${` existance:
![image](https://github.com/keycloak/keycloak/assets/13119203/73ca9ac8-6eb4-4699-bd22-9ceaa9ae74f9)

Thus the 2 prefix and one suffix characters are being omitted although the ${} is not present.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Labels are not cutoff

### Actual behavior

Labels of checkboxes are cutoff by first 2 and last characters.

### How to Reproduce?

Create a new user attribute called `test` with 2 options called `test1` and `test2`. Select `multiselect-checkboxes` as input-type. Then go to edit a user profile and find the lables being cutoff.

![image](https://github.com/keycloak/keycloak/assets/13119203/fb91ef53-68d7-4803-9ac6-bdcc55676abe)

**Comment by edewit** [comment] 2024-06-08 10:56
I can't reproduce this

**Comment by Rainson12** [comment] 2024-06-10 07:44
@edewit  how did you try to reproduce it? I am using docker container. I assume that while in non prod build this issue will not occur as it seems to be a bundler / minifying issue.

**Comment by ssilvert** [comment] 2024-06-10 12:44
I'm using a nightly build from a few days ago and this works fine for me.

**Comment by edewit** [comment] 2024-06-11 08:50
it looks like this:
![image](https://github.com/keycloak/keycloak/assets/51133/d02da870-d16c-4400-9d51-fb5372eec20b)
I'm using a fresh distribution build on my local machine

**Comment by Rainson12** [comment] 2024-06-11 10:08
> it looks like this: ![image](https://private-user-images.githubusercontent.com/51133/338510080-d02da870-d16c-4400-9d51-fb5372eec20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDA1NzUsIm5iZiI6MTcxODEwMDI3NSwicGF0aCI6Ii81MTEzMy8zMzg1MTAwODAtZDAyZGE4NzAtZDE2Yy00NDAwLTlkNTEtZmI1MzcyZWVjMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEwMDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODE1ODZhYmRlYWFhNjUxZjAyZmJmN2ZhMjE3YjZjZmYzNjIwM2ExYjA5MDBkZGMyYTM1M2M3NjI2NTE5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hdF3SmMdK-DZD6AA1twB6q-Pp1TQkfQ2jovpV-N-bAQ) I'm using a fresh distribution build on my local machine, as far as I can see it only does the substring if the string has the "${" in it

actually no, its the same like for me, you should see the same issue when selecting multiselect-checkbox as the function that is referenced in your case might only be `Xe` while the actual check of whether the ${} exists is another function called `Qe`. If this is not specifically called by the label function to check if the ${} exists (which in the 25.0.5 does not happen it seems) then it will also not work in your build.

**Comment by Rainson12** [comment] 2024-06-11 10:18
Use this as the config using the json-editor:

You should see the issue

```
{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {},
        "up-username-not-idn-homograph": {}
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "email",
      "displayName": "${email}",
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "firstName",
      "displayName": "${firstName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "lastName",
      "displayName": "${lastName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "organizations",
      "displayName": "organizations",
      "validations": {
        "options": {
          "options": [
            "abcdef",
            "abcdef12",
            "abcdef123",
            "abcdef1234"
          ]
        }
      },
      "annotations": {
        "inputType": "multiselect-checkboxes"
      },
      "permissions": {
        "view": [],
        "edit": [
          "admin"
        ]
      },
      "multivalued": false
    }
  ],
  "groups": [
    {
      "name": "user-metadata",
      "displayHeader": "User metadata",
      "displayDescription": "Attributes, which refer to user metadata"
    }
  ]
}
```

**Comment by edewit** [comment] 2024-06-11 11:23
I can reproduce it with 24.0.5 using docker, but I'll close it as it seems to be fixed in the nightly

**Closed by edewit** 2024-06-11 11:23 UTC
Labels: kind/bug, area/user-profile, status/triage, team/ui
