### ISSUE TITLE
Localized Custom User Profile Field not displayed correctly

### ISSUE THREAD

**Issue by alexanderhofstaetter** [keycloak/keycloak#31142] opened 2024-07-09 08:34 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

A custom added user field does not get shown correctly when the Admin-UI has localization enabled:

The Input label in the Admin UI shows the technical label descriotion only.

![image](https://github.com/keycloak/keycloak/assets/6820505/d554306a-52b8-4d34-8ded-f37406faed84)

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

FIeld in the Admin-UI shows correct label

### Actual behavior

Label gets shown

### How to Reproduce?

1. Enable Localization (e.g. German)
2. add custom user field
3. open user in admin UI

**Comment by alexanderhofstaetter** [comment] 2024-07-09 08:37
This problem also affects custom user attribute groups:

![image](https://github.com/keycloak/keycloak/assets/6820505/642999c3-7a3d-4f29-b944-383fa5cbbd76)

**Comment by ssilvert** [comment] 2024-07-09 19:02
@alexanderhofstaetter This is working fine for me.  Are you using User Profile and the localization icon to set the translations?

**Comment by agagancarczyk** [comment] 2024-07-10 10:29
> @alexanderhofstaetter This is working fine for me. Are you using User Profile and the localization icon to set the translations?

This is working fine for me too.

**Comment by alexanderhofstaetter** [comment] 2024-07-11 16:19
Also see this issue for not beeing able to save already created attributes, because of missing translations:

https://github.com/keycloak/keycloak/issues/31228

**Comment by ssilvert** [comment] 2024-07-16 18:00
Closing as duplicate of fixed issue #30522

**Comment by alexanderhofstaetter** [comment] 2024-07-19 11:33
@agagancarczyk from my POV this is not fixed, with 25.0.2 we still do not see the correct display values for the field label.

The fields are in a custom realm, and in this realm the correct translations (key/value) are added in the translations tab. However this does not work.

BUT: When we add the same key in the master realm als translation, it gets displayed correctl.

So the problem is: Custom user profile fields in other realms, do not show correct label display text, even though key/values translations have been added as overrides in this realm; when managing the custom realm from the master realm. However, they are shown correctly, when the translations are added to the master realm.

Fix would be: Use translations for Admin/UI from the correspondig realm the user is managing.

**Comment by agagancarczyk** [comment] 2024-07-22 14:38
Thanks @alexanderhofstaetter I'll reopen and review this again.

**Comment by agagancarczyk** [comment] 2024-07-26 14:21
This seems to be a duplicated of https://github.com/keycloak/keycloak/issues/31633

@alexanderhofstaetter backport PR is up under https://github.com/keycloak/keycloak/pull/31666, should be available in the next patch release 25.0.3.

**Closed** 2024-07-31 13:03 UTC
Labels: kind/bug, area/admin/ui, team/ui, status/reopened
