### ISSUE TITLE
Possibiility to change port naming in service when using new operator

### ISSUE THREAD

**Issue by webkim** [keycloak/keycloak#11892] opened 2022-05-09 06:09 UTC
### Description

New keycloak operator crds should have option to change port naming in service.

### Motivation

When keycloak is used with istio, it would help if there were possibility to define port names to kubernetes service. Now there seems to be no option in keycloak operator crd to change port naming.  

Istio uses port naming for protocol selection: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by shawkins** [comment] 2023-06-26 20:37
Duplicate of #13884

**Closed by shawkins** 2023-06-26 20:37 UTC
Labels: kind/enhancement
