### ISSUE TITLE
Typo in CI

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#12779] opened 2022-06-28 09:12 UTC
### Describe the bug

![Screenshot 2022-06-28 at 10 11 20](https://user-images.githubusercontent.com/5792097/176141321-98ac7f96-9cc5-4067-945d-04fef6ea0c9c.png)

### Version

main

**Comment by DGuhr** [comment] 2022-06-28 09:35
duplicate of #12690 - closing

**Closed by DGuhr** 2022-06-28 09:35 UTC
Labels: kind/bug, status/triage
