### ISSUE TITLE
Signature change for method KeycloakModelUtils.runJobInTransactionWithResult

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#33733] opened 2024-10-09 10:47 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The Keycloak Benchmark failed to compile (see [1]) due to a change in the method signature `KeycloakModelUtils.runJobInTransactionWithResult` due to the change in commit [2].

Although this API lives in `server-spi-private` and the lines are blurred, I suggest adding a new method with the old signature and marking it deprecated and for removal. 

[1]
https://github.com/keycloak/keycloak-benchmark/actions/runs/11248541133/job/31274639477#step:12:1493

[2] 
https://github.com/keycloak/keycloak/commit/07cf71e818e7feca1a36164c216a225f198d50f0#diff-8c2760488fe1f23b33122b763c930a8efd4e8d5ee4e41261e6de6b48d9157bd2R379

### Version

nightly

### Regression

- [X] The issue is a regression

### Expected behavior

Users may use this API in their custom provider and, when upgrading to the latest patch release, they should not get a compile error. 

### Actual behavior

User custom provider using this API will get a compile error.

### How to Reproduce?

hmm... create a custom provider that uses the API from KC 26 and try to compile with the KC nightly :)

**Comment by pruivo** [comment] 2024-10-09 10:49
cc @mposolda @keycloak/core 
To bring awareness that this change may surprise some users.

**Comment by shawkins** [comment] 2024-10-09 11:25
Relates to #33397 and caused by #32914 - where this was discussed briefly on the PR. It's definitely not good moving forward to have blurred lines around the role of public / private dependencies. Can we capture somewhere what the eventual goal is for the private module - should it not be transitively available from anything public, and in particular should a public contract for using KeycloakModelUtils be created?

**Comment by stianst** [comment] 2024-10-22 08:11
KeycloakModelUtils is not something we should make public, and it's kinda in the name that this module is private. So I would just close this one.

**Comment by shawkins** [comment] 2024-10-22 12:08
Closing based upon @stianst 's feedback. spi-private is marked as provided from the spi module - the only places where it's not provided are not user extension points.  We'll leave KeycloakSessionTask and KeycloakSessionTaskWithResult on the public side for now even though their only usage is from spi-private.

**Closed by shawkins** 2024-10-22 12:08 UTC
Labels: kind/bug, area/core, team/cloud-native, status/triage
