### ISSUE TITLE
UserResource update sets "First name" to "Last name" if "Last name" is null   

### ISSUE THREAD

**Issue by tatavmargaryan** [keycloak/keycloak#9041] opened 2021-12-08 10:38 UTC
### Describe the bug

org.keycloak.admin.client.resource.UserResource is used  for creating and updating users in Keycloak. There is only "firstname" for users but noted  that for some users in keycloak we have the same firstname and lastname. After investigation we have found that after user update keycloak sets firstname to lastname. 

```
                ...
                UserResource resource = realmResource.users().get(users.get(0).getId());
                UserRepresentation user = initUser(resource.toRepresentation(), userDto);
                log.debug("Before update user details: userName {}, first name {}, last name {}",
                    user.getUsername(), user.getFirstName(), user.getLastName());
                resource.update(user);
                UserRepresentation representation = resource.toRepresentation();
                log.debug("Updated user in keycloakClient , userName {}, first name {}, last name {}",
                representation.getUsername(), representation.getFirstName(), representation.getLastName());
               ...
```
in ```initUser ``` method last name is set null
**NOTE:** Code part just for showing how was investigation done.

### Version

15.0.2

### Expected behavior

To keep Last Name null

### How to Reproduce?

This happens randomly so it is hard to describe the steps  for reproduce the bug.

**Comment by abstractj** [comment] 2021-12-23 19:18
@tatavmargaryan we need the reproducible steps for this, considering that people may not have time to dig more into this. Also, please try the latest release (16.1.0), and let us know if the issue persists.

**Comment by pedroigor** [comment] 2023-02-22 15:05
Closing due to the lack of information. Please, try the latest release to see if the issue persists.

**Closed by pedroigor** 2023-02-22 15:05 UTC
Labels: kind/bug, area/admin/api, status/triage
