### ISSUE TITLE
Azure OpenID Connect AADSTS90015: Requested query string is too long.

### ISSUE THREAD

**Issue by manodupont** [keycloak/keycloak#24794] opened 2023-11-16 10:30 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Sign out of Azure with OIDC results in this error on Azure side.

AADSTS90015: Requested query string is too long.

<img width="1536" alt="Screenshot 2023-11-16 at 11 29 13" src="https://github.com/keycloak/keycloak/assets/7568033/131b2c0a-15f9-4887-87a3-c700e7687d93">

### Version

22.0.1

### Expected behavior

Log out should redirect to the Login page

### Actual behavior

Sign out of Azure with OIDC results in this error on Azure side.

AADSTS90015: Requested query string is too long.

<img width="1536" alt="Screenshot 2023-11-16 at 11 29 13" src="https://github.com/keycloak/keycloak/assets/7568033/131b2c0a-15f9-4887-87a3-c700e7687d93">

### How to Reproduce?

1 - Add Azure as OIDC
2 - Login to your application
3 - Log out of your application

### Anything else?

The URL is clearly too long cause if I remove some stuff like the id_token_hint for instance in the URL, it logs out perfectly.

_No response_

**Comment by rmartinc** [comment] 2023-11-17 12:20
Duplicate of https://github.com/keycloak/keycloak/issues/21399

AFAIK the `id_token_hint` is a recommended parameter for logout in the [spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout). Keycloak always sends it when used as a RP if the IDToken was returned by the OP previously. So we don't control its length, it's returned by the OP (microsoft in this case). As commented in the other issue MS sometimes has a very large IDToken (lots of groups or roles) and this issue happens. It seems that MS supports a specific `logout_hint` but that would an extension or enhancement. Any contribution will be welcomed. A more easy solution would be just adding an option in the config to not send the `id_token_hint`.

I'm closing this, because the other one explains better the root problem.

**Closed by rmartinc** 2023-11-17 12:20 UTC
Labels: area/oidc, kind/bug, status/triage, team/core
