### ISSUE TITLE
Unable to add user from kerberos

### ISSUE THREAD

**Issue by KandpalS** [keycloak/keycloak#26063] opened 2024-01-10 05:13 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Hi Everyone, I have a keycloak 22.0.0 running in production with postgres db in a cluster mode. It contains multiple realms with kerberos used for user federation. As an admin, I wanted to add existing users via kerberos to some of the realms.

When I was on version 12.0.4, I just simply tried to create the user from the console and then I used to get user already exists error, but afterwards user starts appearing in the realm users list. But this behavior is no longer showing up with version 22.0.0. User can only be enabled by trying to access the realm using kerberos with browser or curl with negotiate. But I want to enable those users without asking user to try the same as there are multiple realms and need to perform the role mappings for users before they try to access the applications.

Any suggestions or advise will be helpful. Thanks

### Version

22.0.0

### Expected behavior

I should be able to add the user from kerberos like it was working with 12.0.4

### Actual behavior

Was able to add the existing user from user federation kerberos setup using console and from create user api

### How to Reproduce?

Go to realm, then click on create user. Try to create existing user from kerberos. Should get an error saying user already exists, then user should start showing up in realms user list.

**Comment by ssilvert** [comment] 2024-01-10 19:45
This doesn't sound like a UI issue.  Moving to core team.

**Comment by rmartinc** [comment] 2024-01-16 17:04
@KandpalS You are right, the problem is that (probably) since version 12 we added a check to not allow a creation if the username exists (this [check](https://github.com/keycloak/keycloak/blob/23.0.4/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L142-L144)) or change transaction behavior. Now the user is found in the kerberos provider and, because there is an exception, the transaction is rolled-back. So you finish with the error message saying there is a user with that username and no user imported because of the rollback.

One way to import the user is trying to login with a wrong password. That will create our user.

Probably we want to improve this, there are several options:

* Check the user existence with another transaction (importing the user is OK and can persists). But this was really a workaround before.
* Improving the UI to just lookup a user via username (or similar).
* Add something special to the kerberos provider for importing a specific user (maybe more general for providers that import users?).

The first solution is the easiest one but not very clean as you were using this as a workaround before. And the next two points needs some important changes that I don't think we can do in the short term. So I'm moving to the backlog for the moment, we will re-think this later.

**Comment by pedroigor** [comment] 2024-03-04 20:06
@rmartinc For me #3 sounds like the best solution as it relates not only to Kerberos but other providers such as SSD. It should also help to make such providers more consistent with LDAP in terms of providing specific actions to sync users.

**Closed** 2024-06-03 00:06 UTC
Labels: kind/bug, area/core, help wanted, team/core-iam, status/auto-expire, status/auto-bump, priority/normal, status/expired-by-bot
