### ISSUE TITLE
Logout is not working properly when 3rd party identity url's is configured inside keycloak

### ISSUE THREAD

**Issue by saisrinivasnakka** [keycloak/keycloak#24051] opened 2023-10-17 09:59 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

One of the customers in keycloak using third party identity provider. At first issue was even though we click on logout from spotlight it does not used to logout again used to display spotlight dashboard. But after making some configurations in keycloak(disabling cookies) when we clicked on logout it is directly redirecting to logout URL in fabric. Since, the customer is using 3rd party identity provider it is not even allowing him to click on sign out within 10 sec it is automatically redirecting to logout URL which was configured in fabric. Hence, session is not ended properly. We cant customise their keycloak logout with code since they have mentioned they are using cloud everything will be deployed on pipeline. Please refer following screenshot.

### Version

15.0.2

### Expected behavior

Logout is not working properly when 3rd party identity url's is configured inside keycloak. Session of third party identity provider is should get killed.

### Actual behavior

Logout is not working properly when 3rd party identity url's is configured inside keycloak. Session of third party identity provider is not getting killed.

### How to Reproduce?

1. Configure third party identity provider in keycloak identity provider section
2. Logout from keycloak application
3. Observe that third party identity session provider is still not killed.

**Comment by rmartinc** [comment] 2023-10-19 10:51
@saisrinivasnakka We cannot do anything with this issue report. Please give us something we can reproduce. From scratch, from a new realm, please give us the exact steps to reproduce the problem (and it should not include anything internal to your setup).

**Comment by pedroigor** [comment] 2024-01-05 13:36
Closing as can't reproduce and because of the lack of details.

**Closed by pedroigor** 2024-01-05 13:36 UTC
Labels: area/authentication, kind/bug, status/triage, team/core
