### ISSUE TITLE
Upgrade to Infinispan 14.0.4.Final

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#15977] opened 2022-12-13 11:30 UTC
### Description

We need to upgrade to ISPN 14.0.4.Final where JBoss Marshalling will be upgrated to 2.1.1.Final. This will fix `InaccessibleObjectException` on JDK 17 https://github.com/keycloak/keycloak/issues/15607.

**Comment by pedroigor** [comment] 2022-12-15 15:22
@martin-kanis Looks like we need this one ASAP? As per https://github.com/keycloak/keycloak/pull/15975#issuecomment-1352542223.

@Tristan971 Could you please provide a few more detail?

**Comment by Tristan971** [comment] 2022-12-15 15:26
> @Tristan971 Could you please provide a few more detail?

Small use of private api as per the stack trace in #15607 

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.util.AbstractMap() accessible: module java.base does not "opens java.util" to unnamed module @396a51ab

Was tracked down to a transitive dependency of Infinispan which is pulling and older jboss-marshalling-osgi version transitively.

While the original reporter experienced an LDAP-related issue, in my case this exception triggered while trying to delete a realm user. I didn't push the exploration of the symptoms further considering how many things go through the Infinispan caching layer when using clustered KC instances, as I suspect much more would have been broken. But this is merely suspicion.

**Comment by pedroigor** [comment] 2022-12-15 21:22
@Tristan971 Thanks.

Looks like we are missing at least some smoke tests in our GHA workflow to make sure clustering is not broken. 

Now we have tests running on 17, we should be able to do it.

@stianst ^

**Comment by martin-kanis** [comment] 2022-12-16 09:13
@pedroigor Once Infinispan 14.0.4.Final is released we should upgrade. This should go into Keycloak 21.

**Comment by stianst** [comment] 2022-12-16 12:13
> @Tristan971 Thanks.
> 
> Looks like we are missing at least some smoke tests in our GHA workflow to make sure clustering is not broken.
> 
> Now we have tests running on 17, we should be able to do it.
> 
> @stianst ^

We have clustering tests, but only with default JDK (11):
https://github.com/keycloak/keycloak/blob/main/.github/workflows/ci.yml#L249

This issue wasn't caught by those test in a PR where I'm upgrading to JDK 17 though:
https://github.com/keycloak/keycloak/actions/runs/3702967917/jobs/6273957251

This probably suggests the tests we run for clustering is insufficient:
https://github.com/keycloak/keycloak/blob/main/.github/workflows/ci.yml#L265

**Comment by ahus1** [comment] 2022-12-19 07:29
Infinispan 14.0.4.Final is now available: https://github.com/infinispan/infinispan/releases/tag/14.0.4.Final

**Comment by slominskir** [comment] 2023-01-17 14:44
Why wasn't this fix included in Keycloak 20.0.3?   Look like still using old version of Infinispan:

https://github.com/keycloak/keycloak/blob/d37bc90967a7fdc751df5ff40f4dc3143f212ce8/pom.xml#L84

When IS this planned to be released?  Can't use Java 17 until then.

**Comment by mhajas** [comment] 2023-01-17 15:17
Hello @slominskir, minor releases contain only security and regression fixes. This fix will be part of Keycloak 21.

**Comment by slominskir** [comment] 2023-01-17 15:49
https://github.com/keycloak/keycloak/issues/15014 says "plan" is for Keycloak 20 to support JDK 17.  Also stated in the [Keycloak 20 release notes](https://www.keycloak.org/2022/11/keycloak-2000-released#:~:text=Keycloak%20now%20supports%20OpenJDK%2017%20both%20for%20the%20server%20and%20adapters.) that Keycloak supports JDK 17.   I originally reported this as a bug due to the above, but it was closed and replaced with this "enhancement" ticket.  I guess plans change.

**Comment by mhajas** [comment] 2023-02-14 12:53
This issue was reopened due to backport to 20.0.4. Since this is already fixed in `upstream/main` and we decided we won't backport, I am closing this.

**Closed by mhajas** 2023-02-14 12:53 UTC
Labels: kind/enhancement, area/storage, area/infinispan, team/storage-sig
