### ISSUE TITLE
Download of Recovery Codes broken. File contains no Recovery Codes.

### ISSUE THREAD

**Issue by gruenewa** [keycloak/keycloak#31260] opened 2024-07-12 14:59 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When the user downloads the Recovery Codes into a file, the file does not contain any Recovery Code. Issue is that in https://github.com/keycloak/keycloak/blob/28fd38d13d5dbcab11c454fd80231f3047b15fd5/themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl#L108 the javascript wants to parse the Recovery Codes by using 

`var recoveryCodes = document.querySelectorAll(".kc-recovery-codes-list li");`

The not working code tries to find the dom elements using a CSS style class but it should instead look for an ID:

`var recoveryCodes = document.querySelectorAll("#kc-recovery-codes-list li");`

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Clicking button Download to download Recovery Codes should produce a file that contains the Recovery Codes.

### Actual behavior

Downloading the Recovery Codes using the download button produces a file without Recovery Codes.

### How to Reproduce?

On the configure Recovery Codes page click the Download button. Then check the contents of the file.

**Comment by thomasdarimont** [comment] 2024-07-15 07:52
I just gave this a spring with the latest Keycloak main (c33585a5f4) and couldn't reproduce the issue anymore.
The downloaded file contained the recovery codes as expected.

However, I think you are right that the css selector should be fixed, as the download currently works because the css selector `.kc-recovery-codes-list li` is effectivly handled as `li`.

**Comment by rmartinc** [comment] 2024-07-15 07:59
I cannot reproduce this. It works for me in chrome and firefox. AFAIK the expression `.kc-recovery-codes-list li` means the `li` components that are below another component with class `kc-recovery-codes-list`. You are right that `#kc-recovery-codes-list li` also works because that is the `li` components below the component with that id. But let's see what @jonkoops thinks about the PR.

**Comment by jonkoops** [comment] 2024-07-15 09:35
Sound like this would be fixed by #31106. @edewit do you want to handle these issues together? If this actually affects 25.0.1 the work should be backported as well.

**Comment by jonkoops** [comment] 2024-07-15 10:11
Just tested this on a clean build of 25.0.1 and I cannot reproduce it under the existing login theme. If this is an issue with the new (v2) theme, then it will can be handled under #31106. If not, we need more information to reproduce this.

**Comment by gruenewa** [comment] 2024-07-22 07:24
The bug is in Keycloak's `base`theme. It is still part current main branch: https://github.com/keycloak/keycloak/blob/28fd38d13d5dbcab11c454fd80231f3047b15fd5/themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl#L109

**Comment by jonkoops** [comment] 2024-07-22 10:43
Using the base theme I am able to reproduce this issue, thanks for the additional information @gruenewa. Note that the base theme is never supposed to be used as a standalone theme, but it is often extended by custom themes.

**Closed** 2024-07-22 11:44 UTC
Labels: kind/bug, area/login/ui, team/core-clients, priority/low, status/auto-expire, status/auto-bump, backport/25.0
