### ISSUE TITLE
Invalid redirect uri /

### ISSUE THREAD

**Issue by tiberiuzuld** [keycloak/keycloak#15539] opened 2022-11-17 08:44 UTC
### Area

authentication

### Describe the bug

Having the Valid Redirect Uri configured as ["/"] or ["%2F"] and using the client application to login, we get invalid redirect_uri.
The only way it works is setting Valid Redirect Uris to ["*"]

Login URL: 
https://server-name/auth/realms/my-realm/protocol/openid-connect/auth?client_id=client-id&redirect_uri=%2F&response_type=code&scope=openid%20offline_access&nonce=b5c4a72dff58c2c705960d203d3946ed9cUjLnxmg&state=33f5ca6a4d45cd5f2cd93a623d8eef0e9dMcVhLQg&code_challenge=4ihJW4emhCTVOUsehzsTdjAp3vBjwvzkCMFtPN4L-fg&code_challenge_method=S256

We are running 18.0.0 but we also tested on 19.0.0 and 20.0.0

![image](https://user-images.githubusercontent.com/15310395/202398675-ec499a1d-42e9-4b11-ab5f-c5402906c73c.png)

### Version

18.0.0 19.0.0 20.0.0

### Expected behavior

For the redirect URI to "/" to work 

### Actual behavior

Invalid parameter: redirect_uri
![image](https://user-images.githubusercontent.com/15310395/202396876-b5e526f3-10e5-49b2-b07c-94062a0ab8e0.png)

### How to Reproduce?

1. Create a client configuration as in screenshot
2. Try to login from client with redirect_uri set to "/"
3. Observe Invalid parameter: redirect_uri

### Anything else?

https://www.keycloak.org/docs/latest/server_admin/#con-basic-settings_server_administration_guide
https://www.keycloak.org/docs/latest/server_admin/#unspecific-redirect-uris_server_administration_guide

**Comment by jbman** [comment] 2022-11-17 09:12
Not a bug, you have no root URL set. You can set an absolute URL as redirect URI (including host) or a root URL and relative redirect URIs which are appended to build the complete valid redirect URIs.

**Comment by tiberiuzuld** [comment] 2022-11-17 10:28
If that is the case then how we handle the case where client application and keycloak are behind a a proxy and both can be served on multiple domains?

**Comment by mposolda** [comment] 2022-11-24 10:20
Thanks for reporting, but I am closing this as it doesn't look like a bug. Please consult Keycloak documentation for proxy settings / hostname for some more details.

**Closed by mposolda** 2022-11-24 10:20 UTC
Labels: area/authentication, kind/bug, status/rejected

**Comment by jbman** [comment] 2022-11-25 17:17
@tiberiuzuld you can add all required absolute redirect URIs with different host names explicitly at "Valid redirect URIs".

**Comment by tiberiuzuld** [comment] 2022-11-25 18:24
Hello @jbman ,
Yes we thought about that, but our application is deployed to many systems, 50+, and each can have 1-3 domains, so having the host names hard coded will be a lot more work, that's why where trying a relative path approach.
