### ISSUE TITLE
Group search in user view doesn't work as expected for nested groups

### ISSUE THREAD

**Issue by MartaGolabek** [keycloak/keycloak#34229] opened 2024-10-23 08:17 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have encountered this bug already in the version 23.0.6.: https://github.com/keycloak/keycloak/issues/28079 It still occurrs in 26.0.1.

Group search in user view doesn't work as expected for nested groups. Top-level groups including matching subgroup are displayed instead of the actual hit.

Let's assume that my hierarchy looks like this:

Top_Group_1 > Top_Group_2 > Matching_Subgroup

Then result will look like this:

Top_Group_1/Top_Group_2

Even when I navigate to 'Top_Group_2' and search for the matching subgroup there, 'Top_Group_1/Top_Group_2' will be displayed as a hit. It feels counterintuitive.

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Search returns subgroup matching provided search term, not the top level group.

### Actual behavior

Search returns top level group of the matching subgroup, not the subgroup itself.

### How to Reproduce?

1. Go to Users
2. Select a user
3. Go to Groups Tab
4. Click 'Join Group'
5. Type search term matching one of the nested groups
6. Top level group instead of a subgroup is returned

**Comment by ssilvert** [comment] 2024-10-23 18:59
@MartaGolabek Is this issue a duplicate of https://github.com/keycloak/keycloak/issues/34149 ?

**Comment by MartaGolabek** [comment] 2024-10-24 09:28
@ssilvert no it is something different. Parent groups are displayed, but the matching subgroup isn't.

**Closed** 2024-10-25 13:29 UTC
Labels: kind/bug, priority/important, area/admin/ui, team/ui

**Comment by ctrueltzsch** [comment] 2025-01-27 07:43
Tested in Version 26.1.0. The problem still occurs.
