### ISSUE TITLE
Create a Client Policy on realm with client-roles or client-scopes condition raises an expection on the Client details 

### ISSUE THREAD

**Issue by Dechadni** [keycloak/keycloak#19897] opened 2023-04-24 09:49 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I add a client policy to a realm, with "client-roles" or "client-scopes" as condition, it is no longer possible to display all Client details.

### Version

21.0.2 - 21.1

### Expected behavior

The creation of a new client policy should not impact the Keycloak administration interface.

### Actual behavior

It is no longer possible to navigate to Client Details following the addition of the Client Policy
Displayed error :  Network response was not OK

In the Java logs :
2023-04-24 09:39:36,588 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-21) Uncaught server error: java.lang.IllegalArgumentException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('test')
at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.keycloak.services.clientpolicy.condition.ClientRolesCondition$Configuration["roles"])
...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('test')
...

### How to Reproduce?

Create client policy on a realm (/realm-settings/client-policies/policies/add-client-policy):
Conditions : 
- Condition type : client-roles
- Negative Logic : off
- Client Roles : test

![Condition](https://user-images.githubusercontent.com/33252106/233961898-fd417d03-e63b-4cf6-a584-bb946aa7e7d5.png)

Client profiles : 
- fapi-1-baseline

![ClientPolicy](https://user-images.githubusercontent.com/33252106/233961895-f97d1cd7-19bf-45d5-89a2-2f718923cb13.png)

Navigate to a Client Detail :
Displayed error : Network response was not OK.

![Error](https://user-images.githubusercontent.com/33252106/233961899-91a96643-8fc5-4618-ab07-3a948b7445bc.png)

**Comment by edewit** [comment] 2023-04-26 06:49
Can't reproduce this, this is possibly fixed with #19871

**Comment by edewit** [comment] 2023-04-26 19:10
@Dechadni can you verify with the latest nightly that this is the case?

**Comment by Dechadni** [comment] 2023-04-27 08:30
Hello @edewit, 

It's ok for us in the nightly version.

Is there any idea of the release date?

Thank you,
Denis

**Comment by edewit** [comment] 2023-04-27 10:32
Keycloak 21.1.1 is out

**Closed by edewit** 2023-04-27 10:32 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui
