### ISSUE TITLE
User attributes with a text more than 255 characters

### ISSUE THREAD

**Issue by moolsbytheway** [keycloak/keycloak#9758] opened 2022-01-24 14:26 UTC
### Description

we need to have user attributes with a text more than 255 characters.

### Motivation

we want to have user attributes with a text more than 255 characters.

### Details

Implementation: 
when creating user attributes, the value field is limited to 255 characters, we want to remove this limitation by changing the type of the field "value" in the table "user_attribute" from varchar(255) to TEXT.

**Comment by meden** [comment] 2022-02-02 14:27
For some context: https://issues.redhat.com/browse/KEYCLOAK-9515

**Comment by iudex-** [comment] 2022-04-08 08:49
I'm running into the exact same issue as linked above.

Nothing crazy, just trying to store the link to the profile image as a user attribute:
![image](https://user-images.githubusercontent.com/56843/162399871-b4f00e34-d00d-49b2-9384-c34d5181285b.png)
![image](https://user-images.githubusercontent.com/56843/162400294-1cff8b3a-3822-452d-8c0d-19a428628e39.png)



We are not asking for 10k chars in a user attribute, but storing a link should surely be possible, no?

**Comment by myalcinkuru** [comment] 2022-09-05 10:30
We also faced with same issue while importing LDAP users. Keycloak writes LDAP_ENTRY_DN  to user attributes by default. Thus, value might exist the 255 chars.

**Comment by mhuin** [comment] 2022-09-12 13:22
To expand on @iudex- 's answer, if using mysql as a backend the workaround requires an extra step to recreate an index:

```
alter table USER_ATTRIBUTE drop index IDX_USER_ATTRIBUTE_NAME; 
alter table USER_ATTRIBUTE modify VALUE TEXT(100000) CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table USER_ATTRIBUTE ADD KEY `IDX_USER_ATTRIBUTE_NAME` (`NAME`, VALUE(400));
```

In this example I set the max size of the chunk of text to 100K characters (equivalent to mediumtext type); note that in order to ease indexing only the 400 first characters will be used to build the index. Adapt these values as seems sensible in your use cases.

**Comment by Iodun** [comment] 2022-11-02 03:39
I am using "openssh-lpk" schema on my OpenLDAP to store the users SSH public keys. With the 255 character limit its impossible to map this into Keycloak. That is yet another very simple and legitimate use case which needs the character limit to be increased or removed.

**Comment by kapalex** [comment] 2023-02-06 08:44
In case anyone needs the postgres variant for the same solution provided by @mhuin -

```
DROP INDEX idx_user_attribute_name; 
ALTER TABLE user_attribute ALTER COLUMN value SET DATA TYPE VARCHAR(10000);
CREATE INDEX idx_user_attribute_name ON user_attribute (name, left(value, 1000));
```

Removes the index, changes the type to 10k characters and creates an index on the first 1k characters of the value.

**Comment by vramik** [comment] 2023-02-06 13:02
Capability to store long attribute values will be supported in new store. There is no plan to add support to legacy store regarding it.

**Comment by hmlnarik** [comment] 2023-02-06 13:42
Duplicate of https://issues.redhat.com/browse/KEYCLOAK-9515. Thank you for your requirement. As @vramik mentioned above, this will only be addressed in the new store.

**Comment by zhengyang1988** [comment] 2023-06-14 08:27
I found the following solution for this problem on stackoverflow:

https://stackoverflow.com/questions/44851052/max-size-of-custom-user-attribute-in-keycloak#:~:text=Keycloak%27s%20attribute%20values%20maximum%20length,the%20field%20type%20to%20text%20.

Is it good to solve the problem this way? Since this requires modify the data type of a database field, will it cause any trouble in the future? (I've already tested that this change won't cause any problem for the automatic db migration from 18.0.2 to 21.1.1 by runing keycloak 21.1.1 directly on the database after making this db column datatype change)

**Comment by ahus1** [comment] 2023-08-03 12:31
As the new store hasn't arrived yet, re-opening it for evaluating it. 

We're investigating if the column can be enlarged; still it wouldn't hold unlimited amount of text.

**Comment by ahus1** [comment] 2023-10-05 14:02
AFAIK the value is searchable, and should have an index already. Some databases will restrict the length of a value when indexing it. There should also example for example on group attributes on how to do this.

**Comment by sgpinkus** [comment] 2023-12-17 19:33
> cd /opt/jboss/keycloak
> java -cp ./modules/system/layers/base/com/h2database/h2/main/h2-*.jar org.h2.tools.Shell -url "jdbc:h2:./standalone/data/keycloak;AUTO_SERVER=TRUE" -user sa -password s

Can you do this with the postgres JDBC driver?

**Comment by vramik** [comment] 2024-01-10 16:59
I've started a discussion on the topic: https://github.com/keycloak/keycloak/discussions/26071. Please comment there.

**Closed** 2024-02-16 07:09 UTC
Labels: kind/enhancement, area/storage, team/core-iam
