### ISSUE TITLE
Incorrect authorization response of protocol/openid-connect/token endpoint

### ISSUE THREAD

**Issue by kiriencoder** [keycloak/keycloak#12732] opened 2022-06-24 16:46 UTC
### Describe the bug

**protocol/openid-connect/token** endpoint  with **grant_type=urn:ietf:params:oauth:grant-type:uma-ticket** return unexpected scopes for client resources.

### Version

17.0, 18.0

### Expected behavior

When passing **permission=my_resource**, endpoint will return only scopes of resource, granted to the user by **permission ticket**.

### Actual behavior

When passing **permission=my_resource**, endpoint return all scopes of resource.

### How to Reproduce?

1. Set **User-Managed Access** to the realm.
2. Create ordinary user for the realm.
3. Create a private client for the realm (**back-client** for example).
4. Create client resource with **User-Managed Access** enabled and assigned resource scopes (for example **view**, **modify**). Default resource owner is private client (**project-0001** for example).
5. Create permission ticket for newly created resource from client service account with **requester**=new user ID and **scope**='view' using **authz/protection/permission/ticket** endpoint. 
6. See result in the user account:
![image](https://user-images.githubusercontent.com/108144070/175588156-5597451f-fba7-42b1-8c16-079134699326.png)
7. Call **protocol/openid-connect/token** endpoint with user access token and **grant_type=urn:ietf:params:oauth:grant-type:uma-ticket** without sending **resource** parameter. 
8. Got correct response: {'status_code': 200, 'permissions': [{'scopes': **['view']**, 'rsid': '9a0cfad9-558b-42a3-b179-999acc2bcb7b', 'rsname': 'project-0001'}]}
9. Call **protocol/openid-connect/token** endpoint with user access token and **grant_type=urn:ietf:params:oauth:grant-type:uma-ticket** and **resource=project-0001** parameter. 
10. Got incorrect response: {'status_code': 200, 'permissions': [{'scopes': **['modify', 'view']**, 'rsid': '9a0cfad9-558b-42a3-b179-999acc2bcb7b', 'rsname': 'project-0001'}]}

**Comment by kiriencoder** [comment] 2022-06-27 11:21
**Another incorrect authorization example.**
Client resource shared with an user via **authz/protection/uma-policy** endpoint.
Here is the policy assigned for the resource:
_{
	"id": "615dc3d5-6c2e-4428-ac18-9a11f9024bfd",
	"name": "project-0001:view-3",
	"type": "uma",
	"scopes": [
		"view"
	],
	"logic": "POSITIVE",
	"decisionStrategy": "UNANIMOUS",
	"owner": "005b1c28-174b-4a48-8972-6d5a2588fb84",
	"users": [
		"test-user-00002",
		"test-user-00004"
	]
}_
Permissions granted for **test-user-00002** and **test-user-00004**.
But both users got **not_authorized** calling **openid-connect/token**.
If we set the same policy with only one user - it works correctly.

**Comment by Leedwing** [comment] 2023-02-05 21:53
**Version: 20.03**

I'm experimenting the exact same problem described in the first example. I get wrong shared permissions for a resource when specifying the permission parameter in the request with the resource name as value.

**Comment by Leedwing** [comment] 2023-02-09 22:43
Instead of the resource name as value of the permission parameter when requesting the RPT through protection API, one can also use the resource id as described in this [thread](https://issues.redhat.com/browse/KEYCLOAK-18477). In this case the returned authorization scopes are right. 

Wrong authorization scopes as response is a huge security resource and should be fixed as soon as possible

**Comment by pedroigor** [comment] 2024-03-04 20:31
@Leedwing @kiriencoder It seems a duplicate of https://github.com/keycloak/keycloak/issues/25057. We want to make sure using the ID or the name works the same. Please, look at that issue for more details.

**Closed** 2024-03-04 20:32 UTC
Labels: area/authorization-services, kind/bug, team/core-iam
