### ISSUE TITLE
$authBaseUrl and $authAdminUrl should not be identical

### ISSUE THREAD

**Issue by FSeifer** [keycloak/keycloak#27203] opened 2024-02-21 12:31 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

If `–hostname-url`  and `–hostname-admin-url` are identical except for a port number, the corresponding Variables are identical which they should not be

### Version

23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

when setting 
`–hostname-url` to `https://keycloak.domain.com`
and
`–hostname-admin-url` to `https://keycloak.domain.com:9000`

the corresponding Variables for Client-Configuration are:

`$authBaseUrl` = `https://keycloak.domain.com`
`$authAdminUrl` = `https://keycloak.domain.com:9000`

### Actual behavior

Both Variables contain 

`https://keycloak.domain.com:9000`

### How to Reproduce?

launch Keycloak with 

`–hostname-url` = `https://keycloak.domain.com`
and
`–hostname-admin-url` =  `https://keycloak.domain.com:9000`

### Anything else?

This behaviours leads to wrong Base-URLs and more annoyingly to wrong Endpoint XMLs which than cannot be simply imported into other Configurations

**Comment by vmuzikar** [comment] 2024-02-29 17:11
@FSeifer This seems to be a duplicate of #19070. Let me know if you think otherwise.

**Closed by vmuzikar** 2024-02-29 17:11 UTC
Labels: kind/bug, area/core, team/cloud-native, status/triage
