### ISSUE TITLE
Cannot invoke "org.keycloak.authentication.RequiredActionFactory.isConfigurable()" because "factory" is null

### ISSUE THREAD

**Issue by shaidar** [keycloak/keycloak#32531] opened 2024-08-30 15:32 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

After upgrading from v24, in Keycloak UI, under any realm, clicking on the Authentication tab, the call to required-actions throws a 400 error and the error in the UI is "Network response was not OK"

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Clicking on the Authentication tab should provide a list of workflows

### Actual behavior

Call to required-actions throws a 400 error and the error in the UI is "Network response was not OK"

### How to Reproduce?

1. Login to Keycloak CI UI
2. Click on Authentication

### Anything else?

https://github.com/mitodl/ol-keycloak/issues/80

**Comment by mposolda** [comment] 2024-09-03 15:14
@shaidar I am closing as looks like the issue with undeployed provider. Please re-open just if it is not the case and deploying your provider does not help. In that case, please provide the details about your environment and what exactly you did to reproduce this issue.

**Closed** 2024-09-03 15:14 UTC
Labels: kind/bug, area/account/ui, team/core-clients

**Comment by bclements** [comment] 2024-09-03 17:44
i'm having the same issue but it only occurs when upgrading to keycloak 25. We did a stepwise upgrade from 21 to 24 and the authentication link worked, upgraded to 25, and we get this same error.  

is there a query we can make in the database that will show what the missing required action or custom provider is in order to debug this?

**Comment by shaidar** [comment] 2024-09-03 19:53
@mposolda I'm not completely sure I follow. So you are saying that I had a provider that created `RequiredActionFactory` references in the DB and now that provider is not there which is what's causing the issue I'm running into? If that's the case, shouldn't the UI at least load the other actions instead of blocking and throwing this error? Additionally, if I've had multiple providers over time, how would I go about knowing which one is the missing one?

I would imagine that others would run into this and simply showing that error isn't exactly helpful/useful. Even if this issue is related to a missing provider, I don't believe closing/ignoring this is the way to go as that seems to be a UI bug to me. Would love to hear more about this so that I can help resolve it on our end and also make sure that whoever runs into it has a clear idea of what the issue is.

**Comment by bclements** [comment] 2024-09-03 20:00
I second @shaidar . I'm having to modify the code itself to tell me what is broken. @shaidar  I can send you my modified AuthenticationManagementResource.java if you want once I ensures it tells me what I need.

**Comment by thomasdarimont** [comment] 2024-09-04 11:41
I added a simple null check with should prevent the issue once it is merged and deployed.

**Comment by bclements** [comment] 2024-09-04 15:35
Thank you @thomasdarimont

**Comment by drduker** [comment] 2024-09-05 14:05
This fixed my issue.  I believe caused by duplicate terms_and_conditions from upgrades/imports over the years.  One is uppercase and one is lowercase.

**Comment by chauhan2000** [comment] 2024-10-01 07:03
Hello, any updates on this fix?

**Comment by fran-ixo** [comment] 2024-10-02 13:56
> Hello, any updates on this fix? we upgraded to keycloak latest version and now it is showing error factory is null due to which we are not able to click on authentication @drduker

We are having the same experience

**Comment by thomasdarimont** [comment] 2024-10-02 15:48
The fix has been backported to the 25.x release branch and will be part of the next 25.0.x patch release besides being part of the Keycloak 26.x release.

**Comment by fran-ixo** [comment] 2024-10-02 15:50
Thanks for the clarification @thomasdarimont

**Comment by jonkoops** [comment] 2024-10-02 16:04
>  and will be part of the next 25.0.x patch release

It doesn't look like this issue was backported to the v25 branch, so this will only be part of the v26 release.

**Comment by thomasdarimont** [comment] 2024-10-02 17:49
@jonkoops I think this is in the release/25.0 branch, see: https://github.com/keycloak/keycloak/commits/release/25.0/
See: 6a7729641b901221b9984be96c3eb9632a56125c

**Comment by jonkoops** [comment] 2024-10-02 17:54
You are right, the commit is there. It seems it was backported under #33056, but the correct labels were not added to the issue. @ssilvert could you make sure the correct labels are attached? I think the problem is likely that a `backport/25.0` label was not added before your PR, so the bot did not attach the correct release label.

**Comment by ssilvert** [comment] 2024-10-02 19:08
> You are right, the commit is there. It seems it was backported under #33056, but the correct labels were not added to the issue. @ssilvert could you make sure the correct labels are attached? I think the problem is likely that a `backport/25.0` label was not added before your PR, so the bot did not attach the correct release label.

@jonkoops I don't understand.  The `release/25.0.7` label was added by the bot two weeks ago.
https://github.com/keycloak/keycloak/issues/32624

**Comment by jonkoops** [comment] 2024-10-09 15:47
Not to this issue
