### ISSUE TITLE
New Operator cannot install multiple instances

### ISSUE THREAD

**Issue by dolfim-ibm** [keycloak/keycloak#14220] opened 2022-09-06 12:40 UTC
### Describe the bug

The new Kubernetes operator should add the CR name in the `matchLabels`, of the statefulset (and possibly other resources), otherwise we cannot install multiple instances in the same namespace.

### Version

20.0.0-alpha.5

### Expected behavior

We can install multiple "isolated" instances in the same namespace.

### Actual behavior

The Operator creates two statefulset (one per instance), but when getting the details of any, we see both pods listed.

**Comment by jsorah** [comment] 2022-09-14 12:31
Seems related to #10562

**Comment by vmuzikar** [comment] 2023-06-26 09:57
Duplicate of https://github.com/keycloak/keycloak/issues/10562

**Closed by vmuzikar** 2023-06-26 09:57 UTC
Labels: kind/enhancement, status/triage, area/operator
