### ISSUE TITLE
Override of SSO Session Max for client does not work

### ISSUE THREAD

**Issue by Delirante** [keycloak/keycloak#9896] opened 2022-01-31 13:30 UTC
### Describe the bug

Value set in "Client Session Max" in Clients/settings/advanced settings is ignored in terms of invalidation of client session. It is taken into account only in terms of "Client Session Idle" (timeout for refresh token).

### Version

16.1.1

### Expected behavior

Expected behavior is written in popup.
![png1](https://user-images.githubusercontent.com/17479833/151799838-ba3c04c5-6673-4101-b9b4-cedaa1b6a447.png)

### Actual behavior

Tokens are not invalidated after time set in "Client Session Max" passed.

### How to Reproduce?

Setup of realm token:
![image](https://user-images.githubusercontent.com/17479833/151801001-234711c4-cc3b-4d12-98ef-d7e3ee0aa4aa.png)

Setup of client:
![image](https://user-images.githubusercontent.com/17479833/151800661-72512fa6-bd55-4d14-9086-d4120e58d2fd.png)

Set up of client advanced settings:
![image](https://user-images.githubusercontent.com/17479833/151801651-29e06550-a672-4075-84bb-986c7cda56dc.png)

Use standard flow for authentication.

**Comment by movertaker** [comment] 2022-02-23 17:02
We have the same problem. We set the Client Session Max to "2 hours". But Client session stay active until SSO Session Max of default 10 hours.

**Comment by momyyao** [comment] 2022-03-03 00:17
I just patched a fix for this issue with the following method rewrite in `OIDCLoginProtocol.java` in keycloak-services.
```
    protected boolean isAuthTimeExpired(UserSessionModel userSession, AuthenticationSessionModel authSession) {
        String authTime = userSession.getNote(AuthenticationManager.AUTH_TIME);
        String maxAge = authSession.getClientNote(OIDCLoginProtocol.MAX_AGE_PARAM);
        ClientModel client = authSession.getClient();
        if (maxAge != null) {
            int authTimeInt = authTime==null ? 0 : Integer.parseInt(authTime);
            int maxAgeInt = Integer.parseInt(maxAge);

            if (authTimeInt + maxAgeInt < Time.currentTime()) {
                logger.debugf("Authentication time is expired, needs to reauthenticate. userSession=%s, clientId=%s, maxAge=%d, authTime=%d", userSession.getId(),
                        client.getId(), maxAgeInt, authTimeInt);
                return true;
            }
        }

        AuthenticatedClientSessionModel clientSession = userSession.getAuthenticatedClientSessionByClient(client.getId());
        int clientSessionMaxLifespan;
        String clientSessionMaxLifespanPerClient = client.getAttribute(OIDCConfigAttributes.CLIENT_SESSION_MAX_LIFESPAN);
        if (clientSessionMaxLifespanPerClient != null && !clientSessionMaxLifespanPerClient.trim().isEmpty()) {
            clientSessionMaxLifespan = Integer.parseInt(clientSessionMaxLifespanPerClient);
        } else {
            clientSessionMaxLifespan = client.getRealm().getClientSessionMaxLifespan();
        }
        if (clientSession.getTimestamp() + clientSessionMaxLifespan < Time.currentTime()) {
            clientSession.detachFromUserSession();
            logger.debugf("Client session is expired, needs to reauthenticate. userSession=%s, clientId=%s, clientSessionMaxLifespan=%d, clientSessionTimestamp=%d",
                    userSession.getId(), client.getId(), clientSessionMaxLifespan, clientSession.getTimestamp());
            return true;
        }

        return false;
    }
```

This method was only checking for remember me expiration.  I added the second block to check for client session expiration.

**Comment by ptr1120** [comment] 2022-04-01 10:45
Hello,

same problem for `Client Session Idle` (`client.session.idle.timeout`). 
Specifying a value of e.g. 1 day for a client results in a refresh token that expires in 30 minutes (which is the realm default value  `SSO Session Idle` or `ssoSessionIdleTimeout`).
My use case is that the realm defines short access/refresh token lifetimes, but some clients may override these with a long lifetime.


Do I misunderstand the settings of lifetimes for realms and clients, or does this need to be fixed?

**Comment by momyyao** [comment] 2022-04-08 06:38
@ptr1120 Client sessions are attached to SSO sessions.  If a user session expires then all client sessions attached to it will be invalidated.  So SSO sessions need to be configured longer than client sessions.

**Comment by ptr1120** [comment] 2022-04-08 06:46
@momyyao thank you, that sounds reasonable.

**Comment by szlachet** [comment] 2022-04-14 12:58
@momyyao unfortunately this does not work. We tested it on version 16.1.1 and we only extend sessions for all clients. We use standard flow. Can you provide more details about your solution/case. Thanks.

**Comment by multi-io** [comment] 2022-04-14 13:05
I'm also seeing the same problem for the "Client Session Idle". I've created a realm with "SSO Session Idle" 9 minutes and "SSO Session Max" 20 minutes, and inside it a client with "Client Session Idle" 4 minutes and "Client Session Max" 6 minutes. When I create a new token and do nothing, the session is deleted after 9 minutes, not 4.

**Comment by eldarj** [comment] 2022-08-15 12:03
What is the latest update on this?

So Client Session Idle/Max cannot be shorted than SSO sessions?

**Comment by blevine** [comment] 2022-08-29 19:35
I'd like an update as well.  At this point, I'm not sure I understand the behavior of the per-client timeout overrides. If the SSO Session Idle for the realm is 2 hours and the Client Session Idle override for "client1" is one hour, what happens at 1 1/2 hours of inactivity?  If an application accesses a resource protected by client1, does the user NOT have to re-authenticate (since 2 hours has not passed)?  If an application accesses a resource protected by some other client, does the user have to re-authenticate (because more than 1 hour has passed)?

Regardless, it sounds like this doesn't really matter due to this bug.  However, I'd still like to understand what the behavior of these override settings is supposed to be.

**Comment by momyyao** [comment] 2022-08-31 17:42
After upgrade Keycloak to 16, I'm seeing the issue again.  I'm currently trying to figure out the cause myself.  From what I can tell, there is also issue with Spring Security adapter which has been deprecated as of Keycloak 15 in preference of Spring Security 5's own implementation.  So if you are still using the deprecated adapter for some reason, you'll need to fix the issue in both Keycloak and the adapter.

**Comment by momyyao** [comment] 2022-08-31 17:50
> I'd like an update as well. At this point, I'm not sure I understand the behavior of the per-client timeout overrides. If the SSO Session Idle for the realm is 2 hours and the Client Session Idle override for "client1" is one hour, what happens at 1 1/2 hours of inactivity? If an application accesses a resource protected by client1, does the user NOT have to re-authenticate (since 2 hours has not passed)? If an application accesses a resource protected by some other client, does the user have to re-authenticate (because more than 1 hour has passed)?
> 
> Regardless, it sounds like this doesn't really matter due to this bug. However, I'd still like to understand what the behavior of these override settings is supposed to be.

Technically, the client session attached to the SSO session should be detached and user should be re-authenticated through the same client again.  If the SSO session only has that one client session attached, it will be removed as well from what I see in `TokenManager`.  But like you said, it's not the case right now.

**Comment by ddurham2** [comment] 2022-11-15 07:49
Were these Client-Specific settings removed in v19?  I'm not seeing it anywhere now.  I see Access Token lifetime, but not the others!?

**Comment by momyyao** [comment] 2022-11-30 08:30
Think I found where the issue is.  In [KEYCLOAK-9563](https://github.com/keycloak/keycloak/pull/6766/files#diff-fd8b1c47da5ec7ee42d5450d3f7b73cdeef9c08af26b825c9245e3e6052c5cdf), the `TokenManager.validateToken` method was checking for not before in client, realm and user.  But after improvement, the checks skipped check on realm.  This is still the case in release 20.

So I changed the code from
```
        try {
            TokenVerifier.createWithoutSignature(oldToken)
                    .withChecks(NotBeforeCheck.forModel(client), NotBeforeCheck.forModel(session, realm, user))
                    .verify();
        } catch (VerificationException e) {
            throw new OAuthErrorException(OAuthErrorException.INVALID_GRANT, "Stale token");
        }

```
to
```
        try {
            TokenVerifier.createWithoutSignature(oldToken)
                    .withChecks(NotBeforeCheck.forModel(client), NotBeforeCheck.forModel(realm), NotBeforeCheck.forModel(session, realm, user))
                    .verify();
        } catch (VerificationException e) {
            throw new OAuthErrorException(OAuthErrorException.INVALID_GRANT, "Stale token");
        }
```

**Comment by amarlankri** [comment] 2023-01-10 11:22
Hello! I am using Keycloak v19 and I am faced to the same issue. Is there any update?

**Comment by rmartinc** [comment] 2023-03-02 09:35
I don't know what you are expecting to happen here. I'm going to try to explain what happens when you specify a different "SSO Session Idle" "Client Session Max" in a client.

* In OIDC the "SSO Session Max" and "SSO Session Idle" are used for two things. One for the tokens, both are used to set its lifetime, and the other for the lifetime and idle of the session in the infinispan cache.
* When you override the value with "Client Session Max" and "Client Session Idle" it only affects to the token part. The refresh token is now issued with those values in mind if they are smaller. That way if, for example the idle is 10m instead of default 30m, after 10m the refresh will be invalid and the application will need to go to the login page again to start a flow and obtain a new token (probably the browser SSO session is still there and the new token is issued without typing username/password).
* The expiration and idle times in infinispan are not modified. Because this is a SSO system, the SSO session can have several client sessions attached with different times, and the session is only deleted after the realm "SSO Session Max" or "SSO Session Idle" value.

This is what is expected to happen with the current version.

I don't know... Do you think the tooltips needs a different wording to clarify the behavior?

**Comment by armfergom** [comment] 2023-03-02 09:52
> (probably the browser SSO session is still there and the new token is issued without typing username/password).

Well, basically, this is what we were expecting to happen is that if the client session max is reached, then the username and password are requested again. So we basically misunderstood those two settings. 

I appreciate the explanation, this clarified things for me greatly.

**Comment by victorlopezsalazar** [comment] 2023-03-02 10:37
> Do you think the tooltips need a different wording to clarify the behavior?

Definitely, they do 😄. It's quite confusing to see sessions tab in the UI  for clients and users and also options relative to session timeouts and having to figure it out that the word "session" doesn't refer to the same concept in each place.

**Comment by blevine** [comment] 2023-03-02 12:29
In the tooltips and the documentation.  And maybe don't use the word "session" at all here.

**Comment by Delirante** [comment] 2023-03-02 13:01
> When you override the value with "Client Session Max" and "Client Session Idle" it only affects to the token part. The refresh token is now issued with those values in mind if they are smaller. That way if, for example the idle is 10m instead of default 30m, after 10m the refresh will be invalid and the application will need to go to the login page again to start a flow and obtain a new token (probably the browser SSO session is still there and the new token is issued without typing username/password).

In tooltip states: "Max time before a client session is expired. Tokens are invalidated when a client session is expired. If not set, it uses the standard SSO session Max value."
With this wording I suppose that value "Client Session Max" override value "SSO Session Max" for concrete client. If it does not do that then you need to change wording of tooltip accordingly.

As I said in description of bug: "Value set in "Client Session Max" is ignored in terms of invalidation of client session. It is taken into account only in terms of "Client Session Idle" (timeout for refresh token)."

You just said the same thing as I in description of bug. Client Session Idle is taken into account in terms of refresh token. But what about Client Session Max? What for is this attribute then?

**Comment by rmartinc** [comment] 2023-03-02 13:35
@Delirante You cannot override the "SSO Session Max" for expiration of the session as a whole, there is one single SSO user session for all the clients, so only one value can be assigned as max and idle. If a user goes to two different clients in the same session, when should the session expire? The first client value or the second value? That's why only the token lifespan is overriden. It can be said that the SSO Session Max is used in two different parts, and Client Session Max only in one.

I will prepare different tooltips (I will delete the first sentence for sure in each option) and I hope it will be clearer.

**Comment by Delirante** [comment] 2023-03-02 17:26
> @Delirante You cannot override the "SSO Session Max" for expiration of the session as a whole, there is one single SSO user session for all the clients, so only one value can be assigned as max and idle. If a user goes to two different clients in the same session, when should the session expire? The first client value or the second value? That's why only the token lifespan is overriden. It can be said that the SSO Session Max is used in two different parts, and Client Session Max only in one.
> 

Thank you for explanation, now it is clearer.

**Comment by rmartinc** [comment] 2023-03-03 08:34
I have just sent a PR that changes the texts. I decided to change the label to "Client Token Idle/Max" and the tool-tip explicitly says it does not affect the SSO session.

I'm linking here the old JIRA that introduced this feature for more information: https://issues.redhat.com/browse/KEYCLOAK-12406

**Closed** 2023-03-06 11:20 UTC
Labels: area/oidc, kind/bug

**Comment by mrgordon** [comment] 2023-08-11 16:07
Can someone confirm whether 16.1.1 actually has a bug with Client Idle Timeout? It seems to. I don't get logged out when I set Client Idle Timeout to a low value and wait a few additional minutes in case Keycloak waits an extra 2 minutes to expire the session as claimed in the docs. But if I set Session Idle Timeout to a low value then I get the expected behavior.

**Comment by mrgordon** [comment] 2023-08-15 14:11
@jonkoops @rmartinc If you have a minute, we are still struggling with getting Client Idle Timeout to do anything meaningful. If I set it to 1 minute and wait a long time, users are still able to access the application and they get a new `Last Access` time for the session. We only get logged out when SSO Session Idle time is hit. Is our app somehow checking the SSO Session when it should check the Client Session? I'm not aware of how to specifically force a valid Client Session for login.

**Comment by jonkoops** [comment] 2023-08-21 16:04
@mrgordon are you on the latest version of Keycloak?

**Comment by mrgordon** [comment] 2023-08-28 11:48
@jonkoops we are on 16.1.1 the version originally referenced in this ticket. From what I could gather the only thing wrong in that version according to this ticket was the tooltip descriptions but the functionality should work as intended.

**Comment by rmartinc** [comment] 2023-08-28 13:13
In versions previous to https://github.com/keycloak/keycloak/pull/17525 the client values were never used for the session calculation (idle or max life). This was more or less done on purpose (that's why we responded about tooltips initially). But finally we decided to change the behavior and since version 22 the client values are also used in client session timeouts. So it should work now in 22.0.x. Tool-tip changes were also reverted.
