### ISSUE TITLE
bin/kc.sh start-dev fails with banner issue

### ISSUE THREAD

**Issue by ieugen** [keycloak/keycloak#10954] opened 2022-03-26 00:45 UTC
### Describe the bug

I downloaded keycloak 17.0.1 tar.gz and ran kc.sh start-dev.
It failed with the following error:

```
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.BannerProcessor#recordBanner threw an exception: java.lang.IllegalArgumentException: Bad escape
        at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:103)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at io.quarkus.deployment.steps.BannerProcessor.isQuarkusCoreBanner(BannerProcessor.java:117)
        at io.quarkus.deployment.steps.BannerProcessor.getBanner(BannerProcessor.java:93)
        at io.quarkus.deployment.steps.BannerProcessor.readBannerFile(BannerProcessor.java:48)
        at io.quarkus.deployment.steps.BannerProcessor.recordBanner(BannerProcessor.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

ERROR: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.BannerProcessor#recordBanner threw an exception: java.lang.IllegalArgumentException: Bad escape
        at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:103)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at io.quarkus.deployment.steps.BannerProcessor.isQuarkusCoreBanner(BannerProcessor.java:117)
        at io.quarkus.deployment.steps.BannerProcessor.getBanner(BannerProcessor.java:93)
        at io.quarkus.deployment.steps.BannerProcessor.readBannerFile(BannerProcessor.java:48)
        at io.quarkus.deployment.steps.BannerProcessor.recordBanner(BannerProcessor.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

ERROR: Bad escape
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

17.0.1

### Expected behavior

Have keycloak running

### Actual behavior

Failed with error

### How to Reproduce?

Download keycloak tar.gz or zip. 
Unpack and cd. 
run ./bin/kc.sh start-dev 

### Anything else?

Debian 11 on amd64 using openjdk 11

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)
```

**Comment by andreaTP** [comment] 2022-03-29 11:07
Hi @ieugen , thanks for opening this issue, unfortunately I'm not able to reproduce, those are the steps that I attempted:

- write a `Dockerfile` with the following content:
```dockerfile
FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-debian AS build-env

ENV KEYCLOAK_VERSION 17.0.1
ARG KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

RUN apt-get install -y tar gzip

ADD $KEYCLOAK_DIST /tmp/keycloak/

RUN (cd /tmp/keycloak && \
    tar -xvf /tmp/keycloak/keycloak-*.tar.gz && \
    rm /tmp/keycloak/keycloak-*.tar.gz) || true

RUN mv /tmp/keycloak/keycloak-* /opt/keycloak && mkdir -p /opt/keycloak/data

RUN chmod -R g+rwX /opt/keycloak

FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-debian

COPY --from=build-env --chown=1000:0 /opt/keycloak /opt/keycloak

RUN echo "keycloak:x:0:root" >> /etc/group && \
    echo "keycloak:x:1000:0:keycloak user:/opt/keycloak:/sbin/nologin" >> /etc/passwd

USER 1000

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "/opt/keycloak/bin/kc.sh" ]
```

- build it with:

```bash
docker build . -t kc-debian
```

- run it with:

```bash
docker run --rm -it kc-debian start-dev
```

and this is the output, that is pretty much the expected one:
```
Updating the configuration and installing your custom providers, if any. Please wait.
2022-03-29 11:04:24,923 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 7524ms
2022-03-29 11:04:30,597 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-03-29 11:04:32,011 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-03-29 11:04:32,033 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-03-29 11:04:32,130 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-03-29 11:04:32,444 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.6.Final
2022-03-29 11:04:33,154 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_943178, Site name: null
2022-03-29 11:04:35,674 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2022-03-29 11:04:38,635 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2022-03-29 11:04:40,737 INFO  [io.quarkus] (main) Keycloak 17.0.1 on JVM (powered by Quarkus 2.7.5.Final) started in 15.402s. Listening on: http://0.0.0.0:8080
2022-03-29 11:04:40,737 INFO  [io.quarkus] (main) Profile dev activated. 
2022-03-29 11:04:40,738 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-03-29 11:04:40,743 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

Are you passing any extra argument? Can you share the complete command line options passed to `start-dev` and/or the relevant environment variables?

Thanks in advance!

**Comment by ieugen** [comment] 2022-03-30 07:11
Hi @andreaTP , thanks for looking into this. 
Nice touch with Docker. 
I tried that and it works so perhaps is something wrong with my setup or an issue with the Debian packages. 

I've uploaded the output of the `script` command that I use. 
[typescript.txt](https://github.com/keycloak/keycloak/files/8377908/typescript.txt)

**Comment by andreaTP** [comment] 2022-03-30 07:33
Hi @ieugen , perfect! Thanks a lot for the attached file!
Now I can reproduce the issue with this `Dockerfile` :
```dockerfile
FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-debian AS build-env

ENV KEYCLOAK_VERSION 17.0.1
ARG KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

RUN apt-get install -y tar gzip

ADD $KEYCLOAK_DIST /tmp/keycloak/

RUN (cd /tmp/keycloak && \
    tar -xvf /tmp/keycloak/keycloak-*.tar.gz && \
    rm /tmp/keycloak/keycloak-*.tar.gz) || true

RUN mkdir -p "/opt/Descărcări/keycloak" && mv /tmp/keycloak/keycloak-* "/opt/Descărcări/keycloak" && mkdir -p "/opt/Descărcări/keycloak/data"

RUN chmod -R g+rwX "/opt/Descărcări/keycloak"

FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-debian

COPY --from=build-env --chown=1000:0 "/opt/Descărcări/keycloak" "/opt/Descărcări/keycloak"

RUN echo "keycloak:x:0:root" >> /etc/group && \
    echo "keycloak:x:1000:0:keycloak user:\"/opt/Descărcări/keycloak\":/sbin/nologin" >> /etc/passwd

USER 1000

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "/opt/Descărcări/keycloak/keycloak-17.0.1/bin/kc.sh" ]
```

and running it with `docker run --rm -it kc-debian start-dev` produces the stack trace you reported.

While we work on a fix we can already appreciate that the root cause of the issue are the unicode characters in the path (i.e. contained in `Descărcări`).
As a workaround you can unpack the keycloak distribution on a path that doesn't contain those character (e.g. `/opt`) and everything will work as expected.

**Comment by ieugen** [comment] 2022-03-30 10:31
ok, thanks. 
I did not imagine the path had any implications.
I am using Romanian locales LC_ALL and LC_... .
I passed those to docker but saw no change. 

I imagine a fix in quarkus is required ?

**Comment by andreaTP** [comment] 2022-03-31 15:39
The fix in Quarkus has been merged, @pedroigor @DGuhr should we explicitly ask for the backport?

**Comment by ieugen** [comment] 2022-04-01 09:03
I saw a label for triage backport 2.7 - so it might be considered. 
I don't have strong opinions in either direction. 
I am satisfied with the workaround and will deploy in Docker.
I will close this issue if there are no objections.

**Comment by andreaTP** [comment] 2022-04-01 10:08
Sounds good to me, thanks for the report @ieugen !

**Closed by andreaTP** 2022-04-01 10:08 UTC
Labels: kind/bug, status/triage
