### ISSUE TITLE
duplicate users are displayed when User Federation and Mappers "username = cn"

### ISSUE THREAD

**Issue by ArminRadmueller** [keycloak/keycloak#24058] opened 2023-10-17 14:20 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Once in the User Federation with Active Directory (LDAP) is set up and in the Mappers the Username attribute in the "LDAP Attribute" field is changed from userPrincipalName to cn, the users are displayed duplicated in the search. When the attribute is reset to userPrincipalName, the display is correct again. The sync always displays the same number of items, so it seems to be a display error.

### Version

22.0.4

### Expected behavior

Microsoft Edge, ver. 118.0.2088.46 (Official build) (64-bit)

### Actual behavior

Users are displayed duplicated

### How to Reproduce?

1. setup User Federation with Active Directory (LDAP)
2. under the "Mappers"-tabs the Username attribute in the "LDAP Attribute" field is changed from userPrincipalName to cn

**Comment by ssilvert** [comment] 2023-10-19 01:19
@ArminRadmueller I can not reproduce your issue, but I'm not sure I am understanding your description.

Please provide more detailed steps to reproduce.  Screen shots would be helpful.

**Comment by ssilvert** [comment] 2023-10-31 19:36
@ArminRadmueller I'm going to close this now.  If you can provide detailed steps to reproduce then we can reopen.

**Comment by ArminRadmueller** [comment] 2023-10-31 21:57
Hi @ssilvert, 
I sorry for the late reply, unfortunately I totally missed this message. I send you two screenshots to explain it better:
![2023-10-31_22h52_09](https://github.com/keycloak/keycloak/assets/12393757/89fdebf9-5be4-4b93-bcfd-415ea29dbabc)
![2023-10-31_22h53_08](https://github.com/keycloak/keycloak/assets/12393757/e021cda2-6304-42fe-ad4a-73f9a904435e)

**Comment by jonkoops** [comment] 2023-11-01 11:49
@ssilvert don't forget to add the triage label when re-opening issues, the Keycloak bot will remove them automatically when issues are closed.

**Comment by ssilvert** [comment] 2023-11-01 18:32
> @ssilvert don't forget to add the triage label when re-opening issues, the Keycloak bot will remove them automatically when issues are closed.

Thanks @jonkoops

**Comment by ssilvert** [comment] 2023-11-08 19:47
@ArminRadmueller Go to the Users section and open the Inspector in your browser.  Go to the `Network` tab of the inspector.

When you do your search for `adminarminr` look at the response from the REST API call to `brute-force-user?briefRepresentation`.  Please paste the response into a comment so I can see it.

**Comment by ArminRadmueller** [comment] 2023-11-08 20:08
Hi @ssilvert, nice to hear you. I attach the requested screenshot.
![2023-11-08_21h04_40](https://github.com/keycloak/keycloak/assets/12393757/9691744d-4456-4ea6-9b7e-a0bd084a0e0b)

**Comment by ssilvert** [comment] 2023-11-09 13:11
Thanks @ArminRadmueller.  This verifies that it is not a UI issue.  For whatever reason, the REST API is returning two copies of the same user.  I'm going to transfer this issue to the core team.

**Comment by ArminRadmueller** [comment] 2023-11-27 18:05
Hi all, same issue with new version 23.0.0

**Comment by rmartinc** [comment] 2023-12-21 11:39
Hi @ArminRadmueller! But what is the `Username LDAP attribute` in the ldap configuration? CN or samaccountname? You have to set it to cn too.

Nevertheless I think this is a duplicate of #24141. The root cause is the duplicate is located using the username and I think that it's better to use the guid which identifies the user better.

**Comment by pedroigor** [comment] 2024-01-05 13:40
Closing as a duplicate as per @rmartinc last comment.

**Closed by pedroigor** 2024-01-05 13:39 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core
