### ISSUE TITLE
Can't add user to "parent group" if member of a subgroup

### ISSUE THREAD

**Issue by olemathias** [keycloak/keycloak#9482] opened 2022-01-10 20:56 UTC
### Describe the bug

Trying to add a user to a parent group when the user already is a member of a subgroup don't work. No errors, just not added to the group.

### Version

16.1.0

### Expected behavior

User gets added to the group or a error is thrown.

### Actual behavior

User is not added to the group and no visible errors.

### How to Reproduce?

1. Create a new group.
2. Create a group under the newly created group.
3. Add a user to the subgroup created in step 2.
4. Try to add the user to the parent group created in step 1.

You will get `Success! Added group membership`, but the user is not added to the group. The same is true from the API.

The reverse order (add to the root group first) works as excepted.

### Anything else?

If this is working as expected the API should return a error, and doing it in reverse should not work.

![image](https://user-images.githubusercontent.com/891048/148834534-d3cd163f-450d-44c5-b402-6a124e7015d4.png)

**Comment by KirschbaumP** [comment] 2022-02-13 20:24
I am also very interested in a solution to this problem.

**Comment by leischt** [comment] 2022-03-17 09:53
PR: https://github.com/keycloak/keycloak/pull/10785

**Comment by hmlnarik** [comment] 2022-06-22 08:09
Thank you for this report.

This is expected behaviour.

By design, a user is a member of all groups assigned to that user, and also recursively of all parent groups of those groups.

Suppose there are groups _overgroup1_ and _overgroup1/subgroup1_ like in the example above.
Hence the state where a user is both an assigned member of _overgroup1_ and _overgroup1/subgroup1_ is overspecified. This is because it is sufficient for a user to be member of _overgroup1/subgroup1_ which implicitly means they are also member of _overgroup1_.

Keycloak prevents such overspecification if it it can, adding an user into _overgroup1_ when it is a member of _overgroup1/subgroup1_ ignores the request. It cannot prevent though adding an user to _overgroup1/subgroup1_ when they are member of _subgroup1_, since the membership of _overgroup1/subgroup1_ does not follow from being in _overgroup1_.

Hence this is expected behaviour.

One could argue that the error should be returned every time a user is assigned to a group which they belong to either directly or indirectly. Currently an error is returned only for the former case and not for the latter. The latter case could be improved.

**Comment by KirschbaumP** [comment] 2022-06-22 08:41
Hello, thank you for your reply. I think there are some inconsistencies in this behavior.

Case 1:
1. add user to supergroup1/subgroup1.
2. add user to supergroup1.
Result:
User is a member of supergroup1/subgroup1.

Case 2:
1. add user to supergroup1
2. user to supergroup1/subgroup1.
Result:
The user is a member of supergroup1 and supergroup1/subgroup1.

If Keycloak prevents such over-specification, the result of case 2 must be that the user is a member of supergroup1/subgroup1 only and not both.

In my opinion, there is no over-specification if the user is a member of both groups. There are some cases where a user is a member of supergroup1/subgroup1 and supergroup1 and then is removed from supergroup1/subgroup1 and should be a member of supergroup1.

To realize this use case, we need to check if the user is a member of Overgroup1 before adding him to Overgroup1/Subgroup1.

**Comment by hmlnarik** [comment] 2022-06-22 09:52
I agree that this behaviour is not ideal and leads to inconsistencies. However this behaviour is not erroneous, it is one choice of several possible.

Groups respect inheritance by design. Whether it should be allowed to assign groups to users regardless of inheritance is a different question. Could you start a [discussion](https://github.com/keycloak/keycloak/discussions/categories/feedback) if you are interested in bringing in this enhancement?

**Comment by KirschbaumP** [comment] 2022-06-24 14:27
I started a [discussion (#12726)](https://github.com/keycloak/keycloak/discussions/12726).
Feel free to participate and produce an enhancement.

**Closed** 2022-09-06 19:31 UTC
Labels: kind/bug, area/admin/api, status/triage
