### ISSUE TITLE
Unfriendly error message when user-storage provider not available

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#24458] opened 2023-11-01 09:48 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

- Create a realm `test`

- Create LDAP provider in that realm, which is not working. For example fill something like:

Connection URL: ldap://foo-not-working
Bind DN: some
Bind secret: some
Edit Mode: Writable
Users DN: ou=system,ou=com

- Go to `Users` and try to search for user `john`.

- I have unclear error screen shown in the admin console. Could we have some better? There is exception in server.log, but not all UI administrators might have access to server.log etc...

![Screenshot from 2023-11-01 10-45-31](https://github.com/keycloak/keycloak/assets/1223965/6fdf6551-5e31-49d3-83ed-8185077e7ebd)

### Version

nightly

### Expected behavior

Some more clear error message like `Connection to provider 'your-ldap-provider' not available` or at least `javax.naming.CommunicationException: localhost:10389 [Root exception is java.net.ConnectException: Connection refused]`

### Actual behavior

Strange error message `b.map is not a function`

### How to Reproduce?

See above

**Comment by jonkoops** [comment] 2023-11-01 11:25
@ssilvert I gave this a medium impact, feel free to change this if you disagree about the severity.

**Comment by jonkoops** [comment] 2023-11-01 11:30
Upon closer inspection, this seems to be a duplicate of #24293, I will close it as such.

**Comment by jonkoops** [comment] 2023-11-01 11:30
Duplicate of #24293

**Closed by jonkoops** 2023-11-01 11:30 UTC
Labels: kind/bug, impact/medium, area/admin/ui, team/ui
