### ISSUE TITLE
API users call always querys users from LDAP even if "Always Read Value From LDAP" options are set to false

### ISSUE THREAD

**Issue by csbrogi** [keycloak/keycloak#34954] opened 2024-11-14 11:43 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I have configured a user federation with some mappers. All attributes are marked as read only and alway read value from LDAP is turned off. "Edit Mode" is "Read Only" and "Import users" is on. When I sync the users, I can see that the userss are queried from LDAP (in the log of the openldap-server). The SQL-database contains the attributes in the user_attribute table as expected.
Now when I list the users by rest-call (brief-representation is set to false) I see that **each user** is queried every time

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The Users are read from the internal database

### Actual behavior

Each user is read from LDAP

### How to Reproduce?

Create a LDAP User-Federation 
Query the users by [](https://keycloak:443/admin/realms/CRMTest/users?first=0&max=14&enabled=true)

**Comment by pedroigor** [comment] 2024-11-21 19:09
The behavior is expected because users from LDAP must be validated (based on their IDs) to make sure they still exist in LDAP.

The attributes, however, will still be read only from the local database.

**Comment by csbrogi** [comment] 2024-11-25 11:39
Hello Pedro,
I think you are not right. I have configured all mappers to `"always.read.value.from.ldap=false"`
But in the log of the ldap-server I see, that the allributes are querried:

`openldap  | 674461af conn=1000 op=9872 SRCH base="dc=corp,dc=acme,dc=local" scope=2 deref=3 filter="(uid=brossela)"
openldap  | 674461af conn=1000 op=9872 SRCH attr=telephoneNumber manager mail givenName cn title objectclass createTimestamp modifyTimestamp employeeNumber uid postalAddress employeeType secretary krbPrincipalName sn
openldap  | 674461af conn=1000 op=9872 SEARCH RESULT tag=101 err=0 nentries=1 text=
openldap  | 674461af conn=1000 op=9873 SRCH base="dc=corp,dc=acme,dc=local" scope=2 deref=3 filter="(uid=thornbea)"
openldap  | 674461af conn=1000 op=9873 SRCH attr=telephoneNumber manager mail givenName cn title objectclass createTimestamp modifyTimestamp employeeNumber uid postalAddress employeeType secretary krbPrincipalName sn
openldap  | 674461af conn=1000 op=9873 SEARCH RESULT tag=101 err=0 nentries=1 text=
openldap  | 674461af conn=1000 op=9874 SRCH base="dc=corp,dc=acme,dc=local" scope=2 deref=3 filter="(uid=boucoura)"
openldap  | 674461af conn=1000 op=9874 SRCH attr=telephoneNumber manager mail givenName cn title objectclass createTimestamp modifyTimestamp employeeNumber uid postalAddress employeeType secretary krbPrincipalName sn
openldap  | 674461af conn=1000 op=9874 SEARCH RESULT tag=101 err=0 nentries=1 text=
openldap  | 674461af conn=1000 op=9875 SRCH base="dc=corp,dc=acme,dc=local" scope=2 deref=3 filter="(uid=nahmiasa)"
openldap  | 674461af conn=1000 op=9875 SRCH attr=telephoneNumber manager mail givenName cn title objectclass createTimestamp modifyTimestamp employeeNumber uid postalAddress employeeType secretary krbPrincipalName sn
openldap  | 674461af conn=1000 op=9875 SEARCH RESULT tag=101 err=0 nentries=1 text=
openldap  | 674461af conn=1000 op=9876 SRCH base="dc=corp,dc=acme,dc=local" scope=2 deref=3 filter="(uid=parhama)"
openldap  | 674461af conn=1000 op=9876 SRCH attr=telephoneNumber manager mail givenName cn title objectclass createTimestamp modifyTimestamp employeeNumber uid postalAddress employeeType secretary krbPrincipalName sn
openldap  | 674461af conn=1000 op=9876 SEARCH RESULT tag=101 err=0 nentries=1 text=
`


the LDAP User Federation is configured as follows
```
 "org.keycloak.storage.UserStorageProvider": [
      {
        "id": "bf16cb03-133a-48dc-9951-62b5d48e6db1",
        "name": "ldap",
        "providerId": "ldap",
        "subComponents": {
          "org.keycloak.storage.ldap.mappers.LDAPStorageMapper": [
            {
              "id": "b4ee2d60-e7ba-4fcc-8b40-c7adf94c0b15",
              "name": "telephoneNumber",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "telephoneNumber"
                ],
                "attribute.force.default": [
                  "false"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "telephoneNumber"
                ]
              }
            },
            {
              "id": "72feba14-275e-4c94-83ba-d6322cc081d8",
              "name": "postalAddress",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "postalAddress"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "user.model.attribute": [
                  "postalAddress"
                ]
              }
            },
            {
              "id": "8fc77a1a-75a0-4b23-9708-84885984c2e1",
              "name": "employeeType",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "employeeType"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "user.model.attribute": [
                  "employeeType"
                ]
              }
            },
            {
              "id": "f43b5dac-4d82-4452-a4de-804ddc2c8601",
              "name": "last name",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "sn"
                ],
                "is.mandatory.in.ldap": [
                  "true"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "read.only": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "user.model.attribute": [
                  "lastName"
                ]
              }
            },
            {
              "id": "d2eb8ff3-e86f-49d7-824f-3d30a9dce9e8",
              "name": "username",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "cn"
                ],
                "is.mandatory.in.ldap": [
                  "true"
                ],
                "read.only": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "user.model.attribute": [
                  "username"
                ]
              }
            },
            {
              "id": "fd63cb00-8c88-48ae-8582-c5d9ecbd5f01",
              "name": "employeeNumber",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "employeeNumber"
                ],
                "attribute.force.default": [
                  "false"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "user.model.attribute": [
                  "USER_ID"
                ]
              }
            },
            {
              "id": "a1a64bcd-09c7-4bc2-b8cb-9c1e558c6403",
              "name": "modify date",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "modifyTimestamp"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "modifyTimestamp"
                ]
              }
            },
            {
              "id": "192989be-ca99-4e3e-bad6-15284d770e07",
              "name": "creation date",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "createTimestamp"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "createTimestamp"
                ]
              }
            },
            {
              "id": "f379632f-d0b4-41d0-9298-50935ec8c0e0",
              "name": "first name",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "givenName"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.mandatory.in.ldap": [
                  "true"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "false"
                ],
                "user.model.attribute": [
                  "firstName"
                ]
              }
            },
            {
              "id": "bed37f7c-075d-4a21-b5e3-2b3a800e4942",
              "name": "secretary",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "secretary"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "secretary"
                ]
              }
            },
            {
              "id": "65d6d012-7bbc-4685-a9e6-7731422a1be7",
              "name": "title",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "title"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "user.model.attribute": [
                  "title"
                ]
              }
            },
            {
              "id": "94f05b69-7126-4702-8768-fda63d92d37a",
              "name": "email",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "mail"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "attribute.force.default": [
                  "true"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "email"
                ]
              }
            },
            {
              "id": "1b6baeba-df9d-4824-b691-b1f7fdf9e7a3",
              "name": "manager",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "manager"
                ],
                "attribute.force.default": [
                  "false"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "is.binary.attribute": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "user.model.attribute": [
                  "manager"
                ]
              }
            }
          ]
        },
        "config": {
          "pagination": [
            "false"
          ],
          "fullSyncPeriod": [
            "-1"
          ],
          "startTls": [
            "false"
          ],
          "usersDn": [
            "dc=corp,dc=acme,dc=local"
          ],
          "connectionPooling": [
            "true"
          ],
          "cachePolicy": [
            "EVICT_WEEKLY"
          ],
          "evictionHour": [
            "0"
          ],
          "useKerberosForPasswordAuthentication": [
            "false"
          ],
          "importEnabled": [
            "true"
          ],
          "enabled": [
            "true"
          ],
          "bindCredential": [
            "**********"
          ],
          "bindDn": [
            "cn=admin,dc=corp,dc=acme,dc=local"
          ],
          "usernameLDAPAttribute": [
            "cn"
          ],
          "changedSyncPeriod": [
            "-1"
          ],
          "lastSync": [
            "1732533413"
          ],
          "vendor": [
            "rhds"
          ],
          "uuidLDAPAttribute": [
            "uid"
          ],
          "connectionUrl": [
            "ldap://hurz10.dev.bpanda.com"
          ],
          "allowKerberosAuthentication": [
            "false"
          ],
          "syncRegistrations": [
            "false"
          ],
          "authType": [
            "simple"
          ],
          "connectionTimeout": [
            "6666666"
          ],
          "krbPrincipalAttribute": [
            "krbPrincipalName"
          ],
          "searchScope": [
            "2"
          ],
          "useTruststoreSpi": [
            "always"
          ],
          "usePasswordModifyExtendedOp": [
            "false"
          ],
          "trustEmail": [
            "false"
          ],
          "userObjectClasses": [
            "inetOrgPerson, organizationalPerson"
          ],
          "evictionMinute": [
            "0"
          ],
          "rdnLDAPAttribute": [
            "cn"
          ],
          "evictionDay": [
            "1"
          ],
          "editMode": [
            "READ_ONLY"
          ],
          "validatePasswordPolicy": [
            "false"
          ]
        }
      }
    ],
```

**Comment by csbrogi** [comment] 2024-11-25 12:41
In my opinion it is sufficient to read the user-data on sync from LDAP and return the values from Database otherwise.

**Comment by pedroigor** [comment] 2024-12-02 19:31
Thanks for the additional details about your configuration.

Each mapper will run individually when querying a specific attribute. If the `always read from ldap` setting is enabled, the attribute value will be resolved from the LDAP entry returned from LDAP when executing the query.

You will see an LDAP query to get the user by the entry ID, that is how it was designed. Keycloak will run additional logic when there is no link between a local user and its corresponding entry in LDAP.

To see what I'm suggesting, please do the following:

* Mark `firstName` mapper to not read from LDAP
* Mark `lastName` mapper to read from LDAP
* Update the `firstName` in your LDAP server and see you won't see the updated value when listing users
* Update the `lastName` in your LDAP server and see you will see the updated value when listing users

Hopefully, we are close to sorting this out but I'm not sure if the behavior you described is a bug.

However, I see a possible bug when editing a user in admin console. The `always read from LDAP` setting is not working when fetching the user representation. Need more investigation and it seems a different issue.

**Comment by csbrogi** [comment] 2024-12-03 12:45
The behaviour of keycloak is a problem in our environment, because we have a lot of users (about 40,000) and querying  them on every request, is not only costly, but also error-prone: if a user cannot be retrieved from LDAP for some reason, the whole request fails. This happens in our environment every then and now.
As you requested, I did some more research:
I changed the sn (lastName) to "Always read" and changed the values of fist- and lastName. The users-Request with _first and max_ or with _filter mail=..._ returns only the updated lastName, whereas the firstName has the old value. Nevertheless log of the openldap shows, that the full information is requested each time:
`openldap  | 674ef958 conn=1024 op=507 SRCH base="dc=corp,dc=acme,dc=local" scope=2 deref=3 filter="(uid=brossela)"`
`openldap  | 674ef958 conn=1024 op=507 SRCH attr=telephoneNumber manager mail givenName cn title objectclass createTimestamp modifyTimestamp employeeNumber uid postalAddress employeeType secretary krbPrincipalName sn
openldap  | 674ef958 conn=1024 op=507 SEARCH RESULT tag=101 err=0 nentries=1 text=`

If I query the user by id _/admin/realms/<REALM>/users/d19a61ad-e485-4415-a925-8a5c0b90d9e6_ the user is only read from LDAP on the first Request and returned from Cache afterwards.

If you give me an entry-point in the code, I would perform some more research.

**Comment by pedroigor** [comment] 2024-12-03 14:17
I think we are on the same page now. Thanks for trying the steps I suggested.

To summarize where we are now, please confirm so that we can move forward:

* Keycloak will query entries from LDAP whenever executing a query via User API
* Keycloak behaves differently when querying users (search) and by ID

The last one is actually a bug, IMO. The behavior you see where attribute values are different when searching and querying by ID is not correct. As you mentioned, this is why we are returning the user from the cache and not really a delegate that will fetch attribute values from LDAP.

The first one we cannot do much now as it will change how the LDAP provider works. For that, I would suggest creating a separate issue because it is the expected behavior. Even though you think is not the best.

If you agree with these thoughts, I'll close this issue and create an RFE to discuss the first point above and an issue to fix the second point.

**Comment by sguilhen** [comment] 2024-12-03 19:58
The LDAP query happens to validate the federated users. So the user is retrieved from the DB, but we query LDAP to see if the user still exists there. Then, if validation fails, we wrap this user so that mappers can read their values from LDAP if the `Always read from LDAP` is on.

When this is false, the wrapped object will always return the value stored in the DB, and updates made directly in LDAP won't be visible until a re-synchronization is performed. So having this flag set to on is a way to catch updates made in LDAP without forcing you to re-sync all users.

If the user cache is completely disabled, this is the behavior you will see: the user models are retrieved from DB, validated against LDAP, and then wrapped so that mappers can still read current values directly from LDAP is that has been configured. With the user cache, you will have potentially user stale data in the cache.

Now, the issue here is that some user queries, like the one performed by the admin console when you hit the Users page, are not cached. So they always go to the DB, validate, wrap, etc, and changes made in LDAP will be visible in the list of returned users. Once you click a particular user, the getById is called, and this call is cached. You will get the cached user that still has potentially outdated information.

This is indeed confusing and we need to find out a way around this - either using cache in a more consistent way across searches or figuring out a way to invalidate the cache of changed users.

**Comment by csbrogi** [comment] 2024-12-04 10:27
Thanks for your answers, I now understand what is happening. From our point, the current implementation is not satisfactorily since our service handles an event that was triggered by a LDAP-import. Then we query the users resulting in more LDAP-requests, even though the data was retrieved just now. 
I understand that it is difficult to handle the problem of users no longer existing in LDAP without a query.
Maybe itcould be helpfull either to  expand the event-data of the LDAP-User-Sync to contain the user-information of affected users or to triggger events for each affected user (USER_ADDED, ....) maybe containg a source=LDAP Attribute.
@pedroigor if you close the bug and create another and a RFE instead, that´s OK for me.

**Comment by pedroigor** [comment] 2024-12-04 19:58
@csbrogi Thanks for the discussion. Created https://github.com/keycloak/keycloak/issues/35637.

**Closed** 2024-12-04 19:58 UTC
Labels: kind/bug, area/admin/api, area/ldap, status/triage, team/core-iam
