### ISSUE TITLE
Cannot search user with space

### ISSUE THREAD

**Issue by quanguyenka** [keycloak/keycloak#21022] opened 2023-06-15 08:34 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

I used API: /admin/realms/safefire/users?search=Quang%20Le (or search=Quang%20Le or use query param q=key:value) to search users by custom attribute but the API response was empty. I surely had set data to user. This situation able happened with first and last name, if their data have space, API not return data. 

### Version

21.1.1

### Expected behavior

Return list user have data match with  value seach

### Actual behavior

Response empty list when value search have space

### How to Reproduce?

Create a user on keycloak, set first name or last name with text containing space. Search that user with API: {host}/admin/realms/safefire/users?q=key:value&search=...

**Comment by quanguyenka** [comment] 2023-06-23 04:47
Thanks for your support

**Comment by sschu** [comment] 2023-06-26 09:07
Closing this as not a bug.

**Closed by sschu** 2023-06-26 09:07 UTC
Labels: kind/bug, area/account/api, status/triage, team/other

**Comment by cuberinooo** [comment] 2024-01-05 10:36
has somebody tried it with json as strings?
like what if we want to query with q=foobar:{"some":"foo bar"}

When Custom-Attribute is saved as foobar -> {"some":"foo bar"}

**Comment by Guite** [comment] 2024-01-05 11:33
@cuberinooo you need to use urlencode(`foobar:"{\"some\":\"foo bar\"}"`)
