### ISSUE TITLE
aws ECS deploy keycloak21.1.1  docker eval "'$JAVA'" -Dkc.config.build-and-exit=true $JAVA_RUN_OPTS  $JAVA is empty

### ISSUE THREAD

**Issue by huangjy6688** [keycloak/keycloak#20418] opened 2023-05-17 13:38 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [x] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

/opt/keycloak/bin/kc.sh: eval: line 125: syntax error: unexpected end of file
/opt/keycloak/bin/kc.sh: eval: line 124: unexpected EOF while looking for matching `''

### Version

21.1.1

### Expected behavior

Normal operation

### Actual behavior

/opt/keycloak/bin/kc.sh: eval: line 125: syntax error: unexpected end of file
/opt/keycloak/bin/kc.sh: eval: line 124: unexpected EOF while looking for matching `''

### How to Reproduce?

![Uploading _20230517213625.png…]()

**Comment by huangjy6688** [comment] 2023-05-18 03:00
if [ "x$JAVA" = "x" ]; then
    if [ "x$JAVA_HOME" != "x" ]; then
        JAVA="$JAVA_HOME/bin/java"
    else
        JAVA="java"
    fi
fi    

eval "'$JAVA'" -Dkc.config.build-and-exit=true $JAVA_RUN_OPTS
    EXIT_CODE=$?

**Comment by huangjy6688** [comment] 2023-05-18 03:02
help help help   thanks

**Comment by sschu** [comment] 2023-05-19 07:52
This could be something specific to your environment. Can you provide steps to reproduce this?

**Comment by huangjy6688** [comment] 2023-05-19 07:59
> This could be something specific to your environment. Can you provide steps to reproduce this?

Yes, docker executes database configuration environment exception

**Comment by sschu** [comment] 2023-05-19 08:27
> > This could be something specific to your environment. Can you provide steps to reproduce this?
> 
> Yes, docker executes database configuration environment exception

This was not an answer to my question. I asked for steps to reproduce this.

**Comment by vmuzikar** [comment] 2023-05-26 11:53
@huangjy6688 Thanks for the report and sorry you are facing issues with starting Keycloak. Since we're unable to reproduce, I'm going to close this. Feel free to reopen whenever you can provide as details steps to reproduce as possible.

**Closed by vmuzikar** 2023-05-26 11:53 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
