### ISSUE TITLE
_b.authenticatorSelection is undefined

### ISSUE THREAD

**Issue by Intron014** [keycloak/keycloak#24882] opened 2023-11-21 13:03 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

When enabling WebAuthn in the flow and trying to add a security key, it works fine until you stumble upon trying it in Bitwarden. I get the error  _b.authenticatorSelection is undefined
![image](https://github.com/keycloak/keycloak/assets/68110374/30f773b7-c331-491a-a351-d367a9a24f6e)

I've tried multiple ways but it just doesn't seem to work.

### Version

22.0.5

### Expected behavior

Keycloak passes the Webauthn request to Bitwarden, which will prompt me to save my passkey somewhere

### Actual behavior

Throws an error:  _b.authenticatorSelection is undefined

### How to Reproduce?

Creating a passkey through keycloak and in combination with Bitwarden

**Comment by jonkoops** [comment] 2023-11-24 14:33
Closing this as a duplicate of #24999 as it has some more details on how to reproduce.

**Comment by jonkoops** [comment] 2023-11-24 14:34
Duplicate of #24999

**Closed by jonkoops** 2023-11-24 14:34 UTC
Labels: kind/bug, status/triage, area/authentication/webauthn, team/core
