### ISSUE TITLE
java.lang.NullPointerException and 500 HTTP code when accessing token endpoint incorrectly

### ISSUE THREAD

**Issue by parrobe** [keycloak/keycloak#14114] opened 2022-08-31 10:15 UTC
### Describe the bug

Keycloak release: 19.0.1
Platform: Windows 64-bit
Server started in development mode with self signed certificate for HTTPS

I am trying out keycloak and i found that i can reliably generate unhandled null pointer exceptions and 500 HTTP codes. It does not damage my keycloak server but isn't very helpful for debugging what i'm doing wrong.

Here's the curl command i run:
```
curl -X POST -k -H "accept: application/json" -H Content-Type: application/x-www-form-urlencoded -d "grant_type=password" -d "redirect_uri=<redirectURI>" -d "username=<user>" -d "password=<password>" https://localhost:8443/realms/<realm>/protocol/openid-connect/token
```
Although i have found you can generate this exception by just POSTing to the token endpoint with no data:
```
curl -X POST -k https://localhost:8443/realms/master/protocol/openid-connect/token
```
and the response
```
curl: (6) Could not resolve host: application
{"error":"unknown_error"}
```
and the null pointer exception that comes out in the logs
```
2022-08-31 11:09:29,711 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-39) Uncaught server error: java.lang.NullPointerException
        at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:53)
        at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
        at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
        at com.sun.proxy.$Proxy45.getDecodedFormParameters(Unknown Source)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:171)
        at jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:871)
```

For my realm setup, i haven't done anything special. I followed the getting started guide to setup a custom realm but this also happens against the default `master` realm

### Version

19.0.1

### Expected behavior

I would not expect an unhandled null pointer exception or a 500 error code. Instead i would expect:

- A 400 HTTP code returned to client
- An error message in the console logs indicating what was missing

### Actual behavior

See above, a unhandled Null Pointer exception is returned in console logs and a HTTP 500 error is returned to curl

### How to Reproduce?

1. Deploy KeyCloak 
2. Start it in development mode `kc.bat start-dev`
3. Try and access the token endpoint with the following (replace localhost:8443 with your own host:port):

```
curl -X POST -k https://localhost:8443/realms/master/protocol/openid-connect/token
```
You will receive a 500 return code and see the null pointer in the console log

### Anything else?

If i add one `--data-urlencode` parameter then i do not see the Null pointer but do see a helpful error message in the console log e.g.
```
curl -X POST -k --data-urlencode "grssssssssant_type=password" https://localhost:8443/realms/master/protocol/openid-connect/token
{"error":"invalid_request","error_description":"Missing form parameter: grant_type"}
```
```
2022-08-31 11:29:39,653 WARN  [org.keycloak.events] (executor-thread-39) type=LOGIN_ERROR, realmId=5d6228a7-39c6-4c8a-9f09-53fbeb2e6271, clientId=null, userId=null, ipAddress=127.0.0.1, error=invalid_client_credentials, grant_type=password
```

**Comment by lexcao** [comment] 2022-09-01 16:41
I think the content type `application/x-www-form-urlencoded` could be missing from your first request, 
causing the status 500 with `unknown_error`.

Duplicated to #14045

**Comment by mposolda** [comment] 2022-12-19 08:34
Duplicate of #14045 .

@lexcao Thanks for finding the duplicate. I am closing this @parrobe Please track the duplicated issue to follow the fix.

**Closed by mposolda** 2022-12-19 08:34 UTC
Labels: area/oidc, kind/bug, status/triage
