### ISSUE TITLE
Keycloak token in  Account Theme

### ISSUE THREAD

**Issue by phenomuser** [keycloak/keycloak#24574] opened 2023-11-06 13:15 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Hi,

We are currently working on customizing the Account theme of Keycloak. As part of our customization, we need to incorporate several API calls to our own APIs during the process of updating basic information. However, we have encountered difficulties in locating the token object within the FTL files. This has impeded our ability to execute API calls upon saving the changes.

We would appreciate any assistance you can provide on this matter.

Sanga

### Version

16

### Expected behavior

we should be able to locate token object

though we are using 16 version we are still with customising ftl files

### Actual behavior

not able to find the token object

### How to Reproduce?

we can run keycloak theme with ftl files for accounts ui

**Comment by sschu** [comment] 2023-11-07 14:06
If you have trouble getting something working, please don't file a bug but open a discussion (https://github.com/keycloak/keycloak/discussions) or ask on the user mailing list. I will close this as it is not a bug as far as I can see.

**Closed by sschu** 2023-11-07 14:06 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
