### ISSUE TITLE
AuthzClient instantiation ignores clientId parameter

### ISSUE THREAD

**Issue by AndriusKarpavicius** [keycloak/keycloak#16175] opened 2022-12-24 22:42 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

Under same realm we have to clients - A and B.

We get an access token from client A (configured as public client, no authorization) and then use it to access API in client B. Client B is configured as confidential with authorization enabled.  

OIDC works fine, as I am able to access API.

As Keycloak no longer does authorization check, we do it ourselves.

```
Configuration configuration = new Configuration("http://localhost:8180/auth", "myrealm", "clientB", "credentials", null);
AuthzClient authzClient = AuthzClient.create(configuration);
List<ResourceRepresentation> resources = authzClient.protection(accessTokenString).resource().findByMatchingUri(url);

```
This used to work in Wildfly v22 with keycloak adapter. But fails to work on Wildlfy v26.1.2 and gives the following error: "Client application clientA is not registered as a resource server."

Problem is that AuthzClient ignores configuration clientId parameter - Access token was obtained from clientA, but in my AuthClient setup I request to use clientB, and that value is ignored, clientID value is taken from an access token.

### Version

20.0.1

### Expected behavior

Use clientID as passed to AuthClient configuration.

### Actual behavior

Uses a clientId value from access token.

### How to Reproduce?

Use a token obtained from one client to access AuthClient of another client.

**Comment by mposolda** [comment] 2023-04-04 09:51
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by pedroigor** [comment] 2024-03-04 19:03
It works like that by design so that you can only invoke the Protection API if the token was issued to the resource server itself (the one protecting its resources). 

FTR:

* https://www.keycloak.org/docs/23.0.7/authorization_services/#_service_protection_api
* https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html

**Closed** 2024-03-04 19:03 UTC
Labels: area/authorization-services, kind/bug, team/core-iam
