### ISSUE TITLE
/admin/realms/{realm}/groups Endpoint is slow

### ISSUE THREAD

**Issue by timo-42** [keycloak/keycloak#25731] opened 2023-12-20 14:17 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

After upgrading from Keycloak 22 to 23, the `/admin/realms/{realm}/groups` takes 40-60s for returning 7.5k groups.
It also seems to create a moderate amount of CPU utilization.

### Version

23.0.3

### Expected behavior

The endpoint returns within < 5s with 7.5k groups as it did with version 22.

### Actual behavior

The endpoint returns within 40-60s with 7.5k groups as it did with version 23.

### How to Reproduce?

I did not try to reproduce it with an empty new Keycloak. But I would guess, to create 7.5K groups and call the endpoint.

### Anything else?

We saw the issue with versions 23.0.0/23.0.1/23.0.2/23.0.3

**Comment by mposolda** [comment] 2023-12-20 14:34
Thanks, just to doublecheck:
- Are all your groups only top-level groups? Or do you also have some "nested" groups?
- Which DB are you using?
- Are you using LDAP with some group mapper? If yes, which LDAP?
- Are you using fine-grained admin permissions configured for some groups?

**Comment by timo-42** [comment] 2023-12-20 14:39
Are all your groups only top-level groups? Or do you also have some "nested" groups?
we only have groups, no "nested" groups.

Which DB are you using? PostgreSQL

Are you using LDAP with some group mapper? If yes, which LDAP? No

Are you using fine-grained admin permissions configured for some groups? No

**Comment by timo-42** [comment] 2023-12-21 21:33
Benchmarks with python and keycloak dev-start:
VERSIONS:
22.0.5
23.0.3
@sha256:30aeeaee2ca2c0e8772f7d989887b69076f4736af4b8665220ba546f15b6a71e


`docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin  quay.io/keycloak/keycloak:${VERSION} start-dev`

y-axis: call to `/admin/realms/{realm}/groups` in s
x-axis: groups

Results:
![keycloak-22 0 5](https://github.com/keycloak/keycloak/assets/10377071/d6351e31-a02b-4bf3-8e04-bc8d5e7fe3a7)
![keycloak-23 0 3](https://github.com/keycloak/keycloak/assets/10377071/9953aa26-4066-45e9-9576-8734e15a7c7f)
![keycloak-nightly-sha256-30aeeaee2ca2c0e](https://github.com/keycloak/keycloak/assets/10377071/bd443082-2da0-4a01-bffe-e80c8f54ae97)

python 3.11 requirements: requests plotille
used python script:
```
import requests
import time
import plotille
import os

USERNAME = "admin"
PASSWORD = "admin"
REALM = "test-realm"
BASE_URL = "http://localhost:8080"
MAX_GROUPS = 2000
PRINT_EVERY_X_GROUPS = 10

BENCHMARK_DATA = []
X = []
Y = []


def fetch_groups(s):
    now = time.time()
    r = s.get(f"{BASE_URL}/admin/realms/{REALM}/groups")
    r.raise_for_status()
    duration = time.time() - now
    print(f"Requests {len(r.json())} Groups in {duration:.2f}s")
    X.append(len(r.json()))
    Y.append(duration)
    return r.json()


def clean_up(s):
    groups = fetch_groups(s)
    for g in groups:
        id = g["id"]
        s.delete(f"{BASE_URL}/admin/realms/{REALM}/groups/{id}")


def auth_session(s):
    r = s.post(
        f"{BASE_URL}/realms/master/protocol/openid-connect/token",
        data={
            "username": USERNAME,
            "password": PASSWORD,
            "grant_type": "password",
            "client_id": "admin-cli",
        },
    )
    r.raise_for_status()
    access_token = r.json()["access_token"]
    s.headers.update({"Authorization": f"Bearer {access_token}"})


with requests.Session() as s:
    auth_session(s)

    r = s.get(f"{BASE_URL}/admin/realms")
    r.raise_for_status()
    if len(r.json()) < 2:
        r = s.post(
            f"{BASE_URL}/admin/realms",
            json={
                "id": REALM,
                "realm": REALM,
            },
            headers={"Content-Type": "application/json"},
        )
        r.raise_for_status()

    clean_up(s)

    print("Start benchmark")
    for i in range(MAX_GROUPS):
        r = s.post(
            f"{BASE_URL}/admin/realms/{REALM}/groups",
            json={"name": f"group-{i}"},
            headers={"Content-Type": "application/json"},
        )
        r.raise_for_status()

        if i % PRINT_EVERY_X_GROUPS == 0:
            # renew auth token
            auth_session(s)
            fetch_groups(s)

print(plotille.plot(
    X,
    Y,
    width=80,
    height=40,
    X_label="Groups",
    Y_label="Fetch in s",
    linesep=os.linesep,
    interp=None,
    x_min=0,
    x_max=MAX_GROUPS,
    y_min=0,
    y_max=None,
    lc=None,
    bg=None,
    color_mode="names",
    origin=True,
    marker=None,
))
```

**Comment by timo-42** [comment] 2023-12-25 10:51
I found the responsible commit: 69497382d8cc6c622e815184d9bc27cb0dc6a400

**Comment by MarinCouderc** [comment] 2024-01-30 15:08
Can confirm same regression on our end after upgrading keycloak from v21.1.2 to v23.0.4. Endpoint was taking ~100ms at most and now takes more than 1s.

**Comment by westphalt** [comment] 2024-01-31 16:31
Same on our side with the following setup with two parallel Keycloak instances between 21.1.1 (integration-stage) to 23.0.4 (development stage): 
We have one Ldap instance syncing against two keycloak instances in user federation. We retrieve groups over admin api in both instances. In development stage this takes repeated around a minute / 60 seconds, while it takes only few milliseconds below 100 in integration stage (this is more than 800 times slower as before!):

development:
![image](https://github.com/keycloak/keycloak/assets/158305749/7050deb7-a284-4dd6-ae84-0cc10c4ded2d)

integration: 
![image](https://github.com/keycloak/keycloak/assets/158305749/c7ebfb4c-b118-45d9-bbba-d8502eb5c3cd)

We have oracle 19 databases for all of the keycloak instances. Keycloak instances running in docker containers in clusters with two instances per stage, nothing special. 

We have even tried with query-param briefDescription=true without any change.

**Comment by michbeck100** [comment] 2024-02-06 10:19
Is there any progress here? I've analysed this problem and when activating the sql logging, you can see N+1 selects for every group, because the first query for all groups only selects the id. I don't know whats the difference to 22.x, because it seems that this behaviour didnb't change in https://github.com/keycloak/keycloak/commit/69497382d8cc6c622e815184d9bc27cb0dc6a400

**Comment by westphalt** [comment] 2024-02-08 07:41
Just to let you now, we have seen that the issue is 21.1.1 as well, but the results are cached in Infinyspan and therefore subsequent reads are much faster then in 23.0.4. Maybe there is something missing / changed in the caches. We will look into this in the next days / week, but have to some production relevant SPI development first.

**Comment by mhajas** [comment] 2024-02-09 15:19
@timo-42 @MarinCouderc @westphalt @michbeck100 Are any of you able to check whether PR #26904 fixes the issues you were seeing?

**Comment by westphalt** [comment] 2024-02-13 17:17
Hi, sorry for the delay, but we have tested today, that it works under PR #26904 nearly as in 21.1.1.: 
![image](https://github.com/keycloak/keycloak/assets/158305749/8d493ad5-a22d-4a94-b222-ecac2616ac74)
And after one initial call its cached again: 
![image](https://github.com/keycloak/keycloak/assets/158305749/45ad17aa-6b57-4efb-ad12-53e26c309abe)
So the bug is fixed in our environment. Nevertheless the performance to retrieve 7.500 groups with nearly one and a half minutes isn't as good as it could be. But this is another topic. We will look into this maybe ourselves later on, when we have a little more time. Thank for fixing the issue.

**Comment by michbeck100** [comment] 2024-02-13 17:29
I think what @westphalt wants to say, is that the initial group fetching takes very long. This was already the case before this issue. the problem is, that the JPA query only fetches the group ids and then fetches every single group by id. Classic N+1 selects. To speed up the initial loading this behavior would have to be changed. And that's the other story.

**Comment by westphalt** [comment] 2024-02-13 17:40
We deploy Keycloak in a medium sized german bank (2.000 employees). We have a bank specific application in place that is used for configuration of access management, where users belong to a hierarchy of departments, groups are assigned to departments and users retrieve this rights over their department memberships. Users sync is done over ldap federation, but there is only a small subset of groups in ldap, so that the groups aren't synced over ldap, but on a daily basis (and additional on demand) over the keycloak APIs to keycloak. A first step is to sync all necessary groups (delete ones from keycloak, that no longer exist in the other system, create new ones that aren't in keycloak already, and so on). Therefore  all groups are read once from keycloak, as the sync is stateless. That's the full story. 

The groups in groups feature makes keycloak maybe a viable replacement for this old application. We will think about this in the future :) One thing that holds us back is German /European regulation in banks esp. for user management and a lot of surrounding reporting, 4 eyes principles for granting rights and a lot of more similar processes.

**Comment by alice-wondered** [comment] 2024-02-13 20:56
> I think what @westphalt wants to say, is that the initial group fetching takes very long. This was already the case before this issue. the problem is, that the JPA query only fetches the group ids and then fetches every single group by id. Classic N+1 selects. To speed up the initial loading this behavior would have to be changed. And that's the other story.

I actually proposed changing this in my initial PR for group scalability. IIRC at the time I was told that the reason it is that way is for the cache to populate correctly. Agreed that it would make sense to try and still update the cache and not fetch all relevant IDs and then fetch the full entity again after that

**Comment by alice-wondered** [comment] 2024-02-13 21:04
I've created a PR keycloak#27010 that moves the group count query into the same transaction as the initial select. That gets the group counts into the cache with the model object as well.

Additionally added an index on the parent_id field to speed up queries there. That secondary index gets used a lot so that seems like an easy decision to me. 

Any additional performance gains would come from what @michbeck100 has mentioned with the double query to the database for loading group entities. AFAIK this would require modifications to the cache to do

**Closed** 2024-02-15 10:46 UTC
Labels: priority/critical, area/admin/api, kind/performance, backport/23.0, team/core-iam
