### ISSUE TITLE
@keycloak@keycloak-admin-client@18.0.2 isn't supported by any available resolver.

### ISSUE THREAD

**Issue by harmoney-franck** [keycloak/keycloak#19627] opened 2023-04-11 01:05 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/node

### Describe the bug

When trying to build my application with `pnpm` in a Docker container, I'm getting the following error for the command `pnpm install --prod`: 

`ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @keycloak@keycloak-admin-client@18.0.2 isn't supported by any available resolver.`

I tried to update to the latest version but it is causing other issues such as the following one with jest: 
```bash
node_modules/.pnpm/@keycloak+keycloak-admin-client@21.0.2/node_modules/@keycloak/keycloak-admin-client/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { RequiredActionAlias } from './defs/requiredActionProviderRepresentation.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

### Version

18.0.2

### Expected behavior

@keycloak@keycloak-admin-client@18.0.2 should be supported by any available resolver.

### Actual behavior

@keycloak@keycloak-admin-client@18.0.2 isn't supported by any available resolver.

### How to Reproduce?

Docker image `node:18-alpine`
`"@keycloak/keycloak-admin-client": "18.0.2"`

run `pnpm install --prod`

**Comment by jonkoops** [comment] 2023-04-11 15:38
Have you verified this is still a problem in the latest version? We do not actively support older versions of this library.

**Comment by harmoney-franck** [comment] 2023-04-11 20:47
> Have you verified this is still a problem in the latest version? We do not actively support older versions of this library.

After upgrading to the latest version (`21.0.2`) and fixing the compilation errors related to `jest`
- Note for anyone who stumbled across the same issue, fixed jest by adding 
  `transformIgnorePatterns: ['/node_modules/.pnpm/(?!@keycloak|url-join|url-template|camelize-ts)'],` to `jest.config.ts`

I can confirm that the issue still exists with the latest: 
` ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @keycloak@keycloak-admin-client@21.0.2 isn't supported by any available resolver.`

**Comment by harmoney-franck** [comment] 2023-04-12 04:07
Is there any chance that you provide a `CJS` build to be able to use the package with `Nestjs`?

**Comment by harmoney-franck** [comment] 2023-04-14 02:28
The node version we use is `18.13.0`
Used latest pnpm `8.2.0`

This was an attempt to switch our packages manager from `npm` to `pnpm` but after over a week of trying to resolve those build issues, we decided it wasn't worth it.  

We also locked our version of `@keycloak/keycloak-admin-client` to `18.0.2` for now following [this Stackoverflow thread](https://stackoverflow.com/questions/73508965/error-adding-keycloak-keycloak-admin-client-package-in-nestjs-application).

Here is a Dockerfile similar to what we have, note this is part of a nx monorepo: 
```
ARG BASE_IMAGE_TAG=latest
ARG DOCKER_REGISTRY_PREFIX=''
FROM ${DOCKER_REGISTRY_PREFIX}...../.....:$BASE_IMAGE_TAG as builder
WORKDIR /code
ENV NODE_ENV production
COPY . .
RUN pnpm build nestjs-app

FROM builder as pruned
RUN pnpm --filter nestjs-app --prod deploy pruned

FROM node:18-alpine as runner
RUN npm install -g pnpm
WORKDIR /app
ENV NODE_ENV production
# COPY --from=builder /code/dist/apps/nestjs-app.
COPY --from=pruned /app/pruned .
ENTRYPOINT ["node", "./main.js"]
```

**Comment by jonkoops** [comment] 2023-04-18 10:39
I wasn't able to get Docker up and running but I am also unable to reproduce this issue on my system using the latest PNPM and the older version of the admin client.

**Comment by ssilvert** [comment] 2023-05-08 21:04
@harmoney-franck Closing this issue because we are unable to reproduce.  We can reopen if you still think there is a problem and you can help us reproduce it on our end.

**Closed by ssilvert** 2023-05-08 21:04 UTC
Labels: kind/bug, status/triage, team/ui, area/admin/client-js
