### ISSUE TITLE
KeyCloak not work in IOS below 15

### ISSUE THREAD

**Issue by Sotatek-HienPham3** [keycloak/keycloak#23823] opened 2023-10-09 04:03 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Throw error: **unexpected identifier 'hasStorageAccess' . Expected ';' is end an if condition**  . Keycloak can't initialize with IOS version 14 because syntax error

### Version

22.0.3

### Expected behavior

NO BUG

### Actual behavior

None

### How to Reproduce?

None

**Comment by jonkoops** [comment] 2023-10-10 15:12
Yeah, this is likely a duplicate of #23743 as this version of Safari doesn't support [top level await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await).

**Comment by jonkoops** [comment] 2023-10-10 15:12
Duplicate of #23743

**Closed by jonkoops** 2023-10-10 15:12 UTC
Labels: kind/bug, area/core, status/triage, team/core
