### ISSUE TITLE
There's a problem in the forgot password flow in keycloak v 22.0.4 and v 23.0.5

### ISSUE THREAD

**Issue by omar-emaratech** [keycloak/keycloak#26593] opened 2024-01-30 11:46 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

I create a realm "MyRealm" and then choose to put the forgot password option in the login page.
I setup the SMTP server and configured it on the realm.
I create a user and assign a password to it.
I proceed to the login page and click on the forgot password link.
The email is received and the link is within it.
When I take the link and open it in the browser, I get the below error

<img width="491" alt="image" src="https://github.com/keycloak/keycloak/assets/158162287/a5db763a-70a9-406d-a2cc-cb65e946eedc">

### Version

23.0.5

### Expected behavior

That the link works correctly and navigates me to the update password page.

### Actual behavior

I get the error message
We are sorry...
An error occurred, please login again through your application.

### How to Reproduce?

Create a realm "MyRealm" and then choose to put the forgot password option in the login page.
Setup the SMTP server and configured it on the realm.
Create a user and assign a password to it.
Proceed to the login page and click on the forgot password link.
The email is received and the link is within it.
Open the link in a browser

**Comment by rmartinc** [comment] 2024-02-05 11:51
@omar-emaratechI cannot reproduce this in main or 23.0.5. Probably the reproducer steps are missing something important. Two questions:

1. Can you please test with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)? (I just want to see if this has been fixed in some recent changes.)
2. The browser you are using to paste the URl from the email? Is it a new one? Are you logged with a previous user in that browser? Is this happening if you use a new incognito window?

**Comment by omar-emaratech** [comment] 2024-02-05 14:02
Hi @rmartinc,
Thank you so much for your response.
I have tried your suggestions:
1. The nightly build gives me the same behavior.
2. I am using Microsoft Edge, no I am not logged in using the same user. And yes it happens when using an incognito window.

**Comment by rmartinc** [comment] 2024-02-06 08:32
:disappointed: I cannot reproduce, what's the error do you see in the logs when you see the error page? (I suppose it's a EXECUTE_ACTION_TOKEN_ERROR.)

**Comment by omar-emaratech** [comment] 2024-02-06 12:37
Yes that's exactly the error I get

2024-01-29 13:47:29,297 TRACE [org.keycloak.events] (executor-thread-105) type=EXECUTE_ACTION_TOKEN_ERROR, realmId=12a51b6a-27da-404c-82c9-786fc5853758, clientId=null, userId=null, ipAddress=0:0:0:0:0:0:0:1, error=invalid_code, reason='Failed to parse JWT',AUTH_SESSION_ID=c5999498-31e5-4133-8813-fcd25fdc48b5], cookies=[, stackTrace=  
 
    org.keycloak.events.log.JBossLoggingEventListenerProvider.logEvent(JBossLoggingEventListenerProvider.java:114)

    org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)

    org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)

	org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)

    org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)

    org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)

    org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:388)

	org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:273)

    org.keycloak.events.EventBuilder.send(EventBuilder.java:246)

    org.keycloak.events.EventBuilder.error(EventBuilder.java:233)

    org.keycloak.services.resources.LoginActionsService.handleActionTokenVerificationException(LoginActionsService.java:710)

	org.keycloak.services.resources.LoginActionsService.handleActionToken(LoginActionsService.java:611)

    org.keycloak.services.resources.LoginActionsService.executeActionToken(LoginActionsService.java:525)

**Comment by rmartinc** [comment] 2024-02-06 13:43
The error is parsing the JWT so the token is not OK. Is it possible to paste the URL in your email (it can be from any test env that fails in the same way)?

**Comment by omar-emaratech** [comment] 2024-02-06 13:57
Please find it below:

http://localhost:8080/realms/MyRealm/login-actions/action-token?key=3DeyJhb=
GciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5MTAyNTc1MS05MWI3LTQwMmItODE1=
Mi03ZTBkZjlkNWE5ZDAifQ.eyJleHAiOjE3MDcyMjgxNDIsImlhdCI6MTcwNzIyNzg0MiwianRp=
IjoiNmEwZjIwM2QtNzMwZC00MjQ0LWI5NTItM2Y4N2FlODY2ODBkIiwiaXNzIjoiaHR0cDovL2x=
vY2FsaG9zdDo4MDgwL3JlYWxtcy9NeVJlYWxtIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MD=
gwL3JlYWxtcy9NeVJlYWxtIiwic3ViIjoiYzFkOGJkMWYtZGUyYS00MjY2LTk1MDUtNjcyMzE1M=
jZjMjA0IiwidHlwIjoicmVzZXQtY3JlZGVudGlhbHMiLCJhenAiOiJhY2NvdW50LWNvbnNvbGUi=
LCJub25jZSI6IjZhMGYyMDNkLTczMGQtNDI0NC1iOTUyLTNmODdhZTg2NjgwZCIsImVtbCI6Im9=
tYXJhbWVyMTk5MUBnbWFpbC5jb20iLCJhc2lkIjoiODg1YzBlNWEtNGE4OS00Mjg1LWI0Y2QtOW=
IzNTQxY2JhNWUzLlBDVnN1UUNYREk0LjU5NGEwNmExLTc2ZWUtNGVhZC05NzRjLTVjMzYyODhjM=
zliYSIsImFzaWQiOiI4ODVjMGU1YS00YTg5LTQyODUtYjRjZC05YjM1NDFjYmE1ZTMuUENWc3VR=
Q1hESTQuNTk0YTA2YTEtNzZlZS00ZWFkLTk3NGMtNWMzNjI4OGMzOWJhIn0.IPouWoch4mGwRsS=
wLDwraF8ND1rNX9JYfl6c_h5KAaM&execution=3D00ad12ba-603d-4466-9e57-cb8392d6ea=
dc&client_id=3Daccount-console&tab_id=3DPCVsuQCXDI4

**Comment by rmartinc** [comment] 2024-02-06 14:25
That link is in mime format or quoted-printable without any interpretation of the email application. As you see the `=`  chars are at the end of the line, and `=3D` is used to escape real equals in the email. So that URL is (after parsing):

`http://localhost:8080/realms/MyRealm/login-actions/action-token?key=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5MTAyNTc1MS05MWI3LTQwMmItODE1Mi03ZTBkZjlkNWE5ZDAifQ.eyJleHAiOjE3MDcyMjgxNDIsImlhdCI6MTcwNzIyNzg0MiwianRpIjoiNmEwZjIwM2QtNzMwZC00MjQ0LWI5NTItM2Y4N2FlODY2ODBkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9NeVJlYWxtIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9NeVJlYWxtIiwic3ViIjoiYzFkOGJkMWYtZGUyYS00MjY2LTk1MDUtNjcyMzE1MjZjMjA0IiwidHlwIjoicmVzZXQtY3JlZGVudGlhbHMiLCJhenAiOiJhY2NvdW50LWNvbnNvbGUiLCJub25jZSI6IjZhMGYyMDNkLTczMGQtNDI0NC1iOTUyLTNmODdhZTg2NjgwZCIsImVtbCI6Im9tYXJhbWVyMTk5MUBnbWFpbC5jb20iLCJhc2lkIjoiODg1YzBlNWEtNGE4OS00Mjg1LWI0Y2QtOWIzNTQxY2JhNWUzLlBDVnN1UUNYREk0LjU5NGEwNmExLTc2ZWUtNGVhZC05NzRjLTVjMzYyODhjMzliYSIsImFzaWQiOiI4ODVjMGU1YS00YTg5LTQyODUtYjRjZC05YjM1NDFjYmE1ZTMuUENWc3VRQ1hESTQuNTk0YTA2YTEtNzZlZS00ZWFkLTk3NGMtNWMzNjI4OGMzOWJhIn0.IPouWoch4mGwRsSwLDwraF8ND1rNX9JYfl6c_h5KAaM&execution=00ad12ba-603d-4466-9e57-cb8392d6eadc&client_id=account-console&tab_id=PCVsuQCXDI4`

If you don't want to do it manually you can use an online service (https://products.aspose.app/email/parser for example) to obtain the correct html.

How are you getting the email? Directly connecting to the pop server via telnet or something?
Have you tested with the previous link after parsing?

Note that the email app will do the parsing and the link should be interpreted to the correct form.

**Comment by omar-emaratech** [comment] 2024-02-07 07:03
I have done what you have advised and it works now.
I am using fakeSMTP.jar as a local smtp server, apparently it has not parsed the email correctly.
I'm not sure if I will encounter that problem if I use a different SMTP server. but for now I think that will suffice.

Thank you so much for your time and effort, immensely appreciated :)

**Closed** 2024-02-07 07:24 UTC
Labels: kind/bug, status/triage, area/login/ui, team/core-clients

**Comment by omar-emaratech** [comment] 2024-02-07 08:34
Ticket closed and the suggestion provided worked excellently.
