### ISSUE TITLE
"Uncaught server error" with JsonMappingException and "At least one condition should be provided to OR query" with LDAP Group Mapper

### ISSUE THREAD

**Issue by lathspell** [keycloak/keycloak#19242] opened 2023-03-22 12:49 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

I get reproducibly the following exception when trying to list the users of a Group in Keycloak 20.0.5
The users as well as their groups are fetched from an OpenLDAP service. The groups are then mapped to equally named Keycloak groups where the roles are configured.

Other realms with (seemingly) same setup work fine. This one used to work as well weeks ago. Unknown if it relates to a recent Keycloak 18 -> 20 upgrade or is a problem in the LDAP data.

Even if the latter would be the case, I would argue that Keycloak gives me way to few information on what exactly is wrong.

(It's not an error in the LDAP user or group filter, I tried both with "ldapsearch" on the command line and they have no syntax error)

```
{
  "timestamp": "2023-03-22T12:27:20.198Z",
  "sequence": 49211,
  "loggerClassName": "org.jboss.logging.Logger",
  "loggerName": "org.keycloak.services.error.KeycloakErrorHandler",
  "level": "ERROR",
  "message": "Uncaught server error",
  "threadName": "executor-thread-867",
  "threadId": 16759,
  "mdc": {},
  "ndc": "",
  "hostName": "keycloak-keycloakx-0",
  "processName": "QuarkusEntryPoint",
  "processId": 1,
  "exception": {
    "refId": 1,
    "exceptionType": "com.fasterxml.jackson.databind.JsonMappingException",
    "message": "At least one condition should be provided to OR query",
    "frames": [
      {
        "class": "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
        "method": "_wrapAsIOE",
        "line": 509
      },
      {
        "class": "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
        "method": "_serialize",
        "line": 482
      },
      {
        "class": "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
        "method": "serializeValue",
        "line": 400
      },
      {
        "class": "com.fasterxml.jackson.databind.ObjectWriter$Prefetch",
        "method": "serialize",
        "line": 1514
      },
      {
        "class": "com.fasterxml.jackson.databind.ObjectWriter",
        "method": "writeValue",
        "line": 1007
      },
      {
        "class": "org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider",
        "method": "writeTo",
        "line": 345
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
        "method": "lambda$writeTo$1",
        "line": 79
      },
      {
        "class": "io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext",
        "method": "executeBlockingIo",
        "line": 251
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
        "method": "writeTo",
        "line": 79
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
        "method": "syncProceed",
        "line": 245
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
        "method": "proceed",
        "line": 224
      },
      {
        "class": "org.keycloak.quarkus.runtime.integration.jaxrs.TransactionalResponseInterceptor",
        "method": "aroundWriteTo",
        "line": 41
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
        "method": "syncProceed",
        "line": 254
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
        "method": "getStarted",
        "line": 170
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
        "method": "lambda$getStarted$0",
        "line": 73
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
        "method": "aroundWriteTo",
        "line": 93
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
        "method": "getStarted",
        "line": 73
      },
      {
        "class": "org.jboss.resteasy.core.ServerResponseWriter",
        "method": "lambda$writeNomapResponse$3",
        "line": 163
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl",
        "method": "filter",
        "line": 410
      },
      {
        "class": "org.jboss.resteasy.core.ServerResponseWriter",
        "method": "executeFilters",
        "line": 252
      },
      {
        "class": "org.jboss.resteasy.core.ServerResponseWriter",
        "method": "writeNomapResponse",
        "line": 101
      },
      {
        "class": "org.jboss.resteasy.core.ServerResponseWriter",
        "method": "writeNomapResponse",
        "line": 74
      },
      {
        "class": "org.jboss.resteasy.core.SynchronousDispatcher",
        "method": "writeResponse",
        "line": 594
      },
      {
        "class": "org.jboss.resteasy.core.SynchronousDispatcher",
        "method": "invoke",
        "line": 524
      },
      {
        "class": "org.jboss.resteasy.core.SynchronousDispatcher",
        "method": "lambda$invoke$4",
        "line": 261
      },
      {
        "class": "org.jboss.resteasy.core.SynchronousDispatcher",
        "method": "lambda$preprocess$0",
        "line": 161
      },
      {
        "class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
        "method": "filter",
        "line": 364
      },
      {
        "class": "org.jboss.resteasy.core.SynchronousDispatcher",
        "method": "preprocess",
        "line": 164
      },
      {
        "class": "org.jboss.resteasy.core.SynchronousDispatcher",
        "method": "invoke",
        "line": 247
      },
      {
        "class": "io.quarkus.resteasy.runtime.standalone.RequestDispatcher",
        "method": "service",
        "line": 73
      },
      {
        "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
        "method": "dispatch",
        "line": 151
      },
      {
        "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
        "method": "handle",
        "line": 82
      },
      {
        "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
        "method": "handle",
        "line": 42
      },
      {
        "class": "io.vertx.ext.web.impl.RouteState",
        "method": "handleContext",
        "line": 1284
      },
      {
        "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
        "method": "iterateNext",
        "line": 173
      },
      {
        "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
        "method": "next",
        "line": 200
      },
      {
        "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
        "method": "handle",
        "line": 84
      },
      {
        "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
        "method": "handle",
        "line": 71
      },
      {
        "class": "io.vertx.ext.web.impl.RouteState",
        "method": "handleContext",
        "line": 1284
      },
      {
        "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
        "method": "iterateNext",
        "line": 173
      },
      {
        "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
        "method": "next",
        "line": 200
      },
      {
        "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$6",
        "method": "handle",
        "line": 430
      },
      {
        "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$6",
        "method": "handle",
        "line": 408
      },
      {
        "class": "io.vertx.ext.web.impl.RouteState",
        "method": "handleContext",
        "line": 1284
      },
      {
        "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
        "method": "iterateNext",
        "line": 173
      },
      {
        "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
        "method": "next",
        "line": 200
      },
      {
        "class": "org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter",
        "method": "lambda$createBlockingHandler$0",
        "line": 82
      },
      {
        "class": "io.quarkus.vertx.core.runtime.VertxCoreRecorder$14",
        "method": "runWith",
        "line": 576
      },
      {
        "class": "org.jboss.threads.EnhancedQueueExecutor$Task",
        "method": "run",
        "line": 2449
      },
      {
        "class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
        "method": "run",
        "line": 1478
      },
      {
        "class": "org.jboss.threads.DelegatingRunnable",
        "method": "run",
        "line": 29
      },
      {
        "class": "org.jboss.threads.ThreadLocalResettingRunnable",
        "method": "run",
        "line": 29
      },
      {
        "class": "io.netty.util.concurrent.FastThreadLocalRunnable",
        "method": "run",
        "line": 30
      },
      {
        "class": "java.lang.Thread",
        "method": "run",
        "line": 829
      }
    ],
    "causedBy": {
      "exception": {
        "refId": 2,
        "exceptionType": "org.keycloak.models.ModelException",
        "message": "At least one condition should be provided to OR query",
        "frames": [
          {
            "class": "org.keycloak.storage.ldap.idm.query.internal.LDAPQueryConditionsBuilder",
            "method": "orCondition",
            "line": 62
          },
          {
            "class": "org.keycloak.storage.ldap.mappers.membership.MembershipType$1",
            "method": "getGroupMembers",
            "line": 114
          },
          {
            "class": "org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper",
            "method": "getGroupMembers",
            "line": 576
          },
          {
            "class": "org.keycloak.storage.ldap.LDAPStorageProvider",
            "method": "lambda$getGroupMembersStream$5",
            "line": 403
          },
          {
            "class": "java.util.stream.ReferencePipeline$3$1",
            "method": "accept",
            "line": 195
          },
          {
            "class": "java.util.stream.SortedOps$SizedRefSortingSink",
            "method": "end",
            "line": 361
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "copyIntoWithCancel",
            "line": 503
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "copyInto",
            "line": 488
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "wrapAndCopyInto",
            "line": 474
          },
          {
            "class": "java.util.stream.FindOps$FindOp",
            "method": "evaluateSequential",
            "line": 150
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "evaluate",
            "line": 234
          },
          {
            "class": "java.util.stream.ReferencePipeline",
            "method": "findFirst",
            "line": 543
          },
          {
            "class": "org.keycloak.storage.ldap.LDAPStorageProvider",
            "method": "getGroupMembersStream",
            "line": 406
          },
          {
            "class": "org.keycloak.storage.UserStorageManager",
            "method": "lambda$getGroupMembersStream$19",
            "line": 359
          },
          {
            "class": "org.keycloak.storage.UserStorageManager",
            "method": "lambda$query$10",
            "line": 254
          },
          {
            "class": "java.util.stream.ReferencePipeline$7$1",
            "method": "accept",
            "line": 271
          },
          {
            "class": "java.util.stream.ReferencePipeline$2$1",
            "method": "accept",
            "line": 177
          },
          {
            "class": "java.util.stream.ReferencePipeline$2$1",
            "method": "accept",
            "line": 177
          },
          {
            "class": "java.util.stream.ReferencePipeline$3$1",
            "method": "accept",
            "line": 195
          },
          {
            "class": "java.util.ArrayList",
            "method": "forEach",
            "line": 1541
          },
          {
            "class": "java.util.stream.SortedOps$RefSortingSink",
            "method": "end",
            "line": 395
          },
          {
            "class": "java.util.stream.Sink$ChainedReference",
            "method": "end",
            "line": 258
          },
          {
            "class": "java.util.stream.Sink$ChainedReference",
            "method": "end",
            "line": 258
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "copyInto",
            "line": 485
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "wrapAndCopyInto",
            "line": 474
          },
          {
            "class": "java.util.stream.StreamSpliterators$WrappingSpliterator",
            "method": "forEachRemaining",
            "line": 312
          },
          {
            "class": "java.util.stream.Streams$ConcatSpliterator",
            "method": "forEachRemaining",
            "line": 735
          },
          {
            "class": "java.util.stream.Streams$ConcatSpliterator",
            "method": "forEachRemaining",
            "line": 734
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "copyInto",
            "line": 484
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "wrapAndCopyInto",
            "line": 474
          },
          {
            "class": "java.util.stream.ForEachOps$ForEachOp",
            "method": "evaluateSequential",
            "line": 150
          },
          {
            "class": "java.util.stream.ForEachOps$ForEachOp$OfRef",
            "method": "evaluateSequential",
            "line": 173
          },
          {
            "class": "java.util.stream.AbstractPipeline",
            "method": "evaluate",
            "line": 234
          },
          {
            "class": "java.util.stream.ReferencePipeline",
            "method": "forEachOrdered",
            "line": 502
          },
          {
            "class": "com.fasterxml.jackson.datatype.jdk8.StreamSerializer",
            "method": "serialize",
            "line": 71
          },
          {
            "class": "com.fasterxml.jackson.datatype.jdk8.StreamSerializer",
            "method": "serialize",
            "line": 15
          },
          {
            "class": "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
            "method": "_serialize",
            "line": 480
          },
          {
            "class": "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
            "method": "serializeValue",
            "line": 400
          },
          {
            "class": "com.fasterxml.jackson.databind.ObjectWriter$Prefetch",
            "method": "serialize",
            "line": 1514
          },
          {
            "class": "com.fasterxml.jackson.databind.ObjectWriter",
            "method": "writeValue",
            "line": 1007
          },
          {
            "class": "org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider",
            "method": "writeTo",
            "line": 345
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
            "method": "lambda$writeTo$1",
            "line": 79
          },
          {
            "class": "io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext",
            "method": "executeBlockingIo",
            "line": 251
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
            "method": "writeTo",
            "line": 79
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
            "method": "syncProceed",
            "line": 245
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
            "method": "proceed",
            "line": 224
          },
          {
            "class": "org.keycloak.quarkus.runtime.integration.jaxrs.TransactionalResponseInterceptor",
            "method": "aroundWriteTo",
            "line": 41
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
            "method": "syncProceed",
            "line": 254
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext",
            "method": "getStarted",
            "line": 170
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
            "method": "lambda$getStarted$0",
            "line": 73
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
            "method": "aroundWriteTo",
            "line": 93
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext",
            "method": "getStarted",
            "line": 73
          },
          {
            "class": "org.jboss.resteasy.core.ServerResponseWriter",
            "method": "lambda$writeNomapResponse$3",
            "line": 163
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl",
            "method": "filter",
            "line": 410
          },
          {
            "class": "org.jboss.resteasy.core.ServerResponseWriter",
            "method": "executeFilters",
            "line": 252
          },
          {
            "class": "org.jboss.resteasy.core.ServerResponseWriter",
            "method": "writeNomapResponse",
            "line": 101
          },
          {
            "class": "org.jboss.resteasy.core.ServerResponseWriter",
            "method": "writeNomapResponse",
            "line": 74
          },
          {
            "class": "org.jboss.resteasy.core.SynchronousDispatcher",
            "method": "writeResponse",
            "line": 594
          },
          {
            "class": "org.jboss.resteasy.core.SynchronousDispatcher",
            "method": "invoke",
            "line": 524
          },
          {
            "class": "org.jboss.resteasy.core.SynchronousDispatcher",
            "method": "lambda$invoke$4",
            "line": 261
          },
          {
            "class": "org.jboss.resteasy.core.SynchronousDispatcher",
            "method": "lambda$preprocess$0",
            "line": 161
          },
          {
            "class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
            "method": "filter",
            "line": 364
          },
          {
            "class": "org.jboss.resteasy.core.SynchronousDispatcher",
            "method": "preprocess",
            "line": 164
          },
          {
            "class": "org.jboss.resteasy.core.SynchronousDispatcher",
            "method": "invoke",
            "line": 247
          },
          {
            "class": "io.quarkus.resteasy.runtime.standalone.RequestDispatcher",
            "method": "service",
            "line": 73
          },
          {
            "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
            "method": "dispatch",
            "line": 151
          },
          {
            "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
            "method": "handle",
            "line": 82
          },
          {
            "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
            "method": "handle",
            "line": 42
          },
          {
            "class": "io.vertx.ext.web.impl.RouteState",
            "method": "handleContext",
            "line": 1284
          },
          {
            "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
            "method": "iterateNext",
            "line": 173
          },
          {
            "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
            "method": "next",
            "line": 200
          },
          {
            "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
            "method": "handle",
            "line": 84
          },
          {
            "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
            "method": "handle",
            "line": 71
          },
          {
            "class": "io.vertx.ext.web.impl.RouteState",
            "method": "handleContext",
            "line": 1284
          },
          {
            "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
            "method": "iterateNext",
            "line": 173
          },
          {
            "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
            "method": "next",
            "line": 200
          },
          {
            "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$6",
            "method": "handle",
            "line": 430
          },
          {
            "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$6",
            "method": "handle",
            "line": 408
          },
          {
            "class": "io.vertx.ext.web.impl.RouteState",
            "method": "handleContext",
            "line": 1284
          },
          {
            "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
            "method": "iterateNext",
            "line": 173
          },
          {
            "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
            "method": "next",
            "line": 200
          },
          {
            "class": "org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter",
            "method": "lambda$createBlockingHandler$0",
            "line": 82
          },
          {
            "class": "io.quarkus.vertx.core.runtime.VertxCoreRecorder$14",
            "method": "runWith",
            "line": 576
          },
          {
            "class": "org.jboss.threads.EnhancedQueueExecutor$Task",
            "method": "run",
            "line": 2449
          },
          {
            "class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
            "method": "run",
            "line": 1478
          },
          {
            "class": "org.jboss.threads.DelegatingRunnable",
            "method": "run",
            "line": 29
          },
          {
            "class": "org.jboss.threads.ThreadLocalResettingRunnable",
            "method": "run",
            "line": 29
          },
          {
            "class": "io.netty.util.concurrent.FastThreadLocalRunnable",
            "method": "run",
            "line": 30
          },
          {
            "class": "java.lang.Thread",
            "method": "run",
            "line": 829
          }
        ]
      }
    }
  },
  "classtype": "application"
}

```

### Version

20.0.5

### Expected behavior

works

### Actual behavior

Exception

### How to Reproduce?

Attached is the UserStorageProvider part of a realm export. I replaced all sensitive data with "x".

```
{
    "org.keycloak.storage.UserStorageProvider": [
      {
        "id": "efb571f7-6eea-46ce-9580-5a71cfc27ea9",
        "name": "ldap",
        "providerId": "ldap",
        "subComponents": {
          "org.keycloak.storage.ldap.mappers.LDAPStorageMapper": [
            {
              "id": "ca568466-fa69-4967-8811-d46d152da8fa",
              "name": "first name",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "cn"
                ],
                "is.mandatory.in.ldap": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "true"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "firstName"
                ]
              }
            },
            {
              "id": "23a4f511-8554-47b6-851a-506ff53adf84",
              "name": "email",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "mail"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "email"
                ]
              }
            },
            {
              "id": "0a4f26ab-5f7b-498a-8f2a-172506aed992",
              "name": "username",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "mail"
                ],
                "is.mandatory.in.ldap": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "user.model.attribute": [
                  "username"
                ]
              }
            },
            {
              "id": "feba7e12-e2f1-43cf-a914-9fafbeea811f",
              "name": "modify date",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "modifyTimestamp"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "true"
                ],
                "user.model.attribute": [
                  "modifyTimestamp"
                ]
              }
            },
            {
              "id": "33afd987-0d2f-4a9b-97cd-57cd6e232346",
              "name": "creation date",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "createTimestamp"
                ],
                "is.mandatory.in.ldap": [
                  "false"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "true"
                ],
                "user.model.attribute": [
                  "createTimestamp"
                ]
              }
            },
            {
              "id": "28284c4d-c2da-4cb2-b246-c88cf97c5c3b",
              "name": "group mapper",
              "providerId": "group-ldap-mapper",
              "subComponents": {},
              "config": {
                "membership.attribute.type": [
                  "DN"
                ],
                "group.name.ldap.attribute": [
                  "cn"
                ],
                "preserve.group.inheritance": [
                  "true"
                ],
                "membership.user.ldap.attribute": [
                  "cn"
                ],
                "groups.dn": [
                  "o=root"
                ],
                "mapped.group.attributes": [
                  "dn, description, cn, uuid, uid"
                ],
                "mode": [
                  "READ_ONLY"
                ],
                "user.roles.retrieve.strategy": [
                  "LOAD_GROUPS_BY_MEMBER_ATTRIBUTE"
                ],
                "groups.ldap.filter": [
                  "(|(cn=xxxxxxxxxxxxxxxxxrnet*) (cn=xxxxxxxxxxxBS*)(cn=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxM)(cn=xxxxxO)(cn=xxxxxxxxxxxxxi*))"
                ],
                "membership.ldap.attribute": [
                  "member"
                ],
                "ignore.missing.groups": [
                  "true"
                ],
                "memberof.ldap.attribute": [
                  "memberOf"
                ],
                "group.object.classes": [
                  "groupOfNames"
                ],
                "groups.path": [
                  "/"
                ],
                "drop.non.existing.groups.during.sync": [
                  "true"
                ]
              }
            },
            {
              "id": "7e03dbf8-4a6f-48dc-9c1a-9d3f4447f149",
              "name": "last name",
              "providerId": "user-attribute-ldap-mapper",
              "subComponents": {},
              "config": {
                "ldap.attribute": [
                  "sn"
                ],
                "is.mandatory.in.ldap": [
                  "true"
                ],
                "read.only": [
                  "true"
                ],
                "always.read.value.from.ldap": [
                  "true"
                ],
                "user.model.attribute": [
                  "lastName"
                ]
              }
            }
          ]
        },
        "config": {
          "fullSyncPeriod": [
            "36000"
          ],
          "pagination": [
            "true"
          ],
          "usersDn": [
            "o=root"
          ],
          "connectionPooling": [
            "true"
          ],
          "cachePolicy": [
            "NO_CACHE"
          ],
          "useKerberosForPasswordAuthentication": [
            "false"
          ],
          "importEnabled": [
            "false"
          ],
          "enabled": [
            "true"
          ],
          "usernameLDAPAttribute": [
            "mail"
          ],
          "bindDn": [
            "uid=Keycloakxxxxxxxxxxxxxxxxxxxxxxxx,o=root"
          ],
          "changedSyncPeriod": [
            "-1"
          ],
          "bindCredential": [
            "xxxxxxxxxx"
          ],
          "lastSync": [
            "1603982268"
          ],
          "vendor": [
            "other"
          ],
          "uuidLDAPAttribute": [
            "entryUUID"
          ],
          "allowKerberosAuthentication": [
            "false"
          ],
          "connectionUrl": [
            "ldapxxxxxxxxxxxxxxxx"
          ],
          "syncRegistrations": [
            "false"
          ],
          "authType": [
            "simple"
          ],
          "customUserSearchFilter": [
            "(&(objectClass=person)(status=aktiv*))"
          ],
          "debug": [
            "false"
          ],
          "searchScope": [
            "2"
          ],
          "useTruststoreSpi": [
            "ldapsOnly"
          ],
          "priority": [
            "0"
          ],
          "trustEmail": [
            "false"
          ],
          "userObjectClasses": [
            "person"
          ],
          "rdnLDAPAttribute": [
            "mail"
          ],
          "editMode": [
            "READ_ONLY"
          ],
          "validatePasswordPolicy": [
            "false"
          ],
          "batchSizeForSync": [
            "1000"
          ]
        }
      }
    ]
}

```

### Anything else?

-

**Comment by lathspell** [comment] 2023-03-22 14:31
I changed “Username LDAP attribute” from "uid" to "mail" so that it matches “RDN LDAP attribute” (after reading MembershipType.java #94) and now there is a different error message. More verbose but still not helpful. The LDAP entries look good to me.

```
"User returned from LDAP has null username! Check configuration of your LDAP mappings. Mapped username LDAP attribute: mail, user DN: cn=xxxxx,o=xxx,c=xx,o=root, attributes from LDAP: [cn]",
```

**Comment by lathspell** [comment] 2023-05-05 13:28
Hello Vlasta, did you already look into this issue?

**Comment by vramik** [comment] 2023-05-05 15:34
Hey @lathspell, thsnks for the report! 

Looking at the stacktrace you provided, and browsing through the code: https://github.com/keycloak/keycloak/blob/27060d63ca637e912e33c6660b89bc701522158d/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#LL114C76-L114C76 it seems that `orSubconditions` there are empty. 

So either `dns` here is empty: https://github.com/keycloak/keycloak/blob/27060d63ca637e912e33c6660b89bc701522158d/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#LL107C39-L107C39

or 

for all `dns` the `firstRdnAttrValue` here: https://github.com/keycloak/keycloak/blob/release/20.0/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#LL109C28-L109C28

I'd like to know to what is causing the issue. Could you provide some steps how to reproduce it? So far I was not successful.

**Comment by vramik** [comment] 2023-05-06 06:58
I've found https://github.com/keycloak/keycloak/issues/10294 and it seems this one might be duplicate of it ... it has even https://github.com/keycloak/keycloak/pull/15987 sent, still in draft stage.

Could you please check whether at least one queried user has right firstRdnAttrValue?

**Comment by vramik** [comment] 2023-05-18 07:42
Thanks @lathspell for the details. I'd like to ask you to continue the discussion within https://github.com/keycloak/keycloak/issues/10294. Thanks

I'm closing this one as duplicate of https://github.com/keycloak/keycloak/issues/10294.

**Closed by vramik** 2023-05-18 07:42 UTC
Labels: kind/bug, area/ldap, team/store, status/triage
