### ISSUE TITLE
Keycloak Get Users returns 403 forbidden

### ISSUE THREAD

**Issue by zoroglu** [keycloak/keycloak#25843] opened 2024-01-02 07:27 UTC
### Description

I get a 403 error when I query the user for the client I created.
**Keycloak version: 23.0.3**

`http://{keycloak_url}/admin/realms/{realm}/users?{username=username}
`
**403 Forbidden**
```
{
    "error": "unknown_error"
}
```

![image](https://github.com/keycloak/keycloak/assets/32324184/8e9a4ab4-ae8b-4cd0-9847-9cc73cc4b2a6)
![image](https://github.com/keycloak/keycloak/assets/32324184/cc95ca13-fc15-429e-9390-aaccda3462e1)
![image](https://github.com/keycloak/keycloak/assets/32324184/b258444b-4517-461e-81b6-4aac10f3be39)

**Comment by sschu** [comment] 2024-01-02 13:05
This is most likely not a bug in Keycloak since this is what the admin console is doing when you list users. I assume your request is malformed somehow (e.g. you miss an access token, your request parameters are not correct). You can see in the browser network tab how this request looks like. I am going to close this since this is not a bug.

**Closed by sschu** 2024-01-02 13:05 UTC
Labels: kind/feature, status/triage

**Comment by LollyBomb-hub** [comment] 2024-03-27 13:22
Add resource scope. See code [lines](https://github.com/keycloak/keycloak/blob/22.0.9/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L98-L106)  
Here is check if admin-cli client or security-admin-console or other
Your case as i understood is other, so keycloak requires JWT token to contain resource_access [info](https://auth.docs.cern.ch/user-documentation/oidc/config/#configuration-checklist) or your jwt token is meant to be authorized to NO admin actions
![image](https://github.com/keycloak/keycloak/assets/34553831/dae73f26-6f83-4142-bec2-a6ef6a2979e2)
