### ISSUE TITLE
Calling DELETE /realms/<realm>/account/sessions does not work

### ISSUE THREAD

**Issue by william-will-angi** [keycloak/keycloak#32500] opened 2024-08-29 23:40 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

When fetching a DELETE on the `/realms/<realm_name>/account/sessions` with a valid access token, I receive a 204 response, however my current session is not deleted. I also do not see any cookies being cleared, so my `login-status-iframe.html` thinks that I am still logged in.

### Version

v25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

When fetching a DELETE on the `/realms/<realm_name>/account/sessions` endpoint with a valid access token, the session should be deleted and relevant cookies should be reset.

### Actual behavior

A 204 is returned, but the current session is not deleted and no cookies are reset on the response headers.

### How to Reproduce?

Using a valid access token, you can run something like this from the browser:
```js
const res = await fetch(`http://localhost:8080/realms/test/account/sessions`, {
  method: 'DELETE',
  headers: {
    Authorization: `Bearer ${accessToken}`,
    'content-type': 'application/json',
  },
});

You should see that the response is a 204, but your session is not deleted within the keycloak admin ui.

```

### Anything else?

As a partial workaround, I can fetch the full session of sessions, find the one that has `"current": true` and use the `/realms/<realm_name>/account/sessions/{id}` to delete the session by id. This _does_ delete the session within keycloak, however, it doesn't reset any cookies on the response headers, so my `login-status-iframe.html` thinks that I am still logged in. I'm also not sure I would expect this particular endpoint to reset cookies since you may not be deleting the `current` session

**Comment by codespearhead** [comment] 2024-09-02 17:41
Please confirm whether this is not a duplicate of https://github.com/keycloak/keycloak/issues/15502 .

If it is, I suggest reporting your findings in there and closing this issue.

**Comment by william-will-angi** [comment] 2024-09-02 18:17
@codespearhead it seems like that issue only refers to offline sessions, so I believe it is unrelated.

**Comment by sguilhen** [comment] 2024-09-17 12:35
What happens if you send the same request but use the `current` param set to `true` - i.e. DELETE to `realms/test/account/sessions?current=true`?

I see the endpoint is currently filtering out any sessions if that param isn't set.

**Comment by sguilhen** [comment] 2024-09-17 12:39
The order in which the endpoint is evaluating the param is actually making it not remove any sessions if it is not set, which I think is wrong.

**Comment by sguilhen** [comment] 2024-09-17 12:54
The endpoint is behaving as expected - if the current session is also to be removed, the query param `current=param` has to be sent in the DELETE request.

**Closed by sguilhen** 2024-09-17 12:54 UTC
Labels: kind/bug, area/account/api, status/triage, team/core-iam, team/core-shared
