### ISSUE TITLE
Users imported from LDAP are not displayed in the Users screen (only appears when performing a search)

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#25005] opened 2023-11-24 12:01 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When users are imported from LDAP they are not displayed in the Users screen : 

![image](https://github.com/keycloak/keycloak/assets/11772429/40d701df-06d6-4f12-9324-1cb929b2102d)

To make them appear it is mandatory to perform a search : 
![image](https://github.com/keycloak/keycloak/assets/11772429/5e817fde-bcec-44ba-b73b-428f4adb9c73)

I don't know if it should work this way but in the previous Keycloak version I've used (Keycloak 15) it was not mandatory to do a search to see the users.

### Version

22.0.5

### Expected behavior

All users should be displayed when entering the Users screen.

### Actual behavior

The only way to display all users is to manually search each time with the '*' expression.
This is not a great UX.

### How to Reproduce?

Import users from LDAP.
Go the Users screen
Stare at the empty screen.

**Comment by jonkoops** [comment] 2023-11-24 12:24
This seems like an API issue to me, the Admin Console requests the users from the REST API, but they are simply not returned.

**Comment by omasseau** [comment] 2023-11-24 13:52
I have also the problems with the 'Realms roles' screen.
Here you can see that I have at least one user having the role 'AOF' : 
![image](https://github.com/keycloak/keycloak/assets/11772429/29ba6642-ff70-4d03-8a14-f55cb4caca03)

When I go in the 'Realms roles' screen, in the 'Users' tab it says that no users are mapped to the role... : 
![image](https://github.com/keycloak/keycloak/assets/11772429/dab3485c-6b7e-4ed7-8d78-0d1aeea6bb18)

**Comment by omasseau** [comment] 2023-11-24 13:54
Hum even the API is wrong : 
![image](https://github.com/keycloak/keycloak/assets/11772429/9edc1649-1f10-4bbc-ac29-acaa5c8593d1)

**Comment by omasseau** [comment] 2023-11-24 14:11
More infos : 
I noticed I also cannot unassign the role : 

![image](https://github.com/keycloak/keycloak/assets/11772429/d73ffd23-af45-4d96-95dd-e64f4938f16e)

2023-11-24 15:04:39,877 WARN  [org.keycloak.services.resources.admin.RoleMapperResource] (executor-thread-168) Not possible to delete role. It's hardcoded by LDAP mapper: org.keycloak.models.ModelException: Not possible to delete role. It's hardcoded by LDAP mapper

**Comment by omasseau** [comment] 2023-11-27 14:23
The problem was also reproduced with an older version of Keycloak (15). It seems we have the problem only when the associated role comes from the from an harcoded ldap role mapper.

**Comment by rmartinc** [comment] 2023-11-27 16:08
@omasseau  Please don't mix things as we are talking about two different issues.

@jonkoops @omasseau AFAIK the admin UI just shows the list of users if there are no user storage providers configured in the realm. See [here](https://github.com/keycloak/keycloak/blob/23.0.0/js/apps/admin-ui/src/components/users/UserDataTable.tsx#L214). I don't know when this was introduced but I remember working like this long ago.

@omasseau The [HardcodedLDAPRoleStorageMapper](https://github.com/keycloak/keycloak/blob/23.0.0/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedLDAPRoleStorageMapper.java) adds the role to the user representation without really adding it to the database. So what you are seeing is expected. The user will be reported to be in that role (also in tokens and so on and so forth), but it cannot be deleted or appears in the role.

**Comment by omasseau** [comment] 2023-11-27 17:36
> @omasseau Please don't mix things as we are talking about two different issues.
> 

Sorry, but I thought they could be related (one being the consequence of the other). This is why I continued to add informations in the same thread.

**Comment by omasseau** [comment] 2023-11-27 17:40
> @omasseau The [HardcodedLDAPRoleStorageMapper](https://github.com/keycloak/keycloak/blob/23.0.0/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedLDAPRoleStorageMapper.java) adds the role to the user representation without really adding it to the database. So what you are seeing is expected. The user will be reported to be in that role (also in tokens and so on and so forth), but it cannot be deleted or appears in the role.

OK I understand.
But is it also expected  that no users at all are reported in the role (wether through the UI or through the Admin API) when it is an harcoded role ?

**Comment by rmartinc** [comment] 2023-11-28 08:23
There are no users at all displayed because I suppose the role is not directly assigned to any user, all the users are using the `HardcodedLDAPRoleStorageMapper` which is like a ghost assignment. If you create a db user and assign the role normally to that user, the user will be appear in the role.

**Comment by martin-kanis** [comment] 2024-02-28 16:34
Entering * to show all users when you use LDAP is indeed an expected behaviour. We changed it since Keycloak 22 (issue https://github.com/keycloak/keycloak/issues/17294). Thus this is not a bug. 

~invalid

**Comment by stianst** [comment] 2024-02-29 06:18
~invalid

**Closed by stianst** 2024-02-29 06:18 UTC
Labels: kind/bug, area/admin/api, team/core-iam
