### ISSUE TITLE
offlineSessionMaxLifespan and clientOfflineSessionMaxLifespan values still affect session lifetime regardless of offlineSessionMaxLifespanEnabled

### ISSUE THREAD

**Issue by yoransabern** [keycloak/keycloak#15550] opened 2022-11-17 15:09 UTC
### Area

authentication

### Describe the bug

We recently noticed on our keycloak v18 server that our offline sessions started expiring (**before idle timeout**) even though we have **offlineSessionMaxLifespanEnabled** set to false.

We noticed the values for **clientOfflineSessionMaxLifespan** and **offlineSessionMaxLifespan** were still set to a value greater than 0.
We can clearly see in the PUT auth/admin/realms/{realm-name} call that goes out when we use the save button in the administrator ui that these values do not get reset to **0** if the **offlineSessionMaxLifespanEnabled** is set to **false**.

We're experiencing the exact same problem with V20.0, however the only difference is that there's no way in the ui to change the clientOfflineSessionMaxLifespan value on realm level anymore. (if someone could shine a light on the differentce between those two and why its not in v20 anymore that would be great)

To me there seem to be two problems regarding this bug:

1. The backend of keycloak should not be considering **offlineSessionMaxLifespan** or **clientOfflineSessionMaxLifespan** if **offlineSessionMaxLifespanEnabled**  is set to false to invalidate sessions even if they have a value configured.
2. The frontend needs to send value 0 for **offlineSessionMaxLifespan** and **clientOfflineSessionMaxLifespan**  if **offlineSessionMaxLifespanEnabled**  is **false**

### Version

20.0.0

### Expected behavior

1. The backend of keycloak should not be considering **offlineSessionMaxLifespan** or **clientOfflineSessionMaxLifespan** if **offlineSessionMaxLifespanEnabled**  is set to false to invalidate sessions even if they have a value configured.
2. The frontend needs to send value 0 for **offlineSessionMaxLifespan** and **clientOfflineSessionMaxLifespan**  if **offlineSessionMaxLifespanEnabled**  is **false**

### Actual behavior

1. Offline sessions are expiring at the **offlineSessionMaxLifespan** and/or **clientOfflineSessionMaxLifespan** configured values even though **offlineSessionMaxLifespanEnabled**  is **false**
2. The frontend is sending the existing value for **offlineSessionMaxLifespan** and **clientOfflineSessionMaxLifespan**  if **offlineSessionMaxLifespanEnabled**  is **false**

### How to Reproduce?

1. Create a new realm 
2. Go to session configuration in the admin console
3. Under Offline session settings set Offline Session Max Limited to true/on
4. Set Offline Session Max to 1 minute
5. Set Offline Session Idle to 90 Days (anything more than 1 works really)
6. Save
7. Under Offline session settings set Offline Session Max Limited to false/off
8. Save
9. Fetch a token using scope offline_access (ensure your user and client are configured to allow that)
10. Attempt to use the refresh token from this response to fetch a new token after 1-5 minutes

**Comment by mposolda** [comment] 2023-03-06 13:55
@rmartinc Another issue, which seems to be very related to your recent work

**Comment by rmartinc** [comment] 2023-03-06 15:43
@yoransabern I cannot reproduce this on 21.0.1. Besides I see that the flag is really taken into account in both  [global](https://github.com/keycloak/keycloak/blob/21.0.1/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/util/SessionTimeouts.java#L168-L169) and [client](https://github.com/keycloak/keycloak/blob/21.0.1/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/util/SessionTimeouts.java#L218-L219) session max lifespan.

I have followed your reproducer steps using the "security-admin-console" as the client and the tokens are refreshed after 5 min and even more. I also see that the token response contains `"refresh_expires_in":0` as the refresh is never expired.

Maybe it was more about something weird in the new console with the boolean values (there have been some issues with them). Can you please check with the new version?

**Comment by Mohamed-Hammada** [comment] 2023-04-06 12:05
@rmartinc Is it possible to prevent session expiration for non-expert developers through configuration or custom SPI providers? as I'm experiencing an issue where my sessions are randomly expiring when I attempt to log in.

I would greatly appreciate your support.

**Comment by rmartinc** [comment] 2023-06-14 07:42
We have managed a big rework about this topic in https://github.com/keycloak/keycloak/pull/17525 and the changes in documentation are being managed in https://github.com/keycloak/keycloak/pull/20967 (not merged yet). I have re-tested this with the new changes and I cannot reproduce it.

You can try it by yourself with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).

**Comment by rmartinc** [comment] 2023-06-20 07:10
Once the documentation changes are also merged I'm closing this too. Please re-open or file a new issue if something wrong is detected. Thanks!

**Closed by rmartinc** 2023-06-20 07:10 UTC
Labels: area/authentication, kind/bug
