### ISSUE TITLE
LDAP User sync reports "0 users removed" when in fact it did remove a user

### ISSUE THREAD

**Issue by tomqwpl** [keycloak/keycloak#26353] opened 2024-01-20 12:12 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I am experimenting with the LDAP user sync behaviour. I have connected Keycloak to a Samba instance running as an active directory.
I create a test user in the directory and sync.
I can then search for the test user in keycloak and I find it.
I then delete the user from the directory. 
When I then use the "sync all users" action, I get a notification: "Sync of users finished successfully.0 users added, 4 users updated, 0 users removed, 0 users failed.". Note the "0 users removed".
When I now search for the test user in keycloak, it no longer exits. This is what I believe is the expected behaviour (can I control that? Can I instead mark it as inactive?).
So the LDAP sync appears to have deleted the user. Yet it says "0 users removed".

Am I just misunderstanding what's happenning?

By the way, can I get more detail on what has actually occurred when it says "4 users updated" etc? Can I get a detailed list of what users have been added, updated etc, and what changes were made?

### Version

23.0.4

### Expected behavior

I get a message that correctly lists how many users have been deleted.

### Actual behavior

It says "no users removed">

### How to Reproduce?

As per description above.

**Comment by martin-kanis** [comment] 2024-02-13 12:29
Thanks for the report @tomqwpl. I was able to reproduce it from the testsuite. 

Following code didn't report that a user was removed.
```
LDAPTestUtils.removeLDAPUserByUsername(ctx.getLdapProvider(), ctx.getRealm(), ctx.getLdapProvider().getLdapIdentityStore().getConfig(), "user1");
            
SynchronizationResult syncResult = usersSyncManager.syncAllUsers(sessionFactory, ctx.getRealm().getId(), ctx.getLdapModel());
LDAPTestAsserts.assertSyncEquals(syncResult, 0, 0, 1, 0);
```

Looking more into the code, `org.keycloak.storage.user.SynchronizationResult#increaseRemoved` is called only for groups but not for users. It seems to be broken for a long time so this is not a regression from Keycloak 22 or 23. It will be in our backlog for now. Contributions are also welcomed.

**Comment by sguilhen** [comment] 2024-04-01 19:54
The LDAP sync doesn't delete any users, that's why it reports zero users deleted. What happens is, the users are fetched from LDAP (can be a full search, can be a partial one such as the `Sync changed users`) and then Keycloak checks if the user already exists - if it does, it is "updated", otherwise it is imported. Failures to import the user are also recorded (for example, entry has a null value for the attribute that is mapped to the username).

No users are deleted at the time you run the synchronization. If you synch users and check your DB, you will still see the previously imported users, even those that were deleted from LDAP. Now, when you perform a search, or try to log in with a user that was deleted from LDAP, Keycloak validates the locally stored user and at this time it realizes the user no longer exists in LDAP. So it deletes any invalid users. (See https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L127-L136).

The bottom line here is: no users are deleted during sync. A naive implementation would simply compare the users fetched from LDAP with the list of users already imported, and delete any imported users from the DB that are not fetched from LDAP. But that would only work for full sync, and sometimes that's not what is happening. For example periodic sync only fetches users that changed since the last synch, so it can't really make any assumptions about users in the local DB that don't appear in the search result.

As for the "updated" users, the message can be a bit misleading. It contains the number of users that were fetched from LDAP and already exist in the local DB. All mappers are applied again during sync, so that info that changed in LDAP is reflected in the local user, but even if nothing has changed the user will still count as an "updated" user. Treat this number as a measure of users that are now in sync with LDAP, even if nothing changed locally.

**Closed by sguilhen** 2024-04-01 19:54 UTC
Labels: kind/bug, priority/important, area/ldap, help wanted, team/core-iam
