### ISSUE TITLE
Generate registration access token use wrong signature algorithm

### ISSUE THREAD

**Issue by michelpromonet** [keycloak/keycloak#10715] opened 2022-03-11 14:46 UTC
### Describe the bug

Generating a client access token doesnot use the signature algorithm specified.
![kc](https://user-images.githubusercontent.com/26296946/157887806-3cf2dc7c-38df-4739-82f9-82bcd08fc384.jpg)

The token has HS256 algo field

### Version

16.1.1

### Expected behavior

should have alg field set to RS256

### Actual behavior

should have alg field set to HS256

### How to Reproduce?

Click on "Generate registration access token", decode the token https://jwt.io/ give :
{
  "alg": "HS256",
  "typ": "JWT",
  "kid": "<>"
}

### Anything else?

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/jose/jws/DefaultTokenManager.java#L196 
```
    public String signatureAlgorithm(TokenCategory category) {
        switch (category) {
            case INTERNAL:
                return Algorithm.HS256;
            case ADMIN:
                return getSignatureAlgorithm(null);
```

Modifying with 
```
    public String signatureAlgorithm(TokenCategory category) {
        switch (category) {
            case INTERNAL:
            case ADMIN:
                return getSignatureAlgorithm(null);
```
Allow to choose the algorithm used by the token generated from keycloak UI.

**Comment by mposolda** [comment] 2022-06-28 08:20
I am closing as this is not a bug. So just to clarify:

- The "Signature algorithm" field is related to the client authentication with "Signed JWT". It specifies that when client wants to authenticate against Keycloak, it needs to use private key signed with the "RS256" algorithm and Keycloak is expected to verify that with client's public key. More details in the Keycloak documentation for client authentication and in the OIDC specification (chapter for client authentication)

- The registration access token is related to OIDC client registration. This is always signed with the HS256 as it is both issued and verified by Keycloak (in fact it is Keycloak implementation detail that registration access token is JWT, as OIDC client registration specs does not prescribe that this token must be JWT. See https://openid.net/specs/openid-connect-registration-1_0.html ).

- You can see that there is line (href) between both sections of the "Credentials" tab, to mark that they are unrelated to each other. However I agree that maybe there is space for improvement of the usability of this screen to avoid the confusions... Maybe both parts of the screen can be somehow better isolated from each other. I am tagging @ssilvert and @jonkoops in case you guys have some better idea how to make this tab cleaner in the new admin console (If it is already cleaner, then feel free to ignore this comment). However this would be separate usability improvement rather than bugfix, so closing this.

**Closed by mposolda** 2022-06-28 08:20 UTC
Labels: area/oidc, kind/bug, status/triage

**Comment by mposolda** [comment] 2022-06-28 12:56
@ssilvert Thanks for doublecheck this!
