### ISSUE TITLE
Theme & Provider folder empty in KeyCloak 20.0.3

### ISSUE THREAD

**Issue by zzador** [keycloak/keycloak#19121] opened 2023-02-16 16:17 UTC
### Describe the bug

The documentation and nearly all online tutorials advice to take an existing theme in the subfolder "theme" and extend it to specific needs. The theme folder however is empty and there is absolutely NO TEMPLATE to start from. I don't even know where and how to start.

### Version

20.0.3

### Expected behavior

Well documented

### Actual behavior

Very poorly documented

### How to Reproduce?

Try to theme your keycloak login with the help of the keycloak documentation and the current server download (v 20.0.3)

**Comment by ssilvert** [comment] 2023-04-15 20:12
There is a readme.md file in the themes directory that points to the documentation and to the jar for the built-in themes.

This is a documentation issue and not a UI issue.

**Comment by jsorah** [comment] 2023-05-18 20:15
Closing as a duplicate of #17130

**Closed** 2023-05-18 20:16 UTC
Labels: kind/bug, area/docs, status/triage, team/other
