### ISSUE TITLE
Accepting terms & conditions triggers a java.lang.NullPointerException

### ISSUE THREAD

**Issue by valentindruon** [keycloak/keycloak#21560] opened 2023-07-10 14:02 UTC
### Before reporting an issue

- [X] I have searched existing issues

### Area

core

### Describe the bug

I have set `Terms and conditions` as a default required action on my realm

At the first log in, my newly created user can accept or decline my terms. Everything works fine.

Then, I add a `Terms and conditions` required action on **this same user**, but when he signs in again, when it's time for him to accept the terms, it triggers a NullPointerException

### Version

21.1.2

### Expected behavior

It should not trigger any error

### Actual behavior

Accepting terms & conditions as an end user triggers this error : 

`Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.userprofile.AttributeMetadata.getGuiOrder()" because "o.metadata" is null `

### How to Reproduce?

- Set `Terms and conditions` as a default required action
- Sign in with a new user, and accept conditions
- Go to Admin UI, and set `Terms and conditions` as a required action on this user
- Try to sign in again with the user

**Comment by rmartinc** [comment] 2023-07-11 07:42
@valentindruon I cannot reproduce it with a default 21.1.2 (not in current main either). Can you please check if you can reproduce the same with a clean realm and default startup options? Maybe something more is needed that we are missing?

**Comment by valentindruon** [comment] 2023-07-11 07:52
@rmartinc ah, seems like I cannot reproduce it with a clean realm either...
At first I thought it came from the fact we add custom attributes to our users, but it seems like it's not

**Comment by rmartinc** [comment] 2023-07-28 10:11
@valentindruon I'm closing this. If you discover there is an issue just re-open of file a new issue. Thanks!

**Closed by rmartinc** 2023-07-28 10:11 UTC
Labels: kind/bug, area/core, team/core
