### ISSUE TITLE
NPE when deleting Identity provider

### ISSUE THREAD

**Issue by tungtt1501** [keycloak/keycloak#23192] opened 2023-09-13 04:17 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Delete an Identity provider -> NPE
![image](https://github.com/keycloak/keycloak/assets/71362704/82faa672-7a83-49b2-ab90-8ca893b95934)

### Version

22.0.1

### Expected behavior

Can be deleted without error

### Actual behavior

NPE
![image](https://github.com/keycloak/keycloak/assets/71362704/82faa672-7a83-49b2-ab90-8ca893b95934)

### How to Reproduce?

Delete an Identity provider.
- Go to tab Identity providers -> add new provider -> choose "Keycloak OpenID Connect provider" -> enter the alias for provider(for example: test-oidc) + add the config -> click button Add
- After add the Identity provider above -> delete it -> NPE error(see in log)

**Comment by kaustubh-rh** [comment] 2023-09-13 04:51
Hi @tungtt1501 , can you share the exact steps to reproduce the issue? Thanks

**Comment by tungtt1501** [comment] 2023-09-13 05:10
@kaustubh-rh Below steps to reproduce:
- Go to tab Identity providers -> add new provider -> choose "Keycloak OpenID Connect provider" -> enter the alias for provider(for example: test-oidc) -> click button Add
- After add the Identity provider above -> delete it -> NPE error(see in log)

**Comment by ssilvert** [comment] 2023-09-13 18:22
@tungtt1501 I followed your steps and did not see any error.

Can you try this on the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by pedro-hos** [comment] 2023-09-13 22:38
@tungtt1501 @ssilvert  I was not able to reproduce on nightly. @tungtt1501 there are some specific configurations that you are using to test?

**Comment by ssilvert** [comment] 2023-10-02 19:40
I'm closing this.  We can reopen if someone can reproduce the problem on a recent build.

**Closed by ssilvert** 2023-10-02 19:40 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
