### ISSUE TITLE
Error in Core? ( Clients Client details Dedicated scopes): Cannot read properties of undefined (reading 'helpText')

### ISSUE THREAD

**Issue by Laurenzi** [keycloak/keycloak#15349] opened 2022-11-04 07:09 UTC
### Describe the bug

When opening up a client from any realm and navigating to Client scopes tab in the Client details view, upon clicking a dedicated mapper (for example account-dedicated, see screenshot)
![image](https://user-images.githubusercontent.com/5363733/199910423-21c895ed-0c44-4760-8f25-86119c1f223d.png)

I get an error in the UI: "Cannot read properties of undefined (reading 'helpText')" and cannot proceed (see another screenshot)
![image](https://user-images.githubusercontent.com/5363733/199910676-194a38cf-5c82-46a3-9bc2-c51852b4f4d6.png)

I am running Keycloak 19.0.2 with the switch "--features-disabled=step-up-authentication" set.

Running browser dev tools & debugger I was able to see that the exception is coming from here, the `mapperType` set by

 ```
protocolMappers.filter(
          (type) => type.id === mapper.protocolMapper
        )[0];
```

Being undefined:
https://github.com/keycloak/keycloak-ui/blob/c6ab6a11901581bf58c5a551385b5f7f6a9cd7b7/apps/admin-ui/src/client-scopes/add/MapperDialog.tsx#L65

I can also see that the protocolMapper list is missing a mapper with `protocolMapper` value of `oidc-acr-mapper`.

EDIT: 
Additional information: I debugged how the default protocolMappers get populated in the UI and was able to surmise that during Keycloak startup DESPITE deliberately disabling step up authentication support, for some reason the OidcLoginProtocolFactory will call `Profile.isFeatureEnabled(Profile.Feature.STEP_UP_AUTHENTICATION)`  (see https://github.com/keycloak/keycloak/blob/55c514ad56b4e13b5d0d64a75a9bcc6a512d3f32/services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java#L215) and it will return `true` instead of `false` which will lead to creating the `oidc-acr-mapper` protocol mapper. This could be related to this behaviour seen here.

### Version

19.0.2 (also observed in 20.0.0)

### Environment

Chrome version 107

### Expected behavior

Expected for keycloak not to display error and to display whatever is in dedicated mapper tab.

### Actual behavior

I get an error in the UI: "Cannot read properties of undefined (reading 'helpText')" and cannot proceed (see another screenshot)
![image](https://user-images.githubusercontent.com/5363733/199910676-194a38cf-5c82-46a3-9bc2-c51852b4f4d6.png)

### How to Reproduce?

Open up keycloak admin UI, navigate to any realm and pick a client in the client menu (from left). then navigate to Client scopes. In that view, pick the "clientname-dedicated" mapper (ie. if my client would be named account, then i'd have account-dedicated item in the list) and click it. This reproduces the error in the Keycloak UI.

**Comment by lexcao** [comment] 2022-11-05 14:34
Hi @Laurenzi 
I reproduced this from my local, then I created a PR to fix this.
https://github.com/keycloak/keycloak/pull/15356

There is some unit testing that needs team help.
Could you please check this? @pedroigor

**Comment by lexcao** [comment] 2022-11-06 15:05
My PR is duplicated, it could be fixed at https://github.com/keycloak/keycloak/pull/15341

**Comment by elavrenchuk** [comment] 2022-11-08 07:24
Hi @lexcao, I can confirm that this is still not fixed. I got to my client's scopes, one of those default *-dedicated and received this error:
`Cannot read properties of undefined (reading 'helpText')`
![image](https://user-images.githubusercontent.com/30771249/200500050-2a2a944d-27bf-49df-8419-e43734a16a50.png)

**Comment by lexcao** [comment] 2022-11-08 09:11
Hi, @elavrenchuk 
The PR was merged but is not released.
Could you please try `nightly`?

**Comment by elavrenchuk** [comment] 2022-11-08 10:12
@lexcao yes, you are right, that worked. 
Thanks for your prompt response!

Can you please also tell me, when it will be released? Thanks in advance!

**Comment by lexcao** [comment] 2022-11-08 16:08
@elavrenchuk 
I am not sure, may be the next release.
Need Keycloak team to check.

**Comment by jonkoops** [comment] 2022-11-14 11:43
Since #15341 is quite an extensive refactor I don't think we'll be back-porting it in a patch release, so it will likely end up in the next major version.

@stianst do you feel like we could safely backport your refactored code, or would you rather wait for major?

**Comment by stianst** [comment] 2022-11-14 14:34
We don't need to (and shouldn't) backport the whole thing.

This particular issue should be fixed by only adding changes to OIDCLoginProtocolFactory and DefaultMigrationProvider.

**Closed** 2022-11-15 08:29 UTC
Labels: kind/bug, area/admin/ui
