### ISSUE TITLE
Non informative message when trying to create subgroup that already exists

### ISSUE THREAD

**Issue by MaryamBerg** [keycloak/keycloak#8940] opened 2021-11-28 18:38 UTC
### Describe the bug

When subgroup already exists keyclock server will return message status code 409 with message "Unknown_error" when Endpoint POST "/{realm}/groups/{id}/children" is called.

### Version

15.0.2

### Expected behavior

More informative return message

### Actual behavior

When subgroup already exists keyclock server will return message status code 409 with message "Unknown_error" when Endpoint POST "/{realm}/groups/{id}/children" is called.

### How to Reproduce?

Create group with body params: {"name": "A"}, create with body params: {"name": "B"} with Endpoint POST "/{realm}/groups/{id_of_group "A"}/children" . This will return status 200. Now we call same end point to create subgroup B with same body and path parameters.  Keyclock server will return message status code 409 with message "Unknown_error"

**Comment by abstractj** [comment] 2021-12-23 19:18
@MarissaTee please try the latest release (16.1.0), and let us know if the issue persists.

**Comment by rmartinc** [comment] 2023-02-17 09:00
The issue is still the same in last nightly but it's just a minor issue. If someone from the community can help on this would be much appreciated.

**Comment by keshavprashantdeshpande** [comment] 2024-09-09 20:27
@rmartinc @MaryamBerg This issue is no more reproducible. Now the error message is quite descriptive and according to me this issue can be closed.

**Comment by rmartinc** [comment] 2024-09-10 07:05
Thanks @keshavprashantdeshpande!

Yes, I have quickly checked and the error message is now `Sibling group named 'xxx' already exists.`

Closing the issue.

**Closed by rmartinc** 2024-09-10 07:05 UTC
Labels: area/admin/api, help wanted, status/triage
