### ISSUE TITLE
Inclusion of `resteasy-jackson2-provider` in a Keycloak extension causes build failure

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#25589] opened 2023-12-14 20:16 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client/java

### Describe the bug

Sometimes extensions include the use of `keycloak-admin-client`, which depends on `resteasy-jackson2-provider`. >=23, after the upgrade to resteasy reactive, this seems to cause a build problem 

### Version

23

### Expected behavior

This should allow the `resteasy-jackson2-provider` jar to be included in the `providers/` dir.

### Actual behavior

```
#0 3.859 Caused by: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.name()" because "currentClazz" is null
#0 3.859 	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.createTypedAnnotationInstance(ResteasyReactiveProcessor.java:850)
#0 3.859 	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor$6.transform(ResteasyReactiveProcessor.java:832)
#0 3.859 	at io.quarkus.arc.processor.AnnotationStore.transform(AnnotationStore.java:108)
#0 3.859 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
#0 3.859 	at io.quarkus.arc.processor.AnnotationStore.getAnnotations(AnnotationStore.java:61)
#0 3.859 	at io.quarkus.arc.processor.AnnotationStore.hasAnnotation(AnnotationStore.java:85)
#0 3.859 	at io.quarkus.arc.processor.BeanDeployment.isVetoed(BeanDeployment.java:1277)
#0 3.859 	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1000)
#0 3.859 	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:271)
#0 3.859 	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:141)
#0 3.859 	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:419)
#0 3.859 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 3.859 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 3.859 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 3.859 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 3.859 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#0 3.860 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#0 3.860 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#0 3.860 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#0 3.860 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#0 3.860 	at java.base/java.lang.Thread.run(Thread.java:840)
#0 3.860 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

Create a `Dockerfile` that extends the base image with the `resteasy-jackson2-provider` jar in the `providers/` dir and then runs `build`.

```
COPY ./org.jboss.resteasy-resteasy-jackson2-provider-6.2.4.Final.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh --verbose build
```

### Anything else?

Already noticed here https://github.com/keycloak/keycloak/discussions/25265

Tried on `nightly`.

**Comment by koplas** [comment] 2023-12-22 14:17
@xgp Can you include the required `keycloak-admin-client` dependency in [quarkus/runtime/pom.xml](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/pom.xml) and build the server as described here: [Building keycloak](https://github.com/keycloak/keycloak/blob/main/docs/building.md)?
If you then declare the dependency in your extension as provided, it should no longer cause a conflict.

**Comment by xgp** [comment] 2023-12-22 15:42
I can try this. 

Can you explain exactly what this does? What is special about this library that requires a custom build of Keycloak? Are there other libraries with the same requirements? Is there any documentation that explains this?

Thank you!

**Comment by vince760** [comment] 2023-12-22 18:33
> I can try this. Can you explain exactly what this does? What is special about this library that requires a custom build of Keycloak? Are there other libraries with the same requirements? Is there any documentation that explains this? Thank you!

I am getting a build error when I do as suggested by @koplas...would be curious to know if yours builds. 
![image](https://github.com/keycloak/keycloak/assets/26665765/886802a3-80a4-4236-9123-b2d61bc167b1)

**Comment by koplas** [comment] 2023-12-24 13:29
> I am getting a build error when I do as suggested by @koplas...would be curious to know if yours builds. ![image](https://private-user-images.githubusercontent.com/26665765/292567127-886802a3-80a4-4236-9123-b2d61bc167b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTk5MzgsIm5iZiI6MTcwMzQxOTYzOCwicGF0aCI6Ii8yNjY2NTc2NS8yOTI1NjcxMjctODg2ODAyYTMtODBhNC00MjM2LTkxMjMtYjJkNjFiYzE2N2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEyMDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMmYwNjZmMWQyZmRkNDQxNmUwM2FmY2NjMzNhOTc3Yzc3MzEyYjQwMThhNWM4NWFlNWRkNjU0ZDcyYWZkYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QADADwfLOq2-0pT-nMcZ1DJdaXRWxyojOes5-2BWF1A)

The following works for me:
1. Clone the keycloak repo
2. Run `mvn -DskipTests clean install`
3. Add `keycloak-admin-client-reactive` to the runtime and `keycloak-admin-client-reactive-deployment` to deployment (Apply this [keycloak-admin-client.diff.txt](https://github.com/keycloak/keycloak/files/13761899/keycloak-admin-client.diff.txt))

4. Run `mvn -pl quarkus/deployment,quarkus/dist -am -DskipTests clean install`

I have not tested it, but now you should be able to use the `keycloak-admin-client-reactive` in your extension.

> Can you explain exactly what this does? What is special about this library that requires a custom build of Keycloak? Are there other libraries with the same requirements? Is there any documentation that explains this?

Keycloak provides a couple of dependencies that the extension can use. For example, `quarkus-resteasy-reactive` is provided by the Quarkus runtime and can be used by the Keycloak extension. Using a dependency that uses the same transitive dependencies as the runtime can result in these errors. A workaround would be to exclude all conflicting dependencies, but this can break if you upgrade Keycloak.

I have a similar problem and the documentation and upgrade guide only mentions that the usage is deprecated and the application should be rewritten. Someone with Quarkus and Keycloak expertise can provide the intended way of including dependencies into the extension.

**Comment by xgp** [comment] 2023-12-29 19:28
Thanks @koplas . It needed the `quarkus-keycloak-admin-client-common` as well, but it seems to work. Here is the patch I had to use:
```
diff --git a/quarkus/deployment/pom.xml b/quarkus/deployment/pom.xml
index 4476986c6d..824fff2267 100644
--- a/quarkus/deployment/pom.xml
+++ b/quarkus/deployment/pom.xml
@@ -170,6 +170,19 @@
             <artifactId>rest-assured</artifactId>
             <scope>test</scope>
         </dependency>
+
+        <!-- Dependencies used by keycloak extensions -->
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-keycloak-admin-client-common-deployment</artifactId>
+            <version>3.2.9.Final</version>
+        </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-keycloak-admin-client-reactive-deployment</artifactId>
+            <version>3.2.9.Final</version>
+        </dependency>
+
     </dependencies>
 
     <build>
diff --git a/quarkus/runtime/pom.xml b/quarkus/runtime/pom.xml
index 50a99a9f85..8465d770a4 100644
--- a/quarkus/runtime/pom.xml
+++ b/quarkus/runtime/pom.xml
@@ -112,6 +112,18 @@
             <artifactId>picocli</artifactId>
         </dependency>
 
+	<!-- Dependencies used by keycloak extensions -->
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-keycloak-admin-client-common</artifactId>
+            <version>3.2.9.Final</version>
+        </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-keycloak-admin-client-reactive</artifactId>
+            <version>3.2.9.Final</version>
+        </dependency>
+
         <!-- Keycloak -->
         <dependency>
             <groupId>org.keycloak</groupId>
```

I appreciate your explanation, but I still don't really understand what is going on or why it requires a custom build. Does it have to do with those `-deployment` dependencies that end up in `/opt/keycloak/lib/lib/deployment/` dir? And that gets used during the `build` phase to set up some of the quarkus magic?

I've been using the Keycloak Admin Client in extensions since version 9, and there has always been some problem. Between having to build your own module, RESTEasy dependency/version hell, and now this. It really makes the case to stop using it altogether.

**Comment by jemonra** [comment] 2024-01-12 11:26
I'm facing the same issue. Will this be fixed in a future version?

**Comment by koplas** [comment] 2024-01-12 19:57
This is more of an issue of how Quarkus handles extensions and not a keycloak specific problem.

**Comment by koplas** [comment] 2024-01-26 14:19
The root cause for this problem seems to be that different `ClassLoader`s are used.

**Comment by mposolda** [comment] 2024-02-27 11:02
I am adding to Backlog as not sure when Keycloak team has capacity to prioritize this. Anyone is welcome to investigate and send PR with fixing this if it can be fixed on Keycloak side in a nice way. See contributions guide for the details how to contribute a fix https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md .

The possible workaround is also to not use keycloak-admin-client in your providers. As long as provider is deployed in Keycloak, it might be an option to use model-api directly (for example use something like `session.realms().getRealm()` to obtain `RealmModel` in your provider instead of calling keycloak-admin-client to obtain realm).

**Comment by stianst** [comment] 2024-02-28 06:30
We won't include the admin client in the dist that's for sure, so we need some other solution.

I'd give this a go and see if it works: https://quarkus.io/guides/security-keycloak-admin-client

**Comment by xgp** [comment] 2024-02-28 18:47
Thanks for the clarification on including the admin client @stianst 

I tried the quarkus "security-keycloak-admin-client" and I wasn't able to get it to work from inside Keycloak.

**Closed** 2024-06-06 00:06 UTC
Labels: kind/bug, help wanted, area/admin/client-java, team/core-clients, team/core-shared, status/auto-expire, status/auto-bump, priority/normal, status/bumped-by-bot, status/expired-by-bot
