### ISSUE TITLE
cannot acces to admin GUI 

### ISSUE THREAD

**Issue by mehdia4ever** [keycloak/keycloak#23000] opened 2023-09-06 08:53 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hi,

I got the error message when connecting to the keycloak admin GUI with the admin account

code error : 400

{"error":"invalid_grant","error_description":"Code not valid"}

https://URL/realms/master/protocol/openid-connect/token

### Version

21.0.1

### Expected behavior

First step : Acces to admin URL

![image](https://github.com/keycloak/keycloak/assets/73796056/a17dc566-e43f-40cd-9027-727cff6608c7)

Second step : using the admin account to login

![image](https://github.com/keycloak/keycloak/assets/73796056/a023ba7b-6496-41d5-aef5-7691a130f409)

third step :  loading blockeg 

![image](https://github.com/keycloak/keycloak/assets/73796056/62dff4f8-4927-4f50-be4b-79e118c8c478)

with error 

Uncaught undefined 

{"error":"invalid_grant","error_description":"Code not valid"}

### Actual behavior

First step : Acces to admin URL

![image](https://github.com/keycloak/keycloak/assets/73796056/a17dc566-e43f-40cd-9027-727cff6608c7)

Second step : using the admin account to login

![image](https://github.com/keycloak/keycloak/assets/73796056/a023ba7b-6496-41d5-aef5-7691a130f409)

third step :  loading blockeg 

![image](https://github.com/keycloak/keycloak/assets/73796056/62dff4f8-4927-4f50-be4b-79e118c8c478)

with error on the browser debug tools.

Uncaught undefined 

{"error":"invalid_grant","error_description":"Code not valid"}

### How to Reproduce?

i don't know

### Anything else?

no

**Comment by fhochleitner** [comment] 2023-09-06 10:13
we are facing the same issue at the moment. 
for us its reproducable with a standard keycloak instance from the keycloak operator V22.0.1 on openshift 4.12.30

**Comment by fhochleitner** [comment] 2023-09-06 12:38
> we are facing the same issue at the moment. for us its reproducable with a standard keycloak instance from the keycloak operator V22.0.1 on openshift 4.12.30

nevermind. our issue had a different root cause. we have changed from supplying a TLS certificate and using the operator to generate an ingress to supplying a route ourselves with cert-manager annotations. but keycloak started with "KC_PROXY=passthrough" option. this caused admin console to not be available as the route was edge. changing the value of the proxy configuration to edge fixed our issue. 

might be relevant for resolving https://github.com/keycloak/keycloak/issues/9781 as well. so I'll link it here.

**Comment by ssilvert** [comment] 2023-09-06 22:12
There is a catch-all issue for this.
https://github.com/keycloak/keycloak/issues/14666

I'm going to close this and add a reference in the description for #14666

**Closed by ssilvert** 2023-09-06 22:12 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
