### ISSUE TITLE
Kerberos fallback to next provider (user federation) when 

### ISSUE THREAD

**Issue by Mystikal57** [keycloak/keycloak#9290] opened 2021-12-21 15:27 UTC
### Describe the bug

hi,

Why keycloak/kerberos doesn't fallback to next federation provider when it doesn't find user in the first federation provider ?

_Kerberos/SPNEGO authentication succeeded with username [user1], but couldn't find or create user with federation provider [fed01]_

thank you

### Version

15.1

### Anything else?

There is support ticket 286 asking for this.

**Comment by mposolda** [comment] 2022-08-11 08:02
I am changing to task as support for the fallback is rather a new thing to implement than a bug.

There are support tickets related to this.

**Comment by hmlnarik** [comment] 2023-02-17 12:03
Closing this as duplicate of #14665

**Closed by hmlnarik** 2023-02-17 12:03 UTC
Labels: kind/feature, area/ldap, status/triage
