### ISSUE TITLE
"Failed to add user '%s' to realm '%s': user with username exists" Error displayed in logs if any user already exists in master realm.

### ISSUE THREAD

**Issue by sjweixel** [keycloak/keycloak#16961] opened 2023-02-08 21:17 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

If Keycloak instance is started with KEYCLOAK_ADMIN env var set, the "Failed to add user '%s' to realm '%s': user with username exists" message is displayed if any user exists in the master realm.  

### Version

20.0.3

### Expected behavior

The user specified in KEYCLOAK_ADMIN should always be created unless it actually exists already, in which case the "user with username already exists" would be appropriate.  Previous versions of Keycloak would create the admin user specified in the environment variable even if admin user already exists.  This behavior allows recovery if original realm admin user gets accidentally deleted.

### Actual behavior

"Failed to add user '%s' to realm '%s': user with username exists" message is displayed if any user exists in the master realm.   

### How to Reproduce?

Start a new Keycloak instance with KEYCLOAK_ADMIN=admin and KEYCLOAK_PASSWORD=admin
Stop Keyclaok
Restart same Keycloak instance with KEYCLOAK_ADMIN=myadmin and KEYCLOAK_PASSWORD=myadmin , 
The myadmin user will not be created and Error in log: "Failed to add user 'myadmin' to realm 'master: user with username exists". 

### Anything else?

This bechavior changed sometime since Keycloak 12.

**Comment by mabartos** [comment] 2023-02-09 13:40
Duplicate of: #15789

**Comment by mabartos** [comment] 2023-02-23 09:21
@sjweixel You're right. Reopening this issue.

**Comment by vmuzikar** [comment] 2023-04-26 15:40
Closing based on reasoning stated in the related PR: https://github.com/keycloak/keycloak/pull/17230#issuecomment-1523636290

**Closed by vmuzikar** 2023-04-26 15:40 UTC
Labels: kind/bug, area/dist/quarkus

**Comment by mhrsavci** [comment] 2023-07-31 09:05
Upgrade Keycloak 21.0.0 -> Keycloak 21.1.2
