### ISSUE TITLE
When press the browser's back button in Login page, the page gets stuck in a loading state. 

### ISSUE THREAD

**Issue by Enesbakir** [keycloak/keycloak#31857] opened 2024-08-02 11:18 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

When users are on the Keycloak login screen and press the browser's back button, the page gets stuck in a loading state. This behavior is not expected and can lead to confusion for users trying to navigate back.

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

When the back button is pressed, the user should be taken to the previous page without any loading issues.

### Actual behavior

The page gets stuck in a loading state, and users are unable to proceed.

### How to Reproduce?

Navigate to the Keycloak login screen.
Attempt to log in (or remain on the login screen).
Press the browser's back button.

### Anything else?

![Image20240802141639](https://github.com/user-attachments/assets/c4dd17cb-a7f6-44ca-b379-586eac4b4337)

**Comment by ssilvert** [comment] 2024-08-02 18:20
I'm not seeing this behavior.  I tried both `keycloak` and `keycloak.v2` themes.  Also tried on both Chrome and Firefox.

Maybe you can try the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment] 2024-08-12 19:37
Closing as can't reproduce.

**Closed by ssilvert** 2024-08-12 19:37 UTC
Labels: kind/bug, status/triage, team/ui, area/welcome/ui
