### ISSUE TITLE
Importing SAML Entity Descriptor XML file

### ISSUE THREAD

**Issue by sven-borkert** [keycloak/keycloak#13722] opened 2022-08-11 10:09 UTC
### Describe the bug

Hello,

from the documentation, regarding the import of a SAML client:

"Instead of registering a SAML 2.0 client manually, you can import the client using a standard SAML Entity Descriptor XML file."

https://www.keycloak.org/docs/latest/server_admin/#proc-using-an-entity-descriptors_server_administration_guide

But it seems to accept only JSON files, even the screenshots show only JSON config being imported.

I don't find any way to import the descriptor file that mod-auth-mellon generates.

Regards,
Sven

### Version

19.0.1

### Expected behavior

Being able to import a "SAML Entity Descriptor XML file" like the documentation says.

### Actual behavior

Seems to accept only JSON input of unknown type.

### How to Reproduce?

Open Keycloak, go to "Clients" -> "Import Client" and try to upload a SAML descriptor.

**Comment by hmlnarik** [comment] 2022-08-11 13:39
Thank you for the report. This is a known issue, please see the duplicate issue for additional details.

This is duplicate of keycloak/keycloak-admin-ui#3041

**Closed by hmlnarik** 2022-08-11 13:39 UTC
Labels: kind/bug, status/triage

**Comment by sinannoureddine** [comment] 2022-09-08 10:23
will this UI fix be updated in the distribution from the website? I tried downloading Keycloak from the website and it has the same issue
