### ISSUE TITLE
findClientSessionsOrderedById too wide filter range

### ISSUE THREAD

**Issue by a-bocci** [keycloak/keycloak#13129] opened 2022-07-15 08:17 UTC
### Describe the bug

The named query findClientSessionsOrderedById called by loadUserSessionsWithClientSessions in class JpaUserSessionPersisterProvider uses a faulty filter as it goes on a range of possibile non consecutive UUIDs resulting in a random result set.
If I have 2 offline user sessions starting with '0....' and 'f....' this query could result in the whole table approximately.
This problem leads to heavy cpu and ram usage which could be deadly in a production environment with a large number of offline session used.
We found a programmatic solution using an iteration on user sessions result and searching for client session by user session id.

### Version

16.1.1

### Expected behavior

This query should return the same number of rows for client user sessions as the user sessions they refer to.

### Actual behavior

A random number of rows and unneeded records returned

### How to Reproduce?

Revoking an offline access using the users dashboard on keycloak console for a user with multiple offline session 

### Anything else?

https://github.com/keycloak/keycloak/compare/main...a-bocci:keycloak:loadUserSessionsWithClientSessions_override

solution adopted

**Comment by hmlnarik** [comment] 2022-10-24 11:15
Thank you for the report and solution. This has been consolidated and will be continued in #13340
Duplicate of #13340

**Closed by hmlnarik** 2022-10-24 11:15 UTC
Labels: kind/bug, area/storage, status/triage
