### ISSUE TITLE
Keycloak Administration console loading issue after upgrading the version from 20.0.3 to 22.0.3

### ISSUE THREAD

**Issue by Vishnu-Priya05** [keycloak/keycloak#23788] opened 2023-10-06 12:22 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Upgraded the Keycloak version from 20.0.3 to 22.0.3. Upgrade was successful, but the administration console UI is not loading.

### Version

Chart version: 17.0.0  App version: 22.0.3

### Expected behavior

Keycloak should be up and running and the UI should be available to enter the credentials.

### Actual behavior

Able to get the Keycloak UI.

![image](https://github.com/keycloak/keycloak/assets/118261385/adf5cac4-5c0f-45cb-9a47-35c766d73d35)

But after clicking Administration console, it keeps on loading.

![image](https://github.com/keycloak/keycloak/assets/118261385/2a880433-0ff0-4316-ac3b-79bca3e48c0d)

### How to Reproduce?

N/A

**Comment by jonkoops** [comment] 2023-10-08 10:58
Looks like your browser is blocking `step1.html` for some reason, perhaps you are running an ad blocker or some sort of plugin that is prevent this request from succeeding? Or perhaps it was [blocked in the devtools](https://developer.chrome.com/docs/devtools/network/#block).

**Comment by Vishnu-Priya05** [comment] 2023-10-09 06:45
Tried in other browser as well, and it is not working there as well.

As a part of troubleshooting, compared the helm values of keycloak from github of both the versions 22.0.3-debian-11-r14 and 20.0.3-debian-11-r14.

Found that there is a change in Ingress, where the value of path variable is set as: path: "{{ .Values.httpRelativePath }}"
Whereas in the older version, we have specified the path variable as: path: /

Can you suggest how we can pass that variable?

**Comment by Vishnu-Priya05** [comment] 2023-10-10 06:21
@jonkoops Can we get any update. 

Attaching the helm file for your reference. Kindly let us know if any changes needs to be done in helm.

```
USER-SUPPLIED VALUES:
args:
- -c
- /opt/bitnami/scripts/keycloak/setup.sh && /opt/bitnami/keycloak/bin/kc.sh build
  --cache=ispn --cache-stack=kubernetes && /opt/bitnami/keycloak/bin/kc.sh -cf /opt/bitnami/keycloak/conf/keycloak.conf
  start
auth:
  adminPassword: ****
  adminUser: ****
  managementPassword: ****
  managementUser: ****
cache:
  enabled: true
command:
- bash
containerSecurityContext:
  allowPrivilegeEscalation: false
externalDatabase:
  database: keycloak
  host: euw1.postgres.database.azure.com
  password: ****
  user: ****
extraStartupArgs: -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled
extraVolumeMounts:
- mountPath: /opt/bitnami/keycloak/themes/test
  name: theme
- mountPath: /opt/bitnami/keycloak/themes/test-new
  name: theme-new
- mountPath: /opt/bitnami/keycloak/themes/test-design
  name: theme-design
- mountPath: /opt/bitnami/keycloak/themes/test-dashboard
  name: theme-dashboard
- mountPath: /opt/bitnami/keycloak/themes/test-cloud-dashboard
  name: theme-cloud-dashboard
- mountPath: /mnt/secrets-store
  name: secrets-store-inline
  readOnly: true
extraVolumes:
- emptyDir: {}
  name: theme
- emptyDir: {}
  name: theme-new
- emptyDir: {}
  name: theme-design
- emptyDir: {}
  name: theme-dashboard
- emptyDir: {}
  name: theme-cloud-dashboard
- csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: keyvault-csi-driver
  name: secrets-store-inline
global:
  imagePullSecrets:
  - regsecret
image:
  imagePullPolicy: IfNotPresent
  registry: coreshsacr.azurecr.io
  repository: image/bitnami/keycloak
  tag: 21.1.2-debian-11-r0-helm-15.1.6
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: ****
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    external-dns.alpha.kubernetes.io/target: 20.31.21.59
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: SecRuleEngine On
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
  enabled: true
  extraTls:
  - hosts:
    - ****
    secretName: keycloak.local-tls
  hostname: ****
initContainers:
- args:
  - -c
  - |
    echo "Copying theme..."
    cp -R /test/* /theme
    cp -R /test-new/* /theme-new
    cp -R /test-design/* /theme-design
    cp -R /test-dashboard/* /theme-dashboard
    cp -R /test-cloud-dashboard/* /theme-cloud-dashboard
  command:
  - sh
  image: ****
  imagePullPolicy: IfNotPresent
  name: theme-provider
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
  volumeMounts:
  - mountPath: /theme
    name: theme
  - mountPath: /theme-new
    name: theme-new
  - mountPath: /theme-design
    name: theme-design
  - mountPath: /theme-dashboard
    name: theme-dashboard
  - mountPath: /theme-cloud-dashboard
    name: theme-cloud-dashboard
nodeSelector:
  agentpool: nodepool
postgresql:
  enabled: false
proxyAddressForwarding: true
rbac:
  apiGroups:
  - ""
  create: true
  resources:
  - pods
  rules: null
  verbs:
  - get
  - list
replicaCount: "3"
service:
  type: ClusterIP
serviceAccount:
  create: true
  name: keycloak
```

Tried downgrading the version to 21.1.2 and it worked fine, able to load the admin console.
![image](https://github.com/keycloak/keycloak/assets/118261385/3c5c64d8-6fcf-453c-9a0b-0ababa1d3686)

But our intention is to run keycloak with 22.0.x version.

**Comment by Schaka** [comment] 2023-10-10 12:13
Could this be the issue?
https://github.com/keycloak/keycloak/issues/23822#issuecomment-1755254024

**Comment by sathishkumar3009** [comment] 2023-10-10 13:11
@Schaka - Post upgrading the version from 21.1.1 to 22.0.4, getting same exception. The UI page is not loading and unable to see master console or the login screen.

**Comment by kavinkvb** [comment] 2023-10-10 13:14
@Schaka @jonkoops - Facing similar of kind login issue after upgrading to helm version 22.0.x

**Comment by jonkoops** [comment] 2023-10-10 14:33
Please post a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), basically strip your configuration of anything aside for the bare minimum to reproduce this issue.

> Could this be the issue? [#23822 (comment)](https://github.com/keycloak/keycloak/issues/23822#issuecomment-1755254024)

Has anyone tried this? I have to agree with @Schaka that this is likely the issue. Please make sure that the request going to `step1.html` is actually correct in terms or URL.

**Comment by jonkoops** [comment] 2023-10-10 14:35
Also, please do not bump this thread with comments unless you have information to add that helps debug and resolve this issue. A simple :+1: on existing comments will suffice, otherwise we keep getting notified.

**Comment by jonkoops** [comment] 2023-10-10 15:52
I am closing this as a duplicate of #14666, where we collect issues related to the loading problems for the Admin Console. Feel free to continue discussion here or on that issue. This is mostly for our bookkeeping, as this same issue has been reported many times and we want to keep all the discussion related to this in the same place.

**Comment by jonkoops** [comment] 2023-10-10 15:52
Duplicate of #14666

**Closed by jonkoops** 2023-10-10 15:52 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by sathishkumar3009** [comment] 2023-10-10 16:06
> Please post a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), basically strip your configuration of anything aside for the bare minimum to reproduce this issue.

Posting Minimal Reproducible Sample:
1. Deploying it in AKS cluster.
2. Ingress-nginx is there in front.
3. helm install keycloak bitnami/keycloak --version=17.0.2 -f helmvalues.yml -n newkeycloak
4. Pods and everything are up and running.
5. Clicking on administrative console the screen remains loading and no response.

Note: Yet to try the one suggested by schaka

Helm Values:

auth:
  adminPassword: *****
  adminUser: test
  managementPassword: ****
  managementUser: *****
containerPorts:
  infinispan: 7800
extraStartupArgs: -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled
global:
  imagePullSecrets:
  - **secret
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
  enabled: true
  extraTls:
  - hosts:
    - keycloak.*.*.*.*
    secretName: keycloak-sbx-tls
  hostname: keycloak.*.*.*.*
  labels:
    app: keycloak
proxyAddressForwarding: true
service:
  type: ClusterIP

**Comment by jonkoops** [comment] 2023-10-14 12:43
@sathishkumar3009 I see you are using version `17.0.2` of `bitnami/keycloak`, which I assume is the equivalent version of Keycloak itsef. Are you able to reproduce this same issue with the latest version of Keycloak?
