### ISSUE TITLE
 Can't import the named export 'sha256' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by nehaWakalkar** [keycloak/keycloak#10647] opened 2022-03-08 12:03 UTC
### Describe the bug

Keycloak-js version : 17.0.0
Typescript version : 4.5.2
Graphql version : 15.6.1

Also tried with keycloak-js version 16.0.0 as well as 6.0.1

### Version

17.0.0

**Comment by jonkoops** [comment] 2022-03-10 09:29
Duplicate of #10314

**Closed by jonkoops** 2022-03-10 09:29 UTC
Labels: kind/bug, area/adapter/javascript, status/triage
