### ISSUE TITLE
AuthzClient getPermissions() deserializes to List<LinkedHashSet> and not List<Permission>

### ISSUE THREAD

**Issue by nschwalbe** [keycloak/keycloak#16520] opened 2023-01-18 13:17 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

Using the Java AuthzClient the `List<Permission> permissions = authorizationResource.getPermissions(authorizationRequest);` returns a list of `LinkedHashSet` and not a `List<Permission>`

This is because the type is not available at runtime and default deserialization of jackson is LinkedHashSet. Following line does not work for:

https://github.com/keycloak/keycloak/blob/5ddb79cbe6ae4bd591df81428139aa468d23ad24/authz/client/src/main/java/org/keycloak/authorization/client/resource/AuthorizationResource.java#L122

### Version

20.0.3

### Expected behavior

Expected is the List<Permission> deserializes to a list of Permission objects.

### Actual behavior

List<Permission> contains a list of LinkedHashSet.

### How to Reproduce?

```
            AuthorizationResource authorizationResource = authClient.authorization(token);

            AuthorizationRequest authorizationRequest = new AuthorizationRequest();
            authorizationRequest.setAudience(audience);
            authorizationRequest.setScope("read");
            AuthorizationRequest.Metadata metadata = new AuthorizationRequest.Metadata();
            metadata.setResponseMode("permissions");
            authorizationRequest.setMetadata(metadata);

            List<Permission> permissions = authorizationResource.getPermissions(authorizationRequest);
```

**Comment by mposolda** [comment] 2023-04-04 09:57
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by borislucas-dev** [comment] 2023-04-04 12:52
Hi,
I just checked, and yes it still occurs with keycloak-authz-client 21.0.2.
I can also confirm that it is definitely a deserialization bug in authz client, introduced in version 20.0.

**Comment by pedroigor** [comment] 2024-03-04 18:39
It should be fixed now as per https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AuthorizationAPITest.java#L190.

**Comment by clezag** [comment] 2024-03-12 13:01
I've opened a PR to fix this.

The test mentioned [here](#issuecomment-1977223854)  did not catch it, because due to type erasure, the return type was in effect List<Object>, which the test was still valid with.

**Closed** 2024-03-18 19:04 UTC
Labels: area/authorization-services, kind/bug, status/out-of-date, team/core-iam, status/auto-expire, status/expired-by-bot
