### ISSUE TITLE
Support for OpenJDK 21

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#26152] opened 2024-01-12 09:49 UTC
### Description

Blocked-by: https://github.com/keycloak/keycloak/issues/26150

JDK21 support has been included in Quarkus since the 3.5.0 version. After upgrading Quarkus, we should make Keycloak support it as well.

**Comment by vmuzikar** [comment] 2024-05-16 12:50
Duplicate of #28517

**Closed by vmuzikar** 2024-05-16 12:50 UTC
Labels: area/core, area/dist/quarkus, team/cloud-native, kind/task, team/continuous-testing, team/core-shared
