### ISSUE TITLE
When update-email feature is enabled, changing emails two times in a row causes unintuitive behaviour

### ISSUE THREAD

**Issue by taminomara** [keycloak/keycloak#19555] opened 2023-04-05 14:15 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

When update-email feature is enabled, updating user email for the first time works as expected. When trying to update email second time in a row, clicking 'change user email' redirects to a page that says "You are already logged in."

### Version

21.0.2

### Expected behavior

User gets a message with verification link. Following the link changes user's email.

### Actual behavior

User sees message "You are already logged in."

### How to Reproduce?

1. Run keycloak with `KC_FEATURES=update-email`, enable email verification in realm settings, enable "Update email" in "authentication/required actions", configure SMTP server.
2. Open a user console, click 'change user email' and proceed as usual.
3. After successfully changing user email, open user console and click 'change user email' once again.
4. If requested, enter user's current password.

**Comment by jsorah** [comment] 2023-05-18 19:44
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.  
It will be helpful if:

-   You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
-   If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
-   If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
-   If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here [https://www.keycloak.org/community](https://www.keycloak.org/community) for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by mposolda** [comment] 2023-10-11 12:17
@taminomara I am closing as I am not able to reproduce with latest Keycloak 22.0.4 and also not able to reproduce with latest Keycloak main. It is possible that this is already resolved by some other changes in the meantime. Please re-open if you are still able to reproduce the issue. In that case, please try to clarify steps to reproduce a bit more as I am not able to reproduce based just on the steps, which you provided.

**Closed by mposolda** 2023-10-11 12:17 UTC
Labels: area/authentication, kind/bug, team/core
