### ISSUE TITLE
Docs: server_admin/topics/overview.adoc

### ISSUE THREAD

**Issue by espinal1976** [keycloak/keycloak#29435] opened 2024-05-10 00:45 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

File: server_admin/topics/overview.adoc

Clicking on Register on the login screen on Keycloak 24.0.3 and 24.0.4 trows:  

We are sorry
Unexpected error when handling authentication request to identity provider.

### Version

24.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

  

Register link should open a form asking for the username, last name, userid and password.

### Actual behavior

Clicking on Register on the login screen on Keycloak 24.0.3 and 24.0.4 trows:  

We are sorry
Unexpected error when handling authentication request to identity provider.

On There server log, I got: 
2024-05-10 00:13:58,381 WARN  [org.keycloak.events] (executor-thread-21) type="REGISTER_ERROR", realmId="738ea455-d2eb-4784-b0f9-29a1ab536a0d", clientId="security-admin-console", userId="null", ipAddress="67.8.27.141", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="https://idtest.itksoluciones.com:8445/admin/master/console/", code_id="699267c9-45a0-4dc1-92ec-87880e214fff"
2024-05-10 00:31:00,290 WARN  [org.keycloak.services] (executor-thread-21) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.authentication.FormAction.buildPage(org.keycloak.authentication.FormContext, org.keycloak.forms.login.LoginFormsProvider)" because "action" is null
	at org.keycloak.authentication.FormAuthenticationFlow.renderForm(FormAuthenticationFlow.java:304)
	at org.keycloak.authentication.FormAuthenticationFlow.processFlow(FormAuthenticationFlow.java:285)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:377)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1051)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:892)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:367)
	at org.keycloak.services.resources.LoginActionsService.processRegistration(LoginActionsService.java:725)
	at org.keycloak.services.resources.LoginActionsService.registerRequest(LoginActionsService.java:781)
	at org.keycloak.services.resources.LoginActionsService.registerPage(LoginActionsService.java:742)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$registerPage_4790ee1a00c5ff439df8d9f43fc42809e1831abf.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

2024-05-10 00:31:00,292 WARN  [org.keycloak.events] (executor-thread-21) type="REGISTER_ERROR", realmId="738ea455-d2eb-4784-b0f9-29a1ab536a0d", clientId="security-admin-console", userId="null", ipAddress="67.8.27.141", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="https://idtest.itksoluciones.com:8445/admin/master/console/#/master/realm-settings/login", code_id="e39f91d2-3f4f-403a-b08e-0f1abdff8955"

### How to Reproduce?

Download keycloak 24.0.4, run it, the go to Master realm, turn User registration On in Master Realm. the go and clic Register in teh login form. 

### Anything else?

It was working ok in keycloak 22.0.1

**Comment by rmartinc** [comment] 2024-05-10 15:02
I cannot reproduce this. I have just download 24.0.4, unzipped it, run in develompemnt, activate user registration, logout and click register. The page is correctly shown as expected. Can you please elaborate how we can test this?

**Comment by espinal1976** [comment] 2024-05-10 15:25
Thanks a lot. 
So it has to be related to my own configuration. 

Could you please suggest what to check in my configuration?, which could lead to this?

I have reproduced the issue with master realm where I have changed almost nothing. 

Please noticed I have enabled preview features, because I need token-exchange for social login. And token exchange needs fine-grained-admin-permissions.

I will proceed to disable those and let you know if the error persist in a few minutes.

Att, 

John A. Espinal A.

**Comment by rmartinc** [comment] 2024-05-10 17:51
It's the other way around. Start with vanilla, do your changes and, when you find the issue, you have the reproducer steps you can share with us.

**Comment by espinal1976** [comment] 2024-05-11 20:24
After more than 16 hours searching I could not find anything.

So this is what I did:

I have production environment running on 22.0.1 with NO problem with Self Registration.
I stopped keycloak 22.0.1
Copy db keycloak22 to Keycloak240004 
Downloaded Keycloak24.0.4
Uncompress. 
Configure it and run it to migrate the database by   

./kc.sh start --spi-connections-liquibase-default-index-creation-threshold=300000 

Then the problem was reproduced.

So it seems the migration get the registration BROKEN.

All details in the next recording:

https://vimeo.com/945354228/8ad303f168?share=copy￼
20240511-MigratingToKeycloak24-MakeAutoRegistrationBroken
vimeo.com

Thanks for any suggestion.

Please notice that tests were done with MASTER REALM so this seems a bug.



P.D. I am migrating because Facebook disable the login with them because we do not have the privacy police before the login screen. I was able to download the login.ftl and template.ftl and do that minor change successfully on the login screen. BUT WHEN I move those two files to 22.0.1 the server GET broken.  Could you please indicate where can I find login.ftl and template.ftl for the 22.0.1 version.


Att, 


John A. Espinal A.
Gerente.

**Comment by rmartinc** [comment] 2024-05-13 07:39
Can you please share with us the registration flow you are using in the old version? You can do a partial export of the realm and then just copy the flow you are using for registration.

**Comment by espinal1976** [comment] 2024-05-13 14:06
is this what you mean?

kc.sh export -dir ../export

￼￼

Please remember that we are reproducing the failure in master realm, master real is generally untouched, I just remember to have changed To allow Self Registration so we can test.  All other parameters are with the original defaults.  I have been migrating the db since keycloak 19. 

Att, 



John A.

**Comment by rmartinc** [comment] 2024-05-13 14:30
You can just export using the console, select the realm affected, click Realm settings, and in the Action combo, click Partial export (groups, roles and clients not needed). If you have concerns sharing everything we are just interested in authenticationFlows section. I'm just trying to have the same config you have, because the error seems related to a missing form.

**Comment by espinal1976** [comment] 2024-05-13 15:03
I have already shared everything. I have no problem with data privacy because this is testing environment.

Any way I have follow the instructions.

MASTERL


￼

￼







Att,

**Comment by espinal1976** [comment] 2024-05-13 15:30
sure: [backauth-realm-export.json](https://github.com/keycloak/keycloak/files/15296764/backauth-realm-export.json)
[master-realm-export.json](https://github.com/keycloak/keycloak/files/15296765/master-realm-export.json)

Please advice if you got two files.

**Comment by rmartinc** [comment] 2024-05-14 08:00
Hi @espinal1976!

I have imported your json export in keycloak 22.0.1 and migrated the DB to 24.0.3 (mariadb) and I cannot reproduce your issue. My feeling is that the problem you are seeing is because the removal of the action `registration-profile-action` which was done in version 23.0.0. But I tested it and the [migration task](https://github.com/keycloak/keycloak/blob/24.0.4/model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java#L98-L110) is correctly removing that action from the registration, so I don't really know what is happening in your env.

You can check if the action is still in your 24 environment checking the registration flow (Authentication -> Flows -> Registration), probably this will fail if the action is still there. In the database you can also do `select * from AUTHENTICATION_EXECUTION where AUTHENTICATOR='registration-profile-action';`. If you see a row in the different realms the migration was incorrect (don't know why) and the removed action is still present in them triggering your issue.

If that's the error please try to remember how you did the upgrade and if it's something we can reproduce.

**Comment by espinal1976** [comment] 2024-05-14 11:18
Ricardo, This info is very valuable. 

When I go to Authentication in Master Realm I find:

Registration (Built-in) Registration Flow.

When I click on it I got in the screen:

Network response was not OK.

Press here to refresh and continue

in server log I got:

2024-05-14 10:55:07,908 WARN  [org.keycloak.services.resources.admin.AuthenticationManagementResource] (executor-thread-17) Cannot find authentication provider implementation with provider ID 'registration-profile-action'
2024-05-14 10:55:27,210 WARN  [org.keycloak.services.resources.admin.AuthenticationManagementResource] (executor-thread-18) Cannot find authentication provider implementation with provider ID 'registration-profile-action'
2024-05-14 10:55:40,575 WARN  [org.keycloak.services.resources.admin.AuthenticationManagementResource] (executor-thread-17) Cannot find authentication provider implementation with provider ID 'registration-profile-action'

When I run   select * from AUTHENTICATION_EXECUTION where AUTHENTICATOR='registration-profile-action’;

I got two records. I suppose one for the realm  Master and the other for the other realm.

How can I proceed to remove this option?

When clicking on the three dots the only option is Duplicate.

Should I stop Keycloak and delete those two records  from the database? Please advice. 

I do not want to brake anything.

Att, 


John A. Espinal A.
Gerente

**Comment by rmartinc** [comment] 2024-05-14 13:14
The problem with this is that we don't know how much data is incorrect. You have to check why the upgrade was not executed. The DATABASECHANGELOG contains information about the migration you can check. I would try to migrate again from the previous version until the upgrade is OK.

You can try deleting the rows at database level and restart. But you can never be sure that there are not going to be more issues.

**Comment by espinal1976** [comment] 2024-05-14 13:55
Thanks Ricardo. 

I still have the production environment in 22.0.1.

I still have testing environment in 22.0.1 

I can do full export of this testing environment. I can send you a tar package with all the DB. I can even give you user and password to a copy of the DB, so you can run the upgrade yourself. 

Let me know which one could be help more.

Att, 


John A. Espinal A.
Gerente

**Comment by rmartinc** [comment] 2024-05-16 15:14
@espinal1976 We are not going to do the upgrade for you. As commented, I uploaded your export in a 22 version, upgraded to 24 and everything worked OK for me. Just try the upgrade again (in another test environment or similar) and check if the step is removed or not from the registration flow.

In general, I cannot reproduce your issue. In all my upgrade attempts, the realm was correctly updated and the registration flow didn't have the `registration-profile-action` step.

**Comment by rmartinc** [comment] 2024-06-03 09:02
I'm closing this as there was no more interaction. As commented the issue was not reproducible. The registration step was correctly removed in the upgrade process. Please re-open or file a new issue if needed.

**Closed by rmartinc** 2024-06-03 09:02 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients

**Comment by espinal1976** [comment] 2024-06-29 16:37
Please reopen this case. 

I need to migrate production environment now. 

So which step should I change in the migration?

In described the steps done in previous comment. 

Att, 

John A. Espinal A.

**Comment by espinal1976** [comment] 2024-07-01 20:14
Please close this case. 

I have done several testing with keycloak 24.0.5 and problem was NOT REPRODUCED.

Ricardo you feedback helped us a lot, since it allowed us to patch it and continue developing. Thanks a lot!

Att, 


John A. Espinal A.
Gerente
