### ISSUE TITLE
Microsoft cert is expired in IDP, however SSO keycloack  still works. is there any reason why it is working

### ISSUE THREAD

**Issue by DREGALLA** [keycloak/keycloak#25718] opened 2023-12-20 07:16 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

https://faq.miniorange.com/knowledgebase/how-to-renew-upgrade-sp-certificate-in-the-saml-sso-plugin-with-keycloak-as-idp/
The above link suggests to replace the cert only when ‘Encrypt Assertion’ and ‘Client Signature Required’ is set ‘ON’
we don’t have these specific settings above under the SAML config menu in keycloak 6.0.  Also the link mentioned where we can import an encryption key and signing key.
But, on Key-cloak version 6.0.0 packaged with AADS,  the ‘Keys’ tab  is not available under the Client >> AADS Menu
It seems that we are not enabling SAML assertion encryption by default on Key-cloak.
Is this the reason why SAML SSO continues working although the cert has expired?

Is this fixed in the keycloak version 22 ?

### Version

22

### Expected behavior

If the certificate expired sso will not work

### Actual behavior

After expiring the cert SSO is still working

### How to Reproduce?

Microsoft cert is expired in IDP, however SSO keycloack  still works. is there any reason why it is working

**Comment by BagalDipti** [comment] 2023-12-26 13:27
Any updates from keycloak side??

**Comment by rmartinc** [comment] 2024-03-05 10:23
@DREGALLA You are using a extremely old version of keycloak (6.0 is from 2019). If you have `Client signature required` to OFF and `Encrypt assertions`to OFF you are not using any client certificate. So it doesn't matter the status of the certificate. It is specially important to enable signatures at both sides for SAML (`Client signature required` for client and `Sign documents` for server). Those options are enabled by default to ON since long ago in keycloak and they need interchanging certificates between client and server. I don't know if there was any issue in keycloak 6.0 but in keycloak 24 you always have the `keys` tab to configure client certificates. The client [certificate is always checked for expiration](https://github.com/keycloak/keycloak/blob/24.0.1/services/src/main/java/org/keycloak/protocol/saml/SamlProtocolUtils.java#L134) before using it to verify signature or encrypt assertion.

I'm closing this one, and please don't use github issues for these type of questions (use better the google [user group](https://groups.google.com/g/keycloak-user)). In general github issues are for code bugs that can be reproduced in the last version of keycloak. Never for questions.

**Closed by rmartinc** 2024-03-05 10:23 UTC
Labels: area/saml, kind/bug, status/triage, team/core-clients
