### ISSUE TITLE
Clarify if JGroups thread metrics can be shown with embedded Infinispan

### ISSUE THREAD

**Issue by sschu** [keycloak/keycloak#31218] opened 2024-07-11 13:14 UTC
### Background:
https://www.keycloak.org/high-availability/concepts-threads#_jgroups_connection_pool suggests to watch the metric `vendor_jgroups_tcp_get_thread_pool_size_active` to check the ratio compared to the Quarkus threads. However, this metrics is not shown for the embedded Infinispan even after enabling cache statistics. 

### Task:

1. Find out if this metric can be enabled for embedded Infinispan.
2. If yes, enable it if Keycloak metrics are enabled.
3. If no, adapt documentation to state these metrics are only available with external Infinispan.

**Comment by sschu** [comment] 2024-07-11 13:15
@ahus1 I created this as a task because I am not sure these metrics can be enabled with embedded Infinispan.

**Comment by pruivo** [comment] 2024-07-11 16:38
@ahus1 what do you mean it is not there? I've accessed the OpenShift cluster right now and it is there:

![Screenshot from 2024-07-11 17-36-51](https://github.com/keycloak/keycloak/assets/1492066/138e69d7-067b-43d9-8327-f2413fc695d7)

@sschu hey! What version are you using? Do you see any `vendor_jgroups_` prefixed metrics?

**Comment by sschu** [comment] 2024-07-11 17:00
@pruivo I used KC25.0.1 with a custom cache-config file to enable statistics. I am not sure this is needed since Infinispan cache metrics are all prefixed with `vendor_statistics_`. Would you expect the jgroups metrics to be shown with a simple `docker run -p 8080:8080 -p 9000:9000  -e KC_METRICS_ENABLED=true -e KC_HEALTH_ENABLED=true -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.1 start-dev`? Because I don't see them - but maybe there is just a config switch I am missing.

**Comment by pruivo** [comment] 2024-07-11 17:08
@sschu `start-dev` does not start a cluster. In other words, JGroups is not instantiated and started, so the metrics are not there :)

**Comment by sschu** [comment] 2024-07-11 17:11
@pruivo Also not when I do `docker run -p 8080:8080 -p 9000:9000  -e KC_METRICS_ENABLED=true -e KC_HEALTH_ENABLED=true -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_CACHE_CONFIG_FILE=cache-ispn.xml quay.io/keycloak/keycloak:25.0.1 start-dev`? The log says Infinispan is started, still the metrics are not there.

**Comment by pruivo** [comment] 2024-07-11 17:11
A bit more context, `start-dev` starts a non-clustered Infinispan. It uses the following configuration file by default: https://github.com/keycloak/keycloak/blob/2da37542e8c9d42c1d169ac42c61d55b9ec6749e/quarkus/runtime/src/main/resources/cache-local.xml

It is possible to change to a clustered Infinispan using the option `--cache-config-file=cache-ispn.xml` or provide a custom Infinispan configuration file. 

The `start` command will use https://github.com/keycloak/keycloak/blob/2da37542e8c9d42c1d169ac42c61d55b9ec6749e/quarkus/runtime/src/main/resources/cache-ispn.xml

**Comment by ahus1** [comment] 2024-07-11 17:12
I tested it locally and I can reproduce it as follows: 

If the cache-stack is specified, the metric is there. If there is no cache-stack there is no JGroup metric.
If I don't specify a cache-stack, at least the docs state that it would used UDP.

```
# JGroup metric present
bin/kc.sh --verbose start --http-enabled true --hostname-strict false \
--cache-stack tcp \
--health-enabled true --metrics-enabled true
```

```
# No JGroup metric present
bin/kc.sh --verbose start --http-enabled true --hostname-strict false \
--health-enabled true --metrics-enabled true
```

**Comment by ahus1** [comment] 2024-07-11 17:23
> what do you mean it is not there? I've accessed the OpenShift cluster right now and it is there:

@pruivo - sorry, I missed it it earlier in our OpenShift deployment. I now found it in the Infinispan dashboard. 
Still, as described in my previous comment, the metric seems to only be available when a cache-stack is specified.

**Comment by sschu** [comment] 2024-07-11 17:32
It's also not there with `--cache-stack=kubernetes` because that's what we are normally using.

**Comment by pruivo** [comment] 2024-07-11 17:40
Thanks @ahus1
I've created https://issues.redhat.com/browse/ISPN-16287 as a minor priority since there is a workaround. Using the `--cache-stack` works and that's good enough for all use cases.

@sschu Using a cache-stack works for me. This is my command
```
podman run --rm -p 8080:8080 -p 9000:9000  -e KC_METRICS_ENABLED=true -e KC_HEALTH_ENABLED=true -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_CACHE_CONFIG_FILE=cache-ispn.xml -e KC_CACHE_STACK=kubernetes -e jgroups.dns.query=localhost quay.io/keycloak/keycloak:25.0.1 start-dev
```
```
$ curl -s http://127.0.0.1:9000/metrics | grep vendor_jgroups | head -n5
# TYPE vendor_jgroups_tcp_get_num_msgs_sent gauge
# HELP vendor_jgroups_tcp_get_num_msgs_sent Number of messages sent (mcasts and ucasts sent)
vendor_jgroups_tcp_get_num_msgs_sent{cache_manager="keycloak",cluster="ISPN",node="2ae20acc88c4-4319"} 34.0
# TYPE vendor_jgroups_tcp_get_number_of_thread_dumps gauge
# HELP vendor_jgroups_tcp_get_number_of_thread_dumps Number of thread dumps
```

**Comment by sschu** [comment] 2024-07-11 17:51
I can confirm that it works, I didn't know the nice trick to specify `localhost` as dns query to run it locally so I only saw it in prod. There we are still on KC23 and the metric seems to be there since KC24. I guess its fine to close this task now or should we leave it open?

And thanks a lot for your help here! @ahus1 @pruivo

**Comment by ahus1** [comment] 2024-07-11 18:08
In KC23, the metric is called `vendor_jgroups_ISPN_tcp_get_thread_pool_size_active`. 

IMHO we need to keep this issue open as the issue Pedro opened is unlikely to be fixed in ISPN 15.0 which will be used in KC 26.0. 

So IMHO the workaround needs to be described in the docs with at least a short comment like "This metric is available when a cache stack is set", or we update the Keycloak code to always set the default parameter, assuming the default is `udp`? Always setting the default transport stack would be IMHO more user friendly. 

Independent on which option we choose above, I realize that the option will be named differently if you used `udp` as the `tcp` is part of the current metric's name.

**Comment by pruivo** [comment] 2024-07-11 18:30
@sschu you're welcome
@ahus1 since KC 26 will become RHKB, I don't think we can update the Infinispan version for KC 26. 

We can add `stack="udp"` to the `<transport>` [tag](https://github.com/keycloak/keycloak/blob/2da37542e8c9d42c1d169ac42c61d55b9ec6749e/quarkus/runtime/src/main/resources/cache-ispn.xml#L25). It should keep the default behavior of starting JGroups with UDP and should register metrics.

**Comment by ahus1** [comment] 2024-07-11 18:55
+1 for this. Please create a PR and double check if my assumption that `udp` is the default really holds. Please also give it a go with the docs. I'm happy to extend the docs as necessary next week.

**Closed** 2024-07-16 10:05 UTC
Labels: kind/bug, help wanted, team/cross-dc, backport/24.0, status/auto-bump, priority/normal, backport/25.0

**Comment by sschu** [comment] 2024-07-16 11:50
Thanks @ahus1 @pruivo !
