### ISSUE TITLE
admin console still loadgin

### ISSUE THREAD

**Issue by kotlil** [keycloak/keycloak#25027] opened 2023-11-26 17:00 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

this is my basic log:

URL | Value
-- | --
Request | http://192.168.0.188:8080/realms/master/hostname-debug
Frontend | http://mykeycloak:8989 [FAILED]
Backend | http://mykeycloak:8989 [FAILED]
Admin | http://192.168.0.188:8080/ [OK]

Server mode | production [start]
Realm | master

hostname-url | http://mykeycloak:8989
hostname-strict | true
hostname-strict-backchannel | true
hostname-strict-https | false
hostname-port | -1
proxy | edge
http-enabled | enabled
http-relative-path | /
http-port | 8080
https-port | 8443

Host | 192.168.0.188:8080

### Version

keycloak-22.0.5

### Expected behavior

i would like to see admin page 

### Actual behavior

page is still loadin

### How to Reproduce?

just start server in production...
this is my configuration:

# Basic settings for running in production. Change accordingly before deploying>

# Database

# The database vendor.
db=mysql

# The username of the database user.
db-username=root

# The password of the database user.
db-password=keycloak

# The full database JDBC URL. If not provided, a default URL is set based on th>
db-url=jdbc:mariadb://localhost:3306/mysql

# Observability

# If the server should expose healthcheck endpoints.
health-enabled=true

# If the server should expose metrics endpoints.
metrics-enabled=true

# HTTP

# http-port=8080

# HTTPS:
# https-client-auth=request

# The file path to a server certificate or certificate chain in PEM format.
https-certificate-file=${kc.home.dir}/conf/certificate.pem

# The file path to a private key in PEM format.
https-certificate-key-file=${kc.home.dir}/conf/key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities >
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
# hostname=keycloak

# log
log-console-color=true

# database
db=mariadb

# hostname: https://www.keycloak.org/server/hostname

#hostname-admin=http//localhost:8080/admin

#hostname-admin-url=http://localhost:8080/keycloak

hostname-debug=true

hostname=keycloak

# hostname-url=http://mykeycloak:8080

hostname-strict-https=false

hostname-strict-backchannel=true

proxy=edge

feature="admin-api,admin2,authorization,account-api"

### Anything else?

nothing special

**Comment by jonkoops** [comment] 2023-11-26 17:06
Duplicate of #14666

**Closed by jonkoops** 2023-11-26 17:06 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
