### ISSUE TITLE
keycloak.js example from the documentation leads to error path

### ISSUE THREAD

**Issue by ioah86** [keycloak/keycloak#8935] opened 2021-11-26 23:19 UTC
### Describe the bug

When I tried to implement the example from [the documentation](https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter), namely

```
<html>
<head>
    <script src="keycloak.js"></script>
    <script>
        function initKeycloak() {
            var keycloak = new Keycloak();
            keycloak.init().then(function(authenticated) {
                alert(authenticated ? 'authenticated' : 'not authenticated');
            }).catch(function() {
                alert('failed to initialize');
            });
        }
    </script>
</head>
<body onload="initKeycloak()">
    <!-- your page content goes here -->
</body>
</html>
```

I consistently reached the "failed to initialize" alert.

When printing out the error code, it was coming from [this line](https://github.com/keycloak/keycloak/blob/main/adapters/oidc/js/src/main/resources/keycloak.js#L1361). Upon further debugging, it appears that the variable `kc.messageReceiveTimeout` is null, while the default timeout is supposed to be 10000. Studying the initialization, I came to the conclusion that it never gets initialized [here](https://github.com/keycloak/keycloak/blob/main/adapters/oidc/js/src/main/resources/keycloak.js#L199-L203), since [this if-condition](https://github.com/keycloak/keycloak/blob/main/adapters/oidc/js/src/main/resources/keycloak.js#L122) will not be fulfilled if init is not called with a non-empty options parameter. But that is what is being done in the example from the documentation.

So, this is an issue of default parameters not being initialized (or the documentation needs fixing; your team's call ;-))

### Version

15.0.1

### Expected behavior

I would have expected that default values are set no matter what is passed to the init function.

### Actual behavior

As mentioned in the description, my code is reaching the `catch` statement.

### How to Reproduce?

Just use your example as is from the documentation, point it to an OIDC configured client, and you should be able to reproduce.

**Comment by FlyveHest** [comment] 2022-04-01 18:27
I can confirm that this is still an issue in 17.0.1, doing thit

`keycloak.init({messageReceiveTimeout: 10000});`

lets you actually progress using the javascript adapter. (Its still not working here, but it looks like a configuration problem on my end now :)

**Comment by pelepelin** [comment] 2024-02-22 01:08
Still an issue with keycloak-js@23.

With `keycloak.init({})` the default `messageReceiveTimeout` is properly set to 10000 ms but with `keycloak.init()` it's effectively 0.

This line 
https://github.com/keycloak/keycloak/blob/5e34769ee04c76723befcec625289075b1dd199c/js/libs/keycloak-js/src/keycloak.js#L167
is never executed in the latter case because of this
https://github.com/keycloak/keycloak/blob/5e34769ee04c76723befcec625289075b1dd199c/js/libs/keycloak-js/src/keycloak.js#L75

Looking at the code, there are more options which suffer from the same problem.

**Comment by jonkoops** [comment] 2024-02-22 14:40
Feel free to submit a fix for this, we'll accept PRs.

**Comment by ioah86** [comment] 2024-04-09 17:28
Will do.

**Comment by jonkoops** [comment] 2024-09-17 14:57
Re-opening this issue so that we don't lose track of it.

**Comment by jonkoops** [comment] 2024-10-10 10:38
I am unable to reproduce this issue, so I will assume it has been fixed since. If someone is able to reproduce this using the latest version of Keycloak and Keycloak JS (26.0.0 at time of writing) please report a new issue with steps to reproduce.

**Comment by jonkoops** [comment] 2024-10-15 11:14
@ioah86 thanks for getting back to me. Upon doing some closer investigation not providing the argument actually breaks things in a different way that I missed in my testing, I am going to re-open this issue.

**Closed** 2024-10-15 15:46 UTC
Labels: kind/bug, area/adapter/javascript, team/core-clients, priority/normal, backport/26.0

**Comment by FlyveHest** [comment] 2024-11-11 10:14
@mVirat22 Please read the changelog, https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-javascript-adapter-now-standalone

Your issue is not related to this at all.
