### ISSUE TITLE
Cannot edit username if you have "email as username" set. 

### ISSUE THREAD

**Issue by rjsoph** [keycloak/keycloak#33360] opened 2024-09-27 23:24 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If you set the "email as username" realm option, you can turn on "edit username" but it does not work.  You cannot update your username.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

I have a use case where the users are required to have a verified email, but optionally they can choose to also setup a separate username.   If the username is setup it should be available for use during login, of course they can also always use their email during login.  

### Actual behavior

If I turn off the "email as username" option, it seems this make me setup a unique username for every user, one that is not their email.

### How to Reproduce?

You can view this behavior in the admin UI.  Be toggling the options and then trying to create and update users.... it also affects the APIs as I get "Bad Request" if I don't provide both email and username when the "email as username" option is off and I cannot set the username to the email as a workaround.  If I have email as username turned on, the api ignores my username updates.

### Anything else?

I think one possible implementation is to allow "email as username" to be set and have it set the username to the email address if a separate username is not provided.  Then if "edit username" is turned on, it should allow you to modify the email address to something other than the email.

**Comment by jonkoops** [comment] 2024-09-28 10:04
Did you try the latest patch version of Keycloak 25?

**Comment by rjsoph** [comment] 2024-09-28 23:03
I just tried with 25.0.6.  The username update via api does not give error but username does not change even though I have edit turned on.  I have a user whose username is different on the users page than it is on user detail?

**Comment by rjsoph** [comment] 2024-09-29 20:37
There seem to be two different issues here when "Use Email as Username" is set with "Edit Username".  1) The User detail screen does not reflect the actual username (it always shows email as username) even if there is a different username set.  The Users list page show it properly.   2) the second issue is that you cannot actually edit the username when "Email as Username" is set.  You cannot edit it via the admin apis (ignores the update) and you cannot edit it via the Admin UI (username is read-only input box).    I did confirm that when the username is set (on the user list screen) it can be used to login even though user detail does not show it.   Maybe this should be two different bugs?  I don't know.

**Comment by rjsoph** [comment] 2024-09-29 20:41
A question for the api team.... assuming we resolve the above issues and I want to unset the username, do I need to set it to the email or can I set it to null when both "Use Email as Username" and "Edit Username" are set?

**Comment by codespearhead** [comment] 2024-09-29 22:45
It seems to be a regression of [1] (fixed by [2]), which was working in v22.0.4 [3], but reappeared around v25.0.0 [4].

[1] https://github.com/keycloak/keycloak/issues/13988
[2] https://github.com/keycloak/keycloak/pull/15583
[3] https://github.com/keycloak/keycloak/issues/13988#issuecomment-1775707499
[4] https://github.com/keycloak/keycloak/issues/13988#issuecomment-2196553475

**Comment by pedroigor** [comment] 2024-10-01 13:49
When you set `email as username` the `username` field is disabled you cannot update the field directly/manually. The server will make sure to update the `username` of a user whenever you are updating that user. AFAIK, that is the behavior we have since we introduced the `email as username` flag.

When you enable `email as username`, users are not automatically updated to have their usernames as the email. That will happen once you create/update the user.

**Comment by rjsoph** [comment] 2024-10-02 03:04
> When you set `email as username` the `username` field is disabled you cannot update the field directly/manually. The server will make sure to update the `username` of a user whenever you are updating that user. AFAIK, that is the behavior we have since we introduced the `email as username` flag.
> 
> When you enable `email as username`, users are not automatically updated to have their usernames as the email. That will happen once you create/update the user.

You seem to be saying the 'email as username' and the 'edit username' options are mutually exclusive.   I would ask then why does the realm settings page let you turn both on?  What are we to assume that would allow?

Lack of information to reproduce?  LOL.... then explain what "edit username" does when "email as username" is set?  Are you able to edit the username?  If not, then what is the purpose of the option?

**Comment by pedroigor** [comment] 2024-10-02 11:03
> You seem to be saying the 'email as username' and the 'edit username' options are mutually exclusive.

They are not. When you turn on `email as username` the `username` field will be managed by the server so that updating the user will automatically set the field with the value from the `email` field. That is why the `username` field is disabled and you can update it.

When you turn on `edit username` your users will be able to update their usernames. If you have `email as username` enabled that means your users will be able to update their e-mails (the `email` attribute only) hence their username. If `email as username` is disabled, your users won't be able to update their email (as a consequence their username).

You can check this behavior by looking at the account console.

From an administration perspective, the `edit username` will have an effect only on the `username` field no mather how `email as username` is set. As an administrator you are always able to change the user's email.

These flags are confusing and especially confusing when you take into account the permissions in the user profile configuration. The permissions in the user profile configuration are basically ignored for both `username` and `email` fields.

**Comment by rjsoph** [comment] 2024-10-02 14:34
You are correct that the UI options and the "expected" behavior is confusing......  one would expect "edit username" option to allow you to edit the username and not force you to do so by editing the email address.... but maybe that is just me.

Am I correct in saying that keycloak cannot support a requirement to require a verified email and allow username as an optional field (this seems to me to be a common use case)?  That if you choose "email as username" you lose the ability to update the two independently.   If you do not choose "email as username" then you must always specify two distinct unique values for both?

**Comment by pedroigor** [comment] 2024-10-03 14:20
Thanks. Perhaps you can create an issue with more details about your use case and see if we can solve it more easily. I think the original query was answered (?) and we are discussing something else. Works for you?

> Am I correct in saying that keycloak cannot support a requirement to require a verified email and allow username as an optional field (this seems to me to be a common use case)? That if you choose "email as username" you lose the ability to update the two independently. If you do not choose "email as username" then you must always specify two distinct unique values for both (cannot make username optional)?

Not sure how common is the use case, but not OOTB. Only the e-mail can be optional by either not setting `email as username` or making the attribute as required in the user profile settings. The username is always a required field as per design.

We have support for email verification. See https://www.keycloak.org/docs/latest/server_admin/#con-required-actions_server_administration_guide.

**Closed** 2024-10-17 15:04 UTC
Labels: kind/bug, area/admin/ui, team/core-iam, status/auto-expire, status/expired-by-bot
