### ISSUE TITLE
Selection list does not close after outside click

### ISSUE THREAD

**Issue by CSalih** [keycloak/keycloak#31415] opened 2024-07-18 14:47 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The selection list component remains open after a user clicks outside. This behavior causes a weird issue, as the dropdown does not close as expected, multiple other selection list elements are opened at the same time.

![image](https://github.com/user-attachments/assets/22876463-d1a2-47c7-8f22-7f3f001e0db7)

### Version

25.0.0 - 25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

When a user clicks outside of the selection list or selects an option from the list, the selection list should close automatically.

### Actual behavior

The selection list remains open even after a user clicks outside. Users need to manually click on the component again to close it.

### How to Reproduce?

1. Goto Admin Console (http://localhost:8080/admin/master/console/)
2. Goto Realm Settings > Themes (http://localhost:8080/admin/master/console/#/master/realm-settings/themes)
3. Click on any selection list e.g. "Select email theme"
4. Click on an different selection list e.g. "Select admin theme"

Note that any selection list has this issue not just in themes.

**Comment by ssilvert** [comment] 2024-07-18 19:16
@CSalih Thanks for reporting.  This appears to be a duplicate of https://github.com/keycloak/keycloak/issues/31166.

**Comment by CSalih** [comment] 2024-10-10 13:49
@ssilvert #31166 appears to fix "remain open after selecting an action/entry," but the issue where dropdown/select fields close after an outside click still exists in v26.

Could we reopen this issue to address this problem?

**Closed** 2024-10-25 13:21 UTC
Labels: kind/bug, area/admin/ui, help wanted, team/ui, status/auto-expire, status/auto-bump, priority/normal
