### ISSUE TITLE
reCAPTCHA v3 not working

### ISSUE THREAD

**Issue by TheoCadoret** [keycloak/keycloak#35232] opened 2024-11-22 11:16 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

reCAPTCHA V3 toggle in authentication/registration flow does not seem to be working. 

It always uses reCAPTCHA v2

With v2 keys configured : 
- V3 not toggled =>  It works and shows a v2 captcha checkbox
- V3 toggled =>  It works and shows a v2 captcha checkbox

With v3 keys configured : 
- V3 not toggled =>  It does not work and shows `ERROR for site owner: Invalid key type`
- V3 toggled =>  It does not work and shows `ERROR for site owner: Invalid key type`

### Version

26.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Invisible reCAPTCHA

### Actual behavior

![image](https://github.com/user-attachments/assets/4e50d4f6-5eaa-485a-9d9a-0926473c8abd)

Text being : ERROR for site owner: Invalid key type

### How to Reproduce?

Follow steps in https://www.keycloak.org/getting-started/getting-started-docker
=> Allow user registration on the realm

Add reCAPTCHA v3 (Google): 
- authentication/registration flow captcha required
- add v3 keys
- toggle v3 

Realm settings / Security defense 
![image](https://github.com/user-attachments/assets/3a92d5e8-97a9-4b2d-81fa-0350b3d109eb)

Try to register using `https://www.keycloak.org/app/`

Then you get 

![image](https://github.com/user-attachments/assets/b2620c90-7b30-4445-a221-4d2bfa6e684b)

**Comment by jonkoops** [comment] 2024-11-22 12:14
@derlin would you be willing to chime in on this one?

**Comment by derlin** [comment] 2024-11-22 14:27
hello @TheoCadoret and thank you for the report.

The choice between v2 and v3 is determined the key itself. If the key works for v2, it means it is configured to use a checkbox-based recaptcha (v2) and is thus not compatible with invisible recaptcha (v3). The toggle in Keycloak is there because there is no way to know how the key way created in the Google Console.

Can you please try creating a key supporting v3 (invisible recaptcha) and try again with the toggle on in Keycloak?

See https://cloud.google.com/recaptcha/docs/create-key-website for a good guide on how to create each type of key, and let me know if you still encounter an issue.

**Comment by TheoCadoret** [comment] 2024-11-22 15:01
Hi @derlin, as mentioned in the bug description, I've tried it with both v2 and v3 keys.

>With v2 keys configured :
V3 not toggled => It works and shows a v2 captcha checkbox
V3 toggled => It works and shows a v2 captcha checkbox
With v3 keys configured :
V3 not toggled => It does not work and shows ERROR for site owner: Invalid key type
V3 toggled => It does not work and shows ERROR for site owner: Invalid key type

Did you try the reproducer ?
Following this reproducer, I could not make it work, but I'm no expert and might be missing something.

**Comment by derlin** [comment] 2024-11-22 15:22
Sorry @TheoCadoret , I should have read better. I just tried the following (on a local keycloak 25.0.6 instance):

1. create a key using https://www.google.com/recaptcha/admin/create (score-based)
2. enable the ReCAPTCHA on the register flow
3. configure it with key+secret+v3 toggle on

Which worked, but got the same problem as you in keycloak 26.0.6. @jonkoops seems to be a regression.

**Comment by TheoCadoret** [comment] 2024-11-22 15:26
All right, thanks @derlin for the quick reply 🙏 
I'll wait for the fix to implement it.

**Comment by derlin** [comment] 2024-11-22 15:39
@jonkoops  I just checked and nothing changed on the recaptcha code.

It seems the toggle doesn't update the default `recaptcha.v3` property (which is `v2`) on the latest versions, however the other boolean toggle (use recaptcha.net) works, which is super strange. I may have a look, but my initial hint is that the issue is outside of my area (not directly linked to recaptcha, more about passing properties around from config to templates).

**Comment by jonkoops** [comment] 2024-11-22 16:08
If this is a regression, which is the oldest Keycloak version that this still worked in? If I am understanding you correctly this value is not properly persisted when changed in the admin console, right? This could possibly be related to changes made by @keycloak/ui, but I am not sure.

**Comment by derlin** [comment] 2024-11-22 16:43
Heven't had time to investigate more unfortunately.

**Comment by jonkoops** [comment] 2024-11-28 22:13
@yanxch if you configure the `v1` theme in the realm settings does it work then?

**Comment by yanxch** [comment] 2024-11-29 07:12
@jonkoops correct, explicitly setting the login theme to `keycloak` is working

**Comment by jonkoops** [comment] 2024-11-29 07:52
Great, thanks for taking this one on. I'll assign it to you :+1:

**Closed** 2024-12-02 11:12 UTC
Labels: kind/bug, priority/important, help wanted, area/login/ui, team/core-clients, status/bumped-by-bot, backport/26.0

**Comment by jonkoops** [comment] 2024-12-02 11:15
Thanks for the fix @yanxch, I've created a backport for 26.x under #35492
