### ISSUE TITLE
Facing issue when container running on K8S

### ISSUE THREAD

**Issue by guptakaran27** [keycloak/keycloak#21616] opened 2023-07-12 04:04 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I am unable to start the Keycloak in a K8s container and getting the following error - 
`Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /opt/keycloak/lib/quarkus/build-system.properties
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.AccessDeniedException: /opt/keycloak/lib/quarkus/build-system.properties
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at io.quarkus.bootstrap.util.IoUtils.createOrEmptyDir(IoUtils.java:114)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:596)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:221)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        ... 6 moreERROR: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /opt/keycloak/lib/quarkus/build-system.properties
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.AccessDeniedException: /opt/keycloak/lib/quarkus/build-system.properties
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at io.quarkus.bootstrap.util.IoUtils.createOrEmptyDir(IoUtils.java:114)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:596)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:221)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        ... 6 moreERROR: java.nio.file.AccessDeniedException: /opt/keycloak/lib/quarkus/build-system.properties
ERROR: /opt/keycloak/lib/quarkus/build-system.properties
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.`

I have tried providing both **rwx** and **rx** permissions to the file mentioned in logs **opt/keycloak/lib/quarkus/build-system.properties**

### Version

21.0.2

### Expected behavior

Keycloak container should come up in K8s

### Actual behavior

Container failing to come up in K8s

### How to Reproduce?

Try building the Keycloak docker image and running in K8s clusters

**Comment by guptakaran27** [comment] 2023-07-17 04:07
Hi Team, any update on this ?

**Comment by vmuzikar** [comment] 2023-07-21 09:52
Thanks for reporting this and sorry you are facing issues with Keycloak.

Could you please provide as detailed steps to reproduce as possible? That would help us significantly with investigating the issue. Without it we are unable to reproduce, unfortunately.  I'm going to close this for now but feel free to reopen when you are able to provide more details.

**Closed by vmuzikar** 2023-07-21 09:52 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage

**Comment by arunksalian** [comment] 2023-11-28 03:10
I am facing same issue as well while deploying in k8 cluster. I have given full permissions to those files.

 Docker file
=====
FROM quay.io/keycloak/keycloak:20.0 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN ls /opt/keycloak/lib/quarkus/
RUN chmod -R 777 /opt/keycloak/lib/quarkus/*
RUN ls -l /opt/keycloak/lib/quarkus/

RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build



#COPY ./keycloak-custom-providers-0.1.0-SNAPSHOT.jar /opt/keycloak/providers/
#RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:20.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

USER root
RUN chmod -R 777 /opt/keycloak/lib/quarkus/*

RUN ls -l /opt/keycloak/lib/quarkus/
RUN ls /home/



# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://dev-slbpgpool.dev.jp.local:9999/keycloak
ENV KC_DB_USERNAME=beauty
ENV KC_DB_PASSWORD=beauty
ENV KC_HOSTNAME=localhost
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=change_me
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
======

**Comment by DaHoC** [comment] 2024-10-15 11:37
Same issue, for me the change causing this behavior is to run the container using a different "user", for instance with following docker-compose.yml:

```
services:
  test-keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: test-keycloak
    hostname: test-keycloak
    user: 8888:3150
    restart: on-failure
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --verbose 
    ports:
      - "8080:8080"
```

I could assume the `AccessDeniedException` is due to insufficient permissions of that user.
I also could not find which uid/gid values are valid for Keycloak after a quick search
