### ISSUE TITLE
User-Profile Feature: Add support for multivalue user profile attributes

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#19606] opened 2023-04-08 19:09 UTC
### Description

Follow up of https://github.com/keycloak/keycloak/issues/19578

Currently user attributes could contain a list of values for each key. This functionality is lost when using the user profile with the new user details screen (the api still allows multiple values for each user attributes key though)

The new user details ui in the admin console renders the inputs according to the settings in the user profile and currently does not offer any possibility to enter multiple values for an attribute. It would be nice if a user profile attribute could be configured to support multiple values.

### Motivation

Some user profile attributes might contain multiple values, requiring e.g. a workaround with seperators if those could only be stored in one string. Having the possibility to add multiple values to one attribute (like it was with the attribute tab before) would be nice.

### Details

Multiple steps would be required:

1. Backend functionality would have to be added (store if the attribute is multivalued),
2. The user profile configuration screen would have to be adapted (checkbox for multivalued) and
3. The user details, account and registration screens would need to be adapted (enabling input of multiple values if the attribute is multivalued)

**Comment by jonkoops** [comment] 2023-09-28 14:20
Closing this as we already have this covered under #23539

**Comment by jonkoops** [comment] 2023-09-28 14:21
Duplicate of #23539

**Closed** 2023-09-28 14:27 UTC
Labels: kind/enhancement, area/user-profile, team/core, team/ui
