### ISSUE TITLE
getting error in maven clean install

### ISSUE THREAD

**Issue by shivamBrahmbhatt-zycus** [keycloak/keycloak#22997] opened 2023-09-06 08:32 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dependencies

### Describe the bug

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm-install) on project keycloak-js-parent: Failed to run task: 'pnpm install --frozen-lockfile --ignore-scripts' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

### Version

22.0.1

### Expected behavior

Build will execute successfull.

### Actual behavior

I am trying to build keycloak project which I have downloaded from Assests.

### How to Reproduce?

run mvn clean install and try to execute build.

### Anything else?

no

**Comment by vmuzikar** [comment] 2023-09-08 16:02
Seems more related to building our UI stuff.

**Comment by jonkoops** [comment] 2023-09-11 11:00
Duplicate of #22580

**Comment by ssilvert** [comment] 2023-09-13 18:34
@shivamBrahmbhatt-zycus I'm going to close this as it is a duplicate of #22580.

I was never able to re-create the problem, but apparently, there is a workaround.

**Closed by ssilvert** 2023-09-13 18:34 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
