### ISSUE TITLE
Cannot modify realm email settings since keycloak 24

### ISSUE THREAD

**Issue by Romain7495** [keycloak/keycloak#27611] opened 2024-03-06 14:55 UTC
NOTE: This issue describes 2 independent bugs.

- The part related with authentication flows was fixed by other issue #23980 .
- The part related to "email settings" configuration is related to user profile. I am leaving this issue related only to email configuration (user profile) and hence moving component to user-profile as the part related to "authentication flows" was addressed by #23980 .

### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Original description 

I cannot configure Authentication flow and Realm email settings in Admin UI

I have the error since migration from `23.0.7` to `24.0.0` then `24.0.1`.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Being able to Configure Authentication flow on `https://{domain}/admin/master/console/#/{realm}/authentication`
![image](https://github.com/keycloak/keycloak/assets/15386726/27d28dc3-f26a-46f3-a154-3c8bb7ea6422)

And being able to configure email on realm settings on `https://{domain}/admin/master/console/#/{realm}/realm-settings/email`
![image](https://github.com/keycloak/keycloak/assets/15386726/578e069d-cf3b-4503-902e-e33cdbf7597c)

Screenshot on `23.0.7` keycloak instance

### Actual behavior

**For Authentication flow tab, I have this error:**
```2024-03-06 10:18:38,383 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-8) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticationFlowModel.getAlias()" because "f" is null```

**For Email settings, I have:**
```2024-03-06 09:58:11,809 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-63) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.userprofile.config.UPConfig.getGroups()" because "config" is null```

For Email settings, it works on master realm, but not on custom realm

**Corresponding screenshots on `24.0.1` are:** 

![image](https://github.com/keycloak/keycloak/assets/15386726/c762da64-e6a3-4c93-93d0-b7dd0addfc7a)
and
![image](https://github.com/keycloak/keycloak/assets/15386726/6f573d64-67fc-45fe-afa8-fff47512e1a1)

### How to Reproduce?

- Deploy `23.0.7` keycloak instance
- Migrate to `24.0.0` or `24.0.1`
- Observe issue on https://<keycloakDomain>/admin/master/console/#/{realm}/authentication and on `https://{domain}/admin/master/console/#/{realm}/realm-settings/email`

### Anything else?

This issue seems to be related https://github.com/keycloak/keycloak/issues/23980

**Comment by rmartinc** [comment] 2024-03-08 12:02
This is because of #25823, the first login flow is null in the realm and there is a NPE.I think that this is fixed by https://github.com/keycloak/keycloak/pull/27630 provided by @shawkins for #23980. I'm reviewing the PR now.

**Comment by rmartinc** [comment] 2024-03-08 12:07
As a workaround you can add the flow using kcadm:

```
./kcadm.sh update -r <realm_name> / -s "firstBrokerLoginFlow=first broker login"
```

**Comment by Romain7495** [comment] 2024-03-08 13:40
Thank you @mposolda and all the team

**Comment by mposolda** [comment] 2024-03-08 13:44
@Romain7495 Could you please send here the JSON content of the user-profile configuration of some realms where you are seeing the issue with email?

When you are going in admin console to "Realm settings" -> "User profile" -> "JSON editor" . Are you able to see `"groups": []` at the end of this JSON?

Just to doublecheck: When you create new realm in 24.0.1, are you able to edit email in such realm (I guess yes as the `"groups": []` would be present. Could you please confirm?

**Comment by Romain7495** [comment] 2024-03-08 13:55
@mposolda 

- existing realm that is not working on Email tab : 
```  "groups": [
    {
      "name": "user-metadata",
      "displayHeader": "User metadata",
      "displayDescription": "Attributes, which refer to user metadata"
    }
  ]
  ```
  
  - new realm
  ```
    "groups": [
    {
      "name": "user-metadata",
      "displayHeader": "User metadata",
      "displayDescription": "Attributes, which refer to user metadata"
    }
  ```

Conclusion:

for both existing realm (not working) ans new freshly created realm (working well), the user-profile config is strictly the same: 

```
{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {},
        "up-username-not-idn-homograph": {}
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "email",
      "displayName": "${email}",
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "firstName",
      "displayName": "${firstName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "lastName",
      "displayName": "${lastName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    }
  ],
  "groups": [
    {
      "name": "user-metadata",
      "displayHeader": "User metadata",
      "displayDescription": "Attributes, which refer to user metadata"
    }
  ]
}
```

**Comment by rmartinc** [comment] 2024-03-08 13:58
@Romain7495 Do you have the complete exception on the email problem? To see what line is giving the error...

**Comment by Romain7495** [comment] 2024-03-08 14:00
Sure @rmartinc, I was capturing it:

```
2024-03-08 13:56:24,384 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-50) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.userprofile.config.UPConfig.getGroups()" because "config" is null
    at org.keycloak.userprofile.config.UPConfigUtils.validateAttributes(UPConfigUtils.java:128)
    at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
    at org.keycloak.userprofile.DeclarativeUserProfileProvider.createUserProfile(DeclarativeUserProfileProvider.java:138)
    at org.keycloak.services.resources.admin.UserResource.getUser(UserResource.java:313)
    at org.keycloak.services.resources.admin.UserResource$quarkusrestinvoker$getUser_7e789726117d7cfd3ef1d9ddd01596d8e6add5b0.invoke(Unknown Source)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by pedroigor** [comment] 2024-03-08 14:22
@Romain7495 Regarding the email issue. If you can debug the server, it would help a lot of you can check two things:

* When updating the email settings, add a breakpoint at https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java#L219. Then, check the return of `UPConfig.getGroups`.
* The add a breakpoint to https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java#L127. The, check if the  `UPConfig.getGroups` returns the same value there.

As we can't reproduce here, your findings should help to figure out what is going on.

**Comment by rmartinc** [comment] 2024-03-08 14:40
It's like the UP config is null when getting the admin user to get the email. Can you please login with the kcadm command and paste the output for this command?

```
./kcadm.sh get components -r <realm_name> -q type=org.keycloak.userprofile.UserProfileProvider
```

**Comment by pedroigor** [comment] 2024-03-08 14:52
@Romain7495 Did you have enabled `User Profile Enabled` settings in your realm before?

**Comment by Romain7495** [comment] 2024-03-08 15:09
@pedroigor you mean the `declarative-user-profile` preview feature (in previous version) ? 
I never enabled it 

Custom Dockerfile
```
ENV KC_FEATURES=token-exchange,account3
RUN /opt/keycloak/bin/kc.sh build
```

**Comment by pedroigor** [comment] 2024-03-08 15:11
@Romain7495 I see. If you can check this https://github.com/keycloak/keycloak/issues/27611#issuecomment-1985811606 it should help too.

**Comment by Romain7495** [comment] 2024-03-08 15:18
@pedroigor @rmartinc 
for `./bin/kcadm.sh get components -r internal -q type=org.keycloak.userprofile.UserProfileProvider`, I have:
```[ {
  "id" : "ff276239-da11-436f-88d4-2dc0054ad25f",
  "providerId" : "declarative-user-profile",
  "providerType" : "org.keycloak.userprofile.UserProfileProvider",
  "parentId" : "595a49be-2a76-406c-8b77-552d3f597108",
  "config" : { }
} ]```

**Comment by Romain7495** [comment] 2024-03-08 15:22
![image](https://github.com/keycloak/keycloak/assets/15386726/6dbd7ac7-0782-46c7-9140-19f2893614e7)

internal = existing realm that is not working
test2 = new freshly created realm that is working
master = working as excepted

**Comment by pedroigor** [comment] 2024-03-08 15:22
What is the realm? `master` ?

**Comment by Romain7495** [comment] 2024-03-08 15:22
@pedroigor the realm that is not working is `internal`

**Comment by pedroigor** [comment] 2024-03-08 15:24
Thanks. That realm should be migrated and a configuration should be set to it when you are upgrading to 24. The key here now is understand why it wasn't migrated.

Can you also check if there is a realm attribute for the `internal` realm with a name `userProfileEnabled`?

**Comment by Romain7495** [comment] 2024-03-08 15:28
If I underndand the question, no

![image](https://github.com/keycloak/keycloak/assets/15386726/ca2a031e-6a4f-41c8-93f4-9049c206f8d6)

**Comment by pedroigor** [comment] 2024-03-08 15:30
Sorry, I meant the realm attributes and not the user attributes in the UP :)

**Comment by pedroigor** [comment] 2024-03-08 15:31
Also, if you just click save on that page. It should be enough to update the component and workaround the issue. Can you check?

**Comment by Romain7495** [comment] 2024-03-08 15:35
Sorry but I don't know where to find  a realm attribute

**Comment by Romain7495** [comment] 2024-03-08 18:29
Thanks @pedroigor, I checked and I have nothing named `userProfileEnabled ` in `REALM_ATTRIBUTE` table for `internal` cluster

Example for the request:
```
SELECT * FROM public.realm_attribute WHERE realm_id = '595a49be-2a76-406c-8b77-552d3f597108' AND  name = 'userProfileEnabled'
```

I did this request for `master`, `internal` and the newly `test2` realm that works and all result are empty
 
Thanks for the explanation and of course for your time

**Comment by Romain7495** [comment] 2024-03-08 18:33
> Also, if you just click save on that page. It should be enough to update the component and workaround the issue. Can you check?

I did that as a workaround, it works, thanks a lot

**Closed** 2024-03-11 12:01 UTC
Labels: kind/bug, priority/blocker, area/user-profile, team/core-iam, backport/24.0, kind/regression
