### ISSUE TITLE
Internal server error when resetting password after logging in

### ISSUE THREAD

**Issue by marc-weber1** [keycloak/keycloak#29989] opened 2024-05-29 20:44 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Page redirects to internal server error after resetting password if you are logged in already

### Version

24.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

It should not throw an error

### Actual behavior

It throws an error:
```
2024-05-29 20:29:45,367 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-10) Uncaught server error: java.lang.IllegalArgumentException: uri parameter is null
        at org.keycloak.common.util.KeycloakUriBuilder.uri(KeycloakUriBuilder.java:184)
        at org.keycloak.common.util.KeycloakUriBuilder.fromUri(KeycloakUriBuilder.java:55)
        at org.keycloak.protocol.oidc.utils.OIDCRedirectUriBuilder.fromUri(OIDCRedirectUriBuilder.java:57)
        at org.keycloak.protocol.oidc.OIDCLoginProtocol.authenticated(OIDCLoginProtocol.java:216)
        at org.keycloak.services.managers.AuthenticationManager.redirectAfterSuccessfulFlow(AuthenticationManager.java:931)
        at org.keycloak.services.managers.AuthenticationManager.redirectAfterSuccessfulFlow(AuthenticationManager.java:879)
        at org.keycloak.services.managers.AuthenticationManager.finishedRequiredActions(AuthenticationManager.java:1032)
        at org.keycloak.authentication.AuthenticationProcessor.authenticationComplete(AuthenticationProcessor.java:1157)
        at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:894)
        at org.keycloak.authentication.AuthenticationProcessor.handleBrowserException(AuthenticationProcessor.java:812)
        at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:373)
        at org.keycloak.services.resources.LoginActionsService.processResetCredentials(LoginActionsService.java:720)
        at org.keycloak.services.resources.LoginActionsService.resetCredentials(LoginActionsService.java:514)
        at org.keycloak.services.resources.LoginActionsService.resetCredentialsPOST(LoginActionsService.java:410)
        at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$resetCredentialsPOST_766bcaa025254e5a31d91db82f14fc45b767f514.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to Reproduce?

- Sign in to a realm and client
- On the same browser, navigate to /realms/[realm]/login-actions/reset-credentials?client_id=[client] to enter in a username and reset the password

**Comment by rmartinc** [comment] 2024-05-30 11:39
Hi @marc-weber1!

Can you please try with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?

I remember something similar and probably was this issue #8887. So maybe this was fixed recently. If it works then it will be fixed in 25.0.0.

**Comment by marc-weber1** [comment] 2024-05-30 20:28
Looks like this issue in particular was fixed on nightly, but nightly has enough other issues that I can't use it right now - is there a timeline for 25.0? Or - is there a workaround to redirect to a different page after password reset?

**Comment by marc-weber1** [comment] 2024-05-30 22:32
Ended up with this in the theme:

```
    <script>
        document.getElementById('kc-reset-password-form').addEventListener('submit', function(event) {
            event.preventDefault(); // Prevent the form from submitting the traditional way

            // Create a new FormData object from the form
            var formData = new FormData(event.target);

            // Send a POST request using fetch
            fetch('${url.loginAction}', {
                method: 'POST',
                body: formData
            }).then(response => {
                document.getElementById('message').innerHTML = 'Email sent to reset password.';
            }).catch(error => {
                document.getElementById('message').innerHTML = 'An error occurred. Please try again.';
            });
        });
    </script>
```

**Comment by rmartinc** [comment] 2024-05-31 13:30
Nice you found a workaround for the issue using a theme.

The nightly build is the compilation of the main branch done every night (sometimes it can be skipped but normally it's done every night). If you have problems with the nightly build you can file new issues because they can reach the next version if we don't detect them before.

If this current issue is fixed in nightly we can close this issue as it's already fixed for the next version.

Duplicate of #8887.

**Closed by rmartinc** 2024-05-31 13:30 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients

**Comment by durcon** [comment] 2025-05-07 09:46
I have a similar problem:

```
2025-05-07 08:25:21.088	2025-05-07 06:25:21,086 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.lang.IllegalArgumentException: uri parameter is null
2025-05-07 08:25:21.088		at org.keycloak.common.util.KeycloakUriBuilder.uri(KeycloakUriBuilder.java:184)
2025-05-07 08:25:21.088		at org.keycloak.common.util.KeycloakUriBuilder.fromUri(KeycloakUriBuilder.java:55)
2025-05-07 08:25:21.088		at org.keycloak.protocol.oidc.utils.OIDCRedirectUriBuilder.fromUri(OIDCRedirectUriBuilder.java:57)
2025-05-07 08:25:21.088		at org.keycloak.protocol.oidc.OIDCLoginProtocol.buildErrorRedirectUri(OIDCLoginProtocol.java:375)
2025-05-07 08:25:21.088		at org.keycloak.protocol.oidc.OIDCLoginProtocol.sendError(OIDCLoginProtocol.java:425)
2025-05-07 08:25:21.088		at org.keycloak.services.resources.SessionCodeChecks.initialVerifyAuthSession(SessionCodeChecks.java:215)
2025-05-07 08:25:21.088		at org.keycloak.services.resources.LoginActionsService.restartSession(LoginActionsService.java:236)
2025-05-07 08:25:21.088		at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$restartSession_b017792629832a0e6da07393f2eab868a7201c64.invoke(Unknown Source)
2025-05-07 08:25:21.088		at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2025-05-07 08:25:21.088		at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2025-05-07 08:25:21.088		at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2025-05-07 08:25:21.088		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
2025-05-07 08:25:21.088		at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
2025-05-07 08:25:21.088		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
2025-05-07 08:25:21.088		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
2025-05-07 08:25:21.088		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
2025-05-07 08:25:21.088		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
2025-05-07 08:25:21.088		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2025-05-07 08:25:21.088		at java.base/java.lang.Thread.run(Thread.java:1583)
```

Does the problem have the same cause?

Keycloak version: 26.1.2

**Comment by soulchild** [comment] 2026-01-13 14:51
> I have a similar problem:

We're seeing this as well with Keycloak 26.4.2.
