### ISSUE TITLE
Attributes on parent group not visible in UI after upgrade

### ISSUE THREAD

**Issue by transducer** [keycloak/keycloak#23739] opened 2023-10-05 12:22 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

After upgrading to 22.0.4 from 21.0.2, attributes on a parent group are not visible in the UI, but they are visible in a user of that group's JWT and when calling the API.

This is not always the case, I think it only happens when the group with attributes is created in the version before the Quarkus upgrade.

### In UI:
![attributes via api visible not in ui](https://github.com/keycloak/keycloak/assets/5002921/532b9827-ddc4-43c2-a05b-f8ac40599d56)

As can be seen what does not help:
- Refreshing the page
- Clicking on another tab and back to attributes

### Getting attributes via API:
<img width="713" alt="Screenshot 2023-10-05 at 14 23 55" src="https://github.com/keycloak/keycloak/assets/5002921/582a2914-d797-4b2b-855d-e61e9208e0c0">

```sh
ACCESS_TOKEN=$(curl -s -X POST \
  "${LOGIN_HOST}/realms/${REALM}/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "client_id=${CLIENT_ID}" \
  -d "client_secret=${CLIENT_SECRET}" \
  -d "username=${USERNAME}" \
  -d "password=${PASSWORD}" \
  -d "grant_type=password" | jq --raw-output '.access_token')

curl "${LOGIN_HOST}/admin/realms/${REALM}/groups/347482f2-fa26-4c24-a2cf-ecf9b94f9871" \
  -H "Authorization: Bearer ${ACCESS_TOKEN}" | jq --raw-output '.attributes'
```

### Version

22.0.4

### Expected behavior

Attributes visible on parent group in UI

### Actual behavior

Attributes on the parent group are not visible in the UI. They are visible via the API and in the JWT.

### How to Reproduce?

- Set attributes on parent group in version before Quarkus (I think this is the culprit, I will have to confirm, groups later created do work)
- Upgrade to version 22.0.4
- Attributes in UI no longer visible

### Anything else?

Possibly related to, but not the same as other issues with attributes on group:

- https://github.com/keycloak/keycloak/issues/23654

**Comment by ssilvert** [comment] 2023-10-06 01:50
Looks like a bug in the migration code and not UI.  Sending to the core team.

**Comment by rmartinc** [comment] 2023-10-06 08:36
@transducer I have done the following:

* Installed keycloak 16.1.1 using the wildfly distribution.
* Created a demo realm and create two parent groups and three child groups:
```
  -> parent1
    -> child11
  -> parnet2
    -> child21
    -> child22
```
* Migrated to 22.0.4.
* I see OK the parent attributes in the console.

The only thing that I detected is, when I click in a parent group, the attributes tab is not refreshed. I have to click in another tab (for example members) and then Attributes again to refresh it. Check if that is your issue.

Another question, when you click back to the Attributes tab, open the web developers tool of your browser and check this request:

```
GET http://localhost:8080/admin/realms/demo/groups/e4e44afa-5aa7-41be-9045-90e280dbf031
{
    ...
    "attributes": {
        "parent1b": [
            "parent1b"
        ],
        "parent1a": [
            "parent1a"
        ]
    },
    ...
}
```

Do you see the attributes in the parent in the response like in my case?

**Comment by rmartinc** [comment] 2023-10-06 08:42
Using mariadb as database in my test. I have not said that.

**Comment by transducer** [comment] 2023-10-06 10:10
@rmartinc thanks very much for the reproduction attempt. Something else is going on then. We added the attributes initially at Keycloak 8.0.1 and are using PostgreSQL.

> The only thing that I detected is, when I click in a parent group, the attributes tab is not refreshed. 

This is another bug, namely https://github.com/keycloak/keycloak/issues/23654. In our case the attributes are never visible, also not after refresh or switching the tab.

>Another question, when you click back to the Attributes tab, open the web developers tool of your browser and check this request: Do you see the attributes in the parent in the response like in my case?

Yes, there the attributes are visible just like in your case.

**Comment by transducer** [comment] 2023-10-06 10:39
@rmartinc I think it's in the UI yes, maybe the fix for https://github.com/keycloak/keycloak/issues/23654 will solve this too.

**Comment by jonkoops** [comment] 2023-10-06 10:52
@transducer perhaps you can try out the fix under #23675 and let us know if it resolves this issue. If so we can link this issue to it and it should get resolved in the next patch release.

**Comment by transducer** [comment] 2023-10-09 09:04
@jonkoops we will check against our environment once the fix is released. For now we find it too time consuming to create our own custom build for this. Hopefully the release with the fix solves the issue, otherwise we will invest more time to diagnose and create a reproducer.

**Comment by jonkoops** [comment] 2023-10-24 16:18
We just released 20.0.5, which includes the aforementioned fix. Let us know if the problem persists.

**Comment by transducer** [comment] 2023-10-25 08:03
Thanks @jonkoops. Unfortunately the problem with invisible attributes on parent groups persists. In version 21.1.2 they are visible, but not in 22.0.5.

For some parent groups they are visible though, I will investigate what the difference is between those that do work and those that don't.

**Comment by jonkoops** [comment] 2023-10-25 08:44
Thanks for checking, since this has been identified as a UI regression (data is showing up in the API from what I gather), I will re-label this to the UI team, so we can triage the issue and assign an impact.

**Comment by transducer** [comment] 2023-10-25 17:41
@jonkoops thank you, I created a reproducer:

# Reproduction scenario

Attributes are no longer visible when creating multivalued attributes by duplicating attribute names with different values.

1. Create a group
1. Add an attribute "foo" with value "bar"
1. Switching tabs and page refreshes keeps the attribute visible
1. Add another attribute "foo" with value "baz"
1. Switching tabs and page refreshes do no longer display attributes
1. Remove one of the multivalued valued attribute from the database `delete from group_attribute where group_id = '<group id>' and id = '<id>'`
1. After a while when refreshing the page or switching tabs a single attribute is visible again.

![reproduction](https://github.com/keycloak/keycloak/assets/5002921/d5437948-4996-467d-9bbc-127213878b7b)

**Comment by transducer** [comment] 2023-10-25 17:56
For some other already existing groups the multivalued attributes do work. I don't see a difference in the group_attribute table, so the reason why my example with the new group and some other existing groups do not work must reside somewhere else.

**Comment by ssilvert** [comment] 2023-10-31 19:27
@transducer As far as I can tell, the nightly build is handling multi-valued group attributes correctly.  I'm not seeing anything disappear.

Can you give the nightly build a try?
https://github.com/keycloak/keycloak/releases/tag/nightly

Also, have we determined that this doesn't have anything to do with upgrades?

**Comment by transducer** [comment] 2023-11-01 09:32
@ssilvert I checked against latest nightly build and this no longer has this problem.

It had to do with upgrades in the sense that the problem did not occur in version 21.0.2. With the same database running 21.0.2 for us all the attributes are visible, but not in 22.0.5. But as said latest nightly does not have this problem. Hopefully the fix will also be available in next release.

Thanks for checking!

**Comment by jonkoops** [comment] 2023-11-01 09:37
@ssilvert considering this has been fixed in the nightly, and therefore the next major release, should we close this issue?

**Comment by ssilvert** [comment] 2023-11-01 18:27
> @ssilvert considering this has been fixed in the nightly, and therefore the next major release, should we close this issue?

Yes.

**Closed by ssilvert** 2023-11-01 18:27 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
