### ISSUE TITLE
query string repeated after login with keycloak 25 and angular integration

### ISSUE THREAD

**Issue by udayrachati** [keycloak/keycloak#31309] opened 2024-07-16 06:17 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

my web application uses KC 16  with angular and its working fine

I have upgraded  key claok  latest version 25.0.1  , its working fine  as individual

I am trying to integrate with web application which uses angular ,
its  shows login page and after login the query string repeated  like below

![KC25issue](https://github.com/user-attachments/assets/ed12532a-a7de-4b02-91d2-ef32ca5b8ee4)

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

should login sucessfully

### Actual behavior

not able to login

### How to Reproduce?
download and setup key cloak 25.0.1 
intergate with angular application
try to login to application
it shows login page provide credentials and click on login

upgrade keycloak to 25  and use angular integration

**Comment by sschu** [comment] 2024-07-16 06:26
You need to provide exact steps to reproduce the problem, otherwise we won't be able to help you.

**Comment by rmartinc** [comment] 2024-07-16 08:39
@udayrachati Your application seems to be in a redirect loop. But as @sschu mentions we need clear steps to reproduce this and check if it's a bug or not.

**Comment by udayrachati** [comment] 2024-07-16 08:44
> download and setup key cloak 25.0.1
> intergate with angular application
> try to login to application
> it shows login page provide credentials and click on login



> @udayrachati Your application seems to be in a redirect loop. But as @sschu mentions we need clear steps to reproduce this and check if it's a bug or not.

@rmartinc  steps are updated

**Comment by udayrachati** [comment] 2024-07-16 08:45
> You need to provide exact steps to reproduce the problem, otherwise we won't be able to help you.

@sschu steps are updated

**Comment by sschu** [comment] 2024-07-16 08:59
@udayrachati This is still by far not enough to reproduce it. I don't have your application. I don't know how the integration is configured between you app and Keycloak (e.g. client settings). Without that, I cannot recreate your problem locally. Currently, your best pointer is what @rmartinc mentioned, that you are stuck in a redirect loop. You can check the browser network tab to see if the first redirect you get gives you any hint on what is wrong.

**Comment by rmartinc** [comment] 2024-07-16 09:03
@udayrachati We need proper steps to reproduce. I did a extremely fast test with this angular 17 app https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards. Changed the file `src/app/core/auth-config.ts b/src/app/core/auth-config.ts` to point to my keycloak and it's working for me OK. This is probably something related to the integration between your app and the keycloak server, and we cannot reproduce it without specific details. If you think this is a bug, you need to add a little example of an angular app that does not work and explain us what's the problem.

**Comment by udayrachati** [comment] 2024-07-16 09:24
@sschu @rmartinc  Thanks for your reply  
 I am using angular 15 version 
 created  sample application ( other application has loop issue)
 i have verified   sample applicaction works fine till 24.0.2 version ,
 but its not working for 25.0.1
keycloak 25.0.1
![image](https://github.com/user-attachments/assets/056a8a9a-78d3-4466-b2dc-00b31e857667)

keycloak 24.0.2
![image](https://github.com/user-attachments/assets/350f8719-9aa4-450d-921c-1cb167a0e578)

do we need to change any configuration for Keycloak 25

**Comment by jonkoops** [comment] 2024-07-16 11:47
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) without any third party libraries that might intervene (such as Angular). Try to only use the latest version of Keycloak and related libraries such as Keycloak JS.

If you are looking for a basic web application to experiment in I [maintain a project](https://github.com/jonkoops/kjs-playground) you can fork that can be used to debug Keycloak JS for issues. We do not maintain or support Angular specific integrations.

**Comment by udayrachati** [comment] 2024-07-17 08:47
@sschu @rmartinc   Issues got resolved and thanks for reply

**Comment by rmartinc** [comment] 2024-07-17 09:07
Thanks @udayrachati! Closing the issue then.

**Closed by rmartinc** 2024-07-17 09:07 UTC
Labels: kind/bug, status/triage, area/login/ui, team/core-clients

**Comment by tuoiconan93** [comment] 2024-08-26 05:01
> @sschu @rmartinc Issues got resolved and thanks for reply

Hi, how to fix it

**Comment by jonkoops** [comment] 2024-09-12 14:31
If you are still experiencing issues please log a new issue that follows the steps outlined under https://github.com/keycloak/keycloak/issues/31309#issuecomment-2230691751
