### ISSUE TITLE
Keycloak.v2 theme account console throwing forbidden errors

### ISSUE THREAD

**Issue by yuyujiejie** [keycloak/keycloak#16234] opened 2023-01-04 08:28 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Cannot access account console if the theme is set to Keycloak.v2 with forbidden errors.
If set to Keycloak theme, works fine. 

### Version

20.0.1

### Expected behavior

Able to access account console

### Actual behavior

> Created realm
> changed theme to Keycloak.v2 for account console
> open account console in new tab

>shows forbidden

### How to Reproduce?

> Created realm
> changed theme to Keycloak.v2 for account console
> open account console in new tab

>shows forbidden
![image](https://user-images.githubusercontent.com/21055992/210514034-139d6ad0-4727-468c-bf37-07a396edc5be.jpg)

**Comment by sschu** [comment] 2023-01-04 09:51
Have you checked if your user has all the necessary roles of the `account` client?

**Comment by yuyujiejie** [comment] 2023-01-09 06:50
Yes it has all the account permissions.
Keycloak theme works while keycloak.v2 doesn't work.

**Comment by sschu** [comment] 2023-01-09 08:47
I cannot reproduce your problem. When I start a Keycloak 20.0.1 or 20.0.2 docker container and log in as default admin user, I can just go to the account console and everything works fine.

**Comment by ssilvert** [comment] 2023-02-17 19:47
@yuyujiejie I'm going to close this as I can't reproduce it either.  If you have some info that can help us reproduce then we can repoen.

**Closed by ssilvert** 2023-02-17 19:47 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui
