### ISSUE TITLE
Linux Firefox + Keycloak 22.0.1 issue(continuation of issue 21307)

### ISSUE THREAD

**Issue by ssill2** [keycloak/keycloak#22839] opened 2023-08-30 21:24 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

This is a follow-on to the issue described in #21307

I have a web application that has a react UI that does keycloak authentication against keycloak 21.1.2.   It was discovered that the same issue occurs on Firefox(Rocky9) but it seems primarily when the app is deployed on docker and the authentication is done against our staging instance of keycloak.  However, this morning my boss had the same issue using Safari while talking to the staging version of our application.  That application is deployed using k8s.  

It was suggested in #21307 that 22.0.x fixes the issue.  I deployed 22.0.1 to see if this in fact fixes it.
While it now gets to the app's landing page, after about 5 seconds it get booted back to before the login screen.  My app presents a page with a "Login" button it it.  click this triggers the whole auth process and afterwards sends it to the app's landing page.

![image](https://github.com/keycloak/keycloak/assets/25040169/9f2cf1eb-4e0f-4422-b35d-0470671143d6)

On Chromium(linux) this doesn't happen, and on Edge(windows) this doesn't happen either.

I have a java (wildfly + vaadin ) application that uses wildfly's oidc client and works fine and has the whole time.  The problem seems to be centered around the react app. 

### Version

22.0.1

### Expected behavior

The app being authenticated using keycloak should log in as normal.

### Actual behavior

The app landing page is pulled up but after about 5 seconds or so it's kicked out. 

### How to Reproduce?

This seems to be particular this one react application, and only with this Firefox on linux and Safari

I thought maybe it was because the app still had keycloak-js 19.0.1 dependency it's package.json.   I cleared out node_modules and changed this dep to be 22.0.1 to agree with latest keycloak release.  no change. 

### Anything else?

everything worked fine in this configuration before update to 21.x + of keycloak, 20.0.x worked great.

**Comment by ssill2** [comment] 2023-08-31 12:48
This is a fully patched Rocky 9 host.   The version of the firefox rpm is 102.14.0-2.el9_2

**Comment by ssill2** [comment] 2023-08-31 13:47
what's frustrating is I can bring up the same app deployed locally in FF and Chromium side by side.  Chromium works just fine, but FF, after about 5 seconds, kicks back to the screen with the login button after having displayed the same landing page that chrome stays on.

**Comment by jonkoops** [comment] 2023-09-01 11:26
> This is a fully patched Rocky 9 host. The version of the firefox rpm is 102.14.0-2.el9_2

@ssill2 is this still reproducible in the latest version of Firefox for you?

**Comment by ssill2** [comment] 2023-09-01 11:30
I'm using the firefox that comes with rocky 9, and is updated via yum.   Give me a few minutes and I'll spin up the application again and verify again.   it did this as recently as yesterday.

**Comment by ssill2** [comment] 2023-09-01 11:46
I just did a "yum update --refresh"  and there were no updates.  so that firefox package is the latest available for rocky 9.
![image](https://github.com/keycloak/keycloak/assets/25040169/87d57260-4dca-404f-83a7-c2e0c07d0cbc)

I just verified the behavior is the same.   visit url,   Simple page with a "login" button is displayed.  Clicking this gives the keycloak login form.  Entering credentials and hitting enter takes me to my app's landing page.  Then after 5 seconds, I'm booted back to the page with "login" button, even though I have a valid keycloak session. and I know it's valid because if I open my other java + vaadin app that uses the same realm, I'm taken directly in because of SSO.

When the page is redirected back to my "login" page I see this in javascript console
![image](https://github.com/keycloak/keycloak/assets/25040169/d030a886-6cb0-4689-9739-ced3cb6ff8db)

**Comment by jonkoops** [comment] 2023-09-01 11:48
Aside from what is available on Rocky Linux, the latest version of Firefox is 116, is the problem reproducible there as well?

**Comment by ssill2** [comment] 2023-09-01 11:50
let me see if I can test from the windows side, or get a newer firefox on the linux side.   I don't have a good way to test if the safari issue my boss was having is addressed with 22.0.1 as well without deploying 22.0.1 to our staging keycloak.    one thing at a time though.

**Comment by ssill2** [comment] 2023-09-01 11:52
I'm pulling 117 from mozilla directly, so let's see how that works.

**Comment by ssill2** [comment] 2023-09-01 11:58
ok, so that fails too, but more messages in javascript console
![image](https://github.com/keycloak/keycloak/assets/25040169/607d0aca-3a78-4777-a8ba-f6093cd75914)

I'm starting to think this could because in my dev environment I'm not using TLS for my app or keycloak.

**Comment by ssill2** [comment] 2023-09-01 12:01
my java + wildfly + vaadin app that also uses keycloak for auth(using oidc-client in wildfly) works just fine regardless

**Comment by ssill2** [comment] 2023-09-01 12:03
if this is a dev only problem because of lack of TLS, I'm less concerned since that's not how it's configured in staging and prod for us since it's in GCP behind an ingress that gets a real cert and ip address/hostname

**Comment by jonkoops** [comment] 2023-09-02 11:25
@ssill2 I have [this repo](https://github.com/jonkoops/kjs-playground) I use for testing locally with fake TLS, perhaps it might help reproduce it?

**Comment by ssill2** [comment] 2023-09-02 12:50
let me dig into this on tuesday after the long weekend.  Thanks

**Comment by ssill2** [comment] 2023-09-03 13:09
ok, I think your repo recreates the issue.  I followed the instructions exactly.  I did have to edit the line in my /etc/hosts file that mapped localhost and localhost.localdomain to ::1 since it was getting a connection refused.
A quick run of netstat showed me that 5173 was only listening on v6

I just edited this line in my /etc/hosts
`::1         localhost localdomain localhost6 localhost6.localdomain6`
to be
`::1         localhost6 localhost6.localdomain6`

Once I did this I reran the steps on latest FF 117 and things all came up.

In your playground app I hit login and it says user is logged in and then after 5 seoncs it says the user isn't authenticated.  Exactly what I'm seeing in my app, but in my case when the user isn't authenticated it sends them back to login page.
Here's a screenshot

![image](https://github.com/keycloak/keycloak/assets/25040169/e21224da-4cac-4256-88f2-1a1bfe194b34)

**Comment by jonkoops** [comment] 2023-09-04 10:22
I am actually able to reproduce this in the aforementioned test project. This seems like a pretty critical one, so I am marking this for the next patch release (we might even want to do a release just for this fix).

**Comment by ssill2** [comment] 2023-09-04 12:29
that's great news!    Thanks!

**Comment by ssill2** [comment] 2023-09-04 12:34
I'll be interested to see if this also fixes safari.  I don't have a mac to try your test project on though.

**Comment by edewit** [comment] 2023-09-05 06:11
So it's the update token, looking in the console it seems it results in a status 400 because just before the token is updated the refresh token gets cleared as well

**Comment by ssill2** [comment] 2023-09-05 11:56
I'm you're able to reproduce it.  That's first step in fixing for sure.

**Comment by edewit** [comment] 2023-09-08 12:18
Okay we found out what the cause of the problem is, firefox has a strange implementation of `requestStorageAccess`, because as it needs can only be called from user interaction. We might have to work around this by adding a "firefox" specific check

**Comment by ssill2** [comment] 2023-09-08 12:23
I would definitely see if you can try this in safari too.   as 21.1.2 was having exactly the same issue as FF in our production deployed keycloak.  The difference from 21.1.2 -> 22.0.1 was that 22.0.1 could at least get into the app before being kicked out.   I've not installed 22.0.1 to our staging our prod so I can't test safari locally like I can FF.

**Comment by jonkoops** [comment] 2023-09-08 14:57
I think the 'real' solution here is to do what the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API/Using#checking_and_requesting_storage_access) state:

> We first use feature detection (`if (document.hasStorageAccess) {}`) to check whether the API is supported. If not, we run our code that accesses cookies anyway, and hope that it works. **It should be coded defensively to deal with such eventualities anyway.**

Essentially, what is being said here is that we always need a fallback to deal with the fact that the cookies might just randomly not be there. It seems that at least in Firefox (and [probably also Safari](https://github.com/privacycg/storage-access/issues/3)) cannot reliably tell us that 3rd-party cookies are supported.

Also, access to these cookies is granted on a per frame basis, which means that we could have one iframe with access and another not, making it required to ask for permission for each frame.

This essentially means that we will just have to work on a 'best effort' approach. We will try to set the cookie and signal support, even when it might be incorrect. Then if the Silent SSO fails due to a missing cookie, we will instead fall back to the redirect flow.

The same would go for the session status iframe, if a cookie is not detected we will simply pretend the session status never changed.

**Comment by dominiktopp** [comment] 2023-09-18 09:35
I think I have kind of a workaround.
We have the same problem and reading the docs about [Storage Access API][(https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API)) I stumbled on [Security measures](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API#security_measures) bullet 5.

Testing locally I inserted "allow-storage-access-by-user-activation" in keycloak.js in node_modules (where my local environment loads keycloak.js from) to all iFrames with sandbox attribute.
After that everything seems to work fine.

**Comment by jonkoops** [comment] 2023-09-20 08:00
We're working on a fix for this, but it needs to be verified against all possible variations of browsers and users settings (which is a lot). Considering this is the third time we have had to change this code because browsers change their cookie settings and APIs every other day, we need to get it right.

Please be patient whilst we work on this, in the meantime I recommend disabling silent authentication and the session status checks.

**Comment by ssill2** [comment] 2023-09-20 10:18
No worries!  As a developer myself I get how daunting a task that is.   Thanks!

**Comment by jonkoops** [comment] 2023-09-20 10:40
> Do you guys use something like selenium for ui testing?

Yes, we have some automated testing in place. But not specifically for these kinds of 3rd party cookie problems. The issue is getting the browsers started with the correct configurations. We want to test the happy path of getting cookie access, but also the worst case scenarios such as 3rd-party cookies being blocked (with and without the [Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API)), and in the very worst scenario, no cookies at all.

Covering all these separate scenarios is just a massive PITA. But perhaps there is something that can be done.

**Comment by ssill2** [comment] 2023-09-20 10:46
yep, I appreciate the massive problem supporting all those browsers presents lol   It's a big reason I mostly do backend stuff! :)    During this whole time, my other app(which I wrote) that uses JEE + Vaadin, has never had issues.  That's primarily because of the way Vaadin works though.   This whole thing is another reason for me to dislike react anyway haha

**Comment by jonkoops** [comment] 2023-09-20 13:58
I have a preliminary PR up to fix this issue under #23393. If you are affected by this issue, please test your setup with the changes in that PR and let us know if it fixes the issue.

**Comment by ssill2** [comment] 2023-09-20 14:49
I might not be able to get to this today,  but I can look into this tomorrow

**Comment by ssill2** [comment] 2023-09-20 20:15
@jonkoops do you have an easy way for me to test this using your kjs-playground?   I've not tried to build keycloak from source, I've only used it by extending the docker container.   If you can point me at the easiest way to test I'll be happy to.

**Comment by jonkoops** [comment] 2023-09-21 10:10
@ssill2 I've been testing this by building the Keycloak server from source by running `mvn clean install -DskipTests`. You can then run the Quarkus server in dev mode by running the following in the `quarkus` directory:

```sh
KEYCLOAK_ADMIN=admin KEYCLOAK_ADMIN_PASSWORD=admin mvn -f server/pom.xml compile quarkus:dev -Dquarkus.args='start-dev --http-port=8180 --proxy=edge'
```

Then follow all the instructions in the playground repo, but skip the `pnpm run server:start` command, as the server should already be running.

**Comment by ssill2** [comment] 2023-09-21 12:18
Alright, just getting started this morning and working on my first cup of coffee.   I'll give this a try.  Thanks!  I can only test FF however, Someone with a mac will have to test Safari

**Comment by ssill2** [comment] 2023-09-21 13:10
Ok building now, I'll let you know!

**Comment by ssill2** [comment] 2023-09-21 13:25
build succeeded,  going to run keycloak and then your playground proj

**Comment by ssill2** [comment] 2023-09-21 13:37
looking good.  FF 102 on Rocky 9 works.   going to fire up 117 and try it also

**Comment by ssill2** [comment] 2023-09-21 13:42
I can confirm that firefox 117 also works!
![image](https://github.com/keycloak/keycloak/assets/25040169/a6cbb3d2-4e18-4009-aaf0-b9b23fd8191c)

I'd definitely recommend someone with access to test this with safari give it a whirl too.

Good job! :)

**Comment by jonkoops** [comment] 2023-09-21 13:57
Great, thanks for testing this @ssill2!

**Comment by ssill2** [comment] 2023-09-21 13:58
Surely!   Thanks for fixing! 🥇

**Comment by sebastianohall** [comment] 2023-09-25 19:32
Hello! Not sure if this is the correct place, but I am seeing the same exact issue in **chrome** using the Bitnami helm chart 16.1.5 and keycloak:22.0.3 image on a Kubernetes cluster. I know Bitnami does some stuff on top of the base keycloak image, but I feel like it shouldn't have too much effect on this particular issue. Here are the steps to reproduce:
1. Install Bitnami helm chart 16.1.5 using keycloak:22.0.3 image on a Kubernetes cluster
2. Try to open the admin console in Chrome version 117.0.5938.89 (I have tried different versions also)
3. Note that the admin console does not load (spinner keeps spinning).
4. In the console, see the error: Refused to frame 'http://keycloak.<url>/' because it violates the following Content Security Policy directive: "frame-src 'self'".   index.js:150

**Comment by ssill2** [comment] 2023-09-25 19:41
Interesting, Chrome/chromium as been the one that has constantly worked for me.  Regardless I think the fix hasn't become part of a release yet.  I've been watching for a this like a hawk.  I don't use the bitnami image, yet, but I agree I've not seen bitnami do anything in their other images like wildfly to think that the behavior should differ from the official keycloak one.

**Closed** 2023-09-27 11:38 UTC
Labels: area/authentication, kind/bug, priority/critical, impact/high, team/core, team/ui

**Comment by jonkoops** [comment] 2023-09-27 14:58
The fix for this issue has been backported, it will be included in the 22.0.4 release.

**Comment by dominiktopp** [comment] 2023-09-27 21:23
Hi, thank you for you work on this. I worked not say that #23393  fixes this issue. It is rather a workaround.
Keycloak.js still uses iframes with sandbox attribute set to 'allow-scripts allow-same-origin'. But the storage access api clearly states, that ‚allow-storage-access-by-user-activation‘ is also needed to have access in sandboxed iframes (see my post https://github.com/keycloak/keycloak/issues/22839#issuecomment-1723061220 above)
As far as I understand Firefox does not really have false positives in storage access api, it’s rather the sandbox of the iframes

**Comment by rkoplinger** [comment] 2023-10-10 05:19
I don't think that #23393 fixes this issue. Without 'allow-storage-access-by-user-activation' there is no access to cookies in sandboxed iframes and session monitoring does not work.

**Comment by jonkoops** [comment] 2023-10-10 16:06
@rkoplinger this was already discussed above. We will progressively enhance this in a future PR, but right now this will simply fall back to the redirect flow for Silent Authentication and disable any Session Status checks.

**Comment by jonkoops** [comment] 2023-10-10 16:19
Logged the follow-up to this issue under #23872. Please redirect any further discussion about said issue there.
