### ISSUE TITLE
Mapper for client roles with multivalued disabled, still sets the value as an array

### ISSUE THREAD

**Issue by wanqqq29** [keycloak/keycloak#22349] opened 2023-08-09 18:17 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

In the image below we see a mapper which is intended to return the first client role assigned to the authenticating user.

When the claim type is set to JSON an unknown error is returned when calling the token endpoint.

Further, I don’t believe this is a viable solution as at best, wouldn’t we get a JSON object inserted into the token, when actually, what is required is the name of the first client role without any further adornments, i.e. no enclosing brackets.

Next, the closest I can get is to use the STRING claim type, but this wraps the name of the first client role in brackets. This has to be viewed as a bug, because the user interface clearly indicates it is not a multivalued result. When ‘Multivalued’ is toggled off, this means “get me the first value”, so singular is implicit. Providing a value typed as an array would be deemed invalid.

My target system will not accept the role wrapped in [ ], I have to find a way to get this from keycloak as just the_role not [ the_role ].

![image](https://github.com/keycloak/keycloak/assets/43819451/15de657a-92e6-4fec-b30b-515bc29e51e6)

### Version

22.0.1

### Expected behavior

jwt return :
```
"https://hasura.io/jwt/claims": {
    "x-hasura-default-role": "tenant_admin",
    "x-hasura-user-id": "1f5d0070-eda0-4937-bf59-3123d1fc88d0",
    "x-hasura-allowed-roles": [
      "tenant_admin",
      ...
    ]
  },
```

and
When the claim type is set to JSON an unknown error is returned when calling the token endpoint. 500 CORS  ，and  webOrigin is  not working

### Actual behavior

jwt return :
```
"https://hasura.io/jwt/claims": {
    "x-hasura-default-role": "[tenant_admin]",
    "x-hasura-user-id": "1f5d0070-eda0-4937-bf59-3123d1fc88d0",
    "x-hasura-allowed-roles": [
      "tenant_admin",
      ...
    ]
  },
```

or 
fix : When the claim type is set to JSON an unknown error is returned when calling the token endpoint. 500 CORS 

### How to Reproduce?

I am integrating Keycloak with Hasura. It expects a value x-hasura-default-role to be (in my case) ‘tenant_admin’ or ‘tenant_user’, which will be assigned from a Client Role.

So as per the tooltip on the multivalued option, I specify that the value I want is not multivalued, expecting it will take the first role assigned to the user from the Client Roles. So why is the resulting value wrapped in ‘[’ ‘]’ when it is not multivalued? Refer x-hasura-default-role: “[tenant_admin]”.

This causes my authorisation to fail with Hasura.
![image](https://github.com/keycloak/keycloak/assets/43819451/4df0f1a6-96a6-414d-b4a5-2d7ec58815c8)

When i try to switch Claim JSON Type to JSON,Doing so appears to cause a 500 error accessing the token endpoint.

Just to see if a valid token would be formed I changed the value from STRING to JSON, but I suspect even if this had worked, Hasura would not then correctly interpret this value as it expect just the name of a role as plain text.

But here is my Keycloak config showing JSON is selected, and the resultant 500 error which seems to occur when the token endpoint is called.
![image](https://github.com/keycloak/keycloak/assets/43819451/35744a12-52f9-4227-8577-925e5b3549f2)

**Comment by rmartinc** [comment] 2023-09-26 09:49
@wanqqq29 I think this is dupicate of #20218 which is already fixed in main and it will be incorporated in keycloak 23.

But @pedroigor I have detected a possible regression in that PR #22861. Before the fix, the test `OIDCProtocolMappersTests.testUserGroupRoleToAttributeMappersScopedClientNotSet`  was configured single valued, and it created the string with the values separated with commas. It checked that it contained the roles for `test-app-scope` only.  But it was just that because it was singe-value, and the string was overwritten twice (first for client `test-app` and then `test-app-scope`, just one value of the two apps was set). If I change to multi-value in release/22.0 branch (before the fix), the result contains roles for both apps. So we have to change the test and not add [these weird lines](https://github.com/keycloak/keycloak/commit/13e5a02b9fe73fb8577bfc77af99d8cf6e159563#diff-c9cb7ebcd9e94ec455f413a75c82f3a204173347a477f5cf1461b9d6e3d65056R99-R104).

Those lines are introducing a regression, some configurations will miss the roles. For example the one that @wanqqq29 is using here. He is setting the `clientId` and the claim does not contain the clientId or roles. Imagine I set roles from client `test-client` to a claim called `auth`, it will be discarded now.

I'm going to send a little PR to restore previous behavior and modify the test to check all the roles as it was happening before your fix. The single value case is also tested and it's running OK.

**Comment by pedroigor** [comment] 2023-09-26 22:12
@rmartinc I think I agree about the check on the `roles` suffix. I think you're right and I was tricked by the test suite and added that condition for the `roles` suffix.

However, I'm not sure about removing the checks around the claim name and the client id. If a claim name does not reference the current client, why would you want roles from other clients in the value?

**Comment by pedroigor** [comment] 2023-09-26 22:58
@rmartinc Actually, you are right. Looks like we can remove all those checks. This is already covered before calling that method.

**Comment by rmartinc** [comment] 2023-09-27 07:08
Thanks @pedroigor! PR https://github.com/keycloak/keycloak/pull/23553 sent just now.

**Closed** 2023-09-27 11:11 UTC
Labels: area/oidc, kind/bug, team/core
