### ISSUE TITLE
Passkeys can't be registered in Firefox

### ISSUE THREAD

**Issue by BlackVoid** [keycloak/keycloak#24999] opened 2023-11-24 11:00 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

It's actually in the login/ui but that's not an option when creating the bug report.

When trying out the new passkeys feature in Firefox(120.0) on Mac I get an error when I click register in the webauthn-register-passwordless flow, it works as expected in Chrome. I've tried passkeys in Firefox on passkeys.io and on Google without any problems, so that makes me think it's an issue with the Keycloak implementation.

Error:
```
Security key registration result is invalid.
TypeError: _b.authenticatorSelection is undefined 
```

### Version

nightly as of 24th nov

### Expected behavior

Dialog for passkeys opens up and I can select to create a new one and register the key.

### Actual behavior

Error when trying to register:
```
Security key registration result is invalid.
TypeError: _b.authenticatorSelection is undefined 
```

### How to Reproduce?

1. Enable webauthn passwordless with correct Relying party ID and Relying party entity name for your instance
2. Enable Webauthn Register Passwordless under required actions
3. Add Webauthn Register Passwordless action on your user
4. Login with username and password
5. In register Webauthn Register Passwordless dialog click on register
6. Mentioned error is shown and no errors in console

**Comment by jonkoops** [comment] 2023-11-24 11:39
@mabartos looks like you wrote the original code for this, could you take a look?

**Comment by mposolda** [comment] 2023-11-24 15:13
CC @tnorimat @thomasdarimont just in case you guys have any idea?

**Comment by tnorimat** [comment] 2023-11-27 06:51
@mposolda 
I am arfaid that FireFox does not support the device that a reporter of the issue used.
Passkeys (WebAuthn) support depends on several factors like an OS, a browser, and a passkey (WebAuthn credental).

I could not find the rigorous and comprehensive resourse showing which OS and browser supports which passkey. I only found the following site.
https://passkeys.dev/device-support/
https://www.passkeys.io/compatible-devices

**Comment by zealousGnu** [comment] 2023-11-27 09:41
I get these warnings (systemd):

WARN  [org.keycloak.authentication.requiredactions.WebAuthnRegister] (executor-thread-1) WebAuthn API .create() response validation failure. TypeError: _b.authenticatorSelection is undefined
WARN  [org.keycloak.events] (executor-thread-1) type=CUSTOM_REQUIRED_ACTION_ERROR, realmId=(xxx), clientId=account, userId=(xxx), ipAddress=(xxx), error=invalid_us>

**Comment by mabartos** [comment] 2023-11-27 10:44
@mposolda I'm not aware of any recent changes to WebAuthn, and I haven't touched it for a long time. I'm afraid I will not be able to investigate it due to my time capacity. 

Could someone from the @keycloak/core take a look at it?

**Comment by BlackVoid** [comment] 2023-11-27 16:15
I did read up a bit more about Passkeys and Firefox and it seems like it will be [released natively in version 122](https://connect.mozilla.org/t5/ideas/support-webauthn-passkeys/idi-p/14069/page/9#comments).

For the registration part I also found one place that gives me the same error and that's [webauthn.me](https://webauthn.me/debugger) mentioned [here](https://github.com/bitwarden/clients/issues/6769) and I got it to work with the registration by setting "Authenticator Attachment" cross-platform, causing authenticatorSelection to be present. So it seems that at least in my case it's an issue with how Bitwarden handles passkeys.

This leaves the login parts which is still not working and I'm not sure why it's not working, could not find any major difference between how the `navigator.credentials.get`call looks when it's working i.e on passkeys.io and the one that keycloak makes see the below screenshots. 

Passkeys.io (works):
![image](https://github.com/keycloak/keycloak/assets/673720/b3964e82-3e18-4cfd-93fd-f9cdb67a111f)

Keycloak (does not work):
![image](https://github.com/keycloak/keycloak/assets/673720/f788b0a6-f32a-429d-a73f-58b74ec79664)


I've also played around with the parameters and I am unable to get it to work with what appears to be identical parameters as Passkeys.io with only the rpId and challange having different values. So maybe it's best to wait for Firefox and/or Bitwarden to improve their support for passkeys.

**Comment by mposolda** [comment] 2024-02-21 11:49
I've changed this to "Task" and added to passkeys epic for investigate https://github.com/keycloak/keycloak/issues/24999 . This might be an environment issue as for instance in my environment, passkeys also don't work on Firefox (Ubuntu 22.0.4 , Firefox 122.0.1).

**Comment by LukeDRussell** [comment] 2024-05-13 02:27
Confirming I'm not able to _create_ passkeys in Firefox.
Version 125.0.3 on Fedora 40. 
I can however create passkeys in a chromium-based browser, then successfully login on Firefox using the new passkey.

**Comment by jonkoops** [comment] 2024-05-14 10:13
@tnorimat I noticed that we're not following the [guidelines for feature detection](https://web.dev/articles/passkey-registration#feature_detection) for Passkeys. We're not calling [`PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable_static) or [`PublicKeyCredential.​​isConditionalMediationAvailable()`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isConditionalMediationAvailable) anywhere. Perhaps this could be part of the issue? Do you think we should log a separate issue to handle this properly?

**Comment by jonkoops** [comment] 2024-05-14 10:42
I am not able to reproduce this on `main` with Fedora and with Firefox 125.0.3, it seems that Firefox doesn't support the Passkey flow and instead falls back to using a security key.

![Screenshot from 2024-05-14 12-31-24](https://github.com/keycloak/keycloak/assets/695720/f74671ef-cde2-492b-841c-5181f9524a32)

I'm marking this issue as 'needs more info', if anyone has more detailed steps for an accurate reproduction let us know.

**Comment by ThomasAunvik** [comment] 2024-05-14 15:55
> it seems that Firefox doesn't support the Passkey flow and instead falls back to using a security key.

I believe Bitwarden Extension for Firefox enables passkey flow which can be used to test.

**Comment by tnorimat** [comment] 2024-05-15 02:38
@jonkoops Hello, sorry for my late reply.

As for your comment,
https://github.com/keycloak/keycloak/issues/24999#issuecomment-2109813423
IMO, it might be good to create a new issue for following the [guidelines for feature detection](https://web.dev/articles/passkey-registration#feature_detection) for Passkeys.

Also, I will try to reproduce this issue in my computing environment with Firefox.

**Comment by tnorimat** [comment] 2024-05-15 03:14
@jonkoops @BlackVoid Hello,
I tried to reproduce the issue by the following environment, but the issue did not occur.
I could register a user and its passkey, and authenticate the user by registered passkey.
- PC: Windows 11 Pro 23H2
- Keycloak: 24.0.4
- Browser: Firefox 126.0 (64 bit)

**Comment by jonkoops** [comment] 2024-05-15 09:36
> I believe Bitwarden Extension for Firefox enables passkey flow which can be used to test.

I've used 1Password, which just pops up the Passkey dialog, and everything works as expected. I think whatever bug was occurring has since been fixed since. I'll close this issue, if anyone has further steps to reproduce this accurately let us know.

**Closed** 2024-05-15 09:36 UTC
Labels: kind/bug, area/login/ui, team/core-clients, status/auto-expire, status/missing-information

**Comment by jonkoops** [comment] 2024-05-15 09:41
> As for your comment, [#24999 (comment)](https://github.com/keycloak/keycloak/issues/24999#issuecomment-2109813423) IMO, it might be good to create a new issue for following the [guidelines for feature detection](https://web.dev/articles/passkey-registration#feature_detection) for Passkeys.

Thanks for getting back to me on that, I went ahead and logged #29558 to investigate this further.

**Comment by tnorimat** [comment] 2024-05-16 02:31
@jonkoops Hello, how about creating a new issue for following the [guidelines for feature detection](https://web.dev/articles/passkey-registration#feature_detection) for Passkeys? If you agree with it, I would like to create the issue.

**Comment by BlackVoid** [comment] 2024-05-16 08:58
Not sure how passkeys are implemented in firefox on windows, but on Mac it is by default using Touch ID.
I however use bitwarden and I can register a passkey, but on login the passkey is not discovered.

Since passkeys.io is working as intended it is not clear if it's an issue in Bitwarden or in the parameters Keycloak includes when signing in through passkeys.

**Comment by jonkoops** [comment] 2024-05-16 09:14
> Hello, how about creating a new issue for following the [guidelines for feature detection](https://web.dev/articles/passkey-registration#feature_detection) for Passkeys? 

Already did, that should be #29558

> I however use bitwarden and I can register a passkey, but on login the passkey is not discovered.

This is strange, using 1Password this is working fine for me. Perhaps this is something specific about how Bitwarden works?

**Comment by tnorimat** [comment] 2024-05-16 23:55
@jonkoops Thank you!

**Comment by BlackVoid** [comment] 2024-05-18 08:05
Just looked into it and after digging into how passkeys works on bitwardens side for discovering the keys I noticed that I had not set "Require discoverable credential" to "Yes". So to make sure it works well in all circumstances I also tested having the key not be discoverable and have the user fill in the username first and that works too.

So I think the issue is resolved on my part.
