### ISSUE TITLE
CRD Keycloak is not working by SSA mode

### ISSUE THREAD

**Issue by chendouble** [keycloak/keycloak#21798] opened 2023-07-18 23:48 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

CRD keycloak resource cannot be applied by SSA mode, getting errors likes following:
Error from server: failed to create manager for existing fields: failed to convert new object (keycloak-operator/example-kc; k8s.keycloak.org/v2alpha1, Kind=Keycloak) to smd typed: errors:
  .status.conditions[0].status: expected map, got &{False}
  .status.conditions[1].status: expected map, got &{True}
  .status.conditions[2].status: expected map, got &{False}

### Version

latest

### Expected behavior

SSA mode apply should be work.

### Actual behavior

Not work.

### How to Reproduce?

Sample Keycloak resource file Keycloak-example.yaml:
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1

Steps:
1. kubectl -n keycloak-operator apply -f Keycloak-example.yaml (works)
2. kubectl -n Keycloak-operator apply --server-side=true -f Keycloak-example.yaml (error)

**Comment by shawkins** [comment] 2023-07-19 10:52
Duplicate of #21739

**Closed by shawkins** 2023-07-19 10:52 UTC
Labels: kind/bug, team/cloud-native, status/triage, area/operator
