### ISSUE TITLE
Integrating SPI custom jar: Loader constraint violation

### ISSUE THREAD

**Issue by BouweCeunen** [keycloak/keycloak#12113] opened 2022-05-19 14:10 UTC
### Describe the bug

I want to make an SPI for Keycloak and I use external dependencies such as for example.

```
<dependency>
	<groupId>org.keycloak</groupId>
	<artifactId>keycloak-admin-client</artifactId>
	<version>${version.keycloak}</version>
</dependency>
```

If I make a jar through maven, I get a `Uncaught server error: java.lang.NoClassDefFoundError: org/keycloak/admin/client/KeycloakBuilder`. If I extend my pom file with the maven shade plugin I get the following error.

```
<plugins>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-shade-plugin</artifactId>
		<version>3.2.4</version>
		<executions>
			<execution>
				<phase>package</phase>
				<goals>
					<goal>shade</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<filters>
				<filter>
					<artifact>*:*</artifact>
					<excludes>
						<exclude>META-INF/*.SF</exclude>
						<exclude>META-INF/*.DSA</exclude>
						<exclude>META-INF/*.RSA</exclude>
					</excludes>
				</filter>
			</filters>
		</configuration>
	</plugin>
</plugins>
```

```
ERROR: loader constraint violation: loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1b73be9f wants to load class org.jboss.resteasy.spi.ResteasyDeployment. A different interface with the same name was previously loaded by java.net.URLClassLoader @5a955565. (org.jboss.resteasy.spi.ResteasyDeployment is in unnamed module of loader java.net.URLClassLoader @5a955565, parent loader 'app')
```

What is the standard way to use external dependencies for an SPI, do we have to make an uber jar or is this not necessary?

### Version

18.0.0

### How to Reproduce?

The full pom.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>keycloak</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>keycloak</name>
	<description>keycloak</description>
	<packaging>jar</packaging>

	<properties>
		<java.version>17</java.version>
		<version.keycloak>18.0.0</version.keycloak>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-core</artifactId>
			<version>${version.keycloak}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-server-spi</artifactId>
			<version>${version.keycloak}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.jboss.logging</groupId>
			<artifactId>jboss-logging</artifactId>
			<version>3.4.3.Final</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-server-spi-private</artifactId>
			<version>${version.keycloak}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-services</artifactId>
			<version>${version.keycloak}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-admin-client</artifactId>
			<version>${version.keycloak}</version>
		</dependency>

		<dependency>
			<groupId>io.github.novacrypto</groupId>
			<artifactId>Base58</artifactId>
			<version>2022.01.17</version>
		</dependency>

		<dependency>
			<groupId>software.pando.crypto</groupId>
			<artifactId>salty-coffee</artifactId>
			<version>1.0.4</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>simple-authenticator</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.4</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<filters>
						<filter>
							<artifact>*:*</artifact>
							<excludes>
								<exclude>META-INF/*.SF</exclude>
								<exclude>META-INF/*.DSA</exclude>
								<exclude>META-INF/*.RSA</exclude>
							</excludes>
						</filter>
					</filters>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

Running `./mvnw clean package` and putting this jar in `/providers`.

**Comment by pedroigor** [comment] 2022-05-26 14:42
@BouweCeunen This is a duplicate of https://github.com/keycloak/keycloak/issues/11973.

The problem seems to be related to creating a uber jar with the `keycloak-admin-client` classes (and transient dependencies).

In that issue, the reporter was able to solve the problem and you can follow the same steps for now.

We want to improve this but for now the steps there are needed.

**Closed by pedroigor** 2022-05-26 14:42 UTC
Labels: kind/enhancement, area/dist/quarkus
