### ISSUE TITLE
Cannot read properties of undefined (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by ghenadiibatalski** [keycloak/keycloak#16763] opened 2023-02-01 10:54 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Sometimes i'm getting an error on opening the events with the new Admin UI. 20.0.1 and 20.0.3 are both affected but the error occurs not always.

![image](https://user-images.githubusercontent.com/24528146/216023179-fb05eabb-48a1-4fcf-9029-9f974660e61c.png)

### Version

20.0.3

### Expected behavior

Events can be analyzed without problems.

### Actual behavior

See the screen attached

### How to Reproduce?

i just open the events menu on our realm and the error occures

**Comment by jonkoops** [comment] 2023-02-01 17:05
This is a duplicate of https://github.com/keycloak/keycloak-ui/issues/4127, and a fix will be released with Keycloak 20.0.4.

**Closed by jonkoops** 2023-02-01 17:05 UTC
Labels: kind/bug, area/admin/ui, status/triage
