### ISSUE TITLE
Translations for delegated admin not loading

### ISSUE THREAD

**Issue by matthiasvop** [keycloak/keycloak#22253] opened 2023-08-04 12:06 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

After updating to 22.0.1, the keycloak admin UI is no longer loading translations for delegated admins without access to the master realm.

![image](https://github.com/keycloak/keycloak/assets/92366903/a4fca60a-e7a0-49f7-96f9-a87837822c60)

![image](https://github.com/keycloak/keycloak/assets/92366903/f8cfa104-be7d-48fe-b7c7-0a82634d54e9)

The "translations" request fails with 403 permission denied.

The custom role has the following permissions (for the delegated realm, NOT for the master realm):

![image](https://github.com/keycloak/keycloak/assets/92366903/8400fe5c-9b25-4bb2-850b-ed9b949c9012)

The translations load fine for the master realm users / admins - and work fine if i add "master-realm - view-realm" permission, but this defeats the purpose of having a delegated admin role.

![image](https://github.com/keycloak/keycloak/assets/92366903/ddf45b0e-72c5-4837-afe8-e585953b5b66)

![image](https://github.com/keycloak/keycloak/assets/92366903/99102c01-a314-45f0-b26e-9598886e4dca)

### Version

22.0.1

### Expected behavior

Translations load correctly

### Actual behavior

Translations don't load for delegated admin

### How to Reproduce?

Set roles as listed above

**Comment by jonkoops** [comment] 2023-08-04 16:27
Hmmm, yeah kinda strange that access is being denied for this endpoint. I do believe this is an API issue, rather than a UI issue.

**Comment by ssilvert** [comment] 2023-08-09 19:46
This is definitely a server-side regression.  

@matthiasvop Which Keycloak version are you migrating from?  
I believe that adding any permission from master-realm will work around the problem.  But that's probably not acceptable for your use case?

I have reproduced this.  Looks like the problem is somewhere in `MgmtPermissions.java`.  I suspect maybe the regression was introduced with https://github.com/keycloak/keycloak/issues/15038.  However, that was from 10 months ago.  

I'm going to turn this over to the core team and let them take a look.

**Comment by matthiasvop** [comment] 2023-08-11 07:44
We migrated from 21.1.1 - which fixes another bug which is actually more critical to us than this.


> I believe that adding any permission from master-realm will work around the problem. But that's probably not acceptable for your use case?

Not really (at least not long-term) - though it's what we're running with currently.

From a security perspective, it also defeats the purpose of having a delegated admin, if that admin requires "some" permissions from the over-arching master realm as a workaround to be able to load the translations for the UI.

**Comment by rmartinc** [comment] 2023-09-20 14:56
I think this is a duplicate of https://github.com/keycloak/keycloak/issues/23065 that is already scheduled for 22.0.5. It was fixed by @edewit a few weeks ago. @matthiasvop you can test with the last [nightly](https://github.com/keycloak/keycloak/releases/tag/nightly) if interested.

I will close this one in a few days if nobody says something different.

**Comment by matthiasvop** [comment] 2023-09-21 06:06
@rmartinc quite certainly it is the same issue, yes.

screenshots there also show the same behavior than what i've seen (months earlier ...)

**Comment by jonkoops** [comment] 2023-09-21 09:27
Thanks for checking that, I will close this as a duplicate then.

**Comment by jonkoops** [comment] 2023-09-21 09:27
Duplicate of #23065

**Closed by jonkoops** 2023-09-21 09:27 UTC
Labels: kind/bug, area/core, team/core
