### ISSUE TITLE
JDBC resources leaked warning during startup

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#34819] opened 2024-11-11 11:13 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

During a regular startup the following warning is displayed:

```
WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
```

This could suggest there is an issue that needs to be fixing, or if not the warning should not be displayed. It certainly isn't something that users of Keycloak should need to deal with as this is with just unzipping KC and starting it, without any further configuration.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

No unexpected warning during startup

### Actual behavior

The following warning is shown on every startup:

```
WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
```

### How to Reproduce?

`kc.sh start-dev`

**Comment by shawkins** [comment] 2024-11-11 11:42
Duplicate of #34195

**Closed by shawkins** 2024-11-11 11:42 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
