### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by AlanSnt** [keycloak/keycloak#30836] opened 2024-06-26 19:28 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-js

### Describe the bug

I have one error in my console when i run my app with keycloak-admin-client dependency

```shell
const _keycloakadminclient = require("@keycloak/keycloak-admin-client");
                             ^
Error [ERR_REQUIRE_ESM]: require() of ES Module
```

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

No error in console and kcAdmin run

### Actual behavior

Error in console, kcAdmin can't be run and nestjs app has crashed

### How to Reproduce?

On my NestJS app on my service running ...

```typescript
import KeycloakAdminClient from '@keycloak/keycloak-admin-client';

@Injectable()
export class KeycloakService {
    private readonly kcAdminClient: KeycloakAdminClient;

    constructor(logger: LoggingService) {
        this.log = logger.getLogger(KeycloackService.name);
        this.kcAdminClient = new KeycloakAdminClient();
    }

}
```

### Anything else?

Bug already reported [here](https://github.com/keycloak/keycloak-nodejs-admin-client/issues/523)
But the issue is on a archived repository, without fix after 2years.

**Comment by jonkoops** [comment] 2024-06-26 21:43
Not sure why you decided to report this, as the issue you linked already has the answer. This is a [bug in Nest.js](https://github.com/nestjs/nest/pull/8736), it does not support importing standardized JavaScript modules, as the Nest.js team decided to go all in on the now legacy CommonJS module system, which should no longer be used.

**Comment by jonkoops** [comment] 2024-06-26 21:43
Duplicate of #19829

**Closed** 2024-06-26 21:44 UTC
Labels: kind/bug, status/triage, team/ui, area/admin/client-js
