### ISSUE TITLE
Keycloak writes metadata attributes as User Attributes for federated storage

### ISSUE THREAD

**Issue by btarhan** [keycloak/keycloak#28277] opened 2024-03-28 14:12 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When using a federated storage provider, Keycloak writes metadata attributes like ENABLED and EMAIL_VERIFIED as user attributes instead. This causes issues because when updating a user, these attributes will be removed if they are not managed, and get reset to their default values.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

These "metadata" attributes would be saved correctly on users and their values would persist past the update that currently is breaking them.

### Actual behavior

The attributes are removed from the user during the save process and get reset back to their default values.

### How to Reproduce?

Setup a federated storage provider in keycloak, and then update a user in the account console. 

### Anything else?

The method in question here is AbstractUserAdapterFederatedStorage#setEmailVerified, which just sets EMAIL_VERIFIED as an attribute. This behavior does not match the nonfederated storage behavior.

**Comment by pedroigor** [comment] 2024-10-16 00:13
@btarhan Are you updating the email attribute when at the account console?

**Comment by btarhan** [comment] 2024-10-17 19:03
@pedroigor At this point I don't remember the exact context around this, but it had to do with the UserProfile stuff. I believe when we were syncing data from User Service into Keycloak, if we hadn't marked these attributes as managed they all got reset. So what you would see is a user that existed in the system and had already verified their email would lose that email verification and be prompted to do it again.

**Comment by pedroigor** [comment] 2024-10-17 19:36
I see. I can not reproduce without updating the email. That is why I'm asking. It would be good to know more details about the steps when updating the user.

**Comment by btarhan** [comment] 2024-10-17 19:45
It is certainly not the case in a vanilla instance of keycloak, and probably a result of us using user federation with User Service. Keycloak may be picking up the sync as an email update, even though we don't really want it managing any of that. I.e. user logs in -> we sync their data, including email and emailVerified from User Service -> keycloak sees the email has "changed" (hasn't been changed but a value has been passed) -> updates emailVerified. 

All this being said, this was happening two major versions of Keycloak ago, it is possible this has been inadvertently fixed in the interim.

**Comment by pedroigor** [comment] 2024-10-17 19:47
I see. What I did here to reproduce the problem is to create a very basic user storage provider so I can list and authenticate users from it. Then I try to update the user via account console.

If I update the email, the email verification flag is disabled/removed. Otherwise, it works.

Hope it is enough and perhaps it is already fixed in upstream.

**Closed** 2024-11-12 20:07 UTC
Labels: kind/bug, area/user-profile, help wanted, team/core-iam, priority/low
