### ISSUE TITLE
User Attribute search doesn't work

### ISSUE THREAD

**Issue by hillout** [keycloak/keycloak#24324] opened 2023-10-26 13:25 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

User Attribute search doesn't work.

For example I've got a user called **admin** in KC user storage. He has "test_test" attribute with value "55". Trying to search going to WebUI of KC -> Admin Console -> Users -> Attribute Search  putting key - test_test, Value 55. And nothing happens, **No search results**.

User admin's attrubite:
![Screenshot from 2023-10-26 15-59-53](https://github.com/keycloak/keycloak/assets/15137897/767d5d84-dc9b-47c6-abb0-9c2f7d84cc0d)

Search result:
![Screenshot from 2023-10-26 16-00-31](https://github.com/keycloak/keycloak/assets/15137897/7d3c0f8a-01ff-4f33-ad06-e412f5707c64)

### Version

22.0.4

### Expected behavior

I see result of searching.

### Actual behavior

Search doesn't show result

### How to Reproduce?

Create a new user, add any attribute to it - key and value. Try to search by attribute.

**Comment by ssilvert** [comment] 2023-10-27 01:02
@hillout I believe this is fixed in 22.0.5.  Can you give it a try?

**Comment by hillout** [comment] 2023-10-27 08:55
@ssilvert hi! Yeah, I've tried, but it is even worst, cuz in the filter itself you can choose only from these options: "Username, email, First name Last name", and you can't write something else and by the way, the thing which is really annoying - when you type something in the **Key** section, you can't switch to the **Value** section by TAB - the window just disappears.

 
![Screenshot from 2023-10-27 11-50-21](https://github.com/keycloak/keycloak/assets/15137897/68632b26-7596-4ccb-bab9-8f409af680ee)


![Screenshot from 2023-10-27 11-50-29](https://github.com/keycloak/keycloak/assets/15137897/8d8445b4-6eff-4bc7-8a5d-f4d161d1adc9)

**Comment by ssilvert** [comment] 2023-10-27 18:13
@hillout Regarding your first image, when I select the dropdown arrow for key I do see all of my attributes including the custom attributes I created in User Profile.  Then I can type a value and click the checkmark and it works.

I do see your problem with tabbing though.  We will need to fix that and also just make sure this is a little more intuitive.

Also, it only works on an exact match.  We may want to enhance that to allow more of a fuzzy search.

**Comment by antikalk** [comment] 2023-10-29 17:18
> @hillout Regarding your first image, when I select the dropdown arrow for key I do see all of my attributes including the custom attributes I created in User Profile. Then I can type a value and click the checkmark and it works.

@ssilvert I think the issue is when not using User Profile (and maybe even with using it) you want to be able to enter a generic key, not only the values provided by the dropdown. At the moment when not using user profile, you can only search for these attributes, even if users have attributes with different keys: 

![image](https://github.com/keycloak/keycloak/assets/1793007/9f03b787-e316-422c-bce7-76f92a4a44e9)
Having the dropdown as suggestion is great though, but it should maybe also allow to enter free text.

> Also, it only works on an exact match. We may want to enhance that to allow more of a fuzzy search.

+1 this would be really cool! But would require some work at the backend side afaik...

**Comment by hillout** [comment] 2023-10-30 10:04
@ssilvert hi, thanks for reaching. 
Well, we don't use User Profile, and I removed default roles for users in order to manage it. We use Federation of users in LDAP. And there is no way for searching the attributes by UI, only API. 

As @antikalk noticed it really odd that you can't search by custom attribute name. From my point of view, if there is an option for searching attributes it should be working :)

**Comment by antikalk** [comment] 2023-10-30 18:24
> The day is coming soon when User Profile will not be an option. So I don't see us adding any special logic for those not using User Profile.
> 
> How hard would it be for you to turn on User Profile and define your attributes there?

That would of course be the alternative and when user profile becomes the default, adding special logic does not make sense then. A freetext input is not needed with user profile as you wouldn't be able to add a "non-defined" attribute anyway. I am really looking forward to User Profile becoming a core feature btw.

**Comment by hillout** [comment] 2023-10-31 14:55
I think I know what problem is. We've implemented a custom SPI which gets some user attributes from external database and writes them in the User Storage. 

If I'm turning on User Profile - the Attributes disappears at all. Seems we'll need some work to do on SPI.

**Comment by ssilvert** [comment] 2023-11-01 12:19
Reopened.  We still need to fix the problem where hitting the tab button closes the attribute selection panel.  @agagancarczyk will take it.

**Comment by agagancarczyk** [comment] 2023-11-01 12:59
I'm closing this issue in favor of https://github.com/keycloak/keycloak/issues/24464

**Closed by agagancarczyk** 2023-11-01 12:59 UTC
Labels: kind/bug, impact/medium, area/admin/ui, team/ui
