### ISSUE TITLE
AuthAdmin containing Manage-Realm role is unable to change settings in KeyCloak.

### ISSUE THREAD

**Issue by anshubansal2000** [keycloak/keycloak#15560] opened 2022-11-17 23:28 UTC
### Area

user-profile

### Describe the bug

We have a role AuthAdmin in master realm and AuthAdmin has an assigned role of "Manage-Realm". When we try to change the settings, we are getting 403 Forbidden error. Just wondering if anyone else also have faced the issue. Will appreciate the help/guidance.

 

### Version

latest

### Expected behavior

Auth Admin should be able to change the settings.

### Actual behavior

403 Forbidden 

### How to Reproduce?

1) Create a User account in Master Realm,
2) Assign Manage-Realm role
3) Go to Any Realm
4) Try to change Bindings

### Anything else?

If we create any new realm from scratch, we are able to change it. However, this is happening for our one of the existing realm.

**Comment by lexcao** [comment] 2022-11-18 14:39
Hi, which Keycloak version are you using?

And could you please check this [doc](https://www.keycloak.org/docs/latest/server_admin/#master-realm-access-control)?

**Comment by Sheeren-Caw** [comment] 2022-11-18 15:32
Hi @lexcao, we are using 18.0.0 version.

**Comment by pedroigor** [comment] 2023-01-25 13:34
Changing label to `core` as it is related to admin role management.

**Comment by mposolda** [comment] 2023-04-04 09:53
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by pedroigor** [comment] 2024-03-04 19:15
Not able to reproduce. If you can give more details about how to reproduce, I appreciate.

**Closed** 2024-03-18 20:04 UTC
Labels: kind/bug, area/core, team/core-iam, status/auto-expire, status/expired-by-bot
