### ISSUE TITLE
Very poor performance while fetching the users list

### ISSUE THREAD

**Issue by wornr** [keycloak/keycloak#31739] opened 2024-07-29 20:05 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When Keycloak is configured with an LDAP provider, fetching the list of all users (* as a search string) in the Admin Console or through the Admin API endpoint `GET /admin/realms/{realm}/users` always takes approximately 11.3 seconds.
![Zrzut ekranu 2024-07-29 220252](https://github.com/user-attachments/assets/5d61697c-7c29-4835-a38a-eddacce1a0f4)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Users list should load as quickly as possible, no matter if LDAP provider is used or not.

### Actual behavior

1. First attempt of listing users after LDAP provider has been configured is quick. (approx. 500 ms)
2. Second attempt is significantly slower. (appox. 6 sec.)
3. Third and consecutive attempts are unacceptably slow (11.3 sec.)

**The thing to note here is that the 3rd and consecutive attempts are wierdly capped at 11.3 sec. no matter how big the list of users will be (assuming the search is performed with * as the search string)**

### How to Reproduce?

1. Create new realm (importing realm with predefined the same LDAP configuration behaves a little bit different/better, which is also weird, e.g. [example-realm.json](https://github.com/user-attachments/files/16085129/ldap_federation.json))
2. Add new LDAP Provider under **User federation**.

Example LDAP
- Vendor: **Other**
- Connection URL: **ldap://ldap.forumsys.com:389**
- Bind DN: **cn=read-only-admin,dc=example,dc=com**
- Bind credentials: **password**
- Edit mode: **UNSYNCED**
- Users DN: **dc=example,dc=com**
- Username LDAP attribute: **uid**
- RDN LDAP attribute: **uid**
- UUID LDAP attribute: **uid**
- User object classes: **inetOrgPerson, organizationalPerson**
- User LDAP filter: **(uid=*)**
- Pagination: **true**

There are two ways to go from this point, either invoke `GET /admin/realms/{realm}/users` with attributes `briefRepresentation=true` and `q=*` or continue with the following steps:
3. Open browser dev tools (Network tab), then go to **Users** and search for all users by typing * into the search field.
4. Repeat the search and see how response time grows according to what has been described in section **Actual behaviour**.

### Anything else?

I've checked previous major versions of Keycloak down to 21.0.0. The issue was already there.

**Comment by pedroigor** [comment] 2024-08-16 14:53
Adding the `ldap` label and moving to our backlog as we are planning a review in the LDAP provider.

**Comment by sguilhen** [comment] 2024-10-28 21:52
I ended up missing this one when I've opened https://github.com/keycloak/keycloak/issues/34050 - observed exactly the same symptoms with around 2k users in my LDAP server. With lower number of users (say low hundreds) the difference is barely noticeable, but once you get up to 1.5k - 2k users the time taken to load them grows.

With import disabled, we perform a single LDAP search for the users (in admin console we fetch 11 users by default), build the in-memory proxied user model, and subsequent validation that is performed when searching users knows the LDAP objects have already been fetched and uses these cached objects, so no other LDAP searches are triggered.

With import enabled, the first request does the same as above, only difference is that before returning the users they are saved in Keycloak's DB. This is why the first request (before users are stored in the DB) is as fast as the no-import case. (around 500ms in my tests)

The second request fetches the users from the DB, going through the JPA provider, and each user is validated - for that a LDAP search is performed for each user, and this can lead to performance degradation depending on the size of the LDAP store (number of users there). In my case here, around 6 seconds to return the first 10 users to the admin console.

The third request now hits the cached user, but keycloak still validates the local cached users agains LDAP - so a search is still performed  for each one. However, a bug was causing validate to run twice for each user, and this was leading to requests now taking around 13 seconds.

**Comment by sguilhen** [comment] 2024-10-28 21:59
I've sent a PR to fix the last point, so now all requests (except for the first one that will always be faster) take around 5.5s to 6s with an LDAP store containing around 2k users, which is half of the time it was taking.

We will study some other possibilities to improve this further, but for the time being this was a low hanging fruit that we could pick to improve the performance of these searches.

I'll close this as a duplicate of #34050 as the PR was linked to that issue.

**Closed by sguilhen** 2024-10-28 21:59 UTC
Labels: kind/bug, area/admin/api, area/ldap, help wanted, team/core-iam, status/auto-expire, status/auto-bump, priority/normal
