### ISSUE TITLE
Keycloak Operator: add CRD for Keycloak Client

### ISSUE THREAD

**Issue by brsolomon-deloitte** [keycloak/keycloak#16152] opened 2022-12-21 21:36 UTC
### Description

Keycloak Operator CRDs should have a CRD to express a Keycloak Client as k8s YAML manifest.

### Motivation

[The old Keycloak Operator supported this](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloakclients_crd.yaml), and the new one conspicuously does not. If I can define a Realm but not a Client using configuration-as-code, that only gets me halfway there.

**Comment by brsolomon-deloitte** [comment] 2022-12-21 21:46
Related: https://github.com/keycloak/keycloak/issues/12969, https://github.com/keycloak/keycloak/issues/11928, https://github.com/keycloak/keycloak-community/pull/330/files#diff-1a3bcf2f8669c80d5b09bd9e1f3cd65d516dd36f1857cac43d605c362bca459dR63, https://github.com/keycloak/keycloak/issues/13204, https://www.keycloak.org/2022/09/operator-crs, https://github.com/keycloak/keycloak/issues/13566.

**Comment by vmuzikar** [comment] 2023-08-03 07:13
Duplicate of https://github.com/keycloak/keycloak/issues/13566

**Closed by vmuzikar** 2023-08-03 07:13 UTC
Labels: kind/enhancement, status/triage
