### ISSUE TITLE
Workflow failure: Operator IT on OpenShift - KeycloakIngressTest

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#28870] opened 2024-04-18 07:50 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
2024-04-16 22:50:57  [ERROR] Errors: 
2024-04-16 22:50:57  [ERROR]   KeycloakIngressTest.testFallbackToDefaultProxySettings:120 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.utils.K8sUtils 
2024-04-16 22:50:57  expected: true
2024-04-16 22:50:57   but was: false within 5 minutes.
2024-04-16 22:50:57  [ERROR]   KeycloakIngressTest.testIngressOnHTTP:62 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.utils.K8sUtils 
2024-04-16 22:50:57  expected: true
2024-04-16 22:50:57   but was: false within 5 minutes.
2024-04-16 22:50:57  [INFO] 
2024-04-16 22:50:57  [ERROR] Tests run: 117, Failures: 0, Errors: 2, Skipped: 4
```

Full log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/398/execution/node/69/log/

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment] 2024-04-18 19:32
Possibly related to #28869 

In both the failures the pod log stops before coming up. For example one stopped at:
```
2024-04-16 20:33:32,119 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
```
Which is strange - and so did the events. It's as if nothing was happening for the time that the test was waiting. I'm thinking this points to an environmental issue as I am also able to reproduce against an openshift cluster created by cluster bot.

**Comment by vmuzikar** [comment] 2024-05-02 10:14
@miquelsi Any update on this? Is it still valid? From what I understand it looks like an environmental issue which might be solved by cluster reinstall.

**Comment by vmuzikar** [comment] 2024-05-02 10:16
> I am also able to reproduce against an openshift cluster created by cluster bot

@shawkins You meant _not_ able to reproduce?

**Comment by shawkins** [comment] 2024-05-02 12:05
> You meant not able to reproduce?

Yes, corrected.

**Comment by shawkins** [comment] 2024-05-08 16:35
~priority-low

**Comment by shawkins** [comment] 2024-05-21 15:12
duplicate of #28869

**Closed by shawkins** 2024-05-21 15:12 UTC
Labels: kind/bug, area/ci, help wanted, team/cloud-native, team/continuous-testing, flaky-job, priority/low, status/auto-expire, status/auto-bump
