### ISSUE TITLE
Unable to complete "Update Profile" after enabling the experimental feature "Update Email"

### ISSUE THREAD

**Issue by Guesch** [keycloak/keycloak#22403] opened 2023-08-12 19:00 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

We enabled yesterday the experimental "Update Email" feature (we have no other experimental feature activated) and since then users are unable to move past the "Update profile" step.

If "Edit username" is off, the user sees nothing, just clicking on submit seems to do nothing:
![image](https://github.com/keycloak/keycloak/assets/61683661/2859c017-0ba5-477c-a755-5845ada4e57d)
After clicking on submit:
![image](https://github.com/keycloak/keycloak/assets/61683661/048ad9d6-aed7-447f-9ef5-90fbbc892b86)

If you turn "Edit username" on, then you actually have an error message:
![image](https://github.com/keycloak/keycloak/assets/61683661/89e325bc-c722-4966-b182-4178451e3531)

As you can see, the error message says "Please specify username" even though there is a username.. You will get this error message whatever username you type in this field.

The only way to pass this step is to deactivate: "Email as username". "Funny enough" while this option is off, I was able to use the email as username to pass the "Update Profile" step.
![image](https://github.com/keycloak/keycloak/assets/61683661/35b1ba0e-e9ca-4aa0-9940-92bf501c7bda)

### Version

20.0.2

### Expected behavior

For people to be able to pass the "Update profile" step by entering their first & last name, while enforcing the "your username is your email".

### Actual behavior

Users are unable to complete their "Update profile" if admin decided to have the username = email.

### How to Reproduce?

1. Activate the experimental "Update Email" feature
2. Set the realm settings/login as shown below:
![image](https://github.com/keycloak/keycloak/assets/61683661/3c2d548d-eea5-472e-8165-b0c771bf060d)
3. Create a user (just enter a valid email)
4. Go to the "credential" tab for this user and click on "Credential reset"
5. Select "Update profile" in the Reset Actions
6. Click on the link received in the email
7. Try to pass the Update profile step

### Anything else?

Please note that wile the "Update Email" experimental feature is loaded, the bug happens whether or not this feature is activated in the "Authentication / Required actions" page.

**Comment by Guesch** [comment] 2023-08-13 08:03
I think it could potentially be the same bug than reported here: https://github.com/keycloak/keycloak/issues/21791
but not sure as we are not using "user profile" preview. 

Sorry for the duplicate if this is actually the same bug

**Comment by rmartinc** [comment] 2023-08-14 09:54
Hi @Guesch! I think this is a duplicate of [#21791](https://github.com/keycloak/keycloak/issues/21791). Can you please check with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)? The fix will be probably release in the next 22.0.x micro release.

**Comment by mposolda** [comment] 2023-08-29 12:51
duplicates #21791 

I am closing as there is no additional response, so assuming that this is just a duplicate.
@rmartinc Thanks for checking this!

**Closed by mposolda** 2023-08-29 12:51 UTC
Labels: kind/bug, area/user-profile, team/core
