### ISSUE TITLE
Hard-coded signature algorithm in token verification

### ISSUE THREAD

**Issue by kwouters** [keycloak/keycloak#9771] opened 2022-01-25 10:12 UTC
### Describe the bug

For any connected Identity Provider, token verification fails if the IDP issues tokens signed with ES256 or PS256.

The use of RSA is hard-coded in
https://github.com/keycloak/keycloak/blob/8ed7c0544fb10e66e1e033b2c0f3b0fbdeeb6e28/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L535 

The use of RS256/384/512 is hardcoded in 
https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/core/src/main/java/org/keycloak/jose/jws/crypto/RSAProvider.java#L36 

This also means that a Keycloak instance configured to use e.g. EC-only signed tokens, cannot be used as an IDP in another Keycloak instance...

### Version

16.1.0

### Expected behavior

Keycloak should support IDPs (such as Keycloak :-) ) that issue PS256/384/512 and/or ES256/384/512 - issued tokens.

### How to Reproduce?

Set up two Keycloak instances; configure one of them (KC1) to issue ES256 or PS256 - signed tokens.
In the other Keycloak instance (KC2), configure KC1 as an IDP.
Login to KC2 with an account on KC1.

**Comment by rmartinc** [comment] 2023-02-18 17:56
I think this one is duplicate of #11036 and already fixed by #11121. Closing as done.

**Closed by rmartinc** 2023-02-18 17:56 UTC
Labels: area/oidc, kind/bug, status/triage
