### ISSUE TITLE
Backwards compatibility of UserInfoEndpoint

### ISSUE THREAD

**Issue by CharkeyQK** [keycloak/keycloak#16989] opened 2023-02-10 06:40 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I have MinIO Keycloak integration using OIDC. Working well with keycloak version 19.0.1. After update keycloak to latest version 20.0.3, minio console got 500 error when post request to keycloak UserInfoEndpoint without header. 
As I check the code of Keycloak and MinIO(also you can see at [this issue of minio](https://github.com/minio/minio/issues/16585)), it seems like the keycloak and client should all follow the RFC at the first time, but now keycloak correct the method **issueUserInfoPost** with RFC strictly, but lack backwards compatibility? All clients will go 500 error if they post request to keycloak UserInfoEndpoint without header.

### Version

20.0.3

### Expected behavior

Backwards compatibility support?

### Actual behavior

lack backwards compatibility

### How to Reproduce?

1. Install keycloak version 20.0.3;
2. MinIO Keycloak integration done;
3. login with sso at Minio Console;
4. 500 error shows;

### Anything else?

I think this issue should be fixed by clients, but I also think keycloak should follow the RFC at the first time, sad~ just figure it out.

**Comment by rmartinc** [comment] 2023-02-13 10:41
@CharkeyQK I think this issue probably was fixed with https://github.com/keycloak/keycloak/issues/15429 that will be included in keycloak 21 when released.

Can you please check compiling keycloak yourself and doing a quick test to ensure it's the same?

Thanks!

**Comment by rmartinc** [comment] 2023-02-13 10:43
Duplicate of #15429

**Comment by pedroigor** [comment] 2023-02-16 11:34
Closed as duplicated.

**Closed by pedroigor** 2023-02-16 11:34 UTC
Labels: kind/bug, area/core
