### ISSUE TITLE
User Profile Translations are not saved correctly

### ISSUE THREAD

**Issue by btarhan** [keycloak/keycloak#28379] opened 2024-04-02 18:28 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When creating or updating attributes in the user profile tab, on the nightly build there is translations modal that requires updating. However, regardless of if this field has been filled out in the past, it will always require you to fill it out before saving the attribute.

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Once the translation has been saved once, it will be persisted and can be edited, but will still show up there.

### Actual behavior

The translation is either not saved, or not loaded correctly when the attribute is loaded, so when you are editing an attribute, the translations are always blank.

### How to Reproduce?

- Click edit on a managed attribute
- Click the translation button
- Add a translation
- Save the attribute
- Edit the same attribute
- Click translations -> the translation is not there

**Comment by ssilvert** [comment] 2024-04-02 19:56
Closing as a duplicate of https://github.com/keycloak/keycloak/issues/27837

**Closed by ssilvert** 2024-04-02 19:56 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui
