### ISSUE TITLE
Error ERR_REQUIRE_ESM when create new KeycloakAdminClient()

### ISSUE THREAD

**Issue by Chatard38** [keycloak/keycloak#19829] opened 2023-04-20 07:32 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/cli

### Describe the bug

My tsconfig.json

```
`{
"compilerOptions": {
"target": "es2016", 
"lib": ["es6"], 
"module": "CommonJS", 
"rootDir": "src", 
"resolveJsonModule": true, 
"allowJs": true, 
"outDir": "build", 
"esModuleInterop": true, 
"forceConsistentCasingInFileNames": true, 
"noImplicitAny": true, 
"skipLibCheck": true 
}
}`
```

My package.json

```
`{
  "name": "stade-user-to-keycloak",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "ts-node src/index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^18.15.11",
    "nodemon": "^2.0.22",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4"
  },
  "dependencies": {
    "@keycloak/keycloak-admin-client": "^21.0.2"
  }
}
`
```

My script : 
```
import KeycloakAdminClient from "@keycloak/keycloak-admin-client";
import { type } from "os";

const keycloakAdminClient = new KeycloakAdminClient();
```

And the result : 

```
julien@julien-Virtual-Machine:~/gitLab/stade-user-to-keycloak$ npm start

> stade-user-to-keycloak@1.0.0 start
> ts-node src/index.ts

/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/julien/gitLab/stade-user-to-keycloak/node_modules/@keycloak/keycloak-admin-client/lib/index.js from /home/julien/gitLab/stade-user-to-keycloak/src/index.ts not supported.
Instead change the require of index.js in /home/julien/gitLab/stade-user-to-keycloak/src/index.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/julien/gitLab/stade-user-to-keycloak/src/index.ts:6:49)
    at m._compile (/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/bin.js:54:12)
    at main (/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/julien/gitLab/stade-user-to-keycloak/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Version

 Server Version	15.1.1

### Expected behavior

Just waiting for it to compile

### Actual behavior

I have an error : Error ERR_REQUIRE_ESM 

### How to Reproduce?

Take my config in the message and try ...

**Comment by jonkoops** [comment] 2023-04-20 12:44
Duplicate of https://github.com/keycloak/keycloak-nodejs-admin-client/issues/523

**Closed** 2023-04-20 12:45 UTC
Labels: kind/bug, area/admin/cli, team/cloud-native, status/triage

**Comment by feyzullahyildiz** [comment] 2023-04-29 22:29
> Duplicate of [keycloak/keycloak-nodejs-admin-client#523](https://github.com/keycloak/keycloak-nodejs-admin-client/issues/523)

It is happening in version @21.0.2
Duplicated issues version was 19

**Comment by TBG-FR** [comment] 2023-05-22 10:29
Looks like your best shot when you want to use `keycloak-admin-client` is to use a custom package that forks and rebuilds it, to be able to use it and avoid this issue (_caused by a ~bad~ decision that slows down a lof of developers during the setup of projects using keycloak-admin-client, if you read the linked thread_)

If you don't want to do it yourself, you can use someone else's fork, like this one : [Github ](https://github.com/s3pweb/keycloak-admin-client-cjs) or [NPM](https://www.npmjs.com/package/@s3pweb/keycloak-admin-client-cjs)

Let's thank the folks that provided solutions in the Github issue thread https://github.com/keycloak/keycloak-nodejs-admin-client/issues/523 and those who built packages following their instructions 🙌 

Works like a charm ! (_could easily be included in the official repo, imo..._)

**Comment by jonkoops** [comment] 2023-05-23 15:33
Your best shot at using this package is to convert your application code to use ECMAScript modules, especially when starting a new project there is little to no reason to choose CommonJS.

**Comment by j-d-carmichael** [comment] 2023-09-29 11:07
@jonkoops - this is simply not always possible ergo this is not really a valid answer.

**Comment by j-d-carmichael** [comment] 2023-09-29 11:10
Thanks for the NPM link @TBG-FR
