### ISSUE TITLE
Duplicate path in groups claim

### ISSUE THREAD

**Issue by nevlkv** [keycloak/keycloak#23900] opened 2023-10-11 11:12 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

Create group with subgroups, and single group

in token group claim containes duplicates and no chances to identify group

![изображение](https://github.com/keycloak/keycloak/assets/46656585/f6670179-a66c-49f0-966f-3332fd0d3101)

user membership

![изображение](https://github.com/keycloak/keycloak/assets/46656585/d6d380fa-a92d-4f13-8d3c-6f7f45ab8275)

token claims:

```
  "groups": [
    "/admin",
    "/test/developer",
    "/harbor.admin",
    "/test/lead",
    "/test/lead"
  ],

```

### Version

21.1.1

### Expected behavior

Neded custom child group separator, or deny create groups with "/" in names 

### Actual behavior

duplicate path with groups wich not equal

### How to Reproduce?

create groups, get token

**Comment by jonkoops** [comment] 2023-10-14 12:00
Possible duplicate of #23966

**Comment by rmartinc** [comment] 2023-10-16 10:32
@jonkoops I think it's not a duplicate, this is different. IIUIC this is just  a problem that the we can have one group that is named `test/lead` (with the slash) and we have another one that is `test` and a child `lead`. Both go to the same path `/test/lead`.

Another option nor mentioned is escaping slashes in the name (first one would be `/test\/lead` or similar). But anyway I think we have numerous incompatibilities no matter what we decide to do.

**Comment by pedroigor** [comment] 2024-01-05 12:51
@mposolda @rmartinc Do we want to do something in terms of validation or escaping?

IMO, we should at least escape names when adding groups into the token. Not necessarily on rest?

**Comment by rmartinc** [comment] 2024-01-08 09:42
@pedroigor I vote to add some escaping when creating the full-path and when reading a full-path. For sure there are setups that have groups with a "/" in the name (for example when they are imported from LDAP via mapper), so I would not prevent create them. But adding the escape can break something, because now the returned full-path would be different if having a slash (I don't expect a lot of cases but there can be some of them)... Do we need some backward compatibility option somewhere?

**Comment by pedroigor** [comment] 2024-01-09 13:58
Yeah, I think we should allow slashes in names but escape when adding to tokens. Mainly if you have configured the mapper to set the path and not the name of groups (e.g.: `Full group path` enabled).

**Closed** 2024-04-12 08:53 UTC
Labels: area/oidc, kind/bug, priority/important, team/core-clients
