### ISSUE TITLE
Setting admin theme to anything else than keycloak.v2 breaks the admin UI

### ISSUE THREAD

**Issue by ygerg** [keycloak/keycloak#21987] opened 2023-07-26 11:14 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Setting the admin theme to anything else than keycloak.v2 will break the admin UI, and I cannot login anymore as admin

Similar stack trace
https://github.com/keycloak/keycloak/issues/12619

### Version

tested with nightly and 22.0.1

### Expected behavior

The admin UI should load normally.

I would expect the admin UI to fall back to a working option, if a custom theme is provided.

### Actual behavior

It's impossible to load or log in to the admin UI.

### How to Reproduce?

- Spin up a container
- Log in as admin
- Change the master real theme to `base`
- Log out and see the error message appear

```
We are sorry...
An internal server error has occurred
```

### Anything else?

Bumped into this while upgrading an installation to the latest version. Would be great if there was an option to specify default theme for each category, as I would only need the `login` and `welcome` pages to default to our custom theme!

**Comment by sschu** [comment] 2023-07-26 11:41
This is a duplicate of https://github.com/keycloak/keycloak/issues/21421.

**Closed by sschu** 2023-07-26 11:41 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by jonkoops** [comment] 2023-07-27 09:33
Duplicate of #21421
