### ISSUE TITLE
authBaseUrl error on different hostname-admin-url, hostname-url

### ISSUE THREAD

**Issue by thundercost** [keycloak/keycloak#19070] opened 2023-03-16 12:44 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

On keycloak 21.0.1, we have hostname-admin-url, hostname-url configured with different values e.g 
--hostname-admin-url=admin.example.com
--hostname-url=auth.example.com
The above urls are configured as virtualhosts on reverse proxy
When I create a new realm, the default value ${authBaseUrl} is configured for all the clients.
The value of ${authBaseUrl} is always the value of hostname-admin-url, not hostname-url

### Version

21.0.1

### Expected behavior

The value of ${authBaseUrl} is the hostname-url

### Actual behavior

The value of ${authBaseUrl} is the hostname-admin-url

### How to Reproduce?

1. Start keycloak 21.0.1 with different hostname-admin-url, hostname-url
2. Use the hostname-admin-url to login and configure a new realm
3. Check on any client that ${authBaseUrl} is configured as Root URL
4. Confirm that ${authBaseUrl} is resolved to hostname-admin-url

**Comment by kkcmadhu** [comment] 2023-03-16 15:29
i can vouch, i had the same problem from keycloak 18 or 19 onwards.. 
The thing is when you access using hostname-admin-ur the keycloak oauth redirects uses {authBaseUrl}  :(

**Comment by belfhi** [comment] 2023-04-21 10:12
I can confirm that this is still an issue in Keycloak 21.1.0. Any ideas if there is a way to set hostname and admin hostname differently without ${authBaseUrl} getting set wrong?

**Comment by alfayez91** [comment] 2023-05-21 08:45
I have same issue in keycloak 21.1.1

**Comment by mposolda** [comment] 2023-05-23 06:35
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by vmuzikar** [comment] 2024-02-29 16:49
Reassigning to core as it seems clients use bad URL typ for base URL.

**Comment by calebTree** [comment] 2024-03-09 21:00
### In my situation I have:
`KC_HOSTNAME: iam.domain.tld`
`KC_HOSTNAME_ADMIN: kc-admin.domain.tld`
- Issue:
  - `${authBaseUrl}` resolves to `kc-admin.domain.tld`
  - `${authAdminUrl}` also resolves to `kc-admin.domain.tld`

My understanding, is for the "user account management" URLs to work correctly, given this configuration, one must manually set the `Root URL` value of the `account` and `account-console` built-in KC clients to `iam.domain.tld`, instead of the default `${authBaseUrl}` which again resolves to `kc-admin.domain.tld`.

**Comment by adamsmith959** [comment] 2024-03-10 23:49
Exactly the same problem here as @calebTree describes.

**Comment by FSeifer** [comment] 2024-05-27 09:48
This is still an issue as of 24.04.

Please see my original Bug-Ticket: 
https://github.com/keycloak/keycloak/issues/27203

This should be fixed as it can lead to very frustatring error searches, when you knwo you have set the URLs correctly but keycloak does not use them as such.

Regards,
Florian

**Comment by vmuzikar** [comment] 2024-05-27 13:03
@FSeifer Based on the comment from @pedroigor, seems we cannot reproduce the issue. Would you be able to provide some steps where exactly is `authBaseUrl` resolved to frontend URL?

**Comment by FSeifer** [comment] 2024-05-28 07:32
@vmuzikar 

I can't really give you more info than I did in my Ticket.

If you start keycloak with the following 2 options:

--hostname-url: https://someurl.company.com
--hostname-admin-url: https://someurl.company.com:9000

So the ONLY difference is the Port for the admin-pages, keycloak uses the Port 9000 Url for both the 
$baseUrl Variable in the client section and $baseAdminUrl
This leads to invalid Urls used for the default "account" and "account-console" Urls.

See the attached screenshots for clarification.

![actual_variable_values](https://github.com/keycloak/keycloak/assets/72611412/fe5ca0a0-f193-4be5-a59b-0d20008ca2a9)
![AuthAdminURL-Default](https://github.com/keycloak/keycloak/assets/72611412/763836c9-5a8a-4b1c-8f11-49a874453ae6)
![AuthBaseURL-Default](https://github.com/keycloak/keycloak/assets/72611412/a85eaedd-8481-4c32-8ee1-a9c97a4d76db)

**Comment by vmuzikar** [comment] 2024-05-28 08:01
@FSeifer Thank you, that helped. I think I know what's happening there. The UI isn't reflecting the URL type when expanding/replacing the variable:
https://github.com/keycloak/keycloak/blob/153d1a98418c4f9c6dce006cdf99f14fd6f48254/js/apps/admin-ui/src/utils/client-url.ts#L17-L20
It always replaces it with the base URL regardless if it's admin URL or frontend URL.

Reopening.

**Comment by FSeifer** [comment] 2024-05-28 08:05
@vmuzikar 
But it presents as the other way around:

It always uses the Admin-URL (The one on Port 9000 and not 443)  even when it should use the BaseURL as in for the "normal" account Urls.

Regards
Florian

**Closed** 2024-07-02 11:42 UTC
Labels: kind/bug, priority/important, area/admin/ui, team/ui

**Comment by stianst** [comment] 2024-07-17 07:50
@edewit moving back to Ready for backport as this is still marked as should be backported to 22 and 24.

**Comment by edewit** [comment] 2024-07-18 06:05
But this only needed fixing in 25 because it was introduced by a refactor
