### ISSUE TITLE
Localhost without TLS: Safari Browser Login Failure: error="cookie_not_found"

### ISSUE THREAD

**Issue by cachescrubber** [keycloak/keycloak#33926] opened 2024-10-15 07:34 UTC
### Area

authentication

### Describe the bug

I have a set of selenium based integration tests to verify sso logins with keycloak. Keycloak is running in Docker, without TLS configured. Access to Keycloak is using http://localhost and a random port. The integration tests fail with Safari. Chrome and Firefox are not affected. Versions up to 25.0.6 work as expected.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

SSO Login via http://localhost works.

### Actual behavior

Login Attempts fail:

`16:29:11.776 [docker-java-stream-1814915070] INFO  keycloak:26.0.0_0 - STDOUT: 2024-10-14 14:29:11,792 WARN  [org.keycloak.events] (executor-thread-2) type="LOGIN_ERROR", realmId="afa50d3c-42a2-46b6-8096-abd20998074c", realmName="sso", clientId="keycloak-support-demo", userId="null", ipAddress="172.17.0.1", error="cookie_not_found"`

### How to Reproduce?

Start the Keycloak docker image and try to login with Safari

```
# docker run --rm -ti -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.0.0 start-dev
```

Try to login as admin/admin using Safari.

### Anything else?

https://www.keycloak.org/docs/latest/release_notes/index.html#removal-of-legacy-cookies

**Comment by jonkoops** [comment] 2024-10-15 07:38
Duplicate of #33557

**Closed by jonkoops** 2024-10-15 07:38 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients
