### ISSUE TITLE
token exchange: exchange-sequence fails with Client session for client 'client-exchanger' not present in user session

### ISSUE THREAD

**Issue by flyinfish** [keycloak/keycloak#30614] opened 2024-06-20 12:05 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

when i try to do a token-exchange in sequence it fails on the second exchange:
`[org.keycloak.services.managers.AuthenticationManager] Client session for client '..' not present in user session '..'`

still not shure if it's a plain "bug" or if i just miss something. i created https://stackoverflow.com/questions/78602573/keycloak-token-exchange-sequence with no input so far. 

there is a discussion to from https://github.com/keycloak/keycloak/discussions/17440#discussioncomment-9760955 from @ChrisBrandhorst which seems to hit the same issue

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

token exchange sequence should work for as many clients/audiences you like

### Actual behavior

the second exchange fails when initial token was received by `client_credentials` grant od public-client

### How to Reproduce?

https://github.com/keycloak/keycloak/pull/30615
`org.keycloak.testsuite.oauth.ClientTokenExchangeTest`
- `testExchangeSequenceStartedWithGrantTypePassword` works
- `testExchangeSequenceStartedWithGrantTypeClientCredentials` fails
- `testExchangeSequenceStartedWithGrantTypePasswordOnPublicClient` fails

https://github.com/flyinfish/keycloak-examples/blob/main/token-exchange-sequence/README.md

**Comment by flyinfish** [comment] 2024-06-20 12:10
opened https://github.com/keycloak/keycloak/pull/30615 which adds test to reproduce the behaviour

**Comment by mposolda** [comment] 2024-06-21 09:27
Thanks for the info. I am triaging it as lower priority as it is not clear that this is bug at all and it is related to token-exchange, which is preview feature.

**Comment by rmartinc** [comment] 2024-06-21 11:52
I have been checking this problem a bit and the root cause is that the client session is created for the target client but the in the token the `azp` (issuedFor) is set to the requester client. This way when the client session is checked in the auth manager it is detected as nonexistent ([here](https://github.com/keycloak/keycloak/blob/25.0.1/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1481-L1482)). The reason is the session was created for target client but in the azp is the requester client (and therefore it's not found).

@pedroigor Why the azp is set to the requester client? Should not be the target client? In the end the token is issued for the target client although initiated by the requester... I did a quick change in this [branch](https://github.com/rmartinc/keycloak/tree/issue-30614) and I can exchange three times with no issue. But there are tests that are testing the azp is the requester client. So I'm asking you... :smile:

**Comment by flyinfish** [comment] 2024-06-23 16:16
Thanks @rmartinc for exploring. I agree that the `azp` is somehow the key to the solution. 

The biggest question for us was if this is such an edge case that it does not work. Would it not be the normal case `testExchangeSequenceStartedWithGrantTypePasswordOnPublicClient` starting with a token from a SPA/public client and then exchange it from microservice to microservice as deep as you want?

im out of office for 2 weeks now so sorry when i might not respond to further discussions immediately.

**Comment by pedroigor** [comment] 2024-06-24 15:03
The use case is valid and we need to make it work. It should not matter how much "deep" it is when chaining services and executing token exchanges.

IMO, the `azp` should reference the client to which the token is being issued for. The fact the session is created for the target client is a limitation in the sense that we (internally) create tokens within the scope of a client. When building a token using the `token-exchange` grant type, the client we need to operate is the target client because we'll be using the client scopes, mappers, etc, associated with this client.

I think we can change the validation logic to consider "token exchange tokens". In this case, the validation would take into account that the token, even though issued to `azp`, maps to a session (and a token) in the target client.

Wdyt?

**Comment by J0F3** [comment] 2024-06-25 07:32
> IMO, the azp should reference the client to which the token is being issued for.

I agree. The value of azp makes sense for me. 


> When building a token using the token-exchange grant type, the client we need to operate is the target client because we'll be using the client scopes, mappers, etc, associated with this client.

That makes also sense for me. 

What I do not understand yet is why it works when the first initial token was issued to a secure client with `grant_type=password` where the "chain" of client is actually the same.  (client1 -> client2 -> cleint3)

I assume it has something to do that in this case a user session is created right from the beginning for client1. Vs. with the other grant types where a user session is only created for client2 when the first token exchange is made. But for client1 there is actually no session at all. Is that the difference which makes the validation to fail when the token exchange is made the second time (client2 tries to exchange the token to token for accessing client3)?

**Comment by J0F3** [comment] 2024-06-28 07:41
@rmartinc @pedroigor I did some also some debugging to see what actually happens during the token exchange and when the error accours. So my conclusion for now is the following:

> Why the azp is set to the requester client? Should not be the target client? In the end the token is issued for the target client although initiated by the requester..

The azp is correctly set to the requester client because he is the actual holder of the token which allows him then to call the traget client. 

But what is the root of the problem IMHO is that the session is created for the target client instead of the requester client which is the actual client which gets the token and is therefore in the azp claim. This lead then to the problem that the requester client is not in the session when target client tries to exchange the token again. 
So I am wondering if session can not be created for the requester client instead so that the client which is actually doing the token exchange has actually also a session. But I assume that is what @pedroigor means by "limitation"?:
> The fact the session is created for the target client is a limitation in the sense that we (internally) create tokens within the scope of a client.

> I think we can change the validation logic to consider "token exchange tokens". In this case, the validation would take into account that the token, even though issued to azp, maps to a session (and a token) in the target client.

To change the validation logic would probably also help (@rmartinc  I see you have already created a PR which such a change) but I think the session handling looks then still a bit strange. Because when you look at the Session in the Admin UI for example you will never see that the requester client is part of the session. Which makes it very confusing in my option. I think the requester client of the token exchange should be visible in the session because he gets and can use  the exchanged token.

**Comment by rmartinc** [comment] 2024-06-28 08:12
@J0F3 What I'm trying in my PR is just setting in the user session that it is a Token Exchange session and it's really for the target client. As any TE request creates a new session, the requester calls TE to get a target token, the session is created with a note that indicates is for target (and not for the requester). You can try with my PR to see if it works for you.

**Comment by J0F3** [comment] 2024-06-28 08:45
@rmartinc Yes I will try with your PR. Thank you. 

> the session is created with a note that indicates is for target (and not for the requester)
I got that. But I think this is at least part of the problem and the validation is actually ok as it is.  

Why should the session not be created for the requester? I mean when the User logs in to a SPA using the session is also created for public-spa client event though the audience of the issues Token is a different client. I think the same should be made also for the token exchange. Because the requester client is the client for which the token is issued and not the target client. The target client is just the audience of the token but the target client does actually not hold the token. Thus the session for the target client makes in my opinion no sense here. 
Or is that some sort of technical limitation and it is simply not possible to set the session for the requester client during the Token Exchange?

**Comment by rmartinc** [comment] 2024-06-28 10:17
@J0F3 I'll give it a try, I don't know in advance if it's complicated or not.

**Comment by J0F3** [comment] 2024-06-28 13:28
@rmartinc I am trying to test your PR. But how can I start the Keycloak server correctly so the Token Exchange Feature is actually active? When I start the Keycloak as described here: https://github.com/keycloak/keycloak/blob/main/docs/building.md#starting-keycloak the Token Exchange feature is disabled. Event when I start it with ` java -jar quarkus/server/target/lib/quarkus-run.jar start-dev --features=preview` the Token Exchange Feature is still disabled. Thanks and sorry for the rookie question! 😄

**Comment by rmartinc** [comment] 2024-07-01 15:35
Checking if I could change the session I have realized that we can fix this much more easily. The problem is a bit different to what we have explained in the previous comments. The root cause of the reproducer is that the initial session is created with a `client_credentials` request, which uses a transient session (by default `Use refresh tokens for client credentials grant` is false). But after that, the first TE request creates a persistent session which obviously lacks the session for the initial client. If teh client is configured to generate refresh tokens for client credentials the TE exchange works, because the session is persistent and the initial client has a session.

I think that if the initial session is transient (like `client_credentials`) TE should not create a persistent session but another transient session. That way the session is always transient (limited to the token with no session at server side).

**Comment by rmartinc** [comment] 2024-07-02 09:19
@J0F3 I think that yes, both cases are tested. In the reproducer provided if you just change the client_credentials to have persistent session the reproducer does not fail. It's also a workaround for the moment. The idea is, if the session is persistent, the initial client has a session created (because the token is valid and the client session should be there). And if the session is transient (like with client_credentials default behavior) it also works the first time (because everything is set correctly as transient). The problem was in after the first TE because the session was now persistent but the first client had no session in it as it was initially transient.

**Comment by J0F3** [comment] 2024-07-02 16:23
@rmartinc 

> If teh client is configured to generate refresh tokens for client credentials the TE exchange works

Just to be sure. You a referencing to the following setting of the client right?:
 
![image](https://github.com/keycloak/keycloak/assets/12759579/7a28407c-f667-4424-8362-20761c898de8)


I tested it briefly and I think I can confirm that when this setting is enabled on the clients the TK exchange works as expected when using `client credentials`. But with a public client initially and 'password' or 'authorization_code' grant I get still the same error after the first exchange. 

In the Admin UI there can also now seen a session which makes sense for when using the "client credential" flow and where all clients are part of it.
![image](https://github.com/keycloak/keycloak/assets/12759579/cd87e122-db36-4fbc-89a5-ba7007762c86)
(service-1-client is the client used to get the initial token with "client credentials")

But for login with a public client and with "password" or "authorization_code" flow the session is still missing the service-1-client.
![image](https://github.com/keycloak/keycloak/assets/12759579/5b6e1633-ed53-48ef-8b11-443fd331f208)
Which then still lead to the error `Client session for client 'service-1-client' not present in user session '...'` 

So it seems the persistent session helps when using "client credentials" grant. (service to service communication) but not when a an actual user session exists when using "password" or "authorization_code" grant initially. 

But when I understand you correctly, with your PR the situation would be different because the TE does not create persistent session anymore.  Which is not quite the same as when enabling the "Use refresh tokens for client credentials grant" setting, right?

**Comment by rmartinc** [comment] 2024-07-02 16:31
Try to test with my PR. There can be still some corner case because your scenario is even more complicated.

**Comment by J0F3** [comment] 2024-07-04 10:17
@rmartinc I was nun finally able to start keyvault from source and test our scenarios with both of your PRs. Here are my findings:

https://github.com/keycloak/keycloak/pull/30975:
- When using "client credential" grant initially -> 🆗 TE works as expected
- When using "authorization_code" grant -> ❌ "invalid token" error on second TE
The same error happens after the first TE. I assume that is because in this case a persistent session exists which does not contain the client doing the second TE. (as described already above).

To have the full picture I tested also with https://github.com/keycloak/keycloak/pull/30905:
- When using "client credential" grant initially -> 🆗 TE works as expected
- When using "authorization_code" grant -> 🆗 TE works as expected


So I think the cause for the error is indeed a bit different for when using client credential grant (which is basically service-to-service communication without any user account involved) and for when authorization code grant (or similar) is used where initially a user account has logged in and has a session (the Tokens contains the also claims with information about the user account). 

For the service-to-service communication  is think [#30957](https://github.com/keycloak/keycloak/pull/30975) would be the best solution. 

For the scenario where a user is logged in I think the best would be when the session, created during the TE is created for the requester client (instead of the target client). This way the session information (shown in the Admin UI) would make sense and the token validation would be correct also for the second TE.

**Closed** 2024-07-08 18:44 UTC
Labels: kind/bug, area/token-exchange, help wanted, team/core-clients, status/auto-expire, status/auto-bump, priority/normal

**Comment by flyinfish** [comment] 2024-07-09 12:51
Thank you @rmartinc @pedroigor for tackling the problem and @J0F3 for commenting and testing

unfortunately only half the problem is solved now - see comment above https://github.com/keycloak/keycloak/issues/30614#issuecomment-2208622982

> When using "client credential" grant initially -> 🆗 TE works as expected
When using "authorization_code" grant -> ❌ "invalid token" error on second TE

the problem still exists when using "authorization_code" grant for the first initial token

can you please reopen this issue?

**Comment by rmartinc** [comment] 2024-07-09 13:37
@flyinfish please file a new issue with clear reproducer steps similar to https://github.com/flyinfish/keycloak-examples/blob/main/token-exchange-sequence/README.md in this issue.

**Comment by flyinfish** [comment] 2024-07-10 07:03
> @flyinfish please file a new issue with clear reproducer steps similar to https://github.com/flyinfish/keycloak-examples/blob/main/token-exchange-sequence/README.md in this issue.

@rmartinc i updated the reproducer above with https://github.com/keycloak/keycloak/issues/31180 - thx
