### ISSUE TITLE
start-dev: creation of temporary admin account broken

### ISSUE THREAD

**Issue by jnfingerle** [keycloak/keycloak#35761] opened 2024-12-10 12:18 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The creation of the temporary admin account is broken. I'm stuck in a screen that tells me "Local access required
You will need local access to create the temporary administrative user. To create the temporary administrative user open http://localhost:8080/, or use a bootstrap-admin command."

### Version

26.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

1. When starting a newly downloaded install of keycloak by running `bin\kc.bat start-dev` on the command line, navigating to http://localhost:8080/ should show me a page to create a temporary admin user. After creation I should automatically navigate to the login screen where I should be able log in as the newly created admin user.
2. When doing the same, but with environment variables KC_BOOTSTRAP_ADMIN_USERNAME and KC_BOOTSTRAP_ADMIN_PASSWORD set, I should skip account creation, but be directy sent to the login screen. I should be able to log in using the credentials from the environment variables.

### Actual behavior

In both cases (with or without environment variables): When starting a newly downloaded install of keycloak by running `bin\kc.bat start-dev` on the command line, navigating to http://localhost:8080/ shows a screen "Local access required
You will need local access to create the temporary administrative user. To create the temporary administrative user open http://localhost:8080/, or set the environment variables KC_BOOTSTRAP_ADMIN_USERNAME and KC_BOOTSTRAP_ADMIN_PASSWORD when starting the server."

On the very same machine this works as expected with older versions of keycloak (26.0.6 in case of environment variables, 26.0.5 without environment variables).

### How to Reproduce?

On a Windows Server machine 
* install OpenJDK 23 (download, unpack, set `JAVA_HOME` and `PATH`)
* download https://github.com/keycloak/keycloak/releases/download/26.0.7/keycloak-26.0.7.zip
* unzip and navigate to the unzipped code
* open a command prompt
* depending on the case: set the environment variables using `set KC_BOOTSTRAP_ADMIN_USERNAME=test` and `set KC_BOOTSTRAP_ADMIN_PASSWORD=test`
* start `bin\kc.bat start-dev`
* after startup navigate to http://localhost:8080/ 

### Anything else?

This was first reported to us by one of our customers. So this is not a local issue.

We haven't tested this under linux.

**Comment by jnfingerle** [comment] 2024-12-10 12:31
The error message in the description is from the nightly build. The error message in "actual behaviour" is from 26.0.7.

**Comment by shawkins** [comment] 2024-12-10 14:15
Duplicate of #35675

**Closed by shawkins** 2024-12-10 14:15 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui

**Comment by MATRIT4** [comment] 2024-12-12 06:56
use 127.0.0.1 instead of localhost

![localhost](https://github.com/user-attachments/assets/cfc942c4-e6be-4441-8982-338635e0c873)

![127](https://github.com/user-attachments/assets/ba4b616c-72d7-452d-bbf0-074dd0ccc74b)

**Comment by fokher** [comment] 2024-12-18 16:50
> use 127.0.0.1 instead of localhost
> 
> ![localhost](https://private-user-images.githubusercontent.com/170961517/395042540-cfc942c4-e6be-4441-8982-338635e0c873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDAyNjIsIm5iZiI6MTczNDUzOTk2MiwicGF0aCI6Ii8xNzA5NjE1MTcvMzk1MDQyNTQwLWNmYzk0MmM0LWU2YmUtNDQ0MS04OTgyLTMzODYzNWUwYzg3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxNjM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2E2ZGFlZGFiNzA3OTMwYWEzNTA3ODc1MDIwMjdmODdiMjUyYWIzOTdhM2VkZmY1YmNlNjlkMzU4Njc1N2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HDcjKjxYGr29NfUug14uL-Ni4tfvwazcNNZobZv_joU)
> 
> ![127](https://private-user-images.githubusercontent.com/170961517/395042595-ba4b616c-72d7-452d-bbf0-074dd0ccc74b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDAyNjIsIm5iZiI6MTczNDUzOTk2MiwicGF0aCI6Ii8xNzA5NjE1MTcvMzk1MDQyNTk1LWJhNGI2MTZjLTcyZDctNDUyZC1iYmYwLTA3NGRkMGNjYzc0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxNjM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDZmYzVlYjMxOWZmMzgyY2FjNTQ1OTk0M2FlOGIxN2Y3ODUxODA1ZTFjNTQ0ZDNmM2UxMzEzNjgyNTQxNjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mNgtQT52SHUBuQIoIX_KFaR5CQwlfei-irShu5csFh4)

**Comment by fokher** [comment] 2024-12-18 16:53
@MATRIT4 that's right. It's walk to me. Thank you. Truly, just change localhost to 127.0.01.

**Comment by kathija-aafiya29** [comment] 2024-12-23 11:48
@MATRIT4 just put this line (# http-listener=localhost:8080) in your keycloack.conf . then this url  http://localhost:8080 will works

**Comment by itsmesangram5** [comment] 2024-12-23 17:47
Thank you so much @MATRIT4 ..helps me a lot

**Comment by fokher** [comment] 2024-12-23 18:16
> @MATRIT4 just put this line (# http-listener=localhost:8080) in your keycloack.conf . then this url http://localhost:8080 will works

Thank's you. This help me to configure http to listen on my local machine for others on my local network

**Comment by jonkoops** [comment] 2024-12-24 11:55
I am closing the discussion here as this issue has been resolved under #35675
