### ISSUE TITLE
Failure: FipsDistTest

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#23786] opened 2023-10-06 11:50 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ci

### Describe the bug

[Quarkus IT (ubuntu-latest, zip)](https://github.com/keycloak/keycloak/actions/runs/6328307513/job/17186649977)
[Quarkus IT (ubuntu-latest, zip)](https://github.com/keycloak/keycloak/actions/runs/6315071775/job/17148011571)

```
Error:  Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 515.524 s <<< FAILURE! - in org.keycloak.it.cli.dist.FipsDistTest
Error: OR] org.keycloak.it.cli.dist.FipsDistTest.testUnsupportedHttpsPkcs12KeyStoreInStrictMode(KeycloakDistribution)  Time elapsed: 130.938 s  <<< ERROR!
-- java.lang.RuntimeException: Failed to stop the server
```

```
Error:  Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 399.001 s <<< FAILURE! - in org.keycloak.it.cli.dist.FipsDistTest
Error: OR] org.keycloak.it.cli.dist.FipsDistTest.testUnsupportedHttpsJksKeyStoreInStrictMode(KeycloakDistribution)  Time elapsed: 130.851 s  <<< ERROR!
-- java.lang.RuntimeException: Failed to stop the server
```

Log:
```
FipsDistTest ++ 2023-12-03 00:46:35,780 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
FipsDistTest ++ 2023-12-03 00:46:37,200 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
FipsDistTest ++ 2023-12-03 00:46:37,965 TRACE [org.keycloak.common.crypto.CryptoIntegration] (main) Java security providers: [ 
FipsDistTest ++  KC(BCFIPS version 1.000203 Approved Mode, FIPS-JVM: unknown) version 1.0 - class org.keycloak.crypto.fips.KeycloakFipsSecurityProvider, 
FipsDistTest ++  BCFIPS version 1.000203 - class org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider, 
FipsDistTest ++  BCJSSE version 1.0016 - class org.bouncycastle.jsse.provider.BouncyCastleJsseProvider, 
FipsDistTest ++  SUN version 17 - class sun.security.provider.Sun, 
FipsDistTest ++  SunRsaSign version 17 - class sun.security.rsa.SunRsaSign, 
FipsDistTest ++  SunEC version 17 - class sun.security.ec.SunEC, 
FipsDistTest ++  SunJSSE version 17 - class sun.security.ssl.SunJSSE, 
FipsDistTest ++  SunJCE version 17 - class com.sun.crypto.provider.SunJCE, 
FipsDistTest ++  SunJGSS version 17 - class sun.security.jgss.SunProvider, 
FipsDistTest ++  SunSASL version 17 - class com.sun.security.sasl.Provider, 
FipsDistTest ++  XMLDSig version 17 - class org.jcp.xml.dsig.internal.dom.XMLDSigRI, 
FipsDistTest ++  SunPCSC version 17 - class sun.security.smartcardio.SunPCSC, 
FipsDistTest ++  JdkLDAP version 17 - class sun.security.provider.certpath.ldap.JdkLDAP, 
FipsDistTest ++  JdkSASL version 17 - class com.sun.security.sasl.gsskerb.JdkSASL, 
FipsDistTest ++  SunPKCS11 version 17 - class sun.security.pkcs11.SunPKCS11, 
FipsDistTest ++ ]
FipsDistTest ++ 2023-12-03 00:46:37,966 TRACE [org.keycloak.common.crypto.CryptoIntegration] (main) Security properties: [ 
FipsDistTest ++  Java security properties file: null
FipsDistTest ++  Default keystore type: pkcs12
FipsDistTest ++  KeyManagerFactory.getDefaultAlgorithm(): X.509
FipsDistTest ++  TrustManagerFactory.getDefaultAlgorithm(): PKIX
FipsDistTest ++  keystore.type.compat: true
FipsDistTest ++  javax.net.ssl.trustStoreType: null
FipsDistTest ++  javax.net.ssl.trustStore: null
FipsDistTest ++  javax.net.ssl.trustStoreProvider: null
FipsDistTest ++  javax.net.ssl.keyStoreType: null
FipsDistTest ++  javax.net.ssl.keyStore: null
FipsDistTest ++  javax.net.ssl.keyStoreProvider: null
FipsDistTest ++ ]
FipsDistTest ++ 2023-12-03 00:46:37,991 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: fv-az1208-412-5089, Site name: null
FipsDistTest ++ 2023-12-03 00:46:41,214 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
FipsDistTest ++ 
FipsDistTest ++ UPDATE SUMMARY
FipsDistTest ++ Run:                        117
FipsDistTest ++ Previously run:               0
FipsDistTest ++ Filtered out:                 0
FipsDistTest ++ -------------------------------
FipsDistTest ++ Total change sets:          117
FipsDistTest ++ 
FipsDistTest ++ 2023-12-03 00:46:46,091 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
FipsDistTest ++ 2023-12-03 00:46:46,150 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
FipsDistTest ++ 2023-12-03 00:46:47,237 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
FipsDistTest ++ 2023-12-03 00:46:47,323 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.infinispan.commons.IllegalLifecycleStateException: ISPN000323: realms is in 'TERMINATED' state and so it does not accept new invocations. Either restart it or recreate the cache container.
FipsDistTest ++ 	at org.infinispan.cache.impl.SimpleCacheImpl.getDataContainer(SimpleCacheImpl.java:1307)
FipsDistTest ++ 	at org.infinispan.cache.impl.SimpleCacheImpl.get(SimpleCacheImpl.java:559)
FipsDistTest ++ 	at org.infinispan.cache.impl.StatsCollectingCache.get(StatsCollectingCache.java:54)
FipsDistTest ++ 	at org.infinispan.cache.impl.EncoderCache.get(EncoderCache.java:762)
FipsDistTest ++ 	at org.keycloak.models.cache.infinispan.CacheManager.get(CacheManager.java:95)
FipsDistTest ++ 	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:466)
FipsDistTest ++ 	at org.keycloak.services.managers.RealmManager.getRealmByName(RealmManager.java:98)
FipsDistTest ++ 	at org.keycloak.services.resources.RealmsResource.resolveRealmAndUpdateSession(RealmsResource.java:180)
FipsDistTest ++ 	at org.keycloak.services.resources.RealmsResource.getRealmResource(RealmsResource.java:196)
FipsDistTest ++ 	at org.keycloak.services.resources.RealmsResource$quarkusrestinvoker$getRealmResource_40080643164dd4bff8adf35fd68260654e9c3eab.invoke(Unknown Source)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
FipsDistTest ++ 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
FipsDistTest ++ 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
FipsDistTest ++ 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
FipsDistTest ++ 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
FipsDistTest ++ 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
FipsDistTest ++ 	at java.base/java.lang.Thread.run(Thread.java:840)
FipsDistTest ++ 
FipsDistTest ++ 2023-12-03 00:46:47,334 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Failed to create error page: org.infinispan.commons.IllegalLifecycleStateException: ISPN000323: realms is in 'TERMINATED' state and so it does not accept new invocations. Either restart it or recreate the cache container.
FipsDistTest ++ 	at org.infinispan.cache.impl.SimpleCacheImpl.getDataContainer(SimpleCacheImpl.java:1307)
FipsDistTest ++ 	at org.infinispan.cache.impl.SimpleCacheImpl.get(SimpleCacheImpl.java:559)
FipsDistTest ++ 	at org.infinispan.cache.impl.StatsCollectingCache.get(StatsCollectingCache.java:54)
FipsDistTest ++ 	at org.infinispan.cache.impl.EncoderCache.get(EncoderCache.java:762)
FipsDistTest ++ 	at org.keycloak.models.cache.infinispan.CacheManager.get(CacheManager.java:95)
FipsDistTest ++ 	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:466)
FipsDistTest ++ 	at org.keycloak.services.managers.RealmManager.getRealmByName(RealmManager.java:98)
FipsDistTest ++ 	at org.keycloak.services.error.KeycloakErrorHandler.resolveRealm(KeycloakErrorHandler.java:161)
FipsDistTest ++ 	at org.keycloak.services.error.KeycloakErrorHandler.getResponse(KeycloakErrorHandler.java:96)
FipsDistTest ++ 	at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:67)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.core.RuntimeExceptionMapper.mapException(RuntimeExceptionMapper.java:99)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.mapExceptionIfPresent(ResteasyReactiveRequestContext.java:337)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.handlers.ExceptionHandler.handle(ExceptionHandler.java:15)
FipsDistTest ++ 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
FipsDistTest ++ 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
FipsDistTest ++ 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
FipsDistTest ++ 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
FipsDistTest ++ 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
FipsDistTest ++ 	at java.base/java.lang.Thread.run(Thread.java:840)
FipsDistTest ++ 
FipsDistTest ++ 2023-12-03 00:46:47,337 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (executor-thread-1) MediaType not set on path /realms/master/, with response status 500
FipsDistTest ++ 2023-12-03 00:46:47,343 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to //realms/master/ failed, error id: 10caf4f4-30de-4d37-8568-265ac78eda16-1: jakarta.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
FipsDistTest ++ 	at org.keycloak.headers.DefaultSecurityHeadersProvider.addHeaders(DefaultSecurityHeadersProvider.java:75)
FipsDistTest ++ 	at org.keycloak.services.filters.KeycloakSecurityHeadersFilter.filter(KeycloakSecurityHeadersFilter.java:43)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
FipsDistTest ++ 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
FipsDistTest ++ 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
FipsDistTest ++ 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
FipsDistTest ++ 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
FipsDistTest ++ 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
FipsDistTest ++ 	at java.base/java.lang.Thread.run(Thread.java:840)
FipsDistTest ++ 
FipsDistTest ++ 2023-12-03 00:46:48,366 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to //realms/master/ failed, error id: 10caf4f4-30de-4d37-8568-265ac78eda16-2: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.instance(java.lang.Class, java.lang.annotation.Annotation[])" because the return value of "io.quarkus.arc.Arc.container()" is null
FipsDistTest ++ 	at org.keycloak.quarkus.runtime.integration.resteasy.ResteasyVertxProvider.getContextData(ResteasyVertxProvider.java:33)
FipsDistTest ++ 	at org.keycloak.common.util.Resteasy.getContextData(Resteasy.java:62)
FipsDistTest ++ 	at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:54)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.core.RuntimeExceptionMapper.mapException(RuntimeExceptionMapper.java:99)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.mapExceptionIfPresent(ResteasyReactiveRequestContext.java:337)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.server.handlers.ExceptionHandler.handle(ExceptionHandler.java:15)
FipsDistTest ++ 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
FipsDistTest ++ 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
FipsDistTest ++ 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
FipsDistTest ++ 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
FipsDistTest ++ 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
FipsDistTest ++ 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
FipsDistTest ++ 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
FipsDistTest ++ 	at java.base/java.lang.Thread.run(Thread.java:840)
FipsDistTest ++ 
```

### Version

latest

**Comment by ahus1** [comment] 2023-10-31 11:13
Another failure: https://github.com/keycloak/keycloak/actions/runs/6694897410/job/18190013692

**Comment by stianst** [comment] 2023-12-13 08:44
See https://stianst.github.io/keycloak-dashboard/tests#failed-job-quarkus-it for more failures caused by this issue

**Comment by shawkins** [comment] 2024-01-09 18:01
The sequence is roughly:

- run is called
- the server fails to start properly - as is expected by the test
```
2024-01-07T00:52:43.8944510Z FipsDistTest ++ 2024-01-07 00:52:43,121 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-01-07T00:52:43.8945304Z FipsDistTest ++ 2024-01-07 00:52:43,121 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2024-01-07T00:52:43.8946110Z FipsDistTest ++ 2024-01-07 00:52:43,121 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.lang.IllegalArgumentException: malformed sequence
2024-01-07T00:52:43.8946737Z FipsDistTest ++ 2024-01-07 00:52:43,121 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: malformed sequence
2024-01-07T00:52:43.8947956Z FipsDistTest ++ 2024-01-07 00:52:43,121 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
- the process does not exit within 2 minutes
- the distribution readiness check throws an exception and the test fails

There's no indication in the logs why the process did not exit in a timely manner. 

So we either need to figure out why on GHA some processes are taking a long time to exit, or we could do the run in an async manner so that the output could be checked before the run call completes.

**Comment by shawkins** [comment] 2024-01-10 17:20
I believe the underlying cause is with the transaction manager shutdown:

```
"main" #1 prio=5 os_prio=0 cpu=13493.67ms elapsed=113.30s tid=0x00007f7b5c0130b0 nid=0xfa8b3 in Object.wait()  [0x00007f7b614a2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.1/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@17.0.1/Object.java:338)
	at com.arjuna.ats.arjuna.coordinator.TransactionReaper.shutdown(TransactionReaper.java:760)
	- locked <0x00000000e2f01498> (a com.arjuna.ats.arjuna.coordinator.TransactionReaper)
	at com.arjuna.ats.arjuna.coordinator.TransactionReaper.terminate(TransactionReaper.java:969)
	- locked <0x00000000e2eef7f0> (a java.lang.Class for com.arjuna.ats.arjuna.coordinator.TransactionReaper)
	at io.quarkus.narayana.jta.runtime.NarayanaJtaRecorder.lambda$handleShutdown$3(NarayanaJtaRecorder.java:171)
	at io.quarkus.narayana.jta.runtime.NarayanaJtaRecorder$$Lambda$1058/0x000000080152c900.run(Unknown Source)
	at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:75)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:117)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:124)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.1/Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```
In reviewing the narayana code, there's a potential race condition - while the shutdown method is locked, the removeElementClient method is not and _inShutdown is not marked as volatile, but is accessed as if it is. 

It's possible for removeElementClient [1], to see _inShutdown as false even if the main thread has has entered the shutdown method - that would then cause the main method to not be notified and wait indefinitely.

[1] https://github.com/jbosstm/narayana/blob/05f4a5c1069e7971b6f707cdf806a0bb7c6387c3/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/TransactionReaper.java#L779

cc @keycloak/core

**Comment by shawkins** [comment] 2024-01-10 18:41
Captured upstream as https://issues.redhat.com/browse/JBTM-3830 - also proposed a PR to add a thread dump to help identify this sort of thing in the future.

**Closed** 2024-01-12 18:31 UTC
Labels: kind/bug, area/ci, team/continuous-testing, flaky-job
