### ISSUE TITLE
keycloak.js not handling `iss` param correctly.

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#22486] opened 2023-08-16 12:49 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/javascript

### Describe the bug

It looks like https://github.com/keycloak/keycloak/issues/20584 broke account console V2.

The `iss` parameter will be added to the browser URL, which React sees as invalid.  So you get this in your browser:
http://localhost:8180/realms/master/account/#/iss=http%3A%2F%2Flocalhost%3A8180%2Frealms%2Fmaster

Then account console V2 gives you this:

<img width="454" alt="InvalidRout" src="https://github.com/keycloak/keycloak/assets/507202/6d97ab80-fa58-4063-b548-77d6e3a75373">

I believe the problem is in keycloak.js, as the updated documentation says,
`However, some OpenID Connect / OAuth2 adapters, and especially older {project_name} adapters, may have issues with this new parameter.  For example, the parameter will be always present in the browser URL after successful authentication to the client application.`

@tnorimat, was keycloak.js meant to work properly with the `iss` param?

### Version

main

### Expected behavior

Account console V2 continues to work without error.

### Actual behavior

See error.

### How to Reproduce?

I have reproduced this quite easily, but @edewit can not reproduce on his machine.

### Anything else?

If you set `Exclude Issuer From Authentication Response` to true on the `account-console` client then the problem goes away.

**Comment by jonkoops** [comment] 2023-08-21 12:19
I'll see if I can make a fix for this one.

**Comment by ssilvert** [comment] 2023-08-21 19:22
The PR that added the `iss` is here: https://github.com/keycloak/keycloak/pull/20621

**Comment by SerhiiFilenko** [comment] 2023-09-11 07:27
Hello! Are there any updates on this issue? I have also encountered this problem. Is there any workaround for now?

**Comment by jonkoops** [comment] 2023-09-11 09:33
I am unable to reproduce this issue in the latest nightly, as well as in isolation using [a test project](https://github.com/jonkoops/kjs-playground). Looking at the source of Keycloak JS the `iss` parameter has been added correctly, and thus should be removed (which I can confirm in my testing).

This issue could possibly occur if one is using an older version of Keycloak JS on a newer version of the Keycloak server. Unless someone has a reproducible example in the latest nightly I see no other option but to close this.

**Comment by jonkoops** [comment] 2023-09-11 09:34
> Hello! Are there any updates on this issue? I have also encountered this problem. Is there any workaround for now?

@SerhiiFilenko are you on the latest version of the Keycloak server and Keycloak JS? Can you provide a reproducible example in [this project](https://github.com/jonkoops/kjs-playground)?

**Comment by SerhiiFilenko** [comment] 2023-09-11 12:13
No, I was running an older version 21.1.2 and resolved the issue for my purposes by downgrading the server version from nightly to 21.1. Thank you.

**Comment by jonkoops** [comment] 2023-09-11 12:15
Thanks for checking that. I will consider this issue resolved then. If anyone is able to reproduce this in the future feel free to let me know.

**Closed by jonkoops** 2023-09-11 12:15 UTC
Labels: kind/bug, impact/high, area/adapter/javascript, team/ui

**Comment by bilias** [comment] 2024-01-24 09:48
I got hit by this after account console login.
Keycloak is 23.0.4

I'm running custom theme for account for I've synced today resources and index.ftl
Still getting this.

I've tried to revert to keycloak.v2 in account theme but still got the error.

**Comment by jonkoops** [comment] 2024-01-24 10:05
@bilias please report this as a new issue with detailed steps on how to reproduce from a clean Keycloak installation.
