### ISSUE TITLE
Operator Only Allows you to Create One Keycloak Instance

### ISSUE THREAD

**Issue by silverbp** [keycloak/keycloak#21015] opened 2023-06-14 22:21 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

When you create more than one instance after installing the operator..

example..

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-01
  namespace: keycloak
```

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-02
  namespace: keycloak
```

I've left the rest of the configuration out of the example as it's not necessarily relevant, it is configured in such a way where they both function and come up, however.. what the operator creates for services won't work because the selector labels will hit ALL instances..

both keycloak-01-service and keycloak-02-service that were created by the operator have the following selector labels.

``` 
 selector:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
```

### Version

nightly

### Expected behavior

the keycloak service and keycloak discovery service would both have selectors that would limit it to the instance name and pods running under the instance name.

### Actual behavior

The services created by the operator, both the keycloak-service and keycloak-discovery ones have selectors that will route traffic to ALL keycloak pods.

### How to Reproduce?

Create two different instances of keycloak in the same namespace and cluster.

**Comment by shawkins** [comment] 2023-06-15 01:34
#20906 has been opened to address this.  It was previously reported as #10562 #14220

**Comment by silverbp** [comment] 2023-06-15 01:54
oh, awesome, sorry I looked for an existing bug, didn't find those.. Is that getting merged soon?

**Comment by shawkins** [comment] 2023-06-15 02:03
> Is that getting merged soon?

I'm not sure.  I'll cover with @vmuzikar when he gets back the considerations mentioned in the description on how to handle the migration of any existing StatefulSets.  Depending on how seamless that needs to be, there could be more refinement.

**Comment by vmuzikar** [comment] 2023-06-26 09:56
@silverbp Thanks for the report. We're treating this as an RFE which is tracked by #10562. Hence closing this but feel free to reopen.

**Comment by vmuzikar** [comment] 2023-06-26 09:56
Duplicate of #10562

**Closed by vmuzikar** 2023-06-26 09:56 UTC
Labels: kind/bug, team/cloud-native, status/triage, area/operator
