### ISSUE TITLE
Table pagination and search always display same data

### ISSUE THREAD

**Issue by Kagemusha-san** [keycloak/keycloak#15508] opened 2022-11-15 10:08 UTC
### Area

admin/ui

### Describe the bug

In Admin Console > Users > Role mapping (and Assing role dialog), the tables do not behave as expected when dealing with data sets bigger than the currently selected page size or when searching for data.

### Version

20.0.1

### Expected behavior

Flipping through pages should display the correct data, not always the same. Searching for data should only display filtered data and still allow correct flipping through pages.

### Actual behavior

When flipping through pages, data displayed is always the same (e.g. only the first 10 results). Searching in tables does not filter data correctly or always displays same set of data when flipping through pages.

### How to Reproduce?

**Prerequisite**
- A realm with >10 roles (e.g. test0 - test11)
- A user

**Problem 1: Table always displays same data**
- Open a user, go to "Role mappings" tab and click on "Assign role" button
- Page size of table is 10 per default so the first 10 roles are listed; page indicator displays 1-10 (OK)
- Click on arrow to display the next 10 roles: table seems to be refreshed but it's still displaying the first 10 roles; page indicator displays 11-20 (NOK)
- Try to search for roles (e.g. test): table seems to be refreshed but roles are not filtered and table still displays the first 10 roles (NOK)

**Problem 2: Table displays same data after searching**
- Assign >10 roles with similar name (e.g. test0 - test11) to a user
- In the "Role mapping" tab click through pages to ensure that data is displayed correctly
- Search for "test" and click on arrow to display the next 10 roles: table still shows the first 10 results; page indicator displays 11-20 (NOK)

**Comment by ssilvert** [comment] 2022-11-15 20:39
@Kagemusha-san Thanks for reporting this.  It's a duplicate of https://github.com/keycloak/keycloak-ui/issues/3740.  it was just fixed today.

**Closed by ssilvert** 2022-11-15 20:39 UTC
Labels: kind/bug, area/admin/ui, status/triage
