### ISSUE TITLE
Config OTP via action required

### ISSUE THREAD

**Issue by zakariae-lebriq** [keycloak/keycloak#12221] opened 2022-05-27 10:41 UTC
### Describe the bug

The page login-config-totp.ftl contains a param named "displayRequiredFields" which is not valid.

based on the  error message, the only valid params are bodyClass, displayInfo, displayMessage, displayWide

Hence,  the OTP configuration fails. 

### Version

18.0.0

### Expected behavior

A page with the form to configure OTP

### Actual behavior

A page with 500 error

### How to Reproduce?

Send an action to user to configure his OTP.

After receiving the email, start the process, a page web will be displayed with the name of the action, click on the link to continue. 

Then the page with the error will show up

**Comment by danielFesenmeyer** [comment] 2022-08-23 07:49
@zakariae-lebriq: At least with Keycloak 19.0.1, I could not reproduce: configure OTP worked fine.
And the param "displayRequiredFields" is actually defined in template.ftl.

If you are still facing this issue, the concrete error message would help.

**Comment by mposolda** [comment] 2023-04-04 09:35
@danielFesenmeyer Thanks!
Closing as this was not reproducible with Keycloak 19.0.1 and the details requested in previous comment were not added.

**Closed by mposolda** 2023-04-04 09:35 UTC
Labels: area/authentication, kind/bug
