### ISSUE TITLE
Sending email for locked users doesn't work anymore with KC 25

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#32250] opened 2024-08-19 20:37 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

In Keycloak version 24, we successfully have overriden the DefaultBruteForceProtector and after the number of failed attempts is increased we sent an email to the user notifying them that their account is locked. After upgrading to Keycloak version 25.0.4, this functionality no longer works.
=> I also get the same error if I try to implement a custom event listener for sending the emails

**Issue:**
The issue appears to be related to the session created within the BruteForceProtector session context. The session context is empty, lacking data like the realm and other necessary information. which is needed for the EmailProvider. This causes the email sending process to fail because the FreeMarkerTemplate engine depends on data stored in the session context.

**Impact:**
The custom event listener / overriding the BruteForceProtector can no longer send email notifications when a user's account is locked, significantly impacting our user notification workflow.

The exception I get from the FreeMarkerEmailTemplateProvider:
java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getEmailTheme()" because the return value of "org.keycloak.models.KeycloakContext.getRealm()" is null.

### Version

25.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

The session context within BruteForceProtector should include relevant data such as the realm, allowing the FreeMarkerTemplate to successfully process and send emails.

### Actual behavior

The session context is empty, causing the email sending to fail.

### How to Reproduce?

1. Override the DefaultBruteForceProtector and just override the failure method by calling super.failure() and then implement the sending of email for the user
2. Upgrade from Keycloak 24 to Keycloak 25.0.4.
3. Trigger an account lock (temporary or permanent).
4. Observe that the email sending fails due to an empty session context in BruteForceProtector.

**Comment by douglaspalmer** [comment] 2024-09-04 23:20
I believe that this is a duplicate of #29542 and will hopefully be fixed by #32345.

**Closed** 2024-09-19 17:32 UTC
Labels: area/authentication, kind/bug, area/core, team/core-clients
