### ISSUE TITLE
Admin Page spinning

### ISSUE THREAD

**Issue by Ashittu21** [keycloak/keycloak#27399] opened 2024-02-29 21:37 UTC
### Description

After cofiguration of ssl on my server, i was not able to get to the Admin page, the page has been spining non stop since yesterday.

### Motivation

The Admin Page, is very important in Administration of users and the server.

**Comment by jonkoops** [comment] 2024-02-29 21:41
Closing this as it was logged as an enhancement, which it is not. This is a bug report, without any steps to reproduce.

**Comment by jonkoops** [comment] 2024-02-29 21:41
Duplicate of #14666

**Closed by jonkoops** 2024-02-29 21:41 UTC
Labels: kind/enhancement, status/triage
