### ISSUE TITLE
Not possible to update DeclarativeUserProfile component configuration through API

### ISSUE THREAD

**Issue by ahamid** [keycloak/keycloak#14287] opened 2022-09-08 19:12 UTC
### Describe the bug

When supplying a `config` value in the `ComponentRepresentation` when updating a DeclarativeUserProfile component via the [API](https://www.keycloak.org/docs-api/18.0/rest-api/#_updatecomponent) the component configuration is not updated.

This appears to be the for the same reason that component configuration is stripped when requesting such a component: The [DeclarativeUserProfile](https://github.com/keycloak/keycloak/blob/18.0.0/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java) defines an empty list for config properties, but in the case of custom user attributes, this configuration appears under the `config-piece-0` component configuration property:

https://github.com/keycloak/keycloak/blob/18.0.0/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java#L243
```java
@Override
public List<ProviderConfigProperty> getConfigProperties() {
    return Collections.emptyList();
}
```

https://github.com/keycloak/keycloak/blob/18.0.0/server-spi-private/src/main/java/org/keycloak/models/utils/StripSecretsUtils.java#L147
```java
public static ComponentExportRepresentation strip(KeycloakSession session, String providerType, ComponentExportRepresentation rep) {
    Map<String, ProviderConfigProperty> configProperties = ComponentUtil.getComponentConfigProperties(session, providerType, rep.getProviderId());
    ...
```

https://github.com/keycloak/keycloak/blob/18.0.0/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L2244
```java
Map<String, ProviderConfigProperty> providerConfiguration = null;
if (!internal) {
    providerConfiguration = ComponentUtil.getComponentConfigProperties(session, component);
}
```

### Version

18.0.0

### Expected behavior

Expected the component configuration to be updated with the supplied configuration object

### Actual behavior

supplied configuration is disregarded

### Anything else?

not sure if this is a bug, or expected behavior, but if so is not intuitive

**Comment by ahamid** [comment] 2022-09-08 21:57
Custom attributes can be updated instead via the `/{realm}/users/profile` API
https://www.keycloak.org/docs-api/18.0/rest-api/#_users_resource

**Comment by mabartos** [comment] 2022-10-03 12:45
@ahamid Thanks for creating this issue!

However, IMHO, the configuration of UserProfile should be updated only by, as you've mentioned, the [User Profile API](https://www.keycloak.org/docs-api/18.0/rest-api/#_getconfiguration). You can also obtain there the current configuration of the User Profile.

The method `getConfigProperties()` is mainly used for defining attributes for a particular component, which could be changed by the Admin UI. For the User Profile, the logic behind the configuration of the component is slightly more complex, and it's solved directly on the frontend side. The Admin console just fetches the current configuration of the User Profile via the API and then directly edits the JSON, which is sent back to the server again. So, it's not required in this context.

I'll close this issue as it's not a bug. However, if you feel the documentation/API needs more intuitive instructions, feel free to create an enhancement ticket for that.

**Closed by mabartos** 2022-10-03 12:45 UTC
Labels: kind/bug, area/user-profile, status/triage
