### ISSUE TITLE
User data is incorrectly erased in Keycloak Admin UI

### ISSUE THREAD

**Issue by adrianog3** [keycloak/keycloak#22900] opened 2023-09-01 18:11 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the `Attributes` tab present in the user edition page, when adding new attributes, going to the `Details` tab and clicking on the `Save` button, the newly added attributes are deleted from the server.

The same behavior happens following the reverse way.

### Version

22.0.1

### Expected behavior

1. When editing the `Attributes` tab, the data from the `Details` tab must not be removed
2. When editing the `Details` tab, the data from the `Attributes` tab must not be removed

### Actual behavior

1. When editing the `Details` tab, the data from the `Attributes` tab is removed
2. When editing the `Attributes` tab, the data from the `Details` tab is removed

### How to Reproduce?

1. Open user edit page
2. Add data in the `Attributes` tab
3. Click on `Save` button
4. Select `Details` tab
5. Click on `Save` button
6. Go to `Attributes` tab again and press F5
7. You will notice that all attributes have been deleted from the server
8. The same behavior happens when we edit the `Details` tab, go to the `Attributes` tab and click on `Save` button, the basic data of user (e.g. `firstName`) will be removed

### Anything else?

I recorded a video reproducing the problem: https://drive.google.com/file/d/1suxD52w4ogDGkHrryATE0EKRHkPV6Opw/view?usp=sharing

**Comment by kaustubh-rh** [comment] 2023-09-02 03:42
Hi @jonkoops @mposolda , the issue is reproducible , can I take this one ?

**Comment by jonkoops** [comment] 2023-09-02 10:56
Sure, go right ahead and take this. I recently started making some change to this code under #22851, which may or may not fix this issue.

**Comment by jonkoops** [comment] 2023-09-02 10:57
Before starting work on a fix, let me know if this issue is reproducible, so I can add the correct labels.

**Comment by kaustubh-rh** [comment] 2023-09-02 13:16
Hi @jonkoops , I just tested it , the PR for #22851 fixes the issue as the issue is not reproducible.

**Comment by jonkoops** [comment] 2023-09-03 10:46
Thanks for testing that @kaustubh-rh, I'll link this issue so it will be closed automatically when the PR is merged.

**Closed** 2023-09-04 04:55 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui
