### ISSUE TITLE
Session expired for Google identity provider after upgrading to version 24

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak#28691] opened 2024-04-13 05:13 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We upgraded our Keycloak instance from 23 to 24. After the upgrade, almost 8 out of 10 login attempts via Google resulted in the session expiring.
We tested with many Internet connections, and different VPNs, and the problem still exists.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

It's better to give us a more descriptive text about the underlying problem.

### Actual behavior

It shows us the session expired screen with no data of what could be wrong.

### How to Reproduce?

- Upgrade to 24.0.2
- Enable Google login
- Login via Google

**Comment by Nefcanto** [comment] 2024-04-13 05:19
It shows this screen:
![Screenshot from 2024-04-13 08-48-37](https://github.com/keycloak/keycloak/assets/12782347/a822e463-f5a4-4fd9-82b8-da30a4a7fffc)

**Comment by rmartinc** [comment] 2024-04-15 09:03
Hi @Nefcanto!

I cannot reproduce the issue following the reproducer steps. I can login with my google user into the account console with no issues using the google identity provider. So probably some detail is missing that is necessary to reproduce the issue.

Regards!

**Comment by Nefcanto** [comment] 2024-04-15 10:22
@rmartinc, thank you for responding. Can you guide me on how to collect data to find out the problem? I'm using docker and I used `docker logs --follow --tail 50 our-accounts` to see a bug or error. But I could not find any.

**Comment by sschu** [comment] 2024-04-15 10:55
If I had to guess, I would assume this is because of distributed caches not being formed correctly. How many instances of Keycloak are you running? Does the problem persist if you scale down to one instance?

**Comment by Nefcanto** [comment] 2024-04-15 12:01
@sschu, only one instance. We only have one instance. It's inside a docker container, behind an nginx reverse proxy.

**Comment by rmartinc** [comment] 2024-04-16 07:27
Yes, it's just a startup option, maybe you need more packages to trace but at least you start with something. If it's your production environment I would use another installation to do the tests.

**Comment by Nefcanto** [comment] 2024-04-16 08:15
@rmartinc, thank you. I will test that. Meanwhile I saw these logs:

```
2024-04-16 08:07:07,118 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012095: Abort of action id 0:ffffc0a81004:a0d1:661cfed2:52e8 invoked while multiple threads active within it.
2024-04-16 08:07:07,122 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012381: Action id 0:ffffc0a81004:a0d1:661cfed2:52e8 completed with multiple threads - thread executor-thread-415 was in progress with java.base@17.0.10/sun.nio.ch.SocketDispatcher.read0(Native Method)
java.base@17.0.10/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
java.base@17.0.10/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:266)
java.base@17.0.10/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:317)
java.base@17.0.10/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
java.base@17.0.10/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
java.base@17.0.10/java.net.Socket$SocketInputStream.read(Socket.java:966)
java.base@17.0.10/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
java.base@17.0.10/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
java.base@17.0.10/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
java.base@17.0.10/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
java.base@17.0.10/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
java.base@17.0.10/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
java.base@17.0.10/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
java.base@17.0.10/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:299)
org.keycloak.broker.provider.util.SimpleHttp.asResponse(SimpleHttp.java:229)
org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:541)
org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_fef2d69ce31937f365a37fb3083f9247bc4c56d2.invoke(Unknown Source)
org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

2024-04-16 08:07:07,123 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012108: CheckedAction::check - atomic action 0:ffffc0a81004:a0d1:661cfed2:52e8 aborting with 1 threads active!
2024-04-16 08:07:07,125 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffffc0a81004:a0d1:661cfed2:52e8
2024-04-16 08:11:34,203 WARN  [org.keycloak.events] (executor-thread-421) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="749df324-47b2-43d5-9dcb-089030c15ba0", clientId="AdminPanel", userId="null", ipAddress="51.81.200.142", error="unexpectedErrorHandlingRequestMessage", identity_provider="google", code_id="b62defcb-d592-4f2d-bc65-faf6cfde7efa"
2024-04-16 08:11:34,204 ERROR [org.keycloak.services.resources.IdentityBrokerService] (executor-thread-421) unexpectedErrorHandlingRequestMessage: jakarta.ws.rs.WebApplicationException: HTTP 200 OK
	at org.keycloak.services.resources.IdentityBrokerService.parseSessionCode(IdentityBrokerService.java:1095)
	at org.keycloak.services.resources.IdentityBrokerService.performLogin(IdentityBrokerService.java:376)
	at org.keycloak.services.resources.IdentityBrokerService$quarkusrestinvoker$performLogin_745935650b295aeee07388086becb7de4950b5c4.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-04-16 08:11:37,081 WARN  [org.keycloak.events] (executor-thread-421) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="749df324-47b2-43d5-9dcb-089030c15ba0", clientId="AdminPanel", userId="null", ipAddress="51.81.200.142", error="unexpectedErrorHandlingRequestMessage", identity_provider="google", code_id="b62defcb-d592-4f2d-bc65-faf6cfde7efa"
2024-04-16 08:11:37,081 ERROR [org.keycloak.services.resources.IdentityBrokerService] (executor-thread-421) unexpectedErrorHandlingRequestMessage: jakarta.ws.rs.WebApplicationException: HTTP 200 OK
	at org.keycloak.services.resources.IdentityBrokerService.parseSessionCode(IdentityBrokerService.java:1095)
	at org.keycloak.services.resources.IdentityBrokerService.performLogin(IdentityBrokerService.java:376)
	at org.keycloak.services.resources.IdentityBrokerService$quarkusrestinvoker$performLogin_745935650b295aeee07388086becb7de4950b5c4.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

@sschu, it seems that it's related to threading.

**Comment by rmartinc** [comment] 2024-04-16 08:29
@Nefcanto The first exception seems to be that the thread is stuck trying to call the token endpoint, if you see it's in a socket read generated from this [line](https://github.com/keycloak/keycloak/blob/24.0.2/services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java#L541)). Can you please check that you can always access google from the container? If I'm not wrong that URL is `https://oauth2.googleapis.com/token`.

**Comment by Nefcanto** [comment] 2024-04-16 08:38
@rmartinc, yep you're right. I got this response:

> curl: (6) Could not resolve host: oauth2.googleapis.com

**Comment by Nefcanto** [comment] 2024-04-16 08:38
@rmartinc, so there is something wrong with my network. But I wish the Keycloak team would show something more informative. Thank you for your help.

**Comment by rmartinc** [comment] 2024-04-29 08:07
Closing this. Please re-open or file a new issue if needed.

**Closed by rmartinc** 2024-04-29 08:07 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients, status/auto-expire
