### ISSUE TITLE
Unable to toggle the "Permissions enabled" option in Role details

### ISSUE THREAD

**Issue by pejeio** [keycloak/keycloak#17186] opened 2023-02-19 21:51 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

The option to toggle **"Permissions enabled"** in **Realm roles** --> **Role details** is non-functional. Upon inspection of the browser console, a 500 error is observed with the following response body:

```json
{"error":"unknown_error"}
```
This issue requires further investigation to identify and address the underlying problem.

<img width="1227" alt="Screenshot 2023-02-19 at 22 45 01" src="https://user-images.githubusercontent.com/33237012/219977297-7d74c12e-7605-41c3-8845-dfe4dd96ff3d.png">

### Version

20.0.3

### Expected behavior

I'm able to toggle the **"Permissions enabled"** option in Realm roles --> Role details.

### Actual behavior

I'm unable to enable the **"Permissions enabled"** option in Realm roles --> Role details.

### How to Reproduce?

- Install Keycloak (version 20.0.3)
- Create a new Realm role
- Click the "Permissions" tab
- Try to toggle the "Permissions enabled" toggle

**Comment by sschu** [comment] 2023-02-20 16:57
I can reproduce this problem. Since fine-grained permissions is a preview feature, you have to enable it when starting Keycloak e.g. by passing '-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled' when starting it. Then the switch can be toggled. However, I think throwing a 500 when trying to toggle this switch without the preview feature is not a good behaviour. I think Keycloak should send a more specific reply (maybe 404 or 501) and/or the switch should not be shown in the UI if the feature is not enabled.

**Comment by mposolda** [comment] 2023-03-23 10:19
@sschu Thanks for the investigation!

I am closing as this is not applicable anymore in latest Keycloak main (and likely also in latest release Keycloak 21.0.1). Currently:
- When the `admin_fine_grained_authz` feature is disabled, the "Permissions" tab is not visible in admin console
- When the feature is enabled, it can be successfully switched to ON

**Closed by mposolda** 2023-03-23 10:19 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core
