### ISSUE TITLE
Custom Authenticator with custom ftl language switch url wrong.

### ISSUE THREAD

**Issue by bdssultan** [keycloak/keycloak#25635] opened 2023-12-15 19:36 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Custom Authenticator with custom ftl page urlls for switching language is wrong

### Version

22.0.3

### Expected behavior

url for switching locale has to be as on login page .../login-actions/authenticate...

### Actual behavior

for custom ftl url is ...protocol/openid-connect/auth?...

### How to Reproduce?

Create Custom Authenticator with custom ftl enable internalization(add more then 1 locale) try to authenticate  then try on auth page swtich language

### Anything else?

The reason is the following: my custom authenticator uses a custom FTL form:

authenticationFlowContext.forceChallenge(authenticationFlowContext.form().createForm("customPage.ftl"));

This means that there is no LoginFormsPages defined in FreeMarkerLoginsFormsProvider::createCommonAttributes, resulting in the /protocol/openid-connect path.

**Comment by mposolda** [comment] 2023-12-19 09:11
This might be a valid issue, but not 100% sure as to reproduce this, it is needed to have custom authenticator and custom FTL template, which is not provided here. Keycloak team probably won't have time to look at this in the near future. Adding this to the backlog for now. Anyone is welcome to investigate this and possibly send PR to improve/fix this. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details how to contribute to Keycloak.

**Comment by huguesn** [comment] 2024-05-02 01:12
Looks like a duplicate of https://github.com/keycloak/keycloak/issues/16063

**Closed** 2024-08-01 00:06 UTC
Labels: area/authentication, kind/bug, help wanted, team/core-clients, priority/low, status/auto-expire, status/auto-bump, status/expired-by-bot
