### ISSUE TITLE
CRL Verification failing due to client certificate not being in a chain

### ISSUE THREAD

**Issue by baldmageix** [keycloak/keycloak#19853] opened 2023-04-20 21:41 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Behavior:

When we Enable X509 Browser certificate authentication and turn CRL checking on with the CRL file option, the user always fails to authenticate. This seems to be due to Keycloak expecting a chain of certificates from the Client cert rather than just the client cert. As far as I can tell, it is not standard for the client cert to contain the CA Chain, so Keycloak always end up with this error:

```20T21:27:46.901Z","sequence":8562,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.keycloak.services","level":"ERROR","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","threadName":"executor-thread-3","threadId":118,"mdc":{},"ndc":"","hostName":"ip-10-38-1-109.us-gov-west-1.compute.internal","processName":"QuarkusEntryPoint","processId":77,"exception":{"refId":1,"exceptionType":"java.security.GeneralSecurityException","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","frames":[{"class":"org.keycloak.utils.CRLUtils","method":"check","line":55},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRL","line":737},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRLDistributionPoints","line":760},```

Can this be fixed to accept the child client cert and get its issuer from there? Rather than forcing a minimum length of two certificates?

```
    public static void check(X509Certificate[] certs, X509CRL crl, KeycloakSession session) throws GeneralSecurityException {
        if (certs.length < 1) {
            throw new GeneralSecurityException("Not possible to verify signature on CRL. X509 certificate doesn't exist");
        }

        X500Principal crlIssuerPrincipal = crl.getIssuerX500Principal();
        X509Certificate crlSignatureCertificate = null;

        // Try to find the certificate in the CA chain, which was used to sign the CRL
        for (int i=0 ; i<certs.length ; i++) {
            X509Certificate currentCert = certs[i];
            if (crlIssuerPrincipal.equals(currentCert.getIssuerX500Principal())) {
                crlSignatureCertificate = currentCert;

                log.tracef("Found certificate used to sign CRL in the CA chain of the certificate. CRL issuer: %s", crlIssuerPrincipal);
                break;
            }
        }
```

### Version

21.1.0

### Expected behavior

Users be able to login with x509 Certificate and CRL checking to be working.

### Actual behavior

When CRL checking is turned on in the browser auth flow, and a CRL file is specified.  Users gets rejected due to failed CRL verification.

```20T21:27:46.901Z","sequence":8562,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.keycloak.services","level":"ERROR","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","threadName":"executor-thread-3","threadId":118,"mdc":{},"ndc":"","hostName":"ip-10-38-1-109.us-gov-west-1.compute.internal","processName":"QuarkusEntryPoint","processId":77,"exception":{"refId":1,"exceptionType":"java.security.GeneralSecurityException","message":"Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it","frames":[{"class":"org.keycloak.utils.CRLUtils","method":"check","line":55},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRL","line":737},{"class":"org.keycloak.authentication.authenticators.x509.CertificateValidator","method":"checkRevocationStatusUsingCRLDistributionPoints","line":760},```

Can this be fixed to accept the child client cert and get its issuer from there? Rather than forcing a minimum length of two certificates?

```
    public static void check(X509Certificate[] certs, X509CRL crl, KeycloakSession session) throws GeneralSecurityException {
        if (certs.length < 1) {
            throw new GeneralSecurityException("Not possible to verify signature on CRL. X509 certificate doesn't exist");
        }

        X500Principal crlIssuerPrincipal = crl.getIssuerX500Principal();
        X509Certificate crlSignatureCertificate = null;

        // Try to find the certificate in the CA chain, which was used to sign the CRL
        for (int i=0 ; i<certs.length ; i++) {
            X509Certificate currentCert = certs[i];
            if (crlIssuerPrincipal.equals(currentCert.getIssuerX500Principal())) {
                crlSignatureCertificate = currentCert;

                log.tracef("Found certificate used to sign CRL in the CA chain of the certificate. CRL issuer: %s", crlIssuerPrincipal);
                break;
            }
        }
```

### How to Reproduce?

1. Create a login Browser flow using x509 certificate check
2. Turn on CRL checking and specify a CRL file
3. Login with a certificate that is signed by a single root CA

**Comment by mposolda** [comment] 2023-05-19 09:17
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by sschu** [comment] 2023-05-19 09:52
AFAIK, it is best practice that whoever is presenting a certificate also includes the intermediate certificate. They might be rotated more often and it should be the presenters responsibility to do the update, not the one who is validating it. Also see here for a discussion: https://security.stackexchange.com/questions/204000/truststore-and-intermediate-certificates

You can nevertheless create a custom truststore where you include the intermediate certificate, if you want.
So I would close this as not a bug.

**Comment by mposolda** [comment] 2023-05-19 13:25
@sschu Thanks for the pointer!

**Comment by sschu** [comment] 2023-06-02 16:19
@danweller18 You can still add the intermediate certificate to a custom truststore for Keycloak.

**Comment by danweller18** [comment] 2023-06-02 16:48
@sschu That's the problem- I don't have an intermediate cert. My root ca is already in the keycloak truststore. Keycloak does not appear to support this valid use case

**Comment by sschu** [comment] 2023-06-02 16:51
So you mean you have your own self-signed root certificate and used it directly to create the client certificate?

**Comment by sschu** [comment] 2023-06-09 06:04
@danweller18 I think you are right.

**Comment by 2rpgo2** [comment] 2023-07-05 20:51
Hi, I'm having a similar issue.  However, I'm using a certificate signed by an intermediate CA.  Which truststore do I use for storing the intermediate CA certificate?  I've placed it in the following environment variables:

- KC_HTTPS_TRUST_STORE_FILE
- Djavax.net.ssl.truststore
- spi-truststore-file

With all the above cases, I'm still only seeing the client certificate but no other certificate in the chain.  The CRL is retrieved from the certificate distribution endpoint successfully but only a single certificate (the client cert) is provided to the check() function in the certs array.

I'm running Keycloak 21.1.1 image as a docker container.  I'm not using a proxy.  Thus, all requests are going directly to the Keycloak server.  How do I ensure that the remaining certificate in the chain are added to the certs array?

**Comment by ahus1** [comment] 2023-11-15 08:27
There is now a PR for this "help wanted" issue, see #24760. Looking for reviewers for that issue.

**Comment by danweller18** [comment] 2023-11-17 10:44
> There is now a PR for this "help wanted" issue, see #24760. Looking for reviewers for that issue.

I was able to test this fix locally and verify that it solves the client using a chain length of 1

**Comment by samratdgreat** [comment] 2024-01-03 14:38
> > There is now a PR for this "help wanted" issue, see #24760. Looking for reviewers for that issue.
> 
> I was able to test this fix locally and verify that it solves the client using a chain length of 1

Are you verifying the CRL check locally or with OCSP?

**Comment by danweller18** [comment] 2024-01-03 14:57
> > > There is now a PR for this "help wanted" issue, see #24760. Looking for reviewers for that issue.
> > 
> > 
> > I was able to test this fix locally and verify that it solves the client using a chain length of 1
> 
> @danweller18 Are you verifying the CRL check locally or with OCSP?

I verified with local CRL files, not using ocsp

**Comment by samratdgreat** [comment] 2024-01-03 15:06
> > > > There is now a PR for this "help wanted" issue, see #24760. Looking for reviewers for that issue.
> > > 
> > > 
> > > I was able to test this fix locally and verify that it solves the client using a chain length of 1
> > 
> > 
> > @danweller18 Are you verifying the CRL check locally or with OCSP?
> 
> I verified with local CRL files, not using ocsp

I am getting a weird error(Transaction Reaper) while checking it locally. can we discuss about it when you get chance. my email is grgsamrat785@gmail.com

**Comment by samratdgreat** [comment] 2024-01-03 16:59
> > > > > There is now a PR for this "help wanted" issue, see #24760. Looking for reviewers for that issue.
> > > > 
> > > > 
> > > > I was able to test this fix locally and verify that it solves the client using a chain length of 1
> > > 
> > > 
> > > @danweller18 Are you verifying the CRL check locally or with OCSP?
> > 
> > 
> > I verified with local CRL files, not using ocsp
> 
> @danweller18 I am getting a weird error(Transaction Reaper) while checking it locally. can we discuss about it when you get chance. my email is [grgcamrat785@gmail.com](mailto:grgsamrat785@gmail.com)

**Comment by jlplasce** [comment] 2024-01-31 16:02
@danweller18 Any status on that PR? We could use this fix as well

**Comment by danweller18** [comment] 2024-03-14 13:11
@abstractj what in the world is going on here? The bot is saying we aren’t able to resolve this, but we have had a 2 line, 2 char PR which resolves this…. Just waiting for months. 

I have tested it working personally, and the real issue appears to be that no one with keycloak street cred has time to verify it?

**Comment by ahus1** [comment] 2024-03-14 13:23
If you want to up-vote this issue, please use the "thumbs up" marker at the top, like shown in this screenshot: 

![image](https://github.com/keycloak/keycloak/assets/3957921/8c4d2a49-0416-4504-bfeb-fe81ebdcbf42)

**Comment by prettypot** [comment] 2024-04-10 12:31
> If you want to up-vote this issue, please use the "thumbs up" marker at the top, like shown in this screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/3957921/312854157-8c4d2a49-0416-4504-bfeb-fe81ebdcbf42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTI1NDMsIm5iZiI6MTcxMjc1MjI0MywicGF0aCI6Ii8zOTU3OTIxLzMxMjg1NDE1Ny04YzRkMmE0OS0wNDE2LTQ1MDQtYmZlYi1mZTgxZWJkY2JmNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTIzMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkzOTgzNjkzMmFmNzQzZmUyNmVjN2ZiOGVlMTU2MGUxM2ExYzRmZmViN2Y3NGQxZjhhZDdiODc4NDU1Y2MxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8sQSj3VCQzGAQI7eOk0_dcXGazzT6jFAOMnpRJMQk8w)

Thumbs up icon not visible on my browser.

**Comment by prettypot** [comment] 2024-04-10 12:33
I have this CRL problem in my environments ( prd and uat ).

2024-04-10 14:09:51,019 ERROR [org.keycloak.services] (executor-thread-39) Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it: java.security.GeneralSecurityException: Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it

**Closed** 2024-05-17 09:28 UTC
Labels: area/authentication, kind/bug, priority/important, team/rh-iam, team/core-clients
