### ISSUE TITLE
refresh_expires_in is zero if Offline Session Max Limited is OFF

### ISSUE THREAD

**Issue by hokuda** [keycloak/keycloak#8919] opened 2021-11-25 08:16 UTC
### Describe the bug

If Offline Session Max Limited is OFF,
refreshToken.getExpiration() at [1] returns 0 (even if Offline Session Idle is non-zero).
As a result, refresh_expires_in in a response from the token endpoint with scope=offline_access is 0.

If Offline Session Max Limited is ON,
refreshToken.getExpiration() at [1] returns min(Offline Session Idle, Offline Session Max).
As a result, refresh_expires_in in a response from the token endpoint with scope=offline_access is min(Offline Session Idle, Offline Session Max).

It's inconsistent.

### Version

RH-SSO 7.5.0

### Expected behavior

If Offline Session Max Limited is OFF,
refresh_expires_in in a response from the token endpoint with scope=offline_access should be Offline Session Idle.

Or Offline Session Idle should be disabled, if If Offline Session Max Limited is OFF.

### Actual behavior

If Offline Session Max Limited is OFF,
refreshToken.getExpiration() at [1] returns 0 (even if Offline Session Idle is non-zero).
As a result, refresh_expires_in in a response from the token endpoint with scope=offline_access is 0.

If Offline Session Max Limited is ON,
refreshToken.getExpiration() at [1] returns min(Offline Session Idle, Offline Session Max).
As a result, refresh_expires_in in a response from the token endpoint with scope=offline_access is min(Offline Session Idle, Offline Session Max).

It's inconsistent.

### How to Reproduce?

`RESPONSE=`curl -v --request POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token --header "Accept: application/json" --header "Content-Type: application/x-www-form-urlencoded" --data "grant_type=password&username=admin&password=password&client_id=admin-cli&scope=offline_access"`; echo $RESPONSE | jq .
`

**Comment by hokuda** [comment] 2021-11-25 08:26
[1] https://github.com/keycloak/keycloak/blob/b03b390dd2475979d97f34891b96839a68cd7097/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L1183

**Comment by y-tabata** [comment] 2021-11-25 08:45
I think this is expected behavior.
We need to consider this behavior with the exp claim of the offline token/refresh token and also backward compatibility. 
The following PR is helpful.
https://github.com/keycloak/keycloak/issues/8919

**Comment by eedzjee** [comment] 2022-09-21 13:57
I also ran into this behaviour and it is sadly enough not really documented. It would be nice to add a description on that a value '0' means that the refresh token is valid indefinitly. Otherwise it can be interpreted as 'expires immediately'.

What would be even better is not providing the 'refresh_expires_in' at all when it is valid indefinitely. The code @hokuda pointed out already suggests this behaviour, but since a primitive long always has a default value of 0, it is present in the json-response. Also the PR @y-tabata mentions says not to include the 'exp' claim in the refresh token if it doesn't expire.
So removing the 'refresh_expires_in' from the AccessTokenResponse makes more sense than setting it to zero.
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L1252

On a more extensive functionality: it would be nice to be able to override the indefinite length of the offline_access tokens per client. For example: the realm-wide setting is not to expire (Offline Session Max Limited is OFF), but the clients advanced setting 'Client Offline Session Max' can override it.

@mhajas what do you think?

**Comment by pedroigor** [comment] 2023-02-16 21:24
I'm closing this one as it is working as expected.

Please, open separate RFEs for:

* Allow clients to override offline session max when max lifespan is not enabled at the realm level
* Do not include expiration state if 0. The `AccessTokenResponse` is not really aligned with `JsonWebToken` where a primitive wrapper (e.g.: Long) is used as a type.

**Closed by pedroigor** 2023-02-16 21:24 UTC
Labels: area/oidc, kind/bug, status/triage
