### ISSUE TITLE
18.1 conf/keycloak.conf can't process https-certificate-file

### ISSUE THREAD

**Issue by tolgaulas** [keycloak/keycloak#12675] opened 2022-06-23 09:27 UTC
### Describe the bug

On Debian10,  the below works:
```
bin/kc.sh start --auto-build --https-certificate-key-file="path/to/privkey.pem" --https-certificate-file="path/to/fullchain.pem"
```

But below does not work
-- conf/keycloak.conf
```
https-certificate-key-file=path/to/privkey.pem 
https-certificate-file=path/to/fullchain.pem
```

and cli:
```
bin/kc.sh start --auto-build
```

### Version

18.1

### Expected behavior

keycloak should run and accept connections from 8443

### Actual behavior

Below error appears:
```
2022-06-23 09:20:32,384 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-06-23 09:20:32,385 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: "/path/to/fullchain.pem"
2022-06-23 09:20:32,390 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
```

**Comment by rmartinc** [comment] 2022-06-23 11:53
@tolgaulas I cannot reproduce this. It's working for me creating a two level certificate (ca+server). Please note that the files should be readable and should be specified using the full path. You can use `${kc.home.dir}`, for example in my case:

```bash
tail -3 ../conf/keycloak.conf 
https-certificate-key-file=${kc.home.dir}/conf/server.key.pem
https-certificate-file=${kc.home.dir}/conf/server.cert.pem
hostname=localhost
```
My certificates are placed inside the conf file itself. And my keycloak 18.1 is starting OK:

```
[rmartinc@hulk bin]$ ./kc.sh start --auto-build
2022-06-23 13:52:10,680 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: localhost, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-06-23 13:52:11,199 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-06-23 13:52:11,241 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-06-23 13:52:11,263 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-06-23 13:52:11,396 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-06-23 13:52:11,494 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-06-23 13:52:11,494 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-06-23 13:52:11,546 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-06-23 13:52:11,546 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-06-23 13:52:11,546 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-06-23 13:52:11,547 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-06-23 13:52:13,552 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) hulk-63365: no members discovered after 2002 ms: creating cluster as coordinator
2022-06-23 13:52:13,558 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [hulk-63365|0] (1) [hulk-63365]
2022-06-23 13:52:13,561 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `hulk-63365`, physical addresses are `[192.168.1.164:58309]`
2022-06-23 13:52:13,880 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: hulk-63365, Site name: null
2022-06-23 13:52:14,218 INFO  [io.quarkus] (main) Keycloak 18.0.1 on JVM (powered by Quarkus 2.7.5.Final) started in 5.102s. Listening on: https://0.0.0.0:8443
2022-06-23 13:52:14,218 INFO  [io.quarkus] (main) Profile prod activated. 
2022-06-23 13:52:14,218 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
```

**Comment by DGuhr** [comment] 2022-06-27 12:17
@tolgaulas I just tried and could also not reproduce the mentioned behaviour. 

The points @rmartinc provided are right. Have you tried that out? 

Another observation: 
1) You are setting a relative path in the config file, but the error message shows an absolute path (with trailing `/`) - was this a copy/paste error / an error while changing the actual path to test values?

So, without further information I will close this for now. Feel free to re-open when your problem still persists, but most likely it's a local environment issue and not a keycloak one.

**Closed by DGuhr** 2022-06-27 12:17 UTC
Labels: kind/bug, area/dist/quarkus, status/triage

**Comment by SpiderD555** [comment] 2022-11-09 08:31
I just wanted to chime in with some update. I stumbled upon the same issue while installing 20.0.1 version. 
I tried my regular wildcard certificate and also ACME cert that I generate from my own smallstep CA, both give the same effect.
I tried changing the hostname, merging key and certificate, changing ownership of the cert and key files - nothing helped. I am not sure where the issue is.
For now it seems that the issue appears when I start keycloak using systemd service. If I start it manually from command line, then it all works fine ! Maybe it is some issue with credentials ? or environment variable that is set for the user, but not for systemd service ? I am stuck with this issue. Any tips are welcome to troubleshoot it. By the way I am using Debian Bullseye and set everything up using my own Ansible playbook that I shamelessly based on [this collection](https://galaxy.ansible.com/middleware_automation/keycloak), so I guess I can reproduce the issue consistently.
If needed then I can provide my Ansible role.

**Comment by slominskir** [comment] 2022-11-14 18:40
It appears that the previous version of keycloak example conf for SSL didn't contain a slash between the variable `${kc.home.dir}` and literal path and the latest version does.   So if you copy your old conf over it breaks.   The fix is to add the slash between them.  Example:

```
https-certificate-key-file=${kc.home.dir}conf/server.key.pem
https-certificate-file=${kc.home.dir}conf/server.cert.pem
```

vs

```
https-certificate-key-file=${kc.home.dir}/conf/server.key.pem
https-certificate-file=${kc.home.dir}/conf/server.cert.pem
```

**Comment by SpiderD555** [comment] 2022-11-15 11:14
Unfortunately that is not the case here. I already use absolute path and still can't get it to work.
I even tried to put --https-certificate-file and --https-certificate-key-file options in systemd "ExecStart=". Nothing seems to work here. It's as if key file is entirely invisible to keycloak when used with systemd.

**Comment by vmuzikar** [comment] 2022-11-15 11:36
@SpiderD555 Hello, sorry to hear you're still facing issues with configuring TLS. I'd like to ask if you'd be able to provide us with a reproducer that doesn't involve Ansible. If so, can you also create a new Issue for it? Thanks.

**Comment by SpiderD555** [comment] 2022-11-16 22:38
I have created new issue for this: https://github.com/keycloak/keycloak/issues/15534
I also found some workaround (see the new issue for details)

**Comment by christian-2** [comment] 2023-06-13 09:14
> It appears that the previous version of keycloak example conf for SSL didn't contain a slash between the variable `${kc.home.dir}` and literal path and the latest version does.

This saved my day w/ Keycloak 21.1.1. Switching to absolute path for `https-certificate-file` and `https-certificate-key-file` in `keycloak.conf` made the error "Key material not provided to setup HTTPS" disappear.

**Comment by Felice-Copp56** [comment] 2023-06-23 15:57
Hi, I have the same issue but I have no idea how to resolve.
I'm trying to start a docker container for Keycloak on ec2  and I have followed these steps:

- Created the key.pem and cert.pem file with :openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
- Running the docker container with: docker run -d --name keycloak-dev -p 443:8443 -e KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN -e KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD quay.io/keycloak/keycloak:21.1.1 start-dev --hostname-port=443 --hostname=my-private-ip-ec2:443 --https-certificate-file=cert.pem --https-certificate-key-file=key.pem
Any idea?

**Comment by christian-2** [comment] 2023-06-24 14:35
@Felice-Copp56 From your `docker run ...` it would seem that you are running `start-dev` in the container yet referring to files `cert.pem`, `key.pem` on the host. If so, you'd have to copy or mount those into the container. This is general to Docker, not specific to Keycloak.

**Comment by Felice-Copp56** [comment] 2023-06-25 10:06
@christian-2 I have wrote a DockerFile where I have set the env variables for `cert.pem` and `key.pem` and after `docker build` and `docker run` I was able to start in the correct way the keycloak container in production mode.
But now I have two problems:

- First one is that I can access the main page of Keycloak with https://my-ec2-private-ip:443 but I have a record dns created and associated to ec2_ip for hide this IP. More in depth I have a ALB load balancer in front of the ec2
- Second one is that after I click on administration console it shows me this error message 
![image](https://github.com/keycloak/keycloak/assets/55912466/bb77f8d0-65c5-486c-b6ae-5a91019f7b8f)
and the loading adming page spinning undefinitely.
Any idea? I hope it is clear and thanks for you answer

**Comment by christian-2** [comment] 2023-06-25 11:27
@Felice-Copp56 What I would do in such a case is first try connecting with `openssl s_client -connect my-ec2-private-ip:443 -showcerts` to see whether the basic HTTPS setup is sound. I'm not familiar with ALB load balancer off the cuff, but perhaps you will need to consider one of Keycloak's [proxy modes](https://www.keycloak.org/server/reverseproxy). (IMHO this issue might be better suited for StackExchange, say.)

**Comment by SpiderD555** [comment] 2023-06-25 17:52
@Felice-Copp56 
Possibly you may be hitting a bug with encoding. Please check [this workaround](https://github.com/keycloak/keycloak/issues/12719#issuecomment-1250416313). Worked for me on Haproxy, maybe it will work for you too.

**Comment by petehaaswws2** [comment] 2023-10-30 23:16
It is worth noting; I fixed this by added an absolute full path for each certification file.

**Comment by ksandaru** [comment] 2023-11-21 04:24
You might be able to find the solution here (https://stackoverflow.com/a/77520148/15838526)
In most of cases this should be a permission issue to private key or certificate file.  In this solution you will be able to use the `keycloak `along with `SSL` and `HOSTNAME `like `https://abc.xyz.com:8443` without using `Nginx`
