### ISSUE TITLE
Version 22.0.1 - browser script error when creating client

### ISSUE THREAD

**Issue by johandanforth** [keycloak/keycloak#22935] opened 2023-09-04 11:10 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When creating a new client, there is a javascript error on the third and final step (3. Login settings) in the console, and the new client is not created. Not sure if it has anything to do with the values specified in the steps because sometimes it seems to work, but the scripting error is:

"Object.hasOwn is not a function" at util.ts:81

Originates from NewClientForm.tsx:57

### Version

22.0.1

### Expected behavior

I expected the client to be saved.

### Actual behavior

Nothing happens in the browser UI but there is a scripting error in the browser console.

### How to Reproduce?

Create a new client.

### Anything else?

Note that I'm running on a server that is offline from the Internet. If that may have any effect, but it shouldn't.

**Comment by jonkoops** [comment] 2023-09-04 11:25
What is the browser you are using? And what version is it on?

**Comment by ssilvert** [comment] 2023-09-05 19:13
I took a look at the code and it is most likely that there is some attribute you are trying to save that is having trouble.  It's trying to process the form and one of the objects doesn't have the expected "hasOwn" method.  If you can figure out which value on the form is the culprit then that will help us track this down.

**Comment by johandanforth** [comment] 2023-09-06 17:25
I'm away on a business trip, will try to dig into this on monday. It's a mystery, because I can create the realm and client as I want to using the older version 18, without any problems at all. It's really a mystery and I wish there was a more detailed error explaining what the problem is.

**Comment by skibot11** [comment] 2023-09-08 17:35
Hi, I'd like to join this thread and also say that I have the same issue.  We didn't have any issues before on wildfly, but have since migrated into quarkus and experienced this in KC 21.1.1.  Multiple environments, some with carry over postgres databases and some testing with completely clean databases all return the same 'hasOwn' issue.  I notice that if we jump into a client and save something within ~3 seconds, it will save -- but if not, it will eventually pop up with that error in the console and on subsequent button interactions.

**Comment by jonkoops** [comment] 2023-09-11 11:00
This is all very strange, as the original post states:

> "Object.hasOwn is not a function" at util.ts:81

This is a built-in method of the standard library that is pretty [widely supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility). So I would not be expecting this exception unless you are running an outdated browser version.

Could either of you verify that you are indeed running the latest version of your respective browsers? And if the problem goes away if you do upgrade. If not, could you share the full stack trace? I'd be curious to see the full trace.

**Comment by ssilvert** [comment] 2023-10-02 20:35
I'm going to close this now.  

@skibot11 @johandanforth If you have some more information that can help us reproduce then we can reopen.

**Closed** 2023-10-02 20:35 UTC
Labels: kind/bug, area/admin/ui, team/ui

**Comment by spaceone** [comment] 2023-12-18 14:20
```
util.ts:81 Uncaught (in promise) TypeError: Object.hasOwn is not a function
    at util.ts:81
    at Array.some (<anonymous>)
    at isAttributeArray (util.ts:80)
    at util.ts:134
    at Array.map (<anonymous>)
    at convertFormValuesToObject (util.ts:133)
    at W (ClientDetails.tsx:336)
```
same for me with Chromium 90.0.4430.212 built on Debian 10.9, running on Debian 10.13 (64-Bit).

No saving/modification of any client is possible.

**Comment by jonkoops** [comment] 2023-12-18 14:27
Probably because it's 30 versions behind, you should update your browser.
