### ISSUE TITLE
Possible memory leak in offline sessions

### ISSUE THREAD

**Issue by giacomoa** [keycloak/keycloak#9877] opened 2022-01-28 17:21 UTC
### Describe the bug

Offline users sessions are stored in infinispan cache and in DB; ClearExpiredUserSessions task is scheduled to remove sessions from db but even if the task cleans correctly the DB rows, cleaning of infinispan cache relies on expiration provided by Infinispan.
That works correctly until reboot of the whole cluster, that cause entries to be loaded from db and imported in cache without any expiration ( https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L838 ):

`        // Directly put all entities to the infinispan cache
        Cache<String, SessionEntityWrapper<UserSessionEntity>> cache = CacheDecorators.skipCacheLoaders(getCache(offline));
        cache.putAll(sessionsById);
`

If you then try to use an expired offline session still present in memory (not more in DB) it is correctly removed, but if you don't try to use that session it keeps in memory until next reboot.

### Version

16.1.0

### How to Reproduce?

1. Set offline sessions idle to 15 minutes:

![image](https://user-images.githubusercontent.com/80815286/151590847-98ba9c1b-3350-4963-9fcc-2c12d32da2ad.png)

2. Login to a client with offline_access scope
3. Reboot the cluster
4. Wait until offlineSession expires (15 minutes)
5. Dump JVM Heap memory and search for your session

![image](https://user-images.githubusercontent.com/80815286/151591704-761ca007-1b99-43f1-9ea4-a1bdc52effde.png)

As you can see entry is imported as infinispan's "ImmortalCacheEntry" that will never expire.

**Comment by ahus1** [comment] 2022-02-01 10:18
Thanks for reporting this issue. Looking at the code and the reports you sent it looks like a bug. 

Could you please elaborate on the behavior you'd expect? Would it be sufficient if the entries in the Infinispan cache would be filled with the default expiry for the realm (might be faster on loading), or do you see a scenario where the remaining lifetime would need to be calculated per session?

**Comment by ahus1** [comment] 2022-02-01 11:34
This is a duplicate issue, see #8776. Still I want to capture requirements from the original issue creator here before I close this issue.

**Comment by giacomoa** [comment] 2022-02-02 10:56
Thanks, I'll follow issue you linked and give you further feedback there

**Comment by ahus1** [comment] 2022-02-02 13:06
Closing as a duplicate.

**Closed by ahus1** 2022-02-02 13:06 UTC
Labels: kind/bug, area/storage, team/storage-sig, status/rejected

**Comment by hmlnarik** [comment] 2022-08-05 07:19
Duplicate of #8776
