### ISSUE TITLE
lack step1.html

### ISSUE THREAD

**Issue by yang-shuaijun** [keycloak/keycloak#20640] opened 2023-05-30 07:24 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

I deployed a keycloak in production mode, and I found when I were entering into console page, it was always loading admin ui.
After inspected the page, 
step1.html (failed)net::ERR_NAME_NOT_RESOLVED
![Screenshot 2023-05-30 at 15 20 47](https://github.com/keycloak/keycloak/assets/50227537/163ad49d-2616-4b97-a2c6-bf7339997a4d)

### Version

21.1.1

### Expected behavior

Should enter into admin console page

### Actual behavior

blocked

### How to Reproduce?

The initial installation will reproduce this bug

**Comment by jonkoops** [comment] 2023-05-30 09:48
I am unable to reproduce this issue, but it sounds to me that your production environment is somehow misconfigured. Specifically, it looks like a DNS issue as `ERR_NAME_NOT_RESOLVED` means the browser cannot convert the DNS address to an IP address.

Closing this as it does not seem to be an issue with Keycloak itself.

**Closed by jonkoops** 2023-05-30 09:48 UTC
Labels: kind/bug, area/account/api, status/triage, team/other

**Comment by yang-shuaijun** [comment] 2023-05-30 10:04
Thank you for your valuable comments

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jon Koops ***@***.***>
发送时间: Tuesday, May 30, 2023 5:48:44 PM
收件人: keycloak/keycloak ***@***.***>
抄送: Picoman Yang ***@***.***>; Author ***@***.***>
主题: Re: [keycloak/keycloak] lack step1.html (Issue #20640)


I am unable to reproduce this issue, but it sounds to me that your production environment is somehow misconfigured. Specifically, it looks like a DNS issue as ERR_NAME_NOT_RESOLVED means the browser cannot convert the DNS address to an IP address.

Closing this as it does not seem to be an issue with Keycloak itself.

―
