### ISSUE TITLE
Logo is not loaded for custom theme

### ISSUE THREAD

**Issue by Degoya-Studio** [keycloak/keycloak#34066] opened 2024-10-17 19:22 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have a custom theme where I want to use a different logo.

```
├── my-cool-theme-name
│   ├── admin
│   │   ├── resources
│   │   │   ├── logo.svg
│   │   │   ├── css
│   │   │   │   ├── styles.css
│   │   └── theme.properties
│   └── ...
├── ...
```

my theme properties look like this:

```
parent=keycloak.v2
title=something
styles=css/styles.css
logo=logo.svg
```

For some reason the logo isn't being loaded. However it works for **account** with `parent=keycloak.v3`

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

my custom logo is being displayed

### Actual behavior

I only see an alternative text with a notion that the image couldn't be loaded

### How to Reproduce?

create a custom theme for the admin ui with a custom logo

**Comment by codespearhead** [comment] 2024-10-18 13:51
Show us what you see in the Chrome DevTools console and the HTML element that in theory should display the custom logo.

**Comment by Degoya-Studio** [comment] 2024-10-18 16:22
<img width="409" alt="Bildschirmfoto 2024-10-18 um 18 21 05" src="https://github.com/user-attachments/assets/48816adf-eba4-42be-9256-599d3ed42163">
<img width="978" alt="Bildschirmfoto 2024-10-18 um 18 21 45" src="https://github.com/user-attachments/assets/e2b4aea2-2ac0-4fc0-beec-8be2514a6a2a">

**Comment by codespearhead** [comment] 2024-10-18 16:42
I'm not sure SVG images are supported.

Try updating the logo property:

```bash
logo=/public/logo.svg
```

If that doesn't work, try providing a PNG image instead.

***

Related: [1].

***

[1] https://github.com/keycloak/keycloak/pull/20450

**Comment by ssilvert** [comment] 2024-10-18 17:40
I can verify that svg logos work fine if you are extending `keycloak.v2` for admin console.

You may need to add a leading slash:
`/logo.svg`

I'm going to close this now but we can reopen if you still think it's a bug.

**Closed by ssilvert** 2024-10-18 17:40 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by Degoya-Studio** [comment] 2024-10-18 17:50
/logo.svg worked indeed. Thank you. 

For v3 is it without the slash, like in this example:

https://github.com/keycloak/keycloak-quickstarts/blob/latest/extension/extend-admin-console/themes/my-cool-theme-name/admin/theme.properties

**Comment by Zhazhanan** [comment] 2024-10-24 08:34
I have a similar problem.

Area
account/login/ui

Describe the bug
the img isn't being loaded.
![Uploading image.png…](https://gitee.com/zhazhanan/pic/raw/master/202410241626039575609e1556d8ee77945c86ddb02d3.png)

 DevTools console
![Uploading image.png…](https://gitee.com/zhazhanan/pic/raw/master/20241024163020bab3880f51b26eb916c34a634eb49e5.png)



Version
26.0.0

**Comment by jonkoops** [comment] 2024-10-24 10:38
Do you see any failing requests in your network tab?

**Comment by Zhazhanan** [comment] 2024-10-28 06:52
> Do you see any failing requests in your network tab?
Didn't see any error. I created a new directory ‘public’, I found that admin/theme is ok, but the account/theme is still the same problem，as follows，
![9a8131b644f53e5ac000fcffa275278](https://github.com/user-attachments/assets/daa8f43e-7a80-4c8a-976f-e7325350171b)
![e7fa8c174286b578f6cba15243d8a29](https://github.com/user-attachments/assets/8d861369-3bfa-45fb-acf1-9e46b2e8689e)
![86197b669eb974c55a4df7d963eb8df](https://github.com/user-attachments/assets/471712ed-7e2e-4fc0-ae23-52d11dfe6d6d)

![d6a2de27e5a50337d3c4ea83a26be78](https://github.com/user-attachments/assets/65a69ca2-77a9-4faf-bff1-2821f22fc33e)
![19a59c37556cd426ef4a6f510e4dbbb](https://github.com/user-attachments/assets/f14ebaa8-3dcd-4979-be25-33b77395dff1)

**Comment by jonkoops** [comment] 2024-10-28 11:15
Since this issue is closed please open a new issue with reproducible steps. Also try to ask around the forums first.

**Comment by Zhazhanan** [comment] 2024-10-28 14:47
> account/login/theme:

I have opened a new issue #34399
