### ISSUE TITLE
Quarkus Keycloak IP restriction while accessing the keycloak

### ISSUE THREAD

**Issue by senthilkumarsn** [keycloak/keycloak#16713] opened 2023-01-31 05:04 UTC
### Description

We used to have filter tags in wildlfy version of keycloak for restricting the IP access.
The below tags are used to add the IP access filtering in standalone.xml

"urn:jboss:domain:undertow:12.0."<subsystemxmlns="{subsystem_undertow_xml_urn}"> ... <server
name="default-server"> ... <hostname="default-host" alias="localhost"> ... <filterref name="ipAccess"/> </host> </server> <filters> <expression-filter name="ipAccess"
expression="path-prefix('/auth/realms/appsync/protocol/openid-connect/token)-> ip-accesscontrol(acl={'10.0.0.0/24 allow'})"/> </filters> ... </subsystem>. In addition to the
IP range, if you want to give access to a different IP, modify the expression filter as
shown. <expression-filter name="ipAccess" expression="path-prefix('/auth/realms/appsync/
protocol/openid-connect/token) -> ip-access-control(acl={'10.22.33.11 allow','10.0.0.0/24
allow'})"/>.

We are expecting similar kind of support in quarkus keycloak distribution.

**Comment by sschu** [comment] 2023-01-31 10:12
There is already an issue (https://github.com/keycloak/keycloak/issues/12394) and PR (https://github.com/keycloak/keycloak/pull/16497) for this.

**Comment by jonkoops** [comment] 2023-01-31 12:05
Duplicate of #12394

**Closed by jonkoops** 2023-01-31 12:05 UTC
Labels: kind/enhancement, status/triage
