### ISSUE TITLE
Login with Keycloak No problem, but when reloading the Web Application 502 Bad Request

### ISSUE THREAD

**Issue by ahmad-septian** [keycloak/keycloak#24240] opened 2023-10-24 06:32 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

Previously I used the Keycloak 16 version, when I implemented the Keycloak into my project using Vite React JS there was no problem but when I updated Keycloak 22 I experienced a problem when I logged in using Keycloack there was no problem but when I entered the application project I reloaded the web I'm experiencing 502 bad requests, why?

### Version

22.0.4

### Expected behavior

When reloading the page there should be no 502 bad request problems

### Actual behavior

Bad Request 502 

### How to Reproduce?

<img width="1440" alt="image" src="https://github.com/keycloak/keycloak/assets/93763528/28186af2-dbdf-4286-a478-22bf7f5869e5">

**Comment by jonkoops** [comment] 2023-10-24 15:54
Without proper logs and more details this issue cannot be solved. Please provide minimal instructions on how to reproduce this issue locally as we cannot be expected to emulate the intricacies of  your production environment.

**Comment by ahmad-septian** [comment] 2023-10-25 03:32
<img width="657" alt="image" src="https://github.com/keycloak/keycloak/assets/93763528/1c08b40f-b2f5-4372-9210-9b83ea676151">
Logs

**Comment by jonkoops** [comment] 2023-10-25 08:49
This screenshot only show that a HTTP request has failed. You'll still need to provide logs from your server and steps to reproduce the issue.

**Comment by z0mb1ek** [comment] 2023-12-05 22:03
i see same problem with nginx and `sent too big header while reading response` error, then i increased buffers and it helped

**Comment by jonkoops** [comment] 2023-12-06 08:45
I am going to close this issue because no steps to reproduce it have been provided. If you are still experiencing this problem, please log a new issue with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by jonkoops** 2023-12-06 08:45 UTC
Labels: area/authentication, kind/bug, status/triage, team/core
