### ISSUE TITLE
LDAP User federation: LDAP: error code 49 - Invalid Credentials

### ISSUE THREAD

**Issue by Commifreak** [keycloak/keycloak#29808] opened 2024-05-23 08:24 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Any try to use user federation with ldap (either ActiveDirectory or other) fails while testing the bind creds with `2024-05-23 08:01:55,425 ERROR [org.keycloak.services] (executor-thread-52) KC-SERVICES0055: Error when authenticating to LDAP: [LDAP: error code 49 - Invalid Credentials]: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]`.

I have several other clients using same connection settings and they are working great.

I wonder if its about the password is designed? The bind user has a `§` in its password (to be more detailed, the password has also an `&`.)

Could be there an issue with the `§`?

### Version

20.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

working LDAP connection

### Actual behavior

LDAP connection error

### How to Reproduce?

see description

**Comment by michaelottofits** [comment] 2024-05-23 12:39
Check User DN and Password for a Active Directory you must use DN Attribute as Username.

**Comment by Commifreak** [comment] 2024-05-23 13:12
I know and I use them like this.

**Comment by sguilhen** [comment] 2024-05-23 18:40
I can confirm that the special character `§` is causing this issue when connecting to LDAP. It's actually a problem when we're resolving the password using the `VaultCharSecret` - converting the char[] to ByteBuffer and back to char[] is problematic because of the UTF_8 encoding used there. Switching to the String variant `VaultStringSecret` and calling `toCharArray` after it is resolved by the vault seems to fix the issue.

I'll send a PR later to fix this.

**Closed** 2024-05-27 13:11 UTC
Labels: kind/bug, area/ldap, help wanted, team/core-iam, status/auto-expire, status/auto-bump, priority/normal
