### ISSUE TITLE
Declartive user profile. When multiple attributes with options validator are defined and 1 is selected on UI shown that 2 of them have values.

### ISSUE THREAD

**Issue by OleksiiSydorov** [keycloak/keycloak#25939] opened 2024-01-05 11:24 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have defined 2 attributes, which have options validator. When i try to set value for one of those attribute on user profile page it selects for both of them.
![a1](https://github.com/keycloak/keycloak/assets/87321239/a9bcafb9-9f7a-4a78-b46c-17514f9e1fc4)
![a2](https://github.com/keycloak/keycloak/assets/87321239/90a2293d-f7c5-4745-9439-c588ab4e8221)
![a3](https://github.com/keycloak/keycloak/assets/87321239/9c76540a-9e18-40f7-a0d6-2f2400491b59)
![a4](https://github.com/keycloak/keycloak/assets/87321239/52ea50be-40c0-4687-bff1-822051be38a6)

Small hint: when i click on value which i actually select it shows blue checkmark, on the other dropdown checkmark is not shown. 
![a5](https://github.com/keycloak/keycloak/assets/87321239/bd8a0cbc-2c42-498a-82b3-f1a07921009e)

Also another way to verify that only 1 value is selected is to define Token Mapper -> UserAttribute. Create mapper for attribute a1 and a2. And if you evalue token you will see value from a1 attribute.

### Version

23.0.3

### Expected behavior

Whem multiple attributes with validator options are defined and you set **one** of this values to the user, then UI should render as a **selected** only that value you are actually select.

### Actual behavior

Multiple values are shown as a selected, even though you select only one.

### How to Reproduce?

1. Install Keycloak version 23.0.3. 
2. Enable features declarative-user-profile,account3. 
3. Create multiple attributes, minimum 2. 
4. Define validator for those attributes with type **options**
5. Add multiple values 
6. Go to the user and set value to one of the defined attributes
7. Hit save
8. Multiple values in select are shown. 

### Anything else?
 #23905

**Comment by ssilvert** [comment] 2024-01-05 21:25
@OleksiiSydorov I can't reproduce this.  Can you try it on the latest nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by Thorvaldd** [comment] 2024-01-06 13:29
@ssilvert I also can't reproduce this issue using nightly build.
I have also checked version **23.0.0**, and I was able to reproduce it.

**Comment by pedroigor** [comment] 2024-01-09 14:39
@Thorvaldd @OleksiiSydorov I can't reproduce as well using nightly. @ssilvert If we have an idea which commits fixed this, do we want to backport to 23?

**Comment by OleksiiSydorov** [comment] 2024-01-09 14:46
@pedroigor Maybe this is not related to this particular issue, but do we have mechanism to unselect value, after assigning? So, initially when no value is selected  in dropdown _default value is selecte,_ "Choose value", after i select it is no longer possible to unselect.

**Comment by pedroigor** [comment] 2024-01-09 15:01
@OleksiiSydorov That is a good point ... I know you can achieve this but when the field is marked as multivalued (e.g.: annotation `inputType` set to `multiselect`).

But even using a `multiselect` does not allow you to unset all values.

I would say we should fix both behaviors. @keycloak/ui-maintainers  wdyt?

**Closed** 2024-01-16 13:02 UTC
Labels: kind/bug, area/user-profile, area/admin/ui, status/triage, team/ui
