### ISSUE TITLE
IDELauncher doesn't work

### ISSUE THREAD

**Issue by EvgeniGordeev** [keycloak/keycloak#19679] opened 2023-04-12 19:32 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

IDELauncher doesn't work in Intellij IDEA.

### Version

21.0.2

### Expected behavior

IDELauncher works as per [quarkus readme](quarkus/README.md). 

### Actual behavior

IDE build doesn't work: 

```bash
/Users/evgeni/work/evgeni/keycloak/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/role/HotRodRoleEntity.java:58:12
java: org.infinispan.protostream.annotations.ProtoSchemaBuilderException: Failed to generate marshaller implementation class
  	at org.infinispan.protostream.annotations.impl.BaseProtoSchemaGenerator.generateAndRegister(BaseProtoSchemaGenerator.java:176)
  	at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.processClass(AutoProtoSchemaBuilderAnnotationProcessor.java:335)
  	at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.processElement(AutoProtoSchemaBuilderAnnotationProcessor.java:265)
  	at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.process(AutoProtoSchemaBuilderAnnotationProcessor.java:188)
  	at org.jetbrains.jps.javac.APIWrappers$ProcessorWrapper.process(APIWrappers.java:206)
  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
  	at org.jetbrains.jps.javac.APIWrappers$1.invoke(APIWrappers.java:362)
  	at jdk.proxy2/org.keycloak.models.map.processor.GenerateHotRodEntityImplementationsProcessor.process(Unknown Source)

java: Could not generate implementation for class: javax.annotation.processing.FilerException: Attempt to recreate a file for type org.keycloak.models.map.storage.hotRod.role.HotRodRoleEntityDelegate
```

### How to Reproduce?

* Clone latest from main - https://github.com/keycloak/keycloak/commit/863d28e232bddc1f1623bb8e214bfb8e2fface7a as of today
* `mvn install -DskipTests` works
* import into Intellij as a maven project
* run [IDELauncher](quarkus/server/src/main/java/org/keycloak/quarkus/_private/IDELauncher.java) in IDE

### Anything else?

Maybe some documentation is needed on how exactly to make it work in IDE. I noticed that docs/building.md is not up-to-date too as this command from there doesn't work any more: 

```bash
mvn -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: distribution/server-dist @ 
[ERROR] Could not find the selected project in the reactor: distribution/server-dist -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

```

**Comment by lexcao** [comment] 2023-04-29 18:25
Hi, @EvgeniGordeev 
I have faced this issue as well on my local with `IDEA 2023.1`

I find [this guide](https://github.com/keycloak/keycloak/blob/main/docs/building.md#building-project-from-the-ide) for running from IDE.  
> Make sure you don't rebuild the whole project using the IDE as it would delete the generated classes. E.g. in IntelliJ IDEA use Build → Build Project instead of Build → Rebuild Project.

Maybe there is a issue on the `IDEA 2023.1` which for run command cause rebuilding or cleaning the generated folders in some cases.

Here is a workaround works for me:
1. Build the project by Maven first by following[ this guide](https://github.com/keycloak/keycloak/blob/main/quarkus/README.md#building-the-project-the-first-time)
```
cd quarkus
mvn -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
mvn clean install -DskipTests
```
2. Then configure the IDE configure of the IDELauncher
* **enable the `Do not build before run`**
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/14901139/235318363-8050d091-849f-4742-92bb-bc35aa783ced.png">

**Comment by vmuzikar** [comment] 2023-05-02 09:16
@EvgeniGordeev Thanks for the report. We have seen some issues like that recently especially in IntelliJ. Could you please try running:
```
mvn clean -f model/map-hot-rod
```

CC: @mhajas. Maybe we should document this in [`building.md`](https://github.com/keycloak/keycloak/blob/main/docs/building.md#building-project-from-the-ide)?

**Comment by mhajas** [comment] 2023-05-03 07:21
@vmuzikar It makes sense to me to mention this issue in `building.md` guide. 

To me, it doesn't seem to be caused by our code as it works all the time with Maven. I think we should consider reporting this to the IntelliJ issue tracker if we have a reliable reproducer.

**Comment by vmuzikar** [comment] 2024-02-19 16:27
I believe this is outdated now. Haven't seen that issue for some time already, and map store is now removed. Closing it but let me know if you think otherwise.

**Closed by vmuzikar** 2024-02-19 16:27 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
