### ISSUE TITLE
Admin console inaccessible admin/master/console/ (default console is accessible)

### ISSUE THREAD

**Issue by vladimirpodr** [keycloak/keycloak#27146] opened 2024-02-19 18:03 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I cannot login to the admin console "domain.com/admin/master/console/". It is hanging on the loading spinner.

### Version

23.0.6

### Regression

- [ ] The issue is a regressions

### Expected behavior

The admin console should load!

### Actual behavior

 It is hanging on the loading spinner.
 There are no errors in the container logs.
 But in browser:
 

### How to Reproduce?

Istio injection is enabled.
TLS termination - disabled.
```
__vite-browser-external:1 Refused to frame 'http://keycloak.platform-internal.engops.gopuff.com/' because it violates the following Content Security Policy directive: "frame-src 'self'".

chromewebdata/:1 Mixed Content: The page at 'https://keycloak.platform-internal.engops.gopuff.com/admin/master/console/' was loaded over HTTPS, but requested an insecure resource 'http://keycloak.platform-internal.engops.gopuff.com/realms/master/protocol/openid-connect/3p-cookies/step1.html'. This request has been blocked; the content must be served over HTTPS.
console/:1 Uncaught {error: 'Timeout when waiting for 3rd party check iframe message.'}
```

### Anything else?

I use following Bitnami chart:
```
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.4.21
```

**Comment by SurajWijewickrama** [comment] 2024-02-21 09:25
I'm having the same issue, Did you get it sorted?

**Comment by jonkoops** [comment] 2024-02-25 17:05
Duplicate of #14666

**Closed by jonkoops** 2024-02-25 17:05 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
