### ISSUE TITLE
Cannot disable LDAP-backed user if importEnabled=false

### ISSUE THREAD

**Issue by rmuir** [keycloak/keycloak#24201] opened 2023-10-21 14:49 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

Exception looks like this:
```
[org.keycloak.services.resources.admin.UserResource] (executor-thread-9) Could not update user!: org.keycloak.models.ModelException: Not possible to write 'enabled' when updating user 'user1'
	at org.keycloak.models.utils.ReadOnlyUserModelDelegate.readOnlyException(ReadOnlyUserModelDelegate.java:146)
	at org.keycloak.models.utils.ReadOnlyUserModelDelegate.setEnabled(ReadOnlyUserModelDelegate.java:51)
	at org.keycloak.models.utils.UserModelDelegate.setEnabled(UserModelDelegate.java:65)
	at org.keycloak.storage.ldap.LDAPWritesOnlyUserModelDelegate.setEnabled(LDAPWritesOnlyUserModelDelegate.java:58)
...
        at org.keycloak.storage.ldap.mappers.msad.MSADUserAccountControlStorageMapper$MSADUserModelDelegate.setEnabled(MSADUserAccountControlStorageMapper.java:253)
...
        at org.keycloak.storage.adapter.UpdateOnlyChangeUserModelDelegate.setEnabled(UpdateOnlyChangeUserModelDelegate.java:55)
```

### Version

22.0.4

### Expected behavior

Disabling a user works and propagates bits to LDAP via MSAD user account controls

### Actual behavior

Disabling a user fails with a 400 error complaining that the UserModel `enabled` attribute can't be written. Seems like one of these decorators (LDAPWritesOnlyUserModelDelegate?) is unaware of what MSADUserAccountControlStorageMapper is doing?

### How to Reproduce?

Create WRITEABLE LDAP federated storage, disable import. Create a user and set a password.

THEN Attempt to disable a user with the admin UI (or REST API via PUT request).

### Anything else?

The bug is a little tricky because it only happens on user modifications and not initial user creation: https://github.com/keycloak/keycloak/blob/7b97272b23a9cd42596d05e8a4f4dd05d4bfa0e1/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java#L218

**Comment by rmuir** [comment] 2023-10-24 03:19
I created a reproducer for this bug here: https://github.com/rmuir/keycloak24201

It is really easy to run and doesn't take long at all, just `docker-compose up` to reproduce this issue.

I tried really hard to create a failing integration test in the keycloak repo but I think I struggled with the basics such as running them properly. From analysis of the tests, I believe the problematic untested combination with MSAD Account Controls is:
* importEnabled: false
* editMode: WRITABLE

**Comment by sguilhen** [comment] 2024-02-21 00:36
Possibly related to https://github.com/keycloak/keycloak/issues/26695

**Comment by pedroigor** [comment] 2024-03-06 14:32
@sguilhen @rmuir At least the description looks very similar. So I'm closing this one as a duplicate of https://github.com/keycloak/keycloak/issues/26695 and it was already marked as important.

**Comment by sguilhen** [comment] 2024-03-28 14:10
I'm re-opening this one as it is related to the other mentioned issue, but not the same.

**Closed** 2024-04-01 11:20 UTC
Labels: kind/bug, area/ldap, help wanted, team/core-iam, status/auto-expire, status/auto-bump, priority/normal, status/reopened
