### ISSUE TITLE
User Profile Attribute: userProfileMetadata of user details data structure does not match type definition

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#23443] opened 2023-09-21 13:42 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When debugging why my select options for declarative user profile were not working in the admin ui user details screen, I noticed that there seems to be a discrepancy between the type definition for the user profile attribute metadata and what is actually returned by the API:

![image](https://github.com/keycloak/keycloak/assets/1793007/0203bdcf-437d-401f-b648-95267eb67396)
The admin ui is assuming that the options are provided in validations but in the API they are actually in validators:
![image](https://github.com/keycloak/keycloak/assets/1793007/2abcae77-7953-4d7f-a2e7-b7e982ded0fa)

For the user profile API the Validators are returned as validations: 
![image](https://github.com/keycloak/keycloak/assets/1793007/bb2ee804-4085-41b8-863c-b031d216dc16)

So to me it looks like the user details endpoint is returning the wrong user profile attribute metadata data structure.

### Version

22.0.3

### Expected behavior

User Profile attribute metadata is returned as defined in the type definition.

### Actual behavior

User Profile attribute metadata is **NOT** returned as defined in the type definition.

### How to Reproduce?

1. Enable User profile and add a attribute with a validator
2. Go to users, create one and head to the details page
3. Check the network tab to see the user details response and look for the userProfileMetadata.

**Comment by edewit** [comment] 2023-09-28 13:51
fixed with #23250

**Closed by edewit** 2023-09-28 13:51 UTC
Labels: kind/bug, priority/critical, impact/high, area/user-profile, area/admin/ui, team/ui

**Comment by jonkoops** [comment] 2023-10-02 10:36
Duplicate of #23180
