### ISSUE TITLE
Missing "hideOnLoginPage" property on Keycloak v25 is breaking in Keycloak v26

### ISSUE THREAD

**Issue by vfrz** [keycloak/keycloak#34490] opened 2024-10-30 10:12 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

Create a SAML identity provider using the API and without the "hideOnLoginPage" property in the configuration, using Keycloak v25 (or lower).
Update to Keycloak v26, the config value is now a column in the `IDENTITY_PROVIDER` table, with a NULL value, and the console is displaying a "unknown_error" message when navigating to "Identity providers" page:
![image](https://github.com/user-attachments/assets/b2bd4d06-fa87-44bc-840e-2ad30992d3b9)

### Version

26

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak V26 should either set the value to default (false?) if the config value is not present before upgrading, or allow NULL value as it was allowed in previous versions.

### Actual behavior

Keycloak V26 console is crashing if the `HIDE_ON_LOGIN `is set to `NULL`, even if the database allows it.

### How to Reproduce?

Create a SAML identity provider using the API and without the "hideOnLoginPage" property in the configuration, using Keycloak v25 (or lower).
Update to Keycloak v26, the config value is now a column in the `IDENTITY_PROVIDER` table, with a NULL value, and the console is displaying a "unknown_error" message when navigating to "Identity providers" page:
![image](https://github.com/user-attachments/assets/b2bd4d06-fa87-44bc-840e-2ad30992d3b9)

**Comment by sschu** [comment] 2024-10-30 16:14
This is most likely a duplicate of https://github.com/keycloak/keycloak/issues/34450. Please reopen if you don't agree @vfrz

**Closed** 2024-10-30 16:14 UTC
Labels: area/saml, kind/bug, status/triage, team/core-clients
