### ISSUE TITLE
kc.sh import not creating realm client roles for admin

### ISSUE THREAD

**Issue by glandais** [keycloak/keycloak#11923] opened 2022-05-10 09:40 UTC
### Describe the bug

When importing a new realm with kc.sh import, admin can't access to the realm as client roles in master realm are not created/set.

### Version

18.0.0

### Expected behavior

Admin should be able to access a new realm imported via kc.sh import

### How to Reproduce?

admin user has to be created on started for this case, so I've set these env vars :
```bash
export KEYCLOAK_ADMIN=admin
export KEYCLOAK_ADMIN_PASSWORD=admin
```

From a fresh keycloak installation, I've started (`kc.sh start-dev`) it and I've created a `myrealm` realm and exported it with groups, roles and clients. Export is in [realm-export.txt](https://github.com/keycloak/keycloak/files/8660244/realm-export.txt)

From a fresh keycloak installation, copy this file in `data/import/` as `realm-export.json`. Start this new keycloak with `kc.sh start-dev --import-realm`.
Everything is OK.
![image](https://user-images.githubusercontent.com/864152/167597725-0042366a-47e6-4fd6-ae19-19ed9413a8ab.png)

From a fresh keycloak installation, start Keycloak with `kc.sh start-dev`.
Once started, import realm with `kc.sh import --file realm-export.json`.
I'm unable to access realm as client roles for realm are missing :
![image](https://user-images.githubusercontent.com/864152/167598897-986fdd39-c4eb-49ae-bf40-bd28dd0c0576.png)

### Anything else?

If admin user doesn't exist before first import, realm is correctly imported. When admin user is added, realm client roles are added and set in master realm.

**Comment by vmuzikar** [comment] 2022-07-19 16:07
@glandais Thank you for reporting this. Unfortunately, I was not able to reproduce. I believe your issue was related to the fact that you were running `kc.sh import` while the server was running which is unsupported (as is now stated in the docs).

Could you please try it with the latest `main`? I can see the roles correctly assigned via the `admin` Realm Role:
![Screenshot 2022-07-19 at 17 56 58](https://user-images.githubusercontent.com/13906855/179797520-44983436-5cc5-4c48-a6cf-d9b0f2519096.png)
![Screenshot 2022-07-19 at 17 57 21](https://user-images.githubusercontent.com/13906855/179797595-173e3535-2740-4006-a268-0d0ccddaf386.png)

I'm going to close this issue. Feel free to reopen if it's still valid.

**Closed by vmuzikar** 2022-07-19 16:07 UTC
Labels: kind/bug, area/dist/quarkus, status/triage
