### ISSUE TITLE
Differences in Themes Keycloak and Keycloak.V2

### ISSUE THREAD

**Issue by Andyriod** [keycloak/keycloak#15162] opened 2022-10-26 07:37 UTC
### Area

admin/ui

### Describe the bug

Hi,
in the "old" Theme under a selected client there is a "Client Scope" and a "Scope" tab.
This "Scope" tab is missing in the "new" theme.
Also in the client under the Authorization->Resources entry there is a button "Create Permission". In the old version a new page opens after click on the button. In the new version there comes an empty page.

### Version

19.0.2

### Expected behavior

In the Keycloak.V2 theme there should be an scope tab too and the create permisson button under client->authorization->resource should lead to somewhere.

### Actual behavior

In the Keycloak.V2 theme there is no scope tab and the create permisson button under client->authorization->resource leads to an empty page

### How to Reproduce?

Use the new keycloak.v2 theme.
Open any client and search for the scope tab.
Open Authorization->Resource under any client and click the create permission button

### Anything else?

Is this reproduceable? Or is it a problem with my installation?

**Comment by sschu** [comment] 2022-10-26 15:25
AFAIK this is intended, scopes can no longer be configured per client but are configured per client scope instead.

**Comment by ssilvert** [comment] 2022-10-26 18:07
Thanks @sschu.  You saved me from having to look up that earlier issue.

@Andyriod Are you OK with closing this issue?

**Comment by Andyriod** [comment] 2022-10-26 18:12
But this explains only the Scope tab. What is with the "create permissions" Button?

**Comment by ssilvert** [comment] 2022-12-07 17:28
@Andyriod I tried to reproduce your problem with the "create permissions" link.  But I don't see the empty page.

Can you try this on version 20.x ?

**Comment by ssilvert** [comment] 2023-01-03 19:06
Unable to reproduce.  Closing.

**Closed** 2023-01-03 19:06 UTC
Labels: kind/bug, area/admin/ui, status/triage
