### ISSUE TITLE
AD session is broken when "You are already logged-in" screen is displayed

### ISSUE THREAD

**Issue by llatour** [keycloak/keycloak#11746] opened 2022-04-28 14:32 UTC
### Describe the bug

In some cases message "You are already logged-in" is shown. For example:
1) Open http://localhost:8081/auth/admin in browser tab1. Login page is shown
2) Open http://localhost:8081/auth/admin in browser tab2. Login page is shown
3) Authenticate as admin/admin in tab2. I am redirected to admin console
4) Switch to tab1 and authenticate as admin/admin. Message "You are already logged-in" is displayed

In addition to this, if an identity provider is used to log in, sessions seems to be mixed on keycloak side and it's impossible to log out:
1) Open http://localhost:8081/auth/admin in browser tab1. Login page is shown, press on identity provider button: AD login page is displayed (microsoft login for exemple)
2) Open http://localhost:8081/auth/admin in browser tab2. Login page is shown, press on identity provider button: AD login page is displayed (microsoft login for exemple)
3) Authenticate on identity provider in tab2. I am redirected to client application
4) Switch to tab1 and authenticate on identity provider. Message "You are already logged-in" is displayed
5) Press on "back to application", I am redirected to client application

From this point when trying to logout either on tab1 or tab2, AD displays a logout error and complains about a bad session ID.

### Version

12.0.4

### Expected behavior

Either do not display page "you are already logged in" at all and redirect to clietn application
Or at least do not mix sessions and allow user to logout.

### Anything else?

linked to bug https://issues.redhat.com/browse/KEYCLOAK-5179
link to discussion: https://lists.jboss.org/pipermail/keycloak-dev/2019-June/012157.html

**Comment by mposolda** [comment] 2023-04-04 09:37
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by rmartinc** [comment] 2024-02-06 09:59
I'm closing this as duplicate of https://github.com/keycloak/keycloak/issues/12406.
The "You are already logged-in" is a known issue that has been chased for a long time by @mposolda. Current 23.0.6 has improved it although there are still known issues like #24112 and probably more situations are still complicated to be managed.

**Closed by rmartinc** 2024-02-06 09:59 UTC
Labels: area/oidc, kind/bug, status/triage, team/core-clients
