### ISSUE TITLE
Keycloak Group Attribute APIs failing in case of large payload size

### ISSUE THREAD

**Issue by kurianbenoy-aot** [keycloak/keycloak#9267] opened 2021-12-21 05:16 UTC
### Describe the bug

Our team have been using Keycloak attributes in groups to store some large payload values. But we have noticing when adding a large payload like the below example:

```
{
  "id": "42f508af-03f1-42ee-aafa-721cd06a9962",
  "name": "test-group",
  "path": "/formsflow-analytics/test-group",
  "attributes": {
    "dashboards": [
      "[{'6': 'New Business License Application'}, {'7': 'Freedom Of Information Form'}, {'12': 'dashboard4'}, {'1': 'SAMPLE'}, {'2': 'SAMPL'}, {'5': 'New Business License Application'}, {'9': 'Freedom of Information and Protection of Privacy'},{'1': 'GROUP1'},{'2': 'SAMPLE1'}]"
    ]
  },
  "realmRoles": [],
  "clientRoles": {},
  "subGroups": [],
  "access": {
    "view": true,
    "manage": true,
    "manageMembership": true
  }
}
```
gives a 500 internal server error with response:

```
{"error":"unknown_error"}
```

The keycloak error logs can be found in [this link](https://gist.github.com/kurianbenoy-aot/5c77cf8f30185501d0c930fdb68ee46f).

### Version

14.0.0, 16.0.1

### Expected behavior

Expected the PUT API to update in case of a large payload

### Actual behavior

500 internal server error

### How to Reproduce?

The issue can be reproduced by creating a new group:

add attribute: dashboards

with values as: `[{'6': 'New Business License Application'}, {'7': 'Freedom Of Information Form'}, {'1': 'SAMPLE'}, {'2': 'SAMPL'}, {'5': 'New Business License Application'}, {'9': 'Freedom of Information and Protection of Privacy'}, {'0': 'GROUP1'}, {'11': 'SAMPLE2'}]`

Add a new element to existing object

{'12', 'SAMPLE'}

This will result in an unexpected error

**Comment by kurianbenoy-aot** [comment] 2021-12-23 01:11
Is there any option to increase group attributes size dynamically?

**Comment by abstractj** [comment] 2021-12-23 19:11
@kurianbenoy-aot did you manage to reproduce the issue using the latest Keycloak release 16.1.0.Final?

**Comment by kurianbenoy-aot** [comment] 2021-12-27 04:19
@abstractj I tried in v16.1.0 version as well with `jboss/keycloak:16.1.0` docker image. And I still got the same error in Keycloak with 500 internal server error. Checking the logs, I had noticed the issue has been because of:

```
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)

at org.postgresql.jdbc@42.2.5//org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)

at org.postgresql.jdbc@42.2.5//org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)

at org.postgresql.jdbc@42.2.5//org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)

at org.postgresql.jdbc@42.2.5//org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)

at org.postgresql.jdbc@42.2.5//org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)

at org.postgresql.jdbc@42.2.5//org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)

at org.postgresql.jdbc@42.2.5//org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)

at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:537)

at org.hibernate@5.3.24.Final//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
```

**Comment by rmartinc** [comment] 2023-02-17 10:27
The table GROUP_ATTRIBUTE in its column VALUE has type NVARCHAR(255). You are inserting a longer data. You can always modify to increase the nvarchar but you have to take care with upgrades, maybe the column is changed again.

This is not a direct bug in the software. Closing this as not a bug.

**Closed by rmartinc** 2023-02-17 10:27 UTC
Labels: kind/bug, area/admin/api, status/triage
