### ISSUE TITLE
Empty screen on login to admin console by non-admin user

### ISSUE THREAD

**Issue by mvk37** [keycloak/keycloak#28753] opened 2024-04-15 16:56 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I got to admin console http://localhost:8080/admin/ and trying to login by user who doesn't have admin privileges I see an empty screen and spinning wheel which is spinning forever.

On a background HTTP GET http://localhost:8080/admin/serverinfo call returns '403 - Forbidden', which is correct. But could you look how to show it on the screen in a user readable form?

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

User see a screen with message like 'Forbidden'.

### Actual behavior

Empty screen with spinning wheel

### How to Reproduce?

Login to admin console 
In a master realm create a new user, add password.
Logout from admin console
Try to login to admin console as a new user. You will see empty screen with spinning wheel forever

**Comment by mvk37** [comment] 2024-04-15 16:57
![forbidden_user_login](https://github.com/keycloak/keycloak/assets/43886879/1b01e8ec-467d-4e77-8842-0ed92987021a)

**Comment by jonkoops** [comment] 2024-04-16 10:33
Duplicate of #17749

**Closed by jonkoops** 2024-04-16 10:33 UTC
Labels: kind/bug, area/admin/ui, help wanted, team/ui, status/auto-expire, status/auto-bump, priority/normal

**Comment by sgs-umar** [comment] 2024-08-23 06:09
Facing the same issue in the latest version of keycloak. Is there fix or configuration provided? @keycloak-bot
