### ISSUE TITLE
Race when creating client protocol mappers (ClientManager#enableServiceAccount) resulting in duplicate entries

### ISSUE THREAD

**Issue by mwalser** [keycloak/keycloak#10417] opened 2022-02-23 13:29 UTC
### Describe the bug

It is possible for ClientManager#enableServiceAccount to be called concurrently (for example by TokenEndpoint#processGrantRequest -> TokenEndpoint#clientCredentialsGrant -> ClientManager#enableServiceAccount) this results in duplicate protocol mapper entries

### Version

16.1.1

### Expected behavior

Only three protocol mapper entries are created: Client IP Address, Client Host, Client ID

### Actual behavior

Six protocol mapper entries are created: Client IP Address, Client Host, Client ID, Client IP Address, Client Host, Client ID

### How to Reproduce?

Run Keycloak in a Docker container:
```
docker run --rm --name keycloak -p 8080:8080 -e KEYCLOAK_USER=keycloak -e KEYCLOAK_PASSWORD=keycloak -e KEYCLOAK_LOGLEVEL=DEBUG jboss/keycloak:16.1.1
```

Use the following Java Code to reproduce the behavior:
```java
import org.keycloak.admin.client.KeycloakBuilder;
import org.keycloak.representations.idm.ClientRepresentation;
import org.keycloak.representations.idm.ProtocolMapperRepresentation;

import java.util.Collections;
import java.util.stream.Collectors;

import javax.ws.rs.NotFoundException;

public class Reproducer {

	public static void main(String[] args) throws InterruptedException {
		// Prerequisite:
		// docker run --rm --name keycloak -p 8080:8080 -e KEYCLOAK_USER=keycloak -e KEYCLOAK_PASSWORD=keycloak -e KEYCLOAK_LOGLEVEL=DEBUG jboss/keycloak:16.1.1

		var adminClient = KeycloakBuilder.builder()
				.serverUrl("http://localhost:8080/auth/")
				.clientId("admin-cli")
				.username("keycloak")
				.password("keycloak")
				.realm("master")
				.build();
		var clientsResource = adminClient.realm("master").clients();

		var clientRepresentation = new ClientRepresentation();
		clientRepresentation.setId("reproducer");
		clientRepresentation.setEnabled(true);
		clientRepresentation.setServiceAccountsEnabled(true);
		clientRepresentation.setSecret("very-secret");
		clientRepresentation.setProtocolMappers(Collections.emptyList()); // no protocol mappers defined

		// Clean up previous runs
		try {
			clientsResource.get("reproducer").remove();
		} catch (NotFoundException ex) {
			// ignore
		}

		// At first the client gets created with the default protocol mappers
		clientsResource.create(clientRepresentation);

		// When we update the client the protocol mappers are cleared
		clientsResource.get("reproducer").update(clientRepresentation);

		Runnable doSomethingWithOurReproducerClient = () -> {
			var reproducerClient = KeycloakBuilder.builder()
					.serverUrl("http://localhost:8080/auth/")
					.clientId("reproducer")
					.clientSecret("very-secret")
					.grantType("client_credentials")
					.realm("master")
					.build();

			// Execute a random action
			reproducerClient.tokenManager().grantToken();
		};

		// Do two things in parallel using the "reproducer" client
		var thread1 = new Thread(doSomethingWithOurReproducerClient);
		var thread2 = new Thread(doSomethingWithOurReproducerClient);
		thread1.start();
		thread2.start();
		thread1.join();
		thread2.join();

		// Check
		var mappers = clientsResource.get("reproducer").getProtocolMappers().getMappers();

		if(mappers.size() > 3) {
			System.out.println("Reproducer successful. Protocol mappers: ");
			System.out.println(mappers.stream().map(ProtocolMapperRepresentation::getName).collect(Collectors.joining("\n")));
		} else {
			System.out.println("Reproducer failed");
		}
	}
}
```

Observe the protocol mappers being created twice:
```
13:08:29,935 DEBUG [org.keycloak.protocol.oidc.endpoints.TokenEndpoint] (default task-2) Service account user for client 'reproducer' not found or default protocol mapper for service account not found. Creating now
13:08:29,936 DEBUG [org.keycloak.services.managers.ClientManager] (default task-2) Creating service account protocol mapper 'Client ID' for client 'reproducer'
13:08:29,937 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (default task-1) client authenticator SUCCESS: client-secret
13:08:29,937 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (default task-1) Client reproducer authenticated by client-secret
13:08:29,937 DEBUG [org.keycloak.services.managers.ClientManager] (default task-2) Creating service account protocol mapper 'Client Host' for client 'reproducer'
13:08:29,937 DEBUG [org.keycloak.services.managers.ClientManager] (default task-2) Creating service account protocol mapper 'Client IP Address' for client 'reproducer'
13:08:29,937 DEBUG [org.keycloak.protocol.oidc.endpoints.TokenEndpoint] (default task-1) Service account user for client 'reproducer' not found or default protocol mapper for service account not found. Creating now
13:08:29,941 DEBUG [org.keycloak.services.managers.ClientManager] (default task-1) Creating service account protocol mapper 'Client ID' for client 'reproducer'
13:08:29,941 DEBUG [org.keycloak.services.managers.ClientManager] (default task-1) Creating service account protocol mapper 'Client Host' for client 'reproducer'
13:08:29,941 DEBUG [org.keycloak.services.managers.ClientManager] (default task-1) Creating service account protocol mapper 'Client IP Address' for client 'reproducer'
```

Observe two entries for each protocol mapper in the UI:
![image](https://user-images.githubusercontent.com/2938826/155328007-2358a9ca-8d36-4052-8567-0c3e793af7c1.png)

### Anything else?

The presence of these duplicate protocol mapper entries causes some Keycloak REST endpoints to fail due to assumptions that protocol mapper names are unique.

## Possible solution

Mentioned in this comment https://github.com/keycloak/keycloak/issues/10417#issuecomment-2367775925

**Comment by fredlb** [comment] 2022-10-04 08:22
I reproduced this (with the example code above) for Keycloak 19.0.0 as well.

**Comment by creckord** [comment] 2022-10-20 07:57
We can trigger this problem on our production Keycloak (18.0.1) even for clients that already contain the three mappers just by requesting tokens for the client in parallel. So it might not even be necessary to have a "fresh" client without mappers.

Since we are also using the Keycloak operator, this triggers massive amounts of error logs in Keycloak for us (an `IllegalStateException: Duplicate key` is thrown for every affected client on every reconciliation run), rendering any log monitoring useless.

**Comment by mposolda** [comment] 2023-03-06 10:25
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

**Comment by mabartos** [comment] 2023-12-04 15:57
It is valid even for Keycloak 23. I was able to reproduce it with the help of the provided reproducer (thanks @mwalser). You do not need to run Keycloak in a container as described above, you can just start Quarkus Keycloak distribution via the `kc.sh start-dev --http-relative-path=auth/` command.

The `service-account-reproducer` service account user for the `reproducer` client is properly created, but the protocol mappers are not. There are duplications stored in DB, indeed.

In this log, you can check the code flow of 2 threads and their transactions management:
```
2023-12-04 16:11:39,327 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) new JtaTransactionWrapper
2023-12-04 16:11:39,327 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) was existing? false
2023-12-04 16:11:39,328 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-2) new JtaTransactionWrapper
2023-12-04 16:11:39,328 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-2) was existing? false
2023-12-04 16:11:39,329 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (executor-thread-1) AUTHENTICATE CLIENT
2023-12-04 16:11:39,329 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-1) client authenticator: client-secret
2023-12-04 16:11:39,329 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (executor-thread-2) AUTHENTICATE CLIENT
2023-12-04 16:11:39,329 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-2) client authenticator: client-secret
2023-12-04 16:11:39,336 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-1) client authenticator SUCCESS: client-secret
2023-12-04 16:11:39,336 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-2) client authenticator SUCCESS: client-secret
2023-12-04 16:11:39,336 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-2) Client reproducer authenticated by client-secret
2023-12-04 16:11:39,336 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-1) Client reproducer authenticated by client-secret
2023-12-04 16:11:39,338 DEBUG [org.keycloak.protocol.oidc.endpoints.TokenEndpoint] (executor-thread-1) Service account user for client 'reproducer' not found or default protocol mapper for service account not found. Creating now
2023-12-04 16:11:39,338 DEBUG [org.keycloak.services.managers.ClientManager] (executor-thread-1) Creating service account protocol mapper 'Client ID' for client 'reproducer'
2023-12-04 16:11:39,339 DEBUG [org.keycloak.protocol.oidc.endpoints.TokenEndpoint] (executor-thread-2) Service account user for client 'reproducer' not found or default protocol mapper for service account not found. Creating now
2023-12-04 16:11:39,339 DEBUG [org.keycloak.services.managers.ClientManager] (executor-thread-2) Creating service account protocol mapper 'Client ID' for client 'reproducer'
2023-12-04 16:11:39,339 DEBUG [org.keycloak.services.managers.ClientManager] (executor-thread-1) Creating service account protocol mapper 'Client Host' for client 'reproducer'
2023-12-04 16:11:39,339 DEBUG [org.keycloak.services.managers.ClientManager] (executor-thread-1) Creating service account protocol mapper 'Client IP Address' for client 'reproducer'
2023-12-04 16:11:39,339 DEBUG [org.keycloak.services.managers.ClientManager] (executor-thread-2) Creating service account protocol mapper 'Client Host' for client 'reproducer'
2023-12-04 16:11:39,339 DEBUG [org.keycloak.services.managers.ClientManager] (executor-thread-2) Creating service account protocol mapper 'Client IP Address' for client 'reproducer'
2023-12-04 16:11:39,343 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (executor-thread-2) Removing root authSession 'e5328ac0-ea2b-4dd5-b5b3-f29aae93423e'. Expire restart cookie: true
2023-12-04 16:11:39,343 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (executor-thread-1) Removing root authSession '8acd76ae-2b98-4e94-9fec-7e072f074d40'. Expire restart cookie: true
2023-12-04 16:11:39,356 DEBUG [org.keycloak.services.resources.Cors] (executor-thread-1) Added CORS headers to response
2023-12-04 16:11:39,357 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper  commit
2023-12-04 16:11:39,360 DEBUG [org.keycloak.services.resources.Cors] (executor-thread-2) Added CORS headers to response
2023-12-04 16:11:39,360 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-2) JtaTransactionWrapper  commit
2023-12-04 16:11:39,361 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper end
```

After the TX commit execution in thread-2, the duplicates are present for the client. I think good clue would be to investigate the process behind the `Processing flush-time cascades`. 
```
2023-12-04 16:38:39,740 DEBUG [org.hibernate.sql.results.internal.ResultsHelper] (executor-thread-2) Collection fully initialized: [org.keycloak.models.jpa.entities.ClientEntity.registeredNodes#reproducer]
2023-12-04 16:38:39,740 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (executor-thread-2) Processing flush-time cascades
2023-12-04 16:38:39,740 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (executor-thread-2) Dirty checking collections
...
...
...
2023-12-04 16:38:39,757 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) Listing entities:
2023-12-04 16:38:39,757 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) org.keycloak.models.jpa.entities.ProtocolMapperEntity{protocol=openid-connect, protocolMapper=oidc-usersessionmodel-note-mapper, name=Client Host, client=org.keycloak.models.jpa.entities.ClientEntity#reproducer, id=5da9620f-485a-4e4d-8895-06a67139752c, clientScope=null, config=[clientHost, true, true, true, clientHost, String]}
2023-12-04 16:38:39,757 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) org.keycloak.models.jpa.entities.ProtocolMapperEntity{protocol=openid-connect, protocolMapper=oidc-usersessionmodel-note-mapper, name=Client ID, client=org.keycloak.models.jpa.entities.ClientEntity#reproducer, id=438798e4-8dfd-4500-93c1-7b8ef1181931, clientScope=null, config=[client_id, true, true, true, client_id, String]}
2023-12-04 16:38:39,758 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) org.keycloak.models.jpa.entities.ProtocolMapperEntity{protocol=openid-connect, protocolMapper=oidc-usersessionmodel-note-mapper, name=Client ID, client=org.keycloak.models.jpa.entities.ClientEntity#reproducer, id=446cfe38-c195-4183-8128-42521b459a80, clientScope=null, config=[client_id, true, true, true, client_id, String]}
2023-12-04 16:38:39,758 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) org.keycloak.models.jpa.entities.ProtocolMapperEntity{protocol=openid-connect, protocolMapper=oidc-usersessionmodel-note-mapper, name=Client Host, client=org.keycloak.models.jpa.entities.ClientEntity#reproducer, id=1adfdd8e-f69b-48b1-bb74-2fb3f0c333da, clientScope=null, config=[clientHost, true, true, true, clientHost, String]}
2023-12-04 16:38:39,758 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) org.keycloak.models.jpa.entities.ProtocolMapperEntity{protocol=openid-connect, protocolMapper=oidc-usersessionmodel-note-mapper, name=Client IP Address, client=org.keycloak.models.jpa.entities.ClientEntity#reproducer, id=e29fdf98-6eda-489b-947a-aa5040449a78, clientScope=null, config=[clientAddress, true, true, true, clientAddress, String]}
2023-12-04 16:38:39,758 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) org.keycloak.models.jpa.entities.ProtocolMapperEntity{protocol=openid-connect, protocolMapper=oidc-usersessionmodel-note-mapper, name=Client IP Address, client=org.keycloak.models.jpa.entities.ClientEntity#reproducer, id=b4a2f5c6-389d-4ef3-a6e2-886e8310c294, clientScope=null, config=[clientAddress, true, true, true, clientAddress, String]}

```

The uniqueness validation is made on the adapter level (`jpa/ClientAdapter`), and there is no constraint on the JPA entity to have some composite key for protocol mappers. As the process flow is executed simultaneously and transactions are not committed, I'd assume the validation is completely skipped on the Hibernate level. Otherwise, I cannot explain to myself, that after executing commit phase in thread-1, the commit phase in thread-2 does not fail.  

But I'm not so much experienced in this area. I think it's more store-related.

@keycloak/store Could you take a look at it? Thanks

**Comment by ksawerykarwacki** [comment] 2024-06-06 13:56
Any plans to revisit that? It is still present and causes a lot of troubles.

**Comment by mabartos** [comment] 2024-08-14 14:52
@mposolda @rmartinc @jonkoops 
The issue is also reproducible by the test below in the latest main. 

Put it into the `org.keycloak.testsuite.admin.concurrency.ConcurrencyTest` class or some test class extending `AbstractConcurrencyTest`. The final count of protocol mappers should be 3.

```
@Test
    public void createClientWithServiceAccountAndDefaultProtocolMappers() throws Throwable {
        var clientRepresentation = new ClientRepresentation();
        clientRepresentation.setClientId("reproducer");
        clientRepresentation.setEnabled(true);
        clientRepresentation.setServiceAccountsEnabled(true);
        clientRepresentation.setSecret("very-secret");
        clientRepresentation.setProtocolMappers(Collections.emptyList()); // no protocol mappers defined

        try (var response = testRealm().clients().create(clientRepresentation)) {
            assertEquals(201, response.getStatus());
        }

        var clientRep = testRealm().clients().findByClientId("reproducer").stream().findFirst().orElse(null);
        assertNotNull(clientRep);

        var clientResource = testRealm().clients().get(clientRep.getId());
        assertNotNull(clientResource);

        assertEquals(3, clientRep.getProtocolMappers().size());
        clientRepresentation.setProtocolMappers(Collections.emptyList());

        // delete protocol mappers
        var protocolMappersResource = clientResource.getProtocolMappers();
        protocolMappersResource.getMappers().forEach(f -> clientResource.getProtocolMappers().delete(f.getId()));

        assertEquals(0, protocolMappersResource.getMappers().size());

        var serviceAccount = clientResource.getServiceAccountUser();
        assertNotNull(serviceAccount);

        concurrentTest((threadIndex, keycloak, realm) -> {
            try (var reproducerClient = KeycloakBuilder.builder()
                    .serverUrl("http://localhost:8180/auth/")
                    .clientId("reproducer")
                    .clientSecret("very-secret")
                    .grantType("client_credentials")
                    .realm("test")
                    .build()) {
                reproducerClient.tokenManager().grantToken(); // Execute a random action
            }

            System.err.println("Created protocol mappers with their IDs");
            protocolMappersResource.getMappers().forEach(f -> System.err.println(f.getId() + ":" + f.getName()));
            assertEquals(3, clientResource.getProtocolMappers().getMappers().size());
        });
    }
```

**Comment by mposolda** [comment] 2024-09-23 10:11
Some ideas for fixing this:

1) Adding DB constraint. The disadvantage is that this is DB schema change, which makes it harder if we need to backport this to RH-SSO 7.6 (which can be probably the case). Also it is possible that some customers already have duplicated protocol mappers in their DB, so we will need to make sure that migration does not fail for them in that case. And I am not sure if we can safely achieve this...

2) The bug probably does not apply when clientTypes feature is enabled - https://github.com/keycloak/keycloak/blob/25.0.6/services/src/main/java/org/keycloak/services/managers/ClientManager.java#L170 . So the option might be to fix this bug by making the clientTypes supported and enabled by default. However this won't help with the RH-SSO 7.6 and clientTypes is even the experimental feature right now.

3) Can we do something with clientScopes? I can imagine we can have dedicated clientScope with the protocol mappers for service account. Probably with the switch "Include in token scope" false. Then in the `ClientManager.enableServiceAccount`, we can just add this clientScope to the client instead of creating protocol mappers. Regarding migration, we can add the clientScope to the existing realms, but IMO we don't need to update any clients (as clients possibly already have those protocol mappers on themselves).

4) Anything else?

My favourite approach is 3 right now.

**Comment by rmartinc** [comment] 2024-10-30 15:11
I also thought about this one some weeks ago and fix is not clear to me. The direct option 1 (DB constraint) is complicated because depends on null columns with different behaviors in the different databases. So I would completely forget about that option.

I also considered option 3 as the easiest one. Because the table that joins client scopes and client is CLIENT_SCOPE_CLIENT which has key CLIENT_ID-SCOPE_ID so it would fail in a race as a duplicate key. So we are protected against races throwing an error. But for me the weird point was migration or managing previous conditions.

Right now the enablement of service direct grants creates the user and three mappers (if needed), but removal just deletes the user and the mappers remains there if exist. That's what I don't like, that current behavior is quite erratic.

Following your idea we can do the following:

1. Migration just create the service-account scope for all realms.
2. When service account is enabled create the service account user (if not already created), assign the scope as default (if not already assigned). (It can happen that the protocol mappers are already there, maybe remove them here too? I suppose delete is OK as uses the ID and should be OK for races)
3. When service account is disabled remove the user if exists. (We can also remove the scope from the client but we are not doing that right now with individual mappers so I would do the same.)

That was my problem, I don't see a clear / direct / clean solution for this. :smile: @mposolda WDYT?

**Closed** 2024-11-07 07:45 UTC
Labels: kind/bug, priority/important, area/storage, team/rh-iam, team/core-clients, status/bumped-by-bot

**Comment by jonkoops** [comment] 2024-11-07 11:07
Considering the priority on this one this likely deserves a backport, wdyt @mposolda?

**Comment by rmartinc** [comment] 2024-11-11 11:34
I'm not in favor of backporting because it's a change in behavior and all the notes are set for 26.1. So doing the backport would need changes in the upgrading notes also in main. I think that is OK for 26.1.
