### ISSUE TITLE
Space in path causes build and start failures using kc.bat

### ISSUE THREAD

**Issue by baparker** [keycloak/keycloak#21419] opened 2023-07-04 01:08 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I upgraded from 21.0.2 to 21.1.2, and I am getting an error building or starting Keycloak using the batch file on Windows:
![image](https://github.com/keycloak/keycloak/assets/3460048/83c87935-61ba-44ef-93ee-5d0d30a78c38)

The batch file is no longer handling a path with a space.

It seems at least some of the changes in the following commit https://github.com/keycloak/keycloak/commit/1c9992fdaeff9566fd8f734ec5fdbf82c7fb5720 caused the error.

### Version

21.1.2

### Expected behavior

With a space in Keycloak's path, both the build and start should complete successfully.

### Actual behavior

With a space in Keycloak's path, both the build and start are failing with an error.

### How to Reproduce?

1) On Windows, unzip Keycloak 21.1.2 to a location with a space e.g. C:\Program Files\Keycloak
2) In the terminal, run bin\kc.bat start (or bin\kc.bat build --db=<mysql/postgres/etc.>)

**Comment by sschu** [comment] 2023-07-04 11:37
This is a duplicate of https://github.com/keycloak/keycloak/issues/20115 with an open PR to fix it: https://github.com/keycloak/keycloak/pull/20212

**Closed by sschu** 2023-07-04 11:37 UTC
Labels: kind/bug, area/core, status/triage, team/core
