### ISSUE TITLE
Admin page stuck at loading after adding ingress controller

### ISSUE THREAD

**Issue by taragurung** [keycloak/keycloak#19590] opened 2023-04-07 12:57 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I followed this docs to install the Keycloak 
https://www.keycloak.org/getting-started/getting-started-kube

**Deployed deployment and when checking with Port-Forward it works no issues**. and Once I add the **ingress controller** the admin console page gets stuck at **Loading the admin console** 

- Tried changing the env related to host and all as found in different thread but nothing worked.

This is what I have now
```
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "XXXX"
        - name: KC_HOSTNAME_URL
          value: "https://mydomain.com/"
        - name:  PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_HOSTNAME_ADMIN_URL
          value: "https://mydomain.com/admin/master/console"
        - name: KC_HOSTNAME
          value: "mydomain.com"
        - name: KEYCLOAK_HTTP_ENABLED
          value: "true"
```
         
        

### Version

21.0.2

### Expected behavior

Admin console loading successfully

### Actual behavior

Admins console page stuck at loading

### How to Reproduce?

1. follow the docs to install the deployment mentioned above
2. Install the ingress controller following the documentation 
3. try accessing the admin console page

**Comment by ssilvert** [comment] 2023-04-07 18:56
This is a duplicate of https://github.com/keycloak/keycloak/issues/14666

We are aggregating these issues there.

**Closed by ssilvert** 2023-04-07 18:56 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
