### ISSUE TITLE
[Jenkins Operator CI] - Test remote - KeycloakIngressTest.testIngressOnHTTP

### ISSUE THREAD

**Issue by wojnarfilip** [keycloak/keycloak#34900] opened 2024-11-13 08:15 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

https://keycloak-jenkins.com/view/OpenShift/job/rhbk-operator-test-pipeline/896/testReport/org.keycloak.operator.testsuite.integration/KeycloakIngressTest/testIngressOnHTTP/

```
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a Lambda expression in org.keycloak.operator.testsuite.utils.K8sUtils found status KeycloakStatusCondition{type='Ready', status=False, message='Waiting for more replicas'} and expected status true within 5 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at org.keycloak.operator.testsuite.utils.K8sUtils.waitForKeycloakToBeReady(K8sUtils.java:104)
	at org.keycloak.operator.testsuite.utils.K8sUtils.deployKeycloak(K8sUtils.java:94)
	at org.keycloak.operator.testsuite.utils.K8sUtils.deployKeycloak(K8sUtils.java:63)
	at org.keycloak.operator.testsuite.integration.KeycloakIngressTest.testIngressOnHTTP(KeycloakIngressTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:973)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:823)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.AssertionError: found status KeycloakStatusCondition{type='Ready', status=False, message='Waiting for more replicas'} and expected status true
	at org.keycloak.operator.testsuite.utils.CRAssert.assertKeycloakStatusCondition(CRAssert.java:59)
	at org.keycloak.operator.testsuite.utils.CRAssert.assertKeycloakStatusCondition(CRAssert.java:44)
	at org.keycloak.operator.testsuite.utils.CRAssert.assertKeycloakStatusCondition(CRAssert.java:39)
	at org.keycloak.operator.testsuite.utils.K8sUtils.lambda$waitForKeycloakToBeReady$1(K8sUtils.java:107)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

- 

### Actual behavior

- 

### How to Reproduce?

-

**Comment by shawkins** [comment] 2024-11-13 13:39
Duplicate of #34868

**Closed by shawkins** 2024-11-13 13:39 UTC
Labels: kind/bug, area/ci, team/cloud-native, status/triage, team/continuous-testing, flaky-job, team/core-shared
