### ISSUE TITLE
Workflow failure - User Federation Tests: LDAPSamlIdPInitiatedVaryingLetterCaseTest

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#32884] opened 2024-09-13 06:10 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
Expected: response status code matches is <302>
     but: was <HttpResponseProxy{HTTP/1.1 400 Bad Request [Cache-Control: no-store, must-revalidate, max-age=0, Set-Cookie: 
```

https://keycloak-jenkins/view/Keycloak/job/universal-test-pipeline-server/4002/artifact/user_federation_tests-rhds12/tests.log

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by sguilhen** [comment] 2024-09-24 15:19
Closing this as a duplicate of https://github.com/keycloak/keycloak/issues/33231

**Closed by sguilhen** 2024-09-24 15:19 UTC
Labels: kind/bug, priority/important, area/ci, status/triage, flaky-job, team/core-iam

**Comment by jonkoops** [comment] 2024-09-24 16:16
Duplicate of #33231
