### ISSUE TITLE
Keycloak 26.0.0/26.0.1 Import Issue: Multiple Realms Not Imported, Duplicated Realm Imported Instead

### ISSUE THREAD

**Issue by mikolajMacioszczyk** [keycloak/keycloak#34095] opened 2024-10-18 13:05 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

I am encountering an issue with Keycloak versions 26.0.0 and 26.0.1 when attempting to import multiple realms through the file-based import method. Specifically, I am mounting a directory with multiple realm configuration files at /opt/keycloak/data/import/. However, instead of all realms being imported, only one realm is imported repeatedly, overwriting the others.

### Version

26.0.1, 26.0.0

### Regression

- [x] The issue is a regression

### Expected behavior

All provided realms should be imported.

### Actual behavior

Only one realm is imported multiple times, overwriting any other realms. There seems to be no pattern based on the alphabetical order or file structure of the realms in the directory.

### How to Reproduce?

1. Create multiple realm files (e.g., realm1.json, realm2.json, realm3.json).
2. Mount these realm files to /opt/keycloak/data/import/.
3. Start Keycloak and check the imported realms.

### Anything else?

In the logs, I repeatedly see messages like:
``` 
[org.keycloak.exportimport.util.ImportUtils] (main) Realm 'realm2' already exists. Removing it before import 
[org.keycloak.exportimport.util.ImportUtils] (main) Realm 'realm2' imported
```

Additional Details:
When attempting to create a new realm through the Admin GUI after encountering this issue, I receive the following error:
```
409 Conflict: "Client id 'account-console' already exists"
```

**Comment by codespearhead** [comment] 2024-10-18 13:36
Please make sure all Keycloak nodes are stopped prior to importing the realms [1][2].

Relevant files to the potential problem: [1][2].

***

[1] https://github.com/keycloak/keycloak/blob/e9823d0504c0ec8a05e3f1a312dc2d8cd843fcc9/docs/guides/server/importExport.adoc?plain=1#L19
[2] https://www.keycloak.org/server/importExport
[1] https://github.com/keycloak/keycloak/blob/e9823d0504c0ec8a05e3f1a312dc2d8cd843fcc9/model/storage-services/src/main/java/org/keycloak/exportimport/dir/DirImportProvider.java#L46
[2] https://github.com/keycloak/keycloak/blob/e9823d0504c0ec8a05e3f1a312dc2d8cd843fcc9/testsuite/model/src/test/java/org/keycloak/testsuite/model/exportimport/ImportModelTest.java#L101

**Comment by mikolajMacioszczyk** [comment] 2024-10-21 05:09
> Please ensure that all Keycloak nodes are stopped prior to running the import command [1][2].
> 
> Relevant files to the potential problem: [3][4].
> 
> [1] https://www.keycloak.org/server/importExport [2]
> 
> https://github.com/keycloak/keycloak/blob/e9823d0504c0ec8a05e3f1a312dc2d8cd843fcc9/docs/guides/server/importExport.adoc?plain=1#L19
> 
> 
> [1]
> https://github.com/keycloak/keycloak/blob/e9823d0504c0ec8a05e3f1a312dc2d8cd843fcc9/model/storage-services/src/main/java/org/keycloak/exportimport/dir/DirImportProvider.java#L46
> 
> 
> [2]
> https://github.com/keycloak/keycloak/blob/e9823d0504c0ec8a05e3f1a312dc2d8cd843fcc9/testsuite/model/src/test/java/org/keycloak/testsuite/model/exportimport/ImportModelTest.java#L101

Thank you for the advice. I am performing the import during startup using the --import-realm flag, so all Keycloak nodes were stopped prior to running the command.

**Comment by shawkins** [comment] 2024-10-21 12:09
This should be addressed by #33690 - we need all import related system properties to be set prior to checking if the master realm is part of the import set.

cc @vmuzikar

**Comment by jonkoops** [comment] 2024-10-21 13:44
Shall we close this as a duplicate of #33596 then @shawkins?

**Comment by shawkins** [comment] 2024-10-21 14:40
@jonkoops, sure - I'll update the other issue to reference what is happening here.

**Comment by vmuzikar** [comment] 2024-10-21 16:31
@jonkoops I'd keep this open and link it to the fixing PR for a better visibility.

**Comment by vmuzikar** [comment] 2024-10-22 14:00
Based on the discussion in https://github.com/keycloak/keycloak/pull/33690#issuecomment-2429351052, it looks like it may not be a regression in the end, or at least not in the latest release.

@shawkins Do we know what release introduced this?

**Comment by vmuzikar** [comment] 2024-10-22 14:01
I'm lowering the priority for now.

**Comment by shawkins** [comment] 2024-10-22 14:44
> @shawkins Do we know what release introduced this?

Yes, it was 26.

**Closed** 2024-10-23 11:11 UTC
Labels: kind/bug, priority/blocker, area/import-export, team/cloud-native, kind/regression, backport/26.0
