### ISSUE TITLE
Identity provider Attribute Importer – Cannot import claim "sub"

### ISSUE THREAD

**Issue by korridor** [keycloak/keycloak#22751] opened 2023-08-28 11:00 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

I want to integrate an identity provider in one of my realms. I need to import the ID of the user in the external identity provider in a user attribute called `externalId`. The ID is in the field `sub` in the Bearer token.

I'm using a mapper with the type “Attribute Importer” for that, and that works for other fields like `address`, but not for the `sub` field.

### Version

22.0.1

### Expected behavior

After the "Login in with some other identity provider" the user has a user attribute `externalId` with the ID of the federated user.

### Actual behavior

Import just does not happen. The attribute "externalId" does not exist on users that are federated.

### How to Reproduce?

1. Add any identity provider
2. Create a mapper with type "Attribute importer"
3. Set the "Claim" to `sub` and "User Attribute Name" to `externalId`
4. Try to log in with the newly created identity provider

**Comment by pedroigor** [comment] 2023-08-28 14:33
@korridor I'm failing to reproduce the issue. It is possible to map the `sub` claim as a user attribute. Is there anything missing in the steps to reproduce the issue?

**Comment by pedroigor** [comment] 2024-01-04 12:55
Closing because I can't reproduce.

**Closed by pedroigor** 2024-01-04 12:55 UTC
Labels: kind/bug, status/triage, team/core, area/identity-brokering
