### ISSUE TITLE
Pagination not working on filtered roles in assign role popup

### ISSUE THREAD

**Issue by pschyma** [keycloak/keycloak#17176] opened 2023-02-17 18:42 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Using a filter in the assign role to user (or group) popup disables the pagination in that popup.

### Version

20.0.3

### Expected behavior

The pagination works like in the assign group popup.

### Actual behavior

The view only shows the first page of the filtered results.

### How to Reproduce?

1. Open the assign role popup
2. Apply a filter
3. Try to use the navigation buttons

**Comment by ssilvert** [comment] 2023-02-20 19:28
@pschyma I think this is a duplicate of https://github.com/keycloak/keycloak-ui/issues/4341

Can you try the nightly build and see if it is fixed on your end?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment] 2023-03-13 13:25
I'm going to go ahead and close this.  If it turns out that this is not fixed in the latest nightly then we can reopen.

**Closed by ssilvert** 2023-03-13 13:25 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
