### ISSUE TITLE
Service Account Impersonation fails and results in weird browser state

### ISSUE THREAD

**Issue by sirkrypt0** [keycloak/keycloak#21106] opened 2023-06-20 12:54 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I'd like to impersonate service account users.

Currently, while I can click on `impersonate` in the admin console e.g. the account console doesn't seem to like that and doesn't log me in.
Additionally, this somehow breaks some cookie state, as when I try to log in as another user, it says I'm already logged in to the service account.

### Version

21.1.1

### Expected behavior

Service Account impersonation works (might be a feature request) or the impersonation of service account users is disabled in the frontend so that I don't even try to do it and get confused why it doesn't work.

### Actual behavior

I can impersonate service account users but it doesn't work with the account console. Moreover, my browser is in a weird state where I can't log in normally anymore (without clearing cookies).

### How to Reproduce?

1. Create a new client
    - Enable `Client Authentication`
    - Enable `Service Account roles`
2. Go to the `Service account roles` tab
3. Click on the username in the info box which says _"To manage detail and group mappings, click on the username ..."_
4. On the user info page click on the `Action` dropdown in the top right and hit `Impersonate`
5. Observe that the account console loads, but no user is logged in.
6. Hit the `Login` button to try to login as another user.
7. Enter the login details and login.
8. Observe the _"You are already logged into this session with another user '...'."_ error message.
9. Trying to go back to the application and logging in again yields the same error.

The browser state can of course be cleared by removing all cookies, or impersonating some real user and signing out there.

### Anything else?

The account API explicitly disables access to service account users:

https://github.com/keycloak/keycloak/blob/7d3423ca5fe0cff17d9105ebf3b17f1ad4f1074f/services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java#L135-L137

**Comment by ssilvert** [comment] 2023-06-21 00:24
I was not able to reproduce the same state you got.  I never saw the _"You are already logged into this session.."_ message.  It just lets me log in to account console using whatever credentials I provide.  Of course, this still doesn't make sense with impersonation.

I'm tempted to just say we should hide the `Impersonate` option from the Action dropdown.  Do you have a use case where `Impersonate` should be available for the service account user?

**Comment by sirkrypt0** [comment] 2023-06-21 09:45
Thanks for your quick response!

> I never saw the "You are already logged into this session.." message.

Interesting, I consistently get this error. Even created a fresh instance, new realm etc.

![image](https://github.com/keycloak/keycloak/assets/22522058/f0ecdf0f-697e-4346-a13e-f2f2b1e9577d)

> I'm tempted to just say we should hide the Impersonate option from the Action dropdown. Do you have a use case where Impersonate should be available for the service account user?

We have an application which requires to periodically synchronize its user database with Keycloak. To do so, we use a client with service account which requests the Keycloak admin API.
This application also requires an overall admin user.
Since we don't want that this is any of our "normal" users, we currently have a separate user account without password etc. which we can impersonate when necessary.
Since this account is really tied to that specific client, we thought it'd make sense to use the service account of the client for that.

**Comment by ssilvert** [comment] 2023-06-21 13:00
I'm running a recent nightly build.  I tried this with Keycloak 21 and got the same message as you.

I'm going to assign this to the core team and see if they think it makes sense to support your use case.  

@mposolda, you can assign back to me if you think we should just hide the option to impersonate the service account user.

**Comment by rmartinc** [comment] 2023-06-26 08:56
The service accounts are not allowed to perform a common OIDC authentication flow. The processor does not allow to login a service account [here](https://github.com/keycloak/keycloak/blob/21.1.1/services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java#L1115). I think that impersonating a service account makes no sense and should be avoided. I have not investigated more, but later something is failing as setting a KEYCLOAK_IDENTITY cookie for a service account is something not expected.

Probably we should avoid it at both levels, in the console (hiding the option) and returning an error in the impersonation endpoint. I would do the same for disabled users in both cases too. A disabled user is more or less the same, it makes no sense to impersonate a disabled user.

@mposolda @pedroigor WDYT?

**Comment by pedroigor** [comment] 2023-06-26 11:32
+1

Ideally, we should not only hide the option to impersonate but review how we manage service accounts. Although users and SAs share the same model, they are completely different things. 

Does it really make sense all those fields and tabs from User UI when managing SAs?

**Comment by mposolda** [comment] 2023-06-26 11:52
+1 that lots of the fields in User UI does not makes sense for service accounts. Although I think that some makes sense like for instance:
- Attributes
- Roles (however there is also separate tab `Service Account Roles` available on the client for the same thing)
- Groups?
- Maybe more (but not 100% sure from the top of my head...)

I am not sure if we fix just the particular (this one reported) bug for impersonation or whether we do some deeper review of the UI in general.

**Comment by pedroigor** [comment] 2023-06-26 12:44
Follow-up https://github.com/keycloak/keycloak/issues/21210.

**Comment by rmartinc** [comment] 2023-06-26 13:24
@ssilvert Then it seems that we are maintaining this issue to protect the `impersonation` endpoint in the core services classes (it will return an error when the impersonation is done for a disabled user or a SA). @pedroigor has filed a follow-up for better managing SAs in the admin console which has a broader scope. This one will probably result in a small PR. I'm taking this and assigning to backlog, but I'll try to submit a PR soon.

**Comment by pedroigor** [comment] 2023-06-26 13:28
I don't see it as a problem impersonating disabled users through the Admin API. As an administrator, you might want to impersonate a user without temporarily enabling the account for security reasons.

Better check with @mposolda if there are use cases for it before disabling it.

**Comment by pedroigor** [comment] 2023-06-26 13:46
Ok, I thought you were able to do something with it.

**Comment by sirkrypt0** [comment] 2023-06-27 20:23
Thanks for processing this so fast!

To bring our use case back into the discussion: What would be your suggested way of handling the account for a client which wants to login to the service but also should be able to be logged in by administrators (via impersonation)?
If service accounts exist already, why shouldn't those be used for that, especially as they are intended to be used for services using other services (as far as we understand it)?
Would you suggest a separate user, as we currently do it, give that user a password and let the service perform a direct grant to obtain a token for the user? This would also imply that the client is allowed to perform direct grant for all users, which is not be desirable in our opinion.

Another point: If service accounts can be used to perform certain actions in an application using its token, we would argue that impersonation might be useful for debugging: Consider something like a Nextcloud which allows WebDAV via OIDC Bearer tokens. If something fails, it would be nice to login as the service account and check what's going on.

What's your take on that?

**Comment by rmartinc** [comment] 2023-06-28 07:45
@sirkrypt0 An SA is something that just makes sense in the oauth world while impersonation is a more general thing that should work, for example, for SAML clients. The impersonation in keycloak is done based on the browser, while the SA is only used for the client_credentials grant type, so not related with the browser (just direct connection to the token endpoint to get the tokens for its own resources). That's why the SAs are not valid for common authentication process, they are not users, they are SAs and they are used only for client_credentials. If you need impersonation, in keycloak you need a real user and the impersonation will just work in the browser (you cannot impersonate a direct client_credentials or password call to the token endpoint). But you can always use the service account to test whatever you want, the password of the service account is the client secret, so you can request tokens using client_credentials and use the tokens to test whatever you want. But that's not an impersonation, you are just using the SA.

**Closed** 2023-06-28 08:18 UTC
Labels: kind/bug, area/core, team/core
