### ISSUE TITLE
KC_HTTPS_PROTOCOLS not respected

### ISSUE THREAD

**Issue by johnbrown-yoti** [keycloak/keycloak#22978] opened 2023-09-05 10:13 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [x] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I am trying to set keycloak to only use TLSv1.3, however, it is not respecting the environment variable `KC_HTTPS_PROTOCOLS=TLSv1.3` and is still offering TLSv1.2 (see cipher list below).

The full environment file is listed below...
```
KEYCLOAK_ADMIN=REDACTED
KEYCLOAK_ADMIN_PASSWORD=REDACTED
KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/cert.pem
KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/cert.key
KC_HTTPS_PROTOCOLS=TLSv1.3
KC_SPI_TRUSTSTORE_FILE_FILE=/opt/keycloak/keycloak.jks
KC_SPI_TRUSTSTORE_FILE_PASSWORD=REDACTED
KC_SPI_TRUSTSTORE_FILE_VERIFICATION_POLICY=ANY
KC_METRICS_ENABLED=true
KC_HEALTH_ENABLED=true
KC_LOG_CONSOLE_OUTPUT=json
KC_DB=REDACTED
KC_DB_USERNAME=REDACTED
KC_DB_PASSWORD=u9J3paC8okdVeJkENhqBn44V
KC_DB_URL=jdbc:postgresql://x.x.x.x/REDACTED
KC_HOSTNAME=REDACTED
KC_HTTPS_PORT=8443
KC_HTTP_PORT=8080
KC_HTTP_ENABLED=true
KC_PROXY=passthrough
KC_CACHE=ispn
JAVA_OPTS_APPEND='-Djgroups.bind.address=x.x.x.x'
```

```
Starting Nmap 7.94 ( https://nmap.org ) at 2023-09-05 11:04 BST
Nmap scan report for REDACTED
Host is up (0.027s latency).

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A
|       TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 3072) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 3072) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 3072) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 3072) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 3072) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 3072) - A
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       Key exchange (dh 2048) of lower strength than certificate key
|   TLSv1.3:
|     ciphers:
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 3.99 seconds
```

### Version

22.0.0

### Expected behavior

Only TLSv1.3 ciphers are offered.

### Actual behavior

TLSv1.3 AND TLSv1.2 ciphers are offered.

### How to Reproduce?

1. set environment variable `KC_HTTPS_PROTOCOLS=TLSv1.3`
2. start keycloak server
3. check offered ciphers with `nmap --script ssl-enum-ciphers -p PORT IPADDRESS`

**Comment by johnbrown-yoti** [comment] 2023-09-05 10:18
This appears to be fixed in the `nightly` build. My apologies, I thought I'd tested tested but hadn't!

```
$ nmap --script ssl-enum-ciphers -p 443 REDACTED
Starting Nmap 7.94 ( https://nmap.org ) at 2023-09-05 11:16 BST
Nmap scan report for 172.22.53.37
Host is up (0.027s latency).

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.3:
|     ciphers:
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 0.65 seconds
```

**Comment by johnbrown-yoti** [comment] 2023-09-05 10:26
`22.0.1` & `latest` is still presenting the cipher bug.


```
$ nmap --script ssl-enum-ciphers -p 443 REDACTED
Starting Nmap 7.94 ( https://nmap.org ) at 2023-09-05 11:24 BST
Nmap scan report for REDACTED
Host is up (0.027s latency).

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A
|       TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 3072) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 3072) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 3072) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 3072) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 3072) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 3072) - A
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       Key exchange (dh 2048) of lower strength than certificate key
|   TLSv1.3:
|     ciphers:
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 3.74 seconds
```

**Comment by juv** [comment] 2023-09-05 13:08
I think I have the same issue; it looks like neither `KC_HTTPS_PROTOCOLS` nor `KC_HTTPS_CIPHER_SUITES` has an effect starting from Keycloak 22.0.0. It works for us in the Keycloak 21.x.x versions.

**Comment by rmartinc** [comment] 2023-09-07 10:53
I think this is a duplicate of https://github.com/keycloak/keycloak/issues/21569. It's a bug in quarkus that we suffered when upgrading to 3.2.0 in version 22. It will be fixed in 22.0.2 when quarkus is upgraded. I have tested in current main branch and it works, you can also test with the nightly build.

Closing as duplicate.

**Closed by rmartinc** 2023-09-07 10:53 UTC
Labels: kind/bug, area/core, status/triage, team/core

**Comment by christian-2** [comment] 2024-04-08 15:23
Could it be that this problem is manifesting again? I am starting Keycloak 24.0.2 as follows:

```
# use most of Keycloak's default ciphers plus one that befits vSphere 8.0.2
kc.sh start --https-protocols=TLSv1.3,TLSv1.2 --https-cipher-suites=\
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,\
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,\
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,\
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,\
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,\
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,\
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,\
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

Yet a `nmap --script ssl-enum-ciphers -p 8444 $(hostname -f)` lists only these (TLSv1.2) ciphers:

```
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
```

What could be the reason that `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` is not listed? Could it be that `KC_HTTPS_CIPHER_SUITES` is (also) not respected or am I making a mistake?

**Comment by shawkins** [comment] 2024-04-09 18:50
@christian-2 it would be best to open that as a new issue / discussion if you suspect there is something wrong. Based upon what you have above it would be different - what is shown as enabled is a subset of what you are allowing via the keycloak options. The original issue was that selecting only TLSv1.3 still allowed the use of TLSv1.2.
