### ISSUE TITLE
Master realm Events page issue

### ISSUE THREAD

**Issue by gray380** [keycloak/keycloak#30384] opened 2024-06-12 15:02 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After updating keycloak version from 22 to 25 the 'Events' page for the master (keycloak) realm shows:
under Firefox: (destructured parameter) is undefined
under Safari: Right side of assignment cannot be destructured

If push `clear user events` and `clear admin events` at the 'Realm settings - Events' tab then this issue goes away and the empty 'Events' page has appeared but till the next login in to the admin web console.

In the other realms page 'Events' shows events as expected.

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

Show events at 'Events' page for the master realm.

### Actual behavior

the following error has appeared:
(destructured parameter) is undefined
Right side of assignment cannot be destructured

### How to Reproduce?

Click on the 'Events' button in the keycloak(master) realm.

**Comment by Dennis1993** [comment] 2024-06-12 16:45
Same problem here after the upgrade to v25

![image](https://github.com/keycloak/keycloak/assets/1473674/bc16d9c9-fffc-4367-af68-4b3b0d080fe8)

**Comment by Romain7495** [comment] 2024-06-13 11:46
related to https://github.com/keycloak/keycloak/issues/30306

**Comment by ssilvert** [comment] 2024-06-13 16:34
Closing this as a duplicate of #30306

**Closed by ssilvert** 2024-06-13 16:34 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
