### ISSUE TITLE
After Changing Realm ID: Page shows Netwerk Response was not OK.

### ISSUE THREAD

**Issue by Zozala** [keycloak/keycloak#31923] opened 2024-08-06 07:44 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

After I changed a Realm ID from for example Test to test (so I only changed the first letter from a capital to a non capital letter).
When you now open the realm page it shows the error: Network Response was not OK.
When I look into the logs I see the following exception:

2024-08-06 09:29:49,970 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-395) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getMasterAdminClient()" because "realm" is null
	at org.keycloak.services.resources.admin.AdminConsole.addMasterRealmAccess(AdminConsole.java:283)
	at org.keycloak.services.resources.admin.AdminConsole.whoAmI(AdminConsole.java:255)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Expected behavior should be that the ID of the realm is changed and the error is not shown.

### Actual behavior

Nullreference exception that the realm is not found.

### How to Reproduce?

Change Realm ID.

**Comment by ssilvert** [comment] 2024-08-07 18:45
I do see a problem.  It seems that this only happens if you try to rename a realm where the only change is case.

For instance:

My realm --> My Realm

We need a server-side check for this so you aren't allowed to make a case-sensitive change to a realm name.  Moving to core-iam team.

**Comment by kaustubh-rh** [comment] 2024-08-08 08:05
I will raise a PR for the same.

**Comment by vramik** [comment] 2024-08-08 08:11
@kaustubh-rh thank you, PR would be appreciated.

**Comment by sguilhen** [comment] 2024-08-08 13:15
I've tried this with a SNAPSHOT (nightly) version and it seems to be working

**Comment by kaustubh-rh** [comment] 2024-08-09 08:09
Hi @Zozala @ssilvert , can you share the exact steps to reproduce the issue ?
I have also tried with the latest build, but I am unable to reproduce it.

**Comment by ssilvert** [comment] 2024-08-09 13:46
I'm not able to reproduce on the latest build either.

I wonder if @Zozala is changing the login URL to account for the change in the realm name?  My mistake was that I didn't change the URL in both places.  

`http://localhost:8180/admin/test/console/#/realms/test`  must be changed to `http://localhost:8180/admin/Test/console/#/realms/Test`

I'm going to close this now.  We can reopen if we get a good way to reproduce.

**Closed by ssilvert** 2024-08-09 13:46 UTC
Labels: kind/bug, area/admin/api, help wanted, team/core-iam, priority/normal
