### ISSUE TITLE
Allow using the OpenShift Service CA

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#12597] opened 2022-06-20 12:31 UTC
### Description

The new operator makes it pretty hard to work with the OpenShift Service CA. It does require a `tlsSecret`, with a key/cert combination.

This can be created using the service CA, however that requires an annotation on the service resource, which triggers the creation of a secret, which is tied to the hostname of the service.

Right now the only reasonable way seems to be to manually create the ingress and service.

I think there should be some flag (like the `INSECURE` value on the `tlsSecret`, which triggers:
* adding the service CA annotation to the keycloak service
* automatically uses the generated service as `tlsSecret`
* Set the `reencrypt` annotation on the automatically generated ingress resource

### Motivation

Because you have to deal much less with TLS, certs, keys, and still have a secure deployment.

**Comment by fhochleitner** [comment] 2023-08-30 11:34
additionally it makes working with cert-manager a pain. ingress will only get created with tls block if the tlsSecret is specified but cert-manager only picks up annotations on the ingress when this block is specified.

**Comment by vmuzikar** [comment] 2023-08-31 10:08
This is possibly a duplicate of. @ctron @fhochleitner Let me know if you think otherwise.

**Comment by vmuzikar** [comment] 2023-08-31 10:08
Duplicate of https://github.com/keycloak/keycloak/issues/9781

**Closed by vmuzikar** 2023-08-31 10:08 UTC
Labels: kind/enhancement, team/cloud-native, status/triage, area/operator

**Comment by fhochleitner** [comment] 2023-08-31 11:07
yeah, I'd also say this can be considered to be a duplicate. the openshift-service CA is not exactly a feature of cert-manager. but if cert-manager is supported via the use of annotations to generate the tls secret it should in my opinion also cover @ctron 's usecase.
