### ISSUE TITLE
Bitwarden for storing Keycloak OTP

### ISSUE THREAD

**Issue by ccpsupport** [keycloak/keycloak#12443] opened 2022-06-09 14:04 UTC
### Describe the bug

One of our customers that is using bitwarden for storing the 2FA code complains that the 2FA can be used for 24h then the 2FA gets broken. The setup has been used for half an year and suddenly this effect is visible.
We know that Bitwarden is not on the list of supported apps(Two-factor Authentication - Support for TOTP/HOTP via Google Authenticator or FreeOTP.) but we need to know if you are aware about this bug and if it can be fixed somehow, as well if its predicted to provide support for Bitwarden application in the future.

### Version

15.0.2

### Expected behavior

2FA should be stored on Bitwarden without any crash.

### Actual behavior

After 24h the 2FA cannot be used any longer.

**Comment by darius-m** [comment] 2022-06-09 22:40
This seems to be an issue with Bitwarden itself. As far as I know, TOTP should basically be a value derived from `hash(secret + str(int(currenttime / validinterval)))`. It is an extension of HOTP, which uses a counter instead of `str(int(currenttime / validinterval))`. As long as the secret is properly stored, there is no time skew on the system that generates the code, and the derivation function is not broken, there is nothing dynamic about the algorithm otherwise.

Usually, issues with TOTP are caused by bad time synchronization, so you could recommend them checking their system time. Since by default the valid interval is 30s, the skew cannot be larger than that value (unless you have set a look-around interval to accepts codes for intervals that are in the past or in the future).

**Comment by mposolda** [comment] 2022-11-24 11:21
@darius-m Thanks for your comment. There is no further response from the reporter, so I am closing this.

Feel free to re-open if you still see this as valid issue, but then please add more details and answer to the @darius-m concern.

**Closed by mposolda** 2022-11-24 11:21 UTC
Labels: area/authentication, kind/bug, status/triage
