### ISSUE TITLE
Using Admin2,  Identity Provider Mapper do not take the "Mapper Type" into account

### ISSUE THREAD

**Issue by looorent** [keycloak/keycloak#13374] opened 2022-07-27 15:25 UTC
### Describe the bug

After upgrading to the Admin2 feature, creating an Attribute mapper ignores the Mapper type (e.g. "hardcoded value"). 
Using a mapper type different than a JSON type (such as "Advanced Attribute to Role") still tries to create a JSON value.

### Version

19.0.0

### Expected behavior

Creating an Identity Provider Mapper should store the appropriate fields, according to the selected Mapper Type.

### Actual behavior

The form does not take the Mapper Type into account when saving the attribute mapper.
For example, with an Hardcoded value:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/8242900/181283260-04b5ae35-942e-40ff-b0dd-27f34e3a92a7.png">

The request sent to Keycloak's backend has this payload:
```
{
  "config": {
    "attributes": "[{\"key\":\"\",\"value\":\"\"}]",
    "syncMode": "INHERIT",
    "are.attribute.values.regex": false,
    "role": "",
    "attribute.value": "any-value",
    "claims": "[]"
  },
  "identityProviderMapper": "hardcoded-attribute-idp-mapper",
  "name": "report-issue",
  "identityProviderAlias": "saml"
}
```

The database does not contain any hardcoded value:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/8242900/181283913-217903fd-bf54-4f2a-b389-e176614970f2.png">
_(result of the SQL query: `select * from idp_mapper_config where idp_mapper_id='3cad7da9-89f2-4eff-a9ee-652cca84801c';` after saving the mapper)_

Here is the Admin2 interface showing the mapper that has been created:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/8242900/181284103-b6e93ec0-e930-4b4b-8035-84e4806e79c1.png">

Using another mapper type (such as "Attribute Importer") produces the same result.

### How to Reproduce?

Create a new SAML2 Identity Provider and add a new Identity Provider Mapper using a different Mapper Type.

### Anything else?

Another problem is probably associated to this issue.
The existing mappers cannot be displayed in the Admin2 interface.
For example, here is an existing attribute mapper (extracted from the `identity-provider/instances/:id/mappers` endpoint loaded when displaying an IDP):
```
{
	"8": {
		"id": "c9b4d65f-8604-442d-a333-d45b37282d0f",
		"name": "Display Name",
		"identityProviderAlias": "our-alias",
		"identityProviderMapper": "saml-user-attribute-idp-mapper",
		"config": {
			"syncMode": "INHERIT",
			"user.attribute": "keycloak.displayName",
			"attribute.name": "http://schemas.microsoft.com/identity/claims/displayname"
		}
	}
}
```

The Admin2 interface, when opening the Mapper details fails:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/8242900/181285355-5b9043dc-be3d-4f2a-8fbe-6d613c0e87b7.png">

Using the old Admin interface (with `start-dev`) does not produce this error.

**Comment by looorent** [comment] 2022-07-29 11:48
It also affects `quay.io/keycloak/keycloak:19.0.1`.

**Comment by lexcao** [comment] 2022-07-29 18:49
Hi, @looorent 
Thanks for your feedback.
I have reproduced from my local.
There should be an issue with Keycloak Admin UI.
And I cloned this ticket (with some details) to that repo.
https://github.com/keycloak/keycloak-admin-ui/issues/3022

**Comment by ssilvert** [comment] 2022-08-01 14:43
Closing here because it was cloned in the keycloak-admin-ui repo.

**Closed by ssilvert** 2022-08-01 14:43 UTC
Labels: kind/bug, status/triage
