### ISSUE TITLE
Properly handle IPv6 loopback addresses when checking if the host of the client and the request maps to a local address

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#35734] opened 2024-12-09 11:31 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

"Local access required" page is shown even when accessed through "http://localhost:8080"
It works with "http://127.0.0.1:8080"

`SecureContextResolver#isLocalAddress` method determines whether the address is local, but in my environment, the `address` variable contained an `0:0:0:0:0:0:0:1` and was not judged as local. 
https://github.com/keycloak/keycloak/blob/6a10c0e345299027a96b543875351a7a88459f88/services/src/main/java/org/keycloak/utils/SecureContextResolver.java#L81

The check should be properly implemented instead of simply comparing strings.

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

IPv6 address such as `0:0:0:0:0:0:0:1` or any other format that maps to a local/loopback address should be treated as local.

### Actual behavior

Only local/loopback addresses `[::1]` and `[0000:0000:0000:0000:0000:0000:0000:0001]` are treated as local.

### How to Reproduce?

* Provision a new server using a fresh database
* Make sure `localhost` host points to an IPv6 address such as `0:0:0:0:0:0:0:1`
* Try accessing `http://localhost:8080` to access the page to create the temporary administrative user

**Comment by vmuzikar** [comment] 2024-12-09 13:46
Duplicate of #35675

**Closed by vmuzikar** 2024-12-09 13:46 UTC
Labels: kind/bug, priority/important, team/rh-iam, team/cloud-native, status/triage
