### ISSUE TITLE
Error When Unlocking Temporarily Locked User via Toggle Button

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#32611] opened 2024-09-03 08:57 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When attempting to unlock a temporarily locked user using the "Temporary locked" toggle button on the user details screen, validation errors are displayed for user fields upon pressing the "Save" button.
![Unlock temporary locked user](https://github.com/user-attachments/assets/4147e239-db7b-4b99-9926-ad4bdc6e38dd)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The user is successfully unlocked, and the changes are saved without any validation errors.

### Actual behavior

Validation errors are displayed for several user fields, preventing the user from being unlocked.

### How to Reproduce?

1. Navigate to the User Details screen for a temporarily locked user.
2. Toggle the Temporary locked switch to unlock the user.
3. Press the Save button.

**Comment by ssilvert** [comment] 2024-09-05 19:18
We have had some fixes in this area.

**Comment by edewit** [comment] 2024-09-10 10:11
can't reproduce

**Comment by enastevska** [comment] 2024-09-10 10:48
Will try with the latest version, thanks

**Comment by ssilvert** [comment] 2024-09-17 18:01
@enastevska I am going to close this now.  We can reopen if you find the issue still exists in the latest version.

**Closed by ssilvert** 2024-09-17 18:01 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
