### ISSUE TITLE
Unknown database: H2 in Docker

### ISSUE THREAD

**Issue by MrTwIXx** [keycloak/keycloak#14353] opened 2022-09-12 13:40 UTC
### Describe the bug

I set up Keycloak first directly in Ubuntu without Docker.
There I added the quarkus.properties file with the DB data for my Custom Provider.
I started Keycloak with start-dev and Keycloak used the H2 DB for Keycloak itself and my Custom Provider used the specified DB.

Now I wanted to move everything to Docker.
I added to the docker the same quarkus.properties to the conf folder.

> quarkus.datasource.test.db-kind=oracle
> quarkus.datasource.test.jdbc.url=${DB_URL}
> quarkus.datasource.test.username=${DB_USER}
> quarkus.datasource.test.password=${DB_PW}

When I now start the Container with start-dev I get the following error:

### Version

19.0.1

### Expected behavior

The Docker Container starts without any problems

### Actual behavior

Updating the configuration and installing your custom providers, if any. Please wait.
2022-09-12 13:36:52,105 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 8294ms
2022-09-12 13:36:53,531 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-09-12 13:36:54,686 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-09-12 13:36:56,447 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-09-12 13:36:56,459 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-09-12 13:36:56,485 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-09-12 13:36:56,853 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-09-12 13:36:56,936 WARN  [liquibase.database.DatabaseFactory] (main) Unknown database: H2
2022-09-12 13:36:58,232 WARN  [liquibase.database.DatabaseFactory] (main) Unknown database: H2
2022-09-12 13:36:58,289 WARN  [org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockDatabaseChangeLogGenerator] (main) No direct support for database liquibase.database.core.UnsupportedDatabase . Database lock may not work correctly
2022-09-12 13:36:58,291 WARN  [liquibase.database.DatabaseFactory] (main) Unknown database: H2
2022-09-12 13:36:58,338 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2022-09-12 13:36:59,872 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2022-09-12 13:36:59,872 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2022-09-12 13:36:59,872 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com:
     Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "RENAME[*] REALM_APPLICATION TO REALM_CLIENT"; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, REPLACE, {"; SQL statement:
RENAME REALM_APPLICATION TO REALM_CLIENT [42001-197] [Failed SQL: (42001) RENAME REALM_APPLICATION TO REALM_CLIENT]
2022-09-12 13:36:59,872 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for change set META-INF/jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com:
     Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "RENAME[*] REALM_APPLICATION TO REALM_CLIENT"; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, REPLACE, {"; SQL statement:
RENAME REALM_APPLICATION TO REALM_CLIENT [42001-197] [Failed SQL: (42001) RENAME REALM_APPLICATION TO REALM_CLIENT]
2022-09-12 13:36:59,873 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Syntax error in SQL statement "RENAME[*] REALM_APPLICATION TO REALM_CLIENT"; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, REPLACE, {"; SQL statement:
RENAME REALM_APPLICATION TO REALM_CLIENT [42001-197] [Failed SQL: (42001) RENAME REALM_APPLICATION TO REALM_CLIENT]
2022-09-12 13:36:59,873 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Syntax error in SQL statement "RENAME[*] REALM_APPLICATION TO REALM_CLIENT"; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, REPLACE, {"; SQL statement:
RENAME REALM_APPLICATION TO REALM_CLIENT [42001-197]
2022-09-12 13:36:59,873 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

### How to Reproduce?

Add to the official Docker Image a quarkus.properties file.

**Comment by Pepo48** [comment] 2022-11-01 09:37
Hi @MrTwIXx, thanks for reporting the issue. 

I haven't reproduced the exact same error so far. One thing I noticed though is:
```
Syntax error in SQL statement "RENAME[] REALM_APPLICATION TO REALM_CLIENT"; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, REPLACE,
```
in your error log. Could this be related somehow to your specific custom storage provider configuration?

It would be great if you could provide more details in order to reproduce it exactly the same way.

Thank you very much!

**Comment by mruzicka** [comment] 2022-11-21 23:39
Hi @MrTwIXx, you might be able to work around the problem by renaming your datasource to `atest` for example - in general to anything which comes before '<default>' as determined by the java's `HashMap` (or `HashSet`) iteration order, please see issue #15608 for more details.

**Comment by Pepo48** [comment] 2023-03-29 18:46
Duplicate of #15608

**Closed by Pepo48** 2023-03-29 18:46 UTC
Labels: kind/bug, area/dist/quarkus, status/triage
