### ISSUE TITLE
Access to admin console via access reverse proxy in http fails in proxy with  CONNECT call

### ISSUE THREAD

**Issue by ChrHilgers** [keycloak/keycloak#22088] opened 2023-07-28 18:11 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Our setup follows the idea of an edge Loadbalancer in HW doing the SSL offloading listening on login.example.com.

The keycloak instances are named idm-01 till idm-04 and running as podman instances on Port 8080 on different hosts.

These are the ENV setting from podman systemd unit file:

```
        --env KC_HOSTNAME=login.example.com \
        --env KC_HOSTNAME_ADMIN=idm-prod.int.example.com \
        --env KC_HTTP_RELATIVE_PATH=/auth \
        --env KC_PROXY=edge \
        --env KC_HEALTH_ENABLED=True \
        --env KC_METRICS_ENABLED=True \
        --env KC_CACHE_CONFIG_FILE=cache-ispn-jdbc-ping.xml \
        --env KC_LOG=console \
        --env KC_FEATURES=admin-fine-grained-authz,token-exchange \
        --systemd=true \
```

![grafik](https://github.com/keycloak/keycloak/assets/96293390/f5616d92-46b0-4d3c-abeb-1d3cd580b38e)

HW loadbalancer should block access to admin console via URL blocking, currently disabled due to this issue.

Access to adminconsole should only be possible via an internal reverse proxy. This worked very well until 15.1.1 After an upgrade to 19.0.3 it stopped working. We started on pre-prod with upgrade to 22.0.1 as lots of bug reports indicated many  changes and improvements around KC_HOSTNAME_ADMIN.

With 22.0.1 a new proxy was added to access the external hosted Cluster admin console securely.

I tried Apache httpd and NGINX and both show the same behavior. After several redirects it get stuck as in
#16069   "Loading the admin console"
At that point the proxy logs show:
```
192.168.12.10 - - [26/Jul/2023:14:57:43 +0200] "CONNECT login.example.com:443 HTTP/1.1" 400 157 "-" "-" "-"
```

the CONNECT goes towards `KC_HOSTNAME` instead of a http connect to `KC_HOSTNAME_ADMIN`. 

I tried without visble changes setting/unsetting these parameter
* KC_HTTP_ENABLED
* KC_HOSTNAME_STRICT
* KC_HOSTNAME_STRICT_BACKCHANNEL

I found and read many bug reports like #14666 and hostname-debugs shows the expected names via proxy.

### Version

22.0.1

### Expected behavior

Send all requests for adminconsole to KC_HOSTNAME_ADMIN or KC_HOSTNAME_ADMIN_URL

### Actual behavior

While loading the admin console at least one connect is done as CONNECT towards KC_HOSTNAME

### How to Reproduce?

You need at least 3 nodes to reproduce it.
* 1 external loadbalancer/proxy  listening in https to KC_HOSTNAME
* 1 internal reverse proxy being able to connect to at least  one keycloak container
* 1 keycloak container with KC_PROXY=edge, KC_HOSTNAME and KC_HOSTNAME_ADMIN set

an of course 1 client browser connecting via proxy towards http://KC_HOSTNAME_ADMIN/auth

Then proxy logs should show the CONNECT KC_HOSTNAME when the spinning wheel loading admin console shows up.

I did setup a testenv without connection to internet or connect from access proxy to KC_HOSTNAME.

**Comment by ssilvert** [comment] 2023-07-31 19:42
I've added your issue to the description of #14666.  I'm also going to see if things are moving along toward a resolution.

**Comment by jonkoops** [comment] 2023-08-01 09:21
Duplicate of #14666

**Closed by jonkoops** 2023-08-01 09:21 UTC
Labels: kind/bug, area/admin/ui, team/ui
