### ISSUE TITLE
memberOf in User LDAP filter

### ISSUE THREAD

**Issue by Cistoge** [keycloak/keycloak#26555] opened 2024-01-29 12:16 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Hello,

when  enter this:

ldapsearch -x -D "cn=admin,dc=cs,dc=tu-dortmund,dc=de" -y /usr/local/share/uadmd/conf.d/pwd.conf "(memberOf=cn=group1,ou=groups,dc=cs,dc=tu-dortmund,dc=de)"

in the command line interface of my LDAP server, it returns a list of people who are members of group1, so 
"(memberOf=cn=group1,ou=groups,dc=cs,dc=tu-dortmund,dc=de)" is very probably accepted as a valid search expression by my LDAP server.

But when I enter that expression as User LDAP filter in keycloak, keycloak finds no users. Other search expressions, like (uid=muelle00) work fine.

What is possibly wrong here?

Regards
  Christoph

### Version

23.0.2

### Expected behavior

Keycloak finds users who are member of  group1

### Actual behavior

Keycloak finds no users

### How to Reproduce?

Add dynamic memberOf attribute in LDAP; in OpenLDAP, it works with this ldif file:

dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: dynlist.la

dn: olcOverlay=dynlist,olcDatabase={1}mdb,cn=config
changetype: add
objectClass: olcDynamicList
objectClass: olcOverlayConfig
olcOverlay: dynlist
olcDlAttrSet: groupOfURLs memberURL member+memberOf@groupOfNames

Make users member of groups; in OpemLDAO, it works with this ldif file:

dn: cn=gropu1,ou=groups,dc=cs,dc=tu-dortmund,dc=de
changeType: modify
replace: memberURL
memberURL: ldap:///dc=cs,dc=tu-dortmund,dc=de??sub?(employeeType=Wimi)
memberURL: ldap:///dc=cs,dc=tu-dortmund,dc=de??sub?(employeeType=Prof)
memberURL: ldap:///dc=cs,dc=tu-dortmund,dc=de??sub?(employeeNumber=pipmel.pampel)

**Comment by ahus1** [comment] 2024-01-31 14:47
Possible similar issue: #26317

**Comment by kellenmurphy** [comment] 2024-01-31 16:27
I see this issue as well...

**Comment by sguilhen** [comment] 2024-02-21 21:54
Closing as a duplicate of https://github.com/keycloak/keycloak/issues/26317

**Closed** 2024-02-21 22:08 UTC
Labels: kind/bug, area/ldap, team/core-iam
