### ISSUE TITLE
Enable Keycloak installation to Windows system directories with spaces.

### ISSUE THREAD

**Issue by bharath24122003** [keycloak/keycloak#24538] opened 2023-11-03 17:48 UTC
### Description

**Problem:**
When attempting to install Keycloak on a **Windows** system with a **hostname** containing space characters in the middle (e.g., "**ganesh babu**"), the installation process encounters issues with the path defined in the kc.bat script. This issue results in a failure to install Keycloak in directories with space characters in their names.

**Current Temporary Solution:**
As a temporary workaround, I installed Keycloak in the C:\ directory, which does not contain any spaces in the path. This allowed me to use Keycloak, but it is not an ideal solution.

**Error:**
C:\Users\Ganesh babu\Downloads\keycloak-22.0.5\keycloak-22.0.5>bin\kc.bat
**Error: Could not find or load main class babu\Downloads\keycloak-22.0.5\keycloak-22.0.5\bin\..
Caused by: java.lang.ClassNotFoundException: babu\Downloads\keycloak-22/0/5\keycloak-22/0/5\bin\//**

C:\Users\Ganesh babu\Downloads\keycloak-22.0.5\keycloak-22.0.5>

**Comment by jsorah** [comment] 2023-11-03 18:03
This seems like it may be fixed by https://github.com/keycloak/keycloak/pull/20212 - I don't believe those changes have been backported and expect them to ship with the KC 23 release due out _soon_.

**Comment by vmuzikar** [comment] 2023-11-22 17:37
Duplicate of #20212

**Closed by vmuzikar** 2023-11-22 17:37 UTC
Labels: kind/enhancement, area/dist/quarkus, team/cloud-native, status/triage

**Comment by vmuzikar** [comment] 2023-11-22 17:38
@bharath24122003 Thanks for the report. Feel free to reopen if it's still valid despite #20212 being fixed.
