### ISSUE TITLE
keycloak 23.0.2 shows wrong version string in admin console

### ISSUE THREAD

**Issue by tobias-weiss** [keycloak/keycloak#25609] opened 2023-12-15 11:05 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

admin UI shows after update still version string of previous installed version:

```
for i in 0 1 ; do kubectl exec -it kc-qsciber-$i -c keycloak -- /opt/keycloak/bin/kc.sh -V ; done
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=kc-qsciber-nodes
Keycloak 23.0.2
JVM: 17.0.9 (Debian OpenJDK 64-Bit Server VM 17.0.9+9-Debian-1deb12u1)
OS: Linux 6.1.0-13-amd64 amd64
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=kc-qsciber-nodes
Keycloak 23.0.2
JVM: 17.0.9 (Debian OpenJDK 64-Bit Server VM 17.0.9+9-Debian-1deb12u1)
OS: Linux 6.1.0-13-amd64 amd64
```
Please note, we do not upstream docker image, but a self build one. (basically Java, pull archive, extract it) 

Whereas in UI:

![grafik](https://github.com/keycloak/keycloak/assets/4528801/7d65bc81-5d07-45cc-afa3-ae785167fe56)

### Version

23.0.2

### Expected behavior

show correct version of keycloak

### Actual behavior

show version string of previously installed version (23.0.1)

### How to Reproduce?

tested it on two  of our installations

**Comment by tobias-weiss** [comment] 2023-12-18 10:35
same applies to 23.0.3 , still show 23.0.1 in Admin GUI

**Comment by ssilvert** [comment] 2023-12-19 21:04
I downloaded 23.0.3 from the downloads page and it correctly shows 23.0.3.  But I didn't use docker.

If this is a bug it would be on the server side as the admin console just displays whatever it gets from the call to serverinfo.  Transferring this issue to core team.

**Comment by rmartinc** [comment] 2023-12-22 12:18
The UI calls the `serverinfo` endpoint. The version is obtained from a properties that is filled when the build is generated. It's stored in the keycloak-common jar. The file is named `keycloak-version.properties`. I have checked and it's OK in the zip, in the docker image and maven. So I really don't know what happens in your case.

**Comment by jonkoops** [comment] 2023-12-27 15:13
Looks like this is not reproducible, closing this issue. If you have a reproducible case, feel free to submit an issue again.

**Closed by jonkoops** 2023-12-27 15:13 UTC
Labels: kind/bug, area/core, team/core
