### ISSUE TITLE
Make `MapKeycloakTransaction` check expiration time

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#11974] opened 2022-05-13 08:30 UTC
### Description

Currently, for each entity that can expire we have `if` check in the corresponding provider that checks entity expiration time and if the entity is expired, we remove it from the storage and return `null`.

See for example:
https://github.com/keycloak/keycloak/blob/cdef39f76c50506681227b627e678bdbf15779a4/model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java#L86-L91

This could be done a little bit sooner (for example in `MapKeycloakTransaction` implementation) for all entities that can expire. This way we can be sure that on the logical layer we always have only not-expired entities.

**Comment by hmlnarik** [comment] 2022-08-05 07:02
Duplicate of #11947

**Closed by hmlnarik** 2022-08-05 07:02 UTC
Labels: kind/enhancement, area/storage, team/storage-sig
