### ISSUE TITLE
When importing a realm on start, the ids of authenticationFlows and authenticatorConfig are regenerated

### ISSUE THREAD

**Issue by HerrDerb** [keycloak/keycloak#17528] opened 2023-03-09 10:32 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

Importing and exporting the same realm is not consistent. Some ids are always regenerated.

Out of scope:
When importing and exporting the same realm, it can take up to 4 turnarounds until the export is stable (except this issue)

### Version

21.0.1

### Expected behavior

When importing and exporting  a realm json, all ids should be preserved, as a change of id indicates a change of config.

### Actual behavior

When importing and exporting realm json, the ids for authenticationFlows and authenticatorConfig are not preserved.

### How to Reproduce?

1. Import realm
2. Export realm
3. Compare arrays `authenticationFlows` and  `authenticatorConfig `

**Comment by vramik** [comment] 2023-04-05 20:37
Thank you @HerrDerb for the report! I can confirm the bug!

**Comment by HerrDerb** [comment] 2023-07-17 07:07
@vramik starting from the initial export, after re-import and re-export, the export file containes more information than before, which is somehow unexpected. I noticed this behaviour until the ~4th export

**Comment by vramik** [comment] 2023-08-31 17:08
With current upstream/main I cannot reproduce the issue any more. Closing.

**Closed by vramik** 2023-08-31 17:08 UTC
Labels: kind/bug, area/import-export, team/store
