### ISSUE TITLE
Can't start Keycloak 22.0.3 on Windows

### ISSUE THREAD

**Issue by anar-orujov** [keycloak/keycloak#23563] opened 2023-09-27 13:29 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

I can't start Keycloak 22.0.3 on Windows 10. 
I also checked the latest nightly release, and the same problem happens.

```
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I copied the `kc.bat` file from version 21.0.1, and it works successfully. 
It seems that something changed, and it broke the start process.

### Version

22.0.3

### Expected behavior

Successful start of Keycloak 22.0.3 via `kc.bat`.

### Actual behavior

Error during start of Keycloak 22.0.3 via `kc.bat`.

### How to Reproduce?

`bin\kc.bat start`

### Anything else?

I checked the latest changes to kc.bat. There I found a commit: [ "Removed lots of unnecessary quotes.."](https://github.com/keycloak/keycloak/commit/1c9992fdaeff9566fd8f734ec5fdbf82c7fb5720). Maybe not all of them are unnecessary. Because Windows commands fail when you call directory including spaces. We need quotes for these cases.
I am not sure whether this is the actual reason, but it may be one of the possible causes.

**Comment by anar-orujov** [comment] 2023-09-27 13:36
I also tried to get more details using `--verbose` option, but got the same error message.

**Comment by vmuzikar** [comment] 2023-10-06 15:41
@Pepo48 Can you please look into this when you get a chance?

**Comment by Pepo48** [comment] 2023-10-17 13:10
@anar-orujov thanks for the report. I can't reproduce this behaviour with 22.0.4, nor with the latest nightly release. Would you mind to share more information about your specific environment? Which Java version you use?

Thanks.

**Comment by Pepo48** [comment] 2023-10-20 15:20
Duplicate of #20115

**Closed by Pepo48** 2023-10-20 15:20 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native
