### ISSUE TITLE
Duplicate groups

### ISSUE THREAD

**Issue by jorozcof** [keycloak/keycloak#17630] opened 2023-03-13 17:51 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Groups duplicated. My version before is 20.0.3, but when update 21.0.1, in UI duplicated groups. Same UUID but diferent case, one with lowerCase and the other group upperCase.

I share imagen example.

![image](https://user-images.githubusercontent.com/115189644/224784233-bb05452a-99a0-4610-a651-8ee493ea829c.png)

### Version

21.0.1

### Expected behavior

Groups not duplicated.

### Actual behavior

Groups duplicated.

### How to Reproduce?

Create group and add subgruoup in version 20.0.3. After, get up new server with version 21.0.1. You see group duplicated.

**Comment by ssilvert** [comment] 2023-03-13 19:52
Moving this to the core team as I think it's very unlikely to be a UI bug.

@jorozcof Did you mean that you were seeing this in the admin console?  Not account console, right?

**Comment by jorozcof** [comment] 2023-03-13 20:39
> Moving this to the core team as I think it's very unlikely to be a UI bug.
> 
> @jorozcof Did you mean that you were seeing this in the admin console? Not account console, right?

@ssilvert Sorry, yes. I saw it in the admin console.

**Comment by douglaspalmer** [comment] 2023-03-14 19:28
Can you provide an export of the realm from 20.0.3 please?

**Comment by jorozcof** [comment] 2023-03-15 21:56
> Can you provide an export of the realm from 20.0.3 please?

@douglaspalmer Sorry, is not posibility share the realm. Is confidentials for my company. But, I export realm and after import the realm to the new server I did not get the duplicate groups. In the JSON, groups not are duplicated.

Is duplicated only when migrated BD at the new versión the server.

**Comment by mposolda** [comment] 2023-03-24 09:29
Adding also "store" team as this may be rather DB related issue.

**Comment by jorozcof** [comment] 2023-03-27 16:08
> @jorozcof What is the DB you're using (including DB version and JDBC driver - if you know the version of it?)

I using Sql Server in version 15.0.2000.5 and JDBC Driver version: 11.2

**Comment by jorozcof** [comment] 2023-03-30 14:20
Reciently, I see the groups is duplicated in version 20.0.3. 

Where is duplicated?

In the user module. I want join a Group and I see duplicated grupos.

Steps for you see:

1) Select user in realm
2) Select any user
3) Select Groups
4) Select Join Groups
5) You see duplicated groups.

I share photo of test.

![image](https://user-images.githubusercontent.com/115189644/228865107-49dcd923-0f47-4140-a6d1-2bb67ac65263.png)

**Comment by sguilhen** [comment] 2023-06-07 14:20
@jorozcof I've tried exactly what you described in the How to Reproduce section and I couldn't reproduce the issue. The groups/subgroups were migrated correctly to Keycloak 21 and I see no duplicates in the DB or in the UI when trying to join groups.

Starting with an empty DB, what were the exact steps you followed to get Keycloak to display duplicate groups? Also, in your case are the duplicates visible in the DB?

**Comment by jorozcof** [comment] 2023-06-08 15:04
> @jorozcof I've tried exactly what you described in the How to Reproduce section and I couldn't reproduce the issue. The groups/subgroups were migrated correctly to Keycloak 21 and I see no duplicates in the DB or in the UI when trying to join groups.
> 
> Starting with an empty DB, what were the exact steps you followed to get Keycloak to display duplicate groups? Also, in your case are the duplicates visible in the DB?

Hi @sguilhen I did the tests again and I found out that apparently the error comes from selecting the Page Items. For example if I leave it at 10 per page, everything shows OK. But if I change it to 20, 50 or 100, for example, the groups double.

And answering your questions, in the database I don't have any duplicate groups.. 

![image](https://github.com/keycloak/keycloak/assets/115189644/8f0f01c7-d831-49ed-b1ea-5ed341b3b202)

no duplicates

But if I change items for pages i can see the duplicates.

![image](https://github.com/keycloak/keycloak/assets/115189644/4cae667d-5921-43a7-a238-ff632fff6952)


Maybe, that is.

**Comment by sguilhen** [comment] 2023-06-09 13:37
@jorozcof Thanks for the response. That's interesting, I'll give it another try. So basically just create a bunch of groups and then when selecting the group to join change the number of groups shown. Looks like it has nothing to do with migration after all.

**Comment by sguilhen** [comment] 2023-06-09 14:01
@jorozcof still couldn't reproduce it on Keyclaok 21.1.1 - I've created 15 groups, selected a user, then tried to join a group and all groups were correctly displayed irrespective of the page size selected.

Do you by any chance fetch groups from a federation (e.g. LDAP) along with the ones stored in KC DB?

**Comment by jorozcof** [comment] 2023-06-09 14:45
@sguilhen No, only the ones I have created from the realm. 

Strange that you can't reproduce it. Before, I thought it was due to the migration or even the DB, but it does not show duplicates there, only in the UI when changing the selected page size. I'm using version 20.0.3 by the way. Take the DB and mount it on my local, the problem persists. I don't know what could be happening.

**Comment by sguilhen** [comment] 2023-06-15 11:38
Yeah, it is strange. Would you be able to try with Keycloak 21.1.1?

**Comment by jorozcof** [comment] 2023-06-26 15:58
> Yeah, it is strange. Would you be able to try with Keycloak 21.1.1?

Ok. I will try in this week!

**Comment by jorozcof** [comment] 2023-07-17 14:41
@sguilhen Hello, I tried version 22.0.0 and I had the same problem.

**Comment by jorozcof** [comment] 2023-10-27 18:25
@sguilhen Hello, sorry some news? 
Recently I migrated to 22.0.5 but the mistake still persists.

For example, If I keep the default value, they are not duplicated

![image](https://github.com/keycloak/keycloak/assets/115189644/3c9e45d4-eb23-4197-9e60-81f25fe9cd68)


But If I change 

![image](https://github.com/keycloak/keycloak/assets/115189644/a3e06923-74c7-470d-8e56-e1dbb0bb350c)


In the network I could see that duplicated this group.

![image](https://github.com/keycloak/keycloak/assets/115189644/c4217739-688a-4518-8694-db621711baac)


The only difference is its UUID, one in lowercase and other uppercase.

**Comment by sguilhen** [comment] 2023-11-07 13:17
@jorozcof Hi! Unfortunately I can't reproduce this locally, no matter what I do with my groups. This UUID difference you've showed is really weird - can you confirm you don't have the duplicated groups in the DB? Is this something you only see when checking the network traffic?

**Comment by vramik** [comment] 2023-11-08 11:49
@jorozcof @sguilhen I've also tried a lot of things and I also had no luck with reproducing the issue. I investigated the path from `GroupsResource.getGroups` to GroupEntity and there is no modification of IDs.

@jorozcof would you be able verify that when groups are queried and the duplicates are returned request URL is something like `/admin/realms/master/groups?first=0&max=21&exact=false&global=false`

**Comment by jorozcof** [comment] 2023-11-28 13:50
This is so weird. Answering your question. the request url is the following: `http://localhost:9091/admin/realms/happify/groups?first=0&max=21&search=`
I have two environment, and my concern was that the same thing would happen in the other environment, since the information is a bit similar. So when I migrated my other version dont have the mistake, don thave any duplicated.

I also tried to reproduce this issue on another environment but y dont had luck.

I could say that only I have this problem. I don't see another similar problem on the discussion forum.

**Comment by jorozcof** [comment] 2023-12-04 17:17
@sguilhen Recently I tried with 23.0.1 and I don't have duplicate groups. I think that the improvement that was introduced in groups in version 23.0.0 solved something.

**Comment by sguilhen** [comment] 2023-12-05 12:51
@jorozcof That's good to know. I wonder why you were seeing these duplicates in the first place, but glad it is working for you. Would you mind if I close this issue now?

**Comment by jorozcof** [comment] 2023-12-05 13:43
@sguilhen Yes, for me it is good that close this issue.

**Closed** 2023-12-05 14:10 UTC
Labels: kind/bug, area/storage, status/triage, team/core
