### ISSUE TITLE
Cannot set initial password for new users when using a custom UserFederation

### ISSUE THREAD

**Issue by gvonroten** [keycloak/keycloak#19491] opened 2023-04-03 11:41 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have a custom User Federation in my realm. When I create a user in the admin UI I can not set a password for that user.
I suspect the problem is the new "FederatedCredentials.tsx" used in "UserCredentials.tsx". From what I see it misses the behavior for an empty List of credentials.
This worked fine before updating to 21.0.1

### Version

21.0.1

### Expected behavior

The "Credentials" tab shows the big plus sign and the button to set a password.

### Actual behavior

The "Credentials" tab shows an empty list of credenitals.

### How to Reproduce?

Add a user federation to a realm, create a user and go to the "Credentials" tab of that user.

### Anything else?

It is possible that we are missing something in our User Federation, but it worked fine until I updated.
I suspect this commit: https://github.com/keycloak/keycloak/commit/2ae520fb8a578ac2a44bed55e5c89f147d16a13f#diff-a1e2da5a441004308e9f0a28ff989d02e123ec30a1c9a63e347a11fcac490137

**Comment by gvonroten** [comment] 2023-04-06 08:42
I can't reproduce my problem with that user federation either. I'll try to find the difference and let you know.

**Comment by gvonroten** [comment] 2023-04-06 08:57
From what I can tell that user federation does not allow the creation of new users in it (addUser returns null). So any user created while using that user federation ends up not being a federated user (no federation link can be seen in the user details).

I changed the federation to not implement CredentialInputUpdater and CredentialInputValidator, so that the hardcoded users (Fred Flinstone etc.) don't have passwords and I can reproduce my problem that way.

**Comment by ssilvert** [comment] 2023-04-06 12:57
The UI is behaving correctly.  It will call `configured-user-storage-credential-types`.  If you look at the inspector you will see a GET request like this: http://localhost:8180/admin/realms/master/users/f%3Af1ff1fcb-0e6f-452e-9585-d35d7cc68cc8%3A1/configured-user-storage-credential-types

Without the `CredentialInputUpdater`, that call will return an empty array.  Thus, there are no credential types that can be updated.

The old UI assumed that the password credential would always be valid.  But that is not actually the case.

**Comment by gvonroten** [comment] 2023-04-06 13:05
ok.. so how am I supposed too just implement the user storage and leave the handling of Credentials to Keycloak?

**Comment by ssilvert** [comment] 2023-04-06 13:12
If you implement the interfaces, it should work.  Keycloak will call your provider as needed.

**Comment by gvonroten** [comment] 2023-04-06 13:50
My point is that I don't want to implement those interfaces. Keycloak handled this fine up until now.

**Comment by ssilvert** [comment] 2023-04-06 18:53
For the UI to work, the REST call to `configured-user-storage-credential-types` has to return something.

Are you saying that this REST call works when the user already has a password?  This is starting to sound like a server-side issue.  And I don't know for sure if it's your code or ours.

**Comment by gvonroten** [comment] 2023-04-11 08:51
Yes, when there is a password (or some other credential) it is shown in the credential list, including a "reset password" button. (I have some users from before updating Keycloak)

My problem is that I can't really find a way to tell the UI what the valid credential types are without also having to implement checking/updating/etc. of those credential types. But I really don't want to re-implement password or otp credentials just because I want to store my users in my own User Federation.
Am I missing something?

**Comment by ssilvert** [comment] 2023-04-13 01:24
I'm going to re-label this as a server-side issue.  But without a reproducer, I can't be sure if this is a bug in your code or ours.  And I don't know if we intend that you should be required to implement `CredentialInputUpdater`.  But someone on the core team should know.

**Comment by gvonroten** [comment] 2023-04-13 14:51
ok, sounds good. Thanks!

**Comment by mposolda** [comment] 2023-04-18 08:05
@ssilvert Did some investigation, I am changing again to team/ui and marking as a regression. As pointed above by @gvonroten, this is likely caused by the admin console related change https://github.com/keycloak/keycloak/commit/2ae520fb8a578ac2a44bed55e5c89f147d16a13f#diff-a1e2da5a441004308e9f0a28ff989d02e123ec30a1c9a63e347a11fcac490137

I am able to reproduce this with `DummyUserFederationProvider` from our testsuite. You can deploy it by running embedded Keycloak (via KeycloakServer application) or by depoying testsuite-providers to your server distribution. What I did is:
- Create realm
- Create new `Dummy` provider in this realm
- Create user `john` in the admin console. This user is added in the dummy provider (due the fact `DummyUserFederationProvider` implements `UserRegistrationProvider`)

The behaviour is:

- In the Keycloak 20.0.5, the user `john` can create his password in the admin console. This applies for both new admin console and old admin console. See screenshots:

![john-20 0 5-old-admin-console_credentials](https://user-images.githubusercontent.com/1223965/232711610-b1d6d3a5-f756-4d60-bf59-96aaab418b45.png)

![john-20 0 5-new-admin-console_credentials](https://user-images.githubusercontent.com/1223965/232711806-a241a7c3-9eaa-4826-83d9-2858311ef04d.png)

Note that I am able to set the password for user `john` and this password is saved in the Keycloak DB (due the fact that `DummyUserFederationProvider` does not implement `CredentialInputUpdater`. If provider implements `CredentialInputUpdater`, it means that it prefers to save the password on it's side instead of Keycloak DB). User `john` is able to authenticate with his password.

However in the latest Keycloak main, I cannot see the ability for the user to set his password. See screenshot:
![john-999-SNAPSHOT-new-admin-console_credentials](https://user-images.githubusercontent.com/1223965/232711915-5c4cd8ec-da3d-4a13-bd13-b09e3c235210.png)

I think it will be good to make sure that behaviour in latest Keycloak main is same as was before in Keycloak 20.0.5 regarding passwords.

**Comment by mposolda** [comment] 2023-04-18 08:06
@ssilvert ah, and one note: Area of user-storage providers is more related to `team/store` rather than `team/core` :-)

**Closed** 2023-05-02 21:09 UTC
Labels: kind/bug, impact/high, team/ui, status/regression

**Comment by ssilvert** [comment] 2023-05-02 21:11
@gvonroten This should be fixed now.  You can give the nightly build a try starting Wednesday.

https://github.com/keycloak/keycloak/releases/tag/nightly
