### ISSUE TITLE
SSO with Keycloak and Azure IDP, user getting Account exists.

### ISSUE THREAD

**Issue by DREGALLA** [keycloak/keycloak#35028] opened 2024-11-18 07:00 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

SSO with Keycloak and Azure IDP, user getting Account exists.

Found following log errors in keycloak logs.
type=IDENTITY_PROVIDER_FIRST_LOGIN_ERROR, error=invalid_user_credentials.

### Version

26

### Regression

- [ ] The issue is a regression

### Expected behavior

login successfully

### Actual behavior

SSO with Keycloak and Azure IDP, user getting Account exists.

### How to Reproduce?

Intermittently, existing THD users will get an error when attempting to login w/ SSO with “Account already exists” Solution realm login
error
<img width="321" alt="Keycloak_Error" src="https://github.com/user-attachments/assets/0d69d031-e1d0-4e8c-8b6e-d6721ee60d9a">

### Anything else?

 Configured the following Flow in Keycloak
<img width="952" alt="Auth_1" src="https://github.com/user-attachments/assets/b697890d-1c68-4b5d-8c51-fc991162154e">
<img width="954" alt="Auth_2" src="https://github.com/user-attachments/assets/b590fecf-0423-46b8-b77c-027b2677fd40">
<img width="944" alt="Auth_3" src="https://github.com/user-attachments/assets/20a38420-e5c3-41ce-be1c-13bd32672353">
<img width="959" alt="Auth_4" src="https://github.com/user-attachments/assets/de61cec5-f777-4747-b38b-2082ac1c0820">

**Comment by sschu** [comment] 2024-11-18 08:56
Duplicate of https://github.com/keycloak/keycloak/issues/34831.

**Closed by sschu** 2024-11-18 08:56 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients

**Comment by seema1322** [comment] 2025-08-28 11:40
I am also facing same issue with keycloak 26.2.4 if anyone knows any fix please reply

<html>
<body>

August 28, 2025 at 4:24 PM | No user details | IDENTITY_PROVIDER_FIRST_LOGIN_ERROR | 49.249.28.90 | flink-react-azure-service
-- | -- | -- | -- | --
  | identity_providerazure-idpauth_methodopenid-connectredirect_urihttps://oauth.pstmn.io/v1/callback
identity_provider_identity eyx02aoqoh98hdiaeordshjgbhqunqet2xxo5rylnl3dpv-8code_id46a2c6c8-f6b2-46b5-b162-c450b77a5a84errorinvalid_user_credentials


</body>
</html>
