### ISSUE TITLE
Set requests and limits for the keycloak deployment

### ISSUE THREAD

**Issue by Jumziey** [keycloak/keycloak#20107] opened 2023-05-02 14:41 UTC
When specifying the Keycloak kind you have no way to actually set the limits and requests without going via the unsupported route.

This is of particular interest if you use karpenter but generally is good practice so no pods start to get OOM killed or similar.

**Comment by shawkins** [comment] 2023-06-10 18:30
Another issue with using the unsupported mechanism is that the process launch seems to default to use the values "-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m" rather than relying upon jvm ergonomics or similar to infer them.  That means you'd have to know to set both the resources and override the JAVA_OPTS environment variable.

**Comment by vmuzikar** [comment] 2024-02-02 17:33
Duplicate of #26456

**Closed by vmuzikar** 2024-02-02 17:33 UTC
Labels: kind/enhancement, team/cloud-native, area/operator
