### ISSUE TITLE
./kc.sh does not pickups conf/quarkus.properties

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#15740] opened 2022-11-29 10:43 UTC
### Area

dist/quarkus

### Describe the bug

How can we point quarkus.properties reside in keycloak/conf/ ?

I’m running it in standalone box not the container one.

I kept these properties in quarkus.properties

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=mypassword

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/QuarkusDB
quarkus.datasource.jdbc.max-size=16

and then simply invoking the cli

./kc.sh start-dev

But it start with default database and does create and table in the postgres db.

Can you tell me how to point quarkus.properties

### Version

20.0.1

### Expected behavior

No documentation available  

### Actual behavior

It should have been documented well.

### How to Reproduce?

Run ./kc.sh start-dev

**Comment by JasonGantner** [comment] 2022-12-02 13:32
I'vz witnessed similar behaviour on both 19.0.3 and 20.0.1 ignoring conf/cache-ispn.xml

**Comment by andre-nascimento-rh** [comment] 2022-12-15 12:53
Hello, @ajaiswal595 ,


Thanks for your effort. 

But this issue is NOT a bug. According to this Keycloak Guide [here, section "Using raw Quarkus properties"](https://www.keycloak.org/server/configuration), the `quarkus.properties` file can be used to set or enable some specific behavior or capability that is missing in the Keycloak configuration. For Database connection settings you must rely on Keycloak database properties instead of "quarkus.datasource.*" properties.

We're gonna improve the documentation to make it clearer.

I'm closing this issue, but feel free to reopen it again If you have other relevant point of view.

Thanks.

**Closed by andre-nascimento-rh** 2022-12-15 12:53 UTC
Labels: kind/enhancement, area/docs, area/dist/quarkus
