### ISSUE TITLE
Admin console tabs doesn't load properly while using realms 

### ISSUE THREAD

**Issue by chandu412** [keycloak/keycloak#19951] opened 2023-04-25 18:33 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

when we navigate to the clients, client scopes , users , groups etc in the admin console  it throws unable to preload css and 502 in network logs , even after refresh the issue persists 

![keycloak](https://user-images.githubusercontent.com/48725425/234366970-4762ce97-c93a-4b07-9977-5917929644d9.png)

![keycloak-2](https://user-images.githubusercontent.com/48725425/234369771-c0cf859b-e74d-4280-a585-e55392d269c6.png)

### Version

20.0.3

### Expected behavior

Load all the data on admin console properly with out any errors when we will multiple realms 

### Actual behavior

Throws error while accessing the admin console and dosent load UI properly 

### How to Reproduce?

* Running key cloak 20.0.3 on Dev mode 
=================================
Config map:
===============================
data:
  DB_ADDR: keycloak-postgres:5432
  DB_DATABASE: keycloak
  JDBC_PARAMS: useSSL=false
  KC_DB: postgres
  KC_DB_PASSWORD: xxxxxxx
  KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
  KC_DB_USERNAME: postgresadmin
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_URL: https://xxxxxxxxxxx/auth
  KC_HTTP_RELATIVE_PATH: /auth
  KC_PROXY: edge
  KEYCLOAK_ADMIN: keycloak
  KEYCLOAK_ADMIN_PASSWORD: xxxxxxxxxxx
  KEYCLOAK_LOGLEVEL: DEBUG
  PROXY_ADDRESS_FORWARDING: "true"
  WILDFLY_LOGLEVEL: DEBUG
====================================
Tried with KC_HOSTNAME_PATH as well in the keycloak well but keycloak pod dosent up with this option hence trying with KC_HTTP_RELATIVE_PATH
================
Ingress:
===============
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: keycloak
    meta.helm.sh/release-namespace: ethan
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
  creationTimestamp: "2023-04-24T06:59:04Z"
  generation: 2
  labels:
    app: keycloak
    app.kubernetes.io/managed-by: Helm
    chart: keycloak-xxxx
    heritage: Helm
    release: keycloak
  name: keycloak
  namespace: ethan
  resourceVersion: "2110254"
  uid: 4849e4ef-391d-4dc2-946e-1ab598e55637
spec:
  rules:
  - host: xxxxxxxx.com
    http:
      paths:
      - backend:
          service:
            name: keycloak-http
            port:
              number: 8080
        path: /auth
        pathType: Prefix
  tls:
  - hosts:
    - xxxxxxxxxx.com
    secretName: ingress-ssl

### Anything else?

is there any extra configuration is required to run behind Reverse proxy  (Nginx - ingress) ? please let me know if more information is required

**Comment by ssilvert** [comment] 2023-04-25 20:01
This appears to be a duplicate of https://github.com/keycloak/keycloak/issues/14666#issuecomment-1265482244.  I'll add it to that issue and close this one.

**Closed by ssilvert** 2023-04-25 20:01 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
