### ISSUE TITLE
Poor Error Handling: Unhandled Exception 22.0.1 version

### ISSUE THREAD

**Issue by harshadevaraju** [keycloak/keycloak#24211] opened 2023-10-23 06:34 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

There are issues found in the below files and the highlighted in bold was found by WebInspect.

File: auth/resources/71jvb/admin/keycloak/js/services.js
Line 598: '/admin/realms/:realm/attack-detection/brute-force/users/:userId'

File: auth/resources/71jvb/admin/keycloak/js/app.js
Line 385: .when('/realms/:realm/users/:user'
 
File: auth/resources/71jvb/admin/keycloak/js/controllers/users.js
Line 25/47: '/admin/realms/' + realm.realm + '/users/' + user.id + '/role-mappings/realm'

### Version

22.0.1

### Expected behavior

Error/exceptions should be handled

### Actual behavior

Error/exceptions are not handling

### How to Reproduce?

Open the file or URL shown in the description

**Comment by jonkoops** [comment] 2023-10-23 10:03
I am closing this issue as there is not enough information provided to make this reproducible. The code mentioned in the description seems to be old AngularJS code that is no longer present in this version of Keycloak, so I am not sure why that is being shown, perhaps this is some kind of custom theme.

Also the steps to reproduce say "Open the file or URL shown in the description", but this URL is not documented anywhere. I would recommend to open an new issue once there is enough information to reproduce this problem with a [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by jonkoops** 2023-10-23 10:03 UTC
Labels: area/authentication, kind/bug, status/triage, team/core
