### ISSUE TITLE
No JSON formatted logs

### ISSUE THREAD

**Issue by gabrbuiv** [keycloak/keycloak#31630] opened 2024-07-25 14:41 UTC
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I'm following the logging [documentation](https://www.keycloak.org/server/logging), but I couldn't manage to get JSON formatted logs neither by enabling it through the environment variable (`KC_LOG_CONSOLE_OUTPUT=json`) nor using a flag (`--log-console-output`).

My full list of environment variables that I pass to ECS task definition:
```
    {
      "name": "KC_DB_URL_HOST", // legacy "DB_ADDR",
      "value": var.database.address
    },
    {
      "name" : "KC_DB_URL_DATABASE", // Misleading name for database name
      "value" : var.database.db_name
    },
    {
      "name" : "KC_DB_SCHEMA",
      "value" : "public"
    },
    {
      "name" : "KC_DB", # legacy DB_VENDOR
      "value" : "postgres"
    },
    {
      "name" : "KEYCLOAK_USER",
      "value" : "admin"
    },
    {
      "name": "KC_HTTP_RELATIVE_PATH",
      "value": local.keycloak_relative_path
    },
    {
      "name": "KC_LOG_LEVEL", # legacy KEYCLOAK_LOGLEVEL
      "value": "INFO"
    },
    {
      "name" : "KC_HOSTNAME",
      "value" : format("%s%s", var.keycloak_hostname, local.keycloak_relative_path)
    },
    # KC_HOSTNAME_STRICT, KC_PROXY_HEADERS and KC_HTTP_ENABLED are needed to avoid requirement for certificate
    {
      "name" : "KC_HOSTNAME_STRICT",
      "value" : "false"
    },
    {
      "name" : "KC_PROXY_HEADERS",
      "value" : "forwarded"
    },
    {
      "name" : "KC_HTTP_ENABLED",
      "value" : "true"
    },
    {
      "name" : "KC_HEALTH_ENABLED",
      "value" : "true"
    }
```

Dockerfile:
```
FROM quay.io/keycloak/keycloak:25.0.2

ENV KC_CACHE_CONFIG_FILE=cache-ispn-jdbc-ping.xml
ENV KC_LOG_CONSOLE_OUTPUT=json

COPY ./ecr/configuration/cache-ispn-jdbc-ping.xml /opt/keycloak/conf/cache-ispn-jdbc-ping.xml

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD [ "start" ]
```

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Structured JSON logs

### Actual behavior

<img width="1147" alt="Screenshot 2024-07-25 at 17 39 07" src="https://github.com/user-attachments/assets/146b1d94-9b36-494b-9ded-155ff370a263">

### How to Reproduce?

Enable JSON logging either by environment variable or CLI flag.

**Comment by shawkins** [comment] 2024-07-26 18:43
I cannot reproduce this. Starting keycloak locally with the env or cli option for the console output works as expected. The same is true when running from an optimized image. It also works when putting the env in the Dockerfile.

Since this is a runtime option you may want to double check everything that is being passed into the command / env - can you remote into the container and check the env and/or use kc.sh show config to confirm what the instance is seeing.

Also it is generally recommend to create an optimized image - that is run the build in the image, then use start --optimized when running the image.

~priority-low

**Comment by gabrbuiv** [comment] 2024-07-29 07:16
> I cannot reproduce this. Starting keycloak locally with the env or cli option for the console output works as expected. The same is true when running from an optimized image. It also works when putting the env in the Dockerfile.

It works for me locally as well, but I start as a `start-dev` though. Not sure if that's related.

> Since this is a runtime option you may want to double check everything that is being passed into the command / env - can you remote into the container and check the env and/or use kc.sh show config to confirm what the instance is seeing.

bash-5.1$ ./kc.sh show-config
Current Mode: production
Current Configuration:
	kc.log-console-output =  json (ENV)
	kc.log-level =  INFO (ENV)
	kc.log.console.output =  json (ENV)
	kc.log.level =  INFO (ENV)

> Also it is generally recommend to create an optimized image - that is run the build in the image, then use start --optimized when running the image.

Can this solve the issue?

**Comment by shawkins** [comment] 2024-07-29 15:16
> It works for me locally as well, but I start as a start-dev though. Not sure if that's related.

It will work with start, an start --optimized, as well.

> Can this solve the issue?

No, that is not a intended to be a solution, just a recommendation.

Given what you are seeing in the environment I would assume that you are producing json console logs. Are you sure that the display you are looking at is showing the raw form?

**Comment by gabrbuiv** [comment] 2024-07-30 05:36
Yes, they still are in the raw form.

**Comment by mabartos** [comment] 2024-09-13 09:14
I'm not able to reproduce it in 25.0.2 and in the latest upstream. Everything works as expected with the `KC_LOG_CONSOLE_OUTPUT=json` env var, or `--log-console-output=json` property.

Closing now, feel free to reopen if you still encounter the issue and provide more details.

**Closed by mabartos** 2024-09-13 09:14 UTC
Labels: kind/bug, area/core, area/dist/quarkus, help wanted, team/cloud-native, priority/low, status/auto-expire, status/auto-bump
