### ISSUE TITLE
Error creating realm

### ISSUE THREAD

**Issue by felipeavilis** [keycloak/keycloak#17635] opened 2023-03-13 22:36 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Im following this guide: https://www.keycloak.org/getting-started/getting-started-zip

1. I opened the Keycloak Admin Console
2. Clicked on the word master in the top-left corner, then clicked on Create realm.
3. I entered myrealm in the Realm name field.
4. Clicked on Create.

... nothing happened. This is the console output after start KC:

    $ ./kc.sh start-dev
    2023-03-13 22:10:07,198 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
    2023-03-13 22:10:08,630 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
    2023-03-13 22:10:09,423 INFO  [org.infinispan.SERVER] (keycloak-cache-init) ISPN005054: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
    2023-03-13 22:10:09,535 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
    2023-03-13 22:10:09,581 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
    2023-03-13 22:10:09,592 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
    2023-03-13 22:10:11,005 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_815371, Site name: null
    2023-03-13 22:10:11,011 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
    2023-03-13 22:10:11,753 INFO  [io.quarkus] (main) Keycloak 21.0.1 on JVM (powered by Quarkus 2.13.7.Final) started in 5.982s. Listening on: http://0.0.0.0:8080
    2023-03-13 22:10:11,754 INFO  [io.quarkus] (main) Profile dev activated.
    2023-03-13 22:10:11,754 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, vertx]
    2023-03-13 22:10:11,993 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
    2023-03-13 22:10:12,000 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
    2023-03-13 22:10:35,229 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-3) SQL Error: 23505, SQLState: 23505
    2023-03-13 22:10:35,229 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-3) Unique index or primary key violation: "PUBLIC.UK_ORVSDMLA56612EAEFIQ6WL5OI_INDEX_6 ON PUBLIC.REALM(NAME NULLS FIRST) VALUES ( /* 2 */ 'myrelam' )"; SQL statement:
    insert into REALM (ACCESS_CODE_LIFESPAN, LOGIN_LIFESPAN, USER_ACTION_LIFESPAN, ACCESS_TOKEN_LIFESPAN, ACCESS_TOKEN_LIFE_IMPLICIT, ACCOUNT_THEME, ADMIN_EVENTS_DETAILS_ENABLED, ADMIN_EVENTS_ENABLED, ADMIN_THEME, ALLOW_USER_MANAGED_ACCESS, BROWSER_FLOW, CLIENT_AUTH_FLOW, DEFAULT_LOCALE, DEFAULT_ROLE, DIRECT_GRANT_FLOW, DOCKER_AUTH_FLOW, DUPLICATE_EMAILS_ALLOWED, EDIT_USERNAME_ALLOWED, EMAIL_THEME, ENABLED, EVENTS_ENABLED, EVENTS_EXPIRATION, INTERNATIONALIZATION_ENABLED, LOGIN_THEME, LOGIN_WITH_EMAIL_ALLOWED, MASTER_ADMIN_CLIENT, NAME, NOT_BEFORE, OFFLINE_SESSION_IDLE_TIMEOUT, OTP_POLICY_ALG, OTP_POLICY_DIGITS, OTP_POLICY_COUNTER, OTP_POLICY_WINDOW, OTP_POLICY_PERIOD, OTP_POLICY_TYPE, PASSWORD_POLICY, REFRESH_TOKEN_MAX_REUSE, REGISTRATION_ALLOWED, REG_EMAIL_AS_USERNAME, REGISTRATION_FLOW, REMEMBER_ME, RESET_CREDENTIALS_FLOW, RESET_PASSWORD_ALLOWED, REVOKE_REFRESH_TOKEN, SSL_REQUIRED, SSO_IDLE_TIMEOUT, SSO_IDLE_TIMEOUT_REMEMBER_ME, SSO_MAX_LIFESPAN, SSO_MAX_LIFESPAN_REMEMBER_ME, VERIFY_EMAIL, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]
    2023-03-13 22:10:35,232 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (executor-thread-3) HHH000010: On release of batch it still contained JDBC statements
    2023-03-13 22:10:35,234 ERROR [org.keycloak.services.resources.admin.RealmsAdminResource] (executor-thread-3) Conflict detected: org.keycloak.models.ModelDuplicateException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
            at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:80)
            at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
            at com.sun.proxy.$Proxy68.flush(Unknown Source)
            at org.keycloak.models.jpa.JpaRealmProvider.createRealm(JpaRealmProvider.java:111)
            at org.keycloak.models.cache.infinispan.RealmCacheSession.createRealm(RealmCacheSession.java:401)
            at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:519)
            at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:504)
            at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:54)
            at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
            at org.keycloak.storage.ImportRealmFromRepresentationEvent.fire(ImportRealmFromRepresentationEvent.java:50)
            at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:159)
            at org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:130)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
            at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
            at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
            at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
            at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
            at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
            at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
            at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
            at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
            at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
            at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
            at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
            at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
            at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
            at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
            at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
            at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
            at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
            at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
            at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
            at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
            at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
            at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
            at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
            at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
            at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
            at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
            at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
            at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
            at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
            at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
            at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
            at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
            at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
            at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
            at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
            at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
            at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
            at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
            at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
            at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
            at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
            at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
            at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
            at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1394)
            at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:60)
            ... 56 more
    Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
            at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
            at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
            at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
            at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
            at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
            at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
            at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375)
            at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3937)
            at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
            at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
            at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
            at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
            at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
            at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
            at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
            at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
            at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
            ... 61 more
    Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UK_ORVSDMLA56612EAEFIQ6WL5OI_INDEX_6 ON PUBLIC.REALM(NAME NULLS FIRST) VALUES ( /* 2 */ 'myrelam' )"; SQL statement:
    insert into REALM (ACCESS_CODE_LIFESPAN, LOGIN_LIFESPAN, USER_ACTION_LIFESPAN, ACCESS_TOKEN_LIFESPAN, ACCESS_TOKEN_LIFE_IMPLICIT, ACCOUNT_THEME, ADMIN_EVENTS_DETAILS_ENABLED, ADMIN_EVENTS_ENABLED, ADMIN_THEME, ALLOW_USER_MANAGED_ACCESS, BROWSER_FLOW, CLIENT_AUTH_FLOW, DEFAULT_LOCALE, DEFAULT_ROLE, DIRECT_GRANT_FLOW, DOCKER_AUTH_FLOW, DUPLICATE_EMAILS_ALLOWED, EDIT_USERNAME_ALLOWED, EMAIL_THEME, ENABLED, EVENTS_ENABLED, EVENTS_EXPIRATION, INTERNATIONALIZATION_ENABLED, LOGIN_THEME, LOGIN_WITH_EMAIL_ALLOWED, MASTER_ADMIN_CLIENT, NAME, NOT_BEFORE, OFFLINE_SESSION_IDLE_TIMEOUT, OTP_POLICY_ALG, OTP_POLICY_DIGITS, OTP_POLICY_COUNTER, OTP_POLICY_WINDOW, OTP_POLICY_PERIOD, OTP_POLICY_TYPE, PASSWORD_POLICY, REFRESH_TOKEN_MAX_REUSE, REGISTRATION_ALLOWED, REG_EMAIL_AS_USERNAME, REGISTRATION_FLOW, REMEMBER_ME, RESET_CREDENTIALS_FLOW, RESET_PASSWORD_ALLOWED, REVOKE_REFRESH_TOKEN, SSL_REQUIRED, SSO_IDLE_TIMEOUT, SSO_IDLE_TIMEOUT_REMEMBER_ME, SSO_MAX_LIFESPAN, SSO_MAX_LIFESPAN_REMEMBER_ME, VERIFY_EMAIL, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]
            at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
            at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
            at org.h2.message.DbException.get(DbException.java:223)
            at org.h2.message.DbException.get(DbException.java:199)
            at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
            at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
            at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
            at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
            at org.h2.command.dml.Insert.insertRows(Insert.java:174)
            at org.h2.command.dml.Insert.update(Insert.java:135)
            at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
            at org.h2.command.CommandContainer.update(CommandContainer.java:169)
            at org.h2.command.Command.executeUpdate(Command.java:252)
            at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
            at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
            at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
            at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
            ... 73 more

### Version

21.0.1

### Expected behavior

Realm created

### Actual behavior

ERROR on console.

### How to Reproduce?

Just follow this guide: https://www.keycloak.org/getting-started/getting-started-zip

- Login to a Linux Server
- Download KC to /tmp directory
 
      cd /tmp 
      wget https://github.com/keycloak/keycloak/releases/download/21.0.1/keycloak-21.0.1.tar.gz

- Untar

       tar -xvf keycloak-21.0.1.tar.gz

- Move directory to /opt

      mv keycloak-21.0.1 /opt/

- Create a symlnk

      cd /opt
      sudo ln -s keycloak-21.0.1 keycloak

- Create admin user and pass vars

      export KEYCLOAK_ADMIN=admin
      export KEYCLOAK_ADMIN_PASSWORD=admin

- Get into keycloak/bin

      cd keycloak/bin

- Run KC

      ./kc.sh start-dev

### Anything else?

**OS**
CentOS Linux 7 (Core)

**Java**
openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.18.0.10-1.el7_9) (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.18.0.10-1.el7_9) (build 11.0.18+10-LTS, mixed mode, sharing)

**Comment by felipeavilis** [comment] 2023-03-13 22:41
After restart the server, the realms were created.

**Comment by ssilvert** [comment] 2023-03-14 19:14
@felipeavilis Do you mind if we close this issue or do you think there is a bug?

**Comment by timas** [comment] 2023-03-15 07:11
> I have started to encounter a similar problem in the keyckoak 21.0.x - when I try to create/delete anything (realm/clent/user/group - whatever) in admin ui - nothing happens. The button can be pressed an infinite number of times - no animation of transition/return to the list of objects occurs. Once I refresh the page manually, I find myself on the object list page (let's say when creating a client, user or group) where I see that the object was successfully created and is displayed in the list.

Faced the same problem

**Comment by dethlex** [comment] 2023-03-15 07:20
Agree with @alexted, we have faced the same issue

**Comment by edewit** [comment] 2023-03-15 09:59
From the logs it seems that the you tried to create the realm twice, you didn't get this message?
![image](https://user-images.githubusercontent.com/51133/225274681-f29ab48f-7c05-4fc1-bc43-edbdbc6e4563.png)

**Comment by edewit** [comment] 2023-03-15 10:00
@alexted do you have any browser console log?

**Comment by ssilvert** [comment] 2023-03-15 11:54
@alexted @timas @dethlex Are you getting the same java stack trace as @felipeavilis in the Keycloak console?

**Comment by mabartos** [comment] 2023-03-15 12:15
@ssilvert @edewit I've encountered the same issue. The realm's creation takes some time, and we need to wait. 

As was mentioned, the create button can be clicked many times, which provokes another HTTP request for creating the realm and cause conflict.  

IMHO, the proper solution would be to disable the `Create` button, show some "loading" element and wait for proper handling of the first request.

**Comment by eyvar-git** [comment] 2023-03-15 12:50
> I have started to encounter a similar problem in the keyckoak 21.0.x - when I try to create/delete anything (realm/clent/user/group - whatever) in admin ui - nothing happens. The button can be pressed an infinite number of times - no animation of transition/return to the list of objects occurs. Once I refresh the page manually, I find myself on the object list page (let's say when creating a client, user or group) where I see that the object was successfully created and is displayed in the list.

+1 the same problem

**Comment by felipeavilis** [comment] 2023-03-15 13:33
> I have started to encounter a similar problem in the keyckoak 21.0.x - when I try to create/delete anything (realm/clent/user/group - whatever) in admin ui - nothing happens. The button can be pressed an infinite number of times - no animation of transition/return to the list of objects occurs. Once I refresh the page manually, I find myself on the object list page (let's say when creating a client, user or group) where I see that the object was successfully created and is displayed in the list.

Its happening exactly as @alexted said.

> From the logs it seems that the you tried to create the realm twice, you didn't get this message? ![image](https://user-images.githubusercontent.com/51133/225274681-f29ab48f-7c05-4fc1-bc43-edbdbc6e4563.png)

No. I was expecting something like that, an error message, but no. Nothing happens.

**Comment by OlegSchwann** [comment] 2023-03-15 15:56
I encountered the same behaviour on the latest version.

**Comment by ssilvert** [comment] 2023-03-15 18:03
I just tried this and I can't recreate from just clicking fast.  I see what @edewit sees.

But there would be no harm in disabling the button after the first click.  Since several of you are reporting this I think we should take the time to fix it.

**Comment by edewit** [comment] 2023-03-16 05:52
okay that's why the alert don't work crypto.randomUUID is not available, if you are not on https or localhost we changed this already in the nightly version.

**Comment by edewit** [comment] 2023-03-16 11:00
right this is a duplicate of https://github.com/keycloak/keycloak/issues/17817

**Comment by ssilvert** [comment] 2023-03-17 11:17
Thanks @alexted.  I'm going to close this.  We can reopen if others find problems with the latest build.

**Closed by ssilvert** 2023-03-17 11:17 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui
