### ISSUE TITLE
Spaces in query paramter gives invalid_redirect_uri error

### ISSUE THREAD

**Issue by ThomasReinhardt** [keycloak/keycloak#31899] opened 2024-08-05 10:50 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Hi,
I was testing a new feature for our KeyCloak enabled application and I stumbled over something strange: when I pass a query parameter that contains a space (url-encoded as +) KeyCloak tells me that the redirect uri is invalid:

```
https://reinhardt:8443/testapp/index.xhtml?x=a+b

2024-07-19 07:44:39,659 WARN  [org.keycloak.events] (executor-thread-2) type="LOGIN_ERROR", realmId="2f034680-378a-4ddb-93fd-e3bf182b22f6", realmName="testrealm", clientId="test_client", userId="null", ipAddress="127.0.0.1", error="invalid_redirect_uri", redirect_uri="https://reinhardt:8443/testapp/index.xhtml?x=a b"
```

Keycloak 25.0.2 - the application works as expected as long as the query parameter does not contain spaces.
Unfortunately I need those spaces because the real application encodes user-supplied data that could contain spaces.
FWIW: we use an Azure / SAML IDP in the realm.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Query paramters with spaces get forwarded correctly.

### Actual behavior

error message "invalid_redirect_uri"

### How to Reproduce?

Create OIDC client and try to open its URL with a query parameter with (url encoded as plus-sign) space(s):
https://reinhardt:8443/testapp/index.xhtml?x=a+b

**Comment by rmartinc** [comment] 2024-08-05 12:08
@ThomasReinhardt Remember that the `redirect_uri` is also passed as a request param itself to the authorization endpoint, so it should be encoded twice. I mean, if you want to pass the `redirect_uri` like the following: `https://reinhardt:8443/testapp/index.xhtml?x=a+b`. Then it should be passed to the `auth` method in a parameter like the following: `redirect_uri=https%3A%2F%2Freinhardt%3A8443%2Ftestapp%2Findex.xhtml%3Fx%3Da%2Bb`. If you see the `+` is encoded again to `%2B`. Check if the URL when you go to the `auth` endpoint has the `+` encoded as `%2B` or not. If it's just a direct `+`, the problem is it's first transformed to space ` ` by the param decoding and, when the final URL contains an invalid space and is discarded.

**Comment by ThomasReinhardt** [comment] 2024-08-05 13:11
@rmartinc Thanks for the quick response. You are right, my parameter was seemingly not correctly encoded. When I replace the original plus-sign in my query parameter I get a different error message: 
```
2024-08-05 14:42:08,142 WARN  [org.keycloak.events] (executor-thread-33) type="CODE_TO_TOKEN_ERROR", realmId="...", realmName="...", clientId="...", userId="...", sessionId="...", ipAddress="127.0.0.1", error="invalid_redirect_uri", reason="Parameter 'redirect_uri' did not match originally saved redirect URI used in initial OIDC request. Saved redirectUri: https://reinhardt:8443/testapp/index.xhtml?f=a+b, redirectUri parameter: https://reinhardt:8443/testapp/index.xhtml?f=a b", grant_type="authorization_code", code_id="...", client_auth_method="client-secret"
```
So I went to the sources and commented the corresponding check in `services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java` and voila my redirect works. So I still think there is a bug in keycloak, but a different one than I thought.

Does that sound plausible or am I holding it wrong?

**Comment by rmartinc** [comment] 2024-08-05 13:27
This new error is that the redirect_uri is different in the token endpoint when calling the code2token. so now initially when going to the auth endpoint keycloak is receving `https://reinhardt:8443/testapp/index.xhtml?f=a+b` (which is OK, the uri is decoded OK with th `+` sign). But later when the app is calling the token endpoint with the code returned the redirect_uri parameter is again with the `+` not encoded (`https://reinhardt:8443/testapp/index.xhtml?f=a b`). So the server complains that the redirect_uri is different. My feeling is that in the app you have to encode the `+` in another place, when calling the token endpoint.

**Comment by ThomasReinhardt** [comment] 2024-08-05 13:36
@rmartinc This is a JSF application on top of WildFly/Elytron. So you think the error is within Elytron?

**Comment by rmartinc** [comment] 2024-08-05 15:29
@ThomasReinhardt If you are manually changing the URL in the browser to encode the `+` sign, yes. wildfly/elytron should encode the `+` into `%2B` for you.

**Comment by mposolda** [comment] 2024-08-15 15:56
@rmartinc Thanks for the hints!

This looks like Elytron issue, so I am closing as invalid.

**Closed** 2024-08-15 15:57 UTC
Labels: area/oidc, kind/bug, team/core-clients
