### ISSUE TITLE
User Profile attributes/groups in Admin UI are not translated using Localization

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#25152] opened 2023-11-30 10:32 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

The User Profile attributes and groups Display Name and Descriptions are not translated in the Admin UI, but are correctly translated in the Register/Update_Profile pages:
In the Admin UI:
![image](https://github.com/keycloak/keycloak/assets/33352511/ac986733-1453-4b04-83fd-af09e0426d84)

In Localization for "English"
![image](https://github.com/keycloak/keycloak/assets/33352511/e56cc55e-e75f-481c-bf7d-8a30ac49d708)

In User Profile->Groups
![image](https://github.com/keycloak/keycloak/assets/33352511/20f5771a-2a12-4352-95fb-cc6d3e2ee544)

In User Profile->Attributes
![image](https://github.com/keycloak/keycloak/assets/33352511/a29a827d-1dae-4e82-97d7-f20b79d59bc7)

In Register page
![image](https://github.com/keycloak/keycloak/assets/33352511/aed6e2ce-e132-41bb-9038-199e702002c5)

### Version

23.0.1

### Expected behavior

The Attributes Display Name and Groups Display Name and Description text to be translated, taking it from the Localization (or only for English, always, or based on the signed in user Locale, again, falling back to English or the Default one set if no translations provdied for the user locale)

### Actual behavior

No translation in the Admin UI for Attributes/Groups when Localization key used

### How to Reproduce?

1. Create Attribute and/or Group
2. Add localization key, using ${theLocalizationKeyForMyAttribute} structure
3. Create a Localization message bundle for English for key "theLocalizationKeyForMyAttribute"
4. Open an user in the Admin UI and check if the Attribute Name or Group name/description is translated as per the localization set

**Comment by antikalk** [comment] 2023-11-30 15:11
This is related to and possibly a duplicate of: https://github.com/keycloak/keycloak/issues/22431

Basically the master admin console does only respect the master realm localization settings. If you sign into the realm specific admin ui you will see the correct localizations being applied.

**Comment by mpalavrov** [comment] 2023-12-01 07:43
Hi @antikalk
The issue seems to be the same (probably duplicate as you wrote).
Regarding the statement, that it should work when I am signed in a realm specific admin, it still doesn't work for me, with KC v23.0.1:
![image](https://github.com/keycloak/keycloak/assets/33352511/eccb4eb1-8891-4ae2-86eb-3404b82bb1a9)

**Comment by jonkoops** [comment] 2023-12-11 11:51
Duplicate of #22431

**Closed by jonkoops** 2023-12-11 11:51 UTC
Labels: kind/bug, area/user-profile, status/triage, team/core
