### ISSUE TITLE
User in subgroup not synchronized and still appears as not in the subgroup

### ISSUE THREAD

**Issue by Lexachoc** [keycloak/keycloak#30143] opened 2024-06-04 13:19 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Today I found that one of my user was showing in the "Add member" panel
![image](https://github.com/keycloak/keycloak/assets/20377719/9b6fe621-a78d-4c11-bff2-7a82052712ad)

But I already added this user to the sub-group almost 1 month ago!

And in the user details I can see that the user is actually in the sub-group.
![image](https://github.com/keycloak/keycloak/assets/20377719/5f6a32f3-edc3-416c-9907-aabefef00eca)

But then, I go the the "Groups" page, check again:
![image](https://github.com/keycloak/keycloak/assets/20377719/c1d551b8-3370-4e60-a2a8-a6ebc583fc1b)

But it is still displayed in the "Add member" panel , as in the first image.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that the added user *in the sub-group) won't appear in the "Add Member" panel (window) again.

### Actual behavior

the already added user appears again in the "Add member" panel (window).

### How to Reproduce?

Cannot provide steps to reproduce. This is happening today and I have tried logging out and back in. But it still shows. I even tried to remove this user from the sub-group and add it again, but it still shows up.

**Comment by jonkoops** [comment] 2024-06-04 14:29
Closing this as it's an issue with an older version of Keycloak that is no longer supported. We will not accept issues that do not have steps to reproduce, because we cannot fix bugs that we cannot replicate.

**Comment by Lexachoc** [comment] 2024-06-04 18:01
I ran test to remove another user (named "B") from the sub-group. Then the user ("A") disappeared in the "Add member" window, but after I added user B back, user A shows up again. This is so weird.

I will update to the latest version and get back to you if this issue is still present in the latest version. 
But as I said, I have no idea how to reproduce this for you. The issue is only happening today and oddly enough with a user who has been in this subgroup for almost a month, not new users.

**Comment by Lexachoc** [comment] 2024-06-10 06:53
@jonkoops Do you think this is enough to reopen the issue? 

I upgraded to Keycloak 24.0.5 today but this issue still remains.
![image](https://github.com/keycloak/keycloak/assets/20377719/eb545487-3a46-4fc8-809f-4b38a86e3707)

This issue occurs when I have more than 100 users in the subgroup and each new user registers, the old user is displayed again in the "Add member" window.
So I now have 105 users in the subgroup, but it only recognizes 100 users and shows me 5 users (who are already in the subgroup) who are not in the group and can be added. BUT those 5 users are already in the sub-group.

![image](https://github.com/keycloak/keycloak/assets/20377719/92263aec-975f-4e36-84e2-7c50702f44b2)

This 5 users will still show in the "Add member" window.

**Closed** 2024-06-14 12:26 UTC
Labels: kind/bug, priority/important, area/account/ui, team/ui

**Comment by Lexachoc** [comment] 2025-01-16 03:41
@jonkoops @edewit  I just upgraded to keycloak 26.0.0 and checking if the issue is solved. But unfornately I still seeing users that are already in the subgroup. 

I have over 500 users in a subgroup. And in the `Add Member` window. Now all users are listed there.

But shouldn't only those users who are not in this subgroup be listed there? Since they are already members of this subgroup, wouldn't it make sense to display those who are not in the `Add Member` window? Am I understand it wrong or this issue is still there?

As you can see, all users are now displayed. Before the PR, only users above the 100th position were displayed here. (This is when I discovered the bug.

![Image](https://github.com/user-attachments/assets/8739a4f7-4acc-4a7c-9675-40b642eeef42)

**Comment by Lexachoc** [comment] 2025-01-16 14:32
@jonkoops I am already using 26.1.0 and it still persists. Yes, I'll open a new issue.

P.S. it is actually the same steps in this issue to reproduce.

**Comment by jonkoops** [comment] 2025-01-16 14:33
Thanks, apologies for the extra work. Logging a new issue makes it easier for us to triage.
