### ISSUE TITLE
GET `/admin/realms/{realm}/groups` Endpoint Not Returning `subGroups`, `clientRoles`, `realmRoles` Despite `populateHierarchy` and `briefRepresentation` settings"

### ISSUE THREAD

**Issue by Romain7495** [keycloak/keycloak#25053] opened 2023-11-27 16:03 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

The GET `/admin/realms/{realm}/groups` endpoint is not returning `subGroups`, `clientRoles`, and `realmRoles` as part of the response, despite the documentation indicating these are optional fields. The migration documentation mentions `populateHierarchy` is supposed to be `true` by default, but it seems to have no effect even if we pass it explicitely to `true`. Similarly, `briefRepresentation`, which was previously functional, now appears to be ineffective. This raises the question of whether this is a bug or an intentional change in the API functionality.

### Version

23.0

### Expected behavior

The endpoint should return `subGroups`, `clientRoles`, and `realmRoles` as part of the response when appropriate query parameters are set, as per the existing documentation and the default setting of populateHierarchy (`"populateHierarchy": true`).

### Actual behavior

Despite setting `populateHierarchy`, the endpoint response does not include subGroups, clientRoles, and realmRoles.

### How to Reproduce?

1. Send a GET request to `/admin/realms/{realm}/groups` with `populateHierarchy` set to `true`.
2. (OPTIONAL) Attempt the same with `briefRepresentation` set to true and false.
3. Observe the missing `subGroups`, `clientRoles`, and `realmRoles` in the response.

### Anything else?

We have reviewed the Keycloak migration documentation for version 23.0.0, specifically regarding `populateHierarchy` and the new endpoint for `Group Admin Api`, available here: [Migrating to 23.0.0](https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-23-0-0). There is a lack of clarity on whether the absence of these fields in the response is a bug or an intended change. Clarification on this matter would be highly appreciated.

Here is the documentation for version `23.0`:  

GET on `/admin/realms/{realm}/groups`
![image](https://github.com/keycloak/keycloak/assets/15386726/1a403112-8d64-479e-90f1-6214a967db62)

Group Representation
![image](https://github.com/keycloak/keycloak/assets/15386726/06bfecea-fef6-4ca7-bf59-e3720add7d96)

**Comment by transducer** [comment] 2024-01-10 19:02
@alice-wondered I think this is related to the performance update (https://github.com/keycloak/keycloak/issues/22261). Is returning the subGroups with `GET /auth/admin/realms/{realm}/groups/{id}` a feature that is intended to keep working? Or should we now explicitly call `GET /auth/admin/realms/{realm}/groups/{id}/children`?

**Comment by alice-wondered** [comment] 2024-01-12 07:02
Hey! The group scalability work had to make a trade-off between the overhead that comes from certain ways that groups were processed and maintaining full backwards compatibility. 

One oddity was that searches in the past would bubble all the way up to their root level groups and then populate out the entire group hierarchy underneath it (which is why you would always get the full list of subgroups back from the API). 

The problem was that when you have, say, 10k groups below a parent group, the entire server would grind to a halt doing all of the tree navigation, loading everything, serializing it, etc. 

To remove that searches now return only their relevant groups and then "populate hierarchy" will climb the hierarchy and load each direct parent group to build out the tree. This gives a narrow slice of the tree that only includes the immediately relevant groups to the search. 

Sub group count was added to flag to the user on any group that more groups are available for request because of that. 

That entire explanation is to say that it is expected to explicitly ask for the the subgroups from the "children" endpoint now. It provides a way to load, search, and paginate on those results as well. The increase in functionality and scalability being hopefully worth the loss of compatibility

**Comment by transducer** [comment] 2024-01-12 09:15
Thanks for explanation!

**Comment by Romain7495** [comment] 2024-01-12 09:40
If I summarize correctly, we removed the feature without documentation and without deprecation notice ? If the goal is only to retrive the list of groups, we will need to do hundreds of useless http call ? To retrieve a small list of subgroups ? @alice-wondered

**Comment by vil2be** [comment] 2024-01-12 12:38
I noticed also a similar issue from the UI with KC 23.0.4. When trying to do a group listing via
**https://HOST_NAME/auth/admin/realms/REALM_NAME/groups** redirects to **https://HOST_NAME/auth/admin/realms/REALM_NAME/groups?max=11** without showing the list and just constant spinning navigation on the right pagination and shows a 504 error afterwards from our gateway. 

The following screenshot shows this: 
![KC23_groupscalabilityissue_1](https://github.com/keycloak/keycloak/assets/111115914/533c3e29-2efd-4293-a8b0-d97889fb7100)

I understand it has the request endpoint **/groups?max=11** because it was trying to access depending on the Filter groups range on the right as shown. 
![KC23_groupscalabilityissue_3](https://github.com/keycloak/keycloak/assets/111115914/c83f660a-0c48-4e99-8017-b75f04082ae0)

Knowing this, I tried to change the range to see what requests these designate to in my dev-tools. The screenshot shows as follows: 
![KC23_groupscalabilityissue_2](https://github.com/keycloak/keycloak/assets/111115914/7c92db71-383f-4ffe-9b6c-c78e0a2607f1)

The following observations could be made:

- When refreshed again alternatively, we could see in the right pagination that the Filter groups range on the right starts from 0-0 instead of 1-10 or 11-20 and so on and so forth 
- While playing around with the Filter groups range, I noticed the following with the requests done as shown in the screenshot. The request either has **/groups?first=-1&max=<any number in 11,21,51,101>** or **/groups?max=<any number in 11,21,51,101>**. When the first attribute is there then the query works but when it is not there then it leads to a 504
- I'm not sure if this is related to: [js/apps/admin-ui/src/groups/GroupTable.tsx](https://github.com/keycloak/keycloak/pull/22700/files#diff-fb33de9577fb9729e8721b82a6cac48525932e910d0597da1fbe41f0298fba71) or the if-else statements in  [services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java](https://github.com/keycloak/keycloak/pull/22700/files#diff-cdba8763b4828809135e80a085d9b697f88fe999a9d76ad06988037a5403c84eR103)

Please advise, thanks!

**Comment by Romain7495** [comment] 2024-01-12 14:01
@transducer as I mentionned in the initial issue, `subGroups`, `clientRoles`, and `realmRoles` are empty.


I agree with subGroupCount in the migration guide. But 

> `subGroups` list is now only populated on queries that request hierarchy data

What is the goal of `populateHierarchy` in this case ? if `subGroups`, `clientRoles`, and `realmRoles` are not populated ?

There is a real issue here. This endpoint breaks lot of things on version 23.0.x and need to be fixed or assumed in the documentation.

**Comment by transducer** [comment] 2024-01-12 14:46
`populateHierarchy` now populates "from the bottom-up`, meaning that if you get a child you get the parent but not the other way around.

The missing `clientRoles` and `realmRoles` I didn't notice since we don't use it and I also don't see it mentioned in the Upgrading Guide. That change might be unintended.

We have various APIs and internal tools we have to change.

**Comment by alice-wondered** [comment] 2024-01-12 17:29
The `clientRoles` and `realmRoles` issue might have been related to the inversion on the `briefRepresentation` logic that wasn't intended. I think I saw that issue linked in this thread earlier. 

The actual code that populates those fields was otherwise untouched so if that behavior is regressed I'm not immediately sure what the cause is. 

Relevant section of the code: 
https://github.com/keycloak/keycloak/blob/c2b132171d1ba5e689239a7d00728dc6846e2954/server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java#L129-L155

**Comment by transducer** [comment] 2024-01-12 18:14
The fix for the inversion of the meaning of `briefRepresentation` is available since 23.0.4. @Romain7495 the not returning of `clientRoles` and `realmRoles` might have been fixed in the latest version. Or by using an earlier 23.0.* version than 23.0.4 you can check by passing `briefRepresentation=false`, since meaning of that parameter was inverted from 23.0.0 till 23.0.3 in some cases.

**Comment by alice-wondered** [comment] 2024-01-12 21:05
Digging around from #22261 onward for anything that touches roles and came across some changes from #23404 

That's the only thing that I've come across that changes anything with roles. 

@sschu @ahus1 could this be related to the regression described here?

**Comment by sschu** [comment] 2024-01-15 09:15
@alice-wondered I don't think so. The PR only touched the roles endpoints and it is already included in 23.0.0 while this reports says it worked in 23.0.3 and is broken in 23.0.4.

**Comment by transducer** [comment] 2024-01-15 09:18
@sschu the original report is about changes from 22 to 23.

**Comment by Romain7495** [comment] 2024-01-15 13:38
@transducer I confirm that in `23.0.4`, `clientRoles` and `realmRoles` are well return for `{keycloak server}/realms/{realm}/groups/{group_id}`

We also have `subGroupCount` but no `subGroups` that we had in `22.0.5` and in the upgrading guide:

![image](https://github.com/keycloak/keycloak/assets/15386726/0a1566cf-595d-48ea-a5bf-a2c27a987d0f)

Can you confirm that this is an issue or we need to call `{keycloak server}/realms/{realm}/groups/{group_id}/children`

For my understanding, the best practice is to migrate to the `/children` route, which, since the `23.0.4` fix, now returns `clientRoles`, `realmRoles`, and `subGroupCount`

**Comment by transducer** [comment] 2024-01-16 11:32
@Romain7495 as mentioned in [the comment of alice-wondered](https://github.com/keycloak/keycloak/issues/25053#issuecomment-1888535340) we should now call "children" to get the children yes.

Happy to hear that since the 23.0.4 roles are returned for you.

**Comment by transducer** [comment] 2024-01-16 12:30
Also [`getSubGroupCount`](https://www.keycloak.org/docs-api/23.0.4/javadocs/org/keycloak/representations/idm/GroupRepresentation.html#getSubGroupCount()) returns null.

**Closed** 2024-01-16 12:37 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core

**Comment by davidgubler** [comment] 2024-03-26 08:26
It would be nice to do breaking API changes in a more graceful way in the future, as a lot of people (us included) have built clients which rely on how the API works, and we don't like being confronted with broken systems out of the blue.

Ideal would be a versioned API endpoint with the API version increasing on breaking changes.
