### ISSUE TITLE
[Keycloak Integration CI] - Extension - Unit Test failures

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#35967] opened 2024-12-17 07:23 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
Error:  Errors: 
Error:    ExtendAdminConsoleTest.testAdminUiTodoApp:98 » NoSuchElement no such element: Unable to locate element: {"method":"xpath","selector":"//input[@data-testid='name']"}
  (Session info: chrome=131.0.6778.108)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'fv-az1758-516', ip: '10.1.0.61', os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-1017-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.108, chrome: {chromedriverVersion: 131.0.6778.87 (ce31cae94873..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:44529}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 0ac3527022a3ea44fb6d20c444d225bc
*** Element info: {Using=xpath, value=//input[@data-testid='name']}
Error:    ExtendAdminConsoleTest.testRealmSettingsAttributes:109 » NoSuchElement no such element: Unable to locate element: {"method":"xpath","selector":"//input[@data-testid='logo']"}
  (Session info: chrome=131.0.6778.108)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'fv-az1758-516', ip: '10.1.0.61', os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-1017-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.108, chrome: {chromedriverVersion: 131.0.6778.87 (ce31cae94873..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:44529}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 0ac3527022a3ea44fb6d20c444d225bc
*** Element info: {Using=xpath, value=//input[@data-testid='logo']}
[INFO] 
Error:  Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```

https://github.com/keycloak/keycloak-quickstarts/actions/runs/12366108805/job/34512237668

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by edewit** [comment] 2024-12-20 07:57
duplicate of #35874 now fixed

**Closed by edewit** 2024-12-20 07:57 UTC
Labels: kind/bug, priority/important, area/ci, team/ui, flaky-job
