### ISSUE TITLE
Single quotes not being escaped in message_fr.properties when displayed with message.summary

### ISSUE THREAD

**Issue by cedricguindon** [keycloak/keycloak#10386] opened 2022-02-22 13:31 UTC
### Describe the bug

When a translation string, located in a message_XX.properties file, contains a double single quotes. 
ex: 
message_fr.properties
internalServerError=Une erreur interne du serveur s''est produite

And that string is used by the ${message.summary?no_esc} theme code, the single quotes are not being escaped and displayed as 2 single quotes instead of a single one.

When a trasnlation string is used with the "msg("XX")" theme code, there's no problem.

### Version

16.1.1

### Expected behavior

The double single quotes should be escaped and a single quote should be displayed.

### Actual behavior

the double single quote is not being escaped

### How to Reproduce?

Generate a "500 server error" in a french page, the error.ftl page will be triggered and the "internalServerError=Une erreur interne du serveur s''est produite" will be displayed.

**Comment by stianst** [comment] 2022-02-25 10:24
Wouldn't think you need to escape a single quote, so message should just be `Une erreur interne du serveur s'est produite`

**Comment by romanivna** [comment] 2024-02-02 13:03
Dear KC Team, any news about this?
Italian, french and even english translations are affected
We should remember to put 2 quotes every time, it's quite annoying for custom theme and pages...

**Comment by jonkoops** [comment] 2024-02-02 16:00
We are currently at capacity, which means the team does not have the time to look at this. The issue is marked as help wanted, so feel free to open up a PR to resolve this issue.

**Closed** 2024-06-05 00:06 UTC
Labels: kind/bug, area/translations, good first issue, help wanted, team/community, status/auto-expire, status/auto-bump, priority/normal, status/expired-by-bot
