### ISSUE TITLE
Same Site attribute not set when clearing KEYCLOAK_SESSION cookie on logout.

### ISSUE THREAD

**Issue by Adasgd** [keycloak/keycloak#21214] opened 2023-06-26 14:16 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I am logged in application through Keycloak. I want to logout from different website in different domain, and the logout is called from an iFrame. Logout request goes first to my app and then to Keycloak usind Keycloak Java API.
The logout in Keycloak works correctly, but in HTML Response Keycloak does not set SameSite=None attribute for the KEYCLOAK_SESSION cookie. So then when the first application runs the "check_session_iframe" link to see if user is still logged in, this does not work correctly because check_session_iframe checks KEYCLOAK_SESSION cookie and this still exists because clearing of it was blocked by Chrome browser due to SameSite not set in response for this cookie.

### Version

21.1.1

### Expected behavior

The SameSite=None attribute should be set in KEYCLOAK_SESSION cookie in HTML Response on Keycloak logout 

### Actual behavior

The SameSite=None attribute is not set in KEYCLOAK_SESSION cookie in HTML Response on Keycloak logout 

### How to Reproduce?

See bug description.

**Comment by pedroigor** [comment] 2023-12-19 14:43
@Adasgd Do you mean the `SameSite` is not being set when the server is expiring the `KEYCLOAK_SESSION` cookie?

**Comment by pedroigor** [comment] 2024-01-02 13:48
I'm closing this one because I'm not able to reproduce it. If you can provide more details about how to reproduce the problem, you can re-open the issue.

It is a confusing topic with lots of back and forths and more details is needed to make sure what we should do.

I can understand we don' set `SameSite` when expiring the cookie, not only `KEYCLOAK_SESSION` but changing the behavior is tricky and requires more discussion.

**Closed by pedroigor** 2024-01-02 13:48 UTC
Labels: area/authentication, kind/bug, status/triage, team/core
