### ISSUE TITLE
Client scope role mapping not updated

### ISSUE THREAD

**Issue by pkeuter** [keycloak/keycloak#33998] opened 2024-10-16 12:41 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

We have a setup with 2 Keycloak instances which are both accessed round robin by a reverse proxy. When adding a client scope role mapping, this is reflected in the database, and in Keycloak instance A, but not in Keycloak instance B. It looks like the second instance does not see the change and therefore does not clear it's cache.

I am not 100% sure if this is a regression, but we have never seen this before so I will mark the regression-checkbox.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

All instances of Keycloak should reflect the update when a client scope role mapping is added.

### Actual behavior

Only the instance handling the update reflects the update.

### How to Reproduce?

In a 2 instance setup:
1. Add a client scope role mapping to instance A
2. Check instance A -> it will reflect the update
3. Check instance B -> it will not reflect the update

**Comment by rmartinc** [comment] 2024-10-23 13:34
Duplicate of #33731

**Closed by rmartinc** 2024-10-23 13:34 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core-clients
