### ISSUE TITLE
Can't accept terms and conditions after upgrade from 20.0.3 to 21.0.0

### ISSUE THREAD

**Issue by esbakker** [keycloak/keycloak#17277] opened 2023-02-24 14:37 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

We have enabled Terms and Conditions and Email verificiation as required default actions when a new user is registered.

We updated to keycloak 21 today and new users can't accept the terms and conditions any more.
When Accept is clicked it just reloads the page, and the action isn't removed from the list of required user actions for the user.

### Version

21.0.0

### Expected behavior

When accept is clicked on the terms and conditions page the next required action is triggered, or the user is logged in and redirected to the application

### Actual behavior

Terms and conditions page is refreshed when clicking accept.

### How to Reproduce?

Enable terms and conditions as required default action in the realm authentication settings.

Create a new user. Click on accept on the terms and conditions page

### Anything else?

Some logs around the issue:
```
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-16) Hibernate RegisteredSynchronization successfully registered with JTA platform
DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) Will use client 'web-md-app' in back-to-application link
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) Could not find any cookies with name {0}, trying {1}
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the request header
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the cookie field
DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (executor-thread-16) Found AUTH_SESSION_ID cookie with value 4bc3b110-fdc9-43e7-8678-9237b771faeb
DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) required action doesn't match current required action
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) JtaTransactionWrapper  commit
DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (executor-thread-16) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) Initiating JDBC connection release from beforeTransactionCompletion
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) Initiating JDBC connection release from afterTransaction
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) JtaTransactionWrapper end
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) new JtaTransactionWrapper
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) was existing? false
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-16) Hibernate RegisteredSynchronization successfully registered with JTA platform
DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) Will use client 'web-md-app' in back-to-application link
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) Could not find any cookies with name {0}, trying {1}
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the request header
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the cookie field
DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (executor-thread-16) Found AUTH_SESSION_ID cookie with value 4bc3b110-fdc9-43e7-8678-9237b771faeb
DEBUG [org.keycloak.services.managers.AuthenticationManager] (executor-thread-16) processAccessCode: go to oauth page?: false
```

especially the line `DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) required action doesn't match current required action` seems strange.

It seems even worse, I can't remove the terms and conditions action using the admin console. If I remove the action from required actions of the user and save, it seems like it has been removed, but if I refresh the page, the action reappears again.

**Comment by sboetzel-ewc** [comment] 2023-03-02 00:47
I have the same problem, using official docker image 21.0.1 with realms created in keycloak<21.0

**Comment by MiGrandjean** [comment] 2023-03-03 10:12
> But if in that fresh container you create a new realm, users can register and accept terms in that new realm without any problem (but not in the other, imported realm).

That was a good hint. I can confirm that it works with new realms, but not with older realms created prior to upgrading to 21.0.0.

For old realms I can see "Terms and Conditions" **twice** in _Authentication_ -> _Required Actions_:

![image](https://user-images.githubusercontent.com/8418423/222692418-1bb740ee-2eba-4ee2-bd57-12e4ef66c219.png)

One obvious difference between an export of an old realm and and export of a new one is this:

```diff
   "requiredActions": [
     [...]
     {
-      "alias": "terms_and_conditions",
+      "alias": "TERMS_AND_CONDITIONS",
       "name": "Terms and Conditions",
-      "providerId": "terms_and_conditions",
+      "providerId": "TERMS_AND_CONDITIONS",
       "enabled": true,
       "defaultAction": true,
       "priority": 20,
```

This is currently just a guess, but https://github.com/keycloak/keycloak/commit/de7dd77aebe5f81cf108d4e642400feddcbae150 seems to be a possible cause?

**Comment by Vespasian** [comment] 2023-03-03 16:48
Workaround (Maybe): On a testing system, I renamed the policy (to math the others) in the database and after restarting KC it seemed to have fixed the problem.

**Comment by MiGrandjean** [comment] 2023-03-09 15:07
> I renamed the policy in table required_action_provider (to all upper case) in the database and after restarting KC it seemed to have fixed the problem

Yes, made it work on my test system, too. 

* in the table `required_action_provider`, change `terms_and_conditions` to `TERMS_AND_CONDITIONS` in **both** the `alias` column and in the `provider id` column
* restart Keycloak (in my case I just killed the pod/container)

Without the restart I had some caching(?) issues - when registering a new user, Keycloak would still add something like this to the `user_required_action` table when registering a new user:
| user id                                                                | required action                   |
|--------------------------------------------------------------|---------------------------------------|
| f25850bb-af10-45f3-8b6c-8cb9644775f0    | terms_and_conditions       |
| f25850bb-af10-45f3-8b6c-8cb9644775f0    | VERIFY_EMAIL                       |

when it _should_ have been:

| user id                                                                | required action                   |
|--------------------------------------------------------------|---------------------------------------|
| f25850bb-af10-45f3-8b6c-8cb9644775f0    | TERMS_AND_CONDITIONS |
| f25850bb-af10-45f3-8b6c-8cb9644775f0    | VERIFY_EMAIL                       |

The latter works. That should also be helpful if any user got stuck in the registration process after upgrading to 21.0 but before implementing the above fix.

**Comment by stianst** [comment] 2023-03-10 08:29
@mposolda @hmlnarik this looks like a regression that should be fixed for Keycloak 22. Can you take a look?

**Comment by hmlnarik** [comment] 2023-03-10 09:13
Perhaps caused by #9991

**Comment by raffaeler** [comment] 2023-03-13 15:37
I'm hitting this as well

**Comment by ghenadiibatalski** [comment] 2023-03-29 07:05
Hi all, what is the state of the issue? It blocks the 21.0.2 with some important fixes blocking the update (attributes can not be removed etc.).
Regards, Gena

**Closed** 2023-03-29 14:43 UTC
Labels: area/authentication, kind/bug, priority/important, team/store, team/core

**Comment by stefanwendelmann** [comment] 2023-03-31 11:24
Rolled back my changes in the process of updating from 21.0.1 to 21.0.2

```sql
UPDATE REQUIRED_ACTION_PROVIDER
SET ALIAS = 'terms_and_conditions', PROVIDER_ID = 'terms_and_conditions'
WHERE PROVIDER_ID = 'TERMS_AND_CONDITIONS';

UPDATE USER_REQUIRED_ACTION
SET REQUIRED_ACTION = 'terms_and_conditions'
WHERE REQUIRED_ACTION = 'TERMS_AND_CONDITIONS';
```

**Comment by mhajas** [comment] 2023-03-31 11:38
@stefanwendelmann The rollback should not be needed before the upgrade. The migration introduced in 21.0.2 should do the same thing as was mentioned in:
```sql
UPDATE REQUIRED_ACTION_PROVIDER
SET ALIAS = 'TERMS_AND_CONDITIONS', PROVIDER_ID = 'TERMS_AND_CONDITIONS'
WHERE PROVIDER_ID = 'terms_and_conditions';

UPDATE USER_REQUIRED_ACTION
SET REQUIRED_ACTION = 'TERMS_AND_CONDITIONS'
WHERE REQUIRED_ACTION = 'terms_and_conditions';
```

therefore, if you already migrated the query will do nothing.
