### ISSUE TITLE
Starting from commit 4481b1b3a8 "Running from your IDE" does not work

### ISSUE THREAD

**Issue by potterhe** [keycloak/keycloak#23867] opened 2023-10-10 12:38 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Starting from commit 4481b1b3a8 on branch release/22.0, "Running from your IDE" does not work properly. When running the `org.keycloak.quarkus._private.IDELauncher` class in IDEA, the following error will occur.

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:58)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:88)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at org.keycloak.quarkus._private.IDELauncher.main(IDELauncher.java:45)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:56)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.logmanager.LogContext
	at org.jboss.logmanager.LogManager.getLogger(LogManager.java:110)
	at org.jboss.logmanager.LogManager.getLogger(LogManager.java:27)
	at java.logging/java.util.logging.LogManager.demandLogger(LogManager.java:521)
	at java.logging/java.util.logging.LogManager.demandLogger(LogManager.java:517)
	at java.logging/java.util.logging.Logger.demandLogger(Logger.java:655)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:718)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:702)
	at org.jboss.logging.JDKLogger.<init>(JDKLogger.java:33)
	at org.jboss.logging.JDKLoggerProvider.getLogger(JDKLoggerProvider.java:29)
	at org.jboss.logging.LoggerProviders.logProvider(LoggerProviders.java:152)
	at org.jboss.logging.LoggerProviders.tryJDK(LoggerProviders.java:107)
	at org.jboss.logging.LoggerProviders.findProvider(LoggerProviders.java:102)
	at org.jboss.logging.LoggerProviders.find(LoggerProviders.java:32)
	at org.jboss.logging.LoggerProviders.<clinit>(LoggerProviders.java:29)
	at org.jboss.logging.Logger.getLogger(Logger.java:2465)
	at org.jboss.logging.Logger.getLogger(Logger.java:2491)
	at io.quarkus.bootstrap.utils.BuildToolHelper.<clinit>(BuildToolHelper.java:21)
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:37)
	... 9 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/wildfly/common/lock/SpinLock [in thread "main"]
	at org.jboss.logmanager.LoggerNode.<init>(LoggerNode.java:91)
	at org.jboss.logmanager.LogContext.<init>(LogContext.java:81)
	at org.jboss.logmanager.LogContext.<clinit>(LogContext.java:40)
	at org.jboss.logging.JBossLogManagerProvider.doGetLogger(JBossLogManagerProvider.java:89)
	at org.jboss.logging.JBossLogManagerProvider.getLogger(JBossLogManagerProvider.java:55)
	at org.jboss.logging.LoggerProviders.logProvider(LoggerProviders.java:152)
	at org.jboss.logging.LoggerProviders.tryJBossLogManager(LoggerProviders.java:144)
	at org.jboss.logging.LoggerProviders.findProvider(LoggerProviders.java:80)
	... 15 more

### Version

22.0.4

### Expected behavior

Described in quarkus/README.md ， "Running from your IDE" work

### Actual behavior

throw exception

### How to Reproduce?

git clone https://github.com/keycloak/keycloak.git
cd quarkus
mvn -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
in IDEA IDE，run `org.keycloak.quarkus._private.IDELauncher`

**Comment by mabartos** [comment] 2023-10-13 14:07
I was able to reproduce the issue, moving out of triage.

**Comment by jonkoops** [comment] 2023-10-18 16:50
Possible duplicate of #19738 and #19679

**Closed** 2023-12-30 04:45 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native
