### ISSUE TITLE
Keycloak 24.0.3 pod not coming up due to error in tables when database is mysql

### ISSUE THREAD

**Issue by ankita2402** [keycloak/keycloak#29293] opened 2024-05-06 08:21 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

When keycloak pod is brought up, it fails due to database creation.
Database is mysql

logs of keycloak pod are
```
2024-05-03 18:58:01,473 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-05-03 18:58:01,508 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server
2024-05-03 18:58:01,509 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update datab
2024-05-03 18:58:01,509 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.Lie.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOom:
     Reason: liquibase.exception.DatabaseException: Table 'APPLICATION_DEFAULT_ROLES' already exists [Failed SQL: (1050) CREATEPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
2024-05-03 18:58:01,509 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table 'APPLICATION_DEFAULT_ROLES' already exists [Failed SQL: (1050) CREATEPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
2024-05-03 18:58:01,509 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for cgelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table 'APPLICATION_DEFAULT_ROLES' already exists [Failed SQL: (1050) CREATEPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
2024-05-03 18:58:01,509 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Table 'APPLICATION_DEF [Failed SQL: (1050) CREATE TABLE console_database.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARC
2024-05-03 18:58:01,509 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Table 'APPLICATION_DEF
2024-05-03 18:58:01,510 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the samerbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

After trying the workaround mentioned here 
https://github.com/keycloak/keycloak/issues/14265

Keycloak still errors out due to a diff issue , logs of which mentioned below 
```
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE console_database.REALM_DEFAULT_ROLES ADD PRIMARY KEY (REALM_ID, ROLE_ID)]
2024-05-06 06:54:04,269 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-3.4.0.xml::3.4.0::keycloak:
     Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE console_database.REALM_DEFAULT_ROLES ADD PRIMARY KEY (REALM_ID, ROLE_ID)]
2024-05-06 06:54:04,269 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE console_database.REALM_DEFAULT_ROLES ADD PRIMARY KEY (REALM_ID, ROLE_ID)]
2024-05-06 06:54:04,269 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Multiple primary key defined
2024-05-06 06:54:04,269 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak pod should come up successfully.

### Actual behavior

Keycloak pod fails

### How to Reproduce?

Bringup keycloak pod, using below arguments with kc.sh
`exec /opt/keycloak/bin/kc.sh start --http-enabled=true --http-port=8080 --hostname-strict=false --hostname-strict-https=false -Dkeycloak.profile.feature.step_up_authentication=disabled`

**Comment by ankita2402** [comment] 2024-05-06 12:05
can anyone please help and let me know if there is anything missing ??

**Comment by shawkins** [comment] 2024-05-06 19:40
Duplicate of #23268

**Closed by shawkins** 2024-05-06 19:40 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
