### ISSUE TITLE
Support for unmatching context-paths with reverse proxys

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#16348] opened 2023-01-10 06:58 UTC
### Description

Please add support for `X-Forwarded-Prefix` header.  This can be used in cases in which the context-path of the reverse proxy differs from keycloaks context-path:

```
apache2:  https://apache2/keycloak
keycloak: https://keycloak/
```

which would require the reverse proxy to pass the information about the context-path "/keycloak" to the server

spring for instance does solve this problem by setting the following two configuration params:

```properties
# used to resolve the headers:  X-Forwarded-Server, X-Forwarded-Proto, X-Forwarded-Port
server.use-forward-headers=true

# used to resolve the header: X-Forwarded-Prefix
server.forward-headers-strategy=framework
```

**Comment by jwgmeligmeyling** [comment] 2023-10-12 08:49
Have you tried setting "Frontend URL" on the Realm settings? It turned out that I didn't even need the proxy settings to get the frontend facing endpoints to work behind a proxy.

**Comment by pnowy** [comment] 2024-06-19 11:57
Well - I have a use-case where the support of `X-Forwarded-Prefix` would be very useful.

So we have a docker-compose for some internal development + we use that stack also for some integration tests.

We have a following setup:

- UI handled on `/` of proxy (and keycloak realm detected on browser using the same domain as current UI but with added suffix `/sso`)
- Keycloak handled on `/sso` of proxy
- some backend clients running within docker-compose network

When we set `KC_HOSTNAME` (and strict mode) and we want to use port-forward for localhost development then we have localhost / docker network naming issues.

Without strict mode to make it working on the nginx proxy level we have to set keycloak relative path to `/sso` and add rewriting because otherwise the frontend client receive on the proxy realm address without `/sso`.

The only solution for now which I found with that kind of setup was just set keycloak on relative path `/sso`. If we would like to avoid that relative path for Keycloak and just use `X-Forwarded-Prefix` + rewrite on proxy level that would be nice in use-cases like this.

**Comment by Captain-P-Goldfish** [comment] 2024-09-25 17:48
I am getting the following result if I do this. 

![not-loading](https://github.com/user-attachments/assets/fd912755-bca0-4f5d-a62d-e31ae8178ee9)


here is my configuration:

hosts file on windows
```
127.0.0.1 webadmin
127.0.0.1 sck
```

keycloak.conf
```
hostname-strict=false
https-port=8444

proxy-headers=xforwarded

hostname=https://sck:10443/login
hostname-admin=https://webadmin:10443/login
```

apache2 httpd-vhosts.conf
```
   <Location /login/ >
        ProxyPass https://192.168.178.38:8444/
        ProxyPassReverse https://192.168.178.38:8444/
    </Location>
```

**Comment by shawkins** [comment] 2024-09-25 18:24
Which version of keycloak are you using?

I can't make out from the image what is wrong with the request - are you getting a response, and if so, what response code?

> apache2 httpd-vhosts.conf

Can you verify that it is setting the xforwarded headers?

Also note that for keycloak 25+ hostname-strict is ignored if hostname is set.

**Comment by Captain-P-Goldfish** [comment] 2024-09-25 19:25
this was Keycloak 25.0.5

**Comment by Captain-P-Goldfish** [comment] 2024-09-25 19:30
I used KC 25.0.5 and yes the headers are present as proven by the following screenshot:

![http-headers](https://github.com/user-attachments/assets/662ed658-76dd-4b7d-8908-96dbfcc02e77)

**Comment by shawkins** [comment] 2024-09-25 19:51
I can't make out from the image what is wrong with the request - are you getting a response, and if so, what response code?

My understanding from your proxy configuration is that a request to https://sck/login/realms... should go to keycloak as https://192.168.178.38:8444/realms... - and it does appear you have the server setup to respond to that.

> I also tried X-Forwarded-Prefix=login with the same result

Yes, it is currently unused by Keycloak.

**Comment by Captain-P-Goldfish** [comment] 2024-09-25 22:36
I do not consider it a serious problem I just wanted to mention that Keycloak is not loading the webadmin if Keycloak and reverse-proxy use different context-paths. 
This can be easily fixed by using the `hostname-path=/login` property in this specific case. Everything works fine then. But without it it is simply not loading the admin-console.
Also shouldn't the webadmin js not be loaded by the `hostname-admin` url instead of the `hostname`-url?

**Comment by shawkins** [comment] 2024-09-26 01:22
> I do not consider it a serious problem I just wanted to mention that Keycloak is not loading the webadmin if Keycloak and reverse-proxy use different context-paths.

It is expected that the hostname or hostname-admin account for the proxy using a different context path than keycloak.

> This can be easily fixed by using the hostname-path=/login property in this specific case.

hostname-path is deprecated in KC 25 and can only be used with the hostname v1 feature enabled. For KC 25 and later you are expected to specify the path as part of the hostname or the hostname-admin.

> Everything works fine then

Presumably this true when specifying the path as part of the hostname and hostname-admin as well correct?

> Also shouldn't the webadmin js not be loaded by the hostname-admin url instead of the hostname-url?

For hostname v2 you mean hostname, not hostname-url correct? 

It is expected that anything that relative to admin/ should use hostname-admin, and everything else to use hostname. However there have been several issues addressed in keycloak recently where the wrong base url was being used by the console, so it may matter which js you are talking about specifically.

**Comment by shawkins** [comment] 2024-09-26 13:28
We can continue the discussion, but I believe this issue has to be rejected. We form urls to the admin from places like the welcome page, and links to realms from the admin. If the path information is only coming from proxy header we will not know how to form these links. 

cc @vmuzikar - in the scenario where the user has set hostname-admin, but is using just a simple hostname - this means that realm links formed from the admin console will have the port, path, and protocol of the admin console (confirmed on main). This seems potentially confusing - should it be covered by the docs, and/or a log like what is being proposed for #33261, or should we simply require a full hostname url if you are using hostname-admin?

**Comment by shawkins** [comment] 2024-09-27 13:23
Based upon the previous comment, marking as resolved. At least currently to handle situations like this you to set the hostname to a full url, and possibly hostname-admin as well. If you want to have a discussion about also supporting even more scenarios via proxy prefix support please open a discussion.

**Closed by shawkins** 2024-09-27 13:23 UTC
Labels: kind/feature, team/cloud-native, status/triage

**Comment by Captain-P-Goldfish** [comment] 2024-09-28 17:42
I need to ask. Have you really tried this yourself? And if, what exactly did you configure to make it work?
I personally have no absolute need to make it work like that because I can always configure a new sub-domain which also feels more natural.
But to get back to the topic:
I am attaching a zip containing my test-apache2 docker file with resources. Please try this one with the configuration from above and please do not forget to enter your local IP into the `httpd-vhosts.conf` file. Then try to access the admin-console and you will see that it is not working.

[apache.zip](https://github.com/user-attachments/files/17175699/apache.zip)

I repeat the config from above here:

```
127.0.0.1 webadmin
127.0.0.1 sck
```

keycloak.conf
```
hostname-strict=false
https-port=8444

proxy-headers=xforwarded

hostname=https://sck:10443/login
hostname-admin=https://webadmin:10443/login
```

apache2 httpd-vhosts.conf
```
   <Location /login/ >
        ProxyPass https://192.168.178.38:8444/
        ProxyPassReverse https://192.168.178.38:8444/
    </Location>
```


as you can see, this configuration uses fully qualified URLs for the properties Hostname v2 `hostname` and `hostname-admin` as documented at https://www.keycloak.org/server/all-config.

**Comment by shawkins** [comment] 2024-09-28 19:17
> Have you really tried this yourself? And if, what exactly did you configure to make it work?

Yes, I am locally using fedora and already am running nginx, so I quickly verified that everything does work as expected.

With localhost4 also pointed to 127.0.0.1, I have keycloak configured with:

hostname=https://localhost:10443/login 
hostname-admin=https://localhost4:10443/login 
https-port=8444
proxy-headers=xforwarded

And the proxy configured for reencrypt with:

```
    server {
        listen       10443 ssl;
        server_name  localhost localhost4;
        http2        on;

        ssl_certificate "/etc/ssl/certs/nginx-selfsigned.crt";
        ssl_certificate_key "/etc/ssl/private/nginx-selfsigned.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers PROFILE=SYSTEM;
        ssl_prefer_server_ciphers on;
        
        location /login {
            proxy_pass        https://localhost:8444/;
            proxy_set_header  Host                 $proxy_host;
            proxy_set_header  X-Forwarded-Host     $host:$server_port;
            proxy_set_header  X-Forwarded-For      $proxy_protocol_addr;
            proxy_set_header  X-Forwarded-Proto    $scheme; 
        }
        
    }
```

> Then try to access the admin-console and you will see that it is not working.

Can you clarify what is not working?

**Comment by Captain-P-Goldfish** [comment] 2024-09-28 20:13
It is the `step1.html`-file that is not loaded anymore. I haven't debugged it so I cannot tell the exact reason why. But one thing is very strange there:

1. I opened Keycloak by calling `https://webadmin:10443/login`
2. The browser tries to load the page `step1.html` by calling the `hostname`-url `https://sck:10443/login/...`

Why is it not using `webadmin` as hostname?

You can see this behaviour in the screenshot above.

**Comment by Captain-P-Goldfish** [comment] 2024-09-28 20:31
just got it.
The specific problem here was that my browser was not yet trusting the self-signed certificate for hostname sck. That is why the call was blocked and timed out.
So the only big question in the room is why was it even calling `sck` instead of  `webadmin`? This at least seems to be a bug.

**Comment by shawkins** [comment] 2024-09-28 22:09
> So the only big question in the room is why was it even calling sck instead of webadmin? This at least seems to be a bug.

There likely is not a bug. If the url does not have the relative keycloak root of /admin, then it should be something that is accessible from the public frontend url. Can you confirm this is the case?

**Comment by Captain-P-Goldfish** [comment] 2024-09-29 09:15
I was assuming that the webadmin can be completely separated from the frontend but this does not seem to be the case. TokenEndpoint and AuthorizationEndpoint are also accessed under the `hostname`-url when loading the webadmin. Sure this makes sense somewhere, but I thought that we could separate these two instances by network without overlappings, and this was just a misjudgement from my side.

Thx. Everything is clarified now :-)
