### ISSUE TITLE
Support OAuth flow 'resource' parameter

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#13614] opened 2022-08-08 09:17 UTC
### Description

Based on OAUth specifications and current Keycloak implementation for audience, we propose a solution for all OAuth flow 'resource' parameter to be readen ( if exists) and validated. 'resource' parameter value MUST be an absolute URI and MUST NOT include a fragment. For Token Exchange no change will be made due to "audience" request parameter.

If request parameter exists( can be multiple), audience value will be the request parameter. Otherwise, 'audience default value' will be added. 'audience default value' is optionally configured per realm. Default value empty ( no migration needed). Protocol Mappers ( with scope parameter) can enhance aud parameter ( current upstream functionality).

### Motivation

We want to support [JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens](https://datatracker.ietf.org/doc/html/rfc9068) and [Resource Indicators for OAuth 2.0](https://datatracker.ietf.org/doc/html/rfc8707).

Keycloak now for audience ( except Token Exchange) has the Protocol Mappers that can be requested with scope parameter ( add value only).

**Comment by cgeorgilakis** [comment] 2022-08-09 09:48
[keycloak-admin-ui PR](https://github.com/keycloak/keycloak-admin-ui/pull/3084) has been also created.

**Comment by mposolda** [comment] 2022-11-23 15:10
@cgeorgilakis FYI. I've changed the title and the 1st paragraph of the description - I've changed `request` parameter with `resource` parameter as this issue (and your PR) is in fact about `resource` parameter.

The `request` parameter is also supported by current Keycloak, but it is something different (See for example https://openid.net/specs/openid-connect-core-1_0.html#RequestObject )

**Comment by cgeorgilakis** [comment] 2022-11-24 08:14
You are right about title. I will check PR comments soon.

**Comment by zachmann** [comment] 2023-04-05 08:12
I'm also very interested in seeing this supported. There is also an additional issue #14355 requesting support for RFC 8707.

As this is an RFC I see the described flow using the `resource` parameter as the standard way for a client to request ATs with a specific audience - out of token exchange.

@mposolda mentioned in  the linked PR that an implementation as a protocol mapper would be better. I must admit that I'm coming from the client side and am not familiar with the keycloak administration (even less with implementation). 
My question there would be how this would look from the client perspective: Would this be a configuration option for a client, i.e. enable RFC8707 for this client, and then the client can use the `request` parameter to indicate what should go into the `aud` claim of the AT?

**Comment by stianst** [comment] 2023-10-26 13:12
Closing this one as a duplicate of https://github.com/keycloak/keycloak/issues/14355

**Closed by stianst** 2023-10-26 13:12 UTC
Labels: kind/feature, area/core, help wanted, team/core
