### ISSUE TITLE
Dropdown options on Documentation pointing to 21.1 endpoint instead of latest and throwing 404 when clicking on it.

### ISSUE THREAD

**Issue by BrayanMnz** [keycloak/keycloak#19974] opened 2023-04-27 03:29 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

When on the documentation page, for example: https://www.keycloak.org/docs/latest/server_development/
and hovering the mouse over the _top left **Server Developer**_ dropdown, the options on the dropdown are redirecting to a path like this one _https://www.keycloak.org/docs/21.1/securing_apps/_ 

See the 21.1 on the version fragment of the uri, this should be latest I think.
if you click on it you'll see that it throws a 404

![image](https://user-images.githubusercontent.com/61812255/234752060-f349a8f0-0dc0-4bbb-ad7d-2203dd44f7e3.png)

### Version

latest

### Expected behavior

It should redirect to the correct page instead of throwing a 404

### Actual behavior

404 
![image](https://user-images.githubusercontent.com/61812255/234752375-63b301e6-b4f2-42ae-922a-c349f5f49134.png)

### How to Reproduce?

When on the documentation page, for example: https://www.keycloak.org/docs/latest/server_development/
and hovering the mouse over the _top left **Server Developer**_ dropdown, the options on the dropdown are redirecting to a path like this one _https://www.keycloak.org/docs/21.1/securing_apps/_

**Comment by BrayanMnz** [comment] 2023-04-27 03:33
I'm happy to submit a PR for this one, 
I was looking at the source code for the root cause of this but, I haven't identified it 
I think that it is related to the project_buildType variable not being set as _latest_. 

Any guidance for solving this would be appreciated, thanks!

**Comment by BrayanMnz** [comment] 2023-04-27 04:26
Apparently no code changes are needed here, 
looks like the issue is because documentation was not built using the **_latest_** profile 

https://github.com/keycloak/keycloak/blob/8367f8f3d3bbab44f29376206ff6da6de5715467/docs/documentation/pom.xml#L65

**Comment by stianst** [comment] 2023-04-27 09:49
This was a regression due to migrating the documentation repository to the main repository that changed the way we build the docs. If I remember correctly we used to build both a `latest` and a `release` version of the docs, which would have different links + also would mark the docs as latest in the top header. We'll need to figure out a new way of doing this as the new release process with the mono-repo doesn't really enable building two versions of the docs easily.

**Comment by stianst** [comment] 2023-04-27 10:00
@ahus1 FIY

**Comment by ahus1** [comment] 2023-04-27 11:45
@stianst - sorry that I've missed that. I see you assigned it to you ... feel free to assign it to me and I'll work on this from tomorrow?

**Comment by stianst** [comment] 2023-04-27 11:46
@ahus1 if you could handle it that'd be great. Was probably me that missed this not you 😉

**Comment by BrayanMnz** [comment] 2023-04-27 13:03
If you guys need any help, just add any helpful hint to this thread and I can take a look also. @ahus1 @stianst

**Comment by ahus1** [comment] 2023-04-27 13:51
@BrayanMnz - If you want to create a pull request with the necessary changes, go ahead. I still need to figure out what needs to change here. 

As an alternative I'd be happy for a reviewer once I have created one. If I don't hear from you I will start having a look on Monday the latest.

**Comment by ahus1** [comment] 2023-04-28 16:47
@stianst - I analyzed the current behavior, and this is what I found: 

* Starting from KC 19.0.0, we publish the patch releases of the docs, and not only the minor releases of the docs
* Starting from KC 20.0.0 onward, we use a symlink for "latest", which breaks the logic around  the link to the "lastest" docs in the header

Do we want to keep the functionality for "latest" vs. "archive", or would we rather drop it? It seems to be broken from KC 20.0.0 onward once the symlink was used. From then on, even the old version shows latest, see for example https://www.keycloak.org/docs/20.0.5/securing_apps/index.html

If we drop it, we could have it again once we migrate to a tool like Antora. Antora will re-render all the old docs with their AsciiDoc content when publishing. If we want to keep it, it could be solved by adding some JavaScript, which I'd rather not. 

So I'd like to go ahead and remove the "latest" vs. "archive" feature. Please confirm.

**Comment by ahus1** [comment] 2023-04-28 17:02
There are now two PR which will fix part of the problems: 

* https://github.com/keycloak-rel/keycloak-rel/pull/99
* https://github.com/keycloak/keycloak/pull/20035

**Comment by ahus1** [comment] 2023-05-03 08:55
PR to remove latest vs. archive from the document header: #20103

**Closed** 2023-05-03 09:16 UTC
Labels: kind/bug, area/docs, status/triage, team/other

**Comment by ahus1** [comment] 2023-05-03 09:24
Backport created: #20110

**Comment by ahus1** [comment] 2023-05-03 09:27
PR to fix the old docs created: https://github.com/keycloak/keycloak.github.io/pull/21
