### ISSUE TITLE
Flaky test: Model Tests DBLockTest 

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#15487] opened 2022-11-14 07:40 UTC
### Area

testsuite

### Describe the bug

DBLockTest is failing intermittently on GitHub Actions.

### Version

main

### Expected behavior

Test always pass

### Actual behavior

Test fails randomly

### How to Reproduce?

See test failures for more information:

* https://github.com/keycloak/keycloak/actions/runs/3457308991/jobs/5770727415
* https://github.com/keycloak/keycloak/actions/runs/3452341510/jobs/5762248007

**Comment by ahus1** [comment] 2022-11-14 10:56
Seeing a rather strange error in the logs ... how can H2 database be closed when it is being opened with DB_CLOSE_DELAY=-1?

> 23:24:37,601 WARN  [org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService] (Thread-13) Lock didn't yet acquired. Will possibly retry to acquire lock. Details: The database has been closed; SQL statement:
SELECT ID FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1001 FOR UPDATE [90098-214] [Failed SQL: (90098) SELECT ID FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1001 FOR UPDATE]

**Comment by ahus1** [comment] 2022-11-14 11:27
I traced down the calls when the DB is being created; nothing suspicious here. There's proper locking in place in H2's code that the first caller creates the database and the second thread would wait for it. 

I tried different variations on thread and concurrency, still wasn't able to reproduce it locally.

We has some strange behaviors when analyzing H2 problems in #15469 and might have found a workaround for that. Want to retry this one once that has been merged.

**Comment by ahus1** [comment] 2022-11-15 08:17
This test was still failing in #15469. Locally it is currently hard to reproduce; it failed once in 10.000 local iterations after 1.5 hours.

As this will take more time to analyze, the next step is to create a PR to disable this test until the cause of the instability is known.

**Comment by stianst** [comment] 2022-11-17 10:44
Last 7 days we've also had DBLockTest.testLockConcurrentlyGeneral fail 5 times

**Comment by stianst** [comment] 2022-11-17 10:45
```
============================================================================================================================================
Finding details for DBLockTest.testLockConcurrentlyGeneral
============================================================================================================================================
https://github.com/keycloak/keycloak/actions/runs/3485514883
/home/st/dev/gh/gh-logs/gh-actions-log-failed-3485514883

Model Tests	Run model tests	2022-11-17T05:27:29.3550576Z [ERROR]   DBLockTest.testLockConcurrentlyGeneral:112->KeycloakModelTest.inComittedTransaction:540->KeycloakModelTest.inComittedTransaction:553->KeycloakModelTest.lambda$inComittedTransaction$12:565->lambda$testLockConcurrentlyGeneral$4:113->testLockConcurrentlyInternal:181 expected:<40> but was:<1>
Model Tests	Run model tests	2022-11-17T05:46:18.5536400Z [ERROR]   DBLockTest.testLockConcurrentlyGeneral:112->KeycloakModelTest.inComittedTransaction:540->KeycloakModelTest.inComittedTransaction:553->KeycloakModelTest.lambda$inComittedTransaction$12:565->lambda$testLockConcurrentlyGeneral$4:113->testLockConcurrentlyInternal:181 expected:<40> but was:<1>
--------------------------------------------------------------------------------------------------------------------------------------------
https://github.com/keycloak/keycloak/actions/runs/3476545118
/home/st/dev/gh/gh-logs/gh-actions-log-failed-3476545118

Model Tests	Run model tests	2022-11-16T05:43:51.9506954Z [ERROR]   DBLockTest.testLockConcurrentlyGeneral:112->KeycloakModelTest.inComittedTransaction:540->KeycloakModelTest.inComittedTransaction:553->KeycloakModelTest.lambda$inComittedTransaction$12:565->lambda$testLockConcurrentlyGeneral$4:113->testLockConcurrentlyInternal:181 expected:<40> but was:<1>
Model Tests	Run model tests	2022-11-16T05:44:41.6212833Z [ERROR]   DBLockTest.testLockConcurrentlyGeneral:112->KeycloakModelTest.inComittedTransaction:540->KeycloakModelTest.inComittedTransaction:553->KeycloakModelTest.lambda$inComittedTransaction$12:565->lambda$testLockConcurrentlyGeneral$4:113->testLockConcurrentlyInternal:181 expected:<40> but was:<1>
--------------------------------------------------------------------------------------------------------------------------------------------
https://github.com/keycloak/keycloak/actions/runs/3473754384
/home/st/dev/gh/gh-logs/gh-actions-log-failed-3473754384

Model Tests	Run model tests	2022-11-15T20:40:48.1276925Z [ERROR]   DBLockTest.testLockConcurrentlyGeneral:112->KeycloakModelTest.inComittedTransaction:540->KeycloakModelTest.inComittedTransaction:553->KeycloakModelTest.lambda$inComittedTransaction$12:565->lambda$testLockConcurrentlyGeneral$4:113->testLockConcurrentlyInternal:181 expected:<40> but was:<1>
--------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by stianst** [comment] 2022-11-17 10:45
```
============================================================================================================================================
Finding details for DBLockTest.testLockConcurrentlyOffline
============================================================================================================================================
https://github.com/keycloak/keycloak/actions/runs/3457308991
/home/st/dev/gh/gh-logs/gh-actions-log-failed-3457308991

Model Tests	Run model tests	2022-11-13T23:26:32.8766902Z [ERROR]   DBLockTest.testLockConcurrentlyOffline:119->KeycloakModelTest.inComittedTransaction:540->KeycloakModelTest.inComittedTransaction:553->KeycloakModelTest.lambda$inComittedTransaction$12:565->lambda$testLockConcurrentlyOffline$5:120->testLockConcurrentlyInternal:179 expected:<40> but was:<1>
--------------------------------------------------------------------------------------------------------------------------------------------
https://github.com/keycloak/keycloak/actions/runs/3452341510
/home/st/dev/gh/gh-logs/gh-actions-log-failed-3452341510

Model Tests	Run model tests	2022-11-12T20:44:04.9410666Z [ERROR]   DBLockTest.testLockConcurrentlyOffline:119->KeycloakModelTest.inComittedTransaction:540->KeycloakModelTest.inComittedTransaction:553->KeycloakModelTest.lambda$inComittedTransaction$12:565->lambda$testLockConcurrentlyOffline$5:120->testLockConcurrentlyInternal:179 expected:<40> but was:<1>
--------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ahus1** [comment] 2022-12-16 16:16
Created an upstream issue with H2: https://github.com/h2database/h2database/issues/3695

**Closed** 2022-12-20 07:50 UTC
Labels: area/testsuite, kind/bug, area/storage, flaky-test
