### ISSUE TITLE
Add MSAL4J as a dependency to fix Workload Identity authentication with Azure

### ISSUE THREAD

**Issue by tete17** [keycloak/keycloak#22830] opened 2023-08-30 15:30 UTC
### Description

I am in the process of setting up a keycloak instance for my company.

In the process, I want to leverage [Workload Identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet) in our AKS cluster to avoid having to setup any db credentials in the app. This system uses the native k8s service accounts to authenticate against Azure Active Directory which then issues a token that most Azure services can use to authenticate.

I am using the bitnami helm chart, which technically only supports postgress but I managed to hack it a bit to accept my mssql url as follows:
```
jdbc:sqlserver://{{REDACTED}}.database.windows.net:1433;database=keycloak;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;Authentication=ActiveDirectoryDefault;
```

When I enable verbose logging I get the following logs
```
2023-08-30 15:00:34,191 FINE  [com.microsoft.sqlserver.jdbc.internals.SQLServerException] (agroal-11) *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to load MSAL4J Java library for performing ActiveDirectoryManagedIdentity authentication. Failed to load MSAL4J Java library for performing ActiveDirectoryManagedIdentity authentication.
```

Like the log suggest I think this is because keycloak doesn't have an explicit dependency to [Msal4j](https://mvnrepository.com/artifact/com.microsoft.azure/msal4j), the library that performs the Azure Active Directory Authentication. At least I couldn't find a reference in the `pom.xml` (I am not a java developer so I may be miss reading the file anyway).

Depending on the jdbc driver the [documentation requires different versions of the library](https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#client-setup-requirements). I couldn't find the specific version of the driver keycloak uses. In my case I use the [bitnami container for keycloak](https://github.com/bitnami/containers/blob/main/bitnami/keycloak/22/debian-11/Dockerfile) which doesn't seem to me to override any dependency.

Some references:
 * [Microsoft docs for jdbc](https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#connect-using-activedirectorydefault-authentication-mode)
 * [Similar issue with the solution](https://help.mulesoft.com/s/article/Database-Connector-Failed-to-load-MSAL4J-Java-library-for-performing-ActiveDirectoryPassword-authentication-error-when-connecting-to-Azure-SQL-Server)

### Discussion

https://keycloak.discourse.group/t/how-to-setup-a-workload-identity-token-access-on-aks-to-allow-keycloak-access-on-azure/22208

### Motivation

Worklad identity is a really neat tool that allows one to skip setting up credentials and enhancing the security & auditability of a system.

Google has gone through a very similar route since it based in open standards like oauth2 and jwt. 

### Details

I think is just a matter of adding
```
<dependency>
<groupId>com.microsoft.azure</groupId> 
<artifactId>msal4j</artifactId> 
<version>1.11.3</version> 
</dependency>
```

to the pom.xml but I can't be sure

**Comment by danieltoth55** [comment] 2023-09-11 09:06
This would be great if it worked, we use the same setup and would love to see this added.

**Comment by sschu** [comment] 2023-09-11 09:28
@tete17 Have you tested that it works? I would assume it is not that simple. Quarkus goes some way to disable all the functionality related to Azure AD in the MS SQL JDBC driver because they cannot really test it. So I would be surprised if it was as easy as just adding that dependency. But you could try, just build your own Keycloak distribution and see if it works...

**Comment by tete17** [comment] 2023-09-11 17:42
I haven't

I am not familiar with java but I can try to sneak out some this month to familiarise myself.

I suspect maybe it just works since the problem seems to be at the stage where they load the module rather than quarkus blocking the auth method but I don't know.

@danieltoth55 are you more familiar with java?

**Comment by tete17** [comment] 2023-09-11 18:43
I think it should be fine.

Azure even has a tutorial with Quarks https://learn.microsoft.com/en-us/azure/container-apps/tutorial-java-quarkus-connect-managed-identity-postgresql-database?tabs=flexible

**Comment by sschu** [comment] 2023-09-12 06:06
> I think it should be fine.
> 
> Azure even has a tutorial with Quarks https://learn.microsoft.com/en-us/azure/container-apps/tutorial-java-quarkus-connect-managed-identity-postgresql-database?tabs=flexible

But that is for PostgreSQL and they even use a special library for that: `azure-identity-providers-jdbc-postgresql`.

**Comment by bertcarels** [comment] 2023-09-12 11:41
also interested in this.
in my view the dependencies should be added to the quarkus jdbc mssql extension 
 
 I tested it by adding 2 dependencies in pom.xml
 here: https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/pom.xml
 
 current quarkus distribution used by keycloak comes with mssql jdbc driver 12.2
 
as documented here:
https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#client-setup-requirements

the following dependencies will allow authentication to mssql using 
a) service principal (msal4j) 
b) ma,aged identity (azure identity)
 
 <dependency>
     <groupId>com.microsoft.azure</groupId> 
     <artifactId>msal4j</artifactId> 
     <version>1.13.3</version> 
</dependency>


<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
    <version>1.7.0</version>
    <scope>compile</scope>
</dependency>


I tested this and rebuild keycloak.
Deployed it on Azure AKS and tested with both service principal configuration and managed identity (pod managed identies, didn't test workload identity)



I believe these dependencies need to be added in the quarkus mssql jdbc extension.

**Comment by bertcarels** [comment] 2023-09-12 11:53
reference to quarkus issue:
https://github.com/quarkusio/quarkus/issues/34580

**Comment by tete17** [comment] 2023-11-07 10:00
@sschu  it seems the issue in quarks side has stale a bit. They don't seem to be willing to pull in those dependencies as of now. I personally don't agree but not much I can do.

Would you accept a MR adding the 2 dependencies with a comment to remove them if the ever land upstream? It would be a nice addition to the keycloak project.

**Comment by sschu** [comment] 2023-11-07 15:07
That's not up to me to decide but I will bring this up for discussion.

**Comment by avekrivoy** [comment] 2023-11-15 09:56
> also interested in this. in my view the dependencies should be added to the quarkus jdbc mssql extension
> 
> I tested it by adding 2 dependencies in pom.xml here: https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/pom.xml
> 
> current quarkus distribution used by keycloak comes with mssql jdbc driver 12.2
> 
> as documented here: https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#client-setup-requirements
> 
> the following dependencies will allow authentication to mssql using a) service principal (msal4j) b) ma,aged identity (azure identity)
> 
> ```
>  <dependency>
>      <groupId>com.microsoft.azure</groupId> 
>      <artifactId>msal4j</artifactId> 
>      <version>1.13.3</version> 
> </dependency>
> 
> 
> <dependency>
>     <groupId>com.azure</groupId>
>     <artifactId>azure-identity</artifactId>
>     <version>1.7.0</version>
> </dependency>
> ```
> 
> I tested this and rebuild keycloak. Deployed it on Azure AKS and tested with both service principal configuration and managed identity (pod managed identies, didn't test workload identity)
> 
> I believe these dependencies need to be added in the quarkus mssql jdbc extension.

is it possible to add these dependencies straight to the existing keycloak container? I tried to add jar files to the /opt/keycloak/lib/lib/main/ on the docker build stage but it didn't work

**Comment by avekrivoy** [comment] 2023-11-15 11:18
Managed to get this working by adding jar dependencies into the /opt/keycloak/providers directory and running /opt/keycloak/bin/kc.sh build command afterwards

https://github.com/keycloak/keycloak/blob/190dade456ab97cdbd7c2f2fc2bca03f457bed5e/docs/guides/server/containers.adoc#writing-your-optimized-project_name-dockerfile

**Comment by urbantz-technical-support** [comment] 2023-11-15 12:52
@avekrivoy can you share the dockerfile please?

**Comment by sschu** [comment] 2023-11-15 12:52
@avekrivoy Which means you can get this to work by just building your own image?

**Comment by avekrivoy** [comment] 2023-11-15 13:34
@urbantz-technical-support @sschu 

I'm not sure if this is the right way to do this, but I solved it with a multistaged build. 
On the first stage I download additional dependencies specified in pom.xml using maven container. 
On the second stage I copy dependencies into the keycloak container and build an updated version of app using  /opt/keycloak/bin/kc.sh build command. Pay attention to the env variables defined in the Dockerfile. When building a custom image seems like you have to specify some of the variables there. At least they didn't work for me when I specified them at runtime using operator deployment.
On the third stage I copy app code to a new keycloak container. Not sure why, but keycloak's docs suggest this approach. I think it can be done in two stages in general. 

On app startup I've noticed a warning, but I think it's related to a logging
```
SLF4J: The requested version 2.0.6 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
```

I'm new to keycloak, though, and appreciate any improvements to the process

Dockerfile: 
```
ARG APP_SOURCE_REPO
ARG APP_VERSION

FROM maven:3.8-eclipse-temurin-17-alpine as dependency-builder
COPY pom.xml pom.xml
RUN mvn dependency:copy-dependencies -DoutputDirectory=/tmp/dependencies

FROM ${APP_SOURCE_REPO}:${APP_VERSION} as builder
COPY --from=dependency-builder /tmp/dependencies/* /opt/keycloak/providers/

WORKDIR /opt/keycloak

ENV KC_DB=mssql
ENV KC_TRANSACTION_XA_ENABLED=false
ENV KC_METRICS_ENABLED=true
ENV KC_HEALTH_ENABLED=true

RUN /opt/keycloak/bin/kc.sh build

FROM ${APP_SOURCE_REPO}:${APP_VERSION}
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
APP_SOURCE_REPO is quay.io/keycloak/keycloak
APP_VERSION is 22.0.5

pom.xml:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>com.custom.keycloak</groupId>
  <artifactId>keycloak-dependencies</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>

  <name>Keycloak dependencies</name>
  <url>http://maven.apache.org</url>

  <dependencies>
    <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>msal4j</artifactId>
        <version>1.13.3</version>
    </dependency>
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-identity</artifactId>
        <version>1.7.0</version>
    </dependency>
  </dependencies>

</project>
```

Finally, you need to enable proxy container for a managed identity, since Keycloak itself is not aware of workload identity.
I'm using keycloak operator, so the way to do this is to add an "unsupported" field, which allows to inject the necessary annotations, labels and other pod fields like service account name

```
  unsupported:
    podTemplate:
      metadata:
        labels:
          azure.workload.identity/use: "true"
        annotations:
          azure.workload.identity/inject-proxy-sidecar: "true"
      spec:
        serviceAccountName: keycloak
```
Of course, on top of this you should have a properly configured service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "123213213-213123123-123123213-123123"
```

**Comment by sschu** [comment] 2023-11-15 17:17
@avekrivoy Very cool, thanks! I'll give this a try.

**Comment by ioemat** [comment] 2023-12-15 08:45
Thanks for sharing @avekrivoy, I can confirm that this works :).

In my case (not using the keycloak operator, but running it in a statefulset), the annotation

```
azure.workload.identity/inject-proxy-sidecar: "true"
```

produced an error at pod startup. This may be related to our setup. Removing this annotation fixed the issue, so this is probably not required in all cases.

To fix the warnings, just exclude the slf4j artifacts from the dependencies in your pom.xml:

````
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">

<modelVersion>4.0.0</modelVersion>

 <groupId>com.custom.keycloak</groupId>
  <artifactId>keycloak-dependencies</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>

  <name>Keycloak dependencies</name>
  <url>http://maven.apache.org</url>  <dependencies>
    <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>msal4j</artifactId>
        <version>1.13.8</version>
        <exclusions>
            <exclusion>
                <artifactId>slf4j-api</artifactId>
                <groupId>org.slf4j</groupId>
            </exclusion>
        </exclusions>
    </dependency>
    
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-identity</artifactId>
        <version>1.8.1</version>
        <exclusions>
            <exclusion>
                <artifactId>msal4j-persistence-extension</artifactId>
                <groupId>com.microsoft.azure</groupId>
            </exclusion>
            <exclusion>
                <artifactId>slf4j-api</artifactId>
                <groupId>org.slf4j</groupId>
            </exclusion>
        </exclusions>
    </dependency>
  </dependencies>

</project>
````

**Comment by sschu** [comment] 2023-12-15 10:40
If I get this right, this annotation is only there for migration purposes from the old pod identities, see https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity#deploy-the-workload-with-migration-sidecar.

**Comment by avekrivoy** [comment] 2023-12-15 11:08
> If I get this right, this annotation is only there for migration purposes from the old pod identities, see https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity#deploy-the-workload-with-migration-sidecar.

Correct. In my case Keycloak failed to obtain an auth token without this annotation

**Comment by sschu** [comment] 2024-01-02 13:24
Since there is a way to make this work with Keycloak without adding additional dependencies, I will go ahead and close this issue. Thanks again @avekrivoy for finding out how this works!

**Closed by sschu** 2024-01-02 13:24 UTC
Labels: kind/enhancement, status/triage

**Comment by tete17** [comment] 2024-01-02 18:28
@sschu I would disagree with your assessment.

@avekrivoy clearly showed you do need to add these dependencies.
It is a very unstable solution that doesn't work unless you rebuild your images from scratch which is not very ergonomic. Myself, as a user of the helm chart of bitnami is simply not feasible not practical. 

I am okay if the decision is still not to add the dependencies because they add to much bloat to the existing package but the solution does need to add the dependencies.

**Comment by XcrigX** [comment] 2024-12-06 20:35
For anyone coming across this, I believe you also have to align the SQL driver version to the Azure identity version. 

https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#connect-using-activedirectorymanagedidentity-authentication-mode

For example, keycloak 26.0.7 uses mssql-jdbc.version 12.8.1.jre11. 
So the Azure identity library would need to be 1.12.2. 

You have to be careful also with the Azure libraries overriding dependency versions used by keycloak/quarkus. I had to explicitly import the Quarkus bom in my custom keycloak extensions project (in the dependencyManagement section) so the versions specified in the BOM would take precedence. (Had a problem with azure importing an older version of netty which broke keycloak).

It's fairly brittle to maintain to this way..
