### ISSUE TITLE
Console Realm Creation Results in User Creation and Other Screens Showing Errors

### ISSUE THREAD

**Issue by reoring** [keycloak/keycloak#19053] opened 2023-03-16 01:48 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

When creating a realm with the name "console" in Keycloak, screens related to user creation and other functionalities are resulting in errors. This makes it difficult to manage users and perform various tasks within the realm.

### Version

20

### Expected behavior

The user creation and management screens should work seamlessly, allowing administrators to manage users and perform necessary tasks within the "console" realm.

### Actual behavior

The user creation and management screens are displaying errors, making it impossible to create or manage users within the "console" realm.

### How to Reproduce?

1. Log in to Keycloak administration console.
2. Click on the "Add Realm" button.
3. Enter "console" as the realm name, and click on the "Create" button.
4. Navigate to the "Users" tab and attempt to create or manage users.

**Comment by mposolda** [comment] 2023-04-18 13:06
I am adding to Backlog as this is corner case and Keycloak team won't have time to prioritize this in the near future.

Anyone is welcome to send PR with the fixes for this. See https://www.keycloak.org/community how to contribute to Keycloak

**Comment by pedroigor** [comment] 2024-03-04 20:59
Several issues were fixed in user management and the latest release also includes the declarative user profile. Please, make sure the issue is still valid in the latest release.

**Closed** 2024-03-18 21:04 UTC
Labels: kind/bug, area/admin/api, team/core-iam, status/auto-expire, status/expired-by-bot
