### ISSUE TITLE
after upgrade to 22.0.5, fields not listed on profile are shown on registration form and required when updating profile

### ISSUE THREAD

**Issue by wojmaz** [keycloak/keycloak#24629] opened 2023-11-08 12:05 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

we have a profile with few attributes added, and firstName and lastName deleted. 
It used to work properly in previous versions (22.0.1), after upgrading to 22.0.5 the Registration Form now includes those two fields (First Name, Last Name), and they are also treated as Required. 

### Version

22.0.5

### Expected behavior

removed default fields should not be required

### Actual behavior

removed default fields are still shown and required; that behavior is different than in previous versions

### How to Reproduce?

create new realm, enable profile and self-registration. 
Remove attribute fistName from profile.
Go to registration page, obseve that the the field is still in the registration form and it's required.
<img width="343" alt="image" src="https://github.com/keycloak/keycloak/assets/31618135/6828e540-9796-40e4-9a88-5738239116ea">

<img width="289" alt="image" src="https://github.com/keycloak/keycloak/assets/31618135/d0fe2472-b4ae-46f1-9d30-39b8091ac138">

### Anything else?

there is a nonintuitive workaround - if you recreate the field in the profile with the same name and make it non required, the effect is actually hiding the field on the registration form. Default field (created when switching the option on) must be deleted and then recreated, simply switching the Required to off does not work (or rather, works as it should - makes the filed still visible, but not required). 
I'm not sure what the effect is on the actual saved attributes

**Comment by rmartinc** [comment] 2023-11-08 12:33
I think this is a duplicate of https://github.com/keycloak/keycloak/issues/24420. It will be fixed in next 22.0.6 version. Closing this ofr the moment.

**Closed by rmartinc** 2023-11-08 12:33 UTC
Labels: kind/bug, area/user-profile, status/triage, team/core
