### ISSUE TITLE
RealmResourceProvider is not working as expected since version 23.0.0

### ISSUE THREAD

**Issue by zak905** [keycloak/keycloak#25882] opened 2024-01-03 20:02 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After upgrading to version 23.0.0, I noticed that a custom RealmResourceProvider that I am implementing and deploying as  an extension is misbehaving:
- instead of returning the HTTP 200 OK response I am expecting (which is also the case if I downgrade to some version prior to 23.0.0), it is returning the following:
```
Status: HTTP 405
Response body:  {"error":"HTTP 405 Method Not Allowed"}
```
- I double checked that the method I am using from curl and also from the app matches the annotation on my custom resource (the resource returned from the `getResource()` method in `RealmResourceProvider`), and the method is the same, so I figured this could be due to some Quarkus issue. 
After I activated the debug logging, it turns out the issue is happening at the level of the `quarkus-resteasy-reactive` library. Here is the stack trace:
```
2024-01-03 19:04:09,555 DEBUG [org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext] (executor-thread-1) Restarting handler chain for exception exception: jakarta.ws.rs.WebApplicationException: HTTP 405 Method Not Allowed
	at org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler.handle(ResourceLocatorHandler.java:71)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-01-03 19:04:09,555 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Error response 405: jakarta.ws.rs.WebApplicationException: HTTP 405 Method Not Allowed
	at org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler.handle(ResourceLocatorHandler.java:71)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

The error is happening here  https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java#L70. I also did some debugging and it seems like for some reason the resource class is not found by the method findTarget here https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java#L97 

I was not able to reproduce the error on a plain standalone quarkus (version 3.2.9.Final which is the one used here by Keycloak) project:

```
@Path("/hello")
public class GreetingResource {

    @Path("{lang}")
    public Object hello(@PathParam("lang") String lang) {
        if ("fr".equals(lang)) {
            return new BonjourResource();
        } 
        
        return new HalloResource();
    }

    static class HalloResource{

        @Produces(MediaType.TEXT_PLAIN)
        @GET
        public String hallo() {return "Hallo from RestEasy";}
    }

    static class BonjourResource{

        @GET
        @Produces(MediaType.TEXT_PLAIN)
        public String hallo() {return "Bonjour from RestEasy";}
    }
}
``` 

Everything works as expected with the above, so this could be due to some misconfiguration in the current Keycloak version. 

The only solution I found was to annotate my resource class with `@Provider`.
 

### Version

23.0.3

### Expected behavior

Let's assume, I am using the official Keycloak example https://github.com/keycloak/keycloak/tree/main/examples/providers/rest. 

After deploying it, I would expect  a GET HTTP call to `/realms/test/hello` to return 200 with `"Hello test"` (given that the realm name is test)

### Actual behavior

I am getting a HTTP 405 status with the following response:

```
{"error":"HTTP 405 Method Not Allowed"}
```

unless https://github.com/keycloak/keycloak/blob/main/examples/providers/rest/src/main/java/org/keycloak/examples/rest/HelloResourceProvider.java is annotated with `@Provider`

### How to Reproduce?

To reproduce the issue, the keyloak official rest provider example needs to packaged and deployed in the `providers/` folder of a local running Keycloak distribution. After restarting it, a realm needs to be created and then   `curl http://localhost:8080/realms/test/hello` should return the response mentionned above. 

The issue can also be reproduced on my api key demo project https://github.com/zak905/keycloak-api-key-demo by:
- cloning the project
- removing or commenting the `@Provider` annotation from the resource class https://github.com/zak905/keycloak-api-key-demo/blob/master/api-key-module/src/main/java/com/gwidgets/resources/ApiKeyResource.java#L11
- running the following in a shell: `mvn -f api-key-module package && docker-compose up auth-server`
- finally running from a different terminal `curl -v "localhost:8080/auth/realms/example/check"`

**Comment by Andy-Voigt** [comment] 2024-01-04 12:43
We have the same issue in our keycloak. Any news to this?

**Comment by jordillachmrf** [comment] 2024-01-05 12:08
related to https://github.com/keycloak/keycloak/issues/17891 ?

**Comment by zak905** [comment] 2024-01-06 21:47
Indeed, it's seems related. 
I just went through the upgrading guides https://www.keycloak.org/docs/latest/upgrading/index.html#upgrading-your-custom-jax-rs-resources, and they mention that an empty file named `beans.xml` should be added under META-INF otherwise the JAX-RS resource configured in RealmResourceProvider won't be found in the classpath and the error above will be returned. However, there is no mention that `@Provider` annotation can also solve the issue. 
@pedroigor what do you think ? should we update the docs to mention the `@Provider` annotation as an alternative solution as well ?

**Comment by pedroigor** [comment] 2024-01-08 11:36
@zak905 Sure, we can update the docs. Perhaps we should update https://www.keycloak.org/docs/23.0.3/server_development/#_extensions_rest to mention both `beans.xml` and `Provider` annotation?

**Comment by zak905** [comment] 2024-01-08 12:39
Good idea. I can do that.

**Comment by pedroigor** [comment] 2024-01-08 14:23
@zak905 I appreciate it. Will ask for a review once you have the PR ready.

**Comment by Scorpion1091** [comment] 2024-01-15 13:54
the more advanced example in `providers/domain-extension` still have this issue

any suggestions how to solve it there?

**Comment by Scorpion1091** [comment] 2024-01-15 13:54
the more advanced example in `providers/domain-extension` still have this issue

any suggestions how to solve it there?

**Comment by pedroigor** [comment] 2024-01-15 14:03
@Scorpion1091 The same change you did to `providers/rest` should work, no?

**Comment by Scorpion1091** [comment] 2024-01-15 14:08
No.
for providers/rest I just added the `@Path("")` Annotation to the GET Endpoint of HelloResourceProvider to get it working.

in providers/domain-extention all Endpoints already have a @Path-Annotation 


I tryed adding a @Provider-Annotation to the CompanyResource-Class but still getting the 405

**Comment by pedroigor** [comment] 2024-01-15 14:10
@Scorpion1091 Ahh right, it is probably because there is no `META-INF/beans.xml` or `@Provider` annotation set?

**Comment by Scorpion1091** [comment] 2024-01-15 14:16
that's want I thougth but looking at the examples shows:

- `providers/rest` has no `META-INF/beans.xml` and no `@Provider` but works
- `provider/domain-extention` has also no `META-INF/beans.xml` and no `@Provider` but doesn't works
- adding `@Provider` to `HelloResourceProvider` of provider/domain-extention doesn't change anything... still not working

**Comment by Scorpion1091** [comment] 2024-01-15 14:16
that's want I thougth but looking at the examples shows:

- `providers/rest` has no `META-INF/beans.xml` and no `@Provider` but works
- `provider/domain-extention` has also no `META-INF/beans.xml` and no `@Provider` but doesn't works
- adding `@Provider` to `HelloResourceProvider` of provider/domain-extention doesn't change anything... still not working

**Comment by pedroigor** [comment] 2024-01-15 14:26
Humm ... I'll need to take a closer look then ...

**Comment by zak905** [comment] 2024-01-15 22:45
@Scorpion1091 the example is being updated in this PR #26149

> providers/rest has no META-INF/beans.xml and no @Provider but works

Before I submitted the PR, I have tested `providers/rest` thoroughly, and it is returning the mentioned error 405. Adding `beans.xml` or `@Provider` fixes indeed the issue.

**Comment by Scorpion1091** [comment] 2024-01-16 07:11
@zak905 yes for `providers/rest` we have 3 possible Solutions
- create an empty META-INF/beans.xml
- add an empty `@Path("")` Annotation to the GET-Endpoint
- or add `@Provider` Annotation to the HelloResourceProvider-Class

All three are working for `providers/rest` but none of them is working for the more complex example `providers/domain-extention`

So how do we get the `providers/domain-extention` working again?

**Comment by pedroigor** [comment] 2024-01-16 14:24
@Scorpion1091 I gave it a try and the issue is that:

* The server won't recognize entities within any package starting with `org.keycloak`. See https://github.com/keycloak/keycloak/blob/main/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L353. This is because the core entities are resolved from the server's default persistence unit and we don't want Quarkus dynamically resolving those entities from the index.
* In order to fix the problem, you need to move the `Company` entity class to a package other than `org.keycloak.*`. Perhaps, changing all packages in that example to `org.acme`.

The JAX-RS endpoint should work fine after that as it won't fail when querying the custom entity.

**Comment by Scorpion1091** [comment] 2024-01-17 07:01
ahhh thanks @pedroigor that indeed solved the issue 👍

**Comment by zak905** [comment] 2024-01-25 07:48
@pedroigor FYI, the CRs have been addressed and PR is approved.

**Closed** 2024-02-07 12:32 UTC
Labels: kind/enhancement, priority/important, area/core, area/docs, team/core

**Comment by vovean** [comment] 2024-10-26 22:16
Hi everyone

I'm currently trying to create a custom handler for my project and I am facinf the 405 status once again.
I tried all combinations of 1) adding empty beans.xml 2) adding jakarta.ws.rs.ext.Provider annotation.

Here is my code below

```java
package my.package

import org.jboss.logging.Logger;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.RealmModel;
import org.keycloak.models.UserModel;
import org.keycloak.services.resource.RealmResourceProvider;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.util.List;

import jakarta.ws.rs.ext.Provider;

@Provider
public class CustomAdminRestResourceProvider implements RealmResourceProvider {

    private final KeycloakSession session;
    private static final Logger log = Logger.getLogger(CustomAdminRestResourceProvider.class);

    public CustomAdminRestResourceProvider(KeycloakSession session) {
        this.session = session;
    }

    @Override
    public Object getResource() {
        return this;
    }

    @Override
    public void close() {
        // Clean-up if necessary
    }

    @GET
    @Path("hello")
    public Response hello() {
        log.info("HELLO");

        return Response.ok("HELLO").build();
    }
}
```

Also I use TRACE log level and that's what I get just before the error
```
2024-10-26 22:13:36,028 TRACE [io.vertx.ext.web.impl.RouterImpl] (vert.x-eventloop-thread-9) Router: 1787798588 accepting request GET http://localhost:8080/realms/joker-local/joker-admin-endpoints/hello
2024-10-26T22:13:36.032932215Z 2024-10-26 22:13:36,032 TRACE [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Route matches: RouteState{metadata=null, path='null', name=null, order=-199, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13@545d133e], failureHandlers=null, added=true, pattern=null, groups=null, useNormalizedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=false, exclusive=false, exactPath=true}
2024-10-26T22:13:36.032951090Z 2024-10-26 22:13:36,032 TRACE [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Calling the  handler
2024-10-26T22:13:36.032989756Z 2024-10-26 22:13:36,032 TRACE [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Route matches: RouteState{metadata=null, path='null', name=null, order=-2, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1@3813a7ee], failureHandlers=null, added=true, pattern=null, groups=null, useNormalizedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=false, exclusive=false, exactPath=true}
2024-10-26T22:13:36.033001381Z 2024-10-26 22:13:36,032 TRACE [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Calling the  handler
2024-10-26T22:13:36.033215590Z 2024-10-26 22:13:36,033 TRACE [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Route matches: RouteState{metadata=null, path='/', name=null, order=20500, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler@92d0359], failureHandlers=null, added=true, pattern=null, groups=null, useNormalizedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=true, exclusive=false, exactPath=false}
2024-10-26T22:13:36.033224173Z 2024-10-26 22:13:36,033 TRACE [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Calling the  handler
```

The part with `methods=null` seems odd to me.

I am using 25.0.6

**Comment by vovean** [comment] 2024-10-26 22:17
@pedroigor can you take a look, pls?

**Comment by Scorpion1091** [comment] 2024-10-28 06:06
first Gues: you are using incompatible dependencies.

try replacing all you `javax.ws.rs.*` dependencies with `jakarta.ws.rs.` to match the depenencies keycloak is using
