### ISSUE TITLE
Keycloak Operator multiple namespaces / cluster wide

### ISSUE THREAD

**Issue by j0nm1** [keycloak/keycloak#11938] opened 2022-05-11 11:40 UTC
### Description

Currently, the new operator can only manage keycloak instances within the namespace. This is a major problem for our projects as we would like to use different keycloak instances in different namespaces. 

Without this feature, I can't really see any advantage in using the operator as I would need to deploy an operator for each namespace.

### Motivation

All other operators that I know allow a configuration to manage instances in different namespaces or even cluster-wide. This allows us to separate teams and their environments.

Currently, when a team wants to deploy keycloak (with a new config or a new version) they would need to do this in a shared namespace (which leads to problems with the permissions) or create a new operator in their own namespace. Both solutions are pretty bad in my opinion and should not be the way to go.

**Comment by andreaTP** [comment] 2022-05-12 16:34
Hi @j0nm1 and thanks for your interest in the new operator preview!!! 🙂 

I took a little time to answer because I wanted to find a viable workaround as I think your request is more than legit.

So, long story short, the new operator does already support watching multiple namespaces already but we haven't dedicated time/effort enough to make this a first-class supported feature.

The current workaround is:
 - add an environment variable to the [operator `Deployment`](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L201)
```yaml
            - name: QUARKUS_OPERATOR_SDK_NAMESPACES
              value: test1,test2 # comma separated list of the namespaces to watch
```
 - create appropriate [RBAC resources](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L30-L176) to let the operator perform its tasks in the defined namespaces. For example, assuming you have installed the operator in the `default` namespace, you should create those resources in namespace `test1` and `test2`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-operator-role
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakcontroller-cluster-role
rules:
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloaks
      - keycloaks/status
      - keycloaks/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
  name: keycloak-operator-role-binding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: keycloak-operator-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakcontroller-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: keycloakcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakrealmimportcontroller-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: keycloakrealmimportcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
```

Please note that being this a workaround on top of a "Preview" component, we cannot guarantee that the functionality will continue to work in this way in future releases.
On the good news, this functionality is, eventually, going to be implemented \in future releases of the operator.

cc. @vmuzikar

**Comment by j0nm1** [comment] 2022-05-16 09:42
Thank you! 
I tried it out and it works great. I didn't need to deploy the ClusterRole as it was already there.

Should we close this issue or keep it open to track an official implementation?

**Comment by andreaTP** [comment] 2022-05-16 10:10
@j0nm1 thanks for the feedback, I think we can close this as we have a viable workaround, the official implementation won't be forgotten as it's part of the company's direction 🙂

**Closed by andreaTP** 2022-05-16 10:10 UTC
Labels: kind/enhancement, team/cloud-native-sig, area/operator

**Comment by j0nm1** [comment] 2022-05-17 11:11
Hi, sadly this doesn't work as well as expected. Today I wanted to modify the deployment but the operator is permanently complaining about the wrong namespace. After a restart of the operator, it is able to deploy the changes before logging this again:

````
2022-05-17 10:59:59,495 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (EventHandler-keycloakcontroller) Error during event processing ExecutionScope{ resource id: CustomResourceID{name='keycloak-XXX', namespace='keycloak-XXX'}, version: 8671327} failed.: io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:keycloak-XXX. Operation namespace:keycloak-system.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.checkNamespace(OperationSupport.java:234)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:486)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:469)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:83)
	at org.keycloak.operator.v2alpha1.KeycloakIngress.getReconciledResource(KeycloakIngress.java:47)
	at org.keycloak.operator.OperatorManagedResource.createOrUpdateReconciled(OperatorManagedResource.java:50)
	at org.keycloak.operator.v2alpha1.KeycloakController.reconcile(KeycloakController.java:123)
	at org.keycloak.operator.v2alpha1.KeycloakController.reconcile(KeycloakController.java:51)
	at org.keycloak.operator.v2alpha1.KeycloakController_ClientProxy.reconcile(Unknown Source)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:101)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:76)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:75)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:143)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:109)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:74)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:50)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-17 10:59:59,496 ERROR [io.jav.ope.pro.eve.EventProcessor] (EventHandler-keycloakcontroller) Exhausted retries for ExecutionScope{ resource id: CustomResourceID{name='keycloak-XXX', namespace='keycloak-XXX'}, version: 8671327}
```

Do you have any ideas on how to fix this?

**Comment by andreaTP** [comment] 2022-05-17 17:42
Hi @j0nm1 ,
I confirm that I can reproduce the issue, and I have a fix for it.

As a temporary workaround, you should be able to manually delete the ingress to avoid triggering this bug, do you mind filing a separate issue(cc. me there please) and I will follow up with the proper fix?

Thanks a lot in advance and sorry for the rough experience!

**Comment by andreaTP** [comment] 2022-05-18 09:55
@j0nm1 following up on #12074
