### ISSUE TITLE
Workflow failure: Javascript CI on Firefox

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#32905] opened 2024-09-13 11:42 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Admin UI E2E tests fail constantly on Firefox

https://github.com/keycloak/keycloak/actions/runs/10840712018

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by jonkoops** [comment] 2024-09-13 11:44
Duplicate of #32617

**Closed by jonkoops** 2024-09-13 11:44 UTC
Labels: kind/bug, team/ui, flaky-job
