### ISSUE TITLE
Keycloak online documentation should be versioned

### ISSUE THREAD

**Issue by paul-civitas** [keycloak/keycloak#34218] opened 2024-10-22 20:51 UTC
### Description

The page https://www.keycloak.org/server/all-config is extremely useful, as it shows a variety of environment variables, which are crucial for tuning keycloak in a production environment.

However these environment variables change substantially version to version.

It would be a big enhancement if the online documentation could be versioned. As an example of this the kubernetes documentation here: https://kubernetes.io/docs/setup/

There is a "versions" tab on the top left, and it seems to support up to 5 previous versions. Clicking on 1.27 brings us to this page: https://v1-27.docs.kubernetes.io/docs/setup/

Where there is a yellow banner warning saying that this isn't the current version and that the documentation is only relevant to that specific version. This warning is crucial as people who find the page via search engines might think its for a current version when it's actually for an older version.

### Motivation

Bring keycloak documentation in line with CNCF best practices.

### Details

Can probably be adopted using a similar tech stack to the kubernetes documentation.

**Comment by paul-civitas** [comment] 2024-10-22 20:52
Motivation for this, is seeing KC_METRICS_ENABLED not work as expected, and wondering if this is a flag exclusive to version 26, as we're currently on version 25 as it's our company policy to ideally be one version behind the latest version.

**Comment by shawkins** [comment] 2024-10-22 21:54
Relates to or is a duplicate of #33532

**Comment by paul-civitas** [comment] 2024-10-23 14:36
rgr merging in

**Closed** 2024-10-23 14:37 UTC
Labels: kind/enhancement
