### ISSUE TITLE
Client secret not generated automatically on import

### ISSUE THREAD

**Issue by Laith-Grira** [keycloak/keycloak#9201] opened 2021-12-16 19:08 UTC
### Describe the bug

Hello,

In older Keycloak versions (v10.0.1), a user can import a client by either importing it to an existing realm or while they're (client and realm) created together. The
client secret is generated automatically for the clients in the credentials tab. However an issue for the newer versions of keycloak like v15.0.2 , while importing a realm including the clients, the client secret field in the credentials for clients, is missing. This issue doesn't occur when importing a client directly in an existing realm, it only happens when both: client and realm, are created together.

### Version

15.0.2

### How to Reproduce?

Steps for testing:

1- Test case one: Importing a client on an existing realm
        - Under the configure menu, select Clients
        - Click on the "Create" button
        - select "import" and choose an exported client json file,
        - you can use these configs:

```
{
    "clientId": "testimport",
    "surrogateAuthRequired": false,
    "enabled": true,
    "clientAuthenticatorType": "client-secret",
    "redirectUris": [
        "*"
    ],
    "notBefore": 0,
    "bearerOnly": false,
    "consentRequired": false,
    "standardFlowEnabled": true,
    "implicitFlowEnabled": false,
    "directAccessGrantsEnabled": true,
    "serviceAccountsEnabled": true,
    "authorizationServicesEnabled": true,
    "publicClient": false,
    "frontchannelLogout": false,
    "protocol": "openid-connect"
}
```

**=> Result: both keycloaks behave correctly and create the client secret for
the client "testimport"**

2- Test case one: Importing a realm with clients
        - create a new realm "test-Realm-1"
        - create a client (without importing) name it "client-1"
        - make sure to select the "Access type" to confidential for the client.
        - you will see in the "credentials" tab for the client, that a client secret was generated.
        - now go to "export" in the left menu and click export (enable roles and clients).
        - this will create a json file with all realm info.
        - inside that file, the client secret will be saved as "******", remove that key value pairs
           (make sure you're under the "clients" array and not object).
        - Now go back to keycloak and create a new realm "test-Realm-2" (without importing yet)
        - go to "import" in the left menu and click import.
        - select the exported file.
        - make sure to leave "import client" as enabled.
        - set the dropdown menu of "if resources exist" to "skip"
        - confirm the import.

**=> for keycloak v10.0.1, you will find the client "client-1" created and it has a client secret
in the credentials tab

=> for newer versions (like 15.0.2), the client "client-1" is there but the client secret
is missing (This is where the bug occurs)**

**Comment by tmulle** [comment] 2023-08-22 23:54
I also just ran into this trying to import a previous realm created with the `bitnami/keycloak` container which is running `21.0.2`

I exported my realm from the same version and when I imported it back into keycloak the client credentials were `******` and I had to regenerate a new set on the page.

From what I can read online the credentials should be populated..

Now, I have to change my application to use the new secret because the old one is no longer valid.

Any ideas?

**Comment by tmulle** [comment] 2023-08-28 12:40
This also happens with the official image from Redhat as well. 

I was trying to use the Dev Services in Quarkus with Keycloak to import my realm and my client didn't have its secret imported. It was just '*******' and I had to regenerate.

Is this by design? This would seem like it would break a lot of applications if they need to rebuild their Keycloak servers because the secrets are now invalid and all the applications using it will need to be updated in production.

**Comment by tmulle** [comment] 2023-08-28 15:49
@Laith-Grira I also ran into this issue and after some searching it looks like Admin UI export purposely does not include secrets. It generates the export file with '******'

So looks like we have to use a different way to export than the UI. Or manually up the export file ourselves if we have a small number of secrets.

I found two articles about this:

Blog Post:
https://candrews.integralblue.com/2021/09/users-and-client-secrets-in-keycloak-realm-exports/

Old Red Hat Article:
https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.2/html/server_administration_guide/export_import#admin_console_export_import

**Comment by rmartinc** [comment] 2024-03-13 14:01
@Laith-Grira Yes, you are right. The export never exports secrets (it's at several levels, not only in clients). You need to manually update the file to include it. Closing the issue, please file a new one if needed.

**Closed by rmartinc** 2024-03-13 14:01 UTC
Labels: kind/bug, area/import-export, team/core-clients
