### ISSUE TITLE
Verify Profile doesnt update the user profile, causing the user to be stuck in a loop

### ISSUE THREAD

**Issue by jopotochnykorbit** [keycloak/keycloak#25380] opened 2023-12-07 15:40 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

I am running keycloak v23.0.1 on bare metal, and have the `declarative-user-profile` turned on. I have added a single new  attribute using the user profile, which is required for users and is editable by users and admins. I have the Verify Profile required action turned on, so that users must fill out this field before being able to complete the login/user account creation process.

I have IDP login for Github, Bitbucket, and Microsoft setup and enabled. When I create an account by signing in with, e.g. Microsoft, I am able to log in with a Microsoft account and I am presented with the Verify Profile form, where it prompts me to fill in my new user attribute.

However, instead of accepting the value and finishing the sign-in process, the page just keeps presenting the form as the api call isnt made to update the user's profile.

### Version

23.0.1

### Expected behavior

When I fill in the Verify Profile form, it should accept the values and update the proflle so I can move on in the sign-in flow.

### Actual behavior

The user profile doesn't get updated (because the api call to do so doesn't get made), and so the user is stuck submitting the Verify Profile form and being redirected back to the form.

### How to Reproduce?

1. Run Keycloak v23.0.1 with the user profile flag enabled
2. Set up an IDP like Github, Bitbucket, Microsoft
3. Add a required user attribute in the user profile
4. Enable the Verify Profile required action
5. Create a user by signing into an IDP and attempt to fill in the Verify Profile form. Hit submit and see that the form re-appears because the user profile does not actually get updated.

### Anything else?

I have been able to successfully go through the Verify Profile flow before, but once it doesn't work for an email/IDP, it consistently does not work and that user is never able to move on from the Verify Profile step.

I understand that it might be a pain to reproduce, so if you have any ideas as to why the Verify Profile step might not be making the api call to update the user profile I'd love to hear it as well.

**Comment by rmartinc** [comment] 2023-12-13 08:01
@jopotochnykorbit I cannot reproduce this. I have tested with LinkedIn social provider and with the SAML identity provider. I have done the following steps:

1. Enable the User Profile in the realm.
2. Configure a `employeeNumber` attribute with required field on but only for users. Users and admins can edit and view. I have just added a length validator.
3. Configured the LinkedIn and SAML account.
4. Login with a user in each provider.
5. The update account information is presented and I can add the employee number without issues.

I have tested in 23.0.1 and current main without any problem.

Probably there is something we are missing. As you commented it worked for you before, so maybe something is triggering the problem and it's not in the reproducer steps.

**Comment by jopotochnykorbit** [comment] 2023-12-15 15:10
Thanks for replying, yeah it's weird it works for me but for another coworker it consistently never works for them. Not sure how to reproduce 100% as myself, I'm keeping an eye out for 23.0.2 and when that comes out ill re-try with that coworker and see if it is resolved.

**Comment by mposolda** [comment] 2023-12-19 10:10
There is already released Keycloak 23.0.3, so perhaps you can try with that version? 

There is also nightly release, which could be even better to doublecheck if it is fixed in latest main: https://github.com/keycloak/keycloak/releases/tag/nightly .

If not fixed yet, it can be nice if you try with some Keycloak deployment without userProfile enabled and check what are the attributes, which you have in your profile after login to the social Idp and what are the attributes, which your coworker has. Maybe that can show some hint what attribute is causing issues (assuming that things work for you, but not for your colleague as you pointed).

**Comment by pedroigor** [comment] 2024-01-09 14:48
The only thing I can think of is that the attribute is not accessible by the users (e.g.: attribute permissions to `User` not set or set as read-only) so the form does not show the attribute and keeps re-rendering itself.

We have fixed this recently (not sure in 23) whereas attributes where the user does not have access or are read-only are not even shown or validated.

I'm closing as we can't reproduce it. Feel free to re-open if you managed to provide more details steps on how to do it.

**Closed** 2024-01-09 14:48 UTC
Labels: kind/bug, area/user-profile, status/triage, team/core

**Comment by RuchiSingh18** [comment] 2024-10-09 19:14
I am using keykloak 24.0.5 when doing login to app from clients after username and password prompted with Update Account information. I followed everything that mentioned in release document but still Update Account information popup is coming. I dont need that.
