### ISSUE TITLE
Admin UI Theme Change to Base leads to Internal Server Error

### ISSUE THREAD

**Issue by zzzaJ** [keycloak/keycloak#18884] opened 2023-03-15 14:38 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

I tried to change the Admin Console theme to Base instead of the default for Keycloak v21.0. However, when I changed it and refreshed my screen, and navigated to Admin console I was shown this error:

"An internal server error has occurred".

The Logs showed the following error message:
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-25) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)
	at org.keycloak.services.resources.admin.AdminConsole.getMainPage(AdminConsole.java:350)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@344578f3.
	at freemarker.template.Configuration.getTemplate(Configuration.java:2883)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2703)
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.getTemplate(DefaultFreeMarkerProvider.java:66)
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:39)
	... 47 more

### Version

21.0

### Expected behavior

I expected the admin UI to change to the base theme.

### Actual behavior

Upon changing the UI, the server could no progress to the admin console and resulted in an internal server error.

### How to Reproduce?

Launch the server (v21.0) and attempt to change the Admin UI theme to Base.

**Comment by edewit** [comment] 2023-03-16 10:58
Is these a 'base' admin account theme? I think the option in the dropdown is wrong

**Comment by oteichmann** [comment] 2023-03-16 12:52
Upvote. Please fix.

We had to reset the theme by modifying the realm record in the DB.

**Comment by edewit** [comment] 2023-03-16 14:09
@oteichmann what would the fix be?

**Comment by zzzaJ** [comment] 2023-03-16 17:12
The expected behaviour should be to enable the base theme, as seen in KC20, instead of just crashing.

**Comment by guptakaran27** [comment] 2023-03-20 05:36
UPVOTE, I am also facing the same issue !

Also, I am unable to change the title of the Admin Console, from **Keycloak Administration UI** to my custom message. Any leads on this ?
Raised this ticket: https://github.com/keycloak/keycloak/issues/19116

**Comment by edewit** [comment] 2023-03-20 06:02
The base theme was part of the old console and that has been removed, with the introduction of the new console there is no base theme anymore.

**Comment by guptakaran27** [comment] 2023-03-20 06:36
But i could see base directory in the themes jar of Keycloak 21.0.1.
Also, if base theme is deprecated, then how can we change / modify the admin theme ?  (Like custom favicon icons, logos, and title)

**Comment by oteichmann** [comment] 2023-03-20 08:10
Can we agree then that simply removing it from https://github.com/keycloak/keycloak/blob/31ae434e9206055f90df71a892e15466502a618b/themes/src/main/resources-community/META-INF/keycloak-themes.json#L4 would be a sufficient first solution to our current problem? This file is read by org.keycloak.theme.ClasspathThemeProviderFactory and controls the list of themes available for selection. 

The theme (folder) with all its resources will be kept an still can be customized. By deleting it from the selection we can prevent users from running into the deadlock described by @zzzaJ .

If you agree I can create a PR.

**Comment by edewit** [comment] 2023-03-20 08:40
@guptakaran27 currently the way to customise is by changing the code of the theme itself

@oteichmann yes removing "base" for the admin is the way to solve this if you want to to create a PR for it that would be very appreciated

**Comment by guptakaran27** [comment] 2023-03-20 08:58
Thanks for the update @edewit

**Comment by ssilvert** [comment] 2023-03-21 19:39
Yes, the base themes will be removed soon.   Closing this issue.

**Closed by ssilvert** 2023-03-21 19:39 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui

**Comment by ch4mpy** [comment] 2023-08-29 17:52
`update realm set admin_theme=NULL;` is not enough in my case. Anything else to do to recover?

**Comment by ElRaphik** [comment] 2025-02-21 09:57
Hi, just want to say that the problem is still present in 26.1.0, just changed admin theme to "base" and now accessing the admin console crashes the whole pod. 
Please either handle the error of "index.ftl not found" or remove the option from the drop down.

**Comment by jonkoops** [comment] 2025-02-21 13:56
If this issue still persists in the latest version of Keycloak then please report it as a new issue so it can be triaged.
