### ISSUE TITLE
MULTIVALUED_STRING_TYPE does not show in UI if empty

### ISSUE THREAD

**Issue by cnwaldron** [keycloak/keycloak#28979] opened 2024-04-22 17:51 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have a custom Authentication SPI that uses the MULTIVALUED_STRING_TYPE. Starting in v22.0.4 this field does not appear in the UI if the value is an empty string. This makes it impossible to set any MULTIVALUED_STRING_TYPE settings with the UI. 

### Version

v22.0.4 to nightly

### Regression

- [X] The issue is a regression

### Expected behavior

When the MULTIVALUED_STRING_TYPE option is an empty string the UI should show an empty input box plus a button to add to the list. As seen below in the image.
![working-multivaluestring](https://github.com/keycloak/keycloak/assets/72021941/fa5f0aeb-12cb-4b8a-b5e8-8297e67c9963)

### Actual behavior

The input box and add to the list button is missing.
![failing-multivaluestring](https://github.com/keycloak/keycloak/assets/72021941/5e8c1e05-9a30-4b69-8428-d8f211cb0ae8)

### How to Reproduce?

1) Have a custom authentication spi using the MULTIVALUED_STRING_TYPE option for a configuration type. Have the default setting be an empty string. 
2) Log into the Admin UI and create an authentication flow and executor using this custom authentication spi. Click the settings button on the custom authentication spi step to get to the config settings.
3) Find the option using MULTIVALUED_STRING_TYPE and attempt to add options to the list.

### Anything else?

#22478

**Comment by edewit** [comment] 2024-04-23 05:59
This has been fixed in the newer version of keycloak
~old-release

**Comment by jonkoops** [comment] 2024-04-23 10:33
@edewit from reading the description this also seems to be present in the nightly version.

**Comment by edewit** [comment] 2024-04-23 11:32
I can't reproduce it though

**Comment by cnwaldron** [comment] 2024-04-23 12:45
Just to verify, I tested this in the nightly build yesterday.

**Comment by cnwaldron** [comment] 2024-04-23 12:53
Ok I was able to find the issue, the default value was null not an empty string. When the default value is `""` then it works as expected. This was not the behavior before v22.0.4.

**Comment by edewit** [comment] 2024-04-23 13:42
@cnwaldron I'm not sure what you mean with a default value that is null, if I would configure it like this:
```java
.property()
                .name("test")
                .label("Multi null")
                .type(ProviderConfigProperty.MULTIVALUED_STRING_TYPE)
                .defaultValue(null)
```
That would be the same as not setting the `defaultValue` right? And this would result in the default value not showing up in the json e.g.:
```json
"properties": [
    {
        "name": "test",
        "label": "Multi null",
        "type": "MultivaluedString",
        "secret": false,
        "required": false,
        "readOnly": false
    }
],
```
So I tested both with a value of `""` and setting it to null, but both work on the nightly

**Comment by cnwaldron** [comment] 2024-04-23 16:36
This is what I have that shows the issue and I rebuilt my image using the latest nightly image and I'm still seeing the issue:

```java
CONFIG_PROPERTIES = ProviderConfigurationBuilder.create().property(ISSUER_DENY_LIST, ISSUER_DENY_LIST_LABEL, ISSUER_DENY_LIST_HELP,
						ProviderConfigProperty.MULTIVALUED_STRING_TYPE, null, null)
```

Working:
```java
.property(ISSUER_DENY_LIST, ISSUER_DENY_LIST_LABEL, ISSUER_DENY_LIST_HELP,
						ProviderConfigProperty.MULTIVALUED_STRING_TYPE, "", null)
```

**Closed** 2024-04-24 09:40 UTC
Labels: kind/bug, priority/important, area/admin/ui, status/triage, team/ui
