### ISSUE TITLE
Frequent "Error while evaluating permissions" 500 error in the browser console

### ISSUE THREAD

**Issue by pejeio** [keycloak/keycloak#17316] opened 2023-02-27 18:01 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When evaluating permissions, a 500 error with the message "Error while evaluating permissions" in the browser console is shown. The cause of this issue is not clear.

<img width="828" alt="221420407-b2800348-de3f-4bfc-9fda-311fedcb0ac2" src="https://user-images.githubusercontent.com/33237012/221643737-35c9f959-a394-485a-8fc5-d985057c18f6.png">
<img width="1207" alt="221420405-130614d9-fe8a-412b-8c4f-c0fd2d83b652" src="https://user-images.githubusercontent.com/33237012/221643742-07fc364f-de12-4413-a8c1-daa73ea7353b.png">

### Version

21.0.0

### Expected behavior

The application should evaluate permissions without generating errors.

### Actual behavior

The application frequently generates a 500 error with the message "Error while evaluating permissions" in the browser console.

### How to Reproduce?

1. Install Keycloak 21.0.0
2. Create a new Realm role with the name `author`
3. Create a new OpenID Connect client (enable `Client Authentication` + `Authorization`)
4. Create a scope `read`
5. Create a resource: `car`, with `read` as one of the Authorization scopes
6. Create a policy. Configure `author` as required role.
7. Create a permission
Name: `Authors can read cars`
Apply to resource type: `On`
Resource type: `car`
Authorization scopes: `read`
Policies: `Author role policy`
Decision strategy: `Unanimous`

### Anything else?

- This issue occurs in all modern web browsers.
- There are no specific steps or conditions that consistently trigger the error.
- The error message provides no details about the root cause of the issue.

**Comment by ssilvert** [comment] 2023-03-01 20:18
Closing as a duplicate of https://github.com/keycloak/keycloak-ui/issues/4459

**Closed by ssilvert** 2023-03-01 20:18 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
