### ISSUE TITLE
Getting Started (OpenJDK) not working!

### ISSUE THREAD

**Issue by zzador** [keycloak/keycloak#16579] opened 2023-01-23 14:13 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Every step of the "Getting Started"-Tutorial is working fine until "Login to account console". I just can't login with the newly created user and his password. Tried multiple times. Co-worker also tried multiple times on his installation. No success.

### Version

20.0.3

### Expected behavior

Can login with the newly created user and his password.

### Actual behavior

Login denied.

### How to Reproduce?

Follow the Getting Started (OpenJDK) tutorial step by step until you created a new user and set a password for that user. Then logout and try to login again with the newly created user credentials.

**Comment by mposolda** [comment] 2023-03-24 10:04
I am closing as I cannot reproduce on latest Keycloak 21.0.1 and with latest docs. Please re-open just if you see the issue also with Keycloak 21.0.1.

Also make sure that you have user `myuser` created in correct realm `myrealm` and with correct password.

**Closed by mposolda** 2023-03-24 10:04 UTC
Labels: kind/bug, area/account/api, status/triage
