### ISSUE TITLE
Stuck on "Loading the Admin UI"

### ISSUE THREAD

**Issue by yang-shuaijun** [keycloak/keycloak#27810] opened 2024-03-12 12:27 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I initialized the keyclock by the following code:
`
# Initialize the keycloak environment variables
export KEYCLOAK_ADMIN=admin
export KEYCLOAK_ADMIN_PASSWORD='-------'
export KC_DB=postgres
export KC_DB_URL='jdbc:postgresql://database-1-for-idsimulator-instance-1.c8ufoxxnjv2q.us-east-1.rds.amazonaws.com:5432/keycloak'
export KC_DB_USERNAME=postgres
export KC_DB_PASSWORD='-------'
export KC_DB_SCHEMA=public
export KC_TRANSACTION_XA_ENABLED=true
export KC_HEALTH_ENABLED=true
export KC_CACHE=ispn
export KC_METRICS_ENABLED=true
export KC_HTTP_ENABLED=true
export KC_HTTPS_KEY_STORE_FILE=/home/ec2-user/install/keystore/keycloak.jks
export KC_HTTPS_KEY_STORE_TYPE=jks
export KC_HTTPS_KEY_STORE_PASSWORD=changeit
export KC_HOSTNAME_PATH=/
export KC_HOSTNAME_STRICT=false
export KC_LOG=file
export KC_LOG_FILE=/home/ec2-user/keycloak-24.0.1/data/log/keycloak.log
env
# Import self-signed keycloak_ca.crt into jdk cacert
sudo keytool -importcert -noprompt -trustcacerts -cacerts -storepass changeit -file /home/ec2-user/install/keystore/keycloak_ca.crt
# Initialize the keycloak
sudo -E -u ec2-user env
sudo -E -u ec2-user /home/ec2-user/keycloak-24.0.1/bin/kc.sh build --db=postgres --cache=ispn --transaction-xa-enabled=true --features="account-api:v1,account3:v1,admin-api:v1,admin-fine-grained-authz:v1,admin2:v1,authorization:v1,ciba:v1,client-policies:v1,client-secret-rotation:v1,client-types:v1,declarative-ui:v1,device-flow:v1,docker:v1,dpop:v1,dynamic-scopes:v1,hostname:v1,impersonation:v1,js-adapter:v1,kerberos:v1,login2:v1,multi-site:v1,oid4vc-vci:v1,par:v1,preview,recovery-codes:v1,scripts:v1,step-up-authentication:v1,token-exchange:v1,transient-users:v1,update-email:v1,web-authn:v1"
sudo -E -u ec2-user /home/ec2-user/keycloak-24.0.1/bin/kc.sh start --optimized --proxy-headers forwarded &
`
# The following is the startup log
2024-03-12 12:14:58,402 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following build time non-cli options were found, but will be ignored during run time: kc.cache, kc.db, kc.transaction-xa-enabled, kc.health-enabled, kc.metrics-enabled

2024-03-12 12:14:58,490 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: admin-fine-grained-authz:v1, client-secret-rotation:v1, dpop:v1, recovery-codes:v1, scripts:v1, token-exchange:v1, update-email:v1
2024-03-12 12:14:58,490 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: client-types:v1, declarative-ui:v1, dynamic-scopes:v1, login2:v1, oid4vc-vci:v1, transient-users:v1
2024-03-12 12:14:59,243 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-03-12 12:14:59,345 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-03-12 12:14:59,362 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: /, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2024-03-12 12:14:59,443 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2024-03-12 12:14:59,449 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 61077a44-ba09-406b-a16c-dc2762206793, name: ip-172-31-46-155-54237
2024-03-12 12:14:59,463 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.42746
2024-03-12 12:15:00,809 WARN  [io.quarkus.agroal.runtime.DataSources] (JPA Startup Thread) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2024-03-12 12:15:01,473 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) ip-172-31-46-155-54237: no members discovered after 2002 ms: creating cluster as coordinator
2024-03-12 12:15:01,480 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [ip-172-31-46-155-54237|0] (1) [ip-172-31-46-155-54237]
2024-03-12 12:15:01,493 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `ip-172-31-46-155-54237`, physical addresses are `[172.31.46.155:58282]`
2024-03-12 12:15:01,508 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-03-12 12:15:01,897 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: ip-172-31-46-155-54237, Site name: null
2024-03-12 12:15:02,166 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-03-12 12:15:02,997 INFO  [io.quarkus] (main) Keycloak 24.0.1 on JVM (powered by Quarkus 3.8.1) started in 5.206s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8443
2024-03-12 12:15:02,997 INFO  [io.quarkus] (main) Profile prod activated.
2024-03-12 12:15:02,997 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]

I created 2 instances and attached to an AWS application load balancer.
When I logged into the console through alb DNS Name, the screen showed: Loading the Admin UI.
But when I logged into the console through the ec2 ip address, it worked well.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Normally logged into the admin ui.

### Actual behavior

Stuck the admin ui.

### How to Reproduce?

Login into the console through the alb dns name.

**Comment by jonkoops** [comment] 2024-03-12 12:33
Duplicate of #14666

**Closed by jonkoops** 2024-03-12 12:33 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by njoguamos** [comment] 2025-10-08 13:55
I had a similar issue and I disabled `KC_HOSTNAME_PORT` and enable `KC_PROXY_HEADERS` & `KC_PROXY`  on Keycloak container

```dotenv
#KC_HOSTNAME_PORT=443 <- disabled this
KC_PROXY_HEADERS=xforwarded
KC_PROXY=edge
```
