### ISSUE TITLE
Admin UI impossible

### ISSUE THREAD

**Issue by Zathiel** [keycloak/keycloak#33414] opened 2024-09-30 20:21 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

Admin UI can't be accessed 

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Login to Admin UI

### Actual behavior

according to my dockerfile

`version: '3'

services:
  oremis-keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: oremis-keycloak
    environment:
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://kc_mariadb:3306/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=xxx
      - KC_HOSTNAME=sso.domain.tld
      - KC_HOSTNAME_PORT=8443
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_FEATURES=token-exchange
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=xxxxxxxxx
      - KC_HTTPS_KEY_STORE_FILE=/etc/x509/https/keycloak.p12
      - KC_HTTPS_KEY_STORE_PASSWORD=xxxxxxx
      - KC_HTTPS_KEY_STORE_TYPE=PKCS12
    volumes:
      - /var/lib/docker/volumes/keycloak:/opt/keycloak/conf
      - /etc/x509/https/keycloak.p12:/etc/x509/https/keycloak.p12
    ports:
      - "8080:8080"
      - "8443:8343"
      - "9000:9000"
    networks:
      - keycloak-network
    depends_on:
      - kc_mariadb
    command: ["start"]

  kc_mariadb:
    image: mariadb:10.6
    container_name: kc_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=xxxxx
      - MARIADB_DATABASE=keycloak
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=xxxxx
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - keycloak-network

networks:
  keycloak-network:

volumes:
  mariadb_data:
`

I still cannot access the WebUI to configure keycloak but i can access Health and metrics endpoint

### How to Reproduce?

deploy my docker compose 

NGINX proxy manager

**Comment by shawkins** [comment] 2024-09-30 22:03
> I still cannot access the WebUI 

What response code are you getting?

Based upon what you have above http is not enabled, but https is and is running on port 8443 (the default). You are then mapping that to 8343 or is 8443:8343 a typo?

> KC_HOSTNAME_PORT

You should see a warning in the log that this is not used and deprecated.

> NGINX proxy manager

Access via proxy will also require setting the proxy-headers option.

**Comment by Zathiel** [comment] 2024-09-30 22:10
> > I still cannot access the WebUI 

Hey @shawkins 

Thanks for the fast reply

Concerning the webpage i got in sso.domain.tld pointing to port 9000

It displayed like a white page saying keycloak authentification but cannot login



> What response code are you getting?

See above
> 
> Based upon what you have above http is not enabled, but https is and is running on port 8443 (the default). You are then mapping that to 8343 or is 8443:8343 a typo?
> 
Yes it's a copy paste typo but when I anonyme the record but it's all mapped on my side
> 
> > KC_HOSTNAME_PORT
> 
> 
> 
> You should see a warning in the log that this is not used and deprecated.
> 
Not really
> 
> > NGINX proxy manager
> 
> 
> 
> Access via proxy will also require setting the proxy-headers option.
> 
> 
Can you confirm wich one it is 
>

**Comment by shawkins** [comment] 2024-09-30 22:19
> Concerning the webpage i got in sso.domain.tld pointing to port 9000

Do you mean you are able to access the management port?

> It displayed like a white page saying keycloak authentification but cannot login

At the management port 9000, or at 8443?

> Not really

Ok, for KC 26 you'll definitely see an error log - that was added with #33261

> Can you confirm wich one it is

Do you mean forwarded vs xforwarded? That's up to your proxy configuration. nginix is typically configured to poplulate xfowarded headers. You typically see directives like "proxy_set_header  X-Forwarded-Host     $host;" in the config for xforwarded headers.

**Comment by codespearhead** [comment] 2024-10-02 20:39
To add to what [shawkins](https://github.com/shawkins) said, similar questions come up often. The issue is usually running Keycloak without SSL in production mode behind a reverse proxy, without informing Keycloak that it's behind one. In that case, you just need to do this [1][2].

[1] https://github.com/keycloak/keycloak/discussions/28279
[2] https://github.com/keycloak/keycloak/discussions/28279#discussioncomment-9001818

**Comment by Zathiel** [comment] 2024-10-02 20:45
Hey guys

I will have another look tommorow but I can confirm all is well setup on my nginx and curl show ssl certificate active 

Stay in touch

**Comment by Zathiel** [comment] 2024-10-04 17:57
hey  @shawkins @codespearhead 

After double checking i can confirm that all the docs u gave me are applied on my configuration

Can we book a time together

Regards

**Comment by shawkins** [comment] 2024-10-04 18:24
> Can we book a time together

That shouldn't be needed. If you can provide your latest configuration for keycloak 25 or 26, how your proxy is configured / what headers it is setting, and a description or screenshot of what is not working (what url, and at least the response you are getting), then we should be able to guide you on this issue.

**Comment by shawkins** [comment] 2024-10-04 19:02
> with this config its finally working am i missing some best practices ?

Glad that it's working for you. It's up to you how you want to expose Keycloak. 

Am I correct that this is effectively https passthrough, not https reencryption? And the proxy port and keycloak port are both 8443? If so then that explains why you wouldn't need to set proxy-headers.

> KC_HOSTNAME_PORT=8443

That is not used with your configuration.

**Comment by Zathiel** [comment] 2024-10-04 19:04
> > with this config its finally working am i missing some best practices ?
> 
> Glad that it's working for you. It's up to you how you want to expose Keycloak.
i want it as the safer way possible

> Am I correct that this is effectively https passthrough, not https reencryption? And the proxy port and keycloak port are both 8443? If so then that explains why you wouldn't need to set proxy-headers.
> 
what did u suggest on that
> > KC_HOSTNAME_PORT=8443
> 
> That is not used with your configuration.
Can i remove ?

**Comment by Zathiel** [comment] 2024-10-04 19:06
> > with this config its finally working am i missing some best practices ?
> 
> Glad that it's working for you. It's up to you how you want to expose Keycloak.
> 
> Am I correct that this is effectively https passthrough, not https reencryption? And the proxy port and keycloak port are both 8443? If so then that explains why you wouldn't need to set proxy-headers.
> i want it the safer way as possible so please advise
> > KC_HOSTNAME_PORT=8443
> 
> That is not used with your configuration.

can i remove it so ?

**Comment by Zathiel** [comment] 2024-10-04 19:07
> > with this config its finally working am i missing some best practices ?
> 
> Glad that it's working for you. It's up to you how you want to expose Keycloak.
> 
> Am I correct that this is effectively https passthrough, not https reencryption? And the proxy port and keycloak port are both 8443? If so then that explains why you wouldn't need to set proxy-headers.

I want it the safer way as possible please advise
> 
> > KC_HOSTNAME_PORT=8443
> 
> That is not used with your configuration.

Can i remove it so

**Comment by shawkins** [comment] 2024-10-04 19:17
> I want it the safer way as possible please advise

That's too general of a question for this issue. Let's close this issue and you can move any additional thoughts / questions to a discussion topic.

> Can i remove it so

Yes it can be removed.

**Closed by shawkins** 2024-10-04 19:17 UTC
Labels: kind/bug, team/cloud-native, status/triage, area/welcome/ui
