### ISSUE TITLE
Setting KC_DB_USERNAME=postgres crashes quarkus build for postgres users in 23.0.1

### ISSUE THREAD

**Issue by vipwolf** [keycloak/keycloak#25505] opened 2023-12-12 15:28 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When setting
```
KC_DB_USERNAME=postgres
KC_DB=postgres
```
crashes kc.sh build with the following error:
```
2023-12-12 16:21:38,247 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation

2023-12-12 16:21:38,493 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@1e13529a

2023-12-12 16:21:38,494 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@1e13529a

ERROR: Failed to run 'build' command.
Error details:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
        at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:83)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:119)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.NullPointerException: Cannot invoke "io.smallrye.config.ConfigValue.withConfigSourceName(String)" because the return value of "org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(String, java.util.Optional, io.smallrye.config.ConfigSourceInterceptorContext)" is null
        at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.getConfigValue(PropertyMapper.java:133)
        at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.getValue(PropertyMappers.java:47)
        at org.keycloak.quarkus.runtime.configuration.PropertyMappingInterceptor.getValue(PropertyMappingInterceptor.java:43)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:323)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.lambda$run$0(BuildTimeConfigurationReader.java:603)
        at io.smallrye.config.Expressions.withoutExpansion(Expressions.java:29)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:603)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:424)
        at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:424)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:150)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
        at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
        ... 24 more
```

### Version

23.0.1

### Expected behavior

Setting the default postgres user should not crash keycloak build especially as the parameter is mentioned as not build relevant

### Actual behavior

Setting db username to postgres for DB users should not crash the build process

### How to Reproduce?

1. Download keycloak23.
2. Unzip/untar
3. Set environment variable KC_DB_USERNAME=postgres & KC_DB=postgres
4. Run ./kc.sh build

**Comment by vipwolf** [comment] 2023-12-12 15:31
I could even reproduce it running

podman run --rm -it -e KC_DB_USERNAME=postgres -e KC_DB=postgres keycloak/keycloak:23.0.1 build

**Comment by sschu** [comment] 2023-12-12 15:53
Closing this as duplicate of https://github.com/keycloak/keycloak/issues/25010.

**Closed by sschu** 2023-12-12 15:53 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
