### ISSUE TITLE
Check User Sessions Bugs

### ISSUE THREAD

**Issue by pandu-malik** [keycloak/keycloak#11209] opened 2022-04-11 05:46 UTC
### Describe the bug

Couldn't get user sessions from 
GET _https://keycloakhost.com/auth/{MY_REALM}/users/{USER_ID}/sessions_

i also tried another URL like :
GET _https://keycloakhost.com/auth/admin/{MY_REALM}/users/{USER_ID}/sessions_ (got 404)
GET _https://keycloakhost.com/admin/{MY_REALM}/users/{USER_ID}/sessions_ (got 403)
GET _https://keycloakhost.com/{MY_REALM}/users/{USER_ID}/sessions_ (got 404)

### Version

17.0.0

### Expected behavior

got user session

### Actual behavior

response :```

{
"error": "RESTEASY003210: Could not find resource for full path: https://keycloak....
}
```

### How to Reproduce?

curl --location --request GET "https://KEYCLOAK_HOST/admin/realms/MY_REALM/users/MY_USERS/sessions" --header "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxaGFqNlpkMmV2b28wMHIxUGNxcjZxOEljTjYxcUFwLS1ZS2xWYmFDcmJVIn0.eyJleHAiOjE2NDk2NTUyNzgsImlhdCI6MTY0OTY1NDk3OCwianRpIjoiMWEyMjdlNTMtNTQyZC00NDYxLTlkMDMtZjFmOTY2Y2JiZmQ4IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay1ub25wcm9kLmJmaS5jby5pZC9yZWFsbXMvSUFNX0JGSV9ERVYiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiZGJmOTQ3NmQtNDM4Ny00NGViLTk0NDgtNGI0YjAwZDczMzMxIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibmV3LWluc3VyYW5jZSIsInNlc3Npb25fc3RhdGUiOiIxYTc0MTY5Ny1kZGMyLTRkNTEtOWIwYi1iZjQyZTcyZDdkMWIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vc...."

KEYCLOAK_HOST, MY_REALM, MY_USERS, should be change with your own config


### Anything else?

_No response_

**Comment by mhajas** [comment] 2022-04-11 07:31
Thank you for reporting the bug @pandu-malik. I am not able to reproduce this. 

The correct curl call should be the following:
```
curl  -v "http://$KEYCLOAK_HOST/auth/admin/realms/$MY_REALM/users/$USER_ID/sessions" --header "Authorization: Bearer $TOKEN"
```

Also, make sure the authenticated user is authorized to make such requests. The user needs to be authorized to manage users within the realm. You can do this by adding the user the following client role: `master-realm#view-users`. I am closing this as I can't reproduce the bug, but feel free to reopen it if I missed something.

**Closed by mhajas** 2022-04-11 07:31 UTC
Labels: kind/bug, status/triage

**Comment by pandu-malik** [comment] 2022-04-11 11:17
oh okay, it's may work if the users has `master-realm#view-users` roles, 
but now, how i could checking normal user sessions then ?

**Comment by mhajas** [comment] 2022-04-11 14:34
Users can check their sessions in the account console. Just navigate to `http://KEYCLOAK_HOST/auth/realms/$MY_REALM/account/` in your browser.

**Comment by mhajas** [comment] 2022-04-12 08:47
I don't think there is any REST endpoint for what you need. Users cannot remove their own sessions unless they have authorization for that. 

Not sure what you mean by Client SDK, but if you mean [client service account](https://www.keycloak.org/docs/latest/server_admin/#_service_accounts), it could work. 

Also, for queries like this, it is better to ask on some [community forum](https://www.keycloak.org/community), in this case, User mailing list would be the best option. There is a wider audience and people have more experience with real-world use cases.  You can describe your use case and I am sure someone will help you.
