### ISSUE TITLE
keycloak.conf db-username search for dbname instead

### ISSUE THREAD

**Issue by eassa** [keycloak/keycloak#20770] opened 2023-06-04 14:09 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

i tried to connect to postgressql using the keycloak.conf 
my settings are as such
`
db=postgres 
db-username=eassa
db-password=xxxxx
db-url=jdbc:jdbc:postgresql://PostgreSQL 15/keycloak
` 
it tells me database eassa does not exit ,
when i created a database called eassa , it worked 
eassa is my user name and keycloak is my database , keycloak was empty and eassa database got the tables instead 
tryed it on another username , did the same thing

exception are as such : 

`2023-06-04 16:59:16,803 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
2023-06-04 16:59:16,804 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
2023-06-04 16:59:17,257 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': FATAL: database "eassa" does not exist
2023-06-04 16:59:17,258 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: database "eassa" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2788)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:174)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:290)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
        at org.postgresql.Driver.makeConnection(Driver.java:434)
        at org.postgresql.Driver.connect(Driver.java:291)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-06-04 16:59:18,362 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal`

### Version

21.1.1

### Expected behavior

username should be set to username 
and db-url should be the database name 

### Actual behavior

username is databasename 
db-url: does not check dbname 

### How to Reproduce?

use postgress last version to this date

**Comment by vmuzikar** [comment] 2023-06-05 16:18
@eassa Thanks for the report. Could you please provide as detailed steps to reproduce as possible, especially showing how exactly do you configure Keycloak (the config file you are using)? That would help us significantly when triaging a prioritizing this issue. I'm going to close this for now as we're unable to reproduce. Feel free to reopen when you are able to provide additional details. Thank you.

**Closed by vmuzikar** 2023-06-05 16:18 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
