### ISSUE TITLE
Feature Docker stays enabled in admin ui after disabling it

### ISSUE THREAD

**Issue by BaseCrusher** [keycloak/keycloak#13523] opened 2022-08-03 18:47 UTC
### Describe the bug

If you had feature docker enabled and then you disable it, there is a strange error in the new admin ui where it still shows that it is enabled. In addition to this it shows that it is diabled aswell.

### Version

19.0.1

### Expected behavior

When disabling the docker feature it should also show as disabled in the admin ui.

### Actual behavior

Shows the docker feature as enabled and disabled simultaniously.

### How to Reproduce?

1. Enable the feature docker in the Keycloak Docker image. 
2. Start the Keycloak container.
3. Create a Client that uses the feature docker.
4. Delete said Client.
5. Restart the container without feature docker enabled.

### Anything else?

![image](https://user-images.githubusercontent.com/12885003/182685950-500173c6-ca39-40e1-9b65-38efbf8e1cca.png)

**Comment by mabartos** [comment] 2022-08-04 09:16
@BaseCrusher Thanks for creating this issue. 

Duplicate of this one: https://github.com/keycloak/keycloak-admin-ui/issues/1718

**Closed by mabartos** 2022-08-04 09:16 UTC
Labels: kind/bug, status/triage
