### ISSUE TITLE
Inconsistent behaviour when retrieving users from the Admin REST API w/o parameters

### ISSUE THREAD

**Issue by dardar4** [keycloak/keycloak#13295] opened 2022-07-24 10:00 UTC
### Describe the bug

Hi

When inspecting the user_entity table in the DB I can see that there are 2 types of users - 
"regular" users that we are creating (and that you can see in the admin console users section)
"service-account" users that seem to be created for each client we are creating
in the screenshot, you can see we have a regular "admin" user and a "service-account-alertservice" user

![image](https://user-images.githubusercontent.com/18570901/180641727-78115d66-2918-4c66-a413-5f45bbf7ed00.png)

When sending a GET request to the user's endpoint KC admin API will retrieve all the "regular" users entities from the DB - In this case only the "admin" user.

however, if we use a query parameter "username", KC will filter the results from the DB with the "service-account" users - in this case if we send "https://[kc_url]h/admin/realms/[realm]/users?username=al   we will get the "service-account-alertservice" user.

so it seems that when sending with no query parameters that API is filtering the "service-account" users by default, but when sending with query parameters it does not.

### Version

16.0.0

### Expected behavior

the behavior is Inconsistent  and should be fixed to either retrieve all users or only the "regular" users 

in my opinion, only users that were created from the "users" sections (or the equivalent API) should be displayed and retired from the API

### Actual behavior

described above

### How to Reproduce?

create a user from the users section in the admin console
create a client
make sure there are 2 users in the DB 
send a GET request to "users" endpoint with no query parameters 
send a GET request to "users" endpoint with a query parameter "username" with the name of the client

**Comment by lexcao** [comment] 2022-07-25 16:00
Hi, I have found the following code related.
When searching users by attributes, the service account is included.  (`includeServiceAccounts = true`)

https://github.com/keycloak/keycloak/blob/7158e781bea4130111b57c7475c37b7ad8004fa3/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L332-L335

While searching for the `search` keyword or w/o parameter, the service account is not included.

https://github.com/keycloak/keycloak/blob/7158e781bea4130111b57c7475c37b7ad8004fa3/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L298-L299

It is intendedd behavior, I think.
If none service account is included, there is no way to search it.

**Comment by dardar4** [comment] 2022-07-26 08:29
Ok. 
I see that this was intended for some reason, and not a bug.
I still find it pretty confusing (to say the least) that the type of query parameters (none/search OR all others) decides on which DB entities the filter will be applied

and since this is not transparent to the common user I find it a bad API design

at least now I know how to handle it in my code

thanks

**Comment by mposolda** [comment] 2023-04-04 09:47
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by pedroigor** [comment] 2024-03-04 19:35
I agree this is confusing and more confusing is returning/managing service accounts as a regular user in the administration console.

We have discussions around this. For instance, https://github.com/keycloak/keycloak/issues/22730#issuecomment-1695587234.

Closing as a duplicate of https://github.com/keycloak/keycloak/issues/22730.

**Closed** 2024-03-04 19:41 UTC
Labels: kind/bug, area/admin/api, team/core-iam
