### ISSUE TITLE
IllegalStateException when updating client configuration

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#12484] opened 2022-06-13 16:44 UTC
### Describe the bug

Updating a client fails with an IllegalStateException and `null [unknown_error]` on the CLI.

### Version

18.0.0

### Expected behavior

Not fail, or give a reasonable error.

### Actual behavior

Throws the following exception in the server log:

```
2022-06-13 16:34:47,120 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: java.lang.IllegalStateException: Duplicate key openid-connect%Client ID (attempted merging values org.keycloak.models.ProtocolMapperModel@654f167d and org.keycloak.models.ProtocolMapperModel@48c70504)
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.keycloak.models.utils.RepresentationToModel.updateClientProtocolMappers(RepresentationToModel.java:1659)
        at org.keycloak.services.resources.admin.ClientResource.updateClientFromRep(ClientResource.java:781)
        at org.keycloak.services.resources.admin.ClientResource.update(ClientResource.java:148)
        at jdk.internal.reflect.GeneratedMethodAccessor676.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)


```

### How to Reproduce?

I don't have an exact reproducer, but it happens when first creating the client using `kcadm` and then updating it (with the same content):

```json
{
    "clientId": "services",
    "clientAuthenticatorType": "client-secret",
    "enabled": true,
    "publicClient": false,
    "implicitFlowEnabled": false,
    "standardFlowEnabled": false,
    "directAccessGrantsEnabled": false,
    "serviceAccountsEnabled": true,
    "fullScopeAllowed": true,
    "defaultClientScopes": [
    "email",
    "profile",
    "roles",
    "web-origins"
    ],
    "optionalClientScopes": [
    "address",
    "microprofile-jwt",
    "offline_access",
    "phone"
    ],
    "defaultRoles": [
    "drogue-user",
    "drogue-admin"
    ],
    "protocolMappers": [
    {
        "name": "add-audience",
        "protocol": "openid-connect",
        "protocolMapper": "oidc-audience-mapper",
        "config": {
        "included.client.audience": "services",
        "id.token.claim": "false",
        "access.token.claim": "true"
        }
    }
    ]
}
```

### Anything else?

I also saw this in keycloak versions 14+ when using the legacy operator instead of `kcadm`.

**Comment by ctron** [comment] 2022-06-15 10:14
I just tried using `kcadm update` with `--merge`, which resulted in:

```
null [RESTEASY003065: Cannot consume content type]
```

**Comment by andreaTP** [comment] 2022-06-20 15:30
@mposolda I do believe that this issue falls under your realm.

But I did a little investigation and those are my considerations:
 - `protocolMappers` in `ClientRepresentation` are represented by a `List` which can eventually contain duplicates
 - the previous implementation of the failing line was ignoring duplicates and overwriting: https://github.com/keycloak/keycloak/blame/e6bd12b174a4346af605d2d54d1d3c22ad0a80a0/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L1561
- I'm unable to reproduce locally as the logic seems to prevent the insertion of duplicates (in `ClientTest`)

**Comment by andreaTP** [comment] 2022-06-21 11:32
@ctron I was trying even harder to reproduce the issue to have a proper test, but I'm not able to do it using the `client`.

In addition:
- `resource.getProtocolMappersStream()` is already deduplicating elements when applicable
- there are protections in place to avoid the duplication from happening: https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/model/jpa/src/main/java/org/keycloak/models/jpa/ClientScopeAdapter.java#L122

I'm now guessing that the issue might happen when inserting data with an old version of Keycloak ...
@mposolda I'm happy to collaborate but I think I'm falling short here and I would anyhow need you to assist/take over on this one, should I assign this to you?

**Comment by ctron** [comment] 2022-06-22 11:08
I tested this with 18.0.0. Always with a fresh instance. And had issues before with 14 and 15.

I constantly run into this issue. Though it isn't always the same client that runs into this. Sometimes the first one, sometimes the second one. Maybe it is a some kind of race condition. Requests coming in "too fast". I don't know.

I am not sure this helps, but I can give you some instructions on how I could reproduce that. It just may get a bit messy, as it is a rather complex deployment.

**Comment by mposolda** [comment] 2022-06-24 07:14
@andreaTP Maybe you're right, but hard to prove this. Until we have proper reproducer or figure what is going on, it is quite hard to fix this.

IMO this is not critical issue and not a regression and at the same time, might be harder to fix (until we have proper producer). Hence my vote is to move this to backlog (Triage this with label "Help wanted") and leave to someone from the community to either come with better reproducer or even better with the fix (including test).

**Comment by ctron** [comment] 2022-06-24 07:18
> IMO this is not critical issue

I would disagree. As this makes it impossible to reconcile a Keycloak client. I can try to come up with a reproducer that is simpler to execute.

**Comment by mposolda** [comment] 2022-06-24 08:37
@ctron Note, that it is possible to update client or CRUD of any of it's protocol mappers with the Keycloak admin console, which uses admin REST API under the covers. So there is an alternative option to use the admin REST API instead of `kcadm` and call the same requests, which admin console does, and you should be fine.

Regarding the `kcadm`, it is maybe just a matter of more proper usage as `kcadm` also uses admin console under the covers. TBH I know that our documentation is not very great, however I believe that something of this could help to make client update successful:
- Manually remove `protocolMappers` element from the client JSON (including all protocol mappers). Useful if you want update the client settings and not his protocol mappers.
- Update the `protocolMappers` element and make sure that each of the protocol mappers have properly set `id` with it's ID before you sent the client update request.

**Comment by creckord** [comment] 2022-10-18 09:12
Could this be a duplicate of #10417 ? 

For us, this happens sporadically with clients managed by the operator, which show duplicate mappers for "Client ID", "Client IP Address" and "Client Host", sometimes 3 or 4 of each.

Unfortunately, this causes a lot of noise, both in the Keycloak logs and in the operator logs. Our current workaround is to delete all but one of each mapper, and so far the problem seems to not reoccur for the same client afterwards.

**Closed** 2024-06-10 00:06 UTC
Labels: kind/bug, area/core, help wanted, team/core-clients, status/auto-expire, status/auto-bump, priority/normal, status/expired-by-bot
