### ISSUE TITLE
Listing not working on page "Assign roles to <user> account"

### ISSUE THREAD

**Issue by vc43** [keycloak/keycloak#16043] opened 2022-12-16 14:10 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If there are more than 10 roles, then the listing does not work on the page "Assign roles to <user> account". Always shows only the first page of roles. Helps only selecting "100 per page".

### Version

20.0.1

### Expected behavior

The next page is shown.

### Actual behavior

The first page is always shown.

### How to Reproduce?

Create more than 10 roles and try to assign the last one to some user.

**Comment by pschyma** [comment] 2022-12-19 11:28
And if one has more than 100 roles then even this workaround does not help.

Filtering/ searching for a role doesn't work either.

**Comment by elodie-ferreira** [comment] 2022-12-20 14:33
Pagination is also not working when viewing all roles already assigned to an user, if searching for roles. When not searching for anything, pagination seems to be working.

**Comment by Whalen24** [comment] 2022-12-27 18:27
The Role Mapping tab for Group has the same bug.

**Comment by ssilvert** [comment] 2023-01-03 18:40
This should be fixed in 20.0.2 and/or 20.0.3.  I could not reproduce with latest.

I believe this is a duplicate of https://github.com/keycloak/keycloak-ui/issues/3740

**Closed** 2023-01-03 18:40 UTC
Labels: kind/bug, area/admin/ui, status/triage

**Comment by pschyma** [comment] 2023-01-09 10:34
It's not in 20.0.2. Is there an ETA for 20.0.3?

**Comment by netthier** [comment] 2023-01-11 15:42
Can confirm this issue is still occurring in 20.0.2

**Comment by pschyma** [comment] 2023-03-15 12:08
Just hit that issue again in 21.0.1.

**Comment by WeevilLabs** [comment] 2023-05-12 11:39
I can confirm that the issue still exists in 21.0.2

**Comment by jonkoops** [comment] 2023-05-15 16:51
I believe this is a duplicate of #20356.

**Comment by jonkoops** [comment] 2023-05-15 16:54
True, but we prefer open an fresh issues to resolve :)

**Comment by netthier** [comment] 2023-05-15 16:55
True, re-opening issues that were falsely closed just makes things more confusing.
