### ISSUE TITLE
Glitch with favicon.ico, providers and themes inheritance

### ISSUE THREAD

**Issue by mimigreg** [keycloak/keycloak#30025] opened 2024-05-31 09:56 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

- [x ] I reproduced on  22.0.5, 23.0.7 and 24.0.4
- [x ] I haven't seen the same bug (have one maybe linked but not same)
 

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

One "double" inherited theme should be able to override the favicon.ico

### Actual behavior

One "double" inherited theme let the favicon.ico fallback on the default keycloak default icon

### How to Reproduce?

- Setup a provider including two different themes
```
{
    "themes": [{
        "name" : "theme_one",
        "types": [ "login" ]
    },{
        "name" : "theme_two",
        "types": [ "login" ]
    }]
}
```

- On the first one 
  - make inheritence from base :
```
parent=base
import=common/keycloak
```

  - put a custom favicon.ico in theme_one/resources/img
  - link in the html page this icon :
 ```
<html>
...
  <link rel="icon" href="${url.resourcesPath}/img/favicon.ico" />
```

- On the second
  - make inheritence from the first theme :
```
parent=theme_one
import=common/keycloak/theme_one
```

Then :
-> Watch the login page after setted up the **theme_one**, you can see that styles, images and all are perfectly applied including favicon.ico

-> Watch the login page after setted up the **theme_two**, you can see that styles, images and all are perfectly applied **excepted** favicon.ico : _This one is replaced by keycloak's default icon_

### Anything else?

going further... i noticed as workaround that just renaming **favicon.ico** by **anything.png** solves this minor problem. All icons are perfectly displayed

**Comment by rmartinc** [comment] 2024-06-03 08:59
Hi @mimigreg!

What you are doing here is:

1. The `theme_one` extends `base` and import another folder from `common/keycloak` (theme `keycloak`, type or folder `common` in the theme). The `favicon.ico` is defined locally in `theme_one` so that one is used over the one imported from `common/keycloak`.
2. You define a second theme `theme_two` which extends from `theme_one` but you are importing again `common/keycloak/theme_one`. This import makes no sense because the format of an import is `<theme>/<type>`. Because the code is just splitting by slash, you just import again the same `common/keycloak` as in `theme_one` and the third word is not used (check the code [here](https://github.com/keycloak/keycloak/blob/24.0.4/services/src/main/java/org/keycloak/theme/DefaultThemeManager.java#L145-L146)). So in the end the `favicon.ico` is used from the import instead from the base `theme_one`.

In the `theme_two` just remove the `import=common/keycloak/theme_one` line which makes no sense. You don't need to import the folder from keycloak again as it's already imported by the `theme_one`. Then the favicon is used from the base `theme_one`. Check if this works for you.

**Comment by mimigreg** [comment] 2024-06-04 08:28
Hi you're right import=common/keycloak/theme_one was useless, it behaves exactly the same. Thanks.

But, the icon also. Still there on parent and missing on children.

If i rename favicon.ico with myicon.png it works... i guess, maybe there's a specific treatment on this file somewhere.

**Comment by rmartinc** [comment] 2024-06-04 09:16
In my tests in keycloak 24.0.4 if I remove the import in `keycloak_two` the icon defined in `keycloak_one` is used. And it makes sense, because if you import `common/keycloak/theme_one` you are really importing `common/keycloak` which has the keycloak `favicon.ico` inside it, so it overwrites the one defined in the parent theme.

I cannot reproduce if I remove the import in `keycloak_two`.

**Comment by mimigreg** [comment] 2024-06-06 08:24
you're right. My mistake, i was fooled by a fake positive deployement status.
I confirm, it works. Thank you for your help.

**Comment by rmartinc** [comment] 2024-06-06 08:27
Thanks @mimigreg! Closing then the issue as not planned.

**Closed by rmartinc** 2024-06-06 08:27 UTC
Labels: kind/bug, status/triage, area/login/ui, team/core-clients, status/auto-expire, status/auto-bump
