### ISSUE TITLE
Missing `exp` claim from Offline tokens when `Offline Session Max Limited` is disabled

### ISSUE THREAD

**Issue by havarnov** [keycloak/keycloak#27201] opened 2024-02-21 10:38 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

We're seeing different Offline tokens depending on whether `Offline Session Max Limited` is enabled or not. With `Offline Session Max Limited` disabled Offline tokens (`refresh_token`) don't have any `exp` claim, but with `Offline Session Max Limited` enabled Offline tokens have `exp` set to `iat` plus `Offline Session Idle`.

### Version

23.0.6

### Regression

- [ ] The issue is a regressions

### Expected behavior

That Offline tokens have `exp` set to `iat` plus `Offline Session Idle` regardless of the `Offline Session Max Limited` setting.

### Actual behavior

The Offline tokens are different depending on whether `Offline Session Max Limited` is enabled or not.

### How to Reproduce?

```env
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin
KC_DB=postgres
KC_DB_URL=jdbc:postgresql://postgres:5432/postgres?user=postgres&password=postgres&ssl=false
DEBUG=true
DEBUG_PORT="*:8787"
```

```
podman run -it --rm -e POSTGRES_PASSWORD=postgres --name postgres --network kc postgres
```

```
podman run --rm -it --network kc -p 8080:8080 -p 8787:8787 --env-file=.env quay.io/keycloak/keycloak:23.0.6 start-dev
```

open http://localhost:8080/admin/master/console/ & login with admin/admin

goto `account` client and enable `Direct access grants`
NOTE: this is also reproducable with "grant_type" `Authorization Code (with PKCE)`.

Under Realm settings -> Sessions:
* Make sure `Offline Session Idle` value is set to 30 days (default value).

```
curl --location --request POST 'http://localhost:8080/realms/master/protocol/openid-connect/token' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'password=admin' \
  --data-urlencode 'username=admin' \
  --data-urlencode 'client_id=account' \
  --data-urlencode 'scope=offline_access' \
  --data-urlencode 'grant_type=password'
```

```json
{
  "header": {
    "alg": "HS256",
    "typ": "JWT",
    "kid": "737f1c84-fd16-4bca-a970-da966c7e3640"
  },
  "payload": {
    "iat": 1708510156,
    "jti": "fe7b927d-4e33-4c70-8d56-95a989aaa89c",
    "iss": "http://localhost:8080/realms/master",
    "aud": "http://localhost:8080/realms/master",
    "sub": "7d964bb1-a8e1-4452-a4a8-cb20d89bcff1",
    "typ": "Offline",
    "azp": "account",
    "session_state": "08adc8d6-33a3-43d0-ab10-1eca21e39de8",
    "scope": "profile offline_access email",
    "sid": "08adc8d6-33a3-43d0-ab10-1eca21e39de8"
  },
  "signature": "Zrr15e6ZAR1ytsLzwuuSpvbCAfYfsWFKZf8y1Flj4jk"
}
```

NOTE: `iat` is _now_ and no `exp`

Under Realm settings -> Sessions:
* _Don't_ change the `Offline Session Idle` value.
* Enable `Offline Session Max Limited` and keep the 60 days default value.

Repeat login request:

```
curl --location --request POST 'http://localhost:8080/realms/master/protocol/openid-connect/token' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'password=admin' \
  --data-urlencode 'username=admin' \
  --data-urlencode 'client_id=account' \
  --data-urlencode 'scope=offline_access' \
  --data-urlencode 'grant_type=password'
```

```json
{
  "header": {
    "alg": "HS256",
    "typ": "JWT",
    "kid": "737f1c84-fd16-4bca-a970-da966c7e3640"
  },
  "payload": {
    "exp": 1711102403,
    "iat": 1708510403,
    "jti": "1bfad0b8-ce8a-4238-8612-6771545eba15",
    "iss": "http://localhost:8080/realms/master",
    "aud": "http://localhost:8080/realms/master",
    "sub": "7d964bb1-a8e1-4452-a4a8-cb20d89bcff1",
    "typ": "Offline",
    "azp": "account",
    "session_state": "b0edad69-564c-4137-aa9e-f75e59635688",
    "scope": "profile offline_access email",
    "sid": "b0edad69-564c-4137-aa9e-f75e59635688"
  },
  "signature": "5lVvbdGiWUM2D-vrVha8eTEOFEmYdVbrVlRL64sA6Nc"
}
```

NOTE: `iat` is _now_ and `exp` is now set to `iat` + `Offline Session Idle (30 days)`.

### Anything else?

We've experienced weird `REFRESH_TOKEN_ERROR`s in our system and think we're hitting this bug: https://github.com/keycloak/keycloak/issues/14040. This issue was discovered during our investigation of the `REFRESH_TOKEN_ERROR` issue, but we're not sure if the two issues are related.

**Comment by martin-kanis** [comment] 2024-02-28 15:45
@havarnov Thanks for reporting this. I was able to reproduce this with `main`. The problem is also present in older releases i.e 22.0.5 so is not a regression. 
Are you using the `exp` claim for something? It seems Keycloak is able to refresh token with the missing `exp` claim. So whether it is connected to #14040 needs a deeper look.

**Comment by pedroigor** [comment] 2024-03-06 13:55
@martin-kanis @havarnov AFAIK, not having expiration in refresh tokens is expected in this case. So it is not a bug. See KEYCLOAK-13844.

I'm suggest closing this issue for this reason and watching https://github.com/keycloak/keycloak/issues/14040 for the issue related to refresh token errors.

**Closed** 2024-03-07 23:27 UTC
Labels: kind/bug, area/core, team/core-iam

**Comment by havarnov** [comment] 2024-03-19 08:11
This might not be related to #14040, but it's now been a month and after we enabled `Offline Session Max Limited` we don't see any more of the issue reported in #14040.

**Comment by jonaskello** [comment] 2024-03-20 11:32
I was also trying to understand why `exp` claim is missing. Seems it is only present when "Offline Session Max Limited" is enabled. I think it may be for backwards combability. See this issue and related PR:


https://issues.redhat.com/browse/KEYCLOAK-13844

PR: https://github.com/keycloak/keycloak/pull/7012
