### ISSUE TITLE
Client Roles are not shown when clientId property is set

### ISSUE THREAD

**Issue by Rainson12** [keycloak/keycloak#30436] opened 2024-06-14 10:54 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

When defining a client scope for role mapping and setting the client id, there are no roles shown in the token.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Only roles of the specified client id will be shown

### Actual behavior

no roles are shown

### How to Reproduce?

* Create a new client (eg: `test`)
* Add a new role to the created client like `ABC`
* Go to any existing user (eg. admin) and assign it the newly created client role `ABC`:
![image](https://github.com/keycloak/keycloak/assets/13119203/5663fae5-cf89-4a69-b6e1-a90a469cc962)
* go back to the created client, navigate to the client scopes and selected the dedicated one (first one)
* Add a predefined mapper and select `client roles` and click add
* Select the added mapper and change the `Token claim name` to something like `test_roles`
* Go back to the client scopes tab of the added client and switch to `Evaluate` nested tab
* select the user (eg `Admin`) which you previously assigned to role (eg `ABC`) to and click on `Generated access token` to see an example of how an example token looks like. In the output you should then see something like:
```
  "test_roles": [
    "ABC",
    ....
    ....
  ]
```
* now switch back to client scope setup and select the dedicated one
* Click the previously added `client roles` mapper 
* Set the `client id` property to the clients name (eg `test`)
It should now look like:
![image](https://github.com/keycloak/keycloak/assets/13119203/2c2b8b86-eaca-4faf-858a-e364a15785b6)
* Click save
* Go back to the client scopes tab of the added client and switch to `Evaluate` nested tab
* select the user (eg `Admin`) which you previously assigned to role (eg `ABC`) to and click on `Generated access token` to see an example of how an example token looks like.
* Now the `test_roles` will no longer be shown, even if the created `ABC` role does match to the client that is used in the role mapper client id.

**Comment by graziang** [comment] 2024-06-17 10:32
Hi @Rainson12, this seems to be a valid issue because, in the admin UI, for the property `Client ID` in the `User Client Role`, the ID of the client (`7ab8d536-eec4-495e-af2f-42d597c4a93`) is saved instead of the `clientId` (`test`). However, the method to resolve client roles uses the `clientId` instead of the ID of the client: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/utils/RoleResolveUtil.java#L75.


One solution could be to get the correct `clientId` in the `UserClientRoleMappingMapper` before resolving the roles, but I was wondering if this is a regression after introducing some changes in the admin UI and if databases with older versions could still have the correct `clientId`. @jonkoops WDYT?

**Comment by jonkoops** [comment] 2024-06-17 10:41
I think that this will have to be evaluated by the UI team. I'll re-label the issue. @keycloak/ui FYI

**Closed** 2024-06-20 12:16 UTC
Labels: kind/bug, priority/important, area/admin/ui, team/ui

**Comment by mnlipp** [comment] 2024-06-25 10:28
This is definitely a regression. I've just run into this problem after upgrading. And waiting for 26.0.0 for this to be fixed is definitely too long.

**Comment by jonkoops** [comment] 2024-06-25 10:48
@edewit could you create a backport for this one?
