### ISSUE TITLE
keycloak no port name - keycloak is installed by keycloak operator

### ISSUE THREAD

**Issue by chary1112004** [keycloak/keycloak#13884] opened 2022-08-19 11:15 UTC
### Describe the bug

Hi,

We would like to use prometheus pull metric keycloak using **servicemonitor**. And servicemonitor pull service through port name.

However, keycloak service does not have port name as below:

```spec:
  clusterIP: 10.100.236.248
  clusterIPs:
  - 10.100.236.248
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

While we check source code then there is no code to allow declare port name for keycloak service. Repo: https://github.com/keycloak/keycloak/blob/18.0.2/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakService.java
![image](https://user-images.githubusercontent.com/76929085/185606744-2799b2a7-bfeb-41ac-8f73-9ea5f258b577.png)

Could you please check and enhance keycloak operator to allow declare port name for keycloak service?

Thanks!

### Version

keycloak-operator v18.0.2

### Expected behavior

Enhance keycloak operator to allow declare port name for keycloak service

```
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
```

**Comment by shawkins** [comment] 2023-07-09 16:42
Duplicate of #12593

**Closed by shawkins** 2023-07-09 16:42 UTC
Labels: kind/enhancement, area/operator
