### ISSUE TITLE
Make cookies secure

### ISSUE THREAD

**Issue by VaishaliFoko10** [keycloak/keycloak#24335] opened 2023-10-26 19:57 UTC
### Description

Google is planning to disable third-party cookies in 2024. Partitioned; SameSite=None; Secure attributes are required to be set for all cookies in order to use Keycloak in the expected manner.

https://techcrunch.com/2023/05/18/google-will-disable-third-party-cookies-for-1-of-chrome-users-in-q1-2024/

### Discussion

https://developer.chrome.com/en/docs/privacy-sandbox/chips/

### Motivation

We won't be able to continue using the Keycloak library 

### Details

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java, only the Partitioned attribute is required to be set for all cookies as Samsite and secure are already set

**Comment by vmuzikar** [comment] 2023-11-22 17:45
Closely related to (and possibly duplicate of) #16834.

**Comment by jonkoops** [comment] 2023-11-24 14:09
Don't think this is a duplicate, if I read this correctly this is a request to add the [`Paritioned` attribute](https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies#how_does_chips_work) to our cookies.

**Comment by jonkoops** [comment] 2023-11-24 14:12
See also #19886, #14761

**Comment by stianst** [comment] 2024-01-23 11:07
I don't see how Partitioned is a good idea as it essentially creates a separate cookie jar for each top-level site. That would effectively mean each top-level site would get its own authentication/user sessions, and there would be no single sign-in/out across multiple top-level sites.

With `SameSite=none,secure` the cookies are sent on a GET or POST to Keycloak, but is not available in an iframe context when browsers disallow third-party cookies. That means OIDC and SAML flows work as expected as long as the login page is not embedded as an iframe.

There's the additional `KEYCLOAK_SESSION` cookie that has to be available by design in a iframe context, but that will not help if it's partitioned as it would still not make OIDC session management work as expected if this cookie was partitioned. You'd get the initial value, which is kinda useless, but you wouldn't see any updates from logout/logins from other top-level sites.

**Comment by stianst** [comment] 2024-01-29 13:06
Closing this; using partitioned cookies do not work; cookies without a SameSite will default to lax, which is okay, but we will probably set that at some point; and the cookies that need to be available are already set to None, which makes them available after redirect, but as mentioned won't make them available in iframes or for the session management, but there's no solution to that other than not rely on that, or make sure apps are in the same eTLD+1 as Keycloak.

**Closed by stianst** 2024-01-29 13:06 UTC
Labels: kind/enhancement, status/triage
