### ISSUE TITLE
Colossal consumption of CPU and RAM by getting user offline sessions

### ISSUE THREAD

**Issue by ArmanGhost** [keycloak/keycloak#11780] opened 2022-04-29 17:16 UTC
### Describe the bug

Getting user offline session consumes big amount of CPU and RAM. We found a part of code where is a problem. It is in the PR
https://github.com/keycloak/keycloak/discussions/11779

### Version

17.0.0

### Expected behavior

Typical CPU and RAM consumption

### Actual behavior

x10 CPU and RAM consumption

### How to Reproduce?

Our offline token idle time is 30 days. We have around 700 000 of offline tokens. Two for each of 350 000 users. And each user have one offline token in first days of month and another one in the end of the month. And function loadUserSessionsWithClientSessions load from DB thousands of them instead of two

### Anything else?

We have an open PR
https://github.com/keycloak/keycloak/discussions/11779

**Comment by hmlnarik** [comment] 2022-10-21 12:04
Related to #13129

**Comment by hmlnarik** [comment] 2022-10-24 11:05
Duplicate of #13340

**Closed by hmlnarik** 2022-10-24 11:05 UTC
Labels: kind/bug, area/storage, status/triage, kind/performance
