### ISSUE TITLE
Keycloak-js crasher: Missing null checks. Websites that have inline scripts without a src attribute as src attributes are not required. 

### ISSUE THREAD

**Issue by juanpin-humane** [keycloak/keycloak#20331] opened 2023-05-12 18:18 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

Keycloak-js crash loading. Missing null checks. Websites that have inline scripts without a src attribute crash. src attributes are not required. 

### Version

21

### Expected behavior

not crashing

### Actual behavior

if there is a script without a src attribute, keycloak-js doesn't load

### How to Reproduce?

Add a script tag without a source attribute to a website that loads keycloak-js

**Comment by jonkoops** [comment] 2023-05-15 16:45
Could you provide a reproducible example for this? We are actively using Keycloak JS in places like the Admin Console where there are `script` elements without a `src` attribute and we are not experiencing any issues.

**Comment by juanpin-humane** [comment] 2023-05-17 06:27
Attaching a video. I can only reproduce if the script tag is added in the html, not through JS.


https://github.com/keycloak/keycloak/assets/98841829/b43b8e83-4f8e-4796-ae7a-3221905fc5c7

**Comment by jonkoops** [comment] 2023-05-17 08:24
@juanpin-humane I [cannot reproduce](https://stackblitz.com/edit/typescript-dgw8aq?file=index.ts,index.html) what you are describing here in Firefox or Chrome. I think some code on your page must be explicitly setting `src` to `null`.

**Comment by juanpin-humane** [comment] 2023-05-17 18:32
I'll try to get you a vanilla sample nextjs app, it that seems to be related to that, I tried with a simple html file, and you are right it's a string.

If it helps, based on https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute#non-existing_attributes, attributes not set are supposed to return null, and that it's a good practice to check for nulls, it seemed like a no brainer.

**Comment by jonkoops** [comment] 2023-05-23 16:59
@juanpin-humane were you able to reproduce this in a clean environment?

**Comment by ssilvert** [comment] 2023-06-05 20:02
@juanpin-humane Since it has been a few weeks without progress, I'm going to close this one.  We can reopen if needed.

**Closed by ssilvert** 2023-06-05 20:02 UTC
Labels: kind/bug, area/adapter/javascript, status/triage, team/ui
