### ISSUE TITLE
keycloak-admin-cli add role to group by name

### ISSUE THREAD

**Issue by Maisl** [keycloak/keycloak#11101] opened 2022-04-04 14:25 UTC
### Describe the bug

When using the kcadm.sh add-roles, its not working with the parameter e.g. --gname or gpath

### Version

17.0.1

### Expected behavior

Should add a role to a group by the name of the group.

Request to keycloak should look like
http://localhost:8080/auth/admin/realms/EOS/groups?search=foo&first=0&max=2

### Actual behavior

Can not find the group if there are multiple groups 
(limit is current 2, see:)
https://github.com/keycloak/keycloak/blob/main/integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/HttpUtil.java#L72

Request to keycloak looks like
http://localhost:8080/auth/admin/realms/EOS/groups?name=foo&first=0&max=2

### How to Reproduce?

Create a Keycloak
add groups via kcadmin.sh
kcadm.sh create groups -r master -s name=foo
kcadm.sh create groups -r master -s name=bar
kcadm.sh create groups -r master -s name=foobar
kcadm.sh create groups -r master -s name=xyz

kcadm.sh create roles -r master -s name=test

kcadm.sh add-roles -r master --gname xyz --rolename test

### Anything else?

Replace attrName name with search
https://github.com/keycloak/keycloak/blob/main/integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/operations/GroupOperations.java#L32

**Comment by DirkHeinke** [comment] 2022-06-15 08:27
This looks like the problem from #8936

**Comment by ipavkovic** [comment] 2022-06-15 08:37
@DirkHeinke I do not see a relation between the different problems?

**Comment by DirkHeinke** [comment] 2022-06-15 09:34
@ipavkovic In both issues `add-roles` with `--gname` fails if you have more than 2 groups.

**Comment by keshavprashantdeshpande** [comment] 2024-10-25 22:25
@vmuzikar We can close this ticket as this is no more reproducible.

I think fixed by https://github.com/keycloak/keycloak/pull/25627/files

**Comment by shawkins** [comment] 2024-10-26 12:48
@keshavprashantdeshpande thanks for the update. Closing as out of date.

**Closed by shawkins** 2024-10-26 12:48 UTC
Labels: kind/enhancement, area/admin/cli, help wanted
