### ISSUE TITLE
Cannot delete realm with property 'realm" that has value of '' (empty string)

### ISSUE THREAD

**Issue by ManfredLange** [keycloak/keycloak#28194] opened 2024-03-25 02:23 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Somehow I managed to create realm for which the value of `realm` is the empty string (``). I can list all realms, including the defective one, using end point GET `${this.environment.kcUrl}/admin/realms?briefRepresentation=false`

The resulting entry for the realm looks similar to the following:
```json
{
  id: "e5541d6d-27f8-4da9-a6a3-541ceda02332",
  realm: "",
  displayName: "Display name 89761.29208",

  ... remainder left out for brevity ...

}
```

As a result I cannot use that name to delete the realm because the DELETE endpoint requires the realm name to be non-empty. This is the endpoint I'm using for deleting the realm is DELETE `${this.environment.kcUrl}/admin/realms/${realmName}`.

### Version

22.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

KC should not allow the creation of a realm that has the empty string as its id (not guid, not display name). It should not allow changing it to an empty string.

Alternatively, the REST API should have an endpoint that accepts the immutable id (which appears to be a UUID) to identify the realm instead of the name.

### Actual behavior

Somehow it is possible to end up with a realm that has an empty string as its name. Attached image shows drop box with nameless realm to which I cannot navigate.
![image](https://github.com/keycloak/keycloak/assets/1130812/6fdb3c18-292c-4543-bc56-2d85b8f9899b)

The second screenshot shows in a debugger the data returned from the endpoint for listing all realms. The element at index 2 has no name for the realm.
![image](https://github.com/keycloak/keycloak/assets/1130812/c1a4d39c-5c9e-43bc-9f6f-1886e5e9c543)

### How to Reproduce?

I don't know how to reproduce this. We have a test suite that uses the REST API of Keycloak to create realms or delete realms. We have run our code through a mutation test and ended up with this realm which we can't delete programmatically (yet).

Is there another option to delete a realm via the REST API that takes the GUID, i.e. the `id`, of the realm?

### Anything else?

Happy to try different things, if someone has a suggestion. Thank you!

**Comment by fikrapdso** [comment] 2024-03-25 02:49
This issue is reproduce able using create admin rest api.
url: {keyloack_url}/admin/realms
body: `{"realm":"","enabled":true}`
response: 201

**Comment by ManfredLange** [comment] 2024-03-25 03:16
Looks as if a fix was added some time ago for the scenario where a non-empty name for an existing realm is changed to an empty string. See https://github.com/keycloak/keycloak/pull/25836

This is a different scenario. Keycloak should reject empty realm names to begin with.

**Comment by kiddmi** [comment] 2024-03-26 02:48
how to create realm which the value of is the empty string (``)?,thanks

**Comment by etiksouma** [comment] 2024-03-26 14:17
Local tests with the main branch show that the issue is no longer reproducible:

With the same input I get:

{
    "errorMessage": "Realm name cannot be empty"
}

This issue got fixed in https://github.com/keycloak/keycloak/issues/17449. See https://github.com/keycloak/keycloak/pull/25836/files#diff-d76b745a8ab9f786f735e87ba7dd2642f25d76c595d9f894db496d4fe0e0e58fR520

**Closed** 2024-04-11 17:04 UTC
Labels: kind/bug, area/admin/api, team/core-iam, team/core-shared, status/auto-expire, status/expired-by-bot
