### ISSUE TITLE
not able to get members of a group created via LDAP groupmapper

### ISSUE THREAD

**Issue by mtruiz81-dev** [keycloak/keycloak#12294] opened 2022-06-01 17:28 UTC
### Describe the bug

Hi
I got an error when checking members of a given group created vla LDAP Group Mapper

```
2022-06-01 17:16:58,181 DEBUG [org.keycloak.events] (default task-6) type=LOGIN, realmId=netguard, clientId=netguard-public, userId=0450efc5-6819-4bd4-ba30-b1276212c508, ipAddress=xxxxx, auth_method=openid-connect, token_id=727e8836-1130-4ab0-b8da-e76269b3586b, grant_type=password, refresh_token_type=Refresh, scope='profile email', refresh_token_id=f28ba026-2aa8-4312-8da3-cf56c1295493, client_auth_method=client-secret, username=manuelrl, authSessionParentId=591fa8ec-3241-4358-8e45-e031d9c0e380, authSessionTabId=7wFVqb4XZws
2022-06-01 17:16:58,181 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-6) JtaTransactionWrapper  commit
2022-06-01 17:16:58,186 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-6) JtaTransactionWrapper end
2022-06-01 17:16:58,409 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-6) new JtaTransactionWrapper
2022-06-01 17:16:58,409 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-6) was existing? false
2022-06-01 17:16:58,410 DEBUG [org.keycloak.services.resources.admin.AdminRoot] (default task-6) authenticated admin access for: manuelrl
2022-06-01 17:16:58,416 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager] (default task-6) Creating LdapContext using properties: [{java.naming.ldap.factory.socket=org.keycloak.truststore.SSLSocketFactory, java.naming.security.authentication=simple, java.naming.provider.url=ldaps://hostname:636, com.sun.jndi.ldap.connect.pool=true, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.security.credentials=**************************************, java.naming.security.principal=cn=APPUSER,ou=OrganizationUnit,o=Organization,dc=com}]
2022-06-01 17:16:58,449 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-6) Uncaught server error: org.keycloak.models.ModelException: At least one condition should be provided to OR query
        at org.keycloak.keycloak-ldap-federation@11.0.0//org.keycloak.storage.ldap.idm.query.internal.LDAPQueryConditionsBuilder.orCondition(LDAPQueryConditionsBuilder.java:62)
        at org.keycloak.keycloak-ldap-federation@11.0.0//org.keycloak.storage.ldap.mappers.membership.MembershipType$1.getGroupMembers(MembershipType.java:110)
        at org.keycloak.keycloak-ldap-federation@11.0.0//org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.getGroupMembers(GroupLDAPStorageMapper.java:592)
        at org.keycloak.keycloak-ldap-federation@11.0.0//org.keycloak.storage.ldap.LDAPStorageProvider.getGroupMembers(LDAPStorageProvider.java:401)
        at org.keycloak.keycloak-services@11.0.0//org.keycloak.storage.UserStorageManager.lambda$getGroupMembers$4(UserStorageManager.java:677)
        at org.keycloak.keycloak-services@11.0.0//org.keycloak.storage.UserStorageManager.query(UserStorageManager.java:547)
        at org.keycloak.keycloak-services@11.0.0//org.keycloak.storage.UserStorageManager.getGroupMembers(UserStorageManager.java:675)
        at org.keycloak.keycloak-model-infinispan@11.0.0//org.keycloak.models.cache.infinispan.UserCacheSession.getGroupMembers(UserCacheSession.java:456)
        at org.keycloak.keycloak-services@11.0.0//org.keycloak.services.resources.admin.GroupResource.getMembers(GroupResource.java:232)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:432)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:395)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMe
```

### Version

11.0.0

### Expected behavior

return a list of member usernames

if I check a user belonging to that group I can see he has joined the group but I cannot get a full list via Group menu

**Comment by Zwordi** [comment] 2022-09-14 09:21
Hello,

I have the same bugs with 
Server Version | 16.1.0

Thanks

**Comment by hmlnarik** [comment] 2022-12-16 13:32
Duplicate of #10294

**Closed by hmlnarik** 2022-12-16 13:32 UTC
Labels: kind/bug, area/ldap, status/triage
