### ISSUE TITLE
Flaky test: Base IT(4) CookiesPathTest.testOldCookieWithWrongPath

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#16026] opened 2022-12-15 20:53 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

https://github.com/keycloak/keycloak/actions/runs/3707517764/jobs/6284172083

### Version

999-SNAPSHOT

### Expected behavior

Test always pass

### Actual behavior

Test fails randomly

### How to Reproduce?

See test failures for more information:

* https://github.com/keycloak/keycloak/actions/runs/3707517764/jobs/6284172083
* https://github.com/keycloak/keycloak/actions/runs/3707517764/jobs/6284733053

**Comment by stianst** [comment] 2022-12-16 09:10
This has also failed once in scheduled jobs recently. Haven't seen it before, and the test hasn't changed, so wondering if this could be some regression?

```
From 2022-12-10 to 2022-12-16
============================================================================================================================================
Finding details for CookiesPathTest.testOldCookieWithWrongPath
============================================================================================================================================
https://github.com/keycloak/keycloak/actions/runs/3707534454

Base IT (4)	Run base tests	2022-12-15T20:36:59.3370077Z -- [ERROR]   CookiesPathTest.testOldCookieWithWrongPath:184 
--------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by pedroigor** [comment] 2022-12-16 18:48
More investigation is needed. Shall we prioritize it?

**Comment by stianst** [comment] 2023-01-02 08:29
Closing as duplicate of https://github.com/keycloak/keycloak/issues/16132

**Closed by stianst** 2023-01-02 08:29 UTC
Labels: area/testsuite, kind/bug, area/core, flaky-test
