### ISSUE TITLE
For versions > 18.x.x client mapper is not able to override "name" for OpenID tokens

### ISSUE THREAD

**Issue by jankazim** [keycloak/keycloak#20534] opened 2023-05-24 10:02 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

For version starting 19.x.x the client dedicated mapper is not able to override "name" claim when using "profile" scope.

### Version

20.0.5

### Expected behavior

When client dedicated mapper for "Token Claim Name" ```name``` and "Property" ```email``` is created, the Generated tokens should contain the ```email``` value for the ```name``` key. No manner which scopes are requested by client application.

### Actual behavior

Even with client mapper like:
``` json
{
      "name": "name",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usermodel-property-mapper",
      "consentRequired": false,
      "config": {
        "user.attribute": "email",
        "id.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "name",
        "userinfo.token.claim": "true"
      }
    }
```
   
:x: When Client scope "profile" is set as default or Optional and requested by client application the mapper is ignored and ```<firstName + '  '+ lastName>``` value is generated instead.

:white_check_mark: If the Client scope "profile" is not present or Optional and not requested by client application the mapper is working fine.
In this case ```email``` is used for ```name```.

### How to Reproduce?

Create client with Client dedicated mapper:
Mapper type:  ```User Property```
Property: ```email```
Token Claim Name: ```name```
Claim JSON Type: ```String```
Add to ID token: ```On```
Add to access token: ```On```
Add to userinfo: ```On```

Make sure that the Client scope "profile" is present for client.
In the "Evaluate" sub tab search for 
If the scope "profile" was set ```Optional``` add it to "Scope parameter".

Check any of Generated tokens. They will not have the value of email for the "name" key.

When you remove the Client scope "profile" completely from client configuration or when you'll set is as ```Optional``` and not request it as "Scope parameter", then the mapper works as configured.

### Anything else?

The client mapper was working on 18.x.x versions even with "profile" client scope.

I've also tied workaround to add the "name" mapper directly to realm Client scopes -> profile, but no luck there.

**Comment by mposolda** [comment] 2023-05-24 10:16
Looks like a regression, so preliminary adding to Keycloak 22 to investigate what's going on.

**Comment by pedroigor** [comment] 2023-05-26 19:25
@mposolda This mapper seems redundant and does a lot of unnecessary reflection when resolving the values from the user model like username, first|last name, email, etc.

Now that root attributes are basically attributes I'm wondering if we should deprecate this one and recommend users to use the `oidc-usermodel-attribute-mapper`.

@jankazim Would `oidc-usermodel-attribute-mapper` solve your use case?

**Comment by pedroigor** [comment] 2023-05-26 20:33
@jankazim Could not reproduce the issue. Sent a PR with some tests to cover the usage herein described. See https://github.com/keycloak/keycloak/pull/20612.

**Closed by pedroigor** 2023-05-26 20:33 UTC
Labels: area/oidc, kind/bug, team/core, status/regression
