### ISSUE TITLE
ProviderConfigProperty.MULTIVALUED_LIST_TYPE is not displayed correctly

### ISSUE THREAD

**Issue by zhengyang1988** [keycloak/keycloak#16385] opened 2023-01-11 08:15 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I am developing a custom authenticator. In one of the config property on the authenticator, I need to show the MULTIVALUED_LIST_TYPE where I can select strings from a list of predefined values. Below is my java code for this config property:
```
ProviderConfigProperty roleMapping = new ProviderConfigProperty();
roleMapping.setName(ADMIN_MAPPING);
roleMapping.setLabel("Roles Mapped to Admin User");
roleMapping.setType(ProviderConfigProperty.MULTIVALUED_LIST_TYPE);
roleMapping.setHelpText("Roles Mapped to Admin User");
List<String> options = Arrays.asList("role1", "role2", "role3");
roleMapping.setOptions(options);
configProperties.add(roleMapping);
```

Below is the UI rendered by the frontend
<img width="332" alt="image" src="https://user-images.githubusercontent.com/5608908/211750565-36408e96-495c-47cd-9b49-6fc78d039231.png">

You see there's no option at all!

Below is the frontend html code corresponding to the UI screenshot above
<img width="876" alt="image" src="https://user-images.githubusercontent.com/5608908/211751260-12563809-07f2-42cd-85d2-cfb670058bd1.png">

Also I got the following error message from the console
<img width="567" alt="image" src="https://user-images.githubusercontent.com/5608908/211751926-d73a2096-d569-4c66-8bdf-048a6c30945e.png">

### Version

18.0.2

### Expected behavior

The rendered UI should contain a list of predefined options for me to choose.

### Actual behavior

The UI is an empty input box with no option at all. See the screenshot in the **Describe the bug** section above for more details.

### How to Reproduce?

You can write an authenticator with a config property of the MULTIVALUED_LIST_TYPE to reproduce. My code in the **Describe the bug** section  above can be used as reference

**Comment by ssilvert** [comment] 2023-01-20 20:04
@zhengyang1988 Have you tried this on the latest Keycloak version with the new React-based admin console?

We aren't supporting the old Angular console any more.

**Comment by raphisuter** [comment] 2023-01-26 12:43
I think this is the same issue in the latest version V20 https://github.com/keycloak/keycloak/issues/16640

**Comment by ssilvert** [comment] 2023-02-02 14:11
I'm closing this now as it is likely to be a duplicate of https://github.com/keycloak/keycloak-ui/issues/4273

**Closed** 2023-02-02 14:11 UTC
Labels: kind/bug, area/admin/ui, status/triage
