### ISSUE TITLE
Features versioning

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#24668] opened 2023-11-09 16:05 UTC
### Description

We should add versioning to features. This is to allow users to specify which version of a certain feature they want to use without enabling the new one or disabling the old one based on if the new version is enabled or disabled by default.

See https://github.com/keycloak/keycloak/issues/24252#issuecomment-1803253496

### Discussion

https://github.com/keycloak/keycloak/issues/24252#issuecomment-1803253496

**Comment by shawkins** [comment] 2023-11-16 19:43
Initially we'd allow for the \:vN suffix convention.  Unless we want to introduce a breaking change, the existing versioned keys account2, account3, and admin2 will need to still work.  There has not been a need expressed for more complex versioning such as specifying ranges, at least, or at most - presumably that's not needed in this context.  That means the version will be checked strictly for equality.

The implementation proposal is to add versioning knowledge within the current Profile.Feature enum.  This would allow us to keep the existing logic related to features, and resolve them using versioned names.  See #24811 for a prototype.  With a change like this, 

--features=account2 - will still be allowed and resolve to account2
--features=account:v2 - will appropriately resolve to account2
--features=account - will resolve to enabled for whatever account feature version is marked as a default

--features-disabled=account - will resolve to disabled for whatever account feature version is marked as a default

I'm not sure if it's needed, but there could be additional logic to look for cases that are logically inconsistent:

--features=account:v2,account:v3 - enabling multiple of the same feature, currently the code will just enable whatever appears last

Or both enabling and disabling the same feature:

--features=account:v2
--features-disabled=account

**Comment by sschu** [comment] 2023-11-17 06:54
I would say if no version is default, I would always go for the most stable version which is preview in this case just so you don't accidentally enable something that is more likely to break. With regards to having multiple version, I think the current behaviour is fine - that's just in line with how config options work to allow overriding something that was generated in earlier stages.
For enabling and disabling the same feature, I would ideally throw an error in that case and not allow it. There is no way to tell which one should have higher precedence and any choice we make might lead to unexpected behaviour.

**Comment by stianst** [comment] 2023-11-17 08:52
> Initially we'd allow for the :vN suffix convention. Unless we want to introduce a breaking change, the existing versioned keys account2, account3, and admin2 will need to still work. There has not been a need expressed for more complex versioning such as specifying ranges, at least, or at most - presumably that's not needed in this context. That means the version will be checked strictly for equality.
> 
> The implementation proposal is to add versioning knowledge within the current Profile.Feature enum. This would allow us to keep the existing logic related to features, and resolve them using versioned names. See #24811 for a prototype. With a change like this, there would be the following behavior:
> 
> --features=account2 - will still be allowed and resolve to account2 --features=account:v2 - will appropriately resolve to account2 --features=account - will resolve to enabled for whatever account feature version is marked as a default. If no version is default, should this enable a preview or experimental version?
> 
> --features-disabled=account - will resolve to disabled for whatever account feature version is marked as a default
> 
> I'm not sure if it's needed, but there could be additional logic to look for cases that are logically inconsistent:
> 
> --features=account:v2,account:v3 - enabling multiple of the same feature, currently the code will just enable whatever appears last
> 
> Or both enabling and disabling the same feature:
> 
> --features=account:v2 --features-disabled=account

Seems to make sense to me. One question is how will this look like in the CLI help and on https://www.keycloak.org/server/features

I'd also say that it's `account2` that resolves to `account:v2` for backwards compatiblity, but that we should list `account:v2` in the docs/CLI/etc.

The default version should be resolved based on first of:

1. The highest default supported version
2. The highest non-default supported version
3. The highest deprecated version
4. The highest preview version
5. The highest experimental version

The above allows enabling a disabled by default feature without specifying the version, it also allows enabling a new preview or experimental feature without specifying the version.

**Comment by shawkins** [comment] 2023-11-17 12:41
I've updated the pr to prefer the version based upon the ordering proposed by @stianst.  The help message has been updated to show the versioned form of feature key - account:v2, rather than account2.  I'll still need to clear up the help expectations and find any other documentation that refer to features in an unversioned way.

The way things stand if someone continues to use the unversioned key, e.g. docker, and a different more stable docker is introduced later, then they would automatically be moved to that version.  Do we want to document this behavior and/or recommend that for enabling features one should always use the versioned key?

> For enabling and disabling the same feature, I would ideally throw an error in that case and not allow it. There is no way to tell which one should have higher precedence and any choice we make might lead to unexpected behaviour.

Looking more at how that is handled now, this may be a follow-on issue.  The code currently treats enabled as dominant, rather than checking if there's overlap between the lists.

**Comment by shawkins** [comment] 2023-11-17 16:01
@vmuzikar @stianst @sschu we also need to be explicit about the PropertiesFileProfileConfigResolver and PropertiesProfileConfigResolver.  PropertiesProfileConfigResolver is used only with tests and the PropertiesFileProfileConfigResolver is used the quarkus server.  Most importantly they use a different key convention (they use _ instead of -) than the cli.  Do you want these paths to be version aware or just leave them alone?

Also the cli / help files have been updated to the new expectations.  This means that the expected entries will contain a lot of entries, such as docker and docker:v1, account2 and account:v2, etc.

**Comment by shawkins** [comment] 2023-11-20 17:11
> What happens if let's say v2 is enabled by default but user specifies --features=feature:v1? Do we disable v2? I'd say yes, we should. On the other hand, while it makes sense e.g. for swapping an SPI impl, doesn't make sense e.g. for themes.

Without this pr you'd currently do: --features=feature1 --features-disabled=feature2
With the pr you'd likely do: --features=feature:v1 --features-disabled=feature 

What you are proposing makes sense as long as the feature versions are mutually exclusive, rather than additive.  Are you saying that's true of everything in Profile.Feature, or are you saying that it will need to be an attribute of the Feature because some of theme represent themes.

> For newly introduced features (like the hostname e.g.), do we consider only the new syntax (hostname:v2) or both new and old (hostname2)? I believe we should accept only the new one as there's no backward compatibility burden for new features.

Moving forward I don't think you'd want to allow resolving feature versions greater than 1 by the enum name (there's a flag for that in the pr).

> For docs and CLI help, IMHO we should consider the new syntax exclusively.

There's a pr comment on this - there's no way that I could see with picocli to say that some expected values should be hidden.  So we can't for example selectively try to exclude account2 - unless we go to much greater lenghts to change where the validation is happening and how the help is built.  So for now the list of values in the help will be quite long - at a minimum feature and feature:v1 will be present for the --features help for every feature + the existing higher version entries like account2 and account:v2, etc.

> How exactly does --features-disabled work? I reckon it is relevant only if some feature is enabled by default. Does it then make sense to allow specifying version with this command, e.g. --features-disabled=feature:v1? I'd say not.

The pr does not prevent you from specifying the versioned form, but generally yes the expectation would be reference the unversioned form - do you want to enforce that?  That would clean up the options for features-disabled.

> I'd argue against introducing unversioned features and select the version based on a priority (as suggested by @stianst). Feels a bit overcomplicated without a real use case to me.

Your first point matches my understanding of why @stianst proposed that.  However I don't have any strong knowledge / opinion about whether this type of floating versioning makes any sense.

**Comment by vmuzikar** [comment] 2023-11-21 11:38
> What you are proposing makes sense as long as the feature versions are mutually exclusive, rather than additive. Are you saying that's true of everything in Profile.Feature, or are you saying that it will need to be an attribute of the Feature because some of theme represent themes.

From my perspective, mutually exclusive versions only make sense for selected features. In case of themes (which are then chosen on Realm basis) it's not desirable to disable the older version if a new one is enabled via `--features`.

> There's a pr comment on this - there's no way that I could see with picocli to say that some expected values should be hidden. So we can't for example selectively try to exclude account2 - unless we go to much greater lenghts to change where the validation is happening and how the help is built. So for now the list of values in the help will be quite long - at a minimum feature and feature:v1 will be present for the --features help for every feature + the existing higher version entries like account2 and account:v2, etc.

IMHO stating all the possibilities (with and without version) is a bit messy.

> The pr does not prevent you from specifying the versioned form, but generally yes the expectation would be reference the unversioned form - do you want to enforce that? That would clean up the options for features-disabled.

Yes, enforcing it sounds fine.

Overall, I'm starting to think if we're maybe overcomplicating it a bit. We need versioned features only on case-by-case basis and we can implement a custom behaviour then what happens when some feature version is enabled (if it's mutually exclusive or not, etc.). Maybe we can keep the current behaviour and just name new versioned features with the colon as a separator (`feature:v#`). Not sure. WDYT?

**Comment by shawkins** [comment] 2023-11-21 12:07
> IMHO stating all the possibilities (with and without version) is a bit messy.

Sure, but so is any potential workaround.

> Overall, I'm starting to think if we're maybe overcomplicating it a bit. We need versioned features only on case-by-case basis and we can implement a custom behaviour then what happens when some feature version is enabled (if it's mutually exclusive or not, etc.). Maybe we can keep the current behaviour and just name new versioned features with the colon as a separator (feature:v#). Not sure. WDYT?

Let me know if this understanding is correct:
- for disable expect only unversioned names - an exception would need to be made for account2, account3, and admin2 otherwise this would be a breaking change.
- for enable keep all of the existing names, and do not introduce anything new.  New features will be named feature[:v#] requiring some logic changes to not just use the enum name.
- on a feature by feature basis demarcate whether it's supposed to be exclusive with other versions - currently this is just applicable to account - are its versions supposed to be exclusive?
- there will be no unversioned enabled of features, and no priority based selection of a version

**Comment by vmuzikar** [comment] 2023-11-21 15:24
> Let me know if this understanding is correct:

Yeah, seems correct. And that's where I'm getting second thoughts if we should even go for this. :) Not sure how often we need a versioned features. Hostname is the first time, AFAIK. Themes are a bit different use case as it's basically just about enabling individual features (themes) rather than switching a feature impl.

**Closed** 2024-01-03 16:56 UTC
Labels: kind/enhancement, team/cloud-native, status/triage
