### ISSUE TITLE
Support for Direct Grant (Resource Owner Password Flow) against external OIDC Identity Provider

### ISSUE THREAD

**Issue by anuragensemble** [keycloak/keycloak#26116] opened 2024-01-11 07:11 UTC
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

Keycloak Version: 23.0.4

I have configured an OIDC Provider which supports Resource Owner Password Flow as an Identity Broker on Keycloak.

I have configured a Client on Keycloak with Direct Grant enabled:

![Screenshot 2024-01-11 at 12 36 03 PM](https://github.com/keycloak/keycloak/assets/11298272/9f26d504-a2c3-4f36-b16b-449af18fe9f5)

I have been trying to get an access token using the Direct grant token API:

POST http://127.0.0.1:8080/realms/<realmID>/protocol/openid-connect/token

grant_type=password
client_id=oidc-direct-client
username=<oidc-user>
password=<oidc-password>

The request returns 400 Bad Request:

{
    "error": "invalid_request",
    "error_description": "Missing form parameter: grant_type"
}

Is brokering with OIDC external IDP via Direct Grat/ROP Flow not supported ?

### Version

23.0.4

### Expected behavior

The direct grant /token API should authenticate against the external OIDC IDP and return the access token

### Actual behavior

The direct grant / token API returns 400 Bad Request - Invalid Grant

### How to Reproduce?

Configure OIDC IDP on Keycloak and an OIDC Direct grant client. And issue a token request using the client and external IDP user credentials.

### Anything else?
Use case discussed here:
https://lists.jboss.org/pipermail/keycloak-user/2017-January/009272.html

**Comment by jonkoops** [comment] 2024-01-11 11:01
Looks like this bug was reported for version 22, which is not the latest version of Keycloak. Please confirm this issue still exists in the latest version of Keycloak, or we will have to close it, as outlined in our issue reporting guidelines.

**Comment by anuragensemble** [comment] 2024-01-12 05:09
> Looks like this bug was reported for version 22, which is not the latest version of Keycloak. Please confirm this issue still exists in the latest version of Keycloak, or we will have to close it, as outlined in our issue reporting guidelines.

Verified the issue exists on 23.0.4. Updated the version in the description.

**Comment by jonkoops** [comment] 2024-01-12 11:10
Thanks for checking that @anuragensemble :+1:

**Comment by sschu** [comment] 2024-01-12 12:00
This not a bug but a missing feature. I also doubt this feature should be added since using username password grant defeats a lot of the purpose of having SSO with OIDC (i.e. not giving a user password to the client). It is not even supported anymore in OAuth 2.1.

**Comment by jonkoops** [comment] 2024-01-12 12:19
> It is not even supported anymore in OAuth 2.1.

I honestly doubt we should implement anything that his not supported here, closing this issue.

**Closed by jonkoops** 2024-01-12 12:19 UTC
Labels: kind/enhancement, team/core, area/identity-brokering

**Comment by anuragensemble** [comment] 2024-01-15 05:02
Do we feel the same way about Client Credentials flow? As that is also not supported.

**Comment by sschu** [comment] 2024-01-15 09:40
@anuragensemble I have never seen OIDC with client credentials grant so far. What exactly do you want to achieve here? You would pass the client secret to Keycloak that passes it on to the external IDP for authentication?

**Comment by anuragensemble** [comment] 2024-01-15 14:38
@sschu 
The OIDC/OAuth 2.0 provider implementations define and support multiple flows beyond the Authorization Code Grant, for non-browser flows.

While I understand that the Resource Owner Password flow is not ideal, given that the service provider gets access to the credentials, this is still a defined flow under the specification.

Resource Owner Password Flow and Client Credentials Flow become useful in API only applications integrating with an external OIDC/OAuth 2.0 providers.
While Device Grant and OIDC-CIBA flow allow authentication via out of band authentication, these are not feasible for all API use cases (automation).

I planned to use Keycloak as an OIDC broker both for my client side flow (browser redirect using Authorization Code Flow) as well as our API based flows.

For API based flows, where the customer doesn't use the UI and uses workflows to fire session APIs, I have been evaluating imperative flows such as the ROPF or the Client Credentials Flow.

Based on my understanding, Keycloak can not broker these flows between the Service and the external provider (even if they are supported by the customers' OIDC implementation), and only allows brokering for the UI based flow.

This forces us to write our own client implementation, instead of leveraging Keycloak's OIDC brokering.

**Comment by sschu** [comment] 2024-01-15 16:52
If you want to use tokens that are generated by external providers and exchange them for Keycloak tokens, you could look at the token-exchange preview feature. Besides that, I am still not sure how brokering with client credentials grants is supposed to work. Should Keycloak just pass on client id and secret to an external provider?
