### ISSUE TITLE
Custom configuration fields error

### ISSUE THREAD

**Issue by 1gluk** [keycloak/keycloak#20922] opened 2023-06-12 10:51 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the react code, there is a hardcode of expandable fields only for pre-installed social authorization providers.

When using social providers available in github (or implemented independently), this is not possible.

When the Angular admin panel was used, identity provider authors had the ability to prepare templates and extend the admin interface with them.

Due to your current implementation, it is not possible to fully use any external identity provider with additional customization fields.

### Version

21.1.1

### Expected behavior

There should not be any hardcode, all the features of providers should work correctly according to the documentation

### Actual behavior

For external identity providers, additional fields are ignored by the administrative interface

### How to Reproduce?

connect any of them and see for yourself:
https://github.com/wadahiro/keycloak-discord
https://github.com/playa-ru/keycloak-russian-providers

### Anything else?

```
export const ExtendedFieldsForm = ({ providerId }: ExtendedFieldsFormProps) => {
  switch (providerId) {
    case "facebook":
      return <FacebookFields />;
    case "github":
      return <GithubFields />;
    case "google":
      return <GoogleFields />;
    case "openshift-v3":
    case "openshift-v4":
      return <OpenshiftFields />;
    case "paypal":
      return <PaypalFields />;
    case "stackoverflow":
      return <StackoverflowFields />;
    case "linkedin":
      return <LinkedInFields />;
    default:
      return null; // <---- OMG!!!!!
  }
};
```
[ no comments](https://github.com/keycloak/keycloak/blob/ed473da22b713d599865b4779445dc843258505b/js/apps/admin-ui/src/identity-providers/component/ExtendedFieldsForm.tsx#L13-L33)

**Comment by 1gluk** [comment] 2023-06-12 11:28
@jonkoops 
see also
[apple provider custom fields](https://github.com/klausbetz/apple-identity-provider-keycloak/blob/main/src/main/resources/theme-resources/resources/partials/realm-identity-provider-apple.html)

**Comment by jonkoops** [comment] 2023-06-12 12:17
Duplicate of #15344

**Closed by jonkoops** 2023-06-12 12:17 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
