### ISSUE TITLE
Performance problem with big number of roles

### ISSUE THREAD

**Issue by lounismassinissa** [keycloak/keycloak#12885] opened 2022-07-04 08:12 UTC
### Describe the bug

We have clients with several roles (9000) and we have noticed that for the generation of the token an sql request per role is sent to the database which gives us 9000 requests. 

Authentication takes more than 10 seconds 

"select compositer0_.COMPOSITE as COMPOSIT1_19_0_, compositer0_.CHILD_ROLE as CHILD_RO2_19_0_, roleentity1_.ID as ID1_39_1_, roleentity1_.CLIENT as CLIENT2_39_1_, roleentity1_.CLIENT_REALM_CONSTRAINT as CLIENT_R3_39_1_, roleentity1_.CLIENT_ROLE as CLIENT_R4_39_1_, roleentity1_.DESCRIPTION as DESCRIPT5_39_1_, roleentity1_.NAME as NAME6_39_1_, roleentity1_.REALM as REALM8_39_1_, roleentity1_.REALM_ID as REALM_ID7_39_1_ from COMPOSITE_ROLE compositer0_ inner join KEYCLOAK_ROLE roleentity1_ on compositer0_.CHILD_ROLE=roleentity1_.ID where compositer0_.COMPOSITE=?"

The same problem is exposed on this link

https://github.com/keycloak/keycloak/discussions/11074

### Version

15.0.2

### Expected behavior

Send only one sql request to get all roles

**Comment by Cracky5457** [comment] 2023-06-21 13:31
Hello,

I can confirm

We are using roles a lot, some client contains 10 000 roles, and some of them are composite

Users have role indirectly from groups or composite roles

We are using the /userinfo endpoint to retrieve theses roles because it doesn't sound a good practice to do it in the access token directely

But unfortunately the endpoint is become very slow over years and now for some users we have a lot of issues

This is some screenshot from our analyzing tool, we can see 7,9 sec for this request, and probably thounsands of sub requests I can t put everything in the screenshot obviously


![Capture d’écran 2023-06-21 à 15 26 55](https://github.com/keycloak/keycloak/assets/12050544/b5fcc2a2-2a9b-4950-ada8-4d6a91e91515)

![Capture d’écran 2023-06-21 à 15 28 15](https://github.com/keycloak/keycloak/assets/12050544/c5eb44be-bfe0-4646-9787-943c0bcb2d0f)

**Comment by jonkoops** [comment] 2023-06-22 16:16
@Cracky5457 we no longer support Keycloak 15. Please tests this against the latest version if you want to do any sort of analysis, as too much has changed between these versions to draw conclusions.

**Comment by Cracky5457** [comment] 2023-06-26 14:47
@jonkoops 

I will upgrade to last version in few weeks, I will update this card at this moment. Honestly I don't expect a different behaviour, roles are some kind of tree (because of undirect roles) and SQL is very bad to process this kind of request so if roles was not refactored since vers 15 I expect the same result unfortunately. The issue is probably that for each user, the endpoint have to check groups/composites roles to discover all the indirect roles assigned to the user.

**Comment by jonkoops** [comment] 2023-06-26 14:55
You might be right, but this saves us the time of having to figure that out on our side. We're already quite overloaded as-is. Thanks!

**Comment by Cracky5457** [comment] 2023-07-19 10:53
Hey I can confirm this issue on version 21 and 22 

Here is an exemple running on a copy of our prod database on official docker running Keycloak 22.0.1

https://prod-clone.mycompany.eu/auth/admin/realms/myrealm/users/2472a3c9-e795-49c0-acce-2534e3c04f45/role-mappings/clients/team/composite

Here "team" is my client ID, it contain around 11 000 roles

1st request : 22 sec
2nd request : 23 sec
3nd request : 19sec

https://prod-clone.mycompany.eu/auth/admin/realms/myrealm/ui-ext/effective-roles/users/fa2db206-3eb4-403c-894a-810ebaba98e1?first=0&max=10&search=

Here is the request to get tne inherited roles of a user 

Every call between 15 and 20 sec too

So the request is very slow. And there is also a cache issue since the same requests successfully is always slow.

**Comment by jonkoops** [comment] 2023-07-19 11:02
Thanks for confirming this @Cracky5457!

**Comment by Cracky5457** [comment] 2023-07-24 15:22
@jonkoops your welcome

We (The Human Brain Project) are going to help to investigate theses issues and hopefully found some improvements. Do you have any leads on how to improve that ? 

Would it be possible to reconsider the tag "impact/low" ? For us it's not low at all, unfortunately Keycloak core feature like /userinfo are not even usable anymore, so if no fix is found we will probably have to go out of Keycloak features such as roles/groups to just keep the OIDC part and write our own Identity Manager app aside. So the impact is pretty how for users who depends of keycloak roles/groups

Note that there is an other existing ticket for Groups beeing not scalable (for this the fix is probably easier, could probably be just to rewrite in HQL/Criteria how groups are requested, but I don't think it will works for roles as it's some kind of tree that we have to iterate in SQL)

**Comment by jonkoops** [comment] 2023-07-25 08:50
@ahus1 since you are the new lead on the store team, can I ask you to take a look and see if this should get a different impact? Perhaps this needs to be re-prioritized.

**Comment by klassm** [comment] 2023-10-20 14:09
Is there an update here?

**Comment by buntyrathod** [comment] 2024-02-29 17:33
We are also facing similar issues due to big number of roles per client. I would like to help to resolve the issue.

**Comment by sschu** [comment] 2024-03-01 14:59
At least listing roles should be much faster now since https://github.com/keycloak/keycloak/pull/24012 is merged.

**Comment by buntyrathod** [comment] 2024-03-02 15:59
@sschu in our case it's an authorization operation. As we add more roles to a user, an endpoint to evaluate a permission is taking more time almost 2-3 sec. We have around 250+ roles assigned to a user.

`
export const OBTAIN_PERMISSIONS = ${'baseUrl'}/realms/${'realmName'}/protocol/openid-connect/token
`

**Comment by pedroigor** [comment] 2024-03-04 20:26
@buntyrathod Looks like we are discussing a different issue then. If you can open an issue for `authorization-services` we can discuss the performance issues you are facing when invoking the token endpoint.

@lounismassinissa Can you please check if the latest release helps to address the original issue?

**Closed** 2024-03-18 23:04 UTC
Labels: kind/bug, impact/low, area/storage, kind/performance, team/core-iam, status/auto-expire, status/expired-by-bot

**Comment by rmoustgaard** [comment] 2025-01-28 06:12
Issue still exists in Keycloak 26.
