### ISSUE TITLE
Potential issue with handling HTTP/2 over TLS in Quarkus distribution

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#13315] opened 2022-07-25 18:07 UTC
### Describe the bug

**DISCLAIMER:** This issue requires further investigation as it's not reproducible with `curl`, only with certain Golang version. Due to this fact, it is possible it might not be an issue in KC at all and rather an issue with Golang. Keeping this as a tracker for reference in case we run into a similar issue in the future.

This affects only Quarkus distribution, WildFly is fine.

### Version

main

### Actual behavior

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-14) Uncaught server error: java.lang.RuntimeException: java.io.IOException: Underlying input stream returned zero bytes
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:61)
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
	at com.sun.proxy.$Proxy46.getDecodedFormParameters(Unknown Source)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:171)
	at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Underlying input stream returned zero bytes
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider.parseForm(FormUrlEncodedProvider.java:88)
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:57)
	... 57 more
```

### How to Reproduce?

Build [this reproducer](https://github.com/vmuzikar/playground/blob/quarkus-http2-reproducer/main.go) with Go 1.13.

**Comment by vmuzikar** [comment] 2022-07-25 18:09
@DGuhr @pedroigor jFYI

**Comment by DGuhr** [comment] 2022-07-25 18:11
One other data point: https://github.com/keycloak/keycloak/discussions/10931

**Comment by vmuzikar** [comment] 2022-07-25 18:22
@DGuhr Did try only two so far: 1.13 (affected) and 1.16 (unaffected). Architecture doesn't affect this, acts the same at x64 and arm64.

**Comment by domWinter** [comment] 2022-08-03 11:27
Hi, might be related: 
I am getting the same error when posting form data to a quarkus keycloak from node.js with axios or node-fetch.

node version: v16.16.0
node-fetch: 3.2.10
axios: 0.27.2

**Comment by DGuhr** [comment] 2022-08-04 07:05
hi @domWinter thanks for the data point. added it here: https://github.com/quarkusio/quarkus/issues/26937#issuecomment-1204836209

Tracking issue at quarkus repo is https://github.com/quarkusio/quarkus/issues/26937

RESTEASY tracking issue: https://issues.redhat.com/browse/RESTEASY-3175

**Comment by Jess103** [comment] 2022-08-05 02:30
I'm having the same issue right now.
- Keycloak 18.0.1 over JDK11, https(443), CentOS7
- Windows Chrome to access keycloak username-password-form
 
It worked totally fine w/ https until this morning.
But after I removed all cookies in the browser > close then open the browser again, it started happen like that for user authentication; when I type my username, password in the username-password-form and click sign-in, I get the exactly same "Underlying input stream returned zero bytes".
I tested http(80) and found out that this works fine.
Restarting kc.sh doesn't help.
What else can I try?

**Comment by jsorah** [comment] 2022-08-29 19:34
I can see this issue on a Keycloak deployment running on Openshift 4.10.  This was observed with the latest "nightly" image.

Our Openshift cluster has HTTP/2 enabled on the ingress controllers.  

When we attempt to access the admin console through a route configured with `reencrypt`, thus delegating internal connectivity to the ingress, it fails with a similar stacktrace as the initial comment on this issue:

```
2022-08-29 17:57:52,245 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-36) Uncaught server error: java.lang.RuntimeException: java.io.IOException: Underlying input stream returned zero bytes
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:61)
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
	at com.sun.proxy.$Proxy45.getDecodedFormParameters(Unknown Source)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Underlying input stream returned zero bytes
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider.parseForm(FormUrlEncodedProvider.java:88)
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:57)
	... 59 more
```

When we change to `passthrough` (forcing negotiation to the client) - it works fine and we can authenticate and use the admin console without any problems.

A second reproducer for this could be setting up Keycloak on CodeReady Containers (https://crc.dev/) and making sure the following conditions are met:

- HTTP/2 enabled on ingress controller via `oc -n openshift-ingress-operator annotate ingresscontrollers/default ingress.operator.openshift.io/default-enable-http2=true`
- Install Keycloak Operator (used the new operator)
- Configure Keycloak
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: vanilla
  namespace: test-operator
spec:
  disableDefaultIngress: true
  hostname: keycloak.apps-crc.testing
  instances: 1
  tlsSecret: keycloak-x509-https-secret
```
- Custom Service with Openshift Service CA cert
```
kind: Service
apiVersion: v1
metadata:
  name: keycloak-custom-service
  namespace: test-operator
  labels:
    app: sso
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: keycloak-x509-https-secret
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: keycloak
```
- Configure Route
```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: test
  namespace: test-operator
  labels:
    app: sso
spec:
  host: keycloak.apps-crc.testing
  to:
    kind: Service
    name: keycloak-custom-service
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
```

Which seem to show this will happen on Keycloak installations deployed to Openshift clusters where HTTP/2 is enabled for the cluster using the bundled ingress operator and they are using reencrypt routes.  The issue is not seen with passthrough routes.

**Comment by pedroigor** [comment] 2022-08-30 12:34
I did a simple test here using a local HAProxy and `reencrypt`. I can see backend requests going through `h2`:

```
Aug 30 09:30:26 localhost haproxy[36973]: 127.0.0.1:47748 [30/Aug/2022:09:30:26.716] mykeycloaktls~ mykeycloaktls/kc1 0/0/0/0/1 200 778 - - --NI 1/1/0/0/0 0/0 "GET https://mykeycloak/resources/bekig/admin/keycloak.v2/assets/table-scrollable.c31f0637.css HTTP/2.0"
```

And:

```
2022-08-30 09:33:59,937 INFO  [io.quarkus.http.access-log] (executor-thread-4) 127.0.0.1 - - 30/Aug/2022:09:33:59 -0300 "GET /resources/bekig/login/keycloak/img/keycloak-logo-text.png HTTP/2" 200 16382
```

But I did not get the issue you are mentioning.

I think we should try now using Openshift/k8s to see if we can reproduce. @vmuzikar Any chance to reproduce this using the operator?

**Comment by jsorah** [comment] 2022-08-30 15:02
I did try this again in the latest CRC version (using openshift 4.11 and ingress uses haproxy `2.2.24`) and I received the error.

**Comment by pedroigor** [comment] 2022-08-30 18:23
@jsorah Are you able to somehow export the HAProxy configuration so I can try it locally?

**Comment by jsorah** [comment] 2022-08-30 18:59
Was able to extract it from the router pod with:

`oc rsync -n openshift-ingress router-default-5bff7f5d8d-8mrzz:/var/lib/haproxy/conf/haproxy.config .`

Heres the relevant backend section, but attaching the whole file in case something else is usable there (its just an ephemeral dev set up)

```
# Plain http backend or backend with TLS terminated at the edge or a
# secure backend with re-encryption.
backend be_secure:test-operator:test
  mode http
  option redispatch
  option forwardfor
  balance random

  timeout check 5000ms
  http-request add-header X-Forwarded-Host %[req.hdr(host)]
  http-request add-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto http if !{ ssl_fc }
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  http-request add-header X-Forwarded-Proto-Version h2 if { ssl_fc_alpn -i h2 }
  http-request add-header Forwarded for=%[src];host=%[req.hdr(host)];proto=%[req.hdr(X-Forwarded-Proto)]
  cookie 1075147640a80bb29ada7b995751c8b0 insert indirect nocache httponly secure attr SameSite=None
  server pod:vanilla-0:keycloak-custom-service:https:10.217.0.64:8443 10.217.0.64:8443 cookie c15d02d784658bd62cc989d6fbffe0ee weight 1 ssl alpn h2,http/1.1 verifyhost keycloak-custom-service.test-operator.svc verify required ca-file /var/run/configmaps/service-ca/service-ca.crt
```
[haproxy.txt](https://github.com/keycloak/keycloak/files/9455785/haproxy.txt)

**Comment by jsorah** [comment] 2022-08-30 19:24
Oh also want to note - you have to try to POST something (ex: authenticate to admin console w/ username and password) for the error to happen.  GET appears to work just fine.

**Comment by pedroigor** [comment] 2022-08-31 21:31
@jsorah Thanks. Still not able to reproduce locally after applying your backend settings to my local HAProxy.

My `/etc/haproxy/haproxy.cfg`:

```
#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #
    log         127.0.0.1:514 local0 debug

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

    # utilize system-wide crypto-policies
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-server-ciphers PROFILE=SYSTEM

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

frontend mykeycloaktls
    # Copy the haproxy.crt.pem file to /etc/haproxy
    bind *:443 ssl crt /etc/haproxy/haproxy.crt.pem alpn h2,http/1.1
    use_backend mykeycloaktls

backend mykeycloaktls
    mode http
    option redispatch
    option forwardfor
    balance random

    timeout check 5000ms
    http-request add-header X-Forwarded-Host %[req.hdr(host)]
    http-request add-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto http if !{ ssl_fc }
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    http-request add-header X-Forwarded-Proto-Version h2 if { ssl_fc_alpn -i h2 }
    http-request add-header Forwarded for=%[src];host=%[req.hdr(host)];proto=%[req.hdr(X-Forwarded-Proto)]
    cookie 1075147640a80bb29ada7b995751c8b0 insert indirect nocache httponly secure attr SameSite=None
    server kc1 localhost:8443 cookie c15d02d784658bd62cc989d6fbffe0ee weight 1 ssl alpn h2,http/1.1 verifyhost mykeycloak verify none
```

**Comment by jsorah** [comment] 2022-09-01 12:07
@pedroigor - the versions I pulled for haproxy on my CRC were 2.2.17 (for the 4.10 based one) and 2.2.24 (for 4.11).  I would say for the use case I have, upgrading haproxy at the Openshift level is pretty much out of the question.  AFAIK it might require a net-new ingress to be configured outside of the ingress-operator.

I also have another datapoint for this issue - running Keycloak locally with self-signed HTTPS certificate and then using Burp Suite Community (https://portswigger.net/burp) and its built in browser to browse to and attempt to log in to the application also reproduces the error.  

Intercept was not required to be on, though I suspect the browser is still moving traffic through the Burps internal proxy.

**Comment by pedroigor** [comment] 2022-09-01 18:57
@jsorah Finally, thanks. :) I can confirm the error when using Burp. But I had to turn on the interception first. Then I could disable it and still get the error. Not sure why.

I think I know what is going on and I should update the issue created in Quarkus with more details.

**Comment by pedroigor** [comment] 2022-09-01 19:56
@jsorah Updated the issue in Quarkus with the steps to reproduce the problem. Let's see what comes up from it.

**Comment by jsorah** [comment] 2022-09-02 13:08
@pedroigor - I was able to set up a scenario where I could inspect the on-the-wire HTTP/2 traffic - it seems in the failing case there is an additional DATA frame sent with 0 bytes, but end of stream flag set - I suspect this might be what is tripping up the VertxInputStream "read" method (stream isn't ended, and is told to read data... of size 0).  I'm still gathering more info (wireshark captures / screenshots) and can post to the associated Quarkus issue as well once I have it.

**Comment by vietj** [comment] 2022-09-06 09:31
can you point the VertxInputStream part that performs that ? @jsorah

**Comment by geoand** [comment] 2022-09-06 09:34
https://github.com/quarkusio/quarkus/blob/2.12.0.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxInputStream.java#L23

**Comment by vietj** [comment] 2022-09-06 09:45
@jsorah can we get a reproducer that involves only `VertxInputStream` interacting with an HTTP/2 endpoint that lead to this case ?

**Comment by vietj** [comment] 2022-09-06 13:00
@jsorah can you provide a similar behavior with a simple Resteasy application (that uses Vert.x) and the VertxInputStream ? that would help a lot

**Comment by jsorah** [comment] 2022-09-06 13:05
Hi @vietj - I was able to use the reproducer created by @DGuhr  for this, which is a fairly simplistic quarkus app using vert.x and RestEasy: https://github.com/DGuhr/reproducer/tree/formPostRequest_ssl_exception

You can either use the go client he provided in the README of that branch to trigger the behavior on the server, or I also reproduced more explicitly with this python gist - https://gist.github.com/jsorah/e80e55de3c340521518bf87d2a1710ce

Let me know if that isn't quite what you were looking for.

**Comment by cescoffier** [comment] 2022-09-06 14:02
So, the issue is only happening with RESTEasy Classic. With RESTEasy Reactive, I get the expected response.

**Comment by vietj** [comment] 2022-09-06 14:15
Can we conclude it is a bug in Resteasy classic ?

**Comment by cescoffier** [comment] 2022-09-06 15:24
@vietj what is sure is: it's not a bug in Vert.x. 

I've added a BIG HACK that checks if we get an empty buffer, and when we do return -1 (finished) instead of 0):

```java
ByteBuf buffer = pooled;
        int copied = Math.min(len, buffer.readableBytes());
        if (copied > 0) {
            buffer.readBytes(b, off, copied);
            if (!buffer.isReadable()) {
                pooled.release();
                pooled = null;
            }
            return copied;
        } else {
            return -1;
        }
```

The problem is actually in `org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider`, which is not in the Quarkus realm (RESTEasy Reactive has an equivalent class implemented by @geoand). That class reads the body using `new InputStreamReader(entityStream, charset),` which throws an exception when the `read` method returns 0.

In this case, we receive an empty buffer, so `read` returns 0 and ... BOOM.

I don't believe my hack is correct, as we may receive empty buffers which are not terminal. The RESTEasy provider may need to be tweaked to handle that case.

**Comment by cescoffier** [comment] 2022-09-06 16:48
Well, yes and no.

Many protocols send empty buffers to keep the connection alive. So, it's not surprising. 
We could imagine not sending the empty buffer and blocking this particular context. So, the read method would block until the stream terminates. I tried that approach, but 1) I hate blocking, 2) it can't work without some important refactoring of resteasy classic (I need an unshared lock, with wait / synchronized / notify). There is already a synchronization protocol on the `connection` object, but my attempt to use it was unreliable.

**Comment by jsorah** [comment] 2022-09-13 19:24
@pedroigor looks like Quarkus 2.12.2.Final has landed with the necessary change (thanks all involved) - I was going to raise a PR for the version bump in Keycloak (using the script you wrote), but getting a test error when I do local validation of the quarkus dist.

This appears to be on the `org.keycloak.it.cli.dist.HostnameDistTest`

```
2022-09-13 13:53:52,745 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
ERROR: Unexpected error when starting the server in (development) mode
ERROR: Failed to start quarkus
ERROR: Metaspace

```

running with whats currently set in main does not fail this test.

**Comment by pedroigor** [comment] 2022-09-14 11:05
@jsorah Working on it, thanks.

**Comment by pedroigor** [comment] 2022-09-14 14:32
Sent https://github.com/keycloak/keycloak/pull/14409.

**Closed** 2022-09-14 18:36 UTC
Labels: kind/bug, area/dist/quarkus
