### ISSUE TITLE
Reset password flow fails with "Page has expired" error when Kerberos authentication is enabled in the browser flow

### ISSUE THREAD

**Issue by ynojima** [keycloak/keycloak#20637] opened 2023-05-30 01:45 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

When Kerberos authentication is enabled in the browser flow, non-kerberos authentication user cannot complete the reset password flow because "Page has expired" error happens.

### Version

RH-SSO 7.6

### Expected behavior

HTTP 200 success response should be returned after resetting the password.

### Actual behavior

HTTP 401 error response is returned after resetting the password.

### How to Reproduce?

1. Create a new realm
2. Create a new RH-SSO local user
3. Make "Kerberos" execution in the "Browser" flow requirement "ALTERNATIVE"
(No need to configure kerberos User Federation config for reproducing the error)
4. Make "Forgot password" option "ON"
5. Go "Realm Settings" -> "Email" tab, and configure "Host" and "From" fields. 
6. Open the login form page
7. Navigate to the password reset form page by clicking "Forgot Password?" link
8. Fill the "Username or email" field with the user created in the step2, and submit

The request will be processed properly, the reset link email will be sent, but the HTTP response will have  HTTP status code 401 and "WWW-Authenticate: Negotiate" header, which instructs the browser to do Kerberos authentication.
If the browser is not configured to handle Kerberos authentication, the browser will re-submit the same HTTP request,
but RH-SSO server will reject the request because the session code in the request is already consumed in the previous request, and RH-SSO server will return the "Page has expired" page.

There is a similar issue([KEYCLOAK-17218](https://issues.redhat.com/browse/KEYCLOAK-17218)),  but the issue still persists in RH-SSO 7.6.0.

### Anything else?

RH-SSO server must not add "WWW-Authenticate: Negotiate" header to the "Reset password" response even when Kerberos authentication execution is enabled.

**Workaround(only works for wildfly based distribution)**
Following JBoss CLI commands mitigates the issue by removing the "WWW-Authenticate: Negotiate" header from the "Reset password" response.

```
/subsystem=undertow/configuration=filter/expression-filter=clear-www-authenticate-header-filter:add(expression="clear(attribute='%{o,WWW-Authenticate}', pre-commit='true')")
/subsystem=undertow/server=default-server/host=default-host/filter-ref=clear-www-authenticate-header-filter:add(predicate="method(POST) and path-prefix(/auth/realms/<PUT_YOUR_REALM_NAME_HERE>/login-actions/reset-credentials)")
```
Please note this workaround only works for Wildfly(JBoss-EAP) based distribution. For Quarkus-based distribution, it cannot be used and need to fix the root cause.

**Comment by douglaspalmer** [comment] 2023-10-10 21:52
I cannot reproduce this with HEAD using Safari, Chrome, Firefox and Vivaldi. Closing for now. Feel free to reopen if this is still an issue. Maybe the issue is specific to your environment or OS.

**Comment by ynojima** [comment] 2023-10-10 22:16
Did you test with RH-SSO?

**Comment by douglaspalmer** [comment] 2023-10-10 23:08
> Did you test with RH-SSO?

Yes, with all 4 browsers listed above.

**Comment by ynojima** [comment] 2023-10-11 02:12
Sorry, I added Step 5. to the reproducer.
This issue still persists with RH-SSO 7.6.5, and Chrome for Windows v117.0.5938.134.
I attached a HAR file that captures traffic between the browser and the RH-SSO server when I reproduced the issue.
Could you look into it?
The POST request to "http://sso1.rhlab1.sharplab.org:8080/auth/realms/issue-20637/login-actions/reset-credentials" failed with Status code `401` is the issue.

[issue-20637.zip](https://github.com/keycloak/keycloak/files/12864106/issue-20637.zip)

**Comment by ynojima** [comment] 2023-10-11 02:19
@douglaspalmer, As I don't have right to reopen the issue, could you reopen this?

**Comment by douglaspalmer** [comment] 2023-10-11 06:27
I already did your new step 5 and I also configured an email address for the user when I tried to reproduce. I'm guessing this issue is specific to Chrome on Windows. I don't have access to Windows in order to look deeper.

**Comment by abstractj** [comment] 2023-10-11 15:00
@douglaspalmer if Keycloak is not impacted by this issue, please feel free to close the issue.

**Comment by abstractj** [comment] 2023-10-11 15:57
Reopening it until have more clarity about it.

**Comment by mposolda** [comment] 2023-10-12 09:33
@ynojima @douglaspalmer I've managed to reproduce the issue on Linux and Firefox after some digging into this. After step 8, the browser sends request to endpoint `...login-actions/reset-credentials` and server responds with `401` and header `WWW-Authenticate: Negotiate`. But for reproducing the issue, it is also needed that browser answers to this and sending to server the Negotiate header. So browser needs to send another request to `...login-actions/reset-credentials` with some header like `Authorization: Negotiate <your-kerberos-token-here>`. I am not sure if Windows does this automatically (maybe when you are on Windows domain?). But on Linux, I need to have valid kerberos ticket (initiated manually by `kinit ...` command in my case). Without this ticket, the browser doesn't send the follow-up request with `Authorization: Negotiate <your-kerberos-token-here>`, which is needed in my environment to reproduce this bug.

So I am adding slightly modified steps to reproduce, which worked for me.

1. Create a new realm
2. Create a new Keycloak local user
3. Create LDAP provider with Kerberos supported and valid kerberos configuration (may require setup of SPNEGO on your laptop and setup of `/etc/krb5.conf` or other platform config file. Also requires setup of browser etc. See our Kerberos docs for more details.). This step should automatically switch Kerberos authenticator to ALTERNATIVE. It is good to verify at this step that you are able to login as Kerberos user to your realm
4. Make "Forgot password" option "ON"
5. Go "Realm Settings" -> "Email" tab, and configure "Host" and "From" fields to make sure that emails are possible to send
6. Open the login form page and make sure that you don't yet have the valid kerberos ticket
7. Navigate to the password reset form page by clicking "Forgot Password?" link
8. Now obtain Kerberos ticket from your server with `kinit hnelson@KEYCLOAK.ORG` (or other user according to your config). This step is needed in my environment to make sure that another request to `reset-credentials` with `Authorization: Negotiate ...` would be send in next steps (as I've described above)
9. Fill the "Username or email" field with the user created in the step2, and submit

If not possible to write manually on your laptop, it should be possible to write automated test for this (See the tests in package `org.keycloak.testsuite.federation.kerberos` for the details)

 I suppose the fix should make sure that `SpnegoAuthenticator` is not triggered when the authentication flow is forked (The "Forked" flow happens after reset-credentials). Alternatively, we can ignore `SpnegoAuthenticator` just based on URL (Something like was done as workaround in Windows environment, but we can do that programatically on the server).

**Comment by ynojima** [comment] 2023-10-13 15:21
Thank you for identifying a way to reproduce the issue on non-windows environment.

>But for reproducing the issue, it is also needed that browser answers to this and sending to server the Negotiate header. 
>So browser needs to send another request to ...login-actions/reset-credentials with some header like Authorization: Negotiate <your-kerberos-token-here>. 
>I am not sure if Windows does this automatically (maybe when you are on Windows domain?).

Yes, to reproduce the issue, the browser need to answer the HTTP response with `WWW-Authenticate: Negotiate` header,
but on Windows, even on non-domain environment, Chrome and Edge answer with a request without `Authorization: Negotiate <kerberos-token>` header.
The request is a just a repeat of previous POST request to `...login-actions/reset-credentials`, and RH-SSO server rejects it becasue the session code in the request has been already consumed in the previous request,
Please see the `.har` attached in previous comment.

**Comment by mposolda** [comment] 2023-10-26 08:49
Not strictly a blocker for Keycloak 23, so adding to 24. But if we can have this in Keycloak 23, it can be nice.

**Closed** 2024-03-12 13:23 UTC
Labels: area/authentication, kind/bug, priority/important, team/rh-iam, team/core-clients, backport/24.0
