### ISSUE TITLE
WebApplicationException error log for every error response

### ISSUE THREAD

**Issue by megicivovic** [keycloak/keycloak#9187] opened 2021-12-16 10:28 UTC
### Describe the bug

We have been seeing a lot of these in Sentry after upgrade to Keycloak 15

```
WebApplicationException: HTTP 200 OK
    at org.keycloak.services.resources.IdentityBrokerService.parseSessionCode(IdentityBrokerService.java:1065)
    at org.keycloak.services.resources.IdentityBrokerService.performLogin(IdentityBrokerService.java:372)
    at jdk.internal.reflect.GeneratedMethodAccessor645.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
...
(72 additional frame(s) were not displayed)

unexpectedErrorHandlingRequestMessage
```

There was a change in the IdentityBrokerService in this [commit](https://github.com/keycloak/keycloak/commit/41dc94fead4c20560e0dd96c3efbd7bd10a484b6#diff-e44efb607cb8cb833e99677c01e7fc10d67afc6ee54ce4faf06a01f5acaf50e7R1065)  (line 1065 and so on) that probably caused this. Can you explain why was this changed?

### Version

15.0.2

### Expected behavior

Expected behavior is not to log this as an error

### Actual behavior

Exception being thrown for every error status code

### How to Reproduce?

Try to Login with Google that fails

**Comment by rizkykojek** [comment] 2021-12-28 16:23
@megicivovic  I found too on my sentry, but I don't know how to repro this case. Could you elaborate how to repro this case?

**Comment by megicivovic** [comment] 2021-12-29 10:31
> @megicivovic I found too on my sentry, but I don't know how to repro this case. Could you elaborate how to repro this case?

Try to login with third party idp (Google, Microsoft) which you know would fail (i.e. because of invalid redirect uri or permissions)...Unfortunately, there is nothing you can do about it, since this is Keycloak internal code...We just silenced these alerts for now...

**Comment by lraynal** [comment] 2022-10-17 12:45
Hi, this should not be sending an ERROR when the problem is a third party. 
`
ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-136) unexpectedErrorHandlingRequestMessage: javax.ws.rs.WebApplicationException: HTTP 200 OK
ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-136) unexpectedErrorHandlingRequestMessage: javax.ws.rs.WebApplicationException: HTTP 302 Found
ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-94) unexpectedErrorHandlingRequestMessage: javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
`

**Comment by Sebastian-Wilhelm** [comment] 2022-11-15 09:41
I'll got the same errors, any success getting to the root cause? 

ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-136) unexpectedErrorHandlingRequestMessage: javax.ws.rs.WebApplicationException: HTTP 200 OK
ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-136) unexpectedErrorHandlingRequestMessage: javax.ws.rs.WebApplicationException: HTTP 302 Found
ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-94) unexpectedErrorHandlingRequestMessage: javax.ws.rs.WebApplicationException: HTTP 400 Bad Request

**Comment by simoneguzzi** [comment] 2023-12-05 14:27
This has been a very noisy error in our self-hosted instance as well. Unfortunately, I don't have additional details to provide.

**Comment by patrickbadleyupstart** [comment] 2024-02-15 13:27
@mposolda I have never contributed before, but I think this behavior could be improved with a simple change such as this: https://github.com/keycloak/keycloak/pull/27054. Please take a look and advise on if this is a legitimate fix and how to get my PR merged.

**Comment by pedroigor** [comment] 2024-03-06 21:19
Closing because the corresponding PR was closed.

**Closed** 2024-03-06 21:19 UTC
Labels: kind/bug, area/core, help wanted, area/identity-brokering, team/core-iam
