### ISSUE TITLE
Error when I modify the user which uid is Chinese.

### ISSUE THREAD

**Issue by jz8132543** [keycloak/keycloak#12287] opened 2022-06-01 09:09 UTC
### Describe the bug

Error when I modify the user which uid is Chinese.
```
Error! Could not execute the password modify extended operation for DN [uid={There is chinese text},ou=user,dc=domains,dc=com]
```
But when i modify the project with uid to english everything works fine.
I am using LDAP as User Federation. Below is the LDAP log.
```
62972a25 conn=1997 fd=28 ACCEPT from IP={There is my IP}:32792 (IP=0.0.0.0:636)
62972a25 conn=1997 fd=28 TLS established tls_ssf=256 ssf=256
62972a25 conn=1997 op=0 BIND dn="cn=admin,dc=dora,dc=im" method=128
62972a25 conn=1997 op=0 BIND dn="cn=admin,dc=dora,dc=im" mech=SIMPLE ssf=0
62972a25 conn=1997 op=0 RESULT tag=97 err=0 text=
62972a25 conn=1997 op=1 EXT oid=1.3.6.1.4.1.4203.1.11.1
62972a25 conn=1997 op=1 PASSMOD id="uid=??,ou=user,ou=mail,dc=dora,dc=im" new
62972a25 conn=1997 op=1 RESULT oid= err=32 text=
```

### Version

18.0.0

**Comment by hmlnarik** [comment] 2022-12-13 14:37
Thanks for reporting this issue. It is possible that it is not Keycloak but rather the LDAP server which constraints the ID change to e.g. ASCII characters.

Due to lack of information (LDAP server) and lack of a reproducer we are not able to triage this issue effectively. Due to this we are closing the issue, but feel free to reopen the issue when you are able to provide more information and steps to reproduce the issue.

**Closed by hmlnarik** 2022-12-13 14:37 UTC
Labels: kind/bug, area/ldap, status/triage
