### ISSUE TITLE
OutOfMemory Error persists in HA mode

### ISSUE THREAD

**Issue by ammarhaiderak** [keycloak/keycloak#27244] opened 2024-02-22 16:14 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

So we have setup the keycloak on our Kubernetes Cluster. Every now and then the keycloak crashes with OutOfMemory Errors. The garbage collection doesn't kick in as expected, it's also observed that the available memory on 
keycloak admin dashboard drops gradually and the service crashes when no more free memory is available. 
Everything is configured as per the recommendations from official documentation.

We have to cycle the pods to bring back the service. 

We never had this issue on staging, the staging environment is a mirror of production in terms of configuration.

**Same result** with or without the **startup script**

Following is our configuration:

1. 2 replicas 
2. JAVA_OPTS_APPEND  -Djgroups.dns.query=keycloak-hl -Xms1024m -Xmx2048m   

### Dockerfile

```
FROM quay.io/keycloak/keycloak:21.1 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak


RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:21.1 as runner
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ADD --chown=keycloak:keycloak providers/ /opt/keycloak/providers/

ENV KC_DB=postgres

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

### StatefulSet

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "standardLabels" . | nindent 4 }}
spec:
  replicas: 2
  serviceName: {{ .Release.Name }}-hl
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          args: ["start"]
          env:
          - name: JGROUPS_DISCOVERY_PROTOCOL
            value: dns.DNS_PING
          # Set DNS Name to keycloak-headless service
          - name: JGROUPS_DISCOVERY_PROPERTIES
            value: "dns_query=keycloak-hl.default.svc.cluster.local"
          - name: CACHE_OWNERS_COUNT
            value: '2'
          - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
            value: '2'
          # Allows use of a LoadBalancer
          - name:  PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KC_CACHE_STACK
            value: kubernetes
          - name: JAVA_OPTS_APPEND
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'java.opts.append'
          - name: KEYCLOAK_ADMIN
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.admin'
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: "keycloak-admin-password"
          - name: KC_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.hostname'
          - name: KC_PROXY
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.proxy'
          - name: KC_HOSTNAME_STRICT_BACKCHANNEL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.hostname.strict.backchannel'
          - name: KC_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.db'
          - name: KC_DB_URL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.db.url.host'
          - name: KC_DB_URL_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.db.url.port'
          - name: KC_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.db.username'
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: "kc-db-password"
          - name: KC_DB_URL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: 'kc.db.url.database'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          volumeMounts:
            - name: startup
              mountPath: "/opt/jboss/startup-scripts"
              readOnly: true
      
      volumes:
        - name: startup
          configMap:
            name: keycloak-startup
            defaultMode: 0555
```

### headless service

```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hl
  labels:
    {{- include "standardLabels" . | nindent 4 }}
spec:
  clusterIP: "None"
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}

```

### Startup Script Configmap
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-startup
data:
  keycloak-startup.cli: |
    embed-server --server-config=standalone-ha.xml --std-out=echo
    batch

    echo * Setting CACHE_OWNERS to "${env.CACHE_OWNERS}" in all cache-containers

    /subsystem=infinispan/cache-container=keycloak/distributed-cache=sessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:1})
    /subsystem=infinispan/cache-container=keycloak/distributed-cache=authenticationSessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:1})
    /subsystem=infinispan/cache-container=keycloak/distributed-cache=actionTokens:write-attribute(name=owners, value=${env.CACHE_OWNERS:1})
    /subsystem=infinispan/cache-container=keycloak/distributed-cache=offlineSessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:1})
    /subsystem=infinispan/cache-container=keycloak/distributed-cache=clientSessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:1})
    /subsystem=infinispan/cache-container=keycloak/distributed-cache=offlineClientSessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:1})
    /subsystem=infinispan/cache-container=keycloak/distributed-cache=loginFailures:write-attribute(name=owners, value=${env.CACHE_OWNERS:1})

    run-batch
    stop-embedded-server

```

### Version

21.1

### Regression

- [ ] The issue is a regression

### Expected behavior

1. the memory be cleaned with proper garbage collection.
2. and/or the service should recover on crash.  

### Actual behavior

```
2024-02-22 09:20:55,736 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-3010) HTTP Request to /realms/our-realm/login-actions/authenticate?session_code=oP8LIhik3AZTWgEuzm61ZUupDy1Y6UWukgwJtnRsO5w&execution=88060fde-bc31-4f54-85f7-cf382cf429fe&client_id=our-client&tab_id=mwYaWfJ_9mQ failed, error id: c2af2ab5-5bc3-4f45-b6d5-6325a686099d-58: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:20:55,736 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3146) Failed to create error page: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:20:52,583 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3058) Failed to create error page: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:21:04,177 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3191) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:21:01,281 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-3070) HTTP Request to /realms/our-realm/login-actions/authenticate?session_code=AccL1woO8m7ayysVYukdwECbw--To-VuwBx_Y9dbnnM&execution=88060fde-bc31-4f54-85f7-cf382cf429fe&client_id=our-client&tab_id=n36YwscY-MY failed, error id: c2af2ab5-5bc3-4f45-b6d5-6325a686099d-62: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:19,753 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3109) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:22,485 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3096) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:22,492 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3127) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:22,495 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3131) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:24,291 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3130) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:24,292 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3138) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:39,980 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3145) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:49,207 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3042) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:55,769 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3034) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:55,769 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3174) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:55,770 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3173) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:57,663 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3125) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:57,665 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3176) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:57,666 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3179) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:57,667 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3185) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:22:58,604 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3190) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
2024-02-22 09:23:00,460 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3045) Uncaught server error: java.lang.OutOfMemoryError: Java heap space
```

### How to Reproduce?

deploy with this configuration in production

### Anything else?

https://jimops.io/highly-available-keycloak-on-kubernetes
https://www.keycloak.org/getting-started/getting-started-kube
https://www.keycloak.org/server/configuration-production

**Comment by sschu** [comment] 2024-02-23 10:25
Can you please try to reproduce this with the latest Keycloak version? Also, your cache settings seems to be for the widlfly-based Keycloak but Keycloak ist based on Quarkus since Keycloak 20 and the cache configuration works differently there.

**Comment by ammarhaiderak** [comment] 2024-02-24 00:48
upgrading to v22

was facing this issue after the upgrade:
```
2024-02-23 22:02:40,871 WARN [org.keycloak.services] (executor-thread-17) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: Unable to find factory for AuthenticatorFactory: no-cookie-redirect did you forget to declare it in a META-INF/services file?
```

On further investigation, I was able to get to the root of the problem. It was due to the openshift as keycloak discontinued supporting openshift, so I had to import it as a jar.


https://github.com/keycloak-extensions/keycloak-openshift-ext/blob/main/pom.xml

**Comment by stianst** [comment] 2024-02-26 09:09
I'm closing this as it's reported against an older and no longer supported release. If the problem remains in Keycloak 23 and you have identified an issue in Keycloak please create a new issue with steps to reproduce, but if you just need help on configuring it properly please see https://www.keycloak.org/community for how to get help.

**Closed by stianst** 2024-02-26 09:09 UTC
Labels: kind/bug, area/infinispan, status/triage, team/core-shared
