### ISSUE TITLE
Group names with  slash

### ISSUE THREAD

**Issue by phasianus** [keycloak/keycloak#19447] opened 2023-03-30 13:51 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

In our organization we some have groups with slash (`/`) in its names. If we import them into keycloak groups is it ok, but there is plenty of errors from inner structures of keycloak. Typical problem is here: 

https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java#L683

It seams to be, keycloak groups cannot have slash in names. 

'

### Version

20.0.1

### Expected behavior

Group names witth slash.

### Actual behavior

Erros in console when displaying users groups.

### How to Reproduce?

Create/Import groups with slash in its name, assign users, then try to display users groups.

**Comment by pedro-hos** [comment] 2023-04-04 02:18
![ezgif com-crop](https://user-images.githubusercontent.com/8390247/229669621-e35761a7-bda9-4c7d-95cf-053bee80e10b.gif)

I can't reproduce the issue on Keycloak 21.0.1. I've imported the `foo/bar` role from my LDAP with users assigned to that role, and everything works well. 

There's something that you can share on how to reproduce the issue/bug?

Thanks

**Comment by jonkoops** [comment] 2023-04-05 11:26
If this issue can no longer be reproduced then let us know so it can be closed.

**Comment by hmlnarik** [comment] 2023-04-13 12:29
Closing since the issue cannot be reproduced (anymore?)

**Closed by hmlnarik** 2023-04-13 12:29 UTC
Labels: kind/bug, area/ldap, team/store, status/triage
