### ISSUE TITLE
Slow User Search in Keycloak with Large User Base

### ISSUE THREAD

**Issue by nirweb-ir** [keycloak/keycloak#33166] opened 2024-09-21 18:18 UTC
### Description

Hello,

I am relatively new to using Keycloak, and I recently migrated my existing user base, which consists of over 16 million users, to Keycloak (using its default PostgreSQL database). However, I am currently facing a significant issue with searching for users, both in the Admin Console and via the REST API.

In both scenarios, searching for a username can take up to a minute. My server resources are adequate, so there are no issues on my end regarding resource limitations. It appears that Keycloak's search functionality is severely underperforming when dealing with millions of users.

This performance issue is a major concern for us, and I would appreciate any guidance or improvements that can be made to address this problem.

Thank you.

### Details

We are running Keycloak version 25.0.5 with a PostgreSQL database. We have not modified any default PostgreSQL configurations.

**Comment by dalbani** [comment] 2024-09-21 20:48
I wouldn't be surprised if the issue has the same cause as https://github.com/keycloak/keycloak/issues/12671.
By the way, due to the changes in https://github.com/keycloak/keycloak/pull/22285, the custom index needs to be something like:
```
CREATE INDEX IF NOT EXISTS idx_user_attribute_name_lower_value ON public.user_attribute USING btree (name, lower(value));
```

**Comment by nirweb-ir** [comment] 2024-09-22 05:05
> I wouldn't be surprised if the issue has the same cause as #12671. By the way, due to the changes in #22285, the custom index needs to be something like:
> 
> ```
> CREATE INDEX IF NOT EXISTS idx_user_attribute_name_lower_value ON public.user_attribute USING btree (name, lower(value));
> ```

Thank you for your prompt response!

I have two specific issues:

I want to use the REST API to search for "username."
I want to search for a "username" in the Admin Console.
Based on my understanding, these searches occur on the "username" in the user_entity table. Will your suggested solution resolve my issues for both cases, and what specific command should I execute for this?

**Comment by jonkoops** [comment] 2024-09-22 14:55
Possible duplicate of #31739?

**Comment by nirweb-ir** [comment] 2024-09-27 14:17
> I wouldn't be surprised if the issue has the same cause as #12671. By the way, due to the changes in #22285, the custom index needs to be something like:
> 
> ```
> CREATE INDEX IF NOT EXISTS idx_user_attribute_name_lower_value ON public.user_attribute USING btree (name, lower(value));
> ```
thank you very much With your help, I used the following query and my problem was completely solved

> ```
> CREATE INDEX idx_user_entity_username ON "public"."user_entity"(username);
> ```

**Closed** 2024-09-27 14:18 UTC
Labels: kind/enhancement, status/triage
