### ISSUE TITLE
[Regression] keycloak 22 - enabling "Email as username" breaks "Create user" via Administration Console

### ISSUE THREAD

**Issue by philipreimer** [keycloak/keycloak#23321] opened 2023-09-18 11:53 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

It is not possible to create users in the Administration Console by filling out only the mandatory fields when "Email as username" is enabled in the realm settings.

### Version

22.0.3

### Expected behavior

The Create user form should **not** contain any field for Username. It should contain just the Email field or at least only the Email field should be marked as mandatory.

Filling out only the Email field and clicking Create should create the user.

### Actual behavior

The Create user form contains fields for both Username and Email. Only Username is indicated as mandatory.

Filling the Username field will enable the Create button.

But clicking the Create button results in the following error:

![kc22-create-user-fail](https://github.com/keycloak/keycloak/assets/5737222/6bad6f39-c2db-44ac-86af-a0f9ef5feb8c)

Only when filling both Username and Email keycloak creates the user:

![kc22-create-user](https://github.com/keycloak/keycloak/assets/5737222/a8193bb5-4011-4e62-b0df-ea5ac61976c2)

But the resulting User details screen only displays the email, no username.

![kc22-user-created](https://github.com/keycloak/keycloak/assets/5737222/e787bee8-2b3f-4ace-be5e-fb23183b9054)

Also, the list of users displays the email value for both Username and Email, although a different value was given for Username when creating the user.

![kc22-user-list](https://github.com/keycloak/keycloak/assets/5737222/23a31fc6-394e-4a26-b974-db40e942d5ba)

### How to Reproduce?

1. docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin --rm --name keycloak quay.io/keycloak/keycloak:nightly start-dev
2. Go to http://localhost:8080/admin/ and login
3. Create a new realm named "test"
4. Go to http://localhost:8080/admin/master/console/#/test/realm-settings/login and enable "Email as username"
5. Go to http://localhost:8080/admin/master/console/#/test/users and click "Add user"
6. Fill the "Username" field with "foo@bar.com" and click "Create"
7. See error message "Could not create user: User name is missing"
8. Fill the "Username" field with "foo" and the "Email" field with "foo@bar.com" and click "Create"
9. See that the user has been created but the "User details" screen only displays the email.
10. Go to http://localhost:8080/admin/master/console/#/test/users
11. See that the "User list" displays "foo@bar.com" for both "Username" and "Email"

### Anything else?

In Keycloak 21.1.2 the "Create user" form only contains the "Email" field if "Email as username" is enabled for the realm - although the field is not marked as mandatory.

Filling only the "Email" field and clicking "Create" successfully creates the new user.

**Comment by ssilvert** [comment] 2023-09-18 18:51
I have recreated this in the latest nightly.

**Comment by ssilvert** [comment] 2023-09-18 18:52
Whoever fixes this, please create a regression test so it doesn't happen again.

**Comment by agagancarczyk** [comment] 2023-09-23 13:47
Fixed in https://github.com/keycloak/keycloak/pull/23484

**Closed by agagancarczyk** 2023-09-23 13:47 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui

**Comment by jonkoops** [comment] 2023-09-25 08:33
Duplicate of #23327

**Comment by ahus1** [comment] 2023-10-17 06:39
Removing from 22.0.5 milestone as it was marked as a duplicate of an issue which was part of 22.0.4
