### ISSUE TITLE
docker run v24.0.2 failed

### ISSUE THREAD

**Issue by dannyxu2015** [keycloak/keycloak#28325] opened 2024-04-01 03:43 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

`docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:24.0.2 start-dev
Error: Could not find or load main class io.quarkus.bootstrap.runner.QuarkusEntryPoint
Caused by: java.lang.ClassNotFoundException: io.quarkus.bootstrap.runner.QuarkusEntryPoint`

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

start successfully

### Actual behavior

failed

### How to Reproduce?

 docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:24.0.2 start-dev

**Comment by dannyxu2015** [comment] 2024-04-01 03:44
docker start keycloak refer to [latest official document](https://www.keycloak.org/getting-started/getting-started-docker)

**Comment by stianst** [comment] 2024-04-02 13:04
Not able to reproduce this and it works just fine, so not sure what's going on here

**Comment by jonkoops** [comment] 2024-04-02 13:32
Just tried this on my machine, and this works just fine.

**Comment by mabartos** [comment] 2024-04-02 17:24
Everything works for me as well.

**Comment by codespearhead** [comment] 2024-04-03 13:13
@dannyxu2015 The only cause I can think of for that error is if at least one of the two components on your local machine, the Docker image or the Docker container, is corrupted.

1. Try removing the containers created from that image:

```bash
docker ps -a | grep 'quay.io/keycloak/keycloak:24.0.2' | awk '{print $1}' | xargs docker rm
```

2. Remove the downloaded Docker image:

```bash
docker rmi quay.io/keycloak/keycloak:24.0.2
```

3. Run the original command again:

```bash
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:24.0.2 start-dev
```

**Comment by jonkoops** [comment] 2024-04-03 13:31
Considering several users have not been able to reproduce this issue, and this is likely an issue related to local setup, I will close it.

**Closed by jonkoops** 2024-04-03 13:31 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/auto-expire, status/missing-information

**Comment by dannyxu2015** [comment] 2024-04-30 01:43
yeah, I can run it now, sorry for the bothering
