### ISSUE TITLE
Required Action Update Password  [Enabled] VS [Default Action]

### ISSUE THREAD

**Issue by cybermo** [keycloak/keycloak#14558] opened 2022-09-23 09:10 UTC
### Describe the bug

the tool tip of the default action of the update password states: "If enabled, any new user will have this required action assigned to it."

Meaning when "update password" is the only one enabled means that new user will not have this required action assigned to it until the  "Default Action" is enabled. 

![image](https://user-images.githubusercontent.com/6603243/191923707-92beaffe-a215-4cc6-90ba-441711965d6e.png)

In the that case the user have the right to change reset the password.

The problem with configuration is that every new user will be assigned the update password. 
If we dont wan that beahviour we need to disable "update password". But when we do that there will be no form in the password reset form followinf a " forget password" link. the link withtout the riquired action "update password" will lead directly to the page saying "Your account has been updated.".

### Version

19.0.2

### **Required Action > Update password ( Enabeld [X] Default Action [ ]  )**

Password reset form **enabled**. "Update password" action will not be assigend automatically to new/existing users.

### **Required Action > Update password ( Enabeld [X] Default Action [X]  )**

Password reset form **enabled**. "Update password" action assigend automatically to new users.

### **Required Action > Update password ( Enabeld [ ] Default Action [ ]  )**

Password reset form **disabled**. "Update password" action will not be assigend automatically to new users.

### **Required Action > Update password ( Enabeld [X] Default Action [ ]  )**

Password reset form **enabled**. "Update password" action is assigend automatically to new/existing users. while it hase to be assigned only if Default action is checked

### How to Reproduce?

Important to say this while with federation Active directory

### **Required Action > Update password ( Enabeld [X] Default Action [ ]  )**
In this case action will be assigend automatically to new/existing users while Default Action is not checked

**Comment by lexcao** [comment] 2022-09-24 06:08
Hi, @cybermo 
I can't reproduce from my local with the below settings
* Forgot password enabled
* Required Action > Update password ( Enabled [X] Default Action [ ] )

Could you please provide a minimal way to reproduce?

**Comment by cybermo** [comment] 2022-09-26 07:38
Required Action > Update password ( Enabeld [X] Default Action [ ] )
Password reset form enabled. "Update password" action will be assigend automatically to new/existing users.

Expected: In this case where Default action is not checked, The  "Update password" action has not to be assigend automatically to new/existing users. But only if Default action is enabled.

**Comment by cybermo** [comment] 2022-09-26 15:35
I guess it's related to that old bug.

https://issues.redhat.com/browse/KEYCLOAK-8571

**Comment by cybermo** [comment] 2022-10-04 15:25
@lexcao I gave more detail for how to reproduce.

@stianst I opened a pull reuqest to fix that issue.

Thank you!

**Comment by lexcao** [comment] 2022-10-04 16:32
@cybermo  Thanks, I will give it a try.

**Comment by cybermo** [comment] 2022-10-05 10:10
@lexcao Important to say this while with federation Active directory

**Comment by mposolda** [comment] 2023-03-06 10:22
One question: Are you able to reproduce this issue also without LDAP or just with LDAP / Active Directory?

I suppose it is the latter case. Note that when user is created in MSAD, he may be required automatically to update his password - this is the feature of MSAD. Keycloak just reads the info about the fact that "Update-password is required" from the MSAD. To avoid this behaviour, you can probably remove "MSAD mapper" from your list of mappers in the LDAP provider.

**Comment by jodesmet** [comment] 2024-02-21 23:50
I am seeing this sama behavior on Keycloak 16.1.1 without LDAP configured. I have to disable Reset Password to ensure the Reset Password action is not set on all my users when they are created and is currently causing a lot of pain. Is this resolved in a later version of Keycloak?

**Closed** 2024-03-28 14:04 UTC
Labels: area/authentication, kind/bug, team/core-clients, status/auto-expire, status/expired-by-bot
