### ISSUE TITLE
Hostname with underscore no longer acceptable

### ISSUE THREAD

**Issue by cod3monk** [keycloak/keycloak#13251] opened 2022-07-21 11:19 UTC
### Describe the bug

In a docker-compose environment hostnames often contain underscores (`_`), they used to be accepted by keycloak 16, but are no longer:
```
keycloak_bv             | 2022-07-21 13:09:35,120 ERROR [org.keycloak.services] (executor-thread-27) KC-SERVICES0055: Error when connecting to LDAP: Cannot parse url: ldap://openldap_bv/: javax.naming.NamingException: Cannot parse url: ldap://openldap_bv/ [Root exception is java.net.MalformedURLException: unsupported authority: openldap_bv]
```

Upgrading from 16 to 18, this broke our LDAP interface.

### Version

18.0.2

### Expected behavior

correct resolving of domains/hostnames containing underscore.

### Actual behavior

Error (only to be found in server log)

**Comment by hmlnarik** [comment] 2022-11-29 14:51
Underscores are not supported in DNS, hence closing this as not a bug

**Closed by hmlnarik** 2022-11-29 14:51 UTC
Labels: kind/bug, area/ldap, status/triage

**Comment by cod3monk** [comment] 2022-11-29 15:05
According to  [RFC2181 Section 11 "Name syntax"](https://www.rfc-editor.org/rfc/rfc2181#section-11) underscores and any other characters are valid DNS name entries.

See also https://stackoverflow.com/a/2183140 for examples.
