### ISSUE TITLE
User is redirected to the Update Account page when attempting to [Log In With Apple] if the User has already authorized "Sign In with Apple"

### ISSUE THREAD

**Issue by jshepard-genvid** [keycloak/keycloak#23909] opened 2023-10-11 14:02 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

User is redirected to the Update Account Information page if 

 still has “Sign in with Apple” authorization
- We’ve found two ways of getting into this state so far:

    Deleting an AppleID created account from Keycloak (which can be requested by the User)

    If the User attempts to Sign In With Apple when an account already exists in Keycloak with a matching e-mail (but choses not to link their account with an existing account, or create a new one by opting to Review Profile and enter a new e-mail)
![image](https://github.com/keycloak/keycloak/assets/147628078/20c4f005-115b-47f3-ad32-1345b48a663a)

### Version

21.0.2

### Expected behavior

Not sure if we should be seeing this page, but if it’s not pulling the account name information it might hurt us during certification if it’s encountered.
- At the very least this page needs more information. If the User fills in First Name/Last Name, they can continue (a new account will be created) and the User will be redirected to Profile Completion.

### Actual behavior

User is redirected to the Update Account Information page like we see when selecting “Review Profile” during account linking, except the First and Last name fields are empty.

### How to Reproduce?

1. Launch Demo App
2. Create an account with AppleID
3. Logout
4. Open Keycloak
5. Mile >Users > Locate AppleID account
6 .Select account
7. Delete (be careful not to delete any other accounts)
8. Return to Demo App
9. Attempt to login with AppleID

**Comment by rmartinc** [comment] 2023-10-11 14:26
We don't know about an appleid social provider in keycloak. What are you using to login with apple? A custom social provider? General OIDC provider?

**Comment by rmartinc** [comment] 2023-10-11 14:40
There is no appleid identity provider by default in keycloak. You probably are using this one: https://github.com/klausbetz/apple-identity-provider-keycloak (Check if you have added something to the providers folder.).

But it's an external extension. If you are using that one, try to talk with that project to see if they are aware of this. If the issue is relate to keycloak internals you can come back here.

**Comment by rmartinc** [comment] 2023-10-11 15:11
Thanks! Closing for now.

**Closed by rmartinc** 2023-10-11 15:11 UTC
Labels: kind/bug, area/user-profile, status/triage, team/core
