### ISSUE TITLE
Admin console and account console shows the user-profile configured field without annotations as "combobox" without any options

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#24319] opened 2023-10-26 10:45 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

- Enable user-profile feature and enable it in some realm

- Add new attribute to the user profile configuration. Simple `test` attribute writable for both admins and users. It can be added with this JSON configuration into `JSON Editor` of user profile:
```
    {
      "name": "test",
      "displayName": "",
      "permissions": {
        "edit": [
          "admin",
          "user"
        ],
        "view": [
          "user",
          "admin"
        ]
      },
      "annotations": {
        "inputType": "text"
      },
      "validations": {},
      "group": null
    }
```

- There are not any annotations, so I would expect that this attribute would behave as normal text input field? And it behaves like that for Registration form and Update-profile form (the form shown to the user during login when he has "Update profile" required action). However both admin console and account console (account console V3) shows this as the "combobox" field without any possibilities to choose from. See screenshots for the details. Is it possible to make admin console and account console consistent with the "registration" and "update profile" forms and assume that this is text field by default?

### Workaround

Add annotation `Input type` with value `text`. Then this works as expected and it is normal text field also in admin console and account console.

### Screenshots

![Screenshot from 2023-10-26 12-28-32](https://github.com/keycloak/keycloak/assets/1223965/b90bd0a6-645a-432a-8091-4fd9a364111b)

![Screenshot from 2023-10-26 12-28-56](https://github.com/keycloak/keycloak/assets/1223965/d087aeba-664f-4812-a8fd-439c1588cc0e)

### Version

Keycloak main (from 2023-10-26)

### Expected behavior

Admin console and account console shows the field as "text fields" when there are not any annotations on the field

### Actual behavior

Admin console and account console shows the field as "Combo box" without any options to choose from.

### How to Reproduce?

See description

**Comment by edewit** [comment] 2023-10-26 10:54
duplicate of #23911

**Closed by edewit** 2023-10-26 10:54 UTC
Labels: kind/bug, area/user-profile, area/account/ui, area/admin/ui, status/triage, team/core, team/ui
