### ISSUE TITLE
privacyIDEA provider flow configuration  cant be oppened (can't convert undefined to object)

### ISSUE THREAD

**Issue by fgsasha** [keycloak/keycloak#14525] opened 2022-09-21 13:02 UTC
### Describe the bug

After upgrading the Keycloak server from version 19.0.1 to 19.0.2
can't configure  the authentication flow step - privacyIDEA (Authenticate the second factor against privacyIDEA).
UI error - **can't convert undefined to object**
Reinstall of the privacyIDEA provider didnt help.

`Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.jta] (Timer-0) TransactionImpleManager.suspend
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-0) new JtaTransactionWrapper
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-0) was existing? false
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.jta] (Timer-0) BaseTransaction.begin
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) StateManager::StateManager( 2, 0 )
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::BasicAction()
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::Begin() for action-id 0:ffff034815fc:96c3:632aff0d:2e0
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::actionInitialise() for action-id 0:ffff034815fc:96c3:632aff0d:2e0
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) ActionHierarchy::ActionHierarchy(1)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) ActionHierarchy::add(0:ffff034815fc:96c3:632aff0d:2e0, 1)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::addChildThread () action 0:ffff034815fc:96c3:632aff0d:2e0 adding Thread[Timer-0,5,main]
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::addChildThread () action 0:ffff034815fc:96c3:632aff0d:2e0 adding Thread[Timer-0,5,main] result = true
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) TransactionReaper::insert ( BasicAction: 0:ffff034815fc:96c3:632aff0d:2e0 status: ActionStatus.RUNNING, 300 )
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [com.arjuna.ats.arjuna] (Timer-0) ReaperElement::ReaperElement ( BasicAction: 0:ffff034815fc:96c3:632aff0d:2e0 status: ActionStatus.RUNNING, 300 )
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 DEBUG [org.keycloak.models.sessions.infinispan.changes.sessions.PersisterLastSessionRefreshStore] (Timer-0) Updating 0 userSessions with lastSessionRefresh: 1663763877
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,500 TRACE [org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory] (Timer-0) Create QuarkusJpaConnectionProvider
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl] (Timer-0) Opening Hibernate Session.  tenant=null
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (Timer-0) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.jta] (Timer-0) TransactionImple.getStatus: javax.transaction.Status.STATUS_ACTIVE
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.jta] (Timer-0) TransactionImple.registerSynchronization - Class: class org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization HashCode: 163227158 toString: org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@9baa616
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (Timer-0) Hibernate RegisteredSynchronization successfully registered with JTA platform
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.internal.SessionImpl] (Timer-0) Opened Session [ecc005a2-155c-45ff-89f1-b1fd14f7a4fd] at timestamp: 1663763937501
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-0) JtaTransactionWrapper  commit
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.jta] (Timer-0) BaseTransaction.commit
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.jta] (Timer-0) TransactionImple.commitAndDisassociate
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.jta] (Timer-0) SynchronizationImple.beforeCompletion - Class: class org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization HashCode: 163227158 toString: org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@9baa616
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization] (Timer-0) Registered JTA Synchronization : beforeCompletion()
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl] (Timer-0) Synchronization coordinator: beforeCompletion()
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.internal.SessionImpl] (Timer-0) SessionImpl#beforeTransactionCompletion()
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.internal.SessionImpl] (Timer-0) Automatically flushing session
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.jta] (Timer-0) TransactionImple.getStatus: javax.transaction.Status.STATUS_ACTIVE
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (Timer-0) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.infinispan.quarkus.hibernate.cache.Sync] (Timer-0) 0 tasks done, 0 tasks not done yet
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.infinispan.quarkus.hibernate.cache.Sync] (Timer-0) Finished 0 tasks before completion
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor] (Timer-0) LogicalConnection#beforeTransactionCompletion
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (Timer-0) Initiating JDBC connection release from beforeTransactionCompletion
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl] (Timer-0) SynchronizationRegistryStandardImpl.notifySynchronizationsBeforeTransactionCompletion
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::End() for action-id 0:ffff034815fc:96c3:632aff0d:2e0
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::End() result for action-id (0:ffff034815fc:96c3:632aff0d:2e0) is (TwoPhaseOutcome.PREPARE_OK) node id: (quarkus)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.jta] (Timer-0) SynchronizationImple.afterCompletion - Class: class org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization HashCode: 163227158 toString: org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@9baa616
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization] (Timer-0) Registered JTA Synchronization : afterCompletion(3)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorTrackingImpl] (Timer-0) Synchronization coordinator: afterCompletion(status=3)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl] (Timer-0) Synchronization coordinator: doAfterCompletion(successful=true, delayed=false)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl] (Timer-0) SynchronizationRegistryStandardImpl.notifySynchronizationsAfterTransactionCompletion(3)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor] (Timer-0) LogicalConnection#afterTransaction
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (Timer-0) Releasing JDBC resources
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (Timer-0) Initiating JDBC connection release from afterTransaction
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.internal.SessionImpl] (Timer-0) SessionImpl#afterTransactionCompletion(successful=true, delayed=false)
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.infinispan.quarkus.hibernate.cache.Sync] (Timer-0) Invoked 0 tasks after completion, 0 are synchronous.
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::removeChildThread () action 0:ffff034815fc:96c3:632aff0d:2e0 removing 2
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.arjuna] (Timer-0) BasicAction::removeChildThread () action 0:ffff034815fc:96c3:632aff0d:2e0 removing 2 result = true
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [com.arjuna.ats.arjuna] (Timer-0) TransactionReaper::remove ( BasicAction: 0:ffff034815fc:96c3:632aff0d:2e0 status: ActionStatus.COMMITTED )
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-0) JtaTransactionWrapper end
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 DEBUG [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Executed scheduled task AbstractLastSessionRefreshStoreFactory$$Lambda$1231/0x0000000840c41840
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.keycloak.connections.jpa.DefaultJpaConnectionProvider] (Timer-0) DefaultJpaConnectionProvider close()
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,501 TRACE [org.hibernate.internal.SessionImpl] (Timer-0) Closing session [ecc005a2-155c-45ff-89f1-b1fd14f7a4fd]
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,502 TRACE [org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl] (Timer-0) Closing JDBC container [org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl@b9dad2e]
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,502 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (Timer-0) Releasing JDBC resources
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,502 TRACE [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (Timer-0) Closing logical connection
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,502 TRACE [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (Timer-0) Logical connection closed
Sep 21 12:38:57 keycloak-test kc.sh[10857]: 2022-09-21 12:38:57,847 DEBUG [io.netty.buffer.PoolThreadCache] (executor-thread-2) Freed 1 thread-local buffer(s) from thread: executor-thread-2
Sep 21 12:38:58 keycloak-test kc.sh[10857]: 2022-09-21 12:38:58,827 TRACE [org.jgroups.protocols.pbcast.STABLE] (Timer runner-2,keycloak-test-62675) keycloak-test-62675: updating the local figest with a stable message (coordinator): keycloak-test-62675: [11 (11)]
Sep 21 12:38:58 keycloak-test kc.sh[10857]: 2022-09-21 12:38:58,828 TRACE [org.jgroups.protocols.pbcast.STABLE] (Timer runner-2,keycloak-test-62675) keycloak-test-62675: handling digest from keycloak-test-62675:
Sep 21 12:38:58 keycloak-test kc.sh[10857]: mine:   keycloak-test-62675: [-1]
Sep 21 12:38:58 keycloak-test kc.sh[10857]: sender: keycloak-test-62675: [11]
Sep 21 12:38:58 keycloak-test kc.sh[10857]: result: keycloak-test-62675: [11]
Sep 21 12:38:58 keycloak-test kc.sh[10857]: 2022-09-21 12:38:58,828 TRACE [org.jgroups.protocols.pbcast.STABLE] (Timer runner-2,keycloak-test-62675) keycloak-test-62675: sending stability msg keycloak-test-62675: [11]
Sep 21 12:38:58 keycloak-test kc.sh[10857]: 2022-09-21 12:38:58,829 TRACE [org.jgroups.protocols.UDP] (Timer runner-2,keycloak-test-62675) keycloak-test-62675: sending msg to null, src=keycloak-test-62675, size=83, headers are STABLE: [STABILITY] view-id= [keycloak-test-62675|0], TP: [cluster=ISPN]
Sep 21 12:38:58 keycloak-test kc.sh[10857]: 2022-09-21 12:38:58,829 TRACE [org.jgroups.protocols.pbcast.NAKACK2] (Timer runner-2,keycloak-test-62675) keycloak-test-62675: received stable digest keycloak-test-62675: [11 (11)]
Sep 21 12:38:58 keycloak-test kc.sh[10857]: 2022-09-21 12:38:58,829 TRACE [org.jgroups.protocols.pbcast.NAKACK2] (Timer runner-2,keycloak-test-62675) keycloak-test-62675: deleting msgs <= 11 from keycloak-test-62675`

### Version

19.0.2.

### Expected behavior

Open the privacyIDEA configuration flow step to add settings.

### Actual behavior

Try to open  the privacyIDEA configuration and get the error 
"can't convert undefined to object"

### How to Reproduce?

1. Migrate from version 19.0.1 to 19.0.2
2. cp PrivacyIDEA-Provider-v1.1.0.jar /opt/keycloak-19.0.2/providers/
3. ./kc.sh build
4. service keycloak start
5. Go to the Master admin console
6. Duplicate browser flow in the Authentication admin tab - "Copy of Browser"
7. Add to "Copy of Browser" privacyIDEA step
8. Try to open configuration of the step and get the UI error "can't convert undefined to object" 

### Anything else?
The same issue for docker installation from scratch (quay.io/keycloak/keycloak:19.0.2)
_No response_

**Comment by fgsasha** [comment] 2022-09-21 15:28
> Did it work in 19.0.1?
Yes, I was able to open the privacyIDEA configuration. But there was another issue but this is a different story [privacyidea/keycloak-provider] privacyIDEA.ftl not found when used with Keycloak 19.0.1 (Issue #112).
> Are you using the new admin UI?
It is hard to say, but this is definitely different from the 18 version.  I guess this is the default UI for 19 version.
You can easily reproduce the issue by yourself using the docker version 
`docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:19.0.2 start-dev`
and PrivacyIDEA-Provider.jar (v1.1.0)

**Comment by lexcao** [comment] 2022-09-21 15:41
Hi, seems it is duplicated to https://github.com/keycloak/keycloak-ui/issues/3375.
Here is a workaround:
change back to legacy admin UI.
or just disable the new admin UI by the following
```
--features-disabled=admin2
```

**Comment by fgsasha** [comment] 2022-09-22 15:02
@lexcao 
Yes, I am able to open the privacyIDEA configuration menu in OLD UI.
Thank you, for the workaround.

Best regards,
Oleksandr

**Comment by stianst** [comment] 2022-09-28 12:09
Closing this as it's a duplicate of the above issue

**Closed by stianst** 2022-09-28 12:09 UTC
Labels: kind/bug, status/triage
