### ISSUE TITLE
cookie_not_found error on authentication since Keycloak 24 

### ISSUE THREAD

**Issue by woprandi** [keycloak/keycloak#30977] opened 2024-07-01 16:59 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When authenticating to admin-console from non-localhost origin (nor direct IP address), we get a error message : `Cookie not found. Please make sure cookies are enabled in your browser.`
This is from Keycloak 24
Previous issue : https://github.com/keycloak/keycloak/issues/24821
`--hostname` flag does not seem to have any impact

### Version

from 24 to 25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Authentication works without problem

### Actual behavior

Error after authentication attempt (with any password btw)

### How to Reproduce?

- Host : Debian 12 (Debian 11 seems not impacted), Fedora 40
- Docker version 24.0.5 (current on Fedora),  not checked on Debian 12
- run `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.1 start-dev ` 
- Access from non localhost origin nor IP address, on Linux with avahi you should be able to access with`http://<hostname>.local:8080`
- Connect to the admin console (behavior is same with good or wrong credentials btw)
- Error message

Adding `--hostname` does not change :  `docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.1 start-dev --hostname http://william-laptop.local:8080` 
I get same error message

### Anything else?

Docker logs 
`
2024-07-01 16:57:29,759 WARN  [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="d192c62e-7786-4b72-bbb2-d3482323b9a7", realmName="master", clientId="security-admin-console", userId="null", ipAddress="172.17.0.1", error="cookie_not_found"
`

**Comment by codespearhead** [comment] 2024-07-02 15:13
Is this reproducible when you run it with `start` instead of `start-dev`?

**Comment by woprandi** [comment] 2024-07-02 15:49
Apparently yes with this command : `docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_PROXY=edge quay.io/keycloak/keycloak:25.0.1 start --hostname http://william-laptop.local:8080`

**Comment by rmartinc** [comment] 2024-07-04 10:17
The error of the `cookie.not-found` is when the restart cookie is not found. IIRC version 25 added SameSite to all cookies (https://www.keycloak.org/docs/latest/release_notes/index.html#cookies-updates) but I don't know if it's really related. Please check the browser is sending/accepting the cookies correctly in the navigation. Nevertheless my impression is that we are missing something here.

I don't use avahi but I really don't know how DNS resolution can affect this. I can execute the image with podman without issues doing:

```
docker run -p 8443:8443 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -v /home/rmartinc/keycloak-25.0.1/conf:/opt/keycloak/conf quay.io/keycloak/keycloak:25.0.1 start --hostname myserver
```

I had created before the `server.keystore` with the self-signed cert  before in my local path `/home/rmartinc/keycloak-25.0.1/conf`.

**Comment by woprandi** [comment] 2024-07-04 10:25
As I said, this issue come with Keycloak 24 (tested with 24.0.4) so it's not related to v25 changes.

I originally discovered this issue with a hosted Keycloak instance on a dedicated VM with DNS so it's not related to avahi. But it's not reproductible with localhost

**Comment by jonkoops** [comment] 2024-07-04 10:33
Also v24 included changes to the cookies. instead of `.local` try `.localhost`, the browsers will treat this as a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).

**Comment by woprandi** [comment] 2024-07-04 10:45
Yeah with `.localhost` it's not reproductible. 
So Keycloak is no longer runnable on development mode except on localhost ?

**Comment by jonkoops** [comment] 2024-07-04 10:51
Because of the way security features of browsers work and the APIs Keycloak needs to function you'll need to make sure it runs on what browsers consider a secure context, which is basically a valid domain with HTTPS enabled, or `http://localhost` or `http://*.localhost` for development.

Closing this issue, as there is not really anything we can do about this, and we plan to enforce secure contexts in the future.

**Closed by jonkoops** 2024-07-04 10:51 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients

**Comment by woprandi** [comment] 2024-07-04 11:39
btw it's not reproductible on a Debian 11 host (if someone is interested). I don't know why

**Comment by woprandi** [comment] 2024-07-04 12:36
No I was using a Keycloak 24 instance on a Debian 11 for a while. I discovered this issue by installing it on a Debian 12 host.
I have `*_LEGACY` cookies

**Comment by jonkoops** [comment] 2024-07-04 12:41
> No I was using a Keycloak 24 instance on a Debian 11 for a while. I discovered this issue by installing it on a Debian 12 host. I downgraded as a workaround

Weird, I don't see how the OS of the server would play into this bug.

> I have `*_LEGACY` cookies

Yeah, that is expected behaviour (for now). These cookies will go away in the future.

**Comment by woprandi** [comment] 2024-07-04 12:46
> Weird, I don't see how the OS of the server would play into this bug.

I had same reaction. The docker version is different too. I tried to read source code to understand but there is a lot of abstraction it's kinda hard when you don't know

**Comment by bernardoveras** [comment] 2024-07-30 00:28
Same problem...
