### ISSUE TITLE
Unable to set absolute target directory for H2 data files outside of kc.home.dir

### ISSUE THREAD

**Issue by amarktl** [keycloak/keycloak#22865] opened 2023-08-31 15:50 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

When using H2 as database we are not able to set the directory where the datafiles are to be stored. We want the H2 datafiles to be located outside of the keycloak directory structure.

In older keycloak versions based on wildfly this was possible by setting `-Djboss.server.data.dir`.

As far as we see in 

https://github.com/keycloak/keycloak/blob/main/quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java

```
public String apply(String alias) {
                        if ("dev-file".equalsIgnoreCase(alias)) {
                            return addH2NonKeywords("jdbc:h2:file:${kc.home.dir:${kc.db-url-path:" + escapeReplacements(System.getProperty("user.home")) + "}}" + escapeReplacements(File.separator) + "${kc.data.dir:data}"
                                    + escapeReplacements(File.separator) + "h2" + escapeReplacements(File.separator)
                                    + "keycloakdb${kc.db-url-properties:;;AUTO_SERVER=TRUE}");
                        }
                        return addH2NonKeywords("jdbc:h2:mem:keycloakdb${kc.db-url-properties:}");
                    }
```

Keycloak now always attempts to create the h2 datafiles in the `kc.home.dir`, because this parameter is always set. 

### Version

22.0.1

### Expected behavior

we would expect to be able to set `kc.data.dir` to an absolute Path and that this would be used for storing the H2 datafiles. 

### Actual behavior

when setting `kc.data.dir` this is treated as a relative path below of `kc.home.dir`

### How to Reproduce?

Set `kc.data.dir` and it will be created below `kc.home.dir`.
It is irrelevant if it is set to an absolute or an relative path.

**Comment by amarktl** [comment] 2023-09-26 07:28
@sguilhen thank you for assigning the task to yourself - do you have any plan when you find time to deal with this issue? Can we support you somehow?
BR Alex

**Comment by sguilhen** [comment] 2023-09-26 13:04
@amarktl yeah, I'm triaging a bunch of issues this week, it is very likely that I get to this one in the next couple of days :)

**Comment by wgssi** [comment] 2023-09-26 13:33
[like]  Grandl Wilhelm reacted to your message:
________________________________

**Comment by sguilhen** [comment] 2023-10-19 14:48
@amarktl I think the evaluation of the options `kc.home.dir` and `kc.db-url-path` in `Database` should be switched, so that the db-url-path is evaluated first. As you pointed out, `kc.home.dir` is always set, which ends up ignoring the url path part all the time.

In the meantime, I worked out it by setting the db-url-path in `keycloak.conf` - i.e. added this line

`db-url=jdbc:h2:file:/tmp/data/h2/keycloakdb;;AUTO_SERVER=TRUE;NON_KEYWORDS=VALUE`

and then I've run `kc.sh start-dev --db=dev-file`  - the data is now stored under `/tmp/data/h2/`

**Comment by sguilhen** [comment] 2023-10-19 14:51
This is a good candidate for a community fix - I'm adding the `help-wanted` label. If you feel like giving this a try, feel free to pick it up :)

**Comment by stianst** [comment] 2024-02-08 08:44
I'm closing this as it's not a bug. It's by design that H2 can only live inside the Keycloak directory, and also adding that H2 is not recommended for production use-cases.

**Closed by stianst** 2024-02-08 08:44 UTC
Labels: kind/bug, area/storage, help wanted, team/store
