### ISSUE TITLE
Unusable Realm if has Trailing Whitespace in Name

### ISSUE THREAD

**Issue by hariubc** [keycloak/keycloak#33122] opened 2024-09-19 20:38 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When realm created with trailing white space, it becomes unusable. 

![image](https://github.com/user-attachments/assets/bcc78360-ab67-4dd8-b762-b5fdbed8ef4d)

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Trailing white spaces are not an issues on real creation. Drop trailing whitespaces if added inadvertently when creating realm.

### Actual behavior

Realm is inaccessible. Inability to update relam name to remove trailing whitespace.

### How to Reproduce?

Create realm with trailing whitespace in name

**Comment by codespearhead** [comment] 2024-10-03 19:09
This is a duplicate of [1] and [2], which was fixed by [3] in PR [4].

The patch was included in version 24.0.4, released on 2024-05-08T06:35:37Z, approximately four months before this issue was created. I personally confirmed that the issue exists in version `24.0.3`, but is not present in version `24.0.4` or the current version (`25.0.6`).

Please note that only the most recent stable release will continue to receive updates [5][6].

@hariubc Can you please close it [7]?

[1] https://github.com/keycloak/keycloak/issues/16345
[2] https://github.com/keycloak/keycloak/issues/27913
[3] b7c6bdd3e1bf45ba2babbf984905c25012d4a3c1
[4] https://github.com/keycloak/keycloak/pull/28349
[5] https://github.com/keycloak/keycloak/discussions/29126
[6] https://github.com/keycloak/keycloak/discussions/29126#discussioncomment-9257666
[7] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue

**Closed** 2024-10-03 22:04 UTC
Labels: kind/bug, area/admin/ui, team/ui, status/auto-expire, status/expired-by-bot
