### ISSUE TITLE
Updating user attributes after upgrade from 23.0.7 to 24.0.3

### ISSUE THREAD

**Issue by hesam-talkscriber** [keycloak/keycloak#28908] opened 2024-04-19 07:27 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I have a function that updates attributes of a user during registration:
```python
async def keycloak_user_update_attribute(user_id, attribute, value):
    try:
        user = keycloak_admin.get_user(user_id)
        attibutes = user.get('attributes', {})

        # Add a new attribute
        attibutes[attribute] = value
        response = keycloak_admin.update_user(user_id=user_id,
                                            payload={'attributes': attibutes}
                                            )
        user = keycloak_admin.get_user(user_id)

        return user
    except Exception as e:
        return None
```

This function worked as expected with `python-keycloak==3.12.0` and Keycloak version `23.0.7`.  However, it fails after upgrade to version `24.0.3` with the following error:
```
{"field":"email","errormessage":"error-user-attribute-required","params":["email"]}
```

There is a fix for it to include `email` in the `update_user()` call but this seems like a regression from previous version.

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

The expected behavior is I should be able to update the attributes of the user by providing the `user_id` and not require to provide the `email` field.

### Actual behavior

The following error occurs:
```
{"field":"email","errormessage":"error-user-attribute-required","params":["email"]}
```

### How to Reproduce?

Use the function in the bug description.

**Comment by shawkins** [comment] 2024-04-19 11:44
Duplicate of #28220

**Closed by shawkins** 2024-04-19 11:44 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core-shared
