### ISSUE TITLE
Some groups not displayed in realm admin console (fine grained permissions)

### ISSUE THREAD

**Issue by pfhartma** [keycloak/keycloak#28209] opened 2024-03-26 11:06 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

When an admin is permitted to view/manage only a single group, the behavior in the admin console is inconsistent.

It depends on the alphabetical position of the group name. (Fine grained permissions are used.)

This also makes it difficult for the group admin to add new users to their group.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

On the realm admin console, the assigned group is normally displayed in both columns:
![image](https://github.com/keycloak/keycloak/assets/51408017/ef0cec1e-cb36-4008-b57f-0305733bddb2)

### Actual behavior

However, some Groups are only displayed on the left:

![image](https://github.com/keycloak/keycloak/assets/51408017/80d8c63e-e8d0-4336-afd1-4f29f5d0965b)

And some not at all.

### How to Reproduce?

This depends on the alphabetical position in the list of all available groups. If the group is one of the first 11, it works correctly. If it is one of the first 21, it shows on the left. All others are not shown at all. This behavior corresponds to the query parameter `max=...` that is sent with the `/admin/realms/.../ui-ext/groups` request to the keycloak backend.

Details on the setup:
* For the realm-management client, we added client policies of type "Group" meaning "_is member of Group X_"
* For the group, we enabled permissions and updated the _view_ scope: Include the policy created above
* We do this for each group, but for reproducing the issue, one or two should be enough
* Add a user that is member of just that group and open the admin console `/admin/.../console` for that user

### Anything else?

**Why does it matter?**

The group admin is supposed to add users for their group. However, when selecting the group for the new user, the same issue occurs. Depending on the alphabetical position of the group, the admin will be able to select their group for the new user or not.

**Comment by sguilhen** [comment] 2024-03-27 13:09
Looks related to https://github.com/keycloak/keycloak/issues/27512 which was fixed in upstream.

**Comment by pfhartma** [comment] 2024-03-27 13:33
Related, but the current MR will not fix it, as far as I can tell. This issue is related to the `/groups` endpoint, i.e. `GroupsResource.getGroups` rather than  `GroupResource.getSubGroups`.

**Comment by sguilhen** [comment] 2024-03-28 19:48
This is caused by pretty much the same problem that affected #27512 - the permission evaluation happens after pagination, which can lead to an incorrect number of groups being loaded.

**Closed** 2024-06-27 00:06 UTC
Labels: kind/bug, area/admin/fine-grained-permissions, help wanted, team/core-iam, status/auto-expire, status/auto-bump, priority/normal, status/expired-by-bot
