### ISSUE TITLE
Unable to remove the users imported through LDAP User Federation

### ISSUE THREAD

**Issue by guptakaran27** [keycloak/keycloak#19514] opened 2023-04-04 06:48 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

- I have created an LDAP User Federation in Keycloak, to import my users via an OpenLDAP. 
- In the **Action** dropdown of the **User Federation** config page, after selecting **_Remove imported_** I could see the popup message saying **_Imported Users have been removed_** 
- But in the Users section, I could still see the LDAP imported users 

![image](https://user-images.githubusercontent.com/128346079/229709933-90f1a03b-fb72-4648-9853-2916c27480ad.png)
- I could see the same bug present in 21.0.1 as well 

--> Also, even if I **turn off** the _**Import user**_ flag in the LDAP Configuration, KC is auto importing the users without me selecting **_Import users_** from **_Action_** dropdown 
![image](https://user-images.githubusercontent.com/128346079/229710135-92cbf195-5e8a-4834-820d-6bae94e6c3fb.png)

### Version

21.0.2

### Expected behavior

LDAP Federation Users should be removed from the User List 

### Actual behavior

LDAP Federation Users are not getting removed from the User List ever after selecting remove imported  

### How to Reproduce?

- Install KC 21.0.2
- Setup a User Federation using LDAP (I used openLDAP )
- Try importing users via the Action Dropdown 
- Try removing imported users via Action Dropdown 
![image](https://user-images.githubusercontent.com/128346079/229710614-67b82ca9-cabf-4f84-ac99-efec1fffd339.png)

**Comment by guptakaran27** [comment] 2023-04-07 08:16
Hi Team, any update on this issue ?

**Comment by edewit** [comment] 2023-04-20 13:54
The problem is when you search the users they automatically get added again, it's an error in the server not in the ui. Changing the the label accordingly.

**Comment by guptakaran27** [comment] 2023-04-24 11:22
Hi @edewit , 
Is there any plan to include the fix in another 21.0.x patch or in any upcoming nearby release ?
Also, what are the timelines of 23.0.0 (as mentioned in  milestones above)?

**Comment by rmartinc** [comment] 2023-08-08 07:50
@guptakaran27 @ssilvert But what do you want the server do here? The users are really deleted from the database but, as the ldap provider is still there and enabled, the users are re-imported when needed by keycloak (UI searching, a login or whatever). To stop importing users the provider can be disabled (before or after the removal).

If you remove imported and the sync all users again you will see that the users were created (not updated). And that's because they were previously deleted.

**Comment by vramik** [comment] 2023-10-26 08:18
Hello @guptakaran27, @edewit, @ssilvert. I second @rmartinc's comment. What would be a desired behavior? 

Currently if the LDAP storage provider is **enabled** then each call which could eventually lands there and therefore the user is automatically loaded from LDAP. 

Based on the `import enabled` flag on the provider, the user(s) is either persisted in the DB or in-memory user (`InMemoryUserAdapter`) is returned.

I've added back `triage` label.

**Comment by edewit** [comment] 2023-10-26 09:37
Okay, I'm confused what should be done to fix this?

**Comment by rmartinc** [comment] 2023-10-26 11:07
Our question is what should be fixed?

As commented the users are really removed but they are re-imported when you search for them. Because the ldap provider is enabled and they are imported when found (searching, login or whatever). So the correct order to do this is:

1. Setup a User Federation using LDAP (I used openLDAP )
2. Try importing users via the Action Dropdown (all users are imported)
3. Che the users are there in the Users tab.
4. Disable the ldap provider to not re-import them anymore.
5. Try removing imported users via Action Dropdown (all users are removed)
6. Go to users and you will see the users are not there. (Because the ldap provider is disabled and they were removed in the previous point.)

**Comment by rmartinc** [comment] 2023-10-26 11:07
IMHO this is working as expected and not a bug.

**Comment by ssilvert** [comment] 2023-10-26 19:41
I'd be fine with closing this issue.  But since it's currently labeled as `team\store`, I'll leave it to the storage folks to decide.

**Comment by vramik** [comment] 2023-10-27 07:20
Closing, thank you.

**Closed by vramik** 2023-10-27 07:20 UTC
Labels: kind/bug, area/ldap, team/store, status/triage
