### ISSUE TITLE
Mutual TLS Certificate Bound Access Tokens  not working

### ISSUE THREAD

**Issue by phasianus** [keycloak/keycloak#15872] opened 2022-12-06 15:13 UTC
### Area

account/api

### Describe the bug

After enable Mutual TLS Certificate Bound Access Tokens on client, certificate hash is never included in access token, or not error is returned if client has no certificate.

### Version

20.0.0

### Expected behavior

Cert hash is included in acces token.

### Actual behavior

Method `OIDCAdvancedConfigWrapper.fromClientModel(client).isUseMtlsHokToken())`;  returns `false` when client has enabled this feature. 

My investigation: `OIDCConfigAttributes.USE_MTLS_HOK_TOKEN` has value `tls.client.certificate.bound.access.tokens`, but the client returns attribute `tls-client-certificate-bound-access-tokens`, all other client attributes are dot-separatated, only this one is dash separated.

```
...
,"attributes":{"client.secret.creation.time":"1669810898","sa_application":"vispart","oauth2.device.authorization.grant.enabled":"false","backchannel.logout.revoke.offline.tokens":"false","use.refresh.tokens":"true","tls-client-certificate-bound-access-tokens":"true","oidc.ciba.grant.enabled":"false","backchannel.logout.session.required":"true","client_credentials.use_refresh_token":"false","sa_resources":"app b2app/isskodacr","acr.loa.map":"{}","require.pushed.authorization.requests":"false","display.on.consent.screen":"false","token.response.type.bearer.lower-case":"false"},
...
```

### How to Reproduce?

Try configure Mutual TLS Certificate Bound Access Token:  cert hash is not in access token.

**Comment by phasianus** [comment] 2022-12-07 11:50
I tried  create client with rest api. When I put in client attributes `"tls.client.certificate.bound.access.tokens": true` then keycloak works as expected: returns access token with cert hash. 

Sorry I have no clue about inner structures of keycloak code so I am not able to create patch.

**Comment by lexcao** [comment] 2022-12-07 16:03
> After enable Mutual TLS Certificate Bound Access Tokens on client

* How to enable? by API or Admin UI?
* If possible, could you please tell me how to reproduce this in steps?

**Comment by lexcao** [comment] 2022-12-10 14:06
@phasianus Thank you.

It seems it is related to the new Admin UI,
@ssilvert could you please check this?

**Comment by jsorah** [comment] 2023-05-08 14:21
Is this still an issue for you on the latest Keycloak release? 

Based on some quick checks it looks like the correct attribute is being set from the UI now - `tls.client.certificate.bound.access.tokens`.

**Comment by ssilvert** [comment] 2023-05-15 11:43
Closing as assumed fixed.  We can reopen later if someone is still having this problem.

**Closed by ssilvert** 2023-05-15 11:43 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
