### ISSUE TITLE
User lockout - No clear error message when the user gets locked

### ISSUE THREAD

**Issue by ygoldner1** [keycloak/keycloak#20651] opened 2023-05-30 11:32 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

When a user tries to login to many times to a certain account, at some point, the user gets locked (if the brute force feature is enabled). Once the user is locked, there should be an error message displayed, letting the user know that the account was locked.

### Version

21.1.1

### Expected behavior

When user gets locked there should be a message, letting the user know, that the account has been locked.

### Actual behavior

There is no message.

### How to Reproduce?

Enable brute force feature.
Try to login with a valid user ame, but invalid password, several times (until the user gets locked).

**Comment by sschu** [comment] 2023-05-30 17:05
This should actually not be the case as this can be used to enumerate existing users (you just try to login a few times and then the lockout would give you a different error message so you know the user exists). The only case were you should respond with a different message is when the correct password is entered.

I am not 100% sure what the current behaviour is after entering the correct password. So if you could verify that the message is still the same even the correct password is entered and change this issue description accordingly, I would keep this open - otherwise close it as not a bug.

**Comment by jsorah** [comment] 2023-06-23 15:28
Adding to what @sschu mentioned and confirming the last part of his comment - this is expected behavior per https://www.keycloak.org/docs/latest/server_admin/#password-guess-brute-force-attacks

> When a user is temporarily locked and attempts to log in, Keycloak displays the default Invalid username or password error message. This message is the same error message as the message displayed for an invalid username or invalid password to ensure the attacker is unaware the account is disabled.

I confirmed it still works this way on 21.1.1.

Changing the message when it is the correct password and the user is locked in this scenario would provide another avenue to continue the brute force attack as now the adversary looks for the new message to validate the credential despite the user being "locked".

**Closed by jsorah** 2023-06-23 15:28 UTC
Labels: kind/bug, area/account/api, team/other
