### ISSUE TITLE
[Fine grain admin permissions] Restricted admin can't view or configure the client's Authorization tab

### ISSUE THREAD

**Issue by rh-** [keycloak/keycloak#20296] opened 2023-05-10 23:24 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/fine-grained-permissions

### Describe the bug

A **restricted admin** (as per [Fine grain admin permissions](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions)) can't view and can't configure the settings on the **Client** -> **Authorization** tab, although the **restricted admin** has the **Client**'s `view` scope from the **Fine grain admin permissions** assigned.

The other tabs (e.g. `Settings`, `Keys`, `Roles`, `Client scopes`, `Service account roles`, `Sessions`, `Advanced`) from the **Client details** page are accessible (as they should be).
But the `Authorization` tab's sub-tabs aren't accessible.

### Version

21.1.1

### Expected behavior

A **restricted admin** with a **Client**'s `view` scope should be able to view and configure the details on the **Authorization** tab inside the **Client details** for the given `<client-id>`.

i.e.
- the following URLs should be accessible
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/settings`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/resources`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/scopes`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/policies`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/permissions`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/evaluate`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/export`
- the **restricted admin** should be able to alter the resources/policies/permissions for the given client

### Actual behavior

When navigating to the **Client details** -> **Authorization** tab, the **restricted admin** can't access the sub-tabs of the **Authorization** tab.

-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization`
:white_check_mark: the **Settings** tab is displayed (note: it's the top-level URL for the **Authorization** tab)

:x: For all the other `/authorization/*` sub-URLs
An error message displayed: `Forbidden, permission needed: view-clients`

-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/settings`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/resources`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/scopes`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/policies`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/permissions`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/evaluate`
-- `/admin/<realm>/console/#/<realm>/clients/<client-UUID>/authorization/export`

### How to Reproduce?

- Start the Keycloak instance with the [Fine grain admin permissions](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions) preview feature turned on
- Create a realm called `test`
- Create a client called `example-application` in the `test` realm, toggle the **Client Authentication** and **Authorization** switches **ON**
- Navigate to `test` ->`example-application` -> `Permissions` and switch the **Permissions enabled** to **ON**
- Create a `restricted-admin` user in the "Users" section, assign password to it; assign roles `[realm-management] query-clients` `[realm-management] manage-authorization`, `[realm-management] view-authorization`
- Navigate to the **Clients** -> `realm-management` -> **Authorization** -> **Policies**;
- Click **Create policy**, select **User**, specify **Name** `user: restricted-admin`, specify **Users** `restricted-admin`, click **Save**
- Navigate to the **Clients** -> `example-application` -> **Permissions** -> click **view** -> specify the `user: restricted-admin` policy in the **Policies** and click **Save**
- Open an incognito window, navigate to the `/admin/test/console` page, sign in with the `restricted-admin` user credential
- Navigate to the **Clients** -> `example-application` -> **Authorization**
- Try clicking on any sub-tab of the **Authorization** tab, e.g. **Settings**, **Resources**, **Scopes** etc.

The user will see an error message `Forbidden, permission needed: view-clients`.

### Anything else?

This used to work as expected in the old **Admin UI** (`keycloak`, not `keycloak.v2`).
Confirmed to be working on 18.0.2 with the now deprecated admin theme.

**Comment by mposolda** [comment] 2023-05-18 10:36
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:

- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
- If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here https://www.keycloak.org/community for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by rh-** [comment] 2023-05-18 10:44
> If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info

Yes, still reproduced with the latest Keycloak version (21.1.1).

**Comment by rekup** [comment] 2024-01-06 19:17
This is still an issue in Keycloak 23.0.3

**Comment by pedroigor** [comment] 2024-03-04 18:21
@rekup @rh- Could you please check the latest version. I can't reproduce following the steps in the description. The tabs are available and if the `manage-authorization` role is granted, the admin can also update the authorization settings.

**Comment by rh-** [comment] 2024-03-17 13:33
Hello @pedroigor,

I can confirm that this issue is fixed on the Keycloak 24.0.1.

Thank you

**Comment by pedroigor** [comment] 2024-03-18 11:05
Thanks. @rh-.

**Closed by pedroigor** 2024-03-18 11:05 UTC
Labels: kind/bug, area/admin/fine-grained-permissions, status/triage, team/core-iam, priority/low
