### ISSUE TITLE
Liquibase Error while DB migration from keycloak V14 to V20

### ISSUE THREAD

**Issue by happy0088** [keycloak/keycloak#17578] opened 2023-03-10 18:38 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

Hi , i am upgrading from V14 to V20 .

while running the database migration liquibase throws error :

ERROR: relation \"user_role\" already exists
I am using external postgres as a database connection with teh below config

```
externalDatabase:
  host: "apostgresHost"
  port: 5432
  user: postgres
  database: myDB
  password: "myPassword"
  existingSecret: ""
  existingSecretPasswordKey: ""
```
i have tried deleting the pod , restarting container but it still fails with same error .

_**Please Note - This did not occur on the first migration , but is happening when we rerun the same keycloak migration .**_

**Do we need to set any flag in db config to upsert if relation already exists ?**

### Version

20.0.3

### Expected behavior

Should complete the migration without errors

### Actual behavior

{"timestamp":"2023-02-18T08:56:51.55Z","sequence":8437,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: Migration failed for change set META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::[sthorger@redhat.com](mailto:sthorger@redhat.com):\n Reason: liquibase.exception.DatabaseException: ERROR: relation "user_role_" already exists [Failed SQL: (0) CREATE TABLE public.USER_ROLE (ROLE_ID VARCHAR(255) NOT NULL, USER_ID VARCHAR(36) NOT NULL)]","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"keycloak-release-0","processName":"QuarkusEntryPoint","processId":1}

### How to Reproduce?

upgrade to V20 .
Bring keycloak up pointing to existing database of V14 .
It tries to run migration again on multiple runs and then throws error.

**Comment by sschu** [comment] 2023-03-13 15:55
How do you rerun a Keycloak migration? Normally, you should not rerun it but the migration should be run exactly once.

**Comment by sguilhen** [comment] 2023-04-05 15:57
@happy0088 I've tried the migration from 14 to 20 and it worked as expected. I don't know exactly what you mean by "re-running the Keycloak migration" as this should happen only once when upgrading to a later KC version. In my test, running KC 20 multiple times after migrating from 14 didn't trigger further migration attempts. 

Forcing a migration to run against a DB that was already migrate is expected to fail with messages like the one you've described. Liquibase can't create a table, for example , if it already exists in the DB.

I'm closing this as I couldn't reproduce your issue. Feel free to re-open with more instructions on how exactly you are migrating if you still think there is a problem.

**Closed by sguilhen** 2023-04-05 15:57 UTC
Labels: kind/bug, area/import-export, team/store, status/triage
