### ISSUE TITLE
Incorrect warning log about deprecated option hostname-strict

### ISSUE THREAD

**Issue by Fryie** [keycloak/keycloak#33256] opened 2024-09-24 23:18 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Starting Keycloak with the option `hostname-strict=false` generates a deprecation warning. However, I can't find a deprecation notice for this option either in the [hostname documentation](https://www.keycloak.org/server/hostname) or in the [upgrade guide](https://www.keycloak.org/docs/latest/upgrading/index.html) (although other hostname options such as `hostname-strict-https` are marked as deprecated). Moreover, the warning isn't present when using `start-dev`.

This may have the same underlying issue as https://github.com/keycloak/keycloak/issues/30380.

### Version

latest

### Regression

- [X] The issue is a regression

### Expected behavior

There should be no warning **or** there should be a documented replacement for the option.

### Actual behavior

A warning is displayed

### How to Reproduce?

Command:
```docker run --rm -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin --entrypoint "/bin/bash" quay.io/keycloak/keycloak:latest -c "cd /opt/keycloak/bin && ./kc.sh build && KC_HTTP_ENABLED=true KC_HOSTNAME_STRICT=false ./kc.sh start --optimized"```

Output:
> Updating the configuration and installing your custom providers, if any. Please wait.
2024-09-24 23:14:20,142 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 4263ms
Server configuration updated and persisted. Run the following command to review the configuration:
>
>	kc.sh show-config
>
> 2024-09-24 23:14:20,703 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
	- hostname-strict
Consult the Release Notes for details.

The warning does not appear when using `start-dev`:

```docker run --rm -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HOSTNAME_STRICT=false quay.io/keycloak/keycloak:latest start-dev```

### Anything else?

The issue appears from version 25.0.0 on. Version 24.0.4 didn't have the issue.

**Comment by shawkins** [comment] 2024-09-25 11:29
Duplicate of #30380

**Closed by shawkins** 2024-09-25 11:29 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
