### ISSUE TITLE
Windows: keycloak-21.1.1 start up error

### ISSUE THREAD

**Issue by mehulkhanna25** [keycloak/keycloak#20115] opened 2023-05-03 10:22 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

keycloak-21.1.1 does not start up under windows

### Version

keycloak-21.1.1

### Expected behavior

keycloak-21.1.1 should start up under windows

### Actual behavior

C:\Mehul Khanna\Softwares\keycloak-21.1.1>java --version
java 17.0.7 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

C:\Mehul Khanna\Softwares\keycloak-21.1.1>javac --version
javac 17.0.7

C:\Mehul Khanna\Softwares\keycloak-21.1.1>.\bin\kc.bat start-dev
Error: Could not find or load main class Khanna\Softwares\keycloak-21.1.1\bin\..
Caused by: java.lang.ClassNotFoundException: Khanna\Softwares\keycloak-21/1/1\bin\//

### How to Reproduce?

1. install openjdk 17.0.7 2023-04-18 LTS
2. install keycloak-21.1.1 under windows as recommended by the documentation
3. run .\bin\kc.bat start-dev

**Comment by mehulkhanna25** [comment] 2023-05-03 10:27
Please let me know. What to do now

**Comment by lrozenblyum** [comment] 2023-05-03 10:30
@mehulkhanna25 which software have you used to unpack the keycloak archive? 
Maybe it has been corrupted or unzipped incorrectly?

Try downloading the *.zip archive and unpacking it again.

**Comment by lrozenblyum** [comment] 2023-05-03 10:31
Alternative theory: maybe it's caused by spaces in the directory path, try to use a dir. without spaces

**Comment by mehulkhanna25** [comment] 2023-05-03 10:37
> @mehulkhanna25 which software have you used to unpack the keycloak archive? Maybe it has been corrupted or unzipped incorrectly?
> 
> Try downloading the *.zip archive and unpacking it again.

I have used WinRAR to extrat that .zip file

Again tried.. Same is coming as :
C:\Mehul Khanna\Softwares\keycloak-21.1.1>.\bin\kc.bat start-dev
Error: Could not find or load main class Khanna\Softwares\keycloak-21.1.1\bin\..
Caused by: java.lang.ClassNotFoundException: Khanna\Softwares\keycloak-21/1/1\bin\//

**Comment by jsorah** [comment] 2023-05-03 12:14
Can confirm it is the spaces in the path. A quick workaround is just moving it to a directory tree with no spaces in it.

Quoting a few vars resolved in the `kc.bat` appears to fix this, though further testing should happen for full functionality check as I just quickly made these changes to see if I could get it to start. Mainly here https://github.com/keycloak/keycloak/blob/main/quarkus/dist/src/main/content/bin/kc.bat#L137


the specific changes I made to that line

```batch
set JAVA_RUN_OPTS=%JAVA_OPTS% -Dkc.home.dir="%DIRNAME%.." -Djboss.server.config.dir="%DIRNAME%..\conf" -Dkeycloak.theme.dir="%DIRNAME%..\themes" %SERVER_OPTS% -cp "%CLASSPATH_OPTS%" io.quarkus.bootstrap.runner.QuarkusEntryPoint %CONFIG_ARGS%
```

**Comment by mehulkhanna25** [comment] 2023-05-03 12:47
Thanks same worked for me

**Comment by mposolda** [comment] 2023-05-04 06:32
I am re-opening as this looks like a valid bug and probably something, which should be ideally fixed in Keycloak 22.

@jsorah Can you please send PR since you already figured how to fix it? :-)

**Comment by vmuzikar** [comment] 2023-05-04 06:59
@mposolda @jsorah Thanks for looking into it! I believe we were recently looking into a very similar issue: https://github.com/keycloak/keycloak/issues/19803

CC: @Pepo48

**Comment by Pepo48** [comment] 2023-05-04 07:22
@mposolda @jsorah the issues are caused by [these changes](https://github.com/keycloak/keycloak/pull/16229/files#diff-743aef43b0717e3b41db7c269c0a8460de315f6a5b2cde028fbbcb5c1fc41370). Some of the quotes are still necessary because of the possible white character presence. In my recent PR mentioned above I reverted some of the changes because of the java binary path issues that were reported.

We can revert the qoutes wherever it is necessary, we just need to be extra cautious to not to reintroduce https://github.com/keycloak/keycloak/issues/16189 and https://github.com/keycloak/keycloak/issues/16319.

Also, when the PR will be ready, please contact @miquelsi and he will run the internal pipeline that can be executed on Windows machines. During my PR testing we encountered multiple issues that were specific just to our environment.

Thanks for your time and effort!

**Comment by jsorah** [comment] 2023-05-08 12:22
PR #20212 is up for review, this should address the regression with #16189  as well as the behavior noted in this issue.

**Comment by vmuzikar** [comment] 2023-05-30 12:26
This is related to Quarkus dist only, removing the Core Team and removing from 22 milestone.

**Comment by ncphins** [comment] 2023-07-27 13:29
Since this has been removed from the 22 milestone, does that mean this will not be fixed in 22? Meaning users will not be able to install in a path with spaces (ie "Program Files") on Windows?

**Comment by baparker** [comment] 2023-08-09 00:28
I modified my local kc.bat file myself to work with spaces because we are installing at C:\Program Files\Keycloak. Part of our upgrade process until this is fixed is to merge our fix with the latest kc.bat file. Would greatly appreciate this being fixed.

**Comment by EricLee423** [comment] 2023-09-14 07:18
Hi @jsorah 
We still run into same issue in Keycloak 22.0.3.
the DIRNAME should be quoted as well since it may have space inside. Below is the modified file for your reference.

_set CLASSPATH_OPTS="%DIRNAME%..\lib\quarkus-run.jar"

set JAVA_RUN_OPTS=%JAVA_OPTS% -Dkc.home.dir="%DIRNAME%.." -Djboss.server.config.dir="%DIRNAME%..\conf" -Dkeycloak.theme.dir="%DIRNAME%..\themes" %SERVER_OPTS% -cp %CLASSPATH_OPTS% io.quarkus.bootstrap.runner.QuarkusEntryPoint %CONFIG_ARGS%_

**Closed** 2023-10-20 16:11 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native
