### ISSUE TITLE
Keycloak Delete User From USER_ENTITY Automatically

### ISSUE THREAD

**Issue by hpwahyao** [keycloak/keycloak#12257] opened 2022-05-30 16:15 UTC
### Describe the bug

Keycloak randomly delete user from database. Spotting the issue for a couple of days as the issue is persistent from Keycloak 12 to Keycloak 15. I think this is very serious bug, once the user is deleted, all his groups are gone. it directly impacts the confidence level of the product. 

Before Keycloak starts to delete user, here are the logs I see from the file. 

_2022-05-27 17:25:53,156 DEBUG [org.hibernate.engine.loading.internal.CollectionLoadContext] (default task-4978) No collections were found in result set for role: org.keycloak.models.jpa.entities.UserEntity.attributes
2022-05-27 17:25:53,156 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (default task-4978) Initiating JDBC connection release from afterStatement
2022-05-27 17:25:53,157 INFO  [org.jboss.jca.core.connectionmanager.listener.TxConnectionListener] (default task-4978) IJ000311: Throwable from unregister connection: java.lang.IllegalStateException: IJ000152: Trying to return an unknown connection: org.jboss.jca.adapters.jdbc.jdk8.WrappedConnectionJDK8@5fa22d2a
        at org.jboss.ironjacamar.impl@1.4.27.Final//org.jboss.jca.core.connectionmanager.ccm.CachedConnectionManagerImpl.unregisterConnection(CachedConnectionManagerImpl.java:408)
        at org.jboss.ironjacamar.impl@1.4.27.Final//org.jboss.jca.core.connectionmanager.listener.TxConnectionListener.connectionClosed(TxConnectionListener.java:645)
        at org.jboss.ironjacamar.jdbcadapters@1.4.27.Final//org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.returnHandle(BaseWrapperManagedConnection.java:600)
        at org.jboss.ironjacamar.jdbcadapters@1.4.27.Final//org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.closeHandle(BaseWrapperManagedConnection.java:545)
        at org.jboss.ironjacamar.jdbcadapters@1.4.27.Final//org.jboss.jca.adapters.jdbc.WrappedConnection.returnConnection(WrappedConnection.java:310)
        at org.jboss.ironjacamar.jdbcadapters@1.4.27.Final//org.jboss.jca.adapters.jdbc.WrappedConnection.close(WrappedConnection.java:268)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.closeConnection(DatasourceConnectionProviderImpl.java:127)
        at org.hibernate@5.3.20.Final//org.hibernate.internal.NonContextualJdbcConnectionAccess.releaseConnection(NonContextualJdbcConnectionAccess.java:46)
        at org.hibernate@5.3.20.Final//org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.releaseConnection(LogicalConnectionManagedImpl.java:196)
        at org.hibernate@5.3.20.Final//org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.afterStatement(LogicalConnectionManagedImpl.java:149)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.afterStatementExecution(JdbcCoordinatorImpl.java:265)
        at org.hibernate@5.3.20.Final//org.hibernate.loader.Loader.doQuery(Loader.java:972)
        at org.hibernate@5.3.20.Final//org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
        at org.hibernate@5.3.20.Final//org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:321)
        at org.hibernate@5.3.20.Final//org.hibernate.loader.Loader.loadCollectionBatch(Loader.java:2536)
        at org.hibernate@5.3.20.Final//org.hibernate.loader.collection.plan.LegacyBatchingCollectionInitializerBuilder$LegacyBatchingCollectionInitializer.initialize(LegacyBatchingCollectionInitializerBuilder.java:83)
        at org.hibernate@5.3.20.Final//org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:692)_

After the log above, it will start to delete the user from different tables. Logs as below: 

2022-05-27 17:25:53,163 DEBUG [org.hibernate.engine.internal.Collections] (default task-4978) Collection found: [org.keycloak.models.jpa.entities.UserEntity.requiredActions#bf059a0b-c740-41d1-99e3-f1295f2f469a], was: [org.keycloak.models.jpa.entities.UserEntity.requiredActions#bf059a0b-c740-41d1-99e3-f1295f2f469a] (uninitialized)
2022-05-27 17:25:53,163 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Flushed: 0 insertions, 0 updates, 0 deletions to 1 objects
2022-05-27 17:25:53,163 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Flushed: 0 (re)creations, 0 updates, 0 removals to 4 collections
2022-05-27 17:25:53,163 DEBUG [org.hibernate.internal.util.EntityPrinter] (default task-4978) Listing entities:
2022-05-27 17:25:53,163 DEBUG [org.hibernate.internal.util.EntityPrinter] (default task-4978) org.keycloak.models.jpa.entities.UserEntity{lastName=<<masked due to sensitive data>>, federatedIdentities=<uninitialized>, realmId=sso, credentials=<uninitialized>, createdTimestamp=1652680188370, serviceAccountClientLink=null, enabled=true, notBefore=0, emailConstraint=<<masked due to sensitive data>>, emailVerified=false, firstName=<<masked due to sensitive data>>, requiredActions=<uninitialized>, federationLink=7f507ca2-7e0a-47fc-8d9e-77b8b52719bb, attributes=<uninitialized>, id=bf059a0b-c740-41d1-99e3-f1295f2f469a, email=<<masked due to sensitive data>>, username=<<masked due to sensitive data>>}
2022-05-27 17:25:53,163 DEBUG [org.hibernate.SQL] (default task-4978)
    delete
    from
        USER_ROLE_MAPPING
    where
        USER_ID=?
2022-05-27 17:25:53,163 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (default task-4978) Initiating JDBC connection release from afterStatement
2022-05-27 17:25:53,163 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Processing flush-time cascades
2022-05-27 17:25:53,163 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Dirty checking collections
2022-05-27 17:25:53,163 DEBUG [org.hibernate.engine.internal.Collections] (default task-4978) Collection found: [org.keycloak.models.jpa.entities.UserEntity.attributes#bf059a0b-c740-41d1-99e3-f1295f2f469a], was: [org.keycloak.models.jpa.entities.UserEntity.attributes#bf059a0b-c740-41d1-99e3-f1295f2f469a] (uninitialized)
2022-05-27 17:25:53,163 DEBUG [org.hibernate.engine.internal.Collections] (default task-4978) Collection found: [org.keycloak.models.jpa.entities.UserEntity.credentials#bf059a0b-c740-41d1-99e3-f1295f2f469a], was: [org.keycloak.models.jpa.entities.UserEntity.credentials#bf059a0b-c740-41d1-99e3-f1295f2f469a] (uninitialized)
2022-05-27 17:25:53,163 DEBUG [org.hibernate.engine.internal.Collections] (default task-4978) Collection found: [org.keycloak.models.jpa.entities.UserEntity.federatedIdentities#bf059a0b-c740-41d1-99e3-f1295f2f469a], was: [org.keycloak.models.jpa.entities.UserEntity.federatedIdentities#bf059a0b-c740-41d1-99e3-f1295f2f469a] (uninitialized)
2022-05-27 17:25:53,163 DEBUG [org.hibernate.engine.internal.Collections] (default task-4978) Collection found: [org.keycloak.models.jpa.entities.UserEntity.requiredActions#bf059a0b-c740-41d1-99e3-f1295f2f469a], was: [org.keycloak.models.jpa.entities.UserEntity.requiredActions#bf059a0b-c740-41d1-99e3-f1295f2f469a] (uninitialized)
2022-05-27 17:25:53,163 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Flushed: 0 insertions, 0 updates, 0 deletions to 1 objects
2022-05-27 17:25:53,163 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Flushed: 0 (re)creations, 0 updates, 0 removals to 4 collections
2022-05-27 17:25:53,163 DEBUG [org.hibernate.internal.util.EntityPrinter] (default task-4978) Listing entities:
2022-05-27 17:25:53,163 DEBUG [org.hibernate.internal.util.EntityPrinter] (default task-4978) org.keycloak.models.jpa.entities.UserEntity{lastName=<<masked due to sensitive data>>, federatedIdentities=<uninitialized>, realmId=sso, credentials=<uninitialized>, createdTimestamp=1652680188370, serviceAccountClientLink=null, enabled=true, notBefore=0, emailConstraint=<<masked due to sensitive data>>, emailVerified=false, firstName=<<masked due to sensitive data>>, requiredActions=<uninitialized>, federationLink=7f507ca2-7e0a-47fc-8d9e-77b8b52719bb, attributes=<uninitialized>, id=bf059a0b-c740-41d1-99e3-f1295f2f469a, email=<<masked due to sensitive data>>, username=<<masked due to sensitive data>>}
2022-05-27 17:25:53,163 DEBUG [org.hibernate.SQL] (default task-4978)
    delete
    from
        USER_GROUP_MEMBERSHIP
    where
        USER_ID=?
2022-05-27 17:25:53,172 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (default task-4978) Initiating JDBC connection release from afterStatement
2022-05-27 17:25:53,172 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Processing flush-time cascades
2022-05-27 17:25:53,172 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (default task-4978) Dirty checking collections
2022-05-27 17:25:53,172 DEBUG [org.hibernate.engine.internal.Collections] (default task-4978) Collection found: [org.keycloak.models.jpa.entities.UserEntity.attributes#bf059a0b-c740-41d1-99e3-f1295f2f469a], was: [org.keycloak.models.jpa.entities.UserEntity.attributes#bf059a0b-c740-41d1-99e3-f1295f2f469a] (uninitialized)
2022-05-27 17:25:53,172 DEBUG [org.hibernate.engine.internal.Collections] (default task-4978) Collection found: [org.keycloak.models.jpa.entities.UserEntity.credentials#bf059a0b-c740-41d1-99e3-f1295f2f469a], was: [org.keycloak.models.jpa.entities.UserEntity.credentials#bf059a0b-c740-41d1-99e3-f1295f2f469a] (uninitialized)

### Version

15

**Comment by stianst** [comment] 2022-06-03 07:38
From discussion on dev mailing list looks like this is caused by LDAP syncing, and is probably related to:
https://github.com/keycloak/keycloak/issues/9520

**Comment by hmlnarik** [comment] 2022-12-13 14:29
Duplicate of #9520

**Closed by hmlnarik** 2022-12-13 14:29 UTC
Labels: kind/bug, area/ldap, status/triage
