### ISSUE TITLE
Infinispan crashes with NPE when upgrading keycloak running on k8s from 21.1.1 to 21.1.2 or 22.0.0

### ISSUE THREAD

**Issue by fredriklindberg** [keycloak/keycloak#21754] opened 2023-07-17 16:47 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

It's not possible to upgrade a keycloak running with kubernetes native distributed caching.

During startup it crashes with a NullPointerException inside jgroups.

```
2023-07-17 16:15:39,117 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: localhost, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2023-07-17 16:15:40,566 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-07-17 16:15:41,350 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-07-17 16:15:41,456 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-07-17 16:15:41,651 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2023-07-17 16:15:41,652 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 1511da92-5758-48e1-adbf-f9604012ae65, name: keycloak-5c9ddf6b5f-fjmxx-21596
2023-07-17 16:15:41,705 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.57800
2023-07-17 16:15:41,755 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-8458c9d965-nfr8j-26871|36] (2) [keycloak-8458c9d965-nfr8j-26871, keycloak-5c9ddf6b5f-fjmxx-21596]
2023-07-17 16:15:41,837 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-5c9ddf6b5f-fjmxx-21596`, physical addresses are `[10.244.2.8:7800]`
2023-07-17 16:15:42,035 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-5c9ddf6b5f-fjmxx-21596) [Context=org.infinispan.CONFIG] ISPN100002: Starting rebalance with members [keycloak-8458c9d965-nfr8j-26871, keycloak-5c9ddf6b5f-fjmxx-21596], phase READ_OLD_WRITE_ALL, topology id 38
2023-07-17 16:15:42,035 ERROR [org.infinispan.CLUSTER] (jgroups-6,keycloak-5c9ddf6b5f-fjmxx-21596) ISPN000475: Error processing response for request 2 from keycloak-8458c9d965-nfr8j-26871: java.io.EOFException
	at org.infinispan.marshall.core.AbstractBytesObjectInput.checkPosLength(AbstractBytesObjectInput.java:261)
	at org.infinispan.marshall.core.AbstractBytesObjectInput.readByte(AbstractBytesObjectInput.java:107)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallSize(MarshallUtil.java:426)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:271)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
	at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:86)
	at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:70)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
	at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1570)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1480)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1685)
	at org.jgroups.JChannel.up(JChannel.java:733)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:921)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:138)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:845)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:226)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1052)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:794)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:776)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:425)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:658)
	at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:188)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
	at org.jgroups.protocols.Discovery.up(Discovery.java:294)
	at org.jgroups.stack.Protocol.up(Protocol.java:314)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1178)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:100)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "org.jgroups.stack.IpAddress.getIpAddress()" because "pa" is null
	at org.jgroups.protocols.FD_SOCK2.getPhysicalAddresses(FD_SOCK2.java:445)
	at org.jgroups.protocols.FD_SOCK2.connectTo(FD_SOCK2.java:395)
	at org.jgroups.protocols.FD_SOCK2.connectToNextPingDest(FD_SOCK2.java:376)
	at org.jgroups.protocols.FD_SOCK2.handle(FD_SOCK2.java:347)
	at org.jgroups.protocols.FD_SOCK2.handle(FD_SOCK2.java:31)
	at org.jgroups.util.ProcessingQueue.process(ProcessingQueue.java:55)
	at org.jgroups.util.ProcessingQueue.add(ProcessingQueue.java:35)
	at org.jgroups.protocols.FD_SOCK2.handleView(FD_SOCK2.java:364)
	at org.jgroups.protocols.FD_SOCK2.down(FD_SOCK2.java:227)
	at org.jgroups.protocols.FailureDetection.down(FailureDetection.java:149)
	at org.jgroups.protocols.VERIFY_SUSPECT2.down(VERIFY_SUSPECT2.java:84)
	at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:619)
	at org.jgroups.protocols.UNICAST3.down(UNICAST3.java:611)
	at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:260)
	at org.jgroups.protocols.pbcast.GMS.installView(GMS.java:676)
	at org.jgroups.protocols.pbcast.ServerGmsImpl.handleViewChange(ServerGmsImpl.java:66)
	at org.jgroups.protocols.pbcast.ParticipantGmsImpl.handleViewChange(ParticipantGmsImpl.java:112)
	at org.jgroups.protocols.pbcast.GMS.handle(GMS.java:991)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:855)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:246)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:470)
	at org.jgroups.protocols.pbcast.NAKACK2.deliverBatch(NAKACK2.java:1010)
	at org.jgroups.protocols.pbcast.NAKACK2.removeAndDeliver(NAKACK2.java:943)
	at org.jgroups.protocols.pbcast.NAKACK2.handleMessageBatch(NAKACK2.java:915)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:747)
	at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:119)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:193)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:202)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:288)
	at org.jgroups.protocols.Discovery.up(Discovery.java:314)
	at org.jgroups.protocols.RED.up(RED.java:119)
	at org.jgroups.protocols.TP.passBatchUp(TP.java:1204)
	at org.jgroups.util.MaxOneThreadPerSender$BatchHandlerLoop.passBatchUp(MaxOneThreadPerSender.java:289)
	at org.jgroups.util.SubmitToThreadPool$BatchHandler.run(SubmitToThreadPool.java:150)
	at org.jgroups.util.MaxOneThreadPerSender$BatchHandlerLoop.run(MaxOneThreadPerSender.java:278)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-07-17 16:15:49,952 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-5c9ddf6b5f-fjmxx-21596) ISPN000094: Received new cluster view for channel ISPN: [keycloak-8458c9d965-nfr8j-26871|37] (3) [keycloak-8458c9d965-nfr8j-26871, keycloak-5c9ddf6b5f-fjmxx-21596, b2207e5b-d842-48da-b670-d73d55ad48ae]
2023-07-17 16:15:49,953 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-5c9ddf6b5f-fjmxx-21596) ISPN100000: Node b2207e5b-d842-48da-b670-d73d55ad48ae joined the cluster
2023-07-17 16:15:49,954 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-5c9ddf6b5f-fjmxx-21596) ISPN100000: Node b2207e5b-d842-48da-b670-d73d55ad48ae joined the cluster
```

After this the pod is killed due to unhealthy liveness probe

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned default/keycloak-5c9ddf6b5f-fjmxx to minikube
  Normal   Pulling    18m                   kubelet            Pulling image "quay.io/keycloak/keycloak:nightly"
  Normal   Pulled     18m                   kubelet            Successfully pulled image "quay.io/keycloak/keycloak:nightly" in 10.638319172s (10.638424881s including waiting)
  Normal   Created    18m                   kubelet            Created container build
  Normal   Started    18m                   kubelet            Started container build
  Warning  Unhealthy  17m (x3 over 17m)     kubelet            Liveness probe failed: Get "http://10.244.2.8:8080/health/live": dial tcp 10.244.2.8:8080: connect: connection refused
  Normal   Killing    17m                   kubelet            Container keycloak failed liveness probe, will be restarted
  Normal   Pulled     17m (x2 over 18m)     kubelet            Container image "quay.io/keycloak/keycloak:nightly" already present on machine
  Normal   Created    17m (x2 over 18m)     kubelet            Created container keycloak
  Normal   Started    17m (x2 over 18m)     kubelet            Started container keycloak
  Warning  Unhealthy  13m (x47 over 18m)    kubelet            Readiness probe failed: Get "http://10.244.2.8:8080/health/ready": dial tcp 10.244.2.8:8080: connect: connection refused
  Warning  BackOff    3m32s (x35 over 12m)  kubelet            Back-off restarting failed container keycloak in pod keycloak-5c9ddf6b5f-fjmxx_default(deb96f49-56ae-4d42-ab1a-3218acb3b79d)
```

I believe this may is the source of the problem

Release 21.1.2 upgrades Infinispan to [14.0.8](https://github.com/keycloak/keycloak/commit/10e96f387a0ab469728302ae72b3fdf864700e57)

Infinispan 14.0.8 brings in jgroup [5.2.12](https://github.com/infinispan/infinispan/pull/10622).

Not sure exactly what's changed in Infinispan 14.0.8, but jgroup 5.2.16 contains a fix for this NPE https://github.com/belaban/JGroups/commit/2e8cb5a11060ae0f135b272c3540604839d98ae8 and https://issues.redhat.com/browse/JGRP-2707

### Version

21.1.1

### Expected behavior

Able to upgrade to 21.1.2 or 22.0.0

### Actual behavior

Crash during startup due to `java.lang.NullPointerException: Cannot invoke "org.jgroups.stack.IpAddress.getIpAddress()" because "pa" is null`

### How to Reproduce?

Deploy 21.1.1 to a K8S cluster with kubernetes, can be reproduced inside minikube

Configuration
```
  KC_CACHE: ispn
  KC_CACHE_STACK: kubernetes
  KC_HOSTNAME: localhost
  KC_DB: postgres
  KC_DB_URL: "jdbc:postgresql://pgsql-postgresql:5432/keycloak?password=keycloak&user=keycloak&characterEncoding=UTF-8"
  KEYCLOAK_ADMIN: "keycloak"
  KEYCLOAK_ADMIN_PASSWORD: "keycloak"
```

After deployment of 21.1.1, upgrade to 21.1.2 or 22.0.0

**Comment by trixpan** [comment] 2023-07-17 21:22
seems like a duplicate of 

https://github.com/keycloak/keycloak/issues/21092
https://github.com/keycloak/keycloak/issues/21119

Having said that, AFAIK Keycloak still doesn't support zero downtime upgrades when using RDBMS.

**Closed** 2023-07-18 12:30 UTC
Labels: kind/bug, area/infinispan, team/store, status/triage
