### ISSUE TITLE
Workflow failure: Operator IT on OpenShift instabilities

### ISSUE THREAD

**Issue by vaceksimon** [keycloak/keycloak#29589] opened 2024-05-16 08:19 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

This issue seems related to #28870 and #28869
3 out of 4 runs failed

```
2024-05-13 18:56:33  [ERROR] Errors: 
2024-05-13 18:56:33  [ERROR]   KeycloakIngressTest.testFallbackToDefaultProxySettings:120 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.utils.K8sUtils 
2024-05-13 18:56:33  expected: true
2024-05-13 18:56:33   but was: false within 5 minutes.
2024-05-13 18:56:33  [INFO] 
2024-05-13 18:56:33  [ERROR] Tests run: 116, Failures: 0, Errors: 1, Skipped: 4
```
Log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/430/execution/node/69/log/

```
2024-05-14 11:45:13  [ERROR] Errors: 
2024-05-14 11:45:13  [ERROR]   ClusteringTest.testKeycloakCacheIsConnected:212 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.integration.ClusteringTest 
2024-05-14 11:45:13  Expecting any elements of:
2024-05-14 11:45:13    [KeycloakRealmImportStatusCondition{type='Done', status=False, message=''},
2024-05-14 11:45:13      KeycloakRealmImportStatusCondition{type='Started', status=False, message=''},
2024-05-14 11:45:13      KeycloakRealmImportStatusCondition{type='HasErrors', status=True, message='Deployment not yet ready, waiting for it to be ready'}]
2024-05-14 11:45:13  to match given predicate but none did within 10 minutes.
2024-05-14 11:45:13  [ERROR]   ClusteringTest.testKeycloakScaleAsExpected:115 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.utils.K8sUtils 
2024-05-14 11:45:13  expected: true
2024-05-14 11:45:13   but was: false within 5 minutes.
2024-05-14 11:45:13  [INFO] 
2024-05-14 11:45:13  [ERROR] Tests run: 116, Failures: 0, Errors: 2, Skipped: 4
```
Log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/432/execution/node/69/log/

```
2024-05-14 14:05:32  [ERROR] Errors: 
2024-05-14 14:05:32  [ERROR]   ClusteringTest.testKeycloakCacheIsConnected:212 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.integration.ClusteringTest 
2024-05-14 14:05:32  Expecting any elements of:
2024-05-14 14:05:32    [KeycloakRealmImportStatusCondition{type='Done', status=False, message=''},
2024-05-14 14:05:32      KeycloakRealmImportStatusCondition{type='Started', status=False, message=''},
2024-05-14 14:05:32      KeycloakRealmImportStatusCondition{type='HasErrors', status=True, message='Deployment not yet ready, waiting for it to be ready'}]
2024-05-14 14:05:32  to match given predicate but none did within 10 minutes.
2024-05-14 14:05:32  [ERROR]   ClusteringTest.testKeycloakScaleAsExpected:115 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.utils.K8sUtils 
2024-05-14 14:05:32  expected: true
2024-05-14 14:05:32   but was: false within 5 minutes.
2024-05-14 14:05:32  [INFO] 
2024-05-14 14:05:32  [ERROR] Tests run: 116, Failures: 0, Errors: 2, Skipped: 4
```
Log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/433/execution/node/69/log/

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

- 

### Actual behavior

- 

### How to Reproduce?

-

**Comment by vaceksimon** [comment] 2024-05-16 08:20
Tagging responders of the previous mentioned issues: @vmuzikar @shawkins @miquelsi

**Comment by shawkins** [comment] 2024-05-16 12:40
Based upon the logging sequence 

```
2024-05-14 07:35:36  2024-05-14 07:35:35,037 WARN  [org.key.ope.tes.int.BaseOperatorTest] (main) Event last seen 2024-05-14T11:30:35Z repeated 1 times - Warning Unhealthy example-kc-0.17cf5744d7fed8eb Startup probe failed: Get "https://10.129.2.72:8443/health/started": dial tcp 10.129.2.72:8443: connect: connection refused
2024-05-14 07:35:36  2024-05-14 07:35:35,037 INFO  [org.key.ope.tes.int.BaseOperatorTest] (main) Event last seen 2024-05-14T11:25:35Z repeated 1 times - Normal Created example-kc-0.17cf57448f7a0b16 Created container keycloak
2024-05-14 07:35:36  2024-05-14 07:35:35,037 INFO  [org.key.ope.tes.int.BaseOperatorTest] (main) Event last seen 2024-05-14T11:25:35Z repeated 1 times - Normal Started example-kc-0.17cf5744907f80dc Started container keycloak
2024-05-14 07:35:36  2024-05-14 07:35:35,037 INFO  [org.key.ope.tes.int.BaseOperatorTest] (main) Event last seen 2024-05-14T11:25:34Z repeated 1 times - Normal AddedInterface example-kc-0.17cf5744722ac493 Add eth0 [10.129.2.72/23] from ovn-kubernetes
```

This does seem to be the same as the existing issues. These have not be reproducible for us - it does seem environmental.

Note that the Keycloak instance logs and the events both stop at 2024-05-14T11:25:34Z - we have no visibiility past that point what, or why the instance is not coming up. After 10 minutes pass the test gives up and throws an error.

@miquelsi can this be resolved as a duplicate?

**Comment by shawkins** [comment] 2024-05-21 15:11
duplicate of #28869

**Closed by shawkins** 2024-05-21 15:11 UTC
Labels: kind/bug, area/ci, team/continuous-testing, flaky-job, backport/24.0
