### ISSUE TITLE
Slow user query by attribute

### ISSUE THREAD

**Issue by frederic-kneier** [keycloak/keycloak#12671] opened 2022-06-23 08:39 UTC
### Describe the bug

If querying users by attribute values the response is really slow. 

On further investigation the query is missing the database index because attribute name and value is queried by lower value, eg. lower(name) and lower(value).

Either remove lower and match the actual value (which seems to be the more reasonable approach) or add a matching new index to the attribute table: 
``` CREATE INDEX index ON user_attribute(lower(name), lower(value)); ```

### Version

18.0.1

### Expected behavior

Query by attribute returns in a reasonable time.

### Actual behavior

Query takes really long and produces a lot of load on the database.

### How to Reproduce?

Just query by attribute.

### Anything else?

Adding a max value to the query totally breaks the request. (Timeouts)

**Comment by frederic-kneier** [comment] 2022-07-27 14:39
Any reaction?

**Comment by ttupekadd** [comment] 2022-09-08 15:07
this becomes an issue for us as well, on keycloak 15

**Comment by sschu** [comment] 2022-09-09 07:09
AFAIK this kind of index is not supported on all databases, e.g. not on MS SQL. You will have to add a computed column there. On the other hand, MS SQL is case-insensitive by default anyways, so you might use your own provider to change the query. If you are on PostgreSQL, that apparently supports this kind of index, you can just add it by hand or in a custom migration.

**Comment by hmlnarik** [comment] 2022-09-09 07:52
This is indeed a bug. Thank you for reporting.

The cause is here, none of the `builder.lower` and `.toLowerCase()` should be done.
https://github.com/keycloak/keycloak/blob/fb33cbc2bdcbe03a4668d90ca67d656ebea2fc8d/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L845-L846

**Comment by crackalak** [comment] 2022-09-16 18:19
I have come across a similar issue with querying by URL, looks like the cause is here: 
https://github.com/keycloak/keycloak/blob/2252c65ec7b4ae612b3a5e45089f68f7f795c6ce/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceStore.java#L180

**Comment by dalbani** [comment] 2023-02-21 10:04
Thanks @sschu for the suggestion about added an `jpa-changelog-<your version>.xml` migration.  
Although I'm not so sure how to integrate that in a Docker/Kubernetes setup. How could I do that?
I have very little experience with Liquibase, so I'm also a bit worried of what the consequences would be in terms of maintenance or introducing conflicts/incompatibilities with the standard Liquibase migrations. Should I need to pay attention to something?

I'm curious why the fix suggested at https://github.com/hmlnarik/keycloak/commit/a68f7fceb83872e3ddd3c47925768e0a504700a5 has been considered (yet). Or is it not as simple as it seems?

**Comment by sschu** [comment] 2023-02-21 10:10
I would probably just add the migration to your own custom Keycloak image. The only important thing is which version to give it so it runs in the correct order.

**Comment by dalbani** [comment] 2023-02-21 10:19
From https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml, it seems that Liquibase uses such a list of migrations, doesn't it?
Would I need to overwrite this file?? Or does Liquibase look at a specific location in the classpath or such? If so, would I need to alter some JARs??
Sorry for all those questions, but the implementation details are not really obvious to me 😸

**Comment by sschu** [comment] 2023-02-21 11:41
I just checked how we used to do it on the image and yeah, you would have to alter some jars - so it's a bit more involved. We had a script to insert migrations:
```
#!/bin/bash

insert_changelog() {

    MATCH_FILE="$1"
    INSERT_FILE="$2"
    MASTER_FILE="$3"

    MATCH='    <include file=\"META-INF\/'${MATCH_FILE}'\"\/>'
    INSERT='    <include file=\"META-INF\/'${INSERT_FILE}'\"\/>'

    sed -i "s/${MATCH}/${MATCH}\n${INSERT}/" ${MASTER_FILE}
    mv ${INSERT_FILE} ./META-INF/
}

KEYCLOAK_VERSION=$1

MODEL_JPA="keycloak-model-jpa-${KEYCLOAK_VERSION}.jar"

MASTER_FILE="META-INF/jpa-changelog-master.xml"

jar -xf ${MODEL_JPA} ${MASTER_FILE}

insert_changelog "jpa-changelog-4.3.0.xml" "jpa-changelog-4.3.0-attributes.xml" "$MASTER_FILE"
insert_changelog "jpa-changelog-13.0.0.xml" "jpa-changelog-13.0.99-attributes.xml" "$MASTER_FILE"

jar -uf ${MODEL_JPA} ./META-INF/
```
You would have to call this script from while building the image like that:
```
# add custom migrations
cp /opt/jboss/custom/db_migrations/jpa-changelog-*.xml /opt/jboss/keycloak/modules/system/layers/keycloak/org/keycloak/keycloak-model-jpa/main
cp /opt/jboss/custom/db_migrations/insert-changelog.sh /opt/jboss/keycloak/modules/system/layers/keycloak/org/keycloak/keycloak-model-jpa/main

cd /opt/jboss/keycloak/modules/system/layers/keycloak/org/keycloak/keycloak-model-jpa/main
./insert-changelog.sh $KEYCLOAK_VERSION
```
Maybe it would be in fact easier to just run a custom script against the database.

**Comment by dalbani** [comment] 2023-02-21 11:55
Thanks for the very detailed answer. I think I'll stick to the solution involving running a custom script 😄

**Comment by anlesk** [comment] 2023-08-02 13:44
Seeing the same issue with the request. Fixed by adding the index suggested in the thread.

**Comment by sschu** [comment] 2023-08-04 17:05
Actually, the bug @hmlnarik mentioned is still there. But I can provide a PR to fix that.

**Comment by sschu** [comment] 2023-08-07 08:18
PR: https://github.com/keycloak/keycloak/pull/22285

**Comment by dalbani** [comment] 2024-03-18 17:47
I don't know exactly what that means, but I'm excited to see some activity on this issue 🙇

**Closed** 2024-03-21 11:35 UTC
Labels: kind/bug, priority/important, area/storage, team/core-iam

**Comment by newwdles** [comment] 2025-02-07 08:37
Sorry for digging up this issue but we're still having issue with the search by attribute query. Looking at the fix when the value is less than 255 chars it is passed through the lower function which cause an index bypass (at least on our database engine which is sql server 2019). This cause a major cpu usage on a large table.
Here's the explain plan of the request (sorry for the french, i can't change the language easily) : 

![Image](https://github.com/user-attachments/assets/a7270270-28c8-4cc2-8f9a-cf660d1d2160)

We're on keycloak 26.0.8 and the DB is SQL Server 2019 15.0.2130.3

**Comment by eedzjee** [comment] 2025-02-07 15:05
@newwdles We're actually experiencing performance issues with the user_attribute search as well. The weird thing is that the query wants a lowercase value, but the index on the table as requested in this issue isn't triggered because of this

This index was introduced in version 14:
https://github.com/keycloak/keycloak/blob/22.0.13/model/jpa/src/main/resources/META-INF/jpa-changelog-14.0.0.xml#L105

But the query was implemented in 15: https://github.com/keycloak/keycloak/commit/5b0986e490090433658e9a1e607c0e248f4cc756
And the implementation changed over time:
- 26: `name, lower(value)` (difference in an EXACT vs LIKE query)
- 25: `name, lower(value)` (only EXACT matches)
- 24: `name, lower(value)` (difference in an EXACT vs LIKE query)
- 15 - 23: `lower(name), lower(value)` (only EXACT matches)

I guess the index should be updated to accept `lower(value)`. And one other thing that comes in to play is that it is not hit with the LIKE query, so you explicitly need to request an EXACT match to trigger it.

**Comment by ahus1** [comment] 2025-02-07 15:24
@newwdles / @eedzjee - please open a new (bug) issue, as this PR is closed.
