### ISSUE TITLE
Searching attributes fails with LDAP Federation enabled/synced

### ISSUE THREAD

**Issue by hillout** [keycloak/keycloak#25735] opened 2023-12-20 16:36 UTC
I would like to reopen the issue concerning the searching attributes. I installed brand new 23.0.3, turned on "User profile" and defined some attributes in the User profile settings. So, here when I open "Users" I see a bunch of users which I put by ansible:

![Screenshot from 2023-12-20 19-47-24](https://github.com/keycloak/keycloak/assets/15137897/0f0982a3-4d6d-4ea6-9df2-88df715e7f05)

So, once I try searching by attribute it works: 

![Screenshot from 2023-12-20 19-48-48](https://github.com/keycloak/keycloak/assets/15137897/e759e90c-8c2d-4a7c-a32b-4ce88fdfa2bc)

But, when I add Active Directory Federation and sync with those settings: 
![Screenshot from 2023-12-20 19-29-41](https://github.com/keycloak/keycloak/assets/15137897/7349b552-7d28-4260-b9d8-062cadf48b71)

In the Users I no longer can search by the same attribute (or any other): 
![Screenshot from 2023-12-20 19-50-17](https://github.com/keycloak/keycloak/assets/15137897/54c52653-6d65-4b4d-bbfc-b1a54025d969)

_Originally posted by @hillout in https://github.com/keycloak/keycloak/issues/24324#issuecomment-1864787981_

**Comment by rmartinc** [comment] 2024-01-15 17:00
@jonkoops I'm moving to UI because I think the problem is at UI level (I don't even see the call to the endpoint in the web developer tools, so the request does not reach the server). To reproduce it just use an ldap provider and search by attribute (any attribute, it can be username).

**Comment by rmartinc** [comment] 2024-01-15 17:18
Probaly this is the same of #23701. So @keycloak/ui I think you can close this as duplicate.

**Comment by hillout** [comment] 2024-01-16 07:31
@rmartinc hi, yep, looking similar.

**Comment by jonkoops** [comment] 2024-01-16 12:49
Duplicate of #23701

**Closed by jonkoops** 2024-01-16 12:49 UTC
Labels: kind/bug, area/user-profile, area/admin/ui, status/triage, team/ui
