### ISSUE TITLE
UMA Permissions completely messed up

### ISSUE THREAD

**Issue by Robbilie** [keycloak/keycloak#9298] opened 2021-12-21 23:02 UTC
### Describe the bug

Alright, the title is not super helpful but it describes the problem as best as I could.
It seems the UMA Permissions are completly broken right now, I think i remember it working properly not too long ago, I did just update keycloak though.

I am using UMA, I have a client, I create ressources with it, i set ownerManagedAccess to true and set the owner to the name of the owner, in this case uma-test-user-01.

Resource is there, resource appears in the account console under resources, so far so good.

I try to request a ticket for that user (a normal access token), the resource id and all scopes i added to the resource.
Inspecting the jwt ticket, everything looking good.

Calling the token endpoint with the same access token, the uma-ticket grant type and the ticket yields the first unexpected result:
```
{
    "error": "access_denied",
    "error_description": "request_submitted"
}
```
No, i didnt get a request in the account console from myself for trying to access my own ressource…

Alright then, surely the non-standard way of not passing the ticket but only the audience (and response mode permission) should yield the resource:
```
[
    {
        "rsid": "27f023ed-718e-451d-97a2-996f45d97dc7",
        "rsname": "Default Resource"
    }
]
```

Nope.

Now lets share access to that resource to another user using the account console. I grant 2 out of 4 scopes to another user.
I request a new ticket and exchange the ticket FOR THE OWNER USER and i suddenly get a successfull response.

But the response only contains the 2 scopes i just granted to another user. Changing that to some other subset of scopes yields the same subset as scopes.

What?!

Removing the permissions for the second user returns to the initial issue.

If the second user has no permissions, a permission request to the first user is properly sent.
If the second user has permissions, a rpt is properly returned with the correct scopes.

If the first user shares the resource with themselves (yeah why not lol…) the owner can get the permissions.

Luckily, if the owner shares it with itself the second user does not get any access so at least we got that going for us…

When removing scopes from a permission entry in the account console you can not always update the scopes, sometimes the apply button is grayed out even though you made changes, i guess thats a different bug…

### Version

15.1.1

**Comment by Robbilie** [comment] 2021-12-21 23:03
(sorry for not filling the bottom half, if absolutely required i will, but the full text version makes it easier to understand i believe)

**Comment by Robbilie** [comment] 2021-12-21 23:40
Validated the same behaviour on a second instance (running the same version though…)

**Comment by Robbilie** [comment] 2021-12-22 01:16
response_mode=decision yields result: true btw so at least that one calculates the ownership.

if sharing the resource with a second user with one scope and with a third user using one scope but a different one the permission for the resource when requested by the owner lists the scopes joined

**Comment by pedroigor** [comment] 2021-12-22 12:49
@Robbilie Not sure about how your resource server is configured, but you should have:

* A permission that grants access to resources based on the owner. See https://github.com/keycloak/keycloak-quickstarts/blob/latest/app-authz-uma-photoz/photoz-js-policies/src/main/resources/only-owner.js.
* The resource should be created and set with `ownerManagedAccess` to `true`. Looks like you are already doing that.

I'm not sure which version are you coming from, but we have tests covering the exact steps you described here too. Perhaps you can share your realm settings.

**Comment by Robbilie** [comment] 2021-12-22 15:24
i didnt do any (js) policies, im using the keycloak operator, would need to check how thats done there, but i guess thats the issue here then?

**Comment by Robbilie** [comment] 2021-12-22 15:35
i guess its just like loading an extension, alright, lets see. i dont suppose there is a jar with the owner policy available somewhere that i can just use…?

**Comment by Robbilie** [comment] 2021-12-22 17:42
while i am figuring out if:
https://github.com/keycloak/keycloak-quickstarts/tree/latest/authz-js-policies
or
https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-authz-uma-photoz/photoz-js-policies
are available somewhere as prebuilt jars

even though i dont have the policy there which probably explains why the owner doesnt see the resource, it doesnt explain, why the owner sees the resource once they grant permissions to other users, does it?

**Comment by Robbilie** [comment] 2021-12-22 17:43
realm wise i only enable user managed access and the client only has remote resource management enabled, thats about everything i configured

**Comment by Robbilie** [comment] 2021-12-22 18:20
https://github.com/Robbilie/keycloak-authz-js-policies

alright i built an extension, loaded it, it shows up, i added it using the ui next to the default policy.

i dont see any changes though…

**Comment by Robbilie** [comment] 2021-12-22 18:25
alright, i shouldve thought of that, if i add a permission with the policy assigned it works as expected.

i still think the behaviour of when there is no policy and no permission is a bit weird, dont you agree?

**Comment by pedroigor** [comment] 2022-01-04 14:15
Yes, I agree it brings some confusion if you don't consider some other aspects. But it is how it was designed so that permissions are granted/denied accordingly to the policies they are associated with.

In this particular case, ownership requires a specific policy.

I'm closing this issue then, please let me know if something else needs to be discussed.

**Closed by pedroigor** 2022-01-04 14:15 UTC
Labels: area/authorization-services, kind/bug, status/triage
