### ISSUE TITLE
414 Request-URI Too Long

### ISSUE THREAD

**Issue by strainovic** [keycloak/keycloak#14613] opened 2022-09-27 15:53 UTC
### Describe the bug

When using Keycloak as IDP and Identity Server 4 with federated provider configuration, Keycloak returns `414 Request-URI Too Long` as the URL is more than 4k in length.

### Version

19

**Comment by gutschalk** [comment] 2022-10-04 11:03
Hi, is my assumption correct, that you are getting the error with the Quarkus distribution and not with the deprecated WildFly distribution?

**Comment by strainovic** [comment] 2022-10-04 11:19
Everything works fine after I did a rollback to 16.x version.

**Comment by rblome** [comment] 2022-10-12 16:55
I found a workaround, see below.

Since version 17, the default Keycloak distro is based on Quarkus. Quarkus is not just a Java Framework, it is also an HTTP server. In other words, Quarkus implements the HTTP part of Keycloak instances (if I understand correctly). By default, this HTTP server is configured to limit the first line of HTTP requests to a maximum of 4096 characters (or bytes, IDC).

### Expected behavior

Below URI shows the Keycloak start page.

### Actual behavior

Below URI results in:

>  HTTP ERROR 414

(414 means "URI too long")

### How to Reproduce?

A simple test of this limitation is to locally run a Keycloak 18 (that is just what I used) and navigate to this 5000-character URL:

`bin/kc.sh start-dev`

> http://localhost:8080/?foo=01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
> 

### Workaround

The default can be changed, among other ways by an environment variable.
Doc for this: [HTTP Reference - Quarkus](https://quarkus.io/guides/http-reference#quarkus-vertx-http-config-group-server-limits-config_quarkus.http.limits.max-initial-line-length)

When I start Keycloak like this it works fine:

`QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH=8192 bin/kc.sh start-dev`

For the above 5000-character URI, my browser then shows the Keycloak start page.

**Comment by mannp** [comment] 2023-01-17 21:19
Oddly I have just started getting this issue too, just with 20.0.3.

Workaround works, thx.

**Comment by lmm-git** [comment] 2023-02-21 21:02
I stumbled upon this issue when setting up a Mattermost SAML client with Keycloak 20.0.3 as with signing and encryption the SAML request inital HTTP line gets longer than 4096 chars. So this issue has real world impact I would argue.

It took me some time to get behind this issue especially as there is no logging or specific error message (even with debugging enabled).

**Comment by rmartinc** [comment] 2023-03-08 15:42
Hi!

Yes, this is a limitation of the quarkus server, by default the max is 4096, I suppose you can reach it if using SAML redirect binding with long data. You can use the env variable of the `quarkus.properties` file to set these quarkus specific options.

In general it is a relatively easy fix but it depends on discussions around the configuration. For instance, if we want to map those Quarkus options on our side as a keycloak property. Moving this to backlog and adding the cloud team too. We will get back to this later.

Thanks!

**Comment by stianst** [comment] 2023-03-10 08:43
@pedroigor @vmuzikar seems like something we should consider for Keycloak 22? I would suggest we just increase the default rather than require folks to have to configure it themselves.

**Closed** 2023-04-05 18:21 UTC
Labels: kind/bug, priority/important, area/dist/quarkus, team/cloud-native

**Comment by gitdode** [comment] 2023-04-24 16:33
I'm having a similar issue when logging off a user with a huge id token (id_token_hint) from a webapp using the Javascript client adapter, with Keycloak 20.0.5 and client adapter 18.0.0 (we currently can't upgrade because our Angular release is not recent enough).

The suggested solution increasing QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH alone does not help, I have to disable HTTP2 as well. Otherwise I get "just nothing" in Firefox (no response), ERR_CONNECTION_CLOSED in Chromium and "Stream error in the HTTP/2 framing layer" in Insomnia.

Is this another issue or do I have to disable HTTP2 additionally because the older Javascript client adapter?

**Comment by pedroigor** [comment] 2023-04-24 19:57
@gitdode I haven't seem issues related to HTTP2. Perhaps the problems you are facing are specific to Insomnia? Did you try with other proxy?

**Comment by gitdode** [comment] 2023-04-25 06:57
@pedroigor I get this when running on localhost, there is no proxy involved (I meant Insomnia the REST client). But the behaviour is the same with nginx and Traefik; logout doesn't work unless I disable HTTP2 additionally to increasing the max initial line length limit.

**Comment by pedroigor** [comment] 2023-04-25 11:38
I see. I would suggest opening a new issue with more details (e.g.: network capture) about the problem and the steps to reproduce it.

**Comment by gitdode** [comment] 2023-05-02 11:09
I upgraded to 21.1.0 and re-tested; the issue is solved there, and no need to additionally disable HTTP2 - very nice!
