### ISSUE TITLE
User attributes are not removable or renamable from the Admin console UI

### ISSUE THREAD

**Issue by vidi42** [keycloak/keycloak#19231] opened 2023-03-22 10:21 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Removing an attribute of a user from the Admin console doesn't really delete the attribute after saving, as the attribute reappears again.
Also, when renaming an attribute, a new one is created and the old attribute is still present.

### Version

21.0.1

### Expected behavior

The attribute is deleted when removing it and saving.
The attribute is updated when renaming it.

### Actual behavior

The attribute is not deleted when removing it and saving.
The attribute is not updated when renaming, but rather a new one is created and the old one is kept.

### How to Reproduce?

1. Create a user which has a custom attribute, e.g. `test`
2. After saving the user and the attributes, go to the `attributes` tab of the user
3. Remove the `test` attribute and save
4. The attribute appears again after the save
** the payload of the `PUT /auth/admin/realms/:realm/users/:userId` still contains the `test` attribute

**Comment by twwd** [comment] 2023-03-22 15:25
Is a duplicate of #17454 and fixed on `main`/`nightly`.

**Closed** 2023-03-22 16:19 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
