### ISSUE TITLE
Database migrations are not transactional

### ISSUE THREAD

**Issue by uubk** [keycloak/keycloak#16642] opened 2023-01-26 12:30 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Hey there!

It appears that migrations in Keycloak are not done in a transactional manner - that is, if you launch two or more Keycloaks on an empty database, there is a good chance that one of them will crash because it will try to upgrade the database schema while the first instance is still initializing. This came as a surprise to me - while schema modifications are not transactional in quite a few databases, the usual schema migration tools guard against this by using a "lock table" (e.g. DATABASECHANGELOGLOCK for Liquibase), so I assume this is unintentional.

### Version

20.0.3

### Expected behavior

Keycloak should start - one instance should be doing the schema upgrade, the other instance should block trying to acquire a lock while that is in progress.

### Actual behavior

One instance crashes, an example looks like this:
```
keycloak_1  | 2023-01-26 12:23:16,508 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: localhost, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
keycloak_1  | 2023-01-26 12:23:17,387 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
keycloak_2  | 2023-01-26 12:23:16,690 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: localhost, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
keycloak_2  | 2023-01-26 12:23:17,664 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
keycloak_1  | 2023-01-26 12:23:17,964 INFO  [org.infinispan.server.core.transport.EPollAvailable] (keycloak-cache-init) ISPN005028: Native Epoll transport not available, using NIO instead: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
keycloak_1  | 2023-01-26 12:23:18,097 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
keycloak_1  | 2023-01-26 12:23:18,106 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
keycloak_1  | 2023-01-26 12:23:18,139 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
keycloak_db | 2023-01-26 12:23:18.182 UTC [70] ERROR:  relation "migration_model" does not exist at character 25
keycloak_db | 2023-01-26 12:23:18.182 UTC [70] STATEMENT:  SELECT ID, VERSION FROM MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
keycloak_2  | 2023-01-26 12:23:18,370 INFO  [org.infinispan.server.core.transport.EPollAvailable] (keycloak-cache-init) ISPN005028: Native Epoll transport not available, using NIO instead: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
keycloak_1  | 2023-01-26 12:23:18,394 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
keycloak_db | 2023-01-26 12:23:18.429 UTC [71] ERROR:  relation "migration_model" does not exist at character 25
keycloak_db | 2023-01-26 12:23:18.429 UTC [71] STATEMENT:  SELECT ID, VERSION FROM MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
keycloak_2  | 2023-01-26 12:23:18,490 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
keycloak_2  | 2023-01-26 12:23:18,503 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
keycloak_1  | 2023-01-26 12:23:18,504 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
keycloak_1  | 2023-01-26 12:23:18,505 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
keycloak_2  | 2023-01-26 12:23:18,567 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
keycloak_1  | 2023-01-26 12:23:18,626 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak_1  | 2023-01-26 12:23:18,627 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
keycloak_1  | 2023-01-26 12:23:18,627 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak_1  | 2023-01-26 12:23:18,627 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
keycloak_2  | 2023-01-26 12:23:18,827 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
keycloak_db | 2023-01-26 12:23:18.935 UTC [70] ERROR:  relation "public.databasechangelog" does not exist at character 22
keycloak_db | 2023-01-26 12:23:18.935 UTC [70] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
keycloak_2  | 2023-01-26 12:23:18,950 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
keycloak_2  | 2023-01-26 12:23:18,950 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
keycloak_2  | 2023-01-26 12:23:19,043 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak_2  | 2023-01-26 12:23:19,044 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
keycloak_2  | 2023-01-26 12:23:19,044 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak_2  | 2023-01-26 12:23:19,044 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
keycloak_db | 2023-01-26 12:23:19.265 UTC [71] ERROR:  relation "public.databasechangelog" does not exist at character 22
keycloak_db | 2023-01-26 12:23:19.265 UTC [71] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
keycloak_db | 2023-01-26 12:23:19.393 UTC [72] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
keycloak_db | 2023-01-26 12:23:19.393 UTC [72] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock
keycloak_db | 2023-01-26 12:23:19.427 UTC [70] ERROR:  relation "public.databasechangelog" does not exist at character 22
keycloak_db | 2023-01-26 12:23:19.427 UTC [70] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
keycloak_1  | 2023-01-26 12:23:19,428 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
keycloak_2  | 2023-01-26 12:23:20,408 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
keycloak_1  | 2023-01-26 12:23:20,647 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [469e1cb02a91-10786|0] (1) [469e1cb02a91-10786]
keycloak_1  | 2023-01-26 12:23:20,649 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `469e1cb02a91-10786`, physical addresses are `[172.30.0.2:48041]`
keycloak_1  | 2023-01-26 12:23:20,910 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 469e1cb02a91-10786, Site name: null
keycloak_1  | 2023-01-26 12:23:20,975 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
keycloak_1  | 2023-01-26 12:23:20,985 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
keycloak_1  | 2023-01-26 12:23:21,188 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) ISPN000094: Received new cluster view for channel ISPN: [469e1cb02a91-10786|1] (2) [469e1cb02a91-10786, 5b8b54816628-62738]
keycloak_1  | 2023-01-26 12:23:21,193 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) ISPN100000: Node 5b8b54816628-62738 joined the cluster
keycloak_2  | 2023-01-26 12:23:21,208 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [469e1cb02a91-10786|1] (2) [469e1cb02a91-10786, 5b8b54816628-62738]
keycloak_2  | 2023-01-26 12:23:21,219 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `5b8b54816628-62738`, physical addresses are `[172.30.0.3:54159]`

... infinispan details ...

keycloak_1  | 2023-01-26 12:23:21,844 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t7) [Context=actionTokens] ISPN100010: Finished rebalance with members [469e1cb02a91-10786, 5b8b54816628-62738], topology id 5
keycloak_2  | 2023-01-26 12:23:21,916 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 5b8b54816628-62738, Site name: null
keycloak_1  | 2023-01-26 12:23:22,375 INFO  [io.quarkus] (main) Keycloak 20.0.3 on JVM (powered by Quarkus 2.13.6.Final) started in 6.783s. Listening on: https://0.0.0.0:8443
keycloak_1  | 2023-01-26 12:23:22,376 INFO  [io.quarkus] (main) Profile prod activated. 
keycloak_1  | 2023-01-26 12:23:22,376 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
keycloak_db | 2023-01-26 12:23:22.548 UTC [71] ERROR:  duplicate key value violates unique constraint "uk_cli_scope"
keycloak_db | 2023-01-26 12:23:22.548 UTC [71] DETAIL:  Key (realm_id, name)=(09499d2d-dc87-49d8-a5c8-6c1e44c831c1, role_list) already exists.
keycloak_db | 2023-01-26 12:23:22.548 UTC [71] STATEMENT:  insert into CLIENT_SCOPE (DESCRIPTION, NAME, PROTOCOL, REALM_ID, ID) values ($1, $2, $3, $4, $5)
keycloak_2  | 2023-01-26 12:23:22,549 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 23505
keycloak_2  | 2023-01-26 12:23:22,549 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) ERROR: duplicate key value violates unique constraint "uk_cli_scope"
keycloak_2  |   Detail: Key (realm_id, name)=(09499d2d-dc87-49d8-a5c8-6c1e44c831c1, role_list) already exists.
keycloak_2  | 2023-01-26 12:23:22,551 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (main) HHH000010: On release of batch it still contained JDBC statements
keycloak_2  | 2023-01-26 12:23:22,553 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
keycloak_1  | 2023-01-26 12:23:22,596 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=authenticationSessions] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,598 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=sessions] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,602 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=clientSessions] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,604 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=work] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,607 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=org.infinispan.CLIENT_SERVER_TX_TABLE] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,609 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=loginFailures] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,611 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=offlineClientSessions] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,614 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=org.infinispan.CONFIG] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,616 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=org.infinispan.COUNTER] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,618 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=offlineSessions] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_1  | 2023-01-26 12:23:22,620 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) [Context=actionTokens] ISPN100008: Updating cache members list [469e1cb02a91-10786], topology id 6
keycloak_2  | 2023-01-26 12:23:22,621 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
keycloak_1  | 2023-01-26 12:23:22,625 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) ISPN000094: Received new cluster view for channel ISPN: [469e1cb02a91-10786|2] (1) [469e1cb02a91-10786]
keycloak_1  | 2023-01-26 12:23:22,625 INFO  [org.infinispan.CLUSTER] (jgroups-8,469e1cb02a91-10786) ISPN100001: Node 5b8b54816628-62738 left the cluster
keycloak_2  | 2023-01-26 12:23:22,653 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak_2  | 2023-01-26 12:23:22,653 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
keycloak_2  | 2023-01-26 12:23:22,653 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.hibernate.exception.ConstraintViolationException: could not execute statement
keycloak_2  | 2023-01-26 12:23:22,654 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: could not execute statement
keycloak_2  | 2023-01-26 12:23:22,654 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: duplicate key value violates unique constraint "uk_cli_scope"
keycloak_2  |   Detail: Key (realm_id, name)=(09499d2d-dc87-49d8-a5c8-6c1e44c831c1, role_list) already exists.
keycloak_2  | 2023-01-26 12:23:22,654 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
keycloak_2 exited with code 1
```
Specifically, note that
```
keycloak_1  | 2023-01-26 12:23:19,428 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
keycloak_2  | 2023-01-26 12:23:20,408 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
```
which for me looks like the code in `QuarkusJpaUpdaterProvider` is actually not guarded against running concurrently in different instances.

### How to Reproduce?

The easiest way to reproduce this is using docker-compose:
```
mkdir conf
keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
```
Create a file named `docker-compose.yaml` with the following contents:
```
version: '3'

services:
  database:
    container_name: keycloak_db
    image: "postgres:14"
    command: [ "postgres"]
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    volumes:
      - ./conf:/opt/keycloak/conf
    command:
      - start
      - --hostname=localhost
      - --db=postgres
      - --db-url=jdbc:postgresql://keycloak_db/keycloak
      - --db-username=postgres
      - --db-password=postgres
```
Then run `docker-compose up --scale keycloak=2`.

**Comment by ahus1** [comment] 2023-01-26 18:45
Thanks for reporting this. 

Could you please provide the log from the Keycloak instance which succeeded to start? This would allow me to figure out if the problem is during the schema initialization or during the setup of the initial realm which happens afterwards. 

Thanks again!

**Comment by ahus1** [comment] 2023-01-26 18:46
Sorry, I now see that this is a combined log. I'll have a look at the combined log.

**Comment by ahus1** [comment] 2023-01-27 10:24
Triage result: I can reproduce this. This is probably a regression for https://issues.redhat.com/browse/KEYCLOAK-18073 which fixed it for the Wildfly distribution, but missed a code duplication for Quarkus. 

When running the Quarkus distribution, there is no lock being created when initializing the master realm, so the initialization of the master realm starts concurrently on multiple nodes. This leads to duplicate key exceptions, and one of the nodes looses. 

As this is transactional, the node that succeeds will still have created a master realm that is valid. Upon the second start of the instances when the realm already exists, the start will succeed. 

I'll look into preparing a fix for this.

**Closed** 2023-01-30 11:59 UTC
Labels: kind/bug, area/storage

**Comment by mvah** [comment] 2024-08-06 20:44
> Triage result: I can reproduce this. This is probably a regression for https://issues.redhat.com/browse/KEYCLOAK-18073 which fixed it for the Wildfly distribution, but missed a code duplication for Quarkus.
> 
> When running the Quarkus distribution, there is no lock being created when initializing the master realm, so the initialization of the master realm starts concurrently on multiple nodes. This leads to duplicate key exceptions, and one of the nodes looses.
> 
> As this is transactional, the node that succeeds will still have created a master realm that is valid. Upon the second start of the instances when the realm already exists, the start will succeed.
> 
> UPDATE: This is not about Liquibase locking and the DB schema, but about filling the schema with valid contents.
> 
> I'll look into preparing a fix for this.


**Thank you very much. I got a similar issue in kubernetes with two postgres replicas. I just deleted one replica and run keycloak again. Now, it works for me.**

**Comment by ahus1** [comment] 2024-08-07 06:11
> I got a similar issue in kubernetes with two postgres replicas.

@mvah This issue has been closed for quite a while, and the cause of the symptoms seem to be different. Please create a new issue to describe your setup and what kind of PostgreSQL replication you are using. Most likely this is something we don't support yet, so it might be flagged as an enhancement. 

Once you've created the issue, please post the issue number here.
