### ISSUE TITLE
Invalid OIDC request when changing language in login flow

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#16185] opened 2022-12-27 16:27 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

When an error occurs during the login flow (e.g. wrong credentials have been given), Keycloak offers to change the locale/language like this:

![image](https://user-images.githubusercontent.com/12183470/209693513-b690877b-7f8b-4b87-aba7-7c3112375450.png)

When a user switches the locale, Keycloak redirects back to the client that initiated the login. The redirect looks like an invalid OIDC request for the client.

Keycloak logs show the following error and warnings:

```
2022-12-27 16:15:30,512 ERROR [org.keycloak.services] (executor-thread-60) KC-SERVICES0092: Missing parameter: response_type
2022-12-27 16:15:30,513 WARN  [org.keycloak.events] (executor-thread-60) type=LOGIN_ERROR, realmId=9f2f9c75-5261-4eec-9443-878a34b21f6b, clientId=account-console, userId=null, ipAddress=192.168.48.1, error=invalid_request
2022-12-27 16:21:51,934 WARN  [org.keycloak.services] (executor-thread-69) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
        at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1025)
        at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:879)
        at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:151)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:338)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:194)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-12-27 16:21:51,946 WARN  [org.keycloak.events] (executor-thread-69) type=LOGIN_ERROR, realmId=9f2f9c75-5261-4eec-9443-878a34b21f6b, clientId=account-console, userId=null, ipAddress=192.168.48.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=http://localhost:8080/realms/test/account/#/, code_id=839651c9-8181-4b51-9b29-91d0aea38e98, response_mode=fragment, authSessionParentId=839651c9-8181-4b51-9b29-91d0aea38e98, authSessionTabId=7CboVkMb0Ng
```

### Version

20.0.1

### Expected behavior

Keycloak should simply show the same error page as before switching the locale, but show the error message translated tho the choosen language/locale (German in this case).

### Actual behavior

Keycloak throws an internal error that the parameter `response_type` is missing and redirects back to the client. The client does not know how to handle the redirect/request.

### How to Reproduce?

* Create a new Keycloak realm named `test`
* In `Realm setting` -> `Localization` enable `Internationalization`
  * Add `English` and `German` as supported locales
  * Set `English` as default locale
  * Save the settings
* Under `Authentication` create a new login flow with just two alternative steps
  * `Cookie` authenticator
  * `X509/Validate Username Form` authenticator
* Assign the newly creted login flow as a browser flow to the account console client
*  Open the account console (e.g. at http://localhost:8080/realms/test/account/) 
* Click `Sign in` button
* You should see an (expected) error like this: 
![image](https://user-images.githubusercontent.com/12183470/209692624-07b2cbb5-9c07-4e18-a817-6e11be409c76.png)
  * current URL is something like http://localhost:8080/realms/test/protocol/openid-connect/auth?client_id=account-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Frealms%2Ftest%2Faccount%2F%23%2F&state=5056315e-53b1-48d0-81fd-8bf05a9821f3&response_mode=fragment&response_type=code&scope=openid&nonce=005590a9-13ad-4162-8158-a2c0ecc55c64&code_challenge=Pweu5vvTkKG61k3C6TG1CSIk7q25wyL9VmpLPnCOBwQ&code_challenge_method=S256
* Change the locale from `English` to `Deutsch`
  * This sends a HTTP GET request to http://localhost:8080/realms/test/protocol/openid-connect/auth?client_id=account-console&tab_id=U3qmN3zpOrI&kc_locale=de (note the locale hint)
  * The GET request results in a 302 Redirect to the client (the account console in this case): http://localhost:8080/realms/test/account?error=invalid_request&error_description=Missing+parameter%3A+response_type (note the error description)
  *

**Comment by mposolda** [comment] 2023-02-23 09:24
@sventorben I think this is duplicate of #13922, but not 100% sure. User is not set in the context and authenticationSession is not present when the error page of `X509/validate username` authenticator is shown and that causes this one.

So I am closing this. Please reply to that issue for the further discussions/questions/suggestions. Please re-open this one if you think that this one is different and not the duplicate of #139222

**Closed by mposolda** 2023-02-23 09:24 UTC
Labels: area/oidc, kind/bug, status/triage
