### ISSUE TITLE
User search filter loses focus after entering first character when having user federation enabled

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#29522] opened 2024-05-14 14:12 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When having user federation enabled and trying to search users in the admin console, the focus on the field is lost after entering only one character. But if you click again on the search field and start typing then it works as expected.

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

User search can be executed by entering multiple characters at once, without losing the focus

### Actual behavior

 The focus on the search field is lost after entering only one character. User needs to click again on the field to do the actual search

### How to Reproduce?

Enable custom user federation and in the users section try searching for some user.

**Comment by ssilvert** [comment] 2024-05-14 18:11
This is already fixed in the nightly build.

Also, this is a duplicate of https://github.com/keycloak/keycloak/issues/29488 and https://github.com/keycloak/keycloak/issues/29153

**Closed by ssilvert** 2024-05-14 18:11 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
