### ISSUE TITLE
keycloak-js: iframe for checkLoginIframe functionality gets blocked if a cusotm csp is set for a realm

### ISSUE THREAD

**Issue by Juern-Univention** [keycloak/keycloak#14203] opened 2022-09-05 17:54 UTC
### Describe the bug

keycloak-js uses a hidden iframe to check the login status. The iframe uses the `3p-cookies/step1.html` and `3p-cookies/step2.html` endpoints. To be able to load these in an iframe the `frame-ancestors` content security policy is removed.

The problem is that the `frame-ancestors` content security policy is not removed if the csp for the realm was changed in any way. Since the csp `frame-ancestors` is no not removed, the frame gets blocked by the browser and the checkLoginIframe functionality does not work anymore.

### Version

18

### Expected behavior

The `frame-ancestors` content security policy is always removed for the `3p-cookies/step1.html` and `3p-cookies/step2.html` endpoints. Even if the default content security policy for a realm was changed.

### Actual behavior

The `frame-ancestors` content security policy is removed for the `3p-cookies/step1.html` and `3p-cookies/step2.html` endpoints only if the default content security policy for a realm has not been changed.

### How to Reproduce?

You can reproduce this on the keycloak admin web interface:

Login in and check the `Content-Security-Policy` header for `realms/master/protocol/openid-connect/3p-cookies/step2.html`. `frame-ancestors` should not be set.

Under `Realm Settings` (for the Master realm) -> `Security Defenses` -> `Headers` set `Content-Security-Policy` to `frame-src 'self'; frame-ancestors 'self' https://example.com; object-src 'none';`

Now check the `Content-Security-Policy` header for `realms/master/protocol/openid-connect/3p-cookies/step2.html` again. `frame-ancestors` should be set.

Warning: Do not remove `'self'` from frame-ancestors or you will not be able to login again!

You should also be able to reproduce this using the javascript example in the [documentation](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter). After changing the csp you should be able to see the blocked iframe.

### Anything else?

Workaround:
As a workaround I can disable the iframe in the javascript lib: `checkLoginIframe: false`. I think we could also change the `Content-Security-Policy` header through our reverse proxy without changing the default values in keycloak.

Possible other effected endpoints:
I think `allowAnyFrameAncestor` is the method to search for, for other possibly effected endpoints. The front channel logout might be effected as well. But I didn't tested that.

Other ideas:
It might also be nice to be able to change the `frame-ancestors` for each client individual.

Do you have any other ideas or did I miss something I should change in the settings?

Thanks :)

**Comment by stianst** [comment] 2022-09-16 11:46
When using custom headers we are not able to make changes depending on what endpoint is being called. Why are you using a custom CSP header in the first place?

**Comment by Juern-Univention** [comment] 2022-09-19 16:42
We are using keycloak within a portal. The basic idea is that the outside page is branded with your organization and you can open your web applications in an iframe.

We didn't want to lose the state of the portal, when an application triggers a login. So we changed the CSP to be able to open the login page in the iframe the application is running in.

**Comment by stianst** [comment] 2022-10-06 04:16
Closing this as it's not a bug

**Closed by stianst** 2022-10-06 04:16 UTC
Labels: kind/bug, area/adapter/javascript, status/triage
