### ISSUE TITLE
Searching for users that have a specified role name doesn*t include roles inherited by groups

### ISSUE THREAD

**Issue by steff333** [keycloak/keycloak#19391] opened 2023-03-28 15:25 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

When using GET /{realm}/roles/{role-name}/users you can only find users that have a specific realm role assigned but you will not find users that inherite the role by its group membership.

### Version

21.0.1

### Expected behavior

When search for users with a specific role it is expected to find all users that either have this role or inherited the role.

If the actual behavior should not be broken, either add another endpoint or add a query parameter to search roles recursive

### Actual behavior

Only users are found that have the specific role assigned directly but not if the role is inherited by group membership

### How to Reproduce?

add a group "everyone" has realm role ONE
add user A and assign role TWA an make it a member of "everyone"

If you search for users with role TWO you will find user a but if you search for role ONE the user is not included.
Looking at the composite role of user a with 
 /{realm}/users/{id}/role-mappings/realm/composite
shows role ONE and role TWO

**Comment by DAHAG-ArisNourbakhsh** [comment] 2023-03-30 14:52
Maybe #8991 or https://stackoverflow.com/questions/38371943/keycloak-get-all-users-mapped-to-roles/71434660#71434660 can help you but IMO I wouldn't bet on this being properly included anytime soon.

Related Issues:
#16949 
#10011

**Comment by mposolda** [comment] 2023-05-19 09:24
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by blairmorris** [comment] 2023-11-14 23:01
+1 

One of our apps has a form field dropdown with a list of all users that have specific client role, it fetches the list via the `GET /{realm}/clients/{id}/roles/{role-name}/users` endpoint (which is used by the kc-admin-client js package's `client.findUsersWithRole` method [here](https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-admin-client/src/resources/roles.ts#L60)) and it doesn't include roles inherited from composite roles or groups, only direct assignments. So when our support team started creating composite roles (bc we're mapping roles to SAML attributes, and we wanted to avoid having them create dozens of AD groups for every single role) they noticed users not showing in that list that did have the role needed.

From what I can tell by the Admin API Docs, there's not really any way to fetch a list of users with a specific client role if it's inherited from a composite role or a group aside from fetching a list of every single user, then calling `GET /admin/realms/{realm}/users/{id}/role-mappings/clients/{client}/composite` on each one (potentially hundreds of calls, so not very feasible) A fix for this would prevent a really nasty workaround, otherwise composite roles and groups exhibit unexpected behavior just for this one endpoint, sadly.

**Comment by pedroigor** [comment] 2024-03-07 20:21
Looks like related to https://github.com/keycloak/keycloak/issues/19391. I'm closing because of that. Feel free to re-open if you disagree.

**Closed by pedroigor** 2024-03-07 20:21 UTC
Labels: kind/bug, area/admin/api, help wanted, team/core-iam

**Comment by schonbachler** [comment] 2024-03-07 20:36
@pedroigor 
You accidentally linked to the same issue. Which is the related one?

**Comment by blairmorris** [comment] 2024-04-17 21:11
I believe [this](https://github.com/keycloak/keycloak/issues/16949) is the related ticket, and it got closed as well

**Comment by kirides** [comment] 2024-12-03 20:04
This is still an issue with keycloak 26.

There is no way to find users that have a role inherited.

This is pretty bad. When we update our composites, we need to update ALL users that have the composite, to also contain ALL composite inherited roles.

This increases the load on the keycloak instance and is fragile.

There are a bunch of Stackoverflow posts suggesting how to grab all information using a bunch of direct SQL using Common Table Expressions (CTEs) to recurse all depth.

We can't afford a customers system to directly query the keycloak instance, neither to create a keycloak-proxy/second service that provides this solution.

**Comment by finwast** [comment] 2024-12-05 10:23
Also same problem here - can we somehow vote for the issue?

**Comment by DAHAG-ArisNourbakhsh** [comment] 2024-12-05 10:46
As both Issues have been closed and only the original author could re-open it (besides the maintainers), the best option would be to create a new issue and upvote that

**Comment by steff333** [comment] 2024-12-05 12:23
Being the original author, it seems not possible to reopen the issue after it was closed. 
From our side we are still interested on this issue to be solved.

**Comment by aharasta** [comment] 2024-12-11 21:06
The inherited realm roles do show up in the access tokens. This seems to imply that the logic already exists in the code base and we just need to add it to the API. 

This issue is a problem for our use case as well in which the customer uses Active Directory for user federation and a group mapper to assign roles. The application needs to list users based on those inherited roles.
