### ISSUE TITLE
Upgrade to latest Quarkus 2.13.z

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14817] opened 2022-10-10 08:55 UTC

**Comment by abstractj** [comment] 2022-10-13 12:13
Duplicate of https://github.com/keycloak/keycloak/pull/14834

**Comment by stianst** [comment] 2022-10-17 10:00
Closing since it's a duplicate

**Closed by stianst** 2022-10-17 10:00 UTC
Labels: area/dist/quarkus, status/rejected

**Comment by abstractj** [comment] 2022-10-25 12:32
Duplicates #15032
