### ISSUE TITLE
NPE when trying to enable fine grained permissions on group

### ISSUE THREAD

**Issue by PeterPopma** [keycloak/keycloak#15547] opened 2022-11-17 12:27 UTC
### Area

admin/fine-grained-permissions

### Describe the bug

Turn on preview features, create a group in admin console and go to Permissions tab.
When I click the to enable fine grained permissions, I get the following trace in keycloak server:

2022-11-17 13:19:27,291 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-16) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.authorization.model.Resource.getId()" because the return value of "org.keycloak.services.resources.admin.permissions.GroupPermissionManagement.resource(org.keycloak.models.GroupModel)" is null
        at org.keycloak.services.resources.admin.GroupResource.toMgmtRef(GroupResource.java:299)
        at org.keycloak.services.resources.admin.GroupResource.setManagementPermissionsEnabled(GroupResource.java:321)
        at jdk.internal.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)

### Version

20.0.1

### Expected behavior

permissions enabled switch should be set to "enabled"

### Actual behavior

permissions enabled switch stays "enabled"

### How to Reproduce?

Turn on preview features, create a group in admin console and go to Permissions tab.
When I click the to enable fine grained permissions, I get the following trace in keycloak server:

**Comment by lexcao** [comment] 2022-11-17 15:42
Duplicated to https://github.com/keycloak/keycloak-ui/issues/3741
And it was fixed, waiting for the next release.

**Comment by sschu** [comment] 2023-01-19 15:21
As @lexcao said, it will be in the next release which is Keycloak 21.

**Comment by mposolda** [comment] 2023-04-04 09:53
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by ssilvert** [comment] 2023-04-04 18:25
> As @lexcao said, it will be in the next release which is Keycloak 21.

Correct.  If you want to try it out now, you can give the nightly build a look:
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment] 2023-04-04 18:26
And since it is fixed, I'm closing this as a duplicate.

**Closed by ssilvert** 2023-04-04 18:26 UTC
Labels: kind/bug, area/admin/fine-grained-permissions, status/triage
