### ISSUE TITLE
clientSecret not properly encoded with keycloak-admin-client

### ISSUE THREAD

**Issue by de-dan** [keycloak/keycloak#20167] opened 2023-05-04 17:57 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/node

### Describe the bug

After updating from version 21.0.2 to 21.1.1 I can't authenticate anymore.
In my nestjs application I'm using the latest keycloak-admin-client with client-secret as described in the README:
```
const credentials = {
  grantType: 'client_credentials',
  clientId: 'clientId',
  clientSecret: 'some-client-secret-uuid', // of course, I use my real values :D
};
await kcAdminClient.auth(credentials);
```

But I get an error in node_modules/@keycloak/keycloak-admin-client/lib/utils/auth.js
InvalidCharacterError: Invalid character

I have seen that with version 21.1 the library was transferred to this repository and somehow the auth.js file was changed to not use axios anymore. (https://github.com/keycloak/keycloak-nodejs-admin-client/blob/f0b93984b8d216fc722415209e6c2a501fbc1a7d/src/utils/auth.ts#L81)

In [line 82 of auth.js](https://github.com/keycloak/keycloak/blob/c17fcd49c84e835d0c7aea45704327a3e8fb4239/js/libs/keycloak-admin-client/src/utils/auth.ts#L82) I see this falsy code: `atob(credentials.clientId + ":" + credentials.clientSecret)`
If you try pasting this line directly in e.g. chrome developer tools console you see that this will throw an error. I'm not sure how this is supposed to work, but I think `atob` should be replaced by `btoa`.

### Version

21.1.1

### Expected behavior

Authentication with client-secret should work as described in the README.

### Actual behavior

Authentication with client-secret is crashing with error in auth.js

### How to Reproduce?

Use code example in README:

```
const credentials = {
  grantType: 'client_credentials',
  clientId: 'clientId',
  clientSecret: 'some-client-secret-uuid', // of course, I use my real values :D
};
await kcAdminClient.auth(credentials);
```

This should break because of the wrong values and not because of the atob-parsing.

**Comment by jonkoops** [comment] 2023-05-05 09:28
Duplicate of #19879

**Closed by jonkoops** 2023-05-05 09:28 UTC
Labels: kind/bug, status/triage
