### ISSUE TITLE
Сannot read properties of null (reading 'postmessage')

### ISSUE THREAD

**Issue by gaer87** [keycloak/keycloak#28240] opened 2024-03-27 10:26 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

Hello!
The error "Сannot read properties of null (reading 'postmessage')" throws sometimes in code
```js
if (loginIframe.callbackList.length == 1) {
  loginIframe.iframe.contentWindow.postMessage(msg, origin);
}
```
I guess `loginIframe.iframe.contentWindow` equals `null`.
Can I fix it?

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The error throws

### Actual behavior

The error does not throw

### How to Reproduce?

I have seen one in Sentry monitoring platform.

**Comment by jonkoops** [comment] 2024-03-28 16:02
I am closing this, as it is for an older and unmaintained version of Keycloak, if this is still reproducible in the latest Keycloak then feel free to submit another report. Please also give actual steps to reproduce the issue, as otherwise it will be closed.

**Closed by jonkoops** 2024-03-28 16:02 UTC
Labels: kind/bug, area/adapter/javascript, team/ui, status/auto-expire, status/missing-information

**Comment by sleidig** [comment] 2024-07-29 12:38
I am also seeing this error from time to time in our system using
    "keycloak-angular": "^15.3.0",
    "keycloak-js": "^25.0.2",

Unfortunately I cannot pinpoint the cause. I suspect this happens on slow connections (or possibly on slightly older devices like Android 10 + Chrome Mobile 119, ...).
