### ISSUE TITLE
Impossible to map any attribute from IdentityProviders, context is null

### ISSUE THREAD

**Issue by galzetta** [keycloak/keycloak#8961] opened 2021-11-30 09:35 UTC
### Describe the bug

I'm configuring an application with AzureAD as IdentityProvider.

Authentication works fine, however I'd like to retrieve some claims such as:

* given_name
* family_name
* samAccountName

As such I defined some Attribute importer mappers for the IdentityProvider. However they do not seem to work properly.

From the DEBUG logs I see that keycloak is unable to retrieve these because the whole `context` is `null`:

```
09:21:07,408 DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-11) Going to process JsonNode path family_name on data null
09:21:07,409 DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-11) Going to process JsonNode path given_name on data null
09:21:07,410 DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-11) Going to process JsonNode path profile.given_name on data null
09:21:07,410 DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-11) Going to process JsonNode path samAccountName on data null
```

The team that handles AzureAD has confirmed to me that the claims have been included in the AzureAD authentication. (I don't know if there is a way to make Keycloak log the raw data coming from the IdP for deeper debugging...)

### Version

12.0.4

### Expected behavior

I'd expect that once the user logs it I can see the claims mapped to the values i configured (firstName, lastName etc).

### Actual behavior

The attributes are not imported.

The logs corresponding to line: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractJsonUserAttributeMapper.java#L206
seem to show that the `context` passed to the `getJsonValue` method is `null`, while it should contain the claims provided by the IdentityProvider.

### How to Reproduce?

* Configure Keycloak with AzureAD
* configure AzureAD to include given_name as claim in the ID token
* Add an Attribute Importer mapper in the AzureAD identity provider that maps the claim given_name to firstName
* Try to login using the AzureAD IdentityBroker. In the update profile page the First name is not filled.

### Anything else?

I believe this issue has been discussed here: https://github.com/keycloak/keycloak/discussions/8462

**Comment by rm3l** [comment] 2021-12-07 08:59
> The team that handles AzureAD has confirmed to me that the claims have been included in the AzureAD authentication. (I don't know if there is a way to make Keycloak log the raw data coming from the IdP for deeper debugging...)

@galzetta FYI, this section in the documentation allows to retrieve and inspect the actual external IDP token as seen by Keycloak: https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens 
It was very helpful while debugging #9004

**Comment by longtimeago** [comment] 2022-05-22 17:13
@rm3l could you, please, advice me how to figure out from which keycloak version the API https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens is available?

**Comment by rmartinc** [comment] 2023-02-17 09:28
Hi @galzetta Are you using the OIDC Ideintity provider? Are the claims inside the access token (not the ID token?

I'm asking because probably this is a duplicate of #9004 if the answer of both questions are yes. As explained in the other issue the access token by OIDC spec is an opaque token and it cannot be a JWT token.

**Comment by rmartinc** [comment] 2023-05-22 09:21
Closing as duplicate of https://github.com/keycloak/keycloak/issues/9004. Follow the other issue if you are interested.

**Closed by rmartinc** 2023-05-22 09:21 UTC
Labels: area/oidc, kind/bug
