### ISSUE TITLE
UI - Search function not working when trying to Assign Role under Role Mapping 

### ISSUE THREAD

**Issue by nssecrier** [keycloak/keycloak#19868] opened 2023-04-21 10:13 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When trying to assign a role as part of the role mapping user configuration the search function or page navigation are not working as expected. Further details are included below.

### Version

21.0.1

### Expected behavior

I was expecting to be able to add the required role to the user either by browsing to the right roles page or finding it via the search function.

### Actual behavior

I was able to increase the number of rows up to 100 and select one of the roles that were listed on the first page but when I try to change the page it always remained on the first page. Also, when trying to use the search functionality, the results flashed briefly as a pop-up but could not see or select the desired results so any role that is post the first 100 entries is not available for selection.

The same functionality works fine when creating a composite role. I was able to create the role and then add client roles using both the page changing or the search function.

### How to Reproduce?

Details are included in the actual behaviour section.

**Comment by nssecrier** [comment] 2023-04-24 12:52
Hello, a quick update on this issue. It looks like the issue was fixed on v21.1.0 (https://github.com/keycloak/keycloak/issues/17403) but this was not back-ported across all places.
I can find the same issue now in the Groups when trying to assign permissions to a group. Exactly the same behaviour is there and that needs to be addressed.

**Comment by lrozenblyum** [comment] 2023-04-26 12:02
Hello @nssecrier, I set up Keycloak 21.1.0 and also have this bug...

**Comment by jonkoops** [comment] 2023-04-26 12:23
@lrozenblyum we just released 21.1.1. Does that have the same issue?

**Comment by lrozenblyum** [comment] 2023-04-27 11:52
@jonkoops most likely I was mistaken. It's not the same but different - user group level is affected (see https://github.com/keycloak/keycloak/issues/19981)

**Comment by ssilvert** [comment] 2023-04-30 21:21
Closing this as a duplicate of #19981

**Closed by ssilvert** 2023-04-30 21:21 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by jonkoops** [comment] 2023-05-01 21:15
Duplicate of #19981
