### ISSUE TITLE
Manage account

### ISSUE THREAD

**Issue by ilyabakhlin** [keycloak/keycloak#9343] opened 2021-12-26 14:37 UTC
### Describe the bug

After a fresh installation, I access the Master realm with my administrator account. When I click on the user's name at the top right corner and select the "Manage account" option, the application redirects me to a new view with a spinning circle and hangs.

After that, the application doesn't respond to any HTTP requests besides the main page.

### Version

16.1.0

### Expected behavior

Load the requested view.

### Actual behavior

The application hangs and doesn't respond.

### How to Reproduce?

Perform a fresh installation, access the administrator user's account, and click on the "Manage console" option.

**Comment by ilyabakhlin** [comment] 2022-01-13 07:04
I'm getting the following error: 

![image](https://user-images.githubusercontent.com/28750512/149281770-e1c444bd-b458-4a6b-8c66-ea966ae29c6e.png)

**Comment by ssilvert** [comment] 2022-01-13 14:37
The request to https://keycloak.dev.phoenixconnection.es is forbidden.  Is that the server you are trying to authenticate with?

If you are setting up a simple fresh installation, you would normally just use localhost without https.

This is not a bug, so I am going to close the issue.  If you need more help, please ask a question in our forums.

**Closed by ssilvert** 2022-01-13 14:37 UTC
Labels: kind/bug, area/account/ui
