### ISSUE TITLE
Failed to start keycloak in production (start) mode.

### ISSUE THREAD

**Issue by Krishna-PriyaV** [keycloak/keycloak#29306] opened 2024-05-06 10:48 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When I try to start keycloak Ver 24.0.2 in production mode. I get below errors. But It is working fine in start-dev mode.

Iam using EC2,Mysql DB and Docker file.

**Docker File:**

FROM public.ecr.aws/docker/library/maven:3.8.4-openjdk-17-slim as maven-builder

COPY native-s3-pom.xml ./
RUN mvn package -f native-s3-pom.xml
FROM quay.io/keycloak/keycloak:24.0.2 as keycloak-builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

ENV KC_FEATURES=preview,token-exchange,admin-fine-grained-authz
ENV KC_CACHE_STACK=ec2
ENV PROXY_ADDRESS_FORWARDING=true
ENV KC_PROXY=edge
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=true

COPY APM/*.jar /opt/keycloak/providers/
COPY --from=maven-builder --chown=keycloak target/s3-native-ping-bundle-*-jar-with-dependencies.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:24.0.2
COPY --from=keycloak-builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=keycloak-builder /opt/keycloak/providers/* /opt/keycloak/providers/
COPY themes/bqa /opt/keycloak/themes/bqa
COPY keycloak.conf /opt/keycloak/conf/

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh show-config

ENV KC_DB=mysql
ENV KC_DB_URL=<db url>
ENV KC_DB_USERNAME=******
ENV KC_DB_PASSWORD=******
ENV KC_HOSTNAME=keycloak-qa.com

ENTRYPOINT ["/opt/keycloak/bin/kc.sh" ,"start", "--http-relative-path=/auth" ]

EXPOSE 22 8080 8443 9990 9993 7800

**Error Logs:**

May 06, 2024 at 14:59 (UTC+5:30)	2024-05-06 09:29:49,354 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode	
May 06, 2024 at 14:59 (UTC+5:30)	2024-05-06 09:29:49,355 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection	
May 06, 2024 at 14:59 (UTC+5:30)	2024-05-06 09:29:49,355 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Acquisition timeout while waiting for new connection	
May 06, 2024 at 14:59 (UTC+5:30)	2024-05-06 09:29:49,355 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.	
May 06, 2024 at 14:59 (UTC+5:30)	2024-05-06 09:29:49,303 ERROR [io.quarkus.runtime.StartupContext] (main) Running a shutdown task failed: java.lang.RuntimeException: Failed to start caches	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.getOrCreate(CacheManagerFactory.java:89)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.KeycloakRecorder$1.run(KeycloakRecorder.java:114)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.runtime.StartupContext.close(StartupContext.java:73)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.runtime.Application.start(Application.java:101)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:117)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:33)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine.access$1500(CommandLine.java:148)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)	
May 06, 2024 at 14:59 (UTC+5:30)	at picocli.CommandLine.execute(CommandLine.java:2170)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:125)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.reflect.Method.invoke(Method.java:568)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)	
May 06, 2024 at 14:59 (UTC+5:30)	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)	
May 06, 2024 at 14:59 (UTC+5:30)	Caused by: java.util.concurrent.ExecutionException: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@6c2f9d1f, status=FAILED} failed to start	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.getOrCreate(CacheManagerFactory.java:87)	
May 06, 2024 at 14:59 (UTC+5:30)	... 25 more	
May 06, 2024 at 14:59 (UTC+5:30)	Caused by: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@6c2f9d1f, status=FAILED} failed to start	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:782)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:120)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.Thread.run(Thread.java:840)	
May 06, 2024 at 14:59 (UTC+5:30)	Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@6c2f9d1f, status=FAILED} failed to start	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:584)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.GlobalComponentRegistry.preStart(GlobalComponentRegistry.java:284)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)	
May 06, 2024 at 14:59 (UTC+5:30)	... 7 more	
May 06, 2024 at 14:59 (UTC+5:30)	Caused by: java.lang.BootstrapMethodError: bootstrap method initialization exception	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:481)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:63)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:49)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)	
May 06, 2024 at 14:59 (UTC+5:30)	... 15 more	
May 06, 2024 at 14:59 (UTC+5:30)	Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class org.jgroups.protocols.relay.RELAY2; not a subtype of implementation type class org.jgroups.protocols.relay.RELAY	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:273)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:340)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)	
May 06, 2024 at 14:59 (UTC+5:30)	... 24 more	
May 06, 2024 at 14:59 (UTC+5:30)	2024-05-06 09:29:49,204 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000080: Disconnecting JGroups channel `ISPN`	
May 06, 2024 at 14:59 (UTC+5:30)	2024-05-06 09:29:49,203 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@6c2f9d1f, status=FAILED} failed to start	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:584)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.GlobalComponentRegistry.preStart(GlobalComponentRegistry.java:284)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:120)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.Thread.run(Thread.java:840)	
May 06, 2024 at 14:59 (UTC+5:30)	Caused by: java.lang.BootstrapMethodError: bootstrap method initialization exception	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)	
May 06, 2024 at 14:59 (UTC+5:30)	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:481)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:63)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:49)	
May 06, 2024 at 14:59 (UTC+5:30)	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak 24.0.2 should be start in Prod (Start) mode.

### Actual behavior

Keycloak 24.0.2 failed in production (start) mode.

### How to Reproduce?

Please try with my docker file.

### Anything else?

It is working fine in start-dev mode.

**Comment by sschu** [comment] 2024-05-06 12:25
Your database type set by KC_DB must be set before your run the kc.sh build. Otherwise running with --optimized will use the default db type (in contrast to start-dev) which does an automatic rebuild.

**Comment by sschu** [comment] 2024-05-06 13:10
I think the issue is you are only copying /lib/quarkus. The structure of your multi-layer build is not ideal. You should put everything together in the intermediate layer into the /opt/keycloak folder, than run kc.sh build and then copy the whole /opt/keycloak folder over in the final layer without adding anything else.

**Comment by Krishna-PriyaV** [comment] 2024-05-14 09:38
Hi @sschu Issue was related to Jgroups dependency. We excluded the JGroups dependency which is pulled by org.jgroups.aws:jgroups-aws and our setup now works again with the Keycloak version 24.0.2.

Currently we facing another issue. Application sometime showing "**Failed to find ADMIN theme keycloak-extended, using built-in themes**".

Can anyone please help me to resolve this.? Thank you!

**Comment by jonkoops** [comment] 2024-05-14 10:50
> Currently we facing another issue. Application sometime showing "**Failed to find ADMIN theme keycloak-extended, using built-in themes**".

Sounds like you are trying to include a custom theme that isn't copied into your Keycloak installation. I'd recommend reading the [theme deployment guide](https://www.keycloak.org/docs/latest/server_development/#deploying-themes) and adjust your config accordingly. If you continue to have issues please open a new thread on the forum.

I am closing this issue as the primary problem has been resolved, and further problems are likely a configuration issue, and not an actual bug in Keycloak itself.

**Closed by jonkoops** 2024-05-14 10:50 UTC
Labels: kind/bug, status/triage, area/login/ui, team/core-clients
