### ISSUE TITLE
Problem with displaying realm name, which contains "-" character in email messages

### ISSUE THREAD

**Issue by MarcelSz** [keycloak/keycloak#22777] opened 2023-08-29 06:27 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I've found recently a problem with a realm with a name containing "-" character. Realm name is skipped in email messages. KeyCloak is allowing user to create a realm with "-" character.

### Version

22.0.1

### Expected behavior

The email should contain realm name.

### Actual behavior

Realm name which contains "-" is not visible in the email sent by KeyCloak. 

### How to Reproduce?

- Create a realm with "-", e.g. "dev-test",
- Trigger action to send an email, for which the message contains _realmName_, e.g. password reset / executeActions,
- Check email

### Anything else?

I spot that in the KeyCloak 22.0.1 it is not possible to create a tenant that includes whitespace or any other special character, but "_", "-" works fine. Can you confirm that it's OK?

**Comment by MarcelSz** [comment] 2023-08-30 09:54
I set display name property in realm's settings and it works as it should. 
![obraz](https://github.com/keycloak/keycloak/assets/5735552/9fe22b0b-9360-4217-b87a-ec7a7ae1e479)

However it should be also working correctly for the realm name so the bug is still relevant.

**Comment by rmartinc** [comment] 2023-09-21 10:03
I cannot reproduce, I have even tested with exact 22.0.1 version and current upstream. In both cases I receive an email like the following:

```
Your administrator has just requested that you update your Dev-test account by performing the following action(s): Update Password.
```

The realm id is capitalized but it's received as expected. Probably there is something missing here.

**Comment by rmartinc** [comment] 2023-10-05 13:10
I'm closing this issue as we cannot reproduce it. Please re-open it or file a new one if there is something missing in the reproducing steps.

**Closed by rmartinc** 2023-10-05 13:10 UTC
Labels: kind/bug, area/core, status/triage, team/core
