### ISSUE TITLE
Keycloak 22.0.1/22.0.3: unable to see javascript policy

### ISSUE THREAD

**Issue by amitngm** [keycloak/keycloak#23392] opened 2023-09-20 13:42 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/fine-grained-permissions

### Describe the bug

Hi All, 

I am unable to see javascript policy under policy type. 

Regards, 
Amit

### Version

22.0.3

### Expected behavior

It should display under policy type window. 

### Actual behavior

Javascript policy type is not displaying under policy type window.

### How to Reproduce?

1. Login Keycloak. 
2. Enable authorization. 
3. Create a client and navigate to Authorization tab. 
4. Click on Create Policy. 
5. Policy Type window opens.

**Comment by rmartinc** [comment] 2023-09-20 16:55
@amitngm The upload-script feature was removed long ago (version 18, see [release notes](https://www.keycloak.org/docs/latest/release_notes/index.html#the-deprecated-upload-script-feature-was-removed)).  Now you need to create your javascript policies (in this case) outside keycloak, pack them in a jar file and deploy the file to the server via the providers folder. Once deployed the defined javascript policies will appear in the server to be selected. Check the [documentation](https://www.keycloak.org/docs/22.0.3/server_development/#_script_providers) for more information.

**Comment by amitngm** [comment] 2023-09-21 00:56
Ok Thanks, I have 3 questions now. 

1. Can we get a sample project to create js policy? 

2. I have deployed keycloak on k8s and how to upload created jar here. 

3. I need to compare user attribute with resource attribute. How can I acheive it?

**Comment by rmartinc** [comment] 2023-09-21 07:51
Note that github issues in the project are to report code bugs and not to ask general questions. For that better use the https://groups.google.com/g/keycloak-user group. I'm not an expert on authorization and I just made the first comment because I knew that the javascript uploading was removed long ago. Trying to ask anyway:

1. Just follow the [doc](https://www.keycloak.org/docs/22.0.3/server_development/#_script_providers). You need a jar file with the policy scripts and a `META-INF/keycloak-scripts.json` where the policies are listed pointing to the individual files. Then just pack them all into a jar. Finally copy it to the providers folder. Example:

```
jar tvf javascript-policies.jar 
     0 Wed Sep 20 18:53:00 CEST 2023 META-INF/
    61 Wed Sep 20 18:53:00 CEST 2023 META-INF/MANIFEST.MF
   156 Wed Sep 20 18:49:50 CEST 2023 keycloak-role.js
   205 Wed Sep 20 18:49:30 CEST 2023 localhost-policy.js
   370 Wed Sep 20 18:52:44 CEST 2023 META-INF/keycloak-scripts.json

cat META-INF/keycloak-scripts.json 
{
    "policies": [
        {
            "name": "localhost javascript policy",
            "fileName": "localhost-policy.js",
            "description": "Allow from localhost"
        },
        {
            "name": "keycloak_user javascript policy",
            "fileName": "keycloak-role.js",
            "description": "Allow keycloak_user role"
        }
    ]
}
```

2. Not an expert on kubernetes but I suppose you can create a configmap with the jar and populate it to the container. You can also modify the image itself as in our [doc](https://www.keycloak.org/server/containers).

3. There are several examples in the [documentation](https://www.keycloak.org/docs/latest/authorization_services/index.html#_policy_js) you can start playing with. Sorry but I have just done very few and simple policies and always for demo purposes.

@amitngm I'm closing the issue as not a bug.

**Closed by rmartinc** 2023-09-21 07:51 UTC
Labels: kind/bug, area/admin/fine-grained-permissions, team/core
