### ISSUE TITLE
Update to Keycloak 24.0.5 fails on Migration jpa-changelog-24.0.0.xml

### ISSUE THREAD

**Issue by nidavellir9** [keycloak/keycloak#34463] opened 2024-10-29 18:59 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

When I'm trying to update mi Keycloak version from v23.0.7 to v24.0.5 fails, this is the log I get

```
2024-10-29 11:55:13 2024-10-29 14:55:13,164 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-10-29 11:55:13 2024-10-29 14:55:13,164 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2024-10-29 11:55:13 2024-10-29 14:55:13,165 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-24.0.0.xml::24.0.0-9758::keycloak:
2024-10-29 11:55:13      Reason: liquibase.exception.DatabaseException: (conn=1164) Incorrect information in file: './keycloakusers/user_attribute.frm' [Failed SQL: (1033) CREATE INDEX USER_ATTR_LONG_VALUES_LOWER_CASE ON keycloakusers.USER_ATTRIBUTE(LONG_VALUE_HASH_LOWER_CASE, NAME)]
2024-10-29 11:55:13 2024-10-29 14:55:13,165 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-24.0.0.xml::24.0.0-9758::keycloak:
2024-10-29 11:55:13      Reason: liquibase.exception.DatabaseException: (conn=1164) Incorrect information in file: './keycloakusers/user_attribute.frm' [Failed SQL: (1033) CREATE INDEX USER_ATTR_LONG_VALUES_LOWER_CASE ON keycloakusers.USER_ATTRIBUTE(LONG_VALUE_HASH_LOWER_CASE, NAME)]
2024-10-29 11:55:13 2024-10-29 14:55:13,165 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-24.0.0.xml::24.0.0-9758::keycloak:
2024-10-29 11:55:13      Reason: liquibase.exception.DatabaseException: (conn=1164) Incorrect information in file: './keycloakusers/user_attribute.frm' [Failed SQL: (1033) CREATE INDEX USER_ATTR_LONG_VALUES_LOWER_CASE ON keycloakusers.USER_ATTRIBUTE(LONG_VALUE_HASH_LOWER_CASE, NAME)]
2024-10-29 11:55:13 2024-10-29 14:55:13,166 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: (conn=1164) Incorrect information in file: './keycloakusers/user_attribute.frm' [Failed SQL: (1033) CREATE INDEX USER_ATTR_LONG_VALUES_LOWER_CASE ON keycloakusers.USER_ATTRIBUTE(LONG_VALUE_HASH_LOWER_CASE, NAME)]
2024-10-29 11:55:13 2024-10-29 14:55:13,166 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: (conn=1164) Incorrect information in file: './keycloakusers/user_attribute.frm'
2024-10-29 11:55:13 2024-10-29 14:55:13,166 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

24.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

Update from older Keycloak to newer should work

### Actual behavior

When I start the Keycloak container, during first start of Keycloak 24.0.5, failed to update database

### How to Reproduce?

Attempt to update from Keycloak 23.0.7 to 24.0.5

### Anything else?

It seems to fail when try to create this index
`CREATE INDEX USER_ATTR_LONG_VALUES_LOWER_CASE ON keycloakusers.USER_ATTRIBUTE(LONG_VALUE_HASH_LOWER_CASE, NAME)`
but if I run this command manually in the database, the index was generated correctly. I'm using MariaDB.
I've already tried re run the migration, delete the table (USER_ATTRIBUTE) and re generate it, empty the table before run the migration and restore a backup from another environment, all with the same result.

**Comment by sguilhen** [comment] 2024-11-13 16:57
Tried the exact same migration with MariaDB several times and I was not able to reproduce the index creation issue. After doing some online research, the message `(conn=1164) Incorrect information in file: './keycloakusers/user_attribute.frm'` seems to indicate an issue with in the DB (possibly the table structure is corrupt) and not with the actual migration.

I am closing this for now - the targe migration is an outdated version and we haven't had any other reports of this migration failing with MariaDB.

**Closed by sguilhen** 2024-11-13 16:57 UTC
Labels: kind/bug, area/storage, status/triage, team/core-iam, team/core-shared
