### ISSUE TITLE
User table always shows empty search message, when user federation is configured

### ISSUE THREAD

**Issue by simse07** [keycloak/keycloak#24529] opened 2023-11-03 13:47 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In previous versions, the message `This realm may have a federated provider. Viewing all users may cause the system to slow down, but it can be done by searching for "*". Please search for a user above.` was shown in the user overview, If a realm has an user federation configured.

Now, the empty search message is always displayed `No search results`.

With #19574  the property `isSearching` is set on the KeycloakDataTable in UserDataTable line 324, causing the search message to be displayed.

### Version

22.0.5

### Expected behavior

If an user federation is configured, the correct message is displayed in the user overview table.

### Actual behavior

If an user federation is configured, the empty search result message is displayed.

### How to Reproduce?

1. configure an user federation
2. open users page

**Comment by ssilvert** [comment] 2023-11-03 16:00
I have verified this bug.

**Comment by antikalk** [comment] 2023-11-07 14:01
Duplicate of #24430 ?

**Comment by simse07** [comment] 2023-11-07 15:27
@antikalk you are right, I probably missed that one :/

**Closed** 2023-11-14 17:02 UTC
Labels: kind/bug, impact/medium, area/admin/ui, team/ui
