### ISSUE TITLE
UserModel removeAttribute​() not usable from ScriptBasedAuthenticator

### ISSUE THREAD

**Issue by dbaumgarten** [keycloak/keycloak#26934] opened 2024-02-09 15:01 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When implementing a ScriptBasedAuthenticator methods for modifying a User's attributes are missing.

The documentation (https://www.keycloak.org/docs/23.0.6/server_development/#authenticator) says user is a UserModel-Object.
And the UserModel should have a method removeAttribute(String) ( https://www.keycloak.org/docs-api/21.0.1/javadocs/org/keycloak/models/UserModel.html )

However, when doing user.removeAttribute() in the JavaScript of a ScriptBasedAuthenticator it fails and I get an error that no such method exists.

Is this a bug? A missing feature? Or intentional?

What other optoins do I have to set/delete user-attributes from within an Authentication-Script?

### Version

18 (RH-SSO)

### Expected behavior

All methods from the documentation should be available.

### Actual behavior

Some Methods seem to be missing without any explaination.

### How to Reproduce?

Create a ScriptBasedAuthenticator that uses ```user.removeAttribute("foo")```, add it to an Authentication-Flow and see it fail

**Comment by mposolda** [comment] 2024-02-12 10:09
I am closing as there are lots of fixes and changes since Keycloak 18 (RH-SSO). Please try to check with latest Keycloak release 23.0.6 (or even more ideally with Keycloak nightly) and re-open just in case that it is reproducible also with that version.

**Closed by mposolda** 2024-02-12 10:09 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients
