### ISSUE TITLE
internal server error on entering wrong password but valid username

### ISSUE THREAD

**Issue by iamsalman20** [keycloak/keycloak#35308] opened 2024-11-26 09:30 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I am using latest docker image of Keycloak v26.0.6. The keycloak is bind with Active Directory via LDAP. On login page, if I enter a valid username but wrong password, I get error page "An internal server error has occurred". The logs of keycloak container give the following stack:

`2024-11-26 09:20:12,742 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-8) Uncaught server error: java.util.ConcurrentModificationException

	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:977)

	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:899)

	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:144)

	at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:396)

	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:361)

	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:400)

	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:273)

	at org.keycloak.events.EventBuilder.send(EventBuilder.java:242)

	at org.keycloak.events.EventBuilder.error(EventBuilder.java:229)

	at org.keycloak.authentication.AuthenticationProcessor.handleBrowserException(AuthenticationProcessor.java:860)

	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:386)

	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:349)

	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:341)

	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:407)

	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)

	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)

	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)

	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)

	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)

	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)

	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)

	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)

	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)

	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

	at java.base/java.lang.Thread.run(Thread.java:1583)`

### Version

26.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

I should get "invalid username or password" on the login fields

### Actual behavior

I am routed to the error page "We are sorry...An internal server error has occurred"

### How to Reproduce?

Using the said KC version, try to access your app =>You will be redirected to the Login page of Keycloak
On login screen, enter a valid username but wrong password

### Anything else?

I upgraded from v20.0.3. On the older version it works in expected way. So the bug is introduced with the upgrade basically

**Comment by rmartinc** [comment] 2024-11-26 11:40
@iamsalman20 Obviously we cannot reproduce in plain KC 26.0.6 with your reproducer steps. We do a lot of tests with wrong passwords and ldap. You have something more in your env that is triggering the issue and it's not in the reproducer steps.

Can you please test in a fresh installation of 26.0.6 configuring your AD in the same way (and if reproduced please also send your AD configuration, those are part of the reproducer steps)?

Do you have something custom or different from default in the event configuration in the realm (Realm Settings -> Events)? (The exception is when the error is sent, it seems that some other thread is also modifying the transaction list when closing it to send the event, which cannot be, because the session is new to send the error event.)

**Closed** 2024-11-26 12:36 UTC
Labels: kind/bug, area/login/ui, team/core-clients, status/auto-expire, status/missing-information
