### ISSUE TITLE
jakarta.ws.rs.client.ClientBuilder does not work

### ISSUE THREAD

**Issue by johgoe** [keycloak/keycloak#21623] opened 2023-07-12 06:50 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

We have a extension, which sends keycloak events to a event broker via https. After the switch to 22.0.0 and jakartaee, it won't work anymore.

It seems that jakarta.ws.rs.client.ClientBuilder tries to call javax/ws/rs/client/ClientBuilder which could not be loaded

```
{

    "timestamp":"2023-07-12T04:01:02.602Z",
    "sequence":9231,
    "loggerClassName":"org.keycloak.services.ServicesLogger_$logger",
    "loggerName":"org.keycloak.services",
    "level":"ERROR",
    "message":"KC-SERVICES0085: Failed to send event to event broker",
    "threadName":"executor-thread-11",
    "threadId":1593,
    "mdc":{
    },
    "ndc":"",
    "hostName":"keycloak-0",
    "processName":"QuarkusEntryPoint",
    "processId":1,
    "exception":{
        "refId":1,
        "exceptionType":"java.lang.NoClassDefFoundError",
        "message":"javax/ws/rs/client/ClientBuilder",
        "frames":[
            {
                "class":"java.lang.ClassLoader",
                "method":"defineClass1"
            },
            {
                "class":"java.lang.ClassLoader",
                "method":"defineClass",
                "line":1012
            },
            {
                "class":"io.quarkus.bootstrap.runner.RunnerClassLoader",
                "method":"loadClass",
                "line":105
            },
            {
                "class":"io.quarkus.bootstrap.runner.RunnerClassLoader",
                "method":"loadClass",
                "line":65
            },
            {
                "class":"java.lang.ClassLoader",
                "method":"defineClass1"
            },
            {
                "class":"java.lang.ClassLoader",
                "method":"defineClass",
                "line":1012
            },
            {
                "class":"io.quarkus.bootstrap.runner.RunnerClassLoader",
                "method":"loadClass",
                "line":105
            },
            {
                "class":"io.quarkus.bootstrap.runner.RunnerClassLoader",
                "method":"loadClass",
                "line":65
            },
            {
                "class":"java.lang.Class",
                "method":"forName0"
            },
            {
                "class":"java.lang.Class",
                "method":"forName",
                "line":467
            },
            {
                "class":"java.util.ServiceLoader$LazyClassPathLookupIterator",
                "method":"nextProviderClass",
                "line":1217
            },
            {
                "class":"java.util.ServiceLoader$LazyClassPathLookupIterator",
                "method":"hasNextService",
                "line":1228
            },
            {
                "class":"java.util.ServiceLoader$LazyClassPathLookupIterator",
                "method":"hasNext",
                "line":1273
            },
            {
                "class":"java.util.ServiceLoader$2",
                "method":"hasNext",
                "line":1309
            },
            {
                "class":"java.util.ServiceLoader$3",
                "method":"hasNext",
                "line":1393
            },
            {
                "class":"jakarta.ws.rs.client.FactoryFinder",
                "method":"lambda$findFirstService$1",
                "line":178
            },
            {
                "class":"jakarta.ws.rs.client.FactoryFinder",
                "method":"findFirstService",
                "line":187
            },
            {
                "class":"jakarta.ws.rs.client.FactoryFinder",
                "method":"find",
                "line":114
            },
            {
                "class":"jakarta.ws.rs.client.ClientBuilder",
                "method":"newBuilder",
                "line":62
            },
            {
                "class":"jakarta.ws.rs.client.ClientBuilder",
                "method":"newClient",
                "line":86
            }
            ...
    }
}    

```

### Version

22.0.0

### Expected behavior

final var client = ClientBuilder.newClient(); does not throw an exception if used in a extension

### Actual behavior

java.lang.NoClassDefFoundError is thrown

### How to Reproduce?

```
    public boolean emit() {
        String event = "{ "eventPayload":"somePayload" }";
        final var client = ClientBuilder.newClient();
        final var target = client.target("http://your_mock_url_here");
        final var response = target
            .path("publish")
            .request()
            .header(HttpHeader.TENANT_ID, "1234")
            .buildPost(Entity.entity(event, "MediaType.APPLICATION_JSON"))
            .invoke();
        log.infof("Sending event %s return status (%s,%s) ", event, response.getStatus(), response.getStatusInfo());
        client.close();
        return 200 <= response.getStatus() && response.getStatus() < 300;
    }
```

**Comment by rmartinc** [comment] 2023-07-12 10:08
duplicate of #21596

@johgoe The resteasy-client jars are not part of the quearkus distribution. You have tomanually add them to the `providers` path. In my case a very simple provider works with the following files:

```
cd ~/keycloak-22.0.0/providers/
ls
hello-rest-example.jar  README.md  resteasy-client-6.2.4.Final.jar  resteasy-client-api-6.2.4.Final.jar
```

I added `resteasy-client-6.2.4.Final.jar` and `resteasy-client-api-6.2.4.Final.jar` in the providers path too (and my provider sample).

I'm closing this as I thin is the same than #21596.

**Closed by rmartinc** 2023-07-12 10:08 UTC
Labels: kind/bug, area/core, status/triage, team/core

**Comment by johgoe** [comment] 2023-07-12 17:34
@rmartinc Thank you for your quick reply. I already added resteasy-client to my own dependencies, but I forgot that the switch from javax to jarkartaee requires the upgrade from resteasy-client-4.x to resteasy-client-6.x.

It's working now like expected.
