### ISSUE TITLE
Keycloak.js not found 404, when accessing Admin Console due to missing "/" in URL

### ISSUE THREAD

**Issue by HW-Owl** [keycloak/keycloak#12042] opened 2022-05-17 09:32 UTC
### Describe the bug

When accessing the admin console `/auth/admin/master/console/` you get a blank page and a 404 error getting the `keycloak.js` script.

### Version

18

### Expected behavior

The URL for the script tag loading `keycloak.js` should look like `/auth/js/keycloak.js?version=<version>`.

### Actual behavior

But URL looks like `/authjs/keycloak.js?version=<version>` with a missing "/".

### How to Reproduce?

Access admin console.

### Anything else?

It seems to miss a "/" [here](https://github.com/keycloak/keycloak/blob/7c64f28934200cda613bd46625195681673ac256/services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java#L342).

**Comment by MerlijnElderhuis** [comment] 2022-05-17 10:00
I also encountered this. Solved it by adding a `/` to my `KEYCLOAK_FRONTEND_URL` env var

**Comment by ssilvert** [comment] 2022-06-02 19:11
I'm going to consider this one solved.  Closing.

**Closed** 2022-06-02 19:11 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by arctan90** [comment] 2022-06-16 07:33
This is caused by code introduced on 2022.4.6 in File AdminConsole.java, line 342
```
            map.put("keycloakJsUrl", adminBaseUri.getPath() + "js/keycloak.js?version=" + Version.RESOURCES_VERSION);
```
it should be  "/js/keycloak.js?version=" , missing "/" ahead
