### ISSUE TITLE
admin-client dont enable user

### ISSUE THREAD

**Issue by Kirbylix** [keycloak/keycloak#17103] opened 2023-02-15 07:07 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

The following sends the new /existing user to Keycloak.
Here you can also activate the user.

```
UserResource userResource = usersRessource.get(user.getId());
UserRepresentation kcUser = userResource.toRepresentation();
kcUser.setEnabled(Boolean.TRUE);
userResource.update(kcUser);

```

but it still remains deactivated and you cannot log in. You must then activate the user manually in Keycloak.

### Version

20.0.3

### Expected behavior

after creating/updating the user should be active in Keycloak.

### Actual behavior

the user is deactivated in Keycloak and cannot log in.

### How to Reproduce?

create or edit a user with this code

```
UserResource userResource = usersRessource.get(user.getId());
UserRepresentation kcUser = userResource.toRepresentation();
kcUser.setEnabled(Boolean.TRUE);
userResource.update(kcUser);

```

**Comment by pedroigor** [comment] 2023-12-18 23:22
@Kirbylix I'm closing this one because we have enough coverage to make sure you can enable/disable users through the Admin API. The test suite is doing that very often in most of our tests.

If you can reproduce this issue in our test suite, feel free to re-open the issue.

**Closed by pedroigor** 2023-12-18 23:22 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core
