### ISSUE TITLE
New Admin UI does not send e-mails if account-client is disabled

### ISSUE THREAD

**Issue by foliengriller** [keycloak/keycloak#17857] opened 2023-01-18 10:38 UTC
### Describe the bug

The new admin UI does not send User-Mails if account client is disabled. Instead an error is shown "Client not enabled". In the browser console I can see a 400 bad-request error.

### Version

20.0.3

### Environment

Chrome, Windows

### Expected behavior

E-Mail is send

### Actual behavior

UI shows Error "Client is not enabled" and Mail not send.

### How to Reproduce?

1. Disable client "account"
2. Try to send a Mail via "Reset Actions" (e.g. in User -> Credentials -> Credential Reset -> "Update Password")
3. See Error "Client is not enabled" and Mail not send

### Anything else?

Workaround: Switch back to old Admin UI. Anything works as expected or enable account-client.

**Comment by kapiljaveri** [comment] 2023-03-23 17:02
Hi @edewit , we're actually seeing the same issue. We're on v20.02 and are trying to invoke the executeActions endpoint via the API but we get a `400 Bad Request: Client is not enabled` error.

**Comment by kapiljaveri** [comment] 2023-03-23 17:22
Also tried  to send a Mail via "Reset Actions" (e.g. in User -> Credentials -> Credential Reset -> "Update Password") as suggested above and ran into the same issue.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/6692991/227286165-7bacc187-ffd1-4c4e-93f4-a88fdbf353ac.png">

**Comment by edewit** [comment] 2023-03-24 09:49
@kapiljaveri why not enable the client? That seems to solve the issue

**Comment by foliengriller** [comment] 2023-03-24 12:49
I can explain why we can not enable the account client. We have one realm for all of our customers. Some of them use their own IDP, so we have ~50 IDP-Federations. The account-console now shows a nice list of all this customers under "linked accounts". Of course, we can remove the link and even adapt the template, but there is currently no role that prevents access to the linked accounts. Or do I miss something?
It would be nice, if Keycloak could provide a role for each of the pages of the account-client, so that fine grained access-management is possible.

**Comment by rmartinc** [comment] 2023-06-01 11:07
The test email works for me. The problem is in the `Credential Reset` button of the users tab `Credentials`.

@edewit The endpoint `execute-actions-email` can receive a `clientId` parameter  with the client that is doing the request. If it's not sent it defaults to `account`. I see you don't send it, the request is just `http://localhost:8080/admin/realms/master/users/3ffd40b8-a01d-4814-a7a5-053c0c6528a0/execute-actions-email?lifespan=43200`. Why don't the admin console uses its own client id `security-admin-console`? For sure if someone is using the console it's enabled.

I did a quick test adding the client id hardcoded:

```diff
diff --git a/js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx b/js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
index dffe353c33..eeb5ba362c 100644
--- a/js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
+++ b/js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
@@ -56,6 +56,7 @@ export const ResetCredentialDialog = ({
         id: userId,
         actions,
         lifespan,
+        clientId: 'security-admin-console',
       });
       addAlert(t("credentialResetEmailSuccess"), AlertVariant.success);
       onClose();
```

And it works. We can also change the defult, but I think it's better if you send your own `clientId` in the request.

**Comment by edewit** [comment] 2023-06-05 11:51
okay, that's good to know I see that in the code it does default to "account" when no clientId is specified and there is a test to see if the client is enabled, but what I don't get is why is this client nessary to send this email?

**Comment by rmartinc** [comment] 2023-06-05 12:49
@edewit The client is used to generate the token for the action, the `issuedFor` claim in the token ([here](https://github.com/keycloak/keycloak/blob/21.1.1/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L839)). It is also used to validate the redirect URI if passed, but that validation is not needed here as the admin console never sends a redirectUri.

**Comment by mposolda** [comment] 2023-06-27 13:58
@jonkoops @edewit Is this issue fixed with https://github.com/keycloak/keycloak/pull/20961 being merged?

**Comment by jonkoops** [comment] 2023-06-27 15:36
@mposolda that PR just cleans up some code, it does not functionally change anything. #20960 was supposed to be a fix, but @edewit had some questions that we never got an answer to.

**Comment by stianst** [comment] 2024-02-28 10:14
.

**Comment by mposolda** [comment] 2024-02-29 10:12
Adding to Keycloak 25 for now. Will be good to fix, but I don't consider this a blocker (disabling `account` client is a bit of corner case).

**Comment by schuerg** [comment] 2024-03-19 05:55
https://github.com/keycloak/keycloak/issues/20843

**Closed** 2024-07-03 06:43 UTC
Labels: kind/bug, priority/important, area/core, team/core-clients, team/core-shared
