### ISSUE TITLE
Single Sign On Does not work for associated apps when implementing custom theme for login screen

### ISSUE THREAD

**Issue by myselfuser1** [keycloak/keycloak#34100] opened 2024-10-18 13:52 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

I have two apps, I already integrated `keycloak` in both apps for sign in. If I signed in first app and then go to second app, I would be signed in automatically in second app without the need for entering credentials. I needed to change the login screen UI of `keycloak` so I created a custom theme, In that I created `login.ftl` file and it works fine as well but suddenly when I login in first app and open the second app , I am not signed in automatically but I have to enter the credentials again in my second app for sign in, the issue is definitely with my custom theme. When i revert it back to the original theme which keycloak provides everything works fine and i am automatically signed in my second app. Here is my `login.ftl` code 

```
[](<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link href="https://fonts.cdnfonts.com/css/sf-pro-display" rel="stylesheet">               
    <style>   
    @import url('https://fonts.cdnfonts.com/css/sf-pro-display');
    * {
      box-sizing: border-box;
      padding: 0;
      margin: 0;
      font-family: 'SF Pro Display', sans-serif; 
    }
    .container {
        display: flex;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin: auto;
        max-height:100vh;
    }

    .loginSection {
        display: flex;
        flex-direction: column;
        width: 40%;
        height: 100vh;
        padding-left: 2rem;
        padding-right: 2rem;
        padding-bottom: 2rem;
        justify-content: space-between;
    }

    .infoSection {
        width: 60%;
        background-color: #b8cde3;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding-left: 80px;
        padding-top: 96px;
        max-height: 100vh;
        overflow-y: hidden;
        gap:96px
    }

    .loginContent {
        margin: auto;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        min-height: 70%;
    }

    .loginFormContent {
        display: flex;
        flex-direction: column;
        gap: 2rem;
        min-height: 400px;
    }

    .loginFormTitle h1 {
        font-size: 32px;
        font-weight: 600;
        line-height: 40px;
    }

    .loginFormTitle p {
        margin-top: 1rem;
        font-size: 18px;
        font-weight: 400;
        line-height: 22.5px;
        color: #4d4d4d;
    }

    form {
        display: flex;
        flex-direction: column;
        gap: 1.5rem;
    }

    .formGroup {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }

    .formGroup label {
        font-size: 14px;
        font-weight: 600;
        line-height: 21px;
        color: #4d4d4d;
    }

    .formGroup input {
        border: 1px solid #939393;
        height: 44px;
        border-radius: 10px;
        padding-left: 10px;
    }

    .formOptions {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .formOptions label {
        font-size: 14px;
        font-weight: 600;
        line-height: 21px;
        color: #4d4d4d;
    }

    .formOptions a {
        font-size: 14px;
        font-weight: 600;
        line-height: 21px;
        color: #0a84ff;
        text-decoration: none;
    }

    .checkboxContainer {
        display: flex;
        align-items: center;
    }

    .checkboxContainer input {
        margin-right: 10px;
    }

    .loginButton {
        width: 100%;
        padding: 12px;
        background-color: #000;
        color: #fff;
        border: none;
        border-radius: 96px;
        cursor: pointer;
        font-size: 16px;
        font-weight: 500;
    }

    .loginButton:hover {
        background-color: #333;
    }

    .signupText {
        text-align: center;
        margin-top: 20px;
        font-size: 14px;
        font-weight: 300;
        line-height: 21px;
        color: #4d4d4d;
    }

    .signupText a {
        color: #0a84ff;
        text-decoration: none;
        font-size: 14px;
        font-weight: 600;
        line-height: 21px;
    }

    .signupText a:hover {
        text-decoration: underline;
    }

    .footer {
        color: #4d4d4d;
        font-size: 14px;
        font-weight: 400;
        line-height: 20px;
    }

    .infoContent {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding-right:64px;
    }

    .infoContent h2 {
      font-size: 32px;
      font-weight: 400;
      line-height: 40px;
    }

    .quoteAuthor {
        font-weight: bold;
        font-size: 18px;
        line-height: 22.5px;
    }

    .companyInfo {
        margin-top: 0.5rem;
        font-size: 16px;
        font-weight: 500;
        line-height: 24px;
        color: #4d4d4d;
    }

    .imageContainer {
        width: 100%;
        position: relative;
        height: 100%;
    }

    .dashboardImage {
        width: 100%;
        height: 100%;
        object-fit: fill;
        object-position: center;
        border-top-left-radius: 12px;
        border: 6px solid #1A1A1A;
    }

    .errorMessage {
        color: #ff0f17;
        font-size: 14px;
        line-height: 21px;
        margin-bottom: 12px;
    }

    .logo {
        margin-bottom: 32px;
    }

    .ratingContainer {
       margin-top: 24px;
       display: flex;
       justify-content: space-between;
       align-items: center;
       width: 100%;
       padding-right: 20px;
    }


    @media (max-width: 1024px) {
        .loginSection {
            width: 100%;
        }
        .infoSection {
            display: none;
        }
        .loginContent {
            min-height: 60%;
            width: 100%;
        }
    }
  </style>
</head>
<body>
    <div class="container">
        <div class="loginSection">
            <div class="loginContent">
                 <img src="${url.resourcesPath}/img/ccashLogo.svg" width="126.51" height="32" alt="C-Cash Logo" class="logo"  >
                <div class="loginFormContent">
                    <div class="loginFormTitle">
                        <h1>Login</h1>
                        <p>Welcome back. Please enter your details</p>
                    </div>
                    <form action="${url.loginAction}" method="post">
                        
                        <div class="formGroup">
                            <label for="username">Email</label>
                            <input name="username" id="username" type="text" placeholder="Enter your email" required >
                        </div>
                        <div class="formGroup">
                            <label for="password">Password</label>
                            <input type="password" id="password" name="password" placeholder="********" required>
                        </div>
                        <div class="formOptions">
                            <label class="checkboxContainer">
                                <input type="checkbox">
                                <span class="checkmark"></span>
                                Remember for 30 days
                            </label>
                        <#if realm.resetPasswordAllowed><span><a href="${url.loginResetCredentialsUrl}" class="forgotPassword">Forgot Password</a></span></#if>
                        </div>
                        <button type="submit" class="loginButton">Login</button>
                    </form>
                    <p class="signupText">Don't have an account? <a href="#">Sign Up</a></p>
                </div>
            </div>
            <footer class="footer">© C-Cash 2024</footer>
        </div>
        <div class="infoSection">
            <div class="infoContent">
                <h2>Thanks to the automatic data synchronization from C-Cash platform, we are now able to see a complete picture of our cash flow and its values.</h2>
                <div class="ratingContainer">
                    <p class="quoteAuthor">— Chief Financial Officer</p>
                  <img src="${url.resourcesPath}/img/fiveStar.png" alt="FiveStar" width="108" height="20" class="fiveStarRating">
                </div>
                <p class="companyInfo">Leading mechanical engineering company in Viet Nam</p>
            </div>
            <div class="imageContainer">
                <img src="${url.resourcesPath}/img/background.jpg" class="dashboardImage" alt="Login Image">
            </div>
        </div>
    </div>
</body>
</html>)
```

what am i missing

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The second app should not ask for login credentials again after setting custom theme 

### Actual behavior

The second app asks for login credentials again after setting custom theme 

### How to Reproduce?

Change the `login.ftl` code to the above mentioned code and set the theme in keycloak

### Anything else?

I tried asking ChatGPT and it told me to add 
1. `${formFields()}`
```
<input type="hidden" name="session_code" value="${sessionCode}">
    <input type="hidden" name="execution" value="${execution}">
    <input type="hidden" name="tab_id" value="${tabId}">
    <input type="hidden" name="auth_method" value="${authMethod}">

```

which didn't worked for me as well

**Comment by myselfuser1** [comment] 2024-10-18 13:57
I just tried with keycloak 26.0.1 as well but same issue, just update it in the original post

**Comment by ssilvert** [comment] 2024-10-18 18:12
@myselfuser1 I think this is likely a bug in your custom theme and not a bug in Keycloak.

Do you have reason to believe that this is a Keycloak bug?

**Comment by myselfuser1** [comment] 2024-10-19 02:38
@ssilvert Any idea on what could i be doing wrong for my custom theme of `login.ftl`?

**Comment by slemke** [comment] 2024-10-19 13:59
Something you could try based on the `login.ftl` you linked: Your `rememberMe` checkbox seems not correct. Did you try adding the `name` attribute on the checkbox from the original theme? I think it is supposed to be something like `<input type="checkbox" name="rememberMe" />`. If the checkbox is not set correctly you will be logged out for example when closing the browser

**Comment by myselfuser1** [comment] 2024-10-20 02:51
@slemke  Thanks for the reply but the problem is not with remember me checkbox, even for the original theme i don't check the remember me checkbox and when i open the second app i am signed in automatically if i set the original theme

**Closed** 2024-10-21 05:08 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui
