### ISSUE TITLE
Failing test in realm_settings_user_profile_enabled.spec.ts

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#29709] opened 2024-05-20 19:15 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

`Deletes an attributes group` test is failing.  Skipping the test for now so CI will pass.

This issue is here to make sure we fix it asap.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

passing

### Actual behavior

failing

### How to Reproduce?

run tests in CI

**Comment by hmlnarik** [comment] 2024-05-21 07:27
Duplicate of #29507

**Closed by hmlnarik** 2024-05-21 07:27 UTC
Labels: kind/bug, priority/important, area/admin/ui, team/ui
