### ISSUE TITLE
Check for 999.0.0 in MIGRATION_MODEL breaks Keycloak instances without documented workaround

### ISSUE THREAD

**Issue by bo0ts** [keycloak/keycloak#30364] opened 2024-06-12 07:14 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

~~operator~~ core (edited by @mabartos )

### Describe the bug

Feel free to move this to a discussion.

After updating Keycloak to version 25.0.0 one of our Keycloak instances failed to start with the following error message:

```
Incorrect state of migration. You are trying to run server version '25.0.0' against a database which was migrated to snapshot version '999.0.0'. Databases that have been migrated to a snapshot version can't be migrated to a released version of Keycloak or to a more recent snapshot version.
```

That check makes sense and there was an advisory in the Keycloak 24 Update notes regarding the operator accidentally deploying a snapshot. We never hit that issue (knowingly), but we must have mistakenly run a snapshot in an update a few versions ago already:

```
select * from migration_model ;
  id   | version | update_time 
-------+---------+-------------
 33jeh | 21.0.1  |  ...
 84vyx | 21.0.2  |  ...
 uz6gn | 21.1.0  |  ...
 37dtv | 21.1.1  |  ...
 jxdii | 21.1.2  |  ...
 e4cpa | 22.0.0  |  ...
 nmk0o | 22.0.1  |  ...
 r21q6 | 22.0.2  |  ...
 gn2wq | 22.0.3  |  ...
 2mtf8 | 999.0.0 |  ...
```

Needless to say that the database update we took prior to the upgrade wasn't of much help and we didn't notice the problem because Keycloak never complained about this during the last updates and there were no operational problems.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The error message helps the user how to trigger the correct migrations and a note of that "breaking change" is in the release notes.

### Actual behavior

The error message is hard to search and no official guidance on how to get out of this is provided. Especially when the accidental run of the snapshot could already be quite some time in the past.

### How to Reproduce?

* Run a nightly.
* Run Keycloak 25.

**Comment by mabartos** [comment] 2024-06-12 10:21
@bo0ts Thanks for creating this issue. 

As this is an expected behavior, it should be converted to the enhancement issue for documenting the workaround - not a bug. 

@ahus1 @mposolda Could you please check it, as you were involved in the issue https://github.com/keycloak/keycloak/issues/27941? Thanks!

**Comment by stianst** [comment] 2024-06-17 09:26
If you've run a snapshot version of Keycloak against a production database it's not easy to know what you would need to do to recover, as you don't know what may have changed.

I would probably remove the `999.0.0` entry to the table in a copy, and run the latest release against it, then check if things are looking good after that.

Maybe we should also prevent running KC nightly/dev against a DB with existing real releases in it, with potentially an explicit option to allow it for testing purposes.

**Comment by bo0ts** [comment] 2024-06-17 13:49
@stianst Yes, I would very much prefer making it harder to run dev instances against production databases. Especially since users of the Keycloak Operator don't have immediate control over what version/image of Keycloak is being deployed.

**Comment by waynemorphic** [comment] 2024-06-18 17:35
Due to the important persistence preview feature, I just encountered this issue when upgrading to V25 from a nightly build.  

`ERROR: Incorrect state of migration. You are trying to run server version '25.0.0' against a database which was migrated to snapshot version '999.0.0'. Databases that have been migrated to a snapshot version can't be migrated to a released version of Keycloak or to a more recent snapshot version.`

**Solution**
As suggested by @stianst , I have deleted the `999.0.0` row and ran the latest changes and it has worked. Maybe, the docs could capture such or a better solution. However,  I had come across [this discussion](https://github.com/keycloak/keycloak/discussions/28271) that warned;

`You can't upgrade from a nightly build to a release build of Keycloak [...] always start with an empty database or a backup from a regular release.` 

**Note**

This was all in a sandbox. I am not sure about production behavior if this solution is followed.

**Comment by ahus1** [comment] 2024-07-01 09:40
The workaround of removing the `999.0.0` should work in most cases, but won't work in all of them: 

* When upgrading to the latest snapshot, some migrations have already been run. Currently there is no guarantee that those migrations are idempotent, i.e. that they are safe to run multiple times. Replacing `999.0.0` with the version that was released as stable before that snapshot would limit the re-execution, still this information is not known by the Keycloak build. 
* If the migration for a snapshot-release would try to record both the second-last migration and the snapshot migration, this is not supported by the current table format at is will not be able to show the correct information as all entries are sorted by the update time to retrieve the lastest entry, and no two entries must share a timestamp. 

+1 for adding a safety switch to prevent running a snapshot release against a regular release.

Removing `team/cross-dc` here as it is IMHO more of a core team issue. Let me know if you think otherwise.

**Comment by ahus1** [comment] 2024-10-28 14:19
I've just approved the connected PR which will prevent using a snapshot version on a previous released DB version. While this doesn't help in a situation that is described here, it prevents it. So I assume this issue can be closed once the PR is merged. 

@mposolda - Please re-open or comment if you think otherwise.

**Closed** 2024-10-28 15:02 UTC
Labels: kind/bug, priority/important, area/core, team/core-clients
