### ISSUE TITLE
Can't find or load main class 

### ISSUE THREAD

**Issue by Dexaf** [keycloak/keycloak#21059] opened 2023-06-18 22:28 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

i don't know if i picked the correct area but if you use the command **bin/kc.bat start-dev** (at least in windows)
and the folder is in a path which contains white spaces it doesn't work and says that it can't find or load the main class:
![Windows PowerShell 19_06_2023 00_25_42](https://github.com/keycloak/keycloak/assets/31799040/1aa03396-b518-4cdd-9b8d-8d42d5a0dd08)

as you can see as soon as i put an underscore to replace the whitespace it works just fine
![keycloak 19_06_2023 00_26_12](https://github.com/keycloak/keycloak/assets/31799040/001cdac4-b818-4cfd-aff7-7f805dd26da7)

i didn't find anything about this online so i've posted it here because it took me a bit to solve it

### Version

21.1.1

### Expected behavior

to load up without problem if the path contains white spaces

### Actual behavior

it doesn't load the main class

### How to Reproduce?

just put the folder containing the latest version of keycloak in a path with white space and use bin/kc.bat start-dev

**Comment by jsorah** [comment] 2023-06-22 18:34
Looks like a duplicate of https://github.com/keycloak/keycloak/issues/20115 - which I do have a PR up for (https://github.com/keycloak/keycloak/pull/20212) that you could try copying the batch file from there and see if it works for you.

**Comment by sschu** [comment] 2023-07-11 06:14
Also looks like a duplicate for me. I will go ahead and close this. If that turns out to be wrong, feel free to reopen it @Dexaf

**Closed by sschu** 2023-07-11 06:14 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
