### ISSUE TITLE
Infinispan/TCPPING does not span the cluster over all specified nodes

### ISSUE THREAD

**Issue by elronzo** [keycloak/keycloak#13089] opened 2022-07-13 14:24 UTC
### Describe the bug

keycloak.conf specifies:
```
cache=ispn
cache-stack=tcp
cache-config-file=cache-ispn-tcpping.xml
```

Infinispan config in cache-ispn-tcpping.xml looks like this

```   
<jgroups>
        <stack name="tcpping" extends="tcp">
            <TCP bind_port="7800" />
            <TCPPING
                initial_hosts="10.55.66.1[7800],10.55.66.2[7800],10.55.66.3[7800]"
                stack.combine="REPLACE"
                stack.position="MPING"
                />
        </stack>
 </jgroups>
```

With this config a cluster is only spun over nodes 1 and 3. Node 2 is not found by the other cluster members and does not find any other members. 

### Version

18.0.2

### Expected behavior

Expected behaviour is that the cluster is spun over all three cluster members as specified in initial_hosts.

### Actual behavior

Only two of three nodes are forming a cluster.

### How to Reproduce?

Take my config and try with KC 18.0.2 / Quarkus.

**Comment by martin-kanis** [comment] 2022-11-02 10:06
Discussion to a related topic https://github.com/keycloak/keycloak/discussions/12022

**Comment by mhajas** [comment] 2022-12-02 10:19
@elronzo Thank you for the report and sorry for the late reply.

I tried your config with the following steps and I was not able to reproduce it.
 
I unzipped KC 20.0.1 three times. To each instance I added the following config `cache-ispn-tcpping.xml` (I just changed `bind_port`):
```
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

        <jgroups>
            <stack name="tcpping" extends="tcp">
             <TCP bind_port="7800/7801/7802" /> // based on the instance
             <TCPPING
                  initial_hosts="10.40.20.15[7800],10.40.20.15[7801],10.40.20.15[7802]"
                  stack.combine="REPLACE"
                  stack.position="MPING"
               />
          </stack>
        </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>

```

And then I run each instance using the following command:
```
./kc.sh start-dev --cache-stack=tcp --cache-config-file=cache-ispn-tcpping.xml --http-port=8080/8081/8082
```

and it seems the cluster was formed successfully:
```
ISPN100010: Finished rebalance with members [mhajas-host-12762, mhajas-host-29715, mhajas-host-29308], topology id 9
```

Can you please share more details about how you run the nodes? Ideally, some docker-compose file that would help us reproduce the issue. Also, could you please have a look at the discussion @martin-kanis shared? There are some comments about how to configure the TCP stack.

**Comment by ahmedwarsama** [comment] 2023-01-28 18:53
@mhajas I can't see that you specified the jgroups stack in the transport element. 

Your config:
```
        <jgroups>
            <stack name="tcpping" extends="tcp">
             <TCP bind_port="7800/7801/7802" /> // based on the instance
             <TCPPING
                  initial_hosts="10.40.20.15[7800],10.40.20.15[7801],10.40.20.15[7802]"
                  stack.combine="REPLACE"
                  stack.position="MPING"
               />
          </stack>
        </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>
```

What's missing:
```
        <jgroups>
            <stack name="tcpping" extends="tcp">
             <TCP bind_port="7800/7801/7802" /> // based on the instance
             <TCPPING
                  initial_hosts="10.40.20.15[7800],10.40.20.15[7801],10.40.20.15[7802]"
                  stack.combine="REPLACE"
                  stack.position="MPING"
               />
          </stack>
        </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="tcpping"/> <------- (Specifying the stack to use)
```

**Comment by mhajas** [comment] 2023-02-20 13:52
@ahmedwarsama Thank you for the help, but I still cannot reproduce it. I am still getting: 
```
 Finished rebalance with members [mhajas-host-35802, mhajas-host-48772, mhajas-host-3131], topology id 9
```

**Comment by ahmedwarsama** [comment] 2023-02-20 14:08
That log message doesn't seem to indicate any errors. It seems to be working. Since you didn't specify a node-name in your cache config then infinispan comes up with names like "mhajas-host-35802". I recommend that you specify the node-names like this:

```
        <jgroups>
            <stack name="tcpping" extends="tcp">
             <TCP bind_port="7800/7801/7802" /> // based on the instance
             <TCPPING
                  initial_hosts="10.40.20.15[7800],10.40.20.15[7801],10.40.20.15[7802]"
                  stack.combine="REPLACE"
                  stack.position="MPING"
               />
          </stack>
        </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" 
           stack="tcpping"
           node-name="<hostname>"  <------- set the host name here
        />
```

Do this in all your nodes cache config files.

**Comment by mhajas** [comment] 2023-02-20 14:45
Weird but I needed to do the following 
```
./kc.sh build
```
before the changes within `cache-ispn-tcpping.xml` were applied.

But it still works:
```
Received new cluster view for channel ISPN: [my_hostname_1|4] (3) [my_hostname_1, my_hostname_2, my_hostname_3]
```

**Comment by ahmedwarsama** [comment] 2023-02-20 14:49
Awesome! Yes everytime you change the config file you need to build the config before starting keycloak.

**Comment by ahmedwarsama** [comment] 2023-02-20 15:02
You may be right, i haven't used Keycloak in developer mode. You can close it.

**Closed** 2023-02-20 15:08 UTC
Labels: kind/bug, area/dist/quarkus, area/infinispan, team/store, status/triage
