### ISSUE TITLE
Startup/DB Migration fails with Oracle 19: ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by synth3** [keycloak/keycloak#27590] opened 2024-03-06 09:00 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

When trying to install the current Version with an Oracle 19 DB, the DB Migration fails.

```log
Error has occurred while updating the database
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-24.0.0.xml::24.0.0-9758::keycloak:
     Reason: liquibase.exception.DatabaseException: ORA-00972: identifier is too long
 [Failed SQL: (972) CREATE INDEX INSTALL_TEST.USER_ATTR_LONG_VALUES_LOWER_CASE ON INSTALL_TEST.USER_ATTRIBUTE(LONG_VALUE_HASH_LOWER_CASE, NAME)]
	at liquibase.command.CommandScope.execute(CommandScope.java:253)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.updateChangeSet(LiquibaseJpaUpdaterProvider.java:189)
	at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.updateSynch(LiquibaseJpaUpdaterProvider.java:108)
	at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.update(LiquibaseJpaUpdaterProvider.java:84)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory$2.run(DefaultJpaConnectionProviderFactory.java:391)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:257)
[...]
```

In the `jpa-changelog-24.0.0.xml` file, there are two index names that may pose a problem as they exceed the maximum limit of 30 characters set by Oracle. This limit is applicable to Oracle Databases versions less than 12.2, if I'm not mistaken.
- [`USER_ATTR_LONG_VALUES_LOWER_CASE`](https://github.com/keycloak/keycloak/blob/3e46810b37160d643a0f82b014781bf41966aecd/model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml#L39C60-L39C92)
- [`FED_USER_ATTR_LONG_VALUES_LOWER_CASE`](https://github.com/keycloak/keycloak/blob/3e46810b37160d643a0f82b014781bf41966aecd/model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml#L43C64-L43C100)

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Startup succeeds.

### Actual behavior

Startup fails.

### How to Reproduce?

Start the current version with a Oracle 19 DB configured.

**Comment by ahus1** [comment] 2024-03-06 20:27
@synth3 - reading your statement the docs on the internet, since Oracle 12.2 longer identifiers are are allowed, and you state that you are running Oracle 19. We've been testing with 19.3 and this works with identifier names longer than 30. 

Could you please state the full version of the database you are using, and show that this version is still supported by Oracle?

```
SELECT BANNER_FULL FROM V$VERSION;
```

**Comment by ahus1** [comment] 2024-03-06 20:53
This is caused by the changes for #9758 implemented by @vramik and me. Let's figure out if we plan to support this database for the priority of this issue.

**Comment by synth3** [comment] 2024-03-06 21:04
@ahus1 Thanks for looking into this! Now that I think about it again, it doesn’t make sense that the 19 version doesn’t support identifiers larger than 30. I will check the database version and configuration used for our tests again tomorrow.

**Comment by synth3** [comment] 2024-03-07 13:08
> @synth3 - reading your statement the docs on the internet, since Oracle 12.2 longer identifiers are are allowed, and you state that you are running Oracle 19. We've been testing with 19.3 and this works with identifier names longer than 30.
> 
> Could you please state the full version of the database you are using, and show that this version is still supported by Oracle?
> 
> ```
> SELECT BANNER_FULL FROM V$VERSION;
> ```

@ahus1 @vramik 
-> 19c Version 19.3.0.0.0

Turns out we have the compatibility mode set to "12.1.0.0.0" - probably as the result of an outdated configuration template. 

Sorry for the unnecessary noise!

**Comment by vramik** [comment] 2024-03-07 13:12
@synth3 no worries! Thank you for the confirmation. Closing.

**Closed by vramik** 2024-03-07 13:12 UTC
Labels: kind/bug, priority/important, area/storage, team/core-iam, team/core-shared, backport/24.0
