### ISSUE TITLE
Better error handling on startup

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak#16030] opened 2022-12-16 05:36 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

When I start keycloak with `--optimized` I get the following error:

> ERROR: Failed to start server in (production) mode
Error details:
io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors have prevented the application from starting. The errors are:
    - No value present
    - No value present

Although this version works with exactly the same config in an another namespace.

I am not trying to understand why it fails, just stating that the error message is all but helpful (I checked the obvious, env variables...).

### Version

19.0.3

### Expected behavior

Should display better error messages

### Actual behavior

Useless for debugging

### How to Reproduce?

Maybe jus try to start a keycloak, with missing db credentials or something similar I suspect.
Edit: have a type in KC_DB: `keycloak` instead of `postgres`

**Comment by pedroigor** [comment] 2022-12-20 20:16
@yelhouti Thanks, closing as it is a duplicate of https://github.com/keycloak/keycloak/issues/13608.

**Closed by pedroigor** 2022-12-20 20:16 UTC
Labels: kind/bug, area/dist/quarkus, status/triage

**Comment by yelhouti** [comment] 2022-12-20 20:17
@pedroigor thanks a lot, don't know how I missed that
