### ISSUE TITLE
Case sensitivity differences between /users and /users/count endpoints

### ISSUE THREAD

**Issue by Gjgarr** [keycloak/keycloak#22874] opened 2023-08-31 22:19 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

For `GET /{realm}/users`:
Searching for users by `firstName`, `lastName`, etc is case insensitive.
The API will return the same results between searching for a firstName of `john` or `John`.

For `GET /{realm}/users/count`
Searching for users by `firstName`, `lastName`, etc is case **sensitive**.
The API will return *different* results between searching for a firstName of `john` or `John`.

It would be preferrable for behavior of the two endpoints to align when searching using these fields.

### Version

21.1.2

### Expected behavior

Behavior of the two endpoints to align.

### Actual behavior

Search parameters on one endpoint is case insensitive, whereas searching on the other is case sensitive.

### How to Reproduce?

* create 5 users with varying case of `john` vs `John` as a firstName
* Search for users by firstName of both cases
    * `GET /{realm}/users?firstName=john` - should have 5 results
    * `GET /{realm}/users?firstName=John` - should have 5 results
* Get count of users by firstName of both cases
    * `GET /{realm}/users/count?firstName=john` - expected 5; actual is <5
    * `GET /{realm}/users/count?firstName=John` - expected 5; actual is <5

**Comment by pedro-hos** [comment] 2023-09-01 18:48
I don't know, maybe we can have some parameter on the count endpoint to ignore the case.

**Comment by mposolda** [comment] 2023-09-06 10:50
I think it would be good if "count" endpoint is case insensitive as well if possible. So that both "count" endpoints would also return 5.

@pedro-hos If you can work on this, it would be very welcome. Is it ok that I assigned this issue to you?

**Comment by pedro-hos** [comment] 2023-09-06 12:42
> I think it would be good if "count" endpoint is case insensitive as well if possible. So that both "count" endpoints would also return 5.
> 
> @pedro-hos If you can work on this, it would be very welcome. Is it ok that I assigned this issue to you?

Sure, I will work on that and send the PR sooner =D

**Comment by pedro-hos** [comment] 2023-09-06 21:07
Hi @Gjgarr 
I've tried to reproduce the same behaviour but I have no luck on that:

[Username test](https://github.com/keycloak/keycloak/assets/8390247/74fc7532-dc59-4ad0-88b4-04564dcb7335)

In all my tests the count endpoint is not case-sensitive.  Can you please share the users that you've used to test?

**Comment by sschu** [comment] 2023-09-11 06:29
@pedro-hos Please be aware that case sensitivity also depends on your database collation. Some databases (e.g. MS SQL) have default collations that are not case sensitive.

**Comment by pedro-hos** [comment] 2023-09-11 12:14
Thank you for the tip @sschu I will with other databases.

**Comment by sschu** [comment] 2023-09-12 06:03
Postgres at least should be case-sensitive AFAIK.

**Comment by pedro-hos** [comment] 2023-09-12 20:27
Hi @sschu, I was looking through the query code, and it seems that the same is already case-insensitive due `predicates.add(builder.like(builder.lower(root.get(key)), "%" + value.toLowerCase() + "%"));` in 

https://github.com/keycloak/keycloak/blob/f767eb109e4d419a08be2bb09c42e43b706ee7b2/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L954C17-L954C33

```java
...
                case FIRST_NAME:
                case LAST_NAME:
                    if (Boolean.parseBoolean(attributes.get(UserModel.EXACT))) {
                        predicates.add(builder.equal(builder.lower(root.get(key)), value.toLowerCase()));
                    } else {
                        predicates.add(builder.like(builder.lower(root.get(key)), "%" + value.toLowerCase() + "%"));
                    }
                    break;
...
```
So, both FIRST_NAME and LAST_NAME are using the criteria builder lower and the value to lower also. Maybe there are some other ways to reproduce it, but I can't find them, and I guess that the query is already case-insensitive.

**Comment by sschu** [comment] 2023-09-13 14:14
I checked this with KC 22.0.3 and a PostgreSQL and I could not reproduce this. I also checked the code and it looks like the code used to filter the users and counting them are exactly the same. So I would go ahead and close this issue as cannot reproduce. 

@Gjgarr If you can reproduce this with the current Keycloak version, please reopen it and provide exact steps to reproduce.

**Closed by sschu** 2023-09-13 14:14 UTC
Labels: kind/bug, area/admin/api, help wanted, team/core
