### ISSUE TITLE
After switch to SolutionRealm and press Sessions getting a Unexpected non-whitespace character after JSON at position 2 (line 1 column 3) error.|

### ISSUE THREAD

**Issue by DREGALLA** [keycloak/keycloak#29963] opened 2024-05-29 09:42 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After switch to SolutionRealm and press Sessions getting a Unexpected non-whitespace character after JSON at position 2 (line 1 column 3) error.|
![image](https://github.com/keycloak/keycloak/assets/142571886/d2e3ba54-3469-4c35-b14a-2ab31edf59ee)

### Version

22

### Regression

- [ ] The issue is a regression

### Expected behavior

Need to see the Session page

### Actual behavior

After switch to SolutionRealm and press Sessions getting a Unexpected non-whitespace character after JSON at position 2 (line 1 column 3) error.|

### How to Reproduce?

After switch to SolutionRealm and press Sessions getting a Unexpected non-whitespace character after JSON at position 2 (line 1 column 3) error.|

**Comment by edewit** [comment] 2024-05-29 11:50
I can't reproduce this and it might be fixed in a later version

~old-release

**Comment by DREGALLA** [comment] 2024-05-31 04:50
Hello @edewit ,

Is there any possibility due to the size of session it is breaking we have 3000 plus session running.


Please refer the below configuration we made in the keycloak

![image](https://github.com/keycloak/keycloak/assets/142571886/977087e0-e5f8-4753-a5be-2bbe1bd48abb)
![image](https://github.com/keycloak/keycloak/assets/142571886/5c5d2c7a-8350-42be-b07b-7574c0909d9d)
Is the below PR fix this issue
https://github.com/keycloak/keycloak/pull/28802

**Comment by DREGALLA** [comment] 2024-06-04 09:10
Hell @edewit , Is there any possibility this admin UI sessions break due to external load balancer.

Also Is the below PR fix this issue
https://github.com/keycloak/keycloak/pull/28802

If the sessions size increase that time it  giving the  Unexpected non-whitespace character after JSON at position 2 error

**Closed** 2024-07-02 19:04 UTC
Labels: kind/bug, area/storage, area/admin/ui, team/core-iam, status/auto-expire, status/expired-by-bot
