### ISSUE TITLE
Realm admin console tries to load logon iframe from front-end URL instead of admin URL when front-end URL is set

### ISSUE THREAD

**Issue by fostermi** [keycloak/keycloak#25130] opened 2023-11-29 17:02 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When accessing a REALM admin console (/admin/<realm>/console) using a configured KC_HOSTNAME_ADMIN, which is not public facing, the page tries to embed an IFRAME of the login page using the configured "Front-end" of the realm, which IS public facing, instead of the admin URL. This results in the browser failing to load the page at all and the console error message is: 
```
Refused to frame 'https://external-auth.example.com' because an ancestor violates the following Content Security Policy directive: "frame-ancestors: 'self'"
```
By, removing the front-end configuration in the realm entirely to let the browser "sort-it-out", the Realm admin console correctly tries to fetch the login page using the internal admin URL. 

However, this has a side effect that any applications that are accessed internally but are configured to redirect a user login to the external login page break. The application redirects correctly to the external address (https://external-auth.exmple.com) for login, but after entering credentials, the browser tries to send an HTTP POST with the credentials to Keycloak over the **internal** address instead:
```
https://internal-admin.example.com/login-actions/authenticate?session_code=lKlg3
```
So either the realm admin consoles are not doing the right thing when accessed over the admin url when the front-end is set or the javascript on the login page is not doing the right thing when accessed over the external url when the front-end is NOT set. Or there is just lack of clarity on how to use the admin URL, the configured hostname URL for internal applications and any configured front-end URL. 

### Version

22.0.1

### Expected behavior

If a front-end is configured for the realm, the admin console should still pull the login page from the configured admin URL.

If a front-end is not configured for the realm, any login page called from the external URL should still POST the credentials to external URL the login page was fetched..

### Actual behavior

The Realm admin console tries to load the login page from any configured front-end URL, instead of the admin url.

When the front-end is not set, the admin console works, but you can't use the external auth URL on an internal application.

### How to Reproduce?

Set KC_HOSTNAME and KC_HOSTNAME_ADMIN to the same internal hostname of KC. Then set the front-end of the realm to your external auth.

**Comment by ssilvert** [comment] 2024-02-09 01:56
@mposolda This seems like more of a core issue than a UI issue.  But feel free to kick it back if you disagree.

**Comment by vmuzikar** [comment] 2024-02-19 15:22
@fostermi Thank you for reporting this and my apologies for our late response on this issue.

I could not reproduce the issue but I think that might be due to some misunderstanding. What I did was:
1. Start the server with `--hostname host --hostname-admin host-admin`.
2. Create a Realm named `test-realm` with front-end URL set to `realm-url`, and create a user in it.
3. I accessed the admin console of `test-realm` via `host-admin/admin/test/console/`.
4. Got redirected to `realm-url` login page. This is correct, login flow is always sitting on a front-end URL.
5. After entering the creds, the form was sent to a `realm-url/.../authenticate` endpoint. Again, this is correct.
6. Got redirected back to admin console living at `host-admin`.

Also tried with `--hostname host --hostname-admin host` with the same expected result.

I don't see it as a bug, hence closing this issue. Let me know if you think otherwise.

**Closed by vmuzikar** 2024-02-19 15:22 UTC
Labels: kind/bug, area/core, team/cloud-native, status/triage

**Comment by vmuzikar** [comment] 2024-02-28 07:53
Yes, in my steps the `realm-url` and `host` were different (and they have to be – URL is not a hostname). The admin URL is not meant to host any login flow – that always goes through the frontend. Admin URL is meant for the admin console itself, think of it as an independent app hosted on a separate URL that is secured by Keycloak hosted on the frontend URL. A single realm can't use different URLs for the login process based on which app/client requested the login.
