### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by slominskir** [keycloak/keycloak#19244] opened 2023-03-22 13:29 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When attempting to save a realm client configuration in the admin UI occasionally the Save button click results in no visible outcome and instead an error in the developer web console:

```
LogoutPanel.tsx:139 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at validate (LogoutPanel.tsx:139:27)
    at je (index.esm.mjs:802:34)
    at X (index.esm.mjs:1606:46)
    at async X (index.esm.mjs:1621:22)
    at async Object.fe [as trigger] (index.esm.mjs:1818:42)
    at async ne (ClientDetails.tsx:322:11)
```

Using Chrome browser latest (111.0.5563.111)

### Version

21.0.1

### Expected behavior

Saving a client should not fail silently with errors in developer console.

### Actual behavior

Saving a client failed silently.

### How to Reproduce?

Try updating an existing realm client.

### Anything else?

See developer console screenshot below, which shows issue is with backchannelLogoutUrl field.  If you add a space and then remove it and then re-save it "fixes" the issue.

<img width="548" alt="Screenshot" src="https://user-images.githubusercontent.com/2642119/226921643-a382ffa1-53b2-4c87-869c-addb765c4bf5.png">

Also, I created the client using the admin CLI and just went in to update something using the GUI.  Therefore it seems whatever the admin CLI does by default may not line up with whatever the Admin GUI likes.   I'm leaving the backchannelLogoutUrl field empty so perhaps admin CLI defaults it to null whereas GUI expects empty string?

**Comment by edewit** [comment] 2023-04-27 10:40
duplicate of #19883

**Closed by edewit** 2023-04-27 10:40 UTC
Labels: kind/bug, impact/medium, area/admin/ui, team/ui
