### ISSUE TITLE
realm import: error if ldap groupmapper has a group path set

### ISSUE THREAD

**Issue by bpedersen2** [keycloak/keycloak#10730] opened 2022-03-14 09:20 UTC
### Describe the bug

When importing a realm that has a ldap federation with a group mapper set sets an group path then the import aborts with an error:
```2022-03-14 08:27:13,639 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-41) Uncaught server error: org.keycloak.component.ComponentValidationException: ldapErrorMissingGroupsPathGroup
at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapperFactory.validateConfiguration(GroupLDAPStorageMapperFactory.java:308)
at org.keycloak.models.jpa.RealmAdapter.importComponentModel(RealmAdapter.java:2020)
at org.keycloak.models.utils.RepresentationToModel.importComponents(RepresentationToModel.java:620)
at org.keycloak.models.utils.RepresentationToModel.importComponents(RepresentationToModel.java:622)
at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:399)
```

### Version

17.0.0 (quarkus)

### How to Reproduce?

realm.json (edited)

```
.... 
"groups": [
    {
      "id": xxxx,
      "name": "some-path",
      "path": "/some-path",
      "attributes": {},
      "realmRoles": [],
      "clientRoles": {},
      "subGroups": [
        {
          "id": "xxxx",
          "name": "sgroup1",
          "path": "/some-path/sgroup1",
.....
        },
]
....    

   "org.keycloak.storage.UserStorageProvider": [
      {
        "id": "df9247ed-843f-4988-9149-bc1a796e7a1f",
        "name": "ldap-forge",
        "providerId": "ldap",
        "subComponents": {
          "org.keycloak.storage.ldap.mappers.LDAPStorageMapper": [
            {
       ...
          "name": "groups",
              "providerId": "group-ldap-mapper",
              "subComponents": {},
              "config": {
                "membership.attribute.type": [
                  "UID"
                ],
                "group.name.ldap.attribute": [
                  "cn"
                ],
                "preserve.group.inheritance": [
                  "false"
                ],
                "membership.user.ldap.attribute": [
                  "uid"
                ],
                "groups.dn": [
                  "ou=xxx,dc=xxx,dc=xxx,dc=xxx"
                ],
                "mapped.group.attributes": [
                  "cn"
                ],
                "mode": [
                  "LDAP_ONLY"
                ],
                "user.roles.retrieve.strategy": [
                  "LOAD_GROUPS_BY_MEMBER_ATTRIBUTE"
                ],
                "ignore.missing.groups": [
                  "false"
                ],
                "membership.ldap.attribute": [
                  "memberUid"
                ],
                "group.object.classes": [
                  "posixGroup"
                ],
                "memberof.ldap.attribute": [
                  "memberOf"
                ],
                "groups.path": [
                  "/some-path"
                ],
                "drop.non.existing.groups.during.sync": [
                  "false"
                ]
              }
            },
           ....
            }
          ]
        },
        ....
      },
  ```

**Comment by ahus1** [comment] 2023-01-19 14:28
I could validate that this is a bug. When adding a group mapper with a path, it requires the group to be present first. This problem might exist since KC11 - 6005503a3dd7b65b79e8c3289738cb5d60779d8f

Reproduce with this attached JSON file when creating a new realm: [realm-export-with-ldap-group-mapper.json.gz](https://github.com/keycloak/keycloak/files/10457498/realm-export-with-ldap-group-mapper.json.gz)

The full exception thrown: 

```
org.keycloak.component.ComponentValidationException: ldapErrorMissingGroupsPathGroup
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapperFactory.validateConfiguration(GroupLDAPStorageMapperFactory.java:308)
	at org.keycloak.models.jpa.RealmAdapter.importComponentModel(RealmAdapter.java:2026)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importComponents(LegacyExportImportManager.java:1134)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importComponents(LegacyExportImportManager.java:1136)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:397)
	at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:126)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:571)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:504)
	at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:54)
	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
	at org.keycloak.storage.ImportRealmFromRepresentationEvent.fire(ImportRealmFromRepresentationEvent.java:50)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:159)
	at org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.testsuite.UndertowRequestFilter.lambda$doFilter$0(UndertowRequestFilter.java:49)
	at org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
	at org.keycloak.testsuite.UndertowRequestFilter.doFilter(UndertowRequestFilter.java:47)
```

Possible workaround I found: 

* Modify the JSON before importing and change the path to "/". Once the import is complete, change the path to the real value. 

The following did not work: 

* Create the realm, create the group, then import the realm with "overwrite" - it would fail with a "ModelDuplicateException" in the log, as overwriting of groups doesn't seem to work well. Looking at the code it only tries a create, and not handles the exception. If I choose "skip", the LDAP and the LDAP mapper are not added to the realm. So this might be a dead end for that reason anyway.

**Comment by MartinWeise** [comment] 2024-06-24 18:04
I encounter the same issue as @ahus1 on 21.0

**Comment by mpsOxygen** [comment] 2024-07-29 14:08
I encoutered the same issue in Kyecloak 24.0.5. The export/import functionality seems to be broken and useless if you have any real configurations in Keycloak.

**Comment by kyale** [comment] 2024-09-27 17:44
The cause of this is that groups are being imported **after** the components are imported. If any component has a reference to any group which is part of the realm import you'll end up with an error. The same happens for the LDAP hard coded group mapper. This should be resolved whenever https://github.com/keycloak/keycloak/pull/33358 is approved and merged

**Closed** 2024-09-30 14:46 UTC
Labels: kind/bug, priority/important, area/import-export, area/ldap, help wanted, team/core-iam, status/bumped-by-bot
