### ISSUE TITLE
Firefox causes IOException

### ISSUE THREAD

**Issue by ADASNET** [keycloak/keycloak#12285] opened 2022-06-01 06:48 UTC
### Describe the bug

We have a provider in our authentication flow that only shows a checkmark to confirm a login, it works perfectly fine in Microsoft Edge and Google Chrome but for whatever reason Firefox causes the entire flow to fail once it reaches this checkmark and invokes the loginAction.

This is the error it causes
![image](https://user-images.githubusercontent.com/106650650/171342064-75c81777-5d80-4153-ac29-f849911ddb68.png)

And this is our checkmark FTL code
![image](https://user-images.githubusercontent.com/106650650/171342521-cc225eed-72fe-45c0-9bdb-06d334040e47.png)

And here is the authentication flow where it is the last segment, it does nothing but send the FTL page as a challenge and simple lets the context succeed once it has submitted.
![image](https://user-images.githubusercontent.com/106650650/171344038-28f5b19c-1657-4e99-889e-4e9633378505.png)

The checkmark code is taken from another project that runs on Red Hat SSO and we have tested that works fine in Firefox

### Version

18.0.0

**Comment by mabartos** [comment] 2022-06-24 08:24
@ADASNET Thanks for creating this issue. It's quite interesting behavior of Firefox browser. It seems Firefox prepares the form parameters in a different way than Chromium-based browsers, which may conclude in different behavior. And then the Resteasy cannot parse the form parameters, because no parameter is specified though and the stream is empty. 

Possible solutions:
- Wait for upgrade Resteasy to v4 and maybe it'll resolve the issue #10916 
- Add some parameter to the form in order to avoid sending POST requests with an empty body

Something like that
```
<form id="checkId" method="post" action="${url.loginAction}">
  <input type="hidden" name="ignore" value="42">
...
```

However, I'm not sure, whether the request will be properly processed. I haven't tried it and I'm just sharing my first thoughts about it, maybe it'll help somehow. Did you try to use a more recent version of the Firefox browser?

**Comment by mposolda** [comment] 2023-04-04 09:34
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by mabartos** [comment] 2023-04-14 09:42
Closing this due to inactivity. There are no other reported issues related to this problem.

@ADASNET Could you please try it with the latest main branch? Feel free to reopen this issue if the problem persists.

**Closed by mabartos** 2023-04-14 09:42 UTC
Labels: area/authentication, kind/bug, status/triage
