### ISSUE TITLE
"duplicate key value violates unique constraint" when starting two keycloak instances towards a single postgres db

### ISSUE THREAD

**Issue by Fex97** [keycloak/keycloak#14279] opened 2022-09-08 11:34 UTC
### Describe the bug

Hello,
When trying to start two keycloak instances towards a single postgres instance one of the keycloaks gets stopped because of duplication of key,value in db from the first keycloak that creates the tables.

### Version

19.0.1

### Expected behavior

Both Keycloak instances start and connects to the empty postgres db without issue
the last keycloak should find the required tables and not try to force create a duplicate.

### Actual behavior

[error_dump.txt](https://github.com/keycloak/keycloak/files/9526212/error_dump.txt)

if you restart the keycloak images after the initial docker-compose up with a empty database 
the connection is succesfully made between both the instances.

### How to Reproduce?

[keycloak.env.txt](https://github.com/keycloak/keycloak/files/9526201/keycloak.env.txt)
[docker-compose.yml.txt](https://github.com/keycloak/keycloak/files/9526202/docker-compose.yml.txt)

docker-compose up

**Comment by trixpan** [comment] 2022-09-13 01:32
@Fex97 you seem to be running a cluster without clustering? If that is the case, then the behavior is as expected and not a bug. Configure clustering and that "problem" will go away

**Comment by Fex97** [comment] 2022-09-26 13:02
Yes i added the command "--cache ispn" like this:
    idp2:
        image: quay.io/keycloak/keycloak:19.0.1
        command:  
          - start-dev
          - --cache ispn
          #- --storage=jpa
        env_file:
            - keycloak.env
        ports:
            - "9997:8080"
        depends_on:
          - db_postgres
          
This works fine in 17.0.1 but throws error in 19.
          
[error_dump_cache_ispn.txt](https://github.com/keycloak/keycloak/files/9646402/error_dump_cache_ispn.txt)

**Comment by hmlnarik** [comment] 2022-10-05 12:32
@Fex97  Could you please check in the admin console which provider is there enabled for `dblock` spi? This information is available e.g. in admin console, `https://SERVER/auth/admin/master/console/#/master/providers`

**Comment by hmlnarik** [comment] 2022-10-21 12:24
Thanks for reporting this issue. However, due to lack of information we are not able to triage this issue effectively. Due to this we are closing the issue, but feel free to reopen the issue when you are able to provide more information and steps to reproduce the issue.

**Closed by hmlnarik** 2022-10-21 12:24 UTC
Labels: kind/bug, area/storage, status/triage
