### ISSUE TITLE
After switching the Admin UI theme to "Base," an error occurred when attempting to access the keycloak login

### ISSUE THREAD

**Issue by Tejasbglr** [keycloak/keycloak#21421] opened 2023-07-04 05:43 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hi,

We were able to install the quarkus based keycloak ( 21.1.1 ) and access its GUI. 
Later we changed the **Realm setting --> Themes --> Admin UI theme** to "base" and save it. 
Now after logging out from the UI if we again try to login to the keycloak UI we are facing the following error 

![image](https://github.com/keycloak/keycloak/assets/97670904/f8d3d68d-a5e4-4a6f-8323-f31c13c1b814)

### Version

21.1.1

### Expected behavior

After changing the Admin UI theme to "base" and signing out we should be directed to the keycloak UI page.

### Actual behavior

After changing the Admin UI theme to "base" and signing out we are not able to get the keycloak login page.

### How to Reproduce?

Described in detail in the above section

**Comment by jonkoops** [comment] 2023-07-04 10:37
I am able to reproduce this and getting an exception with the following log:

<details>
  <summary>Show log</summary>
  
  ```log
2023-07-04 12:33:58,003 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-6) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)
	at org.keycloak.services.resources.admin.AdminConsole.getMainPage(AdminConsole.java:354)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@307efe8b.
	at freemarker.template.Configuration.getTemplate(Configuration.java:2883)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2703)
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.getTemplate(DefaultFreeMarkerProvider.java:66)
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:45)
	... 42 more
  ```
</details>

Looks like the `index.ftl` template does not exist in the base theme. I don't quite understand why the base theme is even selectable, as far as I know these themes serve to be extended, and should not be set directly.

We're likely to get rid of the base themes in the future entirely, so I am not quite sure how we want to handle this bug.

**Comment by ssilvert** [comment] 2023-07-06 00:13
+1 for getting rid of the base theme for admin.  It doesn't make a lot of sense to have it there now that the old console is gone.

Admin V2 does still extend from the base theme but that is only because server-side error messages need access to the message bundles from base.  We could move this into V2.

**Comment by jonkoops** [comment] 2023-07-06 09:20
@stian roping you into this conversation. I think you also had the idea to get rid of the base themes, right? Perhaps we should plan this out and attach it to a milestone? I am sure we have community themes that depend on this, so we should communicate this clearly.

**Comment by stianst** [comment] 2023-07-10 08:57
The original intent for the base themes was they where supposed to be the non-styled themes. Not something you would select directly as the active theme, but rather a good starting point to create a custom theme.

That's still the case for email and login themes I believe, but looks like it's not the case for account and admin console. There's also the common resources theme that only has a keycloak theme, but no base theme.

I think the ideal would be to tweak the account and admin themes so the base theme would still work, but would not apply any styles. Then the keycloak themes basically just introduces the default Keycloak styling. Not sure how feasible this is though.

We could also consider making the base themes abstract themes, meaning you can create a custom theme that extends it, but probably not be able to select it as the active theme.

**Comment by ssilvert** [comment] 2023-07-12 20:50
@stianst @jonkoops I propose that we go ahead and make the base theme unselectable for now.  That would fix this bug as reported.  We can decide the rest as part of the cleanup effort that we are starting to look at concerning all the themes.

WDYT?

**Comment by jonkoops** [comment] 2023-07-14 10:06
@ssilvert I agree that this theme should not be selectable, however, it looks like this is also causing issues when users are extending the base theme (see #21654).

**Comment by yangjuexi-ones** [comment] 2023-08-01 09:13
i met the same issue today. Do we have some commands to get back quickly? i read the document but not sure how to fix it temporarily.

**Comment by jonkoops** [comment] 2023-08-01 09:22
So I think we should resolve this as follows:

1. The API needs to be modified not to return the `base` themes.
2. We need a migration to move all installations that use a `base` theme away from them.

Who can pick this up?

**Comment by ssilvert** [comment] 2023-08-01 20:48
@yangjuexi-ones @makarov-roman I can provide you a workaround for now (admin theme only).

The old admin console was saved in [my repo here](https://github.com/ssilvert/old-keycloak-admin-console).  If you install that then the base theme should work again.  I suggest that you delete the keycloak theme as it is considered insecure.

**Comment by ssilvert** [comment] 2023-08-01 20:53
> @yangjuexi-ones @makarov-roman I can provide you a workaround for now (admin theme only).
> 
> The old admin console was saved in [my repo here](https://github.com/ssilvert/old-keycloak-admin-console). If you install that then the base theme should work again. I suggest that you delete the keycloak theme as it is considered insecure.

Actually, I just tried this and if you delete the keycloak theme it won't work.  Base theme still relies on AngularJs, which is in the keycloak/common.  So you would still be running code that is no longer maintained and may be considered insecure.

**Comment by makarov-roman** [comment] 2023-08-02 07:17
Alright, means the only long term solution is to reassemble the theme.

**Comment by gregflynn** [comment] 2023-08-03 20:43
This is an incredible foot-gun for the new to keycloak. If you're like me and ran head first into this naively looking for alternate shiny paint and you lock yourself out of the admin ui with a white 500 page because of this:
```sql
update realm set admin_theme = null;
```

running that sql and restarting the service got me back in

Adapted SQL from this mailing list entry from eight years ago: https://lists.jboss.org/pipermail/keycloak-user/2015-June/002364.html

**Comment by yangjuexi-ones** [comment] 2023-08-04 07:58
> > @yangjuexi-ones @makarov-roman I can provide you a workaround for now (admin theme only).
> > The old admin console was saved in [my repo here](https://github.com/ssilvert/old-keycloak-admin-console). If you install that then the base theme should work again. I suggest that you delete the keycloak theme as it is considered insecure.
> 
> Actually, I just tried this and if you delete the keycloak theme then base theme won't work. Base theme still relies on AngularJs, which is in the keycloak/common. So you would still be running code that is no longer maintained and may be considered insecure.



> @yangjuexi-ones @makarov-roman I can provide you a workaround for now (admin theme only).
> 
> The old admin console was saved in [my repo here](https://github.com/ssilvert/old-keycloak-admin-console). If you install that then the base theme should work again. I suggest that you delete the keycloak theme as it is considered insecure.

Thanks , i chose to reinstall it just because i had not made it open to all users

**Comment by yangjuexi-ones** [comment] 2023-08-07 03:16
> > @yangjuexi-ones @makarov-roman I can provide you a workaround for now (admin theme only).
> > The old admin console was saved in [my repo here](https://github.com/ssilvert/old-keycloak-admin-console). If you install that then the base theme should work again. I suggest that you delete the keycloak theme as it is considered insecure.
> 
> Actually, I just tried this and if you delete the keycloak theme then base theme won't work. Base theme still relies on AngularJs, which is in the keycloak/common. So you would still be running code that is no longer maintained and may be considered insecure.

During the weekend, I suddenly recalled this issue and started doubting whether there was a problem with how I had expressed myself. So I consulted with Claude, and it seems my response made me appear less courteous than intended. What I want to reiterate is that I'm very grateful for your suggestions. However, due to time constraints, I had to opt for reinstalling it to avoid impacting my development progress. Nonetheless, I still appreciate you taking the time to advise me. Please forgive me as I'm still learning how to properly phrase things in English

**Comment by ssilvert** [comment] 2023-08-23 20:44
I'm providing a quick fix for this so the base theme will be hidden.  The rest of the discussion around this can be addressed in #22671 .

**Closed** 2023-08-24 19:49 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui

**Comment by jonkoops** [comment] 2023-08-25 15:36
@ssilvert could you create a PR to back-port this fix to version 22?

**Comment by ssilvert** [comment] 2023-08-25 19:03
> @ssilvert could you create a PR to back-port this fix to version 22?
Done. #22728
