### ISSUE TITLE
Endpoints can have conflicting results -- /groups/{groupid}/members & /users/{userid}/groups

### ISSUE THREAD

**Issue by bp974** [keycloak/keycloak#15553] opened 2022-11-17 17:57 UTC
### Area

ldap

### Describe the bug

While having an LDAP user federation connected to AD and having a group mapper to pull in group membership, there can be conflicting results in 2 endpoints. 

### Version

19.0.2 & 20.0.1

### Expected behavior

Hit `/groups/{groupid}/members` and see that member exists.

Hit `/users/{userid}/groups` and see that the groupid from above is shown in the list. 

### Actual behavior

Hit `/groups/{groupid}/members` and see that member exists.

Hit `/users/{userid}/groups` and see that the groupid from above is NOT shown in the list. 

### How to Reproduce?

Connect LDAP federation as well as group mapper. 

Now say user1 and group1 belong within the AD server but user1 is not part of group1. User sync has just occurred and set to 5 minute sync period for changed users. 

Now add user1 to group1 with the AD server.
Before the next sync has an opportunity to run hit the following endpoints and observe the conflicting information.

`/groups/{group1 UUID}/members` -- will return user1 in the list

`/users/{user1 UUID}/groups` -- will NOT return group1 in the list

Once the next sync period has ran, this group1 will now belong in the list for endpoint `/users/{user1 UUID}/groups`
Forcing user cache deletion also allows the users endpoint to populate the group prior to the next sync period. 

### Anything else?

Setting cache settings to disabled or to something less than the changed users sync period will allow this to refresh on a quick cadence but may not be ideal. 

I'm curious as to why cache is not used for the groups endpoint but is used for the users endpoint.

**Comment by hmlnarik** [comment] 2022-11-29 14:52
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of Keycloak, feel free to reopen and provide details to why it is still valid.

**Closed by hmlnarik** 2022-11-29 14:52 UTC
Labels: kind/bug, area/ldap, status/triage
