### ISSUE TITLE
Align httpclient dependency with the Quarkus Platform BOM

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#21392] opened 2023-07-02 22:08 UTC
### Description

httpclient removal caused [unit test failures](https://github.com/keycloak/keycloak/actions/runs/5411587832/jobs/9834779968)

[By reverting the changes](https://github.com/keycloak/keycloak/pull/21078/commits/ed5e9df7ec6af0137131fe6fe71ee362cd4e2667) and re-adding the dependency override back to the parent POM, all the workflows got stable again. I didn't have time to investigate the cause in more depth yet, therefore it's expected to address it in this follow-up as both the dependencies can be possibly aligned with the Quarkus Platform BOM.

This task serves as an follow-up of https://github.com/keycloak/keycloak/pull/21078.

**Comment by vmuzikar** [comment] 2023-08-04 16:22
@ahus1 @vramik Given this issue does not seem to be very straightforward, I wonder if this belongs more to the store team (as also suggested by #22024 :)).

**Comment by ahus1** [comment] 2023-08-04 16:31
@vmuzikar - looking at the logs of run which failure was attributed to Liquibase, I saw mostly classes not being found.

I suppose this issue should be split. As we have already #22024, all references to liquibase should be removed from this issue, and this issue should remain with the CND team.

**Comment by vmuzikar** [comment] 2023-08-07 06:26
I see #22024 as a duplicate of this issue. Both are about removing liquibase from parent POM and assuming green tests. :) I'm not sure how to split that.

**Comment by ahus1** [comment] 2023-08-07 06:49
@vmuzikar - I assumed that only liquibase belongs to the store team. When you remove liquibase from this issue, they are no longer duplicates, store team will handle the other issue and CND will handle this issue. Call? :-)

**Comment by vmuzikar** [comment] 2023-08-07 06:55
Ah, yeah, this is also about http client, sorry (Monday morning :D). Makes sense to split.

**Closed** 2024-04-23 08:09 UTC
Labels: team/cloud-native, kind/task
