### ISSUE TITLE
Improve UX of read-only attributes

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#26585] opened 2024-01-30 09:56 UTC
### Description

Read-only User attributes: make the UI displaying clearly that those attributes are read-only.
E.g. by using proper CSS styles.

### Motivation

Now it's possible to edit those attribute values but after save the changes are ignored.

On the screenshot the attribute LDAP_ID looks editable but it's fake.
![изображение](https://github.com/keycloak/keycloak/assets/1285898/2144f060-9e46-4678-abb5-d3f6f900e4bb)

Keycloak also behaves differently in different versions when we try to change these attributes values:
**22.0.5**: ignores the changes, shows the error 
![изображение](https://github.com/keycloak/keycloak/assets/1285898/a2f821aa-e6ba-4637-af62-185a81c8d905)

**23.0.5**: just ignores the changes, doesn't inform user about anything.

### Details

Could be also related to the improvement from https://github.com/keycloak/keycloak/issues/25977

**Comment by mposolda** [comment] 2024-01-30 10:27
@lrozenblyum I think that this should be already addressed in latest Keycloak main. Could you please try to download latest Keycloak nightly build from https://github.com/keycloak/keycloak/releases/tag/nightly and confirm if the issue is already addressed here?

**Comment by mposolda** [comment] 2024-01-30 10:28
Adding to 24 for now just to make sure that this is already addressed before user-profile is supported. But I think that this is already improved (Will need to wait for feedback from @lrozenblyum to confirm).

**Comment by lrozenblyum** [comment] 2024-01-30 12:58
@mposolda checked the recent nightly build, the result looks unchanged.

I had to set the setting `Unmanaged Attributes` = `Enabled` at Realm level to show the Attributes tab on the user screen.

Here's the screenshot
![изображение](https://github.com/keycloak/keycloak/assets/1285898/25883741-291e-4538-9ac7-1b5d77f97438)
just ignores the changes, doesn't inform user about anything (same like in 23.0.5)

**Comment by mposolda** [comment] 2024-01-30 16:31
duplicates #25977 

@lrozenblyum Yes, you're right. The issue is still present. As you pointed, this is in fact same (similar) issue to the #25977 . That one would be fixed in Keycloak 24 and it already has PR. So you can monitor that issue for further updates.

Closing this one as duplicate of #25977

**Closed by mposolda** 2024-01-30 16:31 UTC
Labels: kind/enhancement, area/user-profile, team/core
