### ISSUE TITLE
Bump bouncycastle from 1.68 to 1.70

### ISSUE THREAD

**Issue by Bredstone** [keycloak/keycloak#14148] opened 2022-09-01 19:02 UTC
### Description

This upgrade should make possible to use **NIST post-quantum cryptography** algorithms, provided by bouncycastle.

**Comment by abstractj** [comment] 2022-10-26 19:54
Duplicate of #12411

**Comment by abstractj** [comment] 2022-10-26 19:55
Also, @david-rh started to investigate the removal of BC to resolve the ticket created by @stianst #12416

**Closed** 2022-11-03 08:17 UTC
Labels: kind/task
