### ISSUE TITLE
Failed to run scheduled task ClearExpiredEvents

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#14476] opened 2022-09-19 06:50 UTC
### Describe the bug

```console
16:56:21,699 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Failed to run scheduled task ClearExpiredEvents: java.lang.IllegalAccessError: class org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 tried to access protected field org.keycloak.services.scheduled.ScheduledTaskRunner.task (org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 is in unnamed module of loader 'org.keycloak.keycloak-model-legacy-private@19.0.2' @11f2954b; org.keycloak.services.scheduled.ScheduledTaskRunner is in unnamed module of loader 'org.keycloak.keycloak-server-spi-private@19.0.2' @45e7a76)
	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
	at org.keycloak.keycloak-model-infinispan@19.0.2//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
	at org.keycloak.keycloak-server-spi-private@19.0.2//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
	at org.keycloak.keycloak-services@19.0.2//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

```

### Version

quay.io/keycloak/keycloak:19.0.2-legacy

**Comment by davidpiendl** [comment] 2022-09-19 16:23
Sames issue here. Just updated from 19.0.1-legacy to 19.0.2-legacy. 

It seems that its not included in the 19.0.2 release as mentioned [here](https://github.com/keycloak/keycloak/issues/13396). Maybe in 19.0.3

**Comment by rmnijgh** [comment] 2022-09-21 09:14
Also having this issue with 19.0.2-legacy using mariadb.

**Comment by dpevzner** [comment] 2022-09-22 18:20
updated from 19.0.1-legacy to 19.0.2-legacy and seeing the same issue. In addition to the ClearExpiredEvents error, also getting a ClearExpiredClientInitialAccessTokens error as well
```
12:55:38,909 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Failed to run scheduled task ClearExpiredClientInitialAccessTokens: java.lang.IllegalAccessError: class org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 tried to access protected field org.keycloak.services.scheduled.ScheduledTaskRunner.task (org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 is in unnamed module of loader 'org.keycloak.keycloak-model-legacy-private@19.0.2' @47e62e68; org.keycloak.services.scheduled.ScheduledTaskRunner is in unnamed module of loader 'org.keycloak.keycloak-server-spi-private@19.0.2' @33ed5dbe)
	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
	at org.keycloak.keycloak-model-infinispan@19.0.2//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
	at org.keycloak.keycloak-server-spi-private@19.0.2//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
	at org.keycloak.keycloak-services@19.0.2//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
```

Seems that this warrants a 19.0.3 release.

**Comment by ahus1** [comment] 2022-09-26 11:05
As outlined in #13396, this is a duplicate. I'll track the back port in the other issue, and close this as a duplicate.

**Comment by hmlnarik** [comment] 2022-10-05 12:34
Duplicate of #13396

**Closed by hmlnarik** 2022-10-05 12:34 UTC
Labels: kind/bug, area/storage, status/triage
