### ISSUE TITLE
New GUI Identity Provider Mapper problems

### ISSUE THREAD

**Issue by mattiaspantzare** [keycloak/keycloak#13564] opened 2022-08-05 08:54 UTC
### Describe the bug

The new GUI can't display mappers for identity providers in some cases.

When I test on a new test installation it shows [object Object] where there should be text.

In a  upgraded system from keycloak 11 it can't show the mappings at all due to a json parse error (I do not have that error, the new GUI is now disabled there)

### Version

19.0.1

### How to Reproduce?

Use the new GUI

Add an OpenID Connect identity provider.

In the identity provider select the "Mappers" tab.

Click on "Add a mapper"

select mapper type "Claim to Role"

Set a name in the name field
Enter a text in the Claim field.
Enter a text in Claim Value

Press Save

Go back to the list of mappers, open the mapper that you created.

In the claim field it now shows "[object Object]" where it should be the text that you set.

**Comment by ssilvert** [comment] 2022-08-05 13:51
Thanks for reporting this, @mattiaspantzare.

I'm closing as a duplicate of https://github.com/keycloak/keycloak-admin-ui/issues/3048.

**Closed** 2022-08-05 13:52 UTC
Labels: kind/bug
