### ISSUE TITLE
Keycloak Authz Client 19.0.2 is not backward compatible with Keycloak 18 and earlier

### ISSUE THREAD

**Issue by sberyozkin** [keycloak/keycloak#14962] opened 2022-10-18 11:28 UTC
### Describe the bug

Hi everyone, we are seeing a few reports in Quarkus, most recently captured in https://github.com/quarkusio/quarkus/discussions/28649#discussioncomment-3900729, suggesting that using `quarkus-keycloak-authorization` depending on KC 19.0.2 libraries does not work if it is used against KC 18 or earlier.

### Version

18

### How to Reproduce?

Run Keycloak Authz Client 19.0.2 against Keycloak 18

**Comment by stianst** [comment] 2022-10-19 06:59
From the linked issue it seems it has something to do with authentication, I wouldn't have expected any changes, especially not breaking ones around that:

```
2022-10-18 06:50:14,785 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile prod): 
org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 
401 / Unauthorized / Response from server: {"error":"unauthorized_client","error_description":"Invalid client secret"}
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:95)
	at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
```

@mposolda @pedroigor Have we made any changes around how clients are authenticating recently?

**Comment by mposolda** [comment] 2022-10-19 09:37
@sberyozkin @stianst There are those changes, which might be related to fix the decoding of client-secret in case it contains special characters according to the specs:
https://github.com/keycloak/keycloak/pull/12486
https://github.com/keycloak/keycloak/pull/14179
You can see at the corresponding GH issues. The possibilities to avoid this might be:
- Use the latest version of KC server as well as authorization client (or backport both of them to use older version)
- Avoid using client secrets with special characters (Ideally use the secret generated by Keycloak server itself)

**Comment by sberyozkin** [comment] 2022-10-20 14:01
Hi, sorry for a delay, we have a user confirming that at least in their case it now works after moving from Quarkus 2.13.2 with Quarkus 2.13.3, though I definitely did not do anything related to this issue between these last 2 releases. 
@pedroigor sorry if it proves to be a false positive :-)

**Comment by vincejv** [comment] 2022-10-20 15:11
> after moving from Quarkus 2.13.2 with Quarkus 2.13.3

can confirm as well that this solved the issue... so something broke in Keycloak with 2.13.2..

**Comment by sberyozkin** [comment] 2022-10-20 16:05
The user has confirmed it still does not work...

**Comment by pedroigor** [comment] 2022-10-21 14:40
@mposolda I sent https://github.com/keycloak/keycloak/pull/15087. Looks like we did not update the authz client to use the new decoder/encoder.

**Comment by sberyozkin** [comment] 2022-10-21 16:08
We are actually OK as KC 19.0.2/19.0.3 are not in the 2.13.x stream. Still would be of some concern for the upcoming 2.14.x but less so...

**Comment by pedroigor** [comment] 2022-12-14 20:13
@sberyozkin Do you think we can close this one now we have fixed the broken code in authz?

**Comment by sberyozkin** [comment] 2023-02-01 12:03
Hey Pedro, looks like the problem is back with 20.0.3, I've asked the Quarkus user to comment here with more details, please review those comments and re-open if you feel it will be needed, cheers

**Comment by pedroigor** [comment] 2023-02-01 13:13
@sberyozkin Thanks. Re-opened.

**Comment by pedroigor** [comment] 2023-02-02 19:47
@fordsworth Thanks, I'm looking into it.

**Comment by pedroigor** [comment] 2023-02-06 19:26
@fordsworth Looks like the issue you are facing is unrelated to the authz client because the problem seems to be related to CORS. The mentioned library does not need/use CORS.

Would you mind creating an issue with more details about how to reproduce the issue?

**Comment by pedroigor** [comment] 2023-02-16 11:49
Please, re-open if you have more details about how to reproduce the issue.

**Closed by pedroigor** 2023-02-16 11:49 UTC
Labels: area/authorization-services, kind/bug
