### ISSUE TITLE
Add ability to refresh the users listing in the admin ui

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#26498] opened 2024-01-25 12:09 UTC
### Description

User should be able to reload the user list without navigating away from the user list page.

I suggest to add a "Refresh" Button to the page. When the user clicks on refresh, the admin ui should reload the user list, which would now include new users added in the meantime.

### Motivation

Currently the users list in the admin ui is only updated on page load. If new users were added in the backing store, users have to change the view or do a full page reload to see the new users.
![image](https://github.com/keycloak/keycloak/assets/314690/179d297f-e965-488f-8cf3-1f503ad0de9c)
Perhaps just adding a "Refresh" (or Icon) button would do the trick:
![image](https://github.com/keycloak/keycloak/assets/314690/632ab8d9-a47e-4d76-bc8d-0bce078451ba)

**Comment by jonkoops** [comment] 2024-01-25 17:05
Duplicate of #21771

**Closed by jonkoops** 2024-01-25 17:05 UTC
Labels: kind/enhancement, area/admin/ui, status/triage, team/ui
