### ISSUE TITLE
Handle user linking when an IDP with the same name already exists

### ISSUE THREAD

**Issue by ghost** [keycloak/keycloak#19489] opened 2023-04-03 10:16 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

Here is my configuration:

* Two realms: `realmA` and `realmB`.
* `realmA` have an IDP `idpA` which delegates to `realmB`.
* The `idpA` first login flow is the following:

  | Auth Type |     | Requirement |
  | --------- | --- | ----------- |
  | Review Profile |   | REQUIRED |
  | Create Unique User |   | REQUIRED |
  | -> | Create User If Unique | ALTERNATIVE |
  | -> | Automatically set existing user | ALTERNATIVE |

* I have a SPI which allow me to go to the registration page of `realmB` when calling `/realms/realmA/protocol/openid-connect/auth?gotoregistration=true`. This is an authenticator in the browser flow of `realmB` which redirect to the registration page when the query param `gotoregistration=true` is passed. The SPI works well.

Here is the scenario:

1. I call `/realms/realmA/protocol/openid-connect/auth?gotoregistration=true` so I am redirected to the registration page of `realmB`.
2. I fill the form to create my account. So the account is created in `realmB`, then in `realmA` (because of the first login flow for `idpA`).
3. I manually delete the user in `realmB`.
4. I call `/realms/realmA/protocol/openid-connect/auth?gotoregistration=true` so I am redirected to the registration page of `realmB`.
5. I fill the form to create my account. The account is created in `realmB`, but there is en error and the authentication fails.

I see in the Keycloak logs that the first login flow of `idpA` is successfuly terminated, and there is an error a few lines below:

```console
2023-04-03 09:05:42,473 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-14) could not execute statement [n/a]: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_40 ON PUBLIC.FEDERATED_IDENTITY(IDENTITY_PROVIDER, USER_ID) VALUES ( /* key:1 */ 'idpA', '5e0b5314-fdf5-4246-adb5-4235ba05a24a')"; SQL statement:
```

There is already an entry in the database for the combination of this IDP and this user identifier. If I manually unlink the IDP in the user in `realmA` before filling the registration form for the second time, I can confirm that there is no error.

### Version

21.0.2

### Expected behavior

I expect the authentication succeed and the IDP linking for the user is made.

### Actual behavior

I have an error in the browser. I have the following error in Keycloak logs:

```console
2023-04-03 09:05:42,473 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-14) could not execute statement [n/a]: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_40 ON PUBLIC.FEDERATED_IDENTITY(IDENTITY_PROVIDER, USER_ID) VALUES ( /* key:1 */ 'idpA', '5e0b5314-fdf5-4246-adb5-4235ba05a24a')"; SQL statement:
```

### How to Reproduce?

All steps are described in the description.

### Anything else?

I have this behavior with Keycloak 21.0.2 and 18.0.0.

**Comment by mposolda** [comment] 2023-05-24 10:14
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue, which I am not 100% sure as the used scenario is relatively complex involving custom providers). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by AntoineAtLeocare** [comment] 2023-05-24 12:40
> This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue, which I am not 100% sure as the used scenario is relatively complex involving custom providers). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

Thank you! I think we can try to reproduce this issue without the SPI, by calling `/realms/realmB/protocol/openid-connect/registration` then `/realms/realmA/protocol/openid-connect/auth` instead of `/realms/realmA/protocol/openid-connect/auth?gotoregistration=true`.

**Comment by pedroigor** [comment] 2024-03-04 21:03
This seems a duplicate of https://github.com/keycloak/keycloak/issues/26201. Please, let me know if you think otherwise.

**Closed by pedroigor** 2024-03-04 21:03 UTC
Labels: kind/bug, area/identity-brokering, team/core-iam
