### ISSUE TITLE
Trust Store hostname-verification-policy=ANY seems to be ignored

### ISSUE THREAD

**Issue by agross** [keycloak/keycloak#12018] opened 2022-05-16 15:56 UTC
### Describe the bug

I configured my CA's certificate according to https://www.keycloak.org/docs/latest/server_installation/#_truststore.

In docker, I mount my CA's cert using a docker volume and set X509_CA_BUNDLE to point to the cert file.

During the startup Keycloak creates its own truststore.jks file and changes standalone-ha.xml and standalone.xml accordingly. My goal, in addition to that, is to ignore any errors regarding the certificate names or SANs, because I have to work with an Active Directory  CA which is untrusted outside of itself and I cannot control the certificates themselves.

In order to achieve that I created a cli script that also sets hostname-verification-policy to ANY during startup.

This is the resulting XML:

```xml
<spi name="truststore">
    <provider name="file" enabled="true">
        <properties>
            <property name="file" value="/opt/jboss/keycloak/standalone/configuration/keystores/truststore.jks"/>
            <property name="password" value="C6ZJ+p3zj+7Bs6OzGNk1yN039CHoTOrV2P6YiBSDUG4="/>
            <property name="hostname-verification-policy" value="ANY"/>
            <property name="disabled" value="false"/>
        </properties>
    </provider>
</spi>
```

Unfortunately, that does not work at all:

```
10:18:23,822 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager] (default task-4) Creating LdapContext using properties: [{java.naming.security.authentication=simple, java.naming.security.principal=CN=Kessler,CN=Users,DC=wghoch4,DC=local, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.ldap.factory.socket=org.keycloak.truststore.SSLSocketFactory, java.naming.security.credentials=**************************************, java.naming.provider.url=ldaps://arwen.home.therightstuff.de:636}]
10:18:23,827 ERROR [org.keycloak.services] (default task-4) KC-SERVICES0055: Error when authenticating to LDAP: simple bind failed: arwen.home.therightstuff.de:636: javax.naming.CommunicationException: simple bind failed: arwen.home.therightstuff.de:636 [Root exception is javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching arwen.home.therightstuff.de found.]
```

### Version

15.0.2

**Comment by hmlnarik** [comment] 2023-03-06 13:48
Possibly duplicate of #9313

**Comment by hmlnarik** [comment] 2023-05-22 10:55
Confirmed, hostname is not verified the same way for LDAPS as it is for HTTPS during connections. The way to ignore hostname check for `ldaps` protocol by setting `com.sun.jndi.ldap.object.disableEndpointIdentification` system property to `true` upon server start. Beware that this is server-wide settings, and is a security weakening; for that reason prefer using properly configured certificates with correctly specified address e.g. using certificate SAN field.

Sadly. that this does not work correctly for StartTLS LDAP command which seems a to-be-confirmed gap in JDK's ability to respect `com.sun.jndi.ldap.object.disableEndpointIdentification` settings. This particular issue will be fixed by updating documentation, since truststore use is set per LDAP server configuration, so it cannot be switched on automatically according to hostname verification policy in truststore configuration which is server-wide.

Related to #9313: This only stresses the need to removing the "Only for ldaps" option in LDAP `Use Truststore SPI` configuration, since it is confusing when the same truststore works for LDAPS and does not for StartTLS.

**Closed** 2023-06-20 05:47 UTC
Labels: kind/bug, impact/low, area/docs, area/ldap, team/store, team/other
