### ISSUE TITLE
Missing client name translation in Account console's application page

### ISSUE THREAD

**Issue by boomer41** [keycloak/keycloak#33137] opened 2024-09-20 09:15 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

As you can see, we use a translation key in the client's name to translate it. However, the translation is not actually happening:

https://[domain]/realms/[realm]/account/applications:

![img](https://github.com/user-attachments/assets/ead8c9c9-9e0e-4690-9e10-259c8a7fa833)

The reason seems to be that in https://github.com/keycloak/keycloak/blob/fa08cef8ef2a9a859ed96aa86fdb68acc8e01872/js/apps/account-ui/src/applications/Applications.tsx#L145 the translation call is missing.

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Translation is happening

### Actual behavior

Translation is not happening

### How to Reproduce?

Create a client with a translated name and observe the result in the account UI's applications page

**Comment by ssilvert** [comment] 2024-09-20 13:32
@boomer41 From your image, we can see that some of the translation is happening as "Account Console" and "security admin console" have been translated to German.

How are you providing the translation for `clientanfrageplatform`?  Are you using a realm override?

**Comment by boomer41** [comment] 2024-09-20 13:34
Yes, we are using realm overrides.
The key has been set for the default locale and all other locales.
The key has been set in the customer's realm and in the master realm, too.

![grafik](https://github.com/user-attachments/assets/f4017c25-b17c-497a-933c-e1c5539d3efe)

**Comment by ssilvert** [comment] 2024-09-20 18:04
Thanks.  That's what I figured.  So looks like this is a duplicate of #32984.

There is a PR for that one already.

**Closed by ssilvert** 2024-09-20 18:04 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui

**Comment by jonkoops** [comment] 2024-09-20 21:39
Duplicate of #32984
