### ISSUE TITLE
MySQL database empty when using start-dev with the docker container

### ISSUE THREAD

**Issue by bogdanr** [keycloak/keycloak#10959] opened 2022-03-28 08:16 UTC
### Describe the bug

Hello,

My keycloak instance didn't write anything in the database when I used the start-dev parameter.
I am using this because I wanted to avoid having SSL in keycloack as I have an ELB with SSL in front of it.

I know for sure that the instance tried to connect to the DB as it didn't want to start when I had some incorrect credentials for MySQL. But I was very disappointed when I wanted to restore some data from the database because there was nothing written there.

When I finally configured SSL also and started with the start parameter it also started to write to the database.

### Version

16.1.1

### Expected behavior

Write all the configuration to the MySQL database

### Actual behavior

Nothing was written in the database

### How to Reproduce?

start the server with mysql and start-dev

**Comment by DGuhr** [comment] 2022-03-29 08:27
Hey @bogdanr it would really help if you could give us more info on "how to reproduce", describing the environment and the exact commands you used (for sure without credentials or sth). Also an exception, if any, would be good to see.

For now I can confirm that this is no general error. I just started kc 16.1.1 and a mysql docker environment using this docker compose:

```
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak-x:16.1.1
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=mysql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak-secret
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak-secret
      - MYSQL_ROOT_PASSWORD=supersecret
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
```

The result you can see in the screenshot. KC is running and the mysql database got inited correctly and is used. Also a client I created earlier survives docker compose down / up (expected, as the volume is there).
 
![Screenshot 2022-03-29 at 10 21 31](https://user-images.githubusercontent.com/89905860/160567393-3e8330a2-ff40-403f-b891-b393d86d39ef.png) 

So at the moment this is not reproducible without further information.

**Comment by DGuhr** [comment] 2022-03-29 08:45
@bogdanr could you try building it using `-e KC_PROXY=edge` instead of the PROXY_ADDRESS_FORWARDING env variable? Also, you are adding environment dependant runtime config to your _build_, this is not allowed anymore from 17 on, but seems it still worked in 16.1.1 (just tried out locally) - I highly suggest not to do that, as build options get persisted, and so you are persisting passwords into the container. 

Your config looks right apart from that at first sight, though there's a typo in `--db-url-database=keycloack`, should be `--db-url-database=keycloak` i guess.

Also keep in mind keycloak-x is outdated now, as of keycloak 17 quarkus is the standard distribution and as such can be found here: https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest so maybe you want to change to 17.0.1 / keycloak:latest instead.

Also would be good to see what your configuration shows when you do a `docker exec -it a598 /bin/bash` and inside the container run `/opt/keycloak/bin/kc.sh show-config` for the success and error case, so you can check if the right URL etc is really picked up.

**Comment by DGuhr** [comment] 2022-05-02 07:26
Closing here for now, as the problem is not reproducible. Feel free to re-open and provide additional information when the suggested fixes don't work.

**Closed by DGuhr** 2022-05-02 07:26 UTC
Labels: kind/bug, area/dist/quarkus, status/triage

**Comment by ghadirinia** [comment] 2024-02-12 18:57
> Hey @bogdanr it would really help if you could give us more info on "how to reproduce", describing the environment and the exact commands you used (for sure without credentials or sth). Also an exception, if any, would be good to see.
> 
> For now I can confirm that this is no general error. I just started kc 16.1.1 and a mysql docker environment using this docker compose:
> 
> ```
> services:
>   keycloak:
>     container_name: keycloak
>     image: quay.io/keycloak/keycloak-x:16.1.1
>     command: ["start-dev"]
>     environment:
>       - KEYCLOAK_ADMIN=admin
>       - KEYCLOAK_ADMIN_PASSWORD=admin
>       - KC_DB=mysql
>       - KC_DB_URL_HOST=mysql
>       - KC_DB_URL_DATABASE=keycloak
>       - KC_DB_USERNAME=keycloak
>       - KC_DB_PASSWORD=keycloak-secret
>     ports:
>       - 8080:8080
>       - 8443:8443
>       - 9990:9990
>     depends_on:
>       - mysql
>   mysql:
>     image: mysql:latest
>     environment:
>       - MYSQL_DATABASE=keycloak
>       - MYSQL_USER=keycloak
>       - MYSQL_PASSWORD=keycloak-secret
>       - MYSQL_ROOT_PASSWORD=supersecret
>     ports:
>       - 3306:3306
>     volumes:
>       - mysql-volume:/var/lib/mysql
> volumes:
>   mysql-volume:
>     driver: local
> ```
> 
> The result you can see in the screenshot. KC is running and the mysql database got inited correctly and is used. Also a client I created earlier survives docker compose down / up (expected, as the volume is there).
> 
> ![Screenshot 2022-03-29 at 10 21 31](https://user-images.githubusercontent.com/89905860/160567393-3e8330a2-ff40-403f-b891-b393d86d39ef.png)
> 
> So at the moment this is not reproducible without further information. It _may_ be a misconfiguration of e.g. the ELB, the db connection (always pointing to a new instance without a shared volume) or similar, as generally it works as expected.
> 
> p.s.: you may want to try it out with the new 17.0.1, too ;)

Hi,
I use your configuration, both containers created without any problems, also the logs are same as yours in the picture.
but nothing in mysql database is empty!


I didn't use kubernetese...I just try to run the docker compose file.


also, I tried the latest and the version you mentioned.
