### ISSUE TITLE
Unable to disable client through Rest Api

### ISSUE THREAD

**Issue by MudaleSrikanth** [keycloak/keycloak#22545] opened 2023-08-18 12:12 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

I tried to set the enabled property of a client to false(disable) and called update api. It still shows as enabled.
I do have rights to perform this operation since I am able to delete client as well.

### Version

22.0.1

### Expected behavior

On disabling client by setting client's enabled proeprty to false, it must get set as false after calling update.

### Actual behavior

It still shows enabled property of client as true.

### How to Reproduce?

Try to change the client's enabled property to false and call update Api (http PUT with ClientRepresation as body)

**Comment by kaustubh-rh** [comment] 2023-09-02 14:00
Hi @MudaleSrikanth , I am unable to reproduce the issue , can you share the exact steps to reproduce the same ?

**Comment by rmartinc** [comment] 2023-09-25 14:35
Hi @MudaleSrikanth !

I'm going to close this issue. I cannot reproduce this, if I set the `enabled` to `true` or `false` the client is enabled or disabled correctly. This is what the console is also doing to enable or disable a client.

If you want to test it, you can use the `kcadm` too:

```
./kcadm.sh update clients/2d8f7114-aa88-421f-8e2c-c8c5c4d39fee -s enabled=false
./kcadm.sh get clients/2d8f7114-aa88-421f-8e2c-c8c5c4d39fee | jq ".enabled"
false
./kcadm.sh update clients/2d8f7114-aa88-421f-8e2c-c8c5c4d39fee -s enabled=true
./kcadm.sh get clients/2d8f7114-aa88-421f-8e2c-c8c5c4d39fee | jq ".enabled"
true
```

If you see something different please re-open the case of file a new one.

**Closed by rmartinc** 2023-09-25 14:35 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core

**Comment by MudaleSrikanth** [comment] 2023-09-26 10:41
I am unable to do it using Rest Api. I have passed enabled proeprty as false still after calling update Rest Api, it shows as true.
Can you please share working rest Api command for this update?

**Comment by rmartinc** [comment] 2023-09-26 11:19
@MudaleSrikanth You can always check what the console is doing. So, in order to see a disable example, you can go to the console. Select a client and click in the Enable/Disable toggle. If you open the web developers tools of the browser you will see the exact HTTP the console is using.

If have done this quick and dirty bash script (the client-id is hardcoded):

```bash
#!/bin/bash

URL="localhost:8080"
USER="admin"
USER_PWD="XXXXXX"

TKN=$(curl -sX POST "http://${URL}/realms/master/protocol/openid-connect/token" \
 -H "Content-Type: application/x-www-form-urlencoded" \
 -d "username=${USER}" \
 -d "password=${USER_PWD}" \
 -d 'grant_type=password' \
 -d 'client_id=admin-cli' | jq -r '.access_token')

# get the client
CLIENT=$(curl "http://${URL}/admin/realms/master/clients/2d8f7114-aa88-421f-8e2c-c8c5c4d39fee" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json;charset=utf-8" \
 -H "Authorization: Bearer $TKN")

# change enable to false
CLIENT=$(echo "$CLIENT" | jq '.enabled = false')

# update the client
curl -X PUT "http://${URL}/admin/realms/master/clients/2d8f7114-aa88-421f-8e2c-c8c5c4d39fee" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json;charset=utf-8" \
 -H "Authorization: Bearer $TKN" \
 -d "$CLIENT"
```
