### ISSUE TITLE
New Theme user overview pagination issue

### ISSUE THREAD

**Issue by elronzo** [keycloak/keycloak#16725] opened 2023-01-31 09:16 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

In a certain group we do have 15 users. When the pagination is set to 10, one of the users appears twice whereas anotherone is not shown at all. If I switch back to the old theme temporarily, every user is shown as expected.

### Version

20.0.3

### Expected behavior

All users should be shown. No matter which pagination size is set.

### Actual behavior

Pagination size causes users to be shown incorrectly in new KC theme.

### How to Reproduce?

Take a group with 15 users, for example and set pagination to 10.  Some users will be shown twice whereas others are missing. (Ensure you are using the new KC UI -> Choose a Realm -> Groups -> Choose a group -> Members)

**Comment by jonkoops** [comment] 2023-01-31 12:25
This sounds like a UI issue rather than an issue with the Account API. @elronzo which UI are you talking about here? Please provide some more detailed steps on how to reproduce this issue.

**Comment by edewit** [comment] 2023-05-10 06:50
I can't reproduce this can you try the latest version?

**Comment by ssilvert** [comment] 2023-05-10 18:49
We've fixed a lot of bugs in this area.  Since we can't reproduce, I'm going to close this issue.  It can be reopened later if needed.

**Closed by ssilvert** 2023-05-10 18:49 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
