### ISSUE TITLE
Not able to retrieve only local users and after configuring user federation (LDAP) on keycloak 22 and above

### ISSUE THREAD

**Issue by demonappolyon** [keycloak/keycloak#28343] opened 2024-04-02 07:39 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

We were using keycloak 21 and it had multiple user federation added and then we migrated from keycloak 21 to keycloak 22 and even tried keycloak 23. After migration it was noticed that we were not able to access local user of keycloak which were accessible earlier without sending query out to ldap servers and it was even trying to pull in the internal user of ldap server and at times causing bad request response as these internal ldap user don't have userPrincipalName assigned by default.
Earlier queries were sent back to ldap only if  search had * or any specific ldap username mentioned and otherwise only local users were returned. 
It even impacts on the performance as if we have multiple ldap servers configured then it might pull 1000s of user at once and then filtering out only local users will be chaotic.

### Version

keycloak 23.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Get user api without filter field should return only local-users and when search field with * or or any specific ldap username send queries out to ldap server
Earlier after adding ldap server if we used to trigger GET https://{IP}/auth/admin/realms/{realm}/users only local users were shown.

### Actual behavior

On Get user api we are getting all the local users along with the ldap users belonging to all the ldap servers configured over the keycloak.

### How to Reproduce?

Add local user to keycloak. You will be able to see them from user tab.
and trigger GET https://{IP}/auth/admin/realms/{realm}/users
Add ldap server then re visit the user tab from ui it will be showing no users over there.
on triggering following api https://{IP}/auth/admin/realms/{realm}/users it tries to pull in local user along with all the ldap user

**Comment by vramik** [comment] 2024-04-02 08:27
Thank you @demonappolyon for the report, it seems it is duplicate of #21465.

**Closed by vramik** 2024-04-02 08:27 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core-shared
