### ISSUE TITLE
`/admin/realms/{realm-name}/ui-ext/realms` endpoint leaks realms the user doesn't have access to see

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#25679] opened 2023-12-18 17:53 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The `/admin/realms/{realm-name}/ui-ext/realms` endpoint shows realms the user doesn't have access to.

### Version

23.0.3

### Expected behavior

This endpoint should only show the user realms they have access/permission to see.

### Actual behavior

It appears to permit an admin (i.e. all `realm-management` roles) for a specific realm the permission to see all realms.

### How to Reproduce?

Setup:
1. Run Keycloak 23.0.3 in `start-dev` mode.
2. Navigate to the Admin UI and log into the master realm as the default admin user
3. Create `test1` realm and `test2` realm.
4. Create an `admin` user in each `test1` and `test2` realm, and create a password.
5. Grant those new admin users all `realm-management` roles in their respective realms
![Screenshot from 2023-12-18 18-44-04](https://github.com/keycloak/keycloak/assets/244253/8d3f38b5-7bb9-4599-9277-3f0f2212e030)

Reproduce
1. Logout of any sessions for Keycloak
2. Go to the admin console for the new realm you created (e.g. `http://localhost:8080/admin/test1/console`)
3. Log in as the new admin user you created.
4. Click the realms dropdown and see all realms
5. Use the browser devtools to see all the realms returned from the endpoint
![Screenshot from 2023-12-18 18-44-56](https://github.com/keycloak/keycloak/assets/244253/5ab840db-c610-42f3-b6b6-9e6453264a58)
![Screenshot from 2023-12-18 18-45-08](https://github.com/keycloak/keycloak/assets/244253/30c30741-2476-48ae-ad82-ff5ebfcbac0a)

### Anything else?

I didn't send this to the security email, because it only pertains to this UI endpoint, and there is no actual CRUD activity you can do on entities.

Also tried on nightly with the same result.

**Comment by xgp** [comment] 2023-12-18 21:02
There is no permission checking:
https://github.com/keycloak/keycloak/blob/main/rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmsResource.java#L49

There should be something like this:
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java#L117

**Comment by xgp** [comment] 2023-12-18 21:35
PR https://github.com/keycloak/keycloak/pull/25683

**Comment by antikalk** [comment] 2023-12-20 14:49
Possible duplicate of: https://github.com/keycloak/keycloak/issues/25392

**Closed** 2024-01-02 10:46 UTC
Labels: kind/bug, priority/important, area/admin/ui, team/ui
