### ISSUE TITLE
Importing a previously exported realm doesn't work

### ISSUE THREAD

**Issue by nicolasduminil** [keycloak/keycloak#24465] opened 2023-11-01 14:26 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

import-export

### Describe the bug

Using `quay.io/keycloak/keycloak:21.1.1` image. I created a new realm and I exported it. Restarting the container and importing the export file, the new created realm doesn't appear in the admin console. However, trying to create the realm in console raises exception: `Could not create realm Conflict detected. See logs for details` and the log file shows `JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation`. 
So the realm exists and doesn't exist in the same time.

### Version

21.1.1

### Expected behavior

Importing a previously exported realm should succeed and it should appear in the admin console. 

### Actual behavior

Importing the previously exported realm doesn't raise any exception, so it succeeds, but the new realm doesn't appear in the admin console. The realm exists however because, trying to add it manually, in the admin console, fails indicating that the realm already exists.

### How to Reproduce?

1. Run the docker image:
      `docker run --name mykeycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin  quay.io/keycloak/keycloak:21.1.1 start-dev`
2. Create a new realm
    `$kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password admin`
    `$kcadm.sh create realms -s realm=myrealm -s enabled=true`
3. Export the new realm
    `kc.sh export --file /opt/keycloak/data/myrealm.json --realm myrealm`
4. Copy the file `/opt/keycloak/data/myrealm.json` from the container to the host
5. Stop the `mykeycloak` container
6. Restart the `mykeycloak` container
7. Copy the file `/opt/keycloak/data/myrealm.json` from the host to the container
8. Import the new realm
    `kc.sh import --file /opt/keycloak/data/myrealm.json`
9. Open the admin console and confirm that there is no `myrealm` realm.
10. Try to add a new realm named `myrealm`. Confirm that it fails.
11. Confirm that the log file shows an unique constraint violation exception.

**Comment by nicolasduminil** [comment] 2023-11-01 14:45
Here is the output further to the import operation:

    bash-5.1$ /opt/keycloak/bin/kc.sh import --file /opt/keycloak/data/myrealm.json
    2023-11-01 14:37:21,881 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
    2023-11-01 14:37:22,943 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
    2023-11-01 14:37:23,362 INFO  [org.infinispan.SERVER] (keycloak-cache-init) ISPN005054: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
    2023-11-01 14:37:23,378 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
    2023-11-01 14:37:23,436 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
    2023-11-01 14:37:23,470 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
    2023-11-01 14:37:24,016 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_989682, Site name: null
    2023-11-01 14:37:24,022 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
    2023-11-01 14:37:24,589 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /opt/keycloak/data/myrealm.json
    2023-11-01 14:37:25,937 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'myrealm' imported
    2023-11-01 14:37:26,006 INFO  [io.quarkus] (main) Keycloak 21.1.1 on JVM (powered by Quarkus 2.13.7.Final) started in 5.047s. 
    2023-11-01 14:37:26,006 INFO  [io.quarkus] (main) Profile import_export activated. 
    2023-11-01 14:37:26,006 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, vertx]
    2023-11-01 14:37:26,145 INFO  [io.quarkus] (main) Keycloak stopped in 0.136s

Trying to add the realm in console displays the following stack trace in the log file:

    2023-11-01 14:42:44,571 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-7) SQL Error: 23505, SQLState: 23505
    2023-11-01 14:42:44,571 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-7) Unique index or primary key violation: "PUBLIC.UK_ORVSDMLA56612EAEFIQ6WL5OI_INDEX_6 ON PUBLIC.REALM(NAME NULLS FIRST) VALUES ( /* 2 */ 'myrealm' )"; SQL statement:
    insert into REALM (ACCESS_CODE_LIFESPAN, LOGIN_LIFESPAN, USER_ACTION_LIFESPAN, ACCESS_TOKEN_LIFESPAN, ACCESS_TOKEN_LIFE_IMPLICIT, ACCOUNT_THEME, ADMIN_EVENTS_DETAILS_ENABLED, ADMIN_EVENTS_ENABLED, ADMIN_THEME, ALLOW_USER_MANAGED_ACCESS, BROWSER_FLOW, CLIENT_AUTH_FLOW, DEFAULT_LOCALE, DEFAULT_ROLE, DIRECT_GRANT_FLOW, DOCKER_AUTH_FLOW, DUPLICATE_EMAILS_ALLOWED, EDIT_USERNAME_ALLOWED, EMAIL_THEME, ENABLED, EVENTS_ENABLED, EVENTS_EXPIRATION, INTERNATIONALIZATION_ENABLED, LOGIN_THEME, LOGIN_WITH_EMAIL_ALLOWED, MASTER_ADMIN_CLIENT, NAME, NOT_BEFORE, OFFLINE_SESSION_IDLE_TIMEOUT, OTP_POLICY_ALG, OTP_POLICY_DIGITS, OTP_POLICY_COUNTER, OTP_POLICY_WINDOW, OTP_POLICY_PERIOD, OTP_POLICY_TYPE, PASSWORD_POLICY, REFRESH_TOKEN_MAX_REUSE, REGISTRATION_ALLOWED, REG_EMAIL_AS_USERNAME, REGISTRATION_FLOW, REMEMBER_ME, RESET_CREDENTIALS_FLOW, RESET_PASSWORD_ALLOWED, REVOKE_REFRESH_TOKEN, SSL_REQUIRED, SSO_IDLE_TIMEOUT, SSO_IDLE_TIMEOUT_REMEMBER_ME, SSO_MAX_LIFESPAN, SSO_MAX_LIFESPAN_REMEMBER_ME, VERIFY_EMAIL, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]
    2023-11-01 14:42:44,571 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (executor-thread-7) HHH000010: On release of batch it still contained JDBC statements
    2023-11-01 14:42:44,573 ERROR [org.keycloak.services.resources.admin.RealmsAdminResource] (executor-thread-7) Conflict detected: org.keycloak.models.ModelDuplicateException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement

I'm attaching the JSON file to be imported: 
[myrealm.json](https://github.com/keycloak/keycloak/files/13228244/myrealm.json)

**Comment by nicolasduminil** [comment] 2023-11-03 12:02
Is anyone concerned here, please ?

**Comment by sschu** [comment] 2023-11-03 17:49
Have you tested this on the latest version?

**Comment by nicolasduminil** [comment] 2023-11-06 12:00
![Screenshot_20231106_125726](https://github.com/keycloak/keycloak/assets/1037978/765162f2-21f6-43e0-8365-a2d00df15925)

Why do you ask ? Do you think that it might work with the last one but not with 21.1.1 ? Meaning that they've waited the 21st release in order to fix such a basic issue ?

**Comment by sschu** [comment] 2023-11-07 13:29
If there is a bug, it will only be fixed on the current version. That's why it is important to know if it exists on the current version.

**Comment by sguilhen** [comment] 2023-11-08 17:46
I was able to reproduce this using the latest nightly even without running keycloak in a container. I've followed the steps as described, but before stopping keycloak in step 5 I've removed the realm "myrealm" using the console.

After the realm is imported, sometimes it is displayed along with the "master" realm in the drop-down menu, and sometimes it is not. But even when it is displayed, clicking on it leads to a page saying `Welcome to myrealm`, but none of the items in the side menu is displayed, so you can't really do anything with the realm. Re-starting keycloak one more time did the trick for me and I could work on the imported realm just fine.

I've tried with different databases, and the result was always the same: the imported realm can be seen in the database, but the console won't display it (or will display it but clicking on it leads to a page with no side menu) until Keycloak is re-started one more time.

@keycloak/ui Can you please take a look into this one? From a storage perspective the import is working but the imported realm is either not displayed or presents a page with no side menu until Keycloak is re-started.

**Comment by ssilvert** [comment] 2023-11-08 20:16
@sguilhen I don't believe this is a UI bug and it might not be a bug at all.  

I don't think we ever intended to allow an entire realm to be imported while the server is still running.  We have the `Partial Import` feature in the UI for those objects that can be imported at runtime.  

If you want to import an entire realm then you do it as you are starting the server and not in a separate process.  At least that has always been my understanding.

Either way, this can't be a UI issue.  We can only work with what the REST API provides.  In the example from @sguilhen, it appears that the user has not been set up with access to the new realm.  

The issue described by @nicolasduminil is slightly different in that the new realm is not shown in the realm list.   Again, the UI can only display what it is given from the server.  So if it's not in the list we get, we can't show it in the UI.

I'm going to re-assign to both team/store and team/core and see what they think.

**Comment by sguilhen** [comment] 2023-11-08 21:03
@ssilvert you might be right about it not being a bug at all. Reading the documentation on import/export, there's this line under the section "Importing a Realm from a Directory":
```
To import a realm, you can use the import command. Your Keycloak server instance must not be started when invoking this command.
```

The same phrasing, however, is not seen in the next section "Importing a Realm from a File", which can lead one to believe that it would be possible to do it in runtime.

I can confirm that importing the realm during startup works fine, the realm is always visible in the admin console.

**Comment by nicolasduminil** [comment] 2023-11-10 18:04
@sguilhen I'm running the server as a pod in Openshift. Initially, I wanted to create the realm using kcadm.sh commands, for example:

    /opt/keycloak/bin/kcadm.sh create realms ...
    /opt/keycloak/bin/kcadm.sh create users ...
    ...

These commands are in a script executed via `oc exec ...`. But it doesn't work as, in order to execute these commands, the server tries to create the config file in a directory where the user doesn't have write access.

Then I thought to create the realm using the same script in a local running Keycloak instance, to export the realm once created, and to import the realm in the pod. Something like that:

    $ oc new-app -f keycloak-template.yaml ...                                        # deploy a Keycloak server instance as an Openshift pod
    $ keycloak_pod=$(oc get pods | grep keycloak | grep -wv -e deploy | awk '{print $1}')    # get the Keycloak pod name
    $ cat realm-export.json | oc exec -i $keycloak_pod -- sh -c "cat > /opt/keycloak/data/realm-export.json"  # copy the realm file to the pod
    $ oc exec -i $keycloak_pod -- sh -c "/opt/keycloak/bin/kc.sh import"     # import the realm

Doing that and looking in the Keycloak admin console, there is no trace of the imported realm. Now, if you're saying that the server must not be running when I do the import, I'm confused. What could a Keycloak pod be running if not the Keyclaok server ?

I've also tried to import the realm at start-up, i.e. using something like:

    args: ["start-dev", "--import-realm"]

in the DeployConfig definition. But this didn't work neither. There is no exception, just the imported realm doesn't apear in the console.

What could I do in this case ?

Many thanks in advance for your help.

Kind regards,

Nicolas

**Comment by ahus1** [comment] 2023-11-16 16:06
Hi @nicolasduminil,

in your setup you seem to run with an embedded database H2 (the default if you don't specify a database). When you start the pod (or the container), there is one process that creates the H2 database file. 

If you then run Keycloak again (concurrently) to import the realm, another process accesses the H2 files, [which is not supported](https://www.h2database.com/html/advanced.html):

> a database file can only be open for reading and writing (in embedded mode) by one process at the same time.  

What you can do instead: 

* Use an external database (not an embedded H2) 
* Pass the realm to import as a parameter to the start command (`bin/kc.[sh|bat] start --import-realm`) - see https://www.keycloak.org/server/importExport. This will use a single process to first import the realm, and then start Keycloak
* Use `kcadm.sh` and pass the `--config` parameter to point it to a file in a folder that is writable, for example the `/tmp` folder

**Comment by nicolasduminil** [comment] 2023-11-28 13:04
@ahus1 Replying far behind to your comments.

- use an external DB: not an option;
- using `args: ["start-dev", "--import-realm"]` as a start command: if you've read my previous update, and you did since you're replying to it, you've certainly seen that I've reported having tried that, but unsuccessfully. Not sure why the operation is failing since there is no any exception. Please see my detailed description above.
- Using the `--config` option: not sure how is it supposed to help but will try.

Many thanks anyway for your concerns.

Kind regards,

Nicolas

**Comment by sguilhen** [comment] 2023-12-08 12:56
@nicolasduminil What I did when testing the import on startup was add the `--import-realm` option when running the container in step 1. Then I followed the steps to create a realm, export it, delete from the server, and then re-start the container and the realm was available in the console. The only difference was that I put the exported JSON in the `/opt/keycloak/data/import` directory as that is the place Keycloak uses when looking for realms to import.

Relevant container logs:

 ```
 2023-12-08 12:31:52,610 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /opt/keycloak/bin/../data/import/myrealm.json
2023-12-08 12:31:53,891 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'myrealm' imported
2023-12-08 12:31:53,931 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory /opt/keycloak/bin/../data/import
2023-12-08 12:31:53,931 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: IGNORE_EXISTING
2023-12-08 12:31:53,932 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully
```

Importing during server startup will ignore any realms that already exist, as pointed by the strategy in the logs.

**Closed** 2024-02-22 13:48 UTC
Labels: kind/bug, area/import-export, status/triage, team/core-clients
