### ISSUE TITLE
The set value ‘Default Admin-Initiated Action Lifespan’ has no effect on the ‘Credential Reset’ form

### ISSUE THREAD

**Issue by bjrnptrsn** [keycloak/keycloak#32547] opened 2024-08-31 17:40 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Even after override the value 'Default Admin-Initiated Action Lifespan' under 'Realm settings/Tokens', '12 Hours' is always preset in the form for the manual sending of a 'Credential Reset' mail.

This is probably caused by function **getActionTokenGeneratedByAdminLifespan()**, as a fixed value is always returned here:
https://github.com/keycloak/keycloak/blob/f2ff485b7fb96b6ea3ed598a6a3abff0f4b7bdda/model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java#L611

However, the new lifespan value is used correctly when an email is initiated via the API.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Admin initiated actions form should use the override lifespan value.

### Actual behavior

Admin initiated actions form always set lifespan to 12 hours as default.

### How to Reproduce?

- Set 'Default Admin-Initiated Action Lifespan' at 'Realm settings / Tokens' to any value other than 12 hours
- Go to 'Users details / Credentials' for any user
- Click on 'Credentials Reset'

### Anything else?

Override value is correctly used by initiate an email via the API

PUT /admin/realms/{realm}/users/{id}/execute-actions-email

**Comment by ssilvert** [comment] 2024-09-03 19:39
I have verified the bug.  I believe the problem is actually here:
https://github.com/keycloak/keycloak/blob/d21327445d4b701295b0d23c4fb97060139261cc/js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx#L24

The lifespan is hard-coded to 12 hours instead of looking to find if a default has been set in `Realm settings --> Tokens` as described above.

Setting to priority normal as user can still set this to any value in the dialog.

**Comment by thomasdarimont** [comment] 2024-09-05 00:08
I think I have a fix for this, with the change from #32671 the value from the tokens page is correctly transferred to the ResetCredentialsDialog.

**Comment by steinheber** [comment] 2024-09-12 08:26
The **Default Admin-Initiated Action Lifespan** value only kicks in if the `lifespan` parameter is not set in the endpoint `/{realm}/users/{id}/execute-actions-email`. The parameter however is hardcoded to 12hrs as @thomasdarimont points out.

**Closed** 2024-09-16 09:45 UTC
Labels: kind/bug, area/admin/ui, help wanted, team/ui, status/auto-expire, status/auto-bump, priority/normal
