### ISSUE TITLE
Unexpected server error when trying to delete client

### ISSUE THREAD

**Issue by sidguptajhs** [keycloak/keycloak#11619] opened 2022-04-23 03:45 UTC
### Describe the bug

I'm trying to delete a client from one of my realms. It fails with an error `Error! An unexpected server error has occurred`

I checked the logs. The exception is :

```
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "resource_server_scope" violates foreign key constraint "fk_frsrps213xcx4wnkog82ssrfy" on table "resource_scope"
--
  | 2022-04-23T09:10:56.511+05:30 | Detail: Key (id)=(847130fb-e150-4778-9d50-95da0ba6f047) is still referenced from table "resource_scope".
```

### Version

17

### Expected behavior

The client should be deleted and any dependent resources should be realigned.

### Actual behavior

Unhandled Exception.

**Comment by vramik** [comment] 2022-10-07 17:59
@sidguptajhs could you please check whether it still fails with the latest version? Also it'd be good to have steps how to reproduce the issue. It's not clear to me from the description. Thank you

**Comment by vramik** [comment] 2022-10-12 09:21
Due to lack of information we are not able to triage this issue effectively. Due to this we are closing the issue, but feel free to reopen the issue when you are able to provide more information and steps to reproduce the issue.

**Closed by vramik** 2022-10-12 09:21 UTC
Labels: kind/bug, area/storage, status/triage
