### ISSUE TITLE
ClientScope is not being updated in existing realm with partial import in keycloak 21.1.1

### ISSUE THREAD

**Issue by Roma110** [keycloak/keycloak#20962] opened 2023-06-13 11:06 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

In keycloak (21.1.1), when we are trying to do Partial import of sample json then ClientScope is not being updated and also we have checked previous version of keycloak (19.0.3) in that also with Partial Import  ClientScope is not being updated.

**Trying below steps:**
There is an existing realm 'smp' already in keycloak
Click on 'smp' relam settings -> Partial Import
Select a json which has ClientScope details [Clientscope.txt](https://github.com/keycloak/keycloak/files/11734035/Clientscope.txt)
Click on upload

**Observation**:
ClientScope is not getting updated with partial import.
However, with new adding realm along with ClientScope is getting updated.

### Version

21.1.1

### Expected behavior

ClientScope should be updated in case of Partial Import when realm is already exist.

### Actual behavior

ClientScope is not getting updated in case of Partial Import when realm is already exist.

### How to Reproduce?

**Try below steps:**
Click on create realm (Example smp)
Click on 'smp' relam settings -> Partial Import
Select a json which has ClientScope details [Clientscope.txt](https://github.com/keycloak/keycloak/files/11734035/Clientscope.txt)
Click on upload
Go to Client scope and check the client scope which is not getting updated with Partial Import.

**Comment by carlin-q-scott** [comment] 2023-07-18 17:08
duplicate of #16289

**Comment by vramik** [comment] 2023-07-18 17:52
Thanks @carlin-q-scott for the info, closing as duplicate.

**Closed by vramik** 2023-07-18 17:52 UTC
Labels: kind/bug, area/import-export, team/store, status/triage
