### ISSUE TITLE
Role Name with slash

### ISSUE THREAD

**Issue by ballj** [keycloak/keycloak#20505] opened 2023-05-22 17:47 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When using a slash in the roll name under a SAML client (not tested others), it semi creates the role but throws the following error:
```
Could not create the role: t is null
Role created
```

### Version

21.1.0

### Expected behavior

The role is created and functions normally.
When browsing to the role the users displays correctly.

### Actual behavior

When clicking on the role after it has been created (with the error):
- Attibutes display correctly
- Users in role:
```
Network response was not OK.
Press here to refresh and continue
```

Followed by a reload of the admin UI.

### How to Reproduce?

1. Create SAML client.
2. Create role with a `/` in the name of the role

**Comment by jonkoops** [comment] 2023-05-23 15:19
Duplicate of #17590

**Closed by jonkoops** 2023-05-23 15:19 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
