### ISSUE TITLE
Broken link on website 

### ISSUE THREAD

**Issue by MGorsd** [keycloak/keycloak#10305] opened 2022-02-17 17:53 UTC
### Describe the bug

The "JavaDoc" link under the API Documentation header on the https://www.keycloak.org/documentation page takes me to a 404 Error page  

### Version

N/A

### Expected behavior

Take me to a list of the Javadocs 

### Actual behavior

takes me to error page 

### How to Reproduce?

Click the JavaDoc link under the API Documentation header 

### Anything else?

https://www.keycloak.org/documentation : Link containing the broken link 
https://www.keycloak.org/docs-api/17.0/javadocs/index.html Broken Link

**Comment by stianst** [comment] 2022-02-21 12:03
Duplicate of https://github.com/keycloak/keycloak/issues/9841

**Closed by stianst** 2022-02-21 12:03 UTC
Labels: kind/bug, status/triage
