### ISSUE TITLE
SSSD Federation fails with NPE after upgrade

### ISSUE THREAD

**Issue by hbsnmyj** [keycloak/keycloak#11728] opened 2022-04-28 06:58 UTC
### Describe the bug

After upgrading to 18.0, sssd federation fails due to NPE exception:

```
WARN  [org.keycloak.services] (executor-thread-4) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException
      at org.keycloak.federation.sssd.impl.PAMAuthenticator.authenticate(PAMAuthenticator.java:58)
      at org.keycloak.federation.sssd.SSSDFederationProvider.isValid(SSSDFederationProvider.java:180)
      at org.keycloak.credential.UserCredentialStoreManager.lambda$validate$4(UserCredentialStoreManager.java:164)
      at java.base/java.util.Collection.removeIf(Collection.java:544)
      at org.keycloak.credential.UserCredentialStoreManager.validate(UserCredentialStoreManager.java:164)
```

Downgrading back to 17.0.1 solves the issue, I wonder if I missed anything.

### Version

18.0.0

**Comment by mposolda** [comment] 2022-11-25 08:39
@hbsnmyj We did some refactoring in the corresponding part of the codebase. Are you please able to doublecheck the behaviour with latest released Keycloak 20.0.1 and comment here if the bug is still valid?

If it is still valid, can you please send the new stacktrace, which you can see in 20.0.1 version?

**Comment by hbsnmyj** [comment] 2022-11-28 07:36
Thanks, Marek! I am still seeing the error, the stack trace (20.0.1) is as follows:

```
Nov 28 07:31:53 hostname kc.sh[2844]: 2022-11-28 07:31:53,313 WARN  [org.keycloak.services] (executor-thread-2) KC-SERVICES0013: Failed authentication: java.lang.NullPointerE>
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.federation.sssd.impl.PAMAuthenticator.authenticate(PAMAuthenticator.java:58)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.federation.sssd.SSSDFederationProvider.isValid(SSSDFederationProvider.java:181)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.credential.LegacyUserCredentialManager.lambda$validate$11(LegacyUserCredentialManager.java:255)
Nov 28 07:31:53 hostname kc.sh[2844]:         at java.base/java.util.Collection.removeIf(Collection.java:576)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.credential.LegacyUserCredentialManager.validate(LegacyUserCredentialManager.java:255)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.credential.LegacyUserCredentialManager.isValid(LegacyUserCredentialManager.java:71)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.models.SubjectCredentialManager.isValid(SubjectCredentialManager.java:45)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validatePassword(AbstractUsernameFormAut>
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validateUserAndPassword(AbstractUsername>
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.validateForm(UsernamePasswordForm.java:55)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.action(UsernamePasswordForm.java:48)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:155)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:977)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:311)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:282)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:274)
Nov 28 07:31:53 hostname kc.sh[2844]:         at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:339)
Nov 28 07:31:53 hostname kc.sh[2844]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Nov 28 07:31:53 hostname kc.sh[2844]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Nov 28 07:31:53 hostname kc.sh[2844]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by mposolda** [comment] 2022-12-06 10:57
@hbsnmyj Thanks. Scheduling to Keycloak 22 for now. We may postpone if there is no time. The contribution for fixing this can be nice as I don't know if Keycloak team has time to fix this (even if it can be good).

**Comment by mposolda** [comment] 2022-12-06 10:57
@abstractj FYI. Do you have any idea about this?

**Comment by abstractj** [comment] 2022-12-06 20:39
@mposolda the Stack trace does not tell too much about it. @hbsnmyj could you please run the commands below and share the outcome?

```
sudo dbus-send --print-reply --system --dest=org.freedesktop.sssd.infopipe /org/freedesktop/sssd/infopipe org.freedesktop.sssd.infopipe.GetUserGroups string:some-username-here
```

```
sudo sssctl user-checks admin -s keycloak
```

**Comment by hbsnmyj** [comment] 2022-12-12 05:12
Thanks @mposolda and @abstractj ! The command output is as follows:

```
$ sudo dbus-send --print-reply --system --dest=org.freedesktop.sssd.infopipe /org/freedesktop/sssd/infopipe org.freedesktop.sssd.infopipe.GetUserGroups string:snmyj
method return time=1670821439.757560 sender=:1.1 -> destination=:1.73 serial=58 reply_serial=2
   array [
      string "ipausers"
      string "admins"
      string "ipausers"
      string "login-users"
      ...
      string "audio"
   ]
```
```
$ sudo sssctl user-checks admin -s keycloak
user: admin
action: acct
service: keycloak

SSSD nss user lookup result:
 - user name: admin
 - user id: 1948000000
 - group id: 1948000000
 - gecos: Administrator
 - home directory: /home/admin
 - shell: /bin/bash

SSSD InfoPipe user lookup result:
 - name: admin
 - uidNumber: 1948000000
 - gidNumber: 1948000000
 - gecos: Administrator
 - homeDirectory: /home/admin
 - loginShell: /bin/bash
 - sn: Administrator

testing pam_acct_mgmt

pam_acct_mgmt: Success

PAM Environment:
 - no env -
```
I also noticed a part of the stack trace was not pasted properly in my reply above:
Missing part is:  `Cannot invoke "org.jvnet.libpam.PAM.dispose()" because "pam" is null`

**Comment by clbouvier** [comment] 2022-12-15 09:23
I have a testbench where I can reproduce the problem.
I have tested with 1 IPA server and 1 keycloak version 20.0.2 instance on almalinux 9

The problem was the internal PAMlib4j project that the PAMAuthenticator is using for the authentication.
JNA was not loaded generating NPE.
I have added to the classpath in the kc.sh the localization of the jna.jar (/usr/lib/java in my case).

I have already the ipa enrollment done and the setup about sssd and pam for keycloak done.

 ```sudo sssctl user-checks my_user -a auth -s keycloak``` works without problem.
 
 Once keycloak run, a realm created (myrealm) and the sssd federation enabled ; I tried an auth.
 on https://sso.lab.lxd/realm/myrealm/account (keycloak on sso.lab.lxd) but
 the internal PAM4j raised an error like bad authentication System Error.
 The problem was the uid/gid of the user for testing the authentication. They were over the UID_MAC and GID_MAX of the login.defs
Once the uid/gid of the test user changed on ipa  to respect the login.defs . I could authenticate my user on the url realm/myrealm/account...but It is not finished.

Now I observe jvm crash with SIGSEGV.
The jvm is a version 11.0.17.

As side note: 
I know that the project [kohsuke](https://github.com/kohsuke)/[libpam4j](https://github.com/kohsuke/libpam4j) from where the internal PAM4j code is pulled has received some PR which are not in the internal one: 
https://github.com/kohsuke/libpam4j/pull/21
however, I tested one parts of the PR (about the garbage collection) on the master branch without any success.

**Comment by Keeper-of-the-Keys** [comment] 2023-01-24 22:25
@mposolda can you maybe add some pointers where in the code to look so if people want to try and help they have some inkling where to start?

I intend to try and replicate what @clbouvier reported with my test setup (FreeIPA 4.10 on Fedora 37).

**Comment by mposolda** [comment] 2023-01-25 08:17
@Keeper-of-the-Keys sure. I suggest to take a look at `SSSDFederationProvider` class and what it is doing. Also at other classes, which are called from that (like in this case `PAMAuthenticator` from which the NPE was thrown).

Here is some Keycloak docs about SSSD: https://www.keycloak.org/docs/latest/server_admin/index.html#_sssd
Here is some docs about User Storage SPI (note that SSSDFederationProvider pretty much implements this SPI): https://www.keycloak.org/docs/latest/server_development/#_user-storage-spi

**Comment by mposolda** [comment] 2023-05-09 16:47
Closing as this task is replaced by #20262. That task is for overal SSSD integration working again (including tests and docs).

Once #20262 is completed, everyone is welcome to test with latest Keycloak nightly build https://github.com/keycloak/keycloak/releases/tag/nightly and check that it works (But please wait until that task is completed. We will let you know).

**Closed by mposolda** 2023-05-09 16:47 UTC
Labels: area/authentication, kind/bug, team/core
