### ISSUE TITLE
Keycloak does not follow the AssertionConsumerServiceURL specified in the SAML request

### ISSUE THREAD

**Issue by yura-kit** [keycloak/keycloak#21556] opened 2023-07-10 12:39 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

We are currently utilizing Keycloak and SAML for our authentication system. However, we have encountered an issue where Keycloak fails to adhere to the AssertionConsumerServiceURL specified in the SAML request. As a consequence, 
when attempting to authenticate, we receive an error page with the message "BAD REQUEST Invalid redirect uri."

￼

### Version

21.1.2

### Expected behavior

Keycloak should follow the AssertionConsumerServiceURL specified in the SAML request and redirect the user to the provided URL after authentication.

### Actual behavior

Keycloak does not follow the AssertionConsumerServiceURL and returns an error page stating "BAD REQUEST Invalid redirect uri."

### How to Reproduce?

Setup SAML client with the following configuration:

![SAML_config](https://github.com/keycloak/keycloak/assets/22376881/568da1ad-4095-4dec-a8d4-c67814286eeb)
![SAML Config 2](https://github.com/keycloak/keycloak/assets/22376881/45958abb-1770-436f-8f6f-f9e8f48c95b4)
![SAML config 3](https://github.com/keycloak/keycloak/assets/22376881/00338b99-f799-46ea-a06d-61dd25678d22)

Initiate Single Sign-On (SSO) using our application as the Service Provider (SP).
Enter valid user credentials on the Keycloak login page.
The SP sends the following SAML request to Keycloak:

<samlp:AuthnRequest AssertionConsumerServiceURL="https://gitlab-stage.test.lt/users/auth/saml/callback"
                    Destination="https://keycloak.test.com/auth/realms/dev/protocol/saml/clients/gitlab_stage"
                    ID="_a1acfd25-b9eb-4853-b6fd-68258fba5245"
                    IssueInstant="2023-06-20T10:30:14Z"
                    Version="2.0"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    >
    <saml:Issuer>gitlab_stage</saml:Issuer>
    <samlp:NameIDPolicy AllowCreate="true"
                        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
                        />
</samlp:AuthnRequest>

Observe the response from Keycloak, which is an error page with the message "BAD REQUEST Invalid redirect uri."

**Comment by rmartinc** [comment] 2023-07-11 08:28
@yura-kit It's quite complicated to help you here with the information provided. Try setting trace level to the saml category (startup option `--log-level=INFO,org.keycloak.saml:TRACE,org.keycloak.protocol.saml:TRACE`) and you will receive more debug info. But I think there are two things that are not OK in your setup:

* The destination of the SP saml auth request is not OK. It should be `https://{keycloak:port}/auth/realms/{realm}/protocol/saml` (not `protocol/saml/clients/{client}`). You can see it when you download config for keycloak or mod auth mellon.
* And you are not setting any signature. It's OK if you are testing with it but you have to configure it if you are going to use this in production. But this is a second step you can try later once it's working without it.

And, please, try using the [keycloak user group](https://groups.google.com/g/keycloak-user) before filing an issue here. This is more thought for coding issues that are reliably reproduced.

Regards!

**Comment by rmartinc** [comment] 2023-07-11 15:30
@yura-kit AFAIK the saml service tries to locate the redirect URI from [the `AssertionConsumerServiceURL` first](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/saml/SamlService.java#L424). But, as I commented in my previous comment, first try tochange the URL you are using in the SP to `https://{keycloak:port}/auth/realms/{realm}/protocol/saml`. The one you are using seems to be the one used for IDP initiated login.

**Comment by rmartinc** [comment] 2023-07-28 10:12
@yura-kit I'm closing this as there is no more information. If you realize there is a bug please re-open it or file a new issue. Thanks!

**Closed by rmartinc** 2023-07-28 10:12 UTC
Labels: area/saml, kind/bug, team/core
