### ISSUE TITLE
[Jenkins Operator CI] - Test remote - KeycloakIngressTest on OpenShift

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#35356] opened 2024-11-27 12:45 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

The following test is failing constantly when running on OpenShift:

`2024-11-25 21:50:52  [ERROR] Errors: 
2024-11-25 21:50:52  [ERROR]   KeycloakIngressTest.testIngressOnHTTP:62 » ConditionTimeout Assertion condition defined as a Lambda expression in org.keycloak.operator.testsuite.utils.K8sUtils found status KeycloakStatusCondition{type='Ready', status=False, message='Waiting for more replicas'} and expected status true within 5 minutes.
2024-11-25 21:50:52  [INFO] 
2024-11-25 21:50:52  [ERROR] Tests run: 125, Failures: 0, Errors: 1, Skipped: 5`

https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/966/testReport/

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment] 2024-11-27 23:18
Duplicate of #34868 - the same behavior of waiting for the global lock is shown.

**Closed by shawkins** 2024-11-27 23:18 UTC
Labels: kind/bug, area/ci, team/cloud-native, status/triage, flaky-job
