### ISSUE TITLE
v 22.0.0 - when creating a new realm the registration flow does not have terms and conditions step

### ISSUE THREAD

**Issue by jorgemartincuervo** [keycloak/keycloak#21730] opened 2023-07-17 07:26 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

From a fresh installation, windows 22.0.0, 20.0.3 and docker 22.0.0, when i create a new realm and then try to enable the terms and conditions in the registration flow, the step is not there and not in the list to add.

### Version

22.0.0 and 20.0.3

### Expected behavior

As described in the documentation, an step "terms and conditions" should exist in the registration flow.

### Actual behavior

There is a missing step in the registration flow.

### How to Reproduce?

form fresh installation, create a new realm.

**Comment by antikalk** [comment] 2023-07-17 08:21
Did you enable that required action for the realm? (Authentication -> Required Actions)

**Comment by jorgemartincuervo** [comment] 2023-07-17 08:23
Yes, I did enabled it.

**Comment by jorgemartincuervo** [comment] 2023-07-17 08:24
In the master realm appears the step. It seems to happen only with new realms.

**Comment by ctmay4** [comment] 2023-07-17 17:35
I don't see it in the master realm either.

I just updated to 22.0.0 and was also interested in adding this to an existing custom realm. I made sure to set it to "Required" first.

![image](https://github.com/keycloak/keycloak/assets/444345/6c9737da-70a5-42df-82f7-dff4311e9a32)

Then I tried to add it to the flow but the step does not exist.

![image](https://github.com/keycloak/keycloak/assets/444345/a98ee902-4c84-4b1a-9cc2-af81cf7b215d)

I re-read the documentation at https://www.keycloak.org/docs/latest/server_admin/index.html#proc-requiring-tac-agreement-at-registration_server_administration_guide. I don't see any other steps.

**Comment by ctmay4** [comment] 2023-07-17 20:28
I just downloaded a fresh copy of Keycloak 22.0.0 and installed it locally to test. Went to the master realm and I do see the option for terms and conditions. So maybe this has to do with existing databases not picking up the option correctly?

**Comment by mposolda** [comment] 2023-07-18 08:50
Adding to Backlog as not sure if Keycloak team will have time to look at this in the near future. Anyone is welcome to investigate (and eventually fix this if it is a real bug in Keycloak and not some misconfiguration).

**Comment by ctmay4** [comment] 2023-07-18 11:11
A follow-up.

With a fresh instance, I do see the terms and conditions in the flow for the "master" realm. However when I create a new realm it is not there. I also tried importing my realm to the new instance the option is not there either. Not sure how to get this option to show up.

**Comment by ctmay4** [comment] 2023-07-18 14:58
Full steps to reproduce bug.

- download Keycloak 22.0.1 (https://github.com/keycloak/keycloak/releases/download/22.0.1/keycloak-22.0.1.zip)
- explode the zip 
- run the server (I am on Windows)
- set the admin password and log in
- verify that the "master" realm shows the "terms and conditions" in the registration flow
- create a new realm called "test" and switch to it
- enable "Terms and Conditions" in the "Required Actions"
- check the registration flow; the terms and conditions are not there and also not in the list of steps to add

**Comment by jorgemartincuervo** [comment] 2023-07-30 16:30
Hello,

I have compared the tags 19.0.1 and 22.0.0 to update the templates and I have seen something that might be related.

https://github.com/keycloak/keycloak/commit/e49dfe534e979db7f401021b7e2bb7d8c4c7cd73
IF you see this commit the requiredAction key went from lowercase to uppercase.

**Comment by Guesch** [comment] 2023-08-04 23:16
Just a note to confirm the bug on new realm. Unable to see "terms & conditions" in the flow option, despite having them enabled on the realm.

**Comment by mposolda** [comment] 2023-09-05 08:52
Few points to this:

- There is workaround, which can be used for this. It is true that `Terms and conditions` step is missing in the newly created realm. However as a workaround, you can create new registration flow in your realm and add `Terms and conditions` to this flow. When you're at the `Registration` flow of the test realm, you can create `Duplicate` at the `Actions` menu in right top corner and create new flow like `Copy of registration`. In this flow, you can add `Terms and conditions` step and set it as REQUIRED. You also need to bind this flow (Options `Bind flow` in the right top `Actions` menu). After flow is bind, it will be used for user registrations and t&c is here.

- One minor usability issue: It can be nice that documentation section for t&c in the registration flow https://www.keycloak.org/docs/latest/server_admin/index.html#proc-requiring-tac-agreement-at-registration_server_administration_guide contains some link to the section https://www.keycloak.org/docs/latest/server_admin/index.html#proc-enabling-terms-conditions_server_administration_guide as it is needed info that `terms.ftl` needs to be set in order to t&c to be any useful and this info is missing in the "registration" section.

- @ahus1 @jorgemartincuervo I noticed one strange thing when looking at this. When creating new realm, the method `DefaultAuthenticationFlows.registrationFlow(RealmModel realm, boolean migrate)` is triggered with the `migrate` argument set to `true`. This is suspicious to me as I am not migrating anything, but I am creating new realm. When I manually change `migrate` to `false` during my debugging session, then the `Registration` flow is created with `Terms and conditions` step included. Is it possible that this might be regression related to some refactoring of managers during old/new flow? Right now, it looks to me that https://github.com/keycloak/keycloak/commit/e49dfe534e979db7f401021b7e2bb7d8c4c7cd73 is not causing this issue, but rather the old/new store refactoring might be the cause?

**Comment by edemen** [comment] 2023-09-05 10:05
For me, TaC step is missing in existing realms when having upgraded from KC 18 to 22, so the workaround would not work.

**Comment by Guesch** [comment] 2023-09-05 11:39
> Few points to this:
> 
> * There is workaround, which can be used for this. It is true that `Terms and conditions` step is missing in the newly created realm. However as a workaround, you can create new registration flow in your realm and add `Terms and conditions` to this flow. When you're at the `Registration` flow of the test realm, you can create `Duplicate` at the `Actions` menu in right top corner and create new flow like `Copy of registration`. In this flow, you can add `Terms and conditions` step and set it as REQUIRED. You also need to bind this flow (Options `Bind flow` in the right top `Actions` menu). After flow is bind, it will be used for user registrations and t&c is here.

I'm afraid the workaround is not working for me either: Even by creating a copy of the registration flow, the "Terms and conditions" is not an option available in the "Add step"  (I'm not using the master realm and "terms & conditions is enabled on my realm)

**Comment by mposolda** [comment] 2023-09-07 08:52
@Guesch That is strange. Just to doublecheck are you trying to add it in the `Copy of registration registration form` subflow? It is needed to add it to this subflow (not to top level flow) as the `Copy of registration registration form` is the "Form flow", which is supposed to handle this. See screenshot for more details.

![Screenshot from 2023-09-07 10-48-37](https://github.com/keycloak/keycloak/assets/1223965/336db179-d9d5-4246-a3ff-0289dbd184f4)

@edemen You can update the registration flows in the existing realms as I've described above. So I am not sure why the workaround would not work? This should work fine in Keycloak 22.

**Comment by Guesch** [comment] 2023-09-07 17:37
> @Guesch That is strange. Just to doublecheck are you trying to add it in the `Copy of registration registration form` subflow? It is needed to add it to this subflow (not to top level flow) as the `Copy of registration registration form` is the "Form flow", which is supposed to handle this. See screenshot for more details.
> 
> ![Screenshot from 2023-09-07 10-48-37](https://user-images.githubusercontent.com/1223965/266260971-336db179-d9d5-4246-a3ff-0289dbd184f4.png)
> 
> @edemen You can update the registration flows in the existing realms as I've described above. So I am not sure why the workaround would not work? This should work fine in Keycloak 22.

Sorry if I misunderstood the documentation and what I'm supposed to see; but here a screenshot to confirm that the T&C are enabled on our realm (not the master)
![image](https://github.com/keycloak/keycloak/assets/61683661/37f9c84f-80ce-45ce-9f47-3ebf3149bdc0)

And here are the only options I can see when selecting "add a step" in the "Copy of registration registration form"
![image](https://github.com/keycloak/keycloak/assets/61683661/04398ab9-80b3-4156-a005-1f4a45f9d288)

As you can see there is no "Terms and conditions" here. We are supposed to see this option in this list, aren't we?

**Comment by mposolda** [comment] 2023-09-13 08:31
Yes, true. This is not expected.

But I am not seeing this behaviour with latest Keycloak 22.0.3. Not sure if it's already fixed in the latest version or there is something else...

What I did was exactly this:
- Download latest Keycloak 22.0.3

- Start with `./kc.sh start-dev`

- Opened http://localhost:8080 and created `admin`

- Opened http://localhost:8080/admin, login and create realm "test"

- Click tab "Authentication" in the "test" realm -> select flow "registration" -> Click Action in right top corner and click to "duplicate". I have new flow called "Copy of registration"

- In the subflow "copy of registration registration form", I clicked "add step". The "Terms and conditions" step is present (See 
screenshot)

![Screenshot from 2023-09-13 10-20-31](https://github.com/keycloak/keycloak/assets/1223965/dafe2d1a-6757-4b97-a218-68e477597e1a)

- Added "Terms and conditions" as REQUIRED. Then I've bind this flow as "Registration flow"

- Enabled "User registration" for my realm

- Opened localhost:8080/realms/test/account/ then "Sign in" -> Link "Register" on login screen. The "terms and conditions" is required for the newly registered user

Please doublecheck with latest Keycloak 22.0.3. If you still see the same with your environment with latest Keycloak 22.0.3, then please add your **detailed** steps to reproduce, so we can confirm where your steps differ from mine and what exactly is needed to reproduce this.

**Comment by Guesch** [comment] 2023-09-13 09:55
Will do asap and report back! Thank you!

**Comment by ctmay4** [comment] 2023-10-31 19:49
I am on 22.0.5 and this is still an issue. The workarounds didn't help me. Anyone figure this one out?

**Comment by edemen** [comment] 2023-10-31 22:38
@mposolda 
> @edemen You can update the registration flows in the existing realms as I've described above. So I am not sure why the workaround would not work? This should work fine in Keycloak 22.

This does not work unfortunately. When I duplicate registration flow or create a new one, I can't add terms to either. It just isn't in the list of executions to add.
![image](https://github.com/keycloak/keycloak/assets/3247886/8620be60-f047-48a2-a82f-d9ab9dff94bf)

**Comment by ctmay4** [comment] 2023-11-30 18:26
23.0.1 and still an issue. Has anyone found a good workaround?

**Comment by iwtolall** [comment] 2023-12-09 00:44
@ctmay4 I had the same issue but finally I was able to add TaC in Keycloak 22.0.5 (migrated from 12.0.1) on existing realms via guide from @mposolda : 

- Copy the registration flow
- Use the + icon (not the "add step", see screenshot) and add the TaC
- Bind the flow

![image](https://github.com/keycloak/keycloak/assets/1658851/8357ab59-17b3-4b63-baec-040ca0064e50)

**Closed** 2023-12-13 14:32 UTC
Labels: kind/bug, area/core, help wanted, team/core

**Comment by ctmay4** [comment] 2023-12-14 18:41
> @ctmay4 I had the same issue but finally I was able to add TaC in Keycloak 22.0.5 (migrated from 12.0.1) on existing realms via guide from @mposolda :
> 
>     * Copy the registration flow
> 
>     * Use the + icon (not the "add step", see screenshot) and add the TaC
> 
>     * Bind the flow
> 
> 
> ![image](https://private-user-images.githubusercontent.com/1658851/289218731-8357ab59-17b3-4b63-baec-040ca0064e50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Nzk1MjgsIm5iZiI6MTcwMjU3OTIyOCwicGF0aCI6Ii8xNjU4ODUxLzI4OTIxODczMS04MzU3YWI1OS0xN2IzLTRiNjMtYmFlYy0wNDBjYTAwNjRlNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTg0MDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGNkOGE3NTUzZmE3ZTcyOWI5MmZhMzUyZjc3NTFiN2MzZmExNjQ2NGZhNDkxZjU2NzIwZjNlMmRkMWFhMTEzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NG6O1BhikoXzyo40JqVfU5-NTI6Ym-k124YfVW0D9TY)

That definitely works. Great catch! Looks like it was fixed in the next release but it is really nice to have a workaround. Thanks.

**Comment by ryanmaffey** [comment] 2024-04-09 13:58
This is still an issue for me on v23.0.6

**Comment by sebastianopilla** [comment] 2024-04-20 14:26
This still happens for me on a 24.0.2 instance, which started its life in v21.0.0 and went thru various upgrades. It does not happen on a 24.0.2 instance started on a blank database.
