### ISSUE TITLE
Explore using Quarkus Quinoa for UIs

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#20720] opened 2023-06-01 10:23 UTC
We currently use a hodgepodge solution to build the console UIs using [`maven-frontend-plugin`](https://github.com/eirslett/frontend-maven-plugin), however @edewit recently discovered [Quarkus Quinoa](https://github.com/quarkiverse/quarkus-quinoa), which might be a nicer solution (also for development).

Let's figure out if this tool could meet our needs better.

**Comment by edewit** [comment] 2023-06-02 12:14
Did an experiment with this and it seems to work. I think this can be a solution to the problems we have with the maven-frontend-plugin. Things we need to figure out to have this as a permanent solution are:
1. Have multiple endpoints go different applications
1. How do we handle the freemarker variable injection

**Comment by vmuzikar** [comment] 2023-06-05 16:29
We'd probably also need to make sure it's part of RHBQ.

**Comment by edewit** [comment] 2023-06-06 07:34
it's part of RHBQ https://code.quarkus.redhat.com/?extension-search=origin:other%20quinoa

**Comment by ASzc** [comment] 2023-06-07 13:22
If it's a build time only thing, like frontend maven plugin is, then we don't necessarily need a productized artifact to include in the build. If there isn't a productized artifact available, we will need a separate version property in the pom for Quinoa, versus Quarkus as a whole, since that will be using a `-redhat` version.

My main concern with switching plugins is maintaining the ability to use the system nodejs via build parameter. With frontend plugin it's accomplished as follows. I have trimmed the build script to the relevant parts for JS, which is actually most of the build script anyway.

```
for frontend in adapters/oidc/js/node/ themes/node/ node/ js/node
do
    mkdir -p "$frontend"
    ln -s /path/to/global/node_modules/ "$frontend/node_modules"
    ln -s /usr/bin/node "$frontend/node"
done

npm install -g pnpm@8.4.0

mvn deploy -Dskip.installnodepnpm
```

It also needs to be confirmed that Quinoa can be configured to use a HTTP/S proxy. Frontend plugin automatically passes along the maven proxy information to PNPM. The proxy is used in the product build to ensure all relevant NPM packages are saved for possible rebuilds.

**Comment by edewit** [comment] 2023-06-14 05:31
until we have found a way around all these issues this is no alternative yet closing for now

**Closed by edewit** 2023-06-14 05:31 UTC
Labels: area/account/ui, area/admin/ui, kind/task, team/ui
