### ISSUE TITLE
Internal token to internal token exchange on keycloak 17 and up

### ISSUE THREAD

**Issue by zakariae-lebriq** [keycloak/keycloak#12951] opened 2022-07-06 18:37 UTC
### Describe the bug

Null pointer exception is thrown when exchanging a token of a client Source to a client target

2022-07-06 18:27:53,341 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-4) Uncaught server error: java.lang.NullPointerException
        at org.keycloak.protocol.oidc.TokenManager.attachAuthenticationSession(TokenManager.java:539)
        at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchangeClientToOIDCClient(DefaultTokenExchangeProvider.java:336)

### Version

18.0.2

### Expected behavior

Get a token of the  target client

### Actual behavior

Null pointer exception 

2022-07-06 18:27:53,341 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-4) Uncaught server error: java.lang.NullPointerException
        at org.keycloak.protocol.oidc.TokenManager.attachAuthenticationSession(TokenManager.java:539)
        at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchangeClientToOIDCClient(DefaultTokenExchangeProvider.java:336)

### How to Reproduce?

Get a token of a client A, then exchange it for a client B

**Comment by DGuhr** [comment] 2022-07-07 06:25
Hi @zakariae-lebriq - thanks for reporting! 

This seems to be a duplicate of #12596 - there is an open PR from @pedroigor at #12789 that will fix this. I'll close this issue so we can consolidate communication about it inside #12596 and not having 2 places to look at. Feel free to subscribe to that issue instead.

**Closed by DGuhr** 2022-07-07 06:25 UTC
Labels: kind/bug, area/token-exchange, status/triage
