### ISSUE TITLE
Performance degradation when upgrading from RHSSO 7.6 to KC22 caused by TLSv1.3 processing

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20954] opened 2023-06-13 08:41 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

When testing the upgrade from RHSSO 7.6 to KC22 there is a noticeable performance gap even after aligning on garbage collection and ingress configurations. 

While KC22 with Quarkus seems to be slightly faster than RHSSO 7.6 as long as both use TLS 1.2, KC22 becomes slower once it uses TLS 1.3 (which is the default). 

### Version

nightly

### Expected behavior

People upgrading from RHSSO 7.6 to KC22 shouldn't see a performance degredation

### Actual behavior

There is a ~7% performance degradation in a CPU constrained environment on the Client Credential Grant scenario where a caller performs a single request only and therefore the additional TLS 1.3 overhead becomes visible. Other scenarios like the login flow where there is hashing of passwords and multiple requests using the same connection don't have a visible impact. 

In this setup all data used by Keycloak is stored inside the local Infinispan, so no DB calls or remote Infinispan calls occur. In a clustered environment where some Infinispan calls are remote calls and latencies increase, this overhead would become even less visible.

Iterations performed by the setup below for Client Credential Grant: 

KC22 w/ TLSv1.2: 69501
KC22 w/ TLSv1.3: 61851
RHSSO w/ TLSv1.2: 66731

This summarizes for the Client Credential Grant as follows: 
- KC22 is ~4% faster than RHSSO when both run with TLSv1.2
- KC22 w/ TLS 1.3 is ~11% slower than KC22 w/ TLS 1.2
- KC22 w/ TLS 1.3 is ~7% slower than RHSSO w/ TLS 1.2

In this low-latency environment where the load driver is close to the system being tested, the TLSv1.3 advantage of fewer network round-trips can't show their value. As stated above, other scenarios are likely to see a smaller impact as they can re-use the TLS connections or do more work for example for hashing passwords.

Java profiling of KC22 w/ TLSv1.3 vs THSSO w/ TLSv1.2 shows that there are additional cryptographic calls that point to the Diffie Hellman key exchange with ephemeral keys which is required for TLSv1.3

RHSSO 7.6 - smaller time share used on crypto: 
![eap](https://github.com/keycloak/keycloak/assets/3957921/7c7437cc-3e31-4866-9cfc-1989c663b405)

Keycloak 22: larger time share used on crypto:
![quarkus](https://github.com/keycloak/keycloak/assets/3957921/58c8a96c-fcdc-46e9-b135-2ad696e29c1f)

Zoom in on crypto used for TLSv1.3, indicating most of it is doing DH key exchange work:
![crypto](https://github.com/keycloak/keycloak/assets/3957921/90b01f91-7c63-4a29-8030-ad11c9ddc537)

### How to Reproduce?

RHSSO 7.6: Standard Operator deployment on an OpenShift physical dedicated cluster. Single pod started. Uses JDK11. As blog posts show, uses OpenSSL directly.

KC22: Standard Operator deployment on an OpenShift physical dedicated cluster. Single pod started. Uses JDK17. Custom route to use reencrypt instead of passthrough, as passthrough would have an additional negative performance impact. As blog post show, will use JDK cryptographic functions, OpenSSL is not used.

Limit the CPU resources of the containers to 4 vCPU so the scenario is CPU bound.

Due to HAProxy's default configuration of using http-reuse of "safe", new sessions always create new backend connections, so there is a high turnover of TLS connections in this setup. See https://www.haproxy.com/blog/http-keep-alive-pipelining-multiplexing-and-connection-pooling for details.

Performance test to run: 

> ./kcb.sh --server-url=... --log-http-on-failure --realm-name=test-realm --measurement=45 --ramp-up=15 --concurrent-users=8

Run one warmup iteration, then run ~5 more iterations and calculate the average result. 

### Anything else?

There is a Wildfly blog post on TLSv1.3 performance https://wildfly-security.github.io/wildfly-elytron/blog/tls-13-with-wildfly/ and a JIRA issue https://issues.redhat.com/browse/WFWIP-160

More aggressive TLS connection re-use by HAProxy (the OpenShift Router) would prevent this impact, but a review of the configurations didn't reveal such an option. See https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html for the available options. As the KC22 operator creates a passthrough ingress and not a reencrypt ingress, this wouldn't optimize the default setup.

Supporting OpenSSL in Quarkus could reduce the overhead of DH key exchange, but this investigation didn't find an issue to support this in Quarkus JVM mode.

**Comment by ahus1** [comment] 2023-06-15 17:56
@mabartos - I've made the Quarkus team aware of that some time ago when I did my tests, and I used a locally built Quarkus version to verify the TLS v1.2 vs. v1.3 performance. 

Disabling TLS v1.3 by default isn't an option IMHO as we want to have Keycloak secure-by-default, and TLS v1.3 support is exactly that so the client can choose the most secure protocol.

**Comment by mabartos** [comment] 2023-06-16 10:08
@ahus1 I understand your concerns and agree to have Keycloak as secure as possible. However, the issue with the performance degradation for TLSv1.3 still persists, and it seems it's not gonna be solved until our next release. As I've mentioned, also other products are affected by this, and the problem is somewhere on the lower layers. 

AFAIK, using OpenSSL will slightly help with the performance degradation, but still not comparable with the usage of TLSv1.2. 

Probably, I didn't clearly state the point behind the possibility of choosing different versions of TLS for Quarkus. The thing is that we don't have many choices at this moment. Customers need to make a decision, whether either a more secure or more performant application will be preferred. 

We could follow the same approach as EAP as the TLSv1.3 is disabled by default, and customers have the possibility to enable it. In that case, we'd need to properly document it.

@ahus1 Do you have any idea how it could be improved?

**Comment by ahus1** [comment] 2023-06-16 11:18
Summary from my email conversation with @mabartos: Starting from January 1st 2024, NIST SP 800-52 requires support of TLS 1.3 - see https://csrc.nist.gov/publications/detail/sp/800-52/rev-2/final (TLS 1.2 is then still allowed). Therefore it is not an option IMHO to disable it by default. When future versions of Quarkus support disabling TLS 1.3 this might be technically possible, but I'd advise people not to. 

So I'm +1 for keeping TLS v1.3 enabled by default. If you think otherwise, please take it to @stianst.

**Comment by stianst** [comment] 2023-06-16 11:30
Completely agree, let's keep TLS 1.3 enabled by default for sure.

**Comment by stianst** [comment] 2023-06-28 07:45
As performance difference is between TLS 1.2 and TLS 1.3, and not directly Keycloak running on EAP vs running on Quarkus, we are closing this issue. Any potential improvements to TLS 1.3 would need to be done in OpenJDK, or potentially Quarkus supporting OpenSSL (which has potential of being slightly faster). However, for the time being there is nothing we can do here.

**Closed by stianst** 2023-06-28 07:45 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
