### ISSUE TITLE
Bogus error message when forgot to convert urlencoded data to string

### ISSUE THREAD

**Issue by Teut2711** [keycloak/keycloak#20805] opened 2023-06-06 09:25 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

Hi,
The issue is about irrelevant error response when one forgets to stringify urlencoded data.

```js
async function getToken(code) {
      var myHeaders = new Headers();
      myHeaders.append('Content-Type', 'application/x-www-form-urlencoded');

      var urlencoded = new URLSearchParams();
      urlencoded.append('grant_type', 'authorization_code');
      urlencoded.append('client_id', 'energymetrics');
      urlencoded.append('client_secret', 'dvQBRVjsOqy0hB0xlT0NU5vMqcPJ0Ti2');
      urlencoded.append('code', code.toString());
      urlencoded.append('redirect_uri', 'https://files.irasus.com/dashboard');

      var requestOptions = {
        method: 'POST',
        headers: myHeaders,
        body: urlencoded,    
        redirect: 'follow',
      };
      console.log('I  m here');
      try {
        const response = await fetch(
          'https://keycloak.irasus.com/auth/realms/evcompanion/protocol/openid-connect/token',
          requestOptions,
        );
        const result = await response.json();
        console.log(result);
      } catch (error) {
        console.log('error', error);
      }
    }
  };
```

### Version

21.1.1

### Expected behavior

The correct error message should be  "Unable to decode formdata"

### Actual behavior

The following, throws the message :
```
 LOG  {"error": "invalid_request", "error_description": "Missing form parameter: grant_type"} 
 ```
which is not helpful.

### How to Reproduce?

Once to get the code from the url after logging in through user, use that code to get the access token.

### Anything else?

The correct thing is to do      `urlencoded.toString()` but the error message should be improved.

**Comment by rmartinc** [comment] 2023-06-15 08:27
@Teut2711 You are right, but it's easier to use curl to exemplify what happens here.

```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" --data-raw '{"lala"=1}' "http://localhost:8080/realms/master/protocol/openid-connect/token"
{"error":"invalid_request","error_description":"Missing form parameter: grant_type"}
```

Maybe the easiest way for fixing this is just checking if there is no parameters before getting the grant type ([here](https://github.com/keycloak/keycloak/blob/21.1.1/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L200)). And returning a specific error saying `Invalid or empty form parameters` or similar. A simple test can be added for example in [AccessTokenTest](https://github.com/keycloak/keycloak/blob/21.1.1/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java#L1404)

This is a minor issue and an easy one for someone that wants to start collaborating in keycloak. Adding help wanted and good first issue.

**Comment by Teut2711** [comment] 2023-06-15 08:32
Sure, let me work on it after work

**Comment by akbar1214** [comment] 2023-07-15 17:44
@rmartinc I think I can contribute to this as I feel there is only few line of code(**check if grant type is present in formParameters**) change required from development side and only one test case. Let me know if my understanding is incorrect.

**Comment by rmartinc** [comment] 2023-07-17 10:18
@akbar1214 Yes, I think you are right, at first sight it's just adding an if check and a the corresponding test, for example in AccessTokenTest.

**Comment by akbar1214** [comment] 2023-07-18 04:22
@rmartinc  I have raised the PR. Please provide feedback if any

**Comment by rmartinc** [comment] 2023-09-20 09:27
After talking with the rest of the team I think this issue makes no much sense. The problem is that if you pass something in the payload and the content-type is correctly set to application/x-www-form-urlencoded it is parsed by resteasy. If there is no exception, the data is OK (obviously something weird is returned but it is there). In that case the `Missing form parameter: grant_type` message is perfectly OK and makes sense.

@akbar1214 Thanks for collaborating but I'm closing this as not a bug.

**Closed by rmartinc** 2023-09-20 09:27 UTC
Labels: area/oidc, kind/bug, good first issue, help wanted, team/core
