### ISSUE TITLE
Token Exchange response JWT Missing offline_access Scope

### ISSUE THREAD

**Issue by bienblue** [keycloak/keycloak#33140] opened 2024-09-20 11:01 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

When attempting to exchange a token using the curl command, the **offline_access** scope is not included in the response, and also in JWT token. This results in the token received not being an offline token. For the old version(23.0.7), it still working fine.
![image](https://github.com/user-attachments/assets/d2339a2f-d101-4a5d-be86-12ed9f6effd4)

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The offline_access scope is included in the response, and also in JWT token.

### Actual behavior

The offline_access scope is not included in the response, and also in JWT token.

### How to Reproduce?

Execute the following curl command:
curl -s https://auth.development.bienho.com/realms/bien/protocol/openid-connect/token \
      -d client_id='alb' \
      -d client_secret='41bba346-6811-5a74-99c1-70ecbab6113e' \
      -d grant_type=urn:ietf:params:oauth:grant-type:token-exchange \
      -d subject_token='[$subject_token]' \
      -d scope='offline_access openid profile email' \
      -d requested_subject='136f589f-b81f-42cb-a1d0-ddaa7188083b'

**Comment by sschu** [comment] 2024-09-23 16:43
Most likely duplicate of https://github.com/keycloak/keycloak/issues/29614.

**Closed** 2024-09-23 16:44 UTC
Labels: kind/bug, area/token-exchange, team/core-clients

**Comment by jonkoops** [comment] 2024-09-24 10:48
Duplicate of #29614
