### ISSUE TITLE
Export Keycloak Realm is Exporting each Ldap users 2 times in the Users Array of the exported Json file 

### ISSUE THREAD

**Issue by ArijitCode** [keycloak/keycloak#23285] opened 2023-09-15 10:35 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

1) Configure  Keycloak with a sLdap server
2) Syncing Ldap users 
3) Export Realm to a json file (bin/kc.[sh|bat] export [--dir|--file] <path> --realm my-realm)

Actual :- Each Ldap user object present 2 times in the Users array 
Expected :- Users array in the Exported file should not have duplications 

Because the Exported File has duplicated Ldap users , the Import is failing  with the following error :- 

2023-09-13 03:14:46,713 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2023-09-13 03:14:46,713 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: org.keycloak.models.ModelDuplicateException: jakarta.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.keycloak.models.jpa.entities.UserEntity#*******]

### Version

22.0.1, 22.0.3

### Expected behavior

 Users array in the Exported file should not have duplications 

### Actual behavior

 Each Ldap user object present 2 times in the Users array 

### How to Reproduce?

1) Configure  Keycloak with a sLdap server
2) Syncing Ldap users 
3) Export Realm to a json file 

### Anything else?

We are also seeing duplicate LDAP users Listing in the KeyCloak UI , Users page after Configuring Ldap and doing a sync

**Comment by sguilhen** [comment] 2023-11-08 20:43
@ArijitCode I could not reproduce the issue locally. After configuring a LDAP user federation and synchronizing the users, they are displayed only once in the Users page, and exporting the realm results in a JSON with a single entry for each user. I wasn't able to get to a point where the user in imported twice.

**Comment by sguilhen** [comment] 2023-12-08 13:03
Closing the issue as I was not able to reproduce it. Tried exporting users synch'd from an LDAP federation multiple times and every single time the exported file contained only one entry per user.

**Closed by sguilhen** 2023-12-08 13:03 UTC
Labels: kind/bug, area/ldap, team/store, status/triage

**Comment by vishrantgupta** [comment] 2024-05-05 02:16
> A different object with the same identifier value was already associated with the session

check if there is a duplicate client or user in your realm config JSON file.
