### ISSUE TITLE
Export runtime problem without explicite informations

### ISSUE THREAD

**Issue by adryen31** [keycloak/keycloak#35981] opened 2024-12-17 13:50 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

I tried to make a partial export via the keycloak interface (25.0.6 version), and an exception raised.
After that I tried to make the export by command line, but same thing the problem is logged that an "alias" of authentification method seems to be null. after that I filled all "Alias" field of authenticator, but the problem still raise and the log isn't very useful to understand which authenticator alias to set ...
that should be possible at least to return the id or anything on the authenticator concerned plz ? in order to fix the problem of null alias
[error.log](https://github.com/user-attachments/files/18166377/error.log)

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

at least a mean to determine the concerned authenticator 

### Actual behavior

a simple exception raise without any information

### How to Reproduce?

I don't know the problem and what provide you to reproduce

**Comment by adryen31** [comment] 2024-12-18 08:06
> Thanks for reporting this issue, but as this is reported against an older and unsupported release we are not able to evaluate the issue. Please verify with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly) or the [latest release](https://www.keycloak.org/downloads).
> 
> If the issue can be reproduced in the nightly build or latest release add a comment with additional information, otherwise this issue will be automatically closed within 14 days.

sorry but no acceptable for us, you should give some help and assume that as long as there is a new version, each person is supposed to migrate or take the first, so please find a solution and do not cloturer the ticket under penalty of reopening or re-creation

**Comment by shawkins** [comment] 2024-12-18 18:31
> sorry but no acceptable for us

That message is from a bot, and yes it is expected / helpful to reproduce the problem against the latest version. There will no longer be releases on the 25.x line.

In particular this issue looks to be a duplicate of #34888 - please reopen if that is not the case.

**Closed by shawkins** 2024-12-18 18:31 UTC
Labels: kind/bug, area/admin/cli, team/cloud-native, status/triage
