### ISSUE TITLE
Problem with KC_SPI_TRUSTSTORE_FILE_FILE

### ISSUE THREAD

**Issue by breedjaram32** [keycloak/keycloak#13111] opened 2022-07-14 12:55 UTC
### Describe the bug

Hi,
I define SPI truststore and import ldap cert to him.

```
ENV KC_SPI_TRUSTSTORE_FILE_FILE=production.truststore
ENV KC_SPI_TRUSTSTORE_FILE_PASSWORD=changeit
RUN keytool -import -noprompt -storepass changeit -file ldap-production.cer -alias ldapproduction -keystore production.truststore
```

After this action ldap connection with nonpublic cert works fine but since then it stopped working authentication via all identity provider (Google, microsoft...)

`sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I am using those ENV too
```
ENV KC_HTTP_RELATIVE_PATH=auth
ENV KC_HOSTNAME=publicurl.com
ENV KC_HOSTNAME_ADMIN=localurl.localdomain.com
ENV KC_PROXY=edge
ENV KC_HOSTNAME_STRICT_BACKCHANNEL=true
```

SOLUTION
Do not define `KC_SPI_TRUSTSTORE_FILE_FILE` `KC_SPI_TRUSTSTORE_FILE_PASSWORD`

and import the ldap certificate directly into cacert store.

`RUN keytool -importcert -alias ldapcert -cacerts -storepass changeit -noprompt -trustcacerts -file ldap-production.cer `

### Version

18.0.2 quarkus

### Expected behavior

When I define

```
ENV KC_SPI_TRUSTSTORE_FILE_FILE=production.truststore
ENV KC_SPI_TRUSTSTORE_FILE_PASSWORD=changeit
```

Login via Identity provider will be works too.

**Comment by pedroigor** [comment] 2022-08-03 21:11
@breedjaram32 Do you also have the certs for the brokers you are integrating within the JKS?

**Comment by hmlnarik** [comment] 2022-12-13 14:37
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of Keycloak, feel free to reopen and provide details to why it is still valid.

**Closed by hmlnarik** 2022-12-13 14:37 UTC
Labels: kind/bug, area/ldap, status/triage
