### ISSUE TITLE
x509 client certificate popup not work

### ISSUE THREAD

**Issue by sakitA** [keycloak/keycloak#15481] opened 2022-11-13 20:31 UTC
### Area

authentication

### Describe the bug

I configured keycloak server with mutal tls and enable keycloak server accepts secure connection. then follow https://www.keycloak.org/docs/latest/server_admin/#_x509 this guide to add x509 authentication flow. when I try to login, instead of popup window to ask client certificate, it automatically fail and shows the below error.

```
We are sorry...
Invalid username or password.

[« Back to Application](https://localhost:8443/realms/magus/account/)
```
and this is the error log

```
2022-11-13 21:28:24,656 WARN  [org.keycloak.services] (executor-thread-40) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1025)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:879)
	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:151)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:338)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:194)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Version

20.0.0

### Expected behavior

browser should ask client certificate

### Actual behavior

it does not ask client certificate and failed automatically because could not find the certificate

### How to Reproduce?

enable mutal tls and follow this guide https://www.keycloak.org/docs/latest/server_admin/#_x509

### Anything else?

I tested on latest safari and chrome web browser, result both are same

**Comment by alallier** [comment] 2022-11-16 17:59
I'm experiencing this as well, same stacktrace and can't get the client cert popup

**Comment by huangbaron2** [comment] 2022-11-17 15:53
Same issue here on Firefox too, hopefully we get a follow up soon

**Comment by dajester2013** [comment] 2023-01-12 20:32
https://github.com/keycloak/keycloak/blob/02d113ab71de67817890b655ae792580a4fb8ee2/services/src/main/java/org/keycloak/services/x509/DefaultClientCertificateLookup.java#L50

This line is always returning null for me.

**Comment by daurrutia** [comment] 2023-02-01 04:59
Same. Many hours spent.
How can we add a test?

**Comment by Nithe14** [comment] 2023-02-01 12:40
The same for me on keycloak 20.0.1

**Comment by david6983** [comment] 2023-02-01 21:33
Hello Keycloak lovers,

Personally, By doing a quick Mutual-TLS setup for versions 20.0.1 and 20.0.3 on Docker, I can confirm Mutual-TLS is working and the browser is showing the certificate correctly. Let me show you the PoC I did that I hope will help you to solve your configuration:

**TL.DR:** Make sure you import the certificate of the user into the browser

1. First thing first, I generated the certificates based on the [gist](https://gist.github.com/dasniko/b1aa115fd9078372b03c7a9f7e9ec189) from @dasniko 

```bash
# Root CA
openssl req -x509 -sha256 -days 3650 -newkey rsa:4096 -keyout rootCA.key -out rootCA.crt
# Keycloak server certificate
openssl req -new -newkey rsa:4096 -keyout localhost.key -out localhost.csr -nodes
openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in localhost.csr -out localhost.crt -days 365 -CAcreateserial -extfile localhost.ext
# User certificate (Fred Flintstone)
openssl req -new -newkey rsa:4096 -nodes -keyout fredFlintstone.key -out fredFlintstone.csr
openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in fredFlintstone.csr -out fredFlintstone.crt -days 365 -CAcreateserial
# Export certificates and private keys to a p12 file to import them more easily
openssl pkcs12 -export -out fredFlintstone.p12 -name "fredFlintstone" -inkey fredFlintstone.key -in fredFlintstone.crt
openssl pkcs12 -export -in localhost.crt -inkey localhost.key -out localhost.p12
# Create the Java keystore for keycloak
keytool -import -file rootCA.crt -alias rootCA -keystore truststore.jks
``` 

2. Import the fredFlintstone.p12 file in the browser 

For Firefox:
- Go to Settings
- Search 'View Certificates'
- In the section 'Your Certificates', click import
- Import the fredFlintstone.p12

Note that this method is not recommended for production to my mind because the private key of Fred is in the browser. But it's easy to use a hardware PKCS11-compatible device to store the certificate and the private key on it.

3. Run Keycloak on Docker in the folder with all the certificates

```bash
docker run -p 8443:8443 -v $(pwd):/opt/keycloak/certs -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.3 start-dev --https-certificate-file=/opt/keycloak/certs/localhost.crt --https-certificate-key-file=/opt/keycloak/certs/localhost.key --https-key-store-file=/opt/keycloak/certs/localhost.p12 --https-key-store-password=password --https-port=8443 --https-trust-store-file=/opt/keycloak/certs/truststore.jks --https-trust-store-password=password --https-client-auth=required
```

4. Go to Firefox, and enter `https://localhost:8443` and you will see the pop-up because you imported the certificates of Fred Flintstone. In case of a PKCS11-compatible device, The browser should prompt the PIN prompt to unlock the device and read the certificate

<img width="936" alt="certificate" src="https://user-images.githubusercontent.com/34489538/216164797-8890eab5-86f4-45ba-b13f-93776acc4d88.png">

Concerning Safari and Chrome, make sure to trust the root CA in the keychain and import fredFlintstone.p12 in the section `My Certificate` of the keychain

<img width="631" alt="image" src="https://user-images.githubusercontent.com/34489538/216167491-6e97fd94-9a9b-406a-bbeb-c2de313b9ac5.png">

<img width="531" alt="image" src="https://user-images.githubusercontent.com/34489538/216168210-a07857fa-dd9a-4083-a914-f191e25753b9.png">

5. Bonus: Request a token via curl

```bash
curl -XPOST https://localhost:8443/realms/test/protocol/openid-connect/token --cacert rootCA.crt -E fredFlintstone.crt --key fredFlintstone.key -d "client_id=my-client" -d "client_secret=<CLIENT_SECRET>" -d "grant_type=password&scope=openid profile&username=&password=" | jq -r '.access_token'
```

Other note: Mutual-TLS is also working when you want to deploy Keycloak with the operator and even working with an ingress-nginx (Reverse Proxy) with both-side Mutual-TLS (client <- mTLS -> RP <- mTLS -> Keycloak)

Let me know if you have any questions on this topic and don't hesitate to correct me if I said something wrong.

If my response is too out of scope for your use case, I would be glad to have more details of your configuration

**Comment by daurrutia** [comment] 2023-03-27 21:21
Verified this works in v20.0.0. The missing link for me was to ensure the parameter `--https-client-auth` was given the `request` value. This allows for username/password auth to the master realm and X509 pop-ups when the auth flow is configured for X509 in other realms.

**Comment by mposolda** [comment] 2023-04-04 09:53
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Closed** 2024-03-08 08:31 UTC
Labels: area/authentication, kind/bug, team/core-clients

**Comment by mposolda** [comment] 2024-03-08 08:34
I've scheduled this for close as X.509 authentication works in Keycloak as expected. So the issues are typically environment/setup issues rather than Keycloak bugs. At the same time, our docs surely has a space for improvement and it is a bit out-of-date. Creating follow-up issue for improve the docs: https://github.com/keycloak/keycloak/issues/27699 .

Anyone is welcome to send the PR for improving docs.

**Comment by coreycasmedes** [comment] 2024-10-10 21:27
wanted to chime in that if anyone is having trouble importing PKCS#12 formatted certificates (.pfx / .p12 files) into macos keychain it could likely be due to keychain using LibreSSL under the hood

https://discussions.apple.com/thread/254518218?=undefined&previousThread=255082743021&sortBy=rank
