### ISSUE TITLE
token-exchange: invalid_token_type error

### ISSUE THREAD

**Issue by lieven-p** [keycloak/keycloak#30494] opened 2024-06-17 12:19 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

We had token-exchange working in Keycloak version 24.0.2, and it's no longer working when upgrading to 24.0.3 and higher.

The content of the call is build with the following code:
`final FormBody.Builder builder = new FormBody.Builder().add("client_id", keycloakConfiguration.getClientId())
                                                                   .add("grant_type", "urn:ietf:params:oauth:grant-type:token-exchange")
                                                                   .add("subject_token_type", "urn:ietf:params:oauth:token-type:jwt")
                                                                   .add("subject_token", adToken)
                                                                   .add("subject_issuer", issuerName)
                                                                   .add("requested_token_type",
                                                                        "urn:ietf:params:oauth:token-type:refresh_token");` 

The error we're receiving is 'invalid_token_type'

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Able to process the token for token-exchange

### Actual behavior

No longer able to process token for token-exchange.

### How to Reproduce?

- Configure token-exchange in Keycloak 24.0.2 => check that this token-type is accepted
- Upgrade to Keycloak 24.0.3 => check that this token-type is no longer accepted

**Comment by lieven-p** [comment] 2024-06-17 12:25
Can be reproduced against 25.0.0 as well

**Comment by rmartinc** [comment] 2024-06-18 07:59
Hi @lieven-p!

One change between 24.0.2 and 24.0.3 that maybe can affect this issue is https://github.com/keycloak/keycloak/commit/e3edf768678572d0302d83f6a4d477ddf97ddabb. But we need more information to reproduce your issue. 

What type of exchange are you requesting? Another client token in the same realm (internal)? Token from another realm? A token from an external IdP using internal token?

Please when you submit an issue be very specific about what you are doing. The token exchange can be very different depending on what token you are exchanging and what token you are requesting. Please when filing issues be very detailed in the reproducer steps, if you can send a realm import and specific curl or similar, that would be awesome.

**Comment by rmartinc** [comment] 2024-07-08 10:52
I'm closing this as there is no follow up on how we can reproduce this.

**Closed by rmartinc** 2024-07-08 10:52 UTC
Labels: kind/bug, area/token-exchange, status/triage, team/core-clients, status/missing-information

**Comment by AndrejKapusta** [comment] 2024-10-22 07:13
I'm encountering the same issue described above. During token exchange (external to internal), I'm receiving the `invalid_token_type` error. I have a custom identity provider based on `OIDCIdentityProvider`, where I've overridden the `exchangeExternalImpl` method to implement advanced token validations. However, the error occurs when I call the `validateJwt` method.

After investigating further, I think I may have identified the issue. In the `validateJwt` method, the `validateToken` method is executed, which calls `parseTokenInput`. This method returns a JSON string from the encoded token, but the resulting JSON only contains claims from the body section, and the header claims are missing.

Subsequently, the JSON string is serialized into a `JsonWebToken` object, which includes a `type` attribute that corresponds to the `typ` (type) property in the token. Since the header claims are missing, the token type is `null` in the `isTokenTypeSupported` method, causing it to return `false`, which leads to the exception being thrown.
