### ISSUE TITLE
Keycloak CI -> Quarkus IT (ubuntu, zip) -> FipsDistTest.testUnsupportedHttpsJksKeyStoreInStrictMode

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#25213] opened 2023-12-01 14:06 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Fips failure -> affects Quarkus IT job -> Ubuntu, ZIP:

Error: OR] Errors: 
Error: OR]   FipsDistTest.testUnsupportedHttpsPkcs12KeyStoreInStrictMode:110->runOnFipsEnabledDistribution:143->lambda$testUnsupportedHttpsPkcs12KeyStoreInStrictMode$5:112 » Runtime Failed to stop the server

### Version

999.0.0-SNAPSHOT

### Expected behavior

test should pass

### Actual behavior

test fails randomly

### How to Reproduce?

check this link: https://github.com/keycloak/keycloak/actions/runs/7037624642/job/19153111228

**Comment by mposolda** [comment] 2023-12-05 09:42
Still happening. One of latest links: https://github.com/keycloak/keycloak/actions/runs/7073405991/job/19253491056

**Comment by mabartos** [comment] 2023-12-05 10:51
Duplicate of #23786

**Closed by mabartos** 2023-12-05 10:51 UTC
Labels: area/testsuite, kind/bug, area/core, team/core, team/continuous-testing
