### ISSUE TITLE
Enable WebAuthnSigningInTest#checkAuthenticatorTimeLocale test

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#20351] opened 2023-05-15 09:46 UTC
### Description

This test was disabled in #20350 #20349 because of a bug in ChromeDriver. Once version 113.0.5672.92 is available in https://chromedriver.storage.googleapis.com/, the test should be re-enabled.

**Comment by vmuzikar** [comment] 2023-05-17 11:21
Duplicate of https://github.com/keycloak/keycloak/issues/20348

**Closed by vmuzikar** 2023-05-17 11:21 UTC
Labels: area/ci, kind/task, team/continuous-testing
