### ISSUE TITLE
Maven package keycloak-admin-client and keycloak-authz-client missing for version 26.0.1

### ISSUE THREAD

**Issue by qubec26** [keycloak/keycloak#34145] opened 2024-10-21 11:53 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

![image](https://github.com/user-attachments/assets/12c56ab7-ef25-48fe-9fd3-1e58214f85e4)
The packages keycloak-admin-client and keycloak-authz-client are missing 26.0.1 version in maven repository.

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Packages available in maven repository

### Actual behavior

Missing

### How to Reproduce?

Build latest version

**Comment by mposolda** [comment] 2024-10-21 13:33
@qubec26 This is expected Keycloak client libraries for 26.0.1 are not yet released. We are going to release them soon, but not sure about exact time. Please see this for the details: https://www.keycloak.org/docs/latest/release_notes/index.html#dedicated-release-cycle-for-the-client-libraries . I am closing as this is not a bug.

**Closed** 2024-10-21 13:33 UTC
Labels: kind/bug, area/dependencies
