### ISSUE TITLE
Workflow failure: Operator CI - KeycloakDeploymentTest#testPodNamePropagation

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#32709] opened 2024-09-06 10:26 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

There are repeated constant failures on Operator workflow:
`Error:  Errors: 
Error:    KeycloakDeploymentTest.testPodNamePropagation:399 » ConditionTimeout Assertion condition defined as a Lambda expression in org.keycloak.operator.testsuite.utils.K8sUtils found status KeycloakStatusCondition{type='Ready', status=False, message='Waiting for more replicas'} and expected status true within 5 minutes.
[INFO] 
Error:  Tests run: 125, Failures: 0, Errors: 1, Skipped: 0`

`Error:  Tests run: 24, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 953.232 s <<< FAILURE! - in org.keycloak.operator.testsuite.integration.KeycloakDeploymentTest
Error:  org.keycloak.operator.testsuite.integration.KeycloakDeploymentTest.testPodNamePropagation  Time elapsed: 315.853 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a Lambda expression in org.keycloak.operator.testsuite.utils.K8sUtils found status KeycloakStatusCondition{type='Ready', status=False, message='Waiting for more replicas'} and expected status true within 5 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)`

GHA log: https://github.com/keycloak/keycloak/actions/runs/10730132463/job/29758208276#step:8:6991

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment] 2024-09-06 12:57
Duplicate of #32490

**Closed by shawkins** 2024-09-06 12:57 UTC
Labels: kind/bug, area/ci, team/cloud-native, status/triage, team/continuous-testing, flaky-job
