### ISSUE TITLE
Imported users from LDAP get deleted when the bind credentials change

### ISSUE THREAD

**Issue by jhollmannk** [keycloak/keycloak#20177] opened 2023-05-05 08:18 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

When you have a functional LDAP configuration but an LDAP administrator changes the password of the user that is used as the "bind dn" and you correct the bind credentials of the LDAP configuration, all already imported users are deleted.

That leads to a lot of work when you have groups that contain imported users. They are all gone now and you have to rebuild your groups so that the LDAP users get their roles again.

### Version

21.1.1

### Expected behavior

When the LDAP configuration is corrected, the already imported users should still be there and unchanged.

### Actual behavior

It seems the imported users are deleted.

When I get the current user list with a REST call to "admin/realms/test/users" after the password is correct again, only locally created users are retreived.

If you search for "*" in the users view in the admin console, the users get reimported of course. You can see here that the users are reimported as they get new UUIDs.

### How to Reproduce?

I have created a docker-compose to run an openldap server with some pre-defined users to import, so that you can easily change the password in the server: 
[openldap.zip](https://github.com/keycloak/keycloak/files/11404093/openldap.zip)
Unzip the archive and start `docker compose up -d` in the folder. That starts the LDAP server with the standard port 389.

Start Keycloak with `bin/kc start-dev`, create an admin user and a realm `test`.

In the `test` realm create an LDAP user federation with
- Vendor: Other
- Connection URL: ldap://localhost
- Bind DN: cn=admin,dc=playground
- Bind credentials: admin
- Edit mode: READ_ONLY
- Users DN: dc=company,dc=playground

The other settings can stay on their default.

Sync all users for this LDAP configuration which creates 5 users. Search for the user `a-user1` and memorize its UUID.

Stop the LDAP server with `docker compose down` and change the `LDAP_ADMIN_PASSWORD` in the docker-compose.yml to something else like `udmin`.

Now correct the bind credentials of the LDAP configuration to the new value `udmin` and save the corrected configuration.

Now if you search for the user `a-user1` again and lookup its UUID it has changed. Or call the REST endpoint to get all users and see that you only get local users (if you have created any).

This does not happen when you change the bind credentials of the LDAP configuration in Keycloak to a wrong value and back again. As long as the LDAP configuration does not work the "/users" enpoint returns a HTTP status code 400 and the content
```
[]{
    "error": "unknown_error"
}
``` 
I guess the `[]` comes from the local user storage and the `{"error": "unknown_error"}` comes from the LDAP user storage. A valid JSON this is not.
After you correct the password again in this case, the imported LDAP users are still there and unchanged. I don't know why this is different from the case where the LDAP configuration was broken because the password was changed on the LDAP server side.

**Comment by sguilhen** [comment] 2023-05-17 22:16
I think this has nothing to do with the credentials change, but with the connection between Keycloak and the LDAP server. You can reproduce the same behavior by simply re-starting the LDAP server and searching for the users again. No need to change credentials whatsoever.  I've tested on a few different Keycloak versions, from 18.0.2 to the most recent, and it always changes the user id if the LDAP server is restarted.

@hmlnarik I don't know if this is a bug or expected behavior. It looks like Keycloak will re-synch users if the connection to the LDAP server changes, and it seems that this has always been the behavior.

**Comment by hmlnarik** [comment] 2023-05-18 11:22
@sguilhen Is the LDAP UUID (`entryUUID`) the same for the objects upon restart?

**Comment by sguilhen** [comment] 2023-05-18 11:56
@hmlnarik yes, it does. I searched `entryUUID` of the users in the LDAP server before and after the restart and they are indeed different

**Comment by hmlnarik** [comment] 2023-05-19 08:42
Thank you. The important bit is that restart suffices which led to the information that the LDAP users are reimported instead of restored from backup, thus the users are different.

The users are indeed different because their ID is the `entryUUID`, not `cn`. The sync proceeds correctly:
- previously existing users are not found in LDAP and are thus removed
- new users that happen to have the same DN  are created fresh in Keycloak. 

Thus closing as not a bug

**Closed by hmlnarik** 2023-05-19 08:42 UTC
Labels: kind/bug, area/ldap, team/store, status/triage
