### ISSUE TITLE
Child groups filtering returns all groups

### ISSUE THREAD

**Issue by transducer** [keycloak/keycloak#28818] opened 2024-04-16 15:48 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When filtering subgroups all groups are returned.

<img width="701" alt="Screenshot 2024-04-16 at 17 45 30" src="https://github.com/keycloak/keycloak/assets/5002921/0e8c076b-449e-4f4a-a57f-6c37ee9b23bd">
 

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

When filtering a group's subgroups by name, only the groups that contain that name are returned (preferably case insensitive).

### Actual behavior

When filtering a group's subgroups by name, all subgroups are returned.

### How to Reproduce?

```
docker run -p 8081:8080 \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  quay.io/keycloak/keycloak:24.0.2 start-dev
```
- Navigate to localhost:8081
- Create a top level group named BAR
- Create child groups named foo, quz and BLA
- Filter for BLA
- See foo, bar and BLA in the list.

**Comment by transducer** [comment] 2024-04-16 15:49
Also see discussion in https://github.com/keycloak/keycloak/issues/20445

**Comment by ssilvert** [comment] 2024-04-16 21:22
As far as I can tell, this just doesn't work at all.  If you are searching from a child group, it just returns all the children.

And looking at the network call, it's not even doing a search.  It's just asking for the children, which explains a lot.

**Comment by edewit** [comment] 2024-04-17 08:48
Seems that searching / filtering in a subgroup is no longer supported by the API. The fix would be to remove the search field for subgroups, users will have to use search instead.

**Comment by hmlnarik** [comment] 2024-04-17 11:21
> Seems that searching / filtering in a subgroup is no longer supported by the API.

Do you have any reference to that? If that is so, it could be an regression in REST API which needs either documenting or fixing in the core. /cc @keycloak/core-maintainers

**Comment by ssilvert** [comment] 2024-04-18 20:28
Also see comments on #28835

**Comment by pedroigor** [comment] 2024-04-18 21:44
Based on https://github.com/keycloak/keycloak/issues/20445#issuecomment-1935866733, I'm also wondering how this was working before.

@transducer Do you know the version where searching child groups is working as you are suggesting?

**Comment by transducer** [comment] 2024-04-19 07:14
@pedroigor it works in 22.0.3 (only case sensitive search though) and stops working in 23.0.0.

It's likely related to [this performance upgrade](https://github.com/keycloak/keycloak/issues/22261), where `GET /auth/admin/realms/{realm}/groups/{id}` no longer returns subgroups and we should now explicitly call `GET /auth/admin/realms/{realm}/groups/{id}/children` to fetch children (with pagination). See also [this issue](https://github.com/keycloak/keycloak/issues/25053) and the [GroupRepresentation changes in the 23.0.0 upgrading guide](https://www.keycloak.org/docs/23.0.0/upgrading/index.html#grouprepresentation-changes):


> - new field `subGroupCount` added to inform client how many subgroups are on any given group
> - `subGroups` list is now only populated on queries that request hierarchy data
> - This field is populated from the "bottom up" so can’t be relied on for getting all subgroups for a group. Use a `GroupProvider` or request the subgroups from `GET {keycloak server}/realms/{realm}/groups/{group_id}/children`

**Comment by ssilvert** [comment] 2024-04-19 12:46
@pedroigor I marked this as a regression because from a purely objective standpoint, it is a regression.  And since it is a regression it is classified as a blocker.

But there is a workaround already, which is to use the search provided in the lefthand tree pane.  I'll leave it up to @transducer and others if they want to argue that this is not an acceptable workaround.

I think that even though as a general rule we treat all regressions as blockers, it's possible that we could make an exception here.

**Comment by sguilhen** [comment] 2024-04-22 12:15
@edewit @ssilvert I think that the proper way to fix this is to adjust the endpoint to accept the search string - the group provider already supports this search, it should be a matter of adjusting the endpoint so it accepts the search string.

I'll try to get into it later this week, so please for now refrain from merging the PR that removes the search box.

**Closed** 2024-04-25 15:06 UTC
Labels: kind/bug, priority/blocker, area/admin/ui, team/ui, team/core-iam, kind/regression
