### ISSUE TITLE
auth_time claim missing

### ISSUE THREAD

**Issue by cturkalj** [keycloak/keycloak#31572] opened 2024-07-24 10:50 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

The "auth_time" claim is not set in token, although mapping is configured via client scope "basic".

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

When client contains "basic" client scope, auth_time claim should provided as configured in mapper for "auth_time".

### Actual behavior

When client contains "basic" client scope, auth_time claim is not added to tokens.

### How to Reproduce?

Create a new client with "basic" added as client scope (should already be included per default).
Access Token should contain "sub" and "auth_time" from "basic" client scope but the auth_time claim is not present. 

### Anything else?

After some debugging it seems that the user session note "AUTH_TIME" for the "auth_time" claim to be filled is never set.

**Comment by rmartinc** [comment] 2024-07-29 10:11
If the problem is the AUTH_TIME is not in the user session the mapper is never going to add the claim in the token. So the question here is why the note is not in the session. I tried to reproduce and in my env the `auth_time` claim is added correctly. So we are missing something here to understand your issue.

Is this problem happening only in one client or in all clients? For example, do you see the `auth_claim` when you use the account console of the realm `https://server/realms/<realm>/account`?
Are you using the default flow to authenticate or a new one?

We need more info to reproduce this.

**Comment by cturkalj** [comment] 2024-08-01 11:19
So after some further debugging with 25.0.2 and 24.0.5 (@rmartinc thanks for the hint) I can conclude that the missing auth_time or rather the missing note in the user session was due the Resource Owner Password Credentials grant our regression tests used.
In 24.0.5 the id token contained the auth_time claim but the value was always '0' for direct grants, for the standard flow it contained the correct auth time.
In 25.0.2 the id token from a standard flow still contains the correct auth_time.

I'll close the issue.

**Comment by rmartinc** [comment] 2024-08-01 13:35
Thanks @cturkalj! Closing as requested.

**Closed by rmartinc** 2024-08-01 13:35 UTC
Labels: area/oidc, kind/bug, status/triage, team/core-clients
