### ISSUE TITLE
Non working API docs link

### ISSUE THREAD

**Issue by nextMJ** [keycloak/keycloak#19154] opened 2023-01-26 14:33 UTC
### Describe the bug

At page https://www.keycloak.org/docs/latest/server_development/ right before headline `Themes` is link to `API documentation` 
which is currently pointing to https://www.keycloak.org/docs/21.1.1/api_documentation/. This is OK. However on that page, there are links to
- Javadocs documentation, which is https://www.keycloak.org/docs-api/21.1/javadocs/ , but should be https://www.keycloak.org/docs-api/21.1.1/javadocs/
- Admin REST API documentation, which is https://www.keycloak.org/docs-api/21.1/rest-api/, but should be https://www.keycloak.org/docs-api/21.1.1/rest-api/

## Old description (outdated)
```
At page https://www.keycloak.org/docs/latest/server_development/ right before headline `Themes` is link to `API documentation` (2 times!) which is currently pointing to https://www.keycloak.org/docs/20.0/api_documentation/ which doesn't exist. The problem is that `20.0` should be either `20.0.3` or `latest`. It works with both but not with `20.0`.

It can be edited in [this file](https://github.com/keycloak/keycloak-documentation/blob/main/server_development/topics/admin-rest-api.adoc). I just don't know how.

*EDIT: I just found out that the problem is propagated also to the https://www.keycloak.org/docs/latest/api_documentation/ where all links points to version `20.0` (even when asking for `latest` in URL.*
```

**Comment by pedro-hos** [comment] 2023-03-27 23:22
I don't know if the issue is during  the build, or we should use `project_versionLinks` instead of `project_versionDoc` on all `apidocs_` links:

~~~
:project_versionDoc: DEV

ifeval::["{project_buildType}" == "latest"]
:project_versionLinks: latest
endif::[]
ifeval::["{project_buildType}" == "archive"]
:project_versionLinks: {project_versionDoc}
endif::[]

:apidocs_link: https://www.keycloak.org/docs/{project_versionDoc}/api_documentation/
:apidocs_javadocs_link: https://www.keycloak.org/docs-api/{project_versionDoc}/javadocs/
:apidocs_adminrest_link: https://www.keycloak.org/docs-api/{project_versionDoc}/rest-api/
~~~

Also,  idk if the `ifeval::["{project_buildType}" == "latest"]` is working. I am running `mvn clean install -Dlatest -Dinsecure.repositories=WARN -DskipTests` but the `project_buildType` was never latest.

**Comment by abstractj** [comment] 2023-05-15 22:19
@nextMJ it seems that the issue reported on https://www.keycloak.org/docs/latest/server_development/ was fixed. Please see https://ibb.co/7WyTC4c:

![output](https://ibb.co/7WyTC4c)

The issue is still present on https://www.keycloak.org/docs/latest/api_documentation/ and should be fixed.

**Comment by mposolda** [comment] 2023-05-19 13:51
Adding to 22 for now, but we can eventually postpone this.

**Comment by mposolda** [comment] 2023-07-19 09:04
Closing as this issue seems to be already fixed. The API Docs page from https://www.keycloak.org/docs/22.0.1/api_documentation/ contains correct links to javadoc and admin REST API docs.

**Closed by mposolda** 2023-07-19 09:04 UTC
Labels: kind/bug, impact/low, area/docs
