### ISSUE TITLE
Brute force detection - Can't lockout user for more than a single 'Wait Increment' duration

### ISSUE THREAD

**Issue by ygoldner1** [keycloak/keycloak#20353] opened 2023-05-15 09:57 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I can't seem to lockout any user for more than one duration of 'Wait Increment'.

![image](https://github.com/keycloak/keycloak/assets/133647717/0231ac7b-72a5-4c5c-994c-d5f6ea540610)

### Version

21.1.1

### Expected behavior

When going over the step described in the 'How to Reproduce?' section, I expect the user to be locked for longer than 1 minute.

### Actual behavior

User gets locked for a single duration of Wait Increment, and actual locking time does not reach Max Wait.

### How to Reproduce?

1. I set the following values in the brute force detection:
Wait increment = 1 min
Max wait = 6 min
Max login failures = 2

2. I go to the UI and fail to login twice -> user is temporarily locked
3. I fail to login 10 more times, **while the user is still locked**.
4. I expect the lockout time to grow, as a result of these 10 additional failures, but the user is only locked for 1 minute (a single duration of Wait Increment).

**Comment by mposolda** [comment] 2023-05-18 10:53
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:

- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
- If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here https://www.keycloak.org/community for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by jzimmermann** [comment] 2023-10-13 07:15
> I fail to login 10 more times, while the user is still locked.

The failure count will not increase by failing logins while the user is temporarily disabled, so this has no impact on the applied wait timeout. This is also stated in the [documentation](https://www.keycloak.org/docs/latest/server_admin/#password-guess-brute-force-attacks) section Temporary Lockout Algorithm where it says
> count does not increment when a temporarily disabled account commits a login failure.

**Comment by jinzai07** [comment] 2023-11-29 09:41
I had the exact observation of the behavior described but as @jzimmermann pointed out, based from documentation the count does not increment if user is temporarily disabled.
I have observed this from adding breakpoints on DefaultBruteForceProtector class's failure method

**Comment by gilvansfilho** [comment] 2023-12-05 14:15
But after the user is unlocked (after 1 minute), a new wrong attempt should increase the waiting time. 

Therefore, after two failed attempts, the user should be blocked for 1 minute. After that time a new failure should block user for 2 minutes. That increase should happens for each new failure until 6 minutes, as defined at max wait time.

But that not happens.

Perhaps I may help with that.

**Comment by pedroigor** [comment] 2023-12-22 01:27
I'm not sure if this is a bug but an expected behavior as mentioned in some of the previous comments.

> But after the user is unlocked (after 1 minute), a new wrong attempt should increase the waiting time.

The thing is that the max wait time is to make sure the failure state is reset after the max time, not really a point you'll reach after subsequent failure attempts. The wait time is not increased because the number of failed attempts is reset (as well as other failure states).

We should consider reviewing our documentation and perhaps introduce an option that supports incrementing the wait time even when the user is disabled.

FTR, this has been discussed here https://issues.redhat.com/browse/KEYCLOAK-5420.

**Comment by gilvansfilho** [comment] 2023-12-22 12:14
> The thing is that the max wait time is to make sure the failure state is reset after the max time,

That is `failure reset time`. `Max Wait` is Max time a user will be locked out (after somes `Wait Increment`)

> FTR, this has been discussed here https://issues.redhat.com/browse/KEYCLOAK-5420.

That example is bad once all options is defined as 15 minutes. So becomes hard to know what expect.

**Comment by pedroigor** [comment] 2024-01-08 13:29
I'm closing this PR in favor of https://github.com/keycloak/keycloak/issues/25914. Mainly https://github.com/keycloak/keycloak/issues/25917.

**Closed by pedroigor** 2024-01-08 13:29 UTC
Labels: area/authentication, kind/bug, team/rh-iam, status/triage, team/core
