### ISSUE TITLE
Update user email ignored (Keycloak Admin) in case "Email as username" is configured for realm.

### ISSUE THREAD

**Issue by onmomo** [keycloak/keycloak#23440] opened 2023-09-21 13:06 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

It is no longer possible to update the email address of a user in case the realm is configured with "Email as username" enabled using the REST api / keycloak admin client.

### Version

22.0.3 / nightly

### Expected behavior

Updating the email address should actually update the user email and also update the username as it did in previous versions (eg <= 21.1.2) in case the realm is configured with "Email as username".
Furthermore, the admin UI should not require to input the username and only show the email field. 
Please find the screenshot from 20.0.5 with "Email as username" enabled.

![Screenshot 2023-09-21 at 14 44 26](https://github.com/keycloak/keycloak/assets/1713109/68387a8a-7743-4127-b1d2-fd16c8b0b1df)

Realm config

<img width="321" alt="Screenshot 2023-09-21 at 15 03 29" src="https://github.com/keycloak/keycloak/assets/1713109/672e865f-cf68-4462-8277-dc922cabcc21">

We actually don't want to deal with the username of our users and rather rely completely on the email of the user.

### Actual behavior

Updating the user email address does actually have no effect causing a major regression in our application in case the realm is configured with "Email as username".

Please find the screenshot from 22.0.3 / nightly with "Email as username" enabled, that now requires the username to be set and ignores email updates via REST API.

![Screenshot 2023-09-21 at 14 45 31](https://github.com/keycloak/keycloak/assets/1713109/2354d7ea-7acd-4383-8c60-4bf426f6184a)

Realm config

<img width="321" alt="Screenshot 2023-09-21 at 15 03 29" src="https://github.com/keycloak/keycloak/assets/1713109/672e865f-cf68-4462-8277-dc922cabcc21">

### How to Reproduce?

Easily reproducible with the latest nightly build. Please find the screencast.

https://github.com/keycloak/keycloak/assets/1713109/d7b178ba-d179-4c54-80f2-370217cff078

 

### Anything else?

Are there any long term plans on username / email handling in keycloak going forward?

**Comment by pedroigor** [comment] 2023-09-22 13:45
@onmomo I noticed you checked nightly but can you check it again?

The behavior you are reporting is not happening anymore. If you have `Edit username allowed` disabled, the fields should be disabled. We still have the `Username` field visible though when `Email as username` is enabled, we should improve this.

**Comment by onmomo** [comment] 2023-09-22 16:03
> @onmomo I noticed you checked nightly but can you check it again?
> 
> The behavior you are reporting is not happening anymore. If you have `Edit username allowed` disabled, the fields should be disabled. We still have the `Username` field visible though when `Email as username` is enabled, we should improve this.
> 
> IIRC, it is a known issue where the admin console us fetching the user profile configuration rather than the metadata for a particular user.
> 
> @edewit Do you remember the issue we are discussing this?

@pedroigor Unfortunately, it behaves exactly as before with the latest nightly. Configuring the realm like this:

<img width="374" alt="Screenshot 2023-09-22 at 17 59 02" src="https://github.com/keycloak/keycloak/assets/1713109/5ff206fe-9456-4602-9691-031d4fe454d1">

still won't allow to update the user email address. This counts for existing users but also during user creation.

test env
```
docker pull quay.io/keycloak/keycloak:nightly        
docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:nightly start-dev
```

nightly
```
docker image inspect quay.io/keycloak/keycloak:nightly                                                             
[
    {
        "Id": "sha256:19b5fb1296c62d0c0bc08803ff59921f87fcf594da0fac8f65cf7b98073f9cf7",
        "RepoTags": [
            "quay.io/keycloak/keycloak:nightly"
        ],
        "RepoDigests": [
            "quay.io/keycloak/keycloak@sha256:b3787075e6871244d6892a0e4f99a58b5a53c8d79635162ff63577e775b362b5"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-09-22T01:37:19.228575675Z",
        "Container": "",
        "ContainerConfig": {
...
```

**Comment by pedroigor** [comment] 2023-09-22 20:35
@onmomo Sorry, I was assuming you were using the declarative user profile. The UI behaves differently when `User profile` is enabled and aligned with the latest changes in this area.

This issue is also related to https://github.com/keycloak/keycloak/issues/23438.

**Comment by onmomo** [comment] 2023-09-22 21:35
> @onmomo Sorry, I was assuming you were using the declarative user profile. The UI behaves differently when `User profile` is enabled and aligned with the latest changes in this area.
> 
> 
> 
> This issue is also related to https://github.com/keycloak/keycloak/issues/23438.

No worries. The referenced issue seems to describe the exact same thing.

**Comment by pedroigor** [comment] 2023-09-22 21:49
Closed in favor of https://github.com/keycloak/keycloak/issues/23438.

**Closed by pedroigor** 2023-09-22 21:49 UTC
Labels: kind/bug, area/user-profile, status/triage, team/ui

**Comment by jonkoops** [comment] 2023-09-25 08:37
Duplicate of #23438.
