### ISSUE TITLE
v22.0.0 : Loop accessing admin console through Firefox

### ISSUE THREAD

**Issue by tlebars** [keycloak/keycloak#21784] opened 2023-07-18 12:28 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hello,

By logging into the administrator console from a Firefox browser, I (and a colleague) encounter a continuous page reloading issue that prevents me from accessing the Keycloak administration. The problem does seem to occur randomly on Brave browser. Safari appears to be functioning correctly.

Here is the error displayed in the browser:

```text
Unexpected Application Error!
Network response was not OK.
NetworkError@https://mydomain/resources/rvy5p/admin/keycloak.v2/assets/index-0cda761d.js:67:121191
fetchWithError@https://mydomain/resources/rvy5p/admin/keycloak.v2/assets/index-0cda761d.js:67:121366
```
and:

```text
error loading dynamically imported module: https://mydomain/resources/rvy5p/admin/keycloak.v2/assets/Dashboard-8ea6981b.js
```
And log from the Docker container:

```text
WARN [org.keycloak.events] (executor-thread-313) type=REFRESH_TOKEN_ERROR, realmId=[realmId], clientId=security-admin-console, userId=null, ipAddress=[ipAddress], error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```

- Clearing the browser cache and switching to private mode does not resolve the issue.
- The problem emerged after upgrading from version 21.1.1

Thank you for your help.

### Version

22.0.0

### Expected behavior

Access the administration console

### Actual behavior

Continuous reloading page

### How to Reproduce?

Not sure how to get a procedure to reproduce the issue.

**Comment by jonkoops** [comment] 2023-07-22 14:36
Duplicate of #14666

**Closed by jonkoops** 2023-07-22 14:36 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
