### ISSUE TITLE
Can't join a node under certain conditions

### ISSUE THREAD

**Issue by corradocavalli** [keycloak/keycloak#9345] opened 2021-12-27 13:17 UTC
### Describe the bug

Consider this group structure https://ibb.co/JxrjMqr looks like a user can't join the Volvo group is already member of cp:admin group despite the "success" message.
The opposite works fine.

### Version

15.0.2

### Expected behavior

Being able to add the user to Volvo group

### Actual behavior

Interface says success but node is not listed among joined.

### How to Reproduce?

Create the same structure, join the same groups using Admin user and try to join Volvo group.

**Comment by rmartinc** [comment] 2023-02-17 10:15
I have tried in the current 22.0.3 and you can assign both with the new console. In this example I have groups `/group1/group12/group121` and the user is assigned to `/group1` and to `/group1/group12/group121`. I could assign him to both groups without issues:

![groups](https://user-images.githubusercontent.com/26901232/219615536-e6e03eff-7ac5-490e-ae97-76de2616e4f6.png)

Groups `group1` and `group121` are directly assigned and `group12` is indirect. Remember that users that belong to a subgroup inherit the attributes and role mappings from their parent as well (see [doc](https://www.keycloak.org/docs/20.0.3/server_admin/#proc-managing-groups_server_administration_guide)).

I'm closing this, just comment if you have any doubt. Thanks!

**Closed by rmartinc** 2023-02-17 10:15 UTC
Labels: kind/bug, area/admin/api, status/triage

**Comment by PeterMue** [comment] 2023-07-03 14:29
We're facing the same issue and i think it's more a bug than a feature.
Consider the following Group structure:
```
.
└── A
    └── B
        └── C
```

I'm able to join the user to group A, then to B and finally to C. When joining in this order, the user is explicit in every single group (i.e. there are three rows in the USER_GROUP_MEMBERSHIP table).

But when joining the user in reverse order, thus first top C then to B and finally to A, the user is only in group C explicit and in group B and A implicit (i.e. there is only one row in the USER_GROUP_MEMBERSHIP table).

From a user perspective, there is no difference between both: the user has in both cases all the roles from A, B and C.

The problem arises in our case when we remove the user from a group. In our case keycloak is not the primary storage for the group memberships, instead we store them in another system and synchronize the membership changes to keycloak.
Our centralized knows, that the user is in the keycloak group "A", "A/B" and "A/B/C".
When synchronizing with keycloak we may join group "A/B/C" first and then the other two (we're not able to control the order as this can happen at different times). Which results in one explicit group membership of C and two implicit (B and A).
Later we remove the user from group "A/B/C" in our centralized system, sync this group-leave to keycloak and remove the user from group C.
In that case, the user looses all Roles in keycloak as he is in no group at all (at the same time in the centralized system the user is still member of "A" and "A/B").

From my point of view it's a bug because:
* joining in the groups in the right order is possible and perfectly fine
* the api returns a successful response when joining a group the user is implicit member (but in fact does nothing)

IMHO the problem is this check: https://github.com/keycloak/keycloak/blob/51873d6176e7089ab35a91592662440424fcffed/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L1033-L1036
As `user.getGroupsStream` returns a "caluclated" view of all groups the user is member of (no matter if explicit or implicit).
For the example above, if a user is just member of group C, the method return a stream of size 3: A, B, C.
Thus the if body is skipped and the method returns without an error but also without doing anything.

**Comment by rmartinc** [comment] 2023-07-03 15:13
@PeterMue I can join the user from C to A too. At least with the last version21.1.2:

```
./kcadm.sh update users/7cb8fed6-252b-4599-8a6c-c244143ba2b0//groups/f65cb282-b5c8-4569-b9f0-899cdb7c08dd
/kcadm.sh get users/7cb8fed6-252b-4599-8a6c-c244143ba2b0/groups
[ {
  "id" : "f65cb282-b5c8-4569-b9f0-899cdb7c08dd",
  "name" : "C",
  "path" : "/A/B/C"
} ]
./kcadm.sh update users/7cb8fed6-252b-4599-8a6c-c244143ba2b0//groups/8636ac90-7f09-477d-9caa-0f83318de562
./kcadm.sh get users/7cb8fed6-252b-4599-8a6c-c244143ba2b0/groups
[ {
  "id" : "8636ac90-7f09-477d-9caa-0f83318de562",
  "name" : "B",
  "path" : "/A/B"
}, {
  "id" : "f65cb282-b5c8-4569-b9f0-899cdb7c08dd",
  "name" : "C",
  "path" : "/A/B/C"
} ]
./kcadm.sh update users/7cb8fed6-252b-4599-8a6c-c244143ba2b0//groups/6e957e69-7f57-46e0-8851-59d17b8facbb
./kcadm.sh get users/7cb8fed6-252b-4599-8a6c-c244143ba2b0/groups
[ {
  "id" : "6e957e69-7f57-46e0-8851-59d17b8facbb",
  "name" : "A",
  "path" : "/A"
}, {
  "id" : "8636ac90-7f09-477d-9caa-0f83318de562",
  "name" : "B",
  "path" : "/A/B"
}, {
  "id" : "f65cb282-b5c8-4569-b9f0-899cdb7c08dd",
  "name" : "C",
  "path" : "/A/B/C"
} ]
```

Same from A to C:

```
./kcadm.sh update users/7cb8fed6-252b-4599-8a6c-c244143ba2b0//groups/6e957e69-7f57-46e0-8851-59d17b8facbb
./kcadm.sh update users/7cb8fed6-252b-4599-8a6c-c244143ba2b0//groups/8636ac90-7f09-477d-9caa-0f83318de562
./kcadm.sh update users/7cb8fed6-252b-4599-8a6c-c244143ba2b0//groups/f65cb282-b5c8-4569-b9f0-899cdb7c08dd
./kcadm.sh get users/7cb8fed6-252b-4599-8a6c-c244143ba2b0/groups
[ {
  "id" : "6e957e69-7f57-46e0-8851-59d17b8facbb",
  "name" : "A",
  "path" : "/A"
}, {
  "id" : "8636ac90-7f09-477d-9caa-0f83318de562",
  "name" : "B",
  "path" : "/A/B"
}, {
  "id" : "f65cb282-b5c8-4569-b9f0-899cdb7c08dd",
  "name" : "C",
  "path" : "/A/B/C"
} ]
```

I'm using kcadm to avoid the console. So I don't think this is a problem of teh endpoint.

**Comment by PeterMue** [comment] 2023-07-04 07:22
Thanks for clarifying, you're right its not a problem anymore.
I'm sorry i've testes with a older version.

The problem and the fix is addressed in this issue: https://github.com/keycloak/keycloak/issues/9482 and released with version 20.
