### ISSUE TITLE
Admin console not usable when instance has a 1000 realms

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak#32029] opened 2024-08-09 13:16 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

this issue is a re-opening of https://github.com/keycloak/keycloak/issues/31956 

When trying to access the admin UI, the endpoint to retrieve all realms is called: /admin/realms/master/ui-ext/realms/names which loads all realms from DB (one at a time) then checks if the user can access them (again loading from DB one at a time) which again loads the client of the realm (one at a time) to check if the user has the required role to manage/view the realm. Doing this a 1000 times take more than 60 seconds causing the TransactionReaper to intervene an close the connection.

The implemented solution doesn't fix the problem when filtering, as filtering is done two late on the process.
As I tried to explain in my response:

Half of the time is spent  on retrieving all realms.
```
query.getResultStream().map(session.realms()::getRealm).filter(Objects::nonNull)
```
getRealm is very expensive. 

There are two ways to fix this:
1. make getRealm less expensive
2. make getRealmsStream() take a string param to search by name.
Change getAllRealmIds in this code and use something like getAllRealmIdsAndNames and filter on that before calling getRealm
```
@Override
    public Stream<RealmModel> getRealmsStream() {
        TypedQuery<String> query = em.createNamedQuery("getAllRealmIds", String.class);
        return getRealms(query);
    }
```

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Be able to use the Admin GUI

### Actual behavior

Unable to filter Realms correctly

### How to Reproduce?

Create a 1000 realms and open the admin console.
try to filter with a name

**Comment by sschu** [comment] 2024-08-09 15:08
Closing as duplicate of https://github.com/keycloak/keycloak/issues/31956.

**Closed by sschu** 2024-08-09 15:08 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
