### ISSUE TITLE
SAML Response SignatureValue, X509Certificate and Modulus have newline chars every 76 characters

### ISSUE THREAD

**Issue by terahertz5k** [keycloak/keycloak#16561] opened 2023-01-20 19:18 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

saml

### Describe the bug

We recently updated from 16.1.0 (wildfly) to 20.0.2. One client in particular stopped accepting our saml responses, and when comparing the saml responses from 16.1.0 to 20.0.2, the only real difference are newlines every 76 characters in SignatureValue, X509Certificate and Modulus elements. 16.1.0 did not have these newlines.

Is having newlines in these elements to spec? Or is this a regression?

16.1.0:
![image](https://user-images.githubusercontent.com/4625079/213786450-fd870eba-4dda-43a5-91a9-e70b9421211a.png)
20.0.2:
![image](https://user-images.githubusercontent.com/4625079/213786350-d079fa77-811a-4845-8528-a990e8287fdf.png)

### Version

20.0.2

### Expected behavior

Expected the saml response in 20.0.2 to be the same as 16.1.0.

### Actual behavior

Newline characters every 76 characters in the SignatureValue, X509Certificate and Modulus elements.

### How to Reproduce?

Diff the saml response from 16.1.0 and 20.0.2.

**Comment by ericalexanderorg** [comment] 2023-01-31 22:49
Seeing the same issue and is similar to what's described in this mailing list posting:
https://lists.jboss.org/pipermail/keycloak-user/2018-October/015881.html

The <dsig:X509Certificate>, <dsig:Modulus>, and <dsig:SignatureValue> values have carriage returns "&#xd;". 

Intercept and remove those carriage returns and the SP accepts the SAML message.

**Comment by rmartinc** [comment] 2023-03-08 14:19
Duplicate of #14529. As @mhvis commented this was fixed in 20.0.5. Closing it now.

**Closed by rmartinc** 2023-03-08 14:19 UTC
Labels: area/saml, kind/bug, status/triage
