### ISSUE TITLE
Keycloak 26: Not al realms are displayed in the list

### ISSUE THREAD

**Issue by iliuta** [keycloak/keycloak#33616] opened 2024-10-06 13:17 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I've just migrated to Keycloak 26 from 25.0.6.
I have more than 10 realms.

I am loading the admin console and want to switch to a particular realm.
I click on the realm dropdown menu and I cannot find it in the list.
I click on the "Next" link on the dropdown menu.

The XHR request (https://my-keycloak-host-name/auth/admin/realms/master/ui-ext/realms/names?first=10&max=11&search=) correctly retrieves the expected values with that particular realm in it but it is still not displayed in the dropdown menu.

Also the search is not working. The XHR corresponding request retrieves though the correct answer when search field is valuated. But in the UI I my realm is still not displayed.

When directly loading the realm's URL, this is loaded in the GUI.

https://my-keycloak-host-name/auth/admin/master/console/#/realm-name

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

All realms should be visible in the realms dropdown menu.
Search should be working.

### Actual behavior

When more than 10 realms configured, not all of them are displayed.

### How to Reproduce?

Create 15 realms.
Load the admin console and navigate through realm list.

**Comment by iliuta** [comment] 2024-10-06 13:30
I've somehow managed to make it work: delete session/local storage and cookies in the browser for the Keycloak host. The realms came back. But it's frustrating.

**Comment by iliuta** [comment] 2024-10-06 13:33
I thought I managed to make it work, by removing local/session storage and cookies. The realms came back all.
But 2 or 3 click later, it went back to the initial situation.

**Comment by edewit** [comment] 2024-10-10 08:26
sorry but I'm not able to reproduce this, I did see a problem that is was closing the dropdown when I clicked next so created a PR for that

**Comment by iliuta** [comment] 2024-10-10 08:53
Indeed, when I work on a private browser window, I don't see the problem. When I come back to my main, non private, browser window, the problem appears.

Yes, clicking on next/previous closes the dropdown and this is annoying. Thanks.

**Comment by codespearhead** [comment] 2024-10-14 00:59
I couldn't reproduce it either when I tried it in the latest versions of Mozilla Firefox (131.0.2), Google Chrome (129.0.6668.101), and Microsoft Edge (129.0.2792.89).

Make sure you're using the latest version of one of the supported web browsers [1].

[1] https://access.redhat.com/articles/7033107#:~:text=Browser

**Closed** 2024-10-14 09:06 UTC
Labels: kind/bug, priority/blocker, area/admin/ui, team/ui, status/auto-expire, status/missing-information, kind/regression

**Comment by meveno** [comment] 2024-11-25 09:57
We're having the same problem on our keycloak v26.0.5
When on the master realm, the other realm are well listed but when selecting one of the realm, the menu won't show any realm list again until going back to the master realm by modifying the URL in our navigator.

![image](https://github.com/user-attachments/assets/5171d190-30b9-4fc5-b2ee-762c38ce4998)

We only have 3 additionnal realm (+ master).

**Comment by iliuta** [comment] 2024-11-25 10:09
Yes, this is exactly like this for me as well. Also, some of my team members have the same issue. So I guess I wasn't dreaming ...

**Comment by jonkoops** [comment] 2024-11-25 10:12
If you are still having this issue on the latest version of Keycloak please report a new issue. We cannot track and triage comments on a closed issue.

**Comment by edewit** [comment] 2024-11-26 12:48
could be fixed by: #35128
