### ISSUE TITLE
Joining group with text filter does not show all results even if backend returned them

### ISSUE THREAD

**Issue by davidezordan25** [keycloak/keycloak#32419] opened 2024-08-27 10:14 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In Users -> Groups page, joining group and entering a text filter, e.g. "pro" in my case, there should be three results ("Intranet - Project Coordinator", "Intranet - Project Manager" and "project-test") 
They are correctly represented in record number in bottom right, also in the backend response 
(groups?first=0&max=11&search=pro)

[
    {
        "id": "65ccda8c-d10d-4891-a3c6-0ff4466b16e0",
        "name": "Intranet - Project Coordinator",
        "path": "/Intranet - Project Coordinator",
        "subGroupCount": 0,
        "subGroups": [],
        "access": {
            "view": true,
            "viewMembers": true,
            "manageMembers": true,
            "manage": true,
            "manageMembership": true
        }
    },
    {
        "id": "d9c7ba25-aa85-4664-a296-4d69deec401a",
        "name": "Intranet - Project Manager",
        "path": "/Intranet - Project Manager",
        "subGroupCount": 0,
        "subGroups": [],
        "access": {
            "view": true,
            "viewMembers": true,
            "manageMembers": true,
            "manage": true,
            "manageMembership": true
        }
    },
    {
        "id": "9de53528-3008-4507-8ca7-dafff4ff4bcd",
        "name": "project-test",
        "path": "/project-test",
        "subGroupCount": 0,
        "subGroups": [],
        "access": {
            "view": true,
            "viewMembers": true,
            "manageMembers": true,
            "manage": true,
            "manageMembership": true
        }
    }
]

But only one result is shown in the frontend page:

![image](https://github.com/user-attachments/assets/2cafedcd-ab3e-4ee0-9ae0-85d7a693fcc7)

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Three results should also be shown in the frontend page

### Actual behavior

Only one result is shown in the frontend tab, even if record number and backend response contain three results.

### How to Reproduce?

1. Create following groups: "Intranet - Project Coordinator", "Intranet - Project Manager", "project-test"
2. Try to join group by searching "pro" in text filter
3. Only project-test is shown

**Comment by ssilvert** [comment] 2024-08-28 02:20
@davidezordan25 I believe this is a duplicate of https://github.com/keycloak/keycloak/issues/31386

Can you try it out in the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

The fix should have been backported to 25.0.4, so I'm not sure if it's a problem with the backport or if you are seeing a different issue.

**Comment by davidezordan25** [comment] 2024-08-28 07:41
@ssilvert  Just tried in a docker container with Nightly Build, problem still occurs.
Btw, if I search with text filter in "Groups" page , i manage to see them all
![image](https://github.com/user-attachments/assets/ef669b6f-a37d-4d79-bb30-f2e03342ac45)
, only in "Users->tab Groups-> join group" the filter issue occurs.

**Closed** 2024-09-02 13:46 UTC
Labels: kind/bug, area/admin/ui, team/ui, priority/normal
