### ISSUE TITLE
Firefox blocks cookies in login-status-iframe on localhost

### ISSUE THREAD

**Issue by ch-lepp** [keycloak/keycloak#23018] opened 2023-09-06 14:06 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

When I start my client web app under localhost, have Keycloak run under a proper domain and open everything in firefox, the login-status-iframe fails.

This is seemingly cause by the [new stricter firefox cookie policy](https://blog.mozilla.org/en/mozilla/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/).
Everything works perfectly fine with chrome. 
And I can fix this by configuring my firefox to be a little bit more relaxed with its cookies.

However, this fix is no appropriate solution for all our customers...

To be a little more specific:
I can observe my browser sending the GET request to https://<keycloak-domain>/auth/realms/<my-realm>/protocol/openid-connect/login-status-iframe.html/init
This request includes the AUTH_SESSION_ID cookie but lacks the KEYCLOAK_IDENTITY cookie.
This in return causes keycloak to answer with the error "login required"...

All of this seems to be related to [#14466](https://github.com/keycloak/keycloak/issues/new?assignees=&labels=kind%2Fbug%2Cstatus%2Ftriage&projects=&template=bug.yml).
In the [associated pull request](https://github.com/keycloak/keycloak/issues/new?assignees=&labels=kind%2Fbug%2Cstatus%2Ftriage&projects=&template=bug.yml) the new [storage access api](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API/Using) is added to the two 3p-cookies...html files as well as partially to the login-status-iframe.html file.
However, looking at the [login-status-iframe.html](https://github.com/keycloak/keycloak/blob/main/services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html) file in the current main branch the changes seem to be reverted....

### Version

22.0.1

### Expected behavior

Even when running under localhost in Firefox, the login-status-iframe.html should be able to access the KEYCLOAK_IDENTITY cookie and pass it along its requests to the keycloak server

### Actual behavior

When running under localhost in firefox, the login-status-iframe.html is denied access to the KEYCLOAK_IDENTITY cookie and therefor its requests to the keycloak server fail

### How to Reproduce?

Have the keycloak server run under a proper domain.
Start a client web app under localhost and open it in Firefox.
Try to login.

**Comment by jonkoops** [comment] 2023-09-11 11:31
Duplicate of #22839

**Closed by jonkoops** 2023-09-11 11:31 UTC
Labels: area/oidc, kind/bug, status/triage, team/core
