### ISSUE TITLE
Update documentation around `View all users` behavior in the new admin console

### ISSUE THREAD

**Issue by brownp2k** [keycloak/keycloak#16833] opened 2023-02-03 12:41 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

Adding an LDAP provider in READ_ONLY mode and "Import users" set to On actually imports every user from the LDAP provider, contrary to the documentation.

### Version

20.0.3

### Expected behavior

Per the documentation (https://www.keycloak.org/docs/20.0.3/server_admin/#synchronizing-ldap-users-to-keycloak), I am expecting users to be imported into the Keycloak user database only upon the user's first (successful) authentication attempt.

### Actual behavior

All users in the LDAP provider are imported after clicking "Save" to add the provider.

### How to Reproduce?

In a fresh instance, for the master realm, add an LDAP provider (that contains valid users) with the following settings (where "example" is valid for the LDAP instance, in my case a variant of the company name):
"Vendor" set to "Other"
"Connection URL" set to valid url
"Bind DN" set to "uid=lookup,dc=example,dc=com"
"Bind credentials" set to valid password
"Edit mode" set to "READ_ONLY"
"Users DN" set to "ou=People,dc=example,dc=com"
"User object classes" set to "inetOrgPerson"
"Import users" set to On
"Sync Registrations" set to Off
all other settings at default

Click "Save" and then navigate to the "Users" of the realm and enter "*" to search all users.

The expectation is that there are no users at this point.

**Comment by mhajas** [comment] 2023-02-22 07:42
@brownp2k, this is not a bug. To me, it seems this is expected as searching for users involves also searching in LDAP. 

You can check the users are not imported by looking into the database. Note searching will also import users into the Keycloak database.

**Comment by brownp2k** [comment] 2023-02-22 11:27
If you deem this not a bug, then the documentation is incorrect and extremely misleading. I've pasted it here for reference:
"The first time a user logs in, the LDAP provider imports the LDAP user into the Keycloak database and validates the LDAP password. This first time a user logs in is the only time Keycloak imports the user. If you click the Users menu in the Admin Console and click the View all users button, you only see the LDAP users authenticated at least once by Keycloak. Keycloak imports users this way, so this operation does not trigger an import of the entire LDAP user database."

That says it will NOT import the entire database, and that only users who have authenticated at least once. Further, there is no "View all users" button and the descriptive text on the "Users" page referenced says this:
"Viewing all users may cause the system to slow down, but it can be done by searching for "*"."

**Comment by mhajas** [comment] 2023-02-27 07:33
Thanks for sharing more details. I was too fast with closing this. You are correct, the documentation is incorrect. We should not allow for searching all users in the Keycloak storage without querying LDAP users too. We need to look at Keycloak user storage as a whole. Therefore, I am changing this to a documentation issue.

The behaviour with the old admin console (View all users) not returning LDAP users was actually caused by the following bug: #17294.

> What I'm really looking for is a way to view all users who have authenticated against Keycloak, in the web UI. This used to exist and work in at least Keycloak 15.1.1. Shall I open a new bug to point out that "View all users" is missing?

Using "View all users" for this purpose is incorrect as import is performed every time the users are queried, not only when authenticated. For example, even with the old admin console, when searching for something different like `*` or a specific username it will also trigger import and the users do not need to be authenticated.

To view all LDAP users who have already authenticated it is much less error-prone to leverage audit events, maybe you can create a custom event listener that will store some flag for each user when authenticated.

**Comment by brownp2k** [comment] 2023-02-27 10:55
> Thanks for sharing more details. I was too fast with closing this. You are correct, the documentation is incorrect. We should not allow for searching all users in the Keycloak storage without querying LDAP users too. We need to look at Keycloak user storage as a whole. Therefore, I am changing this to a documentation issue.
> 
> The behaviour with the old admin console (View all users) not returning LDAP users was actually caused by the following bug: #17294.

Thank you for confirming and writing up the new bug.

> 
> > What I'm really looking for is a way to view all users who have authenticated against Keycloak, in the web UI. This used to exist and work in at least Keycloak 15.1.1. Shall I open a new bug to point out that "View all users" is missing?
> 
> Using "View all users" for this purpose is incorrect as import is performed every time the users are queried, not only when authenticated. For example, even with the old admin console, when searching for something different like `*` or a specific username it will also trigger import and the users do not need to be authenticated.
> 
> To view all LDAP users who have already authenticated it is much less error-prone to leverage audit events, maybe you can create a custom event listener that will store some flag for each user when authenticated.

It is definitely a shame to no longer have the (built-in) functionality to only view the federated users who have actually authenticated against Keycloak.

**Comment by mhajas** [comment] 2023-02-27 11:16
> It is definitely a shame to no longer have the (built-in) functionality to only view the federated users who have actually authenticated against Keycloak.

The way you used it was not a built-in functionality for what you used it for. As I wrote in the previous message. The users are not imported only when authenticated but anytime Keycloak queries them. This can result in you thinking some user have authenticated while they have not. 

Events are built-in functionality.

**Comment by brownp2k** [comment] 2023-02-27 15:35
> > It is definitely a shame to no longer have the (built-in) functionality to only view the federated users who have actually authenticated against Keycloak.
> 
> The way you used it was not a built-in functionality for what you used it for. As I wrote in the previous message. The users are not imported only when authenticated but anytime Keycloak queries them. This can result in you thinking some user have authenticated while they have not.

I understand that it wasn't intended functionality, but the point is that with Keycloak 15.1.1 it worked exactly as it was documented, so from a user's point of view it was indeed built-in functionality. What between 15.1.1 and 20.0.3 (I'm not sure when) is a loss of that functionality. The "View All Users" button in 15.1.1 made logical sense as a way to see all of the users in the _Keycloak_ DB (not any federated stuff).

> Events are built-in functionality.

Yes, events themselves are built-in functionality, and while I didn't dig much it seems like the custom event usage you suggested is anything but built-in and would require custom code. Given a custom coded listener, I also don't see an easy way to query "all users with some <flag>" (since it would require custom code it's taken for granted that a custom solution to track all authenticated users could also be implemented).

I'm satisfied with a documentation update and your "We need to look at Keycloak user storage as a whole." comment.

**Comment by hmlnarik** [comment] 2023-03-29 12:16
Switching the issue to aim the new admin console since the old one is not supported anymore

**Closed** 2023-05-30 11:36 UTC
Labels: kind/bug, area/docs, area/ldap, team/store, team/other
