### ISSUE TITLE
Audience mapper adds internal id of the client to the claims

### ISSUE THREAD

**Issue by Szer** [keycloak/keycloak#31022] opened 2024-07-03 11:43 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Audience mapper for clients sends internal ID of the client as mappedValue which leads to unexpected behavior. This is a regression  or undocumented change as previous versions of KC added client name to `aud` claim

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Audience should match the client NAME

### Actual behavior

Audience equals client internal ID

### How to Reproduce?

Keycloak 25.0.1
Create a client 
  - client authentication, service account roles
  - add an audience mapper to whatever other client (in example below "broker")

<img width="634" alt="image" src="https://github.com/keycloak/keycloak/assets/10308233/9d7d9cf0-acab-478b-848d-65aacf1e00c9">

Get a token for that client
  - expectation from the token claims
     `"aud": ["broker", .]` or `aud: "broker"`
  - reality
```
"aud": [
    "5c92f1e3-e7b0-47f6-92b9-b75133804f4d", // ?????????
    "account"
  ]
```

### Anything else?

Do the same with Keycloak 24.0.0 or less, you'll get expected behavior.

**Comment by DimeOne** [comment] 2024-07-03 11:52
Hi, that it caused by the same issue described in #31023 - I described a workaround there.

**Comment by Szer** [comment] 2024-07-03 12:39
> Hi, that it caused by the same issue described in #31023 - I described a workaround there.

well, it is an amazing coincidence that we got the same issue filed with 5 minutes in between them :D

**Comment by Szer** [comment] 2024-07-03 12:40
There is a better workaround though, just put "Included custom Audience" value so can be done via UI

**Comment by tbnasi** [comment] 2024-07-03 12:56
+1 I also get this when adding an audience mapper, both in the client scopes and client dedicated scopes.

**Comment by thomasdarimont** [comment] 2024-07-08 09:44
Btw. I just tested this in the latest main branch and it is working fine there, this was fixed in PR #30523.

**Comment by thomasdarimont** [comment] 2024-07-08 09:45
@edewit I think the fix in PR #30523 should be backported to the 25.x line if possible.

**Comment by edewit** [comment] 2024-07-08 13:30
@thomasdarimont already done

**Closed by edewit** 2024-07-08 13:30 UTC
Labels: kind/bug, area/admin/api, area/admin/ui, status/triage, team/ui, team/core-shared

**Comment by jtepe** [comment] 2024-07-14 10:15
Hey, this doesn't seem to have been backported to the 25.0.x versions already released. I also notice, that the backport label on #30865 has been removed. Is this fix going to end up in the released versions, or not?

**Comment by jtepe** [comment] 2024-07-14 12:11
> Hey, this doesn't seem to have been backported to the 25.0.x versions already released. I also noticed that the backport label on #30865 has been removed. Is this fix going to end up in the released versions, or not?

Answering my own question. I see it went in main and release branch. Will probably be released soon.
