### ISSUE TITLE
identity broker exception invalid_client, Unauthorized

### ISSUE THREAD

**Issue by rmarops** [keycloak/keycloak#22009] opened 2023-07-26 20:59 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

trying to using google idp.  after auth, frontend shows Unexpected error when authenticating with identity provider 

server.log on keycloak instance shows
Jul 26 20:44:04 ip-10-0-0-181 kc.sh[1641]: 2023-07-26 20:44:04,740 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-124) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: No access_token from server. error='invalid_client', error_description='Unauthorized', error_uri='null'

### Version

21.1.2

### Expected behavior

auth callback success

### Actual behavior

final error on server.log is Jul 26 20:44:04 ip-10-0-0-181 kc.sh[1641]: 2023-07-26 20:44:04,741 WARN  [org.keycloak.events] (executor-thread-124) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=TEST, clientId=test-client, userId=null, ipAddress=x.x.x.x, error=identity_provider_login_failure, code_id=e0ec55a3-87a8-4d55-a2bd-c68c2dfe6b46

### How to Reproduce?

add google idp in respective realm using client id and secret provided by google and save,
update the oath client on google dev console to
- allow the redirect URL
- add user email as a tester

test auth using new google button on auth screen

### Anything else?

was able to test the same client id, secret setup with another app and keycloak instance but yet to find a useful difference

**Comment by sschu** [comment] 2023-07-27 06:46
@rmarops This is most likely not a bug in Keycloak. It actually tells you what is wrong:  error='invalid_client', error_description='Unauthorized' means either your client id or client secret for your client from Google is wrong.

**Comment by mposolda** [comment] 2023-07-27 12:35
@sschu Thanks for your reply!

@rmarops I am closing as this looks like a mis-configuration of your Google client rather than issue in Keycloak. Please check Keycloak documentation for Identity providers and especially Google documentation (should be referenced from Keycloak docs) for more details.

**Closed by mposolda** 2023-07-27 12:35 UTC
Labels: kind/bug, status/triage, team/core, area/identity-brokering
