### ISSUE TITLE
Multiple Server and 1 Database, doesnt reflect realm config to the other server

### ISSUE THREAD

**Issue by vincentmarkcelino** [keycloak/keycloak#35314] opened 2024-11-26 11:30 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have 2 servers (configured in my LB) and 1 postgreSQL DB hosted in the other server. I am changing the email notification on server1 and save it. i login again using server2, but the settings did not reflect on that server.

However, I can add user and change other settings.

Is this anything I need to configure?

### Version

26.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

I am expecting to reflect changes on both servers

### Actual behavior

Did not reflect on the other server

### How to Reproduce?

Login to server1, change email setting under realm. Test then save.
Login to server2, check the email settings. 
server2 should get the changes.

**Comment by sschu** [comment] 2024-11-28 13:14
You probably need to setup your cache configuration correctly, see https://www.keycloak.org/server/caching. I assume this is not a bug so I will go ahead and close this. Feel free to reopen if you have configured everything correctly and still something does not work. In that case, please also provide clear steps to reproduce.

**Closed** 2024-11-28 13:14 UTC
Labels: kind/bug, area/admin/ui, team/ui
