### ISSUE TITLE
Recursive expression expansion is too deep for KC_HOSTNAME

### ISSUE THREAD

**Issue by SamTV12345** [keycloak/keycloak#20452] opened 2023-05-19 07:42 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

I upgraded the keycloak custom server project of Thomas Darimont to 21.1.1. The upgrade worked as intended and it is running without a project. While upgrading another project that has a lot more keys and values in keycloak.conf it crashed. Even after copying the pom.xml 1 to 1 into the crashing project it still fails. The error message says Recursive Expression Evaluation: KC_METRICS_ENABLED. You can interchange that property also with KC_HOSTNAME. The only difference is that KC_HOSTNAME crashes at runtime while KC_METRICS_ENABLED crashes at compile time. 

### Version

21.1.1

### Expected behavior

It should build and start without a problem and in the case of e.g. metrics-enabled=${KC_METRICS_ENABLED:true} pick true if the other variable is not available/set

### Actual behavior

It crashes either during compile or runtime.

### How to Reproduce?

I created a minimal (non) working example on my working server so you can switch between main and the crashing branch:
1. `git clone https://github.com/SamTV12345/keycloak-custom-server`
2. mvn clean package | Optionally start the server to see that the main branch is working
3. `git checkout bug/recursive-expression`
4. mvn clean package
=> This should fail in the last step where quarkus maven plugin is putting everything together. 

For testing KC_HOSTNAME just put %local.hostname=${KC_HOSTNAME:mylocaldomain.com} and adjust your hosts file. You can pick any hostname that you please. The problem is that KC_HOSTNAME is in this expression.

**Comment by mabartos** [comment] 2023-05-23 15:31
@SamTV12345 Thanks for creating this issue! However, I wasn't able to reproduce this issue. 

The only thing which could be related is that we map Keycloak props to the `env` variables, such as:
`--metrics-enabled` --> `kc.metrics-enabled` --> `ENV KC_METRICS_ENABLED`.

It's possible there is happening certain recursion for these mappers. Could you try renaming the env var (f.e. `METRICS_ENABLED` or `KEYCLOAK_METRICS_ENABLED`)? If the issue persists with the different var name, it might be a real bug in the codebase. Otherwise, we'd need to be able to properly reproduce it, and probably improve documentation a little bit about the env vars propagations.

Could you please also try it with the latest main branch?  I'm closing now as _can't reproduce_, let me know what's the next outcome and possibly provide a better reproducer. Thanks!

**Closed by mabartos** 2023-05-23 15:31 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage

**Comment by SamTV12345** [comment] 2023-05-24 08:15
Thank you for your answer. It was related to  #20032 . I tested it on  the main branch and it is working again.
