### ISSUE TITLE
unknown_error when enabling role permissions

### ISSUE THREAD

**Issue by andreasringdal** [keycloak/keycloak#15522] opened 2022-11-16 09:02 UTC
### Area

admin/fine-grained-permissions

### Describe the bug

When attempting to enable permissions on the first role I created in the first realm in addition to master.
I get no feedback in GUI
In web browser network tab I get  the response {error: "unknown_error"}

Request
PUT http://localhost:8080/admin/realms/JeffreyDev/roles-by-id/4bb2a9a8-15d0-496b-9556-d1751b8514cc/management/permissions

### Version

20.0.1

### Expected behavior

Permissions to be enabled

### Actual behavior

No response in GUI

### How to Reproduce?

Installed fresh keycloak 

Same result using internal h2 and postres in Azure
docker run -p 8080:8080 --name JeffreyDevKeycloak   -e KEYCLOAK_ADMIN=******* -e KEYCLOAK_ADMIN_PASSWORD=********** quay.io/keycloak/keycloak:20.0.1 start-dev  \
   --db=postgres --db-username=testsa --db-url-database=keycloacktestdb --db-password=**********  --db-url=jdbc:postgresql://testurl.postgres.database.azure.com:5432/keycloacktestdb

Create new realm

Create role

Attempt to enable permissions

### Anything else?

Exception from docker console

`2022-11-16 08:57:16,566 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-37) Uncaught server error: java.lang.NullPointerException
        at org.keycloak.services.resources.admin.RoleByIdResource.toMgmtRef(RoleByIdResource.java:276)
        at org.keycloak.services.resources.admin.RoleByIdResource.setManagementPermissionsEnabled(RoleByIdResource.java:300)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by andreasringdal** [comment] 2022-11-16 09:22
Tested in 19.0.3 without error
Reproduced in 20.0.0 with error
➜  ~ docker run -p 8080:8080 --name JeffreyDevKeycloakOld20_0_0  -e KEYCLOAK_ADMIN=TestAdmin -e KEYCLOAK_ADMIN_PASSWORD=Superseecretpassword quay.io/keycloak/keycloak:20.0.0 start-dev  

Using docker desktop 
Host MacOS 12.6.1

**Comment by noose** [comment] 2022-11-16 12:05
I have the same problem with bitnami/keycloak:20.0.1-debian-11-r2 image

**Comment by lexcao** [comment] 2022-11-16 15:23
Hi, I have reproduced this issue from my local.
Then adding `--features=admin-fine-grained-authz` option could fix the issue.

I think the actual issue is related to the new admin UI, it should be shown only when the feature is enabled.

@ssilvert Could you please check this?

**Comment by ssilvert** [comment] 2022-11-16 20:05
@lexcao You are correct.  I fixed this yesterday.  When the feature is not enabled, you should not see the Permissions tab.

Closing this issue as a duplicate of https://github.com/keycloak/keycloak-ui/issues/3741

**Closed by ssilvert** 2022-11-16 20:05 UTC
Labels: kind/bug, status/triage
