### ISSUE TITLE
Getting users of a realm is too slow 

### ISSUE THREAD

**Issue by JorgenPo** [keycloak/keycloak#23737] opened 2023-10-05 11:46 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

We have 263 users from ldap federation and we do `/admin/realms/realm_cc_kerberos/users?briefRepresentation=true&first=0&max=9999` request for getting all users. This request takes up to minute. After examining the request spans in jaeger we found a lot of small db queries, so it seems like the request isn't optimal. I attached a screenshot of the request trace from jaeger.

![image](https://github.com/keycloak/keycloak/assets/6198711/65c6d31a-5742-48ed-b0ae-0f60d68f1315)

Without federation there are no USER_ATTRIBUTE selects in traces and request execution time is ok

### Version

nightly docker image (Keycloak 999.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.6.Final))

### Expected behavior

Getting users takes an adequate amount of time

### Actual behavior

Getting users takes an inadequate amount of time, a lot of small sql queries are executed

### How to Reproduce?

Set up a realm with ldap federation with 100+ users do `/admin/realms/{realm}/users?briefRepresentation=true&first=0&max=9999` 

### Anything else?

**Comment by sschu** [comment] 2023-10-05 14:43
How many queries are you seeing? If there is one USER_ATTRIBUTE query per user and one query seems to take less than 2ms, you should still end up way under a second.

**Comment by JorgenPo** [comment] 2023-10-05 15:57
According to trace graph provided by Jaeger the most time spent on:
 - SELECT org.keycloak.models.jpa.entities.UserEntity (513 spans, 15% of total time)
 - DELETE org.keycloak.models.jpa.entities.UserAttributeEntity (1044 span, 54% of total time)
 
 1044 spans of the second query is exact the same number as number of rows in USER_ATTRIBUTE table

**Comment by JorgenPo** [comment] 2023-10-05 16:02
That's a screenshot of that trace graph (part of it with the most time spent)
![image](https://github.com/keycloak/keycloak/assets/6198711/4988e591-e9c4-483c-9ff7-edcdf63cc560)

**Comment by JorgenPo** [comment] 2023-10-10 12:05
> @sschu 
Hi, thank you for your reply. I can't export the realm configuration that was used for that particular test, but I did the same test on another test cluster with LDAP federation with 32 users and got different results (1.9 sec total time) and no DELETE statements in traces. The total query time for only 32 users is still too much. 

I attach the request trace from jaeger and realm, hope they will help:

[long_get_users_query.json](https://github.com/keycloak/keycloak/files/12856906/long_get_users_query.json)
[realm-export.json](https://github.com/keycloak/keycloak/files/12856936/realm-export.json)

**Comment by omasseau** [comment] 2023-12-09 08:41
Are you sure you don't have any ldap requests made? 

We noticed admin REST APIs to be horribly slow, when using Ldap users federation with about 1000 users, when retrieving users from a group or a role as an LDAP query is made for each users. 

It actually makes the REST APIs unusable when using Ldap users federation.

Someone made a PR to mitigate this bug : https://github.com/keycloak/keycloak/pull/19342

But there is no news about it since July.

**Comment by omasseau** [comment] 2023-12-09 08:49
See also https://github.com/keycloak/keycloak/issues/10005

**Comment by mposolda** [comment] 2023-12-19 09:43
Switching to the store team for triage as this is related to scalability with big number of users together with LDAP used.

**Comment by ahus1** [comment] 2024-01-03 14:23
Closing as a duplicate of #10005. We'll follow-up on the pending PR.

**Closed by ahus1** 2024-01-03 14:23 UTC
Labels: kind/bug, area/storage, area/ldap, team/store, status/triage, kind/performance
