### ISSUE TITLE
`.\kc.bat start-dev` on Windows failed to start in 21.1.0

### ISSUE THREAD

**Issue by Eng-Fouad** [keycloak/keycloak#19803] opened 2023-04-19 11:08 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Executing `.\kc.bat start-dev` failed with the following error:

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

### Version

21.1.0

### Expected behavior

It should run without errors

### Actual behavior

It fails to run

### How to Reproduce?

Execute `.\kc.bat start-dev` on Windows

### Anything else?

Most likely caused by this change https://github.com/keycloak/keycloak/commit/1c9992fdaeff9566fd8f734ec5fdbf82c7fb5720

**Comment by vmuzikar** [comment] 2023-04-19 11:41
Possibly resolved by https://github.com/keycloak/keycloak/pull/19744

**Comment by Pepo48** [comment] 2023-04-19 19:32
@Eng-Fouad thanks for reporting this, I can confirm that the issue is valid and that my PR actually resolves this issue. There are still issues with regards to the testsuite, we would like to fix these before it gets merged.

**Comment by vmuzikar** [comment] 2023-04-25 14:02
Re-opening for 21.1

**Closed** 2023-04-26 07:00 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native
