### ISSUE TITLE
User Profile attributes/groups in Admin UI are not translated using Localization for non-master realm when signed in the master realm

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#29566] opened 2024-05-15 13:23 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The User Profile attributes and groups Display Name and Descriptions are not translated in the Admin UI (non-master realm when signed in via the master realm), but are correctly translated in the Register/Update_Profile pages:
In the Admin UI:
![image](https://github.com/keycloak/keycloak/assets/33352511/ac986733-1453-4b04-83fd-af09e0426d84)

In Localization for "English"
![image](https://github.com/keycloak/keycloak/assets/33352511/e56cc55e-e75f-481c-bf7d-8a30ac49d708)

In User Profile->Groups
![image](https://github.com/keycloak/keycloak/assets/33352511/20f5771a-2a12-4352-95fb-cc6d3e2ee544)

In User Profile->Attributes
![image](https://github.com/keycloak/keycloak/assets/33352511/a29a827d-1dae-4e82-97d7-f20b79d59bc7)

In Register page
![image](https://github.com/keycloak/keycloak/assets/33352511/aed6e2ce-e132-41bb-9038-199e702002c5)

----

Additional screenshot with comparing master realm login and non-master realm login:
![image](https://github.com/keycloak/keycloak/assets/33352511/d9c6275e-ad22-4ec9-a076-f17d5a349c75)

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The Attributes Display Name and Groups Display Name and Description text to be translated, taking it from the Localization (or only for English, always, or based on the signed in user Locale, again, falling back to English or the Default one set if no translations provided for the user locale) of the non-master realm even if signed in as admin, via the master realm.

### Actual behavior

No translation in the Admin UI for Attributes/Groups when Localization key used from the non-master realm and the login is via the master realm

### How to Reproduce?

1. Create Attribute and/or Group on a non-master realm
2. Add localization key, using ${theLocalizationKeyForMyAttribute} structure
3. Create a Localization message bundle for English for key "theLocalizationKeyForMyAttribute"
4. Open an user in the Admin UI signing in via the Master realm and check if the Attribute Name or Group name/description is translated as per the localization set

### Anything else?

https://github.com/keycloak/keycloak/issues/25152 and https://github.com/keycloak/keycloak/issues/22431 already closed as Solved, but the issue is still reproducible. Screenshot from the latest version:
![image](https://github.com/keycloak/keycloak/assets/33352511/1b3ee881-73d1-435a-9628-41c773467ecb)
![image](https://github.com/keycloak/keycloak/assets/33352511/390bd9b1-fa89-4fe6-bb38-0c11c897ad03)
![image](https://github.com/keycloak/keycloak/assets/33352511/e2957056-394b-4163-8131-1966aa17e3f4)

**Comment by ssilvert** [comment] 2024-05-15 18:56
This is a duplicate of #29408 and #29407.

Closing.

**Comment by mpalavrov** [comment] 2024-05-21 09:58
Hey @ssilvert,
As the issue is for not working translations on non-master realm when signed in via the master realm for the Attributes and Groups, I am not sure if the duplicated issues will solve this issue. Could you please check it again and confirm ?

**Comment by ssilvert** [comment] 2024-05-21 18:11
@agagancarczyk I've reopened and assigned this one to you.  

So we have these three closely-related issues.  This one, #29407, and #29408.

Please analyze and close any you are sure are duplicates.

**Closed** 2024-06-24 08:00 UTC
Labels: kind/bug, area/account/ui, help wanted, team/ui, status/auto-expire, status/auto-bump, priority/normal
