### ISSUE TITLE
Importing a realm containing a LDAP Group Mapper with configured Groups Path option fails

### ISSUE THREAD

**Issue by bjoernfi** [keycloak/keycloak#15478] opened 2022-11-13 13:26 UTC
### Area

import-export

### Describe the bug

Maybe related: #9069

When importing an exported realm (as json) which contains a configured LDAP identity provider with a LDAP Group Mapper using the Groups Path option, then the import fails with an exception (see below)

### Version

20.0.1

### Expected behavior

The import works as expected so that the realm is created from the json file on a fresh instance

### Actual behavior

The import fails with the exception:

```
2022-11-13 12:44:39,571 WARN  [org.keycloak.services] (main) KC-SERVICES0005: Unable to import realm SLS from file /opt/keycloak/bin/../data/import/realm-sls.json.: org.keycloak.component.ComponentValidationException: ldapErrorMissingGroupsPathGroup
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapperFactory.validateConfiguration(GroupLDAPStorageMapperFactory.java:308)
	at org.keycloak.models.jpa.RealmAdapter.importComponentModel(RealmAdapter.java:2026)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importComponents(LegacyExportImportManager.java:1123)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importComponents(LegacyExportImportManager.java:1125)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:393)
	at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:126)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:570)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:503)
	at org.keycloak.services.resources.KeycloakApplication.importRealm(KeycloakApplication.java:304)
	at org.keycloak.services.resources.KeycloakApplication.importRealms(KeycloakApplication.java:280)
	at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:213)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:43)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

### How to Reproduce?

1. Create new realm
2. Add top level realm group (i.e. `topgroup`)
3. Setup LDAP identity provider
4. Add group-ldap-mapper to identity provider and set Groups Path option to the path of the top level realm group created in 2.) (i.e. `/topgroup` or `/topgroup/`)
5. Export realm as json
6. Import the json file for the exported realm on a fresh instance
7. The exception mentioned in "Actual behavior" occurs which cancels the import

### Anything else?

The exported json contains the following:

```
{
          "id" : "56e5af95-f33d-4c05-a824-2f8dc5b82d3e",
          "name" : "<CENSORED>",
          "providerId" : "group-ldap-mapper",
          "subComponents" : { },
          "config" : {
            "membership.attribute.type" : [ "DN" ],
            "group.name.ldap.attribute" : [ "cn" ],
            "membership.user.ldap.attribute" : [ "sAMAccountName" ],
            "preserve.group.inheritance" : [ "false" ],
            "groups.dn" : [ "<CENSORED>" ],
            "mode" : [ "READ_ONLY" ],
            "user.roles.retrieve.strategy" : [ "LOAD_GROUPS_BY_MEMBER_ATTRIBUTE" ],
            "membership.ldap.attribute" : [ "member" ],
            "ignore.missing.groups" : [ "false" ],
            "memberof.ldap.attribute" : [ "memberOf" ],
            "group.object.classes" : [ "group" ],
            "groups.path" : [ "/topgroup/" ],
            "drop.non.existing.groups.during.sync" : [ "false" ]
          }
        }
```
I don't know why but it seems that ` "groups.path" : [ "/topgroup/" ]` cannot be resolved to the group `topgroup` created in step 2.)

As a workaround I have omitted the value for "Groups Path" in the ui, leading to the value ` "groups.path" : [ "/" ]` in the json. Then the import works as expected.

**Comment by loetscher** [comment] 2023-02-03 07:37
Looks like a duplicate of https://github.com/keycloak/keycloak/issues/10730

**Comment by jonkoops** [comment] 2023-02-03 11:13
Yes. Duplicate of #10730

**Comment by jonkoops** [comment] 2023-02-03 11:13
Duplicate of #10730

**Closed** 2023-02-03 11:13 UTC
Labels: kind/bug, area/import-export, area/ldap
