### ISSUE TITLE
inputOptionLabels is truncating text that is not wrapped for localization

### ISSUE THREAD

**Issue by john-gom** [keycloak/keycloak#28484] opened 2024-04-06 14:57 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

If literal inputOptinLabels are provided, e.g.

```
        "inputOptionLabels": {
          "one": "One",
          "two": "Two",
          "three": "Three"
         }
```

The first two and last characters are being stripped if the text has more than 3 characters, and the desired label is not displayed if the label has 3 or less characters, so the options display as:

-           one
-           two
-           re

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Literal values should be displayed

### Actual behavior

The first two and last characters are being stripped if the text has more than 3 characters, and the desired label is not displayed if the label has 3 or less characters, so the options display as:

-           one
-           two
-           re

### How to Reproduce?

Create a user profile field with inputOptinLabels, e.g.

```
        "inputOptionLabels": {
          "one": "One",
          "two": "Two",
          "three": "Three"
         }
```

The first two and last characters are being stripped if the text has more than 3 characters, and the desired label is not displayed if the label has 3 or less characters, so the options display as:

-           one
-           two
-           re

**Comment by jonkoops** [comment] 2024-04-06 17:25
Possible duplicate of #28443

**Closed** 2024-04-08 08:28 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui
