### ISSUE TITLE
Duplicated user consents

### ISSUE THREAD

**Issue by svenseeberg** [keycloak/keycloak#13045] opened 2022-07-12 07:10 UTC
### Describe the bug

In some cases the consent of users for SAML clients is duplicated in the database, which throws the following exception when users try to log in:
```
2022-07-11 22:28:07,534 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1570) Uncaught server error: org.keycloak.models.ModelException: More results found for user [789ee841-0966-4d9d-aabb-d513133b138a] and client [2847d11d-7dcb-4697-a4fe-232e089c3bb7]
	at org.keycloak.models.jpa.JpaUserProvider.getGrantedConsentEntity(JpaUserProvider.java:280)
	at org.keycloak.models.jpa.JpaUserProvider.updateConsent(JpaUserProvider.java:248)
	at org.keycloak.storage.UserStorageManager.updateConsent(UserStorageManager.java:594)
	at org.keycloak.models.cache.infinispan.UserCacheSession.updateConsent(UserCacheSession.java:653)
	at org.keycloak.services.resources.LoginActionsService.processConsent(LoginActionsService.java:918)
	at jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The database entry then looks like this:
```
keycloak=# SELECT * FROM user_consent WHERE user_id='e052733f-3106-4030-a833-029a0666e784';
                  id                  |              client_id               |               user_id                | created_date  | last_updated_date | client_storage_provider | external_client_id 
--------------------------------------+--------------------------------------+--------------------------------------+---------------+-------------------+-------------------------+--------------------
[...]
 73c06e73-8bb2-4d81-acaf-397dac52916e | 2847d11d-7dcb-4697-a4fe-232e089c3bb7 | 789ee841-0966-4d9d-aabb-d513133b138a | 1657267613443 |     1657267613455 |                         | 
 6a63b4c2-4968-4ff0-8864-e9b021d58aec | 2847d11d-7dcb-4697-a4fe-232e089c3bb7 | 789ee841-0966-4d9d-aabb-d513133b138a | 1657267610788 |     1657267610790 |                         | 
```

I usually remove both entries from the database (tables user_consent and user_consent_client_scope) and the users are then able to successfully log in.

### Version

18.0.2

### Expected behavior

There should be no redundant database entries for the same consent.

### Actual behavior

In some cases (not sure how to reproduce) the entries are doubled.

### Anything else?

I think the table user_consent should get a uniqe constraint for the tuple (client_id, user_id).

**Comment by cgeorgilakis** [comment] 2022-10-06 08:56
We have also the same problem for OIDC clients in version 16.1 in our production environment. We use PostgreSQL.
We have three duplicate UserConsentEntity that combination of userId - clientId is unique.
After it, the only possible solution for being able User to login succesful is delte at least one entry and restart all Keycloak services.

I assume that the problem is that in database no unique constraint exists for userId - clientId. I know that you have unique constraint for client_id, client_storage_provider, external_client_id, user_id and you make query before creating a UserConsentEntity. However, as you see all these is not enough and local client is the most common use case.

This is critical problem. Could you provide a solution?

**Comment by cgeorgilakis** [comment] 2022-10-06 15:19
As I see in the code of the map storage no check exists for duplicate consents with same combination of userId and clientId. Getting the first one from map storage is not sufficient. Existing more than one consent for same combination of userId and clientId is big problem. With the query check in database, we have already had three such situations.

Is map storage doing any check for duplications?

**Comment by melegiul** [comment] 2023-03-07 14:23
Can confirm that the problem still exists on keycloak 21.0.1, but without any stack traces in the log.

**Comment by svenseeberg** [comment] 2023-03-09 07:29
If anyone needs to fix this problem in production, the following SQL commands can fix it in the PostgreSQL database:
```sql
SELECT * FROM user_consent WHERE user_id='USER_UUID';
```
Look for duplicate client_id columns. Then:
```sql
DELETE FROM user_consent_client_scope WHERE user_consent_id='CONSENT_ID1' OR user_consent_id='CONSENT_ID2';
DELETE FROM user_consent WHERE user_id='USER_UUID' AND client_id='CLIENT_UUID';
```

**Comment by svenseeberg** [comment] 2023-03-09 07:31
> Can confirm that the problem still exists on keycloak 21.0.1, but with a slightly different error message.

I'm wondering if the duplicate entries were created before the unique constraints were introduced?

**Comment by melegiul** [comment] 2023-03-09 08:06
> > Can confirm that the problem still exists on keycloak 21.0.1, but with a slightly different error message.
> 
> I'm wondering if the duplicate entries were created before the unique constraints were introduced?

The unique constraint on db level PR was not merged yet, so it might still appear new duplicates in keycloak 21.

**Comment by cgeorgilakis** [comment] 2023-03-13 07:34
@stianst the problem also exists in OIDC clients. We almost only use OIDC clients.
Could you review my PR and conclude in a way to solve possible problems during Keycloak migration?

Finally, you need to add a check in map storage for such a situation - if not yet impemented.

**Comment by sguilhen** [comment] 2023-04-05 20:48
@svenseeberg thanks for reporting this issue. I was able to partially reproduce it: I didn't figure out what scenario leads to the duplicate records (in your report they were created a couple of seconds apart from each other, so I'm guessing some concurrency issue in `JpaUserProvider` is causing multiple threads to create the consent for the same clientId-userId pair), but I was able to confirm that the current constraint is not enough to prevent the duplicate records.

I'm removing this from triage state and will ask for a review of @cgeorgilakis PR.

**Comment by sguilhen** [comment] 2024-02-21 01:25
@svenseeberg I'm closing this since you reported not seeing the problem in recent versions. If this changes, please re-open.

**Comment by cgeorgilakis** [comment] 2024-02-21 09:09
> @svenseeberg I'm closing this since you reported not seeing the problem in recent versions. If this changes, please re-open.

@sguilhen I can not understand why you have closed the issue even if the false database constraint is still existing.
As I have mentioned in [my PR](https://github.com/keycloak/keycloak/pull/14793) : 

> Unique constraint in a database is not working if one - or more - field is null. So we propose to delete old one and create two appropriate unique constraints.

Map storage will be droped. So, [my PR](https://github.com/keycloak/keycloak/pull/14793) is only needed a migration strategy for possible already duplicate entries.
Do you agree with my proposal to 'Delete newer consent for duplicate consents'? In order to implement it and finish [my PR](https://github.com/keycloak/keycloak/pull/14793).

**Comment by svenseeberg** [comment] 2024-02-21 09:10
I just checked our database again: it still seems to happen, but it seems to be much less likely. Over the last 3 months I can only see 9 duplicate consents. We have about a couple of hundred new consents per day.

**Comment by sguilhen** [comment] 2024-02-21 12:19
@cgeorgilakis yeah, agree, re-opening as the db constraint needs fixing. I agree with your proposal to migrate by deleting duplicates, so go ahead and update the PR.

**Comment by cgeorgilakis** [comment] 2024-02-27 09:41
> elete newer consent for duplicate consents

I have finished the migration part based on database. See my comment in PR. Could you review it?

**Comment by pedroigor** [comment] 2024-03-04 20:41
@cgeorgilakis @sguilhen Can we start by introducing the constraints (and redundant checks on the server once they are there) and then evaluate how to avoid duplicates from happening?

**Comment by sguilhen** [comment] 2024-03-05 01:30
@pedroigor I've set a priority of normal for this one. We already have a PR from @cgeorgilakis , will try to get to it this week. It introduces the constraint that will prevent the duplicates from being created in the DB, and also removes existings dups during migration.

**Comment by cgeorgilakis** [comment] 2024-03-05 07:49
> @cgeorgilakis @sguilhen Can we start by introducing the constraints (and redundant checks on the server once they are there) and then evaluate how to avoid duplicates from happening?
> 
> @sguilhen I'm leaving it to you to set the expected priority ...

Unique constraints in USER_CONSENT are : 
- CLIENT_ID, USER_ID
- CLIENT_STORAGE_PROVIDER, EXTERNAL_CLIENT_ID, USER_ID

Current unique constraint is based on CLIENT_ID, CLIENT_STORAGE_PROVIDER, EXTERNAL_CLIENT_ID, USER_ID.
This seems to work only for Oracle DB. For other databases, unique constraint is not executed due to null values. See [my last PR comment](https://github.com/keycloak/keycloak/pull/14793#issuecomment-1966152652).

**Closed** 2024-03-19 21:16 UTC
Labels: kind/bug, area/storage, help wanted, team/core-iam, status/auto-bump, priority/normal
