### ISSUE TITLE
Userprofile/Translation: user attribute cannot be saved because no translation was (even though it is present)

### ISSUE THREAD

**Issue by alexanderhofstaetter** [keycloak/keycloak#31228] opened 2024-07-11 16:18 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I want to save an exisiting custom user profile field, it says: "Error! User Profile configuration has not been saved Please add translations before saving."
![image](https://github.com/keycloak/keycloak/assets/6820505/26ae8be6-79c3-4b62-8628-6b7f59375652)

Even though the translation string has been added before:

![image](https://github.com/keycloak/keycloak/assets/6820505/6e8163ef-d501-4f13-9d65-712629260fd8) 

to save the attribute again, you have to open the translation fields, put the cursor into the fields and Click OK:

![image](https://github.com/keycloak/keycloak/assets/6820505/4fec643a-6200-41cc-b62a-11aa2e32bab4)

---- 

Localization with DE and EN is enabled, settings see here: https://github.com/keycloak/keycloak/issues/31142#issuecomment-2223340753

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

When a field has translation added before, it should be able to save the field, even though you dont explicity click in the translation field.

### Actual behavior

one always has to open translation modal and set cursor to input, click OK -> and then save afterwards.

### How to Reproduce?

add a custom field when localization is enabled, and after creation, try saving the field again

**Comment by ssilvert** [comment] 2024-07-16 18:02
@agagancarczyk I think this is fixed, right?  If so, please close this issue and reference the issue it was fixed under.

**Comment by ssilvert** [comment] 2024-07-16 18:06
@agagancarczyk Nevermind.  I see this is fixed in 25.0.2 and 26.0.0.

Duplicate of https://github.com/keycloak/keycloak/issues/29407

**Closed by ssilvert** 2024-07-16 18:06 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by garronej** [comment] 2024-08-26 16:26
Hello @ssilvert,  

I don't know about Keycloak 26 but the bug is still present in Keycloak 25.0.4  

https://youtu.be/lMOLrdqilqE?si=GNa_-c4JOlrZQIY2&t=375  

(I like the feature very much otherwise)

**Comment by ssilvert** [comment] 2024-08-26 19:36
@garronej I am not seeing this issue on the nightly build.  Can you give that a try?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by Malcolm-GetAHead** [comment] 2024-08-27 19:06
I'm also experiencing this issue under 25.0.4 but it appears to be resolved in the nightly docker tag.

**Comment by douph1** [comment] 2024-09-06 13:29
Same issue for me on 25.0.4. I will try nightly soon.
Did a 25.0.5 or 26 is scheduled ?

Workaround: use "JSON editor" tab under "User profile" tab for editing.

**Comment by Malcolm-GetAHead** [comment] 2024-09-06 13:38
> Same issue for me on 25.0.4. I will try nightly soon. Did a 25.0.5 or 26 is scheduled ?
> 
> Workaround: use "JSON editor" tab under "User profile" tab for editing.

You can also work around the issue by modifying one of the translations prior to saving

**Comment by valkiriaaquatica** [comment] 2024-10-02 18:25
Hi, same issue here on kubernetes, version 25.0.6, while trying to update the first Name os userProfile to Not required filed, recevied the error: 

`Error! User Profile configuration has not been saved Please add translations before saving.`

**Comment by valkiriaaquatica** [comment] 2024-10-03 17:13
> > Hi, same issue here on kubernetes, version 25.0.6, while trying to update the first Name os userProfile to Not required filed, recevied the error:
> > `Error! User Profile configuration has not been saved Please add translations before saving.`
> 
> hi @valkiriaaquatica Did you have translations added to firstName prior to changing it to not required field and saving?

Hi, thanks for the quick response.
No I didn't add any translatations to any of the default values os "User Profile" -> username, email, firstName and lastName. 
The only trnslations that exist are in the "Localization" parte, where I added the French and Spanish to the default English. (I just tried to remove spanish and french from "Supoported lcoals"  , save and then retried to set firstName "Required field" to off but stills the same error.

Thanks in advanced just seen your PR

**Comment by olga-tsvetkova-pa** [comment] 2025-05-14 14:38
Keycloak 26.2.4 - problem is still here =(

**Comment by ssilvert** [comment] 2025-05-14 18:05
> Keycloak 26.2.4 - problem is still here =(

@olga-tsvetkova-pa This issue is rather old.  Can you open a new one with your exact steps to reproduce?
