### ISSUE TITLE
SSO of OIDC not working after upgrade from 25.0.5 to 26.0.5

### ISSUE THREAD

**Issue by bienblue** [keycloak/keycloak#34907] opened 2024-11-13 09:57 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

After upgrading Keycloak from version 25.0.5 to 26.0.5, the Single Sign-On (SSO) functionality for OpenID Connect (OIDC) is no longer working. Previously, after logging into the system for the first time, users could access other systems without needing to re-enter their username and password. However, after the upgrade, users are required to log in again with their username and password whenever they access any system. The Keycloak log contains the following warning message, which might be related to the issue:
``` log
"level":"WARN","message":"Non-secure context detected; cookies are not secured, and will not be available in cross-origin POST requests"
```

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Users should be able to access other systems without needing to log in again after the initial login, as was the case in version 25.0.5.

### Actual behavior

Users are required to log in again with their username and password whenever they access any system.

### How to Reproduce?

1. Upgrade Keycloak from version 25.0.5 to 26.0.5.
2. Configure SSO for OIDC.
3. Log in to the system for the first time.
4. Attempt to access another system.
5. Observe that the user is prompted to log in again.

**Comment by Nowheresly** [comment] 2024-11-13 12:48
maybe a duplicate of https://github.com/keycloak/keycloak/issues/34295 ?

**Comment by bienblue** [comment] 2024-11-13 15:05
> That message means the server is detecting a non-secure context (secure context is https or http in localhost/127.0.0.1 mainly). Are you using plain http? Or are you behind a reverse proxy? If you are after a reverse proxy maybe the configuration is not OK and it is not detecting the correct URL used. Check this [guide](https://www.keycloak.org/server/reverseproxy) and the issue commented by @Nowheresly #34295 that can be related.

Hi @rmartinc, I have configured Keycloak with Istio and Oauth2-proxy,
After update new env **KC_PROXY_HEADERS** with value **xforwarded**. Then the cookie changed to SameSite=None; Secure.
But, I still facing the same issue with SSO as I mentioned above; although the error in Keycloak pod is no longer displayed.

**Comment by bienblue** [comment] 2024-11-14 06:12
In addition, I got this error in console of browser.
![image](https://github.com/user-attachments/assets/514ba29b-b62d-4424-b433-1d9507549f24)

**Comment by bienblue** [comment] 2024-11-19 15:52
I have found the root cause.
From KC26, the feature **organization** is enabled by default -> that cause the authentication flow **browser** changes.
This one is impact to our SSO implementation.

**Closed** 2024-11-19 15:59 UTC
Labels: area/oidc, kind/bug, team/core-clients, status/auto-expire, status/missing-information
