### ISSUE TITLE
Observed NPE in logs

### ISSUE THREAD

**Issue by rahulshelar** [keycloak/keycloak#16223] opened 2023-01-03 13:51 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When we deploy Keycloak from latest image quay.io/keycloak/keycloak:latest, the master realm has multiple **Clients** added by default.

1. Traverse to Clients. This will open Client listing for user.
2. Click on client with ID "account", this will open "Client details" page.
3. Click on the "Roles" tab. This opens roles listing for user.
4. Click on any role in this listing e.g. "view-profile". This opens "Role details" page for user
5. Go to permissions tab. Here you see "Permissions enabled" toggle switch. Click on this toggle switch.
6. Toggle switch state doesn't changes and NullPointerException is observe logs.

2023-01-03 13:38:40,142 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: java.lang.NullPointerException
        at org.keycloak.services.resources.admin.RoleByIdResource.toMgmtRef(RoleByIdResource.java:276)
        at org.keycloak.services.resources.admin.RoleByIdResource.setManagementPermissionsEnabled(RoleByIdResource.java:300)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)

### Version

20.0.2

### Expected behavior

NullPointerException is not expected in the logs

### Actual behavior

NullPointerException is observed in logs.

### How to Reproduce?

1. Deploy keycloak container from the latest image: docker run --name mykeycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:latest start-dev
2. Login to admin console with the admin credentials
3. Traverse to Clients. This will open Client listing for user.
4. Click on client with ID "account", this will open "Client details" page.
5. Click on the "Roles" tab. This opens roles listing for user.
6. Click on any role in this listing e.g. "view-profile". This opens "Role details" page for user
7. Go to permissions tab. Here you see "Permissions enabled" toggle switch. Click on this toggle switch.
8. Toggle switch state doesn't changes and NullPointerException is observe logs.

**Comment by sschu** [comment] 2023-01-03 18:12
That's probably a duplicate of https://github.com/keycloak/keycloak-ui/issues/3741

**Comment by ssilvert** [comment] 2023-01-03 19:03
Yes, it is a duplicate of https://github.com/keycloak/keycloak-ui/issues/3741.  Fixed in latest nightly.

**Closed by ssilvert** 2023-01-03 19:03 UTC
Labels: kind/bug, area/admin/ui, status/triage
