### ISSUE TITLE
Account Console REST API for /linked-accounts Returns Multiple Access-Control-Allow-Origin Headers

### ISSUE THREAD

**Issue by fabian-paus** [keycloak/keycloak#27646] opened 2024-03-07 08:09 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

In version 23.0.7, if I send a GET request to realms/[realm]/account/linked-accounts with Origin set, I get two Access-Control-Allow-Origin in the response.

Example:
GET  realms/[realm]/account/linked-accounts
Authentication: Bearer e...
Origin: http://localhost:4200

In the response I get the following access control headers:
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true

Chrome (and probably other browsers) reject this due to CORS violations:
Access to fetch at 'https://.../realms/[realm]/account/linked-accounts' from origin 'http://localhost:4200' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:4200, http://localhost:4200', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This prevents cross-origin access to the linked-accounts endpoint. This is mostly relevant for local development of the account console theme. But could also effect other users of the account API.

I looked into the code but could not directly find the cause for this. I suspect multiple places colling "addHeader.accept(ACCESS_CONTROL_ALLOW_ORIGIN, origin);" to add the origin.

### Version

23.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

Only one access control header is returned, so that API is callable from a frontend application.

### Actual behavior

Two access control headers are returned.

### How to Reproduce?

Set the Web Origin for the account-console client to http://localhost:4200.
Call the /linked-accounts API with an Origin header set to http://localhost:4200.
Observe two Access-Control-Allow-Origin headers in the response.

**Comment by fabian-paus** [comment] 2024-03-07 10:06
The bug also exists in 24.0.1. 
All the other endpoints (/account, /account/credentials, ...) correctly return a single Access-Control-Allow-Origin header.

**Comment by pedroigor** [comment] 2024-03-07 22:29
@fabian-paus Thanks. Why this is marked as a regression if you reported the issue for 23? Can you please provide the version before 23 where the issue does not happen?

 I also checked the latest release (24) and it has the same problem, as stated by @fabian-paus. 

FTR, the reason is that we are actually adding CORS headers twice: before and when invoking the endpoint. Seehttps://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java#L136.

We are also adding headers to the response (using an add operation so adding values for existing headers) without checking first if they were already set. As you can not have multiple occurrences of some CORS headers like `Access-Control-Allow-Origin`, I think we can just make sure a single header is always set.

**Comment by fabian-paus** [comment] 2024-03-08 05:28
Thanks for looking into it so fast!

Sorry, for the regression: We upgraded from 20.0.5 to 23.0.7. In 20.0.5 the header was correctly added only once. I do not know, in which version the bug was added.

**Comment by pedroigor** [comment] 2024-03-08 11:00
Np. I think it started after our move to Resteasy Reactive.

**Comment by kaustubh-rh** [comment] 2024-03-11 11:01
Hi @pedroigor ,
Can I raise a PR for the same ?

**Closed** 2024-05-08 15:27 UTC
Labels: kind/bug, priority/important, area/account/api, area/identity-brokering, team/core-iam
