### ISSUE TITLE
Keycloak 23.0.1 - Authorization endpoint doesn't work (We are sorry)

### ISSUE THREAD

**Issue by nicolasduminil** [keycloak/keycloak#25737] opened 2023-12-20 16:56 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

I'm running Keycloak 23.0.1 locally, in mode dev. Doing a GET request at `http://localhost:8080/realms/master/.well-known/openid-configuration` I can see that the `authorization_endpoint` is `http://localhost:8080/realms/master/protocol/openid-connect/auth`. Clicking on the associated link, I get a dialog box saying "We are sorry ..." with the mention "Invalid request". I appreciate the courtesy but I'd have expected a different result.
I have created a new realm called `myrealm`, a new client with ID `myclient` and a new user named `nicolas`. Now, doing a GET at `http://localhost:8080/realms/myrealm/protocol/openid-connect/auth?client_id=myclient&response_type=code` I get the Keycloak login dialog box. After logging in as user `nicolas`, I am redirected to the administration console home page.

### Version

23.0.1

### Expected behavior

Given that the request is made to the authorization endpoint, I'd expect the server to generate an authorization code.
Is that the behavior I should expect or did I misunderstood the way that it works ? I'm attaching here the `myclient.json` file containing the client export.
[myclient.json](https://github.com/keycloak/keycloak/files/13730077/myclient.json)
 

### Actual behavior

The server returns "We are sorry" when requested at `http://localhost:8080/realms/myrealm/protocol/openid-connect/auth` and, after leting me logging in, redirects to its administration console page, when requested at `http://localhost:8080/realms/myrealm/protocol/openid-connect/auth?client_id=myclient&response_type=code`.

### How to Reproduce?

1. Start Keycloak server in dev mode.
2. Create a new realm called `myrealm`.
3. In the new created realm, create a new client having the id `myclient` as shown in the attached export file (`myclient.json`).
4. Fire you prefered browser and make a GET request to `http://localhost:8080/realms/myrealm/protocol/openid-connect/auth?client_id=myclient&response_type=code`. 
5. The Keycloak login dialog is displayed. Login as a new realm user.
6. The server redirects to the administration console home page.

**Comment by mposolda** [comment] 2023-12-20 17:22
@nicolasduminil Thanks for the report, however I am closing as this is not a bug. Please note that Keycloak is OpenID Connect / OAuth2 provider. You can see here requirements for the OpenID Connect authentication request [1] and here for OAuth2 [2]. Since you did not filled `scope=openid`, your request is treated as OAuth2 request (not OpenID Connect) and hence only `response_type` is required and possibly `client_id` as long as you don't use client authentication. Exactly like you have in your 2nd request with `client_id` and `response_type` parameters, which is valid OAuth2 request and that's the reason why it works.

[1] https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint
[2] https://datatracker.ietf.org/doc/html/rfc6749#page-18

**Closed by mposolda** 2023-12-20 17:22 UTC
Labels: area/oidc, kind/bug, status/triage, team/core

**Comment by nicolasduminil** [comment] 2023-12-23 14:11
@mposolda I'm not sure how to interpret your reply to my issue. Many thanks to provide me with links to the documentation but this wasn't what I expected because, as you can imagine, before registering issues here, I've read the documentation. And if some misunderstanding of the described processes might still persist on my side, sending me links to the specification doesn't help much.
When you say: "Since you did not filled `scope=openid`, your request is treated as OAuth2 request (not OpenID Connect) and hence only `response_type` is required and possibly `client_id` as long as you don't use client authentication.", what exactly are you trying to say ? Yes, my request is treated as an OAuth2 request, so what ? This is what I want it to be treated like. Am I supposed to find the solution to my issue in this sentence ? And yes, I agree that only `response_type` and `client_id` are required. So what ?
Do you, at least, understand what my issue is ? I'm reporting that making a GET request to the `authorization_endpoint` just redirects to the admin console, instead of providing an authorization code, as expected. Is there anything in your answer which is supposed to guide me how to solve this issue ?

**Comment by nicolasduminil** [comment] 2024-01-03 14:10
Could anyone clarify that please ? I've raised an issue which was closed and the explanation which was given to me doesn't make much sense. I'm simply reporting that  a GET request to the `authorization_endpoint` just redirects to the admin console, instead of providing an authorization code, as expected.

**Comment by sschu** [comment] 2024-01-03 16:26
According to the oauth spec, you have to send additional parameter to the authorization endpoint in the query string. If you dont send these parameters, the request is invalid, thats why you end up on an error page.

**Comment by nicolasduminil** [comment] 2024-01-04 12:28
You guys seem to have a serious problem here as you're feigning answering questions without really doing it. I'm raising an issue showing that something doesn't appear to work as expected and I'm answered to proceed as written in specs. Thank you very much then, I won't disturb you any more. Good luck in promoting  your server as, given the way you support it, it's certainly not gained in advance.

**Comment by jonkoops** [comment] 2024-01-04 12:34
@nicolasduminil There is no need for this hostility, we're structurally overloaded with issues and community requests so we get to it when we can. The answer provided here by Sebastian is completely valid, if you want to know more I recommend you read the OpenID Conect specification before you come to us.

Please refrain from further non-constructive and abusive language, or I will have you banned from our organization.
