### ISSUE TITLE
Keycloak's performance decrease by the amount of realms

### ISSUE THREAD

**Issue by andrewaldasoro** [keycloak/keycloak#19793] opened 2023-04-18 22:57 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Environment:
Ubuntu 20.04.5 LTS
K8s: 1.21
CPU: 4
Memory: 10Gb
DB: Postgres

After creating 400 realms ({ "realm": "Realm$COUNT",  "enabled": true }), it's impossible to load data in the Admin Console, and also get information about a realm, like the users ( /admin/realms/Realm1/users ) times out. 

I verified if it was a problem related to the number of resources required but CPU and memory are fine, almost reaching 1 CPU and 1Gb of memory. I can make queries in the database, so I don't think is related to that either,

The error in the logs:
```
2023-04-18 21:34:13,910 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012108: CheckedAction::check - atomic action 0:ffff0a200011:abab:643f011c:435 aborting with 1 threads active!
2023-04-18 21:34:13,913 WARN  [io.agroal.pool] (Transaction Reaper Worker 0) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
2023-04-18 21:34:13,924 WARN  [org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorTrackingImpl] (Transaction Reaper Worker 0) HHH000451: Transaction afterCompletion called by a background thread; delaying afterCompletion processing until the original thread can handle it. [status=4]
2023-04-18 21:34:13,925 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffff0a200011:abab:643f011c:435
2023-04-18 21:34:13,970 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredUserSessions: org.hibernate.HibernateException: Transaction was rolled back in a different thread!
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorTrackingImpl.processAnyDelayedAfterCompletion(SynchronizationCallbackCoordinatorTrackingImpl.java:90)
        at org.hibernate.internal.SessionImpl.delayedAfterCompletion(SessionImpl.java:632)
        at org.hibernate.internal.SessionImpl.persistOnFlush(SessionImpl.java:802)
        at org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:341)
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:510)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:434)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:220)
        at org.hibernate.engine.internal.Cascade.cascadeComponent(Cascade.java:405)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:241)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:153)
        at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:159)
        at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:149)
        at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:82)
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:50)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1372)
        at org.hibernate.internal.SessionImpl.scroll(SessionImpl.java:1597)
        at org.hibernate.query.internal.AbstractProducedQuery.doScroll(AbstractProducedQuery.java:1588)
        at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1574)
        at org.hibernate.query.internal.AbstractProducedQuery.stream(AbstractProducedQuery.java:1598)
        at org.hibernate.query.Query.getResultStream(Query.java:1140)
        at org.keycloak.models.jpa.JpaRealmProvider.getClientScopes(JpaRealmProvider.java:975)
        at org.keycloak.storage.ClientStorageManager.getClientScopes(ClientStorageManager.java:212)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientScopes(RealmCacheSession.java:1355)
        at org.keycloak.models.jpa.ClientAdapter.getClientScopes(ClientAdapter.java:366)
        at org.keycloak.models.cache.infinispan.entities.CachedClient.<init>(CachedClient.java:116)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.cacheClient(RealmCacheSession.java:1152)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientById(RealmCacheSession.java:1114)
        at org.keycloak.models.jpa.RealmAdapter.getMasterAdminClient(RealmAdapter.java:1171)
        at org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:267)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:418)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.hibernate.query.spi.StreamDecorator.forEach(StreamDecorator.java:153)
        at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.removeAllExpired(InfinispanUserSessionProvider.java:601)
        at org.keycloak.services.scheduled.ClearExpiredUserSessions.run(ClearExpiredUserSessions.java:39)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.runTask(ScheduledTaskRunner.java:73)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
```

Apart from that I expose the metrics to prometheus but it doesn't show something alarming.

### Version

20.0.5

### Expected behavior

Access to the UI and API shouldn't be affected by the number of realms.

### Actual behavior

Keycloak performance starts dropping exponentially after adding realms.

### How to Reproduce?

Add 400+ realms to a Keycloak instance

**Comment by mposolda** [comment] 2023-05-17 16:38
Moving to store team for the triage.

But AFAIK this is long term issue - We know that Keycloak may not have ideal performance with big number of realms. The workaround might be to increase default transaction timeout (AFAIK there is some system property for that).

**Comment by vramik** [comment] 2023-05-26 17:44
Thank you @andrewaldasoro. This issue is caused by https://github.com/keycloak/keycloak/issues/11796. I'm closing this as duplicate.

For the completeness there is ongoing discussion: https://github.com/keycloak/keycloak/discussions/11074

**Closed by vramik** 2023-05-26 17:44 UTC
Labels: kind/bug, area/storage, team/store, status/triage
