### ISSUE TITLE
keycloak-admin-client javascript doesn't work with NodeJS since version 19.0

### ISSUE THREAD

**Issue by malopez16** [keycloak/keycloak#20587] opened 2023-05-26 04:55 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

From version 19 to version 20, axios changed to use the Native Fetch methods in https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-admin-client/src/utils/auth.ts#L77
This means the admin-client cannot be run anymore in a node based environment, just in browsers. Running the package I'm currently getting: 

```node dist/test.js
Authentication failed: ReferenceError: Headers is not defined
    at getToken (file:///Projects/example/node_modules/@keycloak/keycloak-admin-client/lib/utils/auth.js:29:21)
    at KeycloakAdminClient.auth (file:///Projects/example/node_modules/@keycloak/keycloak-admin-client/lib/client.js:66:53)
    at authenticate (file:///Projects/example//dist/test.js:7:31)
    at file:///Projects/example//dist/test.js:14:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)```

```

### Version

21.1.1

### Expected behavior

Node based system/frameworks should be able to run the admin client code.

### Actual behavior

Erroring our due to Headers() not defined in NodeJS runtime. For some reason it was preferred to migrate to use Headers() instead of Axios to communicate with the server as it was before, when going from major version 19 to 20.

### How to Reproduce?

Easy to reproduce: 

1. Generate a new ts project with tsconfig.json: 
```
{
    "compilerOptions": {
      "target": "es2021",
      "outDir": "dist",
      "moduleResolution":"node",
    }
}
```

test.ts
```
import KeycloakAdminClient from '@keycloak/keycloak-admin-client';

async function authenticate() {
  const keycloakAdminClient = new KeycloakAdminClient({
    baseUrl: 'http://localhost:8080/auth',
    realmName: 'your-realm-name',
  });

  await keycloakAdminClient.auth({
    grantType: 'client_credentials',
    clientId: 'your-client-id',
    clientSecret: 'your-client-secret',
  });

  console.log('Authentication successful!');
}

authenticate().catch((error) => {
  console.error('Authentication failed:', error);
});
```
2. Compile `npx tsc` 
3. Run `node dist/test.js`

### Anything else?

I'm migrating a project I have from 19 to 21, which is based on Nestjs + keycloak-nodejs-admin-client.
I've been unable to get the most simple `auth` call to work. Trying to isolate the issue I'm attempting to bring a simple Node client up with the API call. But it doesn't work. The Keycloak Server returns 500. But obviously this needs to work to troubleshoot that furher.

**Comment by edewit** [comment] 2023-05-26 06:35
we use it in a [node based script](https://github.com/keycloak/keycloak/blob/main/js/apps/keycloak-server/scripts/import-client.mjs) and we don't have this problem, what version of node are you using?

**Comment by jonkoops** [comment] 2023-05-26 09:23
Duplicate of #20515

**Closed by jonkoops** 2023-05-26 09:23 UTC
Labels: kind/bug, status/triage, team/ui, area/admin/client-js
