### ISSUE TITLE
When a user is in more than 1 organization, the accesstoken did't show the organization any more.

### ISSUE THREAD

**Issue by Lord-KalEl** [keycloak/keycloak#34535] opened 2024-10-31 08:13 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

Under Client -> Client details -> Client scopes -> Evaluate. 
You have to put "organization" into the scope parameter and choose a user.

If a user is in more than one organization, the generated accesstoken didn't show any organization any more.
Example:
If a user is in only one organization, than there is the json code:
> "organization": [
    "test"
  ],

"organization" is an array, so I would expect, that if the user is in more than 1 organization, every organization would be put in there …

> "organization": [
    "test",
    "test2",
    "test3"
  ],
  
instead of this expectation, this value disappear completely …

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

"organization" is an array, so I would expect, that if the user is in more than 1 organization, every organization would be put in there …

> "organization": [
    "test",
    "test2",
    "test3"
  ],
  

### Actual behavior

instead of this expectation, this value disappear completely …

### How to Reproduce?

Under Client -> Client details -> Client scopes -> Evaluate. 
You have to put "organization" into the scope parameter and choose a user.

You have to "play" with the memberships of the organizations. If the user you choose is in only one organization, than everything is OK and the Accesstoken shows the information about the organization. 
If the same user gets to an other organization, that the organization in the accesstoken disappears …

### Anything else?

No …

**Comment by pedroigor** [comment] 2024-11-01 14:24
Thanks. Looks like a duplicate of https://github.com/keycloak/keycloak/issues/33938.

**Closed** 2024-11-01 14:24 UTC
Labels: kind/bug, team/core-iam, area/organizations

**Comment by Lord-KalEl** [comment] 2024-11-04 00:58
This is a different issue:
In my case, it's NOT about the authentification, it's after the authentification. It is about the access token. (is this really the same? No …)

Please open https://github.com/keycloak/keycloak/issues/34535 again.

Greetings,
Kal

**Comment by Lord-KalEl** [comment] 2024-11-04 01:00
> Thanks. Looks like a duplicate of #33938.

No, this is a different issue:
In my case, it's NOT about the authentification, it's after the authentification. It is about the access token. (is this really the same? No …)

Please open https://github.com/keycloak/keycloak/issues/34535 again.

Greetings,
Kal

**Comment by bickelj** [comment] 2024-11-19 16:34
@Lord-KalEl I think perhaps [this one](https://github.com/keycloak/keycloak/issues/33556#issuecomment-2427470489) or [my interpretation here](https://github.com/PhilanthropyDataCommons/service/issues/1291#issuecomment-2486180923) may help.

@pedroigor @martin-kanis I see that I am not alone in my expectation that joining multiple organizations would mean my `organization` token claim would show all of them. I think this issue will keep coming up. Is there a use for this case of disappearing the `organization` from the token?
