### ISSUE TITLE
Users with a federation link cannot be deleted

### ISSUE THREAD

**Issue by daniel-frak** [keycloak/keycloak#34747] opened 2024-11-07 14:16 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

Users with federation links cannot be deleted for some reason and the message provided is cryptic.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The user is not deleted and the error message "User couldn't be deleted" is returned.

Deleting this user is only possible by either using "Remove imported" on the User Federation Provider, or by removing the provider entirely.

### Actual behavior

The user gets successfully deleted.

### How to Reproduce?

1. Add a user with a federation link through a User Federation Provider
2. Try to delete the user (e.g. through the admin UI)

### Anything else?

[Keycloak logs](https://github.com/user-attachments/files/17662805/keycloak_logs.txt)

**Comment by pedroigor** [comment] 2024-11-12 19:24
Not able to reproduce using LDAP. Do you have a custom extension?

**Comment by daniel-frak** [comment] 2024-11-13 06:58
@pedroigor The issue was noticed with my Keycloak Migration plugin (link directly to the provider code):

https://github.com/daniel-frak/keycloak-user-migration/tree/master/src/main/java/com/danielfrak/code/keycloak/providers/rest

`UserModelFactory` contains the code to create a `UserModel`:

https://github.com/daniel-frak/keycloak-user-migration/blob/master/src/main/java/com/danielfrak/code/keycloak/providers/rest/remote/UserModelFactory.java

I was able to reproduce this manually after receiving reports about it, but I can also write a Cypress test for it (the repository contains a whole docker-compose environment with preconfigured Keycloak), if that will help.

**Comment by pedroigor** [comment] 2024-11-13 10:56
Thanks. The only thing I can think of is that your provider seems to not implement `UserRegistrationProvider`. In this case, you should expect an error because there is no provider capable of deleting the user.

I don't see anything in your logs related to this but we have enough tests to make sure this works well for our built-in providers (e.g.: LDAP) and custom ones.

**Comment by pedroigor** [comment] 2024-11-22 19:45
Yeah, the `UserRegistrationProvider` is for adding/deleting users but if your provider does not implement this interface you might end up reaching https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L365.

As I mentioned, I appreciate it if you could debug and see what is happening starting from the lines above. As I mentioned, we do have coverage for such a scenario in our test suite.

**Comment by daniel-frak** [comment] 2024-11-25 07:29
I've attached a debugger and it never gets as far down as the line you linked to.

Here's a line-by-line of what happens:

- Line 346: `getFederatedStorage().preRemove(realm, user);` is called
- Line 353: `storageId.getProviderId()` is `NOT NULL`
- Line 355: `federationLink` is `NOT NULL` but **`getStorageProviderInstance(realm, federationLink, UserRegistrationProvider.class)` is `NULL` so `provider.removeUser(realm, user)` never gets called and `linkRemoved` becomes `FALSE`**
- Line 360: `localStorage().removeUser(realm, user)` returns `TRUE` but, since `linkRemoved` is `FALSE`, the entire method returns `FALSE`.

It seems, at first glance, that it fails because Keycloak can't find a `UserRegistrationProvider` and is not able to ignore that fact.

**Comment by pedroigor** [comment] 2024-11-25 12:05
Thanks for sorting it out. Did you try to update your provider to implement the interface?

I'm closing the issue as it seems the behavior from the description is expected.

**Comment by pedroigor** [comment] 2024-12-02 18:40
Yeah, that is how it was designed. I see your point but to make it work you will need to implement that interface.

**Closed** 2024-12-02 18:41 UTC
Labels: kind/bug, area/account/api, team/core-iam, team/core-shared
