### ISSUE TITLE
Importing Realm with declarative user profile attributes fails

### ISSUE THREAD

**Issue by hlavki** [keycloak/keycloak#26266] opened 2024-01-17 12:47 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Using declarative user profile in keycloak 22.0.5 with custom user attributes. Now I tried to upgrade keycloak to 23.0.4, so I exported realm and tried to import into 23.0.4 in our tests and keycloak says.

<details>
<summary>Exception:</summary>

```
2024-01-17 12:32:00,771 ERROR [org.keycloak.storage.datastore.LegacyMigrationManager] (executor-thread-2) Failed to migrate json representation for version: 23.0.0: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getClientScopesStream()" because "realm" is null
        at org.keycloak.userprofile.config.UPConfigUtils.validateScopes(UPConfigUtils.java:195)
        at org.keycloak.userprofile.config.UPConfigUtils.validateAttribute(UPConfigUtils.java:165)
        at org.keycloak.userprofile.config.UPConfigUtils.lambda$validateAttributes$2(UPConfigUtils.java:118)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.keycloak.userprofile.config.UPConfigUtils.validateAttributes(UPConfigUtils.java:118)
        at org.keycloak.userprofile.config.UPConfigUtils.validate(UPConfigUtils.java:95)
        at org.keycloak.userprofile.DeclarativeUserProfileProvider.validateConfiguration(DeclarativeUserProfileProvider.java:199)
        at org.keycloak.models.jpa.RealmAdapter.updateComponent(RealmAdapter.java:2088)
        at org.keycloak.migration.migrators.MigrateTo23_0_0.updateUserProfileConfig(MigrateTo23_0_0.java:92)
        at org.keycloak.migration.migrators.MigrateTo23_0_0.migrateRealm(MigrateTo23_0_0.java:65)
        at org.keycloak.migration.migrators.MigrateTo23_0_0.migrateImport(MigrateTo23_0_0.java:61)
        at org.keycloak.storage.datastore.LegacyMigrationManager.migrate(LegacyMigrationManager.java:186)
        at org.keycloak.migration.MigrationModelManager.migrateImport(MigrationModelManager.java:37)
        at org.keycloak.storage.datastore.LegacyDatastoreProviderFactory.onEvent(LegacyDatastoreProviderFactory.java:95)
        at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
        at org.keycloak.storage.LegacyStoreMigrateRepresentationEvent.fire(LegacyStoreMigrateRepresentationEvent.java:45)
        at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:611)
        at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:504)
        at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:54)
        at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
        at org.keycloak.storage.ImportRealmFromRepresentationEvent.fire(ImportRealmFromRepresentationEvent.java:50)
        at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:161)
        at org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:143)
        at org.keycloak.services.resources.admin.RealmsAdminResource$quarkusrestinvoker$importRealm_6d35df38bd8803a41904a3ba2b8d4b916b587fb6.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
``` 
</details>

When I delete configuration of custom attributes from [realm-export.json](https://github.com/keycloak/keycloak/files/13963334/realm-export.json), it works without issue.

Command to run keycloak:
```bash
docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:23.0.4 start-dev --features=declarative-user-profile
```

### Version

23.0.4

### Expected behavior

Realm should be properly imported.

### Actual behavior

Error occurs while importing realm json that contains custom attributes configuration.

### How to Reproduce?

Import attached realm file.

**Comment by sschu** [comment] 2024-01-18 16:32
The cause is that `RealmModel realm = session.getContext().getRealm();` is called in `validateScopes()` and there is no session when running a migration. I think there was a pretty similar problem recently, I just cannot find the issue.

**Comment by mposolda** [comment] 2024-01-25 18:41
@hlavki Could you please try to download latest Keycloak nightly release from https://github.com/keycloak/keycloak/releases/tag/nightly and check if you can import your realm? As it is possible that this is already fixed in latest Keycloak main.

**Comment by mposolda** [comment] 2024-01-29 18:21
I am able to reproduce with latest Keycloak main. Will try to investigate and fix this...

**Closed** 2024-02-01 08:54 UTC
Labels: kind/bug, priority/important, area/user-profile, area/import-export, team/store, team/core
