### ISSUE TITLE
Operator Support for missing leading slash and present trailing slash in `http-relative-path`

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#16800] opened 2023-02-02 16:39 UTC
This is a follow-up from https://github.com/keycloak/keycloak/pull/16736.

The Operator needs to support:
* missing leading slash, e.g. `auth`
* present trailing slash, e.g. `auth/`
* the combination of both, e.g. `/auth/`

Currently, the Operator [expects](https://github.com/keycloak/keycloak/blob/d12aef0b433a71f5a542486d708e8831886a2bab/operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java#L411-L414) the `http-relative-path` to have only leading slash (`/auth`).

**Comment by nrobert13** [comment] 2023-02-03 14:13
Another thing to consider, is that if you use custom image with the operator, it will automatically add `--optimized` to `start`, which means that the build options configured by the operator won't have any effect. This was the problem in my case. I had to add the `relative-path` to the custom image. So maybe either make the `--optimized` configurable in the operator, or log some messages regarding the build option during startup.

**Comment by shawkins** [comment] 2023-06-26 21:49
Duplicate of #17388

**Closed by shawkins** 2023-06-26 21:49 UTC
Labels: kind/enhancement, area/operator

**Comment by vmuzikar** [comment] 2023-06-27 07:50
@shawkins Closing rather as "Not planned" to avoid spamming the release notes. :)

**Comment by vmuzikar** [comment] 2023-06-27 07:50
https://github.com/keycloak/keycloak/blob/bdb4dd807099e6cd6c622cf9c91ce88377d70618/operator/src/main/resources/example-realm.yaml
