### ISSUE TITLE
Keycloak.v2 admin theme race condition with fetch in MacOS Safari

### ISSUE THREAD

**Issue by Hildebrand-Ritense** [keycloak/keycloak#20114] opened 2023-05-03 09:31 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

While using Safari version 16.4 (18615.1.26.11.23) on a MacBook Pro 16-inch 2021 (Apple M1 Max) running 13.3.1 I get consistent fails to load the login screen (/auth/admin/master/console/#/) when using the keycloak.v2 admin theme.

### Version

20.0.3

### Expected behavior

The login page loads. All (i18n) resources get requested without Safari blocking the fetchAPI calls.

### Actual behavior

Safari's console log shows a varying amount of the following lines that seem to be related to the translation resources:
[Error] Fetch API cannot load https://\<my-domain>/auth/resources/np47i/admin/keycloak.v2/resources/en/identity-providers.json due to access control checks.
	a (index.598a336e.js:20412)
	a (index.598a336e.js:20428)
	value (index.598a336e.js:20539)
	(anonymous function) (index.598a336e.js:20533)

It seems that a number of these resource calls do succeed. This is analysed using burp suite intercepts.

Ultimately, due to the failing i18n resource requests. Safari breaks on: [Error] TypeError: undefined is not an object (evaluating '_.resourceStore.data[_.language].overrides') at process — index.598a336e.js:20810

After investigating the code I suspect it's a race condition where a number of calls in the call queue fail and a number of calls succeed depending on if the fetchApi has been defined/replaced depending on the browser/DOM in lines 20396..20402.

I've ruled out any CORS issues. The requests are made to the same origin.
Chrome has no issues with this fetch code.
Using the v1 keycloak admin theme fixes this issue.

### How to Reproduce?

- Use Safari on MacOS
- Go to keycloak domain /auth (KC has been configured with KC_HTTP_RELATIVE_PATH=/auth)
- See the page load hanging indefinitely

### Anything else?

Running using a PostgreSQL DB.
Running in reverse proxy mode using KC_PROXY=edge.

**Comment by jonkoops** [comment] 2023-05-04 08:44
@Hildebrand-Ritense could you try to reproduce this with the latest [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly) of Keycloak?

**Comment by jonkoops** [comment] 2023-05-17 08:09
Considering this issue seems to be resolved in the nightly and the author of this issue has not gotten back to us I am considering this fixed. Feel free to let us know if this is still an issue.

**Closed by jonkoops** 2023-05-17 08:09 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
