### ISSUE TITLE
Unable setup keycloak in windows from source code.

### ISSUE THREAD

**Issue by nmanthena18** [keycloak/keycloak#21716] opened 2023-07-16 04:35 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

We are facing issue while setup the application locally from source code I am refering this guide for local setup on windows machine.

[](https://github.com/keycloak/keycloak/blob/main/docs/building.md)

`java -version
mvn -version
git --version
` after this I got this.

$ java -version
```
java version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
```

$ mvn -version
```
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: F:\workspace\apache-maven-3.9.2
Java version: 20.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-20
Default locale: en_IN, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

$ git --version
`git version 2.40.0.windows.1`

Then i execute this command after cloning in my keycloak source code  folder.

`mvn clean install`

I got below error 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:18 min
[INFO] Finished at: 2023-07-16T09:33:11+05:30
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 10 plugin(s)
[WARNING]
[WARNING]  * org.apache.felix:maven-bundle-plugin:2.4.0
[WARNING]  * org.apache.maven.plugins:maven-jar-plugin:3.1.2
[WARNING]  * org.apache.maven.plugins:maven-install-plugin:2.5.2
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.2.0
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.8.1
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:3.1.0
[WARNING]  * org.codehaus.mojo:buildnumber-maven-plugin:1.4
[WARNING]  * org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[WARNING]  * org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3
[WARNING]  * org.apache.maven.plugins:maven-source-plugin:3.1.0
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project keycloak-services: There are test failures.
[ERROR]
[ERROR] Please refer to F:\workspace\keycloak\keycloak-22.0.0-source\keycloak\services\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :keycloak-services
```

`mvn clean install -DskipTests=true`
If I skip the testcase I am getting this error. 

`Unresolved dependency: 'org.keycloak.testsuite:integration-arquillian-servers-app-server-wildfly:jar:999.0.0-SNAPSHOT'`

I have refer this suggestion from @Ezreal147 [](https://github.com/keycloak/keycloak/issues/20475)

somehow its working after doing this but its not creating any distribution

`mvn clean install -Pdistribution -DskipTests=true`

this also no luck, please suggest what i missed here.

### Version

22.0.0

### Expected behavior

`mvn clean install`

It suppose run whole keycloak on window machine locally

### Actual behavior

```
[WARNING]
[WARNING] Plugin validation issues were detected in 10 plugin(s)
[WARNING]
[WARNING]  * org.apache.felix:maven-bundle-plugin:2.4.0
[WARNING]  * org.apache.maven.plugins:maven-jar-plugin:3.1.2
[WARNING]  * org.apache.maven.plugins:maven-install-plugin:2.5.2
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.2.0
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.8.1
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:3.1.0
[WARNING]  * org.codehaus.mojo:buildnumber-maven-plugin:1.4
[WARNING]  * org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[WARNING]  * org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3
[WARNING]  * org.apache.maven.plugins:maven-source-plugin:3.1.0
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project keycloak-services: There are test failures.
[ERROR]
[ERROR] Please refer to F:\workspace\keycloak\keycloak-22.0.0-source\keycloak\services\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :keycloak-services
```

### How to Reproduce?

here are the details

OS windows 11.

```
$ java -version
java version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
```

```
$ mvn -version
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: F:\workspace\apache-maven-3.9.2
Java version: 20.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-20
Default locale: en_IN, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

```
$ git --version
git version 2.40.0.windows.1
```

**Comment by akbar1214** [comment] 2023-07-16 05:03
@nmanthena18 did you add the mirror for maven as mentioned in https://github.com/keycloak/keycloak/blob/main/docs/building.md#L14

**Comment by nmanthena18** [comment] 2023-07-16 07:28
@akbar1214 - Yes I have added this in my .m2/settings.xml file.

this is in my file. 
`<mirrors>
  <mirror>
    <id>jboss-public-repository-group-https</id>
    <mirrorOf>jboss-public-repository-group</mirrorOf>
    <name>Jboss public https</name>
    <url>https://repository.jboss.org/nexus/content/groups/public/</url>
  </mirror>
</mirrors>`

**Comment by christian-2** [comment] 2023-07-16 08:53
related #20494

**Comment by nmanthena18** [comment] 2023-07-16 13:03
@christian-2 its working fine with quarks instructions guide
`https://github.com/abstractj/keycloak/blob/issue-16790/quarkus/README.md`

but how i can build from root folder?

**Comment by christian-2** [comment] 2023-07-18 00:01
Well, I'm asking the same question.

I've gotten a bit further towards that goal, but `mvn clean install` still fails (after several hours of preliminary success) in `testsuite/integration-arquillian/tests/base` ("Base TestSuite"). This currently hinders me from extending a PR, because I cannot run relating tests.

**Comment by ahus1** [comment] 2023-07-18 07:52
@nmanthena18 - I've looked at the logs your provided, and there it states: 

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project keycloak-services: There are test failures.
[ERROR]
[ERROR] Please refer to F:\workspace\keycloak\keycloak-22.0.0-source\keycloak\services\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

So there are test failures, and the answer what failed there is the file referenced there. There should also be more information about failing tests before the `BUILD FAILURE` message.

Please note that this project includes Maven wrapper. Instead of starting `mvn`, start the wrapper `mvnw` in the root folder of the project. It will start the maven version that we also use for our builds, which is 3.8.6. 

When running Java, please retry using Java 17, which is the Java version Keycloak supports.

**Comment by Pepo48** [comment] 2023-07-20 15:58
> I've gotten a bit further towards that goal, but `mvn clean install` still fails (after several hours of preliminary success) in `testsuite/integration-arquillian/tests/base` ("Base TestSuite"). This currently hinders me from extending a PR, because I cannot run relating tests.

I could reproduce the same couple days ago. There is another windows specific issue already reported (and possibly related): #21284

**Comment by ahus1** [comment] 2023-07-20 16:12
Thank you @Pepo48 for linking the issue. 
Suggested workaround while this is being fixed for building Keycloak: 
On Windows, add two profiles (Windows and the usual default profile) on the command line like this from the root folder:

```
mvnw clean install -Pwindows-properties-cli,app-server-wildfly ...
```

@christian-2 - if you see failing tests on Windows, please provide the full log output of the Maven command. Only then will I know which tests failed.

**Comment by christian-2** [comment] 2023-07-20 16:24
@ahus1 I'm on Debian (see above). 

If it helps, I could try specific steps on a Debian 12.0 host that was just installed, and we could take it from there. If applicable, what specific invocation of (presumably) `mvnw ... ` (perhaps also with `-Dbrowser=... -Dwebdriver=...`) should I try immediately after `git clone https://github.com/keycloak/keycloak.git && cd keycloak`?

**Comment by ahus1** [comment] 2023-07-20 16:28
@christian-2 - yes, that would be helpful. 

Please record all commands and all outputs. 

To clear the contents of your local maven cache, clear all previously built Maven Keycloak artifacts first:

```
rm ~/.m2/repository/org/keycloak/
``` 

Thanks.

**Comment by christian-2** [comment] 2023-07-20 17:08
@ahus1 So yes, I can do that (probably within the next few days). But I still need the specific command line (`mvnw ...`) that you want me to invoke. (I can e.g. install [Chrome](https://support.google.com/chrome/a/answer/9025926) from `google-chrome-stable_current_amd64.deb` and [ChromeDriver](https://sites.google.com/chromium.org/driver/) from `chromedriver_linux64.zip` prior to `mvnw`.)

**Comment by ahus1** [comment] 2023-07-21 08:52
@christian-2 - I'm afraid if I write things down here, we'll never fix the docs available. As I'm working with the Keycloak code base on a daily basis, I'm unable to read those docs with new eyes. Therefore I'm suggesting the following: 

* Use is `docs/building.md`, `docs/tests.md`, `quarkus/README.md` and `quarkus/CONTRIBUTING.md`. Try to make best use of that documentation, write down the questions you have and possibly the assumptions you make. 
* Record all the command with all CLI options you execute.
* Record all the output for example from Maven runs. 

When something doesn't work, you might want to retry exchanging a `mvn` command with a `mvnw` command. There is an upcoming PR #20883 which will update most commands to `mvnw`.

**Comment by christian-2** [comment] 2023-07-21 09:16
@ahus1 I can see you point of view, but please also see mine: I have started out with `docs/building.md`, etc., and spent considerable effort. Without a specific entrypoint (as opposed to a list of resources to revisit), pursuing this further is not a good use of my time at present, I'm afraid.

**Comment by Pepo48** [comment] 2023-07-23 23:25
Getting back to the original topic - building the project on the Windows platform - based on my investigation, the issue is caused by the changes introduced in #20976. jFTR, these changes also caused #21625, which was then promptly fixed by #21655. But seemingly the issue with building the project specifically on Windows has remained since then.

**Comment by mabartos** [comment] 2023-07-24 09:16
As I've mentioned in the #21284, the problem with building Keycloak for Windows is related to the Maven profile activation. We're now using the `app-server-wildfly` as the default app server in the testsuite. The profile is activated via the activation element `activeByDefault=true`[1]. When some other profile is activated in the module, that one activated by `activeByDefault` property is disabled[2]. 

It means, that for Linux distros everything works as expected because no other profile is enabled in the module. For Win, the `windows-properties-cli` profile is activated based on the OS profile activation, and thus `app-server-wildfly` profile is disabled.

It means when you explicitly specify the profile `-Papp-server-wildfly`, everything should be working as expected.
To have it automatically enabled, it'd require some workarounds around profiles, but it'd be good to, at least, update the documentation for now. @ahus1 WDYT?

[1] https://github.com/keycloak/keycloak/blob/bd0f87fc4d281b869ef067afc6bfd8f5eaf3848b/testsuite/integration-arquillian/servers/app-server/jboss/pom.xml#L838
[2] https://maven.apache.org/guides/introduction/introduction-to-profiles.html#implicit-profile-activation

**Comment by Pepo48** [comment] 2023-07-24 18:52
Interestingly, while I was investigating and testing https://github.com/keycloak/keycloak/pull/21926 with the current upstream, I'm not currently observing any issues regarding the project building on the Windows platform.

**Comment by mabartos** [comment] 2023-07-25 09:18
@Pepo48 Possible explanation could be that you already had the artifact for `app-server-wildfly` in the m2 cache. However, when I tried to build Keycloak on Windows from the parent module, the artifact was not found.

**Comment by Pepo48** [comment] 2023-07-25 09:28
No, I don't think I have, it hadn't worked for me the same was but once I rebased on the current main, it worked. On top of that I invalidate the caches in intellij, I cleaned up the local m2 repo and I did used ˇgit clean...` before the build.

Thanks for trying it anyway.

**Comment by mabartos** [comment] 2023-07-27 13:35
@nmanthena18 Could you please try to reproduce it with the latest upstream main? I've made some changes there, which could be related to this issue. Please, let me know.

**Comment by nmanthena18** [comment] 2023-07-28 00:46
@mabartos sure I will keep you posted with updates

**Comment by surendra-battula** [comment] 2023-07-28 06:07
![Screenshot (6)](https://github.com/keycloak/keycloak/assets/116184474/e9351741-1bd0-4163-9ebb-9580f586e89d)

still im getting this issue while running in developement mode.

**Comment by nmanthena18** [comment] 2023-07-28 06:49
@mabartos I think still we have the same issue as @surendra-battula metioned above, he tested with latest latest from the main branch.

**Comment by Pepo48** [comment] 2023-07-28 07:06
can you guys share with us the whole stack trace (the part before the build summary, where the error happened)?

**Comment by nmanthena18** [comment] 2023-08-05 13:37
@Pepo48  - as you suggested done samething but got below errors.

[ERROR] Failed to execute goal on project keycloak-junit5: Could not resolve dependencies for project org.keycloak:keycloak-junit5:jar:999.0.0-SNAPSHOT: Failed to collect dependencies at io.quarkus:quarkus-junit5:jar:3.2.3.Final: Failed to read artifact descriptor for io.quarkus:quarkus-junit5:jar:3.2.3.Final: The following artifacts could not be resolved: io.quarkus:quarkus-junit5:pom:3.2.3.Final (absent): Could not transfer artifact io.quarkus:quarkus-junit5:pom:3.2.3.Final from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :keycloak-junit5`
`

**Comment by Pepo48** [comment] 2023-10-18 13:08
@nmanthena18 the error message suggests that your .m2 local repo is in inconsistent state. Please, try to delete the affected artifacts (or the whole repo) and let maven to redownload them again.

**Comment by Pepo48** [comment] 2023-10-18 13:13
@surendra-battula based on what I see on the screenshots, you experienced a testsuite failure, not a build failure.

If the particular test is still unstable in your environment, feel free to create a separate issue. Otherwise, you can skip the tests if you just need to build a distribution from a source code.

Thanks!

**Comment by Pepo48** [comment] 2023-12-06 23:33
Since there are no more replies I’m going to close this one for now, but you can always reopen it later if you have more questions or feedback. 

Thanks everybody for the cooperation.

**Closed** 2023-12-06 23:34 UTC
Labels: kind/bug, area/core, status/triage, team/core

**Comment by Nefcanto** [comment] 2024-02-06 06:40
I can't build a clean source even on Linux distros. I tried on Debian 12 and Ubuntu 22.0.4.

I installed JDK 17, cloned the Keycloak source and ran `./mvnw clean install` from the root of the project, and it did not get built. Both on the Debian and on the Ubuntu. I reported it in https://github.com/keycloak/keycloak/issues/26807

**Comment by Nefcanto** [comment] 2024-07-19 13:39
@sirine707 no I simply did not.
