### ISSUE TITLE
Keycloak shows reset password window even in case user uses Okta to login

### ISSUE THREAD

**Issue by mkopeyka** [keycloak/keycloak#24075] opened 2023-10-18 08:48 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

I have a user with username/password to use standard login form.
Also I have configured keycloak to login via Okta.
Everything works fine until keycloak applies password expiration policy to the user. As a result user tries to login via Okta but keycloak displays window to reset password.

### Version

20.0.2

### Expected behavior

Keycloak shouldn't check user password expiration time in case user doesn't use password to login

### Actual behavior

Keycloak checks user password expiration time even if user use Okta instead of username/password form

### How to Reproduce?

1. Configure Keycloak IDP and client to use Okta
2. Set Required User Actions `update password` for test user
3. Use okta to login with test user

**Comment by rmartinc** [comment] 2023-10-19 11:05
Duplicate of https://github.com/keycloak/keycloak/issues/17155.
Closing as I think you are requesting exactly the same issue.

**Closed by rmartinc** 2023-10-19 11:05 UTC
Labels: area/saml, kind/bug, status/triage, team/core
