### ISSUE TITLE
Uncaught Error: Permission denied to access property "__reactFiber$0jlmu2c2v1we"

### ISSUE THREAD

**Issue by m1212e** [keycloak/keycloak#26822] opened 2024-02-06 11:57 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

![image](https://github.com/keycloak/keycloak/assets/14091540/19db61d8-d0cc-43c1-abcf-b5bd6e4fb57c)

When trying to set credentials for a user, in the moment where I paste the password value the dialog closes and this is shown.

```
Uncaught Error: Permission denied to access property "__reactFiber$0jlmu2c2v1we"
    React 30
        Wc
        hd
        Rk
        Jb
        hd
        fd
        gd
        pf
        qf
        sf
        sf
        Fj
        Tk
        Vk
        Uk
        Jk
        Fk
        jg
        Rk
        Jb
        hd
        fd
        ed
        pf
        qf
        sf
        sf
        rl
        sl
        render
    <anonymous> main.tsx:21
2 [react-dom.production.min.js:123:21](https://[REDACTED]/resources/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.production.min.js)
    React 10
    forEach self-hosted:4380
    React 16
    forEach self-hosted:4380
    React 4
    <anonymous> main.tsx:21
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
```

### Version

22.0.1

### Expected behavior

I'd expect the password set to work

### Actual behavior

What described above

### How to Reproduce?

Unsure what causes this to be honest, but as far as I can see just follow the steps I described. It also works when I just run the docker image locally

### Anything else?

No

**Comment by m1212e** [comment] 2024-02-06 13:00
It is still valid for the most recent version, I just tested it. Also, this seems to only happen in Firefox. Do you guys test in Firefox?

**Comment by jonkoops** [comment] 2024-02-06 13:02
Thanks for validating that. I'll re-open the issue. Could you perhaps also check if this occurs in the [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly). 

> Do you guys test in Firefox?

Yes, a large quantity of our devs are using Firefox, and we run nightly integration tests on Firefox as well. Which version of Firefox are you using, and on what operating system?

**Comment by ssilvert** [comment] 2024-02-12 19:19
@m1212e Have you tried other browsers in your environment?  I think we would be getting a lot of complaints if this were a widespread problem.

**Comment by PierreB-V** [comment] 2024-02-13 10:25
I get the same error in Firefox 122.0.1  with keycloak 23.0.6  when using another account than the original admin one. And the roles must be correct since the same action works with Chrome.  
I get the error when typing a new passord when reset credential for a realm user.

**Comment by m1212e** [comment] 2024-02-13 13:37
Yes I can secon pierres comment. Tried with all extensions disabled and in various scenarios. Works in Chromium based browsers. Could not determine whats causing this.

**Comment by edewit** [comment] 2024-02-15 07:58
I've installed bitwarden on my firefox and let it fill out the password, but I couldn't reproduce this

**Comment by jonkoops** [comment] 2024-02-15 12:00
Any chance we could get a more detailed stack trace? Perhaps someone can open up their browser console?

**Comment by m1212e** [comment] 2024-02-18 14:40
Hi, sure this is the error message copied from my browser console:

```
Error: Permission denied to access property "setAttribute"
    toggleSiblingsFromScreenReaders Modal.js:40
    componentDidUpdate Modal.js:84
    React 28
        xi
        Si
        Si
        wi
        Es
        Es
        fs
        Ql
        ps
        Fe
        $r
        Xn
        Kn
        jr
        Wr
        Qr
        Qr
        Xo
        xs
        Ss
        ks
        bs
        fs
        Ql
        us
        us
        as
        ro
    o UserCredentials.tsx:113
    React 16
        Oe
        He
        Vr
        Vr
        Ar
        r
        ds
        Fe
        $r
        Xn
        Kn
        jr
        Wr
        Qr
        Qr
        createRoot
    <anonymous> main.tsx:20
react-dom.production.min.js:10:71285

```
```
toggleSiblingsFromScreenReaders (http://localhost:8080/resources/qmnzo/admin/keycloak.v2/assets/Modal-EL6ZZzO6.js#40)
componentDidUpdate (http://localhost:8080/resources/qmnzo/admin/keycloak.v2/assets/Modal-EL6ZZzO6.js#84)
xi (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Si (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Si (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
wi (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Es (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Es (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
fs (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Ql (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
ps (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Fe (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
$r (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Xn (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Kn (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
jr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Wr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Qr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Qr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Xo (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
xs (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Ss (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
ks (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
bs (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
fs (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Ql (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
us (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
us (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
as (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
ro (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
o (http://localhost:8080/resources/qmnzo/admin/keycloak.v2/assets/EditUser-CmMSRh9d.js#113)
Oe (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
He (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Vr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Vr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Ar (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
r (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
ds (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Fe (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
$r (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Xn (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Kn (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
jr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Wr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Qr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
Qr (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
createRoot (http://localhost:8080/resources/qmnzo/common/keycloak/vendor/react-dom/react-dom.production.min.js#10)
<anonymous> (http://localhost:8080/resources/qmnzo/admin/keycloak.v2/assets/index-GvZjRBc8.js#20)
```
Is this what you need? Also recently I observed that this happens a lot less frequently, I just can't find out whats the cause for this happening. Can not even trigger the error now reliably..

**Comment by jonkoops** [comment] 2024-02-28 13:10
Looking at the stack trace, it seems to be an issue with [a piece of code in PatternFlty](https://github.com/patternfly/patternfly-react/blob/c07b540a74ca2c9a8b644cfa8bb38fd29ef4b0a7/packages/react-core/src/components/Modal/Modal.tsx#L155-L164).

**Comment by ssilvert** [comment] 2024-03-13 19:32
I couldn't reproduce this either.  I'm going to take it out of triage and give it normal priority.

We are upgrading to PatternFly 5 soon, so maybe that will fix it?

@m1212e @PierreB-V This issue could get auto-closed.  If it does and you continue to have problems we can reopen.

**Comment by oneil1838** [comment] 2024-03-14 20:33
I found a workaround that worked for me: open inkognito tab from the keykloak instance and try it there again. Also with another browser (in my case Firefox on Android) it works fine for me.

**Comment by MarcoGriep88** [comment] 2024-03-24 12:41
👍

**Comment by mittkkoo** [comment] 2024-03-30 08:25
24.0.2: Firefox and Firefox incognito fail. Safari works.

**Comment by ErikTraedal** [comment] 2024-03-30 08:29
24.0.2 fails here as well in both normal and incognito, when Bitwarden is enabled.
Works as expected without Bitwarden.

**Comment by edewit** [comment] 2024-04-02 10:42
Right, did some more investigation and found that the error is in Patternfly it tries to set the attributes of the component that bitwarden puts in the page to render the tool tip. That only fails with Firefox, so the workaround is to disable bitwarden. Created an issue for Patternfly https://github.com/patternfly/patternfly-react/issues/10234

**Comment by jonkoops** [comment] 2024-04-02 10:47
Since this issue should be handled in PatternFly I am closing it here. Once the issue is resolved we will upgrade our PatternFly version automatically, so it will resolve itself in due time.

**Closed by jonkoops** 2024-04-02 10:47 UTC
Labels: kind/bug, priority/important, area/admin/ui, help wanted, team/ui, status/bumped-by-bot
