### ISSUE TITLE
Keycloak 25 - protocol_mapper_config stores client_uid in usermodel.clientRoleMapping.clientId instead of client_id

### ISSUE THREAD

**Issue by DimeOne** [keycloak/keycloak#31023] opened 2024-07-03 11:48 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After Upgrading to Keycloak 25 and editing a client dedicated scope with "client roles" token mapper field "Client Id" - the mapper no longer works.

After some debugging, It was apparent, that the value stored in the database is no longer the client_id but instead the clients uid.

Resulting in the tokens not having the required claims.

### Version

25.0.1 with Postgres 16

### Regression

- [X] The issue is a regression

### Expected behavior

When creating a client roles mapper, I expect these roles to be listed in the configured tokens.

Querying the database directly, I expect all values to be names of clients existing in my realm: 
  SELECT * FROM public.protocol_mapper_config WHERE name = 'usermodel.clientRoleMapping.clientId'

### Actual behavior

When creating a client roles mapper, I do not get these roles listed in the configured tokens.

When taking a look at my database, I noticed that the client id format changed after saving it.

![image](https://github.com/keycloak/keycloak/assets/1115938/8b9d725b-7005-44ed-bcb3-a7dd83a29c1f)

On this image we can see a mix of client names and uid's in that field. After manually updating that field with the client id instead of the uid - and restarting Keycloak - the client role mapper is finally working again.

b) After migrating from Keycloak 24 - the value of Client ID is no longer displayed
c) When typing the name manually, it isn't saved.

### How to Reproduce?

Create a client role mapper in Keycloak 25 - check the database representation, 

SELECT * FROM public.protocol_mapper_config WHERE name = 'usermodel.clientRoleMapping.clientId'

Should return the client namens configured for the client roles mappers, not UIDs.

### Anything else?
Workaround: manually update database like:

Update public.protocol_mapper_config SET value = 'git' WHERE protocol_mapper_id = '6efade79-a329-4c4f-8b28-2fe1a4ef6ed2' AND name = 'usermodel.clientRoleMapping.clientId'

**Comment by edewit** [comment] 2024-07-08 05:39
duplicate of https://github.com/keycloak/keycloak/issues/30436

**Closed by edewit** 2024-07-08 05:39 UTC
Labels: kind/bug, priority/blocker, area/admin/ui, team/ui, kind/regression
