### ISSUE TITLE
Duplicated user on group Members tab

### ISSUE THREAD

**Issue by MariiaAlekseichuk** [keycloak/keycloak#19370] opened 2023-03-28 06:40 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

User duplicated on Members list for group (Groups in menu) in Admin Console if this user is member of group in LDAP and also member of this group in database (was added as member manually before user was added as member in LDAP, for example).

### Version

17.0.0

### Expected behavior

user is not duplicated in membership list

### Actual behavior

user is duplicated in membership list

### How to Reproduce?

1. Group was imported and synced from LDAP.
2. Some users were added manually to this group using Admin Console.
3. One of this users from step 2 was added to this group in LDAP.
4. After group was synced this user will be duplicated on Members tab for this group. This user is present in LDAP as member for this group and user present in database (user_group_membership table) as member, that's why user is duplicated, I guess.

**Comment by JonSzeto821** [comment] 2023-05-18 19:03
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.  
It will be helpful if:

-   You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
-   If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
-   If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
-   If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here [https://www.keycloak.org/community](https://www.keycloak.org/community) for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by dbisbos** [comment] 2023-09-15 15:08
Hello,
I'm facing to the exact same issue on Keycloak 22.0.0.
I'm using rest API since Keycloak 16 to search group members and it was ok since i upgraded to KC 22.0.0.
In fact, rest API is not working well with offsets.
In my code either the KC UI, when I look to any of them group, the second page of results already contains members of the first page !!
My testcase group contains 2700 members. When i browse with KC UI (or with my code) all members by 10 per page, after the 7th page, all pages are exactly equivalent !
I don't understand how it works.
It is very disturbing and breaks lot of things.

Can you restudy the priority of this issue ?

Thanks in advancea

**Comment by rmartinc** [comment] 2024-01-29 14:39
I have tested this and I cannot reproduce in the current main ranch. Probably this was solved by #23966 which is not still in any released version (it will be available in version 24). You can test with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).

I'm closing it. If you find that is still reproducible please re-open it or file a new issue with teh exact steps to reproduce.

Regards!

**Closed by rmartinc** 2024-01-29 14:39 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core
