### ISSUE TITLE
Configuration of LDAP doesn't work in Keycloak with Java 8

### ISSUE THREAD

**Issue by aastrahovich-sc** [keycloak/keycloak#12821] opened 2022-06-29 12:58 UTC
### Describe the bug

We got following error in Keycloak log when tried to configure LDAP while click on button "Test authentication" and error in Keycloak Administrative console 
![Screenshot from 2022-06-29 14-44-15](https://user-images.githubusercontent.com/44160034/176439306-e185b614-8c54-4113-bd81-fa8729cb0216.png)

The error in server.log
```
2022-06-28 16:47:23,672 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-15) Uncaught server error: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at org.keycloak.vault.DefaultVaultRawSecret.close(DefaultVaultRawSecret.java:90)
        at org.keycloak.vault.DefaultVaultTranscriber.getCharSecret(DefaultVaultTranscriber.java:84)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getVaultSecret(LDAPContextManager.java:108)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:72)
```
**Version Java** 
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-linux64) (build 25.282-b08, mixed mode)
After installed Java 11 (Zulu) and after that configuration of LDAP was successful.
```

### Version

17.0.0

### Expected behavior

I expected to see message successful in UI.
![Screenshot from 2022-06-29 14-45-53](https://user-images.githubusercontent.com/44160034/176439693-8c3d570b-b0a9-4070-b26d-09220e952d17.png)
 

### How to Reproduce?

The problem is reproduced on Java 8.
**System**
SUSE Linux Enterprise Server 12 SP5

**JAVA_OPTS**
```-Xms256m -Xmx1024m -Djboss.bind.address=127.0.0.1 -Djboss.http.port=8082 -Djboss.https.port=8443 -Dkeycloak.frontendUrl=https://customer.com/keycloak -Dkeycloak.profile.feature.upload_scripts=enabled ```

**Java version on which the problem is reproduced** 

```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-linux64) (build 25.282-b08, mixed mode)
After installed Java 11 (Zulu) and after that configuration of LDAP was successful.
```
**Java version on which the problem is NOT reproduced**
```
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)
```

**Comment by hmlnarik** [comment] 2022-11-09 08:44
Thank you for the report. This is a duplicate of #9885

**Comment by hmlnarik** [comment] 2022-11-09 08:44
Duplicate of #9885

**Closed by hmlnarik** 2022-11-09 08:44 UTC
Labels: kind/bug, area/ldap, status/triage
