### ISSUE TITLE
Realm import is failing for file based map storage keycloak deployment

### ISSUE THREAD

**Issue by sachinjohar2** [keycloak/keycloak#21613] opened 2023-07-11 21:29 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

import-export

### Describe the bug

Realm import is not happening for Keycloak running using file-based map storage.

Realm import does not happen either with KeycloakRealmImport CR or with kc.sh import option even after showing "Realm test imported" message in the logs.

**Ream import only works from the admin UI when running Keycloak using file-based map storage.**

**./kc.sh --verbose import --optimized --file /home/realm.json**
2023-07-11 21:12:35,204 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: **map-storage**
2023-07-11 21:12:35,604 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2023-07-11 21:12:35,605 WARN  [org.keycloak.models.DeploymentStateProviderFactory] (main) Version seed for deployment state set with a random number. Caution: This can lead to unstable operations when serving resources from the cluster without a sticky loadbalancer or when restarting nodes. Set the 'storage-deployment-state-version-seed' option with a secret seed to ensure stable operations.
2023-07-11 21:12:36,063 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-07-11 21:12:36,097 WARN  [org.keycloak.services.DefaultComponentFactoryProviderFactory] (main) No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.
2023-07-11 21:12:36,098 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-07-11 21:12:36,275 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /home/realm.json
2023-07-11 21:12:37,**070 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'test' imported**
2023-07-11 21:12:37,120 INFO  [io.quarkus] (main) Keycloak 22.0.0 on JVM (powered by Quarkus 3.2.0.Final) started in 2.340s. Listening on:
2023-07-11 21:12:37,120 INFO  [io.quarkus] (main) Profile import_export activated.
2023-07-11 21:12:37,120 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, vertx]
2023-07-11 21:12:37,135 INFO  [io.quarkus] (main) Keycloak stopped in 0.013s
 

### Version

22.0.0/nightly

### Expected behavior

Realm import should happen successfully using KeycloakReamImport CR or kc.sh script as well.

### Actual behavior

Realm import works only with Keycloak UI using admin API. It neither works with  KeycloakRealmImport operator CR nor with kc.sh script's import option

### How to Reproduce?

Try importing a realm using KeycloakRealmImport CR or kc.sh import option.

**Comment by ahus1** [comment] 2023-07-12 11:36
Please provide the full configuration on how you configured the store for this to be investigated.

One general comment: The file store is still experimental. For now I'd suggest allow copying file store contents as is without importing them via the classic JSON, as this is likely not being supported in the future.

**Comment by michewl** [comment] 2023-08-02 09:06
Hello @sachinjohar2, I am currently facing a similar issue in my deployment but using MariaDB. I could verify that the import indeed works as I do have the values in the database, however the realm does not show up in the UI.

After a restart of Keycloak, the imported realm is loaded.
It is also loaded, when I create a realm through the UI.

Do you observe a similar behavior?

To me, it looks like that some cache is not properly invalidated when the import is run, but it is with the REST API.

With a test project created with docker compose, I could not reproduce the issue. The issue was only observed in Kubernetes so far.

**Comment by ahus1** [comment] 2023-08-03 18:41
Closing this as the configuration of the store wasn't provided by the original reporter.

**Closed by ahus1** 2023-08-03 18:41 UTC
Labels: kind/bug, area/import-export, team/store, status/triage
