### ISSUE TITLE
SAML AuthNInstant is incorrectly generated

### ISSUE THREAD

**Issue by lagital** [keycloak/keycloak#31197] opened 2024-07-10 16:09 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

When generating SAMLResponse and AuthNStatement/AuthnInstant attribute value in particular, Keycloak always uses current system time, even though the meaning of AuthNInstant is different in the standard. The value should represent the moment of login in IdentityProvider, under which session SAMLResponse was issued. Description from Microsoft's docs as an example: https://learn.microsoft.com/en-us/entra/identity-platform/single-sign-on-saml-protocol#authnstatement

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

When Remember Me setting is set to On and the initial login has been done, on subsequent logins AuthNStatement/AuthNInstant attribute value in SAMLResponses generated by Keycloak must be equal to the time when the initial login occurred.

### Actual behavior

When Remember Me setting is set to On and the initial login has been done, on subsequent logins AuthNStatement/AuthNInstant attribute value in SAMLResponses generated by Keycloak equals to the current system time on the moment of the corresponding subsequent login.

### How to Reproduce?

1. Make a login attempt in SP
2. Get redirected to Keycloak for authentication, enable "Stay logged in" checkbox as True, which gives you a long-running authenticated session.
3. Pass the authentication and get SAMLResponse token with some lifetime validity, get redirected to SP.
4. Attempt to use the SP app after SAML token expiration.
6. Get redirected to Keycloak for authentication, which will pass automatically, because the session in Identity Provider is still active
7. Pass the authentication and get SAMLResponse token with some lifetime validity, get redirected to SP.
8. Compare AuthNStatement/AuthNInstant values from step 3 and step 7 - they will be different (AuthNInstant from step 7 is the current time of Keycloak server at the moment of step 7 processing)

**Comment by rmartinc** [comment] 2024-07-16 08:37
@lagital The spec for SAML says about `AuthnInstant` that `Specifies the time at which the authentication took place. The time value is encoded in UTC, as described in Section 1.3.3`. As you say we are adding the time between the interaction of the keycloak server with the saml request to authenticate (it doesn't matter if the server authenticated using the cookie, requesting username/password, certificate or anything in the authn flow).

I don't like to change this because I don't think we are not following the spec, and this can have important consequences in people now using keycloak with SAML. Besides I don't know how you are interpreting the spec here. What time did the `AuthnInstant` should have? The time the client session was created? (Note the client session have maybe not requested username/password either, because it was already logged in in another other client.) The time that user really interacted to present some credentials? (Which is not very easy to know.)

@mhajas @hmlnarik As you have worked with SAML in the past. WDYT? My vote is to not change anything for the moment.

**Comment by rmartinc** [comment] 2024-07-23 08:35
After talking about this inside the team we decided that this is working as expected. Closing this as not a bug.

**Closed by rmartinc** 2024-07-23 08:35 UTC
Labels: area/saml, kind/bug, status/triage, team/core-clients

**Comment by mhajas** [comment] 2024-07-23 11:04
@rmartinc I agree with your reasoning here. I don't think we are violating the spec. 

@lagital If you disagree, please share more information about why is this problem for you and in which use case you think the behavior you expect is necessary.

**Comment by lagital** [comment] 2024-07-23 11:10
@mha, @rmar, I agree that the specified can be interpreted in different ways. E.g. Azure interprets it in the same way as I do and differently from Keycloak.

The description in the standard is not well detailed and arguing can be infinite, I suppose.

Taking this into account, and considering potential impacts, I'm ok with rejecting this task.
