### ISSUE TITLE
kcreg.bat kcadm.bat cannot run on keycloak 22 and openjdk 17 LTS on Windows

### ISSUE THREAD

**Issue by gt-khoo** [keycloak/keycloak#22784] opened 2023-08-29 10:53 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/cli

### Describe the bug

Got exception when running kcreg and kcadm windows batch files

```
D:\web\keycloak-22.0.1\bin>kcreg
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/WindowsAnsiOutputStream
        at org.jboss.aesh.console.settings.SettingsImpl.getTerminal(SettingsImpl.java:381)
        at org.jboss.aesh.console.Console.init(Console.java:190)
        at org.jboss.aesh.console.Console.<init>(Console.java:118)
        at org.jboss.aesh.console.AeshConsoleImpl.<init>(AeshConsoleImpl.java:98)
        at org.jboss.aesh.console.AeshConsoleBuilder.create(AeshConsoleBuilder.java:160)
        at org.keycloak.client.registration.cli.KcRegMain.main(KcRegMain.java:55)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.WindowsAnsiOutputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 6 more
```

### Version

22.0.1

### Expected behavior

Able to run command line

### Actual behavior

D:\web\keycloak-22.0.1\bin>kcreg
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/WindowsAnsiOutputStream
        at org.jboss.aesh.console.settings.SettingsImpl.getTerminal(SettingsImpl.java:381)
        at org.jboss.aesh.console.Console.init(Console.java:190)
        at org.jboss.aesh.console.Console.<init>(Console.java:118)
        at org.jboss.aesh.console.AeshConsoleImpl.<init>(AeshConsoleImpl.java:98)
        at org.jboss.aesh.console.AeshConsoleBuilder.create(AeshConsoleBuilder.java:160)
        at org.keycloak.client.registration.cli.KcRegMain.main(KcRegMain.java:55)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.WindowsAnsiOutputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 6 more

### How to Reproduce?

Windows OS
OpenJDK 17 LTS (OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7) )
Keycloak 22.0.1

**Comment by ahus1** [comment] 2023-08-29 11:48
Closing as duplicate of #21851

**Closed by ahus1** 2023-08-29 11:48 UTC
Labels: kind/bug, area/admin/cli, team/cloud-native, status/triage
