### ISSUE TITLE
Quickstarts Tests consistently broken on main

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#10950] opened 2022-03-25 16:16 UTC
### Describe the bug

"Quickstarts Tests" are consistently broken on the `main` branch e.g.:

 - https://github.com/keycloak/keycloak/runs/5692285797?check_suite_focus=true#logs

### Version

main

**Comment by abstractj** [comment] 2022-04-06 22:29
Confirmed and we should fix this.

**Comment by abstractj** [comment] 2022-04-06 22:31
Now the issue is slightly different from the original report, but we can make use of this issue considering that they are still broken: https://github.com/keycloak/keycloak/runs/5858287136?check_suite_focus=true

**Comment by ahus1** [comment] 2022-06-10 07:45
Two PRs to work towards a greener build: 
* https://github.com/keycloak/keycloak-quickstarts/pull/328
* https://github.com/keycloak/keycloak-quickstarts/pull/326

Once those are merged, we'll tackle the next ones.

**Comment by abstractj** [comment] 2022-06-10 12:37
@ahus1 thank you so much for looking into this!

**Comment by ahus1** [comment] 2022-06-16 11:23
One more PR: 
* https://github.com/keycloak/keycloak-quickstarts/pull/334

**Comment by ahus1** [comment] 2022-06-20 14:13
Now they are finally green: https://github.com/keycloak/keycloak-quickstarts/pull/336

:tada: :pinata:

**Closed by ahus1** 2022-06-20 14:13 UTC
Labels: kind/bug, priority/critical, area/ci

**Comment by andreaTP** [comment] 2022-06-20 15:02
I applaud you @ahus1 fixer of CIs! 🎉  Thanks!
