### ISSUE TITLE
Problem with UserStorageProviderFactory

### ISSUE THREAD

**Issue by jhowilbur** [keycloak/keycloak#21596] opened 2023-07-11 13:10 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

In Keycloak, version 21.1.1 is possible to use providers, including custom “.jar” code, in our case, we migrated from version 15 to 21, and we used version 15, the factory “org.keycloak.storage.UserStorageProviderFactory”.

Now after this version upgrades, it continues working as expected, but at one point when we start the “create” method implemented from this Keycloak interface:

```java
public interface UserStorageProviderFactory<T extends UserStorageProvider> extends ComponentFactory<T, UserStorageProvider> {
    /**
     * called per Keycloak transaction.
     *
     * @param session
     * @param model
     * @return
     */
    T create(KeycloakSession session, ComponentModel model);
…
}
```

Inside this “create” we’re using the ResteasyClient class.

And then we get the error:
- Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder

or for example using Jakarta:
```java
2023-07-05 10:13:30,422 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.NoClassDefFoundError: jakarta/ws/rs/client/ClientBuilder
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:105)
    at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
    at java.base/java.lang.Class.forName0(Native Method)
```

We tried all possible versions or diff libs of 
```maven
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
```

A code example trying to build client
```java
client = (ResteasyClient) ClientBuilder.newClient();
```

We also tried to put this resteasy-client “.jar” inside the provider to see if the problem with class not found stops, but without success.
We tried to change from Javax to Jakarta the problem continues to happen.

This point could change if change the lib, but all the time, they try to call the “org.glassfish.jersey.client.JerseyClientBuilder”

Could it be related to “org.jboss.resteasy”?

We made some investigations in Keycloak 21.1.1 code, but we can’t find a way to evolve with that, can you please give us some advice or validate if it is a bug or something we can help to fix or improve?

### Version

21.1.1

### Expected behavior

Using this factory in version 15:
“org.keycloak.storage.UserStorageProviderFactory”

Inside this “create” we’re using the ResteasyClient class without problems.

### Actual behavior

Now in version 21.1.1
Using this factory:
“org.keycloak.storage.UserStorageProviderFactory”

Inside this “create” we’re using the ResteasyClient class.

And then we get the error:
- Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder

### How to Reproduce?

create a provider to use “org.keycloak.storage.UserStorageProviderFactory” in keycloak 21.1.1, then implements the UserStorageProviderFactory<> and inside the method:
```
@Override
... create
```

Try to use all possible versions or libraries with resteasy-client, for example:
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>

Then you'll be able to see the error:
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder

A code example trying to build client
```java
client = (ResteasyClient) ClientBuilder.newClient();

**Comment by rmartinc** [comment] 2023-07-12 10:05
Hi @jhowilbur!

The problem I think is that the resteasy-client jar is not bundled with the quarkus implementation. With version 15 you were probably using the wildfly version, right? And in wildfly the resteasy-client is bundle with the server.

Have you tried to add the needed jars in the providers (client and deps)? I can make it work with (not deeply tested):

```
cd ~/keycloak-21.1.2/providers/
cp ~/hello-rest-example.jar . # my sample provider
wget https://repo1.maven.org/maven2/org/jboss/resteasy/resteasy-client/4.7.9.Final/resteasy-client-4.7.9.Final.jar
wget https://repo1.maven.org/maven2/org/jboss/resteasy/resteasy-client-api/4.7.9.Final/resteasy-client-api-4.7.9.Final.jar
wget https://repo1.maven.org/maven2/org/wildfly/client/wildfly-client-config/1.0.1.Final/wildfly-client-config-1.0.1.Final.jar
```

I don't think we want to add jars that the server does not use. @mposolda @pedroigor WDYT?

**Comment by pedroigor** [comment] 2023-07-12 13:53
See https://www.keycloak.org/server/configuration-provider#_using_third_party_dependencies.

We don't ship any JAX-RS Client implementation.

**Comment by rmartinc** [comment] 2023-07-13 07:39
Thanks @pedroigor! Then @jhowilbur I think that this is explained and it is expected. The dependency jars should be also placed in the providers directory. The keycloak server does not contain the resteasy client as it does not need it to work. In keycloak 22 the jakarta packages have substituted the old javax ones (just a not when you plan to upgrade to the new version).

Closing this as not a bug.

**Closed by rmartinc** 2023-07-13 07:39 UTC
Labels: kind/bug, area/core, status/triage, team/core

**Comment by jhowilbur** [comment] 2023-07-13 09:01
Hi @rmartinc 
Thank you, and thanks @pedroigor, for the details.
I'll try to put your mentioned lib versions in the providers directory to test again, I tried it before but if a diff version.

ASAP I'll let you know if that worked

**Comment by rmartinc** [comment] 2023-07-13 15:40
No, it's not expected to work anymore. Previously it was there because it was in wildfly, but now with quarkus only the dependencies neeed by keycloak are bundled. And the jaxrs client implementation jars are not among them. You have to provide them as any other dependency you use in your custom provider. With 21.1.2 I added the resteasy jars for teh same core version (4.7.9). In new version 22 the version is newer (see the other issue linked).
