### ISSUE TITLE
ContextNotActiveException when sending email for event USER_DISABLED_BY_PERMANENT_LOCKOUT

### ISSUE THREAD

**Issue by StephanSchrader** [keycloak/keycloak#27559] opened 2024-03-05 14:32 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

The user should receive an email when account is disabled due to max login failures. Instead an exception is thrown.

### Version

23.0.3, 24.0.1, latest, nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

An e-mail is sent to inform the user that their account is permanently disabled.

### Actual behavior

No e-mail is send and an exception is thrown:

```
2024-03-05 14:03:33 2024-03-05 13:03:33,474 WARN  [org.keycloak.services] (Brute Force Protector) KC-SERVICES0053: login failure for user 00fd0f55-e3b2-402f-b78a-f5e72e948b3e from ip 192.168.65.1
2024-03-05 14:03:33 2024-03-05 13:03:33,495 ERROR [org.keycloak.services] (Brute Force Protector) KC-SERVICES0052: Failed processing type: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.vertx.http.runtime.CurrentVertxRequest, id=d3fea7e849828428a20dd77c1de969b46fc0d001]
2024-03-05 14:03:33     - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
2024-03-05 14:03:33     at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:55)
2024-03-05 14:03:33     at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
2024-03-05 14:03:33     at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.getCurrent(Unknown Source)
2024-03-05 14:03:33     at org.keycloak.quarkus.runtime.integration.resteasy.ResteasyVertxProvider.getContextData(ResteasyVertxProvider.java:33)
2024-03-05 14:03:33     at org.keycloak.common.util.Resteasy.getContextData(Resteasy.java:62)
2024-03-05 14:03:33     at org.keycloak.services.DefaultKeycloakContext.getContextObject(DefaultKeycloakContext.java:102)
2024-03-05 14:03:33     at org.keycloak.services.DefaultKeycloakContext.getHttpRequest(DefaultKeycloakContext.java:150)
2024-03-05 14:03:33     at org.keycloak.events.email.EmailEventListenerProvider.sendEmail(EmailEventListenerProvider.java:74)
2024-03-05 14:03:33     at java.base/java.lang.Iterable.forEach(Iterable.java:75)
2024-03-05 14:03:33     at org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
2024-03-05 14:03:33     at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
2024-03-05 14:03:33     at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
2024-03-05 14:03:33     at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
2024-03-05 14:03:33     at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
2024-03-05 14:03:33     at org.keycloak.services.managers.DefaultBruteForceProtector.run(DefaultBruteForceProtector.java:283)
2024-03-05 14:03:33     at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-05 14:03:33 
```

### How to Reproduce?

1. Start docker image keycloak:latest with env KC_SPI_EVENTS_LISTENER_EMAIL_INCLUDE_EVENTS=USER_DISABLED_BY_PERMANENT_LOCKOUT
2. Login into admin console
2. Configure mail server
3. Add "email" to "Event listeners"
4. Enable "Brute force detection" or set "Brute Force Mode" to "Lockout permanently"
5. Set "Max login failures" to 1
6. Set "Permanent lockout" to on (if shown)
7. Create user with random password
8. Login as user and type in a wrong password

**Comment by mposolda** [comment] 2024-03-06 15:42
Not 100% sure, but I think this might be a duplicate of #26327 .

The issue is caused by the fact that we try to obtain RestEasy context data outside of the transaction (As the transaction commit is already in progress according to stacktrace). Hopefully we can figure something to improve this (EG. make sure that email can be sent earlier than during transaction commit. Or start new transaction if not transaction (and KeycloakSession) is in progress).

Contribution is welcome as I am not sure when/if Keycloak team has time to look at this.

**Comment by StephanSchrader** [comment] 2024-03-07 08:26
Thanks for looking into this. You're right this is duplicate of #26327 .

The event in my case is also triggered by the brute force detector.

**Closed** 2024-06-06 00:06 UTC
Labels: area/authentication, kind/bug, help wanted, team/core-clients, status/auto-expire, status/auto-bump, priority/normal, status/expired-by-bot
