### ISSUE TITLE
When my account was temporarily disabled, the error message on the login page was incorrect.

### ISSUE THREAD

**Issue by wangchengxin** [keycloak/keycloak#35789] opened 2024-12-11 01:55 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When my account was temporarily disabled, the error message on the login page was incorrect, show as invalid username or password.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

show accountTemporarilyDisabledMessage

### Actual behavior

show invalidUserMessage

### How to Reproduce?

services\src\main\java\org\keycloak\authentication\AuthenticationProcessor.java

function handleBrowserExceptionList

case USER_TEMPORARILY_DISABLED:
                    event.error(Errors.USER_TEMPORARILY_DISABLED);
                    forms.addError(new FormMessage(Messages.INVALID_USER));
                    break;

**Comment by rmartinc** [comment] 2024-12-11 08:26
AFAIK this is done on purpose to prevent username enumeration. This has been managed several times (for example https://github.com/keycloak/keycloak/issues/20651 but there are a lot more of the same) and I have seen requests to allow configuring this. But it's not a bug. It could be an enhancement in brute force as I have seen in other issues. I'm closing it for the moment.

**Closed by rmartinc** 2024-12-11 08:26 UTC
Labels: kind/bug, status/triage, area/login/ui, team/core-clients
