### ISSUE TITLE
Joining parent group fails silently if user is member of child

### ISSUE THREAD

**Issue by dbazile** [keycloak/keycloak#11390] opened 2022-04-18 22:00 UTC
### Describe the bug

I can't join a user to a group if they are a member of one of its subgroups.

### Version

17.0.0

### Expected behavior

User should be a member of a group after clicking "join group".

### Actual behavior

UI reports success but user is not joined to the group.

### How to Reproduce?

1. create the following group hierarchy:
  * test-group-parent
    * test-group-child
2. join user to test-group-child
3. attempt to join user to test-group-parent
4. observe that user is not joined to test-group-parent

### Anything else?

Running `quay.io/keycloak/keycloak:17.0.0` in dev mode.

**Comment by rmartinc** [comment] 2023-02-20 12:23
Possibly duplicate of #9345. Closing this, please check the answer in that other issue.

**Closed** 2023-03-03 08:50 UTC
Labels: kind/bug, area/admin/api, status/triage
