### ISSUE TITLE
Negative exp in KEYCLOAK_IDENTITY cookie when long session max lifetime configured

### ISSUE THREAD

**Issue by bvandaele** [keycloak/keycloak#25904] opened 2024-01-04 14:15 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When a session max lifetime bringing new session expiration after the january 2038 19th at 03:14:07 (currently about 5500 days is enougth to reproduce) is configured in the realm, the KEYCLOAK_IDENTITY cookie exp value is negative.
This induce the cookie to be expired and not recognized by keycloak making cookie authentication ineficient.
by exp I mean the value of the exp field of the JWT present as KEYCLOAK_IDENTITY cookie value.

### Version

23.0.3

### Expected behavior

I would expect the cookie expiration to be as large as possible but still positive.

### Actual behavior

Negative cookie exp value

### How to Reproduce?

1. Configure a maximum session lifespan of 5500 days or more in the choosen realm.
2. Authenticate with a client with standard flow
3. Intercept and inspect the KEYCLOAK_IDENTITY cookie returned to the web browser. You will get an negative value.
4. Try to authenticate to another client on the same realm. You will be prompt for password authentication even if cookie authentication should be working.

**Comment by rmartinc** [comment] 2024-01-08 11:47
Duplicate of https://github.com/keycloak/keycloak/issues/19671

Closing this as the other one was filed before.

**Closed by rmartinc** 2024-01-08 11:47 UTC
Labels: area/authentication, kind/bug, status/triage, team/core

**Comment by bvandaele** [comment] 2024-01-08 13:39
This is not exactly a duplicate as I was reporting a similar issue but in the cookie instead of in refresh tokens but I will add a comment on #19671 to mention that the issue is also in the cookie
