### ISSUE TITLE
m.filter is not a function

### ISSUE THREAD

**Issue by thunoldolsen** [keycloak/keycloak#30670] opened 2024-06-22 19:03 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I enters a client and click on tab "Client Scopes" i get the error "m.filter is not a function".
I cant see the same bug reported anywhere else.
![mfilterisnotafunction](https://github.com/keycloak/keycloak/assets/34251082/db9eeb80-8deb-4d57-b433-b3aaeea59813)

Running in docker, but also tested in JDK. Same error.

### Version

25.0.0 and 25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Enter client scopes

### Actual behavior

Error message

### How to Reproduce?

Do as in description

**Comment by thunoldolsen** [comment] 2024-06-23 11:22
Its working when creating client in another realm :)

**Comment by thunoldolsen** [comment] 2024-06-23 17:23
I exported clients from master realm to new realm. Now I get this error in client scopes:
![IMG_1378](https://github.com/keycloak/keycloak/assets/34251082/e7472340-775e-47c9-a71f-84339e834da7)

**Comment by ssilvert** [comment] 2024-06-24 21:57
@thunoldolsen I don't see this problem and I think others would have reported it if the problem was widespread.

Can you help to narrow down the problem?  There must be something different about your environment or what you are doing.

**Comment by ssilvert** [comment] 2024-06-27 19:59
I'm going to close this now.  We can reopen if you find an easy way to reproduce.

**Closed by ssilvert** 2024-06-27 19:59 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by chemaper** [comment] 2024-08-05 18:20
I got the same problem in Keycloak 24.

**Comment by shortone** [comment] 2024-08-28 15:10
Hello, just had the same issue on Keycloak 24.0.5
As far as I can tell after digging into the stack trace in the browser is that when the application is building the UserSelect component for the `Client scopes` tab, if there's an error in the payload returned by the call to the resource `/admin/realms/[realm-name]/users?max=20`, which was the case for me, the application crashes in the way presented in this ticket.
Good news is, fixing the data in ldap or the provider would fix the issue.

For context, the response was something like this:
```
    ...
    },
    {
        "id": "18",
        "username": "jdoe",
        "firstName": "john",
        "lastName": "doe",
        "email": "john@test.com",
        "emailVerified": true,
        "attributes": {
            "uid": [
                "jdoe"
            ],
            "createTimestamp": [
                "20240828043359.723Z"
            ],
            "{"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."}
```

Hope it helps.
Cheers

**Comment by keliansb** [comment] 2025-01-08 13:40
> Hello, just had the same issue on Keycloak 24.0.5 As far as I can tell after digging into the stack trace in the browser is that when the application is building the UserSelect component for the `Client scopes` tab, if there's an error in the payload returned by the call to the resource `/admin/realms/[realm-name]/users?max=20`, which was the case for me, the application crashes in the way presented in this ticket. Good news is, fixing the data in ldap or the provider would fix the issue.
> 
> For context, the response was something like this:
> 
> ```
>     ...
>     },
>     {
>         "id": "18",
>         "username": "jdoe",
>         "firstName": "john",
>         "lastName": "doe",
>         "email": "john@test.com",
>         "emailVerified": true,
>         "attributes": {
>             "uid": [
>                 "jdoe"
>             ],
>             "createTimestamp": [
>                 "20240828043359.723Z"
>             ],
>             "{"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."}
> ```
> 
> Hope it helps. Cheers

Thank you @shortone, we had the same issue `g.filter is not a function`, and we fixed it by setting the missing mapper `username` in the LDAP settings.
