### ISSUE TITLE
API - Refresh token new life time is not extending after generating new tokens using previous refresh token

### ISSUE THREAD

**Issue by kaushi5054** [keycloak/keycloak#15630] opened 2022-11-22 17:11 UTC
### Area

token-exchange

### Describe the bug

Hi All,

I'm using keyclock for my IDP provider. each and every time when I create the access token using refresh token, newly return refresh toke have less time than what I config (it's like old refresh token is rerunning).

My task is to keep the user in active session until user logout but in here after the refresh token life time expired (even I have create access token using newly return refresh token) we have to logout user automatically .

Please find the attachment for more details (Please note I have reduce the access token life time to 1min and refresh token life time 2min to identify the root case)

<img width="884" alt="Screenshot 2022-11-22 at 10 22 55 PM" src="https://user-images.githubusercontent.com/20614311/203376056-14d79450-2dad-40af-9e0b-0e8d5344c282.png">

Please find the below CURL to generate token using refresh token

`curl --location --request POST '{base_url}/auth/realms/{my_relam}/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=refresh_token' \
--data-urlencode 'client_id=XXX_CLIENT' \
--data-urlencode 'refresh_token=eyJhbGciOiJIUzI1NiIsInR5cC'`

Thank you!

### Version

16.1.1

### Expected behavior

once user request the access token using refresh , It's should return new refresh token with same expire as in configuration

### Actual behavior

each and every time when I create the access token using refresh token, newly return refresh toke have less time than what I config

### How to Reproduce?

Please use the curl that I have shared and reduce the access token and refresh token life time to small time frame (it will be easy to identify) replace the newly return refresh token and generate it, new token will expire in same expire as very first refresh token

**Comment by kaushi5054** [comment] 2022-11-23 01:15
Hi Sschu,
Thank you for your comment, I have changed SSO Session Max (5min) more than SSO Session Idle (2min). Even tho newly generated refresh token only have less than 2min (according to my configuration). 

Please find the attachment for your reference. 

<img width="890" alt="Screenshot 2022-11-23 at 6 40 47 AM" src="https://user-images.githubusercontent.com/20614311/203451866-0e17e870-f7b2-48bf-a515-9b562f8e45da.png">

Thank you.

**Comment by rmartinc** [comment] 2023-03-09 15:22
@kaushi5054 I cannot reproduce this. Just version 21.0.1 downloaded and started. Created a new realm called `shorty`. In the realm settings sessions tab `SSO Session Idle: 2m` and `SSO Session Max : 5m`. In the token tab `Access Token Lifespan: 1m`. Created a public OIDC client with direct access grants enabled. Created a user `ricky` with password XXXXX.

This script:

```bash
#!/bin/bash

RESPONSE=$(curl -s -X POST "http://localhost:8080/realms/shorty/protocol/openid-connect/token" -H "Content-Type: application/x-www-form-urlencoded" -d "username=ricky" -d "password=XXXXX" -d 'grant_type=password' -d "scope=openid" -d "client_id=test")
echo $RESPONSE | jq -r '.refresh_expires_in'
REFRESH_TOKEN=$(echo $RESPONSE | jq -r '.refresh_token')

for i in {1..10}
do
  sleep 30
  RESPONSE=$(curl -s -X POST "http://localhost:8080/realms/shorty/protocol/openid-connect/token" -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=refresh_token' -d 'client_id=test' -d "refresh_token=${REFRESH_TOKEN}")
  echo $RESPONSE | jq -r '.refresh_expires_in'
  REFRESH_TOKEN=$(echo $RESPONSE | jq -r '.refresh_token')
done
```

The results is:

```
bash lala.sh 
120
120
120
120
120
120
120
90
60
30

```

As you see the `refresh_expires_in` is 120 and in the last 4 requests starts to decrease as it is reaching the 5m max session.

**Comment by mposolda** [comment] 2023-05-22 17:32
@rmartinc Thanks for looking at this!

There was no additional details, so I am closing this. Please re-open if you still see the issues, but then please add the details of what you did differently than @rmartinc in previous step.

**Closed by mposolda** 2023-05-22 17:32 UTC
Labels: kind/bug, area/token-exchange
