### ISSUE TITLE
Analysis and summary report of the issues related to "Hostname", "Admin Console" and "Proxy" problems

### ISSUE THREAD

**Issue by andre-nascimento-rh** [keycloak/keycloak#20571] opened 2023-05-25 16:23 UTC
### Description

As some complimentary actions to solve the Issue #14666, this task aims to achieve:

- A deeper analysis of each issue aggregated under the umbrella Issue #14666; and
- Create and fulfill a spreadsheet showing clearly and in a summarized way the following info about each Issue investigated:

  - Issue Id;
  - Issue Title;
  - Issuer Username;
  - Brief Issue Description;
  - Possible Cause of the Problem;
  - Proposed Solution/Workaround in Issue's Comments; 
  - Status;
  - Additional Notes.
  
- The spreadsheet link must be disclosed to all team members in order to allow a shared collaboration and transparency.

**Comment by andre-nascimento-rh** [comment] 2023-05-26 15:20
Find the spreadsheet draft at:

https://docs.google.com/spreadsheets/d/1PH7BVYpO1GXWIh3Mm8Q_G0pKGlR3VSwZyJn1CyM3oCs/edit?usp=sharing 

[WIP]

**Comment by abstractj** [comment] 2023-05-31 11:38
> Find the spreadsheet draft at:
> 
> [docs.google.com/spreadsheets/d/1PH7BVYpO1GXWIh3Mm8Q_G0pKGlR3VSwZyJn1CyM3oCs/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1PH7BVYpO1GXWIh3Mm8Q_G0pKGlR3VSwZyJn1CyM3oCs/edit?usp=sharing)
> 
> [WIP]

@andre-nascimento-rh it seems you have to make the access to the spreadsheet public

**Comment by andre-nascimento-rh** [comment] 2023-06-05 18:50
I finished the first round of fulfillment on the [aforementioned spreadsheet]([docs.google.com/spreadsheets/d/1PH7BVYpO1GXWIh3Mm8Q_G0pKGlR3VSwZyJn1CyM3oCs/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1PH7BVYpO1GXWIh3Mm8Q_G0pKGlR3VSwZyJn1CyM3oCs/edit?usp=sharing)).

@abstractj , @vmuzikar and @keycloak/cloud-native , please take a look and feel free to comment out, collaborate and improve.

Thanks.

**Comment by andre-nascimento-rh** [comment] 2023-06-06 06:58
@abstractj , fixed.

Thanks.

**Comment by vmuzikar** [comment] 2023-06-06 09:04
@andre-nascimento-rh Thank you for the update. I'll go through the report in the spreadsheet.

Would you be able to provide some summary and suggested actions to help to resolve the hostname issues?

**Comment by andre-nascimento-rh** [comment] 2023-06-07 12:03
@vmuzikar => `Would you be able to provide some summary and suggested actions to help to resolve the hostname issues?` 
@abstractj => `that would be fantastic to understand what are the next steps.`

The summary:

When reading the issues related to the umbrella issue number [#14666](https://github.com/keycloak/keycloak/issues/14666) and filling out the spreadsheet aforementioned, I noticed that a large part of the complaints and "pains" are due to misunderstanding or confusion in the use of variables:

- KC_HOSTNAME_URL;
- KC_HOSTNAME_PORT;
- KC_HOSTNAME_ADMIN;
- KC_HOSTNAME_ADMIN_URL;
- KC_HTTP_ENABLED;
- KC_HOSTNAME_STRICT;
- KC_HOSTNAME_STRICT_HTTPS;
- KC_PROXY;

In addition to the inherent difficulties in how to properly configure the Proxy, headers forwarding, and details regarding HTTPS/TLS/Certificates, depending on each scenario and environment on the User/Developer side.

IMHO, the suggested actions to minimize such problems would be:

1. Discuss improving variable names to try to make them clearer, simpler and more concise;

2. Improve the documentation by including examples of real-world configurations based on the most common scenarios. Include examples with snippets from `Dockerfiles`, `docker-compose` and Kubernetes deployment files;

3. Improve error messages in the Backend and Frontend to make them clearer, more useful and relevant;

4. Include a Wizard option in the `kc.sh | kc.bat` CLI tool, in which the User can answer objective questions about their scenario and at the end the tool shows the recommended configuration for the variables described above. See more in the open discussion [here](https://github.com/keycloak/keycloak/discussions/20849).

WDYT?

Thanks.

**Comment by vmuzikar** [comment] 2023-06-07 16:40
@andre-nascimento-rh Thanks for the summary.

> 1. Discuss improving variable names to try to make them clearer, simpler and more concise;

Do you have anything specific in mind? In any case, this would be a breaking change and it would require a proper deprecation process (which we still need to figure out).

> 2. Improve the documentation by including examples of real-world configurations based on the most common scenarios. Include examples with snippets from `Dockerfiles`, `docker-compose` and Kubernetes deployment files;

That makes sense to me. I think we can omit specific examples for Docker and K8s (as it would be probably out of scope for docs and rather suitable for a Quickstart). I'd focus on configuration via CLI (as we do for most parts of the docs) but mention some specific use cases from the issues you analysed maybe.

> 3. Improve error messages in the Backend and Frontend to make them clearer, more useful and relevant;

Could you please elaborate? The root cause of the issues is that some resources can't be loaded in browser, if I understand correctly. What is your proposal around error messages in these cases?

> 4. Include a Wizard option in the `kc.sh | kc.bat` CLI tool, in which the User can answer objective questions about their scenario and at the end the tool shows the recommended configuration for the variables described above. See more in the open discussion [here](https://github.com/keycloak/keycloak/discussions/20849).

That sounds like a bigger task which would have to be done as a follow-up.

In the context of Keycloak 22, I think we could go with option 2. We could reconsider other options based on feedback we receive after that. WDYT?

**Comment by vmuzikar** [comment] 2023-07-10 09:14
The analysis is done and visible in the linked spreadsheet

**Closed by vmuzikar** 2023-07-10 09:14 UTC
Labels: priority/important, area/admin/ui, area/dist/quarkus, team/cloud-native, status/triage, kind/task
