### ISSUE TITLE
The list of realms is not displayed correctly in Admin UI using Chrome

### ISSUE THREAD

**Issue by IUADE0TB** [keycloak/keycloak#35773] opened 2024-12-10 16:10 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Some realms are not displayed and searched in Admin UI using Chrome browser. Pagination works incorrectly also.

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

All realms are in the list, page navigation works correctly, realm can be found using search bar

### Actual behavior

Some realms are not displayed in Admin UI, but they are in the response

### How to Reproduce?

In Chrome, when there are realms more than 1 page, some realms can't be found in search bar or are not displayed in the pages.

**Comment by ssilvert** [comment] 2024-12-10 20:28
@IUADE0TB This looks like a duplicate of https://github.com/keycloak/keycloak/issues/34356

We will try to get this included in 26.0.8.

Please give it a try in the nightly build and let us know if you think it is still broken.
https://www.keycloak.org/nightly/

**Closed by ssilvert** 2024-12-10 20:28 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
