### ISSUE TITLE
How do you update a custom user storage provider jar that includes a version number?

### ISSUE THREAD

**Issue by naris** [keycloak/keycloak#26396] opened 2024-01-22 21:14 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I have a User Storage Provider jar that I wrote to use our corporate sign in databse from keycloak which I wrote when using keycloak 19.0.2. I have since updated keycloak to 23.0.4 and had to update the user storage provider jar. When I did so, I updated the version number, which is also in the name of the jar.

However, I am now unable to use the new jar as keycloak's build process complains that the old jar is not found and crashes :(

I have had to symlink the new jar to the old name to get keycloak to build and start, how do I get around this limitation?

Note: I have been using the Quarkus version for 19.0.2 and, of course, for 23.0.4

### Version

23.0.4

### Expected behavior

I should be able to replace the old custom provider jar in the providers directory with the new version without having to symlink the new jar file to have the old name :(

### Actual behavior

keycloak will not build or start when you update a jar in providers (a user storage provider in this case) by deleting the old version and adding the new version. You have to symlink , or rename, the new jar to have the same name as the old version :(

### How to Reproduce?

1. Have a user storage provider with a version in the name, such as keycloak-user-store-1.0.0-SNAPSHOT.jar.
2. Build and start the keycloak server
3. Shut down the keycloak server.
4. Then attempt to update the user storage provider to a new version with a different version number, such as keycloak-user-store-2.0.0-SNAPSHOT.jar, and delete the old keycloak-user-store-1.0.0-SNAPSHOT.jar
5. Start the server

**Comment by mposolda** [comment] 2024-01-25 18:29
This might be related to quarkus distribution, so changing to continuous team to triage this.

**Comment by naris** [comment] 2024-01-30 17:55
I have found that if I replace lib\quarkus\quarkus-application.dat with the version from the downloaded zip (.tar.gz) file as mentioned by @dpulrichth in the comments of [#24459](https://github.com/keycloak/keycloak/issues/24459) and removed the symlink to the old version, then it works

**Comment by sschu** [comment] 2024-01-31 11:38
What happens if you just completely delete that file? I would hope Quarkus is able to still create an optimized build without it?

**Comment by naris** [comment] 2024-01-31 19:19
@sschu > What happens if you just completely delete that file? I would hope Quarkus is able to still create an optimized build without it?

nope, it crashes :(

Exception in thread "main" java.nio.file.NoSuchFileException: /local/app/kc/keycloak-23.0.4/lib/quarkus/quarkus-application.dat
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
        at java.base/java.nio.file.Files.newInputStream(Files.java:160)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:52)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)

**Comment by sschu** [comment] 2024-02-01 13:33
That's too bad. Looks like removing dependencies is not really supported.

**Comment by vmuzikar** [comment] 2024-02-19 16:18
Closing as a duplicate. Let me know if you think otherwise.

**Comment by vmuzikar** [comment] 2024-02-19 16:18
Duplicate of #24459.

**Comment by vmuzikar** [comment] 2024-02-19 17:39
Reopening based on https://github.com/keycloak/keycloak/issues/24459#issuecomment-1952917945

**Comment by naris** [comment] 2024-03-04 16:38
@shawkins The stacktrace is:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.RuntimeException: Failed to open /local/app/kc/keycloak-23.0.6/lib/../providers/els-user-store-24.02.50-SNAPSHOT.jar
        at io.quarkus.bootstrap.runner.JarResource.ensureJarFileIsOpen(JarResource.java:172)
        at io.quarkus.bootstrap.runner.JarResource.readLockAcquireAndGetJarReference(JarResource.java:153)
        at io.quarkus.bootstrap.runner.JarResource.getResourceData(JarResource.java:72)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:99)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        at org.keycloak.quarkus.runtime.Environment.isWindows(Environment.java:156)
        at org.keycloak.quarkus.runtime.Environment.getCommand(Environment.java:95)
        at org.keycloak.quarkus.runtime.cli.Picocli.createCommandLine(Picocli.java:448)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:97)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
        ... 6 more
Caused by: java.nio.file.NoSuchFileException: /local/app/kc/keycloak-23.0.6/lib/../providers/els-user-store-24.02.50-SNAPSHOT.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1428)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at io.smallrye.common.io.jar.JarFiles.create(JarFiles.java:33)
        at io.quarkus.bootstrap.runner.JarResource.ensureJarFileIsOpen(JarResource.java:170)
        ... 15 more

**Comment by shawkins** [comment] 2024-03-04 16:55
@naris the issue here should be the inclusion of commons lang3 in your jar. That dependency is already part of keycloak, and the provider jar location is getting cached as the location. Environment.isWindows is attempting to make a call against commons lang3, thus the exception when the jar is removed.

@vmuzikar this is of course related to the application.properties issue, but is happening much earlier. Moving the provider jar check up even earlier could help, but still anything that's used transitively under our logic up to that point could still see the same problem.

Ideally there should be a split package warning - but I'm not seeing that locally if I just put an extra copy of the commons lang3 jar in the providers directory. So we should put some effort into seeing if that is getting swallowed, or can be produced.

**Comment by naris** [comment] 2024-03-04 17:48
@shawkins The User Provider was forked form this github repository [https://github.com/NovatecConsulting/keycloak-user-storage](https://github.com/NovatecConsulting/keycloak-user-storage), which is where the common lang3 dependency originated, if that helps.

I had to modify it heavily to connect to our *really legacy* Sybase database using the jtds-1.3.1.jar JDBC driver to obtain user information and to call our login stored procedure.

**Comment by naris** [comment] 2024-03-04 18:03
@shawkins , I removed commons lang3 from the jar (build.gradle), rebuilt it and tried again. It still crashes :(
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.RuntimeException: Failed to open /local/app/kc/keycloak-23.0.6/lib/../providers/els-user-store-24.02.50-SNAPSHOT.jar
        at io.quarkus.bootstrap.runner.JarResource.ensureJarFileIsOpen(JarResource.java:172)
        at io.quarkus.bootstrap.runner.JarResource.readLockAcquireAndGetJarReference(JarResource.java:153)
        at io.quarkus.bootstrap.runner.JarResource.getResourceData(JarResource.java:72)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:99)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        at org.keycloak.quarkus.runtime.Environment.isWindows(Environment.java:156)
        at org.keycloak.quarkus.runtime.Environment.getCommand(Environment.java:95)
        at org.keycloak.quarkus.runtime.cli.Picocli.createCommandLine(Picocli.java:448)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:97)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
        ... 6 more
Caused by: java.nio.file.NoSuchFileException: /local/app/kc/keycloak-23.0.6/lib/../providers/els-user-store-24.02.50-SNAPSHOT.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1428)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at io.smallrye.common.io.jar.JarFiles.create(JarFiles.java:33)
        at io.quarkus.bootstrap.runner.JarResource.ensureJarFileIsOpen(JarResource.java:170)
        ... 15 more

**Comment by naris** [comment] 2024-03-04 18:03
The new jar contents are:
META-INF/
META-INF/MANIFEST.MF
com/
com/epsilon/
com/epsilon/keycloakuserstore/
com/epsilon/keycloakuserstore/ConfigurationKey.class
com/epsilon/keycloakuserstore/dao/
com/epsilon/keycloakuserstore/dao/GroupDAO.class
com/epsilon/keycloakuserstore/dao/UserDAO.class
com/epsilon/keycloakuserstore/dto/
com/epsilon/keycloakuserstore/dto/LoginDTO.class
com/epsilon/keycloakuserstore/dto/PrivilegeDTO.class
com/epsilon/keycloakuserstore/dto/UserDTO.class
com/epsilon/keycloakuserstore/ElsGroupAdapter.class
com/epsilon/keycloakuserstore/ElsRoleAdapter.class
com/epsilon/keycloakuserstore/ElsUserStorageProvider.class
com/epsilon/keycloakuserstore/ElsUserStorageProviderFactory.class
com/epsilon/keycloakuserstore/models/
com/epsilon/keycloakuserstore/models/Group.class
com/epsilon/keycloakuserstore/models/package-info.class
com/epsilon/keycloakuserstore/models/Person.class
com/epsilon/keycloakuserstore/models/User.class
com/epsilon/keycloakuserstore/models/UserGroup.class
com/epsilon/keycloakuserstore/models/UserGroupId.class
com/epsilon/keycloakuserstore/representations/
com/epsilon/keycloakuserstore/representations/UserRepresentation.class
META-INF/beans.xml
META-INF/persistence.xml
META-INF/services/
META-INF/services/org.keycloak.storage.UserStorageProviderFactory

**Comment by naris** [comment] 2024-03-04 18:23
However, if I then copy the saved quarkus-application.dat then and it starts (but doesn't work) and if I copy back the jar with commons lang3 in it, it starts without having to shuffle quarkus-application.dat

**Comment by shawkins** [comment] 2024-03-04 18:50
> However, if I then copy the saved quarkus-application.dat then and it starts (but doesn't work) and if I copy back the jar with commons lang3 in it, it starts without having to shuffle quarkus-application.dat

If you start with a fresh install and add the provider jar without commons lang3, then removing it should be fine.

**Comment by jerrycooper** [comment] 2024-03-05 14:52
We have the same problem, we have own provider with commons lang3 dependency.
It is not problem to not include commons or other library to provider jar, but what I don't like about this situation is the fact that I find out about the incorrectly created jar when I update the provider jar file and not when I first run the kc.sh build.

**Comment by shawkins** [comment] 2024-03-08 18:35
Here are the observations:
* Quarkus treats the providers directory having precedence over lib. Meaning that from a quarkus perspective this may be expected behavior, but we're not documenting the possibility on the Keycloak side.
* The split package warning may only occur if there's an overlap within the providers directory - most of what's in the lib directory seems to be skipped by this analysis because those dependencies may lack markers https://github.com/quarkusio/quarkus/blame/09ff3b6de7cd088f26ada351a0743a9e4f97e2e5/core/deployment/src/main/java/io/quarkus/deployment/index/ApplicationArchiveBuildStep.java#L144

What could be done:
* Document this scenario as a current known limitation
* Upstream issue to expand the scope of the split package analysis - cc @geoand 
* Upstream issue to avoid the missing file execption. We'd probably need the providers directory be treated as lower precedence and/or catch this exception as is done in other places (https://github.com/keycloak/keycloak/blob/050acf0d94986523ede1c3d8a25b068f2f027b6e/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java#L83) - cc @geoand 

cc @vmuzikar

**Comment by vmuzikar** [comment] 2024-03-11 09:17
I'd go with option 1 for now – make sure we properly document it on our end. As far as I understand, it's basically just a UX issue and not really a blocker for anyone.

**Comment by shawkins** [comment] 2024-03-11 23:09
Ok, updated the documenation via #27789

And added an upstream issue to see if there is any appitite to improve the other points upstream - https://github.com/quarkusio/quarkus/issues/39343

**Closed** 2024-03-13 13:57 UTC
Labels: kind/bug, priority/important, area/dist/quarkus, team/cloud-native, backport/24.0
