### ISSUE TITLE
Groups view is not loading correctly

### ISSUE THREAD

**Issue by tobiasge** [keycloak/keycloak#17645] opened 2023-03-14 09:38 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

I our environment we have about 20 000 groups, that are build with the following structure:

* companies
  * company_1
    * group_1
    * ..
    * group_20
  * ..
  * company_1000

When using the Admin-API endpoint to get a group by its path, this runs into a timeout.

### Version

21

### Expected behavior

Group is returned from the API in a < 1 second.

### Actual behavior

Loading takes more than 10 seconds.

### How to Reproduce?

Create the mentioned group structure and try to retrieve a group by its path.

### Anything else?

I think the problem is within the handling of the GroupModel and GroupAdapter. 
I tried to solve the problem with an API endpoint that is injected via an SPI. In this endpoint I accessed the DB with the Namedqueries from GroupEntity. I copied the methods that are used to retrieve groups by the path and changed them to only use GroupEntity up until the last moment before returning the found group.
I have pasted this code as an example here: https://gist.github.com/tobiasge/dd827d8a766894e0a40e7594841c6479

**Comment by rmartinc** [comment] 2023-03-17 17:06
Hi @tobiasge!

The group-by-path is not a very fast implementation because it loads all the subgroups (first all the top level groups, then all the groups for the first father,...). But I'm not seeing the times you mention. I have created 20000 groups with the form `/group-{i}/group-{i}-{j}` (where i=0-999 and j=0-19 as you reported). And using postgres as the database:

```
./kc.sh start --db=postgres --db-username=keycloak --db-password=XXXX --cache=ispn --cache-config-file=cache-ispn.xml --hostname=localhost --metrics-enabled=true
```

I get the following times:

```
time bash get-group-by-path.sh group-999/group-999-2
{"id":"41d42392-cc81-4724-a7a0-74d1e0c53762","name":"group-999-2","path":"/group-999/group-999-2","attributes":{"attr":["1"]},"realmRoles":[],"clientRoles":{},"subGroups":[]}
real	0m1.388s
user	0m0.037s
sys	0m0.013s
time bash get-group-by-path.sh group-999/group-999-2
{"id":"41d42392-cc81-4724-a7a0-74d1e0c53762","name":"group-999-2","path":"/group-999/group-999-2","attributes":{"attr":["1"]},"realmRoles":[],"clientRoles":{},"subGroups":[]}
real	0m0.088s
user	0m0.034s
sys	0m0.017s
time bash get-group-by-path.sh group-786/group-786-17
{"id":"a5d7d014-1967-48e1-8146-545a7b2fed68","name":"group-786-17","path":"/group-786/group-786-17","attributes":{"attr":["1"]},"realmRoles":[],"clientRoles":{},"subGroups":[]}
real	0m0.090s
user	0m0.040s
sys	0m0.015s
time bash get-group-by-path.sh group-500/group-500-0
{"id":"b6b95dc2-1866-4ac4-9bca-6f0623458713","name":"group-500-0","path":"/group-500/group-500-0","attributes":{"attr":["1"]},"realmRoles":[],"clientRoles":{},"subGroups":[]}
real	0m0.087s
user	0m0.038s
sys	0m0.013s
```

The first time it takes some time because the cache is empty (1.4s) and it needs to load all the children groups in each parent, but after that it is always  less than 100ms. Please check that your cache is OK and getting a good percentage for the hit ratio (usually it's almost 100% after some searches, or at least 90 something percent).

**Comment by tobiasge** [comment] 2023-03-17 17:12
Yes, when you create 1000 groups as top level groups with everyone having 20 subgroups its working ok, but not fast. This is what we are doing now as a workaround.

When you look at my first entry you will see that we first had one top level group with 1000 subgroups that also had 20 subgroups each. Thats when it really got slow.

**Comment by rmartinc** [comment] 2023-03-19 16:47
@tobiasge Ah! Sorry I missed there was a top level entry. But I think the idea is more or less the same. If you look for groups at second or third level the times are more or less the same:

```
time bash get-group-by-path.sh group-0/group-0-999/group-0-999-10
{"id":"f0b38e80-e117-45d3-a3a8-7ec57bda461b","name":"group-0-999-10","path":"/group-0/group-0-999/group-0-999-10"}
real	0m1.406s
user	0m0.030s
sys	0m0.008s
time bash get-group-by-path.sh group-0/group-0-999/group-0-999-10
{"id":"f0b38e80-e117-45d3-a3a8-7ec57bda461b","name":"group-0-999-10","path":"/group-0/group-0-999/group-0-999-10"}
real	0m0.075s
user	0m0.037s
sys	0m0.014s
time bash get-group-by-path.sh group-0/group-0-100/group-0-100-10
{"id":"9d1f628d-af80-48da-85af-106ae789e5d4","name":"group-0-100-10","path":"/group-0/group-0-100/group-0-100-10"}
real	0m0.100s
user	0m0.029s
sys	0m0.021s
time bash get-group-by-path.sh group-0/group-0-770/group-0-770-15
{"id":"eafb191f-a0e2-4079-af7b-72998343a777","name":"group-0-770-15","path":"/group-0/group-0-770/group-0-770-15"}
real	0m0.092s
user	0m0.035s
sys	0m0.016s
```

First time slow, after that better. The problem is just with the top level group `group-0` in my case. And that's because the `group-by-path` endpoint always fills all the hierarchy for the response (all the direct and non-direct children). And, in the case of that group, means loading 21000 groups which is too many (therefore the timeout). Maybe in the short term the best option is adding to that endpoint a parameter to only return the `briefRepresentation` without children.

**Comment by tobiasge** [comment] 2023-03-20 15:34
Yes, I think a `briefRepresentation` parameter would help.
But I will investigate more in our installation. Could you tell me what metrics I have to look at for the cache and database system?

**Comment by rmartinc** [comment] 2023-03-21 09:44
@tobiasge Regarding cache you need to check the hit ratio in the realms cache. Run it with the ispn cache configured and the `--metrics-enabled=true` option. Modify the cache file increasing the `max-count` to your needs (groups are stored in the realms cache). Regarding prosgresql I'm not an expert, sorry.

**Comment by rmartinc** [comment] 2023-03-21 09:48
Just to summarize my ideas here. I think the correct way of managing very long number of groups (with inheritance) involves:

* There should be an endpoint to retrieve the children of a group. With `first` and `max` parameters to control the number of groups returned. Top level groups would also be returned here when no parent group passed. This endpoint is not there now.
* The group representation should never contain the children groups (there can be hundreds of groups there). The previous endpoint needs to be used to retrieve the children and the hierarchy.
* The group search should not return hierarchy just a list of groups with the full path filled. This way the search can use `first` and `max` parameters to limit the query and complexity is easily maintained. It would work like a `find` command in a FS.
* The `group-by-path` can use an internal API method to retrieve a group via parent ID and name directly (not iterating children). Same for top level groups. This point needs API changes and probably in cache too.

This is just a summary of my ideas but don't know if it's even possible. With the new store and everything is a lot of changes and ity breaks previous API too. But I wanted to write the summary somewhere.

**Comment by tobiasge** [comment] 2023-03-21 11:00
The admin console has also some issues with many groups. For example if you select a user from the list and then navigate to the groups tab, it seems to load all groups, even when the user is only in two groups.

I also tested some of those admin console rest endpoints. They had the same problem. 

You mentioned a new store. I have not seen any reference to that. Could I activate that for tests?

Did you have a look at the code example I posted? I could help with implementing changes, if wanted or needed.

**Comment by pedroigor** [comment] 2024-03-04 20:55
@tobiasge Would you mind checking the Keycloak 24 release? Some improvements in this area might help with your problem.

**Comment by tobiasge** [comment] 2024-03-05 18:08
With Keycloak 23 and 24 we don't have these problems anymore.
I think this issue can be closed.

**Comment by rmartinc** [comment] 2024-03-06 08:28
Thanks for testing @tobiasge! Closing the issue then.

**Closed by rmartinc** 2024-03-06 08:28 UTC
Labels: kind/bug, area/admin/api, status/triage, team/core-iam
