### ISSUE TITLE
401 error when trying to list realms

### ISSUE THREAD

**Issue by iliuta** [keycloak/keycloak#35731] opened 2024-12-09 10:17 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

This issue was supposed to be solved in 26.0.7: https://github.com/keycloak/keycloak/issues/35277

However, I have the same behaviour.

Log in to the Admin console. Switch to another realm by clicking on the dropdown menu on the left.
Now click again on the dropdown menu to choose another realm.
The message "Loading realms" display indefinitely.

The UI performs a query like this:
https://keycloak-host/auth/admin/realms/currentrealm/ui-ext/realms/names?first=10&max=11&search=
which returns 401

### Version

26.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

The realms should be displayed in the list.

### Actual behavior

The message "Loading realms" display indefinitely.

### How to Reproduce?

See the bug description.

**Comment by iliuta** [comment] 2024-12-09 12:58
Obviously it's because the UI tries to list realms using the current realm's URL:

https://keycloak-host/auth/admin/realms/**currentrealm**/ui-ext/realms/names?first=10&max=11&search=

I replaced **currentrealm** with **master** then I replayed the request again, with the same headers, cookies, and so on. 
It worked.

**Comment by jonkoops** [comment] 2024-12-09 14:45
Looks like the original fix was never backported to 26.0, @edewit can you take care of this?

**Comment by jonkoops** [comment] 2024-12-09 14:45
Duplicate of #34356

**Closed by jonkoops** 2024-12-09 14:45 UTC
Labels: kind/bug, area/account/ui, status/triage, team/ui
