### ISSUE TITLE
Flaky test: org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest#availableAuthenticatorsAfterRemove

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#21785] opened 2023-07-18 13:46 UTC
## org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest#availableAuthenticatorsAfterRemove
[Keycloak CI - WebAuthn IT (firefox)]() / [Pull Request #21661](https://github.com/keycloak/keycloak/pull/21661)

```
java.lang.AssertionError: Expected SigningInPage but was Keycloak Account Management (https://localhost:8543/auth/realms/test/account/#/security/signingin&state=4e3aa195-6864-4112-a9fa-8a26a7e7870a&session_state=1646e5de-59bb-4107-9ebd-4f3883c4dba4&code=3cb81e7c-3b12-422b-836f-787063be9995.1646e5de-59bb-4107-9ebd-4f3883c4dba4.25f1fe5f-3a38-4895-aae5-c4e4c214a146)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.page.AbstractPage.assertCurrent(AbstractPage.java:110)
	at jdk.internal.reflect.GeneratedMethodAccessor538.invoke(Unknown Source)
...
```

**Comment by rmartinc** [comment] 2023-07-25 07:47
@mabartos I have been looking the failures in firefox the last days too. And I think that the issue is very ,very weird. If you see a lot of failures come with the meesage:

```
JavaScript error: https://localhost:8543/auth/realms/test/account/#/security/signingin&state=9f1509b4-2422-431a-80c1-cb25263e0c7c&session_state=bf4fe30a-8ef8-403e-8356-2a7ca84eb728&kc_action_status=success&code=a69ef804-df78-4b55-a4d9-3f0dd1eadfad.bf4fe30a-8ef8-403e-8356-2a7ca84eb728.8f3b404e-0f6e-4b63-9ede-736c63a98643, line 136: ReferenceError: Keycloak is not defined
```

And I think it's the same for others. I can reproduce it in my laptop doing (it usually fails before the 10 runs):

```
for i in {1..10}; do
  echo "===========================================> ${i}"; 
  mvn clean test -Pauth-server-quarkus -Dtest=org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest#notDisplayAvailableAuthenticatorsPasswordless -Dbrowser=firefox -Pwebauthn;
  if [ $? -ne 0 ]; then break; fi;
done
```

The corresponding JavaScript line 136 that fails is [this one](https://github.com/keycloak/keycloak/blob/22.0.1/themes/src/main/resources/theme/keycloak.v2/account/index.ftl#L125). So the problem is that the `Keycloak` class is not loaded by this [script](https://github.com/keycloak/keycloak/blob/22.0.1/themes/src/main/resources/theme/keycloak.v2/account/index.ftl#L81) tag somehow.

I have done a lot of tests and IMHO it makes no sense at all (I tried to execute the init code in `onload`, in different places, and nothing works). Besides I cannot make it fail in the browser (with my fedora firefox). So I don't know if the failure is due to arquillian, selenium, firefox or a weird combination of everything.

I can just make it work (in my laptop) loading the `keycloak.js` via JS. Doing something like:

```javascript
                let script = document.createElement("script");
                script.src = "${authUrl}js/keycloak.js";
                script.type = "module";
                script.addEventListener("load", initKeycloak)
                document.head.appendChild(script);
```

Don't know why, this works and I can execute the single test 20 runs without failure (usually it fails in less than 10). I'm going to send this change now to my branch to see if there is some other issue with the CI (maybe changing the index for account makes other test fail).

**Comment by mabartos** [comment] 2023-07-25 09:14
@rmartinc Very interesting findings. Thanks for that.

@jonkoops Have you encountered some similar problems?

**Comment by mposolda** [comment] 2024-05-15 18:07
Closing as it seems the flakiness disappeared.

**Closed by mposolda** 2024-05-15 18:07 UTC
Labels: kind/bug, priority/important, area/ci, flaky-test, team/continuous-testing
