### ISSUE TITLE
 The only admin account is able to be DELETED, DISABLED, or removed from the admin group

### ISSUE THREAD

**Issue by lillyqian** [keycloak/keycloak#20662] opened 2023-05-30 16:29 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The user is able to delete/disable the only admin account, after deletion/disable the user is unable to access the app until the Keycloak database is restored.

When a user is logged into Keycloak with the only admin account, they are able to remove themselves from the admin group.
As a result, the user is unable to access Keycloak again to add another admin without resetting the Keycloak database.

### Version

21.1.1

### Expected behavior

The only admin account shouldn't be deleted, disabled or removed from the admin group.

### Actual behavior

The only admin account can be deleted, disabled or removed from the admin group.

### How to Reproduce?

Login into Admin Console as the only admin account, you can delete, disable  your account, or remove your account from the admin group

**Comment by sschu** [comment] 2023-05-30 16:56
This is strongly related if not a duplicate of https://github.com/keycloak/keycloak/issues/19913. I don't really think this is a bug as there are all kinds of configuration changes you can do to lock yourself out and it would be very hard to prevent all of them. However, there should definitely be a way to recover from that state as described in https://github.com/keycloak/keycloak/issues/19913. @lillyqian I would close this as a duplicate and continue the discussion in the mentioned issue if you are fine with it.

**Comment by ssilvert** [comment] 2023-06-05 20:04
I agree with @sschu.  I'm going to go ahead and close this.

**Closed by ssilvert** 2023-06-05 20:04 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
