### ISSUE TITLE
Deactivate optimistic locking when running JPA Map store on a DB with isolation level serializable

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#14991] opened 2022-10-18 21:36 UTC
### Description

This is a spike to work around a problem on CockroachDB where using optimistic locking (which adds the `version` column to each delete statement) creates a lock that affects the table and not only the single row. 

 

### Motivation

Avoid deadlocks on CockroachDB

**Comment by hmlnarik** [comment] 2022-10-24 12:10
Duplicate of #13213

**Closed by hmlnarik** 2022-10-24 12:10 UTC
Labels: kind/enhancement, area/storage, team/storage-sig
