### ISSUE TITLE
401 Unauthorized response for loadUserProfile() in js-adapter after upgrade from 11.0.2

### ISSUE THREAD

**Issue by wkrtouk** [keycloak/keycloak#9204] opened 2021-12-16 23:25 UTC
### Describe the bug

It seems that there is a problem with js-adapter.

I have a web app, which uses Keycloak for authentication/authorization. Realm is configured properly, users can login. Everything is working good on version 11.0.2, but upgrading caused the issue.

Both keycloak and its js-adapter are of version 12.0.4. The same behavior occurs on 13.0.0, 14.0.0, 15.1.0. (Again, both Keycloak server and js-adapter were updated)

A user which I used for testing has correct roles and adding all possible Client roles does not help.

Could you help me in resolving this issue?

### Version

12.0.4, 13.0.0, 14.0.0, 15.1.0

### Expected behavior

Request should return `200 OK` with user info.

### Actual behavior

Request returns `401 Unauthorized` error

### How to Reproduce?

Webapp and keycloak are on the same origin.

1. Open webapp.
2. You are redirected to login page.
3. Sign in using keycloak js-adapter.
4. Login successfully.
5. On load, webapp sends a request to `http://localhost:8080/auth/realms/<realm>/account` by calling `keycloak.loadUserProfile()` method in Keycloak js-adapter.

### Anything else?

I tried using Keycloak on https and port 8443, but to no avail.

Keycloak and its js-adapter is the only variable here, the webapp stays the same.

Also, if keycloak and webapp are on different origins, the issue is similar: instead of `401 not authorized` I get `401 CORS` error. As for the CORS error, adding correct web-origins to `Realm > Clients > Configure > Account`  does not help either.

**Comment by livefr0mspace** [comment] 2024-06-25 10:55
same problem in my Angular app, any updates?

**Comment by jonkoops** [comment] 2024-06-25 11:01
Closing this issue as we do not support these versions of Keycloak or Keycloak JS any longer and will not be providing patches. This is likely due to increased cookie protection from modern browsers, try disabling `checkLoginIframe` and make sure `silentCheckSsoRedirectUri` is not set.

**Closed by jonkoops** 2024-06-25 11:01 UTC
Labels: kind/bug, area/adapter/javascript, help wanted, team/core-clients, status/auto-expire, status/auto-bump, priority/normal, status/bumped-by-bot

**Comment by livefr0mspace** [comment] 2024-06-25 11:17
@jonkoops I am using the newest version and I still get the unauthorized response from calling loadUserProfile.... Is that solved or is my server just misconfigured (/account client scope?)

**Comment by jonkoops** [comment] 2024-06-25 11:21
Sound like it could be a configuration error, if it is reproducible please log a new issue with steps on how to reproduce it.

**Comment by kamilcglr** [comment] 2024-07-23 14:51
> @jonkoops I am using the newest version and I still get the unauthorized response from calling loadUserProfile.... Is that solved or is my server just misconfigured (/account client scope?)

Hello @livefr0mspace, did you find a solution. I am experiencing the same issue but I do not know if it is a configuration issue or not.

**Comment by livefr0mspace** [comment] 2024-07-23 17:57
Hi @kamilcglr, it was indeed a configuration issue. 

In my case, the account client was not in the aud claim of the token.
I think it was this setting: ![image](https://github.com/user-attachments/assets/d8091951-9c9c-468f-b4de-f7c473a07a22)

 After adding it I got a 403. This 403 issue was a problem with the user role access rights.
 Add the view-profile account role to the default role for your realm (or I guess any other role that your users are assigned to) .
![image](https://github.com/user-attachments/assets/2bbeeba1-f6ab-4e91-914d-8df57ce28935)

If you need any further help just let me know ;)

**Comment by kamilcglr** [comment] 2024-07-25 06:42
> Hi @kamilcglr, it was indeed a configuration issue.
> 
> In my case, the account client was not in the aud claim of the token. I think it was this setting: ![image](https://private-user-images.githubusercontent.com/112657330/351436059-d8091951-9c9c-468f-b4de-f7c473a07a22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODgyNDEsIm5iZiI6MTcyMTg4Nzk0MSwicGF0aCI6Ii8xMTI2NTczMzAvMzUxNDM2MDU5LWQ4MDkxOTUxLTljOWMtNDY4Zi1iNGRlLWY3YzQ3M2EwN2EyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDRkZDIzNDU2MzkxMWU4ZjhlYjUxOTQ3YjU4YTc3ZWJjMDRkMTYzMzQxOGQzYzNkN2I1MTg2MWRlNWNkMWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t_H9-1yCgVo_869XzhtpABvRjuWX-KnsgGIqckauxaw)
> 
> After adding it I got a 403. This 403 issue was a problem with the user role access rights. Add the view-profile account role to the default role for your realm (or I guess any other role that your users are assigned to) . ![image](https://private-user-images.githubusercontent.com/112657330/351437222-2bbeeba1-f6ab-4e91-914d-8df57ce28935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODgyNDEsIm5iZiI6MTcyMTg4Nzk0MSwicGF0aCI6Ii8xMTI2NTczMzAvMzUxNDM3MjIyLTJiYmVlYmExLWY2YWItNGU5MS05MTRkLThkZjU3Y2UyODkzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTViN2I2YThhZjNhNWY4MWVhM2IzYzM5ZGFkMjFmYTc2NGE3NzFmYzkxNTVmNDVlZDc4ZmY1YjE2Y2U1OWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvPX186sm7nRPSJ5Djlyw0EJsL7__YHpxbGnA8Nrh6k)
> 
> If you need any further help just let me know ;)

Hello @livefr0mspace thank you for your reply. I did not actually have the mapper in scope. After setting it I now have 403 errors instead of 401. I have checked that I have the view profile role. What is your mapper configuration? 

![image](https://github.com/user-attachments/assets/890aef96-52e8-40d1-ad80-0a21e3be809c)

**Comment by berkon** [comment] 2025-03-12 19:24
Looks like the UI settings have changed. In Keycloak v21.1.1 for me the following settings were necessary to avoid 401 and 403. After I added **view-groups** 401 turned into 403, which could be solved by adding **manage-account**

![Image](https://github.com/user-attachments/assets/bbd2c33c-35a1-483e-aba8-e8f46d5808f1)

**Comment by joeprabawa** [comment] 2025-04-11 06:52
I'm facing a bit similar scenario. At the moment my company that i worked with have a remote user. 
And the user reporting they got 401 when the app hitting the `/account` endpoint. But, when they try to copy-paste the `/account` URL directly and opening it in a new tab, they able to access Personal Info page of keycloack.

Our app is using angular 18 with `keycloak-angular: ^16.1.0`, `keycloak-js: ^26.0.0`

I tried to reproduce the issue, by trying to take out the `manage-account` role in my local development as what  Mr.@berkon mentioned above, and i got 401 as well (previously i have it in my local). But when directly opening the `/account` URL in new tab, i got into Something went wrong page

<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/49e40836-5d45-4f8f-aff0-24b05b7fe916" />

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/8d9adad3-07e9-418c-9519-b83311bcaadc" />

<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/a36be34f-6bbb-48cb-bb8c-534bb59ab80f" />

Does the `manage_account` will solved this 401 issue ? I need help and some guidance everyone, currently i still don't know what's wrong in this process. Thank you so much before 🙏🙏
