### ISSUE TITLE
Wrong Sync Mode of newly created external IdentityProvider

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#31169] opened 2024-07-09 16:23 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When creating a new Identity Provider configuration, the `syncMode` property won't be created in the database, but the UI is displaying `LEGACY`. In former versions there was `IMPORT` displayed.
If you do now some modifications, but don't change the _Sync Mode_, it will be saved in the DB as `syncMode=LEGACY` which is IMHO wrong, because it was different before and also _LEGACY_ is not meant to be used for newly created configs.

### Version

25 / nightly

### Regression

- [X] The issue is a regression

### Expected behavior

When adding new IdP configs, either create also the config property `syncMode` with value `IMPORT` (as it was until 24.x) or display in the UI the value `IMPORT` if no configuration value is set.

### Actual behavior

`LEGACY` is shown in the UI for sync mode, even if not value is being stored in the database for `syncMode`.

### How to Reproduce?

- create a new IdP config (at least of type OIDC)
- save the config
- see field "Sync Mode" -> displays `LEGACY`
- see table `identity_provider_config` for the just created IdP config, no `syncMode` is stored
- if you edit now some field(s), but not the "Sync Mode" field, the value `LEGACY` will be stored with config property `syncMode`

**Comment by edewit** [comment] 2024-07-11 16:40
The default value in the UI is `IMPORT` seems this has changed in the server after creation I get `syncMode: "LEGACY"` back

**Comment by sguilhen** [comment] 2024-07-22 21:08
According to this commit https://github.com/keycloak/keycloak/commit/8ef3423f4aee0b9b2b4d0f3d153833b061f5b497 by @hmlnarik the console is now showing the effective sync mode, which was wrongly displayed in previous versions. So I would argue that the new behavior is correct.

The problem, to me, lies in the fact that the sync mode cannot be set when creating a new IDP (I tried with OIDC, there's no way to set it during creation), so when the IDP is created the representation has no value set for the `syncMode`. When fetching the IDP data on subsequent requests, we previously returned no sync mode in the representation, which leads the UI to display the default value of `IMPORT`. Now, we're explicitly setting the value to `Legacy` in the returned representation.

To get around this, I would either allow setting the sync mode in the admin console when creating IDPs, or enforce the default value of `IMPORT` when creating the IDP in the model if the incoming representation has no value set for the sync mode.

**Comment by pedroigor** [comment] 2024-07-23 13:21
@ssilvert I'm not sure if this is a regression/blocker but the expected behavior considering that brokers default to `LEGACY` if they are not set. When creating a new broker it will default to legacy even if not set.

We can probably revisit this to use `IMPORT` as a default. But it would be a separate issue.

**Comment by dasniko** [comment] 2024-07-23 13:26
Having `LEGACY` as a default seems more than odd to me. It is, like the name says, a **LEGACY** behavior, which is not expected when creating new IdP configs.

**Comment by pedroigor** [comment] 2024-07-23 13:52
@dasniko I agree. But I would say this change deserves a separate issue because it will also change the default at runtime when running brokers.

If we agree I can create an issue to have `IMPORT`  as the default.

**Comment by dasniko** [comment] 2024-07-23 13:59
@pedroigor Ok, if you need a separate issue to be able to track this better/differently, I'm ok with this. 👍

**Comment by pedroigor** [comment] 2024-07-23 14:24
@dasniko Thanks. I'm closing in favor of https://github.com/keycloak/keycloak/issues/31539.

**Closed** 2024-07-23 14:24 UTC
Labels: kind/bug, area/admin/api, area/admin/ui, team/core-iam, team/core-shared
