### ISSUE TITLE
post_logout_redirect_uri causes "invalid redirect_uri" for clients created in keycloak 19 with old admin console

### ISSUE THREAD

**Issue by tgerakitis** [keycloak/keycloak#14246] opened 2022-09-07 07:17 UTC
### Describe the bug

On our dev system we have clients created in keycloak v17 and clients created in v19.

For example: 
`https://my.keycloak.com/realms/my-realm/protocol/openid-connect/logout?post_logout_redirect_uri=https://valid.redirect.uri&client_id=my-client` should work but did not, even though `https://valid.redirect.uri` is a valid `redirect_uri` configured in `my-client`.

I was able to compare export jsons of old and new clients and found this difference:
```
{
    ...
    "protocol": "openid-connect",
    "attributes": {
        "saml.force.post.binding": "false",
        "saml.multivalued.roles": "false",
        "post.logout.redirect.uris": "+", //<--- this line exists in old but not in the new clients
        "frontchannel.logout.session.required": "true",
        ...
```

This is also the way to hotfix this issue: 
* export the client
* delete exported client from keycloak
* add the line above to the exported json under `"attributes"` object
Line: `"post.logout.redirect.uris": "+"`
* import the edited json 
* redirect works again

### Version

19.0.0

### Expected behavior

That the valid redirect URIs in the client configuration are used to validate post logout redirect URIs.
Or have a separate configuration in each client for valid post-logout URIs.
And - of course - a successful redirect.

### Actual behavior

Error: invalid redirect_uri

### How to Reproduce?

* Create new client in keycloak v19
* log in to client successfully
* build post_logout_redirect_url using URL provided  in `end_session_endpoint` in `realms/my-realm/.well-known/openid-configuration`, adding the following URL params `client_id` & `post_logout_redirect_uri`
* see "Error invalid redirect_uri" both in browser and in logs
`keycloak_1  | 2022-09-06 16:10:00,122 WARN  [org.keycloak.events] (executor-thread-129) type=LOGOUT_ERROR, realmId=my-realm, clientId=null, userId=null, ipAddress=1.1.1.1, error=invalid_redirect_uri, redirect_uri=https://valid.redirect.uri`

**Comment by mposolda** [comment] 2022-09-07 08:49
@douglaspalmer Do you please have a chance to triage this bug and see if it is regression or not?
@tgerakitis Additional question: When you mention in steps to reproduce "Create new client in keycloak v19" - how exactly are you creating the client? Are you using new admin console or old admin console or admin REST API for creation of the client? If you're using new admin console (recommended), did you configure "Valid post logout redirect URIs" ?

**Comment by tgerakitis** [comment] 2022-09-07 08:52
I see what could be causing this issue, we used the old admin console to create the client.
@mposolda

**Comment by mattiaspantzare** [comment] 2022-09-08 15:18
Looks like we have run in to the same bug.

We are using the old GUI due to other buggs in the new GUI that makes that a no go.

Can this be set in directly in the database as a workaround?

**Comment by mposolda** [comment] 2022-09-09 06:09
@tgerakitis Thanks for clarifying. I am closing this as we're not going to add support for the switch in the old admin console. And as you pointed, this is not a blocker as you have still some ways how to change post_logout_redirect_uri .

@mattiaspantzare As pointed by @tgerakitis, you can temporarily switch to the new admin console or export/import client. Another way is to directly use admin REST API for create/update client.

@tgerakitis @mattiaspantzare FYI. if you are aware of any bugs in the new admin console, it will be good to report them in the https://github.com/keycloak/keycloak-ui/issues, so our admin console team is aware of them and can fix them. As the old admin console is going to be removed in one of next releases (Probably Keycloak 21). Feel free to ignore this message if you already reported bugs there :-)

**Comment by sschu** [comment] 2022-09-09 07:23
@mposolda I don't really agree with your assessment here. For two Keycloak versions, people will not be able to use the old admin console to properly create clients. I would not really want to explain to my 30+ customers what the workaround for this is. Considering the fact that the fix is probably small - I would even consider this as something for 19.0.2. We can even check if we can provide the fix quickly...

**Comment by mattiaspantzare** [comment] 2022-09-09 08:30
Please reopen this case.

Switching gui is not a good option on a production system.

Export / import works, but if that is what should be used everytime we make a new client you could just remove the GUI.
At the very least this have to be documented in the relase notes.

I hope that you will not remove the new gui for a while. I have reported the bugs that I found but there may be more things hiding.

This is a very easy fix, so I do not understand why it can't be fixed?

**Comment by mattiaspantzare** [comment] 2022-09-09 08:55
@mposolda I think that you are not understanding the problem.

As it is now, we can't create a new working client in the old GUI.

That is not a "new feature". Creating a new client is not a new thing to do.

If the field was missing from the GUI but it was set to "+" (as is done when you migrate from an old keycloak version) this would not be a big problem.

But that is not what is happening. 

When I create a new client in the old GUI logouts from that application will not work, and there is no documented way to make it work (except the workaround in this bug report).

**Comment by lexcao** [comment] 2022-09-10 11:31
Make sense to me, I am going to create a PR to fix this 
by adding a  feature to configure the `post_logout_redirect_uri` attribute of the client on legacy admin UI.

**Closed** 2022-09-13 06:09 UTC
Labels: area/oidc, kind/bug, help wanted
