### ISSUE TITLE
Extra separators appearing in User Federation required settings

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak#28749] opened 2024-04-15 16:39 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When creating Kerberos or LDAP User Federation providers, extra separators are appearing in the Required Settings or General Options sections, respectively.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

No separators should appear

### Actual behavior

Extra separators appear

### How to Reproduce?

Create a new Kerberos or LDAP user federation provider

### Anything else?

Screen cap:
![user-fed-required](https://github.com/keycloak/keycloak/assets/39063664/4d4305a8-9c96-4ebc-b591-7f62a3a70deb)

**Comment by edewit** [comment] 2024-04-16 07:32
duplicate of https://github.com/keycloak/keycloak/issues/28546

**Closed by edewit** 2024-04-16 07:32 UTC
Labels: kind/bug, priority/important, area/admin/ui, team/ui
