### ISSUE TITLE
User Attribute Mapping not working when UserStorageProvider set to NO_CACHE

### ISSUE THREAD

**Issue by CollinAlpert** [keycloak/keycloak#10826] opened 2022-03-18 16:34 UTC
### Describe the bug

When I add a User Attribute Mapping to a Client, the attribute's value does show up in the User Info when the UserStorageProvider has a Cache Policy of NO_CACHE. 

### Version

17.0.0

### Expected behavior

When I add a User Attribute Mapping to a Client and check the "Add to userinfo" box, evaluating the Client Scopes for a particular user yields the user attribute as part of the Generated User Info.

### Actual behavior

The user attribute's value does not show up in the user info.

### How to Reproduce?

Here's a repro: [KeycloakTest.zip](https://github.com/keycloak/keycloak/files/8306199/KeycloakTest.zip).
1. Run `docker build -t keycloak-test . && docker run -p 8080:8080 keycloak-test`. This will start a Keycloak server with the necessary config.
2. Log into localhost:8080 with admin/admin.
3. Go to Clients => test-client => Client Scopes. The mapper is configured under "Mappers".
4. Select "Evaluate", choose the "LoremIpsum" user and click "Evaluate".
5. In the "Generated User Info" tab, the attribute is missing:
```json
{
  "sub": "f:adb16158-ba92-4c61-92ba-c3260119fea8:123",
  "email_verified": false,
  "name": "Lorem Ipsum",
  "preferred_username": "LoremIpsum",
  "given_name": "Lorem",
  "family_name": "Ipsum"
}
```
6. Head to the User Federation section and change the Cache Policy of the configured UserStorageProvider to DEFAULT.
7. Evaluate the Client Scopes again. The payload now looks like this:
```json
{
  "sub": "f:adb16158-ba92-4c61-92ba-c3260119fea8:123",
  "email_verified": false,
  "user_id": 123
}
```
The attribute is now shown, however all the other data is missing. This may be related to #10824.

### Anything else?

I found [this question](https://keycloak.discourse.group/t/custom-mapper-inclusion-in-access-token-not-working-until-profile-updated/12527) in the Keycloak Discourse which describes my situation exactly and provides a workaround: Saving the user manually makes the attribute appear in the User Info.

**Comment by vramik** [comment] 2022-12-07 16:52
Thank you @CollinAlpert for the report. I was able to reproduce it previously in keycloak 17, now with current main I am not. The issue may have been already resolved. I'm closing it for now. If you believe the issue is still present, feel free to reopen it.

**Closed by vramik** 2022-12-07 16:52 UTC
Labels: kind/bug, area/storage

**Comment by ajwstevens** [comment] 2024-03-15 05:14
I am seeing this issue with Keycloak 22.
