### ISSUE TITLE
Connection string for ldap user federation with multiple hosts no longer supported

### ISSUE THREAD

**Issue by nesc58** [keycloak/keycloak#17359] opened 2023-03-01 08:25 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

Since 21.0.0 the connection string "ldaps://ldap-server-1 ldaps://ldap-server-2" is not longer supported.

### Version

21.0.0

### Expected behavior

The connection string is still valid and will be used for failover scenarios.
When the first host is down the second one will be used

### Actual behavior

Connection string is not valid
Migration guide from 20.x does not contain a note for migrating this connection string

### How to Reproduce?

Try to use the ldap connection string "ldaps://ldap-server-1 ldaps://ldap-server-2"

### Anything else?

When the first host is down the second will be used.
If there is another way to provide this kind of "failover" feature I would use it.

Another way could be to "clone" oder "duplicate" the ldap user fedaration but there is no function for this. So all mappers must be entered twice.

Are there any plans to readd the support for failover ldap connection strings?

**Comment by ahus1** [comment] 2023-03-03 12:17
Triage result: 
* Multiple URLs for failover are supported, see https://docs.oracle.com/javase/jndi/tutorial/ldap/misc/url.html and also by looking in the JDK code at `LdapCtxFactory#getInitialContext()`
* This used to work in KC20
* This is broken in KC21 due to changes in #14965

@mposolda - as you've been working on #14965, do you see a different way to handle a context with multiple URLs without storing them in the session? 

One idea: Could `CustomSSLSocketFactory` in `FIPS1402Provider#wrapFactoryForTruststore()` override some of the `createSocket(host, ...)` methods to avoid putting the hostname into the session?

**Comment by mposolda** [comment] 2023-03-03 16:46
@ahus1 yep, the issue could be caused by #14965. On the other hand, I am not seeing how just storing the hostname as the attribute to kcSession could break this? As for the non-FIPS use-case, everything should work as before regarding connection to LDAP etc?

@nesc58 Few questions:
- Are you using newly added fips feature in your environment - https://www.keycloak.org/server/fips?
- Are you seeing any warnings in the logs?
- If not, when you enable TRACE logging for example with something like:
```
--log-level=INFO,org.keycloak.common.crypto:TRACE,org.keycloak.crypto:TRACE
```
are you seeing any trace messages from `FIPS1402Provider` class?

**Comment by ahus1** [comment] 2023-03-03 17:01
@mposolda - sorry, I missed to add the stack trace which makes it clear.

To reproduce: 
* Start Keycloak regularly with the defaults (no FIPS)
* Add an LDAP provider with an URL like `ldap://localhost:10389 ldap://localhost:10389`
* Press "Test connection"

The following code passes two URLs separated by a blank:

```
    public static void setLDAPHostnameToKeycloakSession(KeycloakSession session,LDAPConfig ldapConfig) {
        String hostname = UriUtils.getHost(ldapConfig.getConnectionUrl());
        session.setAttribute(Constants.SSL_SERVER_HOST_ATTR, hostname);
        log.tracef("Setting LDAP server hostname '%s' as KeycloakSession attribute", hostname);
    }
``` 

This leads to the following exception:

```
12:27:36,007 ERROR XNIO-1 task-3 [org.keycloak.services] KC-SERVICES0055: Error when connecting to LDAP: URI 'ldap://localhost:10389 ldap://localhost:10389' is not valid.
java.lang.IllegalArgumentException: URI 'ldap://localhost:10389 ldap://localhost:10389' is not valid.
	at org.keycloak.common.util.UriUtils.getHost(UriUtils.java:57)
	at org.keycloak.storage.ldap.LDAPUtils.setLDAPHostnameToKeycloakSession(LDAPUtils.java:385)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:70)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:104)
	at org.keycloak.services.managers.LDAPServerCapabilitiesManager.testLDAP(LDAPServerCapabilitiesManager.java:99)
	at org.keycloak.services.resources.admin.TestLdapConnectionResource.testLDAPConnection(TestLdapConnectionResource.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.testsuite.UndertowRequestFilter.lambda$doFilter$0(UndertowRequestFilter.java:49)
	at org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
	at org.keycloak.testsuite.UndertowRequestFilter.doFilter(UndertowRequestFilter.java:47)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
```

**Comment by mposolda** [comment] 2023-03-06 07:30
@ahus1 Thanks for the clarification! So it is not specific to FIPS environment...

Since this was introduced by myself, would you prefer to you to switch this to `team/core` ? As for example for me, it may be easier to test also FIPS enabled scenario? Also I suggest to add this to milestone 22 as this looks like a regression. WDYT?

For the solution you mentioned: maybe it works, but I am not 100% sure...

The easiest approach I can think of is something like:
- Still use KeycloakSession attribute SSL_SERVER_HOST_ATTR, but use the "list of strings" with hostnames (instead of assume that the "connectionURL" is single URL like it is today). We can make sure to divide URLs the same way like Java is using internally (maybe they just split by space, but we can doublecheck...)
- In the FIPS provider, use something like `sslParameters.setServerNames(allHostsHere)` instead of currently used `sslParameters.setServerNames(Collections.singletonList(sniHostName))`

WDYT?

**Comment by ahus1** [comment] 2023-03-06 07:37
+1 for moving this, as I don't know how to test this in a FIPS scenario, and also the milestone. Depending on the fix, it might even be a candidate for a backport, but let's see the solution first.

With the FIPS provider, I don't think a list of all hosts helps to the the SNI, as a SNI is only a single host name, and one wouldn't know which one from the list to pick: The LDAP implementation in JDK will iterate of the list of strings, and on each iteration it needs to pick the right server name for the SNI.

Feel free to ping me for a short meeting about SNIs if you want to have another pair of eyes.

**Closed** 2023-04-16 15:41 UTC
Labels: kind/bug, area/core, team/core, status/regression
