### ISSUE TITLE
Switching Tabs in realm settings not possible

### ISSUE THREAD

**Issue by ton3r** [keycloak/keycloak#20416] opened 2023-05-17 13:04 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We have some Realms in our system which have blanks inside of their names, for example "_t01_Component Tests_"

Meanwhile it isn't possible anymore to input such RealmID. Our Realms are there for a longer time and the most of them we have created through Java (`keycloak-admin-client`) API Calls or import/exports.

But if I navigate to such a Realm and want to edit things on other Tabs than "_General_", the navigation is not working.

### Version

21.1

### Expected behavior

It should still be possible to switch the Tabs

### Actual behavior

I stuck on "General" Tab without having the chance to switch over.

### How to Reproduce?

To get a Realm with blanks in its name, you can edit the database. Because not possible over UI right now.

Rename in a realm the "name" column to something with a blank

`update realm set name='My Realm' where name = 'SOME_VALID_NAME'`

### Anything else?

![kctabs](https://github.com/keycloak/keycloak/assets/10545359/a573c870-f6be-4871-92ee-4fea5d491271)

**Comment by ssilvert** [comment] 2023-05-17 19:37
We decided some time ago that you should not be allowed to use special characters in a realm name.
https://github.com/keycloak/keycloak/discussions/11978

We disallow this in the UI, but the API should disallow as well.  Moving this to the core team.

@ton3r Is there a possibility of renaming your realms?

**Comment by ton3r** [comment] 2023-05-18 06:46
I have to take a look at it, I think it should be possible to rename the realms. But in the end it should not break the UI. At least not without a hint why it does not work. There were no error log or broken call in the developer console.

May be a label on it that special characters are deprecated and there isn't a guarantee that thinks are working correct.

**Comment by mposolda** [comment] 2023-05-19 09:34
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog.

We can probably add some validation when creating/updating realm to make sure that spaces are not allowed. At the same time, it is the question if we should hardcode something like this just for the realms or use some "common validation framework" (SPI) for handle this.

**Comment by raubel** [comment] 2024-01-18 13:54
Hi,

For information, we had a similar (same) issue with a realm containing Unicode caractère (`my–realm` where `–` is `\u2013`).

**Comment by jonkoops** [comment] 2024-01-18 14:30
@raubel is this in the latest version of Keycloak, or an older one?

**Comment by raubel** [comment] 2024-01-18 16:26
Sorry. We are using Keycloak 21.1.2.

**Comment by jonkoops** [comment] 2024-01-18 18:26
I believe this issue may already have been fixed since we're now URL encoding parameters in the route. If someone is able to reproduce this in the latest version of Keycloak feel free to let me know and I will re-open this issue.

**Closed by jonkoops** 2024-01-18 18:26 UTC
Labels: kind/bug, area/admin/api, team/core
