### ISSUE TITLE
SAML IDP initiated SSO getting cookie_not_found error

### ISSUE THREAD

**Issue by diazoxide** [keycloak/keycloak#20490] opened 2023-05-22 10:50 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

saml

### Describe the bug

I have attempted to configure SAML IDP using Onelogin/Azure/Okta SSO in both my development and production environments. While logging in from Keycloak with the IDP works flawlessly in both cases, I continue to encounter the `cookie_not_found` when a 3rd party IDP initiates the login process

```
WARN  [org.keycloak.events] (executor-thread-92) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=595a9ab0-4bc2-429b-a8a0-750a1f75b08e, clientId=null, userId=null, ipAddress=192.168.48.1, error=cookie_not_found
```

### Version

21.1.1

### Expected behavior

In the scenario of an IDP-initiated login, the expected behavior is for the login process to occur and redirect to the RelayState URL provided. However, in my current configuration, I am experiencing an issue where the redirect to the RelayState URL does not occur.

### Actual behavior

instead, I receive the 'cookie_not_found'

<img width="920" alt="image" src="https://github.com/keycloak/keycloak/assets/25997814/20a476bb-737d-432b-a22b-1d58875515ae">

### How to Reproduce?

To reproduce the bug, follow these steps:

1. Create an application named "SAML 2 test" in OneLogin (or your preferred SSO provider).
2. Obtain the SAML 2 metadata descriptor from the created application in OneLogin.
3. In Keycloak, create an IDP using the provided SAML 2 metadata descriptor.
4. Configure SSO in OneLogin by providing the necessary settings and mapping attributes as required.
5. Test the SSO flow by signing in from Keycloak, verifying that everything works correctly.
6. Attempt to initiate the login process from the OneLogin portal.
7. At this point, you will encounter the "cookie_not_found" error.

The error occurs specifically when attempting to initiate the login from the OneLogin or another 3rd party provider portal. This issue persists despite successful login attempts from Keycloak.

**Comment by SevanEl** [comment] 2023-05-22 13:27
I had the exact same issue with the latest release, 21.1.1.

**Comment by PahlevanyanSimon** [comment] 2023-05-23 05:48
Any update?

**Comment by Hrachstepanyan** [comment] 2023-05-23 05:50
No response yet??

**Comment by mposolda** [comment] 2023-05-24 10:10
Not 100% sure if this is a bug or enhancement request. In any case, this is not a blocker for Keycloak 22, so adding to Backlog for now as Keycloak team probably doesn't have time to look at this in the near future. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by Helalihiba** [comment] 2023-07-13 22:25
Hello,
I'm facing a similar problem.
I've set up two Keycloak instances using a docker-compose file: one as an Identity Provider (IdP) on port 9090 and the other as a broker on port 8085. 
However, I'm unable to log in a user created on the Identity Provider to the broker. 
In the logs, I'm seeing the error message "cookie_not_found."

I'm wondering if anyone has found a solution to this problem?

**Comment by stianst** [comment] 2024-02-15 13:20
Looking at the code this error message happens when the `KC_RESTART` cookie is not found. I don't fully understand what this cookie is used for, and why we are throwing an error if this cookie is not found. @mposolda could you explain what this cookie is used for?

One observation is that this cookie does not have any `SameSite` value set on it, which results in it defaulting to `Lax`. A cookie with `SameSite=Lax` will be available after a HTTP GET redirect from the application, but not from a HTTP POST.

I presume everyone having issues here is using POST bindings, which would mean the `KC_RESTART` cookie is excluded from the request.

**Comment by stianst** [comment] 2024-02-15 14:56
> hi @stianst Is the issue related to the KC_RESTART cookie not being found more prevalent or exclusive to scenarios where Keycloak is used as both the Identity Provider (IdP) and the Service Provider (SP)? Or is it a broader issue that also affects interactions with external IdPs?
> 
> also was this functionality working differently or more reliably in earlier versions of Keycloak?

It's not about what version of Keycloak you're using, as this stuff hasn't changed for a long time, but rather it's browsers becoming more eager at blocking cookies.

**Comment by danielfranciscoz** [comment] 2024-02-15 23:05
Hello, I am facing the same issue **type="IDENTITY_PROVIDER_LOGIN_ERROR", error="cookie_not_found"** 

In my case I have a Keycloak version 23.0.6 running on Azure in prod mode and a Keycloak version 23.0.6 running on Docker in dev mode, I have configured a IDP SAML in Keycloak and an Azure application with SAML as SSO method, 

I am not sure if the error is in fact related to cookies, since I am not blocking any cookie in my browser,

Any help is welcome, thanks!

**Comment by trixpan** [comment] 2024-02-29 05:11
@stianst @mposolda 

So the code triggering the error is here:

https://github.com/keycloak/keycloak/blob/326d63ce7462cbcd94f2efde2eb9070c1a724220/services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java#L389-L392

However, if you notice the calling [code](https://github.com/keycloak/keycloak/blob/326d63ce7462cbcd94f2efde2eb9070c1a724220/services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java#L182) it clearly states after the relevant call:

>         // if restart from cookie was not found check if the user is already authenticated

Which is a bit weird, given the method is returning an error.

The change seems to have been introduced in 15.x by 

https://github.com/keycloak/keycloak/commit/a6cd80c9332be7f26e47d2fa131156f95f7ac146

Which sort of aligns with the unusual number of users struggling to reproduce a "how to" designed for Keycloak 11.X with later versions of the KC code:

https://www.lisenet.com/2020/keycloak-with-okta-idp-initiated-sso-login/

**Comment by BabaTataKaka** [comment] 2024-03-06 16:28
> Hello, I am facing the same issue **type="IDENTITY_PROVIDER_LOGIN_ERROR", error="cookie_not_found"**
> 
> In my case I have a Keycloak version 23.0.6 running on Azure in prod mode and a Keycloak version 23.0.6 running on Docker in dev mode, I have configured a IDP SAML in Keycloak and an Azure application with SAML as SSO method,
> 
> I am not sure if the error is in fact related to cookies, since I am not blocking any cookie in my browser,
> 
> Any help is welcome, thanks!

Any update regarding your issue? I'm experiencing the same issue. However, I'm no using IDP and just login with the default admin user.

**Comment by diazoxide** [comment] 2024-03-19 09:30
Glad to see "**priority/important**" label here!

**Comment by LvargaDS** [comment] 2024-03-19 09:52
I have found problem in my WEB-INF/keycloak-saml.xml file (keycloak saml adapter configuration), which does cause to show `error=cookie_not_found` warn in log. Behavior of keycloak was that after redirect from my web app (ear, war inside wildfly) I was able to login into keycloak and be redirected back to my app. My app have redirected me again to keycloak, which have shown me that I am already logged in. In wildfly i have seen info about logged out from other node:

```
2024-03-14 19:41:20,953 DEBUG [org.keycloak.adapters.saml.SamlAuthenticator] (default task-1) SamlAuthenticator is using handler [org.keycloak.adapters.saml.profile.webbrowsersso.BrowserHandler@27c4245f]
2024-03-14 19:41:20,953 DEBUG [org.keycloak.adapters.saml.SamlSessionStore] (default task-1) Session AYA0Eynl1Mss9888888888nAo8nfpao1vuiTkcBVE has expired on some other node
```

Problem lied in my adapter configuration, **keycloak-saml.xml**. I had wrong idp entity id:

```
<IDP entityID="idp"
```
When originally downloaded given config from keycloak, there was value "idp". After tripplechecking all things and configs, I have changed it to "http://localhost:8005/realms/lvarealm" and it started to work and no warning in console.

My final configuration:

```xml
<!-- downloaded from keycloak realm -> client -> action -> download adapter config -->
<keycloak-saml-adapter xmlns="urn:keycloak:saml:adapter"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="urn:keycloak:saml:adapter http://www.keycloak.org/schema/keycloak_saml_adapter_1_9.xsd">
    <SP entityID="http://localhost:8081/myapp/"
        sslPolicy="NONE"
        autodetectBearerOnly="true"
        logoutPage="/myapp/asdf.jsp?akšn=do_logout">
        <Keys>
            <Key signing="true">
                <PrivateKeyPem>
                    MIIJQgIBADANBgk....O2X2Q==
                </PrivateKeyPem>
                <CertificatePem>
                    MIIFaTCCA1GgAwI...
                </CertificatePem>
            </Key>
        </Keys>
        <IDP entityID="http://localhost:8005/realms/lvarealm"
             signatureAlgorithm="RSA_SHA256"
             signatureCanonicalizationMethod="http://www.w3.org/2001/10/xml-exc-c14n#">
            <SingleSignOnService signRequest="false"
                                 validateResponseSignature="true"
                                 validateAssertionSignature="false"
                                 requestBinding="POST"
                                 assertionConsumerServiceUrl="http://localhost:8081/portal/saml"
                                 bindingUrl="http://localhost:8005/realms/lvarealm/protocol/saml"/>
            <SingleLogoutService signRequest="false"
                                 signResponse="false"
                                 validateRequestSignature="true"
                                 validateResponseSignature="true"
                                 requestBinding="POST"
                                 responseBinding="POST"
                                 postBindingUrl="http://localhost:8005/realms/lvarealm/protocol/saml"
                                 redirectBindingUrl="http://localhost:8005/realms/lvarealm/protocol/saml"/>
            <Keys>
                <Key signing="true">
                    <PrivateKeyPem>
                        MIIJQgIBADANBgkqh....MRqO2X2Q==
                    </PrivateKeyPem>
                    <CertificatePem>
                        MIIFaTCCA1GgA.....
                    </CertificatePem>
                </Key>
            </Keys>
        </IDP>
    </SP>
</keycloak-saml-adapter>
```

**Comment by stianst** [comment] 2024-04-05 10:39
Pretty sure the root cause behind this is same-site cookies combined with SAML POST binding. The offending cookie here (`KC_RESTART`) does not have the SameSite attribute set on it, which means it's down to default behaviour in different browsers. Older browser sent these always, but newer browsers are defaulting to Lax, but just to make it more fun some allow them more than others.

For those affected please confirm that you are indeed doing a SAML POST binding across different origins. If anyone that is affected not doing that then I have no clue what's going on, but that would be useful info.

Lax sends the cookies for GET request, but not for POST requests.

My thinking of what we should do to resolve this is:

1. Remove _LEGACY cookies
2. Make all cookies required during OIDC/SAML flows default to SameSite=Lax, but make that configurable so that does that need POST based bindings can use SameSite=None

For 2 we could also go with SameSite=None by default, but allow setting it to SameSite=Lax for those that know they don't need POST bindings.

**Comment by LvargaDS** [comment] 2024-04-05 11:03
I was encountering problem across different origins. **localhost:8081** was http, jboss and keycloak as saml IdP was available on **localhost:8005**.

I have changed in my configuration **<IDP entityID="idp"** to **<IDP entityID="http://localhost:8005/realms/myrealm"** and it started to work. I have tracked it down to this single change in my case.

Perhaps my problem was different one from original one, but symptoms was same.

**Comment by ben-wallis** [comment] 2024-04-15 13:05
As far as I can tell this issue is not resolved - I get the same cookie not found error when logging in via SAML when accessing the application from the Azure "My Applications" page. This is on the latest nightly commit d43980ee6c6 which includes the changes from #28467 

My experience is identical to that described in this issue - Keycloak initiated login works correctly, but IDP (Azure) initiated login fails with cookie not found. Error from the Keycloak console: 

`WARN  [org.keycloak.events] (executor-thread-48) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="841c87a1-64d6-43ad-86c2-e21b494cae1e", clientId="null", userId="null", ipAddress="<redacted>", error="cookie_not_found"`

**Comment by Ketec** [comment] 2024-06-14 23:57
I enabled third party cookies in the browser. They are still not created.
In this case IBM verify initiated login.

And likewise - either azure or ibm - it works if i start the flow from kc login page, fails if it is IDP initiated.

**Comment by mposolda** [comment] 2024-07-30 09:16
Marking this as important due the amount of users having this problem, but will be good to confirm if this is really after the corresponding PR was merged.

@LvargaDS @ben-wallis Could you please comment here what is the Keycloak version where you still see the issue? Are you using at least Keycloak 25 or newer? If not, can you please try with latest Keycloak 25.0.2 and check if issue can be still reproduced with that version?

**Comment by ben-wallis** [comment] 2024-07-30 09:29
@mposolda I can no longer reproduce this on 25.0.2 with Azure SSO. That said, IDP-initiated login doesn't actually seem to work, it just redirects to the main application page where the user has to click "Sign in with <identity provider>". This is however acceptable for our use case, the main thing is that the button on https://myapplications.microsoft.com/ takes the user to the application without an error being displayed.

**Comment by LvargaDS** [comment] 2024-09-16 10:55
> @LvargaDS @ben-wallis Could you please comment here what is the Keycloak version where you still see the issue? Are you using at least Keycloak 25 or newer? If not, can you please try with latest Keycloak 25.0.2 and check if issue can be still reproduced with that version?

I have fixed the problem. It was present in my configuration. Currently I do not have setup, where can I easily test it again.

If you have working environment for some simple saml authentification, try to change "<IDP entityID="http://keycloakurltorealm" into url, which is not actually valid url. For example: "<IDP entityID="idp"". This should simulate my original issue.

**Comment by rmartinc** [comment] 2024-09-27 09:56
I don't understand this completely. In point `6 Attempt to initiate the login process from the OneLogin portal`. Is this an IdP initiated login? And what do you expect keycloak does with an IdP initiated login? Where should keycloak go? To what application?

I did a quick test setting keycloak as the SP and IdP (two different realms) and If I try a IdP initiated login from the IDP side I receive an error page saying Invalid Request. Not the one with the cookie error. So not sure if we are talking about the same thing. My error makes sense because the IdP provider does not even contemplate the IdP login, so it tries to obtain the auth session from the relay state and at that point fails (the relay state should be there for SP initiated).

I would need a HAR file obtained from the browser to understand what is happening here. The full process from starting the login from the IdP side. Thanks!

**Comment by diazoxide** [comment] 2024-09-27 10:17
Can someone get update? If this issue still actual?

**Comment by rmartinc** [comment] 2024-10-09 07:43
I'm closing this because there is no more information. My impression of the issue is that the SAML identity provider does not support IdP initiated login by the external broker. Probably now it shows invalid request and before it showed another error like cookie not found.

The IdP initiated login is thought to open a SAML app with no initial interaction from the SP. In this case the external provider is sending a SAML document with the login response to keycloak with no previous request from keycloak. The provider implementation discards the request as we have no previous request (the relay state is empty). Maybe we can add something and start the account page or any other configured app but I really don't see any benefit doing this. The IdP brokering feature is to allow logins using an external broker (oidc, saml or social), initiated by keycloak, and not the other way around.

Feel free to re-open it or file another issue if you have more information and it's not the IdP initiated login suspicion.

**Closed by rmartinc** 2024-10-09 07:43 UTC
Labels: area/saml, kind/bug, priority/important, status/triage, team/core-clients

**Comment by martin-kanis** [comment] 2024-11-06 14:32
@stianst @rmartinc we are getting this issue in the internal CI https://github.com/keycloak/keycloak/issues/33982 `LDAPSamlIdPInitiatedVaryingLetterCaseTest` tests are failing there because they run with `-Dauth.server.ssl.required=false`. It is possible to reproduce locally i.e `mvn -f testsuite/integration-arquillian clean install -Pauth-server-quarkus -Dauth.server.ssl.required=false -Dtest=LDAPSamlIdPInitiatedVaryingLetterCaseTest#idpInitiatedMatchCaseLDAPTest`
With SSL those tests run fine. I tried to set `sslRequired: none` for the test realm but it didn't help. Any idea why a cookie is not found with http?

**Comment by rmartinc** [comment] 2024-11-06 14:36
@martin-kanis This was happening a lot since the changes in the secure cookies for localhost. Are you using the default web driver? Try using chrome instead (which allows localhost as secure).

**Comment by martin-kanis** [comment] 2024-11-06 14:47
@rmartinc yes with the default one, but it's the same with chrome

**Comment by rmartinc** [comment] 2024-11-06 14:51
Ah! Maybe it's because you are using the SamlClient utility which uses apache http client. In those I recommended to Miquel to use the server with a name (`-Dauth.server.host=127.0.0.1.nip.io` for example). Take a look to the issue: https://issues.redhat.com/browse/RHSSO-3021 (I think it's not public but you can see it).

**Comment by martin-kanis** [comment] 2024-11-07 13:24
@rmartinc  `-Dauth.server.host=127.0.0.1.nip.io` did the trick! Thanks

**Comment by pibragh** [comment] 2025-01-10 09:50
I had a similar issue with Keycloak 26.0.x and NGINX as a proxy.
The solution I found was to add the following line to the NGINX configuration file:
`proxy_cookie_flags ~.* secure samesite=None;`

**Comment by aashutoshkhadgi** [comment] 2025-01-13 12:10
@pibragh This solution worked for me as well. I was having the same error when upgrading keycloak to version 26 in kubernetes. I added the proxy config as annotation in ingress config. If we're not using nginx ingress, we can use nginx sidecar with the nginx config and it should work as well.

**Comment by ecmrauh** [comment] 2025-01-14 11:44
Same here with Keycloak 26.0.x on Kubernetes and behind Ingress/nginx. My fix was to add an extra environment variable to the helm chart:

```yaml
extraEnvVars:
  - name: KC_PROXY_HEADERS
    value: xforwarded
```

**Comment by oculos** [comment] 2025-04-11 11:56
I got the same problem today, but it came out of the blue.
What happened was that I added a frontend url to my realm. I had to remove that frontend url, and then I started to get this error. It feels to me that this is a bug.
