### ISSUE TITLE
Keycloak HTTP code 500 when calling SAML IDP endpoint without RelayState defined

### ISSUE THREAD

**Issue by LoicGudet** [keycloak/keycloak#12782] opened 2022-06-28 10:56 UTC
### Describe the bug

When calling our keycloak SAML IDP endpoint from our SAML provider, Keycloak raises a 500 error

```
https://our-app-domain/auth/realms/<realm_name>/broker/<saml_idp>/endpoint
``` 

Only **SAMLResponse** is set in the payload.
As I understood from [https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf](saml-bindings-2.0), RelayState is optional.
In fact, our SAML provider does not let us add this parameter.

### Version

18.0.0

### Expected behavior

Calling 
```
https://our-app-domain/auth/realms/<realm_name>/broker/<saml_idp>/endpoint
``` 
without RelayState defined should return a 200 HTTP Code and redirect to the related app

### Actual behavior

Calling 
```
https://our-app-domain/auth/realms/<realm_name>/broker/<saml_idp>/endpoint
``` 
without RelayState raise a 500 HTTP Code and logs the following:

```
Uncaught server error: org.keycloak.broker.provider.IdentityBrokerException: Could not process response from SAML identity provider.
at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:547)
at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleSamlResponse(SAMLEndpoint.java:631)
at org.keycloak.broker.saml.SAMLEndpoint$Binding.execute(SAMLEndpoint.java:274)
at org.keycloak.broker.saml.SAMLEndpoint.postBinding(SAMLEndpoint.java:185)
...
...
...
Caused by: java.lang.NullPointerException
at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
at java.base/java.util.regex.Pattern.split(Pattern.java:1261)
at org.keycloak.broker.provider.util.IdentityBrokerState.encoded(IdentityBrokerState.java:41)
```

### How to Reproduce?

1. Setup a SAML IDP on Keycloak,
2. Use a link from the SAML provider to keycloak endpoint to forge the query.
3. Using the developer tools of your browser, copy the request as curl format for instance
4. Copy the query into a tool like postman
5. Execute the query, the response should be 500
6. Add a RelayState in query payload
7. Execute the query, the response should be 200

**Comment by LoicGudet** [comment] 2022-12-20 10:42
Hello 👋 
Do you have any update about this issue ?

**Comment by fazd** [comment] 2022-12-20 15:11
Hi. so there is a way that you can call the IDP without a relay state but you have to use a public client in order to achieve that. 

You have to create a public client and assign it the IDP flow that you are using like this.

![image](https://user-images.githubusercontent.com/16343293/208699056-c505d08a-b72c-4305-93de-189e6125e08f.png)

you configure normally the IDP and you should be able to use the saml

https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/clients/saml/idp-initiated-login.adoc here is a detailed explanation of how to achieve that

**Comment by fazd** [comment] 2022-12-20 15:15
Hi. In order to achieve a flow without a relay state you need to build an SP-initiated flow. For that, you need to create a public client. and set it up like this: 

![image](https://user-images.githubusercontent.com/16343293/208700059-d260ecb7-4879-4358-8fe7-1dc65af508e3.png)
You configure the Identity provider normally and you should now be able to call the endpoint without a relay state.

Here you can find more information about it
https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/clients/saml/idp-initiated-login.adoc

**Comment by mposolda** [comment] 2023-04-04 09:33
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by apateczechmeister** [comment] 2023-06-15 09:13
Dear @mposolda

unfortunately I ran into the same NPE also with the newest KC v21.1.1
```
2023-06-14 13:28:44,453 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-15278) Uncaught server error: org.keycloak.broker.provider.IdentityBrokerException: Could not process response from SAML identity provider.
    at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:596)
    at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleSamlResponse(SAMLEndpoint.java:679)
    at org.keycloak.broker.saml.SAMLEndpoint$Binding.execute(SAMLEndpoint.java:278)
    at org.keycloak.broker.saml.SAMLEndpoint.postBinding(SAMLEndpoint.java:189)
    ...
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
    at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
    at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
    at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
    at java.base/java.util.regex.Pattern.matcher(Pattern.java:1144)
    at java.base/java.util.regex.Pattern.split(Pattern.java:1272)
    at org.keycloak.broker.provider.util.IdentityBrokerState.encoded(IdentityBrokerState.java:66)
    at org.keycloak.services.resources.IdentityBrokerService.getAndVerifyAuthenticationSession(IdentityBrokerService.java:1053)
    at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:418)
    ... 49 more
```

### How to reproduce?

Just start an Idp-Initiated Login Flow from an external IDP and send the assertion directly to the `broker-root/realms/{broker-realm}/broker/{idp-name}/endpoint` endpoint as also written in the description of this ticket. BUT, doing so was never supported by KC, as the documentation states [here](https://www.keycloak.org/docs/latest/server_admin/index.html#idp-initiated-login):
> **Assertion Consumer Service POST Binding URL** in the **Fine Grain SAML Endpoint Configuration** section has to be set to the following URL: `broker-root/realms/{broker-realm}/broker/{idp-name}/endpoint/clients/{client-id}`, where...

On the other hand I think @LoicGudet is right at least in the point, that KC shouldn't through a NPE, shall catch this error since the standard also states that the parameter `RelayState` is optional and should present some meaningful error message.

**Comment by Alonzzzo2** [comment] 2023-09-18 10:14
> Hi. In order to achieve a flow without a relay state you need to build an SP-initiated flow. For that, you need to create a public client. and set it up like this:
> 
> ![image](https://user-images.githubusercontent.com/16343293/208700059-d260ecb7-4879-4358-8fe7-1dc65af508e3.png) You configure the Identity provider normally and you should now be able to call the endpoint without a relay state.
> 
> Here you can find more information about it https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/clients/saml/idp-initiated-login.adoc

That link is broken, here's the new one: https://github.com/keycloak/keycloak/issues/12782

**Comment by AnirudhaGohokar** [comment] 2023-10-10 05:04
> ould now be able to call the endpoint without a relay state

For me it gets past the keycloak SP endpoint but its not going to into a loop where it redirects to keycloak SP endpoint to MS ad IDP endpoint and vice versa

**Closed** 2024-03-04 19:44 UTC
Labels: area/saml, kind/bug, area/identity-brokering, team/core-iam
