### ISSUE TITLE
Enable keycloak-js to work with "node" bundler, types are not recognized in angular and application not starting

### ISSUE THREAD

**Issue by kai1992cool** [keycloak/keycloak#34789] opened 2024-11-08 17:16 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Enable keycloak-js to work with "node" bundler, types are not recognized in angular and application not starting

Application bundle generation failed. [0.253 seconds]

✘ [ERROR] TS2307: Cannot find module 'keycloak-js' or its corresponding type declarations. [plugin angular-compiler]

    src/main.ts:3:21:
      3 │ import Keycloak from 'keycloak-js';
        ╵                      ~~~~~~~~~~~~~

### Version

^26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Types should be available

### Actual behavior

application not starting

### How to Reproduce?

https://stackblitz.com/edit/stackblitz-starters-2vmhf6

application not starting

**Comment by jonkoops** [comment] 2024-11-08 17:41
Duplicate of #33778

**Closed by jonkoops** 2024-11-08 17:41 UTC
Labels: kind/bug, area/core, status/triage, team/core-shared
