### ISSUE TITLE
unexpected behavior, keycloak-js throwing not new Error object rather {error:''...} or undefined

### ISSUE THREAD

**Issue by shimondoodkin** [keycloak/keycloak#19626] opened 2023-04-10 20:41 UTC
### Description

it expected to had thrown something usual, like a ` new Error('error message') ` 

if it is a  propagation of a previous error, a possible solution could be to modify the message of the existing error and throw it again (or set it to a promise.reject).

it was very strange to receive errors with values of undefined or like {error:'asdfasdf'} regular objects.

behavior like this is unexpected.

**Comment by jonkoops** [comment] 2023-04-11 15:44
Could you provide examples of cases where no proper error is returned? Please provide a [minimal  reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by ssilvert** [comment] 2023-05-03 20:18
Since we can't reproduce, I'm going to close this.

**Closed by ssilvert** 2023-05-03 20:18 UTC
Labels: kind/bug, area/adapter/javascript, status/triage, team/ui
