### ISSUE TITLE
Keycloak Operator: Support cluster wide configurations

### ISSUE THREAD

**Issue by Gottox** [keycloak/keycloak#12545] opened 2022-06-16 11:03 UTC
### Description

Currently the keycloak operator only supports two modes of operation:
* serving only the local namespace
* serving a list of namespace through setting `QUARKUS_OPERATOR_SDK_NAMESPACES` in the operator and deploying the RoleBindings into namespaces. (as seen in https://github.com/keycloak/keycloak/issues/11938)

I propose a third mode where a single instance of the keycloak operator serves the whole cluster.

### Motivation

As a cluster administrator, I prefer a central keycloak operator instance that serves multiple namespaces. This allows us to present the keycloak operator as a cluster service to our consumers that create and delete namespaces on demand.

### Details

I'm not sure, if there's anything to change about the operator itself, I was unable to get any events from other namespaces than the ones defined in `QUARKUS_OPERATOR_SDK_NAMESPACES` or if undefined anyones but the local one. I'm unsure if that's due to the operator only requesting events from those namespaces or if the roles I applied only report namespaced events.

**Comment by yelhouti** [comment] 2022-10-16 04:07
@Gottox I was wondering the same thing, and as far as I can tell from Quarkus Operator SDK doc:
https://quarkiverse.github.io/quarkiverse-docs/quarkus-operator-sdk/dev/index.html#quarkus-operator-sdk_quarkus.operator-sdk.namespaces
Leaving the list empty watches all namespaces.
The only thing here is that if the operator doesn't have enough privileges It won't be able to its job.
As far as I can see the code of the operator: https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/19.0.3/kubernetes/kubernetes.yml
The key role for the operator to do his job (crud statfulset, ingress...) is : keycloak-operator-role
This is role is assigned only to the current namespace using keycloak-operator-role-binding because it's a RoleBinding (not a ClusterRoleBinding), you can create a cluster role binding for the same role and everything should (in theory) work automatically .

**Comment by nrobert13** [comment] 2023-01-03 17:03
well, it seems to me that the second mode ( specifying namespaces via `QUARKUS_OPERATOR_SDK_NAMESPACES` ) is broken since `20.0.0`. see this [issue](https://github.com/keycloak/keycloak/issues/16222)

**Comment by vmuzikar** [comment] 2023-06-05 16:40
Thanks for creating the issue. This should be covered in https://github.com/keycloak/keycloak/issues/15888 (although it currently lacks details :)).

**Comment by vmuzikar** [comment] 2023-06-05 16:40
Duplicate of  https://github.com/keycloak/keycloak/issues/15888

**Closed by vmuzikar** 2023-06-05 16:40 UTC
Labels: kind/feature, status/triage, area/operator

**Comment by vmuzikar** [comment] 2023-06-06 06:33
I might be wrong but I believe it's not a bug but rather an RFE. My reasoning to close this one was that we already have an issue to track this. #15888 is covering something we call descoped mode which is basically what I understood this issue is about – having a single Operator instance managing Keycloaks in whole cluster. Please correct me if I'm wrong and feel free to reopen.

**Comment by Bengreen** [comment] 2023-06-16 08:43
Using the latest version (21.1.1) I tried the operator with the ClusterRoleBindings provided by @yelhouti 
And then added the env var:

            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKCONTROLLER_NAMESPACES
              value: default,keycloak

I was able to get the operator to work across multiple namespaces.
I then attempted to try setting the value to JOSDK_ALL_NAMESPACES or "" to make it watch all namespaces. But unfortunately this did not work and it revered to watching only the namespace it is installed into.

Any suggestions much appreciated.
Or timelines or references to track for the watch all to work?

**Comment by b-thiswatch** [comment] 2023-07-28 14:13
@Bengreen would you please point me to the ClusterRoleBindings of yelhouti? Thanks

**Comment by shawkins** [comment] 2023-07-28 14:22
@Bengreen @b-thiswatch all / multi-namespace watching will not with the current operator code.  We're putting the pr to support this on-hold until we pick up additional upstream changes from the quarkus operator sdk.

**Comment by b-thiswatch** [comment] 2023-07-28 14:23
@shawkins alright. thanks for the update!

**Comment by Bengreen** [comment] 2023-08-02 05:11
> @Bengreen would you please point me to the ClusterRoleBindings of yelhouti? Thanks

https://github.com/keycloak/keycloak/issues/12545#issuecomment-1279886768

**Comment by Bengreen** [comment] 2023-08-02 05:13
I used the cluster role bindings and packaged to a helm chart for the operator with configurable target namespace. If folks are interested I'd be happy to create as a PR to project.

**Comment by b-thiswatch** [comment] 2023-08-02 07:58
@Bengreen thanks. I must have been blind and forgot how to use ctrl + f

**Comment by ruslanguns** [comment] 2023-11-18 12:31
Is there any way to make the operator to watch on all namespaces or still the only way to approach that is by setting the `QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKCONTROLLER_NAMESPACES` environment variable?

**Comment by b-thiswatch** [comment] 2024-01-11 16:29
@shawkins is this feature planned? we are running a cluster with a test and prod keycloak and at the moment we have two operators for that. it results in two operators fighting over the CRDs, which is not quite ideal...

**Comment by shawkins** [comment] 2024-01-11 19:26
@b-thiswatch I don't have a timeline for this being considered supported. You can follow the suggestion from the last comment to update the CSV to enable all namespace support, but it won't be considered supported from a project perspective until the much more involved considerations, like blast radius, are addressed.

**Comment by b-thiswatch** [comment] 2024-01-12 09:52
@shawkins thanks, understood. this then means, officially we are supposed to run two operators for our use case for now, but then we do have the problem of having to keep them on the same version because the CRDs are cluster-wide and would be conflicting, correct?

**Comment by shawkins** [comment] 2024-01-12 15:36
@b-thiswatch that is correct.
