### ISSUE TITLE
Upgrade 25.0.6 -> 26.0.6 Admin UI, list realms doesn't working outside master realm.

### ISSUE THREAD

**Issue by RadekSalay** [keycloak/keycloak#35296] opened 2024-11-25 16:25 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When upgrading from KC 25.0.6 to 26.0.6 with a PostgreSQL database. Admin user accounts are federated from Azure AD.
In version 25.0.6 we can list realms without problems.

In version 26.0.6.
When we log in to the admin console and list realms, it shows us realms. But when we are in other realms, not in master, we can't see any realms. We can jump between realms by changing the URL.
<img width="181" alt="LoadingRealms_Unauthorized" src="https://github.com/user-attachments/assets/3f13ba1c-2105-46e2-9122-103a29fd167f">

In the debug console, I see requests ending with 401 Unauthorized. Response header: www-authenticate:
Bearer realm="master", error="invalid_token", error_description="Session expired"
When I check the JWT token, ext claim is alright on 5min.

 A request is on the path
**_serverAddress_**/auth/admin/realms/**_my_realm_**/ui-ext/realms/names?first=0&max=11&search=

But when I'm in the master realm request is 
**_serverAddress_**/auth/admin/realms/master/ui-ext/realms/names?first=0&max=11&search=
In our environment where we still have 25.0.6, no request on ui-ext/realms/names is sent.

Is possible that JWT token is somehow only for the master realm? **_Bearer realm="master"_**
Can it be related to the fact that our admin users are from Azure AD and some new configuration is needed?

### Version

26.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

We can list all realms in the admin console. From every realm, not only from master.

### Actual behavior

We can list all realms only from the master realm.

### How to Reproduce?

Sadly I don't know.

**Comment by jonkoops** [comment] 2024-11-25 17:44
Duplicate of #35277

**Closed by jonkoops** 2024-11-25 17:44 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by meveno** [comment] 2024-12-19 12:45
Hi

We're facing the same issue and we seem to have found out a specific case to reproduce.

We're having this problem when the current user is a federated user (logged with another identity provider). When we use a local keycloak user, the realm are correctly loaded ...
![image](https://github.com/user-attachments/assets/1ef6cd21-0f5d-4cf8-b096-787466eab575)
