### ISSUE TITLE
The "<" UI component to navigate tabs in "Realm settings" doesn't work

### ISSUE THREAD

**Issue by y-tabata** [keycloak/keycloak#31458] opened 2024-07-21 05:24 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

">" does work, but "<" doesn't work.
![image](https://github.com/user-attachments/assets/e198112b-77fa-4867-a4a4-2051e06db495)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The tabs on the left are displayed.

### Actual behavior

The tabs on the left are not displayed.

### How to Reproduce?

Access to the "Realm settings."

**Comment by edewit** [comment] 2024-07-22 06:47
this was logged as a PF issue https://github.com/patternfly/patternfly-react/issues/8769

**Comment by edewit** [comment] 2024-07-23 11:55
The problem is that I can't reproduce this, could you supply us with browser and os environment?

**Comment by ahanamallik1** [comment] 2024-07-25 21:35
Hello @y-tabata,

I have also tried to analyze the code and reproduce the issue but the issues seems to be very inconsistent.  I have tried on both safari and chrome browsers. It will be really great if you have provide the exact browser you are using.

**Comment by ssilvert** [comment] 2024-07-26 20:31
@y-tabata I also can't reproduce this.  I had this problem some time ago but it was fixed.

I'm going to close this one because we can't reproduce.  If you can give us a consistent way to see the problem then we can reopen.

**Closed by ssilvert** 2024-07-26 20:31 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
