### ISSUE TITLE
NullPointerException thrown for UPConfig.getGroups()

### ISSUE THREAD

**Issue by polaris940** [keycloak/keycloak#25183] opened 2023-11-30 22:48 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

```sh
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.userprofile.config.UPConfig.getGroups()" because "config" is null
	at org.keycloak.userprofile.config.UPConfigUtils.validateAttributes(UPConfigUtils.java:112)
	at org.keycloak.userprofile.config.UPConfigUtils.validate(UPConfigUtils.java:95)
	at org.keycloak.userprofile.DeclarativeUserProfileProvider.lambda$createUserDefinedProfileDecorator$8(DeclarativeUserProfileProvider.java:523)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.keycloak.userprofile.DeclarativeUserProfileProvider.configureUserProfile(DeclarativeUserProfileProvider.java:184)
	at org.keycloak.userprofile.AbstractUserProfileProvider.createUserProfile(AbstractUserProfileProvider.java:328)
	at org.keycloak.userprofile.AbstractUserProfileProvider.create(AbstractUserProfileProvider.java:205)
	at org.keycloak.services.resources.admin.UserResource.getUser(UserResource.java:325)
	at org.keycloak.services.resources.admin.UserResource$quarkusrestinvoker$getUser_7e789726117d7cfd3ef1d9ddd01596d8e6add5b0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Version

23.0.1

### Expected behavior

No errors when attempting to view User Detail pages

### Actual behavior

When trying to go into the User details for some Realms, getting a "Network response was not OK". The suggesting reload of the page does not resolve.

![image](https://github.com/keycloak/keycloak/assets/101352781/915fb077-698a-4635-bc37-2aa9d51d6815)

### How to Reproduce?

Try to navigate into a user detail when the error is present. 

### Anything else?

Doesn't appear to affect all realms so possibly related to some partial migration step?

Installation was updated automatically using the Keycloak Operator.

**Comment by ssilvert** [comment] 2023-12-01 19:22
NPE indicates this is not a UI issue.  Moving to core team.

@pedroigor FYI.

**Comment by pedroigor** [comment] 2023-12-04 19:26
I think the error is caused because we changed the name of the realm attribute where the configuration is stored. So, existing realms using user profile should break as they as using the previous name.

@polaris940 Can you confirm that, please?

Could you also confirm that forcing an update to the user profile configuration or enabling/disabling the feature at the realm settings?

**Comment by polaris940** [comment] 2023-12-04 23:31
@pedroigor This has seemingly worked itself out while I tried to debug it further. 

I had 2 realms out of a handful created that had the User Profile Enabled feature turned on at the realm level before migrating to v23. Only one seems to have been affected but the one that wasn't was more of a test realm and wasn't widely used so that could have played into it being alright. 

For the problem realm, disabling the feature at the realm level did provide a workaround. Wasn't able to try forcing an update but that may be what occurred while I was trying to debug as the deployment did restart several times, not seeing any indication that migrations were rerun though.  

For the v23 update was able to track down some logs and it appears the migration went through alright. It logged change set runs and didn't appear to throw any errors while doing so. 

```sh
[org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
Run:                          2
Previously run:             115
Filtered out:                 0
-------------------------------
Total change sets:          117
...
[io.quarkus] (main) Keycloak 23.0.0 on JVM (powered by Quarkus 3.2.9.Final) started in 17.649s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8443
[io.quarkus] (main) Profile prod activated. 
[io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
[org.keycloak.common.Profile] (main) Preview features enabled: declarative-user-profile
```

Does appear to be related to this portion of migrating that you referenced, not sure what ultimately triggered it though or why it didn't trigger with the initial migration. 
https://github.com/vramik/keycloak/blob/c836107dc8f2207fcac82f1a92870a50883e1a7a/model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java#L49-L75

Specifically, and for others if they happen upon the issue and don't want to dig through the code, I noticed a `config-piece-0` in `component_config`. That has since disappeared and seemingly replaced by `userProfileEnabled` entries for each realm in `realm_attribute`.

**Comment by pedroigor** [comment] 2023-12-05 00:49
@polaris940 Thanks for the details.

When running migration there is an error happening due to the realm not being available from the session context:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getClientScopesStream()" because "realm" is null
	at org.keycloak.userprofile.config.UPConfigUtils.validateScopes(UPConfigUtils.java:207)
	at org.keycloak.userprofile.config.UPConfigUtils.validateAttribute(UPConfigUtils.java:177)
	at org.keycloak.userprofile.config.UPConfigUtils.lambda$validateAttributes$2(UPConfigUtils.java:130)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.keycloak.userprofile.config.UPConfigUtils.validateAttributes(UPConfigUtils.java:130)
	at org.keycloak.userprofile.config.UPConfigUtils.validate(UPConfigUtils.java:107)
	at org.keycloak.userprofile.DeclarativeUserProfileProviderFactory.validateConfiguration(DeclarativeUserProfileProviderFactory.java:269)
	at org.keycloak.models.jpa.RealmAdapter.updateComponent(RealmAdapter.java:2088)
	at org.keycloak.models.cache.infinispan.RealmAdapter.updateComponent(RealmAdapter.java:1561)
	at org.keycloak.migration.migrators.MigrateTo23_0_0.updateUserProfileConfig(MigrateTo23_0_0.java:82)
	at org.keycloak.migration.migrators.MigrateTo23_0_0.migrateRealm(MigrateTo23_0_0.java:55)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
```

So the migration happened here but failed due to the above. Not sure why you did not get the same issue. I'm migrating from `22.0.4` (realm + UP enabled + single custom attribute added to config).

The error also indicates we don't have enough coverage from migration tests, I suppose.

**Comment by pedroigor** [comment] 2023-12-05 18:53
@polaris940 Would you mind giving it a try? See https://github.com/keycloak/keycloak/pull/25313.

You probably did not get errors because your configuration does not rely on realm-specific data such as scopes. But it worked for me when testing locally.

The migration tests is also running now with the feature enabled now.

**Comment by dlbas** [comment] 2024-01-04 15:33
Hey @pedroigor, sorry to bother but it seems like the issue is still present in my setup.

**Updating from 22.0.5 to 23.0.3**.

AFAIK no issues during the migration itself:
```

2024-01-04 15:18:38,412 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
--
UPDATE SUMMARY
Run:                          2
Previously run:             115
Filtered out:                 0
-------------------------------
Total change sets:          117

```

When you visit user profile in the admin UI you get NPE:
```
2024-01-04 15:21:53,582 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-8) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.userprofile.config.UPConfig.getGroups()" because "config" is null
--
at org.keycloak.userprofile.config.UPConfigUtils.validateAttributes(UPConfigUtils.java:112)
at org.keycloak.userprofile.config.UPConfigUtils.validate(UPConfigUtils.java:95)
at org.keycloak.userprofile.DeclarativeUserProfileProvider.lambda$createUserDefinedProfileDecorator$8(DeclarativeUserProfileProvider.java:523)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
at org.keycloak.userprofile.DeclarativeUserProfileProvider.configureUserProfile(DeclarativeUserProfileProvider.java:184)
at org.keycloak.userprofile.AbstractUserProfileProvider.createUserProfile(AbstractUserProfileProvider.java:328)
at org.keycloak.userprofile.AbstractUserProfileProvider.create(AbstractUserProfileProvider.java:205)
at org.keycloak.services.resources.admin.UserResource.getUser(UserResource.java:325)
at org.keycloak.services.resources.admin.UserResource$quarkusrestinvoker$getUser_7e789726117d7cfd3ef1d9ddd01596d8e6add5b0.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)
```

Please let me know if I could provide more info or additional context!

**Comment by pedroigor** [comment] 2024-01-05 10:25
@dlbas Sorry for that, I'll check it out and fix it.

**Comment by Theshedman** [comment] 2024-01-08 11:47
> @dlbas Sorry for that, I'll check it out and fix it.

@dlbas has this been fixed? I am having the same issue.

**Comment by pedroigor** [comment] 2024-01-08 11:48
I'm looking at it now

**Comment by pedroigor** [comment] 2024-01-08 13:23
@dlbas @Theshedman I'm probably missing something here when trying to reproduce the error. Here is what I'm doing:

* Create a `migration` database
* Start Keycloak 22.0.5, create a `test` realm, create a `test` user, enable user profile, and create a single `test` attribute
* Stop Keycloak 22.0.5
* Start Keycloak 23.0.3 and access the `test` realm by going to both the user profile settings and clicking on the `test` user to see their details

Does it makes sense to you?

**Comment by Theshedman** [comment] 2024-01-08 13:30
@pedroigor I am using keycloack 23.0.3
I started the server, create a **test** realm and enabled the user profile on the test realm. everything works well. but when I go to the  account  dashboard and click on a signup button, I get the error about missing **UPConfig** config (NPE)

**Comment by pedroigor** [comment] 2024-01-08 14:18
Humm ... So you are actually accessing the account console?

**Comment by pedroigor** [comment] 2024-01-08 14:39
@Theshedman @dlbas I'm missing how to reproduce this. If you could provide the exact steps you are using to force the issue (and if migrating from a previous version, the realm config should help), I appreciate.

**Comment by dlbas** [comment] 2024-01-08 14:42
@pedroigor ok I feel really silly but I'm not able to replicate this locally using the steps you've provided while updating from `22.0.5` to `23.0.3`.
I faced this issue updating an instance from `22.0.5` to `23.0.3` which is running in production-like environment, has a custom realm with some existing users/groups. It also uses some customisations like additional JWT token claims.
I'll try to replicate that setup locally and will let you know if I have something 😅

**Comment by pedroigor** [comment] 2024-01-09 14:30
@dlbas No problem, thanks. Better be safe :) If you find anything, please let me know. We can be a bit more defensive when that error is happening and prevent an unexpected NPE as you have reported.

**Comment by Theshedman** [comment] 2024-01-11 09:21
> Humm ... So you are actually accessing the account console?

@pedroigor No, I could not access the account console. I get the error once I try to sign up to the console.

**Comment by pedroigor** [comment] 2024-01-11 20:23
@Theshedman Could you please provide the steps to reproduce then? Preferrable using a fresh distribution from 22.0.5 and latest?

**Comment by anton-skutov** [comment] 2024-01-16 10:25
To migrate and avoid the issue was required to change
```
"config-pieces-count": [
            "29"
          ],
          "config-piece-0": [
            "{ \"attributes\": ["
          ],
          "config-piece-1": [
            "{ \"name\": \"firstName\", \"displayName\": \"${firstName}\","
          ],
...
```
to 
```
"kc.user.profile.config": [
            "{ \"attributes\": [{ \"name\": \"firstName\", .... }"
```

**Comment by pedroigor** [comment] 2024-01-16 10:34
@anton-skutov That is weird .. It should happen during migration. I think the problem here might be the fact you have multiple "pieces" and the migration is not doing its job properly.

I'll have a look.

**Comment by sebastianSchmidt86** [comment] 2024-02-07 12:20
@pedroigor I tried updating to version 23.0.6 and I still get this error. It looks like user profile configuration is not migrating correctly.
Has it been fixed already?

**Comment by pedroigor** [comment] 2024-02-07 12:26
@sebastianSchmidt86 It seems not ... Can you please provide a realm configuration (before migrating) that I can use to reproduce locally? I'm not sure what is going on.

I'm also re-opening the issue.

**Comment by sebastianSchmidt86** [comment] 2024-02-07 12:50
Sorry @pedroigor - I had another configuration error. The declarative user profile migration works as expected.

**Comment by pedroigor** [comment] 2024-02-07 14:08
phew :)

**Comment by pedroigor** [comment] 2024-02-07 14:08
So, closing again.

**Closed by pedroigor** 2024-02-07 14:08 UTC
Labels: kind/bug, priority/important, area/user-profile, team/core, release/24.0.0, release/23.0.2

**Comment by remigauthierdocaposte** [comment] 2024-02-09 16:05
FYI we reproduced this bug while migrating from 21.1.1 to 23.0.6.

`Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.userprofile.config.UPConfig.getGroups()" because "config" is null`

![image](https://github.com/keycloak/keycloak/assets/89779307/05e0b971-176e-419a-a823-ce74dbfbeebb)

I know that user profiles are in preview mode but the fast fix to be able to see user details again is the following :
- activate "User profile enabled" if not already done
- Go to the "User profile" tab for the "Realm Settings" Menu 
- Open the "JSON editor" sub tab
- Just click "Save"

--> You will be able to access user details from now on

**Comment by indiealexh** [comment] 2024-03-09 09:20
> FYI we reproduced this bug while migrating from 21.1.1 to 23.0.6.
> 
> `Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.userprofile.config.UPConfig.getGroups()" because "config" is null`
> 
> ![image](https://private-user-images.githubusercontent.com/89779307/303706914-05e0b971-176e-419a-a823-ce74dbfbeebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzUzMTcsIm5iZiI6MTcwOTk3NTAxNywicGF0aCI6Ii84OTc3OTMwNy8zMDM3MDY5MTQtMDVlMGI5NzEtMTc2ZS00MTlhLWE4MjMtY2U3NGRiZmJlZWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA5MDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOThjMDQzZmVmNTZkOGE2OWFkNTFjY2IwMTBhMTRhNWY2ZDg0YzQyZWY0ODA2YTBjNzIzOGI0YWUxNjM0YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZ3i2es8YiVHsBsfI4fboQW8qOJ3QbUQpHbLq5KgZVQ)
> 
> I know that user profiles are in preview mode but the fast fix to be able to see user details again is the following :
> 
> * activate "User profile enabled" if not already done
> * Go to the "User profile" tab for the "Realm Settings" Menu
> * Open the "JSON editor" sub tab
> * Just click "Save"
> 
> --> You will be able to access user details from now on

Life saver! I was about ready to tell my users the bad news.

**Comment by yaroslav-koval** [comment] 2024-07-03 14:25
I've encountered the same error ```Cannot invoke "org.keycloak.representations.userprofile.config.UPConfig.getGroups()" because "config" is null``` migrating from v16.4 to v23.0.1, but @remigauthierdocaposte answer above resolved my problem, thank you
