### ISSUE TITLE
proxy error 

### ISSUE THREAD

**Issue by CarlosNasayo** [keycloak/keycloak#26348] opened 2024-01-20 04:21 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I'm new to Keycloak, I'm trying to deploy Keycloak in production, but when I do everything I get this, I'm going to leave a capryra of KIS conf file and what I get in the browser
<img width="634" alt="image" src="https://github.com/keycloak/keycloak/assets/86987650/29114fda-2edd-48a5-9a20-2787c36071b2">

<img width="617" alt="Screenshot 2024-01-19 231303" src="https://github.com/keycloak/keycloak/assets/86987650/cdd3fbac-8a51-4f2a-9b98-3187e339f27e">
<img width="344" alt="image" src="https://github.com/keycloak/keycloak/assets/86987650/72503be6-cc18-4434-a05e-1050e4aaea81">

I would be very grateful if you can help me

### Version

22.0.5

### Expected behavior

It should start normal

### Actual behavior

error in proxy

### How to Reproduce?

doing the build and do the star comand

**Comment by jonkoops** [comment] 2024-01-20 10:30
Closing this issue as it was reported for an older version of Keycloak, as well as not including steps to reproduce, or a minimal reproducible example. Either way, this looks like a configuration problem, perhaps not even related to Keycloak itself.

**Closed by jonkoops** 2024-01-20 10:30 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
