### ISSUE TITLE
I'm able to delete account 1 with account 2 login details

### ISSUE THREAD

**Issue by zivcex** [keycloak/keycloak#26925] opened 2024-02-09 11:49 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Hello after enabling delete account we've been able to delete account 1 by logging in with account 2. We're not using out-of-the-box Account

### Version

23.0.4

### Expected behavior

I delete account 1 while logging in solely with account 1. Otherwise, the request is rejected.

### Actual behavior

I deleted account 1 while logging in with account 2.

### How to Reproduce?

Issue a delete account action with re-auth for account 1, and re-login with account 2, the account 1 will get deleted.

**Comment by zivcex** [comment] 2024-02-09 14:36
> What do you mean by this? You are using a customized Account Console?

We're using Account API to fetch the details. And we're crafting action URL and redirecting to Keycloak for update password, delete account, update email.

> You'll have to provide us with some more detailed steps to reproduce this issue. Where are you initiating this behaviour?

Try to delete account with email1@x.com, it will ask for re-auth then login with other account (email2.x.com) and you'll delete email1@x.com if you confirm the delete.

**Comment by abencun-symphony** [comment] 2024-02-09 14:43
I'm from the same team as @zivcex.

We're doing the following:
- the user logs in to the client app using their email/pw, let's say email1@example.com (we use the standard auth flow) 
- the user decides to delete their account: here we use keycloak-js to generate a login action  URL for the delete action and redirect them to Keycloak
- after redirection they are required to reauthenticate on Keycloak in order to complete the action
- the user can then proceed to authenticate with a completely different account on this screen (e.g. email2@example.com) and proceed to confirm the deletion of the account
- the account with the email email1@example.com is deleted

We would expect this to be impossible to accomplish.

**Comment by ssilvert** [comment] 2024-02-12 20:04
OK.  This is a server-side API issue.  Transferring to core team.

**Comment by martin-kanis** [comment] 2024-02-19 11:09
@abencun-symphony I tried this with 23.0.6 and pure account console and behavior is slightly different in my case (still not ideal in my opinion)

1. enable delete-account required action and create 2 users in admin console user1 and user2
2. set passwords and delete-account role for them
3. log in as **user1** into the account console and initiate delete account action
4. you are redirected to a page with **pre-filled user1 identity** to enter the password again
5. you are able to restart the flow with blue arrow in which case you are redirected to an empty login page
6. you can log in as **user2** and continue with the delete account flow
7. another warning page is shown that account will be deleted and you have to confirm it or cancel
8. if you confirmed **user2** is deleted

So the difference is that I deleted a user that didn't request the delete account action but I needed to have correct credentials for the user.
So my question is how do you generate the login action with keycloak-js? That is probably the step I'm missing here.

**Comment by zivcex** [comment] 2024-02-27 13:17
What's the status for this task @pedroigor ?

**Comment by vramik** [comment] 2024-02-27 14:00
@abencun-symphony Could you please provide an example URL when you call 
```js
kcInstance.createLoginUrl({ action, redirectUri, loginHint });`
```
? 

I'd like to find out where is the difference between standard theme and the custom one. 

When I follow steps from @martin-kanis. In step 4 the URL parameters looks like: 

**client_id**=account-console
**redirect_uri**=http%3A%2F%2Flocalhost%3A8080%2Frealms%2Ftest%2Faccount%2F%23%2F
**state**=ba286864-4380-4578-871e-799144110c2c
**response_mode**=query
**response_type**=code
**scope**=openid
**nonce**=f5136ba5-4a73-4c84-bb7e-be52a3be03df
**kc_action**=delete_account
**code_challenge**=lEzAkv7oejofgdYzMSgs5TCjfEG62BYBxQyaG6EpRFs
**code_challenge_method**=S256

Thanks a lot.

@zivcex the issue is currently being investigated.

**Comment by abencun-symphony** [comment] 2024-02-27 14:24
Here it is for the `delete_account` action. Please keep in mind that I've replaced some of the data in the URL that we don't want to post pubicly here (domain, realm name, client ID, my email):

```
https://OUR_DOMAIN_NAME/realms/OUR_REALM_NAME/protocol/openid-connect/auth?
client_id=OUR_CLIENT_ID
&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Faccount%2Fdetails
&state=305125f0-a022-4780-999b-e08918e489c6
&response_mode=fragment
&response_type=code
&scope=openid
&nonce=df88980a-7846-4343-879a-9f38e14723ce
&login_hint=MY_ACCOUNT_EMAIL
&kc_action=delete_account
```

I see that the `code_challenge` and `code_challenge_method` are missing when generating URLs on our end, but should that be an issue? `response_mode` is also different but I'm wondering whether that should matter?

**Comment by zivcex** [comment] 2024-02-27 16:25
`code_challenge` and `code_challenge_method` are PKCE verifications for public clients. This shouldn't cause any issues with the actual authentication.

**Comment by vramik** [comment] 2024-02-28 13:36
@zivcex @abencun-symphony thank you. Unfortunately so far I was not able to get to the point where I would be able to delete one user with the other user's credentials. Could you please provide how the authentication flow in your realm looks like? Is it the standard one with Username Password Form?

**Comment by zivcex** [comment] 2024-02-28 13:53
I can't share the authentication flows but username password form is still there and that hasn't been extended at all.

**Comment by vramik** [comment] 2024-02-28 13:56
> I can't share the authentication flows but username password form is still there and that hasn't been extended at all.

Thank you, I'm afraid that I cannot do much more here without a reproducer or some steps how the issue could be reproduced. Would you be able to create such a reproducer?

~missing-info

**Comment by zivcex** [comment] 2024-02-28 14:43
I've set up the browser flow with Keycloak and can still reproduce the same scenario on the account console/account management console. 

Also in this required action challenge in the delete action, there's no check that the customer who requested the delete account action is the one who wants to delete the account. Or am I missing something here:

org.keycloak.authentication.requiredactions.DeleteAccount
```
  @Override
  public void requiredActionChallenge(RequiredActionContext context) {
      if (!clientHasDeleteAccountRole(context)) {
        context.challenge(context.form().setError(Messages.DELETE_ACCOUNT_LACK_PRIVILEDGES).createForm("error.ftl"));
        return;
      }

      context.challenge(context.form().setAttribute(TRIGGERED_FROM_AIA, isCurrentActionTriggeredFromAIA(context)).createForm("delete-account-confirm.ftl"));
  }
```

**Comment by vramik** [comment] 2024-02-28 14:54
@zivcex could you please provide exact steps how did you reproduce it? I'm not able to do so on my end and without it I cannot proceed. 

Alternatively any PR with a test case and a fix is more then welcome. Thank you.

**Comment by zivcex** [comment] 2024-02-29 09:56
Steps to reproduce:
- new realm with regular/default browser flow 
- create two users and add them the role of delete-account
- login as user A and try to delete the account
- re-authentication screen appears
- I login as user B here
- I get thrown to confirm delete account
- I click confirm/submit
- User A is deleted

These don't reproduce on your end?

**Comment by zivcex** [comment] 2024-02-29 10:54
Okay @vramik same on my end with the default login theme happens. So I suppose we don't pre-fill correctly the login page if re-authz occurs. Will be checking it from here and reply on this issue.

**Comment by zivcex** [comment] 2024-02-29 14:10
We're using Keycloakify to generate these themed pages, and we missed somehow this attempted username check. We'll add it now and see what happens.

Can you somehow circumvent this page with a prefilled username with the default theme? If that's doable you can check if the replacement happens and why.

**Closed** 2024-07-26 00:06 UTC
Labels: kind/bug, area/account/api, help wanted, team/core-iam, team/core-shared, priority/low, status/auto-expire, status/auto-bump, status/expired-by-bot
