### ISSUE TITLE
Partial import - include SMTP-Password from imported realm

### ISSUE THREAD

**Issue by c0ntradicti0n** [keycloak/keycloak#15428] opened 2022-11-09 17:14 UTC
### Area

import-export

### Describe the bug

I can successfully import SMTP-settings, but not really the authentication details.

I have there:

```json
  "smtpServer": {
    "replyToDisplayName": "project",
    "starttls": "false",
    "auth": "true",
    "envelopeFrom": "${MAIL_ADDRESS}",
    "ssl": "true",
    "password": "${MAIL_PASSWORD}",
    "port": "${MAIL_SMTP_PORT}",
    "host": "${MAIL_SMTP_HOST}",
    "replyTo": "${MAIL_ADDRESS}",
    "from": "${MAIL_ADDRESS}",
    "fromDisplayName": "project",
    "user": "${MAIL_USER}"
  },
```
  
 That works so far, but when testing the connection it fails. Seems to be a frontend issue, that only the "Authentication"-switch misbehaves here something, because after disabling and enabling testing the connection works, also the Section is collapsed despite button is enabled

### Version

19.0.3

### Expected behavior

Connection should be testable directly after import

### Actual behavior

Not testable

### How to Reproduce?

Create realm and configure smpt-server

**Comment by hmlnarik** [comment] 2023-02-17 12:51
Triaging blocked on https://github.com/keycloak/keycloak-ui/issues/4420

**Comment by hmlnarik** [comment] 2023-02-17 16:39
@c0ntradicti0n Please provide more detailed steps to reproduce.

How do you import the realm? Via admin console? Via command line? Can you provide exact steps?

**Comment by ctmay4** [comment] 2023-03-17 18:00
I'm having a similar situation, however the issue goes beyond SMTP settings. It seems like non of the tabs in "Realm Settings" are getting imported. 

I verified that the SMTP settings were present in the exported realm file.

```json
  "smtpServer": {
    "replyToDisplayName": "",
    "starttls": "false",
    "auth": "",
    "port": "25",
    "host": "smtp.imsweb.com",
    "replyTo": "no-reply@imsweb.com",
    "from": "seertransfer@seerdms.com",
    "fromDisplayName": "SEER*Transfer",
    "envelopeFrom": "",
    "ssl": "false"
  }
```

I imported using these settings.

![image](https://user-images.githubusercontent.com/444345/225982534-ffc1d3d6-c7fd-4712-987d-93694c87426b.png)

and here is the summary

![image](https://user-images.githubusercontent.com/444345/225982746-d8096f80-cb40-4bed-979d-9cde47852f2b.png)


After the import I verified that none of those fields were set in "Email" tab of realm settings in the new realm.

![image](https://user-images.githubusercontent.com/444345/225982878-92f8dbf4-60c8-47e5-9add-4dd9247a9b81.png)

**Comment by hmlnarik** [comment] 2023-05-16 06:55
@c0ntradicti0n I cannot reproduce the issue. Could you please retry with the latest keycloak and check if it still is an issue? If it indeed is, please provide more detailed steps to reproduce.

@ctmay4 Thank you for the details. The partial import does not support updating realm properties.

**Comment by hmlnarik** [comment] 2024-01-10 10:23
I'm reclassifying to enhancement. This issue is about importing realm properties in partial import.

@ahus1 I am personally in favour of closing this if it cannot be touched anytime soon, but assigning this to you to consider its destination (to close or not close)

**Comment by ahus1** [comment] 2024-01-10 11:30
A full import for a new realm via the UI should work, as well as a full import on the CLI. I also see that it didn't receive many comments or votes since it has been opened. The settings on a realm can still be changed via other REST operations on the CLI.

As for the partial import via the UI, I'm following Hynek's suggestion to close it. Still, if someone would in the future propose a PR to improve it, I would be happy to review it.

**Closed by ahus1** 2024-01-10 11:30 UTC
Labels: kind/enhancement, area/import-export, team/store, status/triage
