### ISSUE TITLE
Resources are not correctly loaded with proxy config

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#17586] opened 2023-03-08 07:22 UTC
### Describe the bug

Hi, I am currently helping a client with the keycloak installation and we noticed an issues with the configuration when using reverse-proxies:

![setup-keycloak](https://user-images.githubusercontent.com/3079540/223641257-d1f9e8dd-89cc-4865-86ab-dcfc5c604be6.png)

When using the following condition we cannot enter the admin-ui:

**Scenario 1:**
The client wanted to access the webadmin with localhost for testing with the following configuration
   - hostname-port=6666
   - http-port=8080
   - hostname-admin=localhost
   - hostname=${external-access-hostname}
   - proxy=edge
I tried to recreate this scenario on my local machine and got the following result as shown by the browser:
  
![keycloak-login-failure-2](https://user-images.githubusercontent.com/3079540/223644085-8ead3992-ca0d-4076-8c1c-18b9752a7dc0.png)

The admin console is not loaded because the hostname-port is basically hijacking the access to the html-resource. So allowing access only from localhost to the admin-ui is not possible.
The screenshot shows access via HTTP in the browser. But the same result occurs if I access it with https://localhost:8443

**Scenario 2:**
If the scenario 1 would be fixed we would still run into another problem if the client wants access via HTTP to the keycloak from localhost:
   - https-port=8180
   - http-port=8080
   - hostname-admin=localhost
   - hostname=${external-access-hostname}
 
![keycloak-login-failure](https://user-images.githubusercontent.com/3079540/223647405-6d6daa17-cea3-4275-83ee-0cfd581d159b.png)

When trying to access the admin-ui with http a call is made with https that is rejecting the access.

### Version

all Quarkus related versions until 21.0.1

### Environment

all browsers

### Expected behavior

Login is possible

### Actual behavior

Login is not possible

### How to Reproduce?

see description

**Comment by ssilvert** [comment] 2023-03-11 19:58
Closing as a duplicate of #14666

**Closed by ssilvert** 2023-03-11 19:58 UTC
Labels: kind/bug, status/triage
