### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.session.OfflineSessionPersistenceTest#testPersistenceMultipleNodesClientSessionAtSameNode

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#16571] opened 2023-01-23 07:29 UTC
## org.keycloak.testsuite.model.session.OfflineSessionPersistenceTest#testPersistenceMultipleNodesClientSessionAtSameNode
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/3966046833/jobs/6796515905) / [Pull Request #16547](https://github.com/keycloak/keycloak/pull/16547)

```
java.lang.AssertionError: 
threads didn't terminate in time: [main (TIMED_WAITING): locked on java.util.concurrent.FutureTask@2a0b92a1 waiting for 152885 ms blocked for 7 ms
	at java.base@11.0.17/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.17/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.17/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444)
...
```

**Comment by martin-kanis** [comment] 2023-06-14 13:53
I wasn't able to reproduce this locally nor in [20 GHA runs](https://github.com/martin-kanis/keycloak/actions/runs/5266667685/jobs/9521209385). I'll monitor this for a week or so. if this re-appear.

**Comment by martin-kanis** [comment] 2023-06-23 11:21
Closing as the issue seems to be gone.

**Closed by martin-kanis** 2023-06-23 11:21 UTC
Labels: kind/bug, area/storage, area/ci, team/store, flaky-test
