### ISSUE TITLE
admin console is not loaded because of "whoami" request returns http 401

### ISSUE THREAD

**Issue by rajbhupendra588** [keycloak/keycloak#26577] opened 2024-01-30 05:20 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We are migrating from KC 22 to KC 23 

When we try to log in to KC admin , whoAmI API is failing with 401

![tempsnip](https://github.com/keycloak/keycloak/assets/10944722/48f4266e-eb85-47d4-abc6-b2a5c3c71fe2)

### Version

23.0.1

### Expected behavior

whoAmI Api should have passed

### Actual behavior

whoAmI Api is failing

### How to Reproduce?

1. TLS is not enabled 
2. --proxy=edge
3. Run kc.sh  "--verbose start --optimized --hostname-strict=false -Djnr.ffi.asm.enabled=false -Dcore.contextpropagation.providers.xversion.sync.enabled=false --hostname-strict-https=false --http-enabled=true --proxy=edge"

### Anything else?

I have tried setting 
PROXY_ADDRESS_FORWARDING, KC_HOSTNAME_ADMIN_URL, KC_FRONTEND_URL but after all I am still getting 401.

**Comment by rajbhupendra588** [comment] 2024-01-30 05:26
so basically it's failing in TokenVerifier.java#L112-113

`
if (! this.realmUrl.equals(t.getIssuer())) {
                throw new VerificationException("Invalid token issuer. Expected '" + this.realmUrl + "'");
            }
`

Here in keycloak session, instead of the actual Host of our cloud, the default hostname is set 

i.e 

this.realmUrl = http://{kc-service-name}:8080/auth/realms/master **// this is incorrect** 
t.getIssuer() = https://{actual-hostname-in-token}/auth/realms/master **// this is correct**

**Comment by ssilvert** [comment] 2024-01-31 00:56
This doesn't look like a UI bug.  Moving to core.

**Comment by rajbhupendra588** [comment] 2024-01-31 15:37
@pedroigor 
Can you please help here ?

**Comment by pedroigor** [comment] 2024-02-02 12:11
@rajbhupendra588 As you have `hostname-strict=false`, the base URL (scheme, host, port) you are using to access the admin console should be the same as in the token issuer.

Ideally, you should set the `hostname-url` to avoid such issues.

**Comment by pedroigor** [comment] 2024-02-06 20:05
Thanks, please re-open if still the case.

I can't reproduce this using the steps you provided in the issue.

**Closed by pedroigor** 2024-02-06 20:05 UTC
Labels: kind/bug, area/dist/quarkus, team/cloud-native, status/triage
