### ISSUE TITLE
Docs: server_admin/topics/users/proc-requiring-tac-agreement-at-registration.adoc

### ISSUE THREAD

**Issue by Cetellibe99** [keycloak/keycloak#22389] opened 2023-08-11 10:20 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

File: server_admin/topics/users/proc-requiring-tac-agreement-at-registration.adoc

### Version

22.0.1

### Expected behavior

- Set terms of agreement as checkbox on the register page

### Actual behavior

- Not even able to set terms and conditions step for the registration page. I can only set the feature if I am switching to master realm. I have enabled the user registration and terms and conditions required action.

### How to Reproduce?

Create a new realm, enable terms and conditons required action and User Registration. Then go to the registration flow page - you are not able to see the terms and conditions option.

### Anything else?

I would like to use this feature for the reset password flow. Can this be somehow configured? or at least make it working for the registration flow

**Comment by ahus1** [comment] 2023-09-01 15:29
Duplicate of #22612

**Closed by ahus1** 2023-09-01 15:29 UTC
Labels: kind/bug, area/user-profile, status/triage, team/core
