### ISSUE TITLE
session_state is missing from authendication response incase of client credentials grant

### ISSUE THREAD

**Issue by M-Sivanraj** [keycloak/keycloak#11653] opened 2022-04-25 14:26 UTC
### Describe the bug

We are generating token using client credential grant in Keycloak on version 10.0.2 which works good recently we upgraded our keyclak to latest which is 17.0.1 where as "session_state" is missing from the token. 

incase of password grant it works fine also I have cross checked the setting "Exclude Session State From Authentication Response" on keycloak client which disabled only but still keycloak not providing me the "session_state" on token response for client cred use.

Can someone guide me what I am missing or it's issue on Keycloak 17.

### Version

17.0.1

### Expected behavior

"session_state" parameter should included in all authendication response.

### Actual behavior

"session_state" parameter is missing from authendication response incase of client cred grant

### How to Reproduce?

Try to generate the token with your clientid and secret with "Service Accounts Enabled" property enabled.

**Comment by mposolda** [comment] 2022-05-25 10:19
@M-Sivanraj Thanks for the report. There is no session_state because there is no session created by default in case of client credentials grant. This is for performance optimizations.

In case you really need session for the Client Credentials Grant, you can enable switch "Use Refresh Tokens For Client Credentials Grant" in admin console in the client settings (Section "OpenID Connect Compatibility Modes" ).

I am closing this as this is expected behaviour. Feel free to re-open if you have more questions/concerns related to this.

**Closed by mposolda** 2022-05-25 10:19 UTC
Labels: area/oidc, kind/bug, status/triage
