### ISSUE TITLE
Admin UI doesn't show the service account user's attributes

### ISSUE THREAD

**Issue by colcek** [keycloak/keycloak#29855] opened 2024-05-26 10:14 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After upgrading to version 24, the admin UI stopped listing the existing attributes for services accounts. It is possible to add a new attribute but it disappears as soon as the page is saved. Similarly, you can't add a new attribute (even though it isn't listed on the page) if it already exists. In short, it is not possible to delete or modify an existing attribute.

Token is generated correctly and can include the attributes if the mappers are defined.

One interesting thing is that the admin REST api (`/users`) returns the attributes properly.

### Version

24.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

The attributes should be listed under `Attributes` tab of the service account.

### Actual behavior

Existing attributes are not listed

### How to Reproduce?

Create a client having service accounts and go to the service account user and add attribute. Afterwards, that attribute disappears from the page.

**Comment by edewit** [comment] 2024-05-28 07:28
duplicate of #29362

**Closed by edewit** 2024-05-28 07:28 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui
