### ISSUE TITLE
Keycloak UI admin query users causes java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by aresabalo** [keycloak/keycloak#23219] opened 2023-09-13 17:51 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When you enter on Keycloak UI Admin for user matenaince and openldap user storage configured, it causes by default one full search on openldap without filters:

resultSize: 65622 entries
took: 131007 ms

Finally, keycloak ends with blocked threads due to java.lang.OutOfMemoryError: Java heap space
Only reboot is posible.

### Version

22.0.X

### Expected behavior

Don't permit full search or limit results automatically, when user enter on user mantenaince.

### Actual behavior

Keycloak terminating due to java.lang.OutOfMemoryError: Java heap space

### How to Reproduce?

Enter on Keycloak UI Admin for user matenaince.

**Logs:** 

2023-09-13 11:22:09,016 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.perf] (executor-thread-1)
LdapOperation: search
baseDn: ou=Users,dc=example,dc=com
filter: (&(objectclass=identityPerson))
searchScope: 1
returningAttrs: [uid, nickName, lastLoginTime, im, externalId, mobile, modifyTimestamp, otherPhone, givenName, aytoEscaladorID, cn, mail, aytoAbsysID, lastLogonTime, sn, aytoBicicorunaID, createTimestamp, dateOfBirth, extendedExternalId]
resultSize: 65622
took: 131007 ms

Terminating due to java.lang.OutOfMemoryError: Java heap space

### Anything else?

**Workaround:** activate pagination in user federation screen.

**Comment by cesarcoruna** [comment] 2023-09-14 06:52
This query is automatically executed when entering the "Evaluate" tab of a client's "Authorization" section. As it is executed before typing anything in the user box, the query does not include any filter and tries to retrieve all users.

**Comment by edewit** [comment] 2023-10-03 06:15
The query that is done is limited to 20: `admin/realms/master/users?max=20`

**Comment by cesarbtt** [comment] 2023-10-03 06:49
The url you send looks like the API. We are talking about the Admin-UI

In the log of our system you can see that it does not limit to any number of results.

**Comment by edewit** [comment] 2023-10-03 09:46
@cesarbtt this is the api call the UI makes

**Comment by cesarbtt** [comment] 2023-10-03 10:16
With the log of org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager at debug level you can see the difference of having the "Paginated" parameter activated or not. With the parameter activated, the number of elements is effectively limited to 20, but without it, the virtual machine tries to recover the whole ldap and it throws the virtual machine with an OutOfMemoryError error. The problem is that this query is executed immediately by clicking on the "Evaluate" tab and only with that the keycloak instance crashes.

I copy below the log output with and without paging enabled.

============= PAGINATION ACTIVE ===========================
2023-10-03 12:10:33,561 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.perf] (executor-thread-7)
LdapOperation: searchPaginated
 baseDn: ou=Users,dc=coruna,dc=gal
 filter: (&(objectclass=identityPerson))
 searchScope: 1
 returningAttrs: [uid, nickName, lastLoginTime, aytoAutenticacionNivel3, im, externalId, mobile, modifyTimestamp, otherPhone, aytoAutenticacionNivel4, description, givenName, aytoEscaladorID, cn, mail, aytoAbsysID, lastLogonTime, sn, aytoBicicorunaID, createTimestamp, dateOfBirth, extendedExternalId]
 limit: 19
 resultSize: 19
took: 111 ms


============= PAGINATION INACTIVE ===========================
2023-10-03 12:12:39,381 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.perf] (executor-thread-14)
LdapOperation: search
 baseDn: ou=Users,dc=coruna,dc=gal
 filter: (&(objectclass=identityPerson))
 searchScope: 1
 returningAttrs: [uid, nickName, lastLoginTime, aytoAutenticacionNivel3, im, externalId, mobile, modifyTimestamp, otherPhone, aytoAutenticacionNivel4, description, givenName, aytoEscaladorID, cn, mail, aytoAbsysID, lastLogonTime, sn, aytoBicicorunaID, createTimestamp, dateOfBirth, extendedExternalId]
 resultSize: 65638
took: 51277 ms

Terminating due to java.lang.OutOfMemoryError: Java heap space

**Comment by edewit** [comment] 2023-10-03 11:51
@cesarbtt so this issue is on the server side and the parameters are not going through?

**Comment by cesarbtt** [comment] 2023-10-03 11:54
I don't know whether to call the error an interface error or a server error. For me it is an error that the query is executed as soon as I enter the "Evaluate" tab, so it could be an interface error. On the other hand it also seems to me important that a massive user query manages to throw the whole keycloak instance because of a memory error.

**Comment by edewit** [comment] 2023-10-03 11:56
I'll change it to make it a server error as the UI is only querying the first 20 users.

**Comment by pedroigor** [comment] 2024-03-27 20:45
@sguilhen Based on a similar [issue](https://github.com/keycloak/keycloak/issues/27989#issuecomment-2009817051) we recently discussed, I think we can close it?

**Comment by sguilhen** [comment] 2024-03-28 02:13
@pedroigor Not sure is the same thing - in this case, based on one of the commands, it is mentioned that the whole user base is loaded as soon as you enter the "Evaluate" tab (so it is authz related). We need to check why the console is fetching things like this.

**Closed** 2024-04-10 21:04 UTC
Labels: kind/bug, priority/important, area/core, team/core-iam, status/auto-expire, status/expired-by-bot
