### ISSUE TITLE
When Localization is enabled in realm settings, the login page layout is a bit messy

### ISSUE THREAD

**Issue by potterhe** [keycloak/keycloak#33761] opened 2024-10-10 05:43 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

look attach file, "locales" extrusion titile text "Sign in to your account"

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

![20241010133233](https://github.com/user-attachments/assets/f6939ed4-a0e8-4556-8e2c-52af345dc9f3)

### Actual behavior

login form layout well

### How to Reproduce?

realm-settings -> localization -> Internationalization enabled -> "Supported locales" select multi; then view login page

**Comment by SebastEnn** [comment] 2024-10-10 07:22
Duplicate of #33607

**Comment by jonkoops** [comment] 2024-10-10 09:36
Duplicate of #33607

**Closed by jonkoops** 2024-10-10 09:36 UTC
Labels: kind/bug, status/triage, area/login/ui, team/core-clients
