### ISSUE TITLE
The freemarker templates are not compiled correctly

### ISSUE THREAD

**Issue by chsun68** [keycloak/keycloak#10431] opened 2022-02-24 03:19 UTC
### Describe the bug

The following pages are not compiled correctly in the downloaded Zip file and the docker image:
* User Federation (http://localhost:8080/admin/master/console/#/realms/master/user-federation)
* Users (http://localhost:8080/admin/master/console/#/realms/master/users)

### Version

17.0.0

### Expected behavior

Visiting http://localhost:8080/admin/master/console/#/realms/master/users
The page title shall be "Users".

### Actual behavior

The page title is `{{:: 'users' | translate}}`

### How to Reproduce?

Visit "User Federation" or "Users" pages from the left sidebar menu in the Keycloak admin console.

**Comment by chsun68** [comment] 2022-02-24 07:11
Screenshot
![Screenshot-user-federation](https://user-images.githubusercontent.com/58097055/155475727-f58bc01b-05e6-4f1a-8260-a8fb7a4d7f0b.png)
![Screenshot-users](https://user-images.githubusercontent.com/58097055/155475735-dea32936-81c3-4b05-b88c-4e9c558de941.png)
s

**Comment by Arthur380** [comment] 2022-02-24 09:42
Hello,

Same issue for me.

**Comment by stianst** [comment] 2022-02-25 08:00
Can you please check developer console in the browser so see if there are any 404s or any JS errors?

**Comment by Arthur380** [comment] 2022-02-25 08:46
![image](https://user-images.githubusercontent.com/45686298/155684034-20e60717-16b3-4877-81e0-fde0f8deb41f.png)

**Comment by stianst** [comment] 2022-02-25 08:55
Weird, a few more questions:

* Any 404s?
* What browser/Firefox version? Do you have any extensions installed?
* Does it also happen in other browsers?
* Does it always happen?

**Comment by Arthur380** [comment] 2022-02-25 09:48
I have no 404 errors.
I use firefox version 68.0 but it also happened on Chrome.
And yes I have this issue everytime.

**Comment by stianst** [comment] 2022-02-25 09:52
> I have no 404 errors. I use firefox version 68.0 but it also happened on Chrome. And yes I have this issue everytime.

That's strange because we've not been able to reproduce this one ourselves. Would you be able to provide me with the exact steps to reproduce it?

**Comment by Arthur380** [comment] 2022-02-25 09:56
Yes I've install Keycloak on docker(v20.10.11) on my Ubuntu and then I use the following line to launch keycloak 
`sudo docker run -p 3030:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:17.0.0 start-dev`

That's all I did about Keycloak.

Any ideas ?

**Comment by stianst** [comment] 2022-02-25 10:03
Copy/pasted that command here and it is working just fine. Was wondering if it could be down to exposing it as 3030, but that seems to be working just fine here in both Chrome and Firefox.

I'm a bit clueless here to be honest, only thing I can think of is that it's something specific to your OS/Browser/Extension, or something like that.

@jonkoops @EricWittmann @ssilvert Any clues?

**Comment by jonkoops** [comment] 2022-02-25 16:59
I am unable to reproduce this using Keycloak 17.0.0 in the following browsers on Fedora 34:
- Firefox 97.0
- Chrome 98.0.4758.102

@Arthur380 Firefox 68 is no longer supported as far as I can see, even for an extended support release. Can you use a more recent version of Firefox and confirm this is still happening there? Also which version of Chrome are you running?

Also if this error happens in Chrome, can you share a screenshot of the stack trace there? Firefox tends to butcher these since older versions have trouble reading the source maps.

@chsun68 can you also let me know what version of Firefox you are using? Please also try a more recent version if it is outdated.

**Comment by chsun68** [comment] 2022-02-28 01:43
Here is the snapshot of developer console on CentOS 7 Firefox 68.3.0esr
![Screenshot-user-federation-1](https://user-images.githubusercontent.com/58097055/155910503-c7d60956-ca76-42dd-9abc-c5eb68eb8795.png)

My firefox 72.0.1 on Windows has the similar problem.

My chrome 98 on Windows is OK.

Yes, it seems the problem relates to browser version.

**Comment by chsun68** [comment] 2022-02-28 01:55
I update the Firefox on CentOS 7 to 91.6.0esr and it works!

@Arthur380 , did you try a newer version of your browser?

**Comment by Arthur380** [comment] 2022-02-28 08:56
I installed the latest version of Chrome (v98.0.4758.102) and it works well !
Thanks !

**Comment by jonkoops** [comment] 2022-02-28 10:05
Thanks for testing all! I am closing this issue as we do not support these older browser versions any longer.

**Closed by jonkoops** 2022-02-28 10:05 UTC
Labels: kind/bug, area/admin/ui, status/triage

**Comment by zinginging** [comment] 2022-07-22 08:19
how to deal with this problem in old version browser. It's not easy for us to upgrade the browser version in our special environment.

**Comment by jonkoops** [comment] 2022-07-23 11:24
Sorry to hear that, but if you want to maintain support for older browsers the burden of support is on your organization, not ours. If you want to keep support I would recommend you fork Keycloak and maintain your own version that includes fixes for your support target.

**Comment by zinginging** [comment] 2022-07-25 03:13
> I solved this problem by updating file themes/base/admin/resources/js/controllers/users.js.Function _filterSearchedGroups_ in this js uses ES6 features **includes** but older browsers not supported. Change it to ES5 grammar and it works!

**Comment by jonkoops** [comment] 2022-07-25 09:29
Feel free to open up a PR if you like @zinginging, contributions are always welcome.
