### ISSUE TITLE
Username not shown in register page if user is not allowed to edit it

### ISSUE THREAD

**Issue by relatedbits** [keycloak/keycloak#26359] opened 2024-01-21 12:36 UTC
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

After `declarative-user-profile` feature is activated and disabling `User` from `Who can edit?` for `username` attribute, `username` and `password` fields are missing from the registration form.

### Version

image: quay.io/keycloak/keycloak:23.0.4

### Expected behavior

`username` and `password` fields shown in the registration form and users can be registered.

### Actual behavior

For Frontend:
`username` and `password` fields are missing.

For Backend:
User can still be registered if a POST request with required fields is sent.

### How to Reproduce?

1. Create Realm
2. Realm settings -> Login -> Enable `User registration`
3. Open registration form in browser Tab A
4. Realm settings -> General -> Enable `User Profile Enabled`
5. Realm settings -> User profile -> username -> uncheck `User` for `Who can edit?` and save
6. Open registration form in browser Tab B

The form is missing username and password fields.
<img width="551" alt="Screenshot 2024-01-21 at 20 03 47" src="https://github.com/keycloak/keycloak/assets/53244783/a8af5468-2d07-4d13-947f-42c8534674d3">

At this point, user can still be created by submitting a filled form in browser Tab A.

**Comment by ssilvert** [comment] 2024-01-21 19:52
@relatedbits I'm not sure I understand your use case.  Are you trying to make it so that the user can edit the user name during registration, but not after?

**Comment by relatedbits** [comment] 2024-01-22 01:47
@ssilvert  Yes, you are right.
More precisely, it should be allowing the user to "create" the user name during registration, but not "editing" after.
It seems strange that users cannot even create their accounts now if the `Who can edit?` setting set to `User`.

**Comment by ssilvert** [comment] 2024-01-22 13:08
@pedroigor It occurs to me that this use case could apply to any attribute.  What do you think about adding an "Always editable during registration." flag?

**Comment by pedroigor** [comment] 2024-02-07 21:46
That is kinda the confusion we have due to the overlap between `Edit username` and the User Profile configuration.

@ssilvert What you are proposing makes sense for me too but a more generic solution should be https://github.com/keycloak/keycloak/issues/25575.

Not sure if this is a bug but an improvement we want to make in future versions of the feature.

**Comment by ssilvert** [comment] 2024-02-12 20:58
@relatedbits I'm going to close this as a duplicate of the more generic enhancement described in https://github.com/keycloak/keycloak/issues/25575

If you haven't given that one an "upvote", I'd suggest you go there and do it.

**Closed by ssilvert** 2024-02-12 20:58 UTC
Labels: kind/bug, status/triage, team/ui, area/login/ui

**Comment by SimsonMoses** [comment] 2024-08-23 09:46
2024-08-23 06:20:37,319 WARN  [org.keycloak.events] (executor-thread-62) type="REGISTER_ERROR", realmId="df175d91-86b3-4c60-9ab9-5567d73a73e5", realmName="xyz", clientId="account-console", userId="null", ipAddress="172.18.0.1", error="invalid_registration", auth_method="openid-connect", auth_type="code", register_method="form", redirect_uri="http://localhost:8088/realms/xyz/account/", code_id="de74f87b-ee52-4820-a8d4-edf4b17ed067", email="simson.m+22@gmail.com"

As you take a look at the error user id is passed as null that's the issue

so you could possible workaround change label name of the userName to custom name and handle in the SPI
