### ISSUE TITLE
Event Representation is not shown for Admin Events in UI

### ISSUE THREAD

**Issue by ravthiru** [keycloak/keycloak#35483] opened 2024-12-01 23:23 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

With Keycloak 26.0.6 resource representation is not avilable to view through Admin UI even after eanbling the  "Include representation" for the admin events
With Previous releases of Keycloak Resource  Representation was available to view when Representation is Enabled.

### Version

26.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

When "Include representation" for the Event is enabled Resource Representation can be viewed in the UI as JSON format 

### Actual behavior

Currently there no option for the event to select and show Representation.

![image](https://github.com/user-attachments/assets/bd796147-f9ff-4d42-9e73-1a70cefe4ccf)

![Screenshot 2024-12-02 at 10 03 21 am](https://github.com/user-attachments/assets/12479eaf-526c-4f18-9d91-2d01a8e29ebd)

### How to Reproduce?

Install KC 26.0.6 .
Enable admin events with Include representation
Generate some admin events (REALM UPDATE and CLIENT CREATE) 
Try to access the admin event view, the UI only shows events and there is no way to admin events

**Comment by ssilvert** [comment] 2024-12-02 14:13
I took a quick look.  This used to work so I've marked as a regression.  

@agagancarczyk I don't think it should be a release blocker, but since it's a regression we do need to fix asap.

**Closed** 2024-12-04 08:09 UTC
Labels: kind/bug, priority/important, area/admin/ui, team/ui, kind/regression, backport/26.0
