### ISSUE TITLE
js/apps/keycloak-server does not start anymore

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#33536] opened 2024-10-03 19:33 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When starting the `js/apps/keycloak-server` an error occurs:

```
> node ./scripts/start-server.js "--admin-dev"

Downloading and extracting server…
Starting server…
login:v2 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn].
account:v3 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn]
```

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Server to start.

### Actual behavior

```
> node ./scripts/start-server.js "--admin-dev"

Downloading and extracting server…
Starting server…
login:v2 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn].
account:v3 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn]
```

### How to Reproduce?

Start dev keycloak server

**Comment by jonkoops** [comment] 2024-10-03 19:35
This is a regression caused by #33458

**Comment by antikalk** [comment] 2024-10-03 19:36
I will issue an PR soon :)

**Comment by jonkoops** [comment] 2024-10-03 22:13
Closing for reasons mentioned under https://github.com/keycloak/keycloak/pull/33537#issuecomment-2392429879, will re-open if still an issue.

**Closed by jonkoops** 2024-10-03 22:13 UTC
Labels: kind/bug, area/admin/ui, help wanted, team/ui, status/auto-expire, status/auto-bump, priority/normal
