### ISSUE TITLE
Web Application hit too many redirects issue after upgrade from keycloak-23.0.7 to keycloak-25.0.5

### ISSUE THREAD

**Issue by weim3ng** [keycloak/keycloak#34727] opened 2024-11-07 03:32 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

1. Upgrade from keycloak 23.0.7 to 25.0.5

2. Environment - azure aks with Kubernetes version v 1.28.5

3. Run - Login with Angular Web Application which is using keycloak-angular package with keycloak.js v 25.0.6

4. Web Application hit too many redirect issue
![377838864-e671e387-dc8d-44f7-898c-fac7ff0b65f2](https://github.com/user-attachments/assets/980e960f-57d8-4aab-b62a-3f70ca1ebff6)
5. Found that is related to duplicate Cookies AUTH_SESSION_ID
![377839569-08873d33-c4d9-423f-b675-d1282663e9a6](https://github.com/user-attachments/assets/a3345f22-2b96-4620-9b6c-09078c5375a9)
6. how do I get rid of the duplicate cookies in client browser without the need of users to manually clear their browser cookies?

### Version

25.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

Able to login successfully as in keycloak 23.0.7 version

### Actual behavior

Angular Web Application hit too many redirect issue.
![377838864-e671e387-dc8d-44f7-898c-fac7ff0b65f2](https://github.com/user-attachments/assets/cdb3fff0-15cb-4c5e-b1ff-24dadc368382)

### How to Reproduce?

1. Upgrade from keycloak 23.0.7 to 25.0.5

2. Environment - azure aks with Kubernetes version v 1.28.5

3. Run - Login with Angular Web Application which is using keycloak-angular package with keycloak.js v 25.0.6

4. Web Application hit too many redirect issue
![377838864-e671e387-dc8d-44f7-898c-fac7ff0b65f2](https://github.com/user-attachments/assets/980e960f-57d8-4aab-b62a-3f70ca1ebff6)
5. Found that is related to duplicate Cookies AUTH_SESSION_ID
![377839569-08873d33-c4d9-423f-b675-d1282663e9a6](https://github.com/user-attachments/assets/a3345f22-2b96-4620-9b6c-09078c5375a9)
6. how do I get rid of the duplicate cookies in client browser without the need of users to manually clear their browser cookies?

### Anything else?

yaml file
``` yaml
image:
  debug: true

auth:
  adminUser: ${KEYCLOAK_ADMIN_USER}
  adminPassword: ${KEYCLOAK_ADMIN_PASSWORD}

postgresql:
  enabled: false

externalDatabase:
  host: ${DB_HOST}
  port: 1433
  database: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

cache:
  enabled: true

production: true

proxy: edge

extraStartupArgs: "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true --spi-sticky-session-encoder-infinispan-should-attach-route=true"

extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
    value: "true"
  - name: QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY
    value: "/opt/bitnami/keycloak/objectstore"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_DB
    value: "mssql"
  - name: KC_DB_URL
    value: "jdbc:sqlserver://${DB_HOST}:1433;databaseName=${DB_NAME};encrypt=true;trustServerCertificate=false;loginTimeout=30;sendStringParametersAsUnicode=false;"
  - name: KC_TRANSACTION_XA_ENABLED
    value: "false"

replicaCount: 2

resources:
  requests:
    cpu: 384m
    memory: 1536Mi
  limits:
    cpu: 500m
    memory: 2048Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 1
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 60
  successThreshold: 1

nodeSelector:
  application: "yes"

extraVolumeMounts:
  - mountPath: /opt/bitnami/keycloak/themes/dms
    name: theme
  - mountPath: /opt/bitnami/keycloak/objectstore
    name: objectstore

extraVolumes:
  - name: theme
  - name: objectstore

service:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.xxx.xxxxxxxx.com, http://localhost:4200" 
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    # this section was used in keycloak 23.0.7 but have to remove in 25.0.5
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "AUTH_SESSION_ID" 
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
    # nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
    # nginx.ingress.kubernetes.io/affinity-mode: "balanced"
  hostname: ${KEYCLOAK_INGRESS_HOST}
  ingressClassName: nginx-internal
  tls: true

pdb:
  create: true
  minAvailable: 1

logging:
  output: default
  level: INFO
```

**Comment by weim3ng** [comment] 2024-11-15 09:16
I have upgraded keycloak to latest version 26.0.5 as below
![image](https://github.com/user-attachments/assets/6b8e36d3-c640-4402-afe1-8b8e2e6027b8)

but I will still hit too many redirects issue when there is duplicate AUTH_SESSION_ID cookies with different path on the browser
![image](https://github.com/user-attachments/assets/c43def35-ae79-4d63-a321-43e146c99e6e)

browser network:
![image](https://github.com/user-attachments/assets/35093fd6-07db-4cd3-9a81-4ea1dace9733)

keycloak log:
![image](https://github.com/user-attachments/assets/19227969-3f49-4de2-a758-c509bc1b723b)

Is there any way to remove client browser cookies while we perform upgrade without the need of users to manually clear their browser cookies?

**Comment by rmartinc** [comment] 2024-11-19 15:57
AFAICT keycloak server never assigns a cookie to path `/`. So there is something weird in you installation. Something different seems to be adding another AUTH_SESSION_ID to `/`. Are you using a proxy or similar in front of keycloak? Can you check that configuration?

But we cannot reproduce this easily, so if you can give us some reproducer steps in a clean installation/upgrade is better. We also recommend you to upgrade to last 26.0.5 version.

**Comment by tiesto-nk** [comment] 2024-11-21 13:13
If you rename AUTH_SESSION_ID in nginx.ingress.kubernetes.io/session-cookie-name: "AUTH_SESSION_ID" to example - AUTH_SESSION_ID_NEW, keycloak start to work!

**Comment by weim3ng** [comment] 2024-11-22 05:41
> AFAICT keycloak server never assigns a cookie to path `/`. So there is something weird in you installation. Something different seems to be adding another AUTH_SESSION_ID to `/`. Are you using a proxy or similar in front of keycloak? Can you check that configuration?
> 
> But we cannot reproduce this easily, so if you can give us some reproducer steps in a clean installation/upgrade is better. We also recommend you to upgrade to last 26.0.5 version.

in previous version we used nginx ingress to add AUTH_SESSION_ID to enable sticky session. After upgrade to latest 26.0.5 version, it hit too many redirects issue, then we just found out the AUTH_SESSION_ID we added is causing the issue.

removing the AUTH_SESSION_ID from nginx ingress did solve the issue, but we are trying to upgrade keycloak in production, if the cookies is still valid in users' browser after we upgrade, users will hit the same too many redirects issue.

So we are trying to prevent users have to manual clear their cookies after we upgrade keycloak. is there any way to clear users' browser cookies after we upgrade keycloak?

**Comment by weim3ng** [comment] 2024-11-22 05:44
> If you rename AUTH_SESSION_ID in nginx.ingress.kubernetes.io/session-cookie-name: "AUTH_SESSION_ID" to example - AUTH_SESSION_ID_NEW, keycloak start to work!

yes is will work. But removing it seems the sticky session also working, so we removed it.
as my previous comment, we are trying to prevent users hit too many redirects issue when we upgrade in production.

Do you have any idea, how I can prevent it? Thanks

**Comment by rmartinc** [comment] 2024-11-22 07:44
@weim3ng The question here is different and probably not for the keycloak team. Why is nginx adding an AUTH_SESSION_ID to path `/` when keycloak assigns it to `/realms/<name>/`?

This is the cookie that keycloak returns when running in production mode:

```
AUTH_SESSION_ID=XXXXX.YYYY;Version=1;Path=/realms/master/;Secure;HttpOnly;SameSite=None
```

Note it adds by default the route for sticky as commented in the [proxy guide](https://www.keycloak.org/server/reverseproxy#_enable_sticky_sessions).

**Comment by rmartinc** [comment] 2024-11-26 15:41
@weim3ng We think this issue is related to configuration of nginx so we are closing it. If you see a clear bug in keycloak please re-open it or file a new one with your new findings.

**Closed by rmartinc** 2024-11-26 15:41 UTC
Labels: area/authentication, kind/bug, status/triage, team/core-clients

**Comment by kresnasatya** [comment] 2025-03-08 00:01
Hi! From future here! I'm also facing the same trouble couple days ago until yesterday! As information, I deploy Keycloak 25.0.6 on GKE with 3 replicas. So, this may lead too many redirect or redirect loop issue on browser. Since Keycloak v24, Keycloak team has rewritten their cookies, so we don't need to set affinity cookie on ingress nginx.

Back to my problem, I get the redirect loop and I even try a silly way by set affinity cookie on ingress nginx too even since Keycloak v24 the cookies mechanism has changed. The result: I get no luck and then I remove the affinity cookie because this is not the culprit. Then, today, I wake up, I try this way:

1. Rolldown replicas to 0. This makes sure to cleanup cache stack because I'm using embedded cache with Kubernetes cache stack. Then, I see the web is out of service which is good sign.
2. Next, rollup replicas into 1. This for wake up the deployment. I try to open the Keycloak admin console, login, and it works! Ok, now with replicas 1 still good!
3. Next, rollup replicas into 3. I try again then then, I get a sign that this lead too many redirect or I get 401 http code in my browser. Ok! So, if I increase the replicas, I get this error.

Then, I scroll down my deployment yaml code, then I see the JGroups DNS discovery (Kubernetes DNS) value is incorrect.

I was set to `keycloak-discovery.keycloak.svc.cluster.local`. But, I realized that the correct namespace is `dev-keycloak` NOT `keycloak` because I use this for development. Then, I change the DNS value from:

| Before                                          | After                                               |
|:------------------------------------------------|:----------------------------------------------------|
| `keycloak-discovery.keycloak.svc.cluster.local` | `keycloak-discovery.dev-keycloak.svc.cluster.local` |

Then, it works! 🥳🎉

I left a post about the implement distributed cache on Keycloak: https://dev.kresna.me/posts/implement-distributed-cache-on-keycloak

Hope, it helps!
