### ISSUE TITLE
TCPPING: Unable to use proxy between KC instances

### ISSUE THREAD

**Issue by gertjankoorn** [keycloak/keycloak#25822] opened 2023-12-29 13:58 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

When trying to configure shared caching with TCPPING in Nomad, i am unable to connect them to each other. 
A little context: The goal is to run multiple instances of Keycloak on our Nomad cluster. However, running them normally in a single task (like adeployment in Kubernetes), they are not able to communicate to each other. This is intended behaviour by Nomad, because an instance of a service should only be reached by the service in front of it. With Kubernetes, it's a possibility to use a headless service. This is not an option in Nomad unfortunately.
A workaround i'm trying now is to manually create a task for each Keycloak instance. Each instance has the other instances' Consul Connect upstreams in their TCPPING configuration, which goes through the sidecar. An overview of they connect:
![kc](https://github.com/keycloak/keycloak/assets/29374639/075a2912-2c26-48ef-bc5c-779400d4052c)
The problem here, is that the infinispan traffic goes through the consul connect proxies, which does not seem to work. The port is open and when i do a telnet to the upstream address and port, i do indeed see an error in the logs of keycloak that it doesn't know what to do with that traffic. That seems to me the connection `KC1 -> connect proxy KC1 -> connect proxy KC2 -> KC2` is open. I have the feeling it has something to do specifically with the infinispan cache traffic, but cannot find what's different. 

To test this further, i thought to try this in Docker compose with a Nginx proxy between the instances using the `stream` directive. The config looks like this:
```
stream {
    upstream keycloak1 {
        server <ip01>:<port01>;
    }
    upstream keycloak2 {
        server <ip02>:<port02>;
    }
    server {
        listen <proxy_port01>;
        proxy_pass keycloak1;
    }
    server {
        listen <proxy_port02>;
        proxy_pass keycloak2;
    }
}
```

The ispn configuration is use is: 
```
    <jgroups>
        <stack name="tcpping" extends="tcp">
          <TCP external_addr="${KC_BIND_ADDR}" bind_addr="${KC_BIND_ADDR}" bind_port="${TCP_BIND_PORT}" />
          <TCPPING initial_hosts="${INITIAL_HOSTS}"
                   max_dynamic_hosts="0"
                   port_range="0"
                   stack.combine="REPLACE"
                   stack.position="MPING"/>
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="tcpping"/>
```
With `INITIAL_HOSTS` being the ip:port of the proxy. 
I get the same experience as in Nomad, where i can telnet with the resulting error in the logs, but the KC's don't seem to find the other instance to build a cache pool. To imitate the behaviour of Nomad, i've put both KC instances in a different Docker network, so they cannot use UDP multicast (which is done by default). When i point them to each other directly with `INITIAL_HOSTS`, they do share cache (to confirm the TCPPING config works correctly). 

Does anyone have an idea what might be the issue here? Or a suggestion what to try?

### Version

23.0.0

### Expected behavior

For keycloak to use a proxy in between the instances, instead of directly communicating to each other.

### Actual behavior

They don't communicate via a proxy. 

### How to Reproduce?

Using 2 KC instances, configuring TCPPING where `INITIAL_HOSTS` points to the proxy.

**Comment by akbar1214** [comment] 2024-01-01 12:14
Can you try jdbc_ping and provide the results?

**Comment by sschu** [comment] 2024-01-01 12:26
This is most likely not a bug in Keycloak but a problem in your specific network setup. If you like other people to help you with your specific setup, you can ask a question in the Q&A section (https://github.com/keycloak/keycloak/discussions/categories/q-a) or on the user mailing list (https://groups.google.com/g/keycloak-user). I will go ahead and close this issue as not a bug.

**Closed by sschu** 2024-01-01 12:26 UTC
Labels: kind/bug, area/infinispan, team/store, status/triage
