### ISSUE TITLE
Organization Membership mapper:  "Add organization attributes" and "Add organization id" changes to Off when "Multivalued" is unchecked 

### ISSUE THREAD

**Issue by mikolajMacioszczyk** [keycloak/keycloak#34131] opened 2024-10-21 08:26 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

When in the mapper "Organization Membership" for sclient scope organization I change the value of "Multivaled" from On to Off, and I also have "Add organization attributes" and "Add organization id" checked on On, after saving and refreshing the page, they also change to Off.

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

"Add organization attributes" and "Add organization id" should remain On

### Actual behavior

"Add organization attributes" and "Add organization id" changes to Off

### How to Reproduce?

1. Create client scope "organization"
2. Create Organization Membership mapper by configuration:
![image](https://github.com/user-attachments/assets/15ea70e8-1db0-4fcc-9190-bc471c66f594)
3. Save changes
4. Change "Multivalued" to Off
5. Save changes
6. Refresh the page: "Add organization attributes" and "Add organization id" also changes to Off

**Comment by martin-kanis** [comment] 2024-10-21 09:39
Thanks for the issue. The cause of the problem is in `org.keycloak.organization.protocol.mappers.oidc.OrganizationMembershipMapper#setDefaultValues` which forces defaults values if they are defined in the config. I'll provide a fix.

**Comment by pedroigor** [comment] 2024-10-21 10:57
Not sure if the UX is the best but the idea is that if you choose a single-value mapping you won't have attributes or IDs set. That is why the other two fields are `OFF` when `Multivalued` is set to OFF.

**Comment by martin-kanis** [comment] 2024-10-21 18:36
OK after discussion with @pedroigor we are closing this on in favour of https://github.com/keycloak/keycloak/issues/34164

**Closed by martin-kanis** 2024-10-21 18:36 UTC
Labels: kind/bug, priority/important, team/core-iam, area/organizations

**Comment by mikolajMacioszczyk** [comment] 2024-10-22 05:12
@pedroigor
If attributes and IDs are not taken into account when single-value mapping is selected, perhaps these two switches should be disabled in this case? Currently, UX is a bit confusing, as values change without the user's knowledge.
What do you think about it?
