### ISSUE TITLE
org.keycloak.userprofile.UserProfileProvider is bounced on every realm change

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#20970] opened 2023-06-13 13:48 UTC
Originally reported in [KEYCLOAK-19044](https://issues.redhat.com/browse/KEYCLOAK-19044):

Whenever the realm is changed:

- the org.keycloak.userprofile.UserProfileProvider is added to the export/components if it was previously missing
- the org.keycloak.userprofile.UserProfileProvider is removed from the export/components if it was previously present
So the org.keycloak.userprofile.UserProfileProvider's presence is constantly bounced when the realm is changed.

Steps to reproduce:

- Start the docker image with: docker run -p 8080:8080 -e KEYCLOAK_USER=keycloak -e KEYCLOAK_PASSWORD=keycloak -e JAVA_OPTS="-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled" quay.io/keycloak/keycloak:15.0.1
- In the browser go to the localhost:8080
- Log in with keycloak/keycloak
- Create a new realm - ex 'jose'
- export the realm - the org.keycloak.userprofile.UserProfileProvider is not present
- Change the realm (ex set description to 'a')
- export the realm - the org.keycloak.userprofile.UserProfileProvider is present
- Change the ream (ex set description to 'b')
- export the realm - the org.keycloak.userprofile.UserProfileProvider is not present
- Change the realm (ex set the descriptio to 'c')
- export the realm - the org.keycloak.userprofile.UserProfileProvider is present
- ...

I was able to reproduce the issue with current main.

**Comment by okozachenko1203** [comment] 2023-08-04 06:11
This is reproducible by ansible and affects to ansible idempotence also.

We create a realm and clients in that realm using ansible modules `community.general.keycloak_realm` and `community.general.keycloak_client` etc.
I exported realm after the first playbook run(realm created and clients created inside it) and compared the exported one after 2nd playbook run. The 2nd export includes the following section additionally comparing with the first export.
```json
    "org.keycloak.userprofile.UserProfileProvider": [
      {
        "id": "09c0575d-d0dc-440b-a6c9-5422a1dbd209",
        "providerId": "declarative-user-profile",
        "subComponents": {},
        "config": {}
      }
    ],
```
It is because the realm has been changed by the client creation task in the first playbook run. And it causes ansible idempotence failure.
As you can guess, the 3rd playbook run is ok because there is no realm change.

**Comment by vramik** [comment] 2023-08-30 07:30
Upon every change in realm there is a call to set `null` to `UserProfileProvider`'s configuration:
https://github.com/keycloak/keycloak/blob/94f41444f47cfc2404ed9e37046eb53eb7903dd5/model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java#L702

This call creates new component if there is none already:
https://github.com/keycloak/keycloak/blob/2a6b4d12109c6795db3fb932c85795c2d51f2b91/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java#L212
https://github.com/keycloak/keycloak/blob/2a6b4d12109c6795db3fb932c85795c2d51f2b91/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java#L452 

and then in the same transaction the component is removed:
https://github.com/keycloak/keycloak/blob/2a6b4d12109c6795db3fb932c85795c2d51f2b91/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java#L233

There is open issue for the same problem for map store: https://github.com/keycloak/keycloak/issues/11666. Corresponding hibernate issue also exist: https://hibernate.atlassian.net/browse/HHH-15230.

Workaround for this would be to register overridden `DefaultAutoFlushEventListener` similarly as for the map store: https://github.com/keycloak/keycloak/blob/8b232ff04de1afd72966e6dc2c9a80990fa5cf47/model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/listeners/JpaAutoFlushListener.java#L92-L94

I want to investigate first whether we can avoid creating and deleting the component altogether.

**Comment by ahus1** [comment] 2023-10-10 11:29
@vramik - with this now being merged to main, please agree with @pedroigor when and if this should be backported with other user profile changes for KC22. Thanks!

**Closed** 2023-10-10 11:28 UTC
Labels: impact/low, area/storage, area/import-export, team/store
