### ISSUE TITLE
The performance issue when keycloak admin logs into the web console

### ISSUE THREAD

**Issue by hqch0708** [keycloak/keycloak#17455] opened 2023-03-06 06:44 UTC
### Description
If we have more than 1000 realms in keycloak, when the keycloak admin logs into the web console, the whoami api is very slow, even may get a 5XX response.

I have created a PR for this enhancement, please take a look at https://github.com/keycloak/keycloak/pull/17402

**Comment by scoopex** [comment] 2023-05-30 20:01
I wrote a hacky script for reproduction and reproduced that with the latest release.
See: https://github.com/scoopex/keycloak-mass-realm

**Comment by jonkoops** [comment] 2023-05-31 08:57
Duplicate of #20453

**Closed by jonkoops** 2023-05-31 08:57 UTC
Labels: kind/enhancement, area/admin/api, status/triage, team/core
