### ISSUE TITLE
Admin Page Spining

### ISSUE THREAD

**Issue by Ashittu21** [keycloak/keycloak#27400] opened 2024-02-29 22:25 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Admin Page Spinning After SSL Configuration to the site.

### Version

Latest Version

### Regression

- [X] The issue is a regression

### Expected behavior

I should be able to access Admin UI, To Adminster User Access

### Actual behavior

Admin Page Spinning since Yesterday Non Stop.

### How to Reproduce?

Any Configuration on the Server should not Affect the Admin Page.

**Comment by jonkoops** [comment] 2024-02-29 23:48
Duplicate of #14666

**Closed by jonkoops** 2024-02-29 23:48 UTC
Labels: kind/bug, area/admin/ui, status/triage, team/ui

**Comment by jonkoops** [comment] 2024-02-29 23:50
@Ashittu21 this still has no steps on how to reproduce this issue, please follow the discussion in the issue this is marked a duplicate of.

**Comment by Ashittu21** [comment] 2024-03-01 13:58
@jonkoops Can you advise on what i can try on the server to stop the spinning of the Admin Page.
