### ISSUE TITLE
Dangling authenticator config and authenticator config entry in database

### ISSUE THREAD

**Issue by docid00** [keycloak/keycloak#28428] opened 2024-04-04 08:45 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When deleting a flow, it cascades and delete it's child executions, but if there is configuration for authenticators, they are left 'dangling' in the database.

This also happens when you delete an execution w/o deleting its containing flow.

This causes the db to contain a lot of dangling data and makes it impossible to work with static aliases for authenticator configs, especially but not exclusively when using configuration as code to apply realm and flow config.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Authenticator configs are being deleted when executions/flows get deleted.

### Actual behavior

Configs remain in the database forever.

### How to Reproduce?

- log into admin ui
- create a new flow 
- add an execution, e.g. "Conditiaonal OTP Form config"
- configure the step and give it an alias you can easily recognize
- delete the flow
- check db table `authenticator_config` for your config by the alias you set above
- check table `authenticator_config_entry` for rows where `authenticator_id` is `id` of the row from `authenticator_config`

### Anything else?

Also see https://github.com/keycloak/keycloak/discussions/17040

**Comment by docid00** [comment] 2024-04-09 07:17
The issue is not reproducible in nightly anymore. As far as i can see this is fully resolved.

**Comment by rmartinc** [comment] 2024-04-09 07:28
Thanks @docid00! then this is a duplicate of #24795. I'm closing this one. I will ask @mposolda if we need #24795 backported to 24.x.

**Closed by rmartinc** 2024-04-09 07:28 UTC
Labels: area/authentication, kind/bug, priority/important, team/core-clients
