### ISSUE TITLE
Keycloak logs account-console passwords in plain text when started in debug mode

### ISSUE THREAD

**Issue by thoren-w** [keycloak/keycloak#30296] opened 2024-06-10 10:32 UTC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Keycloak logs account-console passwords in plain text when started in debug mode.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The password should at least be replaced, e.g. by asterisks or the password line should be suppressed completely.

### Actual behavior

`2024-06-10 11:44:00,639 DEBUG [org.apache.http.wire] (executor-thread-2) http-outgoing-0 >> "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><password><value>PLAINTEXTPASSWORD</value></password>"`

### How to Reproduce?

Set the log level to Debug (--log-level=DEBUG) and then login to the account-console via browser.

**Comment by sschu** [comment] 2024-06-11 05:52
I think this is essentially a duplicate of https://github.com/keycloak/keycloak/issues/23548. Since this is a lower-level framework that is just emitting plain wire transfer, it will contain all data and there is not much Keycloak can do about it. You essentially should not enable debug logging for `org.apache.http.wire` in production.

**Closed by sschu** 2024-06-11 05:52 UTC
Labels: kind/bug, area/core, status/triage, team/core-shared
